### ISSUE TITLE
BlockPos should implement == operator

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#1]
I just ran into this again, trying to compare two `BlockPos` instances. They do implement `IEquatable`, so `Equals` works, but `==` doesn't.

```csharp
var pos1 = new BlockPos(0, 0, 0);
var pos2 = new BlockPos(0, 0, 0);
Console.WriteLine(pos1 == pos2);
```

**Expected output:** `true`
**Actual output:** `false`

### Workaround

Can use `Equals`, as I said, though it's not null-safe so an additional check might be required.

```csharp
Console.WriteLine(pos1.Equals(pos2));
```

**Comment by copygirl** [comment]
In addition, it seems like `BlockPos` has a **non-static** `Equals` method that takes **two** values.

**Comment by tyronx** [comment]
Added `
        public bool Equals(BlockPos a, BlockPos b)
        {
            return (a == null && b == null) ||
                   (a != null && b != null && a.X == b.X && a.Y == b.Y && a.Z == b.Z)
            ; 
        }`

The 2 arg equals is required to implement IEqualityComparer. Please reopen if there's is something wrong with this.

**Comment by copygirl** [comment]
`BlockPos` shouldn't implement `IEqualityComparer`, it already implements `IEquatable`, right? The former is for types you can't modify which don't extend the latter. It is used to specify a custom equality comparer for collections if you want custom behavior instead of the default one (`IEquatable` or `Object.Equals`). You'd have to use it like this: `new Dictionary<BlockPos, string>(comparer: new BlockPos());` and you can probably see why that's silly. If you wanted to implement it, you'd use it on a different type, not the one you're trying to compare.

**Comment by tyronx** [comment]
Oki, removed it
