### ISSUE TITLE
Crash on game closing

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#100]
Using 1.5.3 rc4 no mods
[VintagestoryCrash.txt](https://github.com/anegostudios/VintageStory-Issues/files/1973095/VintagestoryCrash.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/1973096/client-crash.txt)
Only happens if a world loads. Going into the client and back out without opening a world does not crash.

**Comment by tyronx** [comment]
Should be fixed for 1.5.3
