### ISSUE TITLE
Character sneaks while standing close to the gate

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1001]
**Game Version:** 1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Place a gate
2. Come close to the gate
3. Character is sneaking

### Videos

https://user-images.githubusercontent.com/69315569/121821718-628bd980-cca3-11eb-8eea-7fec2d743c53.mp4

**Comment by Saricane** [comment]
Similar problem with doors, depending on the position of the player. If you stand at the exact place shown on the screenshot (and on this side of the door, so, on the same block as the door) and you open the door, you will sneak.

![door](https://user-images.githubusercontent.com/84909583/122038933-6d935680-cdd6-11eb-8c80-eaf5b30cc2b7.jpg)

**Comment by Craluminum2413** [comment]
Yes, but you can also use the door as a complex stairs

https://user-images.githubusercontent.com/69315569/122040327-55283980-cde0-11eb-8b40-54e4f0164590.mp4

**Comment by Saricane** [comment]
Wonderful. But ... how could you have the idea to stack doors and try to climb on them ?

**Comment by Craluminum2413** [comment]
Because I've always done this in minecraft. In VS, this works the same way

**Comment by copygirl** [comment]
Are you sure the door issue is not from you being "stuck" in the door, and thus the game forcing you into a sneaking position, in an attempt to unstuck you. I think this is different from the fence gate (which I've also noticed before) which simply forces you to sneak by walking up to it. Even though there is nothing in the blockspace above that should make you sneak.

**Comment by Saricane** [comment]
To be honnest, I'm sure about nothing :-) I just report what I consider as a bug. As you said, there is nothing above my head that should force me to sneak. Moreover, once opened, I must cross the whole door sneaking. I have never noticed such a behaviour in 1.14.

**Comment by Craluminum2413** [comment]
[1.15.4-rc.1](https://www.vintagestory.at/blog.html/news/the-homesteading-update-balance-stable-patch-v1154-rc1-r291/)
> Fixed: Players go sneak mode in front of fence gates
