### ISSUE TITLE
Some recipes cause long lag spikes

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1008]
**Game Version:** 1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### Description
Viewing recipes of `clutch` (very huge lag spike), `angled gears`, `transmission`, `fruitpress`, `large gear section` cause lag spikes

### How to reproduce
1. See the recipes for items listed in the description
2. They cause lag spikes

### Videos

https://user-images.githubusercontent.com/69315569/121931026-bce07500-cd4b-11eb-93cb-aa5003e6c4d5.mp4

**Comment by Craluminum2413** [comment]
It applies to performance label by the way

**Comment by tyronx** [comment]
thanks for the report, this issue should be greatly mitigated for pre.7
