### ISSUE TITLE
Player ghosting from lack of timeout

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#101]
I found it's possible for a player to crash in a way they don't disconnect, but they don't time out after time and their player entity doesn't disappear. When they log back in, I'd still see them in the place they were before, changing the item they were holding but not moving around. I think this might be related to other players seeing these "ghosts" when the real players were somewhere else.

**Comment by tyronx** [comment]
Might be related to the general issue where you see multiple instances of a player in the game after some time

**Comment by Craluminum2413** [comment]
Clones
