### ISSUE TITLE
Beemob entity seek and melee AI tasks cause InvalidCastExceptions when targetting entities NOT derived from EntityAgent.

### ISSUE THREAD

**Issue by TaskaRaine** [anegostudios/VintageStory-Issues#1010]
**Game Version:** 1.15.0 Pre-2
**Platform:** Windows
**Modded:** Yes

### Description
Beemobs utilize a wildcard for their seek and melee AI tasks. All creature entities can be attacked. However, both these AI tasks assume that the target entity will always derive from EntityAgent, which is not necessarily the case for simple modded entity creatures(a floating orb, for example). InvalidCastExceptions are thrown and can cause the server to die and may not be recoverable even on world restart, especially if bees are within melee range of the entity.

### How to reproduce
1. Make a very simple mod creature that doesn't do anything, but derives from Entity.
2. Spawn many of the creature using an item or command.
3. Surround the entity with bee hives.
4. Break all the bee hives and anger them.
5. The server will quickly become unresponsive as exceptions are thrown.
6. Log out.
7. Log back in, and the server will remain unresponsive.

### Expected behavior
Bees shouldn't be the end of the world! And neither should be a very basic entity that doesn't do anything. In my case, I have a very simple entity that floats in place with an animation. It doesn't need any functionality from EntityAgent, therefore, it's not used. It's quite possible other modders might think the same way and that could be problematic.

If there are other ways to handle this on my end please let me know~

### Screenshots
I made this video to demonstrate

https://www.youtube.com/watch?v=mGuF6QGsZrU

### Logs
```
14.6.2021 16:30:42 [Fatal] System.InvalidCastException: Unable to cast object of type 'OreCrystals.EntityCrystalHeart' to type 'Vintagestory.API.Common.EntityAgent'.
   at Vintagestory.GameContent.AiTaskMeleeAttack.ContinueExecute(Single dt)
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by Craluminum2413** [comment]
Does this happen in 1.15.0-pre. 3?

**Comment by TaskaRaine** [comment]
> 
> 
> Does this happen in 1.15.0-pre.3? Oh, I see it doesn't depend on the version of the game

Yes

**Comment by tyronx** [comment]
Thanks for the report, i believe this should now be fixed for pre.7
