### ISSUE TITLE
How to copy an entity?

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1011]
How do I copy an entity I'm looking at in creative gamemode? In minecraft, this can be done by simply pressing the MMB (middle mouse buttom), but how to do it here?

**Comment by sirStroam** [comment]
This has been marked as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
