### ISSUE TITLE
Strange double door behavior

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1013]
**Game Version:** 1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### Description
The work of the double doors is very strange. It's easier to show on video

### Videos

https://user-images.githubusercontent.com/69315569/122042910-6c1c5b00-cde3-11eb-9300-340a72b580a1.mp4

https://user-images.githubusercontent.com/69315569/122043359-ee0c8400-cde3-11eb-9d7d-b78c60dbcb15.mp4

https://user-images.githubusercontent.com/69315569/122043449-0381ae00-cde4-11eb-9e09-d918e3955af5.mp4

**Comment by copygirl** [comment]
I suppose the code for opening a door simply looks for another door to the opposite side and opens it. Since these are configurations people would be very unlikely to place doors, I'm considering closing this as intentional.

**Comment by Craluminum2413** [comment]
What if I say that it can cause crash?

**Comment by tyronx** [comment]
Yea, i also see nothing wrong with this behavior.
