### ISSUE TITLE
Partially eaten pie : missing information

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1015]
When character eats a meal in a bowl and cannot finish it, the remaining rate of this bowl in given in the information box (ie "0,2", or "3%" ...), so you can know when to go back to the cellar. There is no such information on a pie part partially eaten.

**Comment by Craluminum2413** [comment]
I'm wondering why you can't cook 4 pieces at once, that is, you can cook a whole pie, but not 4 pieces (only 1 at a time)

**Comment by Craluminum2413** [comment]
I meant 1/4 of the pie, that is, 4 pie pieces. You can't bake these small pie pieces together, if you cut raw pie

**Comment by Saricane** [comment]
Ah ok, the fact is I never tried tu cut a raw pie, that's why I didn't understand.

**Comment by tyronx** [comment]
this should be fixed in pre.5
