### ISSUE TITLE
/worldconfig commands should tell user to restart server

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1016]
Players are constantly asking in #gameplay-help in Discord why /worldconfig commands are not working.

Unfortunately the information about the necessity to restart the server is easily missed.

Player Zarkonnen - David Stark#2792  suggested that these commands should notify player in chat that they need to restart the server.

Imho this is a simple and highly important solution.

**Comment by tyronx** [comment]
ok, notice added, will be in pre.7 👍
