### ISSUE TITLE
Redwoodtree : cannot be cut

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1019]
**Game Version:** 1.15.0-pre3
**Platform:** Windows
**Modded:** No

### Description
Redwood tree cannot be chopped as a whole tree. Character have to cut each quarter log of the trunk one after one. Only the main branches, which are made from log (and not quarter log) can be chopped down as usual.

### How to reproduce
1. Take a axe and hit any redwoodtree 

### Expected behavior
Same as other trees : tree being cut.

### Screenshots

https://user-images.githubusercontent.com/84909583/122600519-3213b900-d070-11eb-8577-0603bf9c76c8.mp4

**Comment by Craluminum2413** [comment]
In this case, it's just `redwood tree trunk`

**Comment by Craluminum2413** [comment]
Can confirm ![2021-06-18_21-12-58](https://user-images.githubusercontent.com/69315569/122601452-fa117380-d079-11eb-87e0-2d2951abad66.png)

**Comment by tyronx** [comment]
Thanks for the report. This is now fixed for pre.6. 

In fact the axe chopping behavior is now no longer hardcoded but elegantly done via the block attributes `treeFellingGroupCode` and `treeFellingGroupSpreadIndex`
