### ISSUE TITLE
Chests not opening properly

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#102]
1.5.3, official server.
After closing a chest (floatyGuis on) I can't open it with the first right-click, only a sound is played. The chest is opened with the second click only.

**Comment by zkol** [comment]
Seems that this will happen when you previously closed the chest by escape. In this case the next try to open plays the "close" sound and does not open the GUI. When you closed it previously by right-click, it opens as expected with the "open" sound.

**Comment by tyronx** [comment]
Aw. Thats due to pre 1.5.3 chests. If broken and placed again, the bug should be gone. hm. Whats the best way to fix this.

**Comment by copygirl** [comment]
A small hook in chest blockentity loading / initialization code that fixes whatever is necessary?

**Comment by tyronx** [comment]
Ok, found a solution, thank you, fixed for 1.5.4. Thanks for the suggestion though.
