### ISSUE TITLE
trader : cannot sell books

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1020]
**Game Version:** 1.15.0-pre3
**Platform:** Windows
**Modded:** No

### Description
Luxury trader refuses to buy books, with no apprently reason.

### How to reproduce
No known algorithm to reproduce it. What I did is 

- I visited him a first time, sell him the gold coronet on my head, bought a carpet.
- I went back to my base to fetch 3 books and returned to this trader.
- No way to put a single book in a selling slot.

### Screenshots
![trader](https://user-images.githubusercontent.com/84909583/122610124-69d62d00-d07f-11eb-937e-caedc41d377d.png)

**Comment by Craluminum2413** [comment]
Seems like he is buying only lore book in diaries category. Also seems hardcoded 
![image](https://user-images.githubusercontent.com/69315569/122612456-d2c3a200-d08b-11eb-8dbc-7d1013af8a60.png)

**Comment by Craluminum2413** [comment]
I removed
 ```
               "attributes": {
                    "category": "diaries"
                }
```
and now I can sell books, what...

**Comment by copygirl** [comment]
It might be intended that only certain books can be sold, in which case the tooltip in the trader doesn't sufficiently specify which type of book they accept.

**Comment by Craluminum2413** [comment]
It would be more correct to say that books are indistinguishable even with the help of `Extended Debug Info`

**Comment by Saricane** [comment]
> It might be intended that only certain books can be sold, 

I thought about that first, but in this case, knowing that only luxuries traders accept books (AFAIK), and not always (must wait ...), if we add the necessity to match the exact title, we will all have full chests of dusty books that we can never sell.

**Comment by tyronx** [comment]
Thanks! Lore items will now have a description about their lore category so they can be told apart. Will be in pre.6

**Comment by Craluminum2413** [comment]
Seems it doesn't fixed, I can't even put lore-book to offer slot

![image](https://user-images.githubusercontent.com/69315569/125360706-f15c4680-e374-11eb-9b6f-89be03be2af6.png)

**Comment by tyronx** [comment]
oh, creative inventory, that one has no lore category, not sure why its in the creative inventory to begin with. You need a lore book looted from ruins.

**Comment by Craluminum2413** [comment]
Oh, sorry, I meant `/giveitem lore-book`

**Comment by tyronx** [comment]
Yea, this is intended to not work. But, it sounds it would be useful if /giveitem and /giveblock would allow attribute setting as an argument. I've made that now in rc.3, via `/giveitem lore-book 1 { category: "diaries" }`
