### ISSUE TITLE
Rope is odd

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1021]
**Game Version:** 1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Place a fence
2. Put a rope on the fence with Sneak + RMB
3. Drop rope with Q button
4. Rope item stuck to the entity rope, it will not turn to rope item after breaking fence

### Videos

https://user-images.githubusercontent.com/69315569/122624021-17a90200-d0a7-11eb-874d-0b6dbe339a44.mp4

**Comment by copygirl** [comment]
From what I understand ropes are very much WIP at this time.

**Comment by Craluminum2413** [comment]
Yeah, this is why I reported about this

**Comment by Craluminum2413** [comment]
It looks like a snake, so I guess rope physics will allow to add snakes in the future

**Comment by tyronx** [comment]
Yea, its derpy. Thats why its off for survival mode. Will revisit this on another major version.
