### ISSUE TITLE
Water completely destroys lamps, torch holders and torches

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1023]
**Game Version:** 1.14.10
**Platform:** Windows 10
**Modded:** No

### Description
Flowing water from a placed water source block completely destroys ceramic lamps, torch holders with/without torch and torches, instead of turning them into items and/or extinguishing them. Very unpleasant discovery when moving animals inside a den.

### How to reproduce
1. Place oil lamp, burning torch, torch holder on the ground or on a side of block just above the ground
2. Place a water source block on the ground near them, so flowing water reaches them.
3. When water reaches them, they simply disappear with particle effect, leaving nothing.

### Expected behavior
Either to have torch holders and oil lamps unaffected by water, like lanterns. And torches to keep standing but become extinguished.

Or:
- Lamp turning into an item, ceramic bowl. Maybe with a 50% chance of getting the fat back.
- Torch to be turned into item, extinguished torch.
- Torch holder to stay in his place, but remove torch from inside of it, spawning it as an extinguished torch item.

### Screenshots
Screenshots with placement before water, after water placed, with water removed -> no items left.
![2021-06-19_11-38-39](https://user-images.githubusercontent.com/25122345/122636775-b1969c00-d0f3-11eb-8e23-ad10c83d8c62.png)
![2021-06-19_11-38-49](https://user-images.githubusercontent.com/25122345/122636778-b2c7c900-d0f3-11eb-983f-b33ab235d76a.png)
![2021-06-19_11-38-56](https://user-images.githubusercontent.com/25122345/122636779-b3605f80-d0f3-11eb-9fcb-53f64493d284.png)

### Logs
no crashy

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed in pre.5
