### ISSUE TITLE
Spoiled pie part : endless rot

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1024]
**Game Version:** 1.15.0-pre3
**Platform:** Windows 
**Modded:** No

### Description
You can generate infinite rot with a single spoiled pie part.

### How to reproduce
1. Take a 100% spoiled pie part in hand 
2. Throw the part in water (not in a barrel)
3. After a few seconds, the pie start generating endless rot icons (1st bug)
4. Sneak to fetch 1 rot AND the pie part (2nd bug)
5. goto 2 (heretic ... he used a goto, throw him in the flames)

### Expected behavior
Probably just 1 rot and 1 icon.

### Screenshots
![pie](https://user-images.githubusercontent.com/84909583/122649278-639e8a00-d12d-11eb-94d9-89f67973fc79.png)

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.15.0-pre.5. Can you record a video to explain it better? Are you playing on a server?

**Comment by Saricane** [comment]
I'm installing pre5, but it seems to be fixed
`Fixed: Placed rotten pies going invisible and not properly rotting`

**Comment by copygirl** [comment]
Will close as fixed for now. Comment if you still find issues. Thank you!
