### ISSUE TITLE
Some items in handbook have incorrect text placement

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1027]
**Game Version:** 1.15.0-pre.4
**Platform:** Windows
**Modded:** No

### Description
For some items, the handbook displays incorrect text placement for "Created by" etc

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/122670796-774cfd80-d1cc-11eb-80cb-96c4b319f820.png)

**Comment by tyronx** [comment]
thanks, this should be fixed in pre.6

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/123540477-dfa95b00-d747-11eb-8f83-6ecb0c44ca59.png)
![image](https://user-images.githubusercontent.com/69315569/123540488-e8019600-d747-11eb-8750-dda848d82fde.png)
![image](https://user-images.githubusercontent.com/69315569/123540504-ff408380-d747-11eb-8bb5-dcf3afd86565.png)

**Comment by tyronx** [comment]
thank you, this should be fixed in pre.10
