### ISSUE TITLE
Several problems with the crucible in the firepit

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1028]
**Game Version:** 1.15.0-pre.4
**Platform:** Windows
**Modded:** No

### Description
Can put ingots in the crucible using Shift. Cannot take the crucible from the firepit. Cannot put any fuel when crucible in the firepit, except using Shift, but then you cannot take if from. Lag spikes when trying to take any item (that you cannot take) from the firepit using Shift, when there is a crucible.

### Videos

https://user-images.githubusercontent.com/69315569/122672118-92bb0700-d1d2-11eb-8a9b-965ee9b78051.mp4

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.5
> Fixed: Various Firepit bugs introduced in pre.4

**Comment by copygirl** [comment]
I presume all of the ones you mentioned have been fixed, then?

**Comment by Craluminum2413** [comment]
@copygirl Yes. If not everything is fixed, then I always write about it
