### ISSUE TITLE
items dropped above occupied surface are bouncing

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1029]
**Game Version:** 1.15.0-pre4
**Platform:** Windows
**Modded:** No

### Description
I stored 4 cooking pot on 4 squares. Whatever I drop above them keep bouncing.

### How to reproduce
1. Put some cooking pots on ground
2. Drop any item above them
3. You can dance.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

https://user-images.githubusercontent.com/84909583/122675515-12989f80-d1da-11eb-8160-bb8d2129372e.mp4

**Comment by Saricane** [comment]
But I wonder if I really want to see this one fixed. It could make nice animation in your main room !

https://user-images.githubusercontent.com/84909583/122675985-3a890280-d1dc-11eb-929b-bfd684cce4e3.mp4

**Comment by Craluminum2413** [comment]
Throw 640 torches there and everything will lag

**Comment by tyronx** [comment]
lol, that surely is one of the more entertaining bugs :D

**Comment by tyronx** [comment]
Thanks for the report, this bug should be mitigated for pre.6

**Comment by Craluminum2413** [comment]
Do you mean pre.7?

**Comment by tyronx** [comment]
ah yes, pre.7, my bad
