### ISSUE TITLE
Cannot make different piles on top of each other

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1030]
**Game Version:** 1.15.0-pre.4
**Platform:** Windows
**Modded:** No

### Description
For example, you cannot make `bauxite stone brick pile` on `phyllite stone brick pile`. But there is a workaround, this can only be done as shown in the video.

### How to reproduce (stone brick pile as example)
1. Make a full stone brick pile
2. Try to make another stone brick pile (from a different type of stone) on the top of previous pile
3. You cannot

### Videos

https://user-images.githubusercontent.com/69315569/122678064-c9eae180-d1ed-11eb-86b5-f7cd5d8ccdbd.mp4

**Comment by Saricane** [comment]
I always thought that you can only have homogenous stacks, so I never considered this as a bug.

**Comment by Craluminum2413** [comment]
From a realistic point of view, this is definitely a bug

**Comment by tyronx** [comment]
Surely is debatable if this is a bug. In any case, making this work is easy, so this will be possible from pre.6 and onwards
