### ISSUE TITLE
Character sits and stands up when typing in chat (hotkeys G, WASD)

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1032]
**Game Version:** 1.14.10
**Platform:** Windows 10
**Modded:** No

### Description
When typing text in chat, including commands, the character reacts on hotkey "G", and when seated, stands up when one of WASD is typed.

### How to reproduce
1. Stand.
2. Type in chat: /group create
3. Observe that while typing your character will sit on "g" and stand up on "a".

### Expected behavior
Character does not react on any movement keys when they are typed in chat.

### Screenshots
-

### Logs
-

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.15.0-pre.4

**Comment by copygirl** [comment]
No need to record a video.

@Craluminum2413 If you can reproduce the issue in 1.14.10 we can assume it is now fixed.
Alternatively, @Heptagon-ru could see if they can still reproduce it in 1.15.

**Comment by Heptagon-ru** [comment]
Will do when TOPTS converted to 1.15 and issue is not resolved yet. Can't install 1.15 till then.

**Comment by Craluminum2413** [comment]
I haven't been able to reproduce this in 1.14.10

**Comment by Heptagon-ru** [comment]
Ok, thanks to Fulgen, the source of issue was found - VSHUD :(((((((((((((

I do disable mods for testing such simple tickets, to be able to place "No" to the "Mods" section.
Something went wrong this time :(

Sorry for all the hassle and thanks for cross-testing!
Gonna bother Novocain with this now.
Closing the ticket then.
