### ISSUE TITLE
Cannot put rope on the dry stone fence or rough-hewn fence

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1035]
**Game Version:** 1.15.0-pre.5
**Platform:** Windows
**Modded:** No

### Videos

https://user-images.githubusercontent.com/69315569/122685087-121bfb00-d212-11eb-91c9-ef65fa962dc0.mp4

**Comment by tyronx** [comment]
Ok, can now attach ropes to hewn fences starting from pre.6. Them not being attachable to stone fences is on purpose.
