### ISSUE TITLE
How to solve meal naming problem - always name them alphabetically

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1036]
**Game Version**: 1.14.x, 1.15.x

At the moment, meals from the same, but with a different order of ingredients, the game understands as two different meals.

Leaving only first name by alphabet and skipping other variants (**right in the code**) will completely fix "why I cannot put absolutely the same meal in the crock".

For example, the meal on screenshot should be always named as `blueberry-cranberry jam`, other variants should be omitted.
![image](https://user-images.githubusercontent.com/69315569/122685169-7a6adc80-d212-11eb-8bd1-e3f468aab627.png)![image](https://user-images.githubusercontent.com/69315569/122732867-585e7200-d285-11eb-9572-167cd408bc87.png)

**Comment by Craluminum2413** [comment]
What if I turn it into "the different meals from the same ingredients" issue?

**Comment by copygirl** [comment]
Just keep this issue and edit it as needed. Not being able to stack meals that are effectively the "same" could be considered a bug, even if just a small one.

**Comment by Craluminum2413** [comment]
Fixed with sort attributes thing in 1.19 I think
