### ISSUE TITLE
The cursor is centered with item, if an item is selected on the hotbar when the game window is inactive

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1039]
**Game Version:**  1.15.0-pre.5
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Have any item in the hotbar
2. Press `Win` key, without pause the game
3. Select the item you have in your hotbar
4. The item with your cursor is moved to the center of the screen

### Videos

https://user-images.githubusercontent.com/69315569/122689351-95e1e180-d22a-11eb-8a6c-2a54985e683e.mp4

**Comment by copygirl** [comment]
This is intentional, so you can for example press and release `Alt` to move items between containers, or just in general for Immersive Mouse Mode. The fact that this happens in this weird edge-case is just an implementation detail. Let me know if it affects survival gameplay.
