### ISSUE TITLE
Cannot open item's handbook page in some cases

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1040]
**Game Version:** 1.15.0-pre.5
**Platform:** Windows
**Modded:** No

### Description
If a some window was opened right before you wanted to view the item's handbook page, it will open the handbook only, but not the item's handbook page.

### How to reproduce (one of the ways)
1. Open creative inventory
2. Try to open the pages of some items by hovering over them and pressing H
3. Now try (without closing the window) to open the Journal by pressing the key, then close it
4. Repeat 2nd step
5. You cannot open item's handbook page

### Videos

https://user-images.githubusercontent.com/69315569/122689698-58cb1e80-d22d-11eb-8465-ab092260e428.mp4

**Comment by copygirl** [comment]
What happens if you move your mouse a little bit (perhaps to another slot) before you attempt to press H again? I think there might be code that updates the currently hovered slot which is only run when the mouse is moved.

**Comment by Craluminum2413** [comment]
It looks like it only crashes when I open the chest when my character is in blocks. But I don't know for sure

**Comment by Craluminum2413** [comment]
Oh

**Comment by Craluminum2413** [comment]
Maybe yes

https://user-images.githubusercontent.com/69315569/122690592-199fcc00-d233-11eb-8aef-2ebf55a2677c.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.7 and probably break 10 other edge cases :D
