### ISSUE TITLE
Why do trees and bushes generated on gravel and sand?

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1043]

**Comment by tyronx** [comment]
That's on purpose
https://www.google.com/search?q=tree+growing+in+sand&client=firefox-b-d&source=lnms&tbm=isch&sa=X

**Comment by Craluminum2413** [comment]
But they cannot grow on such a scale in reality.
![2021-06-21_22-11-48](https://user-images.githubusercontent.com/69315569/122910801-4cdf7980-d35f-11eb-9f40-9f30a6c61660.png)
![2021-06-21_22-13-12](https://user-images.githubusercontent.com/69315569/122910714-30dbd800-d35f-11eb-9db0-ce93ad290d94.png)

**Comment by tyronx** [comment]
It's a game. We cannot smoothly transition from soil to sand without issues. I.e. this is intentional and not a bug.
