### ISSUE TITLE
Items that cannot be sold can be put into the trader's offer inventory using Shift

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1045]
**Game Version:** 1.15.0-pre.6
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Open trader's inventory
2. Press `Shift` + `Left Click` on any item that you cannot sell to trader
3. It took the trader's offer slot

### Expected behavior
Cannot move an item that cannot be sold

### Videos

https://user-images.githubusercontent.com/69315569/122840649-3a375700-d303-11eb-9321-4da837aab290.mp4

**Comment by Th3Dilli** [comment]
thanks to korobya this will be fixed in the next released version
