### ISSUE TITLE
Bamboo generation looks weird.

### ISSUE THREAD

**Issue by zkol** [anegostudios/VintageStory-Issues#105]
1.5.3 single player, worldgen (new world): Brown and green bamboo has no leafs, but some pumpkin vines instead.

![2018-05-20_10-12-39](https://user-images.githubusercontent.com/37601868/40276990-6b3c8bb0-5c17-11e8-8f54-874da0d238e6.png)

On the official server, the previously generated Bamboo looks normal (means no client texture issue)

![2018-05-20_10-17-58](https://user-images.githubusercontent.com/37601868/40276993-820b273e-5c17-11e8-9663-cc44ae3f9f7e.png)

**Comment by tyronx** [comment]
Is it just a texture issue? And maybe you can upload me the savegame, i can't reproduce this

**Comment by zkol** [comment]
The second screenshot is the same client on the public server. No issue on the public server means from my understanding that the client has no texture issue. The weird blocks are "real".  It is not only that I see bamboo and pumpkin vines instead of leafs, I get the bamboo and "growing pumpkin vine" drops, when I fell the tree. I can craft bamboo planks from this drops and I can try to place  the pumpkin vines (but they disappear after a second or so, I think because that's not the way how pumpkins are planted).

**Comment by zkol** [comment]
[awesome cave valley.vcdbs.gz](https://github.com/anegostudios/VintageStory-Issues/files/2022031/awesome.cave.valley.vcdbs.gz)
gzipped the savegame

**Comment by tyronx** [comment]
I see the bug, but i don't see by what it could be caused. Outside the spawn chunks the bamboo looks fine. If i recreate the world using the same seed it also looks fine. Can you also try that? There is a button for that on the modify world screen.

**Comment by zkol** [comment]
OK strange, when I recreated the world, the bamboo looked fine too. 
So the issue not reproducible for me too.
