### ISSUE TITLE
output sound devices appear twice

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1050]
**Game Version:** 1.15 pre 6
**Platform:** Windows
**Modded:** No

### Description
Output device duplicated in settings

### How to reproduce
1. Have output device
2. Go to settings
3. Click the down arrow

**Comment by Craluminum2413** [comment]
I have the same, I noticed this about six months ago
![image](https://user-images.githubusercontent.com/69315569/123073993-9a232000-d41f-11eb-9cb0-2ca91e73ab6e.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.7
