### ISSUE TITLE
Invisible amaranth porridge

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1052]
**Game Version:** 1.15.0-pre6
**Platform:** Windows 
**Modded:** No

### Description
Amaranth porridge is not rendered. The cooking pot looks empty, even the bowl containing it. Just a graphical issue, the porridge is present.

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/123512961-03f73000-d693-11eb-8248-bee003ac6023.png)

**Comment by tyronx** [comment]
thanks for the report, should be fixed in pre.11
