### ISSUE TITLE
Handbook links don't work

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1057]
**Game Version:** 1.14 stable
**Platform:** Windows
**Modded:** No

### Description
mechanical power article links don't work

### How to reproduce
Open handbook to mechanical power and try to click on links

### Expected behavior
Links to take you to wiki

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/123390338-a7d7c300-d54f-11eb-825e-03f20cc86acc.png)

**Comment by Craluminum2413** [comment]
The same for clutch and transmission

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.8

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/123514180-4112f080-d69a-11eb-9080-167d12c53d74.mp4
