### ISSUE TITLE
Can't squeeze honeycomb in bowl

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1059]
**Game Version:** 1.15 pre 6
**Platform:** Windows 
**Modded:** No

### Description
Due to the updated ground storage, can no longer squeeze honeycomb into a bowl.

### How to reproduce
1. place bowl
2. select honeycomb and hold right click

### Expected behavior
bowl to fill with honey

**Comment by tyronx** [comment]
thanks for the report, this should be fixed for pre.8
