### ISSUE TITLE
Can't place furniture if a dropped item in that space

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#106]
1.5.3, official server.
If the air space above the block is "taken" by a dropped item, I can't place a bomb or a table into that space.
But I can place a torch or a ladder.
These are all the blocks I tested.

So e.g. when I blow up some ore with a bomb, and there is a rock item floating in air, I can't place a bomb into the same air block where the rock item is floating.

**Comment by tyronx** [comment]
Ok, fixed for 1.5.3.1, thank you

**Comment by copygirl** [comment]
> Ok, fixed for 1.5.3.1, thank you

Already told Tyron this, but as a result of some of the changes I made to the game to push SemVer as a standard, 4-part version numbers will cause issues with mod dependencies. I didn't realize this at first, but it's probably better this way. So the next version will actually have to be `1.5.4`.
