### ISSUE TITLE
Animals that die in deep water sink 2-4 blocks and the corpse hovers

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#1061]
**Game Version:** 1.14 all through to 1.15 pre7
**Platform:** Windows
**Modded:** No

### Description
Reported on discord. It's a bug that's been around for a while. https://discord.com/channels/302152934249070593/334233095374897152/856540000743850005

### How to reproduce
1. Kill animal/mob in deep water
2. Animals/mob sinks a few blocks then hovers/lands in the water about 2-4 blocks below surface regardless of ground or water beneath it

### Expected behavior
Animals/mob corpse should either float or sink. Not sink then hover part way.

### Screenshots
Discord link to report: [Link](https://discord.com/channels/302152934249070593/334233095374897152/856540000743850005)
![unknown-5](https://user-images.githubusercontent.com/13642054/123423423-7397ed00-d5b7-11eb-8ab4-b4b4713793ab.png)

**Comment by tyronx** [comment]
thank you for the report! I belive this should be fixed in pre.11 now
