### ISSUE TITLE
Body temperature vs Meal temperature

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1063]
**Game Version:** 1.15.0-pre6
**Platform:** Windows
**Modded:** No

### Description
On pre4, you said : 
`Feature: The players body temperature is now affected by the temperature of consumed meals (meals only right now)`

Well, just after eating 2 bowls of cold amaranth porridge, my body t° just dropped to 31°, with icy windshield and shaking. I was perfectly fine before, and the outside t° is 23°. So, I have a doubt about this new mechanism. Does it need some tuning ?

![2021-06-25_16-13-27](https://user-images.githubusercontent.com/84909583/123439967-94ba0700-d5d2-11eb-8f14-d78ad7eb8656.png)

**Comment by tyronx** [comment]
thanks for the report. I'll disable getting colder from a meal for the time being, will be in pre.8
