### ISSUE TITLE
Fired kiln items disappearing on 1.15.0 pre 7

### ISSUE THREAD

**Issue by LordDeatHunter** [anegostudios/VintageStory-Issues#1065]
**Game Version:** 1.15.0-pre7
**Platform:** Windows
**Modded:** No

When a kiln finishes firing, the fired items disappear.
Because of #1062, a torch couldn't be used, so the fire was started using a fire starter.

**Comment by copygirl** [comment]
What specifically were you firing? Or does this happen with any items?

**Comment by LordDeatHunter** [comment]
I tried it with raw fire clay bricks, and my friend tried it with cooking pots and bowls.
I didn't mention that since I assume it applies to everything.

**Comment by Saricane** [comment]
In issue #1044 , Tyron said 

>There is a small-ish chance this is fixed in pre.7

It seems not.

**Comment by tyronx** [comment]
Is there any pattern behind this? Does it never fire correctly? Does it sometimes fire correctly? Does it depend on the position you fire, or does it break only after you go on a journey and come back to it?

**Comment by Saricane** [comment]
Sadly, I did not find any reproductible pattern.

>  Does it never fire correctly? Does it sometimes fire correctly?

Yes, In the same pit, I had some success and some fail. Fail look random, though it's not :-)

> Does it depend on the position you fire?

Not sure to understand. I had fails with anvil, storage vessel, pickaxe and other "flat" molds, 4 bowls, 1 cooking pot ... as far as I remember.

I cheked chunk boundary, but no, kilns were not on a boundary.

>does it break only after you go on a journey and come back to it?

No, because, two times, I was right near the kiln, panning, when I heard the fire sound stop.

**Comment by LordDeatHunter** [comment]
Just reporting that I am no longer having this issue on 1.15.0 pre-8.
If no one else has gotten it, feel free to close the issue.

**Comment by Heptagon-ru** [comment]
Sorry, iirc player Entity on TOPTS said just few hours ago they lost their items in kilns. Iirc it were ingot molds and axe mold. So they asked any player to help them out. Dark Nekromant 2 did help and brought them molds.

**Comment by Saricane** [comment]
Bug still there on pre8. Now with a stack of 12 fire bricks. Was close when the kiln stopped burning.

![2021-06-27_06-19-27](https://user-images.githubusercontent.com/84909583/123532785-87a33200-d710-11eb-811f-b1bfbff3bdd5.png)

**Comment by Saricane** [comment]
Just made another kiln with the same method (2 blocks of soil in a corner wall) but at another place in the base, again with 12 fire bricks, same result.

**Comment by tyronx** [comment]
I'll add logging to pre.9, so we can narrow down the cause of this.

**Comment by Heptagon-ru** [comment]
Four planters vanished from pit kilns just now  on pre 9, TOPTS. Maybe were lighted in pre 8.
I returned from long journey to 1.15 lands.
Adding a zipped log dir.
[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/6721741/Logs.zip)

**Comment by Thor8472** [comment]
Pre9 (new world, SP)  products from 1 of 2 kiln gone! the pot and 3 bowls on the left are there. but second pit with a storage vessel is empty. its seems only the kiln with the bows and pots are mentioned in the logs. I cant find an entry about the kiln with the storage vessel

[logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/6721792/logs.zip)

**Comment by Saricane** [comment]
3 kilns, from left to right, 2 bowls, 3 bowls, 4 bowls (I love bowls).  All empty when process finished. On purpose, I did not leave the area during the process. Logs included. Good reading :-)

![2021-06-27_17-21-33](https://user-images.githubusercontent.com/84909583/123551871-f4034d00-d773-11eb-932d-4aa34ef634ea.png)

[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/6721898/Logs.zip)

**Comment by Saricane** [comment]
With pre10, I tried the exact same test as above, it is a complete fail, and this time, the new debug logs give something to read. Logs attached.
[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/6728074/Logs.zip)

**Comment by copygirl** [comment]
Here is the relevant info from the debug logs:

> ```
> 28.6.2021 17:26:40 [Debug] Pit kiln @514566, 144, 527908: Ignited.
> 28.6.2021 17:26:44 [Debug] Pit kiln @514564, 144, 527908: Ignited.
> 28.6.2021 17:26:48 [Debug] Fire @514566, 145, 527908: Spread to 514566, 145, 527908.
> 28.6.2021 17:26:53 [Debug] Fire @514564, 145, 527908: Spread to 514564, 145, 527908.
> 28.6.2021 17:26:55 [Debug] Pit kiln @514562, 144, 527908: Ignited.
> 28.6.2021 17:27:04 [Debug] Fire @514562, 145, 527908: Spread to 514562, 145, 527908.
> 28.6.2021 17:45:17 [Debug] Pit kiln @514574, 139, 527890: Ignited.
> 28.6.2021 17:45:25 [Debug] Fire @514574, 140, 527890: Spread to 514574, 140, 527890.
> 28.6.2021 18:53:14 [Debug] Fire @514566, 145, 527908: Destroy fuel @ 514566, 144, 527908.
> 28.6.2021 18:53:14 [Debug] Fire @514566, 145, 527908: Destroy fire.
> 28.6.2021 18:53:19 [Debug] Fire @514564, 145, 527908: Destroy fuel @ 514564, 144, 527908.
> 28.6.2021 18:53:19 [Debug] Fire @514564, 145, 527908: Destroy fire.
> 28.6.2021 18:53:30 [Debug] Fire @514562, 145, 527908: Destroy fuel @ 514562, 144, 527908.
> 28.6.2021 18:53:30 [Debug] Fire @514562, 145, 527908: Destroy fire.
> ```
> ```
> 28.6.2021 21:14:55 [Debug] Fire @514574, 140, 527890: Destroy fuel @ 514574, 139, 527890.
> 28.6.2021 21:14:55 [Debug] Fire @514574, 140, 527890: Destroy fire.
> ```

One random thought that came to my head: This only happens to some people's kilns, right? Does it happen if you re-use the same spot you fired something previously? Could it be that there is block entity data that is not correctly cleared, and affects future kiln use?

**Comment by Muyingwa** [comment]
Mixed results today. Anvil mold failed both times, others were successful but I've had the same molds fail before.

[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/6730144/server-debug.txt)

**Comment by Saricane** [comment]
I made a test on 2 never used pits (to answer Copygirl's question) : 2 fails.

Here's the logs extract ;

>29.6.2021 07:47:29 [Debug] Pit kiln @514565, 144, 527911: Ignited.
29.6.2021 07:47:33 [Debug] Fire @514565, 145, 527911: Spread to 514565, 145, 527911.
29.6.2021 07:47:33 [Debug] Pit kiln @514563, 144, 527911: Ignited.
29.6.2021 07:47:39 [Debug] Fire @514563, 145, 527911: Spread to 514563, 145, 527911.
29.6.2021 08:06:39 [Debug] HandleEntityInteraction received from client Saricane but no such entity found in his range
29.6.2021 08:19:16 [VerboseDebug] Saricane moved 1x from hotbar-xad+H0RO0dszrWmxOMc3uFgq to ground-xad+H0RO0dszrWmxOMc3uFgq
29.6.2021 08:34:01 [Debug] Fire @514565, 145, 527911: Destroy fuel @ 514565, 144, 527911.
29.6.2021 08:34:01 [Debug] Fire @514565, 145, 527911: Destroy fire.
29.6.2021 08:34:01 [Debug] Fire @514565, 145, 527911: Spread to 514565, 145, 527911.
29.6.2021 08:34:06 [Debug] Fire @514565, 145, 527911: Destroy fuel @ 514565, 145, 527912.
29.6.2021 08:34:06 [Debug] Fire @514565, 145, 527911: Destroy fire.
29.6.2021 08:34:07 [Debug] Fire @514563, 145, 527911: Destroy fuel @ 514563, 144, 527911.
29.6.2021 08:34:07 [Debug] Fire @514563, 145, 527911: Destroy fire.
29.6.2021 08:34:07 [Debug] Fire @514563, 145, 527911: Spread to 514563, 145, 527911.
29.6.2021 08:34:12 [Debug] Fire @514563, 145, 527911: Destroy fuel @ 514564, 145, 527911.
29.6.2021 08:34:12 [Debug] Fire @514563, 145, 527911: Destroy fire.

[Logs3.zip](https://github.com/anegostudios/VintageStory-Issues/files/6733038/Logs3.zip)

**Comment by tyronx** [comment]
Ok I think the problem is, the normal fire system sees the pit kiln as fuel and consumes it as such.

**Comment by copygirl** [comment]
I'll close as resolved, then.
