### ISSUE TITLE
Buckets of water placing non-flowing water

### ISSUE THREAD

**Issue by LordDeatHunter** [anegostudios/VintageStory-Issues#1067]
**Game Version:** originally tested on 1.15.0-pre6, still exists in 1.15.0-pre7
**Platform:** Windows
**Modded:** No

Placing down water from a bucket makes an non-flowing water source most of the time.
Rarely, the water is fine and flowing, but most of the time it is stuck in place.
I have not managed to figure out what this depends on, but I think it might be position-related since placing, then removing the water, then placing it again in the same place will always give the same result.
![unknown](https://user-images.githubusercontent.com/26803198/123460213-94783680-d5e7-11eb-9b9b-cc4c76f6970b.png)

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.8

**Comment by copygirl** [comment]
> Fixed: Water placed by a bucket not spreading
~ [1.15.0-pre.8](https://info.vintagestory.at/v1dot15#pre8)
