### ISSUE TITLE
Items stored in reed basket in trader's cart vanished

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1069]
**Game Version:** 1.15.0-pre7
**Platform:** Windows 
**Modded:** No

### Description
I stored various items in the reed basket inside agricultural trader's cart (the main cart, not a trailer), then went for a trip a few chunks away, and when I returned, the basket was empty.

**Comment by tyronx** [comment]
is this reproducible?

**Comment by sirStroam** [comment]
Unable to reproduce in 1.15 pre 10. Closing until more detail is provided.
