### ISSUE TITLE
Signs delete 4th text line

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#107]
When entering 4 lines of text into a sign and clicking Save, it shows 4 lines in the world.
But opening it again - it shows only 3 lines in sign's text editor.
If click "Save" - the 4th line will disappear from the sign surface. If Cancel - it stays.
But it is absent in the text editor anyway.
On the screenshots I opened the sign after entering the text the first time and saving it.
![2018-05-20_21-35-00](https://user-images.githubusercontent.com/25122345/40282318-48c70f56-5c76-11e8-9268-16b6a9a002b0.png)
![2018-05-20_21-35-44](https://user-images.githubusercontent.com/25122345/40282319-48e5d206-5c76-11e8-922c-7b71b0083e56.png)
![2018-05-20_21-36-08](https://user-images.githubusercontent.com/25122345/40282320-49030150-5c76-11e8-922d-a21e677b5d65.png)

**Comment by tyronx** [comment]
thank you, fixed for 1.5.4
