### ISSUE TITLE
Trader : buy duplicate item

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1070]
**Game Version:** 1.15.0-pre7
**Platform:** Windows
**Modded:** No

### Description
Found an agricultural trader who buy twice the same item. As the clothes are exactly the same, and with the same condition rate, I guess this is a duplicate offer.

### Screenshots
![dup-trade](https://user-images.githubusercontent.com/84909583/123487914-23e51000-d60f-11eb-8f47-2c4dbc0e9759.png)

**Comment by Craluminum2413** [comment]
They also sometimes have empty slots between items

**Comment by tyronx** [comment]
thank for the report, this should be fixed in pre10
