### ISSUE TITLE
Changing month duration using the commands world creation caused time travel

### ISSUE THREAD

**Issue by Fireztonez** [anegostudios/VintageStory-Issues#1071]
**Game Version:** 1.14.10
**Platform:** Windows 10
**Modded:** Yes;
**Mod installed:**  HudClock 2.4.2, PlayerCorpse v1.0.2, StepUp v.1.2.0, Xandus Inventory Tweaks v.1.2.3

### Description
Hello, in my current game I have change the month duration from 9 days to 40 days. When I left my game, it was June 3, 1386. The next day when I reopened the game, we had reached February 8, 1386, so we were back in the past until the winter.

I fixed my issue on my side by adding back 3624h to the time, but I think this is probably a problem who should be report here, because that's clearly not normal to travel back in the time when you change that config 😆.

If needed I have a backup of the before adding the time, so I can provide you that save.

### How to reproduce
1. Create a world without changing any options
2. Change the month duration to 40 days
3. Quit and save your game
4. Go back to your world and enjoy the winter!

### Expected behavior
The date should stay the exact same than before we quit the game

### Screenshots
I get this issue live in twitch, so here's the VOD directly when we open my world: https://www.twitch.tv/videos/1066870372?t=0h8m28s
You can create some's clips if needed, the VOD should be available for about 58 days from now.

### Logs
There have no crash and I didn't take the logs at this moment, sorry. I still have a backup of the game, before we add back the 3624h to fixed the issue if needed.

**Comment by copygirl** [comment]
When you say "mount", do you mean "month"?

**Comment by Fireztonez** [comment]
Yes Sorry, english is not my first language and I make somes error I think, I will edit my message to fix that error, thank's

**Comment by tyronx** [comment]
Because it also affects all past months. Not sure there's an easy fix for that.

**Comment by copygirl** [comment]
Is it possible to save the "progress in year" or maybe month + day something? So when the month duration changes, the time is recalculated so it's roughly the same time of year?

**Comment by tyronx** [comment]
sure is, but that still causes time travel by full years

**Comment by copygirl** [comment]
Then.. save the year, as well? I'd probably go with just saving the full date and time when the game saves, so time can't go back or advance when things such as "days per month" changes.

**Comment by tyronx** [comment]
hmmm. Sounds feasible, true.

**Comment by Fireztonez** [comment]
> Then.. save the year, as well? I'd probably go with just saving the full date and time when the game saves, so time can't go back or advance when things such as "days per month" changes.

This is exactly the fix I have in the head for that issue :-)
