### ISSUE TITLE
Cannot build item above slab

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1077]
**Game Version:** 1.15.0-pre8
**Platform:** Windows
**Modded:** No

### Description
Since pre8, cannot put an item above a slab. 

### How to reproduce
1. Put a horizontal slab on the upper half of a block
2. Try to put something above (a bucket, a quern, ...)
3. "cannot place this block here. Require a solid ground"

Solid blocks can still be built on top of a slab. The issue is just for items.

### Screenshots
![2021-06-27_08-55-30](https://user-images.githubusercontent.com/84909583/123535739-05be0380-d726-11eb-89b9-12fe1223b1e0.png)

**Comment by Craluminum2413** [comment]
[1.15.0-pre.9](https://info.vintagestory.at/v1dot15#pre9)
> Fixed: Upside slabs no longer considered solid ground

**Comment by tyronx** [comment]
indeed, this is now fixed
