### ISSUE TITLE
Pineapple pie has wrong names

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1078]
**Game Version:** 1.15.0-pre9
**Platform:** Windows
**Modded:** No

### Description
Pineapple pie is referenced with its code name, instead of the real label. Others fruit pie are well referenced.

### How to reproduce
1. Make a 1 fruit pineapple pie

### Expected behavior
Should be named like the others : Pineapple pie

### Screenshots
![pie](https://user-images.githubusercontent.com/84909583/123580671-9a823900-d7da-11eb-9b30-b58672d52992.png)

**Comment by tyronx** [comment]
thanks this should be fixed in pre.10

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/123622402-d89c4e80-d814-11eb-98bf-18763e5854b3.png)
![image](https://user-images.githubusercontent.com/69315569/123622428-dfc35c80-d814-11eb-8b97-98cb9adfd6a0.png)

**Comment by copygirl** [comment]
Will mark as resolved for now since I don't know whether its name got added. Tyron might see your comment either way.

**Comment by tyronx** [comment]
didnt yet but will be in pre.11 👍
