### ISSUE TITLE
Axe doesn't lose durability on breaking naturally generated leaves

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1080]
**Game Version:** 1.15.0-pre.10
**Platform:** Windows
**Modded:** Yes
```
CarryCapacity
StepUp
Waypoint Extensions
VS Prospector Info
```

### How to reproduce
1. Craft (any) axe
2. Break (any) naturally generated leaves
3. Axe doesn't lose durability

### Videos

https://user-images.githubusercontent.com/69315569/123877540-0d5bf300-d946-11eb-9831-de79822732fa.mp4

**Comment by copygirl** [comment]
I think the axe not losing durability when cutting leaves is intentional, at least when it chops down entire trees. I suppose this also applies to breaking single leaves blocks?

**Comment by Craluminum2413** [comment]
Then why does it break from the leaves placed in the creative?

**Comment by tyronx** [comment]
ah yes, that should not be the case, will be fixed in pre.11
