### ISSUE TITLE
Some clay products cannot be picked up after clay forming

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1081]
**Game Version:** 1.15.0-pre.10
**Platform:** Windows
**Modded:** Yes
```
CarryCapacity
StepUp
Waypoint Extensions
VS Prospector Info
```
### Description
Can't pick up (when single only) `raw flowerpot`, `raw crucible`, `raw crock`, etc. after finished clay forming

### Videos

https://user-images.githubusercontent.com/69315569/123878148-32049a80-d947-11eb-85d6-793f5ec2ec72.mp4

https://user-images.githubusercontent.com/69315569/123878475-c1aa4900-d947-11eb-89df-3104be85e08c.mp4

https://user-images.githubusercontent.com/69315569/123877932-ce7a6d00-d946-11eb-8149-a2ce74c2d542.mp4

**Comment by tyronx** [comment]
fixed for crock, crucible and flowerpot. for the others i couldn't reproduce the issue, will be in pre.11

**Comment by Craluminum2413** [comment]
Watering can cannot be picked up after clay forming

**Comment by daretmavi** [comment]
In seams, that `Raw watering can` still can not be picked up in 1.15.9 (tested on Linux).

**Comment by Craluminum2413** [comment]
Fixed for raw watering can
