### ISSUE TITLE
Cannot fill troughs with amaranth seed

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1082]
**Game Version:** 1.15.0-pre11
**Platform:** Windows
**Modded:** No

### Description
Unlike other kind of grain, amaranth seed cannot fill animal troughs (the character eat the seeds instead).

### Screenshot
Though being called "Amaranth seed" this actually belongs to the grain category.
![grain](https://user-images.githubusercontent.com/84909583/124022261-dd1b5f80-d9ec-11eb-91d3-a0f238a3068c.png)

**Comment by sirStroam** [comment]
I have verified this in 1.15 pre 11

**Comment by radfast** [comment]
This is now fixed in the bleeding edge `master` branch, only needs Tyron to authorise moving it into `1.15-stable` branch so that it makes it into rc1.

**Comment by radfast** [comment]
All good now for next release, thanks again for reporting.
