### ISSUE TITLE
Falling lava incorrectly rendered

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1083]
**Game Version:** 1.15.0-pre11
**Platform:** Windows 
**Modded:** No

### Description
Column of falling lava is not correctly rendered, and appears as  "semi-ghostly".

### Expected behavior
"Plain looking" hot and red lava.

### Video
https://user-images.githubusercontent.com/84909583/124033070-c3cce000-d9f9-11eb-91c9-28f7063a41dd.mp4

**Comment by Craluminum2413** [comment]
Surround a pillar of lava with glass

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in pre.12
