### ISSUE TITLE
Sunflowers not spawning in wild, absent in blockpatches.json

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1086]
**Game Version:** 1.15 pre11
**Platform:** Windows 10
**Modded:** doesnt matter, info came from assets analysys and other player expeerince

### Description
People exploring new lands on TOPTS have not found any sunflowers in the wild yet.
I also did not find any flying in creative in solo world at deep south.
Most important - blockpatches.json contains nothing about sunflowers, so probably they are skipped at world generation,
although are present in creative inventory/handbook.
Please check?

### How to reproduce
1. Open assets/survival/worldgen/blockpatches.json
2. Search for "sun" or "flower"
3. Nothing about sunflower

### Expected behavior
Sunflower generation description to be present in blockpatches.json as for all other crops.

### Screenshots
--

### Logs
--

**Comment by copygirl** [comment]
I've been told this has been fixed for the next (pre-)release!
