### ISSUE TITLE
Cured meat can't be used for pies

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1087]
**Game Version:** 1.15 pre11
**Platform:** Windows 10
**Modded:** No

### Description
Cured meat is not accepted as pie filling. Since pickled vegetables are accepted, it seems a bug.

### How to reproduce
1. Make the pie crust
2. Try to fill it with cured redmeat.
3. It says "this item cant be added to pies"

### Expected behavior
To be able to use cured meat as pie filling

### Screenshots
![2021-07-01_14-36-25](https://user-images.githubusercontent.com/25122345/124118455-07672e80-da7a-11eb-8a86-a7efbe334872.png)

### Logs
--

**Comment by Craluminum2413** [comment]
It looks more like a suggestion rather than a bug

**Comment by sirStroam** [comment]
I'm going to leave this since pies are new and I don't know what the intent is.

**Comment by Craluminum2413** [comment]
Still not added, maybe they forgor about this

**Comment by Craluminum2413** [comment]
I assume it is intended so I close it now
