### ISSUE TITLE
Reeds next to farmland dry it out

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#109]
Reeds placed in water next to farmland blocks prevent them from receiving hydration/dry out the farmland

**Comment by Balduranne** [comment]
I made channels to water the crops, then planted reeds in them. If all of the surrounding water blocks within range have reeds in them, it suddenly stops counting as water and instantly dries out the farmland
![2018-05-25_20-32-58](https://user-images.githubusercontent.com/10406037/40570638-d8e48310-605a-11e8-877c-76965b05d129.png)

**Comment by copygirl** [comment]
Closed in favor of #126.
