### ISSUE TITLE
Water affects claimed/reinforced flusheable blocks

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1090]
**Game Version:** 1.15 pre11 TOPTS
**Platform:** Windows 10
**Modded:** No

### Description
1. Water uproots and drops as item things like oil lamps, torches, most likely torch holders, ... which are protected with claim.
So they can be picked up by a griefer who has no access to claim.

2. Water destroys same items (at least oil lamps) if they are on unclaimed land but reinforced. Again, public reinforced builds can be griefed.

On the first video, Dark placed oil lamp and torch on his claimed land, and I poured water on unclaimed land. Water has flown into claimed land and dropped oil lamp and torch as items, which I was able to pick up (potentially steal).

On the second video, Dark placed oil lamp on unclaimed land and reinforced it. I placed water and it plainly destroyed the lamp, without dropping the item. Relog did not help, still no lamp item around.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
https://youtu.be/--IkDEN3gzk
https://youtu.be/rRcZbVoomhg

**Comment by radfast** [comment]
It's challenging to think of a way to solve this for claims.   We can't simply make water not affect these types of blocks on claimed land.

For reinforced blocks it's easier.  There's a good case for water not affecting any reinforced block, on the basis the block is "bolted down" (as described in the wiki)

**Comment by Craluminum2413** [comment]
No longer relevant starting from 1.17?

**Comment by copygirl** [comment]
Makes sense. If there's remaining problems, lets open a new issue.
