### ISSUE TITLE
High destroy speed of some blocks makes easy to grief them reinforced

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1091]
**Game Version:** 1.15 pre 11 TOPTS
**Platform:** Windows 10
**Modded:** No

### Description
Placed oil lamp, reinforced by another person, can be quickly destroyed many times and picked up, because the initial destroy speed of the lamp is very low.
Video shows that I quickly removed 7 reinforcements with one short hold of left mouse button.

### How to reproduce
1. Ask a friend to place an oil lamp and reinforce it
2. Left-click it and hold
3. It spends reinforcements very fast, allowing to pick up item in seconds.

### Expected behavior
Reinforcements should provide significant protection, making destroying the property hard for griefers.

### Screenshots
5th second of:
https://www.youtube.com/watch?v=rRcZbVoomhg

**Comment by sirStroam** [comment]
Perhaps each reinforcement should reduce the order of magnitude of damage an object takes. So if an item is reinforced once, all damage it takes is divided by 10. At reinforce two all damage it takes is divided by 100. With that sort of setup, it doesn't take many levels of reinforcement to make even easily broken items pretty safe.

**Comment by radfast** [comment]
Fixed in next build, thanks for reporting the issue.
