### ISSUE TITLE
Dark Pine Seed unplantable

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1094]
**Game Version:** 1.15 pre 11
**Platform:** Windows 
**Modded:** No 

### Description
Unable to plant dark prine seed

### How to reproduce
1. Obtain dark pine seed
2. Go to grass block
3. Try to right click

### Expected behavior
For it to plant

Reference
https://discord.com/channels/302152934249070593/334233095374897152/858339651521871912

**Comment by radfast** [comment]
Intended behavior.   There is no "Dark pine" sapling or "Dark pine" tree currently, therefore nothing for this particular seed to grow into.  The only way of obtaining Dark Pine leaves is in Creative mode.  Players are still welcome to use them for custom landscaping.  It's possible in a future version there will be a new tree species implementing this.

**Comment by radfast** [comment]
For example it might be a Parasol Pine, or we might re-work the Scots Pine.  But the general feeling in the dev team is there are already enough new trees in 1.15, I would guess... !
