### ISSUE TITLE
Reinforced blocks can be picked up (right-click) by anyone

### ISSUE THREAD

**Issue by bgoetschke** [anegostudios/VintageStory-Issues#1097]
**Game Version:** 1.15.0-pre.12
**Platform:** Linux
**Modded:** No (tested on TOPTS)

### Description
A reinforced block (in this case a lantern) can be picked up (right-click) by anyone, the reinforcement stays on the item, but it can be taken away.

### How to reproduce
1. Place a lantern
2. Reinforce the lantern
3. Another player can pick it up by right-clicking

### Expected behavior
Right-Click pickup should be disabled for players that did not reinforce the block (or have been granted access).

**Comment by radfast** [comment]
Thanks for reporting.  Fixed in next release of 1.15  (which may be the final `pre` or it may be `1.15-rc1`, I'm not sure yet...).  Also discussed in Multiplayer channel on Discord on 3 July.
