### ISSUE TITLE
New water source blocks don't stop producing waterflow particles

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1099]
**Game Version:** 1.15 pre 12
**Platform:** Windows 10
**Modded:** No

### Description
v1.15.0-pre.8: 
> Tweak: Liquids that are surrounded by 3 liquid source blocks now also turn into a liquid source block. This should mitigate the forever flowing lakes issues a bit.

Tested in survival in flat world, see the video - newly generated source blocks still have "water flowing" particles generating above them. Or above parent source blocks.
Reloading does not help.
Placing parent source blocks helps, particles disappear.

### How to reproduce
(See video)
1. Place 8 water source blocks using bucket in a diamond shape around 5 air blocks shaped like cross
2. Observe 5 middle blocks becoming source blocks but "water flowing" particles still exist.
3. Reload world - particles still there.
4. Replace 8 external water source blocks again with the very same water source blocks - now particles disappear.

### Expected behavior
"Water flowing" particles disappearing right away after the first placing of 8 external water blocks (or after reloading world).

### Screenshots
https://youtu.be/R0rS_SFLN44

### Logs
--

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/124349557-4b803d80-dbf8-11eb-8b6e-bedf6c2127cd.mp4

**Comment by Craluminum2413** [comment]
Fixed in v1.18.2-rc.1
