### ISSUE TITLE
1.5.2.1 Shift click or clicking results with saw to make planks uses entire durability and give only 4

### ISSUE THREAD

**Issue by RainnMannx** [anegostudios/VintageStory-Issues#11]
Shift click with saw and maple uses entire saw and only returns 4.
Win 10 64
Happened with copper and steel saw.

**Comment by RainnMannx** [comment]
https://youtu.be/YP_J7vqC0HM
Video of it.

**Comment by milochristiansen** [comment]
I had this happen with my iron saw and kapok wood.

**Comment by tyronx** [comment]
Fixed for 1.5.2.2
