### ISSUE TITLE
Arrowheads no longer visible

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1100]
**Game Version:** 1.15.0-pre12
**World used:** pre11
**Platform:** Windows
**Modded:** No

### Description
Various issues with arrowheads

### How to reproduce
1. In creative mode, look at the arrowheads : they are insivible, and when you hover the mouse on the "empty" slot, you get a mangled icon in the tooltip (see screenshot).

2. It seems to be more than a graphic issue. In survival mode, I had a set of seven copper arrowheads in my inventory (coming from pre11), and when I upgraded to pre12, they where no more visible.  I realised the slot was occupied when I tried to put something. The problem is there was now a single arrowhead, not seven. I know that this part of the bug may be hard to reproduce :-)

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

![2021-07-03_13-57-59](https://user-images.githubusercontent.com/84909583/124353742-8ab68a80-dc08-11eb-92ef-f1c0d3b6d511.jpg)

**Comment by Craluminum2413** [comment]
I think this was noticed a long time ago and therefore I didn't report about this bug

**Comment by Saricane** [comment]
Well, may be. But until pre12, I did not have any problem with arrowheads. Strange.

**Comment by Craluminum2413** [comment]
I mean, people in the discord might have noticed this earlier (actually I have no idea, here is my discord Craluminum2413#9038), therefore, I didn't see the point in reporting this bug, because it will be fixed regardless of whether exists this report or not

**Comment by Saricane** [comment]
I'm not on Discord, so I can't see what is reported by players. I find this  github is a very handy tool for bug reporting.

**Comment by gamenerd2026** [comment]
That happend to me!

**Comment by Craluminum2413** [comment]
This is true for everyone who are using 1.15.0-pre.12

**Comment by Craluminum2413** [comment]
Fixed in [1.15.0-rc.1](https://www.vintagestory.at/blog.html/news/the-homesteading-update-v115-rc1-r284/):
> Fixed: Invisible arrowheads
