### ISSUE TITLE
Music in the Wilderness Survival playstyle does not play at all

### ISSUE THREAD

**Issue by GGBVanix** [anegostudios/VintageStory-Issues#1101]
**Game Version:** 1.15.0-pre.12
**Platform:** Windows 
**Modded:** No 

### Description
Music in the Wilderness Survival playstyle does not play at all. This is not affected by the music frequency being set to "Sometimes" or "Very Often". Music is never played at any point in time within two in-game days. Music in the Standard and Exploration playstyles plays as expected. 

### How to reproduce
1. Create a new world on the Wilderness Survival playstyle

### Expected behavior
Music should begin playing almost immediately upon loading into the world

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release

**Comment by copygirl** [comment]
This appears to still be an issue according to #1182

**Comment by Ryanlupe** [comment]
Followed reproduction steps (after reinstall) of making a Wilderness Survival World, and as of Stable v1.15.6 still no music. Music does still indeed play on other world difficulties like Normal and Creative.

**Comment by tyronx** [comment]
nuuu a small typo caused it. should be fixed in 1.15.7
