### ISSUE TITLE
Trader : money lost if inventory full  [issue withdrawn by OP!]

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1103]
**Game Version:** 1.15.0-pre12 (and 1.14)
**Platform:** Windows 
**Modded:** No 

### Description
If your inventory is full, you still are allowed to buy, but you just lose your money. 

### Expected behavior
The "BUY" button should be greyed out, and when click, a message "no space left".

**Comment by Craluminum2413** [comment]
Or they just need to be dropped

**Comment by Saricane** [comment]
My bad, items are dropped. Thanks Craluminum, and please remove this thread. Sorry.
