### ISSUE TITLE
Cooking pot turns into a crock when transferring food

### ISSUE THREAD

**Issue by shadowodes** [anegostudios/VintageStory-Issues#1104]
**Game Version:** 1.15.0-pre12  
**Platform:** Windows
**Modded:**  Not modded

### Description
Right clicking a cooking pot filled with newly cooked food onto a crock placed on the ground transfers food into the crock. But the cooking pot in hand turns into a crock

![2021-07-05_17-04-26](https://user-images.githubusercontent.com/86990752/124525717-1a00a100-ddb5-11eb-9edc-565c50337f79.png)
![2021-07-05_17-04-32](https://user-images.githubusercontent.com/86990752/124525719-1c62fb00-ddb5-11eb-9e8f-e8a56591f114.png)
### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
thanks for the repor tthis should be fixed next release
