### ISSUE TITLE
`EntityTrader` unexpectedly suppresses `EntityBehavior.OnInteract`

### ISSUE THREAD

**Issue by egocarib** [anegostudios/VintageStory-Issues#1105]
**Game Version:** 1.14.10  
**Platform:** Windows

### Description
*[Modding]*
I have been trying to add an EntityBehavior to traders to listen for when the player interacts with a trader. However, the `OnInteract` event never fires, despite the patch working and other parts of my EntityBehavior running. It looks to me like EntityTrader never calls `base.OnInteract` (if the player starts the interaction), which would prevent any EntityBehavior from ever running. See relevant code here:
https://github.com/anegostudios/vssurvivalmod/blob/6a614481136cba45aad647eed5a8dac29a3c847e/Systems/Trading/EntityTrader.cs#L278

### How to reproduce
Relevant code & JSON excerpts from my mod:
https://gist.github.com/egocarib/7c9f68307cd37d144925d48caa551695

### Expected behavior
`EntityBehavior.OnInteract()` is surfaced to the mod.

**Comment by copygirl** [comment]
I wonder if the trading interaction itself should be converted to a behavior.

**Comment by Craluminum2413** [comment]
It now has
```
base.OnInteract(byEntity, slot, hitPosition, mode);
```
