### ISSUE TITLE
Omok table top has stone material instead wood

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1109]
**Game Version:** 1.15.0-rc.1  
**Platform:** Windows
**Modded:** No

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/124752648-c9ae4e00-df30-11eb-825f-966b8641a4d0.png)

**Comment by copygirl** [comment]
Well, to be fair, it does have stone pieces on the table :laughing:

**Comment by Craluminum2413** [comment]
Now let's remember the chiseled blocks
> Now take on the mining speeds and other block material properties of the first used material

**Comment by Craluminum2413** [comment]
**Don't want to create new an issue:**
Display case is in wrong `creativeinventory`, `terrain` instead `decorative`
![image](https://user-images.githubusercontent.com/69315569/124767485-88259f00-df40-11eb-9ac9-4a255eeb4f40.png)

**Comment by tyronx** [comment]
thanks will be fixed in rc.3
