### ISSUE TITLE
modicon.png not showing

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1117]
**Game Version:** 1.15 rc 1
**Platform:** Windows   
**Modded:** Yes 

### Description
the wiki says you can add a modicon.png to your mod and it will show up in the mod manager menu. However, it does not show up there. If you search this server for "modicon.png" you will see several other modders who have experienced the same issue.
https://discord.com/channels/302152934249070593/334233095374897152/858511891211091968

### How to reproduce
https://wiki.vintagestory.at/index.php?title=Modding:Mod_Packaging

### Expected behavior
Mod icon to be used

**Comment by Craluminum2413** [comment]
I don't want to create another issue, so I post it here:
```author: "xxxxx",``` doesn't work, only ```authors: ["xxxx"]``` displays the author in Mod Manager

**Comment by copygirl** [comment]
> I don't want to create another issue, so I post it here:
> `author: "xxxxx"` doesn't work, only `authors: ["xxxx"]` displays the author in Mod Manager

That's intentional. If it says to use `author` anywhere, like the wiki, that information just needs to be updated.

**Comment by Craluminum2413** [comment]
Fixed in 1.16
