### ISSUE TITLE
Pies drop 2 when broken

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1118]
**Game Version:** 1.15 RC 1
**Platform:** Window
**Modded:** No  

### Description
Pies drop two pies when broken.
https://discord.com/channels/302152934249070593/334233095374897152/858701156577706034

### How to reproduce
1. Make a pie
2. Hit it till it breaks

### Expected behavior
One pie to drop

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/124878977-61fe0e80-dfd5-11eb-85b7-c697a5fe852d.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.2
