### ISSUE TITLE
Steel coffin graphics glitch

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1119]
**Game Version:** 1.15 RC 1
**Platform:** Windows 
**Modded:** No 

### Description
Stone Coffins and steel making in 1.15 pre.8 is 'broken' but 'working'. Notice the empty coffin, stack of charcoal and 16 iron ingots.
![image](https://user-images.githubusercontent.com/12073699/124873691-a8268400-df7b-11eb-953c-ebdb8da48be5.png)

After adding one charcoal, the layer with 4 ingots in charcoal shows. Still 16 ingots in inventory. Adding the ingots removes them from the display, but replaces them with the ones from inventory.
![image](https://user-images.githubusercontent.com/12073699/124873725-b2e11900-df7b-11eb-8009-2922799ab77b.png)

https://discord.com/channels/302152934249070593/334233095374897152/858519885638402099

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/124878751-206d6380-dfd5-11eb-8815-ad78ef614f9c.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
