### ISSUE TITLE
Treeshade does not update after tree is gone

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#112]
Shade created by having large trees does not disappear after the trees are gone - The light engine does not update the light after the trees are felled

**Comment by tyronx** [comment]
This seems to be a major problem with lighting altogether. Completely enclosing a large area with blocks, so that all sunlight access is blocked, reliably does not darken everything inside.

**Comment by tyronx** [comment]
Most likely fixed by now
