### ISSUE TITLE
blocks no longer show reinforced

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1120]
**Game Version:** 1.15 rc 1
**Platform:** Windows 
**Modded:** No 

### Description
blocks don't show when they are reinforced anymore in the block info window on top of the screen
https://discord.com/channels/302152934249070593/334233095374897152/858705551336013835

### How to reproduce
1. Reinforce a block
2. Have block info turned on
3. Look at block

### Expected behavior
Some indicator the block is reinforced.

**Comment by tyronx** [comment]
this should be fixed already

**Comment by tyronx** [comment]
in pre11 or pre12, i think

**Comment by Craluminum2413** [comment]
Yeah ![image](https://user-images.githubusercontent.com/69315569/124930300-e4082a80-e009-11eb-826b-944e82d1345d.png)

**Comment by copygirl** [comment]
Why does @sirStroam not see the reinforcement in rc.1, then?

**Comment by Craluminum2413** [comment]
He'd better send a screenshot or video about it

**Comment by radfast** [comment]
Also [Semka on Discord](https://discord.com/channels/302152934249070593/334233095374897152/862694937795756053) says it's still there in rc1

**Comment by sirStroam** [comment]
I've since upgrade to rc 2 and am no longer seeing this
