### ISSUE TITLE
Pie making not explained

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1121]
**Game Version:** 1.15 rc 1
**Platform:** Windows 
**Modded:** No 

### Description
I scoured the handbook typing in pie, crust, dough, looked at the guides, etc and had to go to discord to figure out that you needed to use a table.

### Expected behavior
A guide or something to appear when pie is searched for

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/124878116-6bd34200-dfd4-11eb-9262-6826b9119bb7.png)

**Comment by Craluminum2413** [comment]
Also no tooltips about "you can add the filling here" ![image](https://user-images.githubusercontent.com/69315569/125069172-11fb7680-e0bf-11eb-9e70-6a24ba4698e3.png), and that "you can put different fillings", as "you can add different type of dough at the top"

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in rc.3

**Comment by Craluminum2413** [comment]
Maybe would be better do also display "(Can be mixed)"
![image](https://user-images.githubusercontent.com/69315569/125506966-a1c0d385-1c16-4947-a440-999b75cc72a9.png)
