### ISSUE TITLE
Rough wooden door doesn't fall after self-destruction in creative game mode

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1124]
**Game Version:** 1.15.0-rc.1
**Platform:** Windows
**Modded:** StepUp

### Description
Rough wooden door break completely after fall if you are interacting with it in creative game mode

### How to reproduce
1. Goto a creative game mode
2. Place a rough wooden door
3. Interact with it until it break
4. It drops nothing

### Videos

https://user-images.githubusercontent.com/69315569/124935347-3e0aef00-e00e-11eb-9dfb-dc866bffc694.mp4

**Comment by radfast** [comment]
I think the best solution is to make the rough wooden door never break, in Creative Mode.  Fixed in next build.

We don't want to drop items, generally items broken in Creative Mode do not drop items.
