### ISSUE TITLE
`BlockEntityCrock` has no Sealed state in `BlockEntityShelf.CrockInfoCompact`

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1126]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
Sealed crock with meal doesn't display Sealed state when placed on the shelf

### How to reproduce
1. Get crock with meal
2. Seal it with wax/fat
3. Place it on the shelf
4. It doesn't display Sealed state

### Expected behavior
It display Sealed state, if it is sealed

### Screenshots/Videos
On the left side are sealed crocks, on the right side are unsealed crocks.
![image](https://user-images.githubusercontent.com/69315569/124960573-21c67c80-e025-11eb-88dc-6b7ac3acc925.png)

https://user-images.githubusercontent.com/69315569/124960187-bbd9f500-e024-11eb-8371-34ddda3ae994.mp4

**Comment by tyronx** [comment]
Not really a bug, just the nature of compact info - i.e. some info is omitted
