### ISSUE TITLE
Developer options

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1127]
**Game Version:** 1.15 rc 2
**Platform:** Windows  
**Modded:** No 

### Description
If you enable developer mode it prompts for confirmation. If cancel is selected it still takes you to the developer options.

### How to reproduce
1. Go to options and click the box to enable developer mode
2. click cancel

### Expected behavior
Takes you back to the previous screen with the developer option unselected.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
