### ISSUE TITLE
Ground Storage have no useful info

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1128]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
Ground Storage have no useful info about how to interact with it, but peat pile and firewood pile have, because they're not ground storage

### How to reproduce
1. Enable `Block Interaction Help`
2. Make any pile except peat and firewood ones
3. Look at the pile
4. It doesn't display needed information

### Expected behavior
Should display the same info as peat pile and firewood pile

### Videos

https://user-images.githubusercontent.com/69315569/124968052-d795c900-e02d-11eb-9a07-38525becd458.mp4

**Comment by Craluminum2413** [comment]
Maybe replace peat pile and firewood pile to Ground Storable too, like you did with all other piles

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3

**Comment by Craluminum2413** [comment]
There is an issue with peat pile. It doesn't show all info when it is full
![image](https://user-images.githubusercontent.com/69315569/125626006-8b793b34-aea5-4eba-a7a8-d7116e831644.png)

**Comment by tyronx** [comment]
thanks should be fixed in rc.4
