### ISSUE TITLE
Customized world settings field was halved in height

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1129]
**Game Version:** 1.15.0-pre.4 - 1.15.0-rc.2 
**Platform:** Windows
**Modded:** No

### Description
Customized world settings field was halved in height since `1.15.0-pre.4` version, `1.15.0-pre.3` and earlier versions are ok

#### `1.15.0-pre.4` - 1.15.0-rc-2:
![Screenshot (13)](https://user-images.githubusercontent.com/69315569/124976346-cce03180-e037-11eb-90e4-46533fbca295.png)

#### 1.15.0-pre.3:
![Screenshot (15)](https://user-images.githubusercontent.com/69315569/124977874-b6d37080-e039-11eb-8854-e40f6aecd020.png)

**Comment by copygirl** [comment]
Could this have been put in place to prevent drop-down options from going off-screen and being unselectable?

**Comment by tyronx** [comment]
no, i tried to fix sizing issues with different gui scales, seems like that didnt go well

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
