### ISSUE TITLE
While creating `BlockEntityGroundStorage` on the reinforced block it first creates an empty pile

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1131]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
If you place on a reinforced block everything that creates a `BlockEntityGroundStorage`, it will first create an `empty pile` (technically ground storage, but empty).

### How to reproduce
1. Go to the survival gamemode
2. Enable `Block info overlay`
2. Reinforce any full block
3. Place ingot, crucible etc. on the reinforced block
4. This created an empty pile, instead of immediately placing the item

### Expected behavior
You have placed an item and created a pile of one item

### Videos

https://user-images.githubusercontent.com/69315569/125083863-8d662380-e0d1-11eb-80de-6a12a45a0b06.mp4

**Comment by Craluminum2413** [comment]
Also exclusive for creative gamemode:
While creating `BlockEntityGroundStorage` on the reinforced block it will destroy the reinforcement
#### How to reproduce:
1. Go to the creative gamemode
2. Reinforce any full block
3. Place ingot, crucible etc. on the reinforced block
4. Ground Storage was created properly, but destroyed the reinforcement

https://user-images.githubusercontent.com/69315569/125085183-f732fd00-e0d2-11eb-923d-947c2a830565.mp4

**Comment by Craluminum2413** [comment]
I also want to say that the `Plumb and Square`'s tooltips are confusing.
It says that you need to right click to remove the reinforcement, that is, it contradicts the handbook
![image](https://user-images.githubusercontent.com/69315569/125085460-46792d80-e0d3-11eb-994c-780d3a6c7193.png)

**Comment by tyronx** [comment]
thanks for the reports, this should be fixed in rc.3
