### ISSUE TITLE
Heated crucibles stack, pouring stack deletes crucibles

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#1134]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
Heated crucibles are stackable if their contents are identical. Pouring the stack into a mold deletes the stack of crucibles, returning a single empty crucible.

### How to reproduce
Heat 2 or more crucibles with equal nugget content until molten
Stack heated crucibles in hotbar
Pour stack of heated crucibles into any mold
Contents of 1 crucible is transferred to mold
Stack disappears and is replaced with single empty crucible

### Expected behavior
Pour heated crucible stack:
-1 heated crucible
+1 empty crucible added to next available empty inventory slot

**Comment by copygirl** [comment]
While this could be fixed in code to not replace the entire stack, I think crucibles should probably not be stackable, also.

**Comment by tyronx** [comment]
thank you for the report, this should be fixed next release. The ones containing smelted metal will no longer stack.
