### ISSUE TITLE
White particles for some blocks

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1135]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
- `BlockEntityGroundStorage` (when falling)
- Cooking pot (when falling)

### How to reproduce
1. Place any block from the description
2. Break the block underneath
3. It falls and emits white particles

### Videos

https://user-images.githubusercontent.com/69315569/125191757-b65ef380-e24c-11eb-9d06-5b8192be0836.mp4

**Comment by tyronx** [comment]
thanks for the report, should be fixed next release

**Comment by Craluminum2413** [comment]
Pies have white particles too

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/125196402-802c6e80-e262-11eb-8360-fb021cff8180.mp4

**Comment by tyronx** [comment]
it should be fixed for all special blocks

**Comment by Craluminum2413** [comment]
Ingot molds and anvil have white particles on falling

**Comment by Craluminum2413** [comment]
Not able to reproduce with toolmold, claypot, anvil, barrel. But white particles still appear for display case and peat block
