### ISSUE TITLE
`BlockEntityGroundStorage` on breaking emits particles of North-West placed item

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1136]
**Game Version:** 1.15.0-rc.2  
**Platform:** Windows
**Modded:** No

### Description
If you place four different items in Ground Storage, then upon destruction it will emit particles of North-West placed item.
If there is no `NW` item, then `SW`.
If there is no `NW` and `SW` items, then `NE`.
Also when copying the Ground Storage, then the conditions above completely coincide.

### Expected behavior
Emits particles of all placed items

### Screenshots / Videos
![2021-07-11_16-23-40](https://user-images.githubusercontent.com/69315569/125197063-f16d2100-e264-11eb-9cd3-d1c095234e56.png)

https://user-images.githubusercontent.com/69315569/125197363-fe3e4480-e265-11eb-9745-d94a80fd1d21.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
