### ISSUE TITLE
Exiting Settings with Unspecified Keybind Renders Game Unplayable/Unexitable

### ISSUE THREAD

**Issue by egocarib** [anegostudios/VintageStory-Issues#1139]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
If you exit the controls menu while a keybind editing action is in-progress, all GUIs stop working and the game becomes unplayable.

### How to reproduce
1. Enter Settings > Controls
2. Click any keybind to begin remapping it. A question mark appears and the game waits for you to press the new keybind.
3. Instead of pressing a new keybind, exit the configuration menu by clicking Back
    - (I found you may need to try to click it a few times before it responds, or click other tabs first.)
4. Escape out of the pause menu.
5. Now, no UI-related keybinds whatsover will work anymore. You can't open inventory/Escape/etc. The game is essentially unplayable and cannot be exited except by Ctrl+Alt+Delete.

### Expected behavior
The default/previous keybind is reset if you exit the menu before specifying a new keybind. (Or the key is unbound, if unbound keys are supposed to be supported.)

**Comment by copygirl** [comment]
I thought this was the way you were "supposed" to "unbind" keys. Is there any error logged to `client-main.txt`?

**Comment by egocarib** [comment]
No, there are no relevant errors. These are the only things logged after unbinding the key. No errors when I'm trying unsuccessfully to use keybinds after exiting the menu.

client-debug.txt:
  108: 11.7.2021 10:28:34 [VerboseDebug] Back to game clicked
  109: 11.7.2021 10:28:34 [VerboseDebug] Escape menu closed
  110: 11.7.2021 10:28:47 [VerboseDebug] Received player data for playeruid KMIS4ncGzeCkZ2DN1jk0Y5Ta

client-main.txt:
  224: 11.7.2021 10:28:34 [Notification] Client pause state is now off

**Comment by sirStroam** [comment]
I confirmed but it took few tries to reproduce as it doesn't always happen.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
