### ISSUE TITLE
Can't construct gambesin armor with linen

### ISSUE THREAD

**Issue by pkwild54** [anegostudios/VintageStory-Issues#1140]
**Game Version:** 1.15.12
**Platform:** Windows 
**Modded:** Yes 

### Description
When I put the eight pieces of linen in the crafting grid to make the gambesin body armor, it doesn't generate it.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Game did not crash.  Just didn't produce the item from the linen.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment]
Cannot reproduce with `Linen (Normal stitches)`
![2021-07-11_20-05-13](https://user-images.githubusercontent.com/69315569/125203924-7109e880-e283-11eb-950e-f73b282a164c.png)
![2021-07-11_20-05-38](https://user-images.githubusercontent.com/69315569/125203927-71a27f00-e283-11eb-92f5-6593fbe21d1f.png)
![2021-07-11_20-06-05](https://user-images.githubusercontent.com/69315569/125203928-723b1580-e283-11eb-94f2-749d984c9145.png)

**Comment by copygirl** [comment]
Could it be that you were just trying to make the armor using the old recipe?

**Comment by pkwild54** [comment]
I looked it up in the handbook and used that one.  Just 8 linen, correct?

*Never approach a bull from the front, a horse from the rear or an idiot
from any direction....Unknown*
*Pamela K Wild**Cell:  903.907.1614*

**Comment by Craluminum2413** [comment]
Maybe you haven't noticed that in the middle you need to use two linen?

**Comment by pkwild54** [comment]
I did not notice that. You may close this ticket.

Sent from my Samsung Galaxy S9

Pamela K Wild
