### ISSUE TITLE
Fired pit kiln doesn't check adjacent blocks

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1143]
**Game Version:** 1.15 rc 2
**Platform:** Windows
**Modded:** No 

### Description
After pit kiln is lit, removing blocks on the side does nothing.
https://discord.com/channels/302152934249070593/334233095374897152/859173437762437160

### Expected behavior
Pit kiln to break

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/125233653-e41b5b00-e293-11eb-9110-1a59908acec9.png)

**Comment by tyronx** [comment]
it does - firing will not be successful. i think it can stay this way
