### ISSUE TITLE
Fruit press does weird things when top is broken

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1144]
**Game Version:** 1.15 rc 2
**Platform:** Windows
**Modded:** No

### Description
If fruit press is broken from the top it leaves a broken top part as a technical block on a floor. Can be placed down but without texture. Bottom part is breaking separately, but drops the whole construction.
![image](https://user-images.githubusercontent.com/12073699/125234381-740dd480-e295-11eb-99ff-168d2c5fc84e.png)

### How to reproduce
1. Make a fruit press
2. break the top

### Expected behavior
Drop fruit press or pieces

**Comment by tyronx** [comment]
because its incomplete. I'll remove it from the creative inventory
