### ISSUE TITLE
Thatch roof ridge has no recipe

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1147]
**Game Version:** 1.15 rc 2
**Platform:** Windows 
**Modded:** No 

### Description
No recipe for thatch roof ridge

**Comment by sirStroam** [comment]
https://discord.com/channels/302152934249070593/334233095374897152/859845918027022358

**Comment by Craluminum2413** [comment]
Slate roof ridge has no recipe too

**Comment by radfast** [comment]
Thanks for reporting, fixed in upcoming `rc3`.
