### ISSUE TITLE
Armor stand doesn't update

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1148]
**Game Version:** 1.15 rc 2
**Platform:** Windows
**Modded:** No

### Description
Armor stand still doesn't update when another player adds/removes armor from it
https://discord.com/channels/302152934249070593/334233095374897152/860740987835777024

### How to reproduce
1. have two people
2. Go into multiplayer server
3. Have other player add/remove armor from it

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
