### ISSUE TITLE
Pit kiln leaving raw materials when chunk unloaded on completion

### ISSUE THREAD

**Issue by bgoetschke** [anegostudios/VintageStory-Issues#1150]
**Game Version:** 1.15.0-rc.2  
**Platform:** Linux  
**Modded:** No (TOPTS)

### Description
I have 3 pit kilns in my base, 2 of them seem to work reliably. The third one only works correctly when i'm at my base when it finishes. If i'm away/offline and come back after it finishes, the raw materials are there and not the fired ones.

The affected pit kiln seems to be on a chunk border at 4504,105,7252 (7253 is a new chunk if i used the chunk wireframe correctly).

### How to reproduce
1. Since it is on TOPTS, maybe it is possible to see the problem in the server logs?

### Expected behavior
Well, fired goods of course ;)

**Comment by tyronx** [comment]
thanks for the report, this should hopefully be fixed in rc.3
