### ISSUE TITLE
Cannot get wallpapers back

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1153]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No 

### How to reproduce
1. Place a wallpaper on any block
2. Break the block
3. It didn't drop the wallpaper

### Expected behavior
You get wallpapers back, 

### Videos

https://user-images.githubusercontent.com/69315569/125440288-a07657bd-65f0-478b-8679-6fde7c15fd6e.mp4

**Comment by radfast** [comment]
This is intended behavior.  Our thinking is that the wallpaper is glued to the block, and is therefore not returnable in any usable form.  Similar for cave art.  Other decors such as carpets can be removed.  Essentially each type of decor block has a setting whether it will be returned to the player on breaking the parent block, or not.

**Comment by Craluminum2413** [comment]
I hope in the future it will be possible to create them from paper and paint, so as not to worry about such trifles as disposability

**Comment by radfast** [comment]
I think it's more likely that they will be loot items in ruins, or trader items.  Maybe eventually industrialization will provide a way for the player to make them...
