### ISSUE TITLE
Blue clay roofing tile corner (inner) uncraftable

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#1156]
**Game Version:** 1.15.0-rc.3
**Platform:** Windows
**Modded:** No

### Description
I cannot craft the **blue clay roofing tile corner (inner)**, because the recipe produces **blue shingle stairs**.

![2021-07-13_18-11-37](https://user-images.githubusercontent.com/75188277/125537329-817a8124-837a-4cfe-96f9-e187d82f8849.png)

**Comment by Craluminum2413** [comment]
Fixed in [1.15.0 (Stable)](https://www.vintagestory.at/blog.html/news/the-homesteading-update-v1150-r287/):
> Fixed: Overlapping shingle roofing blocks now properly distinguished.

![image](https://user-images.githubusercontent.com/69315569/125946233-94a37442-901d-4a38-be5d-5f3576f915a0.png)
