### ISSUE TITLE
The water blocks which are part of the reeds block do not properly simulate water

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#116]
I have a narrow canal, and after cutting grown reeds with a knife, the adjacent, unoccupied water blocks disappeared
![2018-05-25_22-38-44](https://user-images.githubusercontent.com/10406037/40571746-7c8c34e8-606c-11e8-931f-3141d3c716ac.png)
Near as I can tell, it's affecting the 'filled' water blocks that aren't 'source' water blocks from my other issue

**Comment by tyronx** [comment]
This would require a more flexible and more complete implementation of water block + other block

**Comment by tyronx** [comment]
Also cannot refill buckets

**Comment by tyronx** [comment]
Probably needs extension of the water block behavior to allow for such cases.

**Comment by Craluminum2413** [comment]
Especially noticeable when removing blocks of water with Eraser, world edit instrument
![2021-06-05_14-32-19](https://user-images.githubusercontent.com/69315569/120890359-e2160a80-c60a-11eb-9102-a11d567f2de2.png)

**Comment by Craluminum2413** [comment]
Since water is now a separate layer, this is no longer relevant
