### ISSUE TITLE
Sound level bar does nothing

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1161]
**Game Version:** 1.15 rc 3
**Platform:** Windows
**Modded:** No

### Description
The Sound Level adjuster does not seem to adjust overall sound levels. I can set it all the way to 0 and everything else is still playing. I can only turn down individual sound sources, not all of them at once.

https://discord.com/channels/302152934249070593/334233095374897152/861324189097001010

### How to reproduce
1. Go to sound settings and set first bar, sound level, to 0

### Expected behavior
For it to mute all sounds

**Comment by Craluminum2413** [comment]
works witrh master sound level in 1.20
