### ISSUE TITLE
Saw texture bug on rack

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1162]
**Game Version:** 1.15 rc 3
**Platform:** Windows 
**Modded:** No 

### Description
When you put the saw on a rack the wood part is missing two faces.

https://discord.com/channels/302152934249070593/334233095374897152/861348661425078293

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/125585290-14106849-6043-4a3d-84e2-3b5d037f078b.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
