### ISSUE TITLE
Mobs don't react on receiving damage from a player outside of their `seekingRange`

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1171]
**Game Version:** 1.15.0 (Stable)
**Platform:** Windows
**Modded:** No

### Description
If the player hits (using bows or stones) the mobs out of their `seekingRange`, then they don't react to it in any way.

### Expected behavior
\- They ~~look around and~~ run towards the player

### Videos
https://user-images.githubusercontent.com/69315569/125958692-8f86fba7-b1e9-4634-bd70-ffae170bfec6.mp4

**Comment by CookieBoy21** [comment]
Animals now react to long range attack in 1.20 so this issue can be closed.
