### ISSUE TITLE
Picking up the last bit of basalt sand with the wooden pan crashes the game

### ISSUE THREAD

**Issue by HansWoofington** [anegostudios/VintageStory-Issues#1173]
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.0 (Stable)16.07.2021 17:04:10: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockPan.OnHeldInteractStep(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   bei Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   bei _DLw29xcc4gWHWfw8Em0aOjlQATi._TFtOrZMSbYowcBNbCxzYGGi9tPB(Single )
   bei _Hx2yddcXbI4cHPSiFN8uLToeZYi._4nKLMGBXSYT0MlLMXytiZXnv1pE(Single )
   bei _Hx2yddcXbI4cHPSiFN8uLToeZYi._zuHdBQu2Ufqe6gkW2Lbew2nkMld(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _aZ2fvA6N0dSuJcMaBGoJm3sgDNM._I7uMuBrykFfyAmYcxlmGjnH5B6N(_gOZk4eLYIxYBLj6wraBWI9aAKFz , String[] )
   bei _Ftrf2yPR687y7LQA9DOeCuoEf4dA._I7uMuBrykFfyAmYcxlmGjnH5B6N(ThreadStart )
-------------------------------

just standing in the water, panning sand
Crashed the game twice so far when i picked up the last sliver of sand with the pan

**Comment by Craluminum2413** [comment]
Duplicate of #1172
