### ISSUE TITLE
Crash while panning sand

### ISSUE THREAD

**Issue by rainer-schwenkreis** [anegostudios/VintageStory-Issues#1175]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.0 (Stable)16.07.2021 18:28:11: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockPan.OnHeldInteractStep(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei Vintagestory.API.Common.CollectibleObject.OnHeldUseStep(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   bei Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   bei _DLw29xcc4gWHWfw8Em0aOjlQATi._TFtOrZMSbYowcBNbCxzYGGi9tPB(Single )
   bei _Hx2yddcXbI4cHPSiFN8uLToeZYi._4nKLMGBXSYT0MlLMXytiZXnv1pE(Single )
   bei _Hx2yddcXbI4cHPSiFN8uLToeZYi._zuHdBQu2Ufqe6gkW2Lbew2nkMld(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _aZ2fvA6N0dSuJcMaBGoJm3sgDNM._I7uMuBrykFfyAmYcxlmGjnH5B6N(_gOZk4eLYIxYBLj6wraBWI9aAKFz , String[] )
   bei _Ftrf2yPR687y7LQA9DOeCuoEf4dA._I7uMuBrykFfyAmYcxlmGjnH5B6N(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 16.07.2021 18:26:58, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.15.0.0, Zeitstempel: 0x60f15e0d
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1110, Zeitstempel: 0x4809adf2
Ausnahmecode: 0xc000041d
Fehleroffset: 0x0000000000034ed9
ID des fehlerhaften Prozesses: 0x7b8
Startzeit der fehlerhaften Anwendung: 0x01d77a536021c0d5
Pfad der fehlerhaften Anwendung: D:\Program Files\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: bb7f859b-ab1c-4add-b484-cbef2e7a583a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 16.07.2021 18:26:55, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.15.0.0, Zeitstempel: 0x60f15e0d
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1110, Zeitstempel: 0x4809adf2
Ausnahmecode: 0xc0020001
Fehleroffset: 0x0000000000034ed9
ID des fehlerhaften Prozesses: 0x7b8
Startzeit der fehlerhaften Anwendung: 0x01d77a536021c0d5
Pfad der fehlerhaften Anwendung: D:\Program Files\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 41a8b6cc-0389-46cd-968f-a0a1f8c46c0f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 16.07.2021 18:26:54, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFE23B94ED9
Stapel:
 }

**Comment by Craluminum2413** [comment]
Duplicate of #1172
