### ISSUE TITLE
Handbook entry for  stick

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1176]
**Game Version:** 1.15.0
**Platform:** Windows
**Modded:** No

### Description
Handbook for stick has duplicate entry for cycling leaves, and 5 non-cycling entries for cypress leaves.

### Screenshots
![2021-07-14_11-49-04](https://user-images.githubusercontent.com/84909583/125983132-47ea64e4-58a6-4845-96bb-f4f59729795b.png)

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/126407989-62b8539d-493e-40f6-bd46-328d84ad621f.png)
![image](https://user-images.githubusercontent.com/69315569/126408030-4b6e3bcd-7882-4be1-af49-6b0aa65fa5fb.png)
![image](https://user-images.githubusercontent.com/69315569/126408056-20ae7483-86af-40e9-83cb-62efd540f535.png)

**Comment by radfast** [comment]
Thank you, 5 x greenspire leaves now fixed.   The two main cycling leaves are different blocks - one is "branchy leaves" and one is leaves, we probably want to keep it that way even though they are visually the same, because the blocks have two different handbook pages.

**Comment by Saricane** [comment]
Yes, but ... are we supposed to get sticks by breaking non-branchy leaves ?

**Comment by Craluminum2413** [comment]
We get sticks only from breaking branchy leaves, non-branchy leaves are for seeds only

**Comment by radfast** [comment]
OK I've been able to improve the leaves a bit more: merged greenspire with regular leaves, which also means that the rotating leaves codes are offset by 1 between branchy and regular leaves, so that they look different.  I think this is going to be OK.

Also now fixed the emerald, diamond and olivine - thank you for that :)

**Comment by Craluminum2413** [comment]
attributesByType is best for gems

**Comment by radfast** [comment]
Thanks, in 1.15.3 upcoming, the low, medium, high variants of gem-bearing rocks are restored to the handbook
