### ISSUE TITLE
Schematics still show wrong behavior with some rotations

### ISSUE THREAD

**Issue by radfast** [anegostudios/VintageStory-Issues#1179]
**Game Version:** 1.14.10 and 1.15.1

### Description
See discussion on [Discord](https://discord.com/channels/302152934249070593/334233095374897152/865705230154989638).  When placing a saved schematic, while applying a rotation, it may be lifted into the air, and the rotation degrees may be incorrect.

[Screenshots showing chiseled blocks](https://discord.com/channels/302152934249070593/334233095374897152/865898443896782868) how they are, and how they should be

**Comment by Th3Dilli** [comment]
this has been fixed in recent 1.19 rc updates
