### ISSUE TITLE
sewing kit 

### ISSUE THREAD

**Issue by Sekinek** [anegostudios/VintageStory-Issues#1180]
**Game Version:** X.Y.Z  
**Platform:** Windows  
**Modded:** Yes (xlib, xskills, hud clock, stick crafting)  

its not working : 
https://i.imgur.com/mWl6T3C.png
https://i.imgur.com/5VGQ4YA.png
;/

**Comment by copygirl** [comment]
Did you pick the "Tailor" class? This recipe can only be made by that class.

**Comment by Sekinek** [comment]
Ohh okej :D

sob., 17 lip 2021, 09:58 użytkownik copygirl ***@***.***>
napisał:
