### ISSUE TITLE
Incorrect interaction hints for honeycomb + bucket

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1181]
**Game Version:** 1.15.1  
**Platform:** Windows
**Modded:** No

### Description
Tooltip for honeycomb of squeezing it in a bucket is wrong.
https://www.vintagestory.at/forums/topic/5112-squeezing-honeycomb-now-requires-crouch-shiftrmb/?tab=comments#comment-23534

### Expected behavior
Should display `Shift + Right-click` for bucket and `Right-click` for bowl (because you can use both combinations as well)

### Screenshots
![2021-07-17_13-15-49](https://user-images.githubusercontent.com/69315569/126034040-7527e185-92e6-4e53-9695-8f238f20effe.png)

**Comment by Craluminum2413** [comment]
Populated have no tooltip about that you can break them to get beeswax 
![2021-07-19_19-43-32](https://user-images.githubusercontent.com/69315569/126196549-205a10ca-d9b7-4eb3-b7ad-e4e63110dd96.png)

**Comment by tyronx** [comment]
thanks for the reports, this should be fixed in 1.15.3
