### ISSUE TITLE
Music in the Wilderness Survival playstyle doesn't play at all

### ISSUE THREAD

**Issue by GGBVanix** [anegostudios/VintageStory-Issues#1182]
**Game Version:** 1.15.1
**Platform:** Windows 
**Modded:** No 

### Description
Music in the Wilderness Survival playstyle does not play at all. This is not affected by the music frequency being set to "Sometimes" or "Very Often". Music is never played at any point in time within two in-game days. Music in the Standard and Exploration playstyles plays as expected. 

### How to reproduce
1. Create a new world on the Wilderness Survival playstyle

### Expected behavior
Music should begin playing almost immediately upon loading into the world

### Current Workaround
I select the Standard playstyle, then customize the settings to match those found in Wilderness Survival. Music begins playing almost immediately upon loading into the world.

**Comment by Craluminum2413** [comment]
#1101

**Comment by copygirl** [comment]
Will reopen the other issue.
