### ISSUE TITLE
Ladders change each other

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#1189]
**Game Version:** 1.15.1
**Platform:** Windows
**Modded:** No

### Description
Converting ladders to rope ladders and vice versa.

### How to reproduce
Ladder > rope ladder:
1. Place a **rope ladder**.
2. <code>Shift + right-click</code> on the **rope ladder** with a **ladder** in hand.
3. A **rope ladder** will appear above or below.

Rope ladder > ladder:
1. Place a **ladder**.
2. <code>Shift + right-click</code> on the **ladder** with a **rope ladder** in hand.
3. A **ladder** will appear below it. 

Using <code>shift + right-click</code> on the space _above_ or _below_ a **ladder** will place the item in hand normally.
It's only when you <code>shift + right click</code> on the **ladder** _itself_ that it misbehaves.

Also, **rope ladders** are not able to be retrieved by <code>right-click</code> if a **ladder** is directly below them. Is this a related issue or intended?

**Comment by copygirl** [comment]
This was **supposed** to be fixed: #989

**Comment by Craluminum2413** [comment]
Looks like my issue was related to placing, but this issue is about extension existing ladders

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
