### ISSUE TITLE
Spear throwing issues

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#119]
If you're standing on a ledge or pillar and try to throw your javelin at something underneath you, it will hit the block you're standing on pretty much 100% of the time

**Comment by tatsu011** [comment]
This appears to be fixed in the current dev version of the game.

**Comment by tyronx** [comment]
I didn't touch it, so this bug very likely still around.

**Comment by tatsu011** [comment]
I did some testing, and in the current dev version of the game with no changes, I've not encountered this bug.

**Comment by Balduranne** [comment]
Weird, but it seems fine in 1.5.8
