### ISSUE TITLE
Quick crafting by holding `Left-click` is very buggy

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1190]
**Game Version:** 1.15.1
**Platform:** Windows
**Modded:** No, purely vanilla bug

### Description
Quick crafting with holding `Left-click` is very horrible and pain

### How to reproduce
1. Try to craft, for example, cobblestone
2. While crafting, hold `Left-click` and distribute item along the crafting grid as quickly as you can
3. Distributed on the crafting grid in wrong way/very bad

### Expected behavior
Distributed on the crafting grid as it should (as in Minecraft)

### Videos

https://user-images.githubusercontent.com/69315569/126064495-23922fcb-58ee-40c2-855a-2266a2069060.mp4

**Comment by copygirl** [comment]
This is particularly bad on multiplayer.

**Comment by Craluminum2413** [comment]
https://youtu.be/N0rMautzFFs?t=1370

**Comment by Craluminum2413** [comment]
Fixed in [1.15.8-rc.1](https://www.vintagestory.at/blog.html/news/stable-ground-fog-patch-v1158-1159-r300/?tab=comments#:~:text=Fixed%3A%20Click%2BDrag%20distributing%20of%20items%20not%20distributing%20correctly%2C%20especially%20on%20high%20latency%20servers)
