### ISSUE TITLE
Raw bowstave doesn't dry in the open barrel

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1191]
**Game Version:** 1.15.1
**Platform:** Windows
**Modded:** No

### Description
It says "After 168 hours of open storage, dries into..." but it doesn't work for open storages. 

### How to reproduce
1. Place a barrel
2. Craft `raw long bowstave` or `raw recurve bowstave`
3. Put the bowstave into the open barrel
4. It doesn't dry

### Expected behavior
It dries in open storage

### Screenshots
Water in the barrel does nothing, so
![image](https://user-images.githubusercontent.com/69315569/126066724-a5cdb572-9181-4a19-8f22-450a6ac75900.png)

**Comment by Craluminum2413** [comment]
What storages in-game count as open?

**Comment by Grzegorz1984** [comment]
Leave it in the inventory. It will dry up. Currently there is no other why. Why would you assume it will dry in a barrel with water in it?

**Comment by Craluminum2413** [comment]
Because it doesn't matter to this thing whether the barrel is filled with water or not

**Comment by Grzegorz1984** [comment]
In my opinion it would be nice to be able to put it on tool rack. Not to run with it.

**Comment by Craluminum2413** [comment]
Or just put it on the floor like in real life

**Comment by copygirl** [comment]
Things should be able to dry in any inventory, though maybe the barrel doesn't work?

**Comment by Saricane** [comment]
I think the devs consider this as the price to pay to deserve a bow. Inventory slots are so precious.

**Comment by copygirl** [comment]
A regular chest or basket should work to dry things, too.

**Comment by Saricane** [comment]
This way, you could dry a big stack of bowstaves so you have a "fresh" one as soon as your current bow break. Ha ha, too easy, you're in a survival game  :-)

**Comment by Craluminum2413** [comment]
I just leave it here: You can dry bowstave etc. in the placed bag e.g. reed basket

**Comment by Craluminum2413** [comment]
Fixed in [1.16.4](https://www.vintagestory.at/forums/topic/6530-homesteading-part-2-combat-update-stabler-er-finetune-1164/#:~:text=Tweak%3A%20Can%20now%20dry%20items%20on%20tool%20racks%20and%20chests)
