### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1192]
**Game Version:** 1.15.1  
**Platform:** Windows
**Modded:** No

### Description
No translation variables in Crowdin for:
-The tabs' text in the character creation window ("Skin & Voice" and "Class")
-"No positive or negative traits" for the Commoner class

**Comment by Xandoria** [comment]
-The sentence "Price: {0} gears\nDemand: {1}" is in Crowdin but the translation is still in English in the game (it has been translated a long time ago).
-Same for title of the cadaver harvesting window.
-Same for title, text and buttons of the waypoint modifying window.

If I find some more, should write additonnal comments here or open a new comment?

**Comment by Xandoria** [comment]
I have got a pot with 2 portions of meal inside (red meat + cranberries). The display of the nutritious values is not translated ingame.
It is written "- Protein: 840 sat" and "- Fruit: 90 sat"

**Comment by Craluminum2413** [comment]
For what language?

**Comment by Xandoria** [comment]
French language

**Comment by Xandoria** [comment]
- The sentence "Contents:\n{0} litres of {1}" is in Crowdin but the translation is still in English in the game (it has been translated a long time ago).

**Comment by Xandoria** [comment]
- The word "Empty" (for ingot mold) is in Crowdin but the translation is still in English in the game (it has been translated a long time ago).

**Comment by Xandoria** [comment]
- The sentence "Nearby flowers: {0}\nPopulation Size: {1}" is in Crowdin but the translation is still in English in the game (it has been translated a long time ago).

**Comment by Xandoria** [comment]
Game version: 

No translation variables in Crowdin for:
- "Suitable spot for food ripening."
- "Ready to be fired. Ignite a pile of coal below each stone coffin half."
- "Environment" (character sheet)
- Months of the year (date in the character sheet)
- "World map"

Translation variable is in Crowdin but the translation is still in English in the game (it has been translated a long time ago):
- "Temperature: {0}"
- "Condition:"
- "Fertility when tilled:"
- "World map"
- "Contents: {0}x{1}"

There is something wrong with the coding of:
- "{0} with {1} lining and {2} glass panels" because my lantern displays "Blackbronze avec revêtement de Silver lining and  et panneaux de quartz"  -> "Blackbronze" is not translated (and not in Crowdin) and "Silver lining and " should be shortened to just "Silver" which is not translated (it is in Crowdin)

**Comment by daretmavi** [comment]
Game version: 1.15.6-rc.3
Language: slovak

No translation for `Screenshot ... taken` in crowdin
![obrázok](https://user-images.githubusercontent.com/47914240/134661629-fe2cad86-bccd-4053-9ead-8160b4b7c606.png)

**Comment by daretmavi** [comment]
Some text from credits are missing
![Screenshot_20211003_191837](https://user-images.githubusercontent.com/47914240/136586317-465be037-feff-4571-9060-e11a6ceedc7c.png)

**Comment by daretmavi** [comment]
One more, if you create new character:
- `Skins & Voice` and `Class` are not translated - not in crowdin

![character](https://user-images.githubusercontent.com/47914240/140314504-b828f8d8-7fc5-46d0-a193-49e5925e1b4e.png)

**Comment by daretmavi** [comment]
Pigment color is not translated.
E.g. `Carbon black`

![pigment_color](https://user-images.githubusercontent.com/47914240/140431795-7f12ea96-f4a9-4218-aa79-69f004c1a3d9.png)

**Comment by Xandoria** [comment]
The barrel window's title "Barrel" is not translated. The "Seal" button in that window is not translated.

**Comment by Xandoria** [comment]
"Pigment : Cinnabar" is not translated correctly though "Cinnabar" is in Crowdin and is translated.

**Comment by Xandoria** [comment]
When I look at the forge on the ground, the tooltip is missing some translation for "Contents:" and "Temperature:"
I did not find it in Crowdin.

**Comment by Xandoria** [comment]
![8a1abb437435123e42c067db8ec0e673](https://user-images.githubusercontent.com/26251843/144623034-cf005f36-97f0-4f6f-8b32-c471eb65afb1.png)

This screenshot is from Crowdin.
2 bugs?

**Comment by daretmavi** [comment]
I updated the status for my entries in 1.17.10
Only [new character text](https://github.com/anegostudios/VintageStory-Issues/issues/1192#issuecomment-960822633) are not implemented.

**Comment by Craluminum2413** [comment]
Are all those fixed?

**Comment by daretmavi** [comment]
Only "Members description" is not fully translated:
![obrázok](https://user-images.githubusercontent.com/47914240/232254789-b5f6ba79-0ed0-460e-8cc9-fa323a16488d.png)

**Comment by tyronx** [comment]
Thanks for the reports! I wont translate the credits page for now.
