### ISSUE TITLE
potash applied to terra preta revert farmald to high fertility

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1193]
**Game Version:** 1.15.1
**Platform:** Windows 
**Modded:** No

### Description
Terra preta is already of higher quality than High Fertility soil. So, applying potash to it should not downgrade to High Fertility. 

### How to reproduce
1. Create a Terra preta farmland
2. Apply potash

### Expected behavior
If potash cannot upgrade Terra preta, then it should not be possible to apply it.

### Screenshots
![2021-07-18_15-31-31](https://user-images.githubusercontent.com/84909583/126069517-d34d3e7c-1690-49bf-a37e-63e25e10d02d.png)

**Comment by Craluminum2413** [comment]
Isn't it high priority?

**Comment by tyronx** [comment]
thanks for the report this is only a visual issue, it does not affect the growth rates. In any case its fixed for 1.15.3
