### ISSUE TITLE
Slanted roof blue shingles texture changes when snow accumulates on them

### ISSUE THREAD

**Issue by stewoe12** [anegostudios/VintageStory-Issues#1194]
**Game Version:** 1.15.1
**Platform:** Windows 
**Modded:** Yes, but irrelevant in this case. 

### Description
When blue shingles slanted roof blocks get snow on them, their texture changes into that of fireclay shingles. 

### How to reproduce
1. Make a blue shingles slanted roof block.
2. Make sure snow falls on them. 
3. You will see that the texture of the blocks changes (other than the snow ofcourse)

![2021-07-18_19-40-59](https://user-images.githubusercontent.com/57070177/126077008-ab74552d-6d3c-4fda-85c4-698061cfc500.png)

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![2021-07-17_15-19-21](https://user-images.githubusercontent.com/57070177/126076898-dfea0be7-8c2e-4b5a-abcb-c879e590df18.png)

EDIT: I can now confirm that this is in fact happening to all clay slanted roof blocks. They all change their texture to that of fireclay. (so red, brown and blue clay change to fireclay when snowed upon)

```

**Comment by Craluminum2413** [comment]
I reproduced this

https://user-images.githubusercontent.com/69315569/126899071-22706121-f844-41a2-bdc6-53716459eb05.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release

**Comment by Saricane** [comment]
I would add that not only the color change, but the snow remains when you break the block. Ideal to build a snowy roof under the tropics.

![slr2](https://user-images.githubusercontent.com/84909583/127197489-8f201e56-2d8b-45a8-8635-021c5c4b4b1c.jpg)

**Comment by tyronx** [comment]
thanks, fixed as well
