### ISSUE TITLE
DivideByZeroException in BlockEntityMicroBlock.CreateMesh

### ISSUE THREAD

**Issue by loveandbarley** [anegostudios/VintageStory-Issues#1195]
Hello - having the following issue when I try to play from a server and the game crashes:

![image](https://user-images.githubusercontent.com/87617431/126079106-05c9b055-8e04-4760-80bb-04c1cc320e88.png)

- The issue does *not* occur when playing single player
- I was able to play as recently as last night / this morning without issue, including after the most recent update
- I tried updating to the latest .1 to resolve the issue and it didn't
- Tried restarting PC, etc,
- Will confirm server owner can do a restart to see if that helps  

Portion of the log I assume is most relevant:
**18.7.2021 14:56:00 [Fatal] Caught unhandled exception in thread 'networkproc'. Exiting game.
18.7.2021 14:56:00 [Fatal] System.DivideByZeroException: Attempted to divide by zero.**
   

More from client-main log:

18.7.2021 14:55:47 [Notification] Received server assets
18.7.2021 14:55:48 [Notification] Connected to server, downloading data...
470 kilobyte received
18.7.2021 14:55:48 [Notification] Loaded 2240 item types from server
18.7.2021 14:55:49 [Notification] Collected 1246 shapes to tesselate.
18.7.2021 14:55:49 [Notification] Composed 1 4096x2048 entities texture atlases from 167 textures (last textureid = 157)
18.7.2021 14:55:50 [Notification] Composed 1 4096x2048 items texture atlases from 1112 textures (last textureid = 158)
18.7.2021 14:55:50 [Notification] Reloaded sounds (async), now with mod assets
18.7.2021 14:55:52 [Notification] Composed 1 4096x2048 blocks texture atlases from 3308 textures (last textureid = 159)
18.7.2021 14:55:52 [Notification] Loaded 9285 block types from server
18.7.2021 14:55:52 [Notification] Color maps loaded
18.7.2021 14:55:54 [Notification] Blocks tesselated
18.7.2021 14:55:54 [Notification] Loaded Shaderprogramm for render pass instanced. 
18.7.2021 14:55:54 [Notification] Loading world map cache db...
18.7.2021 14:55:54 [Notification] Initialized Music Engine
18.7.2021 14:55:54 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
18.7.2021 14:55:55 [Notification] Server assets loaded
18.7.2021 14:55:55 [Notification] Wow, client daytime drifted off significantly from server daytime (501908.7 mins)
18.7.2021 14:55:56 [Notification] Received level finalize
18.7.2021 14:55:56 [Notification] Loaded Shaderprogramm for render pass clouds. 
18.7.2021 14:56:00 [Fatal] Caught unhandled exception in thread 'networkproc'. Exiting game.
18.7.2021 14:56:00 [Fatal] System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.GameContent.BlockEntityMicroBlock.CreateMesh(ICoreClientAPI coreClientAPI, List`1 voxelCuboids, Int32[] materials, BlockPos posForRnd)
   at Vintagestory.GameContent.BlockEntityMicroBlock.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve)
   at Vintagestory.Client.NoObf.ClientChunk.PreLoadBlockEntitiesFromPacket(_judMEzrGk2BBXJydxkBBqGcDfbeA[] blockEntities, Int32 blockEntitiesCount, ClientMain game)
   at Vintagestory.Client.NoObf.ClientWorldMap.LoadChunkFromPacket(_5ocOnepe4mFe8AThVp0N0383f4m p)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.ProcessInBackground(_VDN4c9aNSGhuso1YJUSgt1aBDX packet)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.TryReadPacket(Byte[] data, Int32 dataLength)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.NetworkProcess()
   at Vintagestory.Client.NoObf.ClientThread.Update()
   at Vintagestory.Client.NoObf.ClientThread.Process()
18.7.2021 14:56:10 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
18.7.2021 14:56:10 [Notification] Found 16 base assets in category lang
18.7.2021 14:56:10 [Notification] Found 0 base assets in category patches
18.7.2021 14:56:10 [Notification] Found 22 base assets in category config
18.7.2021 14:56:10 [Notification] Found 0 base assets in category worldproperties
18.7.2021 14:56:10 [Notification] Found 44 base assets in category sounds
18.7.2021 14:56:10 [Notification] Found 96 base assets in category shapes
18.7.2021 14:56:10 [Notification] Found 76 base assets in category shaders
18.7.2021 14:56:10 [Notification] Found 15 base assets in category shaderincludes
18.7.2021 14:56:10 [Notification] Found 125 base assets in category textures
18.7.2021 14:56:10 [Notification] Found 4 base assets in category music
18.7.2021 14:56:10 [Notification] Found 0 base assets in category dialog
18.7.2021 14:56:10 [Notification] Found 0 base assets in category compatibility
18.7.2021 14:56:10 [Notification] Found 16 base assets in category lang
18.7.2021 14:56:10 [Notification] Found 0 base assets in category patches
18.7.2021 14:56:10 [Notification] Found 22 base assets in category config
18.7.2021 14:56:10 [Notification] Found 0 base assets in category worldproperties
18.7.2021 14:56:10 [Notification] Found 44 base assets in category sounds
18.7.2021 14:56:10 [Notification] Found 96 base assets in category shapes
18.7.2021 14:56:10 [Notification] Found 76 base assets in category shaders
18.7.2021 14:56:10 [Notification] Found 15 base assets in category shaderincludes
18.7.2021 14:56:10 [Notification] Found 125 base assets in category textures
18.7.2021 14:56:10 [Notification] Found 4 base assets in category music
18.7.2021 14:56:10 [Notification] Found 0 base assets in category dialog
18.7.2021 14:56:10 [Notification] Found 0 base assets in category compatibility
18.7.2021 14:56:10 [Notification] Exiting current game to main menu, reason: client thread crash

**Comment by loveandbarley** [comment]
Note: Server restart did not resolve the problem.

**Comment by loveandbarley** [comment]
Note: Do not face this on a different public server.

**Comment by loveandbarley** [comment]
Help! :)

**Comment by copygirl** [comment]
I'll bump the priority and poke the developers. In the meantime, would it be possible for you to check if another player runs into the same issue when around the same area? (Though they might get stuck in a crash loop themselves.) Something else that would be useful would be the world + rough coordinates where this issue occurs. (Tyron generally recommends [WeTransfer](https://wetransfer.com/) to upload worlds.)

**Comment by radfast** [comment]
@loveandbarley   I think I have been able to fix this issue for the next release - but I'd be glad if can try it out to confirm.

I made a private test version of the next release for you to try.  [Download link](https://drive.google.com/file/d/1kol7PWHNLnc61eRpUm1-BLcayc7jQQwj/view?usp=sharing)   This is to be used by the player who is crashing, i.e. you - the server does not need to download anything.

The file which downloads will be named `VSSurvivalMod.dll` with today's date.  It's an update for the Survival mod, which is part of the vanilla game.  That is the only thing which needs to change.  Drag this file into your VintageStory `Mods` folder, overwriting the file with the same name which is already there.  You can ask the game to open the Mods folder for you from the main menu Mod Manager, and click on Open Mods Folder. 

If you have concerns about downloading code files from strangers on the internet - which you should! - you [can check](https://www.vintagestory.at/aboutus.html/) that I am part of the VS dev team :)

**Comment by loveandbarley** [comment]
Thanks. I'll discuss with the server owner / players but would like to avoid sending one of them into the same issue :). I'll see if the owner can TP me away from that spot since it takes a few seconds to crash.

Location: -5938, 110, 3204

**Comment by loveandbarley** [comment]
Acknowledged - trying this now.

**Comment by loveandbarley** [comment]
Hi @copygirl radfast - **this appears to have resolved the issue!**

BTW - ty for the clear reply - I found the wrong mod folder first :) so that note helped + appreciated the dev team note. 

Thanks for the help and thank you @copygirl
