### ISSUE TITLE
Reinforcement on path blocks is ignored

### ISSUE THREAD

**Issue by bgoetschke** [anegostudios/VintageStory-Issues#1196]
**Game Version:** 1.15.1 (Still a problem in 1.16.0-pre3)
**Platform:** Linux
**Modded:** No

### Description
Stone path blocks can be reinforced, but the reinforcement is not shown in the tooltip and the block can still be normally broken.

### How to reproduce
1. Place a stone path block (full, slab, stair doesn't matter)
2. Reinforce the block
3. Break the block

### Expected behavior
The reinforcement status should be shown in the tooltip and the block should not be breakable as long as it is reinforced.

**Comment by bgoetschke** [comment]
Seems also be the case for thatch/aged thatch roofing, grass and ferns. Other roofing blocks seem to work, same as flowers.

**Comment by Ragolution** [comment]
Was able to reproduce in 1.15.3. Roads & thatch rooves can't be reinforced, but they **will** consume a stone or ingot and act as if they were successfully reinforced, which can be very misleading.

**Comment by bgoetschke** [comment]
Still a problem in 1.15.8-rc1

**Comment by bgoetschke** [comment]
Still a problem in 1.16.0-pre3

**Comment by Craluminum2413** [comment]
Reproduced in 1.16.0-rc.7
