### ISSUE TITLE
"System.Exception: Invalid spawn coordinates found" on reloading freshly made world

### ISSUE THREAD

**Issue by GhostLich** [anegostudios/VintageStory-Issues#1201]
**Game Version:** 1.15.1
**Platform:** Win 10
**Modded:** No

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a new world (I uploaded a screenshot of my exact seed and world settings)
2. Load in, immediately save and exit to main menu
3. Reload the game, hopefully it'll show you the same error I was getting, which is indefinitely hanging on the error
"[Error] System.Exception: Invalid spawn coordinates found"

### Expected behavior
For my game to load.

### Screenshots

![Vintagestory_s9ksoj9joG](https://user-images.githubusercontent.com/79675610/126199433-880c9c85-3674-47a5-8de4-7722b9a63b41.png)

### Logs
```
19.7.2021 13:03:22 [Event] Launching server...
19.7.2021 13:03:22 [Event] Server v1.15.1, network v1.15.0, api v1.7.0
19.7.2021 13:03:22 [Event] Loading configuration...
19.7.2021 13:03:22 [Event] Loading assets...
19.7.2021 13:03:22 [Event] Loading save game...
19.7.2021 13:03:32 [Event] 7 metal alloys loaded
19.7.2021 13:03:32 [Event] 6 cooking recipes loaded
19.7.2021 13:03:32 [Event] 427 crafting recipes loaded from 187 files
19.7.2021 13:03:32 [Event] 197 smithing recipes loaded
19.7.2021 13:03:32 [Event] 53 clay forming recipes loaded
19.7.2021 13:03:32 [Event] 36 knapping recipes loaded
19.7.2021 13:03:32 [Event] 129 barrel recipes loaded
19.7.2021 13:03:33 [Event] Loading 7x7x12 spawn chunks...
19.7.2021 13:03:33 [Event] 0% (49 in queue)
19.7.2021 13:03:34 [Event] Begin save game ticking...
19.7.2021 13:03:34 [Event] Singleplayer Server now running!
19.7.2021 13:03:34 [Error] System.Exception: Invalid spawn coordinates found
   at Vintagestory.Server.ServerMain.EntityPosFromSpawnPos(PlayerSpawnPos playerSpawn)
   at Vintagestory.Server.ServerMain.GetSpawnPosition(String playerUID, Boolean onlyGlobalDefaultSpawn, Boolean consumeSpawn)
   at Vintagestory.Server.ServerMain.FinalizePlayerIdentification(_t6LkF11nBz0KuUOWUo0X6LP0HGA packet, ConnectedClient client, String entitlements)
   at Vintagestory.Server.ServerMain.HandlePlayerIdentification(_BmaUDLQdS8S3tsHiIyoYwbceJqZ p, ConnectedClient client)
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket)

```

**Comment by GhostLich** [comment]
I have a feeling this is related to world width/length. I made a new world with all the same settings except with the default width and length (same height as before, 384) and I can reload just fine now.

**Comment by tyronx** [comment]
Did you happen to manually edit the serverconfig.json? Particularly the spawn position in there

**Comment by GhostLich** [comment]
> 
> 
> Did you happen to manually edit the serverconfig.json? Particularly the spawn position in there

Nah, this was a single player world. I have not hosted any servers so there's no reason that would have been changed.

**Comment by tyronx** [comment]
most likely fixt
