### ISSUE TITLE
Slate rooves don't block weather particles.

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1206]
**Game Version:** 1.15.1
**Platform:** Win10
**Modded:** No

### Description
Slate rooves don't block hail particles. Possibly other precipitation types.
Edit: Snow ~~and rain~~ also pass through them.

### How to reproduce
1. Build a slate roof.
2. Don't put any blocks under it.
3. Hail passes through the block.

### Expected behavior
No hail inside my house.

### Screenshots
https://cdn.discordapp.com/attachments/334233095374897152/867436732001550366/unknown.png
https://cdn.discordapp.com/attachments/342070163417333761/867442336274972702/unknown.png

**Comment by tyronx** [comment]
Can you run the command `/we rebuildrainmap` and tell me if that fixes the issue

**Comment by Ragolution** [comment]
Snow continues to fall through rooves after running `/we rebuildrainmap`. 
As a note, this does not occur while it is raining, only while snowing or hailing. It seems like it may be treating the roof as a transparent block.

![image](https://user-images.githubusercontent.com/1075592/127219868-1a2f354a-c760-4de0-abcf-befd90bc2319.png)

**Comment by tyronx** [comment]
Thanks for the report, this should get fixed in 1.15.3 stable
