### ISSUE TITLE
Partially-filled pies don't generate correct model

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1207]
**Game Version:** 1.15.1
**Platform:** Win10
**Modded:** No

### Description
Partially filled and baked pies do not have a respective model when cut using a knife. They will instead use the base model as a fallback.

### How to reproduce
1. Make a pie with less than the full number of ingredients.
2. Bake
3. Cut the pie.

### Screenshots
https://cdn.discordapp.com/attachments/342070163417333761/867453900508758086/unknown.png

**Comment by tyronx** [comment]
oh wow, i was not aware you could bake those :D

**Comment by Craluminum2413** [comment]
You forgot to close issue
