### ISSUE TITLE
Tooltip changes width over time when hovering over a pie

### ISSUE THREAD

**Issue by bgoetschke** [anegostudios/VintageStory-Issues#1211]
**Game Version:** 1.15.1 (Still a problem in 1.16.0-pre3)
**Platform:** Linux
**Modded:** No

### Description
While hovering over a pie (or pie piece) with the mouse, the tooltip width changes. It shrinks until it reaches a certain width on GUI scale 5 and 6. It grows until it reaches a certain width on GUI scale 7. Other GUI scales not tested.

The changed tooltip width stays the same, even for other items. So once it reached the minimum width due to hovering over a pie, all toolstips are quite small and difficult to read.

### How to reproduce
1. Have a pie or piece of pie (unbaked pie is enough)
2. Hover over it with the mouse
3. Watch the tooltip width change

### Expected behavior
Tooltip should not change width.

### Screenshots
![2021-07-21_21-39-54](https://user-images.githubusercontent.com/5882564/126549826-aaddd9d2-0a81-47e8-9b03-2050cbfef381.png)

![2021-07-21_21-39-56](https://user-images.githubusercontent.com/5882564/126549869-f5475347-7883-442b-9ef9-732f2fed94b8.png)

![2021-07-21_21-40-00](https://user-images.githubusercontent.com/5882564/126549919-3e3b430c-1786-4e97-a96a-e723788b0a60.png)

![2021-07-21_21-40-05](https://user-images.githubusercontent.com/5882564/126549943-ec74b71e-0676-479c-80b1-183ddc8835a0.png)

![2021-07-21_21-40-10](https://user-images.githubusercontent.com/5882564/126549956-1ea83bd3-3e14-4c6b-93ca-dfe4a17a9246.png)

**Comment by Craluminum2413** [comment]
I wonder why these tooltips are so small and cannot be configured

**Comment by Ragolution** [comment]
in..teresting..

**Comment by bgoetschke** [comment]
Addition: Also happens with a bowl, but only if it has food or rot in it - not when it is empty.

**Comment by Craluminum2413** [comment]
I also noticed this with super long code names for items

**Comment by bgoetschke** [comment]
Still a problem in 1.16.0-pre3
