### ISSUE TITLE
Music volume attached to ambient slider and not music slider

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#1212]
Vintage Story 1.15.1
Windows
Modded (StepUp, CarryCapacity, Simple HUD Clock)

When a new music track came up in the normal rotation it's volume was attached to the ambient slider and not the music slider.

Here's a clip of the song and the sliders in use. <3
https://clips.twitch.tv/BoredBadFalconGrammarKing-K7moY5eEyjeKrvjS

**Comment by tyronx** [comment]
hi vallen, thank you for the report, this should be fixed next release 👍
