### ISSUE TITLE
When a thrown spear breaks, a second spear is also lost

### ISSUE THREAD

**Issue by cmps66** [anegostudios/VintageStory-Issues#1214]
1.15.1
Windows
Tested in unmodded Creative

### Description
When a spear is thrown and breaks, a second spear is also lost, whether it is on the hotbar or in the backpack. Does not appear to affect spears if destroyed in melee. Initially observed in Survival (modded) but tested in Creative without mods

### How to reproduce
1. Make two spears
2. Use one until it is down to 1 HP
3. Throw the spear and the second spear will also be destroyed

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
