### ISSUE TITLE
Crushed ilmenite only gives half of the original input.

### ISSUE THREAD

**Issue by eifel13** [anegostudios/VintageStory-Issues#1215]
Game Version: 1.15.1
Platform: Windows
Modded: No
Description:

I recently observed on a public multiplayer server that when placing an ilmenite chunk on an automated pulverizer will give only half of what crushed ilmenite should give out as per the handbook. As of now, I mainly found medium chunks of ilmenite when looking for it. I'm not sure for the other chunks if it is the same for them.

The first time that occured was when we speculated that someone was trolling with us but it was on claimed land.
The second time was officially observed that it did give half of what it should be when no one other than myself went to the automated pulverizer. 

Other materials like bauxite and olivine gives the exact same number of crushed items as per number of items being placed on the chest.

How to reproduce:

1. Have a basic automated pulveriser with chests for input and output.
2. Place Ilmenite chunk inside chest.
3. Come back after sometime to check the chest output.
4. Expect medium sized chunk to give 1 crushed Ilmenite.
5. Recieve only half of crushed Ilmenite.

Expected behavior:

Pulverizer should give the exact amount of crushed ilmenite based on the chunk size as per the game handbook

**Comment by Craluminum2413** [comment]
Can you describe that ilmenite chunk? What quality it has? How many you expect?

**Comment by eifel13** [comment]
If I remember correctly, it came from Granite rock with as a medium sized chunk.

When reading from the game handbook, it says that it should give a 1:1 ratio for medium sized chunk.

The first was 6.5 stacks of medium ilmenite chunk and the result was at least 3 stacks of crushed ilmenite.
The second was 3 stack of the same size and the result was 1.5 stacks of crushed ilmenite.

**Comment by Craluminum2413** [comment]
Do you have such an automated pulverizer?
![image](https://user-images.githubusercontent.com/69315569/126840230-ecde01ed-f407-4dab-ac7d-2abf1f41251e.png)

**Comment by eifel13** [comment]
There were no slabs around the hopper.
There should be no issue since other items like bauxite and olivine was also used to make crushed items.

**Comment by Craluminum2413** [comment]
I mean, do you have any blocks around hopper, not slabs

**Comment by eifel13** [comment]
no blocks around the hopper

**Comment by Craluminum2413** [comment]
This can be a problem. I advice you to always place blocks around hopper

**Comment by eifel13** [comment]
Ok I'll try that. Thank you

**Comment by Craluminum2413** [comment]
If you still get the same amount, it will be really weird

**Comment by eifel13** [comment]
It works fine now. Thank you very much
