### ISSUE TITLE
Spelling mistake - Cob (Sparse gras)

### ISSUE THREAD

**Issue by Juliusvanvern** [anegostudios/VintageStory-Issues#1216]
**Game Version:** 1.15.1  
**Platform:** Windows
**Modded:** No

### Description
Not really a bug. But a small spelling mistake. 
The letter s is missing in gras(s)

### Screenshots
![Cob](https://user-images.githubusercontent.com/1310058/126863870-d29af8e5-ad37-463e-8cb2-449f12d93c3e.JPG)

### Logs
```
Not relevant
```

**Comment by radfast** [comment]
Fixed in next build, thank you for spotting @Juliusvanvern
