### ISSUE TITLE
Slow server time progress without any player online.

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#1219]
Suggestion: possibility to set the speed of server time progress when NO one player is online.

Explanation: server with small amount of player is often off-line - no player online. In that case if you login after day or two the game is in the same state as you left it before. It's sometimes annoying. When other players play and when you login after day or two the server time is progressed less or more. So you can see your work (barrels, leather, milk, etc) progressed. Without players playing no progress. We can set the server to progress time without players. But the speed of progress is very high. After 2 days of no playing server run 2 months. It's too much. Possibility to settle it down to [1 real day no player logged in = 1 game day] or something similar would be perfect solution.

**Comment by copygirl** [comment]
Apologies. We've decided against suggestions on the issue tracker - they become too numerous and difficult to manage. Your suggestion is of course valid, and I've heard it discussed before. Please post it on the forums or Discord.
