### ISSUE TITLE
Pre 1.5 treasure generation bug

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#122]
Firewood generated in the world before the new fences were introduced drops Dirty Shirt instead
![2018-05-26_23-12-41](https://user-images.githubusercontent.com/10406037/40582155-7b0880b2-613a-11e8-8814-3fd4d73e94d5.png)

**Comment by copygirl** [comment]
I think this might be fixed now, but the items in the pile can't be changed retroactively. However, maybe every firewood pile should just be hardcoded to only drop firewood instead of being some sort of inventory?

**Comment by tyronx** [comment]
If there is not a huge outcry I would just leave the bug as it is for old worlds and not hardcode a solution that has the potential of introducing new bugs. Reopen the issue if there are objections.
