### ISSUE TITLE
Uncraftable/No recipe for Crushed Cinnabar

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1221]
**Game Version:** 1.15.2
**Platform:** Win10
**Modded:** N

### Description
Crushed Cinnabar cannot be crafted, making red dye similarly uncraftable.

### How to reproduce
1. Insert cinnabar into Pulverizer.
2. Pulverizer rejects cinnabar
*. Crushed Cinnabar in Handbook doesn't list "Crushing" as a crafting method.

### Screenshots

![image](https://user-images.githubusercontent.com/1075592/126911874-4b411285-83f6-4e79-887c-cdacc6908410.png)
![image](https://user-images.githubusercontent.com/1075592/126911917-ee441446-6874-41ed-a05f-240622524602.png)

**Comment by Craluminum2413** [comment]
The same for:
- Crushed lapis
- Crushed lead

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
