### ISSUE TITLE
Bighorn ewe doesn't provide enough milk in 1.5.x

### ISSUE THREAD

**Issue by Grzegorz1984** [anegostudios/VintageStory-Issues#1222]
**Game Version:** 1.5.2
**Platform:** Windows  
**Modded:** No 

### Description
It seems as the ewe's after preganancy has a milk only for 2-3 days and then no more.
A have a big herd with around 20 ewe's and i had 20-30 liters of milk for two days.
When i came few days later they doesn't provide any milk at all.

### How to reproduce
1. Have domesticated big horn ewe's. Let them reproduce. They stop giving milk very early. It supposed to be 20 days but
they seem to stop lactating after 2 or 3 days.

### Expected behavior
Ewe's should lactate for 20 days as it was before in 1.4.x version of the game.

### Screenshots
![2021-07-25_17-45-13](https://user-images.githubusercontent.com/7847820/126912231-a5ba66c4-23c3-4b37-b343-691608a3b17f.png)
![2021-07-25_17-45-19](https://user-images.githubusercontent.com/7847820/126912232-3688d6b6-803f-4f6b-ab9c-32e7f546e4b5.png)
![2021-07-25_17-44-53](https://user-images.githubusercontent.com/7847820/126912234-e01edcd8-65fc-4092-9c16-ff0e4f6bced4.png)
![2021-07-25_17-45-03](https://user-images.githubusercontent.com/7847820/126912236-71a978d9-8538-4dc9-84d1-14e03bf0e768.png)

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed next version. The issue was that unloading an ewe reset their lactating timer.
