### ISSUE TITLE
jump over fence when water below

### ISSUE THREAD

**Issue by JustForVS** [anegostudios/VintageStory-Issues#1223]
**Game Version:** 1.15.2  
**Platform:** Windows 10  
**Modded:** Yes (only GUI: zoombutton, VSprospectorInfo, HUD clock, automap)  

### Description
putting a water block below a fence leads to ability to jump over the fence

### How to reproduce
1. put a water block below a fence 
2. jump over the fence at this point

### Expected behavior
![001](https://user-images.githubusercontent.com/87942616/126931415-dd727469-593f-4c25-8ce3-32313d4a848e.png)
obvious

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Ragolution** [comment]
Was surprised when I was able to reproduce this. Seems to effect all fence types, with and without snow, including diagonally.

**Comment by Craluminum2413** [comment]
No longer relevant in [1.16.0-rc.7](https://www.vintagestory.at/forums/topic/6186-homesteading-part-2-7th-release-candidate-1160-rc7/#:~:text=Tweak%3A%20Experimental%20change%3A%20Fences%20are%20no%20longer%201.5%20blocks%20high%2C%20instead%20no%20creature%20can%20step%20on%20them), also I cannot reproduce this bug with animals, so it is fixed
