### ISSUE TITLE
Temporal Stability gone or ineffective?

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#1224]
Vintage Story 1.15.1
Windows
Modded Server (StepUp, CarryCapacity, Better Crates, Better Stairs, Brick Layers, More Roads, Player Corpse, Workbench Expansion)

Upon updating to 1.15.1 from 1.14.8 our base being previously a very unstable area (yes we're crazy like that) is no longer unstable. This effected the entire server now and no one is experiencing destabilization - even during storms.

**Comment by tyronx** [comment]
hey, could you DM me on discord one more time with the server address and get me to that location for me to debug please

**Comment by tyronx** [comment]
turns out a server update probably left some odd files behind
