### ISSUE TITLE
Honey use description incorrect

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1227]
**Game Version:** 1.15.2
**Platform:** Windows 
**Modded:** No 

### Description
When honey is selected it only displays right-click when you need to sneak and right click

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/127095554-296cfc2e-3129-48d0-b12d-fe0937f97aab.png)

**Comment by copygirl** [comment]
Duplicate of #1181?

**Comment by Craluminum2413** [comment]
I circled the same area in red in the screenshot in my issue

**Comment by Craluminum2413** [comment]
Yes, this is a duplicate

**Comment by tyronx** [comment]
duplicate indeed
