### ISSUE TITLE
Pulverizer does not Cruch Cinnabar

### ISSUE THREAD

**Issue by Icecubegame** [anegostudios/VintageStory-Issues#1228]
**Game Version:** 1.15.2  
**Platform:** Windows 
**Modded:** No

### Description
Cinnabar is not being crushed in the Pulverizer, even with steel pounding caps.

### How to reproduce
1. Make a Pulverizer setup with steel caps
2. Put Cinnabar into it.
3. The Pulverizer spits out the raw Cinnabar.

**Comment by Craluminum2413** [comment]
Duplicate of #1221
