### ISSUE TITLE
Redwood saplings in Planters don't rustle/sway in the wind

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1229]
**Game Version:** 1.15.2
**Platform:** Win10
**Modded:** No

### Description
Redwood saplings don't sway/rustle during wind.

### How to reproduce
1. Sprout a redwood sapling
2. Put it in a ceramic planter
3. The leaves ontop don't move

https://user-images.githubusercontent.com/1075592/127597540-fd4e4ea1-fc0a-4e6a-a9fd-38db6ace2520.mp4

**Comment by tyronx** [comment]
thanks for the report, should  be fixed next release
