### ISSUE TITLE
Broken/Outdated blocks take too long to destroy

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#123]
They should be as fast to break in Survival as hay blocks are. The current time it takes to destroy them is unacceptable

**Comment by tyronx** [comment]
Reduced default block breaking time from 6s to 2s for 1.5.5. I kinda want to avoid too easy breaking of them because they kinda are there to indicate a problem and should usually be handled by fixing the savegame / engine / mod itself. The fence unknown blocks should rather be the exception.

**Comment by copygirl** [comment]
Pickaxes seem to be faster at breaking them, too. I suppose the default material is stone..?
