### ISSUE TITLE
Honey buckets can overfill other honey buckets

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1231]
**Game Version:** 1.15.2
**Platform:** Win10
**Modded:** No

### Description
Buckets full of a fluid can be forced into another bucket, effectively giving a single bucket near-infinite capacity for the particular substance it contains.

### How to reproduce
1. Make a bucket
2. Fill it with honey
3. Make another bucket
4. Also fill it with honey.
5. Use left-click to transfer the contents of one bucket to the other.
6. The target-bucket is able to exceed its nominal limitation of 10 units/liters.

Note: This does NOT effect buckets containing water or milk.

### Expected behavior
I expected the two full buckets of honey to stack, since they're identical, bitwise.

### Screenshots
![image](https://user-images.githubusercontent.com/1075592/127600555-1c265a30-e9a2-45c4-9943-8814ad64d8b3.png)

**Comment by Craluminum2413** [comment]
No longer able to reproduce with new liquid system in 1.16
