### ISSUE TITLE
[1.15.3|Windows] Unable to place oil lamps on vertical surfaces higher than "ground+1"

### ISSUE THREAD

**Issue by BradyThe** [anegostudios/VintageStory-Issues#1234]
**Game Version:** 1.15.3
**Platform:** Windows
**Modded:** No

### Description
Since the update I am unable to place oil lamps on vertical surfaces which are not directly located above ground level. I assume that this is related to "Fixed: Able to place floating oil lamps"

### How to reproduce
1. Take an oil lamp
2. Use it on vertical surface at least two above ground level.
3. It doesn't place the oil lamp and displays the error message "Cannot place this block here. Requires a solid ground"

### Expected behaviour
The oil lamp should be mounted to the vertical surface.

### Screenshots
![20210731153713_1](https://user-images.githubusercontent.com/8181555/127741641-c4a836ad-5ed9-41de-8afc-cf93dcb7c5dc.jpg)

**Comment by Ragolution** [comment]
Was able to reproduce in 1.15.3

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
