### ISSUE TITLE
Traders wont buy clothes

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1237]
**Game Version:** 1.15.3
**Platform:** Win10
**Modded:** No

### Description
Traders will occasionally buy clothes. ~~But they refuse to buy any clothing that's TOO nice.~~

### How to reproduce
1. Find a trader buying clothes ~~at a % condition other than 100%~~
2. Get the respective shirt,~~repair it to 100%~~, condition is irrelevant
3. Trader wont buy it

### Expected behavior
~~Naturally it makes sense they wont buy any with _less_, but Traders should willingly buy clothing in better condition than specified.~~

Part of me half-remembers Tyron disabling traders buying clothes so he could fix this.

https://user-images.githubusercontent.com/1075592/127784130-71f52019-29fb-440b-bd5a-c3286ce81522.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
