### ISSUE TITLE
Freeze when creating clay oven

### ISSUE THREAD

**Issue by trezker** [anegostudios/VintageStory-Issues#1238]
**Game Version:** 1.15.2 
**Platform:** Linux (Ubuntu 20.02)  
**Modded:** Yes (
 Auto Map Markers.zip'
 hudclock-2.5.0.zip
 TranslocatorLocator_v0.1.0.zip
 vsprospectorinfo_v4.0.2.zip
 medievalexpansion-3.5.5.zip             
 xlib_v0.6.0-pre.6.zip
 MushroomMod1.0.0.zip                    
 xskills_v0.6.0-pre.7.zip
)  

### Description
Game froze right when I placed the final bit in a clay oven. No mouse pointer, couldn't alt-tab out. Had to kill mono by opening a terminal. When I try logging in again it freezes when ingame rendering starts, I see some things like my lantern but it doesn't get to rendering the world.

### How to reproduce
1. Make a clay oven
2. ...
3. It freezes the game

**Comment by Craluminum2413** [comment]
The xLib and xSkills mods are to blame

**Comment by trezker** [comment]
Yeah, with those mods unchecked it loads fine.

I have downgraded to 1.15.1 and it works fine with the mods activated in that version.

**Comment by copygirl** [comment]
Needs to be reported to mod author. Look / wait for an updated version of the mod to be released.
