### ISSUE TITLE
Oil lamps easily duplicated while falling

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1239]
**Game Version:** 1.15.3
**Platform:** Win10
**Modded:** No

### Description
Explain the issue you're running into.

### How to reproduce
1. Place an oil lamp ontop of a block
2. Break the block while aiming at the oil lamp
3. The oil lamp will break moments before falling
4. You will have X+1 as many oil lamps as you started with.

https://user-images.githubusercontent.com/1075592/127782794-3326dd0e-f44f-41df-ba7f-e7d152715a59.mp4

**Comment by tyronx** [comment]
Any mods installed? Because i cannot reproduce this

**Comment by tyronx** [comment]
thanks for the report, i'll give the oil lamp some breaking resistance, that'll fix it
