### ISSUE TITLE
Empty buckets wont stack after containing different fluids

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1240]
**Game Version:** 1.15.3
**Platform:** Win10
**Modded:** No

### Description
Buckets that were recently filled with different fluids, but are presently empty, will not stack with one another.

### How to reproduce
1. Obtain buckets
2. Fill Bucket A with Milk, Bucket B with Water and Bucket C with Honey
3. Dump them all out
4. You now have 3 buckets that will not stack.
*Workaround: Just fill+unfill all the buckets with water so they stack.

PS Im sorry for making so many of these

**Comment by Craluminum2413** [comment]
Duplicate of #862

**Comment by Ragolution** [comment]
You right.
