### ISSUE TITLE
New fences don't interact with snow correctly

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1242]
**Game Version:** 1.15.3 
**Platform:** Win10
**Modded:** No

### Description
Refer to screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/1075592/127910397-bc201a45-403b-4e92-8cc1-f19ef58585f0.png)

![image](https://user-images.githubusercontent.com/1075592/127910580-0051a158-c33e-4fcc-aed6-e00323a7b045.png)

**Comment by Craluminum2413** [comment]
I noticed the same https://github.com/anegostudios/VintageStory-Issues/issues/912#issuecomment-891043328

**Comment by Ragolution** [comment]
Why tf didn't that show up when i searched 'fence' on github SMDH
