### ISSUE TITLE
Media control keys unlocks cursor (like LAlt)

### ISSUE THREAD

**Issue by Wolf-64** [anegostudios/VintageStory-Issues#1245]
**Game Version:** 1.15.2/1.15.3
**Platform:** Linux
**Modded:** No

### Description
On keyboards with additional (media control) keys, pressing the following keys unlocks the cursor as by pressing LAlt (default):

-  VolumeUp
- VolumeDown
- VolumeMute
- MediaPlayPause
- MediaNextTrack
- MediaPreviousTrack
- LaunchMail
- BrowserHome 

And possibly a few others. In C#, the corresponding enum values of these keys are >= 128, starting from BrowserHome = 128. Knowing that, maybe it'll help solve the issue.

Tested on Linux Mint 20.2 Cinnamon (based on Ubuntu 20.04) with Mono 6.12.0.122.

**Comment by Th3Dilli** [comment]
this seems to have been fixed for some time, at least with 1.18.10 (NET7.0 update)  I can't reproduce anything similar to that
