### ISSUE TITLE
Cannot place oil lamps attached to walls.

### ISSUE THREAD

**Issue by kurazarrh** [anegostudios/VintageStory-Issues#1246]
**Game Version:** 1.15.3
**Platform:** Windows 
**Modded:** Originally discovered on modded server, but verified on singleplayer vanilla.

### Description
When attempting to place an oil lamp, it is no longer possible to place them so that they are attached to a wall. When doing so, red text at the bottom of the screen says, "This block requires solid ground."

### How to reproduce
1. Make an oil lamp.
2. Right-click a side face of a block, preferably one that is at least 2 blocks above the ground.
3. Oil lamp is not placed.

### Expected behavior
It should be possible to place oil lamps so that they are attached to the side of a block. Existing oil lamps attached to walls/sides of blocks in previous patches still exist, but cannot be re-attached once removed.

It is still possible to place oil lamps on the top of surfaces.

**Comment by Craluminum2413** [comment]
Duplicate of #1234

**Comment by kurazarrh** [comment]
> 
> 
> Duplicate of #1234

Oh, my bad. How did I miss seeing that one in the list? Time to check my eyes.
