### ISSUE TITLE
1.15.3 on Windows 10 modded game crashed very world every game

### ISSUE THREAD

**Issue by langemjenswo** [anegostudios/VintageStory-Issues#1247]
**Game Version:** X.Y.Z  
**Platform:** Windows / Mac / Linux (which?)  
**Modded:** No / Yes (which?)  

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

- [ ] [

1. 

-  @`[](url)`

](url)

**Comment by Craluminum2413** [comment]
Where is the crash?

**Comment by copygirl** [comment]
No information. Will close for now.
