### ISSUE TITLE
Long blade and axe clay mold change shape on completion

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#1248]
**Game Version:** 1.15.3
**Platform:** Windows 
**Modded:**  Yes 

### Description
When making the longblade clay mold it doesn't match the final result visually. It's kinda jarring when you complete it and it changes shape suddenly. Been around for a long time now.

### How to reproduce
1. Make a longblade clay mold from clay
2. Finish the pattern

### Expected behavior
Either the finished pattern matches the initial pattern or the reverse.
### Screenshots
![image](https://user-images.githubusercontent.com/13642054/128400634-e1727d6e-efbb-4af0-a5c7-ec04a0d052c7.png)

**Comment by copygirl** [comment]
As @VallenFrostweaver points out, this also happens with axe molds:

![](https://user-images.githubusercontent.com/13642054/128400882-0e988ea2-cb04-4516-81b6-4a846f21523a.png)

**Comment by Craluminum2413** [comment]
Second one happens with all molds

**Comment by copygirl** [comment]
@Craluminum2413 The rotation is off a lot of the time, yes, and it probably shouldn't be, but in the axe mold's case, there are some extra voxels that need to be removed which are not missing in the final mold.

**Comment by Craluminum2413** [comment]
The same for
- Helve hammer mold
- Hoe mold
- Pickaxe mold
- Prospecting pick mold
