### ISSUE TITLE
Axe clay mold changes shape on completion

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#1249]
**Game Version:** 1.15.3
**Platform:** Windows 
**Modded:**  Yes 

### Description
When making the axe clay mold it doesn't match the final result visually as it suddenly rotates upon completion. It's kinda jarring when you complete it and it changes shape suddenly. Been around for a long time now.

### How to reproduce
1. Make an axe clay mold from clay
2. Finish the pattern

### Expected behavior
Either the finished pattern matches the initial pattern or the reverse.
### Screenshots
![image](https://user-images.githubusercontent.com/13642054/128400882-0e988ea2-cb04-4516-81b6-4a846f21523a.png)

**Comment by copygirl** [comment]
Going to merge this with #1248.
