### ISSUE TITLE
Unable to craft Recurve Bow

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1254]
**Game Version:** 1.15.3
**Platform:** Windows
**Modded:** No

### Description
 I can't seem to be able to craft the Recurve Bow. I place all the required materials in the grid, but the resulting item does not appear in the bottom slot. (I did make sure that the stick is 100% dry).

![bow](https://user-images.githubusercontent.com/26251843/128602401-a662d1ed-8c25-48af-991c-62895a0320ee.png)

**Comment by Xandoria** [comment]
Edit: I just noticed right now that the bowyer trait is required.
Sorry...

**Comment by Xandoria** [comment]
May I suggest to write it bigger for stupid persons like me :p

**Comment by Craluminum2413** [comment]
I suggest highlighting this with some color like orange

**Comment by copygirl** [comment]
It happens :stuck_out_tongue:
