### ISSUE TITLE
Windmill sail has no texture

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1255]
**Game Version:** 1.15.4-rc.1
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Place a windmill rotor
2. Put the sails on
3. Texture appears for milliseconds and then disappears completely

### Videos

https://user-images.githubusercontent.com/69315569/128613312-a5b3b9ab-8cf0-4a2e-bac4-1e3f2f2d61a6.mp4

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/topic/5279-invisible-but-working-windmill-wings-1154-rc1/?tab=comments#comment-24499

**Comment by Saricane** [comment]
Confirmed.

**Comment by Craluminum2413** [comment]
Fixed in 1.15.4 (Stable)
