### ISSUE TITLE
Water blocks with reeds don't count as water (Can't refill bucket)

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#126]
Related to the farmland [issue](https://github.com/anegostudios/VintageStory-Issues/issues/109).
I was supposed to submit separate tickets for every issue so:
You cannot refill your bucket from a water block that has reeds in it. I think the game considers such blocks as either reeds or water exclusively.

**Comment by copygirl** [comment]
I'd say it's the same issue: Reed in water not behaving like water. I suppose I'll close the other issue as this one is more descriptive. Tyron can still refer to the other one.

**Comment by tyronx** [comment]
Merged with #116
