### ISSUE TITLE
An incorrectly placed door in the cellar is considered closed

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1260]
**Game Version:** 1.15.4-rc.1
**Platform:** Windows
**Modded:** No

### Description
If you place door like normal, but facing the wall then it will be considered closed (maybe the same for normal rooms)

### How to reproduce
1. Place the cellar door facing the side wall
2. Look at stored food perish speed for shelf or vessel
3. Close the door
4. Look at the same as in step 2
5. This value has changed for the worse

### Videos

https://user-images.githubusercontent.com/69315569/128614680-c45541b4-c47b-47f2-9f16-f8f0bb26e186.mp4

**Comment by Ragolution** [comment]
May be specific to 1.15.4RC1. Couldn't reproduce in 1.15.3.
