### ISSUE TITLE
Some items don't float

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1261]
**Game Version:** 1.15.4-rc.1
**Platform:** Windows
**Modded:** No

### Description
Items and blocks that don't float:
- Water lily
- Firestarter
- Henbox
- Axle
- Fruit press
- Wooden pan
- Sticks layer

### Screenshots
![2021-08-08_00-49-42](https://user-images.githubusercontent.com/69315569/128614713-115a9c1a-0c73-427a-bc05-bbbc6550eaee.png)

**Comment by Ragolution** [comment]
Easy confirm. Both items definitely do not float.

**Comment by Craluminum2413** [comment]
Update a list of items
