### ISSUE TITLE
Oven will regenerate partially-eaten pie when advancing 'doneness'

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1265]
**Game Version:** 1.15.3
**Platform:** Win10
**Modded:** No

### Description
When placed into an oven, a partially eaten or cut pie (X<1) will be restored to 1.00 servings (4 slices).
This requires the pie to advance a step, from part-cooked to cooked or from cooked to charred.

### How to reproduce
1. Create a pie.
2. Slice and eat part of it. Leave at least .01 of one slice.
3. Place the slice in the oven and allow it to advance in doneness.
4. Upon advancing, the slice of pie will have 1.00 servings, despite a slice only being 0.25 servings to begin with.

### Screenshots
![image](https://user-images.githubusercontent.com/1075592/128664033-304e99a6-fe6d-471d-b4be-e638751ce1f2.png)

Edit: This appears to only be a **visual** bug. The pie will still be consumed for an appropriate amount of nutrition on consumption.

**Comment by tyronx** [comment]
pretty sure that was fixed in 1.15.4, otherwise please reopen
