### ISSUE TITLE
Gui dissappears

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1266]
**Game Version:** 1.15.3
**Platform:** Mac  
**Modded:** No 

### Description
Whenever a block is close enough to be selected, the gui disappears.

### How to reproduce
1. Load game on mac
2. get close enough for block info to appear

### Screenshots
https://youtu.be/LrIH969ZSO8

**Comment by copygirl** [comment]
Duplicate of #983.
