### ISSUE TITLE
Minimap starts jittering if you hold down spacebar

### ISSUE THREAD

**Issue by diamondboi232** [anegostudios/VintageStory-Issues#1267]
**Game Version:** 1.15.3
**Platform:** Windows
**Modded:** No

### Description
If you hold down spacebar the minimap starts vibrating

**Comment by Craluminum2413** [comment]
[1.15.4-rc.1](https://www.vintagestory.at/forums/topic/5273-the-homesteading-update-balance-stable-patch-v1154-rc1)
> Fixed: Jumping made the map hud jitter
