### ISSUE TITLE
Pies don't leave behind rot when placed on tables/ground

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1269]
**Game Version:** 1.15.5
**Platform:** W10
**Modded:** N

### Description
Pies, raw and cooked, do not leave behind any rot when they expire while placed on the ground or another block.
Probably not specifically a bug and just an oversight.

Just to tack on, pies only yield 1 unit of Rot when they expire on a shelf, in a player inventory or an oven.

### How to reproduce
1. Place pie on ground
2. It expires
3. No rot

**Comment by Craluminum2413** [comment]
Just checked, it just pops up rot instead placing it, to make it place rot, someone should make rot ground storable
