### ISSUE TITLE
Kimberlite stones don't say  "Too soft for tools", but are

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1273]
**Game Version:** 1.15.5
**Modded:** N

### Description
Kimberlite stones aren't knappable, but lack the "Too soft for stone tools" subtext.

edit: This also applies to Scoria, Tuff, Bauxite, Suevite, Limestone, Phyllite, Halite and all three varieties of marble.

### How to reproduce
1. Get a kimberlite rock
2. no knapp

### Screenshots
![image](https://user-images.githubusercontent.com/1075592/129291250-344f7e91-065a-4b1d-9f9d-405b7f952b2c.png)
![image](https://user-images.githubusercontent.com/1075592/129291274-fff09fc0-7f19-47f8-ba45-652774b28a11.png)
![image](https://user-images.githubusercontent.com/1075592/129291517-6482c78b-eb2a-477a-9ffa-2fa3a5918aa0.png)

**Comment by tyronx** [comment]
thanks, should be fixed next release
