### ISSUE TITLE
Unable to join singleplayer world due to invalid worldconfig value

### ISSUE THREAD

**Issue by meganu1216** [anegostudios/VintageStory-Issues#1278]
**Game Version:** 1.15.5  
**Platform:** Windows
**Modded:** No

### Description
I can't start the game because it won't finish loading the world I've been playing in.
I created a new world and it started fine.

### How to reproduce
1. Load the world
2. Stops at loading screen

### Screenshots
![Vintagestory Screenshot 2021 08 17 - 14 25 12 19](https://user-images.githubusercontent.com/89061138/129668425-1d9b0281-a6df-4d50-8aa2-fb8be6f8fe38.png)

### Logs
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6997283/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6997284/server-main.txt)

**Comment by copygirl** [comment]
Here are the errors that occur:
```
// In server-main.txt:
17.8.2021 14:25:04 [Error] Exception thrown during handling event OnSaveGameLoaded: Newtonsoft.Json.JsonReaderException: Failed deserializing deposits.json: Error converting value "[2]" to type 'System.Single'. Path 'chanceMultiplier', line 3, position 27.
   場所 Vintagestory.Common.Asset.ToObject[T](JsonSerializerSettings settings)
   場所 Vintagestory.ServerMods.GenDeposits.initWorldGen(Boolean blockCallbacks)
   場所 Vintagestory.GameContent.ProPickWorkSpace.OnLoaded(ICoreAPI api)
   場所 Vintagestory.GameContent.ItemProspectingPick.<>c__DisplayClass2_0.<OnLoaded>b__1()
   場所 Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[T](ICoreAPI api, String key, CreateCachableObjectDelegate`1 onRequireCreate)
   場所 Vintagestory.GameContent.ItemProspectingPick.OnLoaded(ICoreAPI api)
   場所 Vintagestory.Server.ServerSystemBlockSimulation.OnSaveGameLoaded()
   場所 Vintagestory.API.Common.Action.Invoke()
   場所 Vintagestory.Server.ServerEventManager.TriggerSaveGameLoaded()

// In client-main.txt:
17.8.2021 14:25:05 [Fatal] Newtonsoft.Json.JsonReaderException: Failed deserializing deposits.json: Error converting value "[2]" to type 'System.Single'. Path 'chanceMultiplier', line 3, position 27.
   場所 Vintagestory.Common.Asset.ToObject[T](JsonSerializerSettings settings)
   場所 Vintagestory.ServerMods.GenDeposits.initWorldGen(Boolean blockCallbacks)
   場所 Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
   場所 Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   場所 Vintagestory.Server.ServerMain.Launch()
   場所 _q065sSmA3CNgGuKTGnlAjR4ljPw._jv5ACTxQ2zYdp9fsBzvU76QFoiQ()
```

For some reason, `deposits.json` contains a value that is `[2]` when it should likely just be `2`. Have you modified this file or used a command recently? If you used a command, it should probably show an error when you use it, rather than making it impossible to join the world again.

Now, unfortunately, I believe this data might be stored inside the `.vcdbs` which you'd have to open with a program able to view / edit SQLite databases. The [Repairing a corrupt savegame](https://wiki.vintagestory.at/index.php?title=Repairing_a_corrupt_savegame) wiki page recommends getting [sqlite](https://www.sqlite.org/download.html) tools to fix your savegame. Maybe @tyronx can jump in and tell us how to do this.

**Comment by meganu1216** [comment]
When I typed the text to change the world config in the game, I wrote [2].
Is the only way to fix it by myself using sqlite?

**Comment by copygirl** [comment]
The only other option I can think of is starting the world up in a dedicated server, since it looks like the error is only fatal on the client. Then, you can run the command again with the right value and close the server. It should then load fine in singleplayer.

**Comment by meganu1216** [comment]
I don't know how to set up an existing world on a dedicated server.
I only have one PC, so it is difficult to build a dedicated server.
Is it possible to send the relevant data to the world config and have it edited?

**Comment by copygirl** [comment]
Open your `serverconfig.json` file (which should be in `%AppData%/VintagestoryData` - you can also go to this by opening the mods folder from within the mod manager and going one folder up), and change the `SaveFileLocation` to point to your save file. Then start up `VintagestoryServer.exe` in your install directory (in `%AppData/Vintagestory` I think). This should show a command line window in which you can type the correct command once the server has started up. After, just type `/stop` to stop the server, and see if you can join the singleplayer world again?

**Comment by meganu1216** [comment]
Let's say the world I want to fix is 1, and the newly created world is 2.
When I open serverconfig.json, it contains the data for 2.
I change the item "SaveFileLocation" to 1 and save it.
When I start VinragestoryServer.exe, the window disappears with red text.
I changed the SaveFileLocation back to 2 to test it out and VintagestoryServer.exe started correctly with the world of 2.

**Comment by copygirl** [comment]
Ah okay. I was hoping it was possible to fix this way, but I suppose I was incorrect. Apologies.

**Comment by meganu1216** [comment]
Since it seems difficult to use sqlite, do I have to give up on the current situation?

**Comment by copygirl** [comment]
If you upload your world (devs recommend https://wetransfer.com/) I could have a look at it.

**Comment by meganu1216** [comment]
I sent you an email.
surfaceCopperDeposits, surfaceTinDeposits, and globalDepositSpawnRate with [].

**Comment by copygirl** [comment]
I'm not entirely sure what format these values are stored in, but it's some form of binary. I've fixed them up without changing the length since that will mess up said format, so it will now be "002" and 0.200". If that bothers you, just run the commands with the proper values (and without the `[]` this time) again. The upload will take me half an hour because of my bad internet connection.

In the meantime, I'm keeping this issue open because it's not nice to be locked out of your world like that.

Related issue: #801 - supposedly this should have been fixed?

**Comment by meganu1216** [comment]
![Vintagestory Screenshot 2021 08 18 - 03 15 46 71](https://user-images.githubusercontent.com/89061138/129779577-c1419fe0-ffe6-475a-9293-9ce13d212042.png)
![Vintagestory Screenshot 2021 08 18 - 03 22 21 26](https://user-images.githubusercontent.com/89061138/129780065-b2331433-46ac-4ab6-a566-d4667149e133.png)
I rewrote the save data, but it won't start.
There was nothing left in the logs.

**Comment by meganu1216** [comment]
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7002220/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7002221/server-main.txt)
I'm sorry, there was a log.

**Comment by copygirl** [comment]
Not sure why it's working for me but not for you.
I used "DB Browser for SQLite" to edit the file. Maybe it's a platform thing, since I'm on Linux?

![Image](https://user-images.githubusercontent.com/272586/129780617-1e7ed7e3-f9b9-45df-99d6-bba4abf64378.png)

**Comment by meganu1216** [comment]
I think I'll give up and start fresh.
Thank you for taking the time to do this for me.

**Comment by tyronx** [comment]
Sorry for the late reply. You should be able to launch the game client by temporarily deleting assets/survival/patches/globaldepositspawnrate.json

Then you can fix the value using `/worldconfig globalDepositSpawnRate 2`, restore the patch file and restart the game. 

 The next release of vintage story will now also warn users if they type in an incorrect value.
