### ISSUE TITLE
Add ability to mark behaviors as optional

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#128]
I would like to make CarryCapacity a client-side optional mod, allowing the server to install it but not having it required on the client. This is currently not possible because the behavior it adds will be sent from the server to the client, which then crashes because it can not map the behavior `Carryable` to a class.

It would be nice to mark custom behaviors optional so they would not crash the client and would simply be ignored. Of course this means the mod developer has to account for this, and needs to be aware of possible behavior desync issues.

**Comment by copygirl** [comment]
Actually the same would be useful for optional mod behavior dependencies. Say a mod wants to allow its block to be carried using CarryCapacity, it should easily be able to add the `Carryable` behavior without making it a required dependency.

**Comment by sirStroam** [comment]
Pretty sure this is already implemented. Closing
