### ISSUE TITLE
Armor and clothing don't drop after death

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1286]
**Game Version:** 1.14.x, 1.15.5 
**Platform:** Windows
**Modded:** No

### Description
If the player dies in armor and clothing, they will not drop

### How to reproduce
1. Put on armor and clothing
2. Die (`/kill` or etc)
3. Armor and clothing didn't fall

### Videos
https://user-images.githubusercontent.com/69315569/130590273-60a11613-522f-4968-bb4e-a0977e695a1e.mp4

**Comment by copygirl** [comment]
This is intentional.

**Comment by Craluminum2413** [comment]
I don't understand why
