### ISSUE TITLE
Blasted crystals drop untranslated versions of themselves

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1289]
**Game Version:** 1.15.5
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Find a geode in quartz vein / Place crystal (any)
2. Blast it with an ore blasting bomb
3. Untranslated version of any crystal that isn't `-up` is dropped

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/130839966-bdda10f4-33f6-4f8a-b4cf-55d068c6ca98.png)
![image](https://user-images.githubusercontent.com/69315569/130840939-37412c3f-351d-4e74-a2e5-e3b841a70a12.png)
![image](https://user-images.githubusercontent.com/69315569/130841063-c6a4b208-662a-4f3a-8cbc-acb6d1257c09.png)
![image](https://user-images.githubusercontent.com/69315569/130841158-ccbc61d5-63e2-4743-82d7-6fd9aab41961.png)

![image](https://user-images.githubusercontent.com/69315569/130839175-cda689f4-30b1-4c4d-9066-77dba8fa86a6.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
