### ISSUE TITLE
Spider Webs don't slow you down

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#129]
As the title says. Roads appear to speed you up. Apparently, spider webs won't slow you down because you aren't walking above them but threw them.  Liquids do so perhaps `walkspeedmultiplier` and no collision box should treat the block more like a liquid.

**Comment by Heptagon-ru** [comment]
It would be nice if with adding slowing down by spiderwebs, faster cutting them with some tool like knife would be added too.

**Comment by tyronx** [comment]
fixed in v1.9
