### ISSUE TITLE
Keyboard - diacritics

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1290]
**Game Version:** 1.15.5
**Platform:** Linux (KDE neon 20.04 5.22)
**Modded:** No

### Description
Writing diacritics  is search box.
Standard way (mostly used) to write diacritics characters (like á, é, š, ď, ...) is to use 2 keys. First is the diacritical mark (', ˇ, ...) and then the character itself (a, e, s, d, ...).

If I try it in Vintage Story, then the diacritical mark is written straightaway and it is not possible to write diacritics this way and it is not possible to search translated text this way.

### How to reproduce
1. Just open some inventory
2. And try to write e.g. `ˇ + s`
3. You don't get `š`, but `ˇs`

### Expected behavior
Writing diacritics this way should be possible.
Even better solution would be just to ignore diacritics in the search box and find all result ignoring diacritical marks. Like `a` would found `a, á, ǎ, ...`

### Screenshots
![Text-dia](https://user-images.githubusercontent.com/47914240/131081112-4a7f1d09-7884-4674-a011-0b44249a5312.png)

**Comment by daretmavi** [comment]
I tried it on Windows and it seems to be working fine.
Something is different between Windows and Linux. Even fonts are different.

**Comment by Craluminum2413** [comment]
Diacritics are now ignored, see #2559

**Comment by daretmavi** [comment]
Tested with 1.19.0 pre.4 and everything looks ok.
