### ISSUE TITLE
Lots of memory leaks issue on 1.15.5(vanilla)

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1291]
**Game Version:** 1.15.5
**Platform:** Windows 
**Modded:** No

### Description
Memory leak is happening within seconds of creating a singleplayer game.
Performance Hits

### How to reproduce
1. Enable the developper mode with everything checked. (was just to trace the leaks i was getting anyway without the dev mode/debug
2. Make a a new world in singleplayer with no mods but the 3 from the game enabled ( so vanilla)
3. Check on your logs in client-main.txt

### Expected behavior
No memory leaks.

### Logs
https://gist.github.com/Aledark789/5164eaf37299da760511b2eb3a3c6897

**Comment by tyronx** [comment]
oh, awesome, thanks. This should be fixed next release. 

The leak is in the character selector screen, and not massive. Should be limited to a few hundred kb each time you open the character seletor.
