### ISSUE TITLE
Unable to create new world after 1.15.5 update

### ISSUE THREAD

**Issue by MattNuske** [anegostudios/VintageStory-Issues#1292]
**Game Version:** 1.15.5
**Platform:** Windows
**Modded:** No

**Description:**
When creating a new single-player game, the game tries to load and then crashes just before launch.

**How to reproduce:**
1) Download - "Full Installer - 1.15.5 for Windows (354.2 MB)" from website
2) Run installer and select option to remove previous '1.14.8.0' version of the game.
3) After install complete, restart PC & launch VintageStory
4) Create a new single-player world, style=Exploration with default settings.
5) The loading screen populates with the regular text and then game blacks out 3 X while trying to launch and then crashes.

**Expected behavior:**
Should be able to create a new single player game and load a new world.

**Logs:**
[Logs_29AUG2021.zip](https://github.com/anegostudios/VintageStory-Issues/files/7072010/Logs_29AUG2021.zip)
[CrashReport_29AUG2021.txt](https://github.com/anegostudios/VintageStory-Issues/files/7072012/CrashReport_29AUG2021.txt)

**Comment by copygirl** [comment]
You say the game is not modded, but it's loading Medieval Expansion:
```
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
   at medievalexpansion.src.block.mechanical.WaterWheel.<>c.<OnLoaded>b__4_1(CollectibleObject x)
```
Disable or delete the additional mods or update them to 1.15.5.

**Comment by MattNuske** [comment]
> You say the game is not modded, but it's loading Medieval Expansion:
> 
> ```
> System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
>    at medievalexpansion.src.block.mechanical.WaterWheel.<>c.<OnLoaded>b__4_1(CollectibleObject x)
> ```
> 
> Disable or delete the additional mods or update them to 1.15.5.

@copygirl 
Thanks very much for your prompt reply on this one.
I am very sorry that I got it wrong, Your reply and response was accurate.
I have followed your advice and all is working as expected now.
Thanks again.
:-)
