### ISSUE TITLE
1.5.2.1 Weird textures (linux, singleplayer)

### ISSUE THREAD

**Issue by zkol** [anegostudios/VintageStory-Issues#13]
![2018-03-21_00-29-54](https://user-images.githubusercontent.com/37601868/37689374-dee8b75c-2ca4-11e8-8e1e-a162dc27ab02.png)
In 1.5.2.1 a couple of textures seems to be messed up, including the crosshair. Reproduced with a new generated singleplayer world (linux)

**Comment by copygirl** [comment]
What's your linux distribution, graphics card and drivers?

**Comment by tyronx** [comment]
I have a feeling it's related to the pngcrush I executed over all the pngs to get rid of the 'Incorrect sRGB profile' error

**Comment by copygirl** [comment]
@tyronx The crafting table leaves, too?

@zkol So earlier versions don't have this bug?

**Comment by tyronx** [comment]
I dunno really, but please do test

**Comment by tyronx** [comment]
Also @copygirl do you also get these issues?

**Comment by copygirl** [comment]
Game looks fine for me (and I'm quite happy about the libPNG warnings being gone).

**Comment by tyronx** [comment]
Oh ok, thats good to hear. Maybe you and @zkol could also compare the installed libPng Version?

**Comment by zkol** [comment]
```
Linux karg 4.4.0-116-lowlatency #140-Ubuntu SMP PREEMPT Mon Feb 12 22:41:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)
ii  libpng12-0:amd64    1.2.54-1ubuntu1   amd64   PNG library - runtime
ii  libpng12-0:i386     1.2.54-1ubuntu1   i386    PNG library - runtime
ii  libpng12-dev:amd64  1.2.54-1ubuntu1   amd64   PNG library - development
```

**Comment by zkol** [comment]
Updating to 1.5.2.2 did not change the problem.
Additional Info: seems that the messed up textures always change a bit, for every server restart. Here are some examples:
![2018-03-22_23-05-57](https://user-images.githubusercontent.com/37601868/37801508-30f740ee-2e27-11e8-8fc0-d31539f0431b.png)
![2018-03-22_23-06-45](https://user-images.githubusercontent.com/37601868/37801510-32d39732-2e27-11e8-96b2-92664f251934.png)
![2018-03-22_23-07-59](https://user-images.githubusercontent.com/37601868/37801512-34558656-2e27-11e8-8d5a-cb8c761c2ecc.png)
![2018-03-22_23-08-42](https://user-images.githubusercontent.com/37601868/37801516-3638f6b0-2e27-11e8-8c94-f60ac90874e4.png)
![2018-03-22_23-10-26](https://user-images.githubusercontent.com/37601868/37801518-38895b44-2e27-11e8-8623-60541643460f.png)
![2018-03-22_23-11-02](https://user-images.githubusercontent.com/37601868/37801528-409b691c-2e27-11e8-81c3-479e5b7bf284.png)
![2018-03-22_23-12-01](https://user-images.githubusercontent.com/37601868/37801534-456e196c-2e27-11e8-92ce-ba07f07058c7.png)
I like the last one very much

**Comment by tyronx** [comment]
Lol, thats too wicked. Maybe a peek into the texture atlas reveals something. Please send us the output of `.debug exptexatlas block` please. It should generate a png file where the VintageStory.exe resides.

**Comment by tyronx** [comment]
Also @zkol please try for me one more thing. Copy&Overwrite all textures from 1.5.1.6 into your 1.5.2.2 folder. Then we can identify if the engine is at fault or pngcrush

**Comment by zkol** [comment]
![blockatlas-0](https://user-images.githubusercontent.com/37601868/37849179-f788c232-2ed6-11e8-8e46-f4212bf596f1.png)
here comes the atlas

**Comment by zkol** [comment]
Ok, I'll try to patch the textures. But why not the textures from 1.5.2 - in 1.5.2 there was no texture issue. Maybe this information may help you.

**Comment by tyronx** [comment]
Oh yea, 1.5.2 is fine too then

**Comment by tyronx** [comment]
Well I did find some minor brainf*** in my code involving converting an array of pixels into a system.drawing.bitmap and back for no apparent reason, maaaaaybe that fixes something. Also should speed up start up times by 0.5 - 2 seconds \o/

**Comment by zkol** [comment]
I did the texture patch in between (with 1.5.1.6) and the issue seems to be gone.

**Comment by tyronx** [comment]
Aw. So it is the pngcrush I guess :/

**Comment by tyronx** [comment]
Confirmed to be not the engines fault. Either mono or pngcrush borks its.

**Comment by tyronx** [comment]
Reported on the mono bug tracker: https://github.com/mono/mono/issues/7821

**Comment by tyronx** [comment]
Also reverting to pre-pngcrush files until we know more about in from the mono guys.

**Comment by filipnavara** [comment]
It was fixed in libgdiplus last year (https://github.com/mono/libgdiplus/pull/47, https://github.com/mono/libgdiplus/pull/77). That library is used by Mono to implement System.Drawing and the related graphics manipulation. New enough libgdiplus+Mono should be enough to fix the issue. It is possible to avoid triggering the issue by running pngcrush with different parameters, but probably not worth the effort.

**Comment by tyronx** [comment]
Thank you! @filipnavara

**Comment by zkol** [comment]
Tested 1.5.2.4 successfully (no such texture issue). Thanks a lot!

**Comment by tyronx** [comment]
Yea but @copygirl has her error log spam back :<
Probably need to fiddle with pngcrush options to make it print no errors.

**Comment by filipnavara** [comment]
You can strip just the color profiles by running `pngcrush -rem gAMA -rem cHRM -rem iCCP -rem sRGB -noreduce -ow <files>`.

**Comment by tyronx** [comment]
Oh okay, thanks a lot @filipnavara! I'll try that out.
