### ISSUE TITLE
Crash when looking up reed basket in handbook

### ISSUE THREAD

**Issue by Cr4Shd** [anegostudios/VintageStory-Issues#1301]
Running on 64 bit Windows 10 with 8 GB RAM GForce 1060M
 
Version: v1.15.5 (Stable)16.09.2021 12:33:02: Critical error occurred
Installed Mods : Primitive Survival, ProPickMapInfo
SaveGame = Fresh World with ~30min playing.
Mode : Wilderness Survival Costumized

Ausgabe der Fehlerkonsole / Output Errorlog
```
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.ThrowHelper.ThrowKeyNotFoundException()
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Vintagestory.GameContent.BlockLootVessel.GetDropsForHandbook(ItemStack handbookStack, IPlayer forPlayer)
   bei Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   bei Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   bei Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   bei Vintagestory.API.Client.GuiElementHandbookList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   bei Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   bei Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   bei Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   bei _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
```

 
 Situation : Ich hab versucht innerhalb des InGame Wikis den Eintrag für den Bastkorb nachzulesen. 
 1 => Eintrag wird unter der englischen Bezeichnung gefunden.
 2 => Icon und Name werden korrekt angezeigt.
 3 => Das Spiel stürzt allerdings ab, sobald man auf den Eintrag klickt.
 
Konnte 2x reproduziert werden indem man einfach den Eintrag klickt. 

Situation : I tried to look after the "ReedBasket" in the Ingame Wiki
1 => Entry is found with the correct Name.
2 => Even the Icon and/or the Name is displayed correctly.
3 => Game crashes if you try to click on the Basketentry 

Tried two different times; error is reproducable, simply by clicking on the WikiEntry.

**Comment by copygirl** [comment]
Does the game also crash if you disable the mods? (Perhaps test in a new world.)

**Comment by Cr4Shd** [comment]
*Hey!*


*Jep, just checked your suggestion; same result. Tested on the same map and
also with a fresh created Map with all (thirdParty) mods disabled. *

*The errorlog looks much the same as the last, but i´ll upload it anyway. *


* Greetings Matthias*

Running on 64 bit Windows with 8 GB RAM
Version: v1.15.5 (Stable)16.09.2021 15:15:36: Critical error occurred
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel
war nicht im Wörterbuch angegeben.
   bei System.ThrowHelper.ThrowKeyNotFoundException()
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei
Vintagestory.GameContent.BlockLootVessel.GetDropsForHandbook(ItemStack
handbookStack, IPlayer forPlayer)
   bei Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot
inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1
openDetailPageFor)
   bei
Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI
capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   bei Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   bei
Vintagestory.API.Client.GuiElementHandbookList.OnMouseUpOnElement(ICoreClientAPI
api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api,
MouseEvent args)
   bei Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   bei Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   bei Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   bei Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   bei
Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object
sender, MouseButtonEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle,
WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double
frames_per_second)
   bei
_q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA
, String[] )
   bei _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart
)




Am Do., 16. Sept. 2021 um 14:57 Uhr schrieb copygirl <
***@***.***>:

**Comment by copygirl** [comment]
I can't reproduce this crash in my game, nor with the mods you mentioned. (Though I could not find ProPickMapInfo, installed ProspectorInfo instead.) I feel like I've seen a similar error before but I could not find a related issue.

**Comment by Cr4Shd** [comment]
Oops... you are totally right.. ; Mods are PrimitiveSurvival and
*ProspectorInfo*.

*Error is not repro. at my Homestation, though i got the exact same
GameVersion and Mods.*

Seems like its only on my Laptop. Reinstalled it for the second time now
(LapTop), still got the error with and without mods.
If i can figure out whats causing this, i´ll send you a mail. Start to
think that my Laptop is the problem.

Thanks for the fast answers by the way!









Am Do., 16. Sept. 2021 um 15:32 Uhr schrieb copygirl <
***@***.***>:

**Comment by copygirl** [comment]
Maybe I remember. I think the updater had or has problems deleting files that are not necessary in the game any longer. Could you simply try running the full installer for 1.15.5 again?

**Comment by Cr4Shd** [comment]
Check!

*Installed fresh from 1.15.5 Installer and works just fine now!*

*Thanks for the support!*

Friendly Regards
Matthias :)

Am Do., 16. Sept. 2021 um 17:58 Uhr schrieb copygirl <
***@***.***>:

**Comment by copygirl** [comment]
Thanks for refreshing my memory! Enjoy the game!
