### ISSUE TITLE
Panning bone blocks in water will stop water flow.

### ISSUE THREAD

**Issue by YewYew** [anegostudios/VintageStory-Issues#1305]
**Game Version:** 1.15.5  
**Platform:** Windows
**Modded:** No

### Description
Fully panning a bone block in water won't update the water around it, leaving an air pocket.

### How to reproduce
1. Place a bone block in water.
2. Pan the bone block until it disappears.
3. There shall now be a spot where water doesn't flow.

### Expected behavior
Water should flow where the bone block once was.

### Screenshots
![image](https://user-images.githubusercontent.com/25268005/133896668-b6da1086-f8e2-4e54-8767-36f1bff71167.png)

### Logs
N/A

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next update
