### ISSUE TITLE
Larch fence texture is the same as birch

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1307]
**Game Version:** 1.15.x
**Platform:** Windows
**Modded:** No

### Description
In `\block\wood\debarked` larch has the same texture as birch

### Screenshot
On the left is larch, on the right is birch.
![2021-09-19_11-54-08](https://user-images.githubusercontent.com/69315569/133921498-6319db1e-9ea7-41f8-bf86-0e7f5436a849.png)

**Comment by tyronx** [comment]
thanks for the report, this is now fixed for next release
