### ISSUE TITLE
IndexOutOfRangeException in Entity.OnCollideWithLiquid

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1309]
**Game Version:** 1.15.6-RC2
**Platform:** Windows 
**Modded:** No

### Description
Crash when doing nothing special (just existing a shallow cave). Here's the log.

>Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6-rc.2 (Unstable)19/09/2021 13:28:54: Critical error occurred
System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   à Vintagestory.API.Common.Entities.Entity.OnCollideWithLiquid()
   à Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt)
   à Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)
   à Vintagestory.GameContent.EntityBehaviorControlledPhysics.GameTick(Entity entity, Single dt)
   à Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)
   à Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   à Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   à Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   à Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   à _5PLCV9nT6lKYshnvhcLKYmPbSv2._SDEctPLMGfsOebRp3QVxVEQCiUh(Single )
   à _DXJNEmwVJN2e1mVFBQ5fTNR95yc._aLrho8PYHXGJeKPDayUCeRClMEf(Single )
   à _DXJNEmwVJN2e1mVFBQ5fTNR95yc._fFzUEjicM6tZAbcIuKZDCkHSfMJ(Single )
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   à OpenTK.GameWindow.DispatchRenderFrame()
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   à _tWK3XnqdKwEz32DZgEFtVG3UU4k._ZGFqinpvIwFTz7F68DuIhzHOWm(_0yeWQ9WAjs9sBw2gtkuglYTlTmO , String[] )
   à _O6YHJJOUkiLLqUHLpLxBur1CoDP._ZGFqinpvIwFTz7F68DuIhzHOWm(ThreadStart )
-------------------------------
>Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 31/07/2021 16:16:32, Site = , Source = Application Hang, Message = Le programme Vintagestory.exe version 1.15.3.0 a cessé d'interagir avec Windows et a été fermé. Pour voir si plus d'informations sur le problème sont disponibles, vérifiez l'historique des problèmes dans le Panneau de configuration Sécurité et maintenance.
ID de processus : 1f08
Heure de début : 01d7860fc9a24d20
Heure d'arrêt : 19
Chemin d'accès à l'application : C:\Users\vg\Vs15\Vintagestory.exe
ID de rapport : 69acf594-f147-49d8-885b-291586ba1669
Nom complet du package défectueux : 
ID de l'application relative à un package défectueux : 
Type de blocage : Unknown
 }
--------------
>{ TimeGenerated = 31/07/2021 14:08:02, Site = , Source = Application Hang, Message = Le programme Vintagestory.exe version 1.15.3.0 a cessé d'interagir avec Windows et a été fermé. Pour voir si plus d'informations sur le problème sont disponibles, vérifiez l'historique des problèmes dans le Panneau de configuration Sécurité et maintenance.
ID de processus : 1d28
Heure de début : 01d785f518741acd
Heure d'arrêt : 6
Chemin d'accès à l'application : C:\Users\vg\Vs15\Vintagestory.exe
ID de rapport : af97701e-3b77-4e5b-adf2-86118dd5ee91
Nom complet du package défectueux : 
ID de l'application relative à un package défectueux : 
Type de blocage : Unknown
 }>

**Comment by Trexdude** [comment]
I have this issue too, running on 64 bit Windows 7 with 16 GB RAM, same event log seemingly.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.3
