### ISSUE TITLE
Freezes on trying to put new item from creative menu into filled hotbar

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1311]
**Game Version:** 1.15.6-rc.2  
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Open a creative menu
2. Fill hotbar completely with something
3. Try to put new item into filled hotbar with `Shift + Right-click` on the item **from creative inventory**
4. It freezes for a couple of seconds

### Video
https://user-images.githubusercontent.com/69315569/133927293-150beb6c-42bf-45a1-9886-ae2890682fa1.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
