### ISSUE TITLE
Knaping voxel grid is invisible

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1318]
**Game Version:** v1.15.6-rc.3
**Platform:** Windows 10
**Modded:** No

### Description
Trying to knap a flint axe blade is impossible because the knapping grid is invisible.

### How to reproduce
1. Use a flint on a low quality soil block
2. Green grid does not appear, though it seems the voxel are there when I move my cursor

**Comment by JustForVS** [comment]
Can reproduce this with different types of stone placed on soil or stone blocks.
It's still possible to craft the item blind.

**Comment by Trexdude** [comment]
I'm not sure if this is a related issue and/or if it's simply a visual bug but sometimes when you're knapping the invisible voxels it'll take two knaps to clear out a single voxel, I don't know if this is purely visual or not.

**Comment by multicody10** [comment]
This is happening to me as well. Happens on all blocks as far as I can tell. I've only tried to knap with flint as well.

**Comment by daretmavi** [comment]
The same on Linux (KDE neon 20.04 5.22)

**Comment by tyronx** [comment]
thanks, this is fixed in stable 👍
