### ISSUE TITLE
Kiln items disappearing after firing

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1319]
**Game Version:** 1.15.5
**Platform:** Windows 
**Modded:**  Yes 

### Description
Modded local client work properly with mods and kiln make fired clay, but on server it firing items to nothing.

### How to reproduce
1. start server and login to it
2. make kiln with clay items (vanilla or modded)
3. wait until it will disappear.  Sometimes some clients see kiln unfired when it on fire.

### Expected behavior
It must make fired clay items

**Comment by dann1kid** [comment]
> This was supposed to have been fixed. See #1065. Not sure why the issue is back.

Same client and server behaviours different. I can record a video to show it.

**Comment by copygirl** [comment]
Why was this closed?
