### ISSUE TITLE
Mono 4.x / 5.x still has png loading issues?

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#132]
At least one player (Eloraam) has issues with glitchy graphics on linux/mono

Presumably caused by pngcrush on all png files to remove the incorrect srgb profile to prevent the error log spam, this issue (#13) was supposed to be fixed by only removing the srgb profile without optimizing the png. 

For Eloraam Mono 5.4.1.16 still has broken graphics on the main menu / home screen.

**Comment by tyronx** [comment]
is this still happening?

**Comment by copygirl** [comment]
Wasn't this related to the particular Mono / libgdiplus versions a player was using?

**Comment by tyronx** [comment]
¯\_(ツ)_/¯

**Comment by Th3Dilli** [comment]
we are currently a t mono 6 which seems not to have this issue.

and soon we will only have net7 where I have not heard of any such complains
