### ISSUE TITLE
Update dialog - not translation friendly

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1327]
**Game Version:** 1.15.6-rc.3
**Platform:** Linux (KDE neon 20.04 5.22 )
**Modded:** No

### Description
Update dialog is not "translation friendly" - `No, Ignore` can be longer than english version is - the button overaps the yes-button - see picture
I changed the crowdin translation to just `Ignore` = `Ignoruj`, but this is not the full translation.

### How to reproduce
1. Open older save game and see the dialog in slovak language (in 1.15.6-rc.3)

### Expected behavior
`No, Ignore` should be aligned to right.

### Screenshots
![obrázok](https://user-images.githubusercontent.com/47914240/134659995-cd583b7f-1bf7-4f69-9f75-2cf4c847d7da.png)

**Comment by Craluminum2413** [comment]
Closed in favor of #4086
