### ISSUE TITLE
Japanese text in the menu is not displayed

### ISSUE THREAD

**Issue by kengo700** [anegostudios/VintageStory-Issues#1328]
**Game Version:** 1.15.6
**Platform:** Windows
**Modded:** No

### Description
Japanese text in the menu is garbled and not displayed. It seems that the Japanese font is not implemented.

### How to reproduce
1. Launch the game
2. Change the language setting to Japanese

### Expected behavior
Japanese text in the menu should be displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/17540972/134755088-20868c4a-ef51-43ca-83b1-a4869c7fdb3e.png)

**Comment by kengo700** [comment]
If you edit the clientsettings.json file, you will see the Japanese text correctly.
![image](https://user-images.githubusercontent.com/17540972/134755267-962cfe40-1e40-455e-8f21-4514c6d1c508.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed for next release
