### ISSUE TITLE
Japanese text is not line breaking

### ISSUE THREAD

**Issue by kengo700** [anegostudios/VintageStory-Issues#1329]
**Game Version:** 1.15.6
**Platform:** Windows
**Modded:** No

### Description
There are no spaces in Japanese text, so text will not be line broken.

### How to reproduce
1. Launch the game
2. Change the language setting to Japanese

### Expected behavior
Japanese text should be line broken.

### Screenshots
![image](https://user-images.githubusercontent.com/17540972/134755524-bfb62767-cb35-4fc1-bea8-e2325fc706ea.png)

**Comment by tyronx** [comment]
Hm. This seems to cause linebreaks inside buttons. I'll have to look at that issue seperatly

**Comment by Spoonail-Iroiro** [comment]
So... now Japanese texts have white spaces between every character?

![20211109063505_1](https://user-images.githubusercontent.com/38171201/140822015-9e678326-2752-43b6-9d6a-911a34fb22e8.jpg)

It doesn't look fine and looks buggy...
Some GUI actually truncate texts.
For example, "草（少し草深い）" only shows "草（少し") in the screenshot below.

![20211109063812_1](https://user-images.githubusercontent.com/38171201/140822301-0df317fb-18c4-4843-927f-a89f857129c6.jpg)

The handbook page title is also truncated, so in the screenshot below, "クラフトメカニクス"s (Crafting Mechanic) and "ゲームメカニクス"s (Game Mechanic) don't show their own specific topics (clay forming, farming, etc.)

![image](https://user-images.githubusercontent.com/38171201/140823013-b17855e6-113a-43d9-b80d-6438d0377157.png)


If it's not planned to implement auto line breaking not based on white spaces for now, I think it's better to line break by translated text (`\n` or `</br>`), same as 1.15.7 or former did.

**Comment by tyronx** [comment]
Whoops, sorry about that. I was not sure if its a quirk of the font or an actual bug in the game. Fixed it now, which also fixed the button issue \o/
Thanks for the report, will be in the next release.

<img width="667" alt="jap" src="https://user-images.githubusercontent.com/762006/140877486-6ede96b9-2390-41b4-b54a-20cd26f1a777.png">

**Comment by tyronx** [comment]
If there's more problems with it, please reopen

**Comment by tyronx** [comment]
Note to myself: https://github.com/adah1972/libunibreak
