### ISSUE TITLE
seraph glow at night even though i did not respawn 

### ISSUE THREAD

**Issue by OrphanWaffle** [anegostudios/VintageStory-Issues#1331]
i was just fighting some drifters and i started glowing, one time i was in the house at night, clay molding and started glowing for no reason

**Comment by Ragolution** [comment]
Have been able to reproduce this a number of times. My best guess is it has something to do with updates to body temperature dealing 0 damage, since it seems to only happen in winter.

**Comment by tyronx** [comment]
this should be fixed in 1.15.7, if not, please reopen
