### ISSUE TITLE
Placing multiple crocks(fired) on ground storage

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1333]
**Game Version:** 1 15.6
**Platform:** Windows
**Modded:** no

### Description
You can place 4 raw crocks(not fired) on ground storage but only one fired one(empty) per block...

### Expected behavior
Being able to place 4 fired crocks on ground, even better if they can contain food too

**Comment by Craluminum2413** [comment]
This is intended

**Comment by Craluminum2413** [comment]
Fixed in 1.16

**Comment by Craluminum2413** [comment]
Issue should be closed
