### ISSUE TITLE
Add color customization for voxel borders outlines when chiseling/ use opposite negative color for block outlines

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1334]
**Game Version:** 1.15.6
**Platform:** Windows
**Modded:** yes

### Description
When chiseling dark blocks such as obsidian polished or even basalt i wish the color of outlines of voxels would be white or color or my choosing. Even better if game knows that x block is dark it would choose a light color while if block is light it choose a dark color.

Would also be nice for when i hover my tera petra fields the outline of the block is black so i cant see well and gotta concentrate on what visor points.

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by copygirl** [comment]
This is a good suggestion, but it is a suggestion. This issue tracker is for issues only. Apologies.
