### ISSUE TITLE
Add mining backpack and linen backpack as models on seraph back

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1335]
**Game Version:** 1.15.6
**Platform:** Windows
**Modded:** No

### Description
Linen bag and mining bag dont have a model on seraphs backs.

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by copygirl** [comment]
Same as with the other issue. No suggestions on the issue tracker. (They got too numerous.)
