### ISSUE TITLE
Placing an ingot on ground sometimes results in empty ingot pile

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#134]
Not quite sure about how to reproduce it, but it definitely happened often enough to be noticable. Breaking the block underneath, getting the ingot back and retrying usually works.

**Comment by tyronx** [comment]
Is the 1 voxel thick hitbox still visible?

**Comment by copygirl** [comment]
Looks like the first time you join a world, the model for a single ingot is invisible but still interactable. Once you add a second ingot to any pile suddenly renders all the other 1 ingot piles?

This seems to be different from the other times I experienced a similar issue where the ingot pile was not interactable with at all and I **had** to break the block below.

**Comment by tatsu011** [comment]
Does this issue still occur?

**Comment by tyronx** [comment]
Oh yea, this should be fixed!
