### ISSUE TITLE
Berry Bushes don't grow 

### ISSUE THREAD

**Issue by Vapervop** [anegostudios/VintageStory-Issues#1345]
**Game Version:** 1.15.6
**Platform:** Windows
**Modded:** No 

### Description
Berry bushes constantly show "Will Flower in 4 Days, weather permitting." I am near the equator (Hot Climate) temperature 32 °C. They are supposed to grow in these condition since winter doesn't exist here.

### How to reproduce
1. Go near the equator
2. Place some Barry Bushes
3. It keeps saying: "Will Flower in 4 Days, weather permitting." also if sveral days passed.

### Expected behavior
Berry Bushes should flower.

**Comment by Craluminum2413** [comment]
As `assets\survival\blocktypes\plant\bigberrybush.json` file says me:
```json
resetBelowTemperature: -2,
stopBelowTemperature: 4,
revertBlockBelowTemperature: -4,

resetAboveTemperature: 35,
stopAboveTemperature: 30,
revertBlockAboveTemperature: 38,
```

**Comment by copygirl** [comment]
Sounds like berry bushes not being to survive too hot temperatures is intended. Closing.
