### ISSUE TITLE
Helvehammers can't create scales or chain anymore

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1352]
**Game Version:** 1.15.6
**Platform:** Win10
**Modded:** No

### Description
Helve hammers have lost their ability to produce Scale + Chain.

### How to reproduce
1. Obtain a plate, heat it up, any material
2. Slap it on the Helve and pick your recipes (chain or plate)
3. It just sits there. Menacingly!

### Expected behavior
This could be a case of the Mandella/Berenstain effect, but Helve hammers used to be able to produce scales from plates. They're no longer able to do so, as of the current Stable revision. I vividly remember making scale armor using a helve hammer but was unable to find the changelog notes for when it was added.

**Comment by Craluminum2413** [comment]
I sure they weren't be able to create scales and chain even in earlier versions

**Comment by Ragolution** [comment]
It was scales specifically. Chain, I'm not certain of, but I remember using a Helve to make scales back before steel was added.

**Comment by copygirl** [comment]
Have you played with mods before? From what I know, in Vanilla the helve hammer can only do ingots from blooms, and plates.

**Comment by Ragolution** [comment]
> Have you played with mods before? From what I know, in Vanilla the helve hammer can only do ingots from blooms, and plates.

I've only ever played Vanilla.
