### ISSUE TITLE
Farmland permanent fertility boosters can be applied multiple times

### ISSUE THREAD

**Issue by Barhandar** [anegostudios/VintageStory-Issues#1359]
**Game Version:** 1.15.7
**Platform:** Windows
**Modded:** No

### Description
Fertility boosters (currently only potash, +15% K) can be applied multiple times. The code in BlockEntityFarmland checks for whether the booster is in a list of boosts, but does not add used booster to said list.

### How to reproduce
1. Get potash.
2. Apply it to barren/low fertility farmland several times.
3. Watch as it progressively visually changes into higher fertility farmlands because K fertility keeps getting bumped by 15% every application, hence increasing the average. Alternately, use debug tools to see BlockEntity data, with originalFertility increasing every time and PermaBoosts staying empty.

**Comment by tyronx** [comment]
oh wow, epic fail. I fixed a bug with this in 1.15.6. Turns out it has yet another bug.

Thanks for the report, this will be fixed next release.
