### ISSUE TITLE
Lanterns with colored glass eventually lose the colored light

### ISSUE THREAD

**Issue by Barhandar** [anegostudios/VintageStory-Issues#1360]
**Game Version:** 1.15.7  
**Platform:** Windows
**Modded:** No

### Description
Colored-glass lanterns emit colored light once placed, but after a while reset to default (yellowish) light. Not all of them reset at the same time, and I have not been able to identify the specific condition for the reset, but eventually they all lost the light color.  
The lanterns start emitting the correct light again if picked up and replaced. They do not lose other data (material, lining, glass type).

### How to reproduce
1. Make a lantern with colored glass.
2. Place it in world, observe light color matching the glass.
3. Wait, doing other things including quitting and re-entering world, and moving away outside chunkload range.
4. Observe that the light color has reset. You might need to refresh the light data by placing and removing a light, including another lantern of the same color.

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed no later than 1.16.

The problem was that the server did not do update the light source. You can work around the problem in creative middle - middle mouse click the colored lantern, break the placed one, then place the colored one from your inventory
