### ISSUE TITLE
(visual) hair clipping with Leather helmet

### ISSUE THREAD

**Issue by SodoPlex** [anegostudios/VintageStory-Issues#1362]
**Game Version:** 15.7
**Platform:** Windows
**Modded:** No

### Description
when wearing Leather helmet, the hair will begin to clip through the front and back sides

### How to reproduce
1. Make a leather helmet
2. wear it

### Expected behavior
hair doesnt clip in and out of existence

### Screenshots
https://i.imgur.com/TbRZNjL.png

### Logs
```
not needed
```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
