### ISSUE TITLE
water does not extinguish pit-kiln fire

### ISSUE THREAD

**Issue by Konfuz** [anegostudios/VintageStory-Issues#1366]
**Game Version:** v1.15.7 (Stable)
**Platform:** Linux (Manjaro)
**Modded:** Only clientside, server unknown but unlikely.

### Description
Water does not extinguish pit-kiln

### How to reproduce
1. Make a Pit-Kiln
2. ignite it
3. place a water source above it
### Expected behavior
water should extinguish pit-kiln same way as rain does. 
### Screenshots
![2021-10-20_16-38-22](https://user-images.githubusercontent.com/11818151/138115930-aa1acfc6-3e1c-44d6-aea1-511bfdf60c7e.png)

**Comment by Craluminum2413** [comment]
Since 1.17 you can even create pit kilns underwater and light them with firestarter
