### ISSUE TITLE
First item in the creative inventory can't be removed in empty area until get a full stack size

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1370]
**Game Version:** 1.15.7
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Open the creative inventory (for example, `Creatures` tab)
2. Take the first item and try to remove it in empty area
3. It isn't removed

### Videos

https://user-images.githubusercontent.com/69315569/138506754-6f186b3d-887b-454b-8ddf-a83a389de62b.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
