### ISSUE TITLE
Handbook: Wrong `excludebytype` for fireclay chimneys

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1371]
**Game Version:** 1.15.7  
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Open handbook
2. Search for `clay brick chimney`
3. `Fireclay brick chimney` is not showing

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/138507167-96d922f8-51ea-4485-b83e-87461a7bc434.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
