### ISSUE TITLE
Missing paintings and odd % choice(prey, underwater vs their real rarity) for Painting randomizer for Ruins loot

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1376]
**Game Version:** 1.15.7
**Platform:** Window
**Modded:** No

### How to reproduce
Go in creative and check special then painting randomizer odds and list.

### Expected behavior
Option A) Either remove the old paintings such as elk, howl, forest dawn, prey, underwater because they all sold by traders....
Prey and underwater shouldnt have rare odds...they can be bought super cheap from traders.
Also its missing all the new paintings of 1.15 if you wanna keep all paintings.
Remove quartz chunk from the painting randomizer.
Redistribute the % across all paintings while keeping Sleeping wolf, fish and the rain, old village and last day rare %

### Screenshots
![2021-09-23_10-48-38](https://user-images.githubusercontent.com/31166271/138766281-068664d6-5753-42ce-ace7-3b39e7d93d55.png)

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed in 1.16
