### ISSUE TITLE
Missing texture for bottom part of Metorite chain leg armor

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1378]
**Game Version:** 1.15.7
**Platform:** Windows 
**Modded:** No

Missing texture/model for bottom part of Metorite chain leg armor

### Screenshot
![2021-10-07_22-34-58](https://user-images.githubusercontent.com/31166271/138766812-8000d972-3d83-44cf-b8da-c3cf0ecabf40.png)
s

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
