### ISSUE TITLE
Crash in SystemSoundEngine.OnGameTick100ms in existing save

### ISSUE THREAD

**Issue by Mrsfoxy** [anegostudios/VintageStory-Issues#1379]
**Game Version:** 1.15.7  
**Platform:** Windows  
**Modded:** Yes (AnvilMetalRecovery_V0.1.15_Release, CarryCapacity-VS1.15.6-v0.6.3, hudclock-2.5.0, ProspectorInfo-3.1.0)  

### Description
Game crashes on start when I try to load my save, but running ok in new save

[Game crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7419849/Game.crash.txt)

**Comment by copygirl** [comment]
Strange issue. Here is the crash to make searching easier:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemSoundEngine.OnGameTick100ms(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
```
Here is a pretty old, maybe related issue that crashes in the same function: #642

**Comment by copygirl** [comment]
If you'd be willing to do a bit of extra work, could you create a .zip of your world and upload it somewhere? The developers tend to recommend wetransfer.com for this sort of thing. If the same error occurs on their end, this could be fixed quickly.

**Comment by Mrsfoxy** [comment]
I started a new save and don't hane the old one anymore so I'll have to leave it at that. Thank you
