### ISSUE TITLE
Higher-tier damage resistance is not displayed on armor that doesn't have stat modifiers assigned

### ISSUE THREAD

**Issue by Barhandar** [anegostudios/VintageStory-Issues#1380]
**Game Version:** 1.15.7
**Platform:** Windows
**Modded:** No

### Description
Leather armor, for example, doesn't show that it has high damage tier resistance, even though in the files (`assets\survival\itemtypes\wearable\armor.json, `"armor-*-sewn-leather": {... highDamageTierResistant: true, ...}` it does, and the effect is there.  

### How to reproduce
Mouse over any of the leather armor (not padding aka jerkin) pieces, observe they don't have extra info in the tooltip.

### Expected behavior
High-tier protection, if enabled for given armor piece, should be displayed independently from the StatModifiers (which leather armor lacks, being otherwise the weakest armor with real cost to production).

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
