### ISSUE TITLE
Bug in API https://masterserver.vintagestory.at/api/v1/servers/heartbeat

### ISSUE THREAD

**Issue by kozak97** [anegostudios/VintageStory-Issues#1382]
If the token has expired or not found, the server returns a response with mixed fields. The status field contains the token, and the data field contains the status. Because of this, in case of interruptions to the Internet, the game servers disappear from the master server, and at the same time they do not attempt to re-register, since the game checks the status field for the status "timeout" or "invalid".

Code in game:
```
this.SendRequestAsync<HeartbeatPacket>(this.server.Config.MasterserverUrl + "heartbeat", packet, delegate(ResponsePacket response)
            {
                if (response.status == "invalid" || response.status == "timeout")
                {
                    ServerMain.Logger.Notification("Master server sent response {0}. Will re-register now.", new object[]
                    {
                        response.status
                    });
                    this.server.EnqueueMainThreadTask(delegate
                    {
                        this.SendRegister();
                    });
                }
            });

```
![2021-10-27_190347](https://user-images.githubusercontent.com/16307583/139106363-71405a0a-0fa8-45e3-a5ba-c68ba136920f.png)
![2021-10-27_190356](https://user-images.githubusercontent.com/16307583/139106362-a2000c36-b374-42a4-ba31-e89857715e29.png)

**Comment by tyronx** [comment]
wow, nice find. thanks! The status field should now contain "timeout".
