### ISSUE TITLE
Water destroys tapestries

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1383]
**Game Version:** 1.15.7
**Platform:** Windows 
**Modded:** Yea

### Description
I found ruins which had a waterfall running thru...destroying the tapestries for what had contact with water...kinda despressing with the odds of finding one you need+ a one which isnt rotted.

Im guessing if someone makes a mess or drops bucket of water in someone else home...they could ruin them also...or you just found a ruin...dig up...lake floods it and ruins it! 

### Expected behavior
Prevent water from going into ruins or destroying tapestries...

### Screenshots
![2021-09-24_13-27-21 (2)](https://user-images.githubusercontent.com/31166271/139112625-a97a6c04-c31d-4706-8d11-90c2999afd28.png)

**Comment by tyronx** [comment]
I dont think that can be considered a bug, in fact, realisticly speaking those neighbouring tapestries should be long rotten as well 😛
