### ISSUE TITLE
Missing small oiled hide recipe

### ISSUE THREAD

**Issue by vasekhodina** [anegostudios/VintageStory-Issues#1387]
**Game Version:** 1.5.7 
**Platform:** Linux Achlinux
**Modded:** No 

### Description
Small oiled hide is not craftable. When you place a small raw hide and fat in a crafting grid small oiled hide does not appear in output field. When you place any bigger hide, oiled hide appears.

### How to reproduce
1. Add small raw hide to crafting grid
2. Add lump of fat to crafting grid
3. No output of the crafting

### Expected behavior
Small oiled hides should be craftable since small pelts can be used to craft longbow staff.

### Screenshots
When using small hide, bug:
![image](https://user-images.githubusercontent.com/1662022/139305998-287e0fcd-6c22-498c-800c-98946402f6e9.png)

When using medium hide, correct:
![image](https://user-images.githubusercontent.com/1662022/139306124-3adabd2d-38f8-497b-a639-1797a18d7aab.png)

### Logs
```
N/A
```

Fixed version of oiledhide.json:
https://gist.github.com/vasekhodina/be5efe1af4e0c6ddc828f99c0f194986

**Comment by tyronx** [comment]
thanks, this is fixed for next release
