### ISSUE TITLE
Armor `Ranged Weapon Charge Time` description

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1388]
**Game Version:** 1.15.7
**Platform:** (KDE neon 20.04 5.22)
**Modded:** No

### Description
No plus / minus sign by armor `Ranged Weapon Charge Time` effect.

### How to reproduce
1. See any armor description

### Expected behavior
Instead of just e.g. `7%`, plus/minus `+/-` sign should be displayed like by other effects. E.g. `-7%`

### Screenshots
![Armor_ranged_w_ch_t_plus-minus](https://user-images.githubusercontent.com/47914240/139413343-f73c7a23-48b1-4808-88c0-bfe9bff0df3f.png)

**Comment by tyronx** [comment]
thanks, this will be fixed next release

**Comment by daretmavi** [comment]
Hi, it's ok in 1.15.8-rc1, but it is still a bit confusing, because armor has Ranged Weapon Charge **Time** (+7%) and stats has Ranged Charge **Speed** (-7%)
(not a big deal, but I was confused at first)

![RWCharge_time-speed](https://user-images.githubusercontent.com/47914240/140315544-8b9c9132-2f47-4a4d-bcc6-1dcb34a2d677.png)

**Comment by daretmavi** [comment]
In 1.16.4, the description of `Ranged Weapon Charge Time` is for both the same - OK.
But the % is not correctly recalculated.
It is 93% (it was the speed before), but should be 107% (100% + 7%)
![2022-03-02_12-25-37](https://user-images.githubusercontent.com/47914240/156353439-68f7807d-06c4-4102-b48b-d9b1cfbd4ff3.png)

**Comment by Craluminum2413** [comment]
Should be 107%?

**Comment by daretmavi** [comment]
I would say yes. If the armor Ranged Change Time is +7%, then the according statistic should be 100+7%, not 100-7%.

**Comment by tyronx** [comment]
should be fixed next release
