### ISSUE TITLE
More cooking pots on firepit

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1396]
**Game Version:** 1.15.8-rc1
**Platform:** Linux (KDE neon 20.04 5.22 )   
**Modded:** No
**SP/MP:** Singleplayer

### Description
More cooking pots on firepit

### How to reproduce
1. Give one cooking pot on firepit (left or right click)
2. Take more cooking pots in the hand
3. Right click on the one cooking pot on firepit - they will swap and you have more cooking pots on firepit

You can not give more cooking pots, if firepit is empty.

### Expected behavior
Only one cooking pot should be placed on firepit, or if more are possible by design, then you should be able to give more pots even is firepit is empty (which is not possible). Only one pot on firepit makes more sense.

### Screenshots
![more-pots-on-firepit](https://user-images.githubusercontent.com/47914240/140359537-b7e4eaa5-7e34-476d-8d9e-8f0072b71ce1.png)

**Comment by Saricane** [comment]
I have the same crash (same error) with a quern and a single grain. So I think this is not related to the cooking pot, but rather to put and retrieve objets fo/from an input/output slot.
Take a quern, open it, and put a single grain (or more) either in the input or the output slot. Take it back, put it again in the same slot, or in the other slot, you won't wait for long before the crash.

**Comment by tyronx** [comment]
What the heck, I was certain I fixed the cooking pot stacking issue at least twice already :O

**Comment by tyronx** [comment]
Thanks for the report, should be fixed next release
