### ISSUE TITLE
raccoon-female JSON death SFX typo

### ISSUE THREAD

**Issue by veskveskvesk** [anegostudios/VintageStory-Issues#1397]
There is a typo in the JSON of the "raccoon-female" mob on line 237, causing them to never play their "death.ogg" SFX and instead play their "hurt.ogg" when killed.

"    sounds: {
        hurt: "creature/raccoon/hurt",
        death: "creature/raccoon/hurt","

raccoon-male and raccoon-pup JSONs seem free from this issue.

**Comment by tyronx** [comment]
thanks, will be fixed next release
