### ISSUE TITLE
Mini-map and map kills my fps(see screenshots+video)

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1398]
**Game Version:** 1.15.8 rc1
**Platform:** Windows
**Modded:** Yes
BetterCratesCC 1.3.3
CarryCapacity v0.6.3
ExtraChestsCC 1.4
FarmlandDropSoil 1.4
Medieval Expansion 3.6.1
Prospector Info 3.1.0
Tradeomat 1.5.9
workbench expansion 1.3

Singleplayer but loading our Aura Fury world with my 3.5gig map and 2500-2800 waypoints.

### Description
When the mini map or map shows up...the FPS drops significantly.

### Expected behavior
Optimized the mini-map and world map better.

### Screenshots

![2021-11-04_14-04-18](https://user-images.githubusercontent.com/31166271/140422259-e0455568-c443-4a30-97f4-2aa3bbafecd6.png)
![2021-11-04_14-05-09](https://user-images.githubusercontent.com/31166271/140422263-759bf024-6d24-4e2a-9750-20c2cb20cfc1.png)
![2021-11-04_14-05-02](https://user-images.githubusercontent.com/31166271/140422267-29658d9a-2b6d-4f53-84ba-552ab604aad7.png)
![2021-11-04_14-04-49](https://user-images.githubusercontent.com/31166271/140422268-8a5eb052-fdb2-4aca-95e4-7c26bc33288b.png)
### Video
```
Here's video 5 mins of me running with CTRL f10 + mini-map with and without.
https://youtu.be/Dsks-4KuZ8w

**Comment by tyronx** [comment]
Thanks for the report. This should be fixed next release.
