### ISSUE TITLE
Swimming (breast stroke with shift) on shallow to deep water gets you stuck.

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1399]
**Game Version:** 1.15.7
**Platform:** Windows 10
**Modded:** Yes
**SP/MP:** Singleplayer but loading our AF world for testing.

### Description
As you start swimming in shallow water pressing W + shift you do breaststrokes just fine until you hit border of the 1 deep water to the 2nd deep water. (I believe its because shift is used to not fall off the edge of blocks but also to do breastroke to swim fast...might wanna remap key to something else or make it it detects water and lets you keep swimming...

### Video
https://youtu.be/v-W5X9Pp0Ys

**Comment by copygirl** [comment]
Being able to swim in shallow water might also be a bug in the first place, unsure about this.

**Comment by Craluminum2413** [comment]
Can't swim in shallow water anymore, no idea which version added this
