### ISSUE TITLE
404 URL In-Game Mod Manager/VS Mod DB

### ISSUE THREAD

**Issue by veskveskvesk** [anegostudios/VintageStory-Issues#1402]
**Game Version:** 1.15.7
**Platform:** Windows 10
**Modded:** HUD Clock (Code)
**SP/MP:** Singleplayer

### Description
There is a typo in-game on the Mod Manger menu, which points to the Mods Database but results in a 404 error.

### How to reproduce
1. Main Menu>Mod Manager
3. "official mod hub" ( "https://mods.vintagestory.at//")
4. 404 error (extra "/" at the end of the URL)

### Screenshots
![screen](https://user-images.githubusercontent.com/83672364/140611673-a7648101-ec7c-4998-bd6f-77418f3aa768.png)
![Screenshot 2021-11-06 064506](https://user-images.githubusercontent.com/83672364/140611888-0fd91d3b-fbc9-4572-bef1-b6e5a4ff2a93.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
