### ISSUE TITLE
я скачал игру и запускаю лаунчер и тут это, что мне делать?

### ISSUE THREAD

**Issue by MAX228228228** [anegostudios/VintageStory-Issues#1410]
Running on 64 bit Windows with 4 GB RAM 
Version: artEA#9289 for VW-Dim v1.15.9 (Stable)11.11.2021 22:20:49: Critical error occurred
System.MissingMethodException: Метод не найден: "!!0[] System.Array.Empty()".
   в _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   в _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )
-------------------------------

**Comment by Craluminum2413** [comment]
Purchase the game https://www.vintagestory.at/store/product/1-game-account/

**Comment by copygirl** [comment]
Also a duplicate: #1303
