### ISSUE TITLE
1.15.9 : Sounds issues : OpenAL Error during SetPitch/Dispose and Construction

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1411]
**Game Version:** 1.15.9
**Platform:** Windows 10 
**Modded:** Yes 
**SP/MP:** Multiplayer (AuraFury)  

### Description
I ran the dev mode with all checks and also ran .debug logticks 100.
11.11.2021 15:25:59 [Notification] Reloaded sounds (async), now with mod assets

heres the 3 errors i get most often i get spam with those warning OpenAL each seconds x10-15 per seconds...:
11.11.2021 15:26:30 [Notification] Loaded Shaderprogramm for render pass clouds. 
11.11.2021 15:26:30 [Notification] Shader clouds: Uniform locations for variables sunColor, playerPos, cloudTileSize, shadowRangeFar, toShadowMapSpaceMatrixFar, shadowRangeNear, toShadowMapSpaceMatrixNear, viewDistance, viewDistanceLod0, glitchStrengthFL, pointLights, pointLightColors, pointLightQuantity, zNear, zFar, lightPosition, shadowIntensity, shadowMapFar, shadowMapWidthInv, shadowMapHeightInv, shadowMapNear, sky not found (or not used).
11.11.2021 15:26:31 [Notification] DebugSeverityMedium DebugTypePerformance | Program/shader state performance warning: Vertex shader in program 48 is being recompiled based on GL state.
11.11.2021 15:26:42 [Notification] DebugSeverityMedium DebugTypePerformance | Program/shader state performance warning: Vertex shader in program 48 is being recompiled based on GL state.
11.11.2021 15:26:45 [Warning] OpenAL Error during SetPitch: InvalidName
11.11.2021 15:26:45 [Warning] OpenAL Error during dispose: InvalidName
11.11.2021 15:26:45 [Warning] OpenAL Error during dispose: InvalidName
11.11.2021 15:26:45 [Warning] OpenAL Error during SetPitch: InvalidName
11.11.2021 15:26:45 [Warning] OpenAL Error during SetPitch: InvalidName
11.11.2021 15:26:45 [Warning] OpenAL Error during SetPitch: InvalidName
11.11.2021 15:26:45 [Warning] OpenAL Error during construction before: InvalidName

### Logs
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7523169/client-main.txt)

**Comment by Aledark789** [comment]
Still present in 1.16.1 and not just for me. Almost everybody i ask loose their sound after long time of gameplay...gotta relog or select their source.

**Comment by copygirl** [comment]
@svanheulen confirmed this, or a similar issue, on Linux and 1.16.1 as well:
```
OpenAL Error during construction before of sound game:sounds/walk/gravel4.ogg: InvalidValue
```
I also have in the past noticed sounds not playing after the game has been running for a bit.

**Comment by tyronx** [comment]
This will be fixed in 1.18, thanks to Fulgen.

**Comment by Aledark789** [comment]
Oh wow this like the best christmas gift. Thanks @Fulgen and @tyronx

**Comment by tyronx** [comment]
ohwait, I hope it is. Not 100% sure its the same bug. We fixed the sound isssues when changing output devices.
