### ISSUE TITLE
Place 2 ropes on the one fence sauses game crash

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1425]
**Game Version:** 1.15.9
**Platform:** Windows 
**Modded:**  Yes
**SP/MP:** Multiplayer 

### Description
I connected 2 fences together with 1 rope, then tried to connect another rope to one of these fences

### How to reproduce
1. Make 2 fences and place it on the ground with 1 block gap. 
2. Make 2 ropes and connect these 2 fences with 1 rope. Finish operation. Start connect 2nd rope to one of those fences.
3. It crashes and doesnt make link between 2 rope and already roped fence.

```
Sorry, forgot copy crash log
```

**Comment by copygirl** [comment]
Ropes are still a work-in-progress last time I've heard of them.

**Comment by Craluminum2413** [comment]
Closing because ropes are still not implemented
