### ISSUE TITLE
(Creative) Grid recipes consume all liquid instead certain amount

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1433]
**Game Version:** 1.16.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
It cannot be reproduced without using both gamemodes

### How to reproduce
1. Get a stack of `bowls`/`buckets` with water
2. Get 1 flour
3. Put flour and the stacks of `bowls`/`buckets` with water into crafting grid
4. Craft it
5. It consumed all liquid inside liquid containers

### Expected behavior
Always consume certain amount even if there is more than one liquid container in a slot

### Videos

https://user-images.githubusercontent.com/69315569/144245669-851d067c-bbe4-481d-8d18-17add3bba58e.mp4

**Comment by Craluminum2413** [comment]
Made a mod with such recipe, but 4 buckets with 10L of liquid mortar give only 10 instead of 40```json
{
  "ingredientPattern": "W",
  "ingredients": {
    "W": { "type": "block", "code": "game:woodbucket" }
  },
  "width": 1,
  "height": 1,
  "shapeless": true,
  "attributes": {
    "liquidContainerProps": {
      "requiresContent": { "type": "item", "code": "sboverhaul:liquidmortar" },
      "requiresLitres": 1
    }
  },
  "output": { "type": "item", "code": "game:mortar" }
}
```

**Comment by Craluminum2413** [comment]
So I suggest to forbid to put more than one liquid container to each crafting grid slot

**Comment by tyronx** [comment]
thanks for the report, should be fixed in rc.6
