### ISSUE TITLE
Black screen when minimising on mod manager tab

### ISSUE THREAD

**Issue by NRobbo** [anegostudios/VintageStory-Issues#1435]
**Game Version:** 1.16.0-pre. 1
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer / Multiplayer (In the menus)  

### Description
while on the mod manager tab if I minimise the game and then re-open it the right section of the game becomes black (see attached image)

### How to reproduce
explained in description

### Expected behavior
not show a black screen

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![image](https://user-images.githubusercontent.com/49168246/144301165-b8a0b218-c63a-4864-942e-af366a9ff3ed.png)

### Logs
Nothing specific shown on logs

P.S This is a tiny tiny issue, but still might as well report it

**Comment by Craluminum2413** [comment]
Cannot reproduce in 1.16.0-rc.7

**Comment by copygirl** [comment]
@NRobbo Does this issue still occur for you?
