### ISSUE TITLE
Clean bandage recipe overlaps linen's recipe

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1449]
**Game Version:** 1.16.0-pre.3
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer

### How to reproduce
1. Get 4 flax twine
2. Open crafting grid and try to craft a linen
3. You can craft clean bandage only

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/144598776-6199a2f5-6551-44f4-8c66-b9b5860d84ab.png)

**Comment by Saricane** [comment]
Confirmed (if necessary).

**Comment by Craluminum2413** [comment]
It is fixed in 1.16.0-pre.4
