### ISSUE TITLE
json texture rotation

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#145]
As it stands if you have an arrow texture you need to include four textures for every possible way it could point. It would be nice to rotate textures and overlays in the same way as shapes. Example
```
textures: {
		horizontals: { base: "block/hay/{type}-side", rotate: -90 },
		verticals: { base: "block/hay/{type}-top" },
	},
```

**Comment by copygirl** [comment]
Do we support picking random textures from a list of them, too? It would be nice to also say "add this texture in all its four possible rotations" without adding an explicit orientation for each possibility.

**Comment by tyronx** [comment]
json texture rotation is a thing since v1.10
