### ISSUE TITLE
Duplicate "Respawn" lang key in en.json

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1450]
**Game Version:** 1.16.0-pre.3 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
There is also extra comma at the end of the file

### How to reproduce
1. Open `assets\game\lang\en.json`
2. Search `"Respawn": "Respawn"`
3. You found duplicates

**Comment by Craluminum2413** [comment]
Also there is duplicate for `block-crock-burned`

**Comment by brummbar7** [comment]
I removed the duplicate respawn, but only now saw the comment about the crock.  So that still needs removed.

**Comment by Craluminum2413** [comment]
Also moldrack is translated with wildcard, that makes impossible to translate modded variants:
Original: `"block-moldrack-*": "Tool mold rack"`,
Should be `"block-moldrack-normal": "Tool mold rack",`

**Comment by copygirl** [comment]
@Craluminum2413 That should be its own issue.
