### ISSUE TITLE
Only liquid containers with capacityLitres 10 can place water block, while others don't

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1452]
**Game Version:** 1.16.0-pre.3
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
Liquid containers with more than `capacityLitres: 10` (e.g. 11) cannot place water block.
Liquid container with `capacityLitres: 10` can place water block.

### How to reproduce
1. Set `capacityLitres` to 11 for `blocktypes/clay/bowl.json`
2. In the game, fill a bowl with any liquid e.g. water
3. Empty the bowl contents with `Ctrl + Right mouse button`
4. Water block is not placed

**Comment by copygirl** [comment]
I'll leave this open but the ability to place water being limited to buckets might be intentional.

**Comment by Craluminum2413** [comment]
You didn't get it, containers with capacityLitres 10 can place a water block, while 11 and more don't

**Comment by copygirl** [comment]
Ah I see.

**Comment by Craluminum2413** [comment]
The same behavior for fruit press and distiller, I cannot place liquid containers with more than 10L under them
