### ISSUE TITLE
Rocks can cross a wall

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1455]
**Game Version:** 1.16.0-pre4
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
In some (undetermined) case, rocks thrown by drifters can cross a wall. I have a perfectly safe basic room made of cobblestones and glass, and had some hits coming from nowhere. After a while, I managed to determine the origin of those rocks. I recorded one throw on the following video.

### How to reproduce
Cannot reproduce it, because drifters are not Ok to participate peacefully.

### Video

https://user-images.githubusercontent.com/84909583/144757749-6c96f794-834a-41f1-b744-7fe4a9f55f8f.mp4

**Comment by Saricane** [comment]
https://user-images.githubusercontent.com/84909583/145104697-3253d293-020b-4142-8a59-9b7c955e6d60.mp4

**Comment by Saricane** [comment]
> Fixed: Drifters throwing stones without line of sight

Now they don't throw anything if the player cannot be reached, so I think this bug is fixed.
This issue can be closed.

**Comment by copygirl** [comment]
If the root cause of rocks phasing through walls still exists, I think this is still a bug worth tracking and eventually fixing, even if now it likely won't happen to players anymore.
