### ISSUE TITLE
Slanted Blue Clay Block Not Counting As Roof

### ISSUE THREAD

**Issue by furnox** [anegostudios/VintageStory-Issues#1458]
**Game Version:** 1.15.10  
**Platform:** Linux   
**Modded:** No
**SP/MP:** Singleplayer

### Description
The clay, slanted roof tiles do not appear to count as roofing to define a "room". When a valid (equal to or smaller than the 7x7x7 limit for a heatable room size) room is created using the blue clay slanted roof tiles, the game does not recognize it as a valid room. Temperatures plunge and there is a 125% hunger penalty.

This issue was first noticed in v1.15.5 and still exists in v1.15.10.

[Forum post](https://www.vintagestory.at/forums/topic/5576-does-blue-clay-roofing-count-as-a-room/)

### How to reproduce
1. Make a 7 x 7 x 2 wall.
2. Then continue with one level of 7x7 clay blocks, building inward each level until the roof meets in the middle (this will be 4 levels of slanted clay blocks in total). This will give an enclosed "space" of 5x5x5.
2. Set season to winter when it is really cold.
3. The room gets temperature and hunger penalties.

### Expected behavior
The valid room is given the heat and hunger benefits of a shelter.

### Screenshots
![2021-09-27_23-39-05](https://user-images.githubusercontent.com/874194/144799387-7beb6ec0-1bbf-4ce4-b6c3-3b2e4a21c0ae.png)

**Comment by Craluminum2413** [comment]
Fixed in 1.19.0-pre.5
