### ISSUE TITLE
Add hunger costs to crafting.

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#146]
I was doing a poll recently for active time costs such as for making a rope, chopping wood, or sanding. Most want to hold down a button for X many seconds for as many hours it takes to make something IRL. Well, that seems kind of boring to me. Instead what I'd like to opt for is being able to add hunger costs to recipes to represent the time and energy it takes to make something. What this does is put more demand on food encouraging people to forage and hunt more early game and have a use for all their food late game. Also right now you can eat even if you are already full which is nice for healing and later gaining nutrition but if you weren't able to eat when already full you could then craft some stuff to get hungry again so you can eat more and gain more hp and nutrition. Overall I think it'd add more to the game and I know I get really hungry after chopping a bunch of firewood.

**Comment by copygirl** [comment]
I have a couple of thoughts to add to this:
- With the simple crafting grid in your inventory this seems sort of odd. I would love it if crafting was implemented in some in-world fashion and the number of times you hit it would communicate the amount of work required to finish the task; the more steps required, the higher the hunger costs.
- When this is implemented, I feel like we should significantly nerf the idle hunger cost. Thus you can just hang out and walk around and chat and especially go AFK with little to no worry regarding getting food.
- Something important to avoid is causing the player to get stuck being unable to craft basic tools to get food, as that could be unnecessarily frustrating.

**Comment by copygirl** [comment]
> Something important to avoid is causing the player to get stuck being unable to craft basic tools to get food, as that could be unnecessarily frustrating.

Reading this again, I think that could be done by slowing down the speed at which you can do crafting. That is, breaking of voxels when knapping, placing voxels when clayforming, or swinging the hammer when smithing.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
