### ISSUE TITLE
Liquid dupe in a barrel

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1467]
**Game Version:** 1.16.0-pre.6  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a barrel
2. Fill the barrel with any liquid
3. Get more than one e.g. 64 buckets
4. Open the barrel menu
5. Take the buckets and holding them, `right click` on the barrel's input slot
6. You get 64 buckets each with 10 liters of liquid

### Videos
https://user-images.githubusercontent.com/69315569/145265859-fefa8b05-5238-4c06-a5ef-63ad6be1dffb.mp4

**Comment by Craluminum2413** [comment]
The same for cooking pot and toolbar

https://user-images.githubusercontent.com/69315569/145450978-5dcf34f6-70db-4306-8843-7766dd50f97a.mp4

**Comment by tyronx** [comment]
thanks for the report, for the time being, i'll disable stackable buckets.

**Comment by Craluminum2413** [comment]
But the bowls still have a stack of 16 and you can do the same using them

**Comment by tyronx** [comment]
thanks for the report, this should now be properly addressed for next release. Made buckets stackable again.

**Comment by Craluminum2413** [comment]
Still possible

**Comment by Craluminum2413** [comment]
You forgot to reopen this issue

**Comment by copygirl** [comment]
You saw nothing!

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/topic/6143-duping-honey-with-bowls/

**Comment by tyronx** [comment]
Aw, forgot the gui slots handling. Now hopefully fixed for real in rc.6

**Comment by Craluminum2413** [comment]
Still possible in rc.7, I crafted 4 buckets and 1 barrel, squeezed honey into them, then filled the barrel with honey and got 4x more liquid

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/148445331-8008161c-0699-4f24-af49-f8ad1484df4f.mp4

**Comment by tyronx** [comment]
That is one tenacious bug. Fixed again for next release. Thanks for the continous testing 👍
