### ISSUE TITLE
Item hover text glitching off-screen [v1.16 pre.6]

### ISSUE THREAD

**Issue by AythaAquaheart** [anegostudios/VintageStory-Issues#1468]
As the title says, when hovering over an item in the hotbar the textbox flickers between going upwards from the cursor like it should to going off the screen, making it near impossible to read information on items at times.

I am also not sure if it's intended to be this bright at night, it never gets darker than in this image, I will open a new issue if this is a bug as well.

![image](https://user-images.githubusercontent.com/32623264/145291619-4c995d71-85de-40c4-be45-c02e77ccfe2a.png)

**Comment by AythaAquaheart** [comment]
A small addition since at the time I hadn't found the template and as such forgot a few small details:
I am playing on Windows, Singleplayer without mods.

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
