### ISSUE TITLE
Oil Lamps not attaching to the side of blocks and floating [1.16 pre.6]

### ISSUE THREAD

**Issue by AythaAquaheart** [anegostudios/VintageStory-Issues#1469]
**Game Version:** 1.16 pre.6
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer

### Description
When placing an Oil Lamp against the side of a block it simply hovers there like it was placed on the ground. It also has no collission, but I do not use them enough to know if they usually do.
Additionally, when the oil lamp is placed above a non-solid block like long grass for example, it will drop to the ground once said block is broken.

### How to reproduce
1. Make an oil lamp
2. Try to place it on the side of a block.
3. It will just float in the air in the position it would be in when placed on the ground.
4. [if the oil lamp was placed above a non-solid block or other item, like another oil lamp or grass] Break the block beneath the grass/non-solid block/item.
5. The oil lamp falls down to the ground.

### Expected behavior
The oil lamp attaches to the side of the block and is unaffected by breaking blocks around it outside of the one it is attached to or resting on.

### Screenshots
![image](https://user-images.githubusercontent.com/32623264/145404860-9fdaf0ae-3533-4312-a46f-7b8a8dea0239.png)
![image](https://user-images.githubusercontent.com/32623264/145404405-b744cfb2-b6aa-4528-a692-91d8355b4feb.png)
![image](https://user-images.githubusercontent.com/32623264/145404708-e7c84904-29ac-48e3-9d88-9e88c93980fc.png)

**Comment by Craluminum2413** [comment]
#1234?

**Comment by AythaAquaheart** [comment]
No, I can place them on any vertical surface, they are just floating instead of attaching properly.
![image](https://user-images.githubusercontent.com/32623264/145409759-7f1bc5ff-2346-49b2-bcd2-8ec5975f7fd6.png)

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
