### ISSUE TITLE
Able to overfill cooking pot

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1470]
**Game Version:** 1.16.0-pre.7 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Make a firepit
2. Put an empty cooking pot into it
3. Get a bucket filled with e.g. water
4. Open the cooking pot menu
5. Right-click on empty slot with the bucket filled with liquid until you add 10 liters
6. Now you can use bucket to add any amount of liters inside cooking pot

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/145450443-246c70c2-7d17-48a1-91bf-428fd139dc9a.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
