### ISSUE TITLE
Quartz bits on the ground

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1473]
**Game Version:** 1.16.0-pre7
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer, survival and creative

### Description
When collecting quartz bits on the ground you can determine if you want to collect quartz chunk or clear quartz

### How to reproduce
1. Find quartz bits on the ground (or spread them yourself in creative mode).
2. Take a clear quartz in hand, coming from your stock
3. With this clear quartz in hand, pick up quartz bits on the ground
4. All quartz bits collected will become clear quartz (oddly, in that case, you often have to click several times on it before you can actually pick it up).

5. Now take a quartz chunk in your hand
6. With this quartz chunk in hand, pick up quartz bits on the ground
4. All quartz bits colected will become quartz chunk (and this time with a single click, no stuttering)

### Expected behavior
Quartz collected being determined by the same ratio clear quartz/quartz chunk than when mining.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
