### ISSUE TITLE
Clumsy bighorn

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1475]
**Game Version:** 1.16.0-pre7
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer survival

### Description
Bighorn can barely chase the player anymore.

When trying to provoke a wild bighorn to move him to his new enclosure, he is now quite unable to step a single block up, and stay there, almost stuck. This makes the process of moving this animal a very tedious task. I did not try with boars.

### Poor quality video 

https://user-images.githubusercontent.com/84909583/145683077-810e4e9b-4306-4ef1-970e-b3aa7ca2a537.mp4

**Comment by Saricane** [comment]
> Fixed: Creatures no longer stepping on blocks

Thanks. That was very annoying. Another problem is bighorn now run faster than the player (I have no armor penalty), so I get rammed from behind when trying to guide him to his new home :-)
But I don't know if this is a bug or if it's intended.

**Comment by copygirl** [comment]
Closing as fixed, then.

> Another problem is bighorn now run faster than the player (I have no armor penalty), so I get rammed from behind when trying to guide him to his new home :-)
> But I don't know if this is a bug or if it's intended.

This seems to be more in the "suggestion" space. You can ask the devs whether this is intended in the Discord group, if you happen to be there. If it's indeed a bug you may open another issue.
