### ISSUE TITLE
Journal expansion

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#148]
The ability for mods to add their own pages and ability to add pages automatically. I don't know what all you planned for the journal, but people want to use it for mod tutorials and recipes.

**Comment by Balduranne** [comment]
Also the ability to take notes in the journal would be great.

**Comment by Heptagon-ru** [comment]
Also embedding screenshots for logging ore and other goodies and bases locations.
Or, similar to what Balduranne said,  just a "text screenshot" when some text is added, but game automatically adds coords where it was added, time, thumbnail=screenshot.
Maybe with ability to organise notes, like moving them, gathering under topics, custom tabs creation, so I could group all ore records under a new "Ores" tab, bases under "Bases", ... Kinda like Microsoft OneNote :DDD

**Comment by copygirl** [comment]
It's likely this issue will be closed once it's possible for mods to add their own journal entries. In that case, please create a new issue with your suggestion regarding players using the journal for their personal notes.

**Comment by sirStroam** [comment]
I'm pretty sure support already added. Closing
