### ISSUE TITLE
wrong shadow rendering at cooper's reed bottom

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1482]
**Game Version:** 1.16.0-pre9
**Platform:** kubuntu (21.10)
**Modded:** No   
**SP/MP:** Singleplayer survival

### Description
When grouped, the shadows at the bottom of cooper's reeds (or papyrus) make a checkeredboard pattern.

### Screenshots
![2021-12-16_21-28-09](https://user-images.githubusercontent.com/84909583/146585922-51758909-6b4c-4a25-8d32-61eac3952e5c.png)

**Comment by Craluminum2413** [comment]
Was fixed in [1.16 Stable](https://www.vintagestory.at/forums/topic/6214-homesteading-part-2-combat-update-stable-1160/#comment-30399:~:text=shadows%20around%20reed%26papyrus)
