### ISSUE TITLE
Unable to save map mark under certain conditions

### ISSUE THREAD

**Issue by whitebyte** [anegostudios/VintageStory-Issues#1484]
**Game Version:** 1.16.0-pre10
**Platform:** Linux 
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Start adding a map mark
2. Type in some nonexistent color
3. Clear the color input
The Save button will stay disabled

### Expected behavior
Should be able to add a mark with a default color

**Comment by Craluminum2413** [comment]
Reproduced in 1.16.0-rc.7, but it more looks like a suggestion

**Comment by copygirl** [comment]
While I small bug, I think it's still a bug. If the input is empty it should use the default color.

**Comment by Craluminum2413** [comment]
Was fixed in some of 1.17 updates where grids of icons and colors were added, also they have default icon and color
