### ISSUE TITLE
Trader will not buy requested 2 bowls of honey, 1.16.pre11

### ISSUE THREAD

**Issue by Corvus1313** [anegostudios/VintageStory-Issues#1489]
**Game Version:** 1.16.pre11
**Platform:Linux  
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Despite requesting a stack of 2 bowls of honey (1 liter per bowl) the buy button is never enabled when two bowls are presented.  Honey bowls cannot be stacked the way they are present and offering two separate bowls still doesn't work.

### How to reproduce
1. Fill two bowls with 1 liter of honey
2. Place both bowls in buy window of a purchasing trader
3. Buy button not enabled.

### Expected behavior
Enable buy button when two bowls placed.

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed in rc.3
