### ISSUE TITLE
Bandage that cannot be used shows tooltip that it can be used

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1497]
**Game Version:** 1.16.0-rc.2  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Get clean bandage
2. Look at tooltip
3. It shows that it can be used, but it cannot

**Comment by tyronx** [comment]
what does it write for you? because I cannot see any text in the tooltip

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/147405102-13eb258d-be4a-44e3-9c6b-8b095cf54524.png)
For clean and dirty

**Comment by tyronx** [comment]
oh, the held interaction help. Ok, thanks, fixed for rc.4
