### ISSUE TITLE
.tfedit leaves the invisible window if no item selected

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1499]
**Game Version:** 1.16.0-rc.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Choose empty slot
2. Write `.tfedit`
3. It leaves invisible window

**Comment by tyronx** [comment]
Oh lol, this issue again

**Comment by tyronx** [comment]
thanks, fixed for rc.3
