### ISSUE TITLE
Stone knife eats cattails on last use

### ISSUE THREAD

**Issue by PyralIron** [anegostudios/VintageStory-Issues#15]
Using a stone knife on a cattail (potentially other tools on blocks) when it has one use left will destroy the cattail plant and only give the cattails item, as if you were using your fist.

**Comment by copygirl** [comment]
Actually, I do remember this, too! The last use of an item causes the drops to vanish as if the block was broken without the appropriate tool

**Comment by tyronx** [comment]
Ok, should be fixed for the upcoming 1.5.2.2
