### ISSUE TITLE
Bugged knapping

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#150]
Placed down 2 knapping surfaces down quickly. One of them bugged, turned invisible and incompletable. I had to destroy it with another tool
![2018-07-14_22-03-57](https://user-images.githubusercontent.com/10406037/42729800-feb443cc-87b1-11e8-93f5-4af652464253.png)
![2018-07-14_22-03-59](https://user-images.githubusercontent.com/10406037/42729801-003271c4-87b2-11e8-9d13-25104b7f1bb5.png)
Left clicking on it with an appropriate stone brings up the selection window, but clicking any option does nothing but close said menu

**Comment by tyronx** [comment]
Is it reproducible somehow?

**Comment by Balduranne** [comment]
Unfortunately no, I tried to do this again, but it didn't happen again.

**Comment by tyronx** [comment]
Decently confident that this is fixed in v1.7.8 so closing this.
