### ISSUE TITLE
Watering can is not erasing cave art

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1501]
**Game Version:** 1.16.0-rc.2  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Get a chalk stone
2. Place any rock block
3. Draw something on the rock with the chalk stone
4. Get a watering can full of water
5. Water the drawing for about 5-10 seconds
6. It does nothing

### Videos
https://user-images.githubusercontent.com/69315569/147396478-8b991cec-2d19-4b35-a7cd-bd02a2a81f09.mp4

**Comment by tyronx** [comment]
Thanks for the report, this is will be fixed in rc.3
