### ISSUE TITLE
Porting v 1.15.x game to 1.16.rc2 map descriptions destroyed

### ISSUE THREAD

**Issue by Corvus1313** [anegostudios/VintageStory-Issues#1502]
**Game Version:** 1.16.rc2
**Platform:** Linux
**Modded:** No
**SP/MP:** Singleplayer

### Description
All map point descriptions were removed when porting a game from version 1.15.x to 1.16.x

### How to reproduce
1.  Create 1.15.x game
2. Make described map points
3. Upgrade game to 1.16.rc2

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed in rc.3 -  your waypoint names should be restored again there
