### ISSUE TITLE
Crash on autosave (?)

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#1510]
**Game Version:** 1.16.0-rc 3
**Platform:** Windows 
**Modded:** Yes CarryCapacity 0.6.4; HUD Clock 2.6.0
**SP/MP:** Singleplayer

### Description
Game crashes for seemingly no reason a few minutes after starting the world. The world is not saved. Probably crash on autosave. Maybe caused by the mods I'm using.

### Logs

Sorry but some errors are described in polish.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.3 (Unstable)29.12.2021 00:46:49: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Vintagestory.API.Datastructures.ItemstackAttribute.ToJsonToken()
   w Vintagestory.API.Datastructures.TreeAttribute.ToJsonToken()
   w Vintagestory.API.Datastructures.TreeAttribute.ToJsonToken()
   w Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   w Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   w Vintagestory.GameContent.BlockLiquidContainerBase.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   w Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug)
   w Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose()
   w Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   w Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot)
   w Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot)
   w Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args)
   w Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse)
   w Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args)
   w Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args)
   w Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args)
   w Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition()
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) w C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:wiersz 476
   w OpenTK.GameWindow.DispatchRenderFrame() w C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:wiersz 452
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) w C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:wiersz 375
   w _Gqy4bfkYgCRmVM3rr5ctXVLZlMh._aoi1Mc6iTidbcOBRjahZfdoHVdN(_BNIaG9Y7PSPYLFpjzhV1OMF5mHh , String[] )
   w _0ynubLUTRXRju8HMEIDSQn5ni6F._aoi1Mc6iTidbcOBRjahZfdoHVdN(ThreadStart )

**Comment by Craluminum2413** [comment]
Did you have a bowl or something similar in your inventory or hand that can hold any liquid?

**Comment by tkkot** [comment]
Hmm... a bowl of berry jam and an empty bucket

**Comment by copygirl** [comment]
Stack trace ends with the same methods as in #1508.

**Comment by tkkot** [comment]
I did some more testing, game crashed when I placed the bowl on the ground:

Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.3 (Unstable)29.12.2021 13:53:56: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Vintagestory.API.Datastructures.ItemstackAttribute.ToJsonToken()
   w Vintagestory.API.Datastructures.TreeAttribute.ToJsonToken()
   w Vintagestory.API.Datastructures.TreeAttribute.ToJsonToken()
   w Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   w Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   w Vintagestory.GameContent.BlockLiquidContainerBase.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   w Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug)
   w Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose()
   w Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   w Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot)
   w Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot)
   w Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args)
   w Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse)
   w Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args)
   w Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args)
   w Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args)
   w Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition()
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) w C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:wiersz 476
   w OpenTK.GameWindow.DispatchRenderFrame() w C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:wiersz 452
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) w C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:wiersz 375
   w _Gqy4bfkYgCRmVM3rr5ctXVLZlMh._aoi1Mc6iTidbcOBRjahZfdoHVdN(_BNIaG9Y7PSPYLFpjzhV1OMF5mHh , String[] )
   w _0ynubLUTRXRju8HMEIDSQn5ni6F._aoi1Mc6iTidbcOBRjahZfdoHVdN(ThreadStart )

Event Log entries containing Vintagestory.exe, the latest 3

{ TimeGenerated = 29.12.2021 13:53:57, Site = , Source = .NET Runtime, Message = Aplikacja: Vintagestory.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: kod wyjątku: c0020001, adres wyjątku: 00007FF8206C4F69
Stos:
 }

**Comment by tkkot** [comment]
Should I create another bug report? It seems to be the same stack trace

**Comment by tkkot** [comment]
And I tried again and managed to place both the bowl and the bucket on the ground and then closed the world successfully.

**Comment by copygirl** [comment]
No worries let's just keep this issue open. Even if the cause might be one or the other, the developers will eventually look at this.

**Comment by Craluminum2413** [comment]
Why it is closed?

**Comment by copygirl** [comment]
Not sure, they have also closed this issue: #1512
