### ISSUE TITLE
Grain nutrition levels not dropping after death

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#1511]
**Game Version:** 1.15.10, 1.16-rc.6
**Platform:** Windows
**Modded:** Yes: CarryCapacity 0.6.2; HUD Clock 2.5.0
**SP/MP:** Singleplayer

### Description
After I die all nutrition values drop, but grain stains at it's original (before death) level

### How to reproduce
I did not test whether the bug happened on other worlds.
1. In a survival world increase your nutrition values
2. Die

### Expected behavior
All nutritions should drop by some amount

**Comment by copygirl** [comment]
If you have the type, could you check if this is reproducible in the 1.16 release candidates?

**Comment by tkkot** [comment]
Tested on a different world, occurs both in 1.15 and 1.16 rc-4

**Comment by Craluminum2413** [comment]
I don't see grain here https://github.com/anegostudios/vsessentialsmod/blob/0a1ef20c3280370c9b93ba47d818ced1d0228c90/Entity/Behavior/BehaviorHunger.cs#L452-L456

**Comment by copygirl** [comment]
That's probably it! Good catch.

**Comment by tyronx** [comment]
oh, thanks! fixed for next release
