### ISSUE TITLE
Drinking milk immediately after milking ewe

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#1512]
**Game Version:** 1.16.0-rc 5
**Platform:** Windows 
**Modded:** Yes CarryCapacity 0.6.4; HUD Clock 2.6.0
**SP/MP:** Singleplayer

### Description
Upon milking an ewe, you immediately drink the milk.

### How to reproduce
1. You need a ewe that is milkable
2. Milk it
3. You get no milk in the bucket, you can see your dairy nutrition go up (by a lot)

### Expected behavior
Getting a bucket of milk

### Videos
https://youtu.be/L_LWUkHyv8g

**Comment by tkkot** [comment]
Reproduced in 1.16.0-rc4

**Comment by tkkot** [comment]
Recorded me reproducing the bug, video [here](https://youtu.be/L_LWUkHyv8g). When I watched it I realized that I tried to milk a sheep that was too stressed at that moment. But the animation played and the sheep's status was changed. I guess the bug is different (I'll edit the report)

**Comment by tkkot** [comment]
Tested again, now I see what is happening... You drink the milk right as you get it

**Comment by copygirl** [comment]
Why was this closed? Did it get fixed?
