### ISSUE TITLE
Vintage Story Installation does not ask where to install.

### ISSUE THREAD

**Issue by TonyLiberatto** [anegostudios/VintageStory-Issues#152]
The game installer still overwrites the previous installation without ever asking where I want to install the game.
If the game is Uninstalled first it will ask, otherwise it asks if you want to remove the old version, if you say no it will go ahead and overwrite the last installation.
We should be able to install the game on several locations, like having one location for each version, without having to jump hoops.
I solved the issue, by copying my old files to a new location before installing the new version, but is not the best way to handle the installation, for all players. 
The installation should always ask where to install, even if it pre-populates the location of the old installation. But give the player the choice to change that location

**Comment by Craluminum2413** [comment]
Is it still actual? It seems that we can install at least 10 versions separately

**Comment by copygirl** [comment]
I will close this as resolved, then.
