### ISSUE TITLE
Traders still buy/sell old crates

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#1526]
**Game Version:** 1.16.0-rc 5
**Platform:** Windows
**Modded:** Yes: CarryCapacity 0.6.4; HUD Clock 2.6.0
**SP/MP:** Singleplayer

### Description
Traders can buy and sell "Wooden crate" items, despite their being described as deprecated and convertible to new, 1.16 variants. 

### How to reproduce
1. Spawn a trader (of a type which can buy/sell crates)
2. Interact with it

### Expected behavior
Selling new, 1.16 crates (aged wood would make the most sense?)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.6
