### ISSUE TITLE
duplicate behaviors in verticalboiler file

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1527]
**Game Version:** 1.16.0-rc.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open `blocktypes/metal/verticalboiler.json`
2. Search for `behaviors`
3. Duplicate value is found

**Comment by Craluminum2413** [comment]
Also duplicate in `blocktypes/metal/chandelier.json`, there is two `chandelier-candle1` in `lightHsvByType`

**Comment by tyronx** [comment]
thanks for the report, should be fixed in rc.6
