### ISSUE TITLE
"Growing" tooltip for mature turnips.

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#153]
1.6 pre3, public test server.
Mature turnips have toltip saying "Growing" instead of expected "Mature" and stages 5 of 5.
When destroyed they give both seed and vegetable, so behave as mature.
Other veggies and crops seems to be ok.
In pre2 the issue was "inverted" - turnips were the only veggies having "MAture" tooltip, while others were "Growing" in the end of growth and when destroyed gave only seeds and not always, as if they are really not mature.
![2018-07-20_02-43-43](https://user-images.githubusercontent.com/25122345/43012105-24018a7c-8c4e-11e8-85fc-d2b769864aa5.png)

**Comment by tyronx** [comment]
fixed in pre4
