### ISSUE TITLE
Entity harvestable drops limited to 4 entries.

### ISSUE THREAD

**Issue by GhostLich** [anegostudios/VintageStory-Issues#1534]
**Game Version:** 1.16.0-rc.5 
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer & Multiplayer

### Description

Configuring an entity to drop more than 4 drop types results in only the first 4 dropping in-game.

### How to reproduce
1. Make an entity that drops more than 4 types under "code: "harvestable", drops: ["
2. Kill & harvest the entity in-game.
3. View that only the first 4 drop types are shown.

### Expected behavior

For all drops to be reflected & the GUI to extend to support it.

**Comment by Craluminum2413** [comment]
https://github.com/anegostudios/vsessentialsmod/blob/0a1ef20c3280370c9b93ba47d818ced1d0228c90/Entity/Behavior/BehaviorHarvestable.cs#L111

**Comment by Craluminum2413** [comment]
[Added in 1.17.0](https://www.vintagestory.at/forums/topic/8931-de-jank-and-game-juice-update-1170-pre1/#comment-37602)
Search there for "Configurable inventory slot count for entity harvesting" to find it.
Strange, but only 1.17.0-pre.1 changelog have mentioned it.

Example of how to make it to work
<https://github.com/anegostudios/VintageStory-Issues/issues/2306#issuecomment-1342550000>
