### ISSUE TITLE
Cannot fill fruitpress

### ISSUE THREAD

**Issue by jollki** [anegostudios/VintageStory-Issues#1535]
**Game Version:** 1.16.0-rc.6
**Platform:** Linux
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Can't put any fruit into press

### How to reproduce
1. Place fruit press
2. Right click on press with any fruit
3. Nothing happens

### Expected behavior
The fruit should be loaded into the press

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
