### ISSUE TITLE
Map is not opening in survival

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#154]
1.6 pre3 (pre2 too), public test server, and survival singleplayer.

The map feature, added in 1.6 pre1 is not working for me since pre1.
I tried setting another control key for it (N instead of M) - still no reaction.

The same in survival singleplayer. **But** when I switch to Creative mode - the map is opened fine. back to Survival - no map again.

**Comment by copygirl** [comment]
I'll mark this as question for now because this sounds like it's intentional. Perhaps the idea is that the player would unlock the map through crafting?

**Comment by Heptagon-ru** [comment]
@tyronx has replied in Discord:

> the world map hotkey is indeed registered as a creative mode only thing(edited)
> fixed now

**Comment by copygirl** [comment]
Ah, unintentional after all. Resolved it is, then!

**Comment by lluis** [comment]
This is happening me again on 1.11.4
tried with new ~/.config/VintagestoryData/ without luck

**Comment by lluis** [comment]
solved itself :O 
maybe after opening a creative mode world
