### ISSUE TITLE
Client not disabling older versions of mods 1.16 rc6

### ISSUE THREAD

**Issue by StewBagger** [anegostudios/VintageStory-Issues#1540]
1.16 RC6 
Windows  
Modded
Multiplayer 

Client is not disabling older versions of mods. client attempts to download new version of mod on each connect and is never actually able to connect. Removing older versions of mods solves issue.

5.1.2022 16:10:06 [Notification] Exiting current game
5.1.2022 16:10:08 [Notification] Will search the following paths for mods:
5.1.2022 16:10:08 [Notification]     D:\Vintagestory\Mods
5.1.2022 16:10:08 [Notification]     C:\Users\ut2k3\AppData\Roaming\VintagestoryData\Mods
5.1.2022 16:10:08 [Notification] Send request: mod/animalcages
5.1.2022 16:10:08 [Notification] Send request: mod/wolftaming
5.1.2022 16:10:08 [Notification] Send request: mod/petai
5.1.2022 16:10:08 [Notification] Send request: mod/lichen
5.1.2022 16:10:12 [Notification] Connecting to 72.87.69.65...
5.1.2022 16:10:12 [Error] Unable to read srv record, will connect to supplied hostname. Error: Non-Existent Domain
;; ->>HEADER<<- opcode: Query, status: Non-Existent Domain, id: 59591
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
5.1.2022 16:10:12 [Notification] Initialized GUI Manager
5.1.2022 16:10:12 [Notification] Initialized Server Connection
5.1.2022 16:10:12 [Notification] GuiScreenConnectingToServer constructed
5.1.2022 16:10:12 [Notification] Connected to server, downloading data...
0 kilobyte received
5.1.2022 16:10:13 [Notification] Loading and pre-starting client side mods...
5.1.2022 16:10:13 [Notification] Will search the following paths for mods:
5.1.2022 16:10:13 [Notification]     D:\Vintagestory\Mods
5.1.2022 16:10:13 [Notification]     C:\Users\ut2k3\AppData\Roaming\VintagestoryData\Mods
5.1.2022 16:10:13 [Notification]     C:\Users\ut2k3\AppData\Roaming\VintagestoryData\ModsByServer\72.87.69.65
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'animalcages' ('animalcages_v2.0.4.zip', 'animalcages_v2.0.5.zip'). Will only load the first one.
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'lichen' ('Lichen-v1.5.1-VS1.16.0.zip', 'Lichen-v1.6-VS1.16.0.zip'). Will only load the first one.
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'petai' ('petai_v1.2.0.zip', 'petai_v1.2.1.zip'). Will only load the first one.
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'creative' ('VSCreativeMod.dll', 'VSCreativeMod.dll'). Will only load the first one.
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'game' ('VSEssentials.dll', 'VSEssentials.dll'). Will only load the first one.
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'survival' ('VSSurvivalMod.dll', 'VSSurvivalMod.dll'). Will only load the first one.
5.1.2022 16:10:13 [Error] Multiple mods share the mod ID 'wolftaming' ('wolftaming_v1.2.0_petai_v1.2.x.zip', 'wolftaming_v1.2.1_petai_v1.2.x.zip'). Will only load the first one.
5.1.2022 16:10:13 [Notification] Found 29 mods (2 disabled)

**Comment by tyronx** [comment]
thanks for the report, this should be working for real now next release
