### ISSUE TITLE
1.15.10 : Crash from Importing schematic json in creative that i exported from diff game survival (same mod/same version)

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1541]
**Game Version:** 1.15.10
**Platform:** Windows
**Modded: Yes
- Mod 'BetterCratesCC_v1.3.4.zip' (bettercrates):
- Mod 'CarryCapacity-VS1.15.6-v0.6.3.zip' (carrycapacity):
- Mod 'FarmlandDropsSoil-VS1.15-v1.4.0.zip' (farmlanddropssoil):
- Mod 'medievalexpansion-3.6.1.zip' (medievalexpansion):
- Mod 'workbench-expansion-1.3.2.zip' (workbenchexpansion):
**SP/MP: Singleplayer

### Description
In a newly 1.15.10 World, i made a creative world. I wanted to import my json file i exported from my survival world which contains chiseled blocks, vanilla blocks as well as blocks from bricklayers, medieval expansion and bettercrates/betterchests.

### How to reproduce
1. Export a json file from a world with those mods and some of their blocks placed.
2. Since it's a big export gotta change : "schematicMaxUploadSizeKb": 20000 since my json export was 11 megs.
3. Open Creative World
4. Hit E, select a block that can be placed.
5. Click ~ key by the 1 key to activate world edit tools
6. Click import tools
7. Open where the json file is located (zipped for uploading on github)
[CastleGang11sept.zip](https://github.com/anegostudios/VintageStory-Issues/files/7819356/CastleGang11sept.zip)
8. Once the json is copied to clipboard
9. Right click with block in hand.

### Expected behavior
Not Crash!

### Logs
''' Client-Crash
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7819368/client-crash.txt)

`` Server-main
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7819370/server-main.txt)

``Client-Main
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7819371/client-main.txt)

**Comment by Th3Dilli** [comment]
thank you
this should be fixed by now see for similar issue #2656
