### ISSUE TITLE
Branches don't smelt into torches in firepit

### ISSUE THREAD

**Issue by wbottenberg** [anegostudios/VintageStory-Issues#1544]
Game Version: v1.16.0-rc.7
Platform: Windows 10
Modded: No
SP/MP: SP
World: new with v1.16.0-rc.6 update

![2022-01-06_08-30-55](https://user-images.githubusercontent.com/62803161/148419012-dcbf2106-f0b5-480f-91ed-bc92cde17d89.jpg)

**Comment by Craluminum2413** [comment]
Looking at the game files, I can only say that this is intentional

**Comment by copygirl** [comment]
Indeed. They are made differently now.
