### ISSUE TITLE
Able to fill the barrel with liquid from another barrel in survival

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1548]
**Game Version:** 1.16.0-rc.7
**Platform:** Window
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a barrel
2. Fill with honey
3. `Right-click` on the barrel GUI while holding another empty barrel
4. Place the second barrel
5. It has liquids as itemstacks in the input slot

### Videos

https://user-images.githubusercontent.com/69315569/148598070-67300c0c-55d2-46f8-b395-88d1f30acf30.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
