### ISSUE TITLE
Jug turns into bowl when picked up meal from cooking pot

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1549]
**Game Version:** 1.16.0-rc.7
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a cooking pot with meal
2. `Right-click` with jug on it
3. It is turned into bowl

**Comment by Craluminum2413** [comment]
It required json fix btw

**Comment by tyronx** [comment]
thanks for the report, should be fixed for next release
