### ISSUE TITLE
Some sounds are skipped randomly

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#155]
1.6 pre2, pre3, public test server.

Starting from approx 1.6 pre2 I started to notice that sometimes some sounds are not played, e.g.
walking, door/fence/chest open/close, sapling plant/destroy, ingot/plate pickup/place on ground.
It happens just randomly - one moment a sound is played and when I do the next action - no sound from it.

Sometimes it is only 1% of sounds, sometimes 50-70%

It is hard to reproduce. I seem to reproduce it reliably by first running about 200 blocks on a path, then trying to make sounds by placing and destroying saplings.

On the video the audio level is low, so probably you will not notice that initially my running sounds are 100%, but in the end they are skipped more and more.
And finally you can hear that lot of sapling placing and destroying sounds are missing, same as gate opening/closing.

https://yadi.sk/i/-Wbo3Loq3ZPz3X

**Comment by tyronx** [comment]
hm yea, might be related to the extinguished campfires, as they each load up a sound and keep it in memory

**Comment by Heptagon-ru** [comment]
You wanna keep the campfires road to be a stress test build and try to improve the sound system?
Or want me to destroy the campfires and see if the issue disappears?

**Comment by copygirl** [comment]
Could this be related to #130?

**Comment by tyronx** [comment]
You can leave the campfires for now, not sure if its related to #130, that one made the sound disappear completely and even in new worlds.

**Comment by Heptagon-ru** [comment]
As Tyron said, the bug was fixed. Does not appear any more. Closing.
