### ISSUE TITLE
Some strings are not translated

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1554]
**Game Version:** v1.16.0-rc.8

### Screenshots

![roturier](https://user-images.githubusercontent.com/26251843/148679110-74fba926-fec0-47d3-87cf-17a989bfeaef.png)
![skin](https://user-images.githubusercontent.com/26251843/148679114-d159a26e-1623-4691-953f-191f1229e5f7.png)
![clothier](https://user-images.githubusercontent.com/26251843/148679120-d3a92f4d-1053-460b-962e-ee87d8275241.png)

Also:
- "Thigh-high boots" and "High leather boots" are linked as a clothier exclusive in the character creation sheet but they don't have the sentence "* Requires clothier trait" in their description (see : "handbooksearch://sewing kit or chateau or pastoral or reindeer or moon or minstrel or fortune or nomad or spice or cobalt or azure or thigh-high or fine trousers or high leather")

**Comment by copygirl** [comment]
Related issue: #1325

**Comment by Xandoria** [comment]
Also, there is a small problem with a translation made by TyronX1 in the French file.

His translation for "<font color="#99c9f9"><i>The Hanseatic League, with their merchant navies, offered their services to charter and transport the incredible amount of goods, materials, and refugees. It was a monumental effort of logistics; something only they could pull off.</i></font><br>"

He forgot to add the <font color="#99c9f9"><i> in the translation. But his translation is rated +3, so the correct translation cannot be accepted. I have tried to mp him in Crowdin but there was no answer.

**Comment by Xandoria** [comment]
Game Version: v1.16.0

![fruit press 1](https://user-images.githubusercontent.com/26251843/148927176-ae8cbb64-61f2-4c3f-9be8-0abe5f4dec75.png)

Not in Crowdin:
- "Container is full, press out juice and remove the mash before adding more"
- "Release the screw first to add/release fruit"

**Comment by Xandoria** [comment]
Game Version: v1.16.2-rc.1
![beeHive](https://user-images.githubusercontent.com/26251843/151843447-f6a4bd77-2947-46f9-ad85-851b53b4919f.png)
