### ISSUE TITLE
Utilize More CPU Usage, or streamline entity processes. 

### ISSUE THREAD

**Issue by VintageCiv** [anegostudios/VintageStory-Issues#1565]
**Game Version:** 1.15.10  
**Platform:** Windows 
**Modded:**Yes
![Mods](https://user-images.githubusercontent.com/96968356/148871184-7f976ee2-3b47-4e30-9fae-9c9305996961.PNG)
 
Multiplayer

### Description
High TPS from Entity Physics, See attached download

### How to reproduce
1. Run VintageStoryServer.exe
2. Add 20 people
3. Watch the TPS climb, with ServerEntitySimulation(.cs?) being the biggest culprit, almost 50% of the main server thread.

### Expected behavior
I don't know

### Screenshots
See Zip File attached at the bottom

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```
(https://user-images.githubusercontent.com/96968356/148871452-aa70d8f9-8b7a-46d7-b616-3cc260c4dab1.png)
[https://drive.google.com/file/d/1YJWr-1a400W6i2l8_xptVBBEeBwQFSc8/view?usp=sharing] Download ZIP here. This Zip includes a 15 minute benchmark of CPU usage as players get on. I included how many players were on at certain points, notated in the txt file during the benchmark. Run this in Windows Visual Studio. 

Solutions: I think a possible solution would be to run Entity Related Threads ASynchronous to the main.server thread. This would take some load off that thread in general, and something else can just handle entity processing. Another way is to make most heavy process's scale, mostly the ones that should get bigger as more players are on. I am barely touching my CPU, and if the dream is to make this game into that big multiplayer immersion that you guys and we want as a community, Please, Please, Prioritize multiplayer server optimization
[Picture of my CPU's with 14 people on](https://user-images.githubusercontent.com/96968356/148871880-1e6afac4-51c6-400d-8250-f5ebe4f04f13.png)

**Comment by copygirl** [comment]
I doubt making things run asynchronously will be the right choice here. If just 20 players cause this much lag, then it's likely something is taking up much more processing time than it should, and we should address it directly. Of course, spreading tasks across cores is still a good idea. Just, when something is *this* noticeable ... Thank you very much for looking into it!

**Comment by VintageCiv** [comment]
The goal isn't to call you guys out, or tell ya how to run your project. You guys are doing a wonderful job, and it can't be helped that it grew so popular so quickly. Is there a way to give it more juice from the CPU? I'm hardly scraping my resource usage.

**Comment by copygirl** [comment]
There are some server settings which I'm not familiar with that can help in certain situations, though I don't know if it would affect anything in regards to this issue.

**Comment by Aledark789** [comment]
> There are some server settings which I'm not familiar with that can help in certain situations, though I don't know if it would affect anything in regards to this issue. (edit: I'm just trying to respond to this ticket with the information I have. An actual developer will have to check and respond proper, when they find the time.)

I shared Tyron suggestion on magicnumbers tweaks.

Yea they basically experiencing very very similar issues we have on AF also that we reported this fall 2021 in other performance threads on the github.

**Comment by tyronx** [comment]
So, I debugged this now. Your mods massively tank server performance. This is not a vanilla issue.
