### ISSUE TITLE
Open file location button for savegames

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#157]
So players can move/copy their savegames around in their os specific file explorer. 

Windows: https://stackoverflow.com/questions/13680415/how-to-open-explorer-with-a-specific-file-selected/13680458

Linux: Check if exo-open exists, if yes: exo-open --launch FileManager $FILE
Otherwise xdg-open on the save file folder

Mac OS: Needs researching

**Comment by copygirl** [comment]
The command on Mac is just called `open` apparently.

**Comment by Heptagon-ru** [comment]
May I interest the code lords in a request to also implement buttons to open screenshot and video folders?

**Comment by tyronx** [comment]
No need for a particular milestone here. Definitely should add the suggesetion by @Heptagon-ru too ^_^

**Comment by copygirl** [comment]
@tyronx What's the status on this? If not finished, what's missing?

**Comment by Craluminum2413** [comment]
There is such a button for a long time ![image](https://user-images.githubusercontent.com/69315569/120891103-5ce12480-c60f-11eb-8908-0d1f2e2808f1.png)
