### ISSUE TITLE
Snow Particles Falling Through Roof Blocks

### ISSUE THREAD

**Issue by Xaffiri** [anegostudios/VintageStory-Issues#1571]
**Game Version:** 1.16.0
**Platform:** Windows   
**Modded:** No 
**SP/MP:** Multiplayer

### Description
Weather particles like snow seem to fall through slanted roofs and some sold plank blocks. I believe this was sorted out in 1.15 because I haven't seen this happen in a while, but it might be back on 1.16.

### How to reproduce
1. Make building with sloped slate roofing
2. Make sure the season is winter and that snow is falling
3. Watch as particles fall through the roof blocks

### Expected behavior
I would expect weather particles to collect and roll off the top of the block then fall on, not go through them.

### Screenshots
![image](https://user-images.githubusercontent.com/77014327/149204075-1729d5ca-7377-4f0c-8274-b59fc4a39b67.png)
![image](https://user-images.githubusercontent.com/77014327/149204111-f9626f0c-cd96-42a5-90fb-a6320909f656.png)
![image](https://user-images.githubusercontent.com/77014327/149204137-3faf009c-89f2-4602-8946-43a3fbe3a6ef.png)

### Logs
N/A
```

**Comment by Saricane** [comment]
I can confirm. Same for particles dropped by a quern.

**Comment by Craluminum2413** [comment]
Closed due to inactivity
