### ISSUE TITLE
Redmeat stack duplication

### ISSUE THREAD

**Issue by moxian** [anegostudios/VintageStory-Issues#1574]
**Game Version:** 1.16.0
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer

### Description
- had a firepit inventory open with a single redmeat cooking. Had also the inventory open with 2 more pieces of raw redmeat in it.
- right as the piece on the firepit was cooked, shift+clicked on the redmeat 2-stack in the inventory
- ended up with a 2-stack of redmeat *both* in the firepit input slot *and* on the hotbar. So 4 redmeat total (discounting the one that was already cooked)

### How to reproduce
??

### Expected behavior
Conservation of amount of substance.

### Screenshots
Right after the incident:
![20220113-025007-Vintagestory](https://user-images.githubusercontent.com/7831163/149257161-cd0f65b2-f32b-4a93-89d3-343a8e93bd45.png)
(the 2-stack was originally in the top left inventory corner. The mouse cursor is buggy in the screenshots and always appears in the screen center)

### Logs
There's something remotely related in the server-audit (`shift clicked slot 5 in hotbar-AA8mmJjWNyAQwKRN8IhedGp9. Moved 2xRaw redmeat to (2x into backpack-AA8mmJjWNyAQwKRN8IhedGp9)` and `shift clicked slot 4 in backpack-AA8mmJjWNyAQwKRN8IhedGp9. Moved 2xRaw redmeat to (2x into smelting-512950/112/512628)`) but i'm not sure how exactly to interpret those. I'm 100% confident my first shift+click was on the backpack grid, not the hotbar. Which appears to be missing? Either way:

[Logs - Copy.zip](https://github.com/anegostudios/VintageStory-Issues/files/7859474/Logs.-.Copy.zip)

**Comment by moxian** [comment]
Update: after waiting a bit for the meat to get cooked, *both* stacks end up cooked, so i presume one of them is phantom? That would be surprising to experience a desync like that in single player
![20220113-030300-Vintagestory](https://user-images.githubusercontent.com/7831163/149258373-ea95b93e-3859-4bb1-8d4b-c0e82526db36.png)

**Comment by DArkHekRoMaNT** [comment]
Phantom items for multiplayer are normal. It happens sometimes. In any case, I close it as not very relevant, there is no dupe and it is old.
