### ISSUE TITLE
"libpng warning: iCCP: known incorrect sRGB profile" is back

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#158]
On Linux (possibly Mac too?), this is getting spammed into the console when the game starts up.

**Comment by tyronx** [comment]
Ok, running pngcrush again. I  guess it's due to new textures being added

**Comment by tyronx** [comment]
Oh yea, 219 files had a profile again.

**Comment by copygirl** [comment]
Could this be automated so it does it when the game is built?

**Comment by copygirl** [comment]
There's still 6 warnings left.
