### ISSUE TITLE
1.16.0 People who had cooked food in a container/bowl/crock in their inventory/bar in 1.15.10 world then try to logging in on 1.16.0 for first time (continously crash each attempt)

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1586]
**Game Version:** 1.16.0 (for server and players)
**Platform:** Windows (for most clients) and Linux for server
**Modded:** Yes
BetterCratesCC_v1.4.0.zip, 
ExtraChestsCC_v1.5.0.zip, 
tradeomat_v1.16.0-1.6.0.zip, 
CarryCapacity-VS1.16.0-v0.6.4.zip, 
FarmlandDropsSoil-VS1.15-v1.4.0.zip, 
medievalexpansion-3.7.1.zip, 
workbench-expansion-1.4.1.zip, 
bricklayers-0.8.0.zip
**SP/MP:** Multiplayer (AuraFury)  

### Description

People who had cooked food in a bowl(with one of the special bowls from bricklayers...the glazed ones) in their inventory/bar in 1.15.10 world then try to logging in on 1.16.0 for first time (continuously crash each attempt)

Happened to 3 diff users with same crash. While other ppl who can log in and play if they dont have any...i'vetryed with vanilla bowls, it's fine.

Tels#2365 seeking way to fix this, he hasn't found a way.

### How to reproduce
1. Have a 1.15.10 world or a 1.16.0 world and cook a meal in a crockpot
2. Pick it up with a glazed bowl
3. Upon logging from 1.15.10 to 1.16.0 (when we migrate the world) or if they were in 1.16.0 and used one of those bowls they get the error in the logs below and then they cant play anymore as soon as client instance loads up.

To reproduce quicker : can load this world http://bloodgate.com/vintagestory/bowlcrash.zip with [bricklayers 0.8.0]([url](https://mods.vintagestory.at/download?fileid=3744)) and (get a glazed bowl) and you'll see what happens as you take a meal in the bowl to see the bug show up. 

### Logs
[message.txt](https://github.com/anegostudios/VintageStory-Issues/files/7873487/message.txt)
[m00n client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7873489/m00n.client-main.txt)

**Comment by tyronx** [comment]
thanks fro the report, this should be fixed for next release
