### ISSUE TITLE
Auction system fails sanity checks, allows infinite Rusty Gear dupe

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1588]
**Game Version:** 1.16.0
**Platform:** Windows
**Modded:** _Yes_
**SP/MP:**  Multiplayer 

### Description
Server does not check with client to confirm for auction prices. This can lead to some VERY unusual interactions. With a clientside mod that allows for a negative duration, this allows a player to give themselves a nearly infinite amount of Rusty Gears. Not only does the server not detect this, the auction system does nothing to stop it.

### How to reproduce
1. Install the mod linked in this GitHub post.
2. Log onto a friend's server. Possibly Mudwall.
3. Find a trader, and open the Auction interface
4. Set an auction for any item and price, with a negative duration.
5. You will receive rusty gears.

MOD FILE: https://cdn.discordapp.com/attachments/816971526229983282/931665388423495690/auctionweeks_v1.0.0.zip
SOURCE FILE: https://cdn.discordapp.com/attachments/816971526229983282/931708318576156732/src.zip
GENEROUSLY PROVIDED BY KENIGVOVAN

### Screenshots
https://cdn.discordapp.com/attachments/816971526229983282/931707053691535380/2022-01-15_01-29-31.png
https://cdn.discordapp.com/attachments/816971526229983282/931707054110941214/2022-01-15_01-29-39.png
https://cdn.discordapp.com/attachments/816971526229983282/931707054463279214/2022-01-15_01-29-42.png

**Comment by tyronx** [comment]
thanks for the report, this should be fixed for next release
