### ISSUE TITLE
Able to place shelf on the firewood pile

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1595]
**Game Version:** 1.16.1-rc.2  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Make a full firewood pile
2. Try to place a shelf on it
3. Shelf is placed

### Expected behavior
Shelf shouldn't be placed on the firewood pile

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/149659767-ddf3ac5c-286a-4ab3-903e-860a808340a1.png)

**Comment by copygirl** [comment]
Yeah the side of a firewood block should probably not be considered "solid" in that sense.

**Comment by Craluminum2413** [comment]
Since 1.18 firewood pile is now made as ground storage, ground storage sides never considered solid
