### ISSUE TITLE
cpu thread maxed out when paused in singleplayer world (linux mint)

### ISSUE THREAD

**Issue by crustmonkey** [anegostudios/VintageStory-Issues#160]
Processor usage for a given thread is maxed out upon pausing the game in single player, causing my processor fan to get very loud. Unpausing the game causes things to return to normal. No impact on gameplay or ability to use the settings menu or other things when paused. Just loud. Only occurs in singleplayer, not when connected to a server.

Vintage Story 1.5.8
OS: Linux Mint 18.3 Sylvia/4.13.0-32 generic 
Mono Version: Mono JIT compiler version 4.2.1
Video Driver: NVIDIA binary driver 384.130

Will update Mono and a few other things and see if the issue persists.

**Comment by tyronx** [comment]
Oh thanks for the info, i think i know why, will add a high potential fix to 1.6!

**Comment by tyronx** [comment]
1.6 is out, please reopen if the issue persists
