### ISSUE TITLE
baked red meat cannot be sold to a merchant

### ISSUE THREAD

**Issue by Dashutka1** [anegostudios/VintageStory-Issues#1605]
Game Version: 1.16.0
Platform: Windows
Modded: No
Singleplayer

I can't sell 8 baked red meat to a vendor. The meat will rot only after 2,2 days, but he does not take it. Please correct.

![2022-01-18_11-57-16](https://user-images.githubusercontent.com/97848885/149900985-4a249957-c422-458e-8b02-51e2de905cf8.png)
![2022-01-18_11-57-22](https://user-images.githubusercontent.com/97848885/149900990-593d9226-0b01-4ed1-a12f-b14ea0de3b9e.png)
![2022-01-18_11-57-46](https://user-images.githubusercontent.com/97848885/149900995-2eb60458-dfdb-470a-88fe-3a71fba75e98.png)

**Comment by Craluminum2413** [comment]
Why it is closed?

**Comment by Dashutka1** [comment]
> Why it is closed?

Because I found the reason. Sellers do not accept products with an expiration date of less than 50% of the full expiration date.

**Comment by copygirl** [comment]
Definitely something the game should tell you, though.
