### ISSUE TITLE
Auction house traders :dont give back deposit gears when items get sold

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1609]
**Game Version:** 1.16 rc2 
**Platform:** Windows 
**Modded:**
- BetterCratesCC_v1.4.0
- bricklayers-0.8.0
- CarryCapacity-VS1.16.0-v0.6.4
- ExtraChestsCC_v1.5.0
- FarmlandDropsSoil-VS1.15-v1.4.0
- medievalexpansion-3.7.1
- tradeomat_v1.16.0-1.6.0
- workbench-expansion-1.4.1
**SP/MP:** Multiplayer (AuraFury)  

### Description
I put an item for sale for X price. Let's say 5 RG. an other player buys it from the auction house. In X hours, i get the payment delivered and i'll obtain the X price but not what i deposited. So if i select 5 weeks(5 rg) deposit i would actually be at 0 RG from selling an item at 5 RG with 5 weeks period on Auction house.

### How to reproduce
1. Put a item for auction at X price and select 1,2,3,4,5 weeks and the deposit scales 1 RG per week. 5 RG at 5 weeks by default settings.
2. an other buyer buys it for my X price
3. I wait to receive payment of X price
4. I never get the what i deposit for only what the person bought it at X price.
5. in short in my example i ended with 0 RG from selling my item at 5 RG if i put it for sale for 5 weeks...doesnt make sense.

### Expected behavior
Get my deposit back.

** additionally what happends with RG cut of 10% the trader if item is sold less than 10 RG? 9 RG whats 10% of 9 RG? 1 RG min? not clear. What if i sell it for 1 RG, he takes his cut of 1 full RG or its free?
### Screenshots
![2022-01-18_03-17-02](https://user-images.githubusercontent.com/31166271/150084949-fd0f539a-1cc5-4259-bf06-ca8a377ce23a.png)

**Comment by tyronx** [comment]
this is intentional, but the wording is wrong, we'll adjust that
