### ISSUE TITLE
Grief people's claimed land with drawing pigments on surfaces/ Wrong selection of the icon selected in the UI-Box with F)

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1611]
**Game Version:** 1.16 rc2
**Platform:** Windows 
**Modded:** Yes
- BetterCratesCC_v1.4.0
- bricklayers-0.8.0
- CarryCapacity-VS1.16.0-v0.6.4
- ExtraChestsCC_v1.5.0
- FarmlandDropsSoil-VS1.15-v1.4.0
- medievalexpansion-3.7.1
- tradeomat_v1.16.0-1.6.0
- workbench-expansion-1.4.1

**SP/MP:** Multiplayer (AuraFury)  

### Description
-Players without claim access to someone's else claim can draw with pigments by selecting F to pick the Icon (btw it doesnt select the good ones in like 75%+ of the choices)...it selects an other almost everytime for most of them.

### How to reproduce
1. 1 player builds something and claims the area for himself only.
2. 2nd player goes to the 1st player area
2. 2nd player has a pigment with he can draw with (chalk, charcoal, etc.) selected in his bar
3. Hits F and pick one icon he wanna draw with (btw in most of them it wont select the right one)
4. Hits CTRL right click to draw on a possible block like a granite cobblestone on the 1st player claimed castle.

### Expected behavior
_Disallow people without claim access to draw on other people claimed areas
-Fix the selection(F) when you select which icon you wanna draw with)

### Screenshots

![2022-01-16_19-19-14](https://user-images.githubusercontent.com/31166271/150087117-9d6dc124-aea9-43cc-975f-ac9423e71780.png)

**Comment by Konfuz** [comment]
I just checked the symbols, the matrix is transposed (mirrored at the top-left to bottom-right diagonal)

**Comment by DArkHekRoMaNT** [comment]
Can't reproduce in 1.18.5 with Trader claim

**Comment by Konfuz** [comment]
> I just checked the symbols, the matrix is transposed (mirrored at the top-left to bottom-right diagonal)

Can no longer reproduce in a different server (sorry forgot about this ticket for quite some time)
