### ISSUE TITLE
missing texture relise in AuctionCellEntry?

### ISSUE THREAD

**Issue by niciel** [anegostudios/VintageStory-Issues#1613]
**Game Version:1.16.0-rc.6

https://github.com/anegostudios/vssurvivalmod/blob/c1961caf8fecb4a463f34a345206058decde7205/Systems/Auction/AuctionCellEntry.cs#L20
GuiElementRichtext sellerTextElem; need dispose ??

is not disposed at all?
maybe there is some kind of GC mechanism that relese unused textures based on object references but i dont know. 
TraderGui dont realise this texture

**Comment by Aledark789** [comment]
should upgrade to 1.16.1 rc2 https://cdn.vintagestory.at/gamefiles/unstable/vs_install_1.16.1-rc.2.exe
