### ISSUE TITLE
capi.World.AllOnlinePlayers returns null (or it should be sapi.World.AllOnlinePlayers) at Systems/WorldMap/EntityLayer/PlayerMapLayer.cs

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#1616]
**Game Version:** any
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer / Multiplayer (which?)  

### Description
`https://github.com/anegostudios/vsessentialsmod/blob/0d4339c18d3f96e4e4bee489244f9b58f8c80ed0/Systems/WorldMap/EntityLayer/PlayerMapLayer.cs#L100`
Looks like there's no capi.World.AllOnlinePlayers, only sapi.World.AllOnlinePlayers.
It might be the source of the issue where after some time you can't see players icons on the map after some time, unless it's obfuscated but it's not in the playermaplayer.cs.

Probably needs `using Vintagestory.API.Server;` for it to work too.

I gave a look in the code after this message from Apache: https://discord.com/channels/302152934249070593/351624415039193098/933413619675324426

Mind you this is a guess. I might be wrong on that, but it's worth checking.

**Comment by tyronx** [comment]
Intentional. This is client code, you can't access server data on the client like that.
