### ISSUE TITLE
Regrow grass on clay and peat

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#162]
Not sure if it's a feature or a bug, but it's very weird that grass does not grow on harvested/exposed blocks of clay and peat. It only has grass when the map is generated, and it's a little jarring when you start harvesting them.

**Comment by jchappelle** [comment]
We didn't add grass regrowth to clay and peat. This would be an enhancement.

**Comment by tyronx** [comment]
would be nice to have

**Comment by Craluminum2413** [comment]
Close issue? 1.15.0-pre.2
![2021-06-05_14-51-06](https://user-images.githubusercontent.com/69315569/120890763-75503f80-c60d-11eb-97aa-19379472d711.png)
