### ISSUE TITLE
Game doesn't quit properly in Linux

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#164]
This happens both when clicking the "Quit" button in the main menu and closing the window. Music keeps playing if it already started and the process stays open, often still using hundreds of MB of memory. I have to kill it in my task manager.

**Comment by tyronx** [comment]
Since what version does this happen?

**Comment by copygirl** [comment]
As long as I can remember.

**Comment by tyronx** [comment]
I did change all thread to be background threads in 1.6, which means they're suppose to shut down when the parent process shuts down. That had no observable effect for you?

**Comment by copygirl** [comment]
I only had 1.6.0-rc.1 handy at the moment, though I probably also tested a later version from my development environment (directly from source), and yeah, closing the window or pressing Quit keeps the game running in the background.

**Comment by tyronx** [comment]
Maybe related to the missing SIGTERM handler on linux? Does this still happen with the latest version built from source?

**Comment by tyronx** [comment]
no new info in nearly a year, assuming to no longer appear

**Comment by copygirl** [comment]
Ah apologies. It does seem I haven't had this occur to me for a while now, yes.
