### ISSUE TITLE
[Error] Missing mapping for texture code

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1641]
**Game Version:** 1.16.1
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
Getting an error about missing mapping for texture in the logs. I didn't notice anything odd in the game, it ran fine. It looks like it was for one of the chests in a translocator ruin.

Here's the log file: [client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7936910/client-main.txt)

**Comment by copygirl** [comment]
```
25.1.2022 14:40:45 [Error] Missing mapping for texture code floor during shape tesselation of block game:chest-south using shape game:block/wood/chest/normal, or one of its alternates
25.1.2022 14:40:47 [Error] Missing mapping for texture code corners during shape tesselation of block game:chest-south using shape game:block/wood/chest/normal, or one of its alternates
25.1.2022 14:40:48 [Error] Missing mapping for texture code sides during shape tesselation of block game:chest-south using shape game:block/wood/chest/normal, or one of its alternates
```
