### ISSUE TITLE
 [Warning] OpenAL Error during ...

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1643]
**Game Version:** 1.16.1
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
I'm getting many OpenAL warnings/errors in the logs like this:

```
25.1.2022 14:45:41 [Warning] OpenAL Error during construction before of sound game:sounds/walk/gravel4.ogg: InvalidValue
```

### Logs
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7936910/client-main.txt)

**Comment by Aledark789** [comment]
Yea me and bunch others got the same sounds issues as you do.
see
[(https://github.com/anegostudios/VintageStory-Issues/issues/1411)]
It's still present in 1.16.1 for a wide variety of users on vanilla as well.

**Comment by svanheulen** [comment]
Ah sorry, I should have searched before opening this. Definitely a duplicate so I'll close this one.
