### ISSUE TITLE
Cannot specify quantities in ucontents

### ISSUE THREAD

**Issue by Zarkonnen** [anegostudios/VintageStory-Issues#1646]
**Game Version:** 1.16.1
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
When specifying ucontents for liquids, using quantity or stacksize doesn't work to specify the amount you want. Only makefull: true works.

### How to reproduce
Add the following crafting recipe that lets you extract milk from resin for some reason. (Mod that does this is attached.)

```
{
	ingredientPattern: "RB",
	ingredients: {
		"R": { type: "item", code: "game:resin" },
		"B": { type: "block", code: "game:bowl-fired" },
	},
	width: 2,
	height: 1,
	shapeless: true,
	output: {
		type: "block",
		code: "game:bowl-fired",
		attributes: {
			ucontents: [{ type: "item", code: "game:milkportion", quantity: 100 }]
		}
	}
}
```

### Expected behavior
You should be able to craft a bowl containing 1l of milk from a bowl and a resin.

### Observed behaviour
The crafting recipe produces a bowl that looks like it contains milk but is actually empty.

![emptybowl](https://user-images.githubusercontent.com/898230/151130744-34fa3cc7-d64d-47ab-80a4-3ef6b2dc4d28.png)

### Makefull
The same recipe using "makefull: true" works:

```
{
	ingredientPattern: "RB",
	ingredients: {
		"R": { type: "item", code: "game:resin" },
		"B": { type: "block", code: "game:bowl-fired" },
	},
	width: 2,
	height: 1,
	shapeless: true,
	output: {
		type: "block",
		code: "game:bowl-fired",
		attributes: {
			ucontents: [{ type: "item", code: "game:milkportion", makefull: true }]
		}
	}
}
```

![fullbowl](https://user-images.githubusercontent.com/898230/151130703-ad1fd810-cb21-4f34-b27f-511e2ec9f238.png)

But this means there is no way to craft items containing less than their maximum quantity of liquid.

Mod that reproduces problem: [quantitest.zip](https://github.com/anegostudios/VintageStory-Issues/files/7940124/quantitest.zip)

**Comment by Craluminum2413** [comment]
You need to use `litres` instead `quantity`

**Comment by tyronx** [comment]
thanks for the report, the quantity attribute should be working in the next release
