### ISSUE TITLE
Liquid content strings use wrong domain

### ISSUE THREAD

**Issue by Zarkonnen** [anegostudios/VintageStory-Issues#1647]
**Game Version:** 1.16.1
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
When adding a new liquid type in a mod, the game looks for the incontainer-item-*liquidportion* string in the main game domain rather than in the domain of the mod.

### How to reproduce
Add a new liquid type in a mod, eg "poisonportion". Add "incontainer-item-poisonportion" to en.json in your mod.

### Expected behavior
Containers containing the new liquid should be labelled with the string from the en.json.

### Observed
Containers use the fallback item ID instead.

### Workaround
Add the incontainer-item-*liquidportion* string to en.json in the game domain instead.

### Screenshots
![pp1](https://user-images.githubusercontent.com/898230/151132225-eea1e266-1ce1-443a-84e3-53c501a4606d.png)

![pp2](https://user-images.githubusercontent.com/898230/151132239-36769940-3d1f-44ee-9b12-a5d44204aaf4.png)

### Repro Mod
A version of the ranged weapons mod that lacks the workaround strings for poisonportion: 
[RangedWeapons-0.4.5-poisonportionbug.zip](https://github.com/anegostudios/VintageStory-Issues/files/7940189/RangedWeapons-0.4.5-poisonportionbug.zip)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
