### ISSUE TITLE
Game server stuck at 101% processor, when clients try to connect to it, they stuck on message: Connected to server, downloading data, 0 kilobyte received 

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#1648]
**Game Version:** 1.15 - 1.16.1 (current version is 1.16.1)
**Platform:** Linux, Ubuntu 20.04.1 LTS
**Modded:** Yes, current versions: RopeBridges v1.1.0,  hudclockserver 1.1.1, workbench-expansion v1.4.1, fancydoors v1.16.0-1.1.0,         medievalexpansion v3.7.1

**SP/MP:** Multiplayer

### Description
Hello, since upgrade to version 1.15, we're experiencing the following problem on our server:
the game server sometimes stuck at 100 - 103% processor usage. When clients try to connect to it, they stuck on message: Connected to server, downloading data, 0 kilobyte received. When I connect to the VS screen terminal and type a command, it returns nothing.
The problem happends randomly, in average once per 1-2 days.
This is really annoying problem, please what can we do?
I'm ready to assist developers, run some debug or whatewer you want. I'd like to solve the problem.

EDIT: One of our player noticed, that maybe the initiating situation is the following: when he's playing alone on the server and he goes to sleep into his aged wooden bed. Then he notices a message on top right corner saying that server is not responding and showing increasing time. And the VS client does not recover from the situation. So he closes the VS client and try to connect, then happends the situation described above - he cannot connect to server, it stucks on the message "Connected to server, downloading data, 0 kilobyte received". 
Hope that it helps.

Thank you!
Fipil

### Screenshots
Top, see the mono process:
![VSLinuxTop](https://user-images.githubusercontent.com/768590/151228702-a30c512a-7655-478a-a603-249f247c713a.PNG)
A message when clients try to connect:
![VS downloading 0 bytes](https://user-images.githubusercontent.com/768590/151228804-efbda1a4-31f3-4b6e-97ae-48dc72eb70e1.PNG)

### Logs
There is no error log in logs, just ordinary records, no errors nor warnings.

**Comment by tyronx** [comment]
Hi, thanks for the report. this issue should be fixed in 1.16.3, otherwise please reopen the issue.

**Comment by fipil** [comment]
Hi, thanks a lot! Just updated server to 1.16.3 and it seems that the problem is solved.
