### ISSUE TITLE
Cyrillic text reads by server as question marks "??????"

### ISSUE THREAD

**Issue by DoctorLexus** [anegostudios/VintageStory-Issues#1649]
**Game Version:** 1.16.0, 1.16.1 
**Platform:** Mac, Windows  
**Modded:** No
**SP/MP:** Multiplayer

### Description
When you sending cyrillic text to the server as admin from server console – it's shows like "?????" but if you type cyrillic text in game in chat – it shows as "??????" in server console too. At the screenshot I've sent "/announce тест test" and server just show english "test" as normal, but cyrillic is "???????"

### How to reproduce
1. Open server console
2. Type some cyrillic text (ex. Russian "test") - "тест"
3. Text transforms to "??????" and shows in the game and console as question marks

### Screenshot
![image](https://user-images.githubusercontent.com/64277255/151246871-3984e253-0fd3-474d-925a-e4dc35009101.png)

**Comment by copygirl** [comment]
How are you accessing the server console? Is this the [official server hosting](https://www.vintagestory.at/store/product/7-30-days-simple-server-hosting/) provided by the developers? From my (limited) knowledge, this could be the terminal / console emulator not supporting UTF-8 or Unicode, or something getting lost when it's being displayed on the web page..?

**Comment by DoctorLexus** [comment]
It's hosting on g-portal website, so I need to write to this site's support?

**Comment by copygirl** [comment]
Contacting third-party support was going to be my recommendation (if it was third-party).

When you type cyrillic text ingame, it shows up fine to the other players, right? I'm guessing when you type into the console, it doesn't know what to do with the Unicode symbols so it just turns them into question marks. When the server reads the command from the console it already doesn't know they used to be Cyrillic text.

Just my guess.

**Comment by copygirl** [comment]
I will close the issue for now since I'm 90% sure it's not an issue with the game itself.

Do let us know if you get a response from G-Portal.
