### ISSUE TITLE
Wooden path is invisible when there is a solid block above it

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1652]
**Game Version:** 1.16.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a wooden path
2. Place a solid block above
3. The wooden path is invisible

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/151593036-2ee25801-24cb-4e9a-a208-49a26105b0b8.png)

**Comment by RedramVS** [comment]
This appears to have been addressed in 1.18 or earlier.
![Vintagestory Screenshot 2023 04 20 - 10 11 25 74](https://user-images.githubusercontent.com/36369046/233409847-842ce5d6-abf6-4c15-b4c2-418d4d477fdb.png)
