### ISSUE TITLE
Chest causes server and client crash w/o any errors

### ISSUE THREAD

**Issue by TarikYuzkiv** [anegostudios/VintageStory-Issues#1653]
**Game Version:** 1.16.1
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Multiplayer

### How to reproduce
1. Place a double chest
![step1](https://user-images.githubusercontent.com/11008996/151603511-f165fa53-b00d-4312-8ed6-86d5496baab3.png)
2. Burn it down
![step2](https://user-images.githubusercontent.com/11008996/151603519-edc19241-b835-4ec4-863f-a0392cf92fca.png)
3. Place a new double chest near the old
![step3](https://user-images.githubusercontent.com/11008996/151603521-5198e28b-dad4-446e-be89-cf2f0a84228c.png)
4. We get a broken client and a server that does not respond to commands. 
![step4](https://user-images.githubusercontent.com/11008996/151603523-922ddd66-35f2-4886-b208-a55486a18dc4.png)

**Comment by TarikYuzkiv** [comment]
Edit step 3: we need to open chest and wait ~5sec

**Comment by TarikYuzkiv** [comment]
Edit step 3: after this we need to open chest and wait ~5sec (and maybe write some command in chat)

**Comment by tyronx** [comment]
oh wow, nice find, thanks. This should be fixed for next release, which I'll prioritize now
