### ISSUE TITLE
Can milk sheep infinitely

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#1656]
**Game Version:** 1.16.1
**Platform:** Windows
**Modded:** Yes CarryCapacity 0.6.4; HUD Clock 2.6.0
**SP/MP:** Singleplaye

### Description
You can milk ewes which are lactating, but not milkable, thus allowing sheep to be milked infinitely. It plays the animation, but doesn't make any sound. As I'm aware, works on all generations up to 4 (that's as far as I got).

### How to reproduce
Reproduced in a creative world, not working all the time.
1. Obtain a ewe which is lactating
2. Try milking her (the milking doesn't have to be successful)
3. Then milk the same ewe again.
4. The animation will play though no sound is made. The bucket gets filled with milk

### Expected behavior 
Milking only working when sheep are milkable.

### Video
https://youtu.be/sb6MMGqIRV4

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
