### ISSUE TITLE
Pit kiln has placeSoun for sticks instead placeSound

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1658]
**Game Version:** 1.16.2-rc.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open `survival/blocktypes/wood/pitkiln.json`
2. Look at stick entry in the `buildMats/sticks`
3. It has `placeSoun` instead `placeSound`

**Comment by Craluminum2413** [comment]
It might be worth reclassifying the issue, because it looks like `placeSound` in `pitkiln.json` does nothing.
The only way to set placeSound is to put it directly into attributes of item file itself

**Comment by tyronx** [comment]
Indeed, I've removed those 2 properties now.
