### ISSUE TITLE
Hotbar toolip hides health info

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#166]
1.6 rc1, PTS

When selecting items in hotbar, e.g. by mouse wheel, their tooltip covers and hides some of health bar and digital health value, for few seconds.

![2018-08-01_19-21-23](https://user-images.githubusercontent.com/25122345/43538328-5d27ff54-95ca-11e8-92e2-d1f08cc8557f.png)

**Comment by tyronx** [comment]
fixed this for rc.2, thanks
