### ISSUE TITLE
Upgrade harmony to fix SEGSEGV with mods on Linux

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/VintageStory-Issues#1664]
**Game Version:** 1.16.2-rc1
**Platform:** Linux
**Modded:** Yes (lots)
**SP/MP:** Multiplayer

### Description
There was a nasty [bug](https://github.com/pardeike/Harmony/issues/414) with Harmony on Linux what would end up causing buffer overruns in mono. Most notably that caused crashes with the VSHUD mod.

The Harmony bug was fixed in Harmony 2.2. I've been manually upgrading to that version for a while, and I haven't had any problems. Please make that default version in VS so that other Linux users don't have to discover the old bug and manually upgrade their installs.

**Comment by tyronx** [comment]
To which one did you update? the net45 one?

**Comment by bluelightning32** [comment]
That's right, `net45/0Harmony.dll` from inside the `Harmony.2.2.0.0.zip` release.

**Comment by tyronx** [comment]
Oh wow, i just read up on the issue, you made a highly detailed bug report and even PRed a fix to Harmony. Nice work!

**Comment by tyronx** [comment]
I'm a bit unsure if i should upgrade harmony for 1.16.x or reserve it to 1.17.x

Are you awere of any incompatibilites with existing mods?

**Comment by bluelightning32** [comment]
I use it with lots of mods on Linux, and I haven't found any problems with Harmony. I didn't test on Windows or Mac.

**Comment by tyronx** [comment]
thanks, will be included in the next release
