### ISSUE TITLE
Dupe with crates

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1666]
**Game Version:** 1.16.2-rc.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a chest
2. Place a chute above the chest
3. Place a crate above the chute
4. Put items into crate
5. Items go to chest through chute, but items in the crate are remained
6. Take items out the chest and the crate
7. You have duped items

### Videos

https://user-images.githubusercontent.com/69315569/152078668-a8c09136-50ac-42e4-8221-ee30d95f9920.mp4

**Comment by tyronx** [comment]
Not a dupe bug. The client side count on the crate just doesn't update.

**Comment by tyronx** [comment]
Fixed the fact that its not updating the display for next release
