### ISSUE TITLE
Burned out torches can be lit

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1669]
**Game Version:** 1.16.3
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
By "burned out" I mean when they get charred after a few days and breaking them doesn't return the torch to you. I'm not talking about when they get put out by rain/water. You can light it by shift + right-clicking on it, and it gets transformed into a working torch again.

### How to reproduce
1. Place a torch
2. Wait for it to burn out
3. Shift + right-click on it with a lit torch to restore it to a working torch

### Expected behavior
You should not be able to light burned out torches

**Comment by tyronx** [comment]
🤦‍♂️ 

Thanks for the report, will be fixed next release
