### ISSUE TITLE
Near search propick show dynamic info

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1673]
**Game Version:** 1.16.3
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Any

### Description
When the ore is depleted, this shows the ore in dynamic mode, although traces in the surrounding rock should show in its original state

### How to reproduce
1. Find ore node and use propick. It will shows rich node
2. Excavate node
3. It shows ore is excavated

### Expected behavior
It must shows still rich node nearly

**Comment by copygirl** [comment]
This might be intended, even if it isn't particularly realistic. The near search mode is an optional feature that isn't quite in the realm of realism, just makes it easier to pinpoint the exact location of actual ore blocks. I'll let the team speak for themselves however.

**Comment by DArkHekRoMaNT** [comment]
I think copygirl's explanation is enough. Closed like staled
