### ISSUE TITLE
Game progress lost on save if low on disk space. No error or warning shown.

### ISSUE THREAD

**Issue by skegg99** [anegostudios/VintageStory-Issues#1679]
Version: v1.16.1
Platform: Windows 10
Mods:
![image](https://user-images.githubusercontent.com/5307515/152698269-55707073-56d0-4857-9fde-df65923be5fa.png)
SinglePlayer

Game progress silently lost if low on disc space. I had about 1.6 GB disc free, experienced lost progress after game save several times, no warning showed. I have also noticed inconsistent save state: players gear changes were lost, changes in house saved. Cause could  only be discovered in log files:

6.2.2022 17:23:10 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exit request by client
6.2.2022 17:23:10 [Notification] Entering runphase Shutdown
6.2.2022 17:23:10 [Notification] [metalrecovery] Persisting configuration.
6.2.2022 17:23:10 [Notification] Defragmented listener lists
6.2.2022 17:23:10 [Fatal] Disk space is below 200 megabytes. A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json. Will kill server now...
6.2.2022 17:23:10 [Error] Exception thrown during handling event OnGameWorldBeingSaved: System.Exception: Out of disk space!
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldBeingSaved()
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved()
6.2.2022 17:23:10 [Event] Shutting down 5 server threads... 
6.2.2022 17:23:10 [Event] Killed console thread
6.2.2022 17:23:10 [Event] All threads gracefully shut down
6.2.2022 17:23:10 [Event] Doing last tick...
6.2.2022 17:23:10 [Event] Stopped the server!

Expected: a clear error shown.

**Comment by tyronx** [comment]
By default, the most you loose is 5 minutes of progress. And it kills the server, not sure how that is silent?

**Comment by skegg99** [comment]
> By default, the most you should loose is 5 minutes of progress, did you loose more? And it kills the server, not sure how that is silent?

Autosaves also failed with the same error. No errors were shown except for logs. Thats what I call silent.

6.2.2022 17:10:39 [Notification] Autosaving game world. Notifying mods, then systems of save...
6.2.2022 17:10:40 [Notification] Defragmented listener lists
6.2.2022 17:10:40 [Fatal] Disk space is below 200 megabytes. A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json. Will kill server now...
6.2.2022 17:10:40 [Error] Exception thrown during handling event OnGameWorldBeingSaved: System.Exception: Out of disk space!
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldBeingSaved()
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved()
6.2.2022 17:10:40 [Notification] A client reconnected, resuming game calendar.
6.2.2022 17:10:40 [Notification] Server ticking has been resumed
6.2.2022 17:15:41 [Notification] Server ticking has been suspended
6.2.2022 17:15:41 [Notification] Autosaving game world. Notifying mods, then systems of save...
6.2.2022 17:15:41 [Notification] Defragmented listener lists
6.2.2022 17:15:41 [Fatal] Disk space is below 200 megabytes. A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json. Will kill server now...
6.2.2022 17:15:41 [Error] Exception thrown during handling event OnGameWorldBeingSaved: System.Exception: Out of disk space!
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldBeingSaved()
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved()
6.2.2022 17:15:41 [Notification] A client reconnected, resuming game calendar.
6.2.2022 17:15:41 [Notification] Server ticking has been resumed
6.2.2022 17:20:43 [Notification] Server ticking has been suspended
6.2.2022 17:20:43 [Notification] Autosaving game world. Notifying mods, then systems of save...
6.2.2022 17:20:43 [Notification] Defragmented listener lists
6.2.2022 17:20:43 [Fatal] Disk space is below 200 megabytes. A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json. Will kill server now...
6.2.2022 17:20:43 [Error] Exception thrown during handling event OnGameWorldBeingSaved: System.Exception: Out of disk space!
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldBeingSaved()
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved()
6.2.2022 17:20:43 [Notification] A client reconnected, resuming game calendar.
6.2.2022 17:20:43 [Notification] Server ticking has been resumed
6.2.2022 17:22:55 [Notification] Server ticking has been suspended
6.2.2022 17:23:10 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exit request by client
6.2.2022 17:23:10 [Notification] Entering runphase Shutdown

**Comment by tyronx** [comment]
Oh wow strange. Yea that's bad. Will look into it

**Comment by tyronx** [comment]
thanks for the report. This should be fixed in 1.16.4
