### ISSUE TITLE
Using the CompatibilityLib method of patching files, JsonPatch Loader does not load patches between mods upon first world load. 

### ISSUE THREAD

**Issue by TaskaRaine** [anegostudios/VintageStory-Issues#1680]
**Game Version:** 1.16.0+
**Platform:** Windows 
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
When a mod tries to make compatibility patches by using the CompatibilityLib method of compatibility patching, the patches won't be applied when a world has been loaded for the first time after launching the game. However, the patches will properly apply when the user exits to the title screen and loads the world again.

### How to reproduce
1. Download the two mods attached to this issue and place them in your mods folder
2. Launch Vintage Story and, in setting, enable block info help(this helps visualize the issue).
3. Enter Creative mode.
4. Search for any bark basket from Ancient Tools and place it in world.
5. Look at the bark basket. The Carryable behavior from Carry Capacity hasn't been applied to the block via a patch and, therefore, there is only a right click interaction option. The block cannot be picked up by pressing shift and holding right click with an empty hand, either, as is intended.
6. Exit the world to the title screen.
7. Load the same world.
8. Look at the bark basket again. You should now see an extra interaction help option and, following those instructions, you should be able to pick up the basket. The patch has now been applied on second world load.

### Expected behavior
See above ^

### Screenshots
First Load:
![Carryable Not AppliedJPG](https://user-images.githubusercontent.com/53409481/152843805-64692b93-217e-4070-8c0d-9b1091f5a1b4.jpg)

Second Load:
![Carryable AppliedJPG](https://user-images.githubusercontent.com/53409481/152843825-47774b72-4b86-4e2a-8c7e-44a39f4bc359.jpg)

### Logs
The following logs help explain the issue. The Loader finds 93 patches on first load, and 94 patches on second load. There are no patch errors logged that indicates any issues with a patch being applied to the bark baskets.

Server Main First Load:
```
[Notification] JsonPatch Loader: 93 patches total, successfully applied 92 patches, missing files on 1 patches, unmet conditions on 9 patches, no errors
```
Server Debug First Load:
```
7.2.2022 11:32:06 [VerboseDebug] Patch file game:patches/playertemporalstability.json, patch 0: Unmet IsValue condition (true!=False)
7.2.2022 11:32:06 [VerboseDebug] Patch file game:patches/playertemporalstability.json, patch 1: Unmet IsValue condition (true!=False)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 0: Unmet IsValue condition (false!=True)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 1: Unmet IsValue condition (false!=True)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 2: Unmet IsValue condition (false!=True)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 3: Unmet IsValue condition (false!=True)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 4: Unmet IsValue condition (false!=True)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/item/resources/bark.json, patch 0: Unmet IsValue condition (false!=True)
7.2.2022 11:32:06 [VerboseDebug] Patch file ancienttools:patches/item/resources/bark.json, patch 1: Unmet IsValue condition (false!=True)
7.2.2022 11:32:07 [VerboseDebug] Patch 10 in carrycapacity:patches/carryable.json: File game:blocktypes/wood/crate.json not found
```
Server Main Second Load:
```
[Notification] JsonPatch Loader: 94 patches total, successfully applied 93 patches, missing files on 1 patches, unmet conditions on 9 patches, no errors
```
Server Debug Second Load:
```
7.2.2022 11:36:22 [VerboseDebug] Patch file game:patches/playertemporalstability.json, patch 0: Unmet IsValue condition (true!=False)
7.2.2022 11:36:22 [VerboseDebug] Patch file game:patches/playertemporalstability.json, patch 1: Unmet IsValue condition (true!=False)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 0: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 1: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 2: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 3: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/block/salve.json, patch 4: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/item/resources/bark.json, patch 0: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch file ancienttools:patches/item/resources/bark.json, patch 1: Unmet IsValue condition (false!=True)
7.2.2022 11:36:22 [VerboseDebug] Patch 10 in carrycapacity:patches/carryable.json: File game:blocktypes/wood/crate.json not found
```
[CarryCapacity-VS1.16.0-v0.6.4.zip](https://github.com/anegostudios/VintageStory-Issues/files/8017509/CarryCapacity-VS1.16.0-v0.6.4.zip)
[AncientTools_V1.3.1.zip](https://github.com/anegostudios/VintageStory-Issues/files/8017510/AncientTools_V1.3.1.zip)

**Comment by tyronx** [comment]
thanks for the report this should be fixed for 1.17
