### ISSUE TITLE
Spoiled milk in barrel gives 512L of rot

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#1683]
**Game Version:** 1.16.3
**Platform:** Linux (Ubuntu)   
**Modded:** Yes (Medieval expansion, HUD clock, Fancy doors, )  
**SP/MP:** Multiplayer

### Description
Spoiled milk in barrel gives over 500 L of rot after barrel "cutting" with axe.

### How to reproduce
1. Fill barrel with milk
2. Wait for milk spoiling
3. Cut barrel with axe

### Expected behavior
You should get much lower amount of the milk

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed in the next release
