### ISSUE TITLE
servings of - translation

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1685]
**Game Version:** 1.16.4-rc1
**Platform:** Linux (KDE neon 20.04 5.23 )
**Modded:** No
**SP/MP:** Singleplayer

### Description
"servings of" on Cooking Pot is not translated

### How to reproduce
1. Make more servings in a Cooking pot
2. Place it on earth
3. Look at the information (tested with slovak translation)

### Expected behavior
Should be translated

### Screenshots
![2022-02-09_20-27-48](https://user-images.githubusercontent.com/47914240/153276733-78847b40-2001-4159-a39f-62bcce4ba767.png)

**Comment by l1ving** [comment]
Followed up, daretmavi added translations for these but they don't appear to be approved. 

`{1} porcie {0}` is correct for singular, `{1} {0} porcií` is correct for plural

**Comment by daretmavi** [comment]
Is not that simple.
Plural is 2-4 porcie and 5-... porcií 
This is why I changed the translation to
{1}, porcie: {0}

It is not that elegant like eng original, but at least not totally wrong.

What does it mean "they don't appear to be approved" anyway?

**Comment by daretmavi** [comment]
In crowdin, it is translated.

**Comment by l1ving** [comment]
Ah, my current selected language got reset. I do see it now, thank you 
![image](https://user-images.githubusercontent.com/17222512/156388677-831578ac-e317-4f02-81c7-22f739018964.png)

**Comment by daretmavi** [comment]
Hmmm,

this is what I see
![obrázok](https://user-images.githubusercontent.com/47914240/156389369-20441c84-0d9a-438a-9bbd-5f7bc2d8899c.png)

**Comment by daretmavi** [comment]
I'll try to remove it and write again

**Comment by daretmavi** [comment]
OK, I removed old, and wrote it again.
Could you please check?

![obrázok](https://user-images.githubusercontent.com/47914240/156389959-6e49d0e2-6dae-4a8c-b727-0dd254c3152f.png)

**Comment by l1ving** [comment]
This one is fixed 
![image](https://user-images.githubusercontent.com/17222512/156391000-7fd42b9d-6f9f-4d79-8b1d-3e1f767e5f5d.png)

The following are not fixed:
- `{0} servings of {1}.` (note the period at the end, different from the one you just edited)
- `Will create {0} servings of {1}`
- `{0} serving of {1}
Temperature: {2}{3}{4}`
- `{0} servings of {1}
Temperature: {2}{3}{4}
`

**Comment by daretmavi** [comment]
Why is it crowdin doing to me (cry cry cry)?
I'm going to rewrite all of them.

**Comment by daretmavi** [comment]
OK, I updated all `servings` strings.

**Comment by l1ving** [comment]
All fixed on my end!
