### ISSUE TITLE
Buried in earth after game reload

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1687]
Game Version: 1.16.4-rc1
Platform: Linux (KDE neon 20.04 5.23 )
Modded: No
SP/MP: Singleplayer

### Description
One block in earth after game reload.

### How to reproduce
1. Start new game (survival or creative, does not matter)
2. exit the game
3. load game again
4. Your legs are now buried in earth

### Expected behavior
You should stay on ground

### Screenshots
![2022-02-10_11-02-44](https://user-images.githubusercontent.com/47914240/153384091-cbf49ed3-d8c7-4a83-b064-3b16cf76ed55.png)

![2022-02-10_11-06-34](https://user-images.githubusercontent.com/47914240/153384773-6436b050-41a4-47f6-9f2f-09eaa9f4dbe8.png)

**Comment by Chrysandros** [comment]
I get the same. Sunk one block into the ground on load. Although I'm on Win11.

**Comment by daretmavi** [comment]
Seems to be resolved with 1.16.4
