### ISSUE TITLE
Liquid lost when partially filled containers are stacked

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1688]
**Game Version:** 1.16.4-rc1
**Platform:** Linux
**Modded:** No
**SP/MP:** Singleplayer

### Description
If you have a partially filled bucket of any liquid and pick up a completely full bucket of the same type of liquid they will stack together in your inventory and then both buckets will have only the amount of the partially filled bucket. This also happens with bowls and jugs. Issue #862 can interfere with activating this bug.

### How to reproduce
1. Place a bucket with 10 liters of apple juice on the ground.
2. Place a bucket with 5 liters of apple juice on the ground.
3. Pick up the bucket with 5 liters of apple juice.
4. Pick up the bucket with 10 liters of apple juice.
5. You now have a stack of 2 buckets with 5 liters of apple juice each, losing 5 liters of apple juice.

### Expected behavior
Containers with different amounts of the same liquid should not stack with each other.

**Comment by svanheulen** [comment]
I was just able to get it to happen with honey as well, but it doesn't always happen.

**Comment by andyneff** [comment]
I am not able to get step 4 to stack in 1.16.5. I have to switch to an empty hotbar to pick up the second bucket, and that does not stack.

**Comment by DArkHekRoMaNT** [comment]
Fixed together with #1862
