### ISSUE TITLE
Sealed crocks stay sealed after removing a meal

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1690]
**Game Version:** 1.16.4-rc1
**Platform:** Linux
**Modded:** No
**SP/MP:** Singleplayer

### Description
If you use a bowl to remove a meal from a sealed crock, it will stay sealed.

**Comment by copygirl** [comment]
Just to confirm: Does the sealed status persist after reloading the world? (Otherwise it could be a sync issue, instead.)

**Comment by svanheulen** [comment]
Yes, after restarting the game, the crock is still sealed.

**Comment by JustForVS** [comment]
Had the same right now in v 1.17.4, so it's still an issue.

**Comment by Craluminum2413** [comment]
Duplicate of #852
