### ISSUE TITLE
Game client dont unload memory data

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1694]
**Game Version:** 1.16.3
**Platform:** Windows 
**Modded:** Yes 
**SP/MP:** Any

### Description
when you exit the main menu, the data from the RAM is not unloaded, which causes the client to hang heavily.
Some mods, when adding several vanilla options (for example, craliumium mods), can easily add 2 gigabytes of RAM (for me, Windows optimizes swap in RAM and any load is noticeable without swap file analysis tools). Naturally, this is noticeable when using mods. Please optimize the loading of new items

### How to reproduce
1. Make client with any mods
2. Check ram load at Task Manager
3. leave from game to main menu
4. check ram again

**Comment by Craluminum2413** [comment]
Fixed in 1.20.0-pre.4
