### ISSUE TITLE
Improve crash experience

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#17]
Right now, when the game crashes, all you get is an ugly error message and no additional information is included for the developer to debug the issue, other than the stacktrace itself. Also, the `VintagestoryCrash.txt` file includes all past crashes, so it might be a bit annoying (or confusing) to find the most recent crash and upload only that.

It would be nice to instead get a window with the crash information and a bunch of additional information, such as operating system, hardware, drivers, basic information about the state of the game (mods, single/multiplayer?, ...), when the crash occured (rendering, update, loading mods, handling input, interacting with a block, ...), and so on. This should also be written to a dedicated crash folder, which would be how the information is accessed on a server.

The user should see an option to upload the crash log and links to where it can be reported.

**Comment by Heptagon-ru** [comment]
Also I see that on my system some crash info is in Russian. Maybe sometimes it can be uncomfortable for devs to read this. Should be forced to English somehow.

**Comment by tyronx** [comment]
Huge problem with that: Creating the window :/
Could use System.Windows.Forms, but it is unsupported in 64bit mode on macos....

**Comment by copygirl** [comment]
Is it possible to create another window with OpenTK?

**Comment by tyronx** [comment]
Yea but like, you would want to have a textarea and some buttons. Ideally you save yourself the work to render that extra with opentk and use something native

**Comment by tatsu011** [comment]
At the very least I could make each crash a separate text file and mark in a timestamp.

**Comment by tyronx** [comment]
we already have that

**Comment by tyronx** [comment]
Current status: This is implemented, but i think it's broken on linux and/or mac because it derps up from the whole stack trace passed as a command argument. Should probably piped into it or something like that. 
@tatsu011 feel free to work on that and other tasks for another 10 hours with compensation.

**Comment by tatsu011** [comment]
The next version released will have a different method of piping into the crash reporter- This will be passed into a file that will be removed once the crash reporter is closed.  I'm gonna leave this as In-Progress for now, as we will have future plans for this.

**Comment by tyronx** [comment]
Assuming this to work correctly now.
