### ISSUE TITLE
Last deleted waypoint still shown and crashes game

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#170]
1.6 rc1, PTS

1. Create waypoint via /waypoint add aqua wp1
2. List them via /waypoint list
3. Delete it via /waypoint remove 0

After that it is still visible on the map, and as soon as I close and reopen the map by cycling its modes, game crashes. I dont see any fresh record of the crash in any logs, except some errors in client-main.

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/2250705/client-main.txt)

**Comment by tyronx** [comment]
Ok, should be fixed for rc.2, thanks
