### ISSUE TITLE
Game crashing when loading in world

### ISSUE THREAD

**Issue by Netskimmer** [anegostudios/VintageStory-Issues#1703]
The game keeps crashing when I load into a world. I was able to play without issue with version 1.13.?, but was prompted to update to 1.16 and did so. I started with updating, but then did a fresh install. I created a new world, but it is still crashing. Also restarted several times throughout the process.

**Comment by copygirl** [comment]
Can't help much without you providing the crash report.

Have you used mods before? Make sure to remove those, as those old mods are likely not compatible with the new version of the game. Mods, along with worlds, are stored in the "user folder" for Vintage Story which is not removed when you uninstall the game.

**Comment by Netskimmer** [comment]
I didn't think I was using any mods, but it's been a while. Deleted the 'Mod' folder which caused the game to crash on launch. Did another fresh install which seems to have done the trick. Thank you for the help.
