### ISSUE TITLE
Double hit projectiles

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1708]
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** Any
**SP/MP:** Any

### Description
Projectiles like arrow or spear hitting double after meeting hitbox

### How to reproduce
1 throw spear or shoot arrow with bow to target entity
2 projectile double hitting traget while falling from hands and falling after hit the hitbox

### Expected behavior
one time hit to the target

**Comment by Craluminum2413** [comment]
Duplicate of #811

**Comment by copygirl** [comment]
By the way: `1.16.4` is not out yet. Did you mean one of the release candidates? Please specify the full version, such as `1.16.4-rc.2`. It's important.
