### ISSUE TITLE
Quern grinding issues

### ISSUE THREAD

**Issue by Grzegorz1984** [anegostudios/VintageStory-Issues#1709]
**Game Version:** 1.16.3  
**Platform:** Windows 10 Home x64   
**Modded:** No 
**SP/MP:**  Multiplayer - own server

### Description
While grounding lime in quern only half of the grounded material exits quern. So every second grounding is successful.
While grounding salt only quern only quarterof the grounded material exits quern.  So every fourth grounding is successful.

### How to reproduce
1. Run quern connected to windmill
2. Fill it up
3. Se results, lot of grounded material doesn't appear. Wasting material put into quern.

### Expected behavior
Every ground should give yeld. It was running correctly in pre 1.16

### Screenshots
![2022-02-16_00-34-31](https://user-images.githubusercontent.com/7847820/154168852-c31e0b79-7613-4e20-89e2-64f5a9ea015b.png)

**Comment by Craluminum2413** [comment]
It is intentional. You blocked two sides of the quern and expect to get all material, but since you didn't add 4 hoppers around it, you lost the half

**Comment by copygirl** [comment]
Which, honestly, is a bit strange. There should be some indication that items are going to be lost. I'll leave the issue open so a team member can respond.

**Comment by Grzegorz1984** [comment]
Hi, in both cases i have 3 sides blocked so the output comes to one hopper. It has always worked correctly pre 1.16 the material came out on the side that has hopper. Nothing was lost. I can add another screenshot from the other quern that processes lime.

**Comment by copygirl** [comment]
I know that it has been said before (unsure if by the team or not) that a blocked side will delete the items that try to exit there. If you are sure of your claim, would you want to test it in previous versions?

**Comment by tyronx** [comment]
No items are lost, the process only resets,  which is intentional

**Comment by tyronx** [comment]
this behavior is also documented in the handbook, so I don't see anything that should be majorly changed here, so closing this issue.
