### ISSUE TITLE
Fence gate placement in not intuitive

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#171]
1.6 rc1, PTS

When placing a wooden fence gate, it seems to be always placed looking at one direction, unless there is another fence gate nearby, turned in such a way that a double-gate will be created after placing the second one :)

So the alone-placed gate is not influenced by a fence nearby, or an already placed gate with the tall side closer to the new gate, or player's look (e.g. like in MC where the door hinges will be at the block side which is closer to the player sight).

This seems a bit unintuitive when placing gates after a long gaming break. Also now the fence gates have unequally tall sides even for a single gate, so the question "how to place" actually appears.

Maybe a single gate should have equally tall sides, until it is paired with another gate?
Also maybe some more intuitive placing rules whould be added.

Or maybe this is not an important issue.

Screenshots show that 
1. (The nearest gate+fence) Gate doesnt care about already placed fence.
2. (The further fence+gate+gate) Placing the second gate near an "incorrectly" placed first gate does not merge them into a double gate.

![2018-08-01_22-34-11](https://user-images.githubusercontent.com/25122345/43544562-03c0cc0e-95dc-11e8-8c14-69f8a3d58f28.png)

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
