### ISSUE TITLE
Entities, when scaled up using the size property on the client, emit bloom.

### ISSUE THREAD

**Issue by TaskaRaine** [anegostudios/VintageStory-Issues#1710]
**Game Version:** 1.16.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Entities that are scaled up beyond their original model size seem to emit a 'reflective glow' that, after experimentation, seemed to be a bloom effect. This is very prevalent on the male polar bear, which is scaled up 1.40x in vanilla. It's most easily seen in the mornings/evenings when the sun is shining directly against a flat face on the animal. The male brown bear similarly emits bloom, at 1.25x scale. Any animals scaled below 1 appear normal. No properties of the bears have been modified from vanilla to demonstrate this.

### How to reproduce(Vanilla Method)
1. Launch the game into a creative world.
2. Grab a polar bear from the creative menu and spawn it in world.
3. Ensure that the time is morning/evening for easiest viewing.
4. Wait for the bear to show a side directly to the sunlight, following closely(for easiest viewing).
5.  Pause the game.
6. Click Settings and toggle Bloom several times. You should see the creature emitting an unnatural glow. 

### How to reproduce(Modded Method/Best Method)
1. Apply a patch OR change modify the chicken-hen JSON file that defines the chicken-hen entity and add a `size: 5` property to the client object in the file.
2. Launch Vintage Story into a creative world.
3. Grab a hen from the creative menu and spawn it in world.
4. Ensure the Bloom setting is on. 
5. Watch the sides of Chickenzilla glow like the surface of the sun as she turns majestically towards the light.
6. Go back into settings and toggle Bloom several times. The effect should be very prevalent here.

### Expected behavior
Just like their smaller counterparts, scaled up entities shouldn't emit a glow-like bloom.

### Screenshots

Bloom Off:
![AmbientBloomOff](https://user-images.githubusercontent.com/53409481/154185760-46b31806-3e33-4bf4-9881-746d7c54f0d5.png)

Bloom On + 0% Ambient Bloom:
![AmbientBloomOn](https://user-images.githubusercontent.com/53409481/154185739-26b94fc4-9b9d-43b9-9256-a37d4fd630ad.png)

**Comment by TaskaRaine** [comment]
Hmm... but, when a white chicken gets scaled up near to the size of a polar bear, the effect is _intense_. Like, multitudes more intense than anything on the bear. 
![ChickenBearComparison](https://user-images.githubusercontent.com/53409481/154316004-72803bf0-d57b-4e63-b16a-5770e807c4d6.png)
.

**Comment by tyronx** [comment]
true, that does look too intense

**Comment by copygirl** [comment]
Does the scaling also scale the normal vectors or something? Maybe that could cause the math to get weird.

**Comment by tyronx** [comment]
no, the scale happens on a transformation matrix thats passed onto the shader, not on the mesh itself
