### ISSUE TITLE
Allow placing small objects on sideways slabs

### ISSUE THREAD

**Issue by l1ving** [anegostudios/VintageStory-Issues#1711]
**Game Version:** 1.16.3
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  `farmlanddropssoil`
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

### Description
Explain the issue you're running into.

Unable to place small objects (bowls, crocks, etc) on the sides of slabs.

### How to reproduce

Try to place in an area like so:

![image](https://user-images.githubusercontent.com/17222512/154265571-bc66c2f5-24c2-454b-a156-a972f4ff4577.png)

### Expected behavior

Able to place it in a 2x1, similar to the 2x2 here:

![image](https://user-images.githubusercontent.com/17222512/154265599-3d6e28f8-9041-45c4-b79f-f1c2c81b3f91.png)

**Comment by copygirl** [comment]
Agreed, but this is a suggestion more than an bug. Please post in the forums or on Discord.
