### ISSUE TITLE
Broken or missing wind animations for flower pots and planters

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1715]
**Game Version:** 1.16.4-rc2
**Platform:** Linux
**Modded:** No
**SP/MP:** Singleplayer

### Description
Flowers are missing wind animations when placed in a planter or flower pot.
Bamboo saplings have messed up wind animations when placed in a planter or flower pot, but other tree saplings seem to have correct wind animations.
![flower_pot](https://user-images.githubusercontent.com/533741/154360310-2a68be42-02f6-4ee4-b697-13af5d821aff.png)

**Comment by DArkHekRoMaNT** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/15899143/dbbc2f03-5ab0-4f0b-b53f-582178493317)

**Comment by RedramVS** [comment]
Added.  If I missed any, let me know.
