### ISSUE TITLE
Free-standing ladders don't break when support is removed

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1717]
**Game Version:** 1.16.3
**Platform:** **Windows** / Mac / **Linux** (which?)  Reproducible on Windows and Linux (no idea about macOS)
**Modded:** **No** / Yes (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?) Reproducible on both

### Description
Explain the issue you're running into.

### How to reproduce
1. Build free-standing ladder (not next to anything)
2. Break the bottom one
3. Only adjacent ladders (to the one you broke) drop on the ground, the rest stay floating

### Expected behavior
If not obvious, what did you expect to happen?

The entire ladder should fall.

Placing the ladder against a tree and removing the tree after removing the bottom ladder is a functional work-around to this issue, as the tree forces a new block update for each ladder.

**Comment by DArkHekRoMaNT** [comment]
Since the issue is old and not reproducible, I will close this as stale
