### ISSUE TITLE
Bamboo corrupt each other

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#172]
1.6 rc1, PTS

It seems bamboo trees when grow multiple from one sapling at least, replace some trunk block with leaves in each other.
On the screenshot I removed few leaf blocks which were "interrupting" the bamboo trunk. 
I did not remove any trunk blocks.

![2018-08-01_23-10-09](https://user-images.githubusercontent.com/25122345/43545984-14f12574-95e0-11e8-9e6e-a1ed5fce9b90.png)

**Comment by tyronx** [comment]
Hm, nothing jumps at me code-wise. Please do report if the issue occurs again.

**Comment by Heptagon-ru** [comment]
I am quite sure the issue happens often, because I noticed it in pre3 - pre4, but thought it is because another thing. Noticed in rc1 in one place, on my curved pillar, and made a special testcase near my base.
I noticed it because after shearing all leaves and cutting trunk at the bottom, I often had floating leafy trunk blocks, which is uncomfortable for bamboo farming.

There is line of fresh rc1 planted bamboos, of which I looked into the first one only to make a screenshot.
If you have time and desire, the testcase is still there at the coords on screenshot, you can check other bamboos.
Some of them are planted close and some a bit apart.
Or send Saraty :D
If not - I will check tomorrow or at weekend on a bigger number of bamboos and report how often this happens.

**Comment by Heptagon-ru** [comment]
I cleared the bamboos grown in rc2 from leaves and here are the hanging trukc blocks. Looks quite ok actually, but I still thing there is some bug. Will try in singleplayer and post pics too.
The first screenshot is of their original state.
![2018-08-04_13-23-46](https://user-images.githubusercontent.com/25122345/43675805-de76bfb6-97ee-11e8-875c-da607b61240c.png)
![2018-08-04_13-27-12](https://user-images.githubusercontent.com/25122345/43675806-de948956-97ee-11e8-9f16-1400c51f06fd.png)
![2018-08-04_13-27-21](https://user-images.githubusercontent.com/25122345/43675807-deb13d9e-97ee-11e8-9a8e-4186997b9682.png)

**Comment by Heptagon-ru** [comment]
Tried in singleplayer, plantinng saplings and speeding up time. The same.
Interesting: if I force bamboo to grow only one plant, by surrounding with stone, it still has this anomaly.
Again removed all leaves with shears.
![2018-08-04_14-14-10](https://user-images.githubusercontent.com/25122345/43675921-e5c25c06-97f0-11e8-8041-842475e6fd00.png)
![2018-08-04_14-15-32](https://user-images.githubusercontent.com/25122345/43675922-e5de88ae-97f0-11e8-9ebe-d2118d7fbd12.png)

**Comment by tyronx** [comment]
Ok, this is now fixed. Was actually a problem for every tree grown by a sapling, so grown trees probably yielded a bit less logs than they should have.
