### ISSUE TITLE
Jugs filled with water cannot be used for making dough

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1721]
**Game Version:** 1.16.3
**Platform:** **Windows** / Mac / **Linux** (which?) Reproducible on both
**Modded:** **No** / Yes (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?) Both

### Description
Explain the issue you're running into.

Jugs filled with water cannot be used for making dough, while bowls with water and buckets filled with water can be used.

### How to reproduce
1. Try to make dough with a jug full of water instead of a bowl of water

### Expected behavior
If not obvious, what did you expect to happen?

All water-containing vessels can be used to make dough.

**Comment by Craluminum2413** [comment]
All suggestions go there <https://www.vintagestory.at/forums/forum/5-suggestions/>
