### ISSUE TITLE
Hitting M key crashes me out of VS

### ISSUE THREAD

**Issue by brummbar7** [anegostudios/VintageStory-Issues#173]
If i hit the m key I'm immediately booted entirely from VS.  This was on the public server.  Copy paste:

Running on 64 bit Windows with 8GB RAM 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityMapComponent.Render(GuiElementMap map, Single dt)
   at Vintagestory.GameContent.GuiElementMap.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRender2D(Single deltaTime)
   at _XBMFFtc1YrGCEeJCTErr4gMwhkG._ddugVcIsGLKDacnUpKNGWrIMZbc(Single )
   [...]
```

[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/2251753/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/2251754/client-main.txt)
[VintagestoryCrash.txt](https://github.com/anegostudios/VintageStory-Issues/files/2251755/VintagestoryCrash.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/2251756/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/2251757/client-crash.txt)

**Comment by tyronx** [comment]
Thanks for the report, should be fixed for rc.2. I'll leave the issue open until we can confirm the fix

**Comment by copygirl** [comment]
(Updated the issue description with what's more likely the actual exception.)

**Comment by tyronx** [comment]
Fixed for me and other players, please reopen if the problem still persist in rc.2
