### ISSUE TITLE
White currants placed on top of red currants are red, in pie layers

### ISSUE THREAD

**Issue by l1ving** [anegostudios/VintageStory-Issues#1730]
**Game Version:** 1.16.3
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** **No** / Yes (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?)  

### Description
Explain the issue you're running into.

White currants placed on top of red currants are red, in pie layers

### How to reproduce
1. Place any kind of berries in a pie shell for the first two layers
2. Place white currants for the next layers
3. New layer is red, not white

### Expected behavior
If not obvious, what did you expect to happen?

The layer should be white, given separate layers show up separately while making a pie.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

![image](https://user-images.githubusercontent.com/17222512/154848305-02d5ae60-7faf-41be-96cb-7c4b4b4f0489.png)

**Comment by Craluminum2413** [comment]
The got mixed

**Comment by l1ving** [comment]
Oh. It wasn't very clear given the bottom two aren't mixed at first(?). I guess I'll just close this, then.
