### ISSUE TITLE
Shift Clicking items into a full barrel deletes the item

### ISSUE THREAD

**Issue by Llama3013** [anegostudios/VintageStory-Issues#1733]
**Game Version:** 1.16.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
When a I shift click a item into a barrel when it already has something in the itemslot, it deletes the stack.

### How to reproduce
1. Make a barrel
2. Open barrel gui
3. Shift click an item into the barrel
4. When the barrel has an item in it, shift click another item.
5. The second item will be deleted

### Expected behavior
Too not delete item.

### Screenshots
![image](https://user-images.githubusercontent.com/51986409/155075843-d1c082ed-b53c-4550-b0ce-7d3d5333eacb.png)

### Extra
I found this when making my own gui basing it off of the barrel's gui. My gui seems to delete anything that is shiftclicked in when one of the slots is filled. I then tried it on vanilla VS with the same problem with the barrel.

**Comment by doornydew** [comment]
possibly have to do with #2045?

**Comment by doornydew** [comment]
as shift makes the issues appear for both

**Comment by DArkHekRoMaNT** [comment]
Not reproduced in 1.18.5, probably due to #2045

**Comment by DArkHekRoMaNT** [comment]
It can also be if player in creative
