### ISSUE TITLE
сбой при запуске

### ISSUE THREAD

**Issue by artem93zz** [anegostudios/VintageStory-Issues#1736]
Running on 64 bit Windows with 6 GB RAM 
Version: v1.16.0 (Stable) by Skif_9722.02.2022 20:46:47: Critical error occurred
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   в Newtonsoft.Json.JsonTextReader.ParseValue()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в _0EQ5mJTcic1pUi9z0CkYT4xDcTI._o1YFaq5XpLdNdIvrcb5qoA5mhNF._YleYc6Hb2N0hsptgJLGOGGML98g(CompletedArgs A_1)
   в Vintagestory.Common.MyWebClient.onComplete(Object sender, UploadValuesCompletedEventArgs e)
   в System.Net.WebClient.OnUploadValuesCompleted(UploadValuesCompletedEventArgs e)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 22.02.2022 20:46:54, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.16.0.0, метка времени: 0x61dc5145
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.1503, метка времени: 0xb2acaea9
Код исключения: 0xe0434352
Смещение ошибки: 0x0000000000034f69
Идентификатор сбойного процесса: 0x17a4
Время запуска сбойного приложения: 0x01d828141d96452d
Путь сбойного приложения: C:\Games\Vintage Story v1.16.0\Vintagestory.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 42a967b4-4ad3-4db5-b610-063ad5430f1c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 22.02.2022 20:46:50, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: Newtonsoft.Json.JsonReaderException
   в Newtonsoft.Json.JsonTextReader.ParseValue()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonContract, Boolean)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonSerializerSettings)
   в _0EQ5mJTcic1pUi9z0CkYT4xDcTI+_o1YFaq5XpLdNdIvrcb5qoA5mhNF._YleYc6Hb2N0hsptgJLGOGGML98g(Vintagestory.Common.CompletedArgs)
   в Vintagestory.Common.MyWebClient.onComplete(System.Object, System.Net.UploadValuesCompletedEventArgs)
   в System.Net.WebClient.OnUploadValuesCompleted(System.Net.UploadValuesCompletedEventArgs)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 22.02.2022 20:31:43, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: Newtonsoft.Json.JsonReaderException
   в Newtonsoft.Json.JsonTextReader.ParseValue()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonContract, Boolean)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonSerializerSettings)
   в _0EQ5mJTcic1pUi9z0CkYT4xDcTI+_o1YFaq5XpLdNdIvrcb5qoA5mhNF._YleYc6Hb2N0hsptgJLGOGGML98g(Vintagestory.Common.CompletedArgs)
   в Vintagestory.Common.MyWebClient.onComplete(System.Object, System.Net.UploadValuesCompletedEventArgs)
   в System.Net.WebClient.OnUploadValuesCompleted(System.Net.UploadValuesCompletedEventArgs)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by artem93zz** [comment]
failure after entering the login. Record "connection" and then crash.

**Comment by Craluminum2413** [comment]
This looks like pirate copy of the game

**Comment by artem93zz** [comment]
> 

and there is. But yesterday it worked without errors.

**Comment by copygirl** [comment]
Apologies, there will be no support for pirated copies.
