### ISSUE TITLE
Mushrooms spawning in wilderness survival broken

### ISSUE THREAD

**Issue by Irulanaa** [anegostudios/VintageStory-Issues#1738]
**Game Version:** 16.3  
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer and multiplayer

### Description
Mushrooms spawning in wilderness survival is broken. I play for about month in 16.x I found some 2x2 oak tree mushrooms and two new ground types. Because people tell me they have no problem with finding mushrooms I ran few test on wilderness survival and standard mode, flying around mostly on forest areas. Few random seeds and result the same, no mushrooms in wilderness and many on standard mode.

### How to reproduce
1. Run random wilderness gamplay (no changed settings) fly around in creative/sepctator for about a day. No mushrooms,
2. Run random standard gamplay (no changed settings) fly around in creative/sepctator for about a day. Many mushrooms,

### Expected behavior
Wilderness should have same amount of mushrooms like standard.

```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
