### ISSUE TITLE
Forest floors unable to be tilled.

### ISSUE THREAD

**Issue by VirtualSkeleton** [anegostudios/VintageStory-Issues#1739]
**Game Version:** 1.16.3 
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer and Multiplayer  

### Description
Forest floors are unable to be tilled by a hoe.

### How to reproduce
Attempt to use hoe to till forest floor.

### Expected behavior
I would expect the forest floor, being a soil block itself, to be tillable.

**Comment by radfast** [comment]
This is a suggestion disguised as an issue report.   It's a good suggestion though, I'll ask the team to consider it.
