### ISSUE TITLE
Forest floors do not indicate soil type.

### ISSUE THREAD

**Issue by VirtualSkeleton** [anegostudios/VintageStory-Issues#1740]
**Game Version:** 1.16.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer and Multiplayer

### Description
Unlike other variations of grassy soil blocks, forest floors give no indication of the type of soil the block is (low fertility, medium, terra preta) in the block info overlay.

### Expected behavior
The forest floor block would be appended/prepended with the associated soil type, e.x. "Forest Floor (Low fertility soil)" or  "Low fertility soil (Forest floor)"

**Comment by DArkHekRoMaNT** [comment]
The forest floor is always low fertility soil
