### ISSUE TITLE
Clay forming - invisible layer

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1741]
Game Version: 1.16.4-rc3
Platform: Linux (KDE neon 20.04 5.23 )
Modded: No
SP/MP: Singleplayer

### Description
When clay forming, the active layer is invisible till first click.

### How to reproduce
1. Start clay forming - eg. Raw storage vessel
2. You can not see clay layout - green blocks
3. Click on if
4. Now you can see the clay layout

### Expected behavior
Should be visible right away, as usual.

### Screenshots
![2022-02-23_08-24-20](https://user-images.githubusercontent.com/47914240/155276991-1d707a7c-77f0-4e06-8b70-902254d14745.png)

### Video

https://user-images.githubusercontent.com/47914240/155276932-5856e587-68a8-43c1-8775-7abf6889a6df.mp4

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
