### ISSUE TITLE
Server segfault

### ISSUE THREAD

**Issue by l1ving** [anegostudios/VintageStory-Issues#1742]
**Game Version:** 1.16.3
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)
```
Auto_Map_Markers.zip
CarryCapacity-VS1.16.0-v0.6.4.zip
FarmlandDropsSoil-VS1.15-v1.4.0.zip
```
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

### Description
Explain the issue you're running into.

Server segfault after player killed a bell. I don't think this is related to killing the bell, it just looks like a fluke with the autosaving.

Logs: https://cdn.l1v.in/paste-16456844301.txt

**Comment by l1ving** [comment]
After poking around a bit, I found https://github.com/mono/mono/issues/12947. 

This is in-line with what I was experiencing, after going through several translocators, where loading new chunks slowed to a crawl (30 to 60 seconds each time).

My server is on a 10 gbit connection with 24GB of ram and 4 cores, and cpu usage was around 40% during the chunk loading.

Also, to test, attempting to teleport with the command within the same chunk (no more than 5 blocks in front of you) still had a 50 second delay before it worked, while other actions didn't have such latency.

**Comment by tyronx** [comment]
please run this command and reopen the ticket if it still happens after that: `sudo sysctl -w vm.max_map_count=262144`

**Comment by l1ving** [comment]
Thank you, I'll update this issue if it happens again.
