### ISSUE TITLE
Pasting password to login does not work inside VS Mod enviornment

### ISSUE THREAD

**Issue by l1ving** [anegostudios/VintageStory-Issues#1749]
### See last comment for workaround

**Game Version:** 1.16.3
**Platform:** Windows / Mac / **Linux** (which?)   

### Description
Explain the issue you're running into.

I am trying to run an example mod with https://github.com/anegostudios/vsmodexamples. I have setup a Rider environment (drop-in replacement for Visual Studio), and can successfully run the game with the mod by hitting the run button. It asks me to login, which is fine. 

I am unable to paste my password into the box. This is not fine, because my password is 48 characters.

I didn't have this problem with regular vintagestory (outside of the mod env). I am running the same Vintagestory.exe in both non-dev and dev envs.

**Comment by l1ving** [comment]
More problems: Moving camera around doesn't work.

More info: I'm pretty sure this is caused by the fact the dev env is running in Wine. How do I get it to not do that?

**Comment by copygirl** [comment]
If the game is actually run using Wine rather than Mono, then that's likely the issue.
Possibly contact Rider support or ask around in their community places.

**Comment by l1ving** [comment]
I checked the logs and it's certainly using wine paths instead, eg when it says which folders it's loading mods from.

I can't find any reference to wine in Rider's own configurations, I'll poke around their forums but ime jetbrains-related forums aren't super helpful.

I'm using system-level dotnet which is selected as the target dotnet sdk, and I don't have any other installed.

```
~ ❯ yay -Q | g dotn
dotnet-host-bin 6.0.2.sdk102-1
dotnet-runtime-bin 6.0.2.sdk102-1
dotnet-sdk-bin 6.0.2.sdk102-1
dotnet-targeting-pack-bin 6.0.2.sdk102-1
```

This does very much seem out of scope / not vintagestory's fault, but in case other people try Rider and encounter the same issue I'll document the solution here (once I have one).

**Comment by l1ving** [comment]
Pain in the ass workaround found:

Edit `launchSettings.json` to a dummy profile. Essentially we want it to compile the dotnet project with the libraries needed and not launch vintagestory.

```json
{
  "profiles": {
	"start-all-mods-in-sln": {
      "commandName": "Executable",
      "executablePath": "/usr/bin/echo",
      "commandLineArgs": "Test"
    }
  }
}
```

Next you can make a Native Executable profile that
- Runs the previous dummy profile, to compile your mod
- Runs mono, which runs Vintagestory with the mods folder set

![](https://frogg.ie/Zqz)

**Comment by l1ving** [comment]
Figured it out 

1. The default SLN project for the example mods runs the exe directly
2. Default file associations will use the default mime type, which is wine when wine is installed
3. Thus, intellij is just sending a command the OS with like. "Hey, run this binary". 
4. *This* is what causes the exe to be run under mono
5. The proper solution is to edit the SLN configuration to run mono, and tell mono where VS is
```json
{
  "profiles": {
    "start-all-mods-in-sln": {
      "commandName": "Executable",
      "executablePath": "/usr/bin/mono",
      "commandLineArgs": "/usr/share/vintagestory/Vintagestory.exe --addModPath=somewhere --dataPath somewherelse",
      "environmentVariables": {
        "VINTAGE_STORY": "/usr/share/vintagestory/",
        "SOLUTION_DIR": "/home/f/projects/vsmodexamples/Mods/AnnoyingTextSystem/bin"
      }
    }
  }
}
```

Re-opening this to request this work-around be added to some sort of documentation.

I'm currently opening an issue with Rider because I would assume it runs the exe under mono, given it asks you to install mono.

**Comment by copygirl** [comment]
On another note: This does not relate to the game itself, but specifically the [vsmodexamples](https://github.com/anegostudios/vsmodexamples) repository. When you are ready, please close this and open an issue or PR on that repo instead.

**Comment by l1ving** [comment]
Moved, thanks.
