### ISSUE TITLE
Trying to start single player game immediately crashes to desktop with no error message

### ISSUE THREAD

**Issue by brummbar7** [anegostudios/VintageStory-Issues#175]
Trying to start a single player game gets immediate desktop crash.  Tried with/without cheats enabled, and with/without seed of my own.  There were some logs, attached.
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/2253501/client-main.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/2253502/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/2253503/server-main.txt)

**Comment by tyronx** [comment]
Please delete the file %appdata%/VintagestoryData/serverconfig.json, it probably corrupted from the pre.4 version
