### ISSUE TITLE
Chutes feed too many grain items into small troughs.

### ISSUE THREAD

**Issue by VirtualSkeleton** [anegostudios/VintageStory-Issues#1751]
**Game Version:** 1.16.4
**Platform:** Windows   
**Modded:** No  
**SP/MP:** Singleplayer  

### Description
When a container and chute are connected to a small trough, the chute will deposit up to 32 grain into the small trough instead of the expected 8.

### How to reproduce
1. Place a chute above a small trough, place a container (chest, trunk, crate) on top of the chute.
2. Add grain to the container.
3. Observe the amount of grain removed from the container (should be 33; 32 into the trough, one held in the chute).

### Expected behavior
I would expect the trough to be filled with only 8 grain items, as when hand-filled, the maximum capacity is 8 portions consisting of one grain each.

**Comment by Craluminum2413** [comment]
Fixed in [1.18.0-pre.1](https://www.vintagestory.at/forums/topic/10595-v1180-pre1-lore-update-the-resonance-archives/#:~:text=Fixed%3A%20Able%20to%20overfill%20troughs%20using%C2%A0chutes)
