### ISSUE TITLE
Extra space before message in chat

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1755]
**Game Version:** 1.16.4
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** **No** / Yes (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

This wasn't an issue before 1.16.3

![image](https://user-images.githubusercontent.com/17222512/155865776-46979df3-dbba-47ff-a69f-8b54a193334c.png)

**Comment by copygirl** [comment]
The space after the `:`? I would assume this was changed to make it easier to differentiate name and message.

**Comment by l1ving** [comment]
Maybe. This is two spaces, instead of the one previously. 

If it isn't a bug, then I guess it's fine, it just looks a bit weird.
