### ISSUE TITLE
Drawings on labels on crates are long for some items

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1759]
**Game Version:** 1.16.4
**Platform:** **Windows** / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

![image](https://user-images.githubusercontent.com/17222512/155869069-61d7edad-9ef5-48b4-976f-becf8f7772d3.png)

**Comment by Craluminum2413** [comment]
Fixed in 1.19 iirc

**Comment by 5HT2** [comment]
Thanks!
