### ISSUE TITLE
The right side of a trunk will not properly pull items using a chute

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1760]
**Game Version:** 1.16.4
**Platform:** **Windows** / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

![image](https://user-images.githubusercontent.com/17222512/155870561-5fc58d76-62c4-42b4-a156-a5bf79fb225f.png)
![image](https://user-images.githubusercontent.com/17222512/155870564-238d3b83-c509-42bf-b470-e12bbbe51163.png)

**Comment by l1ving** [comment]
Tested, this also applies to putting items into the trunk

**Comment by Craluminum2413** [comment]
Fixed since 1.19 or earlier
