### ISSUE TITLE
Instant crash when adding voxels in clayforming

### ISSUE THREAD

**Issue by baeda93** [anegostudios/VintageStory-Issues#1764]
Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: tradeomat@1.6.0, game@1.16.4, carrycapacity@0.6.4, medievalexpansion@3.7.1, creative@1.16.4, survival@1.16.4, xlib@0.6.8, campaigncartographer@2.0.2, xskills@0.6.8
28.02.2022 00:24:51: Critical error occurred
System.MissingMethodException: Methode nicht gefunden: "Void Vintagestory.GameContent.BlockEntityClayForm.CheckIfFinished(Vintagestory.API.Common.IPlayer)".
   bei XSkills.BlockEntityClayFormPatch.Prefix(BlockEntityClayForm __instance, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode, ClayFormRenderer ___workitemRenderer, ItemStack& ___workItemStack, Cuboidf[]& ___selectionBoxes)
   bei Vintagestory.GameContent.BlockEntityClayForm.OnUseOver_Patch1(BlockEntityClayForm this, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   bei Vintagestory.GameContent.ItemClay.OnHeldInteractStop_Patch1(ItemClay this, Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   bei Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   bei _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   bei _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   bei _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 479.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 454.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   bei _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27.02.2022 22:25:15, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFFA54F4F69
Stapel:
 }
--------------
{ TimeGenerated = 31.01.2022 15:53:21, Site = , Source = Application Hang, Message = Das Programm Vintagestory.exe Version 1.16.1.0 hat die Interaktion mit Windows beendet und wurde geschlossen. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.

Prozess-ID: 680

Startzeit: 01d816ac57773c75

Beendigungszeit: 57

Anwendungspfad: C:\Vintagestory\Vintagestory.exe

Bericht-ID: 0169035f-a71f-440c-a6c6-e956e672c5fe

Vollständiger Name des fehlerhaften Pakets: 

Relative Anwendungs-ID des fehlerhaften Pakets: 

Absturztyp: Unknown
 }
--------------
{ TimeGenerated = 30.01.2022 20:47:02, Site = , Source = Application Hang, Message = Das Programm Vintagestory.exe Version 1.16.1.0 hat die Interaktion mit Windows beendet und wurde geschlossen. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.

Prozess-ID: 42d0

Startzeit: 01d81611dfa3f97c

Beendigungszeit: 15

Anwendungspfad: C:\Vintagestory\Vintagestory.exe

Bericht-ID: 63da50ef-c34d-4fab-8f94-5faece21de84

Vollständiger Name des fehlerhaften Pakets: 

Relative Anwendungs-ID des fehlerhaften Pakets: 

Absturztyp: Unknown
 }

**Comment by Craluminum2413** [comment]
The problem is in XSkills mod

**Comment by copygirl** [comment]
Indeed, see the following line:
```
bei XSkills.BlockEntityClayFormPatch.Prefix(BlockEntityClayForm __instance, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode, ClayFormRenderer ___workitemRenderer, ItemStack& ___workItemStack, Cuboidf[]& ___selectionBoxes)
```
One of XSkill's patches to the game causes this issue. It's likely outdated. Disable the mod, wait for a mod update, or contact the mod author.
