### ISSUE TITLE
No re-watering by taken items

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1771]
Game Version: 1.16.4
Platform: Linux (KDE neon 20.04 5.24)
Modded: No
SP/MP: Singleplaye 

### Description
If you give something in the water pool and take it out, the place will not re-water itself.
If you destrou the item, it will re-water

### How to reproduce
1. Place something (e.g. cooking pot i the water)
2. Take it out
3. The place stay open - no re-watering
4. Try to destroy the Item instead - the place will re-water

### Expected behavior
Place should always re-water.

### Screenshots
![2022-03-02_12-01-28](https://user-images.githubusercontent.com/47914240/156349475-f327303f-398e-4cfe-a104-61202e4f08b5.png)

### Video
https://user-images.githubusercontent.com/47914240/156349621-2a7e337a-9095-451a-9a2d-04d9a1197359.mp4

**Comment by Craluminum2413** [comment]
It happens with all Ground Storage and items with SneakPlacing behavior

**Comment by copygirl** [comment]
Lack of block update after the block is removed?

**Comment by copygirl** [comment]
The lack of a block update is probably still an issue but this particular issue is no longer relevant, yeah.
