### ISSUE TITLE
Window border reseting to "Hidden" by F11

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1772]
**Game Version:** 1.16.4
**Platform:** Linux (KDE neon 20.04 5.24)
**Modded:** No
**SP/MP:** Singleplayer

### Description
If I switch between Full-screen and windowed mode with F11, the border gets missing.
Even if I set the `Windows Border` setting to `Resizable`, it will be set back to `Hidden`.

### How to reproduce
1. Switch from Fullscreen to window with F11
2. You can see that window has no border.
3. Open the `Interface` menu and change the setting to `Resizable` of `Fixed` - border is visible
4. Switch Fullscreen-Window (F11)
5. Border is missing
6. Switch Interface tab to update the info (e.g. `Interface - Sound - Interface`)
7. In `Windows Border` you can see `Hidden` again.

### Expected behavior
Changing from Fullscreen to Windows, the `Windows Border` should switch back to previous setting (e.g. `Resizable`)

### Video
https://user-images.githubusercontent.com/47914240/156351683-c861f98c-40ef-4ad8-bcd8-78e898869216.mp4

**Comment by l1ving** [comment]
I cannot reproduce this issue.

```
Operating System: Arch Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.11-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 15.1 GiB of RAM
Graphics Processor: AMD RENOIR
```

**Comment by daretmavi** [comment]
Strange ...

Try to change it more times.
Sometimes is works correctly with first F11, but not with second and more changes.

**Comment by l1ving** [comment]
I'll try again, once I get a chance. Thanks for the additional info.

**Comment by daretmavi** [comment]
Seems to work ok with 1.19.0 pre.4
