### ISSUE TITLE
Wrong transformation for some items placed on shelves

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1773]
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Screenshots
Ingot
![image](https://user-images.githubusercontent.com/69315569/156428815-c9bc21d5-bdad-4b3a-8562-ee51317d5edc.png)

**Comment by Zamaky345** [comment]
I can confirm this.
