### ISSUE TITLE
Meteoric Iron Cleaver does not list Attack Power or Attack Tier

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1781]
**Game Version:** 1.16.4
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?)  

Every other cleaver lists these two.

![image](https://user-images.githubusercontent.com/17222512/156753544-65053d50-4f5b-4f95-b3b4-2d47b820e427.png)
![image](https://user-images.githubusercontent.com/17222512/156753558-fdf00659-7f24-4648-ab58-437bc1d1559a.png)

**Comment by RedramVS** [comment]
fixed
