### ISSUE TITLE
Survival handbook missing recipe for vines basket

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1796]
**Game Version:** 1.16.4
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

They can be crafted with 8 rope. 
![image](https://user-images.githubusercontent.com/17222512/157230054-2030d03e-3e03-42df-b594-7cc54acb289c.png)

**Comment by Craluminum2413** [comment]
This is a suggestion
