### ISSUE TITLE
Cassava and new mushrooms are invisible when added to meals

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1797]
**Game Version:** 1.16.4
**Platform:** **Windows** / Mac / **Linux** (which?)   
**Modded:** **No** / Yes (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?)  

![](https://media.discordapp.net/attachments/334233095374897152/949630011219013702/2022-02-28_01-51-06.jpg)

**Comment by tyronx** [comment]
Are you sure this is 1.16.4? I cannot reproduce this

**Comment by 5HT2** [comment]
Oops, my bad. This was 1.16.3, it's fixed now. Thank you!
![image](https://user-images.githubusercontent.com/17222512/160462926-5054955a-c774-4aeb-8b1a-73f0f7412622.png)
