### ISSUE TITLE
Slanted roofing with snow on it does not show as white on map

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1798]
**Game Version:** 1.16.4
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

![image](https://user-images.githubusercontent.com/17222512/157808191-a745f286-d7ef-4ccf-9812-72266e8d35eb.png)

**Comment by Craluminum2413** [comment]
I guess it can be closed now since snow doesn't show up on new map anymore
