### ISSUE TITLE
Adding variant groups with JSON patch does not appear to work.

### ISSUE THREAD

**Issue by milochristiansen** [anegostudios/VintageStory-Issues#18]
The following patch dose not produce any error, but the `game:bowl-soup` item does not exist either.

```
{ file: "game:blocktypes/clay/bowl", op: "replace", path: "/variantgroups/0/states", value: ["raw", "burned", "honey", "soup"] },
```

**Comment by copygirl** [comment]
With the changes I'll be making, it should be possible to do:
```
{ file: "game:blocktypes/clay/bowl", op: "add",
  path: "/variantgroups/0/states/-", value: "soup" }
```

**Comment by copygirl** [comment]
Going to close this as duplicate of #2 for now, as my changes should fix any other issues there are with the JSON patching library. I've tested to make sure both our patches work now.
