### ISSUE TITLE
Lighting underground is affected by daytime clouds casting shadows when rooms are connected to "outside" or by nighttime darkness

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1800]
**Game Version:** 1.16.4
**Platform:** **Windows** / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / Multiplayer (which?)  

Video explaining the issue:

https://user-images.githubusercontent.com/17222512/158006326-1a84e288-1eca-46c0-a499-ae3b21aea140.mp4

Workaround:
![image](https://user-images.githubusercontent.com/17222512/158006189-9ecb175e-096b-4124-b551-92ab8e178be7.png)

**Comment by Craluminum2413** [comment]
Fixed in 1.20
