### ISSUE TITLE
Board handbook - recipe for crate not available

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1809]
**Game Version:** 1.16.4
**Platform:** Linux (KDE neon 20.04 5.24)
**Modded:** No
**SP/MP:** Singleplayer

### Description
If I look at `Board` Info (`H`), than I can not click on crate to see the recipe.

### How to reproduce
1. Take some board
2. Use `H` key to open `Handbook`
3.  Click on crate
4. Nothing happens
5. If you click something else, you can see the recipe

### Expected behavior
Should show the recipe.

### Video

https://user-images.githubusercontent.com/47914240/158054143-84a0effe-50f5-4c1c-97fa-490964db87a7.mp4

**Comment by Craluminum2413** [comment]
related to #1557

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
