### ISSUE TITLE
CarryCapacity

### ISSUE THREAD

**Issue by Fenrirjernule** [anegostudios/VintageStory-Issues#181]
For some reason,
![uh2](https://user-images.githubusercontent.com/42284824/43985743-81a08890-9ccf-11e8-842d-36170425e604.PNG)
 Carry Capacity on the client side is not functioning right. Please help?

**Comment by copygirl** [comment]
Please report this issue on CarryCapacity's [own issue tracker](https://github.com/copygirl/CarryCapacity/issues) instead.
And also include the text in triple backticks like so:
````
```
Running on 64 bit Windows with 8GB RAM
[...]
```
````
