### ISSUE TITLE
Forming clay crashing game

### ISSUE THREAD

**Issue by Szymons2** [anegostudios/VintageStory-Issues#1810]
**Game Version: v1.16.4 (Stable)
**Platform:** Windows    
**Modded:**  Yes  XSkils , XLib  
**SP/MP:** Singleplayer   

### Description
Po próbie ustawienia gliny gra przestaje działać

### How to reproduce
1. Umieść glinę na ziemi(wybierz co chcesz ulepić np. dachówki 
2. Spróbuj wypełnić  pole gliną
3. Gra się crashuje

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: game@1.16.4, creative@1.16.4, survival@1.16.4, xlib@0.6.8, xskills@0.6.8
13.03.2022 17:31:16: Critical error occurred
System.MissingMethodException: Nie odnaleziono metody: 'Void Vintagestory.GameContent.BlockEntityClayForm.CheckIfFinished(Vintagestory.API.Common.IPlayer)'.
   w XSkills.BlockEntityClayFormPatch.Prefix(BlockEntityClayForm __instance, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode, ClayFormRenderer ___workitemRenderer, ItemStack& ___workItemStack, Cuboidf[]& ___selectionBoxes)
   w Vintagestory.GameContent.BlockEntityClayForm.OnUseOver_Patch1(BlockEntityClayForm this, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   w Vintagestory.GameContent.ItemClay.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   w Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   w Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   w Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   w _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   w _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   w _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 479
   w OpenTK.GameWindow.DispatchRenderFrame() w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 454
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 375
   w _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   w _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

**Comment by Craluminum2413** [comment]
The problem is in XSkills mod

**Comment by copygirl** [comment]
`w XSkills.BlockEntityClayFormPatch.Prefix(BlockEntityClayForm __instance, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode, ClayFormRenderer ___workitemRenderer, ItemStack& ___workItemStack, Cuboidf[]& ___selectionBoxes)`

XSkills likely not updated to the most recent mod version. Check for mod update, use it if available, or message the mod author asking to update the mod to the newest version.
