### ISSUE TITLE
[Feature Request] Mod Manager Overhaul

### ISSUE THREAD

**Issue by ApacheTech** [anegostudios/VintageStory-Issues#1815]
**__MOD MANAGER OVERHAUL__**

There is a major design issue with the Mod Manager that is becoming more of a problem, the more mods are added to the game. Currently, the Mod Manager is a global list, but only for single player worlds. But therein lies the problem...

**Single Player Worlds:**

1. Pure Vanilla Wilderness Survival Permadeath UHC
2. Creative Building World (Aura Fury SMP)
3. Creative Building World (Rusty Gears SMP)
4. Mod Development World (Chaos Mod)
5. Mod Development World (CC/AT)
6. YouTube Let's Play World
7. Twitch Let's Play World

All of these worlds use different mod lists, and the only way to safely switch between worlds is to create sub-folders within my Mods folder, and add every mod that's needed into that folder. Then, manually move mods from the sub-folders to the main folder, whenever I change worlds. With some mods, removing it and launching the world can erase all data from the save file, regarding that mod. It's not worth the risk to just toggle mods in a massive long list within the Mod Manager. It's safer to do it manually.

Ideally, the Mod Manager should be a "Per World" feature, rather than a "Global" feature. A single directory can be used to store all versions of all mods from all worlds; and then these mods can be referenced as either enabled, or disabled within any given world. Each world would then be considered as a "Mod Pack" within its own right; and could even have its own overrides, downgraded mod versions, custom mod loading, etc..

```
As a player,
Given I have multiple Single-Player worlds,
When I choose a world to launch,
Then I should be able to choose a specific mod loadout for that world.
```

**Comment by copygirl** [comment]
I agree. I posted this request four years ago: #4
Unfortunately, even though this is a very important feature, it's still a feature request. Poke Tyron some more on Discord!

**Comment by ApacheTech** [comment]
Why is the status: Invalid? In what way is this invalid?

**Comment by ApacheTech** [comment]
The status should be set to: Enhancement; as it is a Feature Request. It can be linked to a previous Feature Request, but by no means, is it invalid.
