### ISSUE TITLE
Units of XXX - not complete/correct

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1816]
**Game Version:** 1.16.4
**Platform:** Linux (KDE neon 20.04 5.24)
**Modded:** No
**SP/MP:** Singleplayer

### Description
The description how many units of some item you get is not complete.
E.g. instead of `50 units of Copper ingot`, you see only `50 units of Copper` - **ingot** is missing.
White this can be accepted in English, it is causing trouble in other languages (e.g. Slovak)
(`Copper` = _Meď_, while `Copper ingot` = _Medený_ ingot)

### How to reproduce
1. open creative menu
2. look on any nugget

### Expected behavior
`item-ingot-...` is probably not the right attribute to use for this. Attribute `material-...` would be much more suitable.

### Screenshots
EN:
![2022-03-19_18-04-36](https://user-images.githubusercontent.com/47914240/159131512-f920cc62-8bb7-4d2b-91b4-333759cb99dc.png)

SK:
![2022-03-19_18-23-12](https://user-images.githubusercontent.com/47914240/159131589-2dbfa0bf-b6ea-46e9-a885-4e7ed11121c4.png)

**Comment by Craluminum2413** [comment]
@RedramVS Can you look into this?

**Comment by RedramVS** [comment]
@Craluminum2413   I'd have to talk to Tyron and Radfast about this.  I've frankly found it weird that some things phrase it as units of 'copper ingot'.  That's not a normal way to phrase that in English.   "50 units of copper" is much more sensible, english-wise.

**Comment by RedramVS** [comment]
As daretmavi mentioned, it would be best if the code reference 'material-typeofmetal', rather than the ingot item, so that it just says "X units of copper", rather than "X units of copper ingot".  I think this is hopefully a simple code thing.  @Th3Dilli ?

**Comment by Th3Dilli** [comment]
ty, this is now fixed with the next release
