### ISSUE TITLE
Roofing tile visual blocks allows players to see through world

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1821]
**Game Version:** 1.16.4
**Platform:** **Windows** / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

Very minor visual issue, I guess.

![image](https://user-images.githubusercontent.com/17222512/159414369-17487730-607b-4444-b57d-db63f2df57cb.png)

**Comment by DArkHekRoMaNT** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/15899143/2a123304-752f-46ab-999b-a15039ea38e2)

**Comment by DArkHekRoMaNT** [comment]
I'll close it as stale. Probably it was fixed in some version above. If you can still get it in the newer version - reopen it
