### ISSUE TITLE
Recipe Json File Format Not Consistent

### ISSUE THREAD

**Issue by VinterNacht** [anegostudios/VintageStory-Issues#1828]
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer / Multiplayer

### Description
Recipe JSONs aren't consistent, with some single-member recipes (such as chests) not being listed as arrays, while others, such as the chair, are.

### Expected behavior
All Json will be listed in a consisted format, preferably as an array since multi-member recipes require an array.

### Screenshots
Vanilla JSON for Chair:
```
[
	{
		ingredientPattern: "WLW	W_W",
		ingredients: {
			"W": { type: "item", code: "plank-*" },
			"L": { type: "item", code: "cloth-*", quantity: 1, name: "color" }
		},
		width: 3,
		height: 2,
		output: { type: "block", code: "chair-{color}"}
	}
]
```

Vanilla JSON Chest:
```
{
	ingredientPattern: "WWW	W_W	WWW",
	ingredients: {
		"W": { type: "item", code: "plank-*" }
	},
	width: 3,
	height: 3,
	output: { type: "block", code: "chest-east", attributes: { type: "normal-generic" }  }
}
```

**Comment by copygirl** [comment]
Can you explain why this is a problem?

If the recipe parser encounters and array, it will parse multiple recipes. Otherwise just one.

**Comment by 5HT2** [comment]
> If the recipe parser encounters an array, it will parse multiple recipes. Otherwise just one.

This would require extra work on the end of whoever wants to use the jsons outside of the game's recipe parser. I'm not quite sure if you _can_ use the game's recipe parser in your own mods, I haven't checked.

**Comment by copygirl** [comment]
The "extra work" would be a simple `if` statement to check the type of the root JSON element.

This issue is not about a bug within the game, leaving things as-is doesn't really hurt anyone, so I'm going to close it for now. Keep in mind the issue tracker only allows bugs at this time since there's already many open issues that need looking into. Opening it up to suggestions or similar would make it even harder to keep track of everything.

**Comment by VinterNacht** [comment]
I actually have an extant example! I'm glad you asked!

I'm currently patching vanilla recipes in a way that requires separating metal tools from stone tools. Now, if you take a look at the axe, this is a breeze. It's in an array, I just do this:

{"op": "replace",
   "path": "/0/ingredients/T",
   "value": { "type": "item", "code": "axehead-*", "name": "material", "allowedVariants": ["chert", "granite", "andesite", "basalt", "obsidian", "flint", "peridotite"]},
   "file": "recipes/grid/tool/axe.json"
},


And then add a new recipe for metal axes with this:

{
    "op": "add",
    "path": "/-",
    "value": {
		"ingredientPattern": "TB,SR",
		"ingredients": {
			"T": { "type": "item", "code": "axehead-*", "name": "material", "allowedVariants": ["copper", "tinbronze", "bismuthbronze", "blackbronze", "silver", "gold", "iron", "meteoriciron", "steel"]},
			"S": { "type": "item", "code": "stick" },
      "B": { "type": "item", "code": "hammersringingfall:metalband-*"},
      "R": { "type": "item", "code": "hammersringingfall:rivet-*","quantity": 2}
		},
		"width": 2,
		"height": 2,
		"output": { "type": "item", "code": "axe-{material}", "quantity": 1  }
	},
    "file": "recipes/grid/tool/axe.json"
  }
  
  
  I cannot do that with hoes, they are not an array. I have to make a separate recipe file for them.  Is that a real problem? No, but it's messy and inconsistent.  All recipes should be in one consistent format to allow a cohesive way of approaching things like patches.

**Comment by copygirl** [comment]
You don't need to add recipes by patching existing files. Just create your own recipe in your own mod's namespace.
