### ISSUE TITLE
Prospecting Tool in wrong folder

### ISSUE THREAD

**Issue by VinterNacht** [anegostudios/VintageStory-Issues#1829]
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer / Multiplayer 

### Description
A simple concern, the prospectingpick.json is located in the recipe/grid, rather than the recipe/grid/tool folder. Could imagine some corner case issues where this is an inconvenience, at worst.  Would still be nice to have it in the appropriate folder.

### Expected behavior
All tool JSON should be in the same folder.

**Comment by copygirl** [comment]
This sounds too much like a suggestion. Inconsistency in the game's asset structure is hardly a problem. (On the contrary, moving any file around for "no reason" breaks any JSON patches applied to these files and would just potentially hurt mods.) Feel free to mention this to the team in the forums or Discord, however.
