### ISSUE TITLE
Decor code is corrupted for mods

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1848]
**Game Version:** 1.16.5-rc.1  
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
Should be `attach:block-this-planks-oak-hor`, but it uses `block-attach:this-planks-oak-hor`, while vanilla use the same lang key

### How to reproduce
1. Add a block as wallpaper (with Decor behavior) under modded domain
2. Attach it to a block
3. It uses different code

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/162630295-f1f8c71d-121b-4a83-aadf-1325dace4565.png)

**Comment by tyronx** [comment]
thanks for the report, should be fixed in 1.16.5
