### ISSUE TITLE
New language doesn't apply

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1849]
**Game Version:** 1.16.5-rc.1
**Platform:** Window 
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
Adding a whole new language doesn't work if it was added by patching

### How to reproduce
1. Add a new language without editing game files, e.g. by patching `languages.json`
2. Load any world
3. Choose the new language
4. It says to restart the game, do it
5. After restarting, open settings, Interface tab and look at `Language`
6. It looks empty

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/162635980-9a473fea-12ad-4a17-899a-3e1f00a31b53.png)

### Logs
```
10.4.2022 22:19:29 [Error] Language 'langone' not found. Will default to english.
```

**Comment by copygirl** [comment]
Languages can not be added through patching as patches are only applied after a world is loaded. It's meant for gameplay use.

Can you explain your use case?

**Comment by Craluminum2413** [comment]
I load the world, choose language, then reload it, it doesn't apply

**Comment by copygirl** [comment]
You probably have to either provide it as files for people to manually apply to their game data, or request the devs to create a custom language on the translation site they use (unsure about how this one works - just a guess). Going to close this, as I think it's not in the scope for a mod, and thus is a suggestion, not an issue.
