### ISSUE TITLE
BlockEntityPumpkinVine Api reporting as null

### ISSUE THREAD

**Issue by VinterNacht** [anegostudios/VintageStory-Issues#1859]
**Game Version:** 1.16.5
**Platform:** Windows 10
**Modded:** Yes (Is a modding related issue) Fields of Gold and Ancient Tools
**SP/MP:** Both

### Description
__instance.Api reports that the BlockEntityPumpkinVine's Api is null, leading to a crash in the following HarmonyPatch:
                ___pumpkinHoursToGrow = (float)(__instance.Api.World.Calendar.DaysPerMonth / 30.0) * 300f;
                ___vineHoursToGrow = (float)(__instance.Api.World.Calendar.DaysPerMonth / 30.0) * 300f;
                ___vineHoursToGrowStage2 = (float)(__instance.Api.World.Calendar.DaysPerMonth / 30.0) * 150f;
                
This did not occur in 1.16.4, where it behaved as expected.  This same approach is used with BlockEntityFarmland without issue, so it seems to be isolated to BlockEntityPumpkinVine.

### How to reproduce (at least how it happened to me)
Use this harmony patch:

        [HarmonyPrefix]
        [HarmonyPatch(typeof(BlockEntityPumpkinVine), "Initialize")]
        static void Patch_BlockEntityPumpkinVine_CreatedFromParent_Prefix(BlockEntityPumpkinVine __instance,
            ref float ___pumpkinHoursToGrow, ref float ___vineHoursToGrow, ref float ___vineHoursToGrowStage2)
        {
            //System.Diagnostics.Debug.WriteLine(__instance.Api.Side);
                ___pumpkinHoursToGrow = (float)(__instance.Api.World.Calendar.DaysPerMonth / 30.0) * 300f;
                ___vineHoursToGrow = (float)(__instance.Api.World.Calendar.DaysPerMonth / 30.0) * 300f;
                ___vineHoursToGrowStage2 = (float)(__instance.Api.World.Calendar.DaysPerMonth / 30.0) * 150f;
        }

### Expected behavior
For the above patch to not through an NPE in 1.16.5, and instead function as it does in 1.16.4.  (Which would be to not throw an NPE, and properly inject the above values.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by copygirl** [comment]
Out of curiosity. You call the method `Patch_BlockEntityPumpkinVine_CreatedFromParent_Prefix` but you don't actually prefix `CreatedFromParent` but instead `Initialize`? The first thing that Initialize does is [call `base.Initialize(api);`](https://github.com/anegostudios/vssurvivalmod/blob/16a7ad71e1bcc1210013e047b9b63131361c768d/BlockEntity/BEPumpkinVine.cs#L109), which sets the `Api` property in the first place. If I understand correctly you're inserting your patch **before** the base method is called, thus `Api` is `null`.

**Comment by VinterNacht** [comment]
Thank you! I had it working at one point and was blind-sided by my own refactor. >.< Close it, just me bein' dumb. XD

**Comment by copygirl** [comment]
Happens to everyone sometimes.
