### ISSUE TITLE
Mono Crash

### ISSUE THREAD

**Issue by RogueRaidenTV** [anegostudios/VintageStory-Issues#1860]
**Game Version:** 1.16.5 
**Platform:** Linux Ubuntu 20.04
**Modded:** Yes
**SP/MP:** Dedicated Server

C# Framework: Mono 6.12.0.122

### Description
Mono crash. Multiplayer server, several players online. Not sure what what happened to cause it.

[stacktrace0.5.txt](https://github.com/anegostudios/VintageStory-Issues/files/8498334/stacktrace0.5.txt)
[mono_crash.0.5.json.txt](https://github.com/anegostudios/VintageStory-Issues/files/8498335/mono_crash.0.5.json.txt)

**Comment by RogueRaidenTV** [comment]
not sure if it is due to a mod, but it looks like when someone breaks blocks out of a pit kiln it causes the mono crash

**Comment by RogueRaidenTV** [comment]
[pitkilnmonocrash.txt](https://github.com/anegostudios/VintageStory-Issues/files/8537135/pitkilnmonocrash.txt)


New crash report in the console

**Comment by RogueRaidenTV** [comment]
alright, i went though all of my mods and Campaign Cartographer is the culprit. when i only remove that mod it crashes, but does not crash when loaded alone.

**Comment by copygirl** [comment]
Thank you for pinpointing the issue down to a specific mod. :green_heart: I don't personally know what to do with Mono (or native) crashes, so I can't be of much help. Could be related to threading, or native resources - who knows?

I will close this issue for now until the issue can be traced back to the game (if at all).
