### ISSUE TITLE
xSkills on Multiplayer.

### ISSUE THREAD

**Issue by DagonUpadly** [anegostudios/VintageStory-Issues#1869]
**Game Version:** 1.6.8
**Platform:** Windows 
**Modded:**  Yes 
**SP/MP:** Multiplayer

### Description
Playing on MP server with mod XSkills making pottery crashes game. 

### How to reproduce
1. Start making pottery, after placing clay on the floor.
2. It crashes whole app

### Logs
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: sortablestorage@1.0.1, game@1.16.5, vshud@2.0.31, creative@1.16.5, survival@1.16.5, xlib@0.6.8, xskills@0.6.8
19.04.2022 09:44:46: Critical error occurred
System.MissingMethodException: Nie odnaleziono metody: 'Void Vintagestory.GameContent.BlockEntityClayForm.CheckIfFinished(Vintagestory.API.Common.IPlayer)'.
   w XSkills.BlockEntityClayFormPatch.Prefix(BlockEntityClayForm __instance, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode, ClayFormRenderer ___workitemRenderer, ItemStack& ___workItemStack, Cuboidf[]& ___selectionBoxes)
   w Vintagestory.GameContent.BlockEntityClayForm.OnUseOver_Patch1(BlockEntityClayForm this, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   w Vintagestory.GameContent.ItemClay.OnHeldInteractStop_Patch1(ItemClay this, Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   w Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   w Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   w Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   w _esGsESICkihAc8ShXuIoQwZFwP4._lPY9uZeagiMGC6tvSE11dF7naaz(Single )
   w _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   w _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 479
   w OpenTK.GameWindow.DispatchRenderFrame() w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 454
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 375
   w _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   w _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

```

**Comment by Craluminum2413** [comment]
Send this to the mod author https://www.vintagestory.at/forums/topic/1720-xlib-and-xskills

**Comment by copygirl** [comment]
This is an error in the mod, and could be caused from it not being compatible with version 1.16.5 of the game. Make sure you're using the latest version of the mod, then see if anyone else already already reported the issue to the author, and if not, report it to them.
