### ISSUE TITLE
Wildcard in base texture breaks overlays

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1871]
**Game Version:** 1.16.5 
**Platform:** Windows 
**Modded:** Yes 
**SP/MP:** Singleplayer

### Description
`whitemarble*` here makes overlays randomized
```json
  "textures": {
    "all": {
      "baseByType": {
        "@.*-(yellow|orange).*": "game:block/stone/rock/whitemarble*",
        "*": "block/stone/rock/{rock}*"
      },
      "overlaysByType": {
        "*-yellow*": ["game:overlay/ffd800-50"],
        "*-orange*": ["game:overlay/ff6a00-50"]
      }
    }
  },
```
If you change it to `whitemarble1`, overlays will be completely fixed

### How to reproduce
1. Make more than 2 base textures and name them e.g. as `mytexture1` and `mytexture2`
2. Add a wilrdcard to base texture e.g. `mytexture*`
3. Add any overlay
4. Overlays are broken

### Screenshots
`whitemarble*`:
![image](https://user-images.githubusercontent.com/69315569/164249730-99bbad0a-9368-489b-bba4-f6534d391bf5.png)

`whitemarble1`:
![image](https://user-images.githubusercontent.com/69315569/164249874-444f0d26-91c5-43ad-8bca-72997b184530.png)

**Comment by Craluminum2413** [comment]
As a workaround I used billions alternates:
```json
  "textures": {
    "all": {
      "baseByType": {
        "@.*-(yellow|orange).*": "game:block/stone/rock/whitemarble1",
        "*": "block/stone/rock/{rock}*"
      },
      "alternatesByType": {
        "@.*-(yellow|orange).*": [
          { "base": "game:block/stone/rock/whitemarble2", "overlays": ["game:overlay/{rock}"] },
          { "base": "game:block/stone/rock/whitemarble3", "overlays": ["game:overlay/{rock}"] },
          { "base": "game:block/stone/rock/whitemarble4", "overlays": ["game:overlay/{rock}"] }
        ]
      },
      "overlaysByType": { "@.*-(yellow|orange).*": ["game:overlay/{rock}"] }
    }
  },
```

**Comment by copygirl** [comment]
Correct me if I'm wrong but this smells like a feature request.
Are you sure the wildcard is meant to work in this context?

**Comment by Craluminum2413** [comment]
I used the same amount of texture as vanilla, except I added overlays, so I assumed overlays are broken

**Comment by Craluminum2413** [comment]
I found an another example from `ore-ungraded.json`
```json
  "textures": {
    "all": {
      "base": "block/stone/rock/{rock}1",
      "overlays": ["block/stone/ore/{type}1"],
      "alternates": [
        { "base": "block/stone/rock/{rock}1", "overlays": ["block/stone/ore/{type}2"] },
        { "base": "block/stone/rock/{rock}1", "overlays": ["block/stone/ore/{type}3"] }
      ]
    }
  },
```

**Comment by Craluminum2413** [comment]
So it was feature request actually
