### ISSUE TITLE
BlockEntityLabeledChest has hardcoded label's text position

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1873]
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
I didn't find anything in the code related to the position of the label's text

### How to reproduce
1. Move label element in the `survival/shapes/block/wood/chest/normal-labeled.json` shape about 5 cubes below for example
2. Load any world
3. Get and place a labeled wooden chest
4. Text has wrong position

### Expected behavior
Attribute with the ability to specify a position for text

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/164454910-b1fc3f40-80dc-4e37-865f-89c8e391419b.png)

**Comment by copygirl** [comment]
As the code for this is meant to only work for the Vanilla chest, this is a suggestion.
I recommend duplicating the labeled chest's code and implementing this in your own version.
