### ISSUE TITLE
[Handbook] Add the number of resulting items into the craft info

### ISSUE THREAD

**Issue by Quipex** [anegostudios/VintageStory-Issues#1878]
Currently (1.16.5) there is no indication of how many items the craft produces.
This can be confusing when planning on making complicated projects like cementation furnace.

This is how the recipy is currently rendered.
![image](https://user-images.githubusercontent.com/30311108/164895397-13a527ba-2a02-4642-b0ac-5d58a7078de7.png)

As of now, this craft produces 2 bricks but there is no way to know it in-game beforehand.
![image](https://user-images.githubusercontent.com/30311108/164895424-dcb49d97-0f13-4c79-b7d4-9436fa9683db.png)

It would be great if the handbook would show the number of resulting items.

**Comment by Craluminum2413** [comment]
All suggestions go there <https://www.vintagestory.at/forums/forum/5-suggestions/>
