### ISSUE TITLE
Gras do not regrows under chiseled block

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1880]
**Game Version:** 1.16.5
**Platform:** Linux (KDE neon 20.04 5.24)
**Modded:** No
**SP/MP:** Singleplayer

### Description
If you chisel a block on soil, the grass will vanish and not regrow.
Even is you destroy the chiseled block, the grass will not regrow. You have to destroy block around.
Empty block next to the soil with chiseled block on top causes grass to regrow as well.

### How to reproduce
1. Place e.g. cobblestone on soil
2. Use chisel to remove part of it to the ground
3. Speedup time
4. Grass will be removed
5. Destroy chiseled block
6. Grass will not regrow
7. Destroy the block in front of it
8. Grass will regrow

### Expected behavior
Grass should regrow on blocks exposed to light, even partially.
Grass should regrow, then the chiseled block is removed.

### Screenshots
**With chiseled block**
![2022-04-25_13-11-12](https://user-images.githubusercontent.com/47914240/165080905-1e4111c4-54a1-4d1c-b68d-c125a13f6ed9.png)

**Without chiseled block**
![2022-04-25_13-23-57](https://user-images.githubusercontent.com/47914240/165081242-aabf0308-1f4d-4547-b2f9-29d3c558ecc7.png)

**Comment by copygirl** [comment]
Related: #200

**Comment by daretmavi** [comment]
It seems to work pretty good in 1.18.1
