### ISSUE TITLE
Add Crafting window to Creative mode

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#189]
It's a wee bit annoying when I'm testing recipes and need to switch between Survival and Creative to craft something

**Comment by tyronx** [comment]
You can map /gamemode survival and /gamemode creative to single keyboard keys using the macro manager, just sayin'
(I have it mapped to 'I' and 'O')

**Comment by tyronx** [comment]
hm, but the creative menu should probably stay on default inventory key.

**Comment by copygirl** [comment]
Would it be possible to default the creative GUI on the same key as the inventory GUI, except with higher priority, so you can change it if you want to access both individually?

**Comment by tyronx** [comment]
Everything is possible ;-)

**Comment by tatsu011** [comment]
Thought.  Inventory on it's own tab before all other tabs in the creative menu.

**Comment by Balduranne** [comment]
> 
> 
> Thought. Inventory on it's own tab before all other tabs in the creative menu.

This would be ideal honestly.

**Comment by tyronx** [comment]
Rather as a tab on the right hand side, so it's not confused with a creative tab

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
