### ISSUE TITLE
Inconsistent Fly Agaric HP values

### ISSUE THREAD

**Issue by l33tmaan** [anegostudios/VintageStory-Issues#1895]
**Game Version:** 1.16.5
**Platform:** Windows 7
**Modded:** No 
**SP/MP:** Singleplayer

This isn't really a 'bug', but I wasn't sure where else to put it. Mushroom.json has this code starting at line 28: 

```		
nutritionPropsWhenInMeal: { 
			satiety: 120,
			foodcategory: "Vegetable",
			healthByType: {
				"*-flyagaric-*": -10,
				"*-earthball-*": -8,
				"*-deathcap-*": -50,
				"*-funerallbell-*": -40,
				"*-elfinsaddle-*": -7,
				"*-jackolantern-*": -6,
				"*-devilsbolete-*": -10,
				"*-pinkbonnet-*": -10,
				"*-flyagaric-*": -6.5,
				"*-bitterbolete-*": -3,
				"*-devilstooth-*": -2,
				"*-golddropmilkcap-*": -2.5,
				"*": 0
			}
		},
```

Notably, fly agaric is in here twice. I assume the -6.5 value is correct and the -10 is incorrect?

**Comment by l33tmaan** [comment]
Oh, it looks like 'funeralbell' is misspelled here, too. It isn't triggering the -40 HP because of it - but I also noticed that the regular funeral bell mushroom doesn't kill you, so I'm uncertain if it should be poisonous or not.

**Comment by copygirl** [comment]
Typos can be bugs, too!

**Comment by RedramVS** [comment]
I had updated the files to be consistent on fly agaric, and also fixed that devilbolete was not having any health malus applied (due to name typo).  However, Funeralbell and Pinkbonnet also are not having their health malus applied, and I cannot figure out why.  They are both side-mushrooms, for whatever that is worth.  All the correctly working poisonous mushrooms are in the normal mushroom blocktype.

**Comment by l33tmaan** [comment]
Do they need '*-north' applied to them, since they're side mushrooms? I had
to do that when referencing them for Expanded Foods.

**Comment by Craluminum2413** [comment]
Then it should be `@.*-(north|east|west|south)` to apply such value to all four variants

**Comment by RedramVS** [comment]
Tagging north onto the end (i.e. "*-pinkbonnet-*-north": -10,) did not do anything.  If that's the form you meant.  Nor did "*-pinkbonnet-normal-north".  I think you're probably right that it's some kind of naming problem, as I've run into that before.  I think it required Tyron to code it to 'accept' the asterix in a certain spot or configuration, for a given property...

**Comment by sirStroam** [comment]
The issue for which this was opened has been fixed RC 2. Please open new issue for the issue with mushroom health malus not being applied.
