### ISSUE TITLE
cashed when start new world

### ISSUE THREAD

**Issue by Margothp** [anegostudios/VintageStory-Issues#1914]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: bettercrates@1.3.0-rc.2, fulldrop@1.0.0, LargerStacks@1.0.1, game@1.16.5, carrycapacity@0.6.2, farmlanddropssoil@1.4.0, hudclock@2.5.0, creative@1.16.5, vsprospectorinfo@4.1.0, survival@1.16.5
31-05-2022 17:42:55: Critical error occurred
System.MissingMethodException: Método no encontrado: '!!0[] Vintagestory.API.Datastructures.JsonObject.AsArray(!!0[])'.
   en CarryCapacity.Common.BlockBehaviorCarryable.TryGetVec3f(JsonObject json, String key, Vec3f& result)
   en CarryCapacity.Common.BlockBehaviorCarryable.GetTransform(JsonObject json, ModelTransform baseTransform)
   en CarryCapacity.Common.BlockBehaviorCarryable.Initialize(JsonObject properties)
   en Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(_RQM0p3FsENB5dR4EsSMUH8ovhQF packet, IWorldAccessor world, ClassRegistry registry)
   en Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssetsStep1()
   en Vintagestory.Client.NoObf.GeneralPacketHandler.HandleLightLevels(_m4CVIcO3UJPLI62MuOxE8163nQH packet)
   en Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   en _vuG4DGUoqAIliPHbC5Jd2S4bgWAA._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   en _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   en _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   en Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 479
   en OpenTK.GameWindow.DispatchRenderFrame() en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 454
   en OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 375
   en _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   en _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 26-04-2022 20:04:11, Site = , Source = Application Hang, Message = El programa Vintagestory.exe (versión 1.16.5.0) dejó de interactuar con Windows y se cerró. Para ver si hay más información disponible sobre el problema, comprueba el historial de problemas en el panel de control de seguridad y mantenimiento.

**Comment by Craluminum2413** [comment]
The problem is in Carry Capacity mod

**Comment by copygirl** [comment]
Can confirm, this would be the problem.
