### ISSUE TITLE
The bug with the endless piece of pie

### ISSUE THREAD

**Issue by Ampiriy** [anegostudios/VintageStory-Issues#1916]
https://user-images.githubusercontent.com/106914774/172051380-f7b0aacb-84be-4bbd-acca-1b627273824e.mp4

If you eat part of a piece of pie and then put it on the ground and pick it up again with a knife, it will again be a 0.25 portion, even if it was less than that before. The video shows everything, pay attention to the number of servings left:
There was a whole piece of 0.25 servings, I ate it, and there are 0.09 servings left. I put it on the ground and took a knife, again 0.25 servings

**Comment by Ampiriy** [comment]
Game Version: 1.16.5
Platform: Windows 10
Modded: no added mods
SP/MP: Singleplayer survival/creative

**Comment by wasakoki** [comment]
still present in 1.17rc3

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed next release
