### ISSUE TITLE
Visual bugs on 1.17 pre

### ISSUE THREAD

**Issue by VolkodavMstivoy** [anegostudios/VintageStory-Issues#1922]
1.17-pre1
Windows 10
**Modded:** No
 Singleplayer

### Description
Gazelle do not have death animation

### How to reproduce
Kill a Gazelle

### Screenshots
Dead Gazelle
https://imgur.com/t1K8Byk

### Logs

If I need them I will edit post I guess Screens are enough

**Comment by copygirl** [comment]
These should ideally be split into multiple separate issues so they can be worked on and then closed individually.
Could you do that for me? Thank you for reporting these, however!

**Comment by VolkodavMstivoy** [comment]
> These should ideally be split into multiple separate issues so they can be worked on and then closed individually. Could you do that for me? Thank you for reporting these, however!

Three issues will be. We will start from easiest

**Comment by copygirl** [comment]
Thank you, I will close this issue then.

**Comment by copygirl** [comment]
Oh, you used this issue for the gazelle death animation. As it turns out, it will be fixed for the next version!
