### ISSUE TITLE
Harvesting papyrus or reeds with a knife in water

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1925]
**Game Version:** 1.17-pre1
**Platform:** linux kubuntu   
**Modded:** No  
**SP/MP:** Singleplayer  

### Description
Harvesting papyrus or reeds in water acts like using a scythe instead of a knife.

### How to reproduce
1. Go to a group of papyrus in water.
2. Step in water and cut a papyrus (or reed) 
3. The papyrus and its neighbors are cut, and the root is even extracted

The durability of the knife is decreased by 1, not the total number of harvested plants.

**Comment by Craluminum2413** [comment]
It doesn't act as a scythe, reed blocks just break when due to OnNeighbourBlockUpdate

**Comment by Craluminum2413** [comment]
Also it affects only generated reeds/papyrus

**Comment by mahgeetah** [comment]
I found another way to reproduce this.
1. Find reed that is in water.
2. Place rock on tile next to reed.
3. Pick up rock while your cursor is also hovering over the reed.
4. Reed harvests itself.

**Comment by Craluminum2413** [comment]
It completely confirms my theory above that the knife has nothing to do with it.
That is, `OnNeighbourBlockChange` is the only culprit
