### ISSUE TITLE
Termite mounds drop themselves

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1926]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place/find a large/medium termite mound
2. Break a block below
3. Termite mound is dropped instead of termites

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/173695442-72801549-6ce7-4d86-969c-b2b11509a725.png)

**Comment by Aledark789** [comment]
Unsure if its a bugged always used to be like that with old ones too, some people like to pick em up and bring them over to their base to decorate. Would be neat if they would just do the stick-termites to get the termites out like we had once (not completed) like 1.14 or 1.15? But for realisms, yea probably shouldnt be able to move them.

**Comment by Craluminum2413** [comment]
Termite mound in every version of the game dropped only termites on breaking

**Comment by RedramVS** [comment]
Both sizes were dropping termites when I checked.  But I did change it so they have some variability, and the larger mound drops more.
