### ISSUE TITLE
Typos in Crowdin's English text

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1928]
**Game Version:** 1.17  

![steelmankin](https://user-images.githubusercontent.com/26251843/173771460-3085b952-f4eb-4a37-9f13-09ea7322a7f4.png)

You forgot to add the 2 new stone types for the coffin in the English description (basalt and peridotite).

Also:
There is "Horsehound" and "Horsehound bundle" in Crowdin. I could not find any Horsehound plant on google. But I've found a Horehound plant. So maybe it is a typo.

**Comment by Xandoria** [comment]
In creative mode I can see that there are 3 Book Stands : one with a closed book, one with an open book and one without any books. The one without book is not named "Book Stand". The name is "game-clutter-bookshelves-bookstand-empty"

**Comment by Xandoria** [comment]
When juiced: Turns into {0}l {1}
This is in Crowdin and is translated but is not translated in game

**Comment by Xandoria** [comment]
In the description of seeds, the growth time is displayed in days. The word "days" is not translated though there is a "{0} days" translated entry in Crowdin.

**Comment by Xandoria** [comment]
"For reorienting chutes, stairs, slabs and plasater"
"plaster" instead of "plasater"?

**Comment by Xandoria** [comment]
Description of pickaxes (and saws?). A space is missing after the ":" for the mining speed.

**Comment by Xandoria** [comment]
![portions](https://user-images.githubusercontent.com/26251843/176225452-93a6f263-1e5b-4a3d-a5c3-edffa9bd3d14.png)

{0} serving of {1} in {2}
is ok

but the plural version
{0} servings of {1} in {2}
is not ok, though it has been translated in Crowdin

**Comment by Xandoria** [comment]
The string
Will ripen in {0} days
is for the plural but there is no string for the singular

May I suggest you add in Crowdin the string
Will ripen in 1 day

**Comment by Xandoria** [comment]
**1.17.0 pre 2**
![tooltip](https://user-images.githubusercontent.com/26251843/177043631-e51d8339-f8f4-4910-8b45-624dea2e84ba.png)
Not translated in red

**Comment by Xandoria** [comment]
![tooltip2](https://user-images.githubusercontent.com/26251843/177043737-1aea42d6-c800-4be1-adb8-3aa1eddb8068.png)

**Comment by Xandoria** [comment]
1.17.0 rc 2
About the new color grid selection for the waypoints, may I suggest replacing:
Color (<a href="https://yorktown.cbe.wwu.edu/sandvig/shared/NetColors.aspx">List</a>)
by simply "Color" in Crowdin

**Comment by Xandoria** [comment]
1.17.0 rc 7
In Crowdin there is the entry : "Cannot build or break blocks at this location, this land is claimed by {0}"
When {0} is a merchant, the display is "Trader" ingame. No translation is occuring.

**Comment by Xandoria** [comment]
1.17.2
Not in Crowdin : "Tree state: Flowering"

**Comment by Xandoria** [comment]
1.17.2
Not translated in the game:
![barrel](https://user-images.githubusercontent.com/26251843/188882310-6027a64f-d7bf-40fe-b507-c2e29bf77cc2.png)

**Comment by Xandoria** [comment]
1.17.3
"Empty" status for crates is not translated in the game
![barrel](https://user-images.githubusercontent.com/26251843/189493165-2ac764cc-ab21-48c7-a958-668c6d9b9a8f.png)

**Comment by Craluminum2413** [comment]
> 1.17.3 "Empty" status for crates is not translated in the game ![barrel](https://user-images.githubusercontent.com/26251843/189493165-2ac764cc-ab21-48c7-a958-668c6d9b9a8f.png)

Same for "Contents: " key

**Comment by Xandoria** [comment]
1.17.3
Not translated in the game:
![character](https://user-images.githubusercontent.com/26251843/190650502-08bb4501-8605-4377-ad51-3814e807eb55.png)

**Comment by Xandoria** [comment]
1.17.4
Not translated in the game:
![forge](https://user-images.githubusercontent.com/26251843/192300282-eb890cc9-5e9d-4d8e-8314-f138687f6b11.png)

**Comment by Xandoria** [comment]
1.17.9
Not translated in the game, no entry in Crowdin:
![fruit_tree](https://user-images.githubusercontent.com/26251843/197019362-e40eca64-19f4-4d43-adc0-e29ef62c7a12.png)

**Comment by tyronx** [comment]
Thanks a lot for the reports. This should all be fixed next release except for plural formatting - were plannign something more universal for this
