### ISSUE TITLE
Hay

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1929]
**Game Version:** 1.17.0-pre1
**Platform:** linux kubuntu
**Modded:** No  
**SP/MP:** Singleplayer   

### Description
Placing a hay on a wall create a new (lame) kind of hay

### How to reproduce
1. Place a hay on a wall (not on the ground)
2. Put it back in your inventory.
3. The hay is slanted 90° and does not stack with your other hays.
4. Put this slanted hay in the grid, you cannot revert it to dry grass like with usual hay.

### Screenshots
![image](https://user-images.githubusercontent.com/84909583/173782614-a7abd02b-cf5f-4ad2-9a50-d61650a4fb9e.png)

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-pre.2](https://info.vintagestory.at/v1dot17#:~:text=Fixed%3A%20Wrong%20drops%20for%20hay%20block%20(thanks%20Stroam))
