### ISSUE TITLE
Land claim limited to some small space

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#1930]
hi, land claiming is limited to some small space only. Changing of limits in world configuration doesn't help. We need much bigger claims to protect players on our MP server. We should add a lot of separate claims to reach our demanded protection (of CITY for example). Porcess of claiming area 500x500 (150 heigh) is a nightmare... you need to create a lot of small claims and very precisely face one by another. 
The big problem is that you don't know how much and where will be your claim cutted down (you marked start and end but final claim is only fraction of your marked area without any warning/message !!!!).

Moreover claims don't allow claim in claim (necessary for city full of players houses).

I hoped this will be in new 1.17 version but it seems it's not.

I think the multiplayer experience is major factor of VS playing. Missing proper claiming (not limited to small land parts) is essential !!!

When I'm reading all new improvements of 1.17 that are (I am sure) great and I see something like proper claiming system is still missing I feel disappointed and frustrated a lot. I'm pleased by all of the graphics improvement in new version but believe me I'd exchange a lot of them for proper claiming system.

Please Tyron and other  developers rethink it and make something for MP servers, please !!!!

Thank you.

Petr Nowak (DrEngine)
VS registered player
"Djinland" VS MP server admin

**Comment by copygirl** [comment]
I agree with you that this would be important, but the issue tracker unfortunately is just for bugs, not suggestions. I suggest writing this up as a forum thread and/or post it on the Discord. There's still a chance for this to make it into 1.17.
