### ISSUE TITLE
Crude shield crafting conflicts with Layer of sticks

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1931]
**Game Version:** 1.17.0-pre1
**Platform:** linux kubuntu   
**Modded:** No 
**SP/MP:** Singleplayer 

### Description
One of the recipes to craft a crude shied is the same as the Layer of sticks : grid full of sticks. Crafting Layer of sticks is now impossible.

### Screenshots
![image](https://user-images.githubusercontent.com/84909583/173814259-3d090738-d4fb-4763-93c6-de2917b0c266.png)

**Comment by RedramVS** [comment]
The all-sticks shield recipe has been removed.
