### ISSUE TITLE
Dupe in crafting grid output

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1934]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Thanks to skif_97 for finding this bug

### How to reproduce
1. Get 4 twine
2. Open crafting grid
3. Arrange the twine so that you get a linen
4. Press `Q` on the `linen` in output slot
5. It dropped a linen and didn't consume the ingredients
6. Take and put any twine in place
7. Repeat 4-5 steps infinitely

### Videos

https://user-images.githubusercontent.com/69315569/173843472-d8597c73-bf1b-4094-888b-c66dfd85bd77.mp4

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.3
