### ISSUE TITLE
Not able to craft basalt and peridotite coffin section/lid

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1935]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open the handbook
2. Search for basalt coffin section
3. Open its handbook page
4. It doesn't have a recipe

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/173846104-89c3650a-0dbd-4688-8fb1-7bd302534ad6.png)

**Comment by Xandoria** [comment]
Same for the new sod roof blocks. Recipe not implemented yet.

**Comment by Saricane** [comment]
Why did you change the title ? I'm not able to craft a peridotite coffin. It seems the first title was adequate.

**Comment by Craluminum2413** [comment]
Fixed in [1.17.2](https://www.vintagestory.at/forums/topic/9406-stabler-de-jank-and-game-juice-update-1172/#comment-40205:~:text=Fixed%3A%20Missing%20recipes%20for%20peridotite%20and%20basalt%20coffins)
