### ISSUE TITLE
Shot arrow breaks immediately on impact 

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1936]
**Game Version:** 1.17.0-pre.1 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Put a bow into active hand
2. Get steel arrows
3. Shoot an arrow
4. It break in 100% cases

**Comment by tyronx** [comment]
thanks for the report. will be fixed in pre.3
