### ISSUE TITLE
Can't climb onto stairs from snow

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#194]
1.7.0, Public Testing Server

When standing on a snow block - either with additional snow layer or without it - I can't step up into an ajancent wooden stairs block.

![2018-09-29_11-31-54](https://user-images.githubusercontent.com/25122345/46243323-b400b700-c3db-11e8-9c0a-3b98572151a0.png)

**Comment by tyronx** [comment]
hm, seems to work just fine for me

**Comment by tyronx** [comment]
I would dare say this is intentional behavior

**Comment by Heptagon-ru** [comment]
Even with an additional snow layer? Intentional is fine, but it is not clearly visible from the snow block visuals that it has less voxels. So people might keep asking the same questions again.

**Comment by tyronx** [comment]
true, the additional snow layer should probably make it so that the block below has a full collisionbox

**Comment by Heptagon-ru** [comment]
Also it might be annoying to build/settle in the snow regions. Altho you can just add few blocks around the stairs to climb them perfectly.

**Comment by Craluminum2413** [comment]
Can't climb onto stairs/slanted roofing from `snow block`/`moist farmland`

**Comment by sirStroam** [comment]
Intentional mechanic. Closing
