### ISSUE TITLE
No held tooltip for changing toolMode for prospecting pick

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1941]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Put a prospecting pick into active slot
2. No held tooltip appeared

### Expected behavior
A held tooltip about changing `toolMode` with `F` key

**Comment by tyronx** [comment]
thanks for the report, i addressed this for pre.3
