### ISSUE TITLE
New shields are rendered incorrectly when placed on tool rack

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1946]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer  

### How to reproduce
1. Place a tool rack
2. Put 4 any new shields on it (e.g. acacia, oak, maple etc.)
3. It is rendered wrong

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/174063652-eb21efc1-4eb0-4232-98ba-3c77925cfbc0.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed for pre.3

**Comment by Craluminum2413** [comment]
Just for case, I meant their appearance, not toolrackTransform

**Comment by tyronx** [comment]
Yes, they'll show with the correct texture in pre.3
