### ISSUE TITLE
Facial hair disappears with open face (or similar) helmets though you can still see the face.

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#1948]
**Game Version:** 1.16.5
**Platform:** Windows 
**Modded:** Yes though it works like this in non-modded too
**SP/MP:** Singleplayer / Multiplayer (both)  

### Description
Facial Hair is removed by any head gear. May only effect beard or both beard and moustache.

### How to reproduce
1. Make a character with a beard/moustache
2. Wear a helmet where you can see the face (ie. Gamboised helm is perfect for this)
-or-
3. Wear a helmet where you can't see the face.

### Expected behavior
Beard/moustache visible or "tuck" option to make invisible when wearing head armor.

### Screenshots
![Untitled-1](https://user-images.githubusercontent.com/13642054/174076216-ef0aaee1-d185-4902-ab26-5c16cfa09a8f.png)

**Comment by Guimoute** [comment]
That also includes the `fur coat` item which is a chest piece but comes with a hood.
