### ISSUE TITLE
Rendering bug 1.17-pre1

### ISSUE THREAD

**Issue by VolkodavMstivoy** [anegostudios/VintageStory-Issues#1949]
1.17-pre1
Windows 10
**Modded:** No
 Singleplayer

### Description
 Border of new generated world have bugs (screen)

### How to reproduce
 Generate world on 1.16 and go to 1.17, on border of generated terrain will be bugs.

### Screenshots
First time i visited border and second time, same place (they are slighly different and I can take more screenshots if needed from ther parts)
https://imgur.com/a/zeS1xyj

### Logs

If I need them I will edit post I guess Screens are enough

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.2
