### ISSUE TITLE
New chunk property: VS version it was generated in

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#195]
Please consider addiing this property and a public command to check it.
This might be useful when exploring on servers, to see if current chunks are already new.

**Comment by copygirl** [comment]
And if they don't already, the date and time they were generated / last modified?

**Comment by tyronx** [comment]
The VS Version is now stored with each chunk during creation. Date and time, not so sure if we really need that overhead.
