### ISSUE TITLE
Fired crocks blowing in the wind when placed

### ISSUE THREAD

**Issue by Keerp96** [anegostudios/VintageStory-Issues#1950]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer  

### Description
Fired crocks have the wobbling effect applied that grass/leaves use when it's windy. Effect doesn't seem to appear immediately after being fired, only when picked up and placed again.

### How to reproduce
1. Fire raw crocks.
2. Pick up fired crocks.
3. Place while it is windy.

### Expected behavior
Fired crocks not having wobbly effect applied while it's windy.

### Screenshots
https://user-images.githubusercontent.com/1152200/174286808-3c3ed098-df02-49c8-8a5e-dcf3e87c3270.mp4

**Comment by Craluminum2413** [comment]
I cannot reproduce that

**Comment by Keerp96** [comment]
> I cannot reproduce that

It doesn't happen every time, so far I haven't been able to figure out what exactly causes it, aside from it being windy. Also now I've seen it happen to other objects as well, cooking pots, crucibles, meat that's being roasted on the firepit.

**Comment by Xandoria** [comment]
I can confirm that. It happens to me for the cooking pot and for the crocks.

**Comment by Saricane** [comment]
This happens for a large variety of objects, stored on ground or on racks, even the quern. When the wind blows. Great for house animation.

**Comment by tyronx** [comment]
We've been looking at the code carefully, but due to its hard-to-reproduce natures its tough to find the cause of this.

**Comment by Rosethorns** [comment]
If it helps here are some specifics I have noticed.

- It only seems to occur to items placed during storms.
- the affected item will no longer be "windy" when reloading the world.
- If there is already an unaffected item on the ground then only the item added to the ground storage will be affected.

For example: If I have a ground storage containing a Cooking Pot. And then I add a bowl to the same ground storage during a storm only the bowl will be affected by the wind shader. Further, if I remove that bowl from the ground storage and re-add it once the storm is over it will continue to be affected by the wind shader. This will continue until the world is reloaded.

All of this screams to me that its got something to do with shaders applied during a storm and only during a storm.
Hope it helps!

**Comment by tyronx** [comment]
Thanks for the input. We do believe to have found the cause of this and have addressed this for pre.3!
