### ISSUE TITLE
Propick Density Search Mode results do not appear.

### ISSUE THREAD

**Issue by Keerp96** [anegostudios/VintageStory-Issues#1951]
**Game Version:** 1.17.0-pre.1  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Propick Density Search Mode results do not appear. The "too close" and "too far" messages do appear when used incorrectly, but when used correctly, the results do not appear.

### How to reproduce
1. Use propick in the correct way.
2. After 3rd block is mined, no message appears.

### Expected behavior
Ore density results appearing in the info box.

### Screenshots
![image](https://user-images.githubusercontent.com/1152200/174430670-deb1270a-a179-47d9-8503-4c3bf0c3363c.png)

**Comment by pantherpusher** [comment]
I'm seeing the same issue

**Comment by tyronx** [comment]
thanks, should be fixed in pre2
