### ISSUE TITLE
Fish run on the ground after escaping water on the same flat

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1955]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Make / find a lake with fish
2. Make flat surface around on the 1 layer below water
3. Make a fish run away from the water to the ground
4. Fish run very fast when escaped the water

### Videos

https://user-images.githubusercontent.com/69315569/174574715-50130ca9-11dc-464a-bb5a-ee1c6c024c61.mp4

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in pre.3
