### ISSUE TITLE
Doesnt place schematics with non "game" domain

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1959]
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** Yes 
**SP/MP:** Singleplayer 

### Description
Game dosent place any schematics throught code.
If domain  correct - no errors, otherway NullPointer exception, so it sees file.
If domain "game" - placing correctly

code sample
```
schematicFromAsset = api.Assets.TryGet(
                new AssetLocation("game", "worldgen/schematics/overground/flu.json")).ToObject<BlockSchematicStructure>();
               ```

**Comment by tyronx** [comment]
This code does not place a schematic, it only loads it.

**Comment by tyronx** [comment]
Closing this as incomplete report. Feel free to reopen if you got more info on this.
