### ISSUE TITLE
Ingredients not consumed when crafting

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1964]
**Game Version:** 1.7.0 pre 1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Ingredients for the Improvised body armor (Wood) not consumed when crafting.

### How to reproduce
1. Put ingredients in grid
2. Open character's sheet
3. Take the Improvised body armor (Wood) from the grid
4. Place it in the body armor slot in the character's sheet
5. Close the character's sheet
6. Ingredients are still in the inventory

**Comment by tyronx** [comment]
thanks for the report, this is fixed for pre.3
