### ISSUE TITLE
Clay item texture in item preview is white

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1965]
**Game Version:** 1.17.0-pre.1 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Get a blueclay or fireclay
2. Open an inventory and hover over its icon
3. Item preview is showed and it turned out white

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/175769676-e559902a-6fa7-4027-93ff-717f8e75e702.png)

**Comment by tyronx** [comment]
does this still happen in pre.2? I cannot reproduce it there

**Comment by Craluminum2413** [comment]
Yes it still happens for me in pre.2, I even opened clay item page and it gets even worse

https://user-images.githubusercontent.com/69315569/177002436-e9ee5983-d4fc-4036-964a-e4d95b8a314b.mp4

**Comment by tyronx** [comment]
ah i see. thanks for the report. fixed for pre.3
