### ISSUE TITLE
Can put up to 255 different items in ground storage

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1966]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Ground storage can store up to 255 different items in a single block

### How to reproduce
1. Place a crock or anything else that create a ground storage
2. Place a chute above
3. Place a chest above the chute
4. Put 3 different into the chest
5. Wait until it end up pulling items into ground storage
6. Pick up a crock
7. Now you have a massive ground storage in a single block

### Videos / Screenshots
Example of a few different stacks of items inside a single ground storage:
![image](https://user-images.githubusercontent.com/69315569/175770785-1534a86d-fe56-434f-acf2-472fd02f7bc7.png)

Start:

https://user-images.githubusercontent.com/69315569/175770111-c60329a0-cd8f-4cd9-a54f-9d93c8609fb0.mp4

End:

https://user-images.githubusercontent.com/69315569/175770112-a789e0c2-9451-4249-81c2-8547cc53f333.mp4

**Comment by tyronx** [comment]
thanks for the report. I've disabled chute transfer into ground stroage for now.
