### ISSUE TITLE
Empty block after clayforming in water

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1967]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Can be fixed if you place something in that block

### How to reproduce
1. Start a clayforming underwater
2. Once you end, it creates a strange empty block in water block

### Expected behavior
Nothing changed

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/175770329-08bc43d8-0c70-43ea-8766-a777fcecb498.png)

**Comment by copygirl** [comment]
Gonna mark this as a duplicate of #1962.
