### ISSUE TITLE
Copper hammer usable in anvil

### ISSUE THREAD

**Issue by TonyLiberatto** [anegostudios/VintageStory-Issues#197]
There is no tier base for hammers.
copper hammers can be used to work on an iron anvil to create iron tools.
My mod adds Stone Hammers, and so they too are usable in the hammer. 
We add them for crushing and the recipe uses.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
