### ISSUE TITLE
1.17 pre 1: schematics not updated with old swords in loot. (fifty-fifty.json)

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1973]
**Game Version:** 1.17 pre 1
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Singleplayer

### Description
24.6.2022 14:18:58 [Warning] Block schematic file fifty-fifty.json uses items that could no longer be found. These will turn into unknown items! (affected: game:sword-iron)
24.6.2022 14:19:06 [Warning] Cannot fix itemstack mapping, item code game:sword-iron not found item registry. Will delete stack.

24.6.2022 14:22:29 [Warning] Failed resolving a blocks itemdrop or smeltedstack with code game:shield-wood-tinbronze in tradeItem resolver
### How to reproduce
Just start a new world...explore the world flying around and see the errors comes up:

**Comment by LukeUnbound** [comment]
Thanks, should be fixed now.
