### ISSUE TITLE
Wallpaper on a `WrenchOrientable` block completely disappear when wrench is used

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1974]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
It is only related to Decor that never drop itself (as wallpaper), while linen etc. is dropped

### How to reproduce
1. Place a plaster
2. Attach a wallpaper to it
3. Rotate with wrench
4. Wallpaper disappeared

**Comment by Th3Dilli** [comment]
I am not sure when but wrench orientable blocks no longer do remove decors 
and not wrench orientable block do nothing 

so this should be fixed
