### ISSUE TITLE
Visible border between worldgen water and filled water

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1978]
**Game Version:** 1.17.0-pre1  
**Platform:** kubuntu   
**Modded:** No 
**SP/MP:** Singleplayer survival on 1.17 map  

### Description
When filling a "native" (from worldgen) water block with a bucket, the block is then delimited by a green vertical border on its sides.
This effect dissapears after a while (I don't know if this is after loading the game or unloading the chuck when far away).

### How to reproduce
1. Take a bucket
2. Play with water on a natural pond.

### Expected behavior
a flawless junction between worldgen and filled water blocks.

### Screenshots
![water](https://user-images.githubusercontent.com/84909583/175952207-d5da5c8a-466d-4473-83cb-77d30471d1df.png)

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-pre.3](https://info.vintagestory.at/v1dot17#:~:text=Fixed%3A%20Should%20fix%20oddities%20when%20placing%20water%20from%20a%20bucket%20in%20existing%20water)
