### ISSUE TITLE
Protected doors/gates allow to pass thru

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#198]
1. When I try to open a double door or gate, the part I click on does not open and does not allow me to pass as expected.
But the other part is opened and I can freely pass. Altho when relogging it is closed again.
2. If I am walking into the door/gate and opening it, it allows me to pass for that split second it is "opened" before the protection catches up.

![2018-10-01_11-31-29](https://user-images.githubusercontent.com/25122345/46277978-919ea300-c56d-11e8-94b1-a2047937951b.png)

**Comment by darnuria** [comment]
Confirmed on Chrometech last week:

![Screenshot from 2020-05-08 03-33-49](https://user-images.githubusercontent.com/2827553/81622170-86ba1e80-93f0-11ea-9ac0-5a836e325a6a.png)
![Screenshot from 2020-05-08 03-33-55](https://user-images.githubusercontent.com/2827553/81622190-8e79c300-93f0-11ea-97c6-c761e09e96bf.png)
![Screenshot from 2020-05-08 03-33-57](https://user-images.githubusercontent.com/2827553/81622199-946fa400-93f0-11ea-9099-3640340b7248.png)

I was able to glitch into a fence door and also a door. :(
