### ISSUE TITLE
Cannot plant cattails in water

### ISSUE THREAD

**Issue by VinterNacht** [anegostudios/VintageStory-Issues#1982]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Singleplayer 

### Description
Cannot plant cattail roots in eligible blocks underwater

### How to reproduce
Get cattail root, right-click block under one block of water. Does not plant.

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-pre.2](https://info.vintagestory.at/v1dot17#:~:text=Fixed%3A%20Unable%20to%20plant%20reeds/papyrus%20in%20flowing%20water)
