### ISSUE TITLE
Snow doesnt fall to gravity, behaviors tag is missing

### ISSUE THREAD

**Issue by Marcafk** [anegostudios/VintageStory-Issues#1983]
1.17 pr2
Windows 
Modded: No
Singleplayer

### Description
snow doesnt fall when the gravity setting is enabled
in addition the following error is apparent in the server-main log 
"30.6.2022 17:19:47 [Error] Patch 6 (target: game:blocktypes/liquid/snowblock.json) in game:patches/fallingblocks.json failed because supplied path /behaviors/- is invalid: The json path /behaviors/- was not found. No such element 'behaviors' at the root path"

### How to reproduce
Create or load a world with soil gravity enabled.
Build a tower of snow blocks.
They fail to fall down

### Expected behavior
They should fall down. In 1.15 snow was gravity affected, this bug is also present in 1.16

### Screenshots
![image](https://user-images.githubusercontent.com/12321620/176618133-4d8e9a8c-88eb-4fbe-b270-f11fb9d6baa0.png)

### Logs
```
30.6.2022 17:19:47 [Error] Patch 6 (target: game:blocktypes/liquid/snowblock.json) in game:patches/fallingblocks.json failed because supplied path /behaviors/- is invalid: The json path /behaviors/- was not found. No such element 'behaviors' at the root path
```
 Adding the behaviors tag fixes the error 
 1.16 had a similar issue with peat, which now has the following tag that fixed the issue.
 "	behaviors: [],"

**Comment by tyronx** [comment]
thanks for the report, will be fixed in pre.3
