### ISSUE TITLE
Wrench : wrong placement on tool rack

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1984]
**Game Version:** 1.17.0-pre2
**Platform:** kubuntu
**Modded:** No 
**SP/MP:** Singleplayer survival on 1.17 worldgen

### Description
When placed on a tool rack, the wrench is floating in front of the board.

### Screenshots
![2022-06-30_18-24-55](https://user-images.githubusercontent.com/84909583/176730095-3eac2d08-11de-4690-9342-685ee49c5775.png)

**Comment by tyronx** [comment]
thanks for the report, will be fixed in pre.3
