### ISSUE TITLE
Cooking pot can contain fractional number of meals

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1985]
**Game Version:** 1.17.0-pre2
**Platform:** kubuntu
**Modded:** No 
**SP/MP:** Singleplayer  survival

### Description
Disclaimer : I don't know if this is a bug or a new undocumented feature in 1.17.

When your bowl is not empty, you can now filling it again (with the same recipe, of course), letting a fractional number of meals into the cooking pot (e.g 1.4 meal). Previously, the bowl had to be empty, so that you can only take a full meal from the cooking pot.

I just add that I prefer this new mechanism, this allows to go away exploring with a full bowl in the inventory. Hope this is not a bug.
Once again, please excuse me if this a new feature and I missed the announce.

### Screenshots
![image](https://user-images.githubusercontent.com/84909583/176905416-e7b4c5d5-d809-4f32-895a-fb1978289bd9.png)

**Comment by copygirl** [comment]
As look as you can take the rest of the meal out of the cooking pot if it's less than 1 whole serving, I don't see how this could be a bug?

**Comment by tyronx** [comment]
yea i think this is fine
