### ISSUE TITLE
ProPick density mode not working

### ISSUE THREAD

**Issue by wbottenberg** [anegostudios/VintageStory-Issues#1986]
Platform: 64 bit Windows 10 
Game Version 1.17.0p1
SP/MP: Single
Modded: edited jsons for seed drop count
Mode: Explorer
Payability with this bug: Cannot advance in ore finding tree

Propick in Density Search mode:
 sees first sample, says "Ok, need 2 more samples"
 sees second sample, says "Ok need one more sample"
 does not respond after sampling multiple times

Propick in Node Search mode:
 responds correctly before and after attempted use of Density Search mode.

I have loaded and played several hours in 1.17.0p1 in two worlds with the same result, no changes back and forth with /gm.
Has worked in the past with previous versions.

**Comment by Craluminum2413** [comment]
Should now work in yesterday's [1.17.0-pre.2] release (https://info.vintagestory.at/v1dot17#:~:text=Fixed%3A%20Prospecting%20pick%20no%20longer%20working)
