### ISSUE TITLE
Candles appear to float when placed onto fence blocks

### ISSUE THREAD

**Issue by SmileOnSpeedDial** [anegostudios/VintageStory-Issues#199]
![2018-10-02_05-42-14](https://user-images.githubusercontent.com/27910432/46311732-7df34b00-c606-11e8-85f4-619c7efc0895.png)
![2018-10-02_05-46-05](https://user-images.githubusercontent.com/27910432/46311733-7df34b00-c606-11e8-8d6f-d96070efe796.png)

**Comment by Craluminum2413** [comment]
Is it intended? Or they should have recognize and place only one candle?

**Comment by Th3Dilli** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31390939/49cc4edb-7cdc-4e3f-9676-1aef2811c02d)
thank you for reporting

it will be fixed in an upcoming release version
