### ISSUE TITLE
Chairs are not grouped in handbook

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1991]
**Game Version:** 1.17.0-pre.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Open handbook page for any board
2. Chairs are not grouped

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/177015059-309e0a13-006c-4ca2-8f8a-86a1c373f2b9.png)

**Comment by tyronx** [comment]
thanks for the report, this should be addressed in pre.3
