### ISSUE TITLE
Crash on auto-save in 17.1

### ISSUE THREAD

**Issue by Corvus1313** [anegostudios/VintageStory-Issues#1992]
**Game Version:** 17.1 pre 
**Platform:** Linux   
**Modded:** No  
**SP/MP:** Multiplayer

### Description
Crashed out of the server when it attempted to autosave.  The log showed the following

### Logs

16:49:07 [Client Chat] Saving game world.... @ -1
weatherSim for region 997/998 is null. No idea what to do here
weatherSim for region 997/998 is null. No idea what to do here
weatherSim for region 997/999 is null. No idea what to do here
weatherSim for region 997/999 is null. No idea what to do here
weatherSim for region 997/998 is null. No idea what to do here
weatherSim for region 997/1000 is null. No idea what to do here
weatherSim for region 997/1000 is null. No idea what to do here
weatherSim for region 997/999 is null. No idea what to do here
weatherSim for region 997/1000 is null. No idea what to do here
weatherSim for region 997/999 is null. No idea what to do here
16:50:06 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 126, 511775
16:50:06 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 126, 511775
16:50:06 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 127, 511775
16:50:25 [Client Audit] Deyv opened inventory harvestableContents-17717
16:50:25 [Client Audit] Deyv opened inventory harvestableContents-17717
16:50:25 [Client Audit] Deyv opened inventory harvestableContents-17717
16:50:31 [Client Audit] Deyv closed inventory harvestableContents-17717
16:50:34 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 126, 511776
16:50:34 [Client Error] Coding error. Fruit tree without fruit tree type @511243, 126, 511775
16:50:34 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 126, 511774
16:50:34 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 127, 511775
16:50:34 [Client Error] Coding error. Fruit tree without fruit tree type @511244, 128, 511775
16:50:34 [Client Error] Coding error. Fruit tree without fruit tree type @511245, 126, 511775
16:51:20 [Client Audit] Deyv opened inventory harvestableContents-17718
16:51:20 [Client Audit] Deyv opened inventory harvestableContents-17718
16:51:22 [Client Audit] Deyv shift clicked slot 0 in harvestableContents-17718. Moved 1xRaw fish to (1x into hotbar-UY8jt5rbzXbQFBfbP5TTQ0bs)
16:51:22 [Client Audit] Deyv closed inventory harvestableContents-17718
16:51:38 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 116, 511273
16:51:38 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 116, 511273
16:51:38 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 117, 511273
16:52:12 [Client Error] Coding error. Fruit tree without fruit tree type @511214, 116, 511273
16:52:12 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 116, 511274
16:52:12 [Client Error] Coding error. Fruit tree without fruit tree type @511216, 116, 511273
16:52:12 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 116, 511272
16:52:12 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 117, 511273
16:52:12 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 118, 511273
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511214, 117, 511273
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 117, 511272
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 117, 511274
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511216, 117, 511273
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 118, 511273
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 119, 511273
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511216, 117, 511273
16:52:32 [Client Error] Coding error. Fruit tree without fruit tree type @511217, 117, 511273
16:52:53 [Client Error] Coding error. Fruit tree without fruit tree type @511216, 118, 511273
16:52:53 [Client Error] Coding error. Fruit tree without fruit tree type @511216, 117, 511272
16:53:02 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 118, 511272
16:53:02 [Client Error] Coding error. Fruit tree without fruit tree type @511214, 118, 511273
16:53:02 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 118, 511274
16:53:02 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 119, 511273
16:53:31 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 119, 511274
16:53:31 [Client Error] Coding error. Fruit tree without fruit tree type @511214, 119, 511273
16:53:31 [Client Error] Coding error. Fruit tree without fruit tree type @511215, 119, 511272
16:53:31 [Client Error] Coding error. Fruit tree without fruit tree type @511216, 119, 511273
./run.sh: line 3: 57231 Killed                  mono Vintagestory.exe
\

**Comment by copygirl** [comment]
Should be resolved in pre.2, see #1972.
