### ISSUE TITLE
Crazy tree generation in 17.1

### ISSUE THREAD

**Issue by Corvus1313** [anegostudios/VintageStory-Issues#1993]
**Game Version:** v1.17.0-pre.1
**Platform:** Linux
**Modded:** No
**SP/MP:** Multiplayr

### Description
Crazy tree generation in v1.17.0-pre.1

### How to reproduce
This was a single instance of this.  I saw no other trees exhibit this sort of leaf gen.

### Screenshots
See screenshot of tree
![Screenshot from 2022-07-02 16-32-14](https://user-images.githubusercontent.com/91815195/177019426-923b7101-de42-48f5-a80d-9d8d210883d9.png)
![Screenshot from 2022-07-02 16-33-04](https://user-images.githubusercontent.com/91815195/177019427-552365a3-f58f-455b-a0c9-474dc355cd5d.png)

**Comment by copygirl** [comment]
17.1 pre is not a real version.
At the moment there's 1.17.0-pre.1 and 1.17.0-pre.2.

**Comment by Corvus1313** [comment]
Sorry. Fixed.  v1.17.0-pre.1

**Comment by tyronx** [comment]
This should be fixed in pre.2. Please reopen if it still appears in pre.2
