### ISSUE TITLE
1.17.0-pre.2 ruins clutter not rendering model. Collision data remains.

### ISSUE THREAD

**Issue by Rosethorns** [anegostudios/VintageStory-Issues#1995]
**Game Version:** 1.17.0-pre.2  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Some ruins clutter appears to not render, collision remains intact. 

### How to reproduce
Looking in underground ruins should find some pretty quickly. 

### Screenshots
![clutter](https://user-images.githubusercontent.com/2171914/177236371-cef1895e-299b-470e-b4fd-7d76fc98d4a3.png)

**Comment by tyronx** [comment]
thanks for the report! this should be fixed in pre.3
