### ISSUE TITLE
WallHalves ground storage breaks when placed block in front of it

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1996]
**Game Version:** 1.17.0-pre.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place shovel/spear/hoe against wall
2. Place a block or start knapping/clayforming in front of ground storage
3. It breaks

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/177319848-7d358846-38ed-4376-ada9-e39a5bb3af8d.png)
![image](https://user-images.githubusercontent.com/69315569/177319858-a364b085-1fc8-4587-a020-4c63e57f5338.png)

**Comment by tyronx** [comment]
thanks for the report, this is fixed in pre.4

**Comment by Craluminum2413** [comment]
In 1.17.0-pre.4 it became even worse and it breaks when another ground storage is broken near it

**Comment by Craluminum2413** [comment]
Destroys every ground storage in a chain reaction

**Comment by tyronx** [comment]
thanks for the report, this should be properly fixed next release. You will need to break and place them again for the fix to apply
