### ISSUE TITLE
Funeral bell mushrooms don't hurt you

### ISSUE THREAD

**Issue by LukeUnbound** [anegostudios/VintageStory-Issues#2000]
**Game Version:** 1.17pre3 
**Platform:** Windows   
**Modded:** No
**SP/MP:** Singleplayer

### Description
Funeral bell mushrooms don't cause HP loss when eaten raw.

### How to reproduce
1. Grab a funeral bell mushroom from creative inventory.
2. Eat it.
3. You take no damage.

### Expected behavior
You should be dealt 40 points of damage.

### Note
`nutritionPropsByType` don't seem to be working for any of the variants in `mushroom-side`

**Comment by Saricane** [comment]
Funeral bell is edible. I guess you're talking about the death cap ? This is the only one with a 50 hp penalty.

**Comment by LukeUnbound** [comment]
Yes, the problem is that it is not supposed to be edible. Funeral bell is extremely poisonous IRL and the attributes for it in our game are supposed to cause 50 points of damage upon consumption (well, actually 40 to be exact, I'll correct that). It currently does this when eaten in a meal, but not when eaten raw. It's a bug related to nutrition properties for this particular blocktype.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
