### ISSUE TITLE
Game freezes on pressing "Singleplayer" button when launched server using VintagestoryServer.exe

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2003]
**Game Version:** 1.17.0-pre.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Create a server using `VintagestoryServer.exe`
2. Start the game using `Vintagestory.exe`
3. Press `Singleplayer` button
4. Game freezes

**Comment by tyronx** [comment]
thanks for the report, will be fixed in pre.4
