### ISSUE TITLE
Relieving stone blocks leave attached object floating.

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2004]
**Game Version:** 1.17.0-pre3
**Platform:** kubuntu 
**Modded:** no
**SP/MP:** Singleplayer survival

### Description
Objects attached to a stone block don't fall when this block is relieved.

### How to reproduce
1. Stick an object to a stone block (torch, vine ...)
2. Relieve this block using the pickaxe
3. When the block falls, the object stays in the air.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.4
