### ISSUE TITLE
Wrong onmoldrackTransform for shields

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2006]
**Game Version:** 1.17.0-pre.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a mold rack
2. Put any shield on it
3. It placed wrong

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/178155391-a17654db-091a-49d9-ae29-d4466817da7d.png)

**Comment by LukeUnbound** [comment]
Should be fixed now. Thanks.
