### ISSUE TITLE
poisonous pink bonnet stew

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2010]
**Game Version:** 1.17.0-pre3
**Platform:** kubuntu 
**Modded:** No
**SP/MP:** Singleplayer survival

### Description
A hearty pink bonnet stew inflicts 30 hp damage

### How to reproduce
1. Cook a hearty pink bonnet stew. Mine was cooked with soy beans garnish.
2. Eat a meal.
3. Meet the Reaper.

I ate a raw pink bonnet and nothing happened. Only when cooked.
In the handbook description for the pink bonnet, nothing about this mushroom toxicity. No visible history about this in the previous releases.
May be loosely linked with https://github.com/anegostudios/VintageStory-Issues/issues/2000#issue-1296168821, showing there are some tuning to be done on the mushrooms toxicity.

### Screenshots

![image](https://user-images.githubusercontent.com/84909583/178573551-03552967-a40f-43b3-a831-145f11bd8e15.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release. It is meant to be poisnous also raw
