### ISSUE TITLE
Cannot edit sometimes

### ISSUE THREAD

**Issue by Elxas866** [anegostudios/VintageStory-Issues#2011]
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer  

### Description
When I tried editing flint, I could only destroy it, instead of editing it. I placed it down on different blocks, sometimes it worked, sometimes not.
### How to reproduce
1. Find flint
2. place it down (shift + right click)
3. Try to make something (for example flint knife)

### Expected behavior
You should be able to edit, but the block breaks.

**Comment by Craluminum2413** [comment]
Do you use a second flint/stone to knap it?

**Comment by Elxas866** [comment]
> Do you use a second flint/stone to knap it? What stones you have used?

I'm actually not sure

**Comment by Craluminum2413** [comment]
Stones of some rock types cannot be used for knapping, it is written in their description

**Comment by Elxas866** [comment]
> 


> Stones of some rock types cannot be used for knapping, it is written in their description

Oh, okay. I think that was my problem. Thanks!
