### ISSUE TITLE
Repairing leather armor consumes all extra leather

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2015]
**Game Version:** 1.17.0-pre3
**Platform:** kubuntu
**Modded:** No
**SP/MP:** Singleplayer survival

### Description
When repairing a torn leather armor, extra material placed in the grid (like in the screenshot) is consumed in the process.
Some tests with other armor material should be done.

### Screenshots
![image](https://user-images.githubusercontent.com/84909583/179086702-f7a1a51e-ba40-4970-9471-597d7705a43a.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
