### ISSUE TITLE
Ability to place down more items

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#202]
Please consider ability to be able to place down on surfaces more items.
Now some items (blocks?) can be placed: tableware, pumpkins, buckets, furniture, ...
Why not allow to place cabbage to show off the harvest, tools on tables to take them easily or show off,
bread and other food on table (to quickly grab them when passing by), ... 
Maybe it will not influence the beginning of the game too much, because most of early game items wont be placeable ...
I guess I have this idea beacause of the new 1.7 3D items and dropping visuals. Now when an item can be thrown on the ground, I want it to be able to stay there.
Or use cabbage for decorations, its model is so cool and green! :D
Maybe the planned shelves will support it, idk.

**Comment by copygirl** [comment]
Besides plates, it could be neat to store a single type of food item in a pot too. Perhaps buckets, as well. (It's nice to have options.) Maybe allow storing more than one stack? Or maybe just 64, while reducing the stack size in inventory a bit. Barrels eventually could store an even larger amount, but could not be put in inventories when they contain items.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
