### ISSUE TITLE
Easy dupe

### ISSUE THREAD

**Issue by Limon052** [anegostudios/VintageStory-Issues#2022]
**Game Version:** 1.16.5  
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Singleplayer and Multiplayer   

### Description
Blocks and ingots dupe
### How to reproduce
1. Standing on hopper drop stackable items on hopper there is a chance to get an item with zero quantity (only works on blocks and ingots),(use keyboard to move baged item),(if item drop then he is will delete)
2. Place baged block on the ground ,done block duped 

### Screenshots
![1](https://user-images.githubusercontent.com/109580954/179695898-c927e6c9-cf21-49e1-85f5-5e04e644ed7b.PNG)
drop items
![2](https://user-images.githubusercontent.com/109580954/179696257-f19b3fde-7938-4d00-8c0a-c931f0c5a2fe.PNG)
use keyboard to move items
![3](https://user-images.githubusercontent.com/109580954/179696513-48139f00-073c-450e-b50d-fdb05cb2131a.PNG)
place items
![4](https://user-images.githubusercontent.com/109580954/179696776-e1aabf7e-444d-4cc0-a0a7-bea69fc1a0d8.PNG)
 pick up items
![5](https://user-images.githubusercontent.com/109580954/179697197-63a350e6-190d-4b83-94fa-d4163d226d2f.PNG)
 done!

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
Thanks for the report. While i could not reproduce it, i most likely fixed this for the next release.
