### ISSUE TITLE
extreme mouse input delay when using a numpad keybind for unlocking mouse cursor

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2024]
**Game Version:** 1.16.5
**Platform:** Windows   
**Modded:** No
**SP/MP:** Singleplayer (did not test in MP)

### Description
after rebinding "lock/unlock mouse cursor" to numpad3, whenever i hold numpad 3 & shift (in attempt to quick move the items between inventories with "shift clicking"), i am unable to quick move the items at all, instead they are only grabbed (as if i only just clicked on them), additionally, i begin to get extreme mouse delay that gets worse the longer i hold numpad 3 & shift.

additional notes: the game's fps remains completely unaffected. usually the mouse cursor gets stuck in an "unlocked" state when doing this (as if it worked as a toggle instead of hold to activate). shift clicking works as it should while the cursor is in this bugged "toggled" state. the reason for using such a weird keybind combination is because i'm using a razer naga pro mouse with it's 12 configurable mouse keys (with one of the buttons being configured to use numpad 3).

### How to reproduce
1. enable immersive mouse mode
2. rebind lock/unlock mouse cursor to "keypad3" (numpad 3)
3. attempt to move any item between inventories with holding numpad 3, holding shift, and left clicking the item.
4. fail
5. if you keep holding down numpad 3 + shift, start experiencing mouse delay while the mouse is unlocked.

### Screenshots
https://youtu.be/P04v0384nYQ

### Logs
nothing indicating an issue in the logs. (i cleared the log files, reproduced the issue and fresh logs were just generic loading map/assets/etc.)

**Comment by wasakoki** [comment]
i had someone tell me this was a windows issue with shift being hardcoded to act as turning off numlock, meaning numpad3 was getting intepreted as "page down" while holding shift.
so i rebinded cursor lock as pagedown and it's working as i expect it to now, however there is still minorly annoying amounts of mouse delay still happening with using pagedown + shift

**Comment by tyronx** [comment]
hm i have never seen something like this before, which makes me believe this is a operating system issue, rather than an issue with the game

**Comment by wasakoki** [comment]
i wasn't too sure at first since it seemed like this was the only game that gave input lag but i did more testing and i do see some minor fps drops in other games when using this key combination. so yeah you're probably right, it's seems like a combination of razer hardware/software combined with the weird interaction shift has with the numkeys since none of mouse delay even happens if i input the keys on the keyboard directly. all this can be mitigated by configuring my mouse to use something not on the numpad so yeah i'm gonna just close this.
