### ISSUE TITLE
Metal shields are not translated

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2026]
**Game Version:** 1.17.0-pre.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/179965374-46b30dca-88d2-4995-8f57-6e3f63ca8a65.png)

**Comment by Craluminum2413** [comment]
Just found such string in the code
```cs
return Lang.Get("shield-withmaterial", Lang.Get("material -" + metal));
```

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
