### ISSUE TITLE
Able to place water lilies underwater

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2028]
**Game Version:** 1.17.0-pre.5 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Get a water lily
2. Dive into water, for example 5 blocks deep
3. Try to place water lily inside water
4. It is placed

### Expected behavior
It cannot be placed underwater

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
