### ISSUE TITLE
On rare occassions, chunks are invisible

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#203]
![2018-10-03_15-40-16](https://user-images.githubusercontent.com/762006/46444010-b155e700-c778-11e8-8486-0329a9575c86.png)

The chunks seem loaded server side, but never arrived at the client, according to the debug commands.

**Comment by Heptagon-ru** [comment]
Oh yeah, saw this twice, so quite rare. I had an impression that quick relog doesnt always help, had to close VS.

**Comment by Th3Dilli** [comment]
got probably fixed along the way since I have not seen that or heard of any reports
