### ISSUE TITLE
Mantle missing texture

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2031]
**Game Version:** 1.17.0-pre.5 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/180227585-aa8db45b-adba-4ec5-9d7a-ae0158fb498e.png)

**Comment by tyronx** [comment]
thanks for the report, this is fixed for next release
