### ISSUE TITLE
ModMaker never puts game domain to patches

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2034]
**Game Version:** 1.17.0-pre.5
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Edit anything
2. Run ModMaker.exe
3. Complete actions
4. It created patches that don't have game prefix in `file` field

**Comment by tyronx** [comment]
Is it supposed to have them? Sounds to me like that's not an issue

**Comment by Craluminum2413** [comment]
It creates patches under mod domain e.g. `assets/rgbears/patches/make-redbear-stronger.json` and those patches don't patch because if `file` has no domain prefix, then it tries to patch location under the same domain as patches in

**Comment by tyronx** [comment]
oh, right

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
