### ISSUE TITLE
Create a world

### ISSUE THREAD

**Issue by AIADHD** [anegostudios/VintageStory-Issues#2036]
**Game Version:** v1.16.5  
**Platform:** Windows  
**Modded:** yes just those came with 
**SP/MP:** SP

### Description
create new world then crash

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
2022-07-22 18:54:40: Critical error occurred
System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid Vintagestory.GameContent.BlockTroughBase.init()
   vid Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep5(Action onCompleted)
   vid Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   vid _vuG4DGUoqAIliPHbC5Jd2S4bgWAA._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   vid _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   vid _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   vid Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   vid System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   vid OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) i C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:rad 476
   vid OpenTK.GameWindow.DispatchRenderFrame() i C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:rad 452
   vid OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) i C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:rad 375
   vid _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   vid _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

**Comment by Craluminum2413** [comment]
Do you have anything in any of these folders?
Roaming/Vintagestory/Mods
Roaming/VintagestoryData/Mods

**Comment by AIADHD** [comment]
Roaming/Vintagestory/Mods
Yes those i got when i download the game
Roaming/VintagestoryData/Mods
No

**Comment by Craluminum2413** [comment]
Can you try to reinstall the game?

**Comment by AIADHD** [comment]
I try now

**Comment by AIADHD** [comment]
is working thanks
