### ISSUE TITLE
"View Distance" slider has no effect until it is moved

### ISSUE THREAD

**Issue by syntaxaire** [anegostudios/VintageStory-Issues#2042]
**Game Version:** 1.17.0-pre.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
The "View Distance" slider does not affect view distance in game unless it is moved. When it is moved it starts to take effect at its current setting.

### How to reproduce
1. Start a new world. Press Escape and go into the Settings menu. Set view distance slider to 1024 or max.
2. Exit to main menu.
3. Go back into the same world.  Enter creative mode and fly up to visually check view distance. It will be something short, I didn't specifically measure.
4. Press Escape and go into Settings. Change the view distance slider to something smaller than whatever it is set to.
5. Press Escape again to go back to the game. Terrain will begin to generate+render out to whatever distance you just set the slider to.

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
