### ISSUE TITLE
Worldedit tools do not work with water

### ISSUE THREAD

**Issue by syntaxaire** [anegostudios/VintageStory-Issues#2048]
**Game Version:** 1.17.0 pre.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

I've tried to list here some ways that the worldedit tools don't interact as expected with water. This makes it difficult to make changes to landscapes.

### Flood fill does not overwrite water
Steps to reproduce:
1. Using the flood fill tool, fill a world-generated pond with rock
2. Break one of the rocks - water will be left behind (expected: air)

### Undo does not work when placing water

Steps to reproduce:
1. Place a "1000L" still water blocks in your Creative hotbar
2. Use the "Paint Brush" Worldedit tool in Fill mode
3. Place down any amount of water
4. Press the Undo button - nothing happens (expected: undo operation)

~~Note: A bigger problem is that there seems to be no way to remove water using worldedit tools. If you misclick while placing water, this bug is a potentially savegame-ruining event depending on the size of the fill.~~ Craluminum points out below that water can be deleted with the 'liquid selectable' checkbox in the floating settings dialog.

### Cannot undo flood fills if there was water in the replaced blocks
Steps to reproduce:
1. Using the flood fill tool, fill some air blocks with rock
2. Press the undo button - the rock is removed
3. Using the flood fill tool, fill some water blocks with rock
4. Press the undo button - the rock is not removed (expected: removed)

### Move tool does not move water
Steps to reproduce:
1. Use the Select tool and a magic wand to set a bounding cube around a pond in Survival
2. Select the Move tool
3. Click the "Down" button once
4. Any solid blocks will move down by one, but the water will not (expected: selected water would move down 1 block)

**Comment by Craluminum2413** [comment]
You can remove any liquid blocks if you toggle Liquid Selectable setting

**Comment by syntaxaire** [comment]
> You can remove any liquid blocks if you toggle Liquid Selectable setting

Thanks, I didn't know about that setting. I re-tested with this checkbox selected and though it doesn't resolve any of the issues I posted, I was at least able to delete water with a selection box.

**Comment by syntaxaire** [comment]
See #2063

**Comment by Craluminum2413** [comment]
I will close this in favor of issue #2063

**Comment by syntaxaire** [comment]
#2063 is a different bug that is tangentially related.

**Comment by Craluminum2413** [comment]
But you expect to replace everything with air?

**Comment by syntaxaire** [comment]
No, for example I reported an example where the "undo" action does not work after placing SOLID blocks. Should I open separate issues for each bug?

**Comment by Craluminum2413** [comment]
Yeah, it is always better to open separate issue for each bug
