### ISSUE TITLE
1.17 rc client crash on dedicated server during multible interactions

### ISSUE THREAD

**Issue by Gervasn** [anegostudios/VintageStory-Issues#2055]
Direct LAN crashes instantly, when on a dedicated server client crashes during different game world interactions e.g. taking clay out of a chest.

When Client runs on same machine as dedicated Server game works flawless. 
edit: Not Mod related, i ruled that out

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: blacksmithname@1.0.5, buzzwords@1.0.0, fancysky@1.0.3, fieldsofgold@1.3.0-dev.1, HangingOilLamps@1.0.1, moredrygrass@0.2.0, morefirewood@1.0.0, MoreStoneDrops@1.0.0, sortablestorage@1.4.0, game@1.17.0-rc.2, WorldOfDarkness@1.0.4, egocaribautomapmarkers@2.4.0-pre.1, carrycapacity@0.6.5, dsdebarkedlogs@1.0.5, playercorpse@1.3.3, prospectorinfo@3.1.2, ssppvv@1.0.3, creative@1.17.0-rc.2, survival@1.17.0-rc.2
27.07.2022 13:08:15: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.API.Client.HotkeyComponent.GenHotkeyTexture() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\HotkeyComponent.cs:Zeile 49.
   bei Vintagestory.API.Client.GuiElementRichtext.ComposeFor(ElementBounds bounds, Context ctx, ImageSurface surface) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:Zeile 418.
   bei Vintagestory.API.Client.GuiElementRichtext.Compose(Boolean genTextureLater) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:Zeile 118.
   bei Vintagestory.API.Client.GuiElementItemstackInfo.<>c__DisplayClass20_1.<AsyncRecompose>b__1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:Zeile 178.
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:Zeile 1138.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 123.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 664.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 608.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 125.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 87.
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 24.07.2022 09:57:07, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.0.0, Zeitstempel: 0x62d57a08
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1503, Zeitstempel: 0xb2acaea9
Ausnahmecode: 0xc000041d
Fehleroffset: 0x0000000000034f69
ID des fehlerhaften Prozesses: 0x44a8
Startzeit der fehlerhaften Anwendung: 0x01d89f2caa0a9542
Pfad der fehlerhaften Anwendung: C:\Users\ruthr\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 664347ab-0611-4a81-92aa-38cded7d46b5
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 24.07.2022 09:57:04, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.0.0, Zeitstempel: 0x62d57a08
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1503, Zeitstempel: 0xb2acaea9
Ausnahmecode: 0xc0020001
Fehleroffset: 0x0000000000034f69
ID des fehlerhaften Prozesses: 0x44a8
Startzeit der fehlerhaften Anwendung: 0x01d89f2caa0a9542
Pfad der fehlerhaften Anwendung: C:\Users\ruthr\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 8aa9ad13-7324-4a67-b837-0e6b4abe9b01
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 24.07.2022 09:57:04, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFDE9D84F69
Stapel:
   bei System.Environment._Exit(Int32)
   bei System.Environment._Exit(Int32)
   bei System.Environment.Exit(Int32)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   bei Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   bei Vintagestory.Client.ClientProgram.Main(System.String[])
 }

**Comment by Craluminum2413** [comment]
I see multiple mods here, are you sure that the chest you are using are not from sortablestorage mod?

**Comment by Gervasn** [comment]
> 

I made sure it was not mod related. It happens with a clean server as well, tried it on a clean server, but was too lazy to replicate it again. Crash also happened when interacting with the cooking pot ect.

contrary to the crash when directly opening to LAN, the client can log on the server but it crashes under different circumstances.

**Comment by REAL1IDDQD** [comment]
What language setting do you have in the game?

**Comment by Craluminum2413** [comment]
Seems that Gervasn use German

**Comment by Craluminum2413** [comment]
Currently this bug can be reproduced only by using German or Russian

**Comment by Schmarotzer** [comment]
I fixed it on Crowdin for these lines:
-> itemdesc-clay-*
-> itemdesc-flint
`<hk>shift</shift>` was translated, but it should not have been translated

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-rc.4](https://www.vintagestory.at/forums/topic/9287-de-jank-and-game-juice-update-1170-rc4/#comment-39088:~:text=Fixed%3A%20Game%20crashing%20on%20invalid%20hotkeys%20(e.g.%20when%20using%20russian%20translations))
