### ISSUE TITLE
Chiseling created an invisible block that crashes the client when touched on TOPTS

### ISSUE THREAD

**Issue by Zuckerfiedel** [anegostudios/VintageStory-Issues#2059]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: game@1.17.0-rc.2, creative@1.17.0-rc.2, survival@1.17.0-rc.2
28.07.2022 08:43:13: Critical error occurred
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 222.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 208.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 173.
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 401.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 822.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 600.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 89.
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 199.
   bei Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:Zeile 1176.
   bei Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:Zeile 1364.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 204.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 706.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 610.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 132.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 479.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 454.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 87.
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 06.07.2022 15:47:29, Site = , Source = Application Hang, Message = Das Programm Vintagestory.exe Version 1.17.0.0 hat die Interaktion mit Windows beendet und wurde geschlossen. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.

Prozess-ID: 80c

Startzeit: 01d8913eb032c401

Beendigungszeit: 4

Anwendungspfad: C:\Users\Zuckerfiedel\AppData\Roaming\Vintagestory\Vintagestory.exe

Bericht-ID: abbeb6ad-bc24-4e37-9f9d-f8a0f35d49c8

Vollständiger Name des fehlerhaften Pakets: 

Relative Anwendungs-ID des fehlerhaften Pakets: 

Absturztyp: Unknown
 }

**Comment by Craluminum2413** [comment]
Duplicate of #2040
