### ISSUE TITLE
rc2: block of planks appear at 0,0 on all newly generated worlds

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2061]
**Game Version:** 1.17.0-rc2
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer + Multiplayer   

### Description
when creating a world, a block of planks is generated on the surface at 0,0. 

### How to reproduce
1. make a new world on 1.17.0-rc2
2. travel/tp to coordinates 0,0
3. see block of planks

### Expected behavior
no plank

### Screenshots
n/a

### Logs
n/a

**Comment by Craluminum2413** [comment]
It looks like a [feature](https://www.vintagestory.at/forums/topic/9228-de-jank-and-game-juice-update-1170-rc2/#comment-38848:~:text=Tweak%3A%20Players%20should%20no%20longer%20spawn%20underwater%20in%20new%20worlds.%20Search%20range%20for%20solid%20land%20broadened%2C%20if%20it%20still%20fails%20to%20find%20land%2C%20it%20will%20spawn%20a%20block%20of%20planks%20for%20the%20player%20to%20rest%20on%20instead%2C%20i.e.%20a%20mini%2Draft)

**Comment by Saricane** [comment]
Tyron described this new feature, in case of spawning into water.

**Comment by wasakoki** [comment]
that feature indicates planks should only spawn on a player's spawn point, and only on water. this happens without fail regardless of conditions and is reproducible in every world i generated. (i.e. the block spawns on land, and if your world has a spawn radius of anything more than 0 blocks, the player won't spawn at 0,0 but the block of planks exist anyway).

**Comment by Saricane** [comment]
You're right. I made some test, and there is a plank at 0,0 even on land.

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-rc.3](https://www.vintagestory.at/forums/topic/9261-de-jank-and-game-juice-update-1170-rc3/#comment-38903:~:text=Fixed%3A%20Plank%20block%20spawning%20under%20players%20feet%20on%20first%20spawn%20when%20it%20shouldn%27t)
