### ISSUE TITLE
1.17.0 rc2: Water cannot be deleted in WorldEdit

### ISSUE THREAD

**Issue by Acsiel1** [anegostudios/VintageStory-Issues#2063]
**Game Version:** 1.17.0 rc2
**Platform:** Windows 10 
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Water cannot be deleted (nor replaced with another block); both with the Liquid Selectable option On and Off.

### How to reproduce
Try to use the Eraser tool on water (both still and flowing) in WorldEdit.

**Comment by syntaxaire** [comment]
See #2048

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-rc.3](https://www.vintagestory.at/forums/topic/9261-de-jank-and-game-juice-update-1170-rc3/#comment-38903:~:text=Fixed%3A%20Multiple%20issues%20with%20the%20worldedit%20eraser%20and%20paintbrush%20when%20placing/deleting%20water)
