### ISSUE TITLE
Water abnormal on old worlds updated to 1.17.0-rc.2

### ISSUE THREAD

**Issue by JRbBrown** [anegostudios/VintageStory-Issues#2068]
**Game Version:** 1.17.0-rc.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Water behaves abnormally on worlds created in prior versions after updating to 1.17.0-rc.2. In specific:
- Buckets and bowls cannot be filled with water from a source block; animation plays but bucket does not become full (other liquids behave normally)
- Cannot refill watering cans from a source block; animation plays but watering can does not become full 
- Cooper's reeds displace water blocks rather than being waterlogged (both pre-existing reeds, as well as newly-planted ones)
- Deleting a water block by placing and breaking a solid block leaves an air block. Water does not fill the block even if it is surrounded by source blocks on all 4 sides, and adjacent water blocks do not create a running-water block.

### How to reproduce
1. Install 1.17.0-rc.2
2. Open a world created in a prior version
3. Run block/item remapper (/fixmapping applyall)
4. Attempt to fill a bucket from a water block, etc.

```

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-rc.3](https://www.vintagestory.at/forums/topic/9261-de-jank-and-game-juice-update-1170-rc3/#comment-38903:~:text=Fixed%3A%20Water%20and%20reeds%20in%20worlds%20created%20prior%20to%20game%20version%201.17%20not%20updating%20correctly%20in%201.17.0%2Drc.2)
