### ISSUE TITLE
The game crashes and gives an error when entering the world

### ISSUE THREAD

**Issue by Golorn** [anegostudios/VintageStory-Issues#2070]
Game Version:  1.16.5 
Platform:Windows
Modded: No  
SP/MP: Singleplayer

### Description
The game crashes and gives an error when entering the world. This message is also shown:

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable) By Skif_97, final offline release... Good luck to you all...  
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
29.07.2022 22:29:30: Critical error occurred
System.Exception: EndOfStreamException thrown while reading entity, you might be able to recover your savegame through repair mode ---> System.IO.EndOfStreamException: Чтение после конца потока невозможно.
   в System.IO.__Error.EndOfFile()
   в System.IO.MemoryStream.InternalReadInt32()
   в Vintagestory.API.Common.EntityControls.FromBytes(BinaryReader reader, Boolean ignoreData)
   в Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   --- Конец трассировки внутреннего стека исключений ---
   в Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   в Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   в Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_c4zW6iXC6q7Xom9edSwgw3G8Alm entitypacket, ClientMain game, Boolean addToLoadQueue)
   в Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_m4CVIcO3UJPLI62MuOxE8163nQH serverpacket)
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   в _esGsESICkihAc8ShXuIoQwZFwP4._lPY9uZeagiMGC6tvSE11dF7naaz(Single )
   в _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   в _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 479
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 454
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   в _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------
System.IO.EndOfStreamException: Чтение после конца потока невозможно.
   в System.IO.__Error.EndOfFile()
   в System.IO.MemoryStream.InternalReadInt32()
   в Vintagestory.API.Common.EntityControls.FromBytes(BinaryReader reader, Boolean ignoreData)
   в Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
-------------------------------

1. Make a '....'
2. Use it on '....'
3. It crashes 
### Expected behavior
I want to play again in my world and fix this error

Pls help me to fix problem

**Comment by Golorn** [comment]
Here is screenshot:
![image](https://user-images.githubusercontent.com/103250426/181832048-29a61caf-d4b9-444f-a342-1fccb8785ec9.png)

**Comment by Craluminum2413** [comment]
Pirate versions are unsupported
