### ISSUE TITLE
waypoints : no more trader

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2071]
**Game Version:** 1.17.0-rc2
**Platform:** linux Mint
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Trader's icon dissapeared with the new waypoints model. Traders precedently marked on map are not marked anymore.

### Screenshots
![2022-07-29_22-22-01](https://user-images.githubusercontent.com/84909583/181838772-ced34b64-2134-4d27-8a82-1c6563fa5286.png)

**Comment by Craluminum2413** [comment]
Fixed in [1.17.0-rc.3](https://www.vintagestory.at/forums/topic/9261-de-jank-and-game-juice-update-1170-rc3/#comment-38903:~:text=Fixed%3A%20Worldmap%3A%20The%20trader%20icon%20disappeared)
