### ISSUE TITLE
World customization window

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2074]
**Game Version:** 1.17.0-rc.2  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
World customization window:
A simple left click on the tab should not speed move the content of the window to a new position. Only a click and drag should do it or a left click above or under the tab.

### Screenshots
![tab](https://user-images.githubusercontent.com/26251843/181905692-eccb93b3-9e5a-451e-a824-868d41ce5b38.png)

**Comment by tyronx** [comment]
not sure what you mean by that, you arrow points to a scrollbar, not a tab

**Comment by Xandoria** [comment]
Yes it's a scrollbar, my bad. Replace all "tab" in my previous post by "scrollbar" :p

**Comment by Craluminum2413** [comment]
1.20 uses tabs now
