### ISSUE TITLE
Wagon barrels not compatible with 1.16.5

### ISSUE THREAD

**Issue by MusicMakerOwO** [anegostudios/VintageStory-Issues#2079]
**Game Version:** 1.16.5  
**Singleplayer + Multiplayer**

### Description
Wagons spawn with invalid barrel data, game prompts you to break and replace them to use them in 1.16.5 but are protected by the Travelers

### Screenshots
![Screenshot from 2022-07-28 15-02-21](https://user-images.githubusercontent.com/86620902/182010908-ca63c372-ae0a-45ea-b144-0aa1e31565bf.png)

**Comment by Craluminum2413** [comment]
Does this happen in 1.17?
