### ISSUE TITLE
Add events for (player) entity left/right click or attack/interact

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#208]
It would be nice to have events which mods could listen to when a player, or possibly any entity (which might be useful in the future) would start an attack or begin interacting with a block or using an item. This could be used to enhance existing behaviors or outright cancel them.

This should be done in such a way, that if cancelled, a mod could chose whether to send an attack/interact event from the client to the server in the first place.

Specifically, I personally would use this event to completely cancel the default behavior for attacking and interacting with anything while a block is carried in the player's hands.

**Comment by copygirl** [comment]
Note: This is currently somewhat possible with raw events for mouse down/up but not ideal for client-side and not possible on server-side.

**Comment by tyronx** [comment]
You wouldn't it on the server side. If you handle the mouse down event, it won't get passed on to the block/item interaction/attack events, which then wouldn't get sent to the server.

**Comment by tyronx** [comment]
So maybe only thing thats missing is to see the value of `MouseGrabbed`?

**Comment by copygirl** [comment]
No. Mouse and Keyboard events are lower-level than what I'm asking for. I'm aware that those events wouldn't be sent to the server if everything went well, but if not, the server still needs some way to say "no, you aren't allowed to do that" and re-sync the client's state.

**Comment by copygirl** [comment]
Implemented in 1.9.3 and then fixed in 1.9.4?

**Comment by tyronx** [comment]
indeed, that should be the case
