### ISSUE TITLE
Old style "square" berry bushes in 1.17

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2081]
**Game Version:** 1.17.0-rc3
**Platform:** linux mint
**Modded:** No
**SP/MP:** Singleplayer on 1.17 world and rc3 generated chunks

### Description
Some berry bushes (not all) are old style "square" bushes. Not only they are square, their current state is not correctly rendered.
Some ripe bushes have no fruits visible, some flowering bushes are empty, and so on.
This is only a display bug. Fruits can be harvested if the tree state is ripe, even if nothing is visible.

### How to reproduce
1. In creative mode, just add empty or flowering bushes.

### Screenshots

![2022-07-31_14-27-39](https://user-images.githubusercontent.com/84909583/182028654-8b9f53ee-2716-4175-833f-c56179d8cedc.png)
![2022-07-31_14-26-07](https://user-images.githubusercontent.com/84909583/182028722-f67b0d4a-7e50-40c2-81df-f2b43ad962c6.png)
![2022-07-31_14-52-12](https://user-images.githubusercontent.com/84909583/182028785-0db9e311-06b5-4133-b152-b150148367c1.png)

**Comment by tyronx** [comment]
hm. when i generated a new world all berry bushes are fluffy for me. any chance you used shears on them?

**Comment by Saricane** [comment]
Ha ha, nice try, Tyron, but no :smiley: 
However \:
- as I'm the only one to report this behavior,
- as you cannot reproduce it
- as I don't see it no more on a complete fresh reinstall of the game,

I just can deduce this is an odd but temporary behavior, and as such, I close the subject.

**Comment by Craluminum2413** [comment]
I will mark it as resolved
