### ISSUE TITLE
Tree Leaves Appearing as White Blocks in World Map

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#2082]
**Game Version:** 1.17.0-rc. 3  
**Platform:** Windows
**Modded:**  Yes (AutoMapMarkers, Buzzwords, ProspectorInfo, VisibleOre)
**SP/MP:** Singleplayer 

### Description
Tree leaves have been appearing as white blocks on the world map in patches based on chunk, where in other regions they are completely fine. This persists through world loads. 

### How to reproduce
1. Make a new world. 
2. Trees will appear with incorrect map texture on worldgen. 
3. 
### Expected behavior
Tree leaves should all be green. 

### Screenshots
Image A. Shows issues with tree leaves, they are limited to specific chunks and trees which cut across chunks have partly affected leaves. 
![image](https://user-images.githubusercontent.com/40339761/182046346-c53a1ed9-91e9-4867-9ba6-b75de04f6f12.png)

**Comment by tyronx** [comment]
hm. I was able to reproduce this once, and then not anymore.

**Comment by tyronx** [comment]
thanks for the report, this is fixed for next release
