### ISSUE TITLE
Barrels teleporting and duping items

### ISSUE THREAD

**Issue by jtmorphew** [anegostudios/VintageStory-Issues#2088]
**Game Version:** 17.0 rc3
**Platform:** Windows  
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Using barrels teleports items into the slot.  Items can teleport from other storage places like chests or even from the player inventory when clicking an item.  They can also teleport off tool racks.  I had a black bronze hammer teleport off a tool rack and into a chest and then duplicate.  The location doesn't seem to be a factor as I have had items disappear from my inventory when across the map and also teleport from nearby chests.  It's possible that shift-clicking has some sort of cause for this but I'm not certain.

### How to reproduce
1. Make a barrel and put liquid in it (water, limewater, tannin).
2. When interacting with other items and storage units like chests, sometimes items randomly teleport into the barrels and can even duplicate.

**Comment by Void-Seeker** [comment]
17 rc4 here, I have this problem on my save all the time, game became almost unplayable. Looks like when this happens, this messages appears in server-main.txt, and item that player last stored in an inventory teleports into the last barrel that player interacted with.
```
8.8.2022 22:43:08 [Notification] A client reconnected, resuming game calendar.
8.8.2022 22:46:08 [Notification] Server ticking has been suspended
8.8.2022 22:46:08 [Notification] A client reconnected, resuming game calendar.
8.8.2022 22:46:08 [Notification] Server ticking has been resumed
8.8.2022 22:46:08 [Notification] Server ticking has been suspended
```

Sometimes this also leaves ghost item in player inventory, that can generate log messages like this:
```
8.8.2022 22:50:52 [Notification] Client Voidseeker tried to place a block but rejected because the client hand is empty
```

**Comment by doornydew** [comment]
been happening to me and my friend too, though we arent sure what pre. caused it, but for now, just absolutely never use shift to transfer stuff, until its fixed atleast

**Comment by doornydew** [comment]
also
 #2045
