### ISSUE TITLE
1.17-rc3 it's not possible to pick up a cooked pie with your hands

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2090]
**Game Version:** 1.17-rc3
**Platform:** Windows 
**Modded:** No
**SP/MP:** both

### Description
when placing a pie in-world, there is a prompt indicating you can pick the whole item back up with a right click but nothing happens when right clicking the item.

### How to reproduce
1. Make a cooked pie 
2. place it in the world (either full pie, 3/4, 2/4, or 1/4 slices, affects all)
3. it's impossible to pick up with your bare hands, contrary to the tooltip prompts. it's only possible by a painfully slow left click breaking or by right click slicing with a cutting tool (even 1/4 slices can be placed and "sliced" again which causes #1916 )

### Screenshots
(just imagine me spamming right click here)
![image](https://user-images.githubusercontent.com/65874132/183227041-5766321a-f0cc-4830-8e96-973b8d1f7537.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
