### ISSUE TITLE
1.17.3 rc3 Armor StatModifiers are not disabled when armor is broken

### ISSUE THREAD

**Issue by TheHaterofGravel** [anegostudios/VintageStory-Issues#2092]
Game Version: 1.17.3 rc3
Platform: Windows 10
Modded: No
SP/MP: Singleplayer

Description
When armor is brought to 0 durability the StatModifiers portion of ItemWearable.cs is not disabled, even if the stat modifiers are modified to positive. Current implementation is limiting for content mods that add armor with positive effects and want to disable them when armor is broken.

How to reproduce
1. Break armor
2. Positive or negative armor stats/penalties are not disabled and still apply

Expected behavior
Either both ProtectionModifiers and StatModifiers should be disabled when armor is broken, or only positive stats should be disabled; For instance a broken set of armor should either no longer have a negative speed penalty, or in the case of a modded/modified armor set- a speed bonus granted by armor should be disabled once the armor breaks, but instead the speed bonus keeps working.

**Comment by tyronx** [comment]
alright. healingeffectivness, hungerrate, walkSpeed, rangedWeaponsAcc and rangedWeaponsSpeed should no longer contribute positively on broken armor next release.
