### ISSUE TITLE
1.17.0 rc4: Low Temperature on Tall Worlds

### ISSUE THREAD

**Issue by Acsiel1** [anegostudios/VintageStory-Issues#2097]
**Game Version:** 1.17.0 rc4
**Platform:** Windows 10 
**Modded:** No
**SP/MP:** Singleplayer

### Description
When World height is set to max, the surface is alway very cold.

### How to reproduce
Create a new standard World (not superflat) and set the world height to max (1534). Even on a low altitude plain (for example around 700  blocks high) the temperature will be at less than -40 degrees Celsius.
EDIT: I forgot to mention that changing the global temperature in World creation menu does not change anything.

### Expected behavior
The temperature beinng spread proportionately to World height like in the pre-1.17.0 versions of the game.

**Comment by Acsiel1** [comment]
Fixed, thank you!

**Comment by Craluminum2413** [comment]
[1.17.0-rc.8](https://www.vintagestory.at/forums/topic/9383-de-jank-and-game-juice-update-1170-rc8/#comment-39952:~:text=Fixed%3A%20Incorrect%20temperatures%20in%20nonstandard%20world%20height%20worlds%20(due%20to%20incorrect%20sealevel%20value))
