### ISSUE TITLE
1.17.0-rc4: 3 issues relating to the bamboo hat crafting recipes (knife is consumed on craft, empty durability bar, large hat uncraftable)

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2099]
**Game Version:** 1.17.0-rc4 
**Platform:** Windows
**Modded:** No 
**SP/MP:** both

### Description
1. in rc4 the crafting recipe for bamboo hats were changed to include a knife (to fix conflicting recipe with roof ridge according to patch notes), but now crafting a bamboo hat consumes the knife as an ingredient.
2. if the knife has been used/does not have max durability, the resulting bamboo hat will have an empty durability bar when crafted.
3. the large bamboo hat is not craftable, the recipe result displays and creates a small (or is it regular sized?) bamboo hat instead

### How to reproduce
1. craft bamboo hat
2. knife disappears
2.5. if the knife does not have full durability, the resulting hat will be crafted with an empty durability bar.

### Expected behavior
i'd expect it to consume some durability from the knife instead, other issues are self explanatory 

### Screenshots
![image](https://user-images.githubusercontent.com/65874132/183632537-b8e87470-b08d-41d7-ac40-7cc530552ec7.png)
3rd issue shown above
![image](https://user-images.githubusercontent.com/65874132/183629443-4731237e-8bf2-433e-bd6a-d3528f952a70.png)
2nd issue shown above: right side is the hat crafted with a used knife. left side is what i expect it to look like (no durability bar)
### Logs
couldn't find any relevant error in the logs

**Comment by tyronx** [comment]
thanks for the reports, will be fixed next release
