### ISSUE TITLE
1.5.2.1 ghost berry in hot bar

### ISSUE THREAD

**Issue by RainnMannx** [anegostudios/VintageStory-Issues#21]
when you pick berries, if you have some in backpacks, they look like they are on your hot bar, but they are not really there, they go into the backpack.
https://youtu.be/A4tNuBMwT8w
You can also move them around, and seem to not correct until you try to combine them.

**Comment by Heptagon-ru** [comment]
Also observed this bug.

**Comment by Heptagon-ru** [comment]
I don'e observe the bug in 1.5.2.2 any more.

**Comment by tyronx** [comment]
oki
