### ISSUE TITLE
Random crash after Press `esc` key

### ISSUE THREAD

**Issue by ciotto** [anegostudios/VintageStory-Issues#210]
On Mac OS version (**1.7.3**), after pressing `esc` key, the application randomly crash and system go back to Mac OS login window, probably crash the WindowServer

**Comment by copygirl** [comment]
That's, like, a super crash. I hope there's ways to extract more information about the nature of this issue.

**Comment by ciotto** [comment]
Not problem, I have tried to find application log but it does not seem to be in the standard path (`~/Library/Application Support/APPNAME`) but I have found the **WindowServer** crash log.

[WindowServer_2018-10-11-184357_MBP-18.log](https://github.com/anegostudios/VintageStory-Issues/files/2472141/WindowServer_2018-10-11-184357_MBP-18.log)

Tell me if I can help better.

**Comment by tyronx** [comment]
This needs reporting to the opentk people and the mac os people. I did the former now.

**Comment by ciotto** [comment]
I have some other problem that apparently can be related, I have try to play on other Mac (**MacBook Pro (Retina, Mid 2012)**) in order to check if the error are related to the machine but during the game, I can't move the view with the mouse.

**Comment by tyronx** [comment]
might be fixed for v.18

**Comment by copygirl** [comment]
Assuming fixed due to lack of response. Please reopen if still an issue.
