### ISSUE TITLE
Storable in/on not translated

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2103]
**Game Version:** 1.17.0-rc.3  
**Platform:** Linux (KDE neon 20.04 5.25)   
**Modded:** No  
**SP/MP:** Singleplayer / Multiplayer

### Description
"Storable in/on" in the handbook is not translated.
Text is not in crowdin.

### How to reproduce
1. Set non English language, e.g. Slovak
2.  See something e.g. Hematit in the Handbook
3. Text is not translated

### Expected behavior
Text should be added to crodwin and used in the game.

### Screenshots
![2022-08-09_22-20-20](https://user-images.githubusercontent.com/47914240/183754088-543fcede-5619-424b-98bb-80abedafd413.png)

**Comment by tyronx** [comment]
should be in crowdin now 👍
