### ISSUE TITLE
1.17.0-rc.5: firepit GUI does not update on the client

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2106]
**Game Version:** 1.17.0-rc.5
**Platform:** Windows
**Modded:** No 
**SP/MP:** both 

### Description
firepit gui does not update on client when placing or removing items from it's inventory. 

### How to reproduce
1. make a firepit
2. place a cooking pot, crucible, or a burnable item like raw redmeat in it's inventory
3. observe weird behavior (no crucible/cooking pot slots, raw redmeat doesnt say "will create x cooked redmeat", etc.)
4. (optional) closing the GUI and reopening it will "update" the UI, but is still bugged with the temperature and progress meter not visually updating at all.

### Screenshots
picture of what i see when at step 3 in the "how to reproduce" steps (missing the 4 cooking slots)
![image](https://user-images.githubusercontent.com/65874132/183784903-e3095aa6-da11-4920-9627-a1401c7b018c.png)

### Logs
none

**Comment by mrgeoffkat** [comment]
Can confirm the unresponsive cook fires with RC5.  The cook pot does not "refresh" the GUI to include the added 4 block inventory.  Closing out and reopening sometimes resolves.

**Comment by wasakoki** [comment]
most likely the same issue as #2114 which is noted as fixed so i'll close this.
