### ISSUE TITLE
Cannot repair Broken Translocator - Testing stuff on 1.17 before stable release.

### ISSUE THREAD

**Issue by Pallafurious** [anegostudios/VintageStory-Issues#2107]
Game Version:      1.17
Platform:              Windows
Modded:              No
SP/MP:                 Singleplayer

### Description
Cannot place, metal parts or temporal gears to repair a translocator.

### How to reproduce
1. -
2. Using temporal gear on translocator
3. doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?
The usual, where it appears to be repaired and then requires metal parts.
### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by mrgeoffkat** [comment]
I just repaired a transponder to full function in 1.17rc5.  MP server, no major mods.

**Comment by Pallafurious** [comment]
> 
Hmm, I'm not sure if it was just that one, but everything else I could interact with, hopefully it was just a one of glitch and nothing major before stable release.

**Comment by tyronx** [comment]
You need to first place 2 metal parts before you can put temporal gears, did you do that?

**Comment by Pallafurious** [comment]
> You need to first place 2 metal parts before you can put temporal gears, did you do that?

Yeah, I had both items needed, temporal gears and metal parts, I will try again when I find another translocator and see if it works, mind you the one I found was called “static translocator” is this a different one that cannot be repaired?

**Comment by tyronx** [comment]
hm no, all of them should be repairable. Strange.

**Comment by Pallafurious** [comment]
Issue can be closed, everything works fine, I found out it was because I didn't have 2 Metal Parts. Even though you can place one Temporal gear at a time, it would only accept 2 Metal parts if I had them stacked as 2. Went into creative and issue was resolved.

**Comment by Craluminum2413** [comment]
Also tooltip should always show that btw
