### ISSUE TITLE
Windmill Rotor is Uncraftable

### ISSUE THREAD

**Issue by jtmorphew** [anegostudios/VintageStory-Issues#2110]
**Game Version:** 1.17.rc5
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Singleplayer

### Description
The windmill rotor cannot be crafted.  I put all the ingredients into the gui but the output slot doesn't update with the rotor.  Clicking on the empty output slot doesn't give the item.  Other items are still craftable and the rotor is the only thing I've encountered so far that doesn't work.  Possibly related to the broken gui with firepits?

### How to reproduce
Try to make a windmill rotor.

### Screenshots

![bug](https://user-images.githubusercontent.com/110646445/183911439-8401283f-097d-4c09-8d8f-668a6b1852a1.png)

### Logs

**Comment by Craluminum2413** [comment]
Does your hammer have enough durability to craft this?

**Comment by jtmorphew** [comment]
It had something like 43 durability.  I guess I assumed that was enough.

**Comment by jtmorphew** [comment]
I just checked again with a new hammer and everything works fine. You were right on the durability... sorry for the false alarm.

**Comment by Craluminum2413** [comment]
The crafting recipe requires 80 durability for hammer
