### ISSUE TITLE
Visual Glitch with crucible in fire pit

### ISSUE THREAD

**Issue by mellexpro** [anegostudios/VintageStory-Issues#2114]
**Game Version:** 1.17.rc5 
**Platform:** Windows11
**Modded:** No
**SP/MP:** Multiplayer (Self Hosted) 

### Description
When adding ore bits into the crucible, the amount of unit of a particular metal is not shown on the firepit dialog, this happens with all metals that could be smelted.

### How to reproduce
1. Open crucible
2. Add ore bits
3. Doesn't show the unit count

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
![2022-08-11_21-42-00](https://user-images.githubusercontent.com/17949569/184227323-15fd9f9e-efc6-4d9d-ad53-3fccebdee60d.png)

### Logs
```
None
```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
