### ISSUE TITLE
1.17.0-rc.5: Disabling Snow Accumulation causes save errors

### ISSUE THREAD

**Issue by JyeGuru** [anegostudios/VintageStory-Issues#2119]
**Game Version:** 1.17.0-rc.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer (Server)

### Description
Disabling snow accumulation causes server to fail to save, due to being unable to pause. Toggling this value causes reproducible behavior between working correctly and the error below.

### How to reproduce
1. Fresh install of 1.17.0-rc.5
2. Run VintageStoryServer.exe once to generate settings file
3. Delete the default save
4. Change WorldConfiguration in serverconfig.json to below values
5. Run VintageStoryServer.exe - note that it generates the world fine
6. Attempt to `/autosavenow` from the console, or wait until the autosave triggers
7. Kill server and delete world
8. Toggle `snowAccum` and observe behavior changes

### Expected behavior
Autosave works correctly

### Screenshots
![image](https://user-images.githubusercontent.com/5215014/184520250-ffccca44-ab13-41bf-964a-5354a4f2cd66.png)

### Full configuration used in testing:
```
    "WorldConfiguration": {
      "worldClimate": "realistic",
      "gameMode": "survival",
      "temporalStability": true,
      "temporalStorms": "rare",
      "graceTimer": "0",
      "microblockChiseling": "all",
      "polarEquatorDistance": "25000",
      "harshWinters": "true",
      "daysPerMonth": "30",
      "saplingGrowthRate": "1",
      "allowUndergroundFarming": false,
      "temporalGearRespawnUses": "-1",
      "temporalStormSleeping": "1",
      "startingClimate": "temperate",
      "spawnRadius": "0",
      "deathPunishment": "drop",
      "seasons": "enabled",
      "playerlives": "-1",
      "blockGravity": "sandgravel",
      "bodyTemperatureResistance": "0",
      "creatureHostility": "aggressive",
      "creatureStrength": "1",
      "playerHealthPoints": "15",
      "playerHungerSpeed": "0.5",
      "playerMoveSpeed": "1.5",
      "foodSpoilSpeed": "0.5",
      "toolDurability": "1",
      "toolMiningSpeed": "1",
      "propickNodeSearchRadius": "6",
      "globalDepositSpawnRate": "1",
      "allowCoordinateHud": true,
      "allowMap": true,
      "tempstormDurationMul": "1",
      "temporalRifts": "visible",
      "worldWidth": "1024000",
      "worldLength": "1024000",
      "worldEdge": "traversable",
      "globalTemperature": "1",
      "globalPrecipitation": "1",
      "globalForestation": "0",
      "surfaceCopperDeposits": "0.12",
      "surfaceTinDeposits": "0.007",
      "snowAccum": false,
      "allowLandClaiming": false,
      "classExclusiveRecipes": true,
      "auctionHouse": false
    },
```

**Comment by tyronx** [comment]
thanks for the report, should be fixed in rc8
