### ISSUE TITLE
Growth speed do not correl to Nutrient Levels

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2120]
**Game Version:** 1.17.0-rc.5
**Platform:** Linux (KDE neon 20.04 5.25)   
**Modded:** No  
**SP/MP:** Multiplayer, TOPTS

### Description
It looks like the growth speed is not correct according to nutrient level. E.g. for 37,5 K is growth speed 98%

### How to reproduce
1. Tested on TOPTS
2. I took my crops and everything was still green.

### Expected behavior
Earlier the growth. speed was always red/orange according to latest crops

### Screenshots
![2022-08-14_14-50-23](https://user-images.githubusercontent.com/47914240/184539914-74c77862-7235-4b3d-9e96-6a432c947578.png)

**Comment by Barhandar** [comment]
Moisture above 50% gives growth speed bonus.

**Comment by daretmavi** [comment]
I just tried it in 1.16.5 in creative and it seems to be similar. Maybe I never noticed, that I need only 35+% nutrient level to get almost 100% growth speed. I'll close it for now.
