### ISSUE TITLE
debug command /lntest has incorrect permissions and can be used by the default "suplayer" role in servers

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#2122]
**Game Version:** 1.17.0-rc.5
**Platform:** Linux server
**Modded:** No
**SP/MP:** Multiplayer  

### Description
while typing /help and looking at commands, i noticed a new command "/lntest" available which i naively typed. this casted lightning at my cursors location, immediately killing me.

found this out on my server initially, but joined TOPTS to see if it is possible there and it is indeed possible.

### How to reproduce
1. create a dedicated server
2. join/set your role as the default "suplayer" role (permission codes are controlplayergroups, manageplayergrousp, chat, build, useblock, attackcreatures, attackplayers)
3. type /lntest
4. realize you are now god

### Expected behavior
this command should not be available to the default player role

**Comment by tyronx** [comment]
oh wow, nice find :D
thanks for the report, will be fixed next release
