### ISSUE TITLE
Armor repairing - gambeson

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2123]
**Game Version:** 1.17.0-rc.5
**Platform:** Linux (KDE neon 20.04 5.25)   
**Modded:** No  
**SP/MP:** Multiplayer (TOPTS)

### Description
Repairing of gambeson body armor and leggins do not work, or is incorrect described in Survival Handbook.
Repairing of head armor worked.

### How to reproduce
1. Take damaged gambeson body armor, or leggins
2. Try to use the recipe from a Handbook
3. Nothing is in output

### Expected behavior
Repaired armor should be in output slot.

### Screenshots
![2022-08-18_18-17-38](https://user-images.githubusercontent.com/47914240/185449530-7043083b-0962-4f50-856e-ed745a9ecf6f.png)

![2022-08-18_18-18-09](https://user-images.githubusercontent.com/47914240/185449548-d8e25d6e-e3c1-49c7-b9c1-a75a5ff3f878.png)

**Comment by tyronx** [comment]
thanks for the report, should be fixed next release
