### ISSUE TITLE
Hefy cassava stew has wrong name, is invisible, and provides no nutrition

### ISSUE THREAD

**Issue by JRbBrown** [anegostudios/VintageStory-Issues#2126]
**Game Version:** 1.17.0-rc5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Hefty cassava stew has the incorrect name when viewed in a bowl or crock (see screenshots), is invisible when placed in a bowl, and provides no nutrition when eaten.

### How to reproduce
1. Make a vegetable stew with soaked, peeled cassava in all 4 slots
2. Put it in a crock and observe name
3. Take a serving with a bowl and observe name and appearance
4. Eat it and observe (lack of) nutrition change

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![cassava_stew_in_bowl](https://user-images.githubusercontent.com/110252969/185803430-aa3baa5c-b423-47c9-a6a1-260152d66cb3.png)
![cassava_stew_in_crock](https://user-images.githubusercontent.com/110252969/185803438-5c819580-e220-4594-8f51-3296c6546a2d.png)

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by tyronx** [comment]
strange, i'm not able to reproduce this in rc7

**Comment by cyberjasse** [comment]
I have the same bug in 1.18.10 . My way to reproduce it is a bit different. I will make a new ticket for it
