### ISSUE TITLE
Vintage Story Error Connecting to Host

### ISSUE THREAD

**Issue by zshombie** [anegostudios/VintageStory-Issues#213]
My brother an I are trying to play on his server that he set up.  He has all of the supposed information, but I keep getting timed out.

I've attached an image of the error to help.

![image](https://user-images.githubusercontent.com/44128420/46912089-7d25b780-cf2a-11e8-91da-f1edd489938f.png)

**Comment by copygirl** [comment]
Going to mark this as a question for now because it's more likely a setup issue.

Are you both on the same network or trying to connect over the internet? If the latter, you are trying to connect to a local IP address on your network.

**Comment by tyronx** [comment]
Yea and it would suffice to just use one support channel. I replied to your support request as well.

**Comment by zshombie** [comment]
We are both trying to connect over the internet.  We tried using his server IP to connect through and it didn't work.

**Comment by tyronx** [comment]
When you do over internet you need [port forwarding](https://www.google.com/search?q=port+forwarding)

**Comment by tyronx** [comment]
Closing for now, as it is probably not an issue related to the game. Reopen if needed.
