### ISSUE TITLE
Cannot Interact With Trader In 32x32 World

### ISSUE THREAD

**Issue by darkpoetcc** [anegostudios/VintageStory-Issues#2132]
**Game Version:** 1.17.0-rc7
**Platform:** Windows / Mac / Linux Windows 11, build 22000.739
**Modded:** Yes and No (occurs on both, mod is only for wolf behavior)
**SP/MP:** Singleplayer 

### Description
I created a new 32x32 world.  There is a trader at spawn, which I sometimes cannot interact with.  It behaves like they are not there, and my cursor always points "through" to whatever is behind the trader.
I created 3 new worlds with the same seed, and 2/3 had a Trader that I couldn't interact with

### How to reproduce
1. Make a 32x32 world with Seed 1756145007
2. Log in
3. Try to interact with the trader
4. Sometimes, the trader is "invisible" to the user, and cannot be interacted with
NOTE:  You may need to recreate the world a few times to notice the issue

### Expected behavior
The trader should be interactable

### Screenshots
Included
![2022-08-25_16-20-44](https://user-images.githubusercontent.com/6785272/186762208-3f684696-68f1-4126-9bbc-2e105770d19f.png)
![2022-08-25_16-20-46](https://user-images.githubusercontent.com/6785272/186762228-9166e1f3-3ffe-4ea5-9434-7c6b72b2c1c3.png)
![2022-08-25_16-20-50](https://user-images.githubusercontent.com/6785272/186762241-4676db6d-d582-4a59-b8fe-288904c40005.png)

### Logs
```
No meaningful exceptions found in log; please let me know whatever logs you may need
```

**Comment by tyronx** [comment]
hm. I created this world 4 times now and I was able to interact with the trader in all of them

**Comment by darkpoetcc** [comment]
> hm. I created this world 4 times now and I was able to interact with the trader in all of them

Very odd...I'll get you some video of this tomorrow; it's about 3 AM, and I work in 5 hours.  If you need any specific logs, lemme know, I can get them together along with the video. :) 

Thanks!
