### ISSUE TITLE
Error loading world (Exception thrown by server during startup or process)

### ISSUE THREAD

**Issue by RomZomb** [anegostudios/VintageStory-Issues#2133]
**Game Version:v 1.16.5(Stable) By 
**Platform:** Windows 10 
**Modded:** No 
**SP/MP:** Singleplayer 

### Description
I just played the game and I was abruptly thrown out of the world, after that they stopped letting me into the world and I can’t create a new one either, and during these actions an error occurs, shown in the screenshot below.

### How to reproduce
1. Make a: Just play the game
2. Use it on:  Just full of any action
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
![image](https://user-images.githubusercontent.com/96005057/186934987-e0576835-99a6-4bb0-891c-53bc02000f67.png)

### Logs
```Exception thrown by server during startup or process```

26.8.2022 22:56:51 [Notification] Client logger started.
26.8.2022 22:56:51 [Notification] Game Version: v1.16.5 (Stable) By Skif_97, final offline release... Good luck to you all...  
26.8.2022 22:56:51 [Notification] Screens:
26.8.2022 22:56:51 [Notification] 0: {X=0,Y=0,Width=1920,Height=1080}, \\.\DISPLAY2 (primary)
26.8.2022 22:56:51 [Notification] 1: {X=-1280,Y=64,Width=1280,Height=1024}, \\.\DISPLAY3 
26.8.2022 22:56:51 [Notification] 2: {X=-3200,Y=-3,Width=1920,Height=1080}, \\.\DISPLAY1 
26.8.2022 22:56:53 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
26.8.2022 22:56:53 [Notification] Graphics Card Vendor: NVIDIA Corporation
26.8.2022 22:56:53 [Notification] Graphics Card Version: 3.3.0 NVIDIA 472.12
26.8.2022 22:56:53 [Notification] Graphics Card Renderer: NVIDIA GeForce GTX 660/PCIe/SSE2
26.8.2022 22:56:53 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
26.8.2022 22:56:53 [Notification] Cairo Graphics Version: 1.17.3
26.8.2022 22:56:53 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
26.8.2022 22:56:53 [Notification] C# Framework: .net Framework 4.0.30319.42000
26.8.2022 22:56:53 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
26.8.2022 22:56:53 [Notification] Start discovering assets
26.8.2022 22:56:53 [Notification] Found 18 base assets in category lang
26.8.2022 22:56:53 [Notification] Found 0 base assets in category patches
26.8.2022 22:56:53 [Notification] Found 22 base assets in category config
26.8.2022 22:56:53 [Notification] Found 0 base assets in category worldproperties
26.8.2022 22:56:53 [Notification] Found 50 base assets in category sounds
26.8.2022 22:56:53 [Notification] Found 96 base assets in category shapes
26.8.2022 22:56:53 [Notification] Found 74 base assets in category shaders
26.8.2022 22:56:53 [Notification] Found 16 base assets in category shaderincludes
26.8.2022 22:56:53 [Notification] Found 128 base assets in category textures
26.8.2022 22:56:53 [Notification] Found 4 base assets in category music
26.8.2022 22:56:53 [Notification] Found 0 base assets in category dialog
26.8.2022 22:56:53 [Notification] Found 408 base assets in total
26.8.2022 22:56:53 [Notification] Loading sounds
26.8.2022 22:56:53 [Notification] (Re-)loaded frame buffers
26.8.2022 22:56:53 [Notification] Loaded Shaderprogramm for render pass . 
26.8.2022 22:56:53 [Notification] CPU Cores: 4
26.8.2022 22:56:53 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
26.8.2022 22:56:53 [Notification] (Re-)loaded frame buffers
26.8.2022 22:56:54 [Notification] Waiting for async sound loading...
26.8.2022 22:56:54 [Notification] Sounds loaded
26.8.2022 22:56:54 [Notification] Begin loading shaders
26.8.2022 22:56:54 [Notification] Load shaders now
26.8.2022 22:56:54 [Notification] Loading shaders...
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass standard. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass particlescube. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass particlesquad. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass sky. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass nightsky. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass woittest. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass transparentcompose. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass helditem. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass chunkopaque. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass chunkliquid. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass decals. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass final. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass gui. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass blur. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass chunktransparent. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass findbright. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass chunktopsoil. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass godrays. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass autocamera. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass blockhighlights. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass wireframe. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass entityanimated. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass luma. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass blit. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass particlesquad2d. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass texture2texture. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass celestialobject. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass guitopsoil. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass entityanimatedtransparent. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass colorgrade. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass guigear. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass ssao. 
26.8.2022 22:56:54 [Notification] Loaded Shaderprogramm for render pass bilateralblur. 
26.8.2022 22:56:54 [Notification] Cached session key is invalid, require login
26.8.2022 22:56:58 [Notification] Will search the following paths for mods:
26.8.2022 22:56:58 [Notification]     D:\Games\Vintage Story\Mods
26.8.2022 22:56:58 [Notification]     C:\Users\void\AppData\Roaming\VintagestoryData\Mods
26.8.2022 22:57:08 [Notification] Initialized GUI Manager
26.8.2022 22:57:09 [Notification] Initialized Server Connection
26.8.2022 22:57:09 [Notification] Server args parsed
26.8.2022 22:57:09 [Notification] GuiScreenConnectingToServer constructed
26.8.2022 22:57:09 [Notification] Server main instantiated
26.8.2022 22:57:09 [Fatal] System.Exception: Disk space is below 400 megabytes (356 mb left). A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json (or set to -1 to disable this check). Will kill server now...
   в Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration()
   в Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   в Vintagestory.Server.ServerMain.Launch()
   в _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._ZHhrbmNLuSrtHTKBjZE8YscjKrG()

26.8.2022 22:57:09 [Notification] Server logger started.
26.8.2022 22:57:09 [Notification] Game Version: v1.16.5 (Stable) By Skif_97, final offline release... Good luck to you all...  
26.8.2022 22:57:09 [Event] Launching server...
26.8.2022 22:57:09 [Event] Server v1.16.5, network v1.16.5, api v1.7.0
26.8.2022 22:57:09 [Notification] Entering runphase Initialization
26.8.2022 22:57:09 [Event] Loading configuration...
26.8.2022 22:57:09 [Notification] Entering runphase Configuration
26.8.2022 22:57:09 [Fatal] Disk space is below 400 megabytes (356 mb left). A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json (or set to -1 to disable this check). Will kill server now...
26.8.2022 22:57:09 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception thrown by server during startup or process
26.8.2022 22:57:09 [Notification] Entering runphase Shutdown
26.8.2022 22:57:09 [Notification] Defragmented listener lists
26.8.2022 22:57:09 [Event] Shutting down 5 server threads... 
26.8.2022 22:57:09 [Event] Killed console thread
26.8.2022 22:57:09 [Event] All threads gracefully shut down
26.8.2022 22:57:09 [Event] Doing last tick...
26.8.2022 22:57:09 [Event] Stopped the server!

**Comment by Craluminum2413** [comment]
You haven't uploaded any logs

**Comment by EnigmaticaGH** [comment]
@RomZomb You need to free up some hard drive space. Notice in the logs: 

> 26.8.2022 22:57:09 [Fatal] Disk space is below 400 megabytes (356 mb left). A full harddisk can heavily corrupt a savegame. Please free up more disk space or adjust the threshold in the serverconfig.json (or set to -1 to disable this check). Will kill server now...
26.8.2022 22:57:09 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception thrown by server during startup or process

**Comment by Craluminum2413** [comment]
It looks like here is a pirate version, I will close as invalid for now
