### ISSUE TITLE
Access violation crash caused by iron bloom being processed with helve hammer (+example world)

### ISSUE THREAD

**Issue by grompe** [anegostudios/VintageStory-Issues#2134]
**Game Version:** v1.17.0-rc.7
**Platform:** Windows 7
**Modded:** No
**SP/MP:** Singleplayer

### Description
Got almost-hot iron blooms from bloomery, heated up a little to 800°C and put on anvil for a helve hammer to process, game causes an access violation: "Instruction at address 0x1edd5c70 could not read memory at 0x51c60000". The last 4 hex-digits of each seem to be constant.

### How to reproduce
1. Load the provided example world [bloom_crash_trimmed.zip](https://github.com/anegostudios/VintageStory-Issues/files/9435031/bloom_crash_trimmed.zip)
2. Look at the bloom, wait for a few anvil hits
3. Crash
3a. If it doesn't crash, put another bloom on the anvil then it crashes. This crash seems to be a bit random.

### Additional info
Not sure if it's related, in previous 1.17.0 rc/pre versions I had a similar crash when putting too many layers of iron ingots in order to make a coke oven door.

### Screenshots
![bloom_crash](https://user-images.githubusercontent.com/1010017/186955123-fe91a014-6e54-469b-94ec-f5cf7f258595.png)

### Logs
No logs because it is a lower level crash.

**Comment by tyronx** [comment]
Hey, I processed 3 blooms in your world and could not reproduce the crash. 
This rather sounds to me like a potential driver or ram problem. Recommend updating your graphics driver and/or do a memtest.
