### ISSUE TITLE
1.17.0 rc7 Armor no longer can give positive StatModifiers

### ISSUE THREAD

**Issue by TheHaterofGravel** [anegostudios/VintageStory-Issues#2136]
Game Version: 1.17.0 rc7
Platform: Windows 10
Modded: No
SP/MP: Singleplayer

Description-
Seems like the solution to this issue #2092 - https://github.com/anegostudios/VintageStory-Issues/issues/2092
has completely broken all armors so that they are unable to give positive effects at all. The following StatModifiers: walkspeed, healingeffectivness, rangedWeaponsAcc, rangedWeaponsSpeed cannot go over 100% and the StatModifiers: hungerrate, rangedWeaponsSpeed cannot go under 100%. This completely prevents any armors from giving bonuses to these stats in any way.

How to reproduce-
1. Go in to your games armor itemtype json
2. Change any "statModifiersByType" to a value that is inverse to what it is normally set as, for instance change any "hungerrate" value to a negative number
3. Wear the modified armor type with the changed value
4. a -25% hungerrate, or setting the  hungerrate value to -0.25 should change your character tab value for "Hunger rate" to 75%, but instead that value remains at 100% and is unable to go below that.

Expected behavior-
As stated before, all versions before 1.17 have support for positive StatModifiers. This feature should remain since it allows easier implementation of custom modifier armor sets.

**Comment by tyronx** [comment]
oh, i bet that only applies to armor that are fully undamaged. Should be fixed next release 👍
