### ISSUE TITLE
Spoiled and then re-heated cooking pots crash the game when emptied with a bowl

### ISSUE THREAD

**Issue by Lacksi** [anegostudios/VintageStory-Issues#2137]
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Multiplayer

### Description
I had a cooking pot that spoiled. I accidentally reheated it and when I then tried to empty the pot with a bowl (works fine for un-heated, spoiled pots) the game crashed on me consistenly. It crashes when heating the pot, when the pot isnt heated and cooling down, it stills crash the game and when the pot has cooled down completely again it also still crashes the game.
The pot was always in a firepit.

The pot can still be picked up and emptied by throwing it into water normally, as expected.

### How to reproduce
1. put spoiled cooking pot in a firepit
2. Heat the pot
3. right click on the pot with a bowl in hand
4. game crashes

### Expected behavior
empty part of the rot into the bowl

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Do not have log because its not my server and its already overwritten, sorry.
```

**Comment by Craluminum2413** [comment]
I can't reproduce this on 1.17.0-rc.7

**Comment by Craluminum2413** [comment]
Can't reproduce on 1.16.5 either, seems like a problem is in the mods you are using
