### ISSUE TITLE
Cannot take back armor stand

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2138]
**Game Version:** v1.17.0-rc.8
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
After placing an armor stand on the ground (it was packed dirt). It was impossible for me to take it back in my inventory.

**Comment by Craluminum2413** [comment]
Do you use Shift + Right-click? You can also try Ctrl + Right-click

**Comment by Xandoria** [comment]
Oh it's working. Sorry, I did not know about those keys.
