### ISSUE TITLE
Lots of ore blasting bombs can easily cause a server to freeze

### ISSUE THREAD

**Issue by TarikYuzkiv** [anegostudios/VintageStory-Issues#2143]
**Game Version:** 1.17.0-rc.7
**Platform:** Windows 
**Modded:** No
**SP/MP:** Multiplayer

### How to reproduce
Just place a lot (I installed ~120) ore blasting bombs and activate them. The server starts to freeze to a lot of time.

VIDEO:
[![VIDEO](https://img.youtube.com/vi/xarCkg7AWhI/0.jpg)](https://www.youtube.com/watch?v=xarCkg7AWhI)

Explosions starts at 4:35, in 5:15 server is becomes alive! (:

### Logs
Nothing strange, just reports of a very bad tick rate:
```
31.8.2022 05:13:01 [Warning] Server overloaded. A tick took 217336ms to complete.
```

**Comment by TarikYuzkiv** [comment]
I understand very well that the occurrence of such a situation in a real game is unlikely, but on my server this happened with a usual player.

**Comment by wasakoki** [comment]
yeah, the lag is very excessive, i came across this some time ago in my survival world when trying to use bombs to clear out a path to make a road, it was disappointing when i realized manually digging was alot quicker than bombs with this kind of lag!
