### ISSUE TITLE
World doesn't load blocks

### ISSUE THREAD

**Issue by Skrepon** [anegostudios/VintageStory-Issues#2157]
**Game Version:** 1.17.2
**Platform:** Windows   
**Modded:**Yes   
**SP/MP:** Singleplayer  

### Description
This is the second world where I have been unable to play because the world just will not load. The first time, fresh world after the 1.17.2 update came out, and then I couldn't collect reeds. They would break, but there was no drop. I deleted this world thinking I made a mistake. The second world was working just fine, but again, I noticed I wasn't getting any drops. I broke six wild crops with no drops. I broke another block when I realized the problem wasn't luck, and there was no drop. I closed the world and attempted to reopen it. No blocks would spawn. It was just my character and the sky. The map overlay showed the world still. I attempted to run the repair mode, but nothing changed. It did say something about not being able to communicate with the host, but I don't know what that means.

### How to reproduce
Not sure. I will take the mods off and try running the game through each mod individually.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Game didn't crash, no log to add.
```
![2022-09-02_20-54-33](https://user-images.githubusercontent.com/112740001/188253238-49cc1617-0d4d-40c6-b257-9373e6eb2f34.png)

**Comment by Skrepon** [comment]
There was no change when mods were removed. I did attempt the repair mode again as well without mods. I use these mods;
Anvil Metal Recovery+
Carry Capacity
From Golden Combs
ProspectorInfo
Resin Regrow
Visible Terra Preta

**Comment by Craluminum2413** [comment]
Have you encountered this error without using any server-side mods?

**Comment by Skrepon** [comment]
I bought the game about two weeks ago, so I can't say that I have.

**Comment by Craluminum2413** [comment]
Could you try to load new world without any mods installed?

**Comment by Skrepon** [comment]
Yeah, I can try that. I did get onto my world just now. No mods, adding them back one at a time.

**Comment by Skrepon** [comment]
I wish I could offer more help. Is there anything else I can do to help you solve this?

**Comment by Skrepon** [comment]
Do the settings I play with matter? I can set them on the new world if that makes a difference or not.

**Comment by Craluminum2413** [comment]
I don't think it matters until we make sure it doesn't occur without any mods installed

**Comment by Skrepon** [comment]
I started the new world, no mods. As far as I can tell, it functions as normal. I was playing my other world for an hour and a half before the glitch happened. I will run through the mods one at a time like I suggested earlier to see if I can pin-point the problem.

**Comment by Skrepon** [comment]
I was able to recreate this when using Resin Regrow. I will leave a message on the mods page.

**Comment by Skrepon** [comment]
I'll close this ticket in 30 minutes.

**Comment by Craluminum2413** [comment]
So it does only happen with Resin Regrow mod installed? If so, then I close this issue as invalid

**Comment by Skrepon** [comment]
The mod page has a few comments showing problems from Jan. The mod is probably just old.
