### ISSUE TITLE
1.17.8 Fish meat items not in Handbook or Creative menu

### ISSUE THREAD

**Issue by RogueRaiden** [anegostudios/VintageStory-Issues#2166]
**Game Version:** 1.17.2 
**Platform:** Windows
**Modded:** No
**SP/MP:** Either

### Description
Raw Fish, Cooked Fish and Cured Fish are not in the Creative menu or Handbook despite being able to harvest Raw Fish from Salmon.

### How to reproduce
1. Open Handbook and/or Creative menu
2. Type into search bar "fish"
3. Observe as only the Fish and the Rain painting shows up

### Expected behavior
To see Raw Fish, Cooked Fish and Cured Fish in the Creative menu and Handbook

### Screenshots
![2022-09-05_02-28-02](https://user-images.githubusercontent.com/26943867/188383070-6aa8d4d5-772c-434d-b4cf-a7d617cfe924.png)

**Comment by Craluminum2413** [comment]
Worth mention, that once item is listed in creative menu, it can have its own handbook page, not vice versa
