### ISSUE TITLE
Implement and use proper BlockPos, Vector, Matrix structs and similar

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#217]
Right now `BlockPos` and `Vec3f` are classes and `Mat4f` is a static class that provides functions that operate of a `float[]` with 16 elements.

Regarding the math related structs: Don't reinvent the wheel. Use an open source library and if an additional .dll is undesired, just include the source itself in the VintagestoryAPI project.

It would be wonderful if we could replace them throughout the entire engine, but this is likely not an easy task. So perhaps it could be done by introducing the fixed types as new types and slowly work through and replace the old ones.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

Could also be posted in #gamedev on discord.
