### ISSUE TITLE
All plant container block share "fillHeight"

### ISSUE THREAD

**Issue by tels-git** [anegostudios/VintageStory-Issues#2173]
**Game Version:** 1.17.2
**Platform:** All
**Modded:** Yes
**SP/MP:** Both

### Description
Changing fillHeight in any container changes the fillHeight for all blocks, in the entire world, even vanilla planters. This makes it impossible to have different shaped planters.

A similiar issue might exist with sitHeight, but I have not tested this.

See screenshots.

### How to reproduce
1. Make a new planter JSON (copy of planter.json)
2. use a differen shape (any will do)
3. change fillHeight to a different value
4. Observe planters

### Expected behavior
filHeight should be respected for each different planter code.

### Screenshots
Changing the fillHeight on the JSON on the left changes also the planted height of the planter on the right, as well as vanilla planters (not shown in the screenshot):

![plant_container_override](https://user-images.githubusercontent.com/29096965/188428846-e0eab1b0-9dcf-4226-9a54-93017fe48584.jpg)

**Comment by Craluminum2413** [comment]
What `plantContainerSize` did you set for your tall planter?

**Comment by Craluminum2413** [comment]
Currently the only way to change `fillHeight` is to use custom `plantContainerSize`, <https://github.com/anegostudios/vssurvivalmod/blob/9f2f42da65ac74d1aff50f480c6c38769c87890a/BlockEntity/BlockEntityPlantContainer.cs#L356-L360>

Here is a perfect example. I changed `fillHeight` for my planters that have `plantContainerSize` as `fplanter2x1`. vanilla planters are completely untouched.
![image](https://user-images.githubusercontent.com/69315569/188432538-8160e18a-68a8-415f-a451-dbe68fe7e464.png)

**Comment by tyronx** [comment]
thanks for the report, this should be better supported for next version
