### ISSUE TITLE
You can track your coordinates on servers without minimap/coordinate overlays by using waypoints

### ISSUE THREAD

**Issue by strkeeper** [anegostudios/VintageStory-Issues#2174]
**Game Version:** 1.17.2
**Platform:**  Linux 
**Modded:** No 
**SP/MP:**  Multiplayer 

### Description
Waypoints can be used on servers to keep track of your coordinates and to log POIs even when the minimap and coordinate overlay is disabled.

### How to reproduce
1. Join/Create a wilderness survival server
1. Create a waypoint by typing /waypoint add [color] [name]
2. Type /waypoint list
3. The chat window will show the waypoint you just created and thus, your position in the world.

### Expected behavior
These commands should fail to execute if the minimap is disabled on the server.

### Screenshots
![image](https://user-images.githubusercontent.com/112954396/188646621-09a4977a-94bb-4f7d-9af6-9f893856f2cf.png)

**Comment by tyronx** [comment]
oooof, missing `return;` statement. thanks, will be fixed next release
