### ISSUE TITLE
Upgrade from 1.16.5 to 1.17.2 Causes Blackguard Square Shield to Corrupt

### ISSUE THREAD

**Issue by kurazarrh** [anegostudios/VintageStory-Issues#2175]
I updated my world from 1.16.5 to 1.17.2, and all of the Blackguard Square Shields are now square-shaped blobs of white that have no use.

Reproduce:

1) Create a 1.16.5 world.
2) Spawn or craft a Blackguard Square Shield.
3) Update game to 1.17.2.
4) Load in and view/attempt to use the shield.

**Comment by kurazarrh** [comment]
For some reason, github didn't provide the bug creation template for this bug; I realized it afterward. But this should be enough to reproduce the issue.

**Comment by Craluminum2413** [comment]
Duplicate of #2057
