### ISSUE TITLE
Quern progress resets on input

### ISSUE THREAD

**Issue by Konfuz** [anegostudios/VintageStory-Issues#2178]
**Game Version:** 1.16.5

### Description
On input the Quern resets the grinding process of the currently ground item to 0. 
This is very noticable when using a archimedes screw to feed the quern via a chute as 
the progress will constantly get reset making automated feeding highly ineffective. 

### Code
I think the offending line is in https://github.com/anegostudios/vssurvivalmod/blob/08fadd58f5bd39d5dd80fd5755f9534f2a02f12f/BlockEntity/BEQuern.cs#L402 progess should only be reset if the itemtype in slot 0 changes.
```c#
  private void OnSlotModifid(int slotid)
        {
            if (Api is ICoreClientAPI)
            {
                clientDialog.Update(inputGrindTime, maxGrindingTime());
            }

            if (slotid == 0)
            {
                inputGrindTime = 0.0f; //reset the progress to 0 if the item is removed.
                MarkDirty();

                if (clientDialog != null && clientDialog.IsOpened())
                {
                    clientDialog.SingleComposer.ReCompose();
                }
            }
        }
```

**Comment by tyronx** [comment]
i agree. I can reset the time only if the slot is empty, that is a simpler check
