### ISSUE TITLE
Unable to load saves due to spawn issue

### ISSUE THREAD

**Issue by SmeeSlug** [anegostudios/VintageStory-Issues#2179]
**Game Version:** 1.17.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Doesn't allow me to reload a save after exiting. Loading in the spectator mode works, I am placed at the correct spot, then it still does not let me in when loading the game normally.

### Logs
```
7.9.2022 21:29:40 [Event] Launching server...
7.9.2022 21:29:40 [Event] Server v1.17.2, network v1.17.8, api v1.7.0
7.9.2022 21:29:40 [Event] Loading configuration...
7.9.2022 21:29:40 [Event] Building assets...
7.9.2022 21:29:45 [Event] Remapping blocks and items...
7.9.2022 21:29:45 [Event] 6 cooking recipes loaded
7.9.2022 21:29:46 [Event] 588 crafting recipes loaded from 211 files
7.9.2022 21:29:46 [Event] 7 metal alloys loaded
7.9.2022 21:29:46 [Event] 222 smithing recipes loaded
7.9.2022 21:29:46 [Event] 55 clay forming recipes loaded
7.9.2022 21:29:46 [Event] 36 knapping recipes loaded
7.9.2022 21:29:46 [Event] 136 barrel recipes loaded
7.9.2022 21:29:47 [Event] Server assets loaded, parsed, registered and finalized
7.9.2022 21:29:47 [Event] Initialising systems...
7.9.2022 21:29:49 [Event] Starting world generators...
7.9.2022 21:29:52 [Event] Loading 7x7x8 spawn chunks...
7.9.2022 21:29:52 [Event] 0% (49 in queue)
7.9.2022 21:29:53 [Event] Begin game ticking...
7.9.2022 21:29:53 [Event] Singleplayer Server now running!
7.9.2022 21:29:53 [Error] System.Exception: Invalid spawn coordinates found. It is outside the world map.
   at Vintagestory.Server.ServerMain.EntityPosFromSpawnPos(PlayerSpawnPos playerSpawn) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 1387
   at Vintagestory.Server.ServerMain.GetSpawnPosition(String playerUID, Boolean onlyGlobalDefaultSpawn, Boolean consumeSpawn) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 1350
   at Vintagestory.Server.ServerMain.FinalizePlayerIdentification(Packet_ClientIdentification packet, ConnectedClient client, String entitlements) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 279
   at Vintagestory.Server.ServerMain.HandlePlayerIdentification(Packet_Client p, ConnectedClient client) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerGeneralPacketHandler.cs:line 609
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 110
7.9.2022 21:30:08 [Event] Mods and systems notified, now saving everything...
7.9.2022 21:30:08 [Event] Saved player world data...
7.9.2022 21:30:10 [Event] Saved map regions...
7.9.2022 21:30:10 [Event] Saved map chunks...
7.9.2022 21:30:10 [Event] Saved loaded chunks...
7.9.2022 21:30:10 [Event] Saved generating chunks...
7.9.2022 21:30:10 [Event] Saved savegamedata...2
7.9.2022 21:30:10 [Event] World saved! Saved 4 chunks, 0 mapchunks, 16 mapregions.
7.9.2022 21:30:10 [Event] Shutting down 5 server threads... 
7.9.2022 21:30:10 [Event] Killed console thread
7.9.2022 21:30:11 [Event] All threads gracefully shut down
7.9.2022 21:30:11 [Event] Doing last tick...
7.9.2022 21:30:11 [Event] Stopped the server!
```

**Comment by SmeeSlug** [comment]
It seems not to happen with default settings, but has something to do with something in here.
  "worldClimate": "realistic",
  "gameMode": "survival",
  "temporalStability": true,
  "temporalStorms": "sometimes",
  "graceTimer": "0",
  "microblockChiseling": "all",
  "polarEquatorDistance": "50000",
  "lungCapacity": "60000",
  "harshWinters": "true",
  "daysPerMonth": "12",
  "saplingGrowthRate": "1",
  "allowUndergroundFarming": true,
  "temporalGearRespawnUses": "-1",
  "temporalStormSleeping": "0",
  "startingClimate": "temperate",
  "spawnRadius": "50",
  "deathPunishment": "drop",
  "seasons": "enabled",
  "playerlives": "-1",
  "blockGravity": "sandgravelsoil",
  "bodyTemperatureResistance": "0",
  "creatureHostility": "aggressive",
  "creatureStrength": "1",
  "playerHealthPoints": "20",
  "playerHungerSpeed": "0.75",
  "playerMoveSpeed": "1.75",
  "foodSpoilSpeed": "1",
  "toolDurability": "1.25",
  "toolMiningSpeed": "1.25",
  "propickNodeSearchRadius": "8",
  "globalDepositSpawnRate": "1",
  "allowCoordinateHud": true,
  "allowMap": true,
  "tempstormDurationMul": "1",
  "temporalRifts": "visible",
  "worldWidth": "102400",
  "worldLength": "1024000",
  "worldEdge": "traversable",
  "globalTemperature": "1",
  "globalPrecipitation": "1",
  "globalForestation": "0",
  "surfaceCopperDeposits": "0.12",
  "surfaceTinDeposits": "0.007",
  "snowAccum": "true",
  "allowLandClaiming": true,
  "classExclusiveRecipes": false,
  "auctionHouse": true,
  "playstyle": "surviveandbuild"

**Comment by SmeeSlug** [comment]
From a little extra testing, predictably seems to be a world size problem!

**Comment by tyronx** [comment]
could you drop in the entire serverconfig.json please
