### ISSUE TITLE
breaking berry bushes ignores the forage debuff from certain classes

### ISSUE THREAD

**Issue by tacct6** [anegostudios/VintageStory-Issues#2180]
**Game Version:** 1.17.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Both

### Description
when breaking a berry bush as a blackguard/tailor (heavyhanded/civil traits), the amount of berries you get is consistently more than you get compared to harvesting with a right click, implying the debuff does not work when breaking the bush.

### How to reproduce
1. be blackguard/tailor (the difference is more noticeable on blackguard)
2. break 16 fully grown berry bushes, keep track of the amount of berries obtained.
3. harvest (but don't break) 16 more fully grown berry bushes. notice the amount you obtained is substantially less than the previous test.

### Expected behavior
it should not be this easy to bypass a trait debuff.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
