### ISSUE TITLE
Game just crashes

### ISSUE THREAD

**Issue by Perry210174** [anegostudios/VintageStory-Issues#2182]
**Game Version:** 1.17.3  
**Platform:** Windows 11
**Modded:** hudclock, prospectorinfo
**SP/MP:** Singleplayer

### Description
Game crashes, when I run

### How to reproduce
I dont know. I load the game and run to the south.

### Expected behavior
The game doesnt't crash

### Screenshots
-

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.3 (Stable)
10.09.2022 15:12:55: Critical error occurred
Loaded Mods: game@1.17.3, hudclock@2.8.0, prospectorinfo@3.2.0, creative@1.17.3, survival@1.17.3
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 299.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 228.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 372.
   bei Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:Zeile 409.
   bei Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:Zeile 817.
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:Zeile 1138.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 123.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 669.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 613.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 125.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.08.2022 06:11:56, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IndexOutOfRangeException
   bei Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()
   bei Vintagestory.Client.NoObf.ClientMain.FinaliseTextureAtlas_StageC(Vintagestory.Client.NoObf.TextureAtlasManager, System.String, System.Action)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
```
(Sorry, can't attach savegame: file too big)

**Comment by CardiacTasty** [comment]
There's quite a bit of discussion around problems with fruit trees in Vintage Story's Discord. Hopefully we see a fix to this and other problems around fruit trees in the near future.

**Comment by Perry210174** [comment]
I updated to version 1.17.4, error still occures

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.4 (Stable)
21.09.2022 18:07:15: Critical error occurred
Loaded Mods: game@1.17.4, hudclock@2.8.0, prospectorinfo@3.2.0, creative@1.17.4, survival@1.17.4
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 299.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 228.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 372.
   bei Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:Zeile 409.
   bei Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:Zeile 817.
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:Zeile 1138.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 123.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 669.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 613.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 125.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.08.2022 06:11:56, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IndexOutOfRangeException
   bei Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()
   bei Vintagestory.Client.NoObf.ClientMain.FinaliseTextureAtlas_StageC(Vintagestory.Client.NoObf.TextureAtlasManager, System.String, System.Action)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Perry210174** [comment]
Version 1.17.6 doesn't help. :(

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.6 (Stable)
05.10.2022 17:28:29: Critical error occurred
Loaded Mods: game@1.17.6, hudclock@2.8.0, prospectorinfo@3.2.0, creative@1.17.6, survival@1.17.6
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 299.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 228.
   bei Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:Zeile 372.
   bei Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunk.cs:Zeile 409.
   bei Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:Zeile 817.
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:Zeile 1138.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 123.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 669.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 613.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 124.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.08.2022 06:11:56, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IndexOutOfRangeException
   bei Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlasses_StageC()
   bei Vintagestory.Client.NoObf.ClientMain.FinaliseTextureAtlas_StageC(Vintagestory.Client.NoObf.TextureAtlasManager, System.String, System.Action)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
Does it happen on any world you play?

**Comment by Perry210174** [comment]
> Does it happen on any world you play?

No just in one Savegame.

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed next release. Until then, this build should fix this: https://cdn.vintagestory.at/gamefiles/unstable/vs_update_1.17.7-rc.1.exe
