### ISSUE TITLE
Barrel incontainer liquid translation does not respect modid

### ISSUE THREAD

**Issue by tels-git** [anegostudios/VintageStory-Issues#2186]
**Game Version:** 1.17.3  
**Platform:** All
**Modded:** Yes (All)
**SP/MP:** Both

### Description
The barrel's in-container interface does not respect the modid-domain when showing the liquid name, both before and after crafting.

First screenshot shows the missing entries. By adding artificial tags like so:
```
"bricklayers:incontainer-item-causticpotashportion":  "Caustic potash solution (BL)",
"game:incontainer-item-causticpotashportion":         "Caustic potash solution (game)",
```
one can see in the second screenshot that different entries are used for the same liquid.

### Expected behavior
The "game:"-entry should not be necessary and the "modid:incontainer-item-XYZ" entry to be used all the time instead.

### Screenshots
![incontainer_names_missing](https://user-images.githubusercontent.com/29096965/189521251-394f1fb9-8af0-4cf2-afc6-bd8d0cd01c4d.jpg)

![incontainer_names](https://user-images.githubusercontent.com/29096965/189521121-08932181-a28f-48e9-879d-f95d376e8431.jpg)

**Comment by tyronx** [comment]
fixed for next release 👍
