### ISSUE TITLE
Weighted entity random grow

### ISSUE THREAD

**Issue by TonyLiberatto** [anegostudios/VintageStory-Issues#219]
When growing entities instead of a list to pick from we need to have a way to weight the chance of random.
So instead of this:
```json
{ 
	code: "grow",
	hoursToGrow: 168,
	adultEntityCodes: ["chicken-hen", "chicken-hen", "chicken-hen", "chicken-hen", "chicken-hen", "chicken-hen", "chicken-hen", "chicken-hen", "chicken-hen", "chicken-rooster"],
},
```
We could have this:
```json
{ 
	code: "grow",
	hoursToGrow: 168,
	adultEntityCodes: {
		"chicken-hen": { chance: { avg: 0.9, var: 0.2 } },
		"chicken-rooster": { chance: { avg: 0.2, var: 0.1 } },
	},
},
```
When we set Variants the possibilities are even higher with each animal having more attributes, like color, size, speed. And so on and so forth.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
