### ISSUE TITLE
Paintings on glacier ice : wrong rendering

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2190]
**Game Version:** 1.17.3
**Platform:** Mint
**Modded:** No
**SP/MP:** Singleplayer

### Description
Paintings on a glacier ice wall are well rendered only when very close.

### Screenshots
![2022-09-12_14-40-51](https://user-images.githubusercontent.com/84909583/189657351-cccf5268-a8ee-421a-8184-e209c2a06c37.png)
![2022-09-12_14-41-07](https://user-images.githubusercontent.com/84909583/189657367-4add7e58-96ed-4ae2-8069-d19a9f4ec724.png)

**Comment by tyronx** [comment]
thanks for the report, 1.17.4 will mitigate this issue but not fully fix it (and at this point in time don't intend to due to technical limitations).
