### ISSUE TITLE
Crashes even without launching

### ISSUE THREAD

**Issue by TadjikX** [anegostudios/VintageStory-Issues#2192]
![fjfjfj](https://user-images.githubusercontent.com/113508013/190100933-e8e71ecd-689b-4a8a-95d7-4cb554ea4791.png)
**Game Version:** X.Y.Z  
**Platform:** Windows / Mac / Linux (which?)   
**Modded:** No / Yes (which?)  
**SP/MP:** Singleplayer / Multiplayer (which?)  

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment]
Open `\AppData\Roaming\VintagestoryData\clientsettings.json` and set `glContextVersion` to `4.3`, it may fix your problem

**Comment by TadjikX** [comment]
> Open `\AppData\Roaming\VintagestoryData\clientsettings.json` and set `glContextVersion` to `4.2`, it may fix your problem

sadly it didnt help

**Comment by Craluminum2413** [comment]
What GPU do you have and have you launched the game before?

**Comment by TadjikX** [comment]
> What GPU do you have and have you launched the game before?

Game launched on the version 16.x.x but then i left the game for a really long time and when wanted to play it showed me that crash that you see rn, now i installed 17th version and it's still same

**Comment by Craluminum2413** [comment]
Can you send `client-main.txt` from `\AppData\Roaming\VintagestoryData\Logs`?

**Comment by TadjikX** [comment]
> Can you send `client-main.txt` from `\AppData\Roaming\VintagestoryData\Logs`?

i just deleted it but gonna reinstall rn

**Comment by TadjikX** [comment]
> > Can you send `client-main.txt` from `\AppData\Roaming\VintagestoryData\Logs`?
> 
> i just deleted it but gonna reinstall rn

14.9.2022 15:15:18 [Notification] Client logger started.
14.9.2022 15:15:18 [Notification] Game Version: v1.17.3 (Stable) by OverF1X  
14.9.2022 15:15:18 [Notification] Screens:
14.9.2022 15:15:18 [Notification] 0: {X=0,Y=0,Width=1366,Height=768}, \\.\DISPLAY1 (primary)
14.9.2022 15:15:19 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
14.9.2022 15:15:19 [Notification] Graphics Card Vendor: Intel
14.9.2022 15:15:19 [Notification] Graphics Card Version: 3.1.0 - Build 9.17.10.4459
14.9.2022 15:15:19 [Notification] Graphics Card Renderer: Intel(R) HD Graphics 3000
14.9.2022 15:15:19 [Notification] Graphics Card ShadingLanguageVersion: 1.40 - Intel Build 9.17.10.4459
14.9.2022 15:15:19 [Notification] Cairo Graphics Version: 1.17.3
14.9.2022 15:15:19 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
14.9.2022 15:15:19 [Notification] C# Framework: .net Framework 4.0.30319.42000
14.9.2022 15:15:19 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
14.9.2022 15:15:19 [Notification] Start discovering assets
14.9.2022 15:15:19 [Notification] Found 18 base assets in category lang
14.9.2022 15:15:19 [Notification] Found 0 base assets in category patches
14.9.2022 15:15:19 [Notification] Found 22 base assets in category config
14.9.2022 15:15:19 [Notification] Found 0 base assets in category worldproperties
14.9.2022 15:15:19 [Notification] Found 46 base assets in category sounds
14.9.2022 15:15:19 [Notification] Found 97 base assets in category shapes
14.9.2022 15:15:19 [Notification] Found 80 base assets in category shaders
14.9.2022 15:15:19 [Notification] Found 16 base assets in category shaderincludes
14.9.2022 15:15:19 [Notification] Found 128 base assets in category textures
14.9.2022 15:15:19 [Notification] Found 4 base assets in category music
14.9.2022 15:15:19 [Notification] Found 0 base assets in category dialog
14.9.2022 15:15:19 [Notification] Found 411 base assets in total
14.9.2022 15:15:19 [Notification] Loading sounds
14.9.2022 15:15:19 [Notification] Sounds loaded
14.9.2022 15:15:19 [Notification] (Re-)loaded frame buffers
14.9.2022 15:15:19 [Error] Shader compile error in hardcoded ERROR: 0:3: 'layout' : syntax error syntax error
14.9.2022 15:15:19 [Notification] CPU Cores: 4
14.9.2022 15:15:19 [Notification] Window was resized to 1366 768, rebuilding framebuffers...
14.9.2022 15:15:19 [Notification] (Re-)loaded frame buffers
14.9.2022 15:15:20 [Notification] Begin loading shaders
14.9.2022 15:15:20 [Notification] Load shaders now
14.9.2022 15:15:20 [Notification] Loading shaders...
14.9.2022 15:15:20 [Fatal] Game Version: v1.17.3 (Stable) by OverF1X  
14/09/2022 15:15:20: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card supports only OpenGL version 140 (1.40 - Intel Build 9.17.10.4459), but OpenGL version 330 is required.
Please check if you have installed the latest version of your graphics card driver. If they are, your graphics card may be to old to play Vintage Story.(Note: In case of modded gameplay with modded shaders, the mod author may be able to lower the OpenGL version requirements)
   at Vintagestory.Client.NoObf.Shader.EnsureVersionSupported(String versionUsed, String ownFilename)
   at Vintagestory.Client.NoObf.Shader.EnsureVersionSupported()
   at Vintagestory.Client.NoObf.ShaderProgram.Compile()
   at Vintagestory.Client.NoObf.ShaderRegistry.loadRegisteredShaderPrograms()
   at Vintagestory.Client.ScreenManager.DoGameInitStage2()
   at Vintagestory.Client.GuiScreenLoadingGame.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
Crash written to file at "C:\Users\FERID\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

14.9.2022 15:15:20 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed

**Comment by Craluminum2413** [comment]
It looks like your processor doesn't support 3.3 OpenGL version.
I don't know what OpenGL version was used in 1.16, but I'm afraid that for 1.17 you need to buy nvidia or amd video card to play further. But I may be wrong

**Comment by Craluminum2413** [comment]
Yeah, I forgot to say that if you are on laptop, then you can't change video card, it is possible on desktop only

**Comment by TadjikX** [comment]
> Yeah, I forgot to say that if you are on laptop, then you can't change video card, it is possible on desktop only

It is okay but the question is, how i was able to play almost year ago, i mean literally i was able to play and chill.

**Comment by Craluminum2413** [comment]
I think @tyronx can answer that

**Comment by tyronx** [comment]
one of the updates raised the opengl requirements from 3.0 to 3.3, i believe. That was quite some time ago though.

**Comment by TadjikX** [comment]
> one of the updates raised the opengl requirements from 3.0 to 3.3, i believe. That was quite some time ago though.

yeah the moment when 1.16 stopped working was a whila ago
