### ISSUE TITLE
Ore deposit generation problems in world with WorldHeight>384

### ISSUE THREAD

**Issue by digital-r** [anegostudios/VintageStory-Issues#2193]
**Game Version:** 1.17.3 (any)  
**Platform:** Windows / Mac / Linux (any)   
**Modded:** No / Yes (No)  
**SP/MP:** Singleplayer / Multiplayer (Any)  

### Description
Due to semi-hardcoded values in /assets/survival/worldgen/geologicprovinces.json, most of ore deposits in sedimentary layers will never generated. Rock layer thickness defined as absolute value. While ore deposit generation based on relative values from world height. So, in most cases, sedimentary layer are too thin, for ore generation. As result: no borax, bituminous coal, anthracite, lapis, fluorite, phosphorite, kernite... And very small amount of lignite and galena in world. Marble deposits can be affected as well. 

### How to reproduce
1. Make a new survival world with height 576;
2. Examine ore distribution for any landmass with sedimentary layer.
3. No mineral ores found, compared to default world height.

### Expected behavior
Comparable (to default worldheight) amount of ores found in sedimentary layer.

### Screenshots
Have none ATM.

### Logs
No logs needed

Possible solution: Replace rock layer thickness in /assets/survival/worldgen/geologicprovinces.json from absolute values to percent from world height
```

**Comment by digital-r** [comment]
UPD: Tinkering with geologicprovinces.json give no results.
If ore use "disc-followsealevel" generator, then this ore will not generated in sedimentary layer.
"disc-followsurface" generator works, but with issues (not sure, is it oremap or oregen issue): most ores generate in shale rock. And i have not find any mineral ore in sandstone for world height=576.

**Comment by tyronx** [comment]
thanks for the report. I will make it scale the thickness with the world height. Will be in 1.17.4
