### ISSUE TITLE
Not possible to copy JSON in hitbox editor when there are dozens or hundreds of hitboxes

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2195]
**Game Version:** 1.17.3
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### How to reproduce
1. Add about 10 hitboxes to a block
2. In the game, try to change e.g. Hitbox 1
3. Press `copy JSON` values
4. it is impossible to copy them

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/190186416-bd0b8d1d-ea62-4f6b-a123-035bc51d3be9.png)

**Comment by tyronx** [comment]
thanks for the report, should be fixed in 1.17.4
