### ISSUE TITLE
1.5.2.1 Chest Funkyness

### ISSUE THREAD

**Issue by RainnMannx** [anegostudios/VintageStory-Issues#22]
Trying to open the chest on its south or east side is glitchy at edge of interaction.
North and west side seem ok, as soon as you can interact they are fine.
The south and east side open then close very quickly.
Chest position doesn't seem to matter. 
https://youtu.be/X3kcClxu7S8

**Comment by tyronx** [comment]
Thanks, fixed for 1.5.2.3
