### ISSUE TITLE
Cooking pot doesn't put in intended maxmium

### ISSUE THREAD

**Issue by ChrisAE123** [anegostudios/VintageStory-Issues#2201]
Game Version: 1.17.3
Platform: Windows 10
Modded: No
Singleplayer

When mousing over a cooking pot slot and pressing a number of your hotbar to switch the item into the pot, it doesn't respect its maximum. Say you press 1 to bring any item into the slot, instead of putting only 6 it puts the whole stack in. You can't cook anything over 6, it just makes it more annoying to cook meals.

**Comment by Craluminum2413** [comment]
This bug allows you to store 4 stacks of any item inside cooking pot
