### ISSUE TITLE
items when leaning against something go into floor block

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2203]
Version:** X.Y.Z    1 . 17 . 4
**Platform:** Windows / Mac / Linux (which?)       windows
**Modded:** No / Yes (which?)       yes
**SP/MP:** Singleplayer / Multiplayer (which?)       Singleplayer

### Description
Explain the issue you're running into.  The new update is having a visual glitch when I place an item to lean against a block the item is disappearing in floor block, the two items that are against the tree in the picture are a copper scythe and a flint hoe.  
![error with items leaning](https://user-images.githubusercontent.com/112742241/191365866-1dad383e-9952-413e-9c7b-4341a3dcbd0b.png)

### How to reproduce
1. Make a '....' place any item and lean against a block as shown in picture
2. Use it on '....' a did this on a tree and the floor is a grass block
3. It crashes / doesn't do the thing. it does not crash the game 

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.




```

**Comment by ruggbean** [comment]
Hello - here to add to this issue from a multiplayer perspective.

**Game Version:** 1.17.4
**Platform:** Windows
**Modded:** Yes (Carry Capacity, Zoom Button, Step Up, More Candles)
**SP/MP:** Multiplayer

### Description
As the OP explained, tools that are leaned up against the wall are being cut off by the floor block. The affected items in my first screenshot are two scythes, a shovel, and a falx.

This issue also seems to affect items that have already been placed, as can be seen in my second screenshot. The affected items are a pair of shears and an axe.

### Screenshots

![2022-09-21_19-40-12](https://user-images.githubusercontent.com/109896152/191646459-08576226-3e13-47c4-becc-2c56baf47b12.png)
![2022-09-21_19-46-54](https://user-images.githubusercontent.com/109896152/191647056-1588f326-1a52-44d0-a281-1b18ce9d790b.png)
