### ISSUE TITLE
Game doesn't like making food with Olives

### ISSUE THREAD

**Issue by Skrepon** [anegostudios/VintageStory-Issues#2205]
**Game Version:** 1.7.4
**Platform:** Windows 
**Modded:**  Yes   
**SP/MP:** Singleplayer  

### Description
I attempted to make Hefty Olive Stew and some Olive and Red Meat Stew. Crocks have been filled, but I can't fill the bowl with the contents.

### How to reproduce
1. I have tried Stew with 24 Olives and Stew with 12 Olives and 12 Red Meat.
2. Cooked and the cooking pots looked empty.
3. Picked the pot up and filled the crocks. Tried to fill a bowl from the Crocks, nothing happens.

### Expected behavior
I expected to get some food, lol.

### Screenshots

![2022-09-20_19-38-37](https://user-images.githubusercontent.com/112740001/191395472-c8054de4-673f-4aeb-bd4c-cd0fe93eda5e.png)

**Comment by RedramVS** [comment]
I've fixed all this except that the texture is still invisible in the stew pots and bowls.  I don't know how to make those work.

**Comment by RedramVS** [comment]
This is now fully fixed.
