### ISSUE TITLE
game crash without reason

### ISSUE THREAD

**Issue by nikatin61** [anegostudios/VintageStory-Issues#2206]
**Game Version:** 1.17.4
**Platform:** Windows 10
**Modded:** No
**SP/MP:** Singleplayer

### Description
the game just crashes without errors to the desktop, for no particular reason, it can crash at absolutely any moment except for the menu

### How to reproduce
start the game, create or enter an already existing world, just play and at some point it crashes

### Expected behavior
there should be no crashes, or at least it should write what caused the game to crash

### Screenshots
it's impossible to photograph, If you ask I can try to take a video

### Logs

[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/9615158/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9615160/client-main.txt)

**Comment by Craluminum2413** [comment]
Pirated version of the game is not supported
