### ISSUE TITLE
String not translated

### ISSUE THREAD

**Issue by Yota77** [anegostudios/VintageStory-Issues#2209]
**Game Version:** 1.17.4  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
The string {0} servings of {1} in {2} is not tranlsated .
The singular works.
I've tried in another language (France) same issue.

### How to reproduce
1. Cook a pot with multiple servings inside 
2. Put it on the ground
![porservings2](https://user-images.githubusercontent.com/70011570/191738889-bf9a950a-3255-4aa7-a26c-0d9fca6667d4.png)
![porservings3](https://user-images.githubusercontent.com/70011570/191738904-8aa6010a-4904-4d99-9756-bd1d2e4128e7.png)
![porservings](https://user-images.githubusercontent.com/70011570/191738919-4cf4dbe0-d324-4d7d-ba90-6bc8a0faff97.png)

**Comment by tyronx** [comment]
thanks for the report, will become translateable next release
