### ISSUE TITLE
Cannot sell skep

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2212]
**Game Version:** 1.17.4
**Platform:** Mint
**Modded:** No
**SP/MP:** Singleplayer survival

### Description
Cannot sell a skep to agricultural trader. Despite he has money and wants to buy one, impossible to put the skep on the required slot to sell. After this try, I succeded into selling him other wanted items, like bronze tools.

### Screenshots
![skep1](https://user-images.githubusercontent.com/84909583/191954140-86ebfde2-e9cb-4489-b848-78b4832216c4.png)

![skep2](https://user-images.githubusercontent.com/84909583/191954414-607c4406-e2de-4459-960e-fef13ec65b01.png)

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.18.2-rc.4, guess it was fixed
![image](https://github.com/anegostudios/VintageStory-Issues/assets/69315569/694ec105-1096-4f39-af8b-d710dca80b0f)
