### ISSUE TITLE
Pit kiln missing translation

### ISSUE THREAD

**Issue by Yota77** [anegostudios/VintageStory-Issues#2213]
**Game Version:** 1.17.4
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer

### Description
This string cannot be translated "Process Completed in xx.xx Hours". 
Seems that miss the string.

### How to reproduce
1. Make a Pit Klin
2. Put something to fire.
3. Completed the Pit Klin and fire it .

![No_string_pitklin](https://user-images.githubusercontent.com/70011570/192100489-1ebc557c-12f0-4764-bf72-a13012bb8971.png)

**Comment by Craluminum2413** [comment]
This is not vanilla string, but added by VSHUD mod
