### ISSUE TITLE
Bear unable to jump out of a small hollow

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2214]
**Game Version:** 1.17.4
**OS:** Mint 
**Modded:** No
**SP/MP:** Singleplayer survival  

### Description
Bears (brown bear and polar bear for sure, don't know for pandas and sun bears) are often unable to jump out of a small hollow, like in the following video.

### Screenshots

https://user-images.githubusercontent.com/84909583/192105680-8b3f0037-cad0-4f0c-873f-5b33acff8bd2.mov

**Comment by Craluminum2413** [comment]
Maybe this happens due to snow layers below the bear?

**Comment by tyronx** [comment]
thanks for the report, i was able to reproduce it. will be fixed next release
