### ISSUE TITLE
fruit tree state : missing fruit state (multiplayer)

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2216]
**Game Version:** 1.17.4
**Platform:** Mint  
**Modded:** No  
**SP/MP:** Multiplayer  open to Internet  

### Description
When playing "open to internet" mode, the client side is lacking informations on the fruits state when looking at a fruit tree.
The server side information is complete ("fresh fruit for about X days"), but the client side has no information about it.

### Screenshots
On server side : 
![fruits-on-host](https://user-images.githubusercontent.com/84909583/192161369-934055f2-3ccd-4507-a743-d12f1172380a.png)

On client side : 
![fruits-on-client](https://user-images.githubusercontent.com/84909583/192161376-07e45add-d8b7-4ae7-9768-f94e977b9116.png)

**Comment by Barhandar** [comment]
Also happens in dedicated-server multiplayer, information showing/not showing on the client side is intermittent; additionally, the trees are supposed (that's how they worked in 1.16) to change state entire tree at a time, yet I've encountered multiple trees that simultaneously had empty, flowering, fruiting and ripe leaf blocks at same time.

**Comment by Barhandar** [comment]
On further examination, the tree state is only visible to client on freshly-grown leaves - after some time they lose the tooltip. Considering the messed-up fruiting, it seems like the tree data is being lost.

**Comment by tyronx** [comment]
oh yea, looks like i completely broke fruit trees in one of the 1.17 stable releases. I'll push a 1.17.x fix for it. thanks for the report
