### ISSUE TITLE
Clay things when put for firing use tooltips from baking

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#222]
Clay things, e.g. flower pot ot blue clay brick
when put into firepit for firing
use tooltips for baking (instead of tooltips for firing):
 "Baking Temperature: {0} °C"  (internal game key: smeltpoint-bake)
and
"Bakes into {0}x {1}" (internal game key: smeltdesc-bake-singular)

Which looks inaccurate in game, especially in other languages, e.g. Russian.
They should use their own tooltips (and therefore keys) for firing. As I understand, tooltips for firing are currently absent in game.
Most likely other clay things have the same issue. And maybe other tooltips are also incorrectly used.

**Comment by tyronx** [comment]
Oh yea, i think i just simplify all of these into: "Turns into {0} when heated to {1} degrees"

**Comment by Heptagon-ru** [comment]
Well, imho this will make the game poorer in quality. It is very pleasant to read corresponding terms/verbs for different types of stuff. Too much abstraction is not good, game might feel less alive.

**Comment by tatsu011** [comment]
As of today I've added some placeholder tooltip settings for specifically firing things.  They do need to be implemented in some of the clay related recipes, but the tooltips are there, and so is the code to support the tooltips. Marking this as done and should be in the next big API doc update.
