### ISSUE TITLE
Snow block is not secure against mobs

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2221]
**Game Version:** 1.17.4
**Platform:** Mint   
**Modded:** No  
**SP/MP:** Singleplayer  

### Description
Unlike other material blocks, snow block is not secure against mobs attacks.

### How to reproduce
1. Build the three cabins as shown on the picture.
2. Spread a bunch of cool guys, like nightmare drifters, all around the cabins.
3. Stay in the green cabin. You're safe.
4. Stay in the yellow cabin. Only one upper glass block has been replaced by a snow block. You're safe. You can sit up (G) and get up, nothing happens.
5. Stay in the red cabin. Only one bottom glass block has been replaced by a snow block. Now the interesting things begins.
From the tests I made, it seems that as long as you stand up, nothing happens. BUT drifters outside start to throw rocks at you (rocks that don't hit you). They hit themselves with their rocks and begin to fight each other. But you're safe.
Now sit up. You will soon be killed.

### Screenshots

![2022-09-27_18-35-16](https://user-images.githubusercontent.com/84909583/192586826-098ab07f-8ffe-4f51-8ace-41f84a742ad3.png)

**Comment by tyronx** [comment]
i'm not able to reproduce this with a snow block  from creative mode, but even if, i don't think this is an issue - snow is not exactly a very solid material
