### ISSUE TITLE
install - no .local/share/applications/ - no .desktop

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2223]
**Game Version:** 1.17.4
**Platform:** Linux (KDE neon 20.04 5.25 )
**Modded:** No
**SP/MP:** Singleplayer / Multiplayer

### Description
If the directory .local/share/applications/ does not exist, then the .desktop link will not be created

### How to reproduce
1. Install new KDE Neon system (or remove the directory .local/share/applications/)
2. Install Vs with install.sh
3. The game is installed, but no desktop link is created - no menu entry

### Expected behavior
If the applications directory does not exist, then it should be created.

**Comment by tyronx** [comment]
i'm not too well versed with bash script, happen to have a few lines of bash code to address this case?

**Comment by Nyuhnyash** [comment]
> i'm not too well versed with bash script, happen to have a few lines of bash code to address this case?

```bash
applications_dir=$HOME/.local/share/applications
if [ ! -d "$applications_dir" ]; then
        mkdir -p "$applications_dir"
fi
```

**Comment by tyronx** [comment]
thanks! will be the next relesae
