### ISSUE TITLE
Stackrandomiser spawning a stack of 0 copper ingots / 0 Sticks

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2224]
**Game Version:** 1.17.4
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Stackrandomiser has a chance to spawn a stack of 0 copper ingots pls fix it

Fix:
Vintagestory\assets\survival\itemtypes\meta

Line 343:
{ type: "item", code: "ingot-copper", quantity: { avg: 1.5, var: 1.5 }, chance: 32 },

change this to somthing like

{ type: "item", code: "ingot-copper", quantity: { avg: 2.5, var: 1.5 }, chance: 32 },

![image](https://user-images.githubusercontent.com/100879715/193132470-5e2e8020-f1c4-40c4-b1bc-0c7bd84c425b.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release

**Comment by AreYSerious** [comment]
![image](https://user-images.githubusercontent.com/100879715/193652083-7750e0f8-2d65-42ba-a4f1-2455d7a82b54.png)
I check yesterday for more issues like that and it seems like we got another one here. 
Sticks 0-16 might have a chance to spawn as a 0 stack

**Comment by AreYSerious** [comment]
I checked all randomizers now the rest seems fine.
@Craluminum2413 could you reopen this issue or should i make a new one
ty

**Comment by tyronx** [comment]
ok, got this one covered as well now
