### ISSUE TITLE
LootVessels hardcoded droptables

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2225]
LootVessels have hardcoded droptables.

### Description
https://github.com/anegostudios/vssurvivalmod/blob/master/Block/BlockLootVessel.cs
LootVessels Loottables are not available for content mods aka in the jsons.

**Comment by Craluminum2413** [comment]
You can always code your own loot vessels

**Comment by AreYSerious** [comment]
They should be available for content only mods

Stackrandomisers for example are.

**Comment by AreYSerious** [comment]
Fixed by Tyron in the livestream :P prob next update
