### ISSUE TITLE
Recipe duplication occurring likely due to mods not talking together nicely

### ISSUE THREAD

**Issue by josyph** [anegostudios/VintageStory-Issues#2226]
**Game Version:** 
1.17.4
Platform: Windows 10
Modded: Yes--heavily
SP/MP: Singleplayer

**Description:**
Recipe duplication occurring likely due to mods not talking together nicely. Oddly, this seems to be occurring in multiple places including clay recipes, flint recipes, metalworking recipes.  I have personally put together a collection of mods which, as you will note in the picture, produce three copies of every single vanilla and modded recipe.  I lack programming knowledge so it could just be an issue with the mods. It's not game breaking, but it does make it difficult to select certain recipes because the recipe list goes off screen sometimes.

**How to reproduce**
Load up a bunch of mods that significantly add to recipes. Some that come to mind (and I could upload a modlist if needed) are QPTech, Roadworks, Cellar Door, ZEEkea, Stone Quarry, etc.)

**Screenshots:**
![VS clay ingot recipe duplication](https://user-images.githubusercontent.com/111156789/193148543-6a99cf88-7d41-49b2-9ac3-8050a22eb0dc.png)
![VS clay recipe duplication](https://user-images.githubusercontent.com/111156789/193148544-4eba9520-d4c7-4736-a12b-14daa8c9daca.png)

**Comment by Craluminum2413** [comment]
Upload a mod list, it is a modding only issue that can be "easily" avoided while making a mod

**Comment by josyph** [comment]
2x Armor Durability, Anvil Metal Recovery+, Campaign Cartographer, auto close, Autosifter, Better Crates, BetterRuins, calendar, CarryCapacity, Cellar Door, Ceramos, Chess, Coinage, Composter, Extra Overlays, Flexible Tools, From Golden Combs, Glassmaking, Hanging Oil Lamps, HUD Clock, Instruments, Just Light Jars, Lichen, Medieval Expansion, Meteoric Expansion, The NIght Watcher, Player Corpse, ProspectorInfo, QPTECH, Relight Torches, Road Works, Ruin Variants, Simplealchemy, Useful Stuff Sluice Fork, Smokey Chimneys, Sortable Storage, Stone Quarry, Teleportation Runes, Temporal Lamp, Th3Dillis survival expansion, Visible Ore, VS Quest, VS Village, Xlib, Blood, XSkills, Zeekea

All mods are up to date to latest version, although a number of them do not indicate they are for 1.17.4

**Comment by Craluminum2413** [comment]
Have you tried to load mods one by one to see which ones are duplicating the recipes?

To help save you time while you're looking for such a mod, you can open a mod zip and search for `src` folder or `dll` file, if it doesn't have any of them, then you can skip it and move on

**Comment by josyph** [comment]
I've isolated Th3Dillis survival expansion as one of the offending mods and I have my duplication issue down to just two--a much more manageable problem.  I will continue looking for the other one.

**Comment by Th3Dilli** [comment]
@josyph that bug is now fixed in the latest version of the mod

**Comment by tyronx** [comment]
closing, not a vanilla bug
