### ISSUE TITLE
World generation bug with underground lakes

### ISSUE THREAD

**Issue by CapAntonWalker** [anegostudios/VintageStory-Issues#2233]
**Game Version:** 1.17.6  
**Platform:** Windows   
**Modded:** No
**SP/MP:** Singleplayer

### Description
While minining i stunble across a cave wich looked like an small undeground lake but with stone in place of water... and after some diging around posible water spots I find them incased in stone. That`s a deffenotly is related to new water layer system.

### How to reproduce
Don`t know how exactly reproduce. May be try to spawn structure, which represents a small underground lake, inside big stone bloob.

### Expected behavior
It is obvious. Water.

### Screenshots
![2022-10-07_00-04-21](https://user-images.githubusercontent.com/94701154/194419231-7f6e0b61-bff3-4cc2-b344-8b6f14c2f855.png)
That`s is a overall cave.

![2022-10-06_23-49-14](https://user-images.githubusercontent.com/94701154/194418065-6a0302b1-3b14-42f4-b9b7-52f24d07ec9e.png)
That's close look.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
