### ISSUE TITLE
Ebony and Purpleheart logs give 3 firewood instead of 4

### ISSUE THREAD

**Issue by Barhandar** [anegostudios/VintageStory-Issues#2236]
**Game Version:** 1.17
**Platform:** Any
**Modded:** No
**SP/MP:** Any

### Description
Ebony, despite having highest burn length as a log (110 seconds), and purpleheart (72 seconds, higher than pine), give 3 firewood instead of 4 because they're part of the kapok firewood recipe.  
As described in #235 that recipe exists because worldgen kapok trees generate a lot of log blocks, so firewood quantity was reduced to compensate. However, not only the other two generate far fewer logs and far fewer _trees_ on worldgen, they also take _much_ longer to grow from seed than all other woods save redwood, due to their special state, and so shouldn't be giving less firewood than common oak or even redwood itself.

### How to reproduce
Obtain ebony or purpleheart logs and an axe, put axe above log in crafting grid, observe the output.

### Expected behavior
Ebony and purpleheart giving at least 4 firewood.

**Comment by Craluminum2413** [comment]
This is a suggestion, all suggestions should be on the forums https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by Barhandar** [comment]
Those woods giving 3 firewood is an error and fixing them is not a suggestion.

**Comment by Craluminum2413** [comment]
It looks like it is intended, because there is a separate recipe that allows to craft only 3 firewood from `kapok`, `purpleheart` and `ebony`.
