### ISSUE TITLE
Food in sealed crocks spoiling abnormally fast

### ISSUE THREAD

**Issue by mcthrill** [anegostudios/VintageStory-Issues#2245]
**Game Version:** 1.17.8  
**Platform:** Windows
**Modded:** Yes - Workbench Extended, Carry Capacity, Farmland Drops Soil, HUD Clock, Prospector Info
**SP/MP:** Singleplayer  

### Description
Upon updating to 1.17.8, all food in sealed crocks started spoiling abnormally fast. The tooltip display still said items had multiple days before spoilage, but the days count down incredibly fast. Upon starting to spoil, spoilage time until completely rotten also moves at an increased rate. Mousing over the item in inventory, you can see the food dropping 4-5 saturation points every few seconds. Crocks that still have more than a day showing before spoiling are ~15% spoiled by sundown of the same day when taking them out of the cellar. Uncooked food and meals in cooking pots are not affected, just food in crocks.

### How to reproduce
1. Cook a meal in a cooking pot
2. put it in a crock and seal it
3. Once the temperature cools enough to allow the spoilage timer to show, the number of days will appear accurate but count down faster than normal.

### Expected behavior
Time displayed in tooltip should be accurate to how long it actually takes for food to spoil.

**Comment by FreeMoonshadow** [comment]
Can confirm an issue 
I have lost over 30 crocks of food from an established cellar from shelves and also in standard storage vessels
Its only affecting crocks  - raw foods, pies, wine and salted items do not seem affected
Mods used - Hud Clock, Campaign Cartographer, Better Crates, Bricklayers,Carry Capacity, expanded matter, Extra chests, Medieval Expansion, Workbench Expansion.
vs crocks					
					3rd sept
					Days
new pot	New crock	hefty onion	cellar shelf	Sealed	90
new pot	New crock	hefty onion	cellar shelf	unsealed	10
new pot	old crock	hefty onion	cellar shelf	Sealed	130
new pot	old crock	hefty onion	cellar shelf	unsealed	15
old pot	old crock	hefty onion	cellar shelf	Sealed	130
old pot	old crock	hefty onion	cellar shelf	unsealed	15
new pot	New crock	hefty onion	kitchen floor	Sealed	27
new pot	New crock	hefty onion	kitchen floor	unsealed	3
old pot	old crock	hefty onion	kitchen floor	Sealed	43
old pot	old crock	hefty onion	kitchen floor	unsealed	5

**Comment by tyronx** [comment]
hm, I just made red met stea with boiled carrots and sealed it, shelf tells me fresh for 2.1 years. Then did `/time add 10 day` and get fresh for 2 years, with looks correct to me. 

This is on 1.17.8 in a world on default settings.

**Comment by tyronx** [comment]
You all have mods enabled. Try without mods perhaps?

**Comment by tyronx** [comment]
oh, never mind, i see the problem. Sealing a crock is non-functional.

**Comment by FreeMoonshadow** [comment]
Hi Tyron
Did you take it off the shelf by any chance. That seems to be the trigger
for me at least. It's in the screen prints.  Others seem to have been able
to watch it tick down

Re mods yes I have mods installed. But the folks with this issue seem to
have different mods.

I can redo that last test with the mods uninstalled and see.

Regards Jo aka Moonshadow

**Comment by tyronx** [comment]
aye thanks for the reports, i got this fixed, i'll release 1.17.9 for it very soon.
