### ISSUE TITLE
Underground ruin schematic containing no blocks

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2246]
**Game Version:** 1.17.8
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
The file `dormintory2-nt2.json` found in `assets\survival\worldgen\schematics\underground\livingquarters` contains no blocks. Might been exported incorrectly from the creator ^^.

### How to reproduce
Try importing the file `dormintory2-nt2.json` found in `assets\survival\worldgen\schematics\underground\livingquarters`

### Expected behavior
Contain actual Blocks ^^

### Screenshots
![image](https://user-images.githubusercontent.com/100879715/196272665-f91e4335-f9e1-42da-bcb2-8f20acb751b1.png)

**Comment by Craluminum2413** [comment]
Looks like this structure is not used

**Comment by AreYSerious** [comment]
True mb
