### ISSUE TITLE
Chiseling Stairs - Cannot Add Material, Only Remove

### ISSUE THREAD

**Issue by kurazarrh** [anegostudios/VintageStory-Issues#2248]
**Game Version:** 1.17.8
**Platform:** Windows  
**Modded:** No
**SP/MP:** Singleplayer

### Description
When chiseling a stair block, it is not possible to add material. It is only possible to remove material, mirror, and rotate the block. This includes if the user adds additional materials to the chiseled block, regardless of the new material's size or composition. This started happening at the same time as the new chiseling restriction was put in place for half-slabs.

### How to reproduce
1. Place a stair block.
2. Put a hammer in the off-hand and chisel in the main hand.
3. Right-click the stair block to turn it into a chiseled block.
4. Using the F menu, put the chisel into a material editing mode (easiest with the largest size).
5. Left-click on a part of the stair block to remove material.
6. Right-click in the space where material was removed in order to add it.
7. The material is not added.

### Expected behavior
It should be possible to add material to the stair block, at least up to the block's original geometry.

**Comment by ruggbean** [comment]
**Game Version**: 1.17.8 and 1.17.9
**Platform**: Windows
**Modded**: Yes (Carry Capacity, Zoom Button, Step Up, More Candles, Better Backpacks, Stackables)
**SP/MP**: Multiplayer

### Description
Same as above but with slabs as well as stairs. Cannot add to stairs at all, can only add to slabs back to the original shape.

### Screenshots

A [video](https://www.youtube.com/watch?v=Q031EmaacAY) to my attempts to chisel the slab, the plank, and the stairs

**Comment by kurazarrh** [comment]
@ruggbean The change to slabs was intentional and was listed as a fix in 1.17.7. I'm not a fan of this change (including if you add material from a full block, it is still stuck as a slab forever), but that may be intentional.

**Comment by ruggbean** [comment]
@kurazarrh Thank you for bringing that to my attention. I thought that I was more thorough in scanning the update notes but I was mistaken.

**Comment by tels-git** [comment]
This also affects stairs from bricklayers, and as stair blocks have slightly different textures than slabs/blocks, really restricts the chiseling possibilities when it comes to stone/brick textures.

I disagree with this being a medium priority as it breaks many creative uses for chiselers. And it can't be that hard to fix, actually, it worked before just fine.

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in 1.18
