### ISSUE TITLE
Losing molten metal

### ISSUE THREAD

**Issue by bitcynth** [anegostudios/VintageStory-Issues#225]
Steps to reproduce:
- Melt metal (I used copper)
- Pour some into a mold (not sure if this is a required step)
- Put the crucible down on the ground
- Break the crucible
- It is now empty, although it may still show some but you can't pour it and if you put it in a fire it goes away.

Version: 1.7.8

**Comment by tyronx** [comment]
Thanks for the report. This is now fixed for pre.6
