### ISSUE TITLE
Handbook pause allows inventory interaction

### ISSUE THREAD

**Issue by JustForVS** [anegostudios/VintageStory-Issues#2255]
Game Version: 1.17.8
Platform: Windows 10
Modded: Yes (hudclock-2.8.0, ProspectorInfo-4.1.1, singlepause-1.0.3, ZoomButton1.3.0)
SP/MP: Singleplayer

### Description
(Not sure, if you can call this a bug but it allows some kind of cheating):
When opening the handbook you can still interact with your char and inventory to e.g. equip or change amor or a weapon or craft something.

### How to reproduce
1.Press <h> to open handbook
2. Klick somewhere outside the search bar
3. Press <c> and/or <e> to access and alter invenory and char

### Expected behavior
No interaction with game elements except the handbook

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment]
It is not a bug because as far as I know, all actions related to inventory are purely server side.
The client simply displays what the server want to send to it
