### ISSUE TITLE
Sanity Decreasing Randomly Above Ground

### ISSUE THREAD

**Issue by Davis1055** [anegostudios/VintageStory-Issues#2259]
**Game Version:** 1.17.8 
**Platform:** Windows 11
**Modded:** Yes - AlphaWeaponsPack, ACulinaryArtillary, Ancient Tools, AnMiTech, BetterRuins, Bullseye, cellardoor, Ceramos, ExpandedFoods, FromGoldenCombs,MedievalExpansion, OneStick, PrimitiveSurvival, Re-Smeltables Light, roadworks, StoneQuarry. 
**SP/MP:** Multiplayer only
### Description
Randomly, I will start losing sanity and the scary music will play while I'm above ground. This occurs typically in calm rift activity areas as well. My sanity will continue to decrease until it hits 0% and I start taking damage. There are no rifts around in the area (I have 300 hrs on this game, so I'm quite familiar with what to look for). The only way to fix this, is to kill yourself. 

### How to reproduce
1. I have never been able to reproduce this, it just happens, sometimes not for days, sometimes it happens a few days in a row. 

### Expected behavior
I expect in a calm rift activity area, while above ground, that I should not be losing sanity. 

### Screenshots
https://imgur.com/a/HlGxRey

### Logs
This does not crash the game!

**Comment by Craluminum2413** [comment]
If I remember correctly, temporal stability is not linked to current rift activity

**Comment by Barhandar** [comment]
Yes, temporal stability isn't related to rift activity (and the latter isn't local), only your actual location and whether there's a storm going.

There are areas that are normally more or less stable both above and below ground; if you consistently experience decreasing stability in a specific place, then you've found one of the unstable areas. Underground is also not necessarily unstable; in one of my mines I can stand on the mantle without stability decreasing.

**Comment by Craluminum2413** [comment]
I close it as `won't fix`
