### ISSUE TITLE
vintagestory

### ISSUE THREAD

**Issue by EmmeDi99** [anegostudios/VintageStory-Issues#2266]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable)
25/10/2022 22:59:22: Critical error occurred in the following mod: tradeomat@1.6.3
Loaded Mods: bettercrates@1.5.2, Ceramos@0.2.2, fancysky@1.0.5, HumanSkinTones@0.0.3, reducedarmornegatives@1.0.4, necessaries@1.1.3, stackables@2.0.5, tradeomat@1.6.3, game@1.17.9, vshud@2.1.0, zoombuttonreborn@1.3.0, carrycapacity@0.6.5, extraoverlays@1.1.1, fromgoldencombs@1.3.15, hudclock@2.8.0, medievalexpansion@3.8.1, prospectorinfo@4.1.1, tprunes@1.0.5, creative@1.17.9, survival@1.17.9, workbenchexpansion@1.5.1, xlib@0.6.10, accessibilitytweaks@3.0.4, xskills@0.6.11
System.ArgumentException: Fatal: Trying to render a disposed mesh
   in Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef) in VintagestoryLib\Client\ClientPlatform\GLDraw.cs:riga 53
   in tradeomat.src.TradeomatBlock.DealRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   in Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:riga 199
   in Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:riga 1176
   in Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:riga 1259
   in Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:riga 1104
   in Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:riga 125
   in Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:riga 680
   in Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:riga 624
   in Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:riga 131
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:riga 479
   in OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:riga 454
   in OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:riga 375
   in Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   in Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:riga 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25/10/2022 22:59:29, Site = , Source = Application Error, Message = Nome dell'applicazione che ha generato l'errore: Vintagestory.exe, versione: 1.17.9.0, timestamp: 0x63501532
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.19041.2130, timestamp: 0xb0fac6c9
Codice eccezione: 0xc000041d
Offset errore 0x000000000002cd29
ID processo che ha generato l'errore: 0x2418
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d8e8b415f14480
Percorso dell'applicazione che ha generato l'errore: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\System32\KERNELBASE.dll
ID segnalazione: e0e98ad9-15b5-4e70-80ba-8cf9cafcdb77
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:  }
--------------
{ TimeGenerated = 25/10/2022 22:59:24, Site = , Source = Application Error, Message = Nome dell'applicazione che ha generato l'errore: Vintagestory.exe, versione: 1.17.9.0, timestamp: 0x63501532
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.19041.2130, timestamp: 0xb0fac6c9
Codice eccezione: 0xc0020001
Offset errore 0x000000000002cd29
ID processo che ha generato l'errore: 0x2418
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d8e8b415f14480
Percorso dell'applicazione che ha generato l'errore: C:\Users\User\AppData\Roaming\Vintagestory\Vintagestory.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\System32\KERNELBASE.dll
ID segnalazione: 864b4bbf-6a56-451f-ae7f-42d9ecea0d51
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:  }
--------------
{ TimeGenerated = 25/10/2022 22:59:22, Site = , Source = .NET Runtime, Message = Applicazione: Vintagestory.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: codice eccezione c0020001, indirizzo eccezione 00007FFEA9E8CD29
Stack:
 }

**Comment by Craluminum2413** [comment]
Crash is caused by Tradeomat mod
