### ISSUE TITLE
Disabling/Enabling of patches

### ISSUE THREAD

**Issue by tels-git** [anegostudios/VintageStory-Issues#2280]
### Game Version

1.17.9

### Description

It seems its not possible to (temporarily/permanenly) disable patches from JSON.

#### Use case

The mod Expanded Matter adds some new items and it is nec. to patch vanilla items to produce these new items via conversion.

By default, all new items/blocks in EM are disabled with `enabled: false` and they are later enabled via a small patch from the using mod. However, the patches to patch vanilla items are still running and throw warnings about the disabled items like this:

```
[Warning] Failed resolving a blocks itemdrop or smeltedstack with code em:ash-organic-plant in Combustible props for Item game:stick
```

Trying to add one of these:
```
"enabled": false,
```
or:
```
"disabled": true,
```
to the patch file does not help, the patch is still tried to be applied, but then emits a warning.

#### What should happen:

A patch like this:

```
  {
    "op": "replace",
    "enabled": false,
    "path": "/combustibleProps/burnDurationNotExisting",
    "value": 16,
    "file": "game:blocktypes/plant/hay.json",
    "side": "Server"
  },
```
should not run (and thus not emit warnings) unless the "enabled: false" is patched to true.

### How to reproduce

Write a patch producing a warning or error and try to disable it.

**Comment by Craluminum2413** [comment]
This is a suggestion
https://www.vintagestory.at/forums/forum/5-suggestions/
