### ISSUE TITLE
New install on Ubuntu 22 and the game will crash at start

### ISSUE THREAD

**Issue by Defcon2600** [anegostudios/VintageStory-Issues#2286]
### Platform

Linux

### SP/MP

Singleplayer

### Description

Just installed the game and click the icon to run it and get "Vintage Story has crashed. "
Her is my install of the name game 
lucard@USHA:~/Games/vs_archive_1.17.9/vintagestory$ ./install.sh 
lucard@USHA:~/Games/vs_archive_1.17.9/vintagestory$ mono --version
Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:35:00 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
lucard@USHA:~/Games/vs_archive_1.17.9/vintagestory$ 

Install game into /home/lucard/ApplicationData/vs_archive_1 (data into /home/lucard/.config/VintagestoryData)
Create NewDir ./backup
ls: cannot access '/home/lucard/ApplicationData/vs_archive_1.*': No such file or directory
Cleanup
Move AppDir
Create MenuStarter & DesktopStarter
Create LowercaseAlias for REF-50p noise.png
Create LowercaseAlias for REF.png
Create LowercaseAlias for great-steppe-boots-L.png
Create LowercaseAlias for great-steppe-boots-R.png
Create LowercaseAlias for mech-helper WIP.json
Create LowercaseAlias for Lora-Bold.ttf
Create LowercaseAlias for Montserrat-Bold.ttf
Create LowercaseAlias for Lora-BoldItalic.ttf
Create LowercaseAlias for Montserrat-Regular.ttf
Create LowercaseAlias for OFL-Montserrat.txt
Create LowercaseAlias for OFL-Lora.txt
Create LowercaseAlias for Montserrat-Italic.ttf
Create LowercaseAlias for Lora-Italic.ttflucard@USHA:~/Games/vs_archive_1.17.9/vintagestory$ mono --version
Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:35:00 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
lucard@USHA:~/Games/vs_archive_1.17.9/vintagestory$ 

Create LowercaseAlias for Lora-Regular.ttf
Install complete. If the desktop icon does not work, you can still run the game by executing 'mono VintageStory.exe'. If the game has problems connecting to the auth server, please run 'sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt'

lucard@USHA:~/Games/vs_archive_1.17.9/vintagestory$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

### How to reproduce

1) Click the desktop icon to run

### Screenshots

![Screenshot from 2022-11-11 23-31-19](https://user-images.githubusercontent.com/39910898/201457168-0a9bb081-ebbd-4fec-b4ff-6d0569a33212.png)

### Logs

Running on 64 bit Linux with 31 GB. 
Game Version: v1.17.9 (Stable)
11/11/2022 11:24:01 PM: Critical error occurred
Loaded Mods: 
System.DllNotFoundException: libopenal.so.1 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.AL.GetStringPrivate(OpenTK.Audio.OpenAL.ALGetString)
  at OpenTK.Audio.OpenAL.AL.Get (OpenTK.Audio.OpenAL.ALGetString param) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos () [0x000e9] in <f8e7e0ea709348ba8693d95fd255ff41>:0 
  at Vintagestory.Client.ClientProgram.Start (Vintagestory.Client.ClientProgramArgs args, System.String[] rawArgs) [0x00391] in <fd9d0c679a80472ab783dcb948963ece>:0 
  at Vintagestory.Client.ClientProgram+<>c__DisplayClass14_0.<.ctor>b__0 () [0x00000] in <fd9d0c679a80472ab783dcb948963ece>:0 
  at Vintagestory.ClientNative.CrashReporter.Start (System.Threading.ThreadStart start) [0x00007] in <f8e7e0ea709348ba8693d95fd255ff41>:0

**Comment by tyronx** [comment]
Looks to me like openal is not installed.

**Comment by Th3Dilli** [comment]
this should be fixed since 1.18.8, since with that version we ship libopenal with the game
