### ISSUE TITLE
Player's nutrition levels decrease permanently

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#229]
1.7.8, public test server
I have noticed that my nutrition levels in general did decrease permanently. I.e. I can't restore them back to approximately 1/2 of each bar.
Idk how this happened.
I did not die for a long time, did eat various foods, did sleep a lot to push cabbage to grow.
![2018-11-13_10-13-53](https://user-images.githubusercontent.com/25122345/48396958-3d224200-e72d-11e8-8727-d5c03917644b.png)

**Comment by tyronx** [comment]
Its best to eat wholesome cooked foods. Also version 1.8 should make it easier to reach full bars. Please reopen if it's still a major issue in 1.8
