### ISSUE TITLE
entidades invisibles 

### ISSUE THREAD

**Issue by j0s3d4ni3l** [anegostudios/VintageStory-Issues#2296]
### Game Version

v1.17.6

### Platform

Windows

### Description

en el juego lo que son las criaturas me aparecen invisibles y no me permiten verlas no pueso saber si adelante mio hay un lobo, un herrante, o un oso si alguien sabe como solucionarlo por favor ayudeme 

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #2277
