### ISSUE TITLE
Liquid-only meals do not function

### ISSUE THREAD

**Issue by l33tmaan** [anegostudios/VintageStory-Issues#2298]
### Game Version

1.17.9

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

There is an issue with the meal system where it cannot output a meal unless there is a non-liquid item in one of the input slots. This isn't currently a 'bug', but more of a limitation of the system. 

### How to reproduce

An easy way to reproduce this is to download Expanded Foods, go into the creative inventory, then spawn Liquid Chicken Egg into your inventory. Then add 0.2 L into one slot of the cooking pot in a firepit, like making any normal meal. Spawn in some Lard then add 0.1 L into another slot of the cooking pot. Finally, spawn in some carrots or salt or a cheese slice. Once you add the non-liquid item, the meal suddenly starts working.

According to my code here, the only MANDATORY item is Liquid Chicken Egg. Everything else in the meal is optional:
https://github.com/l33tmaan/EFRecipes/blob/master/EFRecipes/assets/game/patches/scrambledeggsrecipe.json

As I understand it, another limitation of the meal system is that it requires a minimum of 2 input slots to be filled in order to result in an output.  It looks like you can go over that and require a minimum of 3 or 4 input slots to be filled, but being able to just require 1 input slot so you can "cook" a single liquid into a meal would be nice.

However, the main issue is that it should still cook into a meal if 2 input slots are filled, regardless of its liquid or solid state.

### Screenshots

![image](https://user-images.githubusercontent.com/89751315/204424146-b2a2415a-21ef-40f5-ae01-1c55ac56cc53.png)
![image](https://user-images.githubusercontent.com/89751315/204424199-a0fbf4df-3480-4431-a40e-42f8a8f48580.png)
![image](https://user-images.githubusercontent.com/89751315/204424233-43ef01e6-b8f4-4df4-9d73-a738f526a047.png)

### Logs

```Log```

**Comment by Pbprovost** [comment]
This is still occurring in 1.20.pre.11 and affects the new non-food cooking recipes. The recipes show up in the handbook, but wont produce items if there are only liquid ingredients.

**Comment by pizza2004** [comment]
Fixed in next release.

**Comment by Craluminum2413** [comment]
Fixed by https://github.com/anegostudios/vssurvivalmod/pull/90
