### ISSUE TITLE
Missing translation lines

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#230]
1.7.8 is missing some translation lines, e.g. because they are hardcoded in English.

- [x] 1. Some words in dynamic meal name, e.g. soup, with, stew, garnish - in GetNameForIngredients()
Altho with the dynamic meal names it may be hard to support them in languages like Russian, because word suffixes vary a lot depending from grammatical case. I still haven't investigated if it is possible to do a good translation.
- [x] 2. Journal entries.
- [x] 3. Probably clay recipes should use "firing" terminology instead of "baking", which is currently shared with baking bread. Described in #222
- [x] 4. While composing a cooking meal in a claypot interface in the firepit, it says "Will create 1 serving of ...".
No translations for "Will create", "serving of".
- [x] 5. At least for soups, when none of ingredients was recognized as a main one, the description has an extra space before "soup".
- [x] 6. Porridge section has Lang.Get(" with mashed {0} as well as sprinkled {1}", ... ), but translation has no entries with "mashed" or "sprinkled".
- [x] 7. No translations for Required Nutrient, Growth Speed in soil infobox.
- [x] 8. No translation for "lining" for lanterns. Maybe for lantern materials too, not sure.
- [x] 9. "I am not tired enough to sleep" notification in chat window. Ofc the chat window must start support Russian characters.
- [x] 10. Character's nutrition window: Nutrition, Protein, Fruit, and maybe others.
- [x] 11. Burn temperature, Burn duration in wooden items infobox.
- [x] 12. Attack power, Attack damage for swords items.
- [x] 13. 1 blunt damage when thrown - in stone item infobox.
- [x] 14. 3.5 piercing damage when thrown - in spear item infobox
- [x] 15. Durability - for tools as items
- [x] 16. Material: ceramic - both words, for bowls, planterns, ... item infoboxes
- [x] 17. Light absorption - for plantern item infobox
- [x] 18. liters - in wooden bucket infobox
- [x] 19. Some slabs are named using "slab", some "slabs", some "Slab". Plural is used for mudbrick, clay brick, stone brick ones.

Created a separate #231 to describe the general problem with dynamic meal descriptions.

**Comment by Heptagon-ru** [comment]
Added item 3 about baking->firing for clay recipes

**Comment by tatsu011** [comment]
Converted to a list.  Will check off as completed as I get to it.

**Comment by tatsu011** [comment]
Journal translations are actually a bit more complicated than other issues on the list and deserved it's own issue.  See #237 for information on what needs to be done.  Marking this done for now.
