### ISSUE TITLE
Game crashes in the same place 4 times

### ISSUE THREAD

**Issue by IamBBard** [anegostudios/VintageStory-Issues#2304]
i tried to reinstall game.
The is crash log below.

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.9 (Stable)
04.12.2022 21:55:56: Critical error occurred
Loaded Mods: game@1.17.9, creative@1.17.9, survival@1.17.9
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) в VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:строка 208
   в Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() в VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:строка 250
   в Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() в VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:строка 236
   в Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) в VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:строка 386
   в Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) в VintagestoryLib\Client\Model\ClientChunk.cs:строка 422
   в Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) в VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:строка 817
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) в VintagestoryLib\Client\ClientMain.cs:строка 1138
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) в VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:строка 123
   в Vintagestory.Client.ScreenManager.Render(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 678
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 622
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 124
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 476
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 452
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

**Comment by Craluminum2413** [comment]
Duplicate of #2102
