### ISSUE TITLE
Translatable dynamic meal descriptions

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#231]
In Russian (I am not a linguist and can be wrong in details and grammatical definitions),
1.  Adverbs and adjectives which qualify main noun,  change their form depending of noun's grammatical gender, quantity, ...
E.g.
*hearty cabbage soup* will be *syt**nuy** kapust**nuy** soop*, but 
*hearty cabbage porridge* will be *syt**naya** kapust**naya** kasha*, 
because *soup* is masculine, but *porridge* is feminine.
Ofc, there is no cabbage porridge, but just for an example.
2. Adverbs, adjectives and nouns change their forms depending of grammarical case. 
E.g. 
*cabbage* is *kapusta*, but 
*soup with cabbage* is *soop s kapust**oi***
3. Nouns usually (or even ever) can't be used as adjectives/adverbs.
E.g.
in *pumpkin-cabbage soup*: *pumpkin* will be strictly adverb, *cabbage* - strictly adjective:
*tykve**nno**-kapust**nuy** soop*.
If you change definitions order: *cabbage-pumpkin soup*:
*kapust**no**-tykve**nnuy** soop*
And btw different words have different adverb/adjective prefixes.

I guess in other languages this may be also as problematic, but in different way.

I have no experience how these things are usually dealt with.
E.g. with current approach we could try to somehow store the source words with context.
Context may be included to the source (doesnt seem to be possible), or may be only visible in the key string.
E.g. if I know that this *hearty* will go with *soup*, not to *porridge*, I will write the matched translation.
Same with point 2, *with cabbage*.
Also with *cabbage-pumpkin* case (even with more-general case of *cabbage-pumpkin-turnip-onion* case): all words except the last one are adverbs, last one is adjective, which can depend from grammatical gender and quantity.

Without such improvement, the awesome feature - dynamic meal descriptions - will look terrible in Russian and may damage VS reputation a lot. Better not to translate at all.
In Russia there were many widely known cases when in movies (usually US ones) or in games the translations were awful (e.g. just a random set of cyrillic characters instead of a person's surname), and people laughed on these translations and looked at them very negatively.

:tired_face:

**Comment by tyronx** [comment]
@tatsu011 whats the state of this?

**Comment by tatsu011** [comment]
The change to fix this has been pushed to the next main version.  As of now this change is complete.

**Comment by tyronx** [comment]
@Heptagon-ru I'll upload the new 1.9.0 translations soon-ish. If the improvements by tatsu do not suffice for a correct translation do let us know. I fully agree on your statement, either we properly translate it or not translate it at all.

**Comment by Heptagon-ru** [comment]
@tyronx , @tatsu011 
So the Type is soup/porridge/...? Then yeah, it might work, if at least Primary will be separate for each type.
Need to see live to understand better.
Yeah, will try to keep an eye on the new translations and check and report back.

**Comment by tyronx** [comment]
This are the new language entries that tatsu added:

	"cooking-porridge-format-g1": "{1} {0}",
	"cooking-porridge-format-g2": "{1}-{2} {0}",
	"cooking-porridge-format-g1o": "{1} {0} with {2}",
	"cooking-porridge-format-g2o": "{1}-{2} {0} with {3}",
	"cooking-porridge-format-g1h": "{2} topped {1} {0}",
	"cooking-porridge-format-g2h": "{3} topped {1}-{2} {0}",
	"cooking-porridge-format-g1oh": "{3} topped {1} {0} with {2}",
	"cooking-porridge-format-g2oh": "{4} topped {1}-{2} {0} with {3}",
	"meaty": "meaty",
	"cooking-stew-format-m1": "{1} {0}",
	"cooking-stew-format-m2": "{2} {1} {0}",
	"cooking-stew-format-m1o": "{1} {0} with {2}",
	"cooking-stew-format-m2o": "{2} {1} {0} with {3}",
	"cooking-stew-format-m1h": "{2} topped {1} {0}",
	"cooking-stew-format-m2h": "{3} topped {2} {1} {0}",
	"cooking-stew-format-m1oh": "{3} topped {1} {0} with {2}",
	"cooking-stew-format-m2oh": "{4} topped {2} {1} {0} with {3}",
	"cooking-stew-format-v1": "{1} {0}",
	"cooking-stew-format-v2": "{2} {1} {0}",
	"cooking-stew-format-v1o": "{1} {0} with {2}",
	"cooking-stew-format-v2o": "{2} {1} {0} with {3}",
	"cooking-soup-format-a1": "{1} {0}",
	"cooking-soup-format-a2": "{2} {1} {0}",
	"cooking-soup-format-a1o": "{1} {0} with {2}",
	"cooking-soup-format-a2o": "{2} {1} {0} with {3}",

**Comment by Heptagon-ru** [comment]
If I understand correctly,
{0} is "porridge"/"stew"/"soup", {1} is main ingredient, {2} is additional, {3} is topping.

I may see 3 kinds of problems.
1.
For porridge, in case "{1} {0}" and in case "{1}-{2} {0}", even if {1} is e.g. rye, it will be two different word forms.
For "{1} {0}" it will be adjective, e.g. "rye porridge" = "ржан**ая** каша",
but for "{1}-{2} {0}" it will be adverb, e.g. "rye-rice porridge" = "ржан**о**-рисовая каша".
Kinda because the last word in chain X-Y-X remains adjective, and all previous become adverbs.
And I think you can't build the chain without dashes using only adjectives, because the adjectives are of the same type/tier. I guess the same in English - you probably can't say "rye rice porridge", but can "tasty rice porridge", because tasty and rice are adjectives of different "type", they describe different attribute "slots" of porridge.
2. 
Sometimes one ingredient, e.g. vegetable, is used in recipes of different types, therefore we need to have a separate form of the ingredient for each type, because meal types have different gender and therefore their adjectives need to have different gender.
E.g. "stew" has neuter gender, "soup" has masculine gender.
So "cabbage stew" will be "капустн**ое** рагу", but "cabbage soup" will be "капустн**ый** суп".
3. 
When e.g. "poultry" is used before meal type for stews, it will be adjective, when after (for soups) - usually a noun: "poultry stew" - "**куриное** рагу", "cabbage soup with poultry" - "капустный суп с **курицей**". Again need to have separate words for substitutions.

So unless there is more of the new entries, I feel this will not save us.
@tyronx , could you please cross-check all this through Saraty? She knows Russian quite good I'm sure, and she is much closer to you and she worked more with the dynamic meals. Maybe I am missing something. Also if you will try to modify the methodology, she will give much faster analysis if it works for Russian.
Ofc if she distastes :) this kind of work, you are stuck with me only :D

**Comment by tatsu011** [comment]
I am curious if "Poultry in Cabbage soup" is written differently than "Cabbage soup with poultry"

**Comment by Heptagon-ru** [comment]
@tatsu011, yes.
"Poultry in cabbage soup" - Куриц**а** в капустн**ом** суп**е**
"Cabbage soup with poultry" - Капустн**ый** суп с куриц**ей**
For reference: cabbage - капуста, poultry - курица, soup - суп

In this example all the changes in suffixes are because of grammatical cases.
According to Wiki, English mostly lost all cases, remained only 3 simplified cases for personal pronouns: I, me, mine/my, He/him/his, ...

(Btw, strictly speaking, poultry is translated differently, and I actually used translation of "chicken".
But the word transformation is the same. It is just that in Russian there is no good short accurate word for poultry, the usual translation is "bird meat" which is not quite correct, because poultry is not all birds.
That's why poultry is one of the most hated by me words in VS OneSky translation :DDD)

**Comment by tatsu011** [comment]
I approve of that little bit of info.  I also approve of changing the format of how things are laid out so that words can flow in the same sort of direction.  What I've put there works for English, but if it's possible to change that formatting to work for Russian, then by all means, change the formatting. (that's what it's there for.

**Comment by Heptagon-ru** [comment]
Aww, I was hoping you guys will find the way with your bright young brains :D I will try to think of something, but I don't feel positive I can :)

**Comment by tatsu011** [comment]
Since I'm not exactly multilingual, (just monolingual English speaker) I wanted to build something that others can work with.  Thus: I give you formatting.

**Comment by tyronx** [comment]
Unfortunately the system proposed by tatsu insufficient. New system, as discussed with @Heptagon-ru:

1. Base language Entries
```
"cooking-normal-porridge": "{0} porridge {1}",
"cooking-normal-stew": "{0} stew {1}",
"cooking-normal-soup": "{0} soup {1}",

"cooking-hearty-porridge": "Hearty {0} porridge {1}",
"cooking-hearty-stew": "Hearty {0} stew {1}",
"cooking-hearty-soup": "Hearty {0} soup {1}",

"cooking-hefty-porridge": "Hefty {0} porridge {1}",
"cooking-hefty-stew": "Hefty {0} stew {1}",
"cooking-hefty-soup": "Hefty {0} soup {1}",
```

**in above list {0} will be replaced by:** The list of primary/secondary ingredients connected with dashes as before, but using primary/secondary language entries for all of possible ingredients:
```
"cooking-ingredient-porridge-secondary-rice": "Rice",
"cooking-ingredient-porridge-primary-rice": "Rice as adjective",

"cooking-ingredient-soup-secondary-rice": "Rice",
"cooking-ingredient-soup-primary-rice": "Rice as adjective",
etc.....
```

**whereas {1} will be replaced by**: 
```
"cooking-porridge-mashed": " with mashed {0}",
"cooking-porridge-sprinkled": " with sprinkled {0}",
"cooking-porridge-mashed-and-sprinkled: " with mashed {0} and sprinkled {1}",
"cooking-porridge-mash-aswellas-sprinkled": " with mashed {0} as well as sprinkled {1}",
```

**in this list {0}/{1} will be replaced by item lists**
```
"itemlist-1": "{0}",
"itemlist-2": "{0} and {1}",
"itemlist-3": "{0}, {1} and {2}",
"itemlist-4": "{0}, {1}, {2} and {3}",
etc... (until 10)
```

**items inside the item list will use language entries of all ingredients in instrumental case**

```
"ingredient-cranberry-instrumentalcase": "cranberry+oi",
"ingredient-carrot-instrumentalcase": "carrot+oi"
etc....
```

**Comment by Heptagon-ru** [comment]
Yes, I have checked it again and cross-checked with Discord messages, it seems we covered all and the system should work. Can't wait to see if it will work flawlessly, or completely fail because of a minorest detail we missed :DDDDDD Thank you for this noice participation opportunity!
Little did @tatsu011 know, when suggested the "format" approach, we quickly mega-exploded it into the Mega Multy Format approach :D Anyway, blame Pushkin and Tolstoy, not us!!! :DDDDD

**Comment by tatsu011** [comment]
The only thing I'd actually suggest changing on the new format is give "Honey" it's own name and allow for other toppings.  eg
"{2} topped hefty {0} soup {1}"

**Comment by Heptagon-ru** [comment]
Yeah, this should work, even with other liquid sauces addition.
And we can avoid adding a new keyword type, for now we can reuse "meal-ingredient-*-instrumentalcase", i.e. "meal-ingredient-honey-instrumentalcase", because honey here will have the same "with what" grammatical case.

**Comment by tyronx** [comment]
Nah, don't do that for now. At that at a later point when it becomes relevant please.

**Comment by tatsu011** [comment]
Might I ask why to leave it as "Honey topped" instead of "{x} topped"?  The formatting required doesn't really add much and it's very easy to do.

**Comment by tyronx** [comment]
- Because it does not add much flexibility (it would be odd to call it "Pepper topped" food)
- Because as we now learned from the russian localization efforts many words can affect other words (i.e. the gender of all subequent words), and hence translators may need to know by what it is topped by exactly.  
- Since we don't know what other translators are going to throw at us i think its rather better to keep the system as simple as possible as the grammar rules of other languages will already add plenty of complexity.

**Comment by tatsu011** [comment]
This task is now complete and waiting on a merge request.

**Comment by tatsu011** [comment]
As of current, the only major feature missing is the implementation of InsturmentalCase as I had no clue how that was supposed to be handled in code- as the formatting for it looked strange.

**Comment by tatsu011** [comment]
All fixed.  Will be pushed with my updates for this month.
