### ISSUE TITLE
Liquid dupe bug for containers larger than 10L

### ISSUE THREAD

**Issue by SpearAndFang** [anegostudios/VintageStory-Issues#2310]
### Game Version

1.17.9

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

There's a couple of lines in BlockLiquidContainerBase.cs, right here (lines 715 + 717):

https://github.com/anegostudios/vssurvivalmod/blob/1fe79a8e38f61fcfc9a96fb558c7e2ac82f1a986/Systems/Liquid/BlockLiquidContainerBase.cs#L715

that completely ignore availItems, so they cause a liquid dupe bug for liquid containers larger than 10L.

Those two lines should instead be:

stack.StackSize += GameMath.Min(availItems, placeableItems, desiredItems);
return GameMath.Min(availItems, placeableItems, desiredItems);

### How to reproduce

Create a liquid container larger than 10L and use it to transfer liquids to/from another liquid container.

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report! i'll include this in 1.17.10
