### ISSUE TITLE
Entity vanish

### ISSUE THREAD

**Issue by jaesaber** [anegostudios/VintageStory-Issues#2315]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

All entities are not visible in both single player and multiplayer. Items being held are visible (sword, shield, torch etc.).

### Screenshots

![image](https://user-images.githubusercontent.com/75695375/206956953-092cf391-76d3-4874-aef4-b806a04ca8ab.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #2277
