### ISSUE TITLE
Fourth pie slice will not stack with the other three + can be baked

### ISSUE THREAD

**Issue by noelle-lavenza** [anegostudios/VintageStory-Issues#2316]
### Game Version

v1.17.9

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

(Not related to #2117; that's about picking up a one-slice BlockPie, while this is about properly taking the fourth slice with a knife.)

Was able to reproduce on Linux, in multiplayer, and in vanilla.

Looking at the stackAttributes for the two stacks, the only difference is the bakeable attribute (ignored attributes like `transitionState` removed for clarity):
```json
"2":{
	"Class": 0, "Id": 854, "stacksize": 3, "stackAttributes": {
		"contents": {
			"0": {"Class": 1, "Id": 52, "stacksize": 2, "stackAttributes": {}},
			"1": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"2": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"3": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"4": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"5": null
		},
		"pieSize": 1, "topCrustType": 0, "bakeLevel": 2, "quantityServings": 0.25, "bakeable": false
	}
},
"3": {
	"Class": 0, "Id": 854, "stacksize": 1, "stackAttributes": {
		"contents": {
			"0": {"Class": 1, "Id": 52, "stacksize": 2, "stackAttributes": {}},
			"1": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"2": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"3": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"4": {"Class": 1, "Id": 82, "stacksize": 2, "stackAttributes": {}},
			"5": null
		},
		"pieSize": 1, "topCrustType": 0, "bakeLevel": 2, "quantityServings": 0.25
	}
},
```
True to this, only the fourth slice can be placed back into an active oven and charred; the other three say 'oven is full' (maybe also a bug?)

I think the cause is here:
https://github.com/anegostudios/vssurvivalmod/blob/08fadd58f5bd39d5dd80fd5755f9534f2a02f12f/BlockEntity/BEPie.cs#L134-L150
Line 149 sets `bakeable: false` for `size > 1`, but the `size <= 1` branch doesn't.

### How to reproduce

1. Bake a pie.
2. Slice all four pieces with a knife.
3. Note that the fourth piece does not stack with the other three.
4. Attempt to place one of the three stacking pieces into a heated oven: fail.
5. Successfully place the fourth piece in an active oven and note that it can char.

### Logs

N/A

**Comment by typingtime** [comment]
The fourth slice of pie also does not give any satiation or nutrition.

**Comment by noelle-lavenza** [comment]
> The fourth slice of pie also does not give any satiation or nutrition.

I believe that is a separate issue when you *pick up* a pie with only one slice left, rather than cutting a fourth slice? I'm pretty sure it worked when I ate it.

**Comment by laitskin** [comment]
> I believe that is a separate issue when you pick up a pie with only one slice left, rather than cutting a fourth slice? I'm pretty sure it worked when I ate it.

I can confirm this.

**Comment by noelle-lavenza** [comment]
```diff
            if (size <= 1)
            {
                if (!stack.Attributes.HasAttribute("quantityServings"))
                {
                    stack.Attributes.SetFloat("quantityServings", 0.25f);
                }
                inv[0].Itemstack = null;
                Api.World.BlockAccessor.SetBlock(0, Pos);
            }
            else
            {
                inv[0].Itemstack.Attributes.SetInt("pieSize", size - 1);

                stack.Attributes.SetInt("pieSize", 1);
                stack.Attributes.SetFloat("quantityServings", 0.25f);
-               stack.Attributes.SetBool("bakeable", false);
            }
+           stack.Attributes.SetBool("bakeable", false);
```
This should be fixed by just moving this line outside the if/else entirely.

**Comment by tyronx** [comment]
thanks for the thorough research! will be in the next rc
