### ISSUE TITLE
Inconsistencies with Scythe

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#232]
Right now the scythe will break anything that it works on regardless what it's used on. That is, if you break grass it will also break nearby crops and the other way around. I suggest making it so it will only break similar blocks, for example:

- On normal ground, breaks anything regardless of which plant it is: Grass, unique plants (ferns, horsetail), flowers, crops when found in the wild / not on tilled farmland.
- On farmland, only breaks crops of the same type, and differentiates between fully grown and partially grown crops to make life easier. Though the last part might be kept as it is intentionally..?
- Pumpkin plants should probably be exempt from this, or be their own separate category.

Additionally the scythe currently doesn't work on all the plants, such as the horsetail I mentioned. So the range of blocks it can be used on should be expanded.

**Comment by Craluminum2413** [comment]
At least you can harvest cattails with this

**Comment by Heptagon-ru** [comment]
This ticket seems already redundant from my part, since scythe works fine in 1.14.
@copygirl , if your addition is irrelevant too, please close the ticket as obsolete.

**Comment by copygirl** [comment]
I suppose my suggestion is still open, but I think the way it's implemented right now where it breaks crops regardless of its growth state is likely intentional, so I will close it, yes.
