### ISSUE TITLE
1.17.9 Import schematic crash on creative for instance 

### ISSUE THREAD

**Issue by Dhrinzor** [anegostudios/VintageStory-Issues#2325]
### Game Version

v1.17-9

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Logs

```Log```
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10269123/client-crash.txt)

**Comment by Craluminum2413** [comment]
Pirate versions of the game are not supported
