### ISSUE TITLE
Textures glitch heavily.

### ISSUE THREAD

**Issue by TarotCardGhost** [anegostudios/VintageStory-Issues#2326]
### Game Version

v1.17.9 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Textures glitch out heavily. either showing up as pure white or this glitched pattern that flickers. Only Happens within a multiplayer server, in single player it works fine.

### Screenshots

![image](https://user-images.githubusercontent.com/106279303/209300227-6d8cc48f-07a0-4257-ba8c-2d88517dc967.png)

### Logs

```Log```
Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.17.9 (Stable)
12/23/2022 12:19:05 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.10, ancienttools@1.4.9, primitivesurvival@3.1.0, game@1.17.9, wildcrafttrees@1.1.2, wildcraft@1.5.1, expandedfoods@1.6.4, creative@1.17.9, survival@1.17.9, xlib@0.6.14, xskills@0.6.14
System.OutOfMemoryException: Your graphics card ran out of memory! Please close other programs and reduce your view distance to prevent the game from crashing.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckGlErrorAlways(String errmsg) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 85
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 692
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/22/2022 11:15:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1924036237561566579, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: atio6axx.dll
P5: 31.0.12029.10015
P6: 6387ad05
P7: c0000005
P8: 0000000000243f86
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF7C4.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4e312c62cb537a18954048b4d9aa96a5a174315_7fba9aec_db5c133d-5c55-475b-a18c-b5baafe5a5d2

Analysis symbol: 
Rechecking for solution: 0
Report Id: a93b17cc-e586-41a4-a9d5-182b844b424d
Report Status: 268435456
Hashed bucket: 5923a57e5b255a6aeab38cc39ad61573
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/22/2022 11:15:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: atio6axx.dll
P5: 31.0.12029.10015
P6: 6387ad05
P7: c0000005
P8: 0000000000243f86
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_4e312c62cb537a18954048b4d9aa96a5a174315_7fba9aec_db5c133d-5c55-475b-a18c-b5baafe5a5d2

Analysis symbol: 
Rechecking for solution: 0
Report Id: a93b17cc-e586-41a4-a9d5-182b844b424d
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/22/2022 11:15:23 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.9.0, time stamp: 0x63501532
Faulting module name: atio6axx.dll, version: 31.0.12029.10015, time stamp: 0x6387ad05
Exception code: 0xc0000005
Fault offset: 0x0000000000243f86
Faulting process id: 0x15f0
Faulting application start time: 0x01d9169e1edf83d9
Faulting application path: C:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0386458.inf_amd64_e0283e9e7966f704\B386218\atio6axx.dll
Report Id: a93b17cc-e586-41a4-a9d5-182b844b424d
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Could you send `client-main.txt` from `\AppData\Roaming\VintagestoryData\Logs` folder?
Also, have you tried to reduce view distance to 96 or 128?

**Comment by Aledark789** [comment]
Ive had happend something similar to 2 players with a Radeon 560x on our server.

I teleported them away and forcedchunks reload on them and worked.

**Comment by TarotCardGhost** [comment]
it was the Primitive survival mod. uninstalled it at it was fixed.

**Comment by Craluminum2413** [comment]
@Aledark789 
Is Primitive Survival mod installed on your server?

**Comment by TarotCardGhost** [comment]
once i installed it within my own solo play i ran into the same issue. so it's the mod itself, not the multiplayer servers version or instance of it causing the glitch. something about that mod and the way it interacts with my graphics drivers causes that effect to happen on all textures.

**Comment by noelle-lavenza** [comment]
Note: I use that mod and it's just fine. It's probably due to the combination of a lot of texture-heavy mods, like Wildcraft, Wildcraft Trees, and Primitive Survival.
