### ISSUE TITLE
Torch holders should accept colored torches

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#233]
In 1.7.8. torch holders do not accept colored torches inside, only ordinary ones.
Can be useful for creative building, and ofc for future survival.

**Comment by tyronx** [comment]
I think colored torches should not be in the game in the first place. Lanterns with tinted glass could take over that job.

**Comment by Heptagon-ru** [comment]
Oh well, good idea, sounds more believable.
I like in colored torches their raising particles and bright colored parts of the torch. I guess these will be absent in the lanterns. I'll make a separate suggestion on forum.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
