### ISSUE TITLE
Possible error in RenderPlants.StartRenderingFrames

### ISSUE THREAD

**Issue by xxmicloxx** [anegostudios/VintageStory-Issues#2332]
### Game Version

v1.17.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

There seems to be a mistake in the matrix multiplication for calculating the MVP matrix in `RenderPlants.StartRenderingFrames()`. When the MVP matrix rows are gathered into the variables `p2`, `p3`, `p4` and `p5`, actually, the last row is not fetched, instead, the second to last row is used twice, resulting, at least theoretically, in invalid matrix multiplication (see screenshot). I am not sure if this affects this use case at all but it does look like it might be a mistake that should be fixed.

### Screenshots

![image](https://user-images.githubusercontent.com/1433632/210082382-0cc7bdb5-3b1e-49d9-98d6-f9d540d36817.png)

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed in 1.17.10. 

Just for info: The entire instanced plant rendering system will be removed again in 1.18
