### ISSUE TITLE
Invisible entities on IntelHD 4000

### ISSUE THREAD

**Issue by LeKrias** [anegostudios/VintageStory-Issues#2346]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

entities (animals and hostile beings) are not rendered, including the player

### Screenshots

![image](https://user-images.githubusercontent.com/123104690/213512282-2d9a45a3-8191-479f-90c1-87eca1bc61e8.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Can you set `maxAnimatedElements` in the `clientsettings.json` to 34?

**Comment by LeKrias** [comment]
How i do that? with vscide? and where find the archive clientsettings.json?

**Comment by Craluminum2413** [comment]
You can find it at `\AppData\Roaming\VintagestoryData`

**Comment by LeKrias** [comment]
> You can find it at `\AppData\Roaming\VintagestoryData`

Hmmmm, i modify the clientsettings,json file, but when I modify the value that you recommended, another file appears with the same default values

**Comment by LeKrias** [comment]
Nvm, i found the way to edit the file, i just use JSON Editor Online, and save it on my desk, and it works, thx you so much :)
