### ISSUE TITLE
Game crashes when trying to make a new world

### ISSUE THREAD

**Issue by Bantoo1231** [anegostudios/VintageStory-Issues#2350]
### Game Version

v1.17.10

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I loaded Vintage story for the first time in a while yesterday and updated it to the latest version. In my previous world I had used mods so I turned the mods off and tried to delete the old save when it crashed. I tried deleting the mods from the folder and it still crashed when trying to delete the save. I deleted the save via the folder then tried making a new world when it still kept crashing. I tried completely uninstalling the game and reinstalling it but it's still crashing.

### How to reproduce

1. Open the game.
2. Try and create a new world. (that's all I'm doing so I don't know what else may cause the crash)

### Screenshots

![Crashreport 21 01 2023](https://user-images.githubusercontent.com/49454307/213847593-05e65111-c8c2-4ef5-ae70-00dcc2653cb6.PNG)

### Logs

```Log```
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10471675/client-crash.txt)

**Comment by Craluminum2413** [comment]
The base game mods should be always turned on, these are: Survival, Creative and Essentials
