### ISSUE TITLE
Compatiblity Patches no longer executed

### ISSUE THREAD

**Issue by tels-git** [anegostudios/VintageStory-Issues#2351]
### Game Version

v1.17.10

### Platform

None

### Modded

Modded

### SP/MP

None

### Description

Undee 1.17.10, any compatibility patches that are under assets/modid/compatibility/... are no longer loaded.

For bricklayers, this means all the alternative recipes are missing, planters can no longer be carried around with carry capacity etc.

### How to reproduce

* Install Bricklayers, Expanded Matter and Carry Capacity
* Try to pick up a colored clay planter (f.i. red) with right mouse click

or install any mod like More Candles, Expanded Foods, etc and see that the extra recipes are missing. See screenshot.

### Screenshots

![missing_patches 1 17 10](https://user-images.githubusercontent.com/29096965/213880694-f3a4141e-6943-4681-bb97-3ffaa5a0e7da.jpg)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
