### ISSUE TITLE
Journal Translation Expansion

### ISSUE THREAD

**Issue by tatsu011** [anegostudios/VintageStory-Issues#237]
Currently the way the journal is laid out is difficult to deal with running translations for the journal without making a bunch of translations in another language.  

The two ideas to fix this are as follows:
Move the Journal to lang/en/journal/entry.json
or add subdirectories to the journal eg: journal/en/entry.json

Related to: #230

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

Also could be mentioned in #gavedev on discord.
