### ISSUE TITLE
NET7: Immersive Mouse Mode - Mouse pointer doesn't 'reset' when letting go of Alt

### ISSUE THREAD

**Issue by PJ-Mog** [anegostudios/VintageStory-Issues#2371]
### Game Version

v1.17.11-net7-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When Immersive Mouse Mode is enabled, if you let go of the Alt key to return to camera controls while the mouse is still over an open dialog box, the game still thinks the mouse is in the previous position. Depending on the camera movements performed afterward, this interferes with mouse clicks when the user is trying to interact with the world and not the windows that are still open. See video: [https://youtu.be/lNUu3lr5fFI](https://youtu.be/lNUu3lr5fFI)

### How to reproduce

1. Enable Immersive Mouse Mode
2. Open an inventory
3. Hold Alt and position the mouse over an open inventory
4. Release Alt and try to break a block in front of you (without moving the camera)
5. You can see the highlighted inventory slots changing as the camera moves with Alt released
6. Clicking with Alt released still interacts with the open inventory in a remembered position

This bug can also occur if hovering over the hotbar when releasing Alt.

**Comment by Th3Dilli** [comment]
thank you for the report, this will be fixed in the next version
