### ISSUE TITLE
NET7 Item description pop-ups semi-randomly appear for a moment

### ISSUE THREAD

**Issue by PaulBlay** [anegostudios/VintageStory-Issues#2373]
### Game Version

v1.11.17-rc1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When doing something item description popups sometimes appear for a brief moment. It isn't entirely random, it never happens if you're just standing around doing nothing, but I have not been able to narrow it down to a particular action. If you play for an hour and it hasn't happened, then it probably isn't going to happen for you.

The popups are for items in your hotbar or inventory, but not the one currently selected.

N.B. The server was vanilla (no mods) and I have only a couple of client side mods (human skin appearance and prospector info).

### How to reproduce

1. Have a bunch of flint on hot-bar
2. Have bamboo-shoots next to flint in hot-bar
3. Knap some flint knives
4. _Possibly_ notice bamboo-shoot popup briefly appear (Also appeared while breaking lilies and swimming and other activities)

### Logs

```Log```

**Comment by PaulBlay** [comment]
After playing further, the inventory use became increasingly unstable with - for example - two slots on the hotbar being highlighted or the object being held changing into a different object.

**Comment by Th3Dilli** [comment]
thank you for the report, this will be fixed in the next release
