### ISSUE TITLE
NET7 Can't split item stacks

### ISSUE THREAD

**Issue by PaulBlay** [anegostudios/VintageStory-Issues#2375]
### Game Version

v1.11.17-rc1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When you right-click on a stack of objects to pick up half of them it appears to do as expected, but actually you have not picked up any items. 

N.B. The server was vanilla (no mods) and I have only a couple of client side mods (human skin appearance and prospector info).

### How to reproduce

1. Have a stack of items in your inventory (e.g. 8 pineapples)
2. Have some other object in your inventory (e.g. Tin bronze axe)
3. Right click stack of items to pick up half of them.
4. Click on other object to switch your half stack (4 pineapples) with the other object (axe)

Expected outcome: 4 pineapples where the axe was, axe now held by cursor.

Actual outcome: 4 pineapples disappear.

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for the report, will be fixed within the next version of net7
