### ISSUE TITLE
Проблема с подключением к другому серверу через VPN.

### ISSUE THREAD

**Issue by nurnbunurnedmsi** [anegostudios/VintageStory-Issues#2376]
### Game Version

v1.17.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable) by OverF1X  
10.02.2023 22:01:45: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt)
   в Vintagestory.Client.ScreenManager.Render(Single dt)
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 476
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 452
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

### How to reproduce

Постоянные вылеты при попытки подключиться к серверу друга по его ip в VPN хотя если заходить на сервер другого друга то там вообще нет никаких проблем. А, и да, при каждом краше/вылете появляется это(смотрите выше). Надеюсь вы это увидите и скоро исправите.

### Logs

```Log```
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710434/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710435/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710436/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710437/client-main.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710438/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710439/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710440/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710441/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710443/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710444/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710445/server-storyevent.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/10710446/client-audit.txt)

**Comment by Craluminum2413** [comment]
The pirated versions of the game are not supported
