### ISSUE TITLE
[1.8.0-pre.7] Crop growth stage tooltip has typo

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#238]
1.8pre7, official server.
In crop tooltip, it is "Growth Stage3/12" instead of "Growth Stage: 3/12"
![2018-12-13_21-47-00](https://user-images.githubusercontent.com/25122345/49960401-1a986a00-ff21-11e8-9722-348a55f1cc3b.png)

**Comment by tyronx** [comment]
ok, fixed for -rc.4
