### ISSUE TITLE
.net7 Client Startup Switches Missing

### ISSUE THREAD

**Issue by DerSandmann-Badcode** [anegostudios/VintageStory-Issues#2384]
### Game Version

v1.17.11-rc.2

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

The --openworld\-o and --playstyle\-p switches do not work on the .net 7 version

### How to reproduce

Try to use the -p or -o switches

### Screenshots

![image](https://user-images.githubusercontent.com/8218786/219606473-e7e2f736-bb56-4f84-9ca6-427ca4df88c3.png)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for your report
the issue will be resolved with the next release
