### ISSUE TITLE
Creative Menu Partially Off Screen

### ISSUE THREAD

**Issue by SapphireBee** [anegostudios/VintageStory-Issues#2388]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The issue persisted to a vanilla single player world, but first occurred in multi-player. The top part of the creative menu, and only that menu, is not on screen and I can not move it. Tried reinstalling the game as well, still hidden.

### How to reproduce

I don't know? I set it to movable once, that might have done it

### Screenshots

![3f71caae-151b-4920-a289-d0d5f37b1afd](https://user-images.githubusercontent.com/125785238/219931407-7d410e4e-4919-4aa1-a55d-7039c5efd093.jpg)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
You can fix it by removing `inventory-creative` setting from `\AppData\Roaming\VintagestoryData\clientsettings.json`

**Comment by SapphireBee** [comment]
> You can fix it by removing `inventory-creative` setting from `\AppData\Roaming\VintagestoryData\clientsettings.json`

Thank you! I don't know where the menu originally was since I've been dealing with this for a while, but it's fully on my screen now! I've set it to fixed to avoid this again.
