### ISSUE TITLE
1.17.11-rc2 Dotnet7 - Interface-Sound-Selection (Default or OpenALsoft) ---doesnt list hardware nor virtual sound devices.

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#2389]
### Game Version

1.17.11rc2 dotnet7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

1.17.11-rc2 Dotnet7 - Interface-Sound-Selection (Default or OpenALsoft) ---doesnt list hardware nor virtual sound devices.

I hear things fine however

i cant select my source output either virtual or hardware.
i have 2 options default or openalsoft.

### How to reproduce

go to settings 
then sounds...
output selection 

doesnt list all my options from my windows system (hardware or virtual).

It does on non dotnet7 version.

### Screenshots

![Capture d’écran 2023-02-23 114555](https://user-images.githubusercontent.com/31166271/220977992-ec265092-1f97-4aa6-84fb-2f744e03c8c0.jpg)

![Capture d’écran 2023-02-23 114758](https://user-images.githubusercontent.com/31166271/220978025-e98839a0-a378-4e3d-8cde-0df38beaf123.jpg)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for reporting

it will be fixed with the next net7 version
