### ISSUE TITLE
Linux only client connection issue to hosted server

### ISSUE THREAD

**Issue by Conamin** [anegostudios/VintageStory-Issues#2390]
### Game Version

v1.17.11

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

I recently purchased some hosting so that I could run a Vintage story server. I tested some mods locally on my machine to determine which ones I was going to upload to my server. All of the mods I selected worked as intended while running on my local machine.

I uploaded the mods to the server, and then attempted to connect. I am receiving the following error when I attempt to connect from my machine:

Running on 64 bit Linux with 14 GB. 
Game Version: v1.17.11 (Stable)
2/23/2023 12:13:05 PM: Critical error occurred
Loaded Mods: arrowtweaks@1.0.0, backpackpackplus@1.0.3, betterpoultice@1.0.0, betterruins@0.0.7, fulldrop@1.0.0, game@1.17.11, carrycapacity@0.6.5, farmlanddropssoil@1.4.0, medievalexpansion@3.8.1, prospectorinfo@4.1.2, creative@1.17.11, survival@1.17.11, VsWaypointSharing@1.0.2, metalrecovery@0.1.18-rc.2, gravemod@2.2.1
System.Exception: Don't know how to instantiate item of class 'itemstick' did you forget to register a mapping?
  at Vintagestory.Common.ClassRegistry.CreateItem (System.String itemClass) [0x0001e] in <3352cf17b586476e962abf3ce6c3aa95>:0 
  at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket (Packet_ItemType packet, Vintagestory.API.Common.IWorldAccessor world, Vintagestory.Common.ClassRegistry registry) [0x00000] in <3352cf17b586476e962abf3ce6c3aa95>:0 
  at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems (System.Collections.Generic.List`1[T] items, System.Int32 listSize) [0x00051] in <3352cf17b586476e962abf3ce6c3aa95>:0 
  at Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes () [0x00057] in <3352cf17b586476e962abf3ce6c3aa95>:0 
  at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1 () [0x0001a] in <3352cf17b586476e962abf3ce6c3aa95>:0 
  at Vintagestory.API.Common.TyronThreadPool+<>c__DisplayClass3_0.<QueueTask>b__0 (System.Object a) [0x00000] in <562a7134e9ed49cdb605c73c95dfac70>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <aaade903710a4403b9bc5b092942709f>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <aaade903710a4403b9bc5b092942709f>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <aaade903710a4403b9bc5b092942709f>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <aaade903710a4403b9bc5b092942709f>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <aaade903710a4403b9bc5b092942709f>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <aaade903710a4403b9bc5b092942709f>:0 

I switch my machine to my Windows 10 partition, and attempted to connect, and it was successful. I had a friend who is running Vintage Story on a Windows machine test, and they are able to connect with no issues. I disabled Mods one by one, and I ultimately ended up with only one Mod being able to work when I connect from my machine when running on the Linux partition.

The only Mod that worked on the Linux client is Better Ruins mod.

On the one hand this looks and feels like it is a Mod issue, but on the other the issue is only occurring when I try to access the hosted server from my Linux partition. I want to reiterate the Mods all work wonderfully on my Linux partition when running the world locally.

Is there a diagnostic tool that I can run, or can I look in some config files to track down this mapping issue?

**Computer: Steam Deck**
Primary partition: Linux: SteamOS 3.4 Stable (Variant of Arch Linux), latest patches
Secondary Partition: Windows 10, Latest patches.

**Hosting service:**
https://www.bisecthosting.com/

### How to reproduce

1. Have a hosted server that is running the following Mods:

**List of Mods in use on the server:**  -- All mods are the latest available as of 2/22/23.
Anvil Metal Recovery+
Arrowtweaks
Backpack Pack Plus
BetterBackPacks
BetterPoultice
BetterRuins
CarryCapacity
Farmland Drops Soil
Full Drop
GraveMod
Medieval Expansion
Primitive Survival
ProspectorInfo
VsWaypointSharing

2. Connect to the server through a machine that is running Linux
The error occurs right as the world is trying to be loaded.

### Logs

```Log client-main.txt```
23.2.2023 12:48:59 [Notification] Client logger started.
23.2.2023 12:48:59 [Notification] Game Version: v1.17.11 (Stable)
23.2.2023 12:48:59 [Warning] Client side assembly resolver did not find the assembly in the binary path, the lib path or the mods path. Tested for the following paths:
  /app/extra/vintagestory/
  /app/extra/vintagestory/Lib
  /app/extra/vintagestory/Mods
  /home/deck/.var/app/at.vintagestory.VintageStory/config/VintagestoryData/Mods
23.2.2023 12:49:00 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
23.2.2023 12:49:00 [Notification] CPU Cores: 8
23.2.2023 12:49:00 [Notification] Available RAM: 14836 MB
23.2.2023 12:49:00 [Notification] Graphics Card Vendor: AMD
23.2.2023 12:49:00 [Notification] Graphics Card Version: 4.6 (Core Profile) Mesa 21.3.9 (git-78c96ae5b6)
23.2.2023 12:49:00 [Notification] Graphics Card Renderer: AMD VANGOGH (DRM 3.45.0, 5.13.0-valve36-1-neptune, LLVM 12.0.1)
23.2.2023 12:49:00 [Notification] Graphics Card ShadingLanguageVersion: 4.60
23.2.2023 12:49:00 [Notification] GL.MaxVertexUniformComponents: 16384
23.2.2023 12:49:00 [Notification] GL.MaxUniformBlockSize: 67108864
23.2.2023 12:49:00 [Notification] Cairo Graphics Version: 1.16.0
23.2.2023 12:49:00 [Notification] OpenAL Version: 1.1 ALSOFT 1.21.1
23.2.2023 12:49:00 [Notification] C# Framework: Mono 6.12.0.182 (tarball Tue Jan 17 04:25:25 PM UTC 2023)
23.2.2023 12:49:00 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
23.2.2023 12:49:00 [Notification] Start discovering assets
23.2.2023 12:49:00 [Notification] Found 21 base assets in category lang
23.2.2023 12:49:00 [Notification] Found 0 base assets in category patches
23.2.2023 12:49:00 [Notification] Found 22 base assets in category config
23.2.2023 12:49:00 [Notification] Found 0 base assets in category worldproperties
23.2.2023 12:49:00 [Notification] Found 46 base assets in category sounds
23.2.2023 12:49:00 [Notification] Found 97 base assets in category shapes
23.2.2023 12:49:00 [Notification] Found 80 base assets in category shaders
23.2.2023 12:49:00 [Notification] Found 16 base assets in category shaderincludes
23.2.2023 12:49:00 [Notification] Found 129 base assets in category textures
23.2.2023 12:49:00 [Notification] Found 4 base assets in category music
23.2.2023 12:49:00 [Notification] Found 0 base assets in category dialog
23.2.2023 12:49:00 [Notification] Found 415 base assets in total
23.2.2023 12:49:00 [Notification] Loading sounds
23.2.2023 12:49:00 [Notification] Sounds loaded
23.2.2023 12:49:00 [Notification] (Re-)loaded frame buffers
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass .
23.2.2023 12:49:00 [Notification] Window was resized to 600 400, rebuilding framebuffers...
23.2.2023 12:49:00 [Notification] (Re-)loaded frame buffers
23.2.2023 12:49:00 [Notification] Begin loading shaders
23.2.2023 12:49:00 [Notification] Window was resized to 600 400, rebuilding framebuffers...
23.2.2023 12:49:00 [Notification] (Re-)loaded frame buffers
23.2.2023 12:49:00 [Notification] Load shaders now
23.2.2023 12:49:00 [Notification] Loading shaders...
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass standard.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass particlescube.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass particlesquad.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass sky.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass nightsky.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass woittest.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass helditem.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass decals.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass final.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass gui.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass blur.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass findbright.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass godrays.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass autocamera.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass wireframe.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass entityanimated.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass luma.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass blit.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass texture2texture.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass celestialobject.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass colorgrade.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass guigear.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass ssao.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass grass.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass flowers.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass shadowgrass.
23.2.2023 12:49:00 [Notification] Loaded Shaderprogramm for render pass shadowflowers.
23.2.2023 12:49:00 [Notification] Cached session key is valid, validating with server
23.2.2023 12:49:02 [Notification] Server validation response: Good
23.2.2023 12:49:02 [Notification] Will search the following paths for mods:
23.2.2023 12:49:02 [Notification]     /app/extra/vintagestory/Mods
23.2.2023 12:49:02 [Notification]     /home/deck/.var/app/at.vintagestory.VintageStory/config/VintagestoryData/Mods
23.2.2023 12:49:04 [Warning] Texture with texture id 92 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 95 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 3 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] MeshRef with vao id 5 with 6 indices is leaking memory, missing call to Dispose. Set env var VAO_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 94 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 96 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] MeshRef with vao id 1 with 8 indices is leaking memory, missing call to Dispose. Set env var VAO_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 98 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 99 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 67 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 66 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 65 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 70 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 69 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 68 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] MeshRef with vao id 4 with 6 indices is leaking memory, missing call to Dispose. Set env var VAO_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 73 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 72 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 71 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 76 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 75 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 74 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 79 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 78 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 77 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 82 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 81 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
23.2.2023 12:49:04 [Warning] Texture with texture id 80 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.

**Comment by Craluminum2413** [comment]
`itemstick` is a class from Primitive Survival mod

**Comment by Conamin** [comment]
@Craluminum2413 Thank you for looking into this so quickly. I appreciate that the closure code points to this is not planned, but can you point out where you were able to determine which Mod was the culprit? Was it in the stack trace some place, or have you run into this with other Linux users and this Mod? I would like to learn how to track back issues in Vintage story so I can do my due diligence in tracking an issue down before creating an issue here on the tracker.

**Comment by Craluminum2413** [comment]
I looked at Primitive Survival source code and searched for itemstick within repository, then I found it <https://github.com/SpearAndFang/primitive-survival>. Well, i already knew which mod added such an item, but if you remove that mod and still will get that crash, then I will reopen this issue.
