### ISSUE TITLE
1.18pre3 Cellar invalid when entrance has a door

### ISSUE THREAD

**Issue by stony99** [anegostudios/VintageStory-Issues#2399]
### Game Version

v1.18-pre.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Doors "solid door(Walnut)" or "crude door" do not make a valid cellar. Cellar has to be blocked off with solid blocks. 

### How to reproduce

1. Make a small cellar underground
2. put a solid door (walnut) at the entrance
3. place a clay vessel
4. look at food perish speed
5. block entry with solid blocks
6. check again

### Screenshots

hmm, GitHub does not let me upload .png ... dunno why. Says "Something went really wrong, and we can´t process that file."

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What the door looks like?

**Comment by stony99** [comment]
https://postimg.cc/gallery/WgLJs6z
It´s that "solid door(walnut)" as mentioned in the handbook.

**Comment by stony99** [comment]
Looks like the old trap door still works. Seems to be an issue with the new doors.
https://postimg.cc/rR2Hyprf

**Comment by Niiohontesha** [comment]
The iron door seems to work as well.

**Comment by Craluminum2413** [comment]
Fixed in 1.18.0-pre.7
