### ISSUE TITLE
1.5.2.2 Most lanterns when placed look as a copper one

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#24]
When I make lanterns from new materials, like bronze or that lead alloy, they are shown correctly in inventory (iirc) but when placed look like a copper one. When picked up they are of a correct metal, not copper. Observed by Saraty first afaik.

**Comment by tyronx** [comment]
And if you were to reload the world or reconnect it probably uses the correct lantern texture, right? 

I fixed this now and also fixed that the block break particles were sampled from the wrong texture and the block info now also displays the material and lining. Assuming it to be fixed, please reopen if the issue persists in the upcoming 1.5.2.3

**Comment by Heptagon-ru** [comment]
Yes, if I relog, the textures are correct. Tested in creative singleplayer.
