### ISSUE TITLE
Cooking GUI food slot should smartly accept 6 items max

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#240]
Currently the four cooking GUI slots behave as ordinary inventory slots, maybe just restricting non-food items.
Since the actual cooking mechanics accepts maximum 6 ingredients in each slot, this is uncomfortable: each time I cook my usual 12 meal pots, I have to right-click each GUI slot 6 times - 268 right clicks in summary.

Please consider an enhancement: if I carry more than 6 items in my mouse and left-click them into the slot, it accepts 6 items and decreases number of items in my mouse cursor by 6.
This will greatly speedup cooking, e.g. allowing me to populate all open pot interfaces very quickly with the same ingridient.

Other standard item transfer behaviours, e.g. shift-click, left-click-drag should also support such behavior if applicable.

**Comment by tyronx** [comment]
Ok, was a bit tricky to add, but this is now implemented in v1.9. Thanks for the suggestion.
