### ISSUE TITLE
game start error

### ISSUE THREAD

**Issue by omirrq** [anegostudios/VintageStory-Issues#2406]
### Game Version

v1.17.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Running on 32 bit Windows with 4 GB RAM 
Game Version: v1.17.9 (Stable) by OverF1X  
27/2/2023 7:54:05 p. m.: Critical error occurred
Loaded Mods: 
System.DllNotFoundException: No se puede cargar el archivo DLL 'nanosvg': No se puede encontrar el módulo especificado. (Excepción de HRESULT: 0x8007007E)
   en NanoSvg.SvgNativeMethods.nsvgCreateRasterizer()
   en Vintagestory.Client.NoObf.SvgLoader..ctor(ICoreClientAPI _capi)
   en Vintagestory.Client.Gui.MainMenuGuiAPI..ctor(ScreenManager screenManager, ICoreClientAPI capi)
   en Vintagestory.Client.Gui.MainMenuAPI..ctor(ScreenManager screenManager)
   en Vintagestory.Client.ScreenManager.Start(ClientProgramArgs args, String[] rawArgs)
   en Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   en Vintagestory.Client.ClientProgram.<>c__DisplayClass14_0.<.ctor>b__0()
   en Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Pirated versions of the game are not supported
