### ISSUE TITLE
Fancy Bed

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2407]
### Game Version

v1.18.0-pre.3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The Fancy Bed (Opened) and the Fancy Bed (Closed) have been switched.

### How to reproduce

Place them on the ground in Creative to see.

### Screenshots

![FancyBed](https://user-images.githubusercontent.com/26251843/221807925-662e690d-dea1-4db9-9cc6-a718a085598e.png)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for the report, it will be fixed with the next release
