### ISSUE TITLE
No breath meter. Infinite under water breathing. 1.18.0rc3

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2409]
### Game Version

1.18.0rc3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When my seraphim goes under water there is no breath meter.

### How to reproduce

Go under water. Breath meter isn't there.

### Screenshots

![image](https://user-images.githubusercontent.com/13642054/221851323-b94ce2f4-77c4-428b-9def-f4c56fc783ad.png)

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10850122/client-main.txt)

**Comment by Saricane** [comment]
Confirmed.

**Comment by Craluminum2413** [comment]
Fixed in 1.18.0-pre.5
