### ISSUE TITLE
Trader trading window will not auto close after walking away

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2416]
### Game Version

1.18.0rc3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I opened a trading window with a trader then walked away and the window stayed open even after traveling over 1k blocks. I can interact in the window but nothing truly happens besides sounds - meaning no trades actually happen at that distance even though it sounds like it.

### How to reproduce

Open trader trading window and walk away. Try trading with them at a long distance.

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10853010/client-main.txt)

**Comment by Th3Dilli** [comment]
thank you vallen, will be fixed in an upcoming release (probably 1.20)
