### ISSUE TITLE
Lighting bug at Spawn area

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#242]
1.8.5, chrometech.
I ran to Spawn village and noticed that some lanterns do not light surrounding area.
When I break one and place it back, it starts to light things again, and some lanterns around it also resume lighting.
I enabled chunk wireframes and it seems that not all lanterns/torch holders in the chunk resume their lighting, only in some area around the replaced lantern.
Two screenshots, both before replacing lantern.
![2019-01-12_16-04-13](https://user-images.githubusercontent.com/25122345/51074210-40826d00-168d-11e9-9883-9d69f0a1219d.png)
![2019-01-12_16-04-33](https://user-images.githubusercontent.com/25122345/51074211-411b0380-168d-11e9-80ba-7b06c81825c9.png)

**Comment by tyronx** [comment]
Not really sure how it happened. I removed and placed them back again. Anybody knows by what it was caused by?

**Comment by tyronx** [comment]
Assuming to no longer be happening
