### ISSUE TITLE
Italic word issue in trader dialogue

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2420]
### Game Version

v1.18-pre3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### How to reproduce

Went into dialogue. Asked about "drifters".

### Screenshots

![2023-02-27_21-08-39](https://user-images.githubusercontent.com/126715524/222247948-590a9af3-b0a4-4817-9353-235cca189b5d.png)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you  for the report, should be fix with the next release
