### ISSUE TITLE
Ui issue in multi recipie crafts in handbook

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2421]
### Game Version

v1.18-pre3

### Platform

Windows

### Modded

None

### SP/MP

SP

### Description

Crafting recipies with more than two recipies seem to have a missplaced crafting result when viewed from the handbook.

### Screenshots

![2023-02-28_20-38-03](https://user-images.githubusercontent.com/126715524/222250564-cd6cd230-c04c-4458-805c-b03feab988c2.png)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, should be fixed in pre4
