### ISSUE TITLE
vintage story closes for some reason

### ISSUE THREAD

**Issue by zilafeindert** [anegostudios/VintageStory-Issues#2425]
### Game Version

v1.17.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

i just try to open vintage story and after a few seconds of black screen it just closes

### How to reproduce

dunno

### Logs

Running on 64 bit Windows with 4 GB RAM 
Game Version: v1.17.9 (Stable) by OverF1X  
02/03/2023 11:15:58 p. m.: Critical error occurred
Loaded Mods: 
System.Threading.ThreadStateException: El subproceso está inactivo; no se puede obtener acceso al estado.
   en System.Threading.Thread.SetBackgroundNative(Boolean isBackground)
   en Vintagestory.Client.ScreenManager.Start(ClientProgramArgs args, String[] rawArgs)
   en Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   en Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02/03/2023 11:16:06 p. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.17.9.0, marca de tiempo: 0x63501532
Nombre del módulo con errores: atio6axx.dll, versión: 6.14.10.11672, marca de tiempo: 0x54b54bdc
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x0000000000151375
Identificador del proceso con errores: 0x2c0
Hora de inicio de la aplicación con errores: 0x01d94d8f413ffe72
Ruta de acceso de la aplicación con errores: C:\Users\Aaron\Desktop\Vintage.Story.v1.17.9\Vintage.Story.v1.17.9\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\SYSTEM32\atio6axx.dll
Identificador del informe: e43ce315-451f-474b-a02e-b7c849d1c6c4
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }
--------------
{ TimeGenerated = 02/03/2023 11:16:06 p. m., Site = , Source = .NET Runtime, Message = Aplicación: Vintagestory.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.AccessViolationException
   en OpenTK.Graphics.OpenGL.GL.Disable(OpenTK.Graphics.OpenGL.EnableCap)
   en Vintagestory.Client.NoObf.ClientPlatformWindows.set_GlDebugMode(Boolean)
   en Vintagestory.Client.ScreenManager.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   en Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   en Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   en Vintagestory.Client.ClientProgram.Main(System.String[])

 }
--------------
{ TimeGenerated = 02/03/2023 11:16:02 p. m., Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.17.9.0, marca de tiempo: 0x63501532
Nombre del módulo con errores: atio6axx.dll, versión: 6.14.10.11672, marca de tiempo: 0x54b54bdc
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x0000000000151375
Identificador del proceso con errores: 0x1730
Hora de inicio de la aplicación con errores: 0x01d94d8f3eb5a143
Ruta de acceso de la aplicación con errores: C:\Users\Aaron\Desktop\Vintage.Story.v1.17.9\Vintage.Story.v1.17.9\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\SYSTEM32\atio6axx.dll
Identificador del informe: da4734d5-bba0-4002-999d-2328b23c67cc
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }

**Comment by Craluminum2413** [comment]
Pirated versions of the game are not supported
