### ISSUE TITLE
Sod texture roof variants don't line up when inverted

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2426]
### Game Version

1.18.3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

See image & title

### Screenshots

![image](https://user-images.githubusercontent.com/13642054/222696515-eb87c983-9b9a-4fb1-af78-83559b7f8520.png)

### Logs

```Log```

**Comment by Balduranne** [comment]
Should be fixed now, thank you for reporting!

**Comment by Craluminum2413** [comment]
@Balduranne In 1.18.0-pre.5?
