### ISSUE TITLE
Bug with making fireplace on stockpile of firewood - cant make wooden coal

### ISSUE THREAD

**Issue by Eraed** [anegostudios/VintageStory-Issues#2428]
### Game Version

1.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After make a 2x2 stock pile of firewood i cant make a fireplace on this. I got information "This is not fireable block or item".

### Screenshots

![sc vintage bug](https://user-images.githubusercontent.com/127052724/222983133-49b78546-0536-4780-b18f-6c702db15f4b.jpg)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
I can't reproduce it
![image](https://user-images.githubusercontent.com/69315569/222983693-763c0c70-0fa8-408f-a2a2-3e0cdcbe0bc5.png)

**Comment by Eraed** [comment]
nope its pre. 1 maybe its a problem 
i will try to download it and give info

**Comment by Eraed** [comment]
On pre. 5 everything is fine, sorry for a problem ;)

**Comment by Craluminum2413** [comment]
It was fixed since 1.18.0-pre.3
