### ISSUE TITLE
Missing quickbar names with single-word items

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#243]
Playing on version 1.8.5. 
Items that have single-word names (Feather, stick, cattails) display a blank box when selected in the inventory because of how the game shortens those to just the "material" (Bottom of screenshot)
![screenshot 2019-01-13 11 58 50](https://user-images.githubusercontent.com/10406037/51088198-aa048900-172a-11e9-8d81-35130b3cb767.png)
Maybe it would be better to have the game display full names instead?

**Comment by tyronx** [comment]
hm. I cannot reproduce this issue in 1.8.6. It correctly displays all item names. Does it always happen to you (and also in 1.8.6?)

**Comment by Balduranne** [comment]
Still bugged in 1.8.6. Did you try testing it at a lower resolution percentage?

**Comment by tyronx** [comment]
Owww, at GUI scale 7 it happens. Thank you! Fixed for v1.9. Maybe also for a potential v1.8.7
