### ISSUE TITLE
v1.18.0-pre.5&6 - Translation issues

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2430]
### Game Version

v1.18.0-pre.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

In Crowdin, the source string:
`Contents: {0}x {1}
Temperature: {2}`

should be replaced by:
`Contents: {0}x {1}
Temperature: {2} °C`

### And also
![NotTranslated8](https://user-images.githubusercontent.com/26251843/223176201-3d0d88b8-79db-4b84-b25a-0d29a8116d0e.png)

![NotTranslated9](https://user-images.githubusercontent.com/26251843/223789133-27258fc7-dd90-4f8b-8177-fabe2037e96d.png)

![NotTranslated10](https://user-images.githubusercontent.com/26251843/223789719-bbd9bd16-7a95-4c70-9322-da4995cc97bc.png)

![NotTranslated11](https://user-images.githubusercontent.com/26251843/224310134-5010a97a-44c7-46c2-8bd5-07f88fb930d5.png)

![NotTranslated12](https://user-images.githubusercontent.com/26251843/224366543-85f0d10f-98c3-4125-b0d6-ec2a7c4878a4.png)

![NotTranslated13](https://user-images.githubusercontent.com/26251843/224491297-9a86e08c-d37f-46f3-9b5c-d2c5abcb61c4.png)

![NotTranslated14](https://user-images.githubusercontent.com/26251843/224531459-1df2e23f-b24f-407a-afc2-d39a7a4c0140.png)

![NotTranslated15](https://user-images.githubusercontent.com/26251843/225341034-d55ff424-e601-46e0-9ad5-19f5e5c19b5d.png)

![NotTranslated16](https://user-images.githubusercontent.com/26251843/225391830-c7d5db63-dddd-422f-9b98-f93b2b8aef3d.png)

![NotTranslated17](https://user-images.githubusercontent.com/26251843/225869972-77e60311-753e-4a4e-9718-52e09e39461d.png)

![NotTranslated18](https://user-images.githubusercontent.com/26251843/225960147-04ba59db-722d-4acf-b38d-45e291f54603.png)

![NotTranslated19](https://user-images.githubusercontent.com/26251843/227246799-cdc88607-4e3e-44db-b30c-98d0851bc3bf.png)

**Note** : I am using the 100% translated French .json file

**Comment by tyronx** [comment]
thanks a lot for the thorough report, will be fixed next release
