### ISSUE TITLE
lung capacity not working

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2434]
### Game Version

v1.18 pre 3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

when going under water it does not recognize that I'm underwater.  Check server settings and have lung capacity set for 40 seconds,  

### How to reproduce

as stated go into any deep water and lung capacity doesnt work

### Screenshots

![2023-03-06_12-14-42](https://user-images.githubusercontent.com/112742241/223198461-b74a070a-a942-41be-853d-4f2767bbe099.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
it was fixed in 1.18.0-pre.5
