### ISSUE TITLE
items (spears axes etc) can't lean against blocks 

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2435]
### Game Version

v1.18 pre 3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

tried to lean a spear and a axe against block items but will not,  if used with spear it will treat it like im throwing a spear when im standing or in crouch mode.  

### How to reproduce

have tool in hand and try to lean against any block will not work like in previous versions

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Did you hold both `shift` and `ctrl` keys?

**Comment by NITRO1623** [comment]
my apologies I did not sorry about that
