### ISSUE TITLE
lung capacity not working

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2436]
### Game Version

v1.18 pre 3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

when under deep water does not recognize and lung capacity does not turn on,  check my server setting on new world and lung capacity is set for 40 seconds,  got out of water reloaded save still same issue.  started another new world same issue.

### How to reproduce

enter and deep water lung capacity does not work 

### Screenshots

![2023-03-06_12-14-42](https://user-images.githubusercontent.com/112742241/223204711-363f801f-1467-4bc1-b118-00364f504505.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It was fixed in 1.18.0-pre.5
