### ISSUE TITLE
Infinite respawn of mobs

### ISSUE THREAD

**Issue by ivanpopelyshev** [anegostudios/VintageStory-Issues#2437]
### Game Version

v1.18-pre3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Look at the screenshot.

Only three cages were there. Maybe I dont know something about game mechanic, this thing was certainly endless

### How to reproduce

Find cages in caves. Have fun.

### Screenshots

![image](https://user-images.githubusercontent.com/695831/223213485-6d9fb597-447c-401e-883f-909158b82697.png)

**Comment by Craluminum2413** [comment]
Maybe some cage is hidden in blocks

**Comment by VallenFrostweaver** [comment]
I experienced this as well. Killed 50+ on a few stops to the same spot. Not sure if these are now endless either.

**Comment by ivanpopelyshev** [comment]
> Maybe some cage is hidden in blocks

They did stop only when i destroyed those three cages.

Before that, it looked like infinite spawn. Huge pile of corpses that are not despawning, hard to even fight being inside them

**Comment by VallenFrostweaver** [comment]
I agree. They can still attack you but you can't hit them due to the pile of corpses.

**Comment by Craluminum2413** [comment]
Fixed in 1.18.0-pre.7
