### ISSUE TITLE
axe durability of tool not effected by leaves on tree

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2438]
### Game Version

v1.18 pre 3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

when cutting down trees with not removing leaf stems the durability is only effected by how many tree logs are on tree,  please see below pics as durability was only minus three from the three tall log tree,  all leaves were on when tree was cut.  

1st pic shows tree

2nd pic shows durability of axe before cut 

3 pic after tree cut with durability

### How to reproduce

count log blocks on tree check durability before cutting tree down and dont take any leafs branches off

### Screenshots

![2023-03-06_13-43-51](https://user-images.githubusercontent.com/112742241/223215559-29e6c8d2-f904-4e8b-898a-792df1ef7929.png)
![2023-03-06_13-44-02](https://user-images.githubusercontent.com/112742241/223215788-d51386e1-9bb2-42bd-a2ac-d5d628ed696b.png)
![2023-03-06_13-44-24](https://user-images.githubusercontent.com/112742241/223215972-6860427d-89e8-4dde-af54-82725e3eab0c.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Do you mean that when you break 3 logs you lose 3 durability, and you are suggesting to make it lose durability from leaves as well?

**Comment by NITRO1623** [comment]
Correct in previous 1.17 when cutting down trees it affected the durability when the leaves were still on.  That's why shears were so important.  Now can cut any tree down with no real need of sheets to help compensate the durability lost.

**Comment by NITRO1623** [comment]
It does give you more sticks when shears are used but durability was a thing.  I would have to bring three to 4 axes when going on logging runs.  Now I cut that In half the amount.  Unless I am mistaken about the durability?
