### ISSUE TITLE
No way to check charcoal progress without particles 

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#244]
Not really a bug per se, but I play with particles turned down to 0 maximize performance. 
Would it be possible to add a way to know that your charcoal is done when you have those off? As it is, I have to turn them back on to know.

**Comment by tyronx** [comment]
Any suggestions?

**Comment by copygirl** [comment]
If looking at a block that contains the charcoal process, show a tooltip with the progress information? Could be implemented by hardcoding the tooltip checker for normal blocks to see if there's any "active" firewood blocks next to them and relaying the information.

**Comment by tatsu011** [comment]
.... keep the sound effect for the pit running was an idea I had in regards to this.  When the charcoal is done, we shouldn't be able to hear anything.

**Comment by Balduranne** [comment]
Sorry, Julie must have deleted the email notification; 
Sound is a good start, but I think the ideal option would be a texture overlay on the dirt block above the charcoal. Copygirl's idea with a tooltip sounds perfect too.

**Comment by tatsu011** [comment]
the soil around the charcoal could turn into a burned soil/burned grass that goes brown as the grass on top has died due to smoke and heat from the fire and when that block is broken drops a block of dirt with some effect on nutrient value?

**Comment by Balduranne** [comment]
> the soil around the charcoal could turn into a burned soil/burned grass that goes brown as the grass on top has died due to smoke and heat from the fire and when that block is broken drops a block of dirt with some effect on nutrient value?

Eh, I'd rather it was purely visual.

**Comment by Craluminum2413** [comment]
That's why it's worth using glass blocks for charcoal pit when you can afford it.

**Comment by copygirl** [comment]
Glass is not available to players early on.

**Comment by Craluminum2413** [comment]
True, but you can use glacier ice instead

**Comment by Craluminum2413** [comment]
Since we already have charcoal drawings, why not draw something on the topmost blocks above the pit?

**Comment by Balduranne** [comment]
> Since we already have charcoal drawings, why not draw something with charcoal on the topmost blocks above the pit?

My dude, how is is this in any way related to the issue at hand?

**Comment by Craluminum2413** [comment]
You can apply the charcoal pattern on the topmost blocks above the charcoal pit

**Comment by Balduranne** [comment]
> You can apply the charcoal drawing on the topmost blocks above the charcoal pit

You mean the game applying a charcoal overlay when it's done?

**Comment by Craluminum2413** [comment]
Yes. Is it possible to do it like you did with ItemCoal? There is drawnart etc.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
