### ISSUE TITLE
Terrain lighting issue

### ISSUE THREAD

**Issue by robert-bowman** [anegostudios/VintageStory-Issues#2442]
### Game Version

v1.18-pre3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Found a small pond that has a lighting issue.  Very dark.  Spotted it some distance away.

### Screenshots

![2023-03-05_15-51-16](https://user-images.githubusercontent.com/39417261/223317369-87b2188d-19d1-4e6b-87fc-fa8c5252002c.png)
![2023-03-05_16-35-04](https://user-images.githubusercontent.com/39417261/223317381-6d049724-3d16-49a5-9f48-234e05891d30.png)

### Logs

```Log```

**Comment by Davis1055** [comment]
I can second this, I have it in my current worlds as well! 
![2023-03-19_10-53-23](https://user-images.githubusercontent.com/109252883/226213082-f075f064-2892-4702-9fbf-7b3105610e1d.png)
![2023-03-19_10-53-38](https://user-images.githubusercontent.com/109252883/226213084-244c98f4-b9fc-4e23-baee-484291ec0799.png)
