### ISSUE TITLE
Wooden Tongs render very strangely

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2443]
### Game Version

1.18.0pre5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When holding the tongs they render behind the player.
![image](https://user-images.githubusercontent.com/13642054/223400041-fb1c3247-a935-4adb-8100-0649ad48fdc4.png)

When using them they hover above the player arm/hand.
![image](https://user-images.githubusercontent.com/13642054/223400086-ddff15de-8c22-4748-96e4-6205b0cc0061.png)

When holding tongs in off hand to pickup hot ingots the hot item renders in the right hand instead of the tongs and the tongs are separate.
![image](https://user-images.githubusercontent.com/13642054/223402231-792e6421-5498-419f-bb40-cbf6c0fa77c2.png)

Side note: Tongs name is "game:item-tongs" and not "wooden tongs" plus there is no obvious explanation on the item page that the tongs should be held in the off hand while handling hot items instead of the main hand.
![image](https://user-images.githubusercontent.com/13642054/223400433-d93f7b67-cc92-45e1-ba46-a5ac02ff5074.png)

### How to reproduce

Use wooden tongs.

**Comment by tyronx** [comment]
thanks for the report, should be fixed in pre6
