### ISSUE TITLE
Tutorials and Guides are all missing! Links to them don't work either.

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2444]
### Game Version

1.18.0pre5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I updated to pre5 from pre3.
Pressing H to open the survival handbook, 2 of the 4 tabs are empty. Clicking on links that might lead to these pages from items (like copper to click on "smithing") leads to bread.
Tutorials
![image](https://user-images.githubusercontent.com/13642054/223405154-63a0e608-836d-408b-a917-f17691e1919c.png)

Everything
![image](https://user-images.githubusercontent.com/13642054/223405198-ae124e07-680d-474c-9793-e0ceffdd71d3.png)

Guides
![image](https://user-images.githubusercontent.com/13642054/223405250-e9ed1d2f-d2b7-4077-bf6f-46544447b0fd.png)

Blocks and Items
![image](https://user-images.githubusercontent.com/13642054/223405294-c1853d1a-78fa-477a-af18-a008a7ba6000.png)

**Comment by jojobmomo** [comment]
Having this aswell

**Comment by tyronx** [comment]
thanks, should be fixed in pre6
