### ISSUE TITLE
animal damage / hunger damage

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2447]
### Game Version

v1.18 pre 5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

all animal damage is one hit one kill.  got attacked by a wolf killed me will full health points (20 pts)  got hit by sheep (ram)  full health at (21 pts)  instant kill.   slept the night off and woke up instant death do to lack of eating when food bar just went down to zero.  
also looked at server setting they are set at 
creature hostility (aggressive)  
creature strength (normal 100%)

### How to reproduce

make a sheep upset to hit you, 

walk by a wolf and say hello!

have half food bar then sleep the night away and will end up in a forever sleep

### Logs

```Log```

**Comment by tyronx** [comment]
please check the damage log after you died and make me a screenshot of it

**Comment by NITRO1623** [comment]
> please check the damage log after you died and make me a screenshot of it

I tried to get the same result I'm not able to duplicate this one again I haven't seen a wolf yet but the sheep now don't hit as hard so I'm assuming it's the same for wolves

**Comment by Craluminum2413** [comment]
What mods you had installed?

**Comment by WhittleBit** [comment]
I am having the same issue.  It's like there is no delay in the attacks.  The damage log shows 31 attacks doing 0.44 damage but it is delivered at one instant attack.
