### ISSUE TITLE
Unable To Modify Plant Tint Texture In A Mod

### ISSUE THREAD

**Issue by Novocain1** [anegostudios/VintageStory-Issues#245]
Example mod which should modify the planttint environment texture, I'm unsure if this also applies to other environment textures.
[PlantTintMod.zip](https://github.com/anegostudios/VintageStory-Issues/files/2784512/PlantTintMod.zip)

**Comment by tyronx** [comment]
Sometimes features like these take massive refactoring and other times you just need to move around a piece of code. In this case thankfully its the latter. Added for v1.9!
