### ISSUE TITLE
flowers / ferns deleted when ground block is dug

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2450]
### Game Version

v 1.18 pre 5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

whenever you dig the ground block out from under the flower it now deletes the fern or flower that was above it.  you get ground dirt but no items that were in it

### How to reproduce

find a flower or fern

dig block under it and item will delete

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is intended for fern
From 1.18.0-pre.1 changelog:
```
Tweak: Breaking soil under ferns now removes the fern
```

**Comment by Craluminum2413** [comment]
They even have `disappearOnSoilRemoved` attribute

**Comment by Craluminum2413** [comment]
Can't reproduce with flowers
