### ISSUE TITLE
Resonance Archives spawn underwater

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2453]
### Game Version

v1.18-pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The resonance archyves generated in the middle of the ocean. This made playing it feel like hell. Some areas were imposible to progress without using commands. The floor of the archives was made out of gravel which made it collapse when walked on. The boss arena was also damaged so fighting the boss was near impossible. Some blocks were also oddly waterlogged. Needless to say my first experience of the archives was completely ruined.

### How to reproduce

In world creator I set the oceans option to Very large lakes. This might have been the cause.

### Screenshots

!
![2023-03-08_18-09-46](https://user-images.githubusercontent.com/126715524/223781726-00c0c8c5-bd22-45bc-a72b-1e0b5d01d754.png)
[2023-03-08_16-23-44](https://user-images.githubusercontent.com/126715524/223780808-39de7367-8b41-426b-9fb4-295b5da11869.png)
![2023-03-08_16-28-29](https://user-images.githubusercontent.com/126715524/223780824-927a3536-f426-4a4f-b63d-31c523f7d331.png)
![2023-03-08_16-35-59](https://user-images.githubusercontent.com/126715524/223780886-bf2e1afb-b898-495d-b25a-170612bfa1f3.png)
![2023-03-08_16-36-03](https://user-images.githubusercontent.com/126715524/223780935-63c134a6-e3bb-42f5-a075-3b9dcc33119b.png)
![2023-03-08_16-37-35](https://user-images.githubusercontent.com/126715524/223780962-ba14f2b4-1215-40a9-b067-a95b7af63d44.png)
![2023-03-08_17-47-14](https://user-images.githubusercontent.com/126715524/223781098-fc099c95-3a36-4f41-8018-312f877882cc.png)
![2023-03-08_17-49-18](https://user-images.githubusercontent.com/126715524/223781341-894e8aeb-1964-4ca0-8517-75b676045dc0.png)
![2023-03-08_17-57-39](https://user-images.githubusercontent.com/126715524/223781639-fa6836b9-fa17-42a9-9aeb-77921e22f9ec.png)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this should be greatly mitigated in pre6
