### ISSUE TITLE
Creative mode middle-click not working correctly with full inventory

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#246]
If my hotbar is filled and I middle-click on something, the block I targeted gets put in my off-hand slot instead (And then the backpack slots, if you keep clicking). This only seems to happen once for every time you fill the hotbar, and having a light source in the off-hand slot prevents that, but it's still a little annoying.

**Comment by copygirl** [comment]
II also remember this somehow crashing me before when I did this.

**Comment by tyronx** [comment]
Thank you, fixed this now.
