### ISSUE TITLE
[1.17.11-rc.3] [.NET 7] Application Errors

### ISSUE THREAD

**Issue by Nyuhnyash** [anegostudios/VintageStory-Issues#2460]
|                  |                       |
|------------------|-----------------------|
| **Game version** | 1.17.11-rc.3 (.NET 7) |
| **Platform**     | Windows 11 22H2       |
| **Modded**       | Vanilla               |

# Description

#### How to reproduce:
Run `Vintagestory.exe --help` command

#### Error Message:
>The instruction at 0x00007FF8F407258A referenced memory at
>0x0000000000000000. The memory could not be read.
>
>Click on OK to terminate the program

#### Windows Event Log
```
Application: Vintagestory.exe
CoreCLR Version: 7.0.323.6910
.NET Version: 7.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.ClientProgram..ctor(String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 68
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 53
   at VintagestoryClientWindows.ClientWindows.Main(String[] args) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryClient\Windows\ClientWindows.cs:line 9
```

#### How to reproduce:
1. Launch the game
2. Hit "Quit" button (or <kbd>Alt</kbd> + <kbd>F4</kbd>)
3. The game freezes
4. Hit <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Delete</kbd>

#### Error Message:
>The exception unknown software exception (0x40000015) occurred in
>the application at location 0x00007FF94F2FF046.
>
>Click on OK to terminate the program

#### Logs
<details>
<summary>client-main.txt</summary>
<pre>
9.3.2023 18:51:38 [Notification] Client logger started.
9.3.2023 18:51:38 [Notification] Game Version: .net7 Experimental build - v1.17.11-rc.3 (Unstable)
9.3.2023 18:51:39 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
9.3.2023 18:51:39 [Notification] CPU Cores: 4
9.3.2023 18:51:39 [Notification] Available RAM: 19895 MB
9.3.2023 18:51:39 [Notification] Graphics Card Vendor: Intel
9.3.2023 18:51:39 [Notification] Graphics Card Version: 3.3.0 - Build 31.0.101.2111
9.3.2023 18:51:39 [Notification] Graphics Card Renderer: Intel(R) HD Graphics 530
9.3.2023 18:51:39 [Notification] Graphics Card ShadingLanguageVersion: 3.30 - Build 31.0.101.2111
9.3.2023 18:51:39 [Notification] GL.MaxVertexUniformComponents: 4096
9.3.2023 18:51:39 [Notification] GL.MaxUniformBlockSize: 65536
9.3.2023 18:51:39 [Notification] Cairo Graphics Version: 1.17.3
9.3.2023 18:51:39 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
9.3.2023 18:51:39 [Notification] C# Framework: .net 7.0.3
9.3.2023 18:51:39 [Notification] Start discovering assets
9.3.2023 18:51:39 [Notification] Found 21 base assets in category lang
9.3.2023 18:51:39 [Notification] Found 0 base assets in category patches
9.3.2023 18:51:39 [Notification] Found 22 base assets in category config
9.3.2023 18:51:39 [Notification] Found 0 base assets in category worldproperties
9.3.2023 18:51:39 [Notification] Found 46 base assets in category sounds
9.3.2023 18:51:39 [Notification] Found 97 base assets in category shapes
9.3.2023 18:51:39 [Notification] Found 80 base assets in category shaders
9.3.2023 18:51:39 [Notification] Found 16 base assets in category shaderincludes
9.3.2023 18:51:39 [Notification] Found 129 base assets in category textures
9.3.2023 18:51:39 [Notification] Found 4 base assets in category music
9.3.2023 18:51:39 [Notification] Found 0 base assets in category dialog
9.3.2023 18:51:39 [Notification] Found 415 base assets in total
9.3.2023 18:51:39 [Notification] Loading sounds
9.3.2023 18:51:39 [Notification] Sounds loaded
9.3.2023 18:51:39 [Notification] (Re-)loaded frame buffers
9.3.2023 18:51:39 [Notification] Loaded Shaderprogramm for render pass .
9.3.2023 18:51:39 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
9.3.2023 18:51:39 [Notification] (Re-)loaded frame buffers
9.3.2023 18:51:39 [Notification] Begin loading shaders
9.3.2023 18:51:39 [Notification] Load shaders now
9.3.2023 18:51:39 [Notification] Loading shaders...
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass standard.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass particlescube.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass particlesquad.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass sky.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass nightsky.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass woittest.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
9.3.2023 18:51:40 [Notification] Loaded Shaderprogramm for render pass helditem.
9.3.2023 18:51:41 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
9.3.2023 18:51:41 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
9.3.2023 18:51:42 [Notification] Loaded Shaderprogramm for render pass decals.
9.3.2023 18:51:42 [Notification] Loaded Shaderprogramm for render pass final.
9.3.2023 18:51:42 [Notification] Loaded Shaderprogramm for render pass gui.
9.3.2023 18:51:42 [Notification] Loaded Shaderprogramm for render pass blur.
9.3.2023 18:51:42 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
9.3.2023 18:51:42 [Notification] Loaded Shaderprogramm for render pass findbright.
9.3.2023 18:51:43 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
9.3.2023 18:51:43 [Notification] Loaded Shaderprogramm for render pass godrays.
9.3.2023 18:51:43 [Notification] Loaded Shaderprogramm for render pass autocamera.
9.3.2023 18:51:43 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
9.3.2023 18:51:43 [Notification] Loaded Shaderprogramm for render pass wireframe.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass entityanimated.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass luma.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass blit.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass texture2texture.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass celestialobject.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass colorgrade.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass guigear.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass ssao.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
9.3.2023 18:51:44 [Notification] Loaded Shaderprogramm for render pass grass.
9.3.2023 18:51:45 [Notification] Loaded Shaderprogramm for render pass flowers.
9.3.2023 18:51:45 [Notification] Loaded Shaderprogramm for render pass shadowgrass.
9.3.2023 18:51:45 [Notification] Loaded Shaderprogramm for render pass shadowflowers.
9.3.2023 18:51:45 [Notification] Cached session key is valid, validating with server
9.3.2023 18:51:47 [Notification] Server validation response: Good
9.3.2023 18:51:47 [Notification] Will search the following paths for mods:
9.3.2023 18:51:47 [Notification]     E:\Games\VintageStory-net7\Mods
9.3.2023 18:51:47 [Notification]     C:\Users\user\AppData\Roaming\VintagestoryDataNet7\Mods
9.3.2023 18:51:49 [Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed
</pre>
</details>

**Comment by Th3Dilli** [comment]
thank you for the report

Error 1
will be fixed with the next release

Error 2
it does take few seconds now for the application to fully close while that it is unresponsive but it should close on its own

**Comment by Th3Dilli** [comment]
Error 2 will be fixed in new version
