### ISSUE TITLE
Unable to create new world in single player v 1.17.11

### ISSUE THREAD

**Issue by TheMissLid** [anegostudios/VintageStory-Issues#2464]
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

**No Playstyles Found**
I  tried to create a single player world but the option to do so is not there. Under 'select a playstyle' it just says No Playstyles Found. I had mods enabled from multiplayer sessions so disabled all. Still no playstyles. I deleted all mods. Still no playstyles found. I uninstalled and reinstalled VS. Same result. I tried enabling the mods which came with the download. I then disabled them again. Same result. I restarted the game after each attempt to fix.
I can join modded multiplayer worlds with no trouble.
I pressed 'create world' to see what would happen and the game crashed with the following report: 
[VS crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/10937960/VS.crash.txt)

### How to reproduce

1. Launch game
2. go to single player
3. select create new world
4. rinse, repeat.

### Screenshots

![VS no playstyles](https://user-images.githubusercontent.com/127462214/224209266-03c5986a-e8ab-411d-914a-5a6407406c08.PNG)

### Logs

```Log```
I don't know if this is useful.
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10937987/client-main.txt)

**Comment by Craluminum2413** [comment]
Do you have anything in these folders?
`C:\Users\New PC\AppData\Roaming\Vintagestory\Mods`
`C:\Users\New PC\AppData\Roaming\VintagestoryData\Mods`

**Comment by TheMissLid** [comment]
Yes, I have both folders

**Comment by TheMissLid** [comment]
UPDATE:
I uninstalled, deleted both folders and changed the filepath to a new place. Reinstalling the game created the VintageStory folder in the new place but created a VintageStoryData folder in AppData, as before. I could successfully create a single player world. I could not add mods without crashing, though.

**Comment by DArkHekRoMaNT** [comment]
You probably have vanilla mods disabled

P.S. If you are still having issues with mods, more info is needed, and we can reopen it.
