### ISSUE TITLE
Worldedit Filler mode replacing certain blocks.

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2466]
### Game Version

v1.18pre3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Worldedit Filler mode boulders and stones are being replaced by each other and replaced by something like filllerblocks.

Mushrooms aswell.

### Screenshots

![2023-03-11_12-10-58](https://user-images.githubusercontent.com/100879715/224481045-4cdde011-66ea-4f41-8288-bcef4cb28fb5.png)

### Logs

None

**Comment by Craluminum2413** [comment]
There is a command that allows you to set whether replace blocks or not
https://wiki.vintagestory.at/index.php/How_to_use_WorldEdit#Flood_Fill_Tool

**Comment by AreYSerious** [comment]
Good to know ty

/we trl 7000 did it for me
