### ISSUE TITLE
Crash at Ending Game

### ISSUE THREAD

**Issue by Thor8472** [anegostudios/VintageStory-Issues#2469]
### Game Version

v.1.18pre6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Just by ending the game!

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
12.03.2023 17:29:19: Critical error occurred
Loaded Mods: 
System.NotImplementedException: Die Methode oder der Vorgang ist nicht implementiert.
   bei Vintagestory.GameContent.EntityBoat.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:Zeile 482.
   bei Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 556.
   bei Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:Zeile 2621.
   bei Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:Zeile 2536.
   bei Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:Zeile 323.
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:Zeile 304.
   bei Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:Zeile 677.
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:Zeile 292.
   bei Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:Zeile 440.
   bei Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:Zeile 564.
   bei Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:Zeile 388.
   bei Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:Zeile 416.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:Zeile 229.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:Zeile 808.
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:Zeile 1551.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 369.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07.03.2023 19:58:18, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.0.0, Zeitstempel: 0x6405c8b8
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.2546, Zeitstempel: 0xe8e9ac9b
Ausnahmecode: 0xc000041d
Fehleroffset: 0x000000000002cd29
ID des fehlerhaften Prozesses: 0x384
Startzeit der fehlerhaften Anwendung: 0x01d95120fbe84aab
Pfad der fehlerhaften Anwendung: C:\Users\Thor\AppData\Roaming\Vintagestory1.18pre\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 2f37d7d2-35d6-4412-a526-a0a7cf04dcb0
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.03.2023 19:58:14, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.0.0, Zeitstempel: 0x6405c8b8
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.2546, Zeitstempel: 0xe8e9ac9b
Ausnahmecode: 0xc0020001
Fehleroffset: 0x000000000002cd29
ID des fehlerhaften Prozesses: 0x384
Startzeit der fehlerhaften Anwendung: 0x01d95120fbe84aab
Pfad der fehlerhaften Anwendung: C:\Users\Thor\AppData\Roaming\Vintagestory1.18pre\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 3f25c897-d933-402b-87c1-36c7e9dee3d4
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 07.03.2023 19:58:13, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFEB414CD29
Stapel:
 }

**Comment by Craluminum2413** [comment]
Duplicate of #2465
