### ISSUE TITLE
Please allow to change color of character's underwear in "Character" screen

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#247]
Please consider this minor enhancement.

1. Some people prefer to wear colorful underwear, not the default grey.
2. Some clothing like straps or belts may look better with underwear of other colors.

Ofc this may raise question of changing underwear color in-game, support of which will be too much for such a minor feature.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
