### ISSUE TITLE
Hail storm in warm climate 

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2474]
### Game Version

V1.18 PRE 6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

walked into a hail storm and took damage (really awesome feature!!)  but Im in the warm climate and in middle of summer.  also this is brand new world started 5 min in to playing

### Screenshots

![2023-03-13_13-34-38](https://user-images.githubusercontent.com/112742241/224798703-3be055fd-0ed5-46d3-ab2a-a6011e1dc7c3.png)
![2023-03-13_13-34-48](https://user-images.githubusercontent.com/112742241/224798764-0ab1bd16-cb1c-40d7-bbf7-889e12c10cdb.png)
![2023-03-13_13-39-16](https://user-images.githubusercontent.com/112742241/224798881-2a91d9fb-2517-4ef4-9f58-880d4643c767.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What is wrong?

**Comment by NITRO1623** [comment]
Is it part of the game to have hail storms in middle of summer near a desert?  Just never had that before seemed like weather was glitched.  When I  exit and reloaded game it was just rain when I reloaded save

**Comment by EnigmaticaGH** [comment]
Hail can happen in any climate. Read more here: https://www.nssl.noaa.gov/education/svrwx101/hail/

**Comment by DArkHekRoMaNT** [comment]
I think it should be closed. No problems with hail in summer @Craluminum2413
