### ISSUE TITLE
v1.17.11 - Multiplayer crash/Server crash

### ISSUE THREAD

**Issue by spielerflo97330** [anegostudios/VintageStory-Issues#2477]
### Game Version

v1.17.11

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

the vintage story instance is crashing every time, i join multiplayer servers [modded]. it doesnt request me to download the mods on the server, it just crashes. i already deinstalled vintage story, but nothing happens, it still crashes and i already tried everything. i'm hoping someone can help me
heres the crash:
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
14.03.2023 20:41:05: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:Zeile 407.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 718.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 622.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 124.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14.03.2023 20:38:30, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.11.0, Zeitstempel: 0x63e108be
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22000.318, Zeitstempel: 0x095a2f2a
Ausnahmecode: 0xc000041d
Fehleroffset: 0x000000000004466c
ID des fehlerhaften Prozesses: 0x704
Startzeit der fehlerhaften Anwendung: 0x01d956ac764d317c
Pfad der fehlerhaften Anwendung: C:\Users\justu\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 1773fcd8-a9a8-4d91-a487-6145b3fe065b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 14.03.2023 20:38:29, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.11.0, Zeitstempel: 0x63e108be
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22000.318, Zeitstempel: 0x095a2f2a
Ausnahmecode: 0xc0020001
Fehleroffset: 0x000000000004466c
ID des fehlerhaften Prozesses: 0x704
Startzeit der fehlerhaften Anwendung: 0x01d956ac764d317c
Pfad der fehlerhaften Anwendung: C:\Users\justu\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: df43a71b-5f05-4586-a589-04a3cedc7498
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 14.03.2023 20:38:29, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFCACAC466C
Stapel:
 }

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #2380
