### ISSUE TITLE
visual gltich with tuning cylinder

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2478]
### Game Version

V1.18 PRE 6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

when putting the tuning cylinder in the vertical stand item does now show in the stand,  item is able to be removed from stand and put back in but does not show.  picked up  vertical stand and put item back in still the same

### Screenshots

![2023-03-14_16-56-55](https://user-images.githubusercontent.com/112742241/225151043-f934a3b7-545b-4ae3-948f-1aa7bef725db.png)
![2023-03-14_16-56-59](https://user-images.githubusercontent.com/112742241/225151083-d97b6a11-c161-44ce-a515-3a263b27faa3.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
1.18.0-pre.8: Disabled racking of tuning cylinders on vertical racks
