### ISSUE TITLE
Add numbers to the hotbar

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#248]
I think it would be great if we could have numbers on the hotbar, so you can see which item corresponds to which number hotkey. It's a minor thing, but it improve my QoL to faster identify what I'm trying to select.

**Comment by tyronx** [comment]
Your wish is my command!
![2019-02-05_19-41-18](https://user-images.githubusercontent.com/762006/52296202-110a0c00-297e-11e9-967b-98d317213bb9.png)

**Comment by copygirl** [comment]
Does this show the alternate keyboard shortcuts when using non-default keybinds?

**Comment by tyronx** [comment]
Ops. I forgot about that part, thanks for pointing it out. I made it respect current keybinds now.

**Comment by copygirl** [comment]
Looking at the screenshot, would it be possible for it to be slightly fainter and using a bold font? I feel like it would fit slightly better.

**Comment by Balduranne** [comment]
Could you make the number be visible above the item? Thanks for adding it <3
