### ISSUE TITLE
World option "Always Spring" does not work, seasons progress anyway

### ISSUE THREAD

**Issue by lOmicronl** [anegostudios/VintageStory-Issues#2480]
### Game Version

v1.17.9 onwards (estimated), up to and including v1.18.0-pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Multiple people have been asking about this on Discord, Reddit and the forums for a month or two now; it broke sometime late in the 1.17 cycle and continues to be broken in the 1.18 prereleases.

I am not personally affected (I don't run with seasons off), but I'm raising this issue so that it is on the tracker.

References:
https://www.reddit.com/r/VintageStory/comments/10rw4wu/turning_off_seasons_doesnt_seem_to_work/
https://www.vintagestory.at/forums/topic/10564-turnign-off-seasons-when-making-a-custom-setting-world-doesnt-seem-to-work/
https://www.vintagestory.at/forums/topic/10672-seasons-off-always-spring-does-not-work-singleplayer/
https://www.vintagestory.at/forums/topic/10530-always-spring/

**Comment by tyronx** [comment]
thanks for the report! this should be fixed next release. Also added summer, fall and winter as options
