### ISSUE TITLE
Crash upon creating new world

### ISSUE THREAD

**Issue by Shadeloid** [anegostudios/VintageStory-Issues#2482]
### Game Version

1.18.0 pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When i'm trying to enter a previous world or creatting a new one, the game crashes on me. Stating that "Specified conversion isn't valid"

### How to reproduce

1.Create/or enter a previous world
2. After some time, it crashes

### Logs

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
16-03-2023 15:07:13: Critical error occurred
Loaded Mods: 
System.InvalidCastException: A conversão especificada não é válida.
   em Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() em VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   em Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) em VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 316
   em Vintagestory.Client.ScreenManager.Render(Single dt) em VintagestoryLib\Client\ScreenManager.cs:line 717
   em Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) em VintagestoryLib\Client\ScreenManager.cs:line 620
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) em VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   em System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   em OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) em C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   em OpenTK.GameWindow.DispatchRenderFrame() em C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   em OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) em C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   em Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   em Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) em VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 09-03-2023 10:00:04, Site = , Source = Application Error, Message = Nome da aplicação com falha: Vintagestory.exe, versão: 1.17.11.0, carimbo de data/hora: 0x638f99ee
Nome do módulo com falha: openal32.dll, versão: 1.23.0.0, carimbo de data/hora: 0x63dd31ad
Código de exceção: 0x40000015
Desvio de falha: 0x00000000000df046
ID do processo com falha: 0x4a0
Hora de início da aplicação com falha: 0x01d9526ddbed1a29
Caminho da aplicação com falha: C:\Users\admin\AppData\Roaming\VintageStoryNET7\Vintagestory\Vintagestory.exe
Caminho do módulo com falha: C:\Users\admin\AppData\Roaming\VintageStoryNET7\Vintagestory\Lib\openal32.dll
ID do Relatório: ec0abc00-6c8f-4d4d-9d9a-914c40eb0d84
Nome completo do pacote com falha: 
ID da aplicação relativa ao pacote com falha:  }
--------------
{ TimeGenerated = 09-03-2023 09:58:03, Site = , Source = Application Error, Message = Nome da aplicação com falha: Vintagestory.exe, versão: 1.17.11.0, carimbo de data/hora: 0x638f99ee
Nome do módulo com falha: openal32.dll, versão: 1.23.0.0, carimbo de data/hora: 0x63dd31ad
Código de exceção: 0x40000015
Desvio de falha: 0x00000000000df046
ID do processo com falha: 0x287c
Hora de início da aplicação com falha: 0x01d9526d789a0b53
Caminho da aplicação com falha: C:\Users\admin\AppData\Roaming\VintageStoryNET7\Vintagestory\Vintagestory.exe
Caminho do módulo com falha: C:\Users\admin\AppData\Roaming\VintageStoryNET7\Vintagestory\Lib\openal32.dll
ID do Relatório: 1eef46c6-6884-4e11-b3da-192cbd8b2fe3
Nome completo do pacote com falha: 
ID da aplicação relativa ao pacote com falha:  }
--------------
{ TimeGenerated = 28-11-2022 03:28:06, Site = , Source = Application Hang, Message = A versão 1.17.9.0 do programa Vintagestory.exe deixou de interagir com o Windows e foi fechada. Para verificar se existem mais informações sobre o problema, consulte o histórico de problemas no painel de controlo de Segurança e Manutenção.

ID do Processo: 6e8

Hora de Início: 01d902d1a4a4eda3

Hora de Cessação: 114

Caminho da Aplicação: C:\Users\admin\AppData\Roaming\Vintagestory\Vintagestory.exe

Id do Relatório: 5e1a349d-b8cf-4200-823e-067b868a7d8f

Nome completo do pacote com falhas: 

ID da aplicação relacionada com o pacote com falhas: 

Tipo de bloqueio: Unknown
 }

**Comment by Craluminum2413** [comment]
Duplicate of #2380
