### ISSUE TITLE
Fehler bei flüssigen Erzen oder auch fertigen Barren

### ISSUE THREAD

**Issue by SlrHui** [anegostudios/VintageStory-Issues#2483]
### Game Version

v1.18.pre-6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Ab der Version pre-4 gibt es folgenden Fehler. Wenn ich das Gefäß mit dem flüssigen Erz nehmen will wird es auf mich geschmissen und verursacht Schaden. Immer wenn ich in die Nähe gehe. Auch bei Barren ist es so.
Wenn ich pre-3 aufrufe gibt es den Fehler nicht. Aber ab pre-4 bei allen Versionen bis zu aktuellen Version.
Habe die Welt auch schon unter pre-6 neu erstellt, keine Änderung.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
English please

**Comment by SlrHui** [comment]
From version pre-4 there is the following error. When I want to take the jar with the liquid ore it is thrown at me and causes damage. Whenever I go near it. It is also the same with ingots.
When I call pre-3 there is no error. But from pre-4 on all versions up to the current version.
Have also already recreated the world under pre-6, no change.

**Comment by Craluminum2413** [comment]
@SlrHui you need wooden tongs in order to hold very hot items
