### ISSUE TITLE
Сhiseling crash

### ISSUE THREAD

**Issue by NeksAltrein** [anegostudios/VintageStory-Issues#2488]
### Game Version

1.18.0-pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When a chiseled block is added to another chiseled block, its texture is selected, and the microblock is placed, a crash occurs.

### How to reproduce

1) Another chiseled block of horizontal boards is added to the chiseled block of vertical boards by means of a crafting grid.
2) The texture of horizontal boards is selected for chiseling.
3) The microblock of the main texture of vertical boards is removed.
4) When the microblock texture of horizontal boards is placed in an empty space, a failure occurs.

### Screenshots

![изображение](https://user-images.githubusercontent.com/128229284/226106146-ac3a19a9-3116-446b-abf5-15f10b6b4483.png)
![изображение](https://user-images.githubusercontent.com/128229284/226106173-103d7f2f-9f98-457c-af79-62313a6e2f53.png)
![изображение](https://user-images.githubusercontent.com/128229284/226106289-fe1e3b61-67b5-4b98-b2ce-9f4f903e5c22.png)
![изображение](https://user-images.githubusercontent.com/128229284/226106514-80590653-8a24-4a52-837d-93983ee28f8b.png)
![изображение](https://user-images.githubusercontent.com/128229284/226106529-74d87fc2-612d-48d9-9304-b12f4eb9e040.png)

### Logs

```Log```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
18.03.2023 19:36:57: Critical error occurred
Loaded Mods: game@1.18.0-pre.6, creative@1.18.0-pre.6, survival@1.18.0-pre.6
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Vintagestory.GameContent.BlockEntityChisel.SetVoxel(Vec3i voxelPos, Boolean add, IPlayer byPlayer, Byte materialId) в VSSurvivalMod\Systems\Microblock\BEChisel.cs:строка 255
   в Vintagestory.GameContent.BlockEntityChisel.UpdateVoxel(IPlayer byPlayer, ItemSlot itemslot, Vec3i voxelPos, BlockFacing facing, Boolean isBreak) в VSSurvivalMod\Systems\Microblock\BEChisel.cs:строка 114
   в Vintagestory.GameContent.BlockEntityChisel.OnBlockInteract(IPlayer byPlayer, BlockSelection blockSel, Boolean isBreak) в VSSurvivalMod\Systems\Microblock\BEChisel.cs:строка 104
   в Vintagestory.GameContent.ItemChisel.OnBlockInteract(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, Boolean isBreak, EnumHandHandling& handling) в VSSurvivalMod\Item\ItemChisel.cs:строка 323
   в Vintagestory.GameContent.ItemChisel.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) в VSSurvivalMod\Item\ItemChisel.cs:строка 236
   в Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) в VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:строка 836
   в Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel) в VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:строка 811
   в Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) в VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:строка 540
   в Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) в VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:строка 89
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) в VintagestoryLib\Client\Util\ClientEventManager.cs:строка 199
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) в VintagestoryLib\Client\ClientMain.cs:строка 778
   в Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) в VintagestoryLib\Client\ClientMain.cs:строка 970
   в Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) в VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:строка 243
   в Vintagestory.Client.ScreenManager.Render(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 717
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 620
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 126
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 479
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 454
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 18.03.2023 18:01:43, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.0.0, метка времени: 0x640994ff
Имя сбойного модуля: unknown, версия: 0.0.0.0, метка времени: 0x00000000
Код исключения: 0x00000000
Смещение ошибки: 0x0000000000000000
Идентификатор сбойного процесса: 0x501c
Время запуска сбойного приложения: 0x01d9597c38cece30
Путь сбойного приложения: E:\1) Games\Vintagestory\Vintagestory.exe
Путь сбойного модуля: unknown
Идентификатор отчета: b7272e25-b032-40e2-ba85-7409642a0bd2
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 18.03.2023 18:01:42, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0020001, адрес исключения 00007FFF7F6DCD29
Стек:
 }

**Comment by tyronx** [comment]
thanks for the report! this should be fixed next release

**Comment by NeksAltrein** [comment]
Is it possible to add a more convenient way to rotate additional textures in chiseled blocks? Drag and drop of chiseled blocks does not work, you have to use a crafting grid.
