### ISSUE TITLE
Keys "/" and "." should start chat typing too, like "T"

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#249]
In many games which use "/" symbol as a chat command identifier, pressing it immideatly opens chat window with focus on it and "/" symbol already typed.
This makes entering commands more comfortable and intuitive.
VS already has the nice shortcut for chatting - "T".
Please consider adding "/" and "." symbols for server and client commands with similar behavior:
chat is opened, the corresponding symbol is added to the input line and typing cursor is placed right after it, ready to accept typed text.

**Comment by tyronx** [comment]
k k k. Added now for v1.9.
