### ISSUE TITLE
Cracked Rock types don't register as rock to the Prospecting Pick

### ISSUE THREAD

**Issue by Haakkkoorn** [anegostudios/VintageStory-Issues#2492]
### Game Version

v1.18pre6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When prospecting in either of the two modes the pick does not register cracked rock variants as rock.

### How to reproduce

break a block with a prospecting pick.

### Logs

```Log```

**Comment by EnigmaticaGH** [comment]
Can confirm in pre7 with unmodded client.

**Comment by CookieBoy21** [comment]
I tested it in 1.20 pre4. Issue is no more.

**Comment by Craluminum2413** [comment]
@CookieBoy21 what exactly?

**Comment by CookieBoy21** [comment]
I mean prospecting pick after use for breaking cracked rocks in any searching mode showing info like during breking normal rocks, so it's fixed?
