### ISSUE TITLE
New clutter pipes not spawning correctly oriented in worldgen

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2494]
### Game Version

v1.18 pre3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

![2023-03-19_21-12-51](https://user-images.githubusercontent.com/100879715/226206390-d9c76123-a16a-48f9-a01c-a92c35e17f7a.png)

Most of the new clutter blocks like the pipes don't spawn with the right rotation.
The new destroyed double crates have the same problem 

### Logs

None

**Comment by Th3Dilli** [comment]
thank you for the report

that should be fixed by now already

**Comment by Th3Dilli** [comment]
this is still an issue, I was testing it wrong with horizontally rotated pipes and the issue is with vertically rotated pipes, may happen to other blocks with similar feature as well

**Comment by Th3Dilli** [comment]
these seem related #1974, #2926, #2798

**Comment by Th3Dilli** [comment]
this should be fixed with next 1.19 pre
