### ISSUE TITLE
New 1.18 tools are resistant to storage.

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#2498]
As of 1.18.0 pre.7, Crude Oars and Tongs seem to only be able to be stashed in chests/baskets/etc.

Not such a big deal for tongs since you're usually nearby some storage, but not being able to lean the oar up against a tree like you can a shovel or axe is a bit surprising.

**Comment by Craluminum2413** [comment]
Fixed for oars in 1.18.0-rc.1

**Comment by TomCatFort** [comment]
I have checked a bunch of items under the Tools section in 1.18.0-rc.2, and found that the following ones are not ground storeable:
 * Wooden tongs.
 * Ink and quill.
 * Sling.
 * Helve hammer.
 * Arrow.

I do not think that helve hammers or arrow are necessary, unless for decoration.
But wooden tongs, and the ink and quill would be nice to be ground storeable.
The sling can already be stored on tool racks.

**Comment by Craluminum2413** [comment]
Tongs are now ground storable
