### ISSUE TITLE
Crash on LAN game exit (with one other person)

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2504]
### Game Version

1.18.0pre6

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

I have StepUp and VSCCI installed for mods. That's it besides the vanilla stuff.
When exiting the game after a LAN game it crashes with this result: 

[Hastebin link](https://hastebin.com/share/tecajuyube.yaml)

**Comment by Craluminum2413** [comment]
Duplicate of #2465
