### ISSUE TITLE
Sod roofing corner (inner) is too small

### ISSUE THREAD

**Issue by Haakkkoorn** [anegostudios/VintageStory-Issues#2507]
### Game Version

1.18pre7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The inner corner is slightly too small, letting you see through the sides and letting light out/in.

### How to reproduce

Place an inner corner with other roof pieces. It doesn't meld seamlessly

### Screenshots

![2023-03-23_14-56-17](https://user-images.githubusercontent.com/128313891/227302208-59451d1b-01e2-42b0-a8c1-fbe13fbe5e22.png)
![2023-03-23_14-56-12](https://user-images.githubusercontent.com/128313891/227302231-923cad0d-63fb-4ac1-9303-d1adc460190d.png)

**Comment by Craluminum2413** [comment]
Fixed in 1.18.0-rc.1
