### ISSUE TITLE
Crash when read a book

### ISSUE THREAD

**Issue by venkom** [anegostudios/VintageStory-Issues#2509]
### Game Version

v 1.18

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### How to reproduce

Кead news about Jonas or something like that

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable) by OverF1X  
24.03.2023 21:06:32: Critical error occurred
Loaded Mods: game@1.18.0-pre.6, creative@1.18.0-pre.6, survival@1.18.0-pre.6
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.GameContent.BlockMultiblock.OnBlockInteractCancel(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumItemUseCancelReason cancelReason) в VSEssentials\Block\BlockMultiblock.cs:строка 0
   в Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   в Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   в Vintagestory.Client.ScreenManager.Render(Single dt)
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 476
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 452
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by Craluminum2413** [comment]
The pirated versions of the game are not supported
