### ISSUE TITLE
Make the dirt layer thicker

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#251]
Okay, I've been nagging about this a lot in Discord, but let's make this official: Increase the thickness of the dirt level before you reach stone. 
It just seems too thin, and doesn't make any sense to me.

Other than being a little immersion breaking... More dirt means it would be easier to landscape without having to raze a hill. Not having to rely on pickaxes so much to flatten an area.
That way you could also have deeper clay/peat deposits. They should have a layer of dirt under them. It never made sense to me that they're right on top of stone.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by copygirl** [comment]
The thickness of the dirt layer actually depends on the area you're in, I think.
