### ISSUE TITLE
Tooltips are not formatted properly and cut off parts

### ISSUE THREAD

**Issue by maritz** [anegostudios/VintageStory-Issues#2513]
### Game Version

v1.18-pre7

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

A lot of tooltips in the game are not formatted properly (line breaks appear random) and then parts of it on the right are cut off as well.

I tried different UI scales and it made no difference.

### Screenshots

![image](https://user-images.githubusercontent.com/159633/227911068-60c6ca86-8307-45d1-abd6-517434fe566b.png)
![image](https://user-images.githubusercontent.com/159633/227912757-280a71e4-ccd1-4954-b118-894972714db9.png)

**Comment by EnigmaticaGH** [comment]
Same for me on Windows 10 64bit with RTX 2060 and 10th gen intel i7 laptop.

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release

**Comment by maritz** [comment]
Can confirm, it is fixed in v1.18-pre8.

(which btw is committed on the vssurvivalmod repo as pre9, doesn't really matter though)

**Comment by tyronx** [comment]
yea, mistyped there
