### ISSUE TITLE
GameTotalCrash after trying to join Modded multiplayer [v1.17.11]

### ISSUE THREAD

**Issue by spielerflo97330** [anegostudios/VintageStory-Issues#2514]
### Game Version

v1.17.11

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

FIRST THING, GIVE ME A SOLUTION AND DON'T CLOSE THIS POST, BECAUSE IT IS SIMILAR TO OTHERS!!! 

Crash: After Vintage story stopped working 3 weeks ago, i finally need help now, i hope someone knows about this error, and has a solution for it: whenever i want to join a certain multiplayer server (i'm not the owner, the server has mods; modded multiplayer), my game crashes right after i try to join, and that log is what i get.. i've already tried to reinstall vintage story about 6 times, tried to fix KERNELBASE.dll, and updatet every programm, that could be helpful... i don't want to loose all my progress, please help.

### How to reproduce

1. Start VS
2. Click Multiplayer
4. Click on a Server (modded;from Other Players)
5. Click Play
7. crash

### Logs

```Log```

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
27.03.2023 16:27:13: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:Zeile 407.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 718.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 622.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 124.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27.03.2023 15:22:38, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.11.0, Zeitstempel: 0x63e108be
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22000.318, Zeitstempel: 0x095a2f2a
Ausnahmecode: 0xc000041d
Fehleroffset: 0x000000000004466c
ID des fehlerhaften Prozesses: 0x13f4
Startzeit der fehlerhaften Anwendung: 0x01d960af29a6668f
Pfad der fehlerhaften Anwendung: C:\Users\Unsolved\AppData\Roaming\VS\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: b67d514d-3a24-4d70-b68f-7b8dae543777
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 27.03.2023 15:22:37, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.11.0, Zeitstempel: 0x63e108be
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22000.318, Zeitstempel: 0x095a2f2a
Ausnahmecode: 0xc0020001
Fehleroffset: 0x000000000004466c
ID des fehlerhaften Prozesses: 0x13f4
Startzeit der fehlerhaften Anwendung: 0x01d960af29a6668f
Pfad der fehlerhaften Anwendung: C:\Users\Unsolved\AppData\Roaming\VS\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 0e7d9a6a-27ba-4a0c-984a-1ff76458891b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 27.03.2023 15:22:37, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFF4366466C
Stapel:
 }

**Comment by Craluminum2413** [comment]
Duplicate of #2380

**Comment by Craluminum2413** [comment]
It is completely the same crash
