### ISSUE TITLE
Quote translation is wrong. (only needs quick review. fix included and linked via crowdin)

### ISSUE THREAD

**Issue by Pengwin83** [anegostudios/VintageStory-Issues#2516]
### Game Version

v.1.17.pre-7

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

The german translation is wrong. "Lead" is translated with "Blei". But the original quote relates to "leading" not the chemical element "lead".
I provided the correct translation/fix here:
https://crowdin.com/translate/vintage-story-game/2/en-de?filter=basic&value=3#5796

### Logs

```Log```

**Comment by tyronx** [comment]
hey, thanks but no need to report this as an issue. I usually re-download translations on every update. Thanks for fixing it!
