### ISSUE TITLE
v1.18.0-pre. 8 - Translation issues

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2517]
### Game Version

v1.18.0-pre.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Typo in Crowdin for an item
![Hourglass](https://user-images.githubusercontent.com/26251843/228250260-78d3f9bf-c61a-4a59-b3e0-75b9a4044a73.png)

### Not translated
![NotTranslated20](https://user-images.githubusercontent.com/26251843/228266535-f1615a57-ac44-40a6-8515-f84e456c58e7.png)

![NotTranslated21](https://user-images.githubusercontent.com/26251843/228486540-61589a71-f565-47e7-a25e-ed8da3ad4ed3.png)
The other tapestries are not translated either.

![NotTranslated22](https://user-images.githubusercontent.com/26251843/228596748-975a5d85-97aa-4eb6-9b18-d11f8370b8ec.png)

![NotTranslated23](https://user-images.githubusercontent.com/26251843/228792697-46628c40-a5ea-4646-a10e-6dc1e20b3e3c.png)

![NotTranslated24](https://user-images.githubusercontent.com/26251843/228792731-f6f76846-4cd6-4ae5-8d40-224c470416e5.png)

![NotTranslated25](https://user-images.githubusercontent.com/26251843/229277679-48852e0c-5385-4e35-98ad-04aec205f37f.png)

![NotTranslated26](https://user-images.githubusercontent.com/26251843/231253556-d6924a4c-75ee-498d-a49a-060dfda751ea.png)

![NotTranslated27](https://user-images.githubusercontent.com/26251843/232247773-d9fd9a7d-f9af-47ad-ac50-cfa4e2543f1a.png)

Please note that when I say "not translated" it means that there is no way to translate them in Crowdin because they are not there to be translated. Same with my previous messages. Total : 26 reported for 1.18 since the pre versions.

**Comment by tyronx** [comment]
thanks for the reports, should be fixed next release
