### ISSUE TITLE
First Character in Books and Lore - v1.18pre7

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2520]
### Game Version

v1.18pre7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The first character in some lines do not display or are invisible. See Screenshots

### How to reproduce

Look at the Journal or a lore piece that opens up like a book.

### Screenshots

![image](https://user-images.githubusercontent.com/100879715/228645665-9e81637d-4a1b-4e49-aea9-48e85e0ac4eb.png)

### Logs

```None```

**Comment by Craluminum2413** [comment]
Update to 1.18.0-pre.8

**Comment by AreYSerious** [comment]
Ok thank you
