### ISSUE TITLE
Lore and Books not showing text correctly

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2522]
### Game Version

v1.18pre8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It was told that this was fixed with pre 8, but it isn't?
After the second line in each paragraph, the first character is invisible or not displayed, this goes for all journal entries and books. 

![image](https://user-images.githubusercontent.com/100879715/228924717-fe86439e-8c90-4a57-8294-1e2a97e69491.png)

### How to reproduce

Just open a lore item and look at it or use the journal.

### Screenshots

![image](https://user-images.githubusercontent.com/100879715/228924726-ef59d58e-bc64-438a-a7f6-0443b525deca.png)
![image](https://user-images.githubusercontent.com/100879715/228924816-de9d5162-dac2-4443-88f1-1cafa822fd6f.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Why you closed it?

**Comment by AreYSerious** [comment]
Bcs I had a wrong link to a different vs startup so it didn't launch the correct version my bad
