### ISSUE TITLE
Can breathe underwater with lantern, ladder etc.

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2526]
### Game Version

1.18.0-pre.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

1. Dig 2 block deep hole underwater
2. Place lantern on the block where player's eyes are located
3. You are breathing underwater now

### Screenshots

![image](https://user-images.githubusercontent.com/69315569/229297877-600184bc-2f06-4eb1-a446-4d67ef3b9f77.png)

**Comment by radfast** [comment]
Thanks for reporting :)  Fixed in next update
