### ISSUE TITLE
Hitting Stone Rubble with Axt ( or hand) at teleporter --> Crash!

### ISSUE THREAD

**Issue by Thor8472** [anegostudios/VintageStory-Issues#2527]
### Game Version

v.1.18pre8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.8 (Unstable)
02.04.2023 09:31:42: Critical error occurred
Loaded Mods: game@1.18.0-pre.8, creative@1.18.0-pre.8, survival@1.18.0-pre.8
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockShapeFromAttributes.GetOrCreateMesh(IShapeTypeProps cprops, ITexPositionSource overrideTexturesource, String overrideTextureCode) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:Zeile 431.
   bei Vintagestory.GameContent.BlockShapeFromAttributes.GetDecal(IWorldAccessor world, BlockPos pos, ITexPositionSource decalTexSource, MeshData& decalModelData, MeshData& blockModelData) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:Zeile 419.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 262.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 206.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 168.
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 378.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 795.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 596.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 86.
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 201.
   bei Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:Zeile 785.
   bei Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:Zeile 977.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 241.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 722.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 625.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 119.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

**Comment by Thor8472** [comment]
still a thing in 1.18 rc1 doesnt matter witch tool!

**Comment by stony99** [comment]
Breaking a wooden aged crate might cause this too, but not always. v1.18-rc2

**Comment by Craluminum2413** [comment]
> Breaking a wooden aged crate might cause this too, but not always. v1.18-rc2

Maybe you broke wooden aged crate and accidentally hit another block

**Comment by stony99** [comment]
Yeah, I probably hit that invisible Stone Rubble. Can´t replicate this just by breaking aged crates.
