### ISSUE TITLE
Black Guard cuirass repair seems bugged

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2528]
### Game Version

v1.18.0-pre.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The recipe to repair a Blackguard cuirass seems wrong.
See screenshots below (grid on the right): the characteristics are exactly the same.

### Screenshots

![BlackGuardCuirass1](https://user-images.githubusercontent.com/26251843/229357141-1fb5c9af-0127-4bba-b897-2830085f4d96.png)

![BlackGuardCuirass2](https://user-images.githubusercontent.com/26251843/229357145-08dd37ea-2f06-449d-bb8d-343302e0c646.png)

![BlackGuardCuirass3](https://user-images.githubusercontent.com/26251843/229357148-cfa661a9-5ce8-42ca-be94-26694681c238.png)

### Logs

```Log```

**Comment by Xandoria** [comment]
Sorry I was wrong. I had not understood.

**Comment by Craluminum2413** [comment]
Invalid issue?

**Comment by Xandoria** [comment]
Yes, please close.
