### ISSUE TITLE
incontainer-dye- not translated

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2529]
### Game Version

1.18.0-pre.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

**Comment by radfast** [comment]
I can't seem to reproduce this in 1.18-rc2.  Barrels containing dye (for example, 20 litres of water + 5 x crushed cinnabar -> seal for 8 hours -> 20 litres of red dye) display their localised names correctly.  The localisation string is, for example, `incontainer-item-dye-red`

**Comment by Craluminum2413** [comment]
This one ![image](https://user-images.githubusercontent.com/69315569/230893648-1e0f6727-fd20-464f-8577-2aad57994643.png)

**Comment by radfast** [comment]
Ah OK, I see what's happened, the localisation strings are correct but the source code had a punctuation error in 1.18-rc2 and earlier.  Tyron fixed this in source code a couple of days back but did not flag this as resolved.  So yes, this is resolved in next build, thank you for reporting :)
