### ISSUE TITLE
Mod Tabs on top Of Creative Inventory

### ISSUE THREAD

**Issue by TonyLiberatto** [anegostudios/VintageStory-Issues#253]
The idea is to have the creative Inventory to allow for page like tabs so a mod can better organize the items and blocks. 
The mod author can follow the same sub-menus as already existing for blocks and items or create new ones.
<img width="603" alt="new-creative-tab" src="https://user-images.githubusercontent.com/37522003/53697691-f6bb2680-3da1-11e9-815c-2a0e15862723.png">

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
