### ISSUE TITLE
Crash when Save & Leave the World

### ISSUE THREAD

**Issue by ChristianJog** [anegostudios/VintageStory-Issues#2530]
### Game Version

v1.18.0-pre.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Whenever I "Save & Leave the world" the game saves, then ends with a crash dialog.
This happens always.  I don't  have to do anything special.

I see following entry in the StackTrace (see attached log):
System.NotImplementedException: Die Methode oder der Vorgang ist nicht implementiert.
   bei Vintagestory.GameContent.**EntityBoat**.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:Zeile 482.

Regarding Boats/Rafts: I have a single raft in my savegame, but without any oars.
The raft is put into a lake (water block).

Hope this helps.
If you need any more info to reproduce  feel free to contact me.

### How to reproduce

1. Start game
2. End game with "Save and leave the world"
Game is saved.
When the game window closes, a Crash Dialog is shown.

### Logs

```Log```Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.7 (Unstable)
02.04.2023 17:39:36: Critical error occurred
Loaded Mods: 
System.NotImplementedException: Die Methode oder der Vorgang ist nicht implementiert.
   bei Vintagestory.GameContent.EntityBoat.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:Zeile 482.
   bei Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 556.
   bei Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:Zeile 2621.
   bei Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:Zeile 2536.
   bei Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:Zeile 323.
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:Zeile 304.
   bei Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:Zeile 677.
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:Zeile 292.
   bei Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:Zeile 440.
   bei Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:Zeile 564.
   bei Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:Zeile 388.
   bei Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:Zeile 416.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:Zeile 229.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:Zeile 808.
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:Zeile 1551.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 369.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19.03.2023 23:07:05, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.11.0, Zeitstempel: 0x638f99ee
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x18a9c
Startzeit der fehlerhaften Anwendung: 0x01d95aaf1f440411
Pfad der fehlerhaften Anwendung: C:\Users\micro\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\micro\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: c3f25521-ac40-4c32-8f79-902a247dd585
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 19.03.2023 23:06:38, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.17.11.0, Zeitstempel: 0x638f99ee
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x1b2e8
Startzeit der fehlerhaften Anwendung: 0x01d95aaefa184de5
Pfad der fehlerhaften Anwendung: C:\Users\micro\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\micro\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: e1632d23-52ae-4b31-b92d-f7329a0abfd5
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 16.03.2023 21:42:37, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Exception
   bei Vintagestory.Common.AssetManager.TryGet(Vintagestory.API.Common.AssetLocation, Boolean)
   bei Vintagestory.Client.NoObf.UnloadableShape.Load(Vintagestory.Client.NoObf.ClientMain, Vintagestory.API.Common.AssetLocationAndSource)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.LoadShapes(System.Collections.Generic.HashSet`1<Vintagestory.API.Common.AssetLocationAndSource>, System.Collections.Generic.IDictionary`2<Vintagestory.API.Common.AssetLocation,Vintagestory.Client.NoObf.UnloadableShape>, System.String)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.LoadBlockShapesAsync(System.Collections.Generic.HashSet`1<Vintagestory.API.Common.AssetLocationAndSource>, System.Collections.Generic.Dictionary`2<Vintagestory.API.Common.AssetLocation,Vintagestory.Client.NoObf.UnloadableShape>)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by ChristianJog** [comment]
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11132641/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11132642/client-main.txt)

**Comment by Craluminum2413** [comment]
Update to 1.18.0-pre.8
