### ISSUE TITLE
Infinite 100% moisture on farmland

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2533]
### Game Version

1.18.0-pre.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

1. Place soil block
2. Turn it into farmland with a hoe
3. Plant any seed
4. Get a bucket with 10L of water
5. Aim seed block and place water with bucket there
6. Wait until block updates and it will have 100% moisture

### Screenshots

![image](https://user-images.githubusercontent.com/69315569/229508109-4be29327-e258-4d39-bcc4-4f7dacdbd64d.png)

**Comment by pizza2004** [comment]
Should be fixed in the next release.
