### ISSUE TITLE
Placing and removing a support beam leaves an unusable void.

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#2537]
### Game Version

v1.18.0-rc.2

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

After placing one end of a maple support beam and then choosing not to, my game now thinks there is a block where it was placed and nothing else can go there.

There's nothing to interact with there, so i can't remove it.

### How to reproduce

1. Place a support beam end on the ground
2. Do... ??? something to cancel the other end of it
3. Remove the stub of a beam
4. Try to place another block. It now says another block is in the way.

I don't know exactly what I did for step 2. Trying to reproduce this on a singleplayer creative mode game didn't cause the same problem.

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for the report, this should be fixed with the next release
