### ISSUE TITLE
Document or repair the /setblock command

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#2538]
### Game Version

v1.18.0-rc.2

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

I was trying to fix the mystery void block from this ticket: https://github.com/anegostudios/VintageStory-Issues/issues/2537

Maybe if I could set the block at that location to something that can be broken, I can clean up the mess and get on with building. 

So from the `/help setblock` it says:
```<i>block code</i> is a precise Block name, optionally immediately followed by braces {} containing attributes for the Block```

However, any attempt to use this command fails because either I don't know how to use it, or it does not work. I can't tell which. 

Trying `/setblock cob s[]` fails with `Error in argument 1 (block code): No such block exists`
Trying `/setblock "Cob" s[]` fails with `Error in argument 1 (block code): No such block exists`
Trying anything even random numbers and gibberish gives me `Error in argument 1 (block code): No such block exists`

Does this command work? If so, how does it work? I found nothing on the wiki about it either. Is this even the right tool for the job? I have no clue...

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Have you tried `/setblock 0`?

**Comment by Craluminum2413** [comment]
`cob` block doesn't exist, but `cob-sparse` etc. do

**Comment by AbortRetryFail** [comment]
I also tried `/setblock 0` It also results in `Error in argument 1 (block code): No such block exists`

`/setblock cob-sparse s[]` worked, but I don't know why it worked? Is there a way to get a list of valid block names?

**Comment by Craluminum2413** [comment]
You can enable developer mode and then `Extended Debug Info` to see code of any block or item in the handbook.
![image](https://user-images.githubusercontent.com/69315569/229864758-3f1d7f8d-8459-47fc-872b-3effd9ff770f.png)

![image](https://user-images.githubusercontent.com/69315569/229864482-c846a268-a240-44dd-8092-f28d80d61593.png)
