### ISSUE TITLE
1.18.0 | Surface structures experiancing gravity

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2539]
### Game Version

v1.18 rc1 to v1.18.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I have tested it in both versions and modded and vanilla and in both the problem occurs.

A lot of structures are getting affected by a weird gravity after they generated.
This wasn't the case in 1.18 pre versions.

The following screenshots and videos should show what happens pretty good.

Affected blocks seem to be:
Clutter
Decoration
boulders
stones
gravel

Everything with gravity, I suppose

https://www.youtube.com/watch?v=flNpzN9YPVc
https://www.youtube.com/watch?v=ME78k1ut1Yo

### Screenshots

![2023-04-04_22-18-46](https://user-images.githubusercontent.com/100879715/229912572-0660f8c3-f252-47db-a58f-f9e8e68fcd39.png)
![2023-04-04_22-01-21](https://user-images.githubusercontent.com/100879715/229912594-32f51110-7c7b-44ff-ad11-268572677d98.png)

### Logs

```None```

**Comment by AreYSerious** [comment]
![2023-04-05_20-43-28](https://user-images.githubusercontent.com/100879715/230175352-915c4b9d-68e6-4d01-9234-5152d3dbdd0a.png)
![2023-04-05_20-43-22](https://user-images.githubusercontent.com/100879715/230175364-1b2fdf8f-1851-4cd4-95df-f7ce4f6d1bc0.png)


Just some more collections of how vanilla is affected by this

**Comment by AreYSerious** [comment]
Got it to crash

![2023-04-11_19-03-42](https://user-images.githubusercontent.com/100879715/231237131-6a8a781f-7fa5-49da-b793-c50872c964d6.png)

Logs will be in first msg

**Comment by AreYSerious** [comment]
Seems like this is still an issue for the stable version...

**Comment by AreYSerious** [comment]
https://discord.com/channels/302152934249070593/334233095374897152/1098291883303784478

**Comment by Th3Dilli** [comment]
thank you

this was fixed with the releases of 1.18.1
