### ISSUE TITLE
Cannot put sails on windmill rotor in single 1.18.0-rc.2

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#2544]
### Game Version

v1.18.0-rc.2

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Cannot build windmill - cannot place sails to windmill rotor.
Mods: only the Electricity mod. Tried without the electricity mod - same problem.

### How to reproduce

Run new creative world. Place wooden axle to some planks pillar, connect windmill rotor to it, then try to connect sails to the rotor. Clicking right mouse button while holding sails does nothing. Trying it with squat as well, does nothing either. 
It§s not possible to build windmill.

### Logs

```Log```

**Comment by tyronx** [comment]
Seems to work just fine for me. Are you holding 4 sails in your slot?

**Comment by fipil** [comment]
> Seems to work just fine for me. Are you holding 4 sails in your slot?

Ahaaa, stupid me. I was holding only one sail. With holding 4 sails it works. 
I'm sorry, my mistake. :-/

**Comment by Craluminum2413** [comment]
Maybe add some interaction help that shows it needs 4 sails?

**Comment by tyronx** [comment]
it already has

**Comment by Craluminum2413** [comment]
I forgor 💀
