### ISSUE TITLE
Leaded glass panes, new doors do not count as walls for indoor spaces

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#2548]
### Game Version

v1.18.0-rc.2

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

Discovered this trying to figure out why our house was playing wind sounds and seraphs are covering faces inside.

Leaded glass pane blocks and the new 1.18 solid doors are both not counting as enclosing walls for the space to be "indoors" 

### How to reproduce

1. Build a structure with leaded glass panes / doors with the flat side "out"
2. listen for wind sound fx 
3. cover leaded glass panes and doors with dirt
4. wind sfx are gone

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in next release.  Thanks for reporting!
