### ISSUE TITLE
A bunch of private methods should be public

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2550]
### Game Version

1.18.0-rc.2

### Description

BlockEntityGroundStorage: [putOrGetItemSingle](https://github.com/anegostudios/vssurvivalmod/blob/e6756e1cd64b5404e360dc0334ca62b12cd6e26d/BlockEntity/BEGroundStorage.cs#L783-L839)

**Comment by radfast** [comment]
Just that one?  Done for you in next release.

**Comment by Craluminum2413** [comment]
Can you also make it so that I can call it when player is null, I would like to put lying ground storable items into existing/create ground storage?
