### ISSUE TITLE
Schematic doesn't transport planks from 1.17 to 1.18

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#2552]
### Game Version

v1.17.9 and  v1.18.0-rc.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer and multiplayer

### Description

I'd like to transport my buildings made in the v1.17 to the new world running on v1.18.0-rc.2. Problem is that everything was transported except planks cubes. It was performed on multiplayer servers.
I made a proof test on singleplayer, vanilla 1.17.9 and vanilla 1.18.0-rc.2. See my screenshots.
I'm also attaching the schematic file here.
[PlanksTest.zip](https://github.com/anegostudios/VintageStory-Issues/files/11180828/PlanksTest.zip)

### How to reproduce

1. Create a new creative flat world in the single vanilla 1.17.9.
2. Build some walls from planks. Put there also any different blocks, so you can see where should be planks located.
3. Select the walls and export to Schematic file.
4. Exit game.
5. Run VS 1.18.0-rc.2
6. Create a new creative flat world.
7. Import the schematic file.
8. Planks are not there, it's not imported or are removed during import.

EDIT: I also made the same proof test with v1.17.**11** - same result.

### Screenshots

![2023-04-07_20-33-25](https://user-images.githubusercontent.com/768590/230662489-b7a6721c-9317-4685-b7ff-3d5bcb5f6978.png)
Exporting walls made of planks and logs from v1.17..

![2023-04-07_20-36-30](https://user-images.githubusercontent.com/768590/230662593-9d899169-bb91-413a-b1ea-67cf5651dae9.png)
Importing the schematic file to 1.18.

![2023-04-07_20-37-06](https://user-images.githubusercontent.com/768590/230662654-daefc9f1-2721-45e8-b09b-8aa65715d1d1.png)
There are no planks!

**Comment by fipil** [comment]
I found some workaround:
I noticed that the planks are exported from the v1.17 in this variants in the BlockCodes property in the Schematic json file:
game:planks-oak-**_hor_** and game:planks-oak-**_ver_**

Those variants can be replaced in some text editor by the variants, known by the 1.18 version:
1. Replace the "hor" postfix by the "ns" postfix, for example game:planks-oak-**_hor_** will become the game:planks-oak-**_ns_**
2. Replace the "ver" postfix by the "ud" postfix, for example game:planks-oak-**_ver_** will become the game:planks-oak-**_ud_**

After that, the schematic file can be imported and the planks are imported correctly.

**Comment by Craluminum2413** [comment]
There are now only three variants: ns, we and ud

**Comment by Th3Dilli** [comment]
this is now fixed with next 1.19 pre release version
