### ISSUE TITLE
Earth balls inventory icon does not match how it looks.

### ISSUE THREAD

**Issue by TomCatFort** [anegostudios/VintageStory-Issues#2554]
### Game Version

v1.18.0-rc.2

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Looks like the earth balls got new models and textures and they are no longer look the same as puffballs.
At least when they are growing on the ground.
In the inventory, the earth ball has the same icon as the puffball.
The inventory icon of the earth ball should match how it looks growing  on the ground.

### How to reproduce

1. Enter creative game mode.
2. Find the earth ball in the creative inventory, and place a few in the hot bar.
3. Place some earth ball on the ground.
4. Compare the looks of the earth ball inventory icon and the model on the ground.

### Screenshots

![earthball_puffball](https://user-images.githubusercontent.com/784076/230742659-4bc5f6b9-2aab-47a0-ba41-b5c4fd784d52.png)

### Logs

I found nothing interesting in the logs regarding this issue.

**Comment by RedramVS** [comment]
Item model has been changed to match block model
