### ISSUE TITLE
Ping glass lantern has neutral white light.

### ISSUE THREAD

**Issue by TomCatFort** [anegostudios/VintageStory-Issues#2555]
### Game Version

v1.18.0-rc.2

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Unlike all the other colored glass, the pink glass does not give a unique colored light to lantern.
Instead it produces the same neutral white color as regular glass, quartz glass, or other colorless glass variants.

For example, the violet glass produces a purple colored light.
And as an another example, the brown glass produces a warm (instead of neutral) white light, which is very nice.
Like these, the pink glass should also change the color of the light to something else than neutral white.
Maybe like the similar violet color, but less saturated?

### How to reproduce

1. Create a completely dark room, preferably with white or gray walls.
2. Place a lantern on the wall.
3. Change the color of the lantern using a Pink glass block.

### Screenshots

**Pink glass lantern:**
![ping_glass](https://user-images.githubusercontent.com/784076/230745059-28b58e5d-0496-4a94-896b-9b9716776135.png)

**Regular glass lantern:**
![regular_glass](https://user-images.githubusercontent.com/784076/230745060-66c97bc1-2fb0-4228-ab7c-e61127c3a2a5.png)

**Violet glass lantern:**
![violet_glass](https://user-images.githubusercontent.com/784076/230745061-9c0ee545-947b-4f63-959e-a53b0a878b2b.png)

**Brown glass lantern:**
![brown_glass](https://user-images.githubusercontent.com/784076/230745058-8825fdb9-e9bd-409d-9da1-10738e05bc7e.png)

### Logs

I found nothing relevant for this issue in the logs.

**Comment by tyronx** [comment]
thanks! this should be fixed in 1.18.0-rc.3
