### ISSUE TITLE
Dark mubbrick slab not craftable with blue clay

### ISSUE THREAD

**Issue by RTHauke** [anegostudios/VintageStory-Issues#2556]
### Game Version

v1.18-rc2

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Dark mudbrick slabs can only be crafted with fire clay whilst dark mudbrick blocks can be crafted with either type of clay.

Expected behavior:  Dark mudbrick slabs should be craftable with any type of clay.  

### How to reproduce

1. Open handbook
2. Review recipes for dark mudbrick blocks and slabs.

### Logs

```Log```

**Comment by RedramVS** [comment]
The recipe actually allowed both already. However the slabmode recipe apparently interfered such that the fireclay was not seen.  The slabmode recipe has now been separated out so it shows separately, and the crafting recipe can properly cycle the clay images.
