### ISSUE TITLE
Search Issue with other Languages that use "acento" in their countries

### ISSUE THREAD

**Issue by Ruyeex** [anegostudios/VintageStory-Issues#2559]
### Game Version

v1.18.pre.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I already put here the details on the discord [here](https://discord.com/channels/302152934249070593/1094632032493121666/1094632032493121666):

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Turned out the issue is about searching words with "acentos", for example, "Mármore" cannot be found by typing "Marmore"

**Comment by tyronx** [comment]
Technical info: Could possibly strip accents from the text (https://stackoverflow.com/a/249126/1873041), and use that as another text source to search in

**Comment by daretmavi** [comment]
Agree, searching without diacritics would be great.

**Comment by tyronx** [comment]
thanks for the report, from 1.19 on diacritics are wholly ignored
