### ISSUE TITLE
Omok table top playable grid is offset by one block in both X and Y

### ISSUE THREAD

**Issue by meganukebmp** [anegostudios/VintageStory-Issues#2562]
### Game Version

v1.18.0-rc2

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The Omok table playfield is offset by one voxel for some reason. In both X and Y directions.

### Screenshots

![2023-04-10_13-20-02](https://user-images.githubusercontent.com/5718823/230892358-7515f8ed-59af-496d-8d5a-9d1ed5ef9543.png)
![2023-04-10_13-19-57](https://user-images.githubusercontent.com/5718823/230892361-fc5d46c6-cb1f-4747-b1ea-b21968aa5235.png)

**Comment by tyronx** [comment]
thanks, this should be fixed in rc.3

**Comment by meganukebmp** [comment]
Not resolved. Visually the pieces are now fixed, but functionally the grid is still offset by 1 in both axis.
![2023-04-15_19-12-53](https://user-images.githubusercontent.com/5718823/232242003-76b584da-9cd5-4ae2-b40b-d8de5b9ee562.png)
![2023-04-15_19-12-49](https://user-images.githubusercontent.com/5718823/232242005-f33e97e8-ac11-4df4-994e-a72dbf20f4dc.png)
See cursor location vs where the piece gets picked.
