### ISSUE TITLE
Crash in a cave

### ISSUE THREAD

**Issue by SlrHui** [anegostudios/VintageStory-Issues#2565]
### Game Version

1.18.0-rc.2 

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

crash in a cave

### Logs

Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.0-rc.2 (Unstable)
11.04.2023 10:15:14: Critical error occurred
Loaded Mods: game@1.18.0-rc.2, hudclock@2.9.0-pre.1, creative@1.18.0-rc.2, survival@1.18.0-rc.2
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockShapeFromAttributes.GetOrCreateMesh(IShapeTypeProps cprops, ITexPositionSource overrideTexturesource, String overrideTextureCode) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:Zeile 431.
   bei Vintagestory.GameContent.BlockShapeFromAttributes.GetDecal(IWorldAccessor world, BlockPos pos, ITexPositionSource decalTexSource, MeshData& decalModelData, MeshData& blockModelData) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:Zeile 419.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 262.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 206.
   bei Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:Zeile 168.
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 378.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 795.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 596.
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:Zeile 86.
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:Zeile 201.
   bei Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:Zeile 785.
   bei Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:Zeile 977.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 241.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 722.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:Zeile 625.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 119.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 93.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 18.03.2023 20:09:15, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Exception
   bei Vintagestory.Common.AssetManager.TryGet(Vintagestory.API.Common.AssetLocation, Boolean)
   bei Vintagestory.Client.NoObf.UnloadableShape.Load(Vintagestory.Client.NoObf.ClientMain, Vintagestory.API.Common.AssetLocationAndSource)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.LoadShapes(System.Collections.Generic.HashSet`1<Vintagestory.API.Common.AssetLocationAndSource>, System.Collections.Generic.IDictionary`2<Vintagestory.API.Common.AssetLocation,Vintagestory.Client.NoObf.UnloadableShape>, System.String)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.LoadBlockShapesAsync(System.Collections.Generic.HashSet`1<Vintagestory.API.Common.AssetLocationAndSource>, System.Collections.Generic.Dictionary`2<Vintagestory.API.Common.AssetLocation,Vintagestory.Client.NoObf.UnloadableShape>)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 27.02.2023 10:30:55, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.18.0.0, Zeitstempel: 0x63fa7873
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22621.1194, Zeitstempel: 0xfaa44dd0
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000009051c
ID des fehlerhaften Prozesses: 0x0x6744
Startzeit der fehlerhaften Anwendung: 0x0x1d94a8e309374ef
Pfad der fehlerhaften Anwendung: C:\vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: cc2ad1a1-9652-4e20-b0d3-1f4b0e7fb9a5
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 27.02.2023 10:30:55, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.NotSupportedException

Ausnahmeinformationen: System.IO.FileLoadException
   bei System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   bei System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   bei System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   bei System.Reflection.Assembly.LoadFrom(System.String)
   bei Vintagestory.Client.ClientProgram.AssemblyResolve(System.Object, System.ResolveEventArgs)

Ausnahmeinformationen: System.Exception
   bei Vintagestory.Client.ClientProgram.AssemblyResolve(System.Object, System.ResolveEventArgs)
   bei System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Ausnahmeinformationen: System.IO.FileLoadException
   bei Vintagestory.Client.ClientProgram..ctor(System.String[])
   bei Vintagestory.Client.ClientProgram.Main(System.String[])

 }

**Comment by Craluminum2413** [comment]
Duplicate of #2527
