### ISSUE TITLE
seasonal coloring looks strange

### ISSUE THREAD

**Issue by stony99** [anegostudios/VintageStory-Issues#2575]
### Game Version

v1.18-rc5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Lots of weird colored patches everywhere. My graphiccard is a GForce GTX 960

### Screenshots

https://postimg.cc/DW8J18Y0

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Related tp #2452

**Comment by stony99** [comment]
The problem seems to occur only with dirtblock(grassy), sand and gravel do not have the problem. The further south I go the less the problem occurs. At 20 °C outside temperature it seems to be completely gone.

**Comment by stony99** [comment]
After 3-4 ingame days everything now looks normal again, no more weird patches.

**Comment by Aurora5252** [comment]
I have writen a way to reproduce the problem in #2452 for those who want to test it.

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2452
