### ISSUE TITLE
My character slept through an in-game month while paused

### ISSUE THREAD

**Issue by SRubago** [anegostudios/VintageStory-Issues#2576]
### Game Version

v1.18.0-rc.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I went to bed on a basic hay bed on May 4 year 0, roughly around 21:00. The screen remained black for a bit longer than usual but I thought it may have been some lag. While still sleeping, I paused my game and when I came back and unpaused it my character didn't automatically wake up. I pressed "shift" to force myself awake and the sunlight moved past very quickly before stabilizing. Upon checking the clock, not only was it already 16:00 - it was June 4th, year 0! My character slept through an entire month of gameplay.
I kept getting a popup in the corner about the game not connecting to the server, but this game is a single-player game. I also could not interact with anything in the game, such as my storage containers, and had to force stop the game from Windows task manager. The only mod I have activated at the moment is the one that converts the temperature from Celsius to Fahrenheit, so I doubt mods did anything but I figured I'd mention it anyway. Unfortunately, I do not have any video or screenshots of this issue at this time.

### How to reproduce

I'm not sure how to reproduce, as I have been able to pause while sleeping a few times during this save already. The issue appeared to have occured before I even paused as I noted the screen was dark for longer than usual already.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Need a way to reproduce it
