### ISSUE TITLE
Cracked Phyllite named as "Cracked Ohyllite"

### ISSUE THREAD

**Issue by richardhendricks** [anegostudios/VintageStory-Issues#2577]
### Game Version

v1.18.0-rc5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Mis-spelled item

### How to reproduce

search for Cracked Phyllite, could not find. 

### Screenshots

![image](https://user-images.githubusercontent.com/1214811/231324215-a1b8fc7d-effc-4919-a1a6-07a7632b3d30.png)

### Logs

```Log```

**Comment by DArkHekRoMaNT** [comment]
@Craluminum2413 should be fixed now
https://crowdin.com/translate/vintage-story-game/2/en-ru?filter=basic&value=0#q=block-crackedrock-phyllite
