### ISSUE TITLE
Rot barrel

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2579]
### Game Version

v1.18.0-rc5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Putting rot into a barrel seems bugged.

### How to reproduce

1. Put rot in the box of an empty barrel. The rot does not disapear from the box
2. The rectangle jauge for the barrel filling status remains empty.
3. The rot appears inside the barrel in the world though
4. The content of the barrel is updated also correctly

### Screenshots

![Rot-barrel-bug](https://user-images.githubusercontent.com/26251843/231366709-3f1ef86b-00b4-4a89-81fb-d52dab1b2f6f.png)

**Comment by Th3Dilli** [comment]
barrel now work different 

solid contents (except salt) will stay in the slot [1] and not fill the bar [2]

the rest of the barrel remain functional as it was
