### ISSUE TITLE
Higher speed on roads, gradually increasing

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#258]
Imho current speed increase when walking on stone path is too small when traveling long distances.
When you explore lands, it is fine to spend lot of time, but when you are re-visiting some established mine or quarry, the game becomes a running simulator.
Until more transport options are introduced, maybe make it so while you are moving on the road, your speed very slowly grows up to 50% or even 100%? Or infinitely ;)
This will encourage people to build more and longer roads, e.g. to quarries of a certain stone type.
And to make them more natural, curvy, because as soon as you step off the road or stop, you loose the accumulated speed addition, so need to turn carefully.

**Comment by Heptagon-ru** [comment]
Sorry, a repeat of a suggestion on forum, deleting.

**Comment by Heptagon-ru** [comment]
Sorry, was a repeat of an existing suggestion on forum :(

**Comment by copygirl** [comment]
As long as there's not a duplicate on the issue tracker it's fine to have it here as well. I'm going to reopen. Hope that's fine.

**Comment by Craluminum2413** [comment]
Add something like clay / brick roads

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
