### ISSUE TITLE
Layer of sticks description

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2580]
### Game Version

v1.18.0-rc5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

In the in-game description of the item "layer of sticks", the "Uses" section is repeated twice: in the translated language of the player and also in the English version.

### Screenshots

![Uses-repeated-in-English](https://user-images.githubusercontent.com/26251843/231375709-ca6158b9-2e91-4350-ba68-8a4bc8d71063.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release, the translation keys will change into `"block-handbooktitle-stickslayer-wooden-ew-*"` and `"block-handbooktext-stickslayer-wooden-ew-*"`
