### ISSUE TITLE
Dry mash when left to spoil in a fruit press makes unusable rot

### ISSUE THREAD

**Issue by ngoomie** [anegostudios/VintageStory-Issues#2584]
### Game Version

v1.17.11

### Platform

Linux (Fedora 38, kernel ver. 6.2.9-300.fc38.x86_64)

### Modded

Modded

### SP/MP

Multiplayer

### Description

Dry fruit mash left inside a fruit press will turn into rot that cannot be put into a barrel to be made into compost, and cannot be stacked with unbugged rot.

### How to reproduce

1. Make any sort of juice using the fruit press
2. Do not remove the resulting dry mash
3. Wait for it to decay into rot
4. Take the resulting rot out and attempt to either put it into barrels or stack it with normal rot

### Screenshots

![1681320286](https://user-images.githubusercontent.com/50791600/231536088-bfb9d988-936c-4e04-87d9-fde7d212df5e.png)
1x rot in the "fluid" storage of the barrel is rot obtained through normal means, 10x is the bugged rot and cannot be put into the fluid storage no matter what I do

### Logs

```Log```

**Comment by pizza2004** [comment]
This should be fixed in 1.20-rc.6, if not earlier.
