### ISSUE TITLE
transitionSpeedMulByType conflicts with solveByType and is now redundant

### ISSUE THREAD

**Issue by noelle-lavenza** [anegostudios/VintageStory-Issues#2585]
### Game Version

v1.17.11

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Because the property `transitionSpeedMulByType` ends in `ByType`, the game tries to set `transitionSpeedMul` based on the provided types. However, `transitionSpeedMul` is not a property that's actually checked. This means `transitionSpeedMulByType` is currently unusable unless you specify it via `transitionSpeedMulByTypebyType`, since `solveByType` is only run once, not recursively.

Proposed solution: Replace `transitionSpeedMulByType` with just `transitionSpeedMul`, which shouldn't break old mods. The current by-type-by-default version of `spoilSpeedMulByFoodCat` should also probably be replaced with `spoilSpeedMulByFoodCatbyType`, but that's potentially a breaking change.

### How to reproduce

1. Use the "transitionSpeedMulByType" property on a container to, for example, change the perish rate for all items.
2. Note that wildcards don't work when specifying the type.
3. Note that *nothing* works when specifying this property, actually!
4. Try `"transitionSpeedMulByTypebyType"` (case sensitive) with an extra `"*": {` `}` wrapping the actual property contents.
5. It works, although wildcards still don't work on the inner part.

### Logs

N/A

**Comment by tyronx** [comment]
thanks for the report, will read just `transitionSpeedMul` next rc.

**Comment by noelle-lavenza** [comment]
This doesn't seem to have been solved properly.
```csharp
		if (block.Attributes["transitionSpeedMul"][type].Exists)
		{
			inventory.TransitionableSpeedMulByType = block.Attributes["transitionSpeedMul"][type].AsObject<Dictionary<EnumTransitionType, float>>();
		}
```
This code is still present, when solveByType makes it unnecessary.

**Comment by noelle-lavenza** [comment]
Huh. Checked again and there's no `[type]` there now. Guess I had to reload the assembly in ILSpy.
