### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by pastekbg** [anegostudios/VintageStory-Issues#2586]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

when i start a game in singleplayer/multiplyer my game crash

### How to reproduce

just lauching a multiplayer game/singleplayer

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.9 (Stable) by OverF1X  
12/04/2023 21:51:37: Critical error occurred
Loaded Mods: 
System.Exception: Don't know how to instantiate item of class 'ItemMagicWand' did you forget to register a mapping?
   à Vintagestory.Common.ClassRegistry.CreateItem(String itemClass)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(List`1 items, Int32 listSize)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   à Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/04/2023 21:51:37, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   à Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 12/04/2023 21:46:12, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   à Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 12/04/2023 21:43:41, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   à Vintagestory.Client.NoObf.GeneralPacketHandler.LoadItemTypes()
   à Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
Pirated versions of the game are not supported
