### ISSUE TITLE
There's 2 buckets in the Handbook with the same entry

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2589]
### Game Version

1.18.0rc5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The first entry seems to have a a liquid inside but they both link to the same place. To reproduce, search "bucket" in the survival handbook.
![image](https://user-images.githubusercontent.com/13642054/231779790-76cb75c5-f37e-4fd5-9f68-8eda59413a47.png)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for reporting, should be fixed in the next version
