### ISSUE TITLE
Placing wooden beams led to a block disappearing while still occupying space.

### ISSUE THREAD

**Issue by GroggyBeholder** [anegostudios/VintageStory-Issues#2591]
### Game Version

v1.18.0-rc.2

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I was placing wooden beams that were supposed to go over an oil lamp. I didn't have enough beams in my inventory so placing failed. The oil lamp disappeared, but now nothing can be placed where it once was. It cannot be targeted to be picked up or destroyed, there is nothing to interact with. There is no collision. The game simply says that there is already a block in that spot.

The mods we use on the server just add a few recipes and should not impact the bug.

Restarting the server did not help.

### How to reproduce

Starting a beam in a block with an oil lamp (possibly other objects too) and failing to finish it, will inevitably make the lamp disappear while leaving the block theoretically occupied.

I successfully replicated the bug in singleplayer.

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thanks for the report

this should have been solved since #2618 is fixed and closed
