### ISSUE TITLE
Chiseled block is invisible when broken in RC6

### ISSUE THREAD

**Issue by robert-bowman** [anegostudios/VintageStory-Issues#2592]
RC6: No mods:

Place block (Debarked pine)
Remove material with chisel
Add a second block (ebony log)
Select second block as active
Add material from second block
Break block
Chiseled block is invisible.

**Comment by robert-bowman** [comment]
To back-check, I deleted the Vintagestory18 install and installed RC4.
Repeated chiseling with standard blocks.
When not placed, chiseled blocks are invisible.  When placed, they seem to be fine.  See screenshots.
Note shadow in first screenshot.
![2023-04-13_19-27-58](https://user-images.githubusercontent.com/39417261/231904832-cb7e3ca0-946b-48a1-948e-f10df16aaa5d.png)
![2023-04-13_19-29-49](https://user-images.githubusercontent.com/39417261/231904848-b6e07b1e-fc19-492f-8ffc-cc2ccf7151aa.png)

**Comment by Th3Dilli** [comment]
thank you for the report

this seems to be already fixed by now
