### ISSUE TITLE
Not remaped items from 1.16.5

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2596]
### Game Version

1.18.0 rc6

### Platform

None

### Modded

Vanilla

### SP/MP

None

### Description

See bug #2057 

According to chat those items are not remapped as well:

    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-scrap found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-copper found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-tinbronze found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-bismuthbronze found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-blackbronze found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-gold found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-silver found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-iron found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-meteoriciron found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-steel found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-blackguard found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-forlorn found @ 0
    15.4.2023 22:48:18 [Chat] No mapping for itemcode game:blade-admin found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-copper found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-tinbronze found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-bismuthbronze found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-blackbronze found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-gold found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-silver found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-iron found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-meteoriciron found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:bladehead-steel found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for blockcode game:toolmold-raw-blade found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for blockcode game:toolmold-burned-blade found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:shield-wood-wood found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:shield-blackguard-iron found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:shield-wood-tinbronze found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:shield-leather-tinbronze found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:shield-pattern3-tinbronze found @ 0
    15.4.2023 22:48:19 [Chat] No mapping for itemcode game:blade-curved-scrap found @ 0
    15.4.2023 22:48:20 [Chat] No mapping for itemcode game:blade-short-blackguard found @ 0
    15.4.2023 22:48:20 [Chat] No mapping for itemcode game:blade-thrusting-forlorn found @ 0
    15.4.2023 22:48:20 [Chat] No mapping for itemcode game:blade-long-admin found @ 0
    15.4.2023 22:48:23 [Chat] No mapping for blockcode game:lore-book-aged-orangebrown found @ 0
    15.4.2023 22:48:24 [Chat] No mapping for itemcode game:blade-short-blackguard found @ 0
    15.4.2023 22:48:24 [Chat] No mapping for itemcode game:blade-thrusting-forlorn found @ 0
    15.4.2023 22:48:24 [Chat] No mapping for itemcode game:blade-long-admin found @ 0
    15.4.2023 22:48:24 [Chat] No mapping for itemcode game:blade-curved-scrap found @ 0
    15.4.2023 22:48:25 [Chat] No mapping for itemcode game:knife-bone-flint found @ 0
    15.4.2023 22:48:29 [Chat] No mapping for itemcode game:resonancearchive-9 found @ 0

### How to reproduce

1. Make item in 1.16.5 version
2. update to newer version (1.17 - 1.18.0 rc6)
3. Items are white squares

**Comment by Spaceslug** [comment]
Please finally fix this. I stopped playing when 1.17 came out because of this issue.

**Comment by Craluminum2413** [comment]
Not relevant anymore
