### ISSUE TITLE
Translation of a sentence about the Hanseatic League

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2598]
### Game Version

v1.18.0-pre.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I cannot replace an incorrect translation (missing formatting tags) by mine because the previous one was highly rated.

### Screenshots

![Tranlation-in-crowdin](https://user-images.githubusercontent.com/26251843/232315111-a011f9ea-30fa-459e-999d-0ecbde5c8cf8.png)

### Logs

```Log```

**Comment by DArkHekRoMaNT** [comment]
@Xandoria In this case, it's better to write a proofreader for your language, if they exist, or just in #wiki-and-translations on [Discord](https://discord.gg/xCDRmCaP25). I removed the original line @Craluminum2413

**Comment by Xandoria** [comment]
Thank you. Can you close the issue?
