### ISSUE TITLE
Corpses sometimes don't get butchered properly

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#260]
I've noticed it can be possible to "butcher" a corpse without getting any loot. Upon closing the empty GUI, the corpse doesn't turn into bones. I have the feeling this might be not because the corpse didn't drop anything, but because the butchery wasn't finished successfully. Could it be that the client thinks the corpse was butchered, opening an empty GUI, while the server disagrees, so it doesn't send any content?

I found that I was able to get this randomly when testing, but also seem to remember it being the case in previous versions. I was also able to reproduce it, either by chance, or by trying to butcher the corpse almost out of range.

**Comment by tyronx** [comment]
a cheap hax in v1.10.6 or so fixes this
