### ISSUE TITLE
this still in 1.18 rc 6

### ISSUE THREAD

**Issue by KeiMuriKoe** [anegostudios/VintageStory-Issues#2600]
### Game Version

v1.18 rc 6

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Any pie, after being cut, is divided into 3 + 1 parts that do not stack, while having identical characteristics.
There may be some logic to it, but I don't understand it.
https://youtu.be/7Fa_hguTVk4

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #2316
