### ISSUE TITLE
Worlds don't load. Can't enter a world

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2604]
### Game Version

v1.18.0-rc.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After updating from pre6 to pre7 any world I enter does not load. I can't even enter new worlds. After joining a world it starts to load as usual but stops when it gets to "Return again" message, afterwards it just stops loading.

### Screenshots

![image](https://user-images.githubusercontent.com/126715524/232468519-b9c1cf62-d842-4400-bee4-4c2c05756c63.png)

### Logs

```Log```

**Comment by BavarianViking87** [comment]
Got the same problem.

Server-main.txt says 

"[Error] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Server.ServerMain.GetSpawnPosition(String playerUID, Boolean onlyGlobalDefaultSpawn, Boolean consumeSpawn) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:Zeile 1331.
   bei Vintagestory.Server.ServerMain.FinalizePlayerIdentification(Packet_ClientIdentification packet, ConnectedClient client, String entitlements) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:Zeile 257.
   bei Vintagestory.Server.ServerMain.HandlePlayerIdentification(Packet_Client p, ConnectedClient client) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerGeneralPacketHandler.cs:Zeile 636.
   bei Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:Zeile 107.
"

**Comment by Nettlesprout** [comment]
I also have this same issue. 118rc6 works fine for me, just did a fresh install when I saw a new version, could not create a fresh world, no mods, all settings default, and none of my attempts to create a new world will work. It gets to "It calls Top You ... Rerturn Again..." then just stops and will not go any further. 

 In my case, I have Windows7 if that could be the issue but 118rc6 was just fine. Hardware specs are FX-4350 (4ghz quadcore), 1050ti, 16g ram.

**Comment by tyronx** [comment]
oh crud.

**Comment by Craluminum2413** [comment]
'''
17.4.2023 16:57:14 [Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerMain.GetSpawnPosition(String playerUID, Boolean onlyGlobalDefaultSpawn, Boolean consumeSpawn) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 1331
   at Vintagestory.Server.ServerMain.FinalizePlayerIdentification(Packet_ClientIdentification packet, ConnectedClient client, String entitlements) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 277
   at Vintagestory.Server.ServerMain.HandlePlayerIdentification(Packet_Client p, ConnectedClient client) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerGeneralPacketHandler.cs:line 636
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 107
'''

**Comment by Nettlesprout** [comment]
> 



> oh crud.

Look how eager we all are to test and play though 👯‍♀️

**Comment by tyronx** [comment]
fixed in a couple of minutes

**Comment by tyronx** [comment]
thanks for reporting!
