### ISSUE TITLE
Confused Step and Stop in BlockMultiblock

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [anegostudios/VintageStory-Issues#2606]
Advanced multiblock interaction still doesn't work correctly in 1.18.0-rc.8 due to typo
https://github.com/anegostudios/vsessentialsmod/blob/7dffd3ba5ad0a907720e82d255d721b6084d7f23/Block/BlockMultiblock.cs#L241
![](https://cdn.discordapp.com/attachments/334233095374897152/1093956136341864528/image.png)

**Comment by DArkHekRoMaNT** [comment]
@tyronx, can you fix this pls? I can't fully release SQ since pre.8 due to this typo

**Comment by tyronx** [comment]
ok, will be in the next release, thanks for the repoert
