### ISSUE TITLE
Have never been able to load a 1.18 game

### ISSUE THREAD

**Issue by Barneyjones** [anegostudios/VintageStory-Issues#2607]
### Game Version

v1.18.0-rc.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Hi there, as title... since 1.18 has been released i can *enter* the game to various degrees... sometimes it will only let me create a creative game... and then freeze on load in

Sometimes it does the *... it remembers...* then freezes at the end

Sometimes it will let me even get to character creation and then lag for 10 seconds then freeze...

Is it an issue on my end? (i can play this game perfectly with latest 1.17 build) 

(i would send my logs but i have no clue which one would be for single player)

### How to reproduce

1. install ANY 1.18 version
2. Load game
3. create game parameters (survival/exploration/creative)
4. change any parameters (or none)
5. load in to the game
6. wait for 100% freeze

### Screenshots

N/A

### Logs

```Log```

**Comment by DArkHekRoMaNT** [comment]
First of all, client-main.txt and server-main.txt are useful (internal server is also exists in singleplayer)

**Comment by Barneyjones** [comment]
how do i upload the logs now it has been posted? and also what about the question of *is anyone else having this same issue?* 

Doubt it because i can't find this issue anywhere else

**Comment by DArkHekRoMaNT** [comment]
Just drag and drop it or click bottom panel in the message box? You can send it as a new message

<br>

> what about the question of is anyone else having this same issue?

Probably not. This is why logs are so important

**Comment by RunTekov** [comment]
I have a similar issue

**Comment by IF-Adin** [comment]
Out of curiosity, does this happen in multiplayer, too? Even when running your own local dedicated server?

Because the game froze for me, too, but only in the menu, whenever the game window was unfocussed, which happened the moment the server got started. When i used the server separately and connected to it, the game suddenly worked fine.

**Comment by Barneyjones** [comment]
I don’t know how to do this, so have never joined or created a server, thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by IF-Adin** [comment]
You can just run VintagestoryServer.exe in the command line, leave it running, then open vintage story, go to multiplayer and add the server "localhost", then connect to it.
