### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Chelios10** [anegostudios/VintageStory-Issues#2615]
### Game Version

v1.18

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

I report the problems here:

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0 (Stable)
20/04/2023 10:42:14: Critical error occurred
Loaded Mods: game@1.18.0, creative@1.18.0, survival@1.18.0
System.Exception: Asset game:config/traits.json could not be found
   in Vintagestory.Common.AssetManager.Get(AssetLocation Location) in VintagestoryLib\Common\FileIO\AssetManager.cs:riga 274
   in Vintagestory.GameContent.CharacterSystem.loadCharacterClasses() in VSSurvivalMod\Systems\Character\Character.cs:riga 160
   in System.Action.Invoke()
   in Vintagestory.Client.NoObf.ClientSystemStartup.OnAllAssetsLoaded_ClientSystems(Int32 i) in VintagestoryLib\Client\Systems\Startup.cs:riga 843
   in Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:riga 755
   in Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:riga 304
   in Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:riga 724
   in Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:riga 627
   in Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:riga 126
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:riga 479
   in OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:riga 454
   in OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:riga 375
   in Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   in Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:riga 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 20/04/2023 10:42:15, Site = , Source = Application Error, Message = Nome dell'applicazione che ha generato l'errore: Vintagestory.exe, versione: 1.18.0.0, timestamp: 0x64400ea0
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.19041.2788, timestamp: 0x62e593d6
Codice eccezione: 0xe0434352
Offset errore 0x000000000002cb69
ID processo che ha generato l'errore: 0x3668
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d97363f975624f
Percorso dell'applicazione che ha generato l'errore: C:\Users\Marco\AppData\Roaming\Vintagestory\Vintagestory.exe
Percorso del modulo che ha generato l'errore: C:\Windows\System32\KERNELBASE.dll
ID segnalazione: aa3304f1-2635-41dd-b644-941665e1f96a
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:  }
--------------
{ TimeGenerated = 20/04/2023 10:42:14, Site = , Source = .NET Runtime, Message = Applicazione: Vintagestory.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.Collections.Generic.KeyNotFoundException
   in Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlockForInventory(Vintagestory.API.Common.Block)
   in Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocksForInventory_ASync(System.Collections.Generic.IList`1<Vintagestory.API.Common.Block>)
   in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   in System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 20/04/2023 10:41:48, Site = , Source = .NET Runtime, Message = Applicazione: Vintagestory.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.Collections.Generic.KeyNotFoundException
   in Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Vintagestory.API.Common.Block)
   in Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks_Async(System.Collections.Generic.IList`1<Vintagestory.API.Common.Block>)
   in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   in System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

### Logs

```Log```

**Comment by radfast** [comment]
Please check your installation: do you have a file in the `/assets/survival/config` folder named `traits.json`?

The crash report states that file cannot be found.

**Comment by Th3Dilli** [comment]
I assume this was fixed by reinstalling, if not let us know
gonna close this for now
