### ISSUE TITLE
Trunk breaking animation sometimes leaves broken animation for a moment longer than the trunk drop

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2617]
### Game Version

1.18.0

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

This is in LAN and may be a multiplayer bug. When breaking a trunk it causes the cracks to appear on it. The cracking animation lasts longer than the trunk takes to drop. Example here:
![image](https://user-images.githubusercontent.com/13642054/233339379-a5b7ee5d-a7c2-4a52-b2c2-655001be8a24.png)

**Comment by bigjo66** [comment]
I am getting this too, except the wood doesn't drop, and I can't cut up the logs into firewood. I'm also getting axes randomly disappearing and reappearing.

**Comment by VallenFrostweaver** [comment]
> I am getting this too, except the wood doesn't drop, and I can't cut up the logs into firewood. I'm also getting axes randomly disappearing and reappearing.

That sounds like several other issues. You may want to create separate issues for those and if you are playing modded, check your mods first.

**Comment by Craluminum2413** [comment]
Fixed no idea when
