### ISSUE TITLE
Beams delete ladders, chests and other blocks

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2618]
### Game Version

1.18.0

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Ladders get deleted if they share the same space as a beam that is being placed (but not the rest of the beam, only the breakable point). See video clip here: [https://clips.twitch.tv/SaltySpikyPorcupineBrokeBack-m1OY69E5QRTDG6gO](https://clips.twitch.tv/SaltySpikyPorcupineBrokeBack-m1OY69E5QRTDG6gO)
This also deletes other items that don't take up a full block space.

**Comment by noelle-lavenza** [comment]
It's way more than just ladders. Here's every report I found in the bug reports channel:

> 1.18 pre1
> When placing a beam above glass panes, it deletes the pane at the source
> seems to work with every partial block (tested with signs and fences)

> Minor bug found in pre1
> Beams placed in a door block remove the door

> Sometimes when placing beams along vertical slabs the beam will delete the slab it was initially attached to, and if I try to place a block (i.e. to replace the slab) there it'll say there's a block or player already in the way. It's not consistent though, it only happens ~10% of the time and seems random; sometimes it'll delete a slab, so I break the beam, replace the slab, and rebuild the beam in the same way it won't delete it. Blocks deleted this way do not drop anything either, they just get yeeted out of existence.

> in addition, placing a beam at the edge of a block (like a windowsill) that has a hand basket placed on it deletes the basket
> both pre3 and 5 have this issue for me

> Placing a support beam on the same block as a chest completely erases the chest. It just disappears along with everything inside

> v1.18.0-rc.5  beams would destroy lanterns if placed in the same block

> I tried placing a support beam through a vertical rack. The beam was placed, but the rack and everything in it has vanished.

> On RC6 i placed a support beam behind a storage vessel and the latter disappeared

> just made a wooden slab top delete itself when placing multiple support beams under it
> 1.18.0 rc6

> Placing a support beam through a storage vessel will delete the vessel and all its contents

> Beams can consume blocks (such as slabs) sometimes -1.18 stable bug

> Has anyone else had the problem where placing a support beam will cause object to just vanish?

> Okay, REALLY bad bug, if you happen to put a support beam next to chests want to remove the beam after placing, it eats the chest. Had a support beam eat an entire large chest full of stuff (metals). Really sucks.

Seems to be one of the oldest unresolved 1.18 issues.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release
