### ISSUE TITLE
Beams blink out of existence from some angles

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2619]
### Game Version

1.18.0

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

This was in LAN and may be a multiplayer bug.
From certain angles, beams will disappear from view by the other player. I tried to reproduce this being the host of the LAN game and could not though the other player could. Video clip here: [https://clips.twitch.tv/ColdbloodedPoliteTapirPRChase-P9X-142EVMMjkMbA](https://clips.twitch.tv/ColdbloodedPoliteTapirPRChase-P9X-142EVMMjkMbA)

**Comment by radfast** [comment]
Fixed in upcoming 1.18.2
