### ISSUE TITLE
Hot metal bits don't hurt to have in inventory

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2621]
### Game Version

1.18.0

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

I smelted a bunch of copper and tin nuggets in a crucible and they had not melted yet. I had to adjust the recipe to add more and took some out for a moment. The 800+ degree nuggets did not hurt me and I had no tongs on me either. I then was burned from the crucible firepit and a hot helv hammer head regularly. Pretty sure it's only hot nuggets that were missed.

**Comment by Craluminum2413** [comment]
Were you holding them in hand?

**Comment by VallenFrostweaver** [comment]
No. Hmm. Now I test more, you can shift+click any hot item into your inventory and even place them in another without tongs. Effectively picking up and transporting them without tongs while hot but to work them requires tongs. I guess this isn't about the bits as much as it is about being able to have, move inventories, and transport hot items without a way of doing so on your person.
