### ISSUE TITLE
die instantly of hunger

### ISSUE THREAD

**Issue by daeagar** [anegostudios/VintageStory-Issues#2625]
### Game Version

v1.18.0

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I'm dying of hunger immediately without this being displayed or apparent

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by daeagar** [comment]
Its CarryCapacity 0.6.5.
if satiety=0 Life drops down immediately.
Thanks
