### ISSUE TITLE
[v1.18.8] Trader structure incomplete

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2626]
### Game Version

v1.18.0 to 1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

```assets\survival\worldgen\schematics\overground\tradeoutposts\caravan-wagon\large-2.json``` Hasnt been exported correctly

### Screenshots

![2023-04-20_17-00-38](https://user-images.githubusercontent.com/100879715/233407362-00ce163a-b0e5-41cc-b943-07093c6ea62b.png)

**Comment by AreYSerious** [comment]
Same goes for ```large-3```

**Comment by AreYSerious** [comment]
```large-4```
just reexport all thb xd

**Comment by AreYSerious** [comment]
![2023-04-20_17-05-42](https://user-images.githubusercontent.com/100879715/233408023-5d3651e5-d65e-46da-93e7-8f3e7fd7a42b.png)

**Comment by AreYSerious** [comment]
Thanks for confirming 😊

**Comment by AreYSerious** [comment]
1.18.8

![2023-08-10_16-12-28](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/207dd3f8-814a-4f89-9315-2b7db25ce86e)

**Comment by Th3Dilli** [comment]
ty, those are now fixed

**Comment by AreYSerious** [comment]
Awesome thank you 👍

**Comment by AreYSerious** [comment]
![2023-10-09_19-45-25](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/a3925313-b882-4201-9512-a8cf31091a4c)
:(

v1.18.14

**Comment by AreYSerious** [comment]
I cant reopen this myself? :(

**Comment by AreYSerious** [comment]
nvm its 1.19 my bad
