### ISSUE TITLE
crashes loading

### ISSUE THREAD

**Issue by stevcook** [anegostudios/VintageStory-Issues#2627]
### Game Version

18.0

### Platform

None

### Modded

None

### SP/MP

None

### Description

wont load crashes at leaf decay load

### How to reproduce

try to load

### Screenshots

none

### Logs

```Log```
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289538/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289539/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289540/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289541/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289542/server-storyevent.txt)
[server-worldgen.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289543/server-worldgen.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289544/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289545/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289546/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289547/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289548/client-main.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289549/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/11289550/server-build.txt)

**Comment by Craluminum2413** [comment]
You are loading too much mods

**Comment by stevcook** [comment]
ok thanksi will cut backHave a great day
    On Thursday, April 20, 2023 at 03:01:07 PM EDT, Dana ***@***.***> wrote:  
 
 


You are loading too much mods
