### ISSUE TITLE
WorldConfiguration settings in serverconfig.json not affecting worldgen on multiplayer servers

### ISSUE THREAD

**Issue by mrrhetorical** [anegostudios/VintageStory-Issues#2628]
### Game Version

v1.18.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I'm trying to change the landcover and oceanscale parameters within the WorldConfiguration section of the WorldConfig object in the serverconfig.json file on my multiplayer server, but it doesn't appear that it is affecting the world generation on my server at all. I've tried with about a dozen different worlds, and it looks like the worldgen is treating them both as default, as opposed to working as intended in single player. 

### How to reproduce

1. Modify the worldconfiguration.json file to modify the "landcover" and "oceanscale" values to something extreme to make it easy to tell if it's not working.
2. Make sure a new world will be generated when you start the server
3. Start the server

### Screenshots

![image](https://user-images.githubusercontent.com/8227749/233478589-783d1703-80fe-4d24-af07-e0729f128e11.png)
Here's what my WorldConfig section of my serverconfig.json looks like.

### Logs

```Log```

**Comment by noelle-lavenza** [comment]
![image](https://user-images.githubusercontent.com/101909198/233763777-a3a60bac-806d-40cd-9cf7-606553ce1dbc.png)
![image](https://user-images.githubusercontent.com/101909198/233763780-e1a95cd0-9c22-4d85-ae1d-162049087405.png)
![image](https://user-images.githubusercontent.com/101909198/233763781-494c14a9-7b95-454d-b6d1-920c61a53771.png)

Unable to replicate.

**Comment by tyronx** [comment]
I am also unable to reproduce this. Make sure your server creates a new world, existing worlds wont be affected by changing this value

**Comment by mrrhetorical** [comment]
In the following image I was first using the default worldgen it appears despite having the worldconfig values set in the serverconfig.json, then I used the /worldconfig commands to set the oceanscale and landcover values immediately after starting the server on a fresh world to what they already should've been from the config, and then past 1024 blocks it appears to change to the new worldgen.

![image](https://user-images.githubusercontent.com/8227749/233798265-e13200d2-df63-4f09-9fed-59bc09c0831d.png)

**Comment by mrrhetorical** [comment]
Appears like a problem other's are having too that is reproducible.

![image](https://user-images.githubusercontent.com/8227749/233798472-c231bfb2-d31f-45da-acb5-d3249f37c31d.png)

**Comment by noelle-lavenza** [comment]
The `/worldconfig` command sets it on the savefile, which *would* create seams. This is basically an unavoidable issue with changing it on an existing world.

The server config should be using `"2"` and `"0.3"`, not `2` and `0.3`. @mrrhetorical can you just upload the serverconfig you're trying to use?

**Comment by Secular12** [comment]
Is there a chance this may have something to do with the ConfigVersion? G-Portal, for instance, only has ConfigVersion 1.3 rather than 1.5 and as such does not have the landcover and oceanscale properties in the config file.

**Comment by tyronx** [comment]
I can only repeat myself -  you should not change this value on existing worlds, the engine is not designed for that.
