### ISSUE TITLE
Metal Plaques have combustible props and the incorrect block material

### ISSUE THREAD

**Issue by SunnyOpossum** [anegostudios/VintageStory-Issues#2637]
### Game Version

v1.18.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Metal plaques are useable as firepit fuel and have the block material "Wood"

### How to reproduce

Observe the plaques

### Screenshots

![2023-04-21_15-48-28](https://user-images.githubusercontent.com/60582335/233723463-2acd18a9-130d-4814-b8aa-371cb9168c56.png)

### Logs

```Log```

**Comment by SunnyOpossum** [comment]
Sounds are also wood.

**Comment by RedramVS** [comment]
Material changed to metal, combustible props removed.  Sounds changed to ingot sounds.
