### ISSUE TITLE
Some text needs shadows for higher contrast

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#264]
I noticed in the loading screen the even log would be more easily readable if the text had a shadow. This also applies to the `Ctrl+F3` information, interaction hints and possibly some other places that show text without known dark background?

**Comment by Craluminum2413** [comment]
Only `Ctrl + F10` has this

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
