### ISSUE TITLE
Really bad performance on high end PC, problems are tied to shadows/hud

### ISSUE THREAD

**Issue by V0g1** [anegostudios/VintageStory-Issues#2640]
### Game Version

v1.18.0

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Constant fps drops on my world. All fps drops resolved by disabling hud (f4), enabling it nearly halves my fps. When I disable shadows completly in settings I can play with hud without fps problems. So its somehow tied together. I will attach screenshots, client-main and server-main files, used commands: .debug logticks 20 and /debug logticks 100 during lag. I did tried disabling occlusion, disabling parts of hud from the options (showing info about block that im looking at) - no difference, still bad fps.  

According to fps meter provided by nvidia without hud on max settings i have avg.fps of 75 (refresh rate of my monitor) with 99%fps=74, where with hud my avg.fps are 60-65 but 99%fps are around 30fps and lower.

My specs:
RTX 4070
i5 12600k
32GB ram
NVME drive
Also im playing on ultrawide resolution 2560x1080
Everything in the settings maxed 

### How to reproduce

Just running around my world causes issues, there doest seem to be any pattern as to where lag happens

### Screenshots

![2023-04-22_04-47-53](https://user-images.githubusercontent.com/131506853/233760826-74910c67-949d-47b7-b361-cb7c069f42d4.png)
![2023-04-22_04-48-17](https://user-images.githubusercontent.com/131506853/233760849-8f37a0a4-f90a-49c0-b89c-739ce4c8f225.png)
![2023-04-22_04-51-49](https://user-images.githubusercontent.com/131506853/233760900-6818fdb1-51a8-42f8-b2d9-7d27d56c0a2e.png)
![2023-04-22_04-53-03](https://user-images.githubusercontent.com/131506853/233760928-21452de1-cc99-4f3e-9fed-bd74d5c493d3.png)
![2023-04-22_04-53-15](https://user-images.githubusercontent.com/131506853/233760970-21422b77-b389-43ac-afdb-a6b8cd95810d.png)
![2023-04-22_04-53-20](https://user-images.githubusercontent.com/131506853/233760995-a89155f3-1d49-41ae-acb6-84f8372b8c55.png)
![2023-04-22_05-10-05](https://user-images.githubusercontent.com/131506853/233761027-31f5e1bf-b8c5-4fcf-b392-8ebb19634132.png)
![2023-04-22_05-46-44](https://user-images.githubusercontent.com/131506853/233761076-37db7607-47d5-4970-a7de-9477a24eb246.png)
![2023-04-22_04-35-28](https://user-images.githubusercontent.com/131506853/233761096-9e09159a-b581-4f62-95a6-02d939d20f35.png)
![2023-04-22_04-35-34](https://user-images.githubusercontent.com/131506853/233761115-3faa40f1-0c8e-4916-a4f8-5d741fd8c3fa.png)
![2023-04-22_04-35-47](https://user-images.githubusercontent.com/131506853/233761145-793ec080-4724-4614-93f7-aa28e6b22d5e.png)
![2023-04-22_04-35-53](https://user-images.githubusercontent.com/131506853/233761191-1dbc9e03-5c9b-4b7b-b39e-2a7bbcc6adb5.png)
![2023-04-22_04-36-01](https://user-images.githubusercontent.com/131506853/233761215-6058a0c0-444e-427b-a696-e60dbde3f8d9.png)
![2023-04-22_04-44-25](https://user-images.githubusercontent.com/131506853/233761221-d7d3de90-eab3-4867-a510-afcc37b5061c.png)
![2023-04-22_04-44-30](https://user-images.githubusercontent.com/131506853/233761256-b0f0df32-d047-4b25-9c74-5ef1728e27be.png)
![2023-04-22_04-44-34](https://user-images.githubusercontent.com/131506853/233761303-0494889c-7bd0-41d1-b2fb-fe9c4bc390b9.png)
![2023-04-22_04-44-37](https://user-images.githubusercontent.com/131506853/233761334-2292ed22-99a2-4084-84f0-f7ce4419ddc7.png)

### Logs

```Log```
[client-main(1).txt](https://github.com/anegostudios/VintageStory-Issues/files/11300232/client-main.1.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11300233/server-main.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11300234/client-main.txt)
[server-main(1).txt](https://github.com/anegostudios/VintageStory-Issues/files/11300235/server-main.1.txt)

**Comment by tyronx** [comment]
Yes, high resolution monitor + shadows + forests are an FPS killer currently.

**Comment by tyronx** [comment]
if you can live with 75% resolution, that would alleviate some of that pressure on the videocard

**Comment by V0g1** [comment]
> Yes, high resolution monitor + shadows + forests are an FPS killer currently.

If it help you in some way rc6 version of 1.18 didn't had those performance problems for me. Is it an fixable issue in the future? Honestly bought new gpu mainly for Vintage Story and don't know what to do now

**Comment by V0g1** [comment]
Also first when I launch a game its fine, but after couple of minutes it just pumps performance like 50% down in some parts of the map

**Comment by V0g1** [comment]
> if you can live with 75% resolution, that would alleviate some of that pressure on the videocard

Even at 50% resolution fps are the same im now checking 
![2023-04-22_10-41-24](https://user-images.githubusercontent.com/131506853/233773489-0742779f-3de9-49cd-bd10-b81dc6cf9932.png)

**Comment by tyronx** [comment]
Looks to me like some sort of forced vsync on the driver end, maybe related to gsync/freesync?

**Comment by tyronx** [comment]
Leaving shadows at middle quality might help. Also make sure its not the mods causing the issue/

**Comment by tyronx** [comment]
Also update drivers. I seem to be able to get smooth 60 fps, interestingly - on a 4070 Ti with a 4k monitor

![2023-04-23_10-17-11](https://user-images.githubusercontent.com/762006/233825658-26cae62d-14a8-432c-90a5-34d9076d8c7c.jpg)

**Comment by tyronx** [comment]
See also https://wiki.vintagestory.at/index.php/Framerate_and_Performance

**Comment by V0g1** [comment]
> Looks to me like some sort of forced vsync on the driver end, maybe related to gsync/freesync?

Tyron you king, that was it. Instant 3x framerate and super smooth. I looked at your options and the problem was setting my max fps to unlimited. Such a weird behavior before because of this. I even planned returning my card honestly. Thank you so much again, now I can play one of my fav games again in nice quality :D

**Comment by tyronx** [comment]
Strange, but glad to hear you got it resolved 👍
