### ISSUE TITLE
SVG Icons No Longer Render Properly in GUI Dropdown

### ISSUE THREAD

**Issue by egocarib** [anegostudios/VintageStory-Issues#2645]
### Game Version

v1.18.0

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

This change:
`Feature: All waypoint icons are now loaded from svg files `
appears to have broken Icons in GUI dropdowns. The game now seems to render all icons on top of one another at the top-left corner of the dropdown area.

### How to reproduce

Mod that demonstrates the issue on 1.18:
<https://github.com/egocarib/Vintage-Story-Mods/releases/tag/2.5.0>

1. Run game with mod
2. Press Ctrl+Shift+M to open affected menu

Example code:
```cs
//Vintagestory.API.Client.GuiComposerHelpers.AddDropDown
.AddDropDown(
    values: icons,   // ["circle", "bee", "cave", "home", "ladder", "pick", "rocks", "ruins", "spiral", "star1", "star2", "trader", "vessel"]
    names: iconsVTML,   // ["<icon name=\"wpCircle\">", "<icon name=\"wpBee\">", "<icon name=\"wpCave\">", "<icon name=\"wpHome\">", "<icon name=\"wpLadder\">", "<icon name=\"wpPick\">", "<icon name=\"wpRocks\">", "<icon name=\"wpRuins\">", "<icon name=\"wpSpiral\">", "<icon name=\"wpStar1\">", "<icon name=\"wpStar2\">", "<icon name=\"wpTrader\">", "<icon name=\"wpVessel\">"]
    selectedIndex: GetIconIndex(icons, markerSetting),
    onSelectionChanged: OnMarkerIconChanged,
    bounds: markerOptionIconDropdownBounds.FlatCopy().WithParent(markerOptionRowBounds),
    key: markerSettingTitle + "-auto-markers-icon")
```

_Versions of mod for 1.17 and earlier can be found here: <https://mods.vintagestory.at/automapmarkers>_

### Screenshots

Starting in 1.18:
<img width="535" alt="map_icon_gui_post_1 18" src="https://user-images.githubusercontent.com/3429497/233793203-f53ba242-4126-4d4c-9a33-a767129fe570.png">

1.17 and earlier:
![map_icon_gui_pre_1 18](https://user-images.githubusercontent.com/3429497/233793169-00f0b241-2916-4548-9ec3-18a6166cbfa7.png)

**Comment by egocarib** [comment]
@tyronx - Any chance you know whether this would be a quick fix / something to expect in a near future version?

I looked into revamping my mod GUI to not use dropdowns, but that would be many hours of coding/redesign. If you don't think this will be prioritized, I understand and can look into revamping my mod, but was hopeful to get some input from game staff before I make that leap.

**Comment by tyronx** [comment]
heya, thanks for the report, this should be fixed next stable release 👍
