### ISSUE TITLE
Game crash at starting a game

### ISSUE THREAD

**Issue by Nougatyn** [anegostudios/VintageStory-Issues#2654]
### Game Version

v1.18

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Everytime I try to start a game single player or multiplayer I have the same error. I try to delete all mod I have but some still get here (not in mod folder). Don't even know where they are honestly. Thank you in advance for all answer. That is the message error the game give me:

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0 (Stable)
24/04/2023 00:00:58: Critical error occurred
Loaded Mods: 
System.Exception: Don't know how to instantiate item of class 'ItemMagicWand' did you forget to register a mapping?
   à Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) dans VintagestoryLib\Common\ClassRegistry.cs:ligne 273
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) dans VintagestoryLib\Common\Network\ItemTypeNet.cs:ligne 19
   à Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) dans VintagestoryLib\Client\Systems\Startup.cs:ligne 517
   à Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() dans VintagestoryLib\Client\Systems\Startup.cs:ligne 337
   à Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() dans VintagestoryLib\Client\Systems\Startup.cs:ligne 280
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 24/04/2023 00:01:01, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.0.0, horodatage : 0x64400ea0
Nom du module défaillant : KERNELBASE.dll, version : 10.0.22000.1817, horodatage : 0x9bd54449
Code d’exception : 0xe0434352
Décalage d’erreur : 0x0000000000052bac
ID du processus défaillant : 0x1c6c
Heure de début de l’application défaillante : 0x01d9762eecdda3d5
Chemin d’accès de l’application défaillante : C:\Users\caman\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Windows\System32\KERNELBASE.dll
ID de rapport : 33842c87-66f2-479c-90df-22358afb7c92
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 24/04/2023 00:00:58, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   à Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   à Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes()
   à Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 23/04/2023 23:58:05, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.0.0, horodatage : 0x64400ea0
Nom du module défaillant : KERNELBASE.dll, version : 10.0.22000.1817, horodatage : 0x9bd54449
Code d’exception : 0xe0434352
Décalage d’erreur : 0x0000000000052bac
ID du processus défaillant : 0x3010
Heure de début de l’application défaillante : 0x01d9762e996832d9
Chemin d’accès de l’application défaillante : C:\Users\caman\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Windows\System32\KERNELBASE.dll
ID de rapport : 444e8a31-eed0-42a4-b4cb-7c150eab31f3
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

### Logs

```Log```

**Comment by noelle-lavenza** [comment]
Looks like you may have disabled the base-game Creative mod. Can you make sure you have the Survival, Game, and Creative mods all enabled?

**Comment by Craluminum2413** [comment]
Incorrect install
