### ISSUE TITLE
Ink and Quills unplaceable 

### ISSUE THREAD

**Issue by Kaedwuff** [anegostudios/VintageStory-Issues#2655]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

The 'Ink and Quill' item currently is not able to be placed on surfaces like floors or tables.  I'm not sure if this is an oversight, because it is an object that lends itself to being on a desk, by its inherent nature.  Even its component item, the Bowl, can be placed on surfaces.

Aside from that, it's a bit odd that you can only write using black ink/dye - there seems to be support for colored text on signs, but not for books? 

### How to reproduce

Hold the quill and (shift) right click on a table.  Feel sad that your dreams of having a cute writing desk are crushed.

### Screenshots

N/A

### Logs

N/A

**Comment by RedramVS** [comment]
Ink and Quill are now ground-storable in quadrants.  Lack of ink colors is not a bug.  It will be added if and when time allows.
