### ISSUE TITLE
Placing schematic file, exported from 1.17 to the 1.18 is crashing client

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#2656]
### Game Version

1.18.0

### Platform

Windows

### Modded

Modded, 
Mods in the 1.18: creaturescan@1.0.0, extrachests@1.7.0-pre.1, primitivesurvival@3.1.6, rope-bridges@1.1.0, game@1.18.1, wildcraft@1.6.4, carryon@1.0.0, djinlandessentials@1.1.0, electricity@0.0.8, hudclock@2.9.1, sailboat@1.0.0, medievalexpansion@3.9.0, morebags@1.2.0, mcrate@1.0.4, stonerailings@1.0.4, creative@1.18.1, survival@1.18.1, workbenchexpansion@1.6.0

Mods in the 1.17 server, from where has been exported the schematic file:
mod@458195964_RopeBridgesv1.1.0forVS1.15, mod@AlphaWeaponPack_v1.3.1, mod@ExtraChests_v1.6.0, mod@fancydoors_v1.16.5-1.1.1, mod@PrimitiveSurvival3.0.5, mod@tradeomat_v1.17.1-1.6.3, mod@wildcraft-v1.5.1, mod@DjinlandEssentials.1.0.5, mod@Electricity, mod@medievalexpansion-3.8.1, mod@MoreBags-1.2.0, mod@MultiblockCrates-v1.0.4, mod@petai_v1.5.5, mod@StoneQuarry_v1.17.4_v2.0.0-rc.4, mod@StoneRailings.1.0.4, mod@workbench-expansion-1.5.1, [mod@FeverstoneHorses-v1.3.9-rc.2-1.17.x](mailto:mod@FeverstoneHorses-v1.3.9-rc.2-1.17.x

### SP/MP

Multiplayer

### Description

We started a new world on v1.18.0 and we want to transport our buildings from an old 1.17 world to the new 1.18 world, as advised. We use a plenty of mods (see the complete mod list in the log file, included). Note that in the 1.17 we used some mods (StoneQuarry, AlphaWeaponPack), which are not ported to the 1.18 yet, so there are probably some blocks/items from those mods in the exported schematic file. And those mods are missing in the 1.18 server.
Situation 1 - When I try to import the schematic to the Single vanilla **without mods**, it imports correctly. Any modded block/item are removed during import. The building is correctly imported includin vanilla items in chests etc.
Situation 2 - When I try to import the schematic to the 1.18.0 server, it crashes client and places the house partially. It thows an NullReferenceException, which somehow interrupts import, so a lot of blocks is not imported, chests for example lost labels and cannot be open, the placed building is somehow corrupted, when I login back to the server.

I tried the import many times and I went into a situation, when my client was crashing whenever I logged in, because my player was in the problematic place, immidiatelly after logged in. I had to login under different admin account, teleport near to the problematic location with visibility set to 32 and used /wgen reggen to regenerate the corrupted chunks.

During my tries to import, I noticed that the Wordedit is in some corrupted state. For example, after regenerating chunks, I wanted to import the schematic to the same place again. So first I use the selection mod in Worldedit and selected some area to prepare place for the house. Then I clicked to the delete button in the Worldedit UI to delete the selected area. In this moment there appeared some parts of the corrupted building, which I was importing before. It seems that the Worldedit has it somewhere in a cache or in a history buffer and wrongly placed it instead of deleting the selected area.

To summarize: The Worldedit and the schematic import process is really buggy, it's pain to use it, it crashes client and it seems to be almost unusable. I know that the problem has been caused by mods, but it should not crash a client, it should at least remove a problematic blocks/items and continue working. The worldedit needs some de-janking and debugging imho.

Unfortunately, the promised way howto move to the new 1.18 world from our old world by transferring our buildings by using schematic, doesn't work as expected. So confusing. I hope that devs will fix it soon.

We love playing VS very much, so it is pitty that we cannot move to the new world. :-/

EDIT2: We found the problematic thing, which has been crashing client. It's the Particulator from the Primitive Survival mod - the configurable cube, which can generate particles. When we removed it from the house and removed all modded items/blocks from chests, then it was able to import to 1.18. But I had to logoff/logon to see the imported house and still there were a lot of errors in server's log. But at least, we were able to import. I enclosed the modified schematic below.

### How to reproduce

Im ready to assist devs with anything. Thanks!

### Logs

[ServerLog.txt](https://github.com/anegostudios/VintageStory-Issues/files/11307804/ServerLog.txt)
[ClientCrash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11307806/ClientCrash.txt)

Edit: here is the schematic file, which I couldn't import.
[JohnyhoExpedicniDum.zip](https://github.com/anegostudios/VintageStory-Issues/files/11312903/JohnyhoExpedicniDum.zip)

Edit2: The schematic file without the problematic particulator and modded items, see the Edit2 description above.
[JohnyhoExpDumBezModu.zip](https://github.com/anegostudios/VintageStory-Issues/files/11319249/JohnyhoExpDumBezModu.zip)

**Comment by fipil** [comment]
I modified the issue description, added new facts, see Edit and Edit2 sections.

**Comment by Th3Dilli** [comment]
with 1.19 we have made a lot of improvements to worldedit  and schematics as well as importing so all issues should be resolved
and you are now able to import schematics from older game versions
