### ISSUE TITLE
If I build a column of dirt in the water from the bottom to the surface and then remove it, the column of air remains. Water won't fill it

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#2660]
### Game Version

1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer/Singleplayer

### Description

build a column of dirt in the water from the bottom to the surface and then remove it, the column of air remains. Water won't fill it. Tried on sea and lakes as well. Same result.

### How to reproduce

Create a new world, find some water lake or sea and build a column from dirt or any other blocks from the bottom to the surface.
Then remove those blocks. The column of air remains there.

Expected behaviour: the water will fill the air by still water.

### Screenshots

![2023-04-25_20-58-34](https://user-images.githubusercontent.com/768590/234376347-1b62d35f-6e0c-4277-a3e4-d005f09643ad.png)

**Comment by radfast** [comment]
Thank you for reporting.  This is fixed in upcoming 1.18.2
