### ISSUE TITLE
Unknown texture when placing vertical wooden slab near snow

### ISSUE THREAD

**Issue by SamMadeChannel** [anegostudios/VintageStory-Issues#2661]
### Game Version

1.18.1 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Unknown texture " ? " appears in the gap between a vertical slab and an adjacent pile of snow.

### How to reproduce

1. Place a vertical slab (in my case Walnut) on the ground, opposite to a block that has snow on top. The empty gap between the vertical slab and the snow will show a red " ? " on a white background, as if it's trying to fill that gap with snow but the desired texture is not found.
2. Removing the snow or the slab clears the " ? " texture and shows the ground texture again.

### Screenshots

![2023-04-25_20-59-57](https://user-images.githubusercontent.com/36215122/234439377-83bf3355-f113-4823-8da5-2f05f97fc11d.png)
![2023-04-25_21-02-23](https://user-images.githubusercontent.com/36215122/234439667-51c35809-2b94-4356-b97a-5a243382e86e.png)

### Logs

```Log```

**Comment by RedramVS** [comment]
I cannot reproduce this.  I'm assuming it's been fixed sometime in the past 7 months, but feel free to reopen if it is actually still a problem.
