### ISSUE TITLE
"newSeraphVoices" config option persisting after update

### ISSUE THREAD

**Issue by Blazingi** [anegostudios/VintageStory-Issues#2667]
### Game Version

v1.18.1-archlinux(aur)

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Upgrading vintage story with persisting config leaves `"newSeraphVoices": false` if you had experimental voices off. Presently there is no option in GUI settings to toggle the option, making the character mute.
This option should be defaulted to true on config version update, but possibly left valid if someone prefers a mute character, maybe even a mute option on charsel.

### How to reproduce

1. Install 1.16.x version
2. Disable experimental seraph voices
3. Upgrade to 1.17.x+
4. Load game, take damage, the character is mute.

**Comment by Th3Dilli** [comment]
thank you for reporting

we now fully removed that setting so it should not effect anything now

will be released with version 1.19
