### ISSUE TITLE
1.18.1 Text not translated

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2670]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Text not translated in the game though French translation in Crowdin is 100% done.

### Screenshots

![Not translated 09](https://user-images.githubusercontent.com/26251843/234922868-2dbe1114-830c-4094-90ca-63e0f3324aec.png)

![Not translated 10](https://user-images.githubusercontent.com/26251843/234924368-bb1cb502-1828-4b54-8569-ce8bd20f1bdc.png)

![Not translated 11](https://user-images.githubusercontent.com/26251843/234956571-fd332953-e40b-49f1-8fe5-983d97449c7a.png)

![Not translated 12](https://user-images.githubusercontent.com/26251843/235067487-79b8bd93-0d2b-4e30-8c78-bc8319ec88f7.png)

![Not translated 13](https://user-images.githubusercontent.com/26251843/236145822-93a5c88b-e523-4603-b1d7-2a8e1a09ba72.png)

![Not translated 14](https://user-images.githubusercontent.com/26251843/236213195-a2580b58-fb9a-4327-8d1f-af7498f92664.png)

![Not translated 15](https://user-images.githubusercontent.com/26251843/236672632-5ec2a4f8-b6e4-4a22-8c1c-67ac3e365374.png)

**Comment by radfast** [comment]
Thank you for the careful report and screenshots, it is very helpful.

All these localizations will be included in 1.18.2.

In CrowdIn look for new strings: 

    "count-days": "{p0: none|# day|# days}",
    "Edit book": "Edit book",
    "gamemode-Survival": "Survival",
    "gamemode-Creative": "Creative",
    "gamemode-Spectator": "Spectator",
    "gamemode-Guest": "Guest",
    "population-Poor": "Poor",
    "population-Decent": "Decent",
    "population-Large": "Large",
    "Search Creative inventory": "Search block/item from the Creative inventory",
    "World Edit": "World Edit",

Some other of the needed strings for example "Show Handbook" for the H hotkey were already translated but not accessed in game code, now they are.

Note that `count-days` uses our new "pluralization" format as an example.  This can specifically allow different pluralization between English and French (and other languages): see also https://www.unicode.org/cldr/charts/42/supplemental/language_plural_rules.html
