### ISSUE TITLE
Mod schematics sometimes (?always) placing one block too low

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#2671]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Can the new doors pls not rotate in worldgen would be nice
![2023-04-27_20-43-52](https://user-images.githubusercontent.com/100879715/234961584-841cb63f-a84b-494b-bf10-967452850747.png)

### Logs

```Log```

**Comment by AreYSerious** [comment]
![2023-04-27_20-48-00](https://user-images.githubusercontent.com/100879715/234962387-41da1fae-570d-4327-8829-3e24fbf06f27.png)
replacewithblocklayers not working everytime

**Comment by radfast** [comment]
The replacewithblocklayers, please can you share that schematic for testing

**Comment by AreYSerious** [comment]
@radfast

I have a mod called BetterTraders just load into a world with it and you will see the issues.
The files are there aswell

**Comment by AreYSerious** [comment]
First of all below chiseled blocks it's not working.
And sometimes in gravel or sand it's not working

**Comment by radfast** [comment]
The original reported issue with door rotations will be fixed in 1.18.2.

Are you 100% confident that the gravel/sand thing is not working __in version 1.18.1__?  I mean, are you sure that these are chunks where all the worldgen occurred in version 1.18.1 not 1.18.0?    Best to test in a brand new 1.18.1 world to be sure.   This gravel/sand issue should have been fully fixed in 1.18.1.   If you believe it is a confirmed issue in 1.18.1, please provide a worldseed and world coordinates for a trader with the problem (and please only test with vanilla + the BetterTraders mod, no others, and please use all default world settings otherwise - I need to reproduce the issue at the same exact spot and then breakpoint the code to investigate why it is not working as intended)

**Comment by AreYSerious** [comment]
I dont really think this will work.... Bcs structures aren't seed bound and always random. I can Send some more screenshots in the coming days and do more testing

**Comment by AreYSerious** [comment]
@radfast
![2023-04-27_20-52-12.jpg](https://user-images.githubusercontent.com/100879715/235741196-d84e1ab3-bf02-41e9-96ec-547ed3bd3e85.jpg)

The picture shows an example of it not working.

**Comment by AreYSerious** [comment]
And a user has sent me this aswell.
I don't know the version of it but most likely 1.18.1

![2023-05-02_18-19-22.png](https://user-images.githubusercontent.com/100879715/235741667-cde18608-fd74-4f33-a0b5-27779bc5ea80.png)

![2023-05-02_18-19-32.png](https://user-images.githubusercontent.com/100879715/235741668-8ce2b7d4-290a-4aa6-abf4-f039a8d06c15.png)

**Comment by AreYSerious** [comment]
And more 1.18.1 worldgen showing replaceblocklayer thing not working

![2023-05-02_20-26-10.png](https://user-images.githubusercontent.com/100879715/235778622-aaafeea2-8319-48f7-92fb-f563153e3aa4.png)

![2023-05-02_20-50-05.png](https://user-images.githubusercontent.com/100879715/235778620-b16eda75-26db-4f57-aad2-f7454473812c.png)

![2023-05-02_20-39-53.png](https://user-images.githubusercontent.com/100879715/235778621-86c90ec6-114a-4456-a71a-8249933eeb46.png)

**Comment by AreYSerious** [comment]
![2023-05-10_19-00-48](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/885e5c3f-5ecb-430f-a975-a9c5a9d9c9a2)
in 1.18.2 rc4

**Comment by AreYSerious** [comment]
![2023-05-10_19-02-40](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/c15ef11a-2f34-4cf9-98b6-24ab9a2d409b)
in 1.18.2 rc4
clutterblocks ? when spawing via worldgen?

**Comment by AreYSerious** [comment]
![2023-05-10_19-02-45](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/6f4fcd1e-8118-4d63-8c2e-4d7180a06471)
Chiseled blocks aswell

**Comment by AreYSerious** [comment]
[ruin with mutliple errors while worldgen.zip](https://github.com/anegostudios/VintageStory-Issues/files/11444594/ruin.with.mutliple.errors.while.worldgen.zip)
This is the ruin 
maybe you can replicate and fix the issues
all the 3 errors accour on this ruin in the latest version and I could replicate them 100%

**Comment by AreYSerious** [comment]
v1.18.5

![2023-05-21_15-58-17](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/452c0712-bfe1-4edc-b1d6-ff0b7b82b401)

some blocks still dont adjust to the correct ground blocks

**Comment by AreYSerious** [comment]
![2023-05-21_16-54-43](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/1afa2392-3698-406f-bfd5-92cc1beb5aa8)
v1.18.5

**Comment by AreYSerious** [comment]
> [ruin with mutliple errors while worldgen.zip](https://github.com/anegostudios/VintageStory-Issues/files/11444594/ruin.with.mutliple.errors.while.worldgen.zip)
> This is the ruin 
> maybe you can replicate and fix the issues
> all the 3 errors accour on this ruin in the latest version and I could replicate them 100%

I found the problem for this issue.
It's first of all fruit trees can somehow crash the client.
But the main problem are firepits via worldgen. If they contain something or in this case rot in a cooking pot it will result in this wierd error

**Comment by AreYSerious** [comment]
Going to split this into 2 new issues 

1. being the firepit issue

2. being the soil replace

**Comment by AreYSerious** [comment]
Moved to 

https://github.com/anegostudios/VintageStory-Issues/issues/3010

and

https://github.com/anegostudios/VintageStory-Issues/issues/3011
