### ISSUE TITLE
Metal parts inventory image is not centered

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2674]
### Game Version

1.18.1

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Hover over metal parts in your inventory to see the image rotate incorrectly. A single frame copy:
![image](https://user-images.githubusercontent.com/13642054/235125098-49b689c1-7cfb-4b5e-b7b7-08225a4e2d1c.png)

**Comment by Th3Dilli** [comment]
thank you for reporting, it will be fixed with the next version
