### ISSUE TITLE
Can't pick up items from hot spring water.

### ISSUE THREAD

**Issue by Blazingi** [anegostudios/VintageStory-Issues#2676]
### Game Version

v1.18.1-archlinux(aur)

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Items dropped into the hot spring hot water can't be picked up by standing on ledge or jumping into the hot water

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Can't reproduce
