### ISSUE TITLE
game buged

### ISSUE THREAD

**Issue by Pernicketyfud** [anegostudios/VintageStory-Issues#2679]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Hello, translated by reverso.
My character seems stuck in space.
No Comand Debugger for me.
I broke a pothole on the floor and it broke the game.
I could no longer interact with the game. I restarted and found myself in space.

It’s no big deal, I only played 18 hours.
But I wanted to talk to you about it.

I love your game.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What mods do you use?

**Comment by Pernicketyfud** [comment]
animalcages_v2.1.4
BetterRuinsv0.1.0
CarryOn-1.18.0-rc.8_v1.0.0-rc.3
cats_v1.7.0_petai_v1.7.+
creaturescan_v1.0.0
FeverstoneHorses-v1.5.0-1.18.x
FromGoldenCombs-1.18-v1.4.16-rc.2
hangingoillamps_1.0.1
medievalexpansion-3.9.1
MoreAnimals-1.2.3
petai_v1.7.1
wolftaming_v1.7.0_petai_v1.7.+

**Comment by radfast** [comment]
> I broke a pothole on the floor and it broke the game.

Screenshot please?

**Comment by Pernicketyfud** [comment]
![Capture d’écran 2023-04-29 194226](https://user-images.githubusercontent.com/132137063/235316650-24c39dbb-4a11-4212-8733-b0d43084400a.png)

**Comment by radfast** [comment]
Thanks, it is likely a mod issue.   Can you post `client-main.txt` log?   Maybe a clue in the log

**Comment by Pernicketyfud** [comment]
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11359805/client-main.txt)

**Comment by radfast** [comment]
Thank you for the log.  Many mod issues are reported in that.  Some of these mods need to update better for 1.18.1, examples are FeverstoneHorses, Creaturescan and HangingOilLamps.

Please can you also now post the `server-main.txt` log and `server-debug.txt` log for a game session where you have this issue that you posted ... so play until the issue happens, then wait like 10 seconds to make sure the log file is saved, then save and exit the game and post the logs please.

Other suggestions:
1. Update all mods to the latest version available
2. Try disabling some of the mods, start a new world, and see if you still have the issue

**Comment by Pernicketyfud** [comment]
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11364076/server-debug.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11364078/server-main.txt)

**Comment by Pernicketyfud** [comment]
I think Mod BetterRuin he’s responsible.I once managed to launch the game without being in space. 
the element of chateau decor in which I made my house no longer interacts while the exterior elements yes. Also some of the decor will display in white with a point of interogation.

**Comment by Pernicketyfud** [comment]
if I disable the mod, the game does not launch.
But if I activate it, I end up in space.

**Comment by radfast** [comment]
The problem is the `MoreAnimals` mod.  Try disabling that and I think everything will be OK

**Comment by Pernicketyfud** [comment]
![Capture d’écran 2023-05-01 161943](https://user-images.githubusercontent.com/132137063/235466034-fbe0e5bd-ad69-4302-9d88-5b3aa902b9b2.png)
Thanks for your help, the game starts but I still have the problem related to BetterRuins!
