### ISSUE TITLE
Instantly pick up broken blocks

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#268]
I think the default for breaking blocks should be picking them up automatically (regardless of distance), rather than first dropping the item, waiting for the pickup timer to elapse, and **then** being able to pick it up. There might be some instances where it would make sense, such as breaking stone or choppng trees, or perhaps in general when not using the right tool. But otherwise, I don't see a reason to adopt this behavior from Minecraft.

**Comment by Craluminum2413** [comment]
I believe it can be done with help of Vintagestory.API.Common.EntityItem.CanCollect by changing itemSpawnedMilliseconds value

**Comment by copygirl** [comment]
That workaround would only work if you're also standing in pick-up range, I think.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
