### ISSUE TITLE
Failing to place a beam without canceling still overwrites the block at the starting position

### ISSUE THREAD

**Issue by noelle-lavenza** [anegostudios/VintageStory-Issues#2684]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

https://github.com/anegostudios/vssurvivalmod/blob/fecc4d6c50c74e08a5dc7869eff7f967bc2577ac/Block/BlockSupportBeam.cs#L116 - overwrites the block at startPos when a beam is placed
https://github.com/anegostudios/vssurvivalmod/blob/fecc4d6c50c74e08a5dc7869eff7f967bc2577ac/Block/BlockSupportBeam.cs#L136 - early return if too few beams to place

These are in the wrong order. It should return before making any changes to the world if you're unable to place a beam.

This is actually the direct cause of #2591 and #2537, and can trigger both #2591 as well; it deletes the ladder by overwriting `startPos`, and the reason the block occupies space while being invisible is because a beam block was placed without any beams being added.

### How to reproduce

1. Start placing a beam.
2. Finish the beam without canceling it, i.e. via having too few beams in your inventory or by having the endpoint be at exactly the start point.
3. There is now a beamless beam block at the startPos, which is especially bad if a block already existed at the startPos, i.e. a bucket or chest.

**Comment by Th3Dilli** [comment]
thanks for the report

this should have been solved since #2618 is fixed and closed

**Comment by Th3Dilli** [comment]
this is still an issue I did close that to early but its getting fixed now
