### ISSUE TITLE
Beams can be placed in claims without permission

### ISSUE THREAD

**Issue by noelle-lavenza** [anegostudios/VintageStory-Issues#2686]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Beams can be placed inside claims. Combined with #2618 this has massive griefing potential.

### How to reproduce

1. Find a trader in singleplayer, or a player claim in multiplayer
2. Confirm that you can't place/break blocks normally there
3. Successfully place a beam

**Comment by tyronx** [comment]
this should be fixed in 1.18.3, please do verify. thanks for the report!
