### ISSUE TITLE
Plants that use a specific shape not using specified renderpass

### ISSUE THREAD

**Issue by Asmidus** [anegostudios/VintageStory-Issues#2687]
### Game Version

v1.18.1

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

The issue is exactly the same as https://github.com/anegostudios/VintageStory-Issues/issues/921 but it only impacts plants that use the "1patch-dense-24x24" shape. This appears to be because the fix for that issue was setting the renderpass to "opaqueNoCull" instead of "blendNoCull", but all the plants using this shape appear to only ever render as "blendNoCull", which is why these plants still have this bug.

Setting the renderpass in flowers.json to Opaque will show that every plant that doesn't use this shape will have rendering artifacts with terrain. The plants using this shape seem to be forced into the blendNoCull renderpass for one reason or another. Changing the shape of the problematic plants (heather, dwarf furze, and orange mallow) to any other plant shape fixes the problem and the plants then appear to abide by the renderpass set in the json file.

### How to reproduce

1. Set the renderpass in flowers.json to Opaque
2. Place all the types of flowers
3. Step back a bit and watch as the plants that use "1patch-dense-24x24" cause no rendering problems while the others do (which, I think, proves that they are forced to use blendNoCull and as a result suffer from the same bug in https://github.com/anegostudios/VintageStory-Issues/issues/921)

### Screenshots

![image](https://user-images.githubusercontent.com/37638316/235334422-654803c2-c752-4e9e-a9b3-15b301e44633.png)

**Comment by noelle-lavenza** [comment]
That's because it specifies `"renderPass": 2,`. It's entirely possible flowerpots, `1patch-cross-24x24`, and anything else that uses `"renderPass": 2` also have this issue.

**Comment by Asmidus** [comment]
Didn't even occur to me that the shape would be specifying the renderpass since the other shapes I've looked at didn't. Removing the renderpass lines in the shape files fixed it for me.

**Comment by kousakak** [comment]
This issure still exist now in 1.18.4...
![screenshot](https://github.com/anegostudios/VintageStory-Issues/assets/60339803/dc083a78-f233-430a-9f2d-2cb30296d70f)
