### ISSUE TITLE
PLEASE HELP CRUSH

### ISSUE THREAD

**Issue by Antonypasech** [anegostudios/VintageStory-Issues#2696]
### Game Version

V. 1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Please HELP!

### Logs

```Log```
Game Version: v1.18.1 (Stable) by OverF1X  
03.05.2023 13:24:54: Critical error occurred
Loaded Mods: HangingOilLamps@1.0.1, instruments@1.2.0, pieontheshelf@1.0.0, primitivesurvival@3.1.8, RangedWeapons@0.6.2, game@1.18.1, canbeignited@1.1.0, carryon@1.0.0, creative@1.18.1, survival@1.18.1
System.IO.FileNotFoundException: Не удалось найти указанный файл.
   в Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) в VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:строка 51
   в Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, CompositeShape forShape, MeshData& modeldata) в VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:строка 679
   в Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateItems(IList`1 itemtypes, Int32 offset, Int32 maxCount) в VintagestoryLib\Client\Render\Tesselation\ShapeTesselatorManager.cs:строка 848
   в Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step7(Int32 index, Int32 frameCount) в VintagestoryLib\Client\Systems\Startup.cs:строка 713
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) в VintagestoryLib\Client\ClientMain.cs:строка 755
   в Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) в VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:строка 304
   в Vintagestory.Client.ScreenManager.Render(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 724
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 627
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 126
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 479
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 454
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

**Comment by Craluminum2413** [comment]
Pirated versions are not supported
