### ISSUE TITLE
Some sheared leaves appear again after relog

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#27]
1.5.2.2, observed on official server (bronze and copper shears) and in creative singleplayer (iron shears).
Google drive dir with screenshots (original tree, sheared tree, after relog):
https://drive.google.com/open?id=1937yicOOwaJX4_FmiCSVyWXyajg6ddJL
Description:
When shearing all leaves of a tree or a tree farm, about 5-10% of them randomly reappear after relog.
Sometimes they reappear even withour relog, e.g. when you place a ladder near them.
Also the branchy ones may damage player with suffocation when he enters the ghost block.
Noticed on all trees except bamboo. Tried to reproduce on bamboo in creative world, on about 20 trees - no single ghost leaf block.

**Comment by tyronx** [comment]
The challenges of multiplayer development... fixed for 1.5.2.3
