### ISSUE TITLE
Knapping problems

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#270]
- [ ] Can't knap stone with another stone while standing on it.
- [ ] Similarly, can't place flint to knap at your feet.
- [ ] Can't knap two stones of different types together.
  (No message for stones that are too soft, either.)
- [ ] No interaction hint for knapping.

Starting knapping at your feet might not be allowed due to the bounding box clipping the player, so it's like placing a block where you're not supposed to; but I feel like maybe there should be an exception for cases like these, where it's "silly" at best and confusing at worst to be unable to place something so minor just because you slightly clip into that block.

**Comment by tyronx** [comment]
> Can't knap stone with another stone while standing on it.
>Similarly, can't place flint to knap at your feet.

Removed the collision box now, that will fix this issue

>(No message for stones that are too soft, either.)

Seems to be there by now 

>Can't knap two stones of different types together.
>No interaction hint for knapping.

Fixed the latter, which mitigates the former. 

Will be in v1.10.9
