### ISSUE TITLE
"entity filters" don't seem to work with (at least) /entity remove

### ISSUE THREAD

**Issue by Nic0d3mu5** [anegostudios/VintageStory-Issues#2710]
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Hi, the "entity filters" don't seem to work with "/entity remove" command, and maybe with the other commands related to entities.

### How to reproduce

1. Stay close to a lamb
2. Enter the command "/entity remove e[sheep-bighorn-lamb,1,true]"
3. All entities on loaded chunks will be removed, not just lambs nearby

I was not sure about the command form, so I also tested:

1. Stay close to a lamb
2. Enter the command "/entity remove e[type=sheep-bighorn-lamb,range=1,alive=true]"
3. A message will say "no entity found"

### Logs

```Log```

**Comment by Craluminum2413** [comment]
I tried this `/entity remove e[type=sheep-bighorn-lamb,1, true]` on 1.18.2-rc.2 and it worked

**Comment by Nic0d3mu5** [comment]
> I tried this `/entity remove e[type=sheep-bighorn-lamb, range=10, alive=true]` on 1.18.2-rc.2 and it deleted all lambs within 10 blocks. Don't forget that `type=`, `range=` etc. must be added, it will not work otherwise

Oh dam, 1 for the range is equal to 1 block... ok x) Sorry then.
And thank you Craluminum ;)
