### ISSUE TITLE
Not full reinforced blocks lose reinforcement when filled with water

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2716]
### Game Version

1.18.2-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

1. Place a bucket
2. Reinforce it
3. Get a bucket with water
4. Fill block with placed bucket with water
5. Try to break placed block
6. It breaks, no reinforcement

**Comment by radfast** [comment]
Fixed next release.  It was a 1-character change in the code ;)  Of course finding that character took a good couple of hours
