### ISSUE TITLE
Barrel cannot be reinforced

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#2717]
### Game Version

1.18.2-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

**Comment by radfast** [comment]
I believe it can be reinforced, it just was not displaying the reinforcement correctly in the Block Info HUD element, see #2719.  Anyhow this is now fixed in next release.  Thank you for reporting!

**Comment by radfast** [comment]
Thanks @Craluminum2413, seems nailing down a barrel is more difficult than I thought.   And I went and broke the HUD info
