### ISSUE TITLE
Snow NEXT to ANY vertical slab not snowed on renders as ?

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2718]
### Game Version

1.18.1

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

See image. 1 layer of snow fell on this half slab of Ancient Stone and is now a ?
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/ed4f571b-dcf8-4ad5-b818-f3d0c8a6af68)

**Comment by Craluminum2413** [comment]
What is ancient stone? Is it vanilla block? How it is crafted

**Comment by VallenFrostweaver** [comment]
It's vanilla. It's a very rare material from pure white marble-like ruins. I don't know that it can be crafted, just found in the world or creative menu

**Comment by radfast** [comment]
See also https://discord.com/channels/302152934249070593/334233095374897152/1105537487222345738

**Comment by RedramVS** [comment]
Can't reproduce, going to assume it was fixed sometime in the past 7 months.
