### ISSUE TITLE
Chiselled blocks breaks soundproofing of weather effects in valid rooms

### ISSUE THREAD

**Issue by okwelp** [anegostudios/VintageStory-Issues#2720]
### Game Version
1.18.2-rc.4
1.18.1 (Stable)
(Tested on both 1.18 versions)

### Platform
Windows

### Modded
Vanilla
Modded
(Tested on a fresh install and with a moderate modlist)

### SP/MP
Singleplayer

### Description

Hi VS team, 

It seems that chiselling a block stops the soundproofing of weather effects. This can make a valid room sound like it's in the wide open during a rainstorm. The soundproofing disappears when the block gets turned into a chisel-able type, even if the original material is preserved.

Not a massive issue but not great for immersion either!

### How to reproduce
See this video for a demonstration: https://youtu.be/oIAxgCCevU8

**Comment by okwelp** [comment]
I've just realised there is an issue template to follow (not sure how I managed to raise this without using it) and I can't retroactively apply it. I'll close this issue for now and raise it in future.

**Comment by radfast** [comment]
I've marked this as a duplicate of #2746 for tidiness, even though 2746 is obviously the newer issue.  Thanks for reporting, we will be aiming to fix this.

**Comment by okwelp** [comment]
Thanks a lot and sorry for messing up the first report!
