### ISSUE TITLE
Broken item in water physics

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2723]
### Game Version

v1.18.2-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When items are thrown in water they begin to jitter and slowly float east.

### How to reproduce

Toss any item into a body of water

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/126715524/703ca022-fc3d-4f7c-82f2-c073021061d3

https://github.com/anegostudios/VintageStory-Issues/assets/126715524/26d1ab1b-85e6-43cf-b0b9-7ec8771cc3c7

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.20
