### ISSUE TITLE
Shadow offset

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#273]
This happens regardless of shadow quality.

![image](https://user-images.githubusercontent.com/272586/56735192-1c8ef700-6765-11e9-8592-30189e099f3c.png)

**Comment by tyronx** [comment]
Called peter panning and next to impossible to get completely rid of. Higher shadow quality settings should mitigate the problem and v1.10 further reduced shadow glitches though.

**Comment by copygirl** [comment]
Should this issue be closed if it's still semi-present?

**Comment by tyronx** [comment]
yes, "next to impossible" means resolution: Won't fix
