### ISSUE TITLE
Wooden path is only craftable with Board (Aged)

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2730]
### Game Version

1.18.1

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When crafting wooden paths you can currently only use Aged wood boards instead of with any boards.

**Comment by Craluminum2413** [comment]
As far as I know, it is intended feature since 1.15 or 1.16, can't find any changelog about this change though

**Comment by DArkHekRoMaNT** [comment]
The paths have always been made from aged boards, this is not a bug
