### ISSUE TITLE
On character creation, closing Handbook unpauses game while still in Character Creation menu

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2732]
### Game Version

1.18.1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When you are making a character you can click on links in the class menu (like "bows and arrows" link for a Hunter - see below image) to see the exclusive craftables the classes have access to. Upon closing the handbook menu (not the character/class creation menu) it then unpauses the game. You still may want to view the rest of the classes but are now cycling time as you read about them.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/a55b2586-51a9-40c9-9f27-b4830cbb471a)

**Comment by CookieBoy21** [comment]
In 1.19.7 as long you will not click pause button to turn off pause while handbook is open, game will be still paused until you will finish your character. I think this issue can be close.

Just don't click this button!
<img width="1280" alt="Vintagestory Screenshot 2024 05 04 - 18 36 52 89" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/794d1202-005c-41fd-921b-d46eeffd2d59">
