### ISSUE TITLE
Book issue

### ISSUE THREAD

**Issue by MurianEmperor** [anegostudios/VintageStory-Issues#2734]
### Game Version

v 1.18.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In book interface i just press left arrow.

### How to reproduce

1) Open book
2) Write something 
3) Press left arrow on last row in book

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.2 (Stable)
12.05.2023 23:14:08: Critical error occurred
Loaded Mods: game@1.18.2, creative@1.18.2, survival@1.18.2
System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
   в System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   в Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) в VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:строка 78
   в Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) в VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:строка 281
   в Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) в VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:строка 266
   в Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) в VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:строка 174
   в Vintagestory.GameContent.GuiDialogEditableBook.OnKeyDown(KeyEvent args) в VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:строка 239
   в Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) в VintagestoryLib\Client\Systems\Gui\GuiManager.cs:строка 361
   в Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) в VintagestoryLib\Client\ClientMain.cs:строка 1738
   в Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) в VintagestoryLib\Client\ClientPlatform\Input.cs:строка 250
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:строка 130
   в OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:строка 646
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:строка 828
   в OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:строка 1551
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 369
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 20.04.2023 18:13:57, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.0.0, метка времени: 0x64400ea0
Имя сбойного модуля: nvoglv64.dll, версия: 31.0.15.2824, метка времени: 0x63c43af3
Код исключения: 0xc0000005
Смещение ошибки: 0x0000000000e52804
Идентификатор сбойного процесса: 0x3e64
Время запуска сбойного приложения: 0x01d973792250cf9f
Путь сбойного приложения: D:\Vintagestory\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_d1bd230cd08e7436\nvoglv64.dll
Идентификатор отчета: c0f148a8-fde3-474f-b255-bca3996f141c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 20.04.2023 18:13:57, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.AccessViolationException
   в OpenTK.Graphics.OpenGL.GL.EnableVertexAttribArray(Int32)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(Vintagestory.API.Client.MeshRef)
   в Vintagestory.Client.Gui.MainMenuRenderAPI.Render2DTexture(Int32, Single, Single, Single, Single, Single, Vintagestory.API.MathTools.Vec4f)
   в Vintagestory.Client.GuiCompositeMainMenuLeft.Render(Single, Int64, Boolean, Boolean)
   в Vintagestory.Client.GuiCompositeMainMenuLeft.RenderBg(Single, Boolean)
   в Vintagestory.Client.ScreenManager.Render(Single)
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double, Double)
   в Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   в Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   в Vintagestory.Client.ClientProgram.Main(System.String[])

 }
--------------
{ TimeGenerated = 10.03.2023 10:16:04, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.17.10.0, метка времени: 0x63bbdc3a
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.1387, метка времени: 0x0b9a844a
Код исключения: 0xc000041d
Смещение ошибки: 0x0000000000034f69
Идентификатор сбойного процесса: 0x262c
Время запуска сбойного приложения: 0x01d952fe4a1b5613
Путь сбойного приложения: D:\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: f3c42952-6822-4796-a9f5-027fb475c715
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }

**Comment by noelle-lavenza** [comment]
Duplicate of #2572, should hopefully be fixed in 1.18.3 (there was a deployment issue with 1.18.2 apparently, and the other issues were supposed to be fixed in that).
