### ISSUE TITLE
sleeping backwards

### ISSUE THREAD

**Issue by FertaliaSnow** [anegostudios/VintageStory-Issues#2738]
### Game Version

1.18.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

whenever I sleep in a bed, I sleep backwards

### How to reproduce

sleep

### Screenshots

![2023-05-13_15-04-59](https://github.com/anegostudios/VintageStory-Issues/assets/133478254/6ba174ef-2887-427d-ac24-dd52912442df)
![2023-05-13_15-05-07](https://github.com/anegostudios/VintageStory-Issues/assets/133478254/c6b1b374-b4a8-49f5-b9c0-17e232bc4593)
![2023-05-13_15-05-12](https://github.com/anegostudios/VintageStory-Issues/assets/133478254/b72a32ff-7130-4a2b-8d7e-3cd4d07d40f7)

**Comment by Th3Dilli** [comment]
thank you for the report, it will be fixed with the next release

**Comment by FertaliaSnow** [comment]
it is not resolved.
