### ISSUE TITLE
Vintagestory.desktop - run.sh

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2739]
### Game Version

1.18.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

None

### Description

Vintagestory.desktop chnged execution to `Exec=run.sh`, but it is not working on KDE desktop.
![obrázok](https://github.com/anegostudios/VintageStory-Issues/assets/47914240/379502fc-6095-4a7d-b8e5-989acd0a08e8)
- it says, application run.sh can not be found

You propably need to add the whole install path e.g. `/home/daret/ApplicationData/vintagestory/run.sh` - this means you need to adapt Vintagestory.desktop according to install path.

The whole idea is to add `export mesa_glthread=true`, but it freezes system even on X11 and should not be added as default option.

Please return `Exec=mono Vintagestory.exe`

### How to reproduce

Install end run on KDE System (e.g. KDE Neon).

(Not tested on other systems)

### Screenshots

See  description.

**Comment by daretmavi** [comment]
Eventually you van change exec to `Exec=bash run.sh`, but remove the `export mesa_glthread=true` from default run.
Maybe install script can ask if you want to activate it.

**Comment by Th3Dilli** [comment]
thank you for the feedback,
i tested it against Ubuntu there it was fine

i now tested with `Exec=bash run.sh` that you proposed and if that works across multiple distros that should be good


and i will add the check to the install script and if a user could benefit from it they get promted if they wanna enable it

about the x11/wayland

when i tested it on a lenovo laptop with integrated Intel graphics i had freezing when using wayland and `mesa_glthread=true` 

what graphics card do you have? and do you also get freezing on wayland with `mesa_glthread=true` if you have that avaialble to test?

**Comment by daretmavi** [comment]
I tried it with wayland and it was better. I could load the game, but it froze at game exit.

**Comment by daretmavi** [comment]
I haven't tested it extensive with wayland (only few minutes), but it looks good.
Performance with or without mesa_glthread was the same on wayland.

**Comment by Th3Dilli** [comment]
ok thank you,
then I will remove the check for x11 so if you may benefit from mesa_glthread you can enable it on install and if some users experience freezing they will have to remove mesa_glthread again from run.sh after that (will put a note on the install script when it gets enabled about removing it again when freezing happens) 
or reinstall without it
