### ISSUE TITLE
Coke can be made anywhere.

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2742]
### Game Version

v1.18.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

A coke furnace can be built by using any blocks. I noticed this when I put a coke oven door bellow a cementation furnace where the coal for buurning has to be placed. I fired the coal and closed the door. After a while I noticed the coal had turned into coke. I tried making coke in a 3x3 dirt enclosure. That also worked. It seems a coke oven cam be made out of any blocks as long as it has a coke oven door.

The guide implies that a coke oven has to be built out of fire clay bricks or refractory bricks.

### How to reproduce

Build a coke oven out of any solid blocks and fire it. After a while it will produce coke.

### Screenshots

![2023-05-13_21-17-46](https://github.com/anegostudios/VintageStory-Issues/assets/126715524/f0ad1ba4-7da6-45ef-8e8b-a55e16ef0db7)
![2023-05-13_21-17-56](https://github.com/anegostudios/VintageStory-Issues/assets/126715524/74eb6547-0996-4e57-9e46-d53a1947feef)
![2023-05-14_06-53-23](https://github.com/anegostudios/VintageStory-Issues/assets/126715524/19b20962-86d1-4f5e-9071-a318d63fa535)
![2023-05-15_16-46-07](https://github.com/anegostudios/VintageStory-Issues/assets/126715524/e5ccbb16-dfa7-4a5a-9f20-7ff8bf088dc3)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for the report

it will be fixed with the next release (most likely 1.19)
