### ISSUE TITLE
Duping Nightvision Masks

### ISSUE THREAD

**Issue by Arahvin** [anegostudios/VintageStory-Issues#2744]
### Game Version

v1.18.2

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

If you feed a temporal gear into a night vision mask it gets additional "charges" that allow you to split the stack and end up with multiple masks

The fuel on a mask doesn't seem to deplete either

### How to reproduce

Craft a Nightvision mask
Add a first temporal gear to fuel it
Add one or more gears to it
Split the stack it generates

### Logs

```Log```

**Comment by Th3Dilli** [comment]
will be fixed with next release, thank you for reporting
