### ISSUE TITLE
Terminus teleporter infinite uses

### ISSUE THREAD

**Issue by Arahvin** [anegostudios/VintageStory-Issues#2745]
### Game Version

v1.18.2

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

If you break and replace a terminus it always comes with one charge, removing the need for additonal temporal gears to recharge it

### How to reproduce

Make a terminus and place it
Use it, break it
Place it, repeat

### Logs

```Log```

**Comment by CookieBoy21** [comment]
I tested it in 1.19.8 and this bug is no more. Terminus teleporter is always empty after placing.
