### ISSUE TITLE
Chiselling a block breaks noise/soundproofing of weather effects (rain/wind storms) in valid rooms

### ISSUE THREAD

**Issue by okwelp** [anegostudios/VintageStory-Issues#2746]
### Game Version

1.18.3 stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It seems that chiselling any block stops the soundproofing of weather effects. This can make a valid room sound like it's in the wide open during a rainstorm. The soundproofing disappears when the block gets turned into a chisel-able type, even if the original material is preserved.

Not a massive issue but not great for immersion either! I suggest tying the soundproofing effect to the validity of the room as an alternative to the current system.

This is a reopening of issue #2720 which I had filled out incorrectly, apologies.

### How to reproduce

Please see this video for a demonstration: https://youtu.be/oIAxgCCevU8

Steps here:
1. Enter a Creative world
2. Create a 5x5 building with a solid door
3. Use /weather **setprecip** 1 to trigger a rainstorm
4. Enter the building. Note that the rainstorm is almost completely muted
5. Use a chisel to make any block chiselable. Note that the room now sounds like it is outside

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.20
