### ISSUE TITLE
"Current Rift Activity" status in the Environment menu doesn't update until relogging on a server

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2748]
### Game Version

1.18.1 and 1.18.3

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer/Singleplayer EDITED: See additional comments 

### Description

Playing on my community server for the past few weeks on version 1.18.1 and 1.18.3 has us all noticing that the Current Rift Activity level is out of sync at times or just doesn't update at all until you relog on to the server. There can be several rifts around the player and it still reads low like it has for the past few hours and after relogging it updates to High which then may stay there through a very peaceful long patch with no rifts at all. All while staying at my home base. Verified by others on the server as well.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/1531a979-fe8d-4d88-9a02-ecb474c6615b)

**Comment by JustForVS** [comment]
Hi!

Same issue in singleplayer.
Game startet with v. 1.18.1, issue realised with v. 1.18.3 and still there in 1.18.5

MOD Simple HUD Clock shows the correct status.
