### ISSUE TITLE
Running/Walking over Boulders at the edge stops player

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2749]
### Game Version

1.19 (and older)

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

When traversing boulders you have no issue stepping up on them if approached at the proper angle. If you approach at the edge of the boulder and try crossing as shown below you sill stop instead of stepping over it like the rest of the boulder.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/c7d87079-9aad-40b9-b125-80624f20008b)

**Comment by RedramVS** [comment]
I could not reproduce this issue, so I'm assuming it has been fixed at some point in the last 7 months.
