### ISSUE TITLE
Player takes (gravity) damage when sneaking on an edge of at least 4m

### ISSUE THREAD

**Issue by zkol** [anegostudios/VintageStory-Issues#275]
Player takes (gravity) damage when sneaking on an edge of at least 4m.

**Version**: 1.9.0-rc.4 (in multiplayer on chrometech.at)
**Reproduce:** Build a tower of at least 4 blocks tall and sneak at the edge, so that you would fall down if you released the sneak key.

**Observations:**
You start rapidly taking damage depending on the height of the tower.
 4m 0.5 hp
 5m 1.5 hp
 6m 2.1 hp
 7m 2.5 hp
 8m 4.5 hp
 9m 4.6 hp
10m 6.5 hp
If you die of this, you get the message that you "got pancaked" indicating that this was fall damage.

**Comment by tyronx** [comment]
Its the fear of falling that kills you! ;-)

Will look into it, thanks.

**Comment by copygirl** [comment]
Likely related to #274 as well.

**Comment by tyronx** [comment]
yup.

**Comment by Craluminum2413** [comment]
Is this still relevant?

**Comment by tyronx** [comment]
haven't heard any new reports, so probably can be closed
