### ISSUE TITLE
command maxchunkradius not working

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#2750]
### Game Version

v1.18.4

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The command /serverconfig maxchunkradius is not working since 1.18.4.
I get the message back: "Can't acces this feature, this server is in hosted mode".

...but in serverconfig is "HostedMode": false . Please fix.

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for reporting.  This is indeed a bug, revealed by fixing another bug.  There is no way for you to get this to work in 1.18.4, all  these settings in 1.18.4 will have the same issue:  `MaxChunkRadius, MaxClients, Upnp, EntityDebugMode, TickTime, RandomBlockTicksPerChunk'.

You can, of course, change these settings in the serverconfig file before starting the server.  I understand that you probably want to make adjustments while the server is running.  That will not be possible in 1.18.4 unless you have a third party mod which also provides a way to change config values (is there one?)

**Comment by radfast** [comment]
Fixed in 1.18.5, released in the next few minutes.  Thanks for reporting
