### ISSUE TITLE
Game Crashing after 1-3 Seconds of Play

### ISSUE THREAD

**Issue by BCrabgarden** [anegostudios/VintageStory-Issues#2753]
### Game Version

v1.18.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashing a few seconds after I load in. Confusing, haven't done anything out of the usual. Loading previously visited areas during winter. 

### Screenshots
![image](https://github.com/anegostudios/VintageStory-Issues/assets/134007127/86191239-bea3-4991-8979-f5e59d40cbbc)

### Logs

```Log```
18.5.2023 13:51:11 [Notification] Server logger started.
18.5.2023 13:51:11 [Notification] Game Version: v1.18.4 (Stable)
18.5.2023 13:51:11 [Event] Launching server...
18.5.2023 13:51:11 [Event] Server v1.18.4, network v1.18.6, api v1.7.0
18.5.2023 13:51:11 [Notification] Entering runphase Initialization
18.5.2023 13:51:11 [Event] Loading configuration...
18.5.2023 13:51:11 [Notification] Entering runphase Configuration
18.5.2023 13:51:12 [Notification] Loading savegame
18.5.2023 13:51:12 [Notification] Loaded existing save game data. Playstyle: surviveandbuild, Playstyle Lang code: preset-surviveandbuild, WorldType: preset-surviveandbuild
18.5.2023 13:51:12 [Notification] Savegame C:\Users\Benny\AppData\Roaming\VintagestoryData\Saves\liberal story.vcdbs loaded
18.5.2023 13:51:12 [Notification] World size = 1024000 256 1024000
18.5.2023 13:51:12 [Notification] Start discovering assets
18.5.2023 13:51:12 [Notification] Found 1 base assets in category blocktypes
18.5.2023 13:51:12 [Notification] Found 0 base assets in category itemtypes
18.5.2023 13:51:12 [Notification] Found 22 base assets in category lang
18.5.2023 13:51:12 [Notification] Found 0 base assets in category patches
18.5.2023 13:51:12 [Notification] Found 22 base assets in category config
18.5.2023 13:51:12 [Notification] Found 0 base assets in category worldproperties
18.5.2023 13:51:12 [Notification] Found 52 base assets in category sounds
18.5.2023 13:51:12 [Notification] Found 97 base assets in category shapes
18.5.2023 13:51:12 [Notification] Found 131 base assets in category textures
18.5.2023 13:51:12 [Notification] Found 0 base assets in category recipes
18.5.2023 13:51:12 [Notification] Found 0 base assets in category worldgen
18.5.2023 13:51:12 [Notification] Found 2 base assets in category entities
18.5.2023 13:51:12 [Notification] Found 327 base assets in total
18.5.2023 13:51:12 [Event] Building assets...
18.5.2023 13:51:12 [Notification] Entering runphase AssetsReady
18.5.2023 13:51:12 [Notification] Will search the following paths for mods:
18.5.2023 13:51:12 [Notification]     C:\Users\Benny\AppData\Roaming\Vintagestory\Mods
18.5.2023 13:51:12 [Notification]     C:\Users\Benny\AppData\Roaming\VintagestoryData\Mods
18.5.2023 13:51:12 [Notification] Found 3 mods (0 disabled)
18.5.2023 13:51:12 [Notification] Mods, sorted by dependency: game, creative, survival
18.5.2023 13:51:12 [Notification] Instantiated 101 mod systems from 3 enabled mods
18.5.2023 13:51:12 [Notification] External Origins in load order: modorigin@C:\Users\Benny\AppData\Roaming\Vintagestory\assets\creative\, modorigin@C:\Users\Benny\AppData\Roaming\Vintagestory\assets\survival\
18.5.2023 13:51:12 [Notification] Found 395 external assets in category blocktypes
18.5.2023 13:51:12 [Notification] Found 234 external assets in category itemtypes
18.5.2023 13:51:12 [Notification] Found 0 external assets in category lang
18.5.2023 13:51:12 [Notification] Found 9 external assets in category patches
18.5.2023 13:51:12 [Notification] Found 54 external assets in category config
18.5.2023 13:51:12 [Notification] Found 25 external assets in category worldproperties
18.5.2023 13:51:12 [Notification] Found 348 external assets in category sounds
18.5.2023 13:51:12 [Notification] Found 3179 external assets in category shapes
18.5.2023 13:51:12 [Notification] Found 5243 external assets in category textures
18.5.2023 13:51:12 [Notification] Found 356 external assets in category recipes
18.5.2023 13:51:12 [Notification] Found 422 external assets in category worldgen
18.5.2023 13:51:12 [Notification] Found 62 external assets in category entities
18.5.2023 13:51:12 [Notification] Found 0 external assets in category compatibility
18.5.2023 13:51:12 [Notification] Reloaded lang file with mod assets
18.5.2023 13:51:12 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
18.5.2023 13:51:12 [Notification] JsonPatch Loader: 2 patches total, successfully applied 2 patches, no issues
18.5.2023 13:51:13 [Notification] Loaded 3039 unique items
18.5.2023 13:51:14 [Notification] Loaded 9250 unique blocks
18.5.2023 13:51:14 [Notification] Loaded 386 unique entities
18.5.2023 13:51:14 [Notification] BlockLoader: Entities, Blocks and Items loaded
18.5.2023 13:51:14 [Event] Remapping blocks and items...
18.5.2023 13:51:15 [Event] 6 cooking recipes loaded
18.5.2023 13:51:15 [Event] 637 crafting recipes loaded from 229 files
18.5.2023 13:51:15 [Event] 9 metal alloys loaded
18.5.2023 13:51:15 [Event] 240 smithing recipes loaded
18.5.2023 13:51:15 [Event] 55 clay forming recipes loaded
18.5.2023 13:51:15 [Event] 36 knapping recipes loaded
18.5.2023 13:51:15 [Event] 140 barrel recipes loaded
18.5.2023 13:51:15 [Notification] Entering runphase AssetsFinalize
18.5.2023 13:51:15 [Event] Server assets loaded, parsed, registered and finalized
18.5.2023 13:51:15 [Event] Initialising systems...
18.5.2023 13:51:15 [Notification] Entering runphase LoadGamePre
18.5.2023 13:51:15 [Notification] Reloaded 19 weather patterns, 5 wind patterns and 5 weather events
18.5.2023 13:51:15 [Notification] Started 88 systems on Server:
18.5.2023 13:51:15 [Notification]     Mod 'VSEssentials.dll' (game):
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.Core
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.EntityPartitioning
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ErrorReporter
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
18.5.2023 13:51:15 [Notification]         Vintagestory.Essentials.PathfindSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.Essentials.PathFindDebug
18.5.2023 13:51:15 [Notification]         Vintagestory.Essentials.PathfindingAsync
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.JsonExport
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemEmotes
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.LeafBlockDecay
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.POIRegistry
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.RoomRegistry
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.WeatherSystemServer
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.WorldMapManager
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.LoadColorMaps
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ClothManager
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GridRecipeLoader
18.5.2023 13:51:15 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenSnowLayer
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenTerra
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenHotSprings
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.NpcControl
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenCreatures
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenMaps
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.WgenCommands
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.DebugSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.UpgradeTasks
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemCorpseReturnTeleporter
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ClutterBookshelfUtil
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemResoArchiveCommands
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.Core
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemGliding
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.MyceliumSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemAuction
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.DialogueSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemTutorial
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.CharacterSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.FruitingSystem
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemRifts
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModTemperature
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.SystemTemporalStability
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModsystemButterflySpawnCondsExtra
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModJournal
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModLootRandomizer
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSleeping
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.TeleporterManager
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenDungeons
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenDeposits
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.GenStoryStructures
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenStructures
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenCaves
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenBlockLayers
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenPonds
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenVegetationAndPatches
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenRivulets
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenLightSurvival
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.RecipeLoader
18.5.2023 13:51:15 [Notification]         Vintagestory.GameContent.TraderOutfits
18.5.2023 13:51:15 [Notification]     Mod 'VSCreativeMod.dll' (creative):
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.Core
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
18.5.2023 13:51:15 [Notification]         Vintagestory.ServerMods.GenLightCreative
18.5.2023 13:51:16 [Notification] Sending server identification with remap False.  Server control privilege is True
18.5.2023 13:51:17 [Notification] Server map set
18.5.2023 13:51:17 [Notification] Entering runphase GameReady
18.5.2023 13:51:17 [Event] Starting world generators...
18.5.2023 13:51:17 [Notification] Entering runphase WorldReady
18.5.2023 13:51:18 [Notification] Reloaded 35 tree generators
18.5.2023 13:51:18 [Event] Loading 7x7x8 spawn chunks...
18.5.2023 13:51:18 [Event] 0% (49 in queue)
18.5.2023 13:51:19 [Event] Begin game ticking...
18.5.2023 13:51:19 [Notification] Entering runphase RunGame
18.5.2023 13:51:19 [Notification] Successfully loaded 66 waypoints
18.5.2023 13:51:19 [Notification] Starting server threads
18.5.2023 13:51:19 [Event] Singleplayer Server now running!
18.5.2023 13:51:19 [Notification] All clients disconnected, pausing game calendar.
18.5.2023 13:51:19 [Notification] A Client attempts connecting via Dummy connection, assigning client id 1
18.5.2023 13:51:19 [Notification] Client uid Wbsx1XUHtXDm3h/VI5p6ylY2 attempting identification. Name: BCrabgarden
18.5.2023 13:51:19 [Notification] Upped server view distance because player is locally connected
18.5.2023 13:51:19 [Notification] Delayed join, need to load one spawn chunk first.
18.5.2023 13:51:19 [Notification] Placing player at 511539.122062305 110 512500.517004688
18.5.2023 13:51:21 [Event] BCrabgarden 127.0.0.1 joins.
18.5.2023 13:51:22 [Notification] A client reconnected, resuming game calendar.
18.5.2023 13:51:35 [Notification] Last player disconnected, compacting large object heap...
18.5.2023 13:51:37 [Event] Player BCrabgarden left.
18.5.2023 13:51:37 [Warning] Server overloaded. A tick took 1341ms to complete.
18.5.2023 13:51:37 [Notification] All clients disconnected, pausing game calendar.
18.5.2023 13:51:37 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exit request by client
18.5.2023 13:51:37 [Notification] Server ticking has been suspended
18.5.2023 13:51:37 [Notification] Entering runphase Shutdown
18.5.2023 13:51:37 [Notification] Defragmented listener lists
18.5.2023 13:51:37 [Event] Mods and systems notified, now saving everything...
18.5.2023 13:51:37 [Event] Saved player world data...
18.5.2023 13:51:37 [Event] Saved map regions...
18.5.2023 13:51:37 [Event] Saved map chunks...
18.5.2023 13:51:37 [Event] Saved loaded chunks...
18.5.2023 13:51:37 [Event] Saved generating chunks...
18.5.2023 13:51:37 [Event] Saved savegamedata...2
18.5.2023 13:51:37 [Event] World saved! Saved 90 chunks, 2 mapchunks, 25 mapregions.
18.5.2023 13:51:37 [Event] Shutting down 5 server threads... 
18.5.2023 13:51:37 [Event] Killed console thread
18.5.2023 13:51:38 [Event] All threads gracefully shut down
18.5.2023 13:51:38 [Event] Doing last tick...
18.5.2023 13:51:38 [Event] Stopped the server!

**Comment by radfast** [comment]
This is very likely the Berry Bush crash in 1.18.4, see #2751 

Release 1.18.5, out in a few minutes, fixes that.   If you still have this issue in 1.18.5, please re-open this and please post up your `client-main` log file
