### ISSUE TITLE
Tree Leaves Floating

### ISSUE THREAD

**Issue by JustinLTu** [anegostudios/VintageStory-Issues#2754]
### Game Version

1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Whenever someone chops down particularly tall trees, many of the top leaves remain behind. So far on the multiplayer server I play on, other players and I have seen it happen on Pine trees. The bunches of leaves left behind are a mix of branchy and normal leaves.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/13356915/317ef1c5-813c-4848-81c4-1d20b16221c7)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you for reporting.  This is fixed in next release, at least in 95% of cases ... tree felling will occasionally leave just a few leaves behind, but they decay over time.
