### ISSUE TITLE
Remove burning firewood from clay oven 

### ISSUE THREAD

**Issue by JustForVS** [anegostudios/VintageStory-Issues#2756]
Game Version
v.1.18.5

Platform
Windows

Modded
Modded

SP/MP
Singleplayer

Description

You can remove burning firewood from a clay oven. The burning sound will continue and the temperature stops to increase.
After the sound stops, you can put in an ignite the firewood again to further increase the temperature of the oven.

Expection: burning firewood should not be removable

**Comment by CookieBoy21** [comment]
I tested it in 1.19.7 and it's look like they fixed it. I couldn't remove burning firewood from clay oven.
