### ISSUE TITLE
Dough in handbook states it bakes into part-baked bread in campfire

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2760]
### Game Version

1.18.5 and older

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

While the text describes that dough when cooked in a campfire will make charred bread, the image shows that it will make "part-baked" bread.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/252010cb-8be5-4474-a8ec-8e834a9afc6c)
In this image, I am hovering my mouse pointer over the bread shown under "(in firepit)"

**Comment by Craluminum2413** [comment]
It is showing info both for clay oven and firepit

**Comment by VallenFrostweaver** [comment]
But it's stating "Bakes into (in firepit)" on the menu (not the hover info) with the icon and info of a part-baked loaf.

**Comment by radfast** [comment]
Thanks for the report, fixed next release
