### ISSUE TITLE
ClientMain.tryAccess throws NullReferenceException when client event added to OnTestBlockAccess 

### ISSUE THREAD

**Issue by kenigvovan** [anegostudios/VintageStory-Issues#2761]
### Game Version

1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

If you add new handler to client OnTestBlockAccess  event and return something other than EnumWorldAccessResponse.Granted 
you'll get NullReferenceException, probably missing "out" for "claimant" for OnTestBlockAccess

### How to reproduce

 public override void StartClientSide(ICoreClientAPI api)
        {
            base.StartClientSide(api);
            api.Event.OnTestBlockAccess += TestBlockAccessDelegate_1;
        }
public EnumWorldAccessResponse TestBlockAccessDelegate_1(IPlayer player, BlockSelection blockSel, EnumBlockAccessFlags accessType, string claimant, EnumWorldAccessResponse response)
        {
             return EnumWorldAccessResponse.DeniedByMod;
        }
----------------------------------------------

### Logs

```Game Version: v1.18.5 (Stable)
20.05.2023 12:26:52: Critical error occurred
Loaded Mods: claims@0.2.14, game@1.18.5, creative@1.18.5, redirectlogs@1.0.0, survival@1.18.5
System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v Vintagestory.Client.NoObf.ClientMain.tryAccess(BlockSelection blockSel, EnumBlockAccessFlags flag) v VintagestoryLib\Client\ClientMain.cs:řádek 1607
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) v VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:řádek 865
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) v VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:řádek 535
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) v VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:řádek 86
   v Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) v VintagestoryLib\Client\Util\ClientEventManager.cs:řádek 191
   v Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) v VintagestoryLib\Client\ClientMain.cs:řádek 787
   v Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) v VintagestoryLib\Client\ClientMain.cs:řádek 979
   v Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) v VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:řádek 241
   v Vintagestory.Client.ScreenManager.Render(Single dt) v VintagestoryLib\Client\ScreenManager.cs:řádek 722
   v Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) v VintagestoryLib\Client\ScreenManager.cs:řádek 625
   v Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) v VintagestoryLib\Client\ClientPlatform\GameWindow.cs:řádek 119
   v System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   v OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 476
   v OpenTK.GameWindow.DispatchRenderFrame() v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 452
   v OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 375
   v Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   v Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) v VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:řádek 102
   v Vintagestory.Client.ClientProgram.Main(String[] rawArgs)```

**Comment by radfast** [comment]
Thanks for reporting.  I think we cannot change the API code (it needs `ref string claimant` as the parameter) at this stage in the release cycle, because that will change the delegate signature which will break any mods using this event.  But we can make that change in 1.19 and for now we can do a null check to prevent the crash.

**Comment by DArkHekRoMaNT** [comment]
@radfast Maybe leave it open in the in-progress status, so as not to forget to return in 1.19?

**Comment by radfast** [comment]
@DArkHekRoMaNT  thanks I thought about that, but instead I added that code change to my own to-do list for 1.19; the issue is sufficiently resolved for now: it won't crash; claimant is only relevant if the mod's response to the event is `EnumWorldAccessResponse.Claimed`; and in general I don't think we want to use the public Github issues list as a to-do list for the code for a future version, we have other internal systems for that.
