### ISSUE TITLE
Clay oven rotates on completion of creation & chimney misplaced

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2763]
### Game Version

1.18.5 and older

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Two issues here (first is very very minor):
1. When clay-forming the clay oven, the chimney is one voxel closer to the front opening than it should be when compared to the finished clay oven. (see first image)
2. Once you finish the clay oven it instantly rotates to another facing. (compare first image to second image) 

![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/369aa389-0aff-4e54-ad73-efafdaa68fe7)
First image (one layer away from completion. Open facing is towards the player during this process. Chimney is one voxel too close to the player comparing to the finished model. Finished model is on the right.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/3b5461e8-9706-4fe4-97a3-bf865593e34d)
Second image (continued from first image crafting to complete the clay oven). Open facing instantly rotated to the left from player perspective on completion.

**Comment by RedramVS** [comment]
I've modified the chimney location, and also shortened it half a voxel so that it can meet a chiseled chimney above cleanly.  The rotation after completion is not a bug, all clay molds do this.  It's just more noticeable for the oven.
