### ISSUE TITLE
Uncrafting an Anvil with chisel Looks like it can be done with lower tier chisels & no mention of durability requirement of chisel

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2764]
### Game Version

1.18.5 and older

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When "uncrafting" an anvil by placing an anvil in a crafting grid with a chisel it will convert it to 8 ingots of like anvil material. The problem here is that the handbook rotates through all chisels including lower tier chisels like copper to break down a steel anvil (as an example). This DOES cost the same tier metal or above and not any chisel and can be misleading (see image).

Additional issue is that the crafting recipe to "uncraft" an anvil does not mention the requirement of an entire brand new chisel and a damaged chisel will not work. Having a note or durability mention (similar to the new Quantity displayed in recipes) of the chisel requirement could alleviate this.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/4ad3a022-40f4-429b-92ec-dcc5dbe99340)

**Comment by DArkHekRoMaNT** [comment]
It would be nice to add a hint if the tools durability is not enough. In fact, this is set by any chisel with suitable durability. Or exclude unsuitable tools from the recipe automatically.

**Comment by RedramVS** [comment]
Recipe has been changed so that inappropriately low tier chisels will no longer be shown in the handbook.  Eventually we hope to be able to display the durability cost in the recipe, but that will be for a future update.
