### ISSUE TITLE
error when taking samples with prospecting peak 1.18.5

### ISSUE THREAD

**Issue by artemax44** [anegostudios/VintageStory-Issues#2767]
### Game Version

v.1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

when I prospect with the spike in non-node mode, it doesn't give me the reading of the percentages. Instead of giving me the percentages, I get a text that says the following:

propick-reading-title
propick-reading
propick-reading

I must say that I have many mods. But with all the mods that I have, I tried version 1.18.3 and I don't have any problem, but in 1.18.5 yes

I also tried to remove all the mods and leave the game vanilla and it doesn't work either.

And finally, I tried uninstalling the game, and going back to do a clean installation of the game and nothing at all.
With mods or without mods, in this latest version the prospecting peak does not work correctly for me.
But if it works fine for me in game version 1.18.3
It happens to me in both singleplayer and multiplayer

### How to reproduce

simply taking the survey peak and performing the task of taking the three samples.

### Screenshots

https://gyazo.com/70a5d4bf1a570c775ecdca825933c079

### Logs

```Log```

**Comment by artemax44** [comment]
It seems to me that the ruling is due to the translation into Spanish from Spain. I had the idea of ​​putting my game in English and the problem is solved, but when I put it back in Spanish from Spain the error appears again. The translation from Spanish to Spain in 1.18.3 was correct and without problems. I don't know who or who translate it but could you look to solve that error? Thank you

**Comment by DArkHekRoMaNT** [comment]
Doesn't it work in singleplayer too? I don't see any problem with the Spanish translation of these strings on crowdin

**Comment by DArkHekRoMaNT** [comment]
These strings are not present at all in the es-es.json language files, strange. In this case, the English text should have been used

**Comment by radfast** [comment]
Thanks for reporting, in next release it will be in English if not in the player's own language
