### ISSUE TITLE
land claim server error

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#2768]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

if a claim ist not loaded and players enter e.g. the command land claim grant xxx all, there are server errors:

[1.txt](https://github.com/anegostudios/VintageStory-Issues/files/11524557/1.txt)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for reporting.  Fixed in next release
