### ISSUE TITLE
Applying potash to tilled soil upgrades it to the next soil tier

### ISSUE THREAD

**Issue by Guimoute** [anegostudios/VintageStory-Issues#2769]
### Game Version

1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Hello,

When you apply bonemeal and compost to your soil, it gets a stats boost and speckles of dust on top of it but the underlying soil does not change. However when you apply potash, the soil upgrades after a few seconds. This should not happen. The expected behavior is for this soil block to get only a stats boost, not a soil tier boost.

This also means you can make terra preta at home and removes one reason to go find it in the wild.
 

### How to reproduce

Apply potash to tilled soil. 

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/51537797/58d1a816-b32a-46e2-b7e0-0f2793871d92

**Comment by VallenFrostweaver** [comment]
You are simply making High Fertility soil that will later on have a higher K value of up to 15% more (Medim soil 50% for all values). Terra preta starts at 80% for all values and once Potash is added it can have it's K value increased to 95% permanently. This is not a bug as far as I can tell. At best, the 15% increase on the Potash should read "up to" 15% since when adding it to anything not terra preta will be close to but not 15% bonus K value.

**Comment by radfast** [comment]
For the reasons mentioned by @VallenFrostweaver, this is intended behaviour.  Potash can permanently increase tilled soil by one tier, depending on the soil's previous level.  The "High Fertility" farmland seen in your video is not Terra Preta, it is one tier below Terra Preta.

**Comment by Guimoute** [comment]
@radfast I didn't say the farmland seen in the video was terra preta. You can improve low fertility soil to medium, medium to high, and high to terra preta.

**Comment by Guimoute** [comment]
I'm just surprised that the ability to skip two game mechanics (composting and terra preta hunt) is intended.

**Comment by VallenFrostweaver** [comment]
It does look like a high fertility as far as I can see. In either of your videos you don't place down Terra preta which is almost black. I can understand the confusion though.

**Comment by Guimoute** [comment]
@VallenFrostweaver Well yes, that is the problem. I don't place down terra preta yet I get "terra preta" in the infobox at the end of the second video.

I am surprised nobody reported "my terra preta is stuck at 65/65/80% N/P/K despite having been left fallow for years" because of the naming confusion.

**Comment by Guimoute** [comment]
As a dirty workaround, I'll modify `potash.json/"attributes/fertilizerProps/permaboost/k"` from 15 to 14.999, since Craluminum told me the block type/texture used by a farmland block is given by comparing its max nutrients to the `Fertilities` dictionary.

Some people do believe potash is the way to upgrade high fertility soil in terra preta: https://old.reddit.com/r/VintageStory/comments/14o0aqp/how_to_compost/jqa889v/

**Comment by Guimoute** [comment]
More people thinking potash upgrades soil types: https://www.vintagestory.at/forums/topic/11103-is-there-a-point-to-high-fertility-soil/?do=findComment&comment=48113
