### ISSUE TITLE
Opening survival handbook should pause the game

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#277]

**Comment by copygirl** [comment]
Additionally, I don't believe the game is paused while you're still in the character creation / customization screen that pops up in the beginning. That might be nice.

**Comment by Craluminum2413** [comment]
If someone looking for that, you can look at this mod https://mods.vintagestory.at/show/mod/696

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
