### ISSUE TITLE
saturation afk

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#2771]
### Game Version

v1.18.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I am aware that I am not making friends with this now:

The game seems to be built in such a way that you consume saturation when you do something. That's okay in itself. However, if you stand around afk, it takes forever to starve. This should possibly be considered and adjusted.

### Logs

```Log```

**Comment by radfast** [comment]
Please make suggestions on the Discord #suggestions channel, not in the issues list.   This issues list is for current game features not working as intended, and similar.
