### ISSUE TITLE
Players can retrieve coordinates in wilderness survival with commands

### ISSUE THREAD

**Issue by teknik1** [anegostudios/VintageStory-Issues#2784]
### Game Version

1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description
With /worldconfig allowCoordinateHud [true|false] set to false,
Players can retrieve coordinates in wilderness survival with commands : 
.cp posi
.cp aposi
.cp apos

### How to reproduce

Just enter the commands ans share the position with others players.

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you

it was disabled with allowMap == false but that does not make much sense so now it uses allowCoordinateHud

will be fixed with the next release (most likely 1.19)
