### ISSUE TITLE
lost HP back to 100% after next log in

### ISSUE THREAD

**Issue by JustForVS** [anegostudios/VintageStory-Issues#2787]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When leaving the game with less then 100% HP, HP are back at 100% after next log in (see #2250).

### How to reproduce

Get some damage.
Log out with less than 100% HP and log in again
HP are back at 100%

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #2250
