### ISSUE TITLE
Pressing esc while screen goes dark (sleeping) renders game unaccessible.

### ISSUE THREAD

**Issue by verticaljelly** [anegostudios/VintageStory-Issues#279]
When: 
Right clicking on a bed and soon after or right then hitting escape (much like the mechanic in minecraft where escape cancels the sleep)

What happens:
Game possibly renders the game is paused with the buttons to go back or leave the game, which is not rendered since the screen goes black through some mechanic that stops rendering the menu too. 

Suggestion on how to fix:

Render the menus on an overlay in another rendering pipe thus making it possible for you to keep doing whatever in the main scene while still able to show the menus.

Related issues to this one:

The minimap shows when opening and then swapping between many chests leaving one or more of them below the rendered minimap . Having the UI respect an UI only rendering (2D) may in fact allow for window collisions including with the minimap.

**Comment by tyronx** [comment]
Thanks, fixed for v1.9.4. It was actually only due to a failing z-test that the GUI didn't render. Furthermore being inside the bed now also shows a hint on how to exit.
