### ISSUE TITLE
Crash when tree chopping is finished

### ISSUE THREAD

**Issue by cyberjasse** [anegostudios/VintageStory-Issues#2792]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

This is not a systematic bug. The game crashed when I just finished to chop a pine tree. When the crash occured, the sound of a falling tree triggered but the tree did not disappear. A pop up windows apparead telling that the client has crashed and a bug report is reported in client-main.txt . I could continue playing but the tree still there.
I put the content of client-main.txt in log section.

The mod that I installed are prospectorInfo, metal recovery and workbench expansion. The crash does not seem linked to them. Also it is the first time I encountered a crash.

### Logs

1.6.2023 20:46:12 [Notification] Client logger started.
1.6.2023 20:46:12 [Notification] Game Version: v1.18.5 (Stable)
1.6.2023 20:46:12 [Notification] Screens:
1.6.2023 20:46:12 [Notification] 0: {X=0,Y=0,Width=1920,Height=1080}, \\.\DISPLAY1 (primary)
1.6.2023 20:46:13 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
1.6.2023 20:46:13 [Notification] CPU Cores: 12
1.6.2023 20:46:13 [Notification] Available RAM: 0 MB
1.6.2023 20:46:13 [Notification] Graphics Card Vendor: NVIDIA Corporation
1.6.2023 20:46:13 [Notification] Graphics Card Version: 3.3.0 NVIDIA 532.03
1.6.2023 20:46:13 [Notification] Graphics Card Renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
1.6.2023 20:46:13 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
1.6.2023 20:46:13 [Notification] GL.MaxVertexUniformComponents: 4096
1.6.2023 20:46:13 [Notification] GL.MaxUniformBlockSize: 65536
1.6.2023 20:46:13 [Notification] Cairo Graphics Version: 1.17.3
1.6.2023 20:46:13 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
1.6.2023 20:46:13 [Notification] C# Framework: .net Framework 4.0.30319.42000
1.6.2023 20:46:13 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
1.6.2023 20:46:14 [Notification] Start discovering assets
1.6.2023 20:46:14 [Notification] Found 22 base assets in category lang
1.6.2023 20:46:14 [Notification] Found 0 base assets in category patches
1.6.2023 20:46:14 [Notification] Found 22 base assets in category config
1.6.2023 20:46:14 [Notification] Found 0 base assets in category worldproperties
1.6.2023 20:46:14 [Notification] Found 46 base assets in category sounds
1.6.2023 20:46:14 [Notification] Found 97 base assets in category shapes
1.6.2023 20:46:14 [Notification] Found 80 base assets in category shaders
1.6.2023 20:46:14 [Notification] Found 16 base assets in category shaderincludes
1.6.2023 20:46:14 [Notification] Found 131 base assets in category textures
1.6.2023 20:46:14 [Notification] Found 4 base assets in category music
1.6.2023 20:46:14 [Notification] Found 0 base assets in category dialog
1.6.2023 20:46:14 [Notification] Found 418 base assets in total
1.6.2023 20:46:14 [Notification] Loading sounds
1.6.2023 20:46:14 [Notification] Sounds loaded
1.6.2023 20:46:14 [Notification] (Re-)loaded frame buffers
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass .
1.6.2023 20:46:14 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
1.6.2023 20:46:14 [Notification] (Re-)loaded frame buffers
1.6.2023 20:46:14 [Notification] Begin loading shaders
1.6.2023 20:46:14 [Notification] Load shaders now
1.6.2023 20:46:14 [Notification] Loading shaders...
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass standard.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass particlescube.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass particlesquad.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass sky.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass nightsky.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass woittest.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass helditem.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass decals.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass final.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass gui.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass blur.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass findbright.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass godrays.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass autocamera.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass wireframe.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass entityanimated.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass luma.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass blit.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass texture2texture.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass celestialobject.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass colorgrade.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass guigear.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass ssao.
1.6.2023 20:46:14 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
1.6.2023 20:46:14 [Notification] Cached session key is valid, validating with server
1.6.2023 20:46:15 [Notification] Server validation response: Good
1.6.2023 20:46:15 [Notification] Will search the following paths for mods:
1.6.2023 20:46:15 [Notification]     C:\Users\J.Bury\AppData\Roaming\Vintagestory\Mods
1.6.2023 20:46:15 [Notification]     C:\Users\J.Bury\AppData\Roaming\VintagestoryData\Mods
1.6.2023 20:46:30 [Notification] Initialized GUI Manager
1.6.2023 20:46:30 [Notification] Initialized Server Connection
1.6.2023 20:46:30 [Notification] Server args parsed
1.6.2023 20:46:30 [Notification] Server main instantiated
1.6.2023 20:46:39 [Notification] Processed server identification
1.6.2023 20:46:39 [Notification] Map initialized
1.6.2023 20:46:39 [Notification] Received server assets
1.6.2023 20:46:39 [Notification] Loading and pre-starting client side mods...
1.6.2023 20:46:39 [Notification] Will search the following paths for mods:
1.6.2023 20:46:39 [Notification]     C:\Users\J.Bury\AppData\Roaming\Vintagestory\Mods
1.6.2023 20:46:39 [Notification]     C:\Users\J.Bury\AppData\Roaming\VintagestoryData\Mods
1.6.2023 20:46:39 [Notification] Found 7 mods (1 disabled)
1.6.2023 20:46:39 [Notification] Mods, sorted by dependency: game, prospectorinfo, creative, survival, workbenchexpansion, metalrecovery
1.6.2023 20:46:39 [Notification] Instantiated 104 mod systems from 6 enabled mods
1.6.2023 20:46:39 [Notification] Done loading and pre-starting client side mods.
1.6.2023 20:46:39 [Event] Workbench Expansion Mod v1.6.2 loading
1.6.2023 20:46:39 [Notification] External Origins in load order: modorigin@C:\Users\J.Bury\AppData\Roaming\Vintagestory\assets\creative\, modorigin@C:\Users\J.Bury\AppData\Roaming\Vintagestory\assets\survival\, mod@workbench-expansion-1.6.2.zip, mod@AnvilMetalRecovery_V0.1.19-pre.1_Debug.zip
1.6.2023 20:46:39 [Notification] Found 8 external assets in category lang
1.6.2023 20:46:39 [Notification] Found 9 external assets in category patches
1.6.2023 20:46:39 [Notification] Found 55 external assets in category config
1.6.2023 20:46:39 [Notification] Found 25 external assets in category worldproperties
1.6.2023 20:46:39 [Notification] Found 350 external assets in category sounds
1.6.2023 20:46:40 [Notification] Found 3188 external assets in category shapes
1.6.2023 20:46:40 [Notification] Found 13 external assets in category shaders
1.6.2023 20:46:40 [Notification] Found 0 external assets in category shaderincludes
1.6.2023 20:46:40 [Notification] Found 5249 external assets in category textures
1.6.2023 20:46:40 [Notification] Found 63 external assets in category music
1.6.2023 20:46:40 [Notification] Found 18 external assets in category dialog
1.6.2023 20:46:40 [Notification] Found 0 external assets in category compatibility
1.6.2023 20:46:40 [Notification] Reloaded lang file now with mod assets
1.6.2023 20:46:40 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
1.6.2023 20:46:40 [Notification] JsonPatch Loader: 14 mises à jour au total, 6 mises à jour appliquées avec succès, conditions non remplies pour 17 mises à jour, aucune erreur
1.6.2023 20:46:40 [Notification] Received 3065 item types from server
1.6.2023 20:46:40 [Notification] Loaded 9300 block types from server
1.6.2023 20:46:40 [Notification] Reloaded sounds, now with mod assets
1.6.2023 20:46:41 [Notification] Composed 1 4096x4096 entities texture atlases from 384 textures
1.6.2023 20:46:43 [Notification] Collected 1810 shapes to tesselate.
1.6.2023 20:46:44 [Notification] Composed 1 4096x4096 items texture atlases from 1593 textures
1.6.2023 20:46:45 [Notification] Server launched
1.6.2023 20:46:46 [Notification] Composed 1 4096x4096 blocks texture atlases from 4316 textures
1.6.2023 20:46:47 [Notification] Server assets loaded
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass lines.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass aurora.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass rift.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass machinegear.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
1.6.2023 20:46:47 [Notification] Started 67 systems on Client:
1.6.2023 20:46:47 [Notification]     Mod 'VSEssentials.dll' (game):
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.Core
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.EntityPartitioning
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ErrorReporter
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemItemRendererOptimizer
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.POIRegistry
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.RoomRegistry
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.WeatherSystemClient
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.WorldMapManager
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.LoadColorMaps
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ClothManager
1.6.2023 20:46:47 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.Client.NoObf.ModSystemBossHealthBars
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.GenMaps
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.DebugSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.UpgradeTasks
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemNightVision
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemMeasuringRope
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.Core
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemBoatingSound
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemGliding
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.MyceliumSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemAuction
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.DialogueSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemHandbook
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemTutorial
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.CharacterSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.FruitingSystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemRifts
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModTemperature
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.SystemTemporalStability
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.MealMeshCache
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.MicroBlockModelCache
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModJournal
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModLootRandomizer
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSleeping
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.TeleporterManager
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
1.6.2023 20:46:47 [Notification]         Vintagestory.GameContent.TraderOutfits
1.6.2023 20:46:47 [Notification]     Mod 'VSCreativeMod.dll' (creative):
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.Core
1.6.2023 20:46:47 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
1.6.2023 20:46:47 [Notification]     Mod 'ProspectorInfo-4.3.0.zip' (prospectorinfo):
1.6.2023 20:46:47 [Notification]         ProspectorInfo.ProspectorInfoModSystem
1.6.2023 20:46:47 [Notification]     Mod 'workbench-expansion-1.6.2.zip' (workbenchexpansion):
1.6.2023 20:46:47 [Notification]         workbenchexpansion.src.WorkbenchExpansionMod
1.6.2023 20:46:47 [Notification]     Mod 'AnvilMetalRecovery_V0.1.19-pre.1_Debug.zip' (metalrecovery):
1.6.2023 20:46:47 [Notification]         AnvilMetalRecovery.MetalRecoverySystem
1.6.2023 20:46:47 [Notification] Loading shaders...
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass standard.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass particlescube.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass particlesquad.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass sky.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass nightsky.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass woittest.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass helditem.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass decals.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass final.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass gui.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass blur.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass findbright.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass godrays.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass autocamera.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass wireframe.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass entityanimated.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass luma.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass blit.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass texture2texture.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass celestialobject.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass colorgrade.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass guigear.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass ssao.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass lines.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass aurora.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass rift.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass machinegear.
1.6.2023 20:46:47 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
1.6.2023 20:46:47 [Notification] Reloaded shaders now with mod assets
1.6.2023 20:46:48 [Notification] Blocks tesselated
1.6.2023 20:46:48 [Notification] Received level init
1.6.2023 20:46:48 [Notification] Loaded Shaderprogramm for render pass instanced.
1.6.2023 20:46:48 [Notification] Loading world map cache db...
1.6.2023 20:46:48 [Notification] Initialized Music Engine
1.6.2023 20:46:48 [Error] Could not load sound The specified sound format is not supported.
1.6.2023 20:46:48 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
1.6.2023 20:46:49 [Notification] Received level finalize
1.6.2023 20:46:49 [Notification] Loaded Shaderprogramm for render pass clouds.
1.6.2023 20:46:50 [Warning] ===============================================================
1.6.2023 20:46:50 [Warning] (x_x) Captured 1 issues during startup:
1.6.2023 20:46:50 [Error] Could not load sound The specified sound format is not supported.
1.6.2023 20:46:50 [Warning] ===============================================================
1.6.2023 20:47:03 [Notification] Finished fully loading sounds (async)
1.6.2023 20:47:15 [Warning] OpenAL Error during construction before of sound game:sounds/creature/drifter-aggro2.ogg: InvalidValue
1.6.2023 20:47:30 [Notification] Wow, client daytime drifted off significantly from server daytime (22,3 mins)
1.6.2023 20:49:03 [Notification] Track music/setting-sun.ogg now started
1.6.2023 20:49:25 [Notification] Client pause state is now on
1.6.2023 20:49:26 [Notification] Client pause state is now off
1.6.2023 20:49:56 [Warning] OpenAL Error during SetPitch of sound game:sounds/block/quern.ogg: InvalidValue
1.6.2023 20:51:11 [Warning] OpenAL Error during SetPitch of sound game:sounds/block/quern.ogg: InvalidValue
1.6.2023 20:52:56 [Warning] Audio File not found: game:block/planks.ogg
1.6.2023 20:52:56 [Warning] Audio File not found: game:block/planks.ogg
1.6.2023 20:58:18 [Warning] OpenAL Error during construction before of sound game:sounds/block/door.ogg: InvalidValue
1.6.2023 20:58:18 [Warning] OpenAL Error during SetPitch of sound game:sounds/block/quern.ogg: InvalidValue
1.6.2023 20:59:32 [Warning] OpenAL Error during SetPitch of sound game:sounds/block/quern.ogg: InvalidValue
1.6.2023 21:00:56 [Notification] Track music/groove.ogg now started
1.6.2023 21:11:53 [Notification] Track music/building.ogg now started
1.6.2023 21:14:22 [Error] The dialog GuiDialogBlockEntityRecipeSelector requested focus, but was not added yet. Missing call to api.Gui.RegisterDialog()
1.6.2023 21:20:46 [Error] The dialog GuiDialogBlockEntityRecipeSelector requested focus, but was not added yet. Missing call to api.Gui.RegisterDialog()
1.6.2023 21:31:04 [Error] The dialog GuiDialogBlockEntityRecipeSelector requested focus, but was not added yet. Missing call to api.Gui.RegisterDialog()
1.6.2023 21:33:53 [Notification] Track music/midnight.ogg now started
1.6.2023 21:36:15 [Warning] OpenAL Error during SetPitch of sound game:sounds/block/quern.ogg: InvalidValue
1.6.2023 21:43:33 [Notification] Client pause state is now on
1.6.2023 21:44:01 [Notification] Client pause state is now off
1.6.2023 21:44:04 [Notification] Track music/night-to-day.ogg now started
1.6.2023 21:44:25 [Notification] Client pause state is now on
1.6.2023 21:44:40 [Notification] Client pause state is now off
1.6.2023 21:44:40 [Notification] Client pause state is now on
1.6.2023 21:46:46 [Notification] Client pause state is now off
1.6.2023 21:59:15 [Notification] Track music/to-dawn.ogg now started
1.6.2023 22:10:22 [Notification] Track music/winter.ogg now started
1.6.2023 22:10:29 [Warning] OpenAL Error during disposestop of sound game:sounds/walk/wood2.ogg: InvalidValue
1.6.2023 22:12:20 [Fatal] Caught unhandled exception in thread 'tesselateterrain'. Exiting game.
1.6.2023 22:12:20 [Fatal] System.InvalidOperationException: La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter.
   à System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   à Vintagestory.Client.NoObf.ChunkTesselator.CullVisibleFacesWithDecor(Dictionary`2 decors, Dictionary`2 drawnDecors) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:ligne 805
   à Vintagestory.Client.NoObf.ChunkTesselator.NowProcessChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, TesselatedChunk tessChunk, Boolean skipChunkCenter) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Render\Tesselation\ChunkTesselator.cs:ligne 357
   à Vintagestory.Client.NoObf.ChunkTesselatorManager.TesselateChunk(Int32 chunkX, Int32 chunkY, Int32 chunkZ, Boolean priority, Boolean skipChunkCenter, Boolean& requeue) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\ChunkTesselatorManager.cs:ligne 323
   à Vintagestory.Client.NoObf.ChunkTesselatorManager.OnSeperateThreadGameTick(Single dt) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\ChunkTesselatorManager.cs:ligne 169
   à Vintagestory.Client.NoObf.ClientThread.Update() dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientThread.cs:ligne 78
   à Vintagestory.Client.NoObf.ClientThread.Process() dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientThread.cs:ligne 34
1.6.2023 22:12:34 [Notification] Client pause state is now on
1.6.2023 22:12:43 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
1.6.2023 22:12:43 [Notification] Stopping single player server
1.6.2023 22:12:45 [Notification] Exiting current game to main menu, reason: client thread crash
1.6.2023 22:12:53 [Warning] Texture with texture id 49 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.

**Comment by Craluminum2413** [comment]
Where is crash log?

**Comment by radfast** [comment]
Thank you for the clear report.  This is fixed in upcoming release 1.18.6    (note: the fix for this is not yet included in 1.18.6-rc1, but will be in the next version)
