### ISSUE TITLE
Bug with some maps to the Archive

### ISSUE THREAD

**Issue by Nic0d3mu5** [anegostudios/VintageStory-Issues#2797]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Hi, for some players, maps to the Archive sometimes lead to "tiny" treasures, like 1 or 2 old chests with random stuff in it. (but not to the Archive)

### How to reproduce

1. Create a world
2. Go in creative
3. Test some of the maps to the Archive

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Could you please screenshot those maps in cretive inventory? Also enable "Developer settings" => "Debug info", take each of those maps, hold shift key, hover over each of them, then screenshot it as well

**Comment by Nic0d3mu5** [comment]
Sorry for the delay. Unfortunately, it seems to have a kind of random factor. It was one friend of mine who tested it but he deleted this world... And I tried to reproduce it but couldn't.
Maybe sometime the map will not indicate correctly for one or two players.
Sorry I can't be more helpful.

**Comment by Nic0d3mu5** [comment]
I'm really sorry, I just realised now that traders now sell treasure maps... and I think all I was saying before was just a big misunderstanding because of that...
Sorry again!
