### ISSUE TITLE
Chutes ignore wrench adjustment

### ISSUE THREAD

**Issue by Jee-Host** [anegostudios/VintageStory-Issues#2798]
### Game Version

v1.18.6-rc.1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

T-shaped chutes' behavior ignores adjustment with a wrench, meaning if you initially place it like -| (one end facing down) and then rotated it to be an upside down T (no end facing down) it will drop transported item from its bottom face as if it was never rotated. However if you initially placed it as an upside down T it will function as such.

P.S. It is possible something like this also happens with other chutes, but I haven't tested for it.

P.P.S. Having the same issue with 3-way chutes.

### How to reproduce

1. Load any world.
2. Place a T-chute so that initially one of its ends is facing down.
3. Adjust it with a wrench so none of its ends are facing down.
4. Feed it items.

### Screenshots

![2023-06-04_14-30-53](https://github.com/anegostudios/VintageStory-Issues/assets/5471117/0ed6e643-6675-4bb9-8543-746bf71bf730)

### Logs

```Log```

**Comment by Zourin2** [comment]
I can confirm this occurring in my current multiplayer game. Also on v1.18.6-rc.1

**Comment by Th3Dilli** [comment]
ty, this has been resolved in 1.19
