### ISSUE TITLE
Game left on pause leaks memory when not in foreground

### ISSUE THREAD

**Issue by verticaljelly** [anegostudios/VintageStory-Issues#280]
When:

Pressing esc and switching window for an extended period of time (game is paused)

What happens: 
Game seemingly leaks memory (increases in memory allocated without it dropping) and when trying to switch back to the game, seems to be very unresponsive and it's impossible to make it responsive again. Have to restart the game when this happens which is a bit annoying.
One of the other problems when left in paused mode for short time is that sometimes block interraction is still rendered with the initial block (taking out bushes shows them as being there even after the item is in your inventory, setting up a knapping or clay surface doesn't show the surface etc) 

Suggestion: 
All of this kind of problems seem to have to do with the rendering thread while paused, but I may be wrong.

**Comment by tyronx** [comment]
Any way to reliably reproduce this bug? I've started a new singleplayer world, hit esc and let the PC run for an hour but I could not observe any memory leaks.

**Comment by tyronx** [comment]
No new info in several months. Assuming to be fixed or not big enough of a problem
