### ISSUE TITLE
Game crash on start up

### ISSUE THREAD

**Issue by Alqueos** [anegostudios/VintageStory-Issues#2805]
Like title says booting up the game and it crashed a second after hitting run. No mods installed. Does this from fresh install.

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
6/9/2023 12:06:37 PM: Critical error occurred
Loaded Mods: 
System.BadImageFormatException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Vintagestory.API.Datastructures.JsonObject.FromJson(String jsonCode)
   at Vintagestory.API.Config.Lang.PreLoad(ILogger logger, String assetsPath, String defaultLanguage) in VintagestoryApi\Localization\Lang.cs:line 99
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by tyronx** [comment]
looks like a corrupted install, try reinstalling the game, make sure antivirus does not interfere

**Comment by Alqueos** [comment]
> looks like a corrupted install, try reinstalling the game, make sure antivirus does not interfere

Sadly I have done that. Different versions of the game. download with different browsers. Disable windows defender. run install as admin. Run game as admin. Done a repair on windows files. I mean I have gone through it lol

**Comment by tyronx** [comment]
make sure to fully delete the game and %appdata%/VintageStory folder. Might also want to clear out %appdata%/VintageStoryData/Mods. Could also run a disk check to search for corrupted sectors. Try on another computer. Could try downloading it from a different internet connection
