### ISSUE TITLE
Can't make dough with jug of water

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2815]
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

You can make dough with a bowl of water (1L) and a bucket of water (10L) but you can't make dough with a jug of water (3L). Not so much a bug as much as a forgotten feature?
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/3a38fc91-58aa-4bc5-b0a4-63ede68414dc)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/b9973e14-b798-4c58-a85c-9973db98cbc3)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/116f472c-b0c8-4165-bb05-299fefb86934)

**Comment by Craluminum2413** [comment]
It is a suggestion. Send suggestions to [forums suggestion section](https://www.vintagestory.at/forums/forum/5-suggestions/) or to discord

**Comment by VallenFrostweaver** [comment]
Please reinstate. I have confirmed this as a bug with Radfast.
