### ISSUE TITLE
Cannot Create Tongs with Sticks and Twine

### ISSUE THREAD

**Issue by inthisidrown** [anegostudios/VintageStory-Issues#2818]
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Following the recipe for tongs on the wiki does generate tongs:

Wiki link: https://wiki.vintagestory.at/index.php/Tongs

### How to reproduce

1. In crafting mode add one twin to slot 2
2. Add sticks to slots 1,3,4,6,7,9
3. No Tongs show in the output box

### Screenshots

![Vintagestory_mWEaJ7GYQt](https://github.com/anegostudios/VintageStory-Issues/assets/136504215/1673c73f-53f9-4346-92c7-5dfc5e38760c)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Use rope instead flax twine

**Comment by inthisidrown** [comment]
@Craluminum2413 the wiki needs to be updated then 😏
