### ISSUE TITLE
Placed lights (torches, lanterns, etc) do not illuminate

### ISSUE THREAD

**Issue by ultradm** [anegostudios/VintageStory-Issues#2819]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Went into a cave and placed a lantern, then some torches. None of the lights were illuminated. Breaking ALL of them in the area and replacing them fixed the problem.

As an added detail, when I climbed out of the cave on to the surface, my torches worked fine. I suspect only the light sources in the cave didn't work because the light level was 0, and that might have caused the glitch.

I use the following mods:
Advanced Smithing
Alternative Glider Implementation
Animal Cages
Knapster
Buzzwords
Can Be Ignited
Carry On
CommonLib
Player Corpse
Workbench Expansion
XLib
XSkills

### How to reproduce

Going into a light level 0 area to place light sources was what caused the issue, but the bug doesn't always get reproduced.

### Screenshots

![lighting](https://github.com/anegostudios/VintageStory-Issues/assets/116535212/4892d3d2-a6d2-400b-a052-9b41222f9654)

### Logs

```Log```

**Comment by Guimoute** [comment]
I got a similar issue the other day. Reloading the world solved the problem. 

Same as ultradm, I can describe what happened before but those are not reproduction steps. The only notable thing I did was travel via a translocator. 

https://github.com/anegostudios/VintageStory-Issues/assets/51537797/2ed119fc-5557-49e2-8e76-fc0eb73fe2b8

**Comment by ultradm** [comment]
Good to know I'm not alone. How did you reload the world?

**Comment by ultradm** [comment]
> I got a similar issue the other day. Reloading the world solved the problem.
> 
> Same as ultradm, I can describe what happened before but those are not reproduction steps. The only notable thing I did was travel via a translocator.
> light.bug.mp4

Good to know I'm not alone. How did you reload the world?

**Comment by Guimoute** [comment]
I simply used the "reload world" hotkey, but it's probably equivalent to leaving to the main menu and joining the world again.

**Comment by Craluminum2413** [comment]
Closed due to inactivity
