### ISSUE TITLE
Passive bears attack without provacation

### ISSUE THREAD

**Issue by vintage-seraph** [anegostudios/VintageStory-Issues#2821]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Created a 'explorer' world with passive mobs.  The first night i sat on a ruin block waiting for dawn.  I was attacked from behind by a bear.  I have experienced this before in another world.  It seems to happen randomly.

### How to reproduce

Seems random.  The bears are not attacking other mods, so I don't think it is related to it being enraged.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
If bear falls, it gets damage, then it gets angry

**Comment by Craluminum2413** [comment]
Yes
