### ISSUE TITLE
Typo in explanation for making blue cheese?

### ISSUE THREAD

**Issue by Nic0d3mu5** [anegostudios/VintageStory-Issues#2822]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

For making blue cheese, in the handbook and the Wiki, it says it needs a cellar... with an unblocked hole.
It feels kind of weird for a proper cellar.
Or maybe I missed something.

### Logs

```Log```

**Comment by RedramVS** [comment]
The description is correct.  Blue cheese requires there be at least 1 block open in the cellar wall, but yet the light level must be very low.  This presents a slightly greater challenge than just having a basic cellar.  The wiki explains this in more detail.  Think of it as letting air circulate to bring in the right mold spores.
