### ISSUE TITLE
Setting GUI scale to the lowest crashes the game

### ISSUE THREAD

**Issue by siasur** [anegostudios/VintageStory-Issues#283]
I am running Version 1.9.2 (Stable)

I wanted to change my GUI scale and messed a bit with the slider, setting it to different values. I wanted to know what the UI would look like with the smallest setting possible, and changed the slider completely to the left. As soon as I released the mouse button the game crashed.

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/3166851/client-crash.txt)

If it is useful/important:

The game was opened in lan and one other player was connected but afk at this moment.

**Comment by copygirl** [comment]
This only appears to happen while in a world.

**Comment by copygirl** [comment]
The issue is from the method that's supposed to blur a surface, probably due the blur radius being too large for a small surface, causing reads happening out-of-bounds. I can't make sense of the method because of the seemingly random variable names, otherwise I would've had a go at fixing it.

**Comment by tyronx** [comment]
Thanks for taking a look copygirl. 
I would assume the blur is not designed to handle cases where witdh/height is smaller than the blur kernel diameter so I'll just clamp it to be never above that. 

Seems to fix the crash. Thanks for reporting. Fixed for v1.9.3
