### ISSUE TITLE
Flatpak installation freezes

### ISSUE THREAD

**Issue by DMLugh** [anegostudios/VintageStory-Issues#2831]
### Game Version

v1.18.5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When i press the Open button, the game starts but freezes in the loading world menu.

### How to reproduce

1. Install the game in Fedora Linux (from Flatpak).
2. Open the app
3. Singleplayer>>Create World
4. Now you are stuck in the loading/creating menu

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/35033301/37220200-c7bb-4923-85c1-1950131e557f)

### Logs

```Log```

**Comment by SamDeNies** [comment]
I also have this issue (ArchLinux with both flatpak and AUR versions).  For me, continuously moving the cursor during world generation and load usually prevent the freeze.  I don't know if this is replicable.

**Comment by decafsaxguy** [comment]
Having same issue with LinuxMint but @SamDeNies fix with moving cursor worked to prevent freeze

**Comment by silverdrake3** [comment]
Same issue on SteamDeck. The mouse moving trick did not work for me (was trying to generate a new world with default settings).

**Comment by decafsaxguy** [comment]
@silverdrake3 I've found either switching to 1.18.6-rc or switching the load screen to dev mode fixed the issue. Thinking either it's an issue with the .NET framework of 1.18.5 not playing nice with the most recent version of Mono or somehow dev mode's interface somehow has activity during the load screen that prevents the freeze? Try one and if that workaround/fix doesn't work then try the other maybe?

**Comment by silverdrake3** [comment]
Forgive me, @decafsaxguy , but I can't seem to figure out how to enable dev mode.

Switching to 1.18.6-rc would be tricky for me (I am only a journeyman linux user, so compiling a tar.gz tends to be hit-and-miss for me). I tried waiting for the new flatpak of 1.18.6 to drop, but I'm still having issues.

**Comment by Rince1972** [comment]
try this and put false instead of true 

![Screenshot from 2023-07-13 09-20-29](https://github.com/anegostudios/VintageStory-Issues/assets/139439899/7680b82a-9892-4513-9544-efee07b0aba5)

**Comment by silverdrake3** [comment]
> try this and put false instead of true
> 
> ![Screenshot from 2023-07-13 09-20-29](https://user-images.githubusercontent.com/139439899/253199027-7680b82a-9892-4513-9544-efee07b0aba5.png)

Just tried that. Sad to say, I'm still having freezing issues with no apparent change. Seems to happen when mousing over the world opens the world details menu. Music keeps playing, but everything else stops.

![Screenshot_20230715_2](https://github.com/anegostudios/VintageStory-Issues/assets/7970585/c11b4327-fb4e-4814-a8cf-007f7521e931)

**Comment by Th3Dilli** [comment]
is this still happening in version 1.18.8 and later?

**Comment by SamDeNies** [comment]
I haven't had this issue in a long time.  I don't recall which version fixed it.  It could have been 1.18.8.

**Comment by Th3Dilli** [comment]
ok great then I'll make this resolved
