### ISSUE TITLE
Coal piles with one item left have no hitbox

### ISSUE THREAD

**Issue by noelle-lavenza** [anegostudios/VintageStory-Issues#2834]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

A coal pile with only one item left in it will be 0 layers tall, which has no hitbox.
[`public int Layers => inventory[0].StackSize / 2;`](https://github.com/anegostudios/vssurvivalmod/blob/744fc26f1fb1132c141d33b327941f05f0397205/BlockEntity/BECoalPile.cs#L72) rounds down, so having 1 coal in the stack will result in 0 layers.
Two possible solutions:
1) Make it so [`CollisionBoxesByFillLevel[0]` isn't empty.](https://github.com/anegostudios/vssurvivalmod/blob/744fc26f1fb1132c141d33b327941f05f0397205/Block/BlockCoalPile.cs#L29)
2) Make it so `Layers` on `BlockEntityCoalPile` rounds up rather than down, so 1 coal = 1 layer, 3 coal = 2 layers instead of 0 layers and 1 layer respectively.

I would prefer  the second, personally.

### How to reproduce

1. Create a coal pile with only one coal remaining.
2. It has no hitbox and the only way to remove it is by breaking the block beneath it.

**Comment by Craluminum2413** [comment]
Fixed in 1.18.7
