### ISSUE TITLE
Progression Guide lists 40 nuggets needed but not what for.

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2843]
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

As seen in the Survival Handbook under the Progression Guide: Early Copper Age entry, it mentions 40 copper nuggets are needed, but not what for (pouring into a pick and hammer mold for first mining tools).
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/ddc1d906-a509-450c-a622-f206983f8d85)

**Comment by tyronx** [comment]
thanks for the report, i've improved this paragraph for the next version
