### ISSUE TITLE
update Fail 

### ISSUE THREAD

**Issue by Michielgr1977** [anegostudios/VintageStory-Issues#2845]
### Game Version

v1.18.6-rc1 

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

[Error] An error occurred trying to start process 'C:\Users\...\AppData\Local\Temp\vs_update_1.18.6-rc.2.exe' with working directory 'C:\Users\...\AppData\Roaming\Vintagestory1.18'. The process has no access to the file because it is by another process is used.

### How to reproduce

Start VStory 
click on the popup
Confirm 
Error.

### Logs

26.6.2023 15:23:38 [Notification] Client logger started.
26.6.2023 15:23:38 [Notification] Game Version: .net7 Experimental build - v1.18.6-rc.1 (Unstable)
26.6.2023 15:23:39 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
26.6.2023 15:23:39 [Notification] CPU Cores: 16
26.6.2023 15:23:39 [Notification] Available RAM: 32128 MB
26.6.2023 15:23:39 [Notification] Graphics Card Vendor: ATI Technologies Inc.
26.6.2023 15:23:39 [Notification] Graphics Card Version: 3.3.0 Core Profile Context 22.20.02.220623
26.6.2023 15:23:39 [Notification] Graphics Card Renderer: AMD Radeon(TM) Graphics
26.6.2023 15:23:39 [Notification] Graphics Card ShadingLanguageVersion: 4.60
26.6.2023 15:23:39 [Notification] GL.MaxVertexUniformComponents: 4000
26.6.2023 15:23:39 [Notification] GL.MaxUniformBlockSize: 131072
26.6.2023 15:23:39 [Notification] Cairo Graphics Version: 1.17.3
26.6.2023 15:23:39 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
26.6.2023 15:23:39 [Notification] C# Framework: .net 7.0.8
26.6.2023 15:23:39 [Notification] Start discovering assets
26.6.2023 15:23:39 [Notification] (Re-)loaded frame buffers
26.6.2023 15:23:39 [Notification] Found 22 base assets in category lang
26.6.2023 15:23:39 [Notification] Found 0 base assets in category patches
26.6.2023 15:23:39 [Notification] Found 22 base assets in category config
26.6.2023 15:23:39 [Notification] Found 0 base assets in category worldproperties
26.6.2023 15:23:39 [Notification] Found 46 base assets in category sounds
26.6.2023 15:23:39 [Notification] Found 97 base assets in category shapes
26.6.2023 15:23:39 [Notification] Found 72 base assets in category shaders
26.6.2023 15:23:39 [Notification] Found 16 base assets in category shaderincludes
26.6.2023 15:23:39 [Notification] Found 131 base assets in category textures
26.6.2023 15:23:39 [Notification] Found 4 base assets in category music
26.6.2023 15:23:39 [Notification] Found 0 base assets in category dialog
26.6.2023 15:23:39 [Notification] Found 410 base assets in total
26.6.2023 15:23:39 [Notification] Loading sounds
26.6.2023 15:23:39 [Notification] Sounds loaded
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass .
26.6.2023 15:23:39 [Notification] Begin loading shaders
26.6.2023 15:23:39 [Notification] Load shaders now
26.6.2023 15:23:39 [Notification] Loading shaders...
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass standard.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass particlescube.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass particlesquad.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass sky.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass nightsky.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass woittest.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass helditem.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass decals.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass final.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass gui.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass blur.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass findbright.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass godrays.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass autocamera.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass wireframe.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass entityanimated.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass luma.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass blit.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass texture2texture.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass celestialobject.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass colorgrade.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass guigear.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass ssao.
26.6.2023 15:23:39 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
26.6.2023 15:23:39 [Notification] Cached session key is valid, validating with server
26.6.2023 15:23:40 [Notification] Server validation response: Good
26.6.2023 15:23:40 [Notification] Will search the following paths for mods:
26.6.2023 15:23:40 [Notification]     C:\Users\michi\AppData\Roaming\Vintagestory1.18\Mods
26.6.2023 15:23:40 [Notification]     C:\Users\michi\AppData\Roaming\VintagestoryDataNet7\Mods
26.6.2023 15:23:44 [Notification] Retrieving releases meta data
26.6.2023 15:23:46 [Error] An error occurred trying to start process 'C:\Users\michi\AppData\Local\Temp\vs_update_1.18.6-rc.2.exe' with working directory 'C:\Users\michi\AppData\Roaming\Vintagestory1.18'. Het proces heeft geen toegang tot het bestand omdat het door een ander
proces wordt gebruikt.
26.6.2023 15:23:46 [Error]    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Vintagestory.Client.GuiScreenGetUpdate.<>c__DisplayClass9_0.<<downloadInstaller>b__0>d.MoveNext() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenGetUpdate.cs:line 126
26.6.2023 15:23:56 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:24:05 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:24:15 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:24:41 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:25:15 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:25:27 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:25:44 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
26.6.2023 15:26:11 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers

**Comment by tyronx** [comment]
I've made a mistake by giving the net7 build a rc1 build version instead of rc2. You dont need to update, you are already on the latest net7 build. Do reopen this issue again should a actual update show the same crash
