### ISSUE TITLE
The game crashes while connecting to a local server

### ISSUE THREAD

**Issue by Pavelkoshkarev** [anegostudios/VintageStory-Issues#2847]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

The game crashes while connecting to a local server

### How to reproduce

1. Connect to server
2. Get an error

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
27.06.2023 18:17:15: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.Client.NoObf.GeneralPacketHandler.HandleDisconnectPlayer(Packet_Server packet) в VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:строка 179
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) в VintagestoryLib\Client\ClientMain.cs:строка 746
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) в VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:строка 163
   в Vintagestory.Client.ScreenManager.Render(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 681
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 625
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 119
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 476
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 452
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

**Comment by AsoskovAlexey** [comment]
Same

**Comment by Craluminum2413** [comment]
Will reopen when someone encounter this in 1.19+
