### ISSUE TITLE
Increasing grass coverage texture size rotates grass coverage incorrectly.

### ISSUE THREAD

**Issue by GringoRSA** [anegostudios/VintageStory-Issues#285]
Increasing the grass coverage texture size rotates the grass coverage incorrectly.

For example increasing from the default 64 X 32 resolution to 256 X 128.
All other block textures resized to 128 X 128.

See screenshot below.
![2019-05-10_23-25-24](https://user-images.githubusercontent.com/50502219/57557762-86b9b580-737b-11e9-8ab7-a0aba7c55498.png)

**Comment by tyronx** [comment]
Oh yea, that could use some improvement.

For now you should be able to fix it by setting blockTextureSize in the clientsettings.json to the resolution of your texture pack

**Comment by copygirl** [comment]
I think this needs to be looked into at some point, even if there's a work-around. Reopening.

**Comment by tyronx** [comment]
This has been now addressed, see my comment on #284.
