### ISSUE TITLE
fall damage bug

### ISSUE THREAD

**Issue by PrivateTF2** [anegostudios/VintageStory-Issues#2854]
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

when i was jumping in a deep cave, i was holding jump to bhop, and the first time i fell i took damage but the second fall directly after i didn't despite falling about 25 - 30 blocks give or take

### How to reproduce

just fall down a big hole, the first time taking damage will negate the next i think if withing invincibility frames

### Screenshots

i don't have one

### Logs

i did not

**Comment by Craluminum2413** [comment]
Closed in favor of #4181
