### ISSUE TITLE
Crash when trying to sleep in hay bed (1.9.3rc2)

### ISSUE THREAD

**Issue by darkphan** [anegostudios/VintageStory-Issues#286]
Crashlog: https://pste.me/#/3yu9F

**Comment by RTHauke** [comment]
I've gotten the same crash.
Crash and client logs: https://paste.ee/p/qJTcC#QGeXst1kOG9mlcydtZBIIoVwbV4ixtst

**Comment by tyronx** [comment]
thanks, should be fixed in 1.9.3 stable
