### ISSUE TITLE
"Cancel" and "Save" buttons on signs do not display correctly in other languages (1.18.6)

### ISSUE THREAD

**Issue by DonKamaro** [anegostudios/VintageStory-Issues#2860]
### Game Version

1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Cancel and Save buttons on signs do not display correctly in other languages. In my case, this is the Russian language, however, for example, I encountered such a problem with the French language in this report from another user. These two buttons override the font size selection menu. To change the font size, you need to have a high pixel hunting skill.

This problem exists in both single player and multiplayer. Occurs on version 1.18.6 and earlier versions.

### Screenshots

![2023-06-29_00-59-41](https://github.com/anegostudios/VintageStory-Issues/assets/108415547/732218e2-b41c-401d-8314-e514acd25cfe)
![2023-06-29_00-53-11](https://github.com/anegostudios/VintageStory-Issues/assets/108415547/75bed958-e990-4ce1-90b4-0cdb56af21a2)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Closed in favor of #4086
