### ISSUE TITLE
1.18.6 Visual bug if you put any shoes on ground.

### ISSUE THREAD

**Issue by teknik1** [anegostudios/VintageStory-Issues#2862]
Just put any shoes on the ground and a ghost will appear.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/9663048/b670d66c-efc6-4601-a982-b710fb90ffd1)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/9663048/a0baa87c-37be-42c7-9c3c-061a236e3f46)

**Comment by Craluminum2413** [comment]
Fixed in 1.18.7
