### ISSUE TITLE
loading of the world crush

### ISSUE THREAD

**Issue by PiatraAlatyr** [anegostudios/VintageStory-Issues#2870]
### Game Version

v.18.6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Everything was fine, but today the world just stopped loading.

### Logs

```Log```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.6 (Stable)
30.06.2023 18:08:35: Critical error occurred
Loaded Mods: backpackpack@1.0.3, blacksmithname@1.1.0, cavecontent@1.0.1, capreolinae@1.0.2, pantherinae@1.0.5, haybales@1.1.0, immersivecorpsedrop@1.0.1, pondfrogsi@1.1.1, sfaws@1.0.0, spyglass@0.4.5, ssppvv@1.0.5, truesunfishes@1.0.0, vgaas@1.0.1, game@1.18.6, wildcrafttrees@1.2.3, alloycalculator@1.0.0, canbeignited@1.1.0, carryon@1.2.0, commonlib@2.1.1, cooperativecombat@1.1.0, grassiergrass@1.0.0, hudclock@3.2.1, lc@1.0.0, moreanimals@1.2.4, morepiles@1.4.1, ovenfuel@1.0.0, petai@1.7.9, postsandbeams@1.1.0, prospecttogether@1.0.0, useplanksinpitkiln@1.0.0, vanvar@3.2.0, creative@1.18.6, survival@1.18.6, waypointtogether@1.0.1, woodbarrels@1.0.4, woodchests@1.0.5, workbenchexpansion@1.6.3, metalrecovery@0.1.19-pre.1, mcbpicks@1.1.1, stonequarry@3.0.1
System.IO.FileNotFoundException: Could not find shape file: game:item/tool/wand in itemtype game:magicwand.  Possibly a broken mod (game) or different versions of that mod between server and client?
   в Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) в VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:строка 51
   в Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, CompositeShape forShape, MeshData& modeldata) в VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:строка 683
   в Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateItems(IList`1 itemtypes, Int32 offset, Int32 maxCount) в VintagestoryLib\Client\Render\Tesselation\ShapeTesselatorManager.cs:строка 861
   в Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step7(Int32 index, Int32 frameCount) в VintagestoryLib\Client\Systems\Startup.cs:строка 777
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) в VintagestoryLib\Client\ClientMain.cs:строка 757
   в Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) в VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:строка 305
   в Vintagestory.Client.ScreenManager.Render(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 724
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в VintagestoryLib\Client\ScreenManager.cs:строка 627
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 126
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 479
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 454
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30.06.2023 18:04:51, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0020001, адрес исключения 00007FF8CFFCCD29
Стек:
   в System.Environment._Exit(Int32)
   в System.Environment._Exit(Int32)
   в System.Environment.Exit(Int32)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   в OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   в OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   в OpenTK.GameWindow.Run(Double, Double)
   в Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   в Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   в Vintagestory.Client.ClientProgram.Main(System.String[])
 }
--------------
{ TimeGenerated = 29.06.2023 21:47:35, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.6.0, метка времени: 0x649be5a4
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.2364, метка времени: 0x5b7d4d22
Код исключения: 0xc0020001
Смещение ошибки: 0x000000000002cd29
Идентификатор сбойного процесса: 0x2220
Время запуска сбойного приложения: 0x01d9aab832fb5970
Путь сбойного приложения: X:\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 2ee7d700-72a2-44d2-ba6c-1775c0c1a013
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 29.06.2023 21:47:34, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0020001, адрес исключения 00007FF9C6C6CD29
Стек:
   в System.Environment._Exit(Int32)
   в System.Environment._Exit(Int32)
   в System.Environment.Exit(Int32)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   в OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   в OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   в OpenTK.GameWindow.Run(Double, Double)
   в Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   в Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   в Vintagestory.Client.ClientProgram.Main(System.String[])
 }

**Comment by Craluminum2413** [comment]
Does it crash without mods? Check latest mod updates and try again

**Comment by PiatraAlatyr** [comment]
I just returned the previous version of the game. Maybe some of the mods are not compatible with 18.6
