### ISSUE TITLE
Held glass blocks are transparent through the player

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2872]
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

The image says it all. I'm looking at another player holding glass.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/ab032571-9298-458a-ae22-e6eced5a9d74)

**Comment by Craluminum2413** [comment]
Duplicate of #1850
