### ISSUE TITLE
Crash when you enter a server with mods

### ISSUE THREAD

**Issue by LeKrias** [anegostudios/VintageStory-Issues#2875]
### Game Version

v1.18.6 (stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Game crashes when trying to join a modded server

### How to reproduce

first, download the mods automatically, second, enter the server third, crash for free

### Logs

Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.6 (Stable)
01-07-2023 14:50:35: Critical error occurred
Loaded Mods: backpackpack@1.0.3, betterruins@0.2.1, canmarket@0.2.7, translocatorengineeringredux@1.4.2, game@1.18.6, carryon@1.2.0, commonlib@2.1.1, medievalexpansion@3.9.3, petai@1.7.9, creative@1.18.6, vsquest@0.4.1, survival@1.18.6, workbenchexpansion@1.6.3, xlib@0.7.2, playercorpse@1.7.1, stonequarry@3.0.1, wolftaming@1.7.3, xskills@0.7.3
System.Exception: Max joint cap of 34 reached. Sorry, you'll have to simplify your model if you want it to be animated. (until some programmer finds another solution to pass on more joint data through shader uniforms)
   en Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) en VintagestoryApi\Common\Model\Animation\Animation.cs:línea 98
   en Vintagestory.API.Common.AnimationUtil.GetAnimator(ICoreAPI api, String cacheDictKey, Shape shape) en VintagestoryApi\Common\Model\Animation\AnimationUtil.cs:línea 175
   en Vintagestory.API.Common.AnimationUtil.InitializeAnimator(String cacheDictKey, MeshData meshdata, Shape shape, Vec3f rotation, EnumRenderStage renderStage) en VintagestoryApi\Common\Model\Animation\AnimationUtil.cs:línea 62
   en Vintagestory.API.Common.AnimationUtil.InitializeShapeAndAnimator(String cacheDictKey, Shape shape, ITexPositionSource texSource, Vec3f rotation, MeshData& meshdata) en VintagestoryApi\Common\Model\Animation\AnimationUtil.cs:línea 53
   en Vintagestory.GameContent.GearRenderer.Init() en VSSurvivalMod\Systems\TemporalStability\GearRenderer.cs:línea 67
   en Vintagestory.GameContent.TemporalStabilityEffects.Event_LevelFinalize() en VSSurvivalMod\Systems\TemporalStability\TemporalStabilityEffects.cs:línea 278
   en System.Action.Invoke()
   en Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) en VintagestoryLib\Client\Systems\Startup.cs:línea 1010
   en Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) en VintagestoryLib\Client\ClientMain.cs:línea 747
   en Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) en VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:línea 305
   en Vintagestory.Client.ScreenManager.Render(Single dt) en VintagestoryLib\Client\ScreenManager.cs:línea 724
   en Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) en VintagestoryLib\Client\ScreenManager.cs:línea 627
   en Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) en VintagestoryLib\Client\ClientPlatform\GameWindow.cs:línea 126
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 479
   en OpenTK.GameWindow.DispatchRenderFrame() en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 454
   en OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 375
   en Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   en Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) en VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:línea 93

**Comment by Craluminum2413** [comment]
Mods are the problem
