### ISSUE TITLE
Block semi-consistently doesn't drop item after breaking

### ISSUE THREAD

**Issue by dougabugg** [anegostudios/VintageStory-Issues#2879]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I built a cellar out of packed dirt, and use 2 dark mud bricks to seal the door when I enter/leave. Semi-consistently, one of the blocks in the door way will not drop as an item after breaking.

### How to reproduce

See attached video

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/18294318/7b4f2d56-4038-42f4-8db8-de9db1768fce

### Logs

I checked both client-main.txt and server-main.txt for log entries at the time I took the video showing the bug, but didn't see anything relevant to include.

**Comment by Craluminum2413** [comment]
It is intended, they have 85% drop chance

**Comment by dougabugg** [comment]
well, if that's true, that's news to me. I don't see any info about drop chances [on the wiki](https://wiki.vintagestory.at/index.php/Soil_Blocks#Mud_Brick) or in the handbook.
![handbook](https://github.com/anegostudios/VintageStory-Issues/assets/18294318/a4b818bf-3716-4513-a408-070ef3bba974)

if this confirmed isn't a bug, feel free to close.

**Comment by dougabugg** [comment]
@Craluminum2413 just curious, where did you learn about the 85% drop rate? I can't find any info on for the life of me lol

**Comment by Craluminum2413** [comment]
`\AppData\Roaming\Vintagestory\assets\survival\blocktypes\soil\mudbrick.json`
