### ISSUE TITLE
Can't Open Any Version of Vintage Story, Mods or Not

### ISSUE THREAD

**Issue by theSHWolf** [anegostudios/VintageStory-Issues#2886]
### Game Version

v1.18.5.0

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I was playing single player and doing some exploration. I had noticed that my game was occasionally freezing and not responding, and then it crashed, saying my graphics card wasn't able to handle loading anything. I tried taking the mods out of the folder, and same result. I tried 1.18.0 and got the same error. I can't even get to the display screen, when it's worked just fine before. I'm not sure what crashed, because I had played that version for several hours at least without having any issue. 

### How to reproduce

I'm not sure how I would reproduce this, sorry.

### Logs

```Log```Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.5 (Stable) by OverF1X  
7/4/2023 12:38:20: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 202
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/4/2023 12:31:21, Site = , Source = Windows Error Reporting, Message = Fault bucket 1494687641767539835, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: KERNELBASE.dll
P5: 10.0.19041.3086
P6: e1ac3f79
P7: c000041d
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E94.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_5fd0ef4746588740865d8b9dae760154ace7390_099fad0f_234fdb60-210f-4302-92fb-db6ac22339d1

Analysis symbol: 
Rechecking for solution: 0
Report Id: cb33a462-38ee-4e9a-9fd8-81e4738a0d48
Report Status: 268435456
Hashed bucket: 86e87740495ae201a4be327db1b8747b
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/4/2023 12:31:20, Site = , Source = Windows Error Reporting, Message = Fault bucket 1965527061383556614, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: VintagestoryLib
P5: 1.18.5.0
P6: 64668a12
P7: 21e0
P8: 113
P9: System.Exception
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B48.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_389f5e7477d22998ac1e0f8f4f433e3a4a93de1_099fad0f_4eddf912-3a14-4c55-96d3-17c1df85de5b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 98aef762-eecd-4beb-bd0d-3a967139c01a
Report Status: 268435456
Hashed bucket: 63daa0a4e883f82ccb46f472d22f2e06
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/4/2023 01:16:08, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: KERNELBASE.dll
P5: 10.0.19041.3086
P6: e1ac3f79
P7: c000041d
P8: 000000000002cf19
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_5fd0ef4746588740865d8b9dae760154ace7390_099fad0f_234fdb60-210f-4302-92fb-db6ac22339d1

Analysis symbol: 
Rechecking for solution: 0
Report Id: cb33a462-38ee-4e9a-9fd8-81e4738a0d48
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Pirated versions are not supported, also they are very unpredictable
