### ISSUE TITLE
Game/Singleplayer Server Crash on damage taken

### ISSUE THREAD

**Issue by SnoopierM** [anegostudios/VintageStory-Issues#2888]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game runs fine until taking damage, then unable to interact with anything. All entities freeze besides player, main source of damage being hunger. 
This is shown in the txt as missing field for 'Vintagestory.API.Common.Entities.Entity.Pos' 
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11952595/server-main.txt)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is an issue in Attributer mod
