### ISSUE TITLE
Survival Handbooks font size not respecting changed GUI scale

### ISSUE THREAD

**Issue by siasur** [anegostudios/VintageStory-Issues#289]
The font size in the Survival Handbook changes only once when changing the GUI scale and is then "frozen".

**Steps to Reproduction:**

1. Start the game and determine which GUI Scale is set.
2. Open the Survial manual but do not scroll.
3. Change the GUI scale significantly (for example to min or max).
4. Open the Survial manual but do not scroll.
    4.1. Make sure that the text size has actually changed.
5. Set the GUI Scale back to the original value.
6. Open the Survival manual and scroll down.

**Expected behavior:**
All texts are the same size and according to the GUI scale.

**Current behavior:**
The texts that were visible before (while changing the GUI scale) didn't change back, the other/lower lines are according to the GUI scale.

_This effect can be "stacked". I now have a manual with a few lines of small text, and a few lines of large text. Have a look at these Screenshots:

![Small2Normal](https://user-images.githubusercontent.com/2236705/57575462-be436300-744a-11e9-8261-7b4f26122ecf.png)
![Normal2Big](https://user-images.githubusercontent.com/2236705/57575461-be436300-744a-11e9-95ca-8014c9402e24.png)

**Comment by tyronx** [comment]
Thanks for the report, fixed in v1.9.4
