### ISSUE TITLE
Overlay Texture Path 

### ISSUE THREAD

**Issue by arkaik8** [anegostudios/VintageStory-Issues#2894]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Running into an issue when trying to set overlay texture paths between game and modded.   The game doesn't seem to work if the base path is set to a modded domain folder, and the overlay path set to game domain folder.   (see pic for example) 

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/38825117/5e7b09a8-0463-439e-a18a-a3d2a52399ab)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
[Try to do overlays like here](https://github.com/Craluminum-Mods/CLRD/blob/126821db2206cee37b13c205d6d68ca403a57719/resources/assets/clrd/blocktypes/leather.json#L19)

**Comment by arkaik8** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/38825117/f7f5c664-8664-4351-843f-af75ad26f372)

That somewhat works, but missing texture is still showing up.

**Comment by arkaik8** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/38825117/2d9f1527-a5a6-48cd-9fc2-dc8e52d3b039)

This is how I set it up for ore-ungraded.

**Comment by Craluminum2413** [comment]
They should be both in game domain

**Comment by arkaik8** [comment]
All my rock textures are in my mod folder. Is there not a way for it to read both domains? Is the only solution to move all my mod textures to the game domain even though none of them are part of the vanilla game?

**Comment by Craluminum2413** [comment]
Currently yes, it is the only solution

**Comment by arkaik8** [comment]
Ok. Thanks for the quick replies.  Are you all planning to fix the code so it will eventually be able to read two domain files?

**Comment by Craluminum2413** [comment]
It worked the last time I tried
