### ISSUE TITLE
Textures are heavily glitched and/or do not load. (fixed)

### ISSUE THREAD

**Issue by Veemie** [anegostudios/VintageStory-Issues#2897]
### Game Version

v1.18.6 (.net7 build)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Textures glitch out heavily, sometimes show up as a black void, don't load, or are a glitchy mess that may flicker. My singleplayer does not have this issue, it's only on multiplayer. Also, this was not a problem for me until the recent update.

Things I tried to fix the bug:
0) Reinstalled the game
1) Deleted mod cache
2) deleted Mod Config
3) no ModData nor Maps folder has been created so did not need to clean
4) ensured not installed to Program Files / Program Files (x86)
5) Deleted server specific folders in ModsByServer folder
6) Deleted contents in Mods folder
7) Updated Graphics Card Drivers
8) checked to see if GPU ram was maxing out but it isn't; however, very high GPU useage being reported
9) checked to see if CPU useage was maxed -- it isn't and is fine
10) looked on github and found a similar report on v1.17.9 (https://github.com/anegostudios/VintageStory-Issues/issues/2326); however, I'm using 1.18.6 and this happens on .NET 4 and .NET 7 versions of the client.
11) tried to see if in-game graphics settings being toggled off had any effect and aside from FPS improvement, there wasn't any progress on fixing the problem.
12) tried to relight the area (.debug relightchunk) and redraw all chunks (.debug redrawall) to see if it had any effect -- none

13*) The issue was solved by teleporting far away (used a runestone to go ~10kblocks from spawn), and then rejoining the server after restarting my game.

Leaving this up if anyone else comes across this issue bc it took me a while to figure it out, and I solved it mid-writing this Github report. 

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/6d2e433c-cf83-4991-ae40-6b6b7cb6a2dc)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/a6cfc1be-7fe3-4a9e-951e-84e335705435)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/acf93b37-354c-4260-8e61-b3403fe56153)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/0868c8a8-a27e-41f4-a39c-ed8962380032)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/8774eaf8-485c-4fda-afb3-27ed5ce74ea1)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/4866547c-6245-4400-bbd4-cc2cfde08923)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/06ea72c5-5b80-4746-b283-34832cab80e9)
![2023-07-08_01-43-41](https://github.com/anegostudios/VintageStory-Issues/assets/138955326/b5b33788-25c1-4e4c-ba69-d5a7304393c0)
this last pic is of me exploring the location I teleported away to :)

**Comment by Craluminum2413** [comment]
It is caused by huge amount of texture heavy mods
