### ISSUE TITLE
Moving away from firepits doesnt close their dialog

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#29]
1.5.2.2, the official server.
I have floatyGuis on.
When I open firepit dialog(s) and move backwards from them, they never close.
I would expect them to have the same bahavior as chests - to close after I moved some distance away from them.

**Comment by Heptagon-ru** [comment]
This issue might be worth solved together with whole vOS update, e.g. with these suggestion forum thread: https://www.vintagestory.at/forums/topic/275-improving-replacing-the-gui/?do=findComment&comment=1616

**Comment by tyronx** [comment]
I happened to add that together with the chest opening issue thing
