### ISSUE TITLE
Intermittent client exception on join -  coincident with "Startup sequence wrong"

### ISSUE THREAD

**Issue by Lantalia** [anegostudios/VintageStory-Issues#2904]
### Game Version

v1.18.6

### Platform

None

### Modded

None

### SP/MP

None

### Description

There is an intermittent exception that corrolates with "8.7.2023 15:27:52.250 [VerboseDebug] Startup sequence wrong, playerdata packet handled before BlocksReceivedAndLoaded; player may be null" being emitted in the client-debug log. The actual exception is in Vintagestory.Client.NoObf.ClientMain.GetItem(Int32 itemId) when attempting to decode a recipe from the server, with the list being empty buy item 252 being indicated by the recipe. Presumably this is due to the playerdata packet being received and processed before BlocksReceivedAndLoaded. Let me know if there is more data or instrumentation I should add/turn on. The issue is intermittent, and likely a race condition. The mods installed are not the source of the "Startup sequence wrong" message, and so far, I have not seen that message when I join successfully. I am separately digging through a culinary artillery, but it really looks like this is a deeper issue

### How to reproduce

1. Start up vintage story
2. Click multiplayer
3. Select rogue house
4. Occasionally the exception included below occurs

### Logs

```Log```
Crash Reporter:
Running on 64 bit Windows with 32508 MB RAM
Game Version: .net7 Experimental build - v1.18.6 (Unstable)
7/8/2023 3:27:52 PM: Critical error occurred in the following mod: aculinaryartillery@1.0.12
Loaded Mods: aculinaryartillery@1.0.12, ancienttools@1.5.7, autowalk@1.0.2, chiseltools@1.8.4, emotemenu@1.0.4, instruments@1.2.1, mannequinstand@1.0.1, meteoricexpansion@1.2.4, leadroof@1.3.4, primitivesurvival@3.2.4, spyglass@0.4.5, tprunes@1.0.8, temporalstormgear@1.0.1, game@1.18.6, wildcraft@1.6.6, beehivekiln@1.2.2, betterfirepit@1.1.1, bodyheatbar@1.0.0, calendar@1.0.0, canmarket@0.3.10, carryon@1.2.0, commonlib@2.1.1, cooperativecombat@1.1.0, expandedfoods@1.6.6, fairplayguardian@1.1.2, hudclock@3.2.0, sailboat@1.1.0, naturalnight@1.0.0, petai@1.7.10, pixelwaypoints@1.0.0, claywheel@1.1.0, prospectorinfo@4.3.0, rhadditions@3.0.12, scarecrow@1.2.3, statushud@1.3.1, stonebakeoven@1.0.3, creative@1.18.6, vsquest@0.4.1, survival@1.18.6, xlib@0.7.4, bullseye@2.5.0-rc.1, cats@1.7.0, doffanddonagain@3.0.0, em@2.2.1, playercorpse@1.7.2, rifteye@0.2.3, simplewinddirection@1.0.2, stonequarry@3.0.2, wolftaming@1.7.3, xinvtweaks@1.5.3, xskills@0.7.4, bricklayers@2.2.0
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Cannot get item of id 252, item list count is only until 0!')
   at Vintagestory.Client.NoObf.ClientMain.GetItem(Int32 itemId) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 2125
   at Vintagestory.API.Common.ItemStack..ctor(BinaryReader reader, IWorldAccessor resolver) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryApi\Common\Collectible\ItemStack.cs:line 187
   at Vintagestory.API.Common.CraftingRecipeIngredient.FromBytes(BinaryReader reader, IWorldAccessor resolver) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryApi\Common\Crafting\CraftingRecipeIngredient.cs:line 270
   at ACulinaryArtillery.DoughIngredient.FromBytes(BinaryReader reader, IWorldAccessor resolver)
   at ACulinaryArtillery.DoughRecipe.FromBytes(BinaryReader reader, IWorldAccessor resolver)
   at ACulinaryArtillery.RecipeUploadSystem.OnServerMessage(RecipeUpload networkMessage)
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkChannel.cs:line 73
   at Vintagestory.Client.NoObf.NetworkChannel.OnPacket(Packet_CustomPacket p) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkChannel.cs:line 27
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkAPI.cs:line 106
   at Vintagestory.Client.NoObf.NetworkAPI.HandleChannelsPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\API\NetworkAPI.cs:line 89
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 73
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 300
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientProgram.cs:line 127
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game-net7\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/8/2023 3:00:11 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1880357656339671929, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 638f99ee
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6c16008d-88cc-45cf-9348-d5c6fa1be625.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a1bc3ddf-2956-417e-8775-d9d11aa84261.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9c7a83ee-6255-46d0-bd1a-2c1b0124b4d6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d01b906d-86a1-4e4d-ab92-752acfbe9aef.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e7b5a166-8e46-40f5-9ebb-8660e1f07e2d.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_429d1884e4154ce84ac24791dbb411b784966a1e_a47ecedf_a42f7568-be78-41c5-a965-5147beb7b858

Analysis symbol: 
Rechecking for solution: 0
Report Id: a5cf1a58-10d4-4e71-b7f2-03f959710b95
Report Status: 268566528
Hashed bucket: 0e6a3f4f1527bf7a2a185f536ccfeb79
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/8/2023 3:00:08 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.6.0, time stamp: 0x638f99ee
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x11a4
Faulting application start time: 0x0x1d9b1dc90614be6
Faulting application path: C:\Users\Lantalia\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Lantalia\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a5cf1a58-10d4-4e71-b7f2-03f959710b95
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/8/2023 1:41:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1880357656339671929, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.6.0
P3: 638f99ee
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3d8e7852-20cd-4d43-aa73-2073cfb87514.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.dd49ef32-dd46-4e22-ad2d-d700fdfe29db.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d563ff14-dc72-4078-8925-1d00e0f10e36.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.db0e6f15-83b0-4bcb-9b2e-bf550e9226e5.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6b150fed-961e-4d7b-a7ea-b989e872ea61.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_429d1884e4154ce84ac24791dbb411b784966a1e_a47ecedf_32f6b4e7-bd22-417b-9a09-e0d46d5e2790

Analysis symbol: 
Rechecking for solution: 0
Report Id: bf4e3a01-ff4a-425f-a80b-62a8b5575454
Report Status: 268566528
Hashed bucket: 0e6a3f4f1527bf7a2a185f536ccfeb79
Cab Guid: 0 }

client-debug
8.7.2023 15:27:38 [Debug] Creating game window with window mode Fullscreen
...
8.7.2023 15:27:51.978 [VerboseDebug] All client-side assets loaded and patched; configs, shapes, textures and sounds are now available for loading
8.7.2023 15:27:51.983 [VerboseDebug] Handling ServerReady packet
8.7.2023 15:27:51.983 [VerboseDebug] Starting system: Core
8.7.2023 15:27:51.983 [VerboseDebug] Starting system: EntityPartitioning
8.7.2023 15:27:51.984 [VerboseDebug] Starting system: ErrorReporter
8.7.2023 15:27:51.984 [VerboseDebug] Starting system: ModSystemControlPoints
8.7.2023 15:27:51.984 [VerboseDebug] Starting system: ConfigManager
8.7.2023 15:27:51.984 [VerboseDebug] Starting system: Core
8.7.2023 15:27:51.984 [VerboseDebug] Starting system: SurvivalCoreSystem
8.7.2023 15:27:51.987 [VerboseDebug] Starting system: BullseyeSystemConfig
8.7.2023 15:27:51.987 [VerboseDebug] Starting system: ModCompatiblityUtil
8.7.2023 15:27:51.987 [VerboseDebug] Starting system: ModJsonPatchLoader
8.7.2023 15:27:51.987 [VerboseDebug] Starting system: ACulinaryArtillery
8.7.2023 15:27:51.987 [VerboseDebug] Starting system: RecipeUploadSystem
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: HarmonySetup
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterItems
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterBlocks
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterBlockEntities
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterBlockEntityBehaviors
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterBlockBehaviors
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterConfig
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterEntityBehaviors
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterEntities
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterAITasks
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterEntityRenderer
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: RegisterCollectibleBehaviors
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: Core
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: ChiselToolLoader
8.7.2023 15:27:51.990 [VerboseDebug] Starting system: EmoteMenuSystem
8.7.2023 15:27:51 [Debug] [EmoteMenu]  loaded language file: en.json
8.7.2023 15:27:51.993 [VerboseDebug] Starting system: RadialMenuSystem
8.7.2023 15:27:51.994 [VerboseDebug] Starting system: InstrumentModCommon
8.7.2023 15:27:51.994 [VerboseDebug] Starting system: InstrumentModClient
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: MannequinStandCore
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: RegisterEntities
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: RegisterConfig
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: ShowerSpawner
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: MeteorSpawner
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: RegisterItems
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: RegisterBehaviours
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: RegisterBlocks
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: RegisterBlockEntities
8.7.2023 15:27:51.999 [VerboseDebug] Starting system: PrimitiveSurvivalSystem
8.7.2023 15:27:52.010 [VerboseDebug] Starting system: SpyglassMod
8.7.2023 15:27:52.019 [VerboseDebug] Starting system: TeleporatationRunesMod
8.7.2023 15:27:52.019 [VerboseDebug] Starting system: SystemTemporalStormGear
8.7.2023 15:27:52.022 [VerboseDebug] Starting system: ModSystemDormancyStateChecker
8.7.2023 15:27:52.022 [VerboseDebug] Starting system: ModSystemItemRendererOptimizer
8.7.2023 15:27:52.022 [VerboseDebug] Starting system: FallingBlockParticlesModSystem
8.7.2023 15:27:52.022 [VerboseDebug] Starting system: CharacterExtraDialogs
8.7.2023 15:27:52.023 [VerboseDebug] Starting system: EntityNameTagRendererRegistry
8.7.2023 15:27:52.023 [VerboseDebug] Starting system: POIRegistry
8.7.2023 15:27:52.023 [VerboseDebug] Starting system: RoomRegistry
8.7.2023 15:27:52.023 [VerboseDebug] Starting system: WeatherSystemCommands
8.7.2023 15:27:52.023 [VerboseDebug] Starting system: WeatherSystemClient
8.7.2023 15:27:52.028 [VerboseDebug] Starting system: WorldMapManager
8.7.2023 15:27:52.029 [VerboseDebug] Starting system: wildcraft
8.7.2023 15:27:52.029 [VerboseDebug] Starting system: BeehiveKilnCore
8.7.2023 15:27:52.029 [VerboseDebug] Starting system: Program
8.7.2023 15:27:52.029 [VerboseDebug] Starting system: canmarket
8.7.2023 15:27:52.033 [VerboseDebug] Starting system: CarrySystem
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: Core
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: CooperativeCombatSystem
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: EFRecipes
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: FairPlayGuardianServer
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: HUDClockMod
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: SailboatMod
8.7.2023 15:27:52.036 [VerboseDebug] Starting system: PetAI
8.7.2023 15:27:52.037 [VerboseDebug] Starting system: ClayWheels
8.7.2023 15:27:52.037 [VerboseDebug] Starting system: ProspectorInfoModSystem
8.7.2023 15:27:52.049 [VerboseDebug] Starting system: ScareCrowMod
8.7.2023 15:27:52.049 [VerboseDebug] Starting system: StatusHudSystem
8.7.2023 15:27:52.064 [VerboseDebug] Starting system: OatsOven
8.7.2023 15:27:52.064 [VerboseDebug] Starting system: WorldEdit
8.7.2023 15:27:52.070 [VerboseDebug] Starting system: QuestSystem
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: ModSystemBossHealthBars
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: DebugSystem
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: UpgradeTasks
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: ModSystemDetailModeSync
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: ModSystemTiledDungeonGenerator
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: GenFromHeightmap
8.7.2023 15:27:52.071 [VerboseDebug] Starting system: GenMaps
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: MyceliumSystem
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: ModSystemSupportBeamPlacer
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: ModSystemCatchCreature
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: ModSystemGliding
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: ModSystemMeasuringRope
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: ScreenshakeToClientModSystem
8.7.2023 15:27:52.072 [VerboseDebug] Starting system: ResoArchivesSpawnConditions
8.7.2023 15:27:52.073 [VerboseDebug] Starting system: ModSystemAuction
8.7.2023 15:27:52.074 [VerboseDebug] Starting system: ModSystemBlockReinforcement
8.7.2023 15:27:52.076 [VerboseDebug] Starting system: Core
8.7.2023 15:27:52.076 [VerboseDebug] Starting system: ModSystemBoatingSound
8.7.2023 15:27:52.076 [VerboseDebug] Starting system: CharacterSystem
8.7.2023 15:27:52.077 [VerboseDebug] Starting system: MealMeshCache
8.7.2023 15:27:52.077 [VerboseDebug] Starting system: DialogueSystem
8.7.2023 15:27:52.078 [VerboseDebug] Starting system: FruitingSystem
8.7.2023 15:27:52.078 [VerboseDebug] Starting system: ModSystemHandbook
8.7.2023 15:27:52.079 [VerboseDebug] Starting system: ModSystemTutorial
8.7.2023 15:27:52.079 [VerboseDebug] Starting system: ModSystemNightVision
8.7.2023 15:27:52.079 [VerboseDebug] Starting system: ModJournal
8.7.2023 15:27:52.080 [VerboseDebug] Starting system: LiquidItemStackRenderer
8.7.2023 15:27:52.080 [VerboseDebug] Starting system: ModSystemStructureLocator
8.7.2023 15:27:52.080 [VerboseDebug] Starting system: ModLootRandomizer
8.7.2023 15:27:52.080 [VerboseDebug] Starting system: MicroBlockModelCache
8.7.2023 15:27:52.080 [VerboseDebug] Starting system: ModSystemRifts
8.7.2023 15:27:52.082 [VerboseDebug] Starting system: ModSystemRiftWeather
8.7.2023 15:27:52.083 [VerboseDebug] Starting system: ModSleeping
8.7.2023 15:27:52.084 [VerboseDebug] Starting system: TeleporterManager
8.7.2023 15:27:52.085 [VerboseDebug] Starting system: ModTemperature
8.7.2023 15:27:52.085 [VerboseDebug] Starting system: SystemTemporalStability
8.7.2023 15:27:52.085 [VerboseDebug] Starting system: TemporalStabilityEffects
8.7.2023 15:27:52.087 [VerboseDebug] Starting system: ModSystemWearableStats
8.7.2023 15:27:52.087 [VerboseDebug] Starting system: ModSystemEditableBook
8.7.2023 15:27:52.087 [VerboseDebug] Starting system: MechanicalPowerMod
8.7.2023 15:27:52.087 [VerboseDebug] Starting system: BullseyeSystemAnimatable
8.7.2023 15:27:52.088 [VerboseDebug] Starting system: BullseyeSystemClientAiming
8.7.2023 15:27:52.089 [VerboseDebug] Starting system: BullseyeSystemCore
8.7.2023 15:27:52.095 [VerboseDebug] Starting system: BullseyeSystemCoreClient
8.7.2023 15:27:52.095 [VerboseDebug] Starting system: BullseyeSystemRangedWeapon
8.7.2023 15:27:52.096 [VerboseDebug] Starting system: Cats
8.7.2023 15:27:52.096 [VerboseDebug] Starting system: ConfigSystem
8.7.2023 15:27:52.096 [VerboseDebug] Starting system: DoffAndDonSystem
8.7.2023 15:27:52.097 [VerboseDebug] Starting system: Core
8.7.2023 15:27:52.097 [VerboseDebug] Starting system: Commands
8.7.2023 15:27:52.097 [VerboseDebug] Starting system: Rifteye
8.7.2023 15:27:52.098 [VerboseDebug] Starting system: SimpleWindDirectionSystem
8.7.2023 15:27:52.098 [VerboseDebug] Starting system: Core
8.7.2023 15:27:52.098 [VerboseDebug] Starting system: StoneSlabMeshCache
8.7.2023 15:27:52.098 [VerboseDebug] Starting system: Wolftaming
8.7.2023 15:27:52.098 [VerboseDebug] Starting system: BodyHeatBarSystem
8.7.2023 15:27:52.099 [VerboseDebug] Starting system: Ticking
8.7.2023 15:27:52.099 [VerboseDebug] Starting system: TradeHandbookInfo
8.7.2023 15:27:52.099 [VerboseDebug] Starting system: XLeveling
8.7.2023 15:27:52.101 [VerboseDebug] Starting system: XEffectsSystem
8.7.2023 15:27:52.101 [VerboseDebug] Starting system: RockManager
8.7.2023 15:27:52.102 [VerboseDebug] Starting system: XSkills
8.7.2023 15:27:52.103 [VerboseDebug] Starting system: LoadColorMaps
8.7.2023 15:27:52.103 [VerboseDebug] Starting system: ClothManager
8.7.2023 15:27:52.104 [VerboseDebug] Starting system: RecipeRegistrySystem
8.7.2023 15:27:52.104 [VerboseDebug] Starting system: TraderOutfits
8.7.2023 15:27:52.104 [VerboseDebug] Starting system: XInvTweaksSystem
8.7.2023 15:27:52.120 [VerboseDebug] Starting system: LatePatcher
8.7.2023 15:27:52.120 [VerboseDebug] Starting system: FairPlayGuardianClient
8.7.2023 15:27:52.197 [VerboseDebug] Loadsounds, found 649 sounds
8.7.2023 15:27:52.197 [VerboseDebug] Sending request to join server
8.7.2023 15:27:52.250 [VerboseDebug] Startup sequence wrong, playerdata packet handled before BlocksReceivedAndLoaded; player may be null
8.7.2023 15:27:52.454 [VerboseDebug] Received world meta data

**Comment by Craluminum2413** [comment]
This error occurred in aculinaryartillery mod

**Comment by Lantalia** [comment]
Can you tell me what  Startup sequence wrong, playerdata packet handled before BlocksReceivedAndLoaded;  is from?

**Comment by Craluminum2413** [comment]
Send all logs from `\AppData\Roaming\VintagestoryData\Logs`
