### ISSUE TITLE
Vanilla 1.18.6 when you put any coal down

### ISSUE THREAD

**Issue by teknik1** [anegostudios/VintageStory-Issues#2905]
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When you put any coal on the ground it take two in the stack, but you are able to put only one . If you put only one on the ground you cant pick it up with rigth click, you have to break the block under it.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/9663048/825d76ce-3dbf-4177-a94a-e53878882524)

### How to reproduce

Just put only one coal-* on the ground

### Logs

```Log```

**Comment by RedramVS** [comment]
I cannot reproduce this in 1.19, so I'm assuming it was fixed earlier.
