### ISSUE TITLE
Offhand Torches & effect not rendering on game load

### ISSUE THREAD

**Issue by BryanBoru** [anegostudios/VintageStory-Issues#291]
**Version:** 1.9.3

**Steps to Reproduction:**
Load into a game where you had a torch in avatar's offhand
Move cursor to 'empty' offhand and click to reveal invisible item in offhand

**Expected behavior:**
Item 

**Current behavior:**
Loading into game and torch effect in offhand is lost and torch is invisible in hand.
taking the torch out of off-hand and replacing it returns the effect and visual.
**Sample Mp4:** https://i.gyazo.com/df568127d92f9ebf2ceba0cea21dcb97.mp4

Possibly related to #281

**Comment by tyronx** [comment]
Excellent bug report, but already fixed for the upcoming v1.9.4. Looks like I forgot to close #281. Thanks anyway!
