### ISSUE TITLE
не запускается, вылазит ошибка

### ISSUE THREAD

**Issue by emr4wsr** [anegostudios/VintageStory-Issues#2914]
### Game Version

1.18.60rc2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

при запуске вылазит такая ошибка

Running on 32 bit Windows with 8 GB RAM 
Game Version: v1.18.6-rc.2 (Unstable) by OverF1X  
13.07.2023 0:38:58: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_explicit_attrib_location which is required to start the game
   в Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() в VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 202
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.Client.ClientProgram.<>c__DisplayClass16_0.<.ctor>b__0()
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 93

### How to reproduce

Скачать приложение , после чего запустил вылез черный экран и тутже свернулся, после чего вылезло окно с ошибкой

### Screenshots

-

### Logs

-

**Comment by emr4wsr** [comment]
на 1.15.10 тоже самое

**Comment by Craluminum2413** [comment]
Pirated versions of the game are not supported, also they are extremely unpredictable due to a lot of changes made by author of a crack
