### ISSUE TITLE
Busted crock pot?

### ISSUE THREAD

**Issue by MisterCakers** [anegostudios/VintageStory-Issues#2916]
### Game Version

v1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

After finishing up my crock pot of hefty meat stew, I went to make some more. After placing the crock pot unto the fire I was suprised to see nothing happen, the pot wouldnt open up. I tried a different crock pot, also didn't work. I tried creating a new world and it still wouldn't work. Though when I tried a crucible that worked and "opened up" when I placed it on the fire.
To go into a little more detail of stuff leading up to it: Before I was going to make more stew I was eating stew out of a sealed crock pot, not sure if its relevent. Then just before placing the crock pot into the fire I had relit my torch.

### Screenshots

![20230713224331_1](https://github.com/anegostudios/VintageStory-Issues/assets/139532015/bd992592-82c5-4c50-96db-67d76d30f76b)
![20230713231006_1](https://github.com/anegostudios/VintageStory-Issues/assets/139532015/56813e78-9ea7-41cd-bdbd-690658b3464d)
![20230713231107_1](https://github.com/anegostudios/VintageStory-Issues/assets/139532015/f1a94067-56c3-497d-b822-ef2c17abc467)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12046841/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12046843/server-main.txt)

**Comment by Craluminum2413** [comment]
Crock is for storing food by using in-world interactions, it doesn't have visual slots, you need cooking pot for this

**Comment by MisterCakers** [comment]
Im a idiot. In my defense It was late when I wrote this -_-.
