### ISSUE TITLE
Resonance Archive not displaying on map after reading map.

### ISSUE THREAD

**Issue by ahunter2345** [anegostudios/VintageStory-Issues#2917]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

In the screen shot provided, you can see that I have the map in my hand, read it, and it prompts no location found. Is this a bug for my game?

### Screenshots

![Resonance Archive Map](https://github.com/anegostudios/VintageStory-Issues/assets/139559434/7c928f1a-ed41-4e41-9474-ed5b2c5a056a)

### Logs

```Log```

**Comment by pingouyn** [comment]
I have the same issue in 1.19.3 with a game started in 1.19.0.rc4 to rc6 (somewhere there I believe).
Purchased 2 maps from 2 different Treasure Hunters, the first one lead me to a treasure, the second map shows "no location found" and no marker is added to the map.

**Comment by Blacksmith-C** [comment]
Same issue. I am on version 1.19.8 on Windows, and the world was generated on this version. 
![2024-12-22_20-23-56](https://github.com/user-attachments/assets/70552926-e7c5-41b4-b493-f53c9d2ab0d0)
