### ISSUE TITLE
Add API method to render WorldInteraction hint

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#293]
I want to render a `WorldInteraction` hint somewhere in the world or on a HUD. Having to do this manually without using behaviors is quite involved, so it would be nice to have an API method to render a custom hint directly.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
