### ISSUE TITLE
Bees from beenades attack inorganic entities such as arrows

### ISSUE THREAD

**Issue by Guimoute** [anegostudios/VintageStory-Issues#2931]
### Game Version

1.18.6

### Platform

Windows

### Modded

Yes, but my mods don't affect bees. 

### SP/MP

Singleplayer

### Description

Bees attack arrows. 

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/51537797/5579967c-5449-4478-a1a1-434cd3eadff1

### Logs

```Log```

**Comment by Guimoute** [comment]
They also attack rafts.

**Comment by tyronx** [comment]
I mean, to be fair, those are some very offensive arrows right there 😄

**Comment by Guimoute** [comment]
The tips were dipped in honey :D

**Comment by Bumber64** [comment]
They attack armor stands, damaging the displayed armor.

**Comment by RedramVS** [comment]
It's been made so they don't attack rafts or armor stands.  They still attack arrows though, and I'm not sure why...
