### ISSUE TITLE
.reload textures = xray with & without mods: in sp & mp

### ISSUE THREAD

**Issue by Diometus** [anegostudios/VintageStory-Issues#2935]
### Game Version

v1.18.6 .NET 7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

1. I have tried this without mods, on the vanilla version of the game while playing singleplayer.

2. I have also tried this with mods and playing online in multiplayer. 

3. The result is the same which tells me this is with the client itself and is not being modified by a mod to react like this.

4. Watch my video completely as that should be all you need.

### How to reproduce

1. type ".reload textures"
2. interact with an object: place a block or open a door.
3. view outcome

### Screenshots

Video:  [https://youtu.be/Lg355HZNOjw](https://youtu.be/Lg355HZNOjw)

### Logs

[https://gist.github.com/Diometus/ce133af09dde18858bbaf54bf4125e93](https://gist.github.com/Diometus/ce133af09dde18858bbaf54bf4125e93)

Logs included in the above link: client-main.txt & server-main.txt

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
