### ISSUE TITLE
Different names of -redmarble

### ISSUE THREAD

**Issue by Erfarenort** [anegostudios/VintageStory-Issues#2937]
### Game Version

v1.18.6

### Description

Blocks and items of `-redmarble` have different names: pink cream, pink and red.

### Screenshots

![redmarble](https://github.com/anegostudios/VintageStory-Issues/assets/138893196/5436ef7e-d84b-47c4-851e-b19e8c849a29)

**Comment by zsuatem** [comment]
☝️

![image-3_1.jpg](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/7b4d1899-4891-4093-b6dd-8224b6d0a082)
