### ISSUE TITLE
Game crashes when pressing H on a wooden bucket

### ISSUE THREAD

**Issue by bennyb1971** [anegostudios/VintageStory-Issues#294]
Hi,

tried this several times, but the game crashes (playing on a server) when pressing H on a wooden bucket.

Crashlog

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/3178738/client-crash.txt)

**Comment by tyronx** [comment]
this is fixed in the upcoming v1.9.4, thanks for reporting
