### ISSUE TITLE
Any type of dough not creating

### ISSUE THREAD

**Issue by GoodCrafter** [anegostudios/VintageStory-Issues#2941]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Dough not crafting via grid, all types of flour not work.

### How to reproduce

1. In crafting grid put 1 of any type flour and container with 1l of water

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/95700526/799b4115-e08a-4727-a845-ba40d24f2c79)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/95700526/02f6eafa-85ef-4551-8ab6-f53acfd0b057)

### Logs

```Log```

**Comment by Aerin-of-the-Toast** [comment]
did you make sure it's freshwater and not saltwater

**Comment by GoodCrafter** [comment]
> did you make sure it's freshwater and not saltwater

I didn't even know it existed yet, man i feel stupid right now, sorry for wasting your time D:
