### ISSUE TITLE
Chain Helmet voids facial hair

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2944]
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

See below. 
With beard is Iron Brigandine: 
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/e7475ae4-7356-4d04-9da2-34f9e0fbe9ae)

Without beard is Iron Chain:
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/03791f35-6975-4911-9367-8dd7e3f8c884)

**Comment by Guimoute** [comment]
I will edit gradually as I find more items.

**Hiding the beard despite being open**:
- all gambeson helms
- peasant scarf
- shepherd cowl
- hunter cape
- stained leather poncho
- fur coat
- reindeer herder fur coat (also hides the ponytail)

**Doesn't properly hide the ponytail:**
- straw hat
- bamboo hat

**Z-fighting:**
- iron plate helm
- blackguard helm

**Comment by Guimoute** [comment]
There is good progress on this in 1.19.0 preview10, thanks Redram :) 

I haven't tested every case but every case I've tested was fixed.

**Comment by RedramVS** [comment]
No problem @Guimoute Feel free to ping me if you do find other issues.  I'm considering perhaps sub-dividing hair a bit more to provide more fine-grained options, in the future.  But for now it should be much better than it was, at least.

**Comment by Craluminum2413** [comment]
I guess it is fixed in 1.20 since all clothes are 3D now
