### ISSUE TITLE
Space in windows username causing error opening mod folder with .NET7 version

### ISSUE THREAD

**Issue by FatherCrosspatch** [anegostudios/VintageStory-Issues#2949]
### Game Version

1.18.6-rc.1 .NET7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

A windows username with a space will error when opening mod folder as it fails to follow the correct path. 

Windows error will report the path only  up to the space. "Cannot find C:\Users\Foo" make sure you typed the name correctly and then try again. 

### How to reproduce

Can be replicated by creating a windows user with a space (Foo Bar) and attempting to open the mod folder from within the GUI.

### Logs

```Log```

**Comment by BlueStoneCreepr** [comment]
Same issue, may be fixable by putting quotes.
