### ISSUE TITLE
"Foam and shiny effect" graphics setting un-renders water. [v1.18.7 (stable)]

### ISSUE THREAD

**Issue by CaveManIsMan** [anegostudios/VintageStory-Issues#2966]
### Game Version

v1.18.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

"Foam and shiny effect" graphics setting un-renders water. Issue persists after relaunch of game. Issue was not previously present in update v1.18.6.

### How to reproduce

Switch on and off "Foam and shiny effects" setting.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/140855964/24665dcd-6f8c-447a-bdb4-4ca31b53be14)
^Setting turned on
![image](https://github.com/anegostudios/VintageStory-Issues/assets/140855964/77811a03-abb7-433d-9b9d-72d1e745073d)
^Setting turned off

### Logs

```Log```

**Comment by Th3Dilli** [comment]
can you share some system information, hardware and graphics driver version you have?

since I wasn't able to reproduce it on an nvidia 2080 TI with driver version 535

**Comment by CaveManIsMan** [comment]
I have a RX 5600 XT driver version 23.5.2. May be an AMD only issue? This only started to occur on the 1.18.7 version and was not an issue before.

**Comment by v4ltages** [comment]
> I have a RX 5600 XT driver version 23.5.2. May be an AMD only issue? This only started to occur on the 1.18.7 version and was not an issue before.

I have experienced the same issue on my Radeon RX 5600 XT card so this is likely not isolated.

**Comment by Th3Dilli** [comment]
did you test again with 1.18.6 to verify that is just the game causing this or could it be anew driver version?

**Comment by v4ltages** [comment]
@CaveManIsMan I have a suspicion it may be a combination shader quality + foamy effect setting as using the medium quality preset causes the water to not render. Using the high quality preset the water renders correctly.

**Comment by CaveManIsMan** [comment]
> @CaveManIsMan I have a suspicion it may be a combination shader quality + foamy effect setting as using the medium quality preset causes the water to not render. Using the high quality preset the water renders correctly. Example is if i use the high quality preset plus turning foamy effect off and on does nothing at that quality setting.

I played around a bit with the settings after reading this and discovered that the "foam and shiny" effect setting is tied to the shadow quality which has to be at least "low quality" to render the water. 
![image](https://github.com/anegostudios/VintageStory-Issues/assets/140855964/b4a577da-f914-4119-ada0-8ec66f04c50c)
^Shadows on "off"
![image](https://github.com/anegostudios/VintageStory-Issues/assets/140855964/1d967812-9a78-4694-8eac-727e57065fb9)
^Shadows on "low quality"

**Comment by v4ltages** [comment]
I've realised that perhaps since the shader quality is set so low quality. It is likely it is missing the capabilities to render the foamy shiny effect. The foamy and shinny effect button should be disabled/unselected as a option if the shader quality is set to the absolute lowest.

**Comment by tyronx** [comment]
with the water not visible, could you also please upload your client-main.txt. Perhaps some shader fails to compile.

**Comment by tyronx** [comment]
actually, i'll just assume this fixes it and push out 1.18.8 net 7 stable
