### ISSUE TITLE
Rain does not moisturize garden soil

### ISSUE THREAD

**Issue by vintage-seraph** [anegostudios/VintageStory-Issues#2973]
### Game Version

V1.18.8-RC-1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Continuous rain does not keep soil wet.  I noticed this in 1.18.6 net-7 version too.  I have a garden which after 5 days of continuous rain was losing moisture.  See screenshot.

After watering every single block to 100% it seemed to hold it a little longer.  If I left any block less than 100% watered, it seemed to dry out faster.

### Screenshots

![2023-07-31_16-34-53](https://github.com/anegostudios/VintageStory-Issues/assets/117089510/b227a2c7-c5c5-443d-ae4c-5fd966410d7f)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
should be fixed in the upcoming 1.19
