### ISSUE TITLE
Crashes when looking at a mob/creature (modded)

### ISSUE THREAD

**Issue by TobyGentlemane** [anegostudios/VintageStory-Issues#2974]
### Game Version

1.18.7 (stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

So fast I look at a mob the game crashes, playing modded and trying to understand which mod it is

### How to reproduce

Get close to a mob, looking at it, crashes

### Logs

```Log```Running on 64 bit Windows with 32 GB RAM 
EMTK Version: 2.0.9
Game Version: v1.18.7 (Stable)
2023-08-01 14:56:49: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.12, ancienttools@1.5.7, betterruins@0.2.1, cloudy3dx@1.0.9, samsdungeonsremastered@1.0.0, eldritchmonsters@2.3.8, fancysky@1.0.6, fantasycreatures@0.5.3, FlexibleTools@2.1.0, capreolinae@1.0.3, pantherinae@1.0.6, furniturelibrary@1.0.9, medieval@2.01.26, meteoricexpansion@1.2.4, bgn_moreclasses@1.0.2, moredrifterloot@1.5.4, NoFallAnimation@1.1.2, optimizedleathertwo@2.0.0, optimizedpreservation@1.0.0, OresAPlenty@3.1.0, patched@1.0.1, TA_plainsandvalleys@1.0.3, primitivesurvival@3.2.6, prospectingplusplus@1.2.0, dzsalvageplus@1.0.1, samshumcreat@0.0.2, sca@1.0.0, simpleelevator@1.3.0, tprunes@1.0.8, game@1.18.7, weaponpackalphaunoff@1.4.0, wildcrafttrees@1.2.4, wildcraft@1.6.6, abcsreborn@0.1.1, alchemy@1.6.15, altgliderimplementation@1.1.2, blacksmithgloves@1.0.1, bodyheatbar@1.0.1, canbeignited@1.1.0, canjewelry@0.1.10, carryon@1.3.0, commonlib@2.2.0, crateful@1.0.3, electricity@0.0.10, fishing@1.1.5, glidervar@1.1.1, sailboat@1.1.0, lavoisier@1.3.0, medievalexpansion@3.9.3, medievalmap@1.3.3, morepiles@1.4.3, movelikekaji@0.0.1, outlawmodcan@1.0.5, paxel@1.3.2, petai@1.7.10, claywheel@1.1.0, simplestep@1.0.5, sts@1.0.4, temporalstormtimer@1.1.0, th3dungeon@0.1.2, usefulstuff17@1.1.6, creative@1.18.7, vsquest@0.4.1, survival@1.18.7, vsvillage@0.7.3, wildfarmingrevival@1.1.0, woodenfortifications@0.0.4, xlib@0.7.4, xmelee@0.0.11, metalrecovery@0.1.19-pre.1, awearablelight@1.0.8, bullseye@2.5.0-rc.1, cats@1.7.0, chemistrylib@1.1.5, cavebeacons@1.0.7, magicmushrooms@1.0.1, tradercamps@1.0.6, em@2.2.2, foxtaming@1.2.0, helvehammerext@1.5.1, playercorpse@1.8.0, tpnet@1.13.1, wolftaming@1.7.3, xinvtweaks@1.5.6, xskills@0.7.5, bricklayers@2.2.0, kosfire@1.1.3, kos-goldamalgam@1.0.0, kosphotography@1.3.2, moreroads@1.5.1, wildcraftxskillspatch@0.2.0
Involved Harmony IDs: com.grifthegnome.outlawmod.causeofdeath, com.grifthegnome.expandedaitasks.aitaskpatches
System.MissingMethodException: Metoden hittades inte: Boolean Vintagestory.API.Config.Lang.HasTranslation(System.String, Boolean).
   vid OutlawMod.BehaviorHarvestableOverride.IgnoreAndOverrideGetInfoText(EntityBehaviorHarvestable __instance, StringBuilder infotext)
   vid Vintagestory.GameContent.EntityBehaviorHarvestable.GetInfoText_Patch2(EntityBehaviorHarvestable this, StringBuilder infotext)
   vid Vintagestory.API.Common.Entities.Entity.GetInfoText() i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryApi\Common\Entity\Entity.cs:rad 1827
   vid Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:rad 66
   vid Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.EntityInView() i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:rad 204
   vid Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Common\EventManager.cs:rad 85
   vid Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientMain.cs:rad 813
   vid Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientMain.cs:rad 712
   vid Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:rad 165
   vid Vintagestory.Client.ScreenManager.Render_Patch0(ScreenManager this, Single dt)
   vid Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ScreenManager.cs:rad 627
   vid Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:rad 126
   vid System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   vid OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) i C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:rad 479
   vid OpenTK.GameWindow.DispatchRenderFrame() i C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:rad 454
   vid OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) i C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:rad 375
   vid Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   vid Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) i C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:rad 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-07-09 22:43:27, Site = , Source = Application Error, Message = Felet uppstod i programmet med namn: Vintagestory.exe, version 1.18.6.0, tidsstämpel 0x649be5a4
, felet uppstod i modulen med namn: unknown, version 0.0.0.0, tidsstämpel 0x00000000
Undantagskod: 0xc0000005
Felförskjutning: 0x00007ffa3a818462
Process-ID: 0x4c9c
Programmets starttid: 0x01d9b2a506d79a50
Sökväg till program: F:\Vintagestory\Vintagestory.exe
Sökväg till modul: unknown
Rapport-ID: 3c2f8f28-d33f-4163-8a74-cd0938b48620
Fullständigt namn på felaktigt paket: 
Program-ID relativt till felaktigt paket:  }
--------------
{ TimeGenerated = 2023-07-09 22:43:27, Site = , Source = .NET Runtime, Message = Tillämpningsprogram: Vintagestory.exe
Framework-version: v4.0.30319
Beskrivning: Processen avslutades på grund av ett ohanterat undantag.
Undantagsinformation: System.NullReferenceException
   vid Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   vid Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   vid Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes()
   vid Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1()
   vid System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   vid System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   vid System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   vid System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 2023-07-02 21:37:59, Site = , Source = Application Hang, Message = Programmet Vintagestory.exe, version 1.18.6.0 avslutades eftersom det slutade samverka med Windows. Ytterligare information om problemet kan finnas i problemhistoriken i Säkerhet och underhåll på Kontrollpanelen.

Process-ID: 81e0

Starttid: 01d9ad1a86c8c68c

Avslutningstid: 33

Programsökväg: F:\Vintagestory\Vintagestory.exe

Rapport-ID: ba9daba1-8415-42f6-a3b0-9c2d0e350e00

Fullständigt namn på felaktigt paket: 

Program-ID relativt till felaktigt paket: 

Typ av låsning: Unknown
 }

**Comment by Craluminum2413** [comment]
It is a bug in the mod
