### ISSUE TITLE
Food Spoiling Faster in Cellar than in Character Inventory

### ISSUE THREAD

**Issue by jtmorphew** [anegostudios/VintageStory-Issues#2977]
### Game Version

1.18.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Food spoilage rates are faster in my cellar than in my inventory.  The rate seems to fluctuate based on outdoor temps, which is directly related to the season.  I think that part makes sense but right now my shelves are showing a spoilage rate of 1.3 for general foods so they actually last longer in my character inventory, which doesn't make any sense.  

The cellar is located inside my house on the main level.  The room is completely interior (no windows) and the walls and floor and ceiling is made out of stone bricks, so I can't see how that is the problem.  

### Screenshots

![2023-08-02_09-28-24](https://github.com/anegostudios/VintageStory-Issues/assets/110646445/445c796a-4850-4c67-a2d0-ec9d4a000a2c)
![2023-08-02_09-28-28](https://github.com/anegostudios/VintageStory-Issues/assets/110646445/ae2f39e3-3897-46a1-8f48-44c09f2a8e12)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@jtmorphew What door you have used?

**Comment by jtmorphew** [comment]
I'm using the Sleek Door (Maple) that's sold by a trader.

**Comment by jtmorphew** [comment]
I just switched out to a solid door (oak) and this dropped the spoil rate to normal levels and fixed the problem.  Seems to be a bug with the sleek door.

**Comment by Craluminum2413** [comment]
Sleek is not airtight

**Comment by jtmorphew** [comment]
I suppose that makes sense but is disappointing since that door looks so much nicer for a pantry.  The ability to add glass panes to it would be a nice addition to counter that.  Thanks for the help!
