### ISSUE TITLE
Snow Texture Bug on Certain Stairs and Slabs

### ISSUE THREAD

**Issue by n4sr** [anegostudios/VintageStory-Issues#2980]
### Game Version

v1.18.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

A potential regression with #911 

The issue is the same as listed in the one above. Currently observed with stairs and sideways slabs.

Notice in screenshot 1 the texture of the first 4 pixels on a block being repeated where a snow texture is supposed to be.

### How to reproduce

1. Place Stair or Sideways Slab
2. Wait for it to snow
3. Observe the block

### Screenshots

![2023-08-02_05-25-33-2](https://github.com/anegostudios/VintageStory-Issues/assets/54733427/5e5ca43f-c180-45e7-a6d1-16cc2595a912)

### Logs

```Log```

**Comment by RedramVS** [comment]
@n4sr I could not reproduce this.  Do you think it's still an issue, or was it fixed at some point in the last 4 months?

**Comment by n4sr** [comment]
@RedramVS I have not played the game in a couple months, so it is possible it was fixed. I have not kept up on the change logs either.

If this can no longer be reproduced, then feel free to close it.
