### ISSUE TITLE
Prospecting Pick not registering start location

### ISSUE THREAD

**Issue by Leviathing** [anegostudios/VintageStory-Issues#2981]
### Game Version

v1.18.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When using the prospecting pick I get the message "Ok need 2 more samples" then when I dig around the initial block multiple times, it still says I need two more samples. After digging 6 blocks, it then says 1 sample needed then another 6 gives me the result. So 12 blocks total. I'm assuming I should only need to dig 3 blocks? 

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/141412321/c7fabf0b-e13f-4276-8ba7-917fd087138c)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
You need to dig 4 blocks away from any sample
