### ISSUE TITLE
File location mismatch in Linux

### ISSUE THREAD

**Issue by Specc-git** [anegostudios/VintageStory-Issues#2982]
### Game Version

1.18.8-rc.1

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Version 1.18.8-rc.1 seems to read from .config/VintagestoryData/ but all mods have to be placed in .config/VintagestoryDataNet7/Mods to be recognized by the game.

### How to reproduce

Update to 1.18.8-rc.1, Open mod folder from in game and it leads to VintagestoryData/Mods.

### Logs

```Log```

**Comment by Th3Dilli** [comment]
did you copy your clientsettings.json from `VintagestoryDataNet7` to `VintagestoryData`?

you should be able to fix this by changing it in your `VintagestoryData/clientsettings.json` where it says `modpaths`

this should not happen under _normal_ circumstances

**Comment by Specc-git** [comment]
I have been going to and from the net7 test, to the stable net 4 to the new unstable, and just copied my files so that would explain why. Marking as solved.
