### ISSUE TITLE
Crash when trying to join a server

### ISSUE THREAD

**Issue by Ancestra** [anegostudios/VintageStory-Issues#2983]
### Game Version

v1.18.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Crash when I install the game and try to join a multiplayer server

### How to reproduce

Just join a server [EN] Rogue house server

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.7 (Stable)
05/08/2023 01:03:11: Critical error occurred
Loaded Mods: acorns@0.5.2, ancienttools@1.5.7, chiseltools@1.8.4, instruments@1.2.2, mannequinstand@1.0.1, meteoricexpansion@1.2.4, millwright@1.0.7, leadroof@1.3.4, primitivesurvival@3.2.7, spyglass@0.4.5, tprunes@1.0.8, wildcraft@1.6.6
System.Exception: Don't know how to instantiate item of class 'ItemMagicWand' did you forget to register a mapping?
   à Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) dans C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Common\ClassRegistry.cs:ligne 273
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) dans C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Common\Network\ItemTypeNet.cs:ligne 19
   à Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) dans C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Startup.cs:ligne 580
   à Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() dans C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Startup.cs:ligne 392
   à Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() dans C:\Users\Tyron\Documents\vintagestory\game-net4\VintagestoryLib\Client\Systems\Startup.cs:ligne 335
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05/08/2023 01:03:12, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.18.7.0, horodatage : 0x64bd7a7d
Nom du module défaillant : unknown, version : 0.0.0.0, horodatage : 0x00000000
Code d’exception : 0x00000000
Décalage d’erreur : 0x0000000000000000
ID du processus défaillant : 0x7358
Heure de début de l’application défaillante : 0x01d9c727c0adcbca
Chemin d’accès de l’application défaillante : E:\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: unknown
ID de rapport : 4fa82842-d8a9-4eed-b7e9-880710dbc6d1
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 05/08/2023 01:03:11, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   à Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   à Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes()
   à Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 05/08/2023 00:57:32, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à Vintagestory.Common.ClassRegistry.CreateItem(System.String)
   à Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   à Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(System.Collections.Generic.List`1<Vintagestory.API.Common.Item>, Int32)
   à Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes()
   à Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment]
Disable mods and try again

**Comment by Ancestra** [comment]
I disabled all the mod, uninstalled and reinstalled the game.
I deleted the Roaming file in Windows as I played for the first time but still crashing.

**Comment by Ancestra** [comment]
It's now working. The problem was about the version of the client used.
I used the 1.18.7 and the server used the 1.18.8-rc.1

**Comment by Craluminum2413** [comment]
Incorrect install or most likely bug in some mod
