### ISSUE TITLE
Graphics lost

### ISSUE THREAD

**Issue by gothchef** [anegostudios/VintageStory-Issues#2984]
### Platform

None

### Modded

None

### SP/MP

None

### Description

While playing, the game froze and crashed. I restarted the computer, removed the mods, and tried to restart. The graphic forms loaded up, but no detail (everything was an off-white color.) I tried the repair file feature and the chunks loaded slowly, so I flew around reloading the graphics. I saved and quit after that. The next time I loaded the game all that loaded was sky (see image.) I quit and turned the graphics settings to the lowest value and tried to load again, but got the same response.
I've tried to open the game a few times; sometimes I can see ore nodes in the ground and my armor stand white globs.

I was able to create a new world without any problem. 

I tried to upload the save file, but it would not let me. I'll be glad to share it if that helps. 

### How to reproduce

Pretty much just load the game.
I also tried uninstalling and reinstalling Vintage Story, but that didn't change anything.

### Screenshots

![VS load](https://github.com/anegostudios/VintageStory-Issues/assets/135153228/4b8fa528-d000-4d82-9dd5-e94c6592e0bf)

### Logs

```Log```
Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/4/2023 6:36:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2069801944697539103, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.7.0
P3: 64bd7a7d
P4: 365f
P5: 67241984
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\socia\AppData\Local\Temp\WER.4319e43c-5bdb-4b60-8ab4-49721d38c21f.tmp.version.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f4ab9cb7-fe85-4de3-927e-f4f1d9a4f0d5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fd7ceb4c-17e0-4863-9f65-efa12acc29da.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.809be802-97a2-40b9-ac38-b2215219f36b.tmp.txt
\\?\C:\Users\socia\AppData\Local\Temp\WER.4c723d7b-0a30-450b-943d-0ddacd31b8d1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9228a1da-37da-45c8-9355-88cee86e3ec6.tmp.xml
WERGenerationLog.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_Vintagestory.exe_fa13bfc5f62cdb2d9c4cdc7bc6e4149b60b2b6_229aabcc_c20cb792-4e98-486d-b604-28f3ba44e742

Analysis symbol: 
Rechecking for solution: 0
Report Id: 161a1479-061c-41f4-8db0-35d18859af7d
Report Status: 268435456
Hashed bucket: b02a266f957959806cb969e7051c0a1f
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/4/2023 6:36:23 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.7.0
P3: 64bd7a7d
P4: 365f
P5: 67241984
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\socia\AppData\Local\Temp\WER.4319e43c-5bdb-4b60-8ab4-49721d38c21f.tmp.version.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f4ab9cb7-fe85-4de3-927e-f4f1d9a4f0d5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fd7ceb4c-17e0-4863-9f65-efa12acc29da.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.809be802-97a2-40b9-ac38-b2215219f36b.tmp.txt
\\?\C:\Users\socia\AppData\Local\Temp\WER.4c723d7b-0a30-450b-943d-0ddacd31b8d1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9228a1da-37da-45c8-9355-88cee86e3ec6.tmp.xml
WERGenerationLog.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_Vintagestory.exe_fa13bfc5f62cdb2d9c4cdc7bc6e4149b60b2b6_229aabcc_cab_c20cb792-4e98-486d-b604-28f3ba44e742

Analysis symbol: 
Rechecking for solution: 0
Report Id: 161a1479-061c-41f4-8db0-35d18859af7d
Report Status: 5
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/4/2023 6:26:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1946851045495480100, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.7.0
P3: 64bd7a7d
P4: f254
P5: 67241984
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\socia\AppData\Local\Temp\WER.7c3836a1-d32f-4b4c-a7e3-4ddae060b7a1.tmp.version.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3daee445-f48e-4aa7-a366-12a24698daa2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9ca75cb4-5b59-4df1-bdc2-a216f9b31b85.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.63422dd3-9e38-4cfc-9a6b-642bc23c3c89.tmp.txt
\\?\C:\Users\socia\AppData\Local\Temp\WER.1bbc022c-ffc0-408b-847b-3d1e132bde48.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0facfe4b-b1f7-4d1a-9f16-599f7d7f5aea.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_Vintagestory.exe_8a732952b2cc8d4d0923ea674a4b0f5205a45dc_229aabcc_cab_2c4eb8b1-d30a-43af-8828-66fbcef22994\minidump.mdmp
WERGenerationLog.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_Vintagestory.exe_8a732952b2cc8d4d0923ea674a4b0f5205a45dc_229aabcc_2c4eb8b1-d30a-43af-8828-66fbcef22994

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0f5ab46d-04b4-49d5-a22b-723054b1f41e
Report Status: 268435456
Hashed bucket: c36017879ae1cf900b049ab6055b1f24
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
Could you send all logs from VintagestoryDara/Logs?

**Comment by gothchef** [comment]
All of the current logs from the vintagestorydata folder are attached. I was able to play using the workaround described below. I did not think to save a copy of the logs from when the problem first occurred.

The problem still occurs if I load the game immediately from the Home screen. If I load another saved game that I just created, run around enough to load a few new chunks, and then save and quit that game first before loading the game that was having issues, the saved game with issues opens correctly. I discovered this by accident but tested it a few times. When I start with the big game first it only loads sky or shapes. If I load the new game first and move around enough to load new map data, the big game would open correctly after saving and closing the new world. This has to be done in the same session (once I close the VS program I will have to do this process again to get the saved game to load correctly.)

I have played VS nearly 400 hours on this machine before this issue occurred.

The save game file size is 1.64 GB. I don't know if that is relevant or not.

James






________________________________

**Comment by gothchef** [comment]
After that description of a "workaround" in my previous message I went to log in and play today. I followed the whole process I explained in my previous email, but it did not work. I attached the new log files, along with a new screenshot of what the game looked like after loading.

James
________________________________

**Comment by gothchef** [comment]
Any update?
________________________________

**Comment by gothchef** [comment]
Any updates on a cause for the funky graphics? I started a new world with the same seed, but am a bit frustrated to have lost a few winter's worth of underground tunneling that connected bases.

James
________________________________

**Comment by Craluminum2413** [comment]
I close it as hardware issue, to me it looks like GPU artifacts after everything you a tried to return it back to normal
