### ISSUE TITLE
Excessive and random moisture drop on both more and less irrigated crops in 1.18.8

### ISSUE THREAD

**Issue by Ulvra** [anegostudios/VintageStory-Issues#2996]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Opened this world just after updating to 1.18.8 and quickly noticed weird behaviour. While I previously (in 1.18.7) was able to water my garden in the morning and evening to keep everything moistened, now randomly plants and soil will rapidly plummit in moisture level. The attached picture shows an example, where I'd literally just watered the whole field, making sure everything showed 100%, then brought in a couple harvested crops into my cellar (just next door), but when I came back out again, this and several other crops/plots of soil had dropped significantly.

Affected plants seem completely random, happening to areas both next to, close to and far from water, but with how quickly it happens, it can quickly drop most of a garden to barely any moisture.

### How to reproduce

1. Water plants to 100% moisture level within varied distance of water source blocks
2. Go about your business for a short duration (1-2 ingame hours or more)
3. Return and check plants
4. Possibly repeat 2 and 3 in intervals

May be related to version migrated plants/soil, from 1.18.7 to 1.18.8.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/141845024/4df46e68-e307-409b-b417-35f5355fd064)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12303642/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12303643/server-main.txt)

**Comment by PaladinWaffles** [comment]
Same. It also happens when you reload a world, it drops from 100 to low 70s

**Comment by m-from-space** [comment]
I can confirm this behavior which didn't seem to happen before or I did not realize it. Some blocks drop to 25% for example, while blocks around it are still good.

**Comment by PaladinWaffles** [comment]
It also seems that the bug affects all farmland, not just the ones already there. I think it messed with the world itself.

**Comment by Amzd** [comment]
updateMoisture is called with hours instead of days here; https://github.com/anegostudios/vssurvivalmod/blame/d1fed2053587ad4bec1fe4a6771d42d5cb29e760/BlockEntity/BEFarmland.cs#L391

BetterMoisture mod prevents this issue https://mods.vintagestory.at/bettermoisture

**Comment by Craluminum2413** [comment]
This most likely fixes it
```
Tweak: Farmland buff - now dries out after 96 hours, instead of 48
```
