### ISSUE TITLE
Can't run server on Linux Server

### ISSUE THREAD

**Issue by cekefun** [anegostudios/VintageStory-Issues#2997]
### Game Version

v1.18.8

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

Hello, I just downloaded the zip file for v 1.18.8 on an Ubuntu server and I can't seem to start the server.
1.18.7 was working fine.

The main issue looks to be the .dll file. My server seems like it can't run this even though I followed the steps on https://wiki.vintagestory.at/index.php/Setting_up_a_Multiplayer_Server 

When I manually try the same command as the server.sh file, I get the following error: 
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'VintagestoryServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Aborted (core dumped)
```
Thanks!

### How to reproduce

1. Download the 1.18.8 zip
2. Extract the zip
3. Make the server.sh runnable using chmod +x
4. Run server.sh (fails)
5. Run dotnet VintagestoryServer.dll --dataPath /var/vintagestory/data (fails with the error)

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/14937306/b31074e4-057f-4f6c-8b8c-5f7c28311e03)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/14937306/b0a30c3e-fe32-4597-9bfa-1d4753a7b012)

### Logs

```Log```

**Comment by Nyuhnyash** [comment]
Сouldn't reproduce on Ubuntu Server 22.04.2 with Microsoft.NETCore.App 7.0.9 runtime (`apt install dotnet-runtime-7.0`).

Which Ubuntu and .NET versions do you use?

**Comment by cekefun** [comment]
Oh, it seems like the issue is me running and ARM based server.
Closing this issue and keeping an eye out for the ARM release.
