### ISSUE TITLE
Custom BlockBehavior causes pick block (middle click) to return incorrectly rotated block code

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#3]
It seems like pick block on some or all orientable blocks doesn't return the same block code that you would find in the creative inventory. For example, chests appear as `chest-east` in the creative menu, but pick block would give you a `chest-north`.

This also slightly affects my CarryCapacity mod because I use the block's `OnPickBlock` method to get a default rotated version of a block for rendering on someone's back.

**Comment by tyronx** [comment]
Is that still relevant in 1.5.2? I think it's fixed there

**Comment by copygirl** [comment]
Ahhh, my own block behavior seems to be the cause of that. Which shouldn't be the case. The only method I override is `OnPlayerBlockInteract`: [BlockBehaviorCarryable.cs](https://github.com/copygirl/CarryCapacity/blob/master/src/BlockBehaviorCarryable.cs)

**Comment by tyronx** [comment]
Pffff. Your fault :P
`properties: { dropBlockFace: "east" }` is missing in your patch

**Comment by copygirl** [comment]
Oooohh... it's on the [**WRONG ASSET**](https://github.com/copygirl/CarryCapacity/blob/master/resources/assets/carrycapacity/patches/carryable.json)!! *headdesks*
No wonder both are rotated the wrong way around.

**Comment by bitcynth** [comment]
*catches copygirl's head before it hits*
