### ISSUE TITLE
Investigate asphyxiation damage taken from doing everyday things

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#30]
1.5.2.2, the official server.
When I place ladders and climb them. I ofter get hurt. Maybe it happens when I climb right after placing.
Considering berry healing nerf, the issue is more annoying now.

**Comment by copygirl** [comment]
In general the fall damage calculations seem a bit odd. I sometimes don't take damage when I should, and then I do take a small amount of damage when I walk down my stairs.

**Comment by tyronx** [comment]
Maybe that's a good opportunity to add a new chat channel that logs all the damage you've taken. That's useful for the player and for finding this bug.

**Comment by Heptagon-ru** [comment]
Well, I was happy when I fell into shaft down to mantle and was unhurt. Maybe it was caused by touching the walls while falling? Like when you swim up the water column and run agaist a wall - you swim up much faster. Love that mechanic, please dont nerf ;)

**Comment by tyronx** [comment]
Hokay, well, damage log is added now. That will tell us if its due to fall damage or asphyxiation

**Comment by Heptagon-ru** [comment]
1.5.2.3 - ladder damage is asphyxiation, 1hp.

**Comment by tatsu011** [comment]
The fix for this should be in the next release.
