### ISSUE TITLE
Underground structures rocktype remap not working if pathway blocks are used

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3006]
### Game Version

v1.18.7 and v1.18.8

### Platform

None

### Modded

None

### SP/MP

None

### Description

Structures that use pathway blocks in their structure to spawn connected to cave entrances dont adjust to the correct rocktype.

the following mod can be used to reproduce.

### How to reproduce

[Underground rocktypes not working mod (2).zip](https://github.com/anegostudios/VintageStory-Issues/files/12313608/Underground.rocktypes.not.working.mod.2.zip)

### Screenshots

![2023-08-10_15-41-24](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/f912c0c6-214e-41b0-82e8-c9687d0b4a1b)
![2023-08-10_16-03-08](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/20d802de-568a-4766-a324-ecca18602b92)
![2023-08-10_16-06-13](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/46c1a7d7-7190-413e-854c-c3bfdfba6b0c)

**Comment by Th3Dilli** [comment]
this is now fixed with next 1.19 pre release
