### ISSUE TITLE
"Master Sound level" slider doesn't work for me in Settings -> Sound

### ISSUE THREAD

**Issue by m-from-space** [anegostudios/VintageStory-Issues#3008]
### Game Version

v1.18.8

### Platform

Linux

### Modded

None

### SP/MP

None

### Description

Using the "Master Sound level" slider inside the audio settings doesn't change anything on my system (Ubuntu 20.04).

### How to reproduce

1. Go into Settings -> Sound
2. Change slider "Master Sound level"
3. I don't hear any change, neither in the game menu, nor inside the game.
4. Other sliders seem to work

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.20
