### ISSUE TITLE
Peanuts do not work in any cooking recipe

### ISSUE THREAD

**Issue by dordle** [anegostudios/VintageStory-Issues#3013]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Peanuts cannot be used in any cooking recipe in place of soybeans or any other ingredient. They can only be eaten raw.

### How to reproduce

Try and make a vegetable stew with peanuts (onion, onion, peanut, peanut for example). The results are incompatible.

### Logs

```Log```

**Comment by RedramVS** [comment]
I've got them working in pies.  Not cooking pots yet though.
