### ISSUE TITLE
Cannot Heal in at All In Steel Armor

### ISSUE THREAD

**Issue by inthisidrown** [anegostudios/VintageStory-Issues#3018]
### Game Version

v1.18.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When wearing steel armor, I cannot use poultice or bandages to heal. There is a 33% reduction in healing effectiveness in steel armor, however that would mean that I should get 4.69 health points for every poultice used (honey-sulfur poultice from linen is 7 HP normally).  

Video: https://1drv.ms/v/s!AhUEfQqGa3Z3ie5SpReikNAl3gzpZw?e=gnbRfc

### How to reproduce

1. Wear steel armor
2. Take damage
3. Attempt to heal using Poultice or bandages
4. Note that health points do not increase

### Logs

```Log```

**Comment by tyronx** [comment]
That video seems unrelated. Make sure you are not wearing heavy armor when healing, as it reduces the healing effectiveness

**Comment by inthisidrown** [comment]
@tyronx Updated video, I am wearing heavy armor but it is not reducing effectiveness, it is stopping healing all together. No health whatsoever is being increased by using poultice.

**Comment by Craluminum2413** [comment]
@inthisidrown Does health increase when healing without armor?

**Comment by inthisidrown** [comment]
Yes I can heal in Tailored gambeson, so I am guessing if I took off all armor I could heal as well. Also, this appears to be unrelated to TRA, I just tried to heal in my steel armor at my home base and a whole stack of poultice does not increase my health points at all. I guess I had never tried healing in steel armor as I just got done smithing it all to visit the TRA 😂.  I realize there is a -33% effectiveness with steel armor, however that indicates I *should* heal.

**Comment by digital-r** [comment]
Wait, don't we have 33.33% healing effectivenes reduction *per plate armor piece*? So, three pieces of plate armor give, total, zero healing.

**Comment by Craluminum2413** [comment]
@digital-r It is stackable, so if you have 3 armor pieces with `-33.33% healing` then it will become 100% very easily

**Comment by inthisidrown** [comment]
@digital-r  Maybe you are right, the wiki does not designate per piece but putting on the full set shows my healing effectiveness at 0.
