### ISSUE TITLE
v1.18.8 release removed windows archive download

### ISSUE THREAD

**Issue by Cogito** [anegostudios/VintageStory-Issues#3019]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

From v1.18.7 and earlier it was possible to download `vs_archive_{version}.tar.gz` and have a fully working game on windows.

Among other things, this allowed for installation and upgrades on machines where running installers is locked down, or if an installer was flagged as malware by overeager antivirus (as recommended by @tyronx in [this forum thread](https://www.vintagestory.at/forums/topic/10221-upgrade-without-exe-upgrader-1174/#comment-41699)).

It looks like the new linux builds no longer generate an exe, and the `vs_archive_{version}.tar.gz` download has been replaced by `vs_client_linux-x64_{version}.tar.gz`

**Could we please have a windows compatible archive download?**

I also note that `install.sh` from the linux download references the old archive file in comments:

```#!/bin/bash
## archive="vs_archive_$(wget 'http://version.vintagestory.at/version.txt' -q -O -).tar.gz"; wget "https://account.vintagestory.at/files/stable/${archive}" -q


### How to reproduce

_No response_

### Screenshots

_No response_

### Logs

_No response_

**Comment by tyronx** [comment]
You could use a 3rd party tool like [innoextract](https://constexpr.org/innoextract/) to get the install files from the installer. I would like to avoid adding yet another file to each release. (and we still need to add another for ARM support)

**Comment by Cogito** [comment]
Thank you for the prompt reply and the help.

This works for my use case.
