### ISSUE TITLE
worldgen/structures new door issues

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3030]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

If I import structures via worldgen the new 1.18 doors do not work as intended.

Look at this video.

https://github.com/anegostudios/VintageStory-Issues/assets/100879715/520d40c3-3dc6-4f8f-acff-6f72fb2592f1

**Comment by Th3Dilli** [comment]
This was fixed in 1.18.15
