### ISSUE TITLE
Some tapestrys dont work I think this is new with net7

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3031]
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Some tapestries result in console errors and dont display their lore.
I think this is new with 1.18.8
[Unbenanntes Video (3)_VP9.webm](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/aa1583ba-9246-4acb-b9b0-f26b43e95f14)

### Logs

[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12381234/server-main.txt)

**Comment by Th3Dilli** [comment]
thanks now fixed
