### ISSUE TITLE
Swapping shift/left control ( sprint and crouch ) can't place most objects on ground

### ISSUE THREAD

**Issue by Toadsquish** [anegostudios/VintageStory-Issues#3046]
### Game Version

v1.18.8 ( stable) 

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Disabled in my left hand ( no pinky finger ) , so in previous versions I must had swapped sprint/crouch , after updating my controls updated ( game forced me to re-log back in my account) , setting back to default. 

Once I discovered this, I tried switching back , but if i swap the two buttons, I can't place things on ground like you normally would , by right clicking such as simple stones, putting bowls down/ect.  It will place building blocks like normal. 

### How to reproduce

Unsure, I do run a lot of QoL mods , not weeding that out... however everything worked fine, until I had to relog back into my account , as I have been updated ( and updated mods) for over two weeks prior to that re-log back in. 

### Logs

Nothing in logs , showing errors i could find on this issue.

**Comment by radfast** [comment]
Accessibility for all is important to us.

I can't explain why your settings were wiped during the update process.  If that is happening on a widespread basis that is a separate issue which we also ought to investigate.  The settings should be in `clientsettings.json` in the game's normal data folder.  Did you by any chance set up your 1.18.8 installation with a different data folder?

In the in-game Settings menu, Controls tab, there is an option at the top for 'Mouse modifiers locked to sprint/sneak keys'.  Please can you try unchecking that, and then the Controls settings should offer you two new options for the Ctrl and Shift keys.  These Ctrl and Shift keys are what govern mouse-clicks when placing items etc.  For example, this setting allows you to change the sprint key to something more comfortable like `Q` or `R`  (you can press `Q` with your fourth finger), while keeping to standard Windows-style `Ctrl + right mouse button` for placing things.  Or any other changes you want to make

If that doesn't work, please can you post up here a screenshot of your Controls tab showing the settings which are not working, and the team can try to reproduce the same settings and figure out why it isn't working for you.

**Comment by Toadsquish** [comment]
That wasn't easy to follow, but issue persist , yes the box is checked. I am having issue where I cannot get the settings screens to capture on screenshot. 
![2023-08-28_12-32-30](https://github.com/anegostudios/VintageStory-Issues/assets/143215367/ee55aa0f-3069-423e-86f2-bfc3909c6589)
Which i had to be fully in game to do. ( could not screen shot main menu area) 
![2023-08-28_12-34-49](https://github.com/anegostudios/VintageStory-Issues/assets/143215367/14f6a889-ff4c-4891-a58b-af0ccaf4c826)

and without in the second, both same results, only blocks I can place are default building blocks. 

No my VS install is in default folders, default place for windows.

**Comment by LastHazzerd** [comment]
Unsure if this is still getting looked at, but I'm a left-handed player and mirror the controls on the keyboard.
So i swap Left-Shift and Left-Ctrl for Right-Shift and Right-Ctrl.

I found that the UI updates to reflect the key bind change, but the actual input i need to use will remain the default key bind.
![Vintage Story Lefty Keybind Issue Resize](https://github.com/anegostudios/VintageStory-Issues/assets/147351060/91668357-9f2f-4421-8b6b-e6363d090d7f)

This happens for pretty much everything that requires the use of the "Primary" or "Secondary" interact feature of the Mouse1 and Mouse2 inputs paired with the Shift key.
The UI changing when i rebind sneak suggests that the intention was "[Primary/Secondary]+[Sneak]" to be how the key bind inputs were meant to be handled, but if that is the case, the functionality is currently not working.
I'm using version v1.18.14 (stable)

I cannot Knap, I cannot place blocks that I am holding, etc.
I need to use the default inputs if i ever need to Shift Click to perform an action, that I cannot explicitly bind myself.

**Comment by Craluminum2413** [comment]
I noticed it was fixed in 1.20
