### ISSUE TITLE
Crash while creating a new world

### ISSUE THREAD

**Issue by Schokomobil** [anegostudios/VintageStory-Issues#305]
I cannot create a new world since the last update (survial and creative). This is what the crash reportd says:

Running on 64 bit Windows with 16 GB RAM 
Version: v1.9.4 (Stable)17.05.2019 16:58:23: Critical error occurred
System.Exception: Found closing tag < font> at position 40 but <font> should be closed first
   bei Vintagestory.API.Common.VtmlParser.Tokenize(String vtml)
   bei Vintagestory.API.Common.VtmlUtil.Richtextify(ICoreClientAPI capi, String vtmlCode, CairoFont baseFont, Action`1 didClickLink)
   bei Vintagestory.API.Client.GuiComposerHelpers.AddRichtext(GuiComposer composer, String vtmlCode, CairoFont baseFont, ElementBounds bounds, String key)
   bei Vintagestory.Client.NoObf.GuiDialogFirstlaunchInfo.Compose()
   bei Vintagestory.Client.NoObf.GuiDialogFirstlaunchInfo..ctor(ICoreClientAPI capi)
   bei _SmAdNDdxV1t1kqXqVRlXvCt1bBn._ND8m4Dng4HQcAxRtxGbV6rWz8sH()
   bei _SmAdNDdxV1t1kqXqVRlXvCt1bBn..ctor(_Huk54HNPXRat1maGdNXKfSSaL6L )
   bei _Huk54HNPXRat1maGdNXKfSSaL6L._NBrbS0B41qKvge4bEEVNJHdfj8Eb()
   bei _GZdFx15BoPPkj4QqBV5TzSRr10j._NBrbS0B41qKvge4bEEVNJHdfj8Eb(Boolean , StartServerArgs , _zBPAQhMenLmYjiVnEbVX6XDHjXu )
   bei _PYkl1MNdchQjIDg8rzO3djOvnON._QmiCyQDyGpmnC0cz7Yz2OTvB0Ab(Boolean , StartServerArgs , _zBPAQhMenLmYjiVnEbVX6XDHjXu )
   bei _Q33xvfrbVP7F0GgjdDakfpWRFrFA._nejaNSECIpJgQucJ7akZDeyfTUR()
   bei _Q33xvfrbVP7F0GgjdDakfpWRFrFA._tRGX79M21gvH08tq8H2dyfLFhOV()
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   bei _UESekn3AoN8jeLTToQ0OhhSbaqE._0fSkgBfPvOT8UD480qqzN8VdkYH(MouseEvent )
   bei _h8mFH1Kpzoh4WltBnsjOPN7149q._t0bFuJUhTi57vEwAvh1X3aJMG9G(Object , MouseButtonEventArgs )
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _3oejdwdkNK1xWXMENbF0ByfhuEY._NBrbS0B41qKvge4bEEVNJHdfj8Eb(_arOnLJpwDKhTxqVMxTjiHzKf7Od , String[] )
   bei _QmumXTloXEzkGO6rMw0sFHHcMxk._NBrbS0B41qKvge4bEEVNJHdfj8Eb(ThreadStart )
-------------------------------

**Comment by tyronx** [comment]
Thanks for the report. I already fixed it and will release version 1.9.5 asap. Until then you can switch to english and play normally. It's only the german translations that broke the game.

**Comment by tyronx** [comment]
ok, v1.9.5 is up
