### ISSUE TITLE
Audit Log Enhancements

### ISSUE THREAD

**Issue by RogueRaiden** [anegostudios/VintageStory-Issues#3050]
### Platform

None

### Modded

None

### SP/MP

None

### Description

The audit log doesn't log nearly enough things. For example, it logs when players shift+click items into and out of containers but not normal movement. Here are some things that need to be added to the audit log:

When a player moves items into and out of any container with any item movement method log the player, coordinates, items moved, amount and method

When a player adds or takes things from any interactable object like shelves, bookshelves, display cases, ovens, and crates log the player, items moved, amount, object and coordinates of the object

When a player moves things in and out of ground storage log player, items and coordinates

When a command is used, log the player that used the command

When a player kills an entity log the player, entity code (wolftaming:dog-wolf-female) and coordinates

**Comment by RogueRaiden** [comment]
also the logging of who placed and broke blocks would be immensely useful. basically exactly like the blocklog mod does. but without the horrible save game lag that it introduces.

being able to see exactly who and when a person broke a block takes the time to resolve griefing incidents down to only seconds.

it is an absolute must have for any and every public server.

**Comment by Th3Dilli** [comment]
this is now mostly done but will be for 1.20
+ log rotation so it keeps 5 sessions of logs (main debug audit chat build)

some stuff with mouse moving items is already in 1.19

**Comment by Th3Dilli** [comment]
this is already added now in 1.20 ;)
