### ISSUE TITLE
Game crash at generating new world 

### ISSUE THREAD

**Issue by leftdead** [anegostudios/VintageStory-Issues#306]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.9.4 (Stable)17.05.2019 21:13:03: Critical error occurred
System.Exception: Found closing tag < strong> at position 387 but <strong> should be closed first
   bei Vintagestory.API.Common.VtmlParser.Tokenize(String vtml)
   bei Vintagestory.API.Common.VtmlUtil.Richtextify(ICoreClientAPI capi, String vtmlCode, CairoFont baseFont, Action`1 didClickLink)
   bei Vintagestory.API.Client.GuiComposerHelpers.AddRichtext(GuiComposer composer, String vtmlCode, CairoFont baseFont, ElementBounds bounds, String key)
   bei Vintagestory.Client.NoObf.GuiDialogFirstlaunchInfo.Compose()
   bei Vintagestory.Client.NoObf.GuiDialogFirstlaunchInfo..ctor(ICoreClientAPI capi)
   bei _HxyJK6bE2SBjOV5hbLQDsFu2oJf._IV1hankyWTzseGA1IWYkQd9l0hg()
   bei _HxyJK6bE2SBjOV5hbLQDsFu2oJf..ctor(_ZAOAXn5R6FHtx928rHbDrWT6Dwm )
   bei _ZAOAXn5R6FHtx928rHbDrWT6Dwm._Dn5MIELVgkc8wZwz9Jm0T9isRgC()
   bei _CoTSf6KaHXzaK1XhITs1eOVSv8h._Dn5MIELVgkc8wZwz9Jm0T9isRgC(Boolean , StartServerArgs , _8My3C7OpKXP0zVQbtu61CXH8gHi )
   bei _MMIoCkLeyppBN4uYXt2PczIAhOR._MANJKWNBcRTubfhiDJHd5KhwI22(Boolean , StartServerArgs , _8My3C7OpKXP0zVQbtu61CXH8gHi )
   bei _3P4jFRjPrGj27kg7XYTXkkTXIai._pOFFHeWOLxa7692mP0Xb1hfZvTf()
   bei _3P4jFRjPrGj27kg7XYTXkkTXIai._pfu3gxI0VuDL9MeXPNSCFmEqYKH()
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   bei _Wqtz6BEBhJEank9Th1HHzi1Cl07._84da0fHEXD2coHkSf2O9gqPaDkA(MouseEvent )
   bei _jJLKn8HqimL4Ea8UhrDnQUNqZLb._4nODtNNv63o1avdixnsksuN5QOC(Object , MouseButtonEventArgs )
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _WcDpMGiROOsUAcHDhoyZ2jj3xHo._Dn5MIELVgkc8wZwz9Jm0T9isRgC(_f688KjsipALFOHFqxDJXsqD4g1f , String[] )
   bei _XzT2Jb8s65KnUb6A9sULHGRUEqK._Dn5MIELVgkc8wZwz9Jm0T9isRgC(ThreadStart )
-------------------------------

**Comment by tyronx** [comment]
Sorry for the troubles. I messed up the latest release. Please switch to english translations, that'll prevent the crash, until v1.9.6 is out
