### ISSUE TITLE
Resonance Archive stalagtites preventing progress

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#3067]
### Game Version

1.18.8

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/1f4d464f-a9c9-4409-acb1-59c30e04d6ab)

**Comment by Craluminum2413** [comment]
Fixed in 1.20
