### ISSUE TITLE
Ingame update from 1.18.8 - 1.18.10 fails while updating

### ISSUE THREAD

**Issue by SUYPERMRBATH** [anegostudios/VintageStory-Issues#3078]
### Game Version

v 1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

i cant update. through the past 2 updates it says the same thing not allowing me to update. the error message is in the attached image.

### How to reproduce

1, make an account,
2, play for a bit
3, attempt to update past 1.18.8

### Screenshots

![Screenshot 2023-09-03 145357](https://github.com/anegostudios/VintageStory-Issues/assets/143760359/aa821cf0-5314-4294-a517-e4a83b0626a9)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for reporting 
we already fixed that so with the next version it will be fixed

but this means only when the new 1.18.11 is installed it will work so you have to install that one still manually

**Comment by chinchilla442200** [comment]
how do i manually update the game/find the needed files too fix this issue

**Comment by Th3Dilli** [comment]
Should be fixed since 1.18.11, it can be installed form the Client Area on https://vintagestory.at
