### ISSUE TITLE
Butchering and inventory

### ISSUE THREAD

**Issue by Siltoneous** [anegostudios/VintageStory-Issues#308]
Version 1.9.5
Butchered a hyena, and had the butcher inventory slot open.  I also had my extended inventory open with similar items in it (skin, bush meat, fat).  When I shift clicked to add the items from the wolf inventory to my personal inventory, the items disappeared from the butcher inventory, but did NOT appear in my inventory.  What happened is that the item pictures went missing in the butcher inventory, but were still in fact there.  I was still able to drag-n-drop the invisible items from the butcher inventory into my personal inventory, where the items incremented properly, and the item pictures in my personal inventory stayed fine.  I've attached a screenshot to show the invisible items in the hyena inventory, even though you can't see them. =)

Also, a minor annoyance is that the gender of the hyena is misspelled. =D

Silt
![2019-05-17 15_27_29-Vintage Story-2](https://user-images.githubusercontent.com/46652566/57972782-bdd42c00-7964-11e9-83ca-2b19915971f9.png)

**Comment by tyronx** [comment]
Hokay this is now fixed
