### ISSUE TITLE
Leather Reinforced Wooden Shield missing attributes

### ISSUE THREAD

**Issue by Datanazush** [anegostudios/VintageStory-Issues#3085]
### Game Version

v1.18.10

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Leather Reinforced Wooden Shields presently lack a `wood:` attribute of any kind if the player crafts one, rendering it unable to be traded to traders.
(Thanks to discord user Staniboy for discovering)

### How to reproduce

Enable Debug mode, examine Shield obtained from creative inventory with extended debug info
Craft equivalent shield, examine said shield, note missing `wood:` attribute

### Screenshots

Tradeable Leather Reinforced Wooden Shield with correct attributes (obtained from creative inventory)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/140927888/0159ebb9-b42a-4432-b534-43fda99c06d6)
Untradeable Leather Reinforced Wooden Shield with incorrect attributes (crafted from raw materials)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/140927888/296a9cfa-4599-4791-a656-4e6f94e7e265)
List of item attributes in the crafting window
![image](https://github.com/anegostudios/VintageStory-Issues/assets/140927888/8f6e71f2-43d8-4612-a1e1-e5a0eb21e3a7)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.20, I assume it is fixed
