### ISSUE TITLE
Option for tooltips to display originating mod

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#309]
Tooltips (both block in-world and item in-GUI) should either always display the name of the mod it originated from - perhaps in smaller font and darker color - or there should at least be an option to change this in the interface settings. Official blocks may be exempt from this.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
