### ISSUE TITLE
World Bomb

### ISSUE THREAD

**Issue by arnoldray007** [anegostudios/VintageStory-Issues#3090]
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

ok, the last 3 games i have started, one 10 min. one 5 hr. one 1 hr. 20 min.  All would lag really bad then just stop. i log out and back in and the world is gone. I can't move or anything there is just air no land.  I have tried this with and without mods. I'm wondering what is going on and how to fix it. 

### How to reproduce

i am doing nothing really. the first one that was 5 hrs.  I was just standing there and logged out and when i logged back in the world was gone.  the other 2 I was exploring. 

### Logs

```Log```couldnt find

**Comment by arnoldray007** [comment]
Just created another one and no lag just like before.   after 1 hour 11 min the game just stopped and i couldn't do anything and  i logged out and back in and i still couldn't interact with anything. it's like everything but me is frozen. but looks like it still moves i.e.: torch's, containers, animals. I just can't interact with them.

**Comment by arnoldray007** [comment]
ok, tried to run fixer, it did nothing. I can log in this world and move around fine but can't interact with anything. can't open containers. I hit the goat, and it acts like I hit it but no damage.  don't know what's up ...

**Comment by kanelillym** [comment]
I am having a similar issue. In a heavily modded game i got about 20 minutes on a fresh world, in unmodded I got just 3 minutes once. Eventually the world stops responding to me which I notice because rocks do not drop items on destruction. If I save and reload, I am floating in the sky with the sun and moon visible and no land or water.

Game version: 1.18.10 and 1.18.12
Platform: Debian 12 / KDE Plasma
Single player only

**Comment by arnoldray007** [comment]
Ok, I fixed my problem. No issues for 29hrs so far.

I unintalled my mods ran a new game. And reinstaled mods 1 at a time.

I think one of my mods was causing it. The mod had to do with res one saps
you plant.

I would try the same.

**Comment by RedramVS** [comment]
@kanelillym if you still have this issue, please start a new report.  I'm going to close this issue since the OP determined their problem was mods.  Despite that in their original report they stated 'mods none'.
