### ISSUE TITLE
Te expulsa del juego al intentar comerciar v1.18.10

### ISSUE THREAD

**Issue by alvarocabezas** [anegostudios/VintageStory-Issues#3097]
### Game Version

v1.18.10

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Al romper alguna cosa del comerciante, al tocar al comerciante el juego te explosa automáticamente, te arroja un error y sucede con todos los comerciantes 

### How to reproduce

1 crear un mundo nuevo 
2 buscar un comerciante
3 darle clik para abrir si interfaz del comerciante

### Screenshots

![Captura](https://github.com/anegostudios/VintageStory-Issues/assets/31289578/b1e3c82f-f2bd-4695-99c9-a091ee5f535a)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Caused by mod
