### ISSUE TITLE
Inventory extenders dropping

### ISSUE THREAD

**Issue by HovadoLesni** [anegostudios/VintageStory-Issues#3104]
### Game Version

1.18.10

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When upgrading my inventory extenders (I don't know what you call them) from basket to hunter backpack and later from hunter to linen sack I can't keep the ones I want to replace.
Once I insert the upgrade the old one stays in my hand(cursor) and once I close the inventory it drops to the ground and I'm unable to interact with it anymore.
This is quite a loss as I invested resources into creating it and would like to keep it. I might open my game to plan to play with my kids and the old items would be suitable for them.

### How to reproduce

use 4 baskets and create on hunter back[pack and replace one basket with hunter backpack ( I know on thew screen is second tier but its the same problem)

### Screenshots

here is a screen I'm standing beside my old hunter's backpack that I replaced with a linen sack and the backpack is unresponsive

![upgrade](https://github.com/anegostudios/VintageStory-Issues/assets/145361680/5afa52c2-a021-4a59-bd43-4883c5154213)
a 

### Logs

```Log```

**Comment by Craluminum2413** [comment]
You can't put backpack into common slot if it has items inside, empty it and then you can pick it up freely

**Comment by HovadoLesni** [comment]
ok now I understand why am I missing my items, they where inside of the hunters backpack with now despawned,
