### ISSUE TITLE
Trader does not accept identical item (Leather reinforced wooden shield)

### ISSUE THREAD

**Issue by thp314** [anegostudios/VintageStory-Issues#3105]
### Game Version

v1.18

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Treasure hunter trader refused to except newly crafted Leather reinforced wooden shield with right metal material (iron) 

Perhaps there is another hidden value like wood type which trader expects? If so would be great if this value can be exposed as I made a shield just for trader only for it to be rejected.

### How to reproduce

1. Make Leather reinforced wooden shield with maple wood and iron
2. Try to trade it to Treasure Hunter Trader and watch it be rejected
3. Use the shield for other purposes :(

### Logs

```Log```

**Comment by Saricane** [comment]
Did you try to activate the Debug option in the Settings/Developper tab ? I had the same kind of problem with trader refusing to buy a skep, and with the game id displayed, I realized there is 4 different game id for a skep, depending on the orientation. May be the game ids for the two shields are not the same.

**Comment by RedramVS** [comment]
This appears to be identical to issue #3085
