### ISSUE TITLE
Falling against a wall negates fall damage

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#3108]
### Game Version

1.18.7+

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Find a deep pit to die in. Jump against a wall pressing forward the entire time against that wall. Upon landing you take no damage. Video here: [https://youtu.be/AoC4He0jKi0](https://youtu.be/AoC4He0jKi0)

**Comment by Craluminum2413** [comment]
Fixed in 1.19.0-pre.1
