### ISSUE TITLE
i cant find the clay oven

### ISSUE THREAD

**Issue by iceking12003** [anegostudios/VintageStory-Issues#3120]
### Game Version

v.18.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

so ive seen many vids of people making bead and i cant find the oven its not in the clay formation option ive cheak on a another world but i still cant find it i really love the game but i want some bread. 

### How to reproduce

try to make a oven you wouldnt be able to find it 

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@iceking12003 it can only be made from fireclay

**Comment by balloonhead** [comment]
Answered correctly. Can be closed
