### ISSUE TITLE
Sieve repaired when placing on ground

### ISSUE THREAD

**Issue by Bumber64** [anegostudios/VintageStory-Issues#3122]
### Game Version

v1.18.13

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Sieves lose durability when used to craft parchment, but are repaired to full when placed as a block and collected again.

### How to reproduce

1. Craft parchment from linen pulp and sieve, notice durability on sieve decreased.
2. Right-click on ground with sieve selected to place.
3. Break placed sieve by holding left-click. Durability now at 200/200.

**Comment by Saricane** [comment]
I can confirm this bug.
