### ISSUE TITLE
Remove all Shape and Texture references from code

### ISSUE THREAD

**Issue by TonyLiberatto** [anegostudios/VintageStory-Issues#313]
I have been struggling on how to approach this subject in a way that people can understand my meaning. 
I made a basic count of the mods in the #Mods Release channel of the forum. As of May/20/2019 we had 47 posts there. Some where re posts with a different name or just updates, some people just edited the old posts. Not considering that, of those, 27 were Content mods with no code in it, 20 were  code mods.
Of the 20 many were publish by me, and everyone knows I cannot code. Some were publish by people that struggle to code, I wonder how many of those consider themselves as proficient C# programmers.  
My point is that the easier way for people like me, and by the amount of Content mods, I am not alone, is if we could use the available code in the game as just attributes or behaviors, and just create json files.
My idea is that if someone, be it a Dev or a Modder, wants to create a new block that uses any feature that is already coded into the game, they would not need to increase the size of the Game code.
So the new block is a liquid container? It just need to have Attribute; LiquidContainer. Not to use the Bucket Class. There would not be a bucket Class.
The bucket would use Attribute; LiquidContainer. 
This is a big change, and it would take time and effort to make it. I do however believe it would be worth it.
One example, of how this would work, is how @copygirl is making her code for the CarryCapacity. 
Is a very extensive code, but anyone can use it without the need to make new code. 
We just set a block with the Attribute: Carryable. And that is it. 
There would always be room for actual coders to create new features, and they would be welcome. 
My idea, is that the game would really grow faster if this was done. 
So, my proposal, for the 1.10, is to be the Modder update.
Another argument in favor of doing this now, is that the more the game grows the harder it would be to implement it latter.

Mod authors with mods in the Forum are: 9 .
Hobbes, Skodone, Tatazaki, Elwood, Balduranne, BunnyViking, MarkAAFK, Sunvald and TonyLiberatto. 

Mod Authors who do code are: 8 .
Erik, Millo, Cout970, Stroam, Doam, Melchior, Novocain, copygirl,
2 files, just quick searches for the words shape and texture.
[Shape-refferences.txt](https://github.com/anegostudios/VintageStory-Issues/files/3203812/Shape-refferences.txt)
[texture-refferences.txt](https://github.com/anegostudios/VintageStory-Issues/files/3203813/texture-refferences.txt)

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
