### ISSUE TITLE
Juice barrels cannot be sealed for some reason

### ISSUE THREAD

**Issue by orborde** [anegostudios/VintageStory-Issues#3132]
### Game Version

v1.18.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

For some unknown reason, some of my barrels of juice cannot be sealed. There is no "will make X amount of wine if sealed" in the barrel UI (see screenshot), and clicking on the "Seal" button does nothing.

My save is too big to attach, but here's a link: https://www.dropbox.com/scl/fi/w9bplc6onowlzuibwyohp/orbordes-hermit-world.vcdbs.gz?rlkey=ick2qtbavdv4jxcoi53hy3l8i&dl=0

### Screenshots

![cantseal](https://github.com/anegostudios/VintageStory-Issues/assets/804638/b77e4cdc-ae96-4ac4-a2b3-b7c656fb856f)

**Comment by SamDeNies** [comment]
I believe this is an issue if the volume has two decimal places.  If you had 11 liters even, or 11.2 liters, I believe it will seal.  Still a bug.

**Comment by orborde** [comment]
Addendum: If I move the liquid to another barrel (using a bucket or bowl), the new barrel does show "will make X amount of wine if sealed".

**Comment by Saricane** [comment]
I can confirm you have to round the volume to the lower integer value before sealing.

**Comment by Ragolution** [comment]
Reproduced on 1.18.15. Barrels with non-interger values will not successful engage a recipe for alcohol, probably due to the recipe calling for a whole-number value to create alcohol.

**Comment by Craluminum2413** [comment]
Recipe should use 0.01 as requirement
