### ISSUE TITLE
Hunter's Backpacks and Inventory Disappear After Dying

### ISSUE THREAD

**Issue by Lbroil** [anegostudios/VintageStory-Issues#3133]
### Game Version

V1.18.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I was killed by a wolf while I had 4 hunter's backpacks making up my inventory. When returning to the spot where I died, only the items in my hotbar dropped. All 4 backpacks and everything contained therein were gone.
I was hosting on a world and playing with one other person on LAN.
The other player picked up two spears that were in my hotbar when I died. They did not pick up anything else.
World settings were tweaked so items do not despawn until 30 minutes after death. I returned to the spot of my death about 7 minutes after death so they should have still been there. 
We searched the entire area to see if they landed somewhere further, but were unable to find anything that was not from my hotbar.
This has only happened once. Other deaths have resulted in expected items dropping.

### How to reproduce

1. In multi-player survival world, craft 4 hunter's backpacks and place them in the character's inventory.
2. Completely fill hotbar slots and all item slots.
3. Provoke wolf and die.
4. Return to area to see if backpacks and inventory dropped as expected.

### Logs

```Log```

**Comment by OldManAlpha** [comment]
I've experienced this issue as well, having the despawn timer set at 1 hour. I think the bags are following a different despawn timer than the hotbar items since I never have had bags despawn if I hastily retrieve them. I also had this happen with hand baskets, so I believe all containers are affected.

**Comment by Lbroil** [comment]
I can confirm that containers are operating on a different timer. My partner died and I watched the bags disappear before their hotbar items.
I don't know if that makes this a bug or a feature operating not as intended/expected by the player base, but would appreciate a fix either way.

**Comment by Gavin-Bowers** [comment]
I lost my items to this glitch. Luckily, my friend is hosting the server and cheated in items to replace them, but it was still disheartening. I would have probably quit the game if not for that. Fix asap!

**Comment by TRex8319** [comment]
Still happens with v1.19 using Hunter Backpack.
Any quick way to mod this out for the despawn timer of bag/baskets/backpack?
Thanks!

![2024-02-03_00-56-33](https://github.com/anegostudios/VintageStory-Issues/assets/150118373/b2106ec5-5367-4f79-9a7f-241dc31fbeaf)

**Comment by Craluminum2413** [comment]
Fixed in 1.19.4-rc.1
