### ISSUE TITLE
Fullscreen toggle broke

### ISSUE THREAD

**Issue by timingplanet** [anegostudios/VintageStory-Issues#3135]
### Game Version

v1.18.14

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When switching to Fullscreen in the latest version of vs it will go full screen but wont go to windowed when pressing F11 again original found while playing a modded server but have tested in vanilla singleplayer and it still occurs 

### How to reproduce

1 start vs
2 start join a game or single player 
3 press f11
4 if in full screen nothing will happen

### Logs

```Log```

**Comment by Vanir-dono** [comment]
same here, need to restart game in order to switch

**Comment by timingplanet** [comment]
Well I know ive seen people in the vs discord say they have the same issue and my friend has the same issue. Idk if it's isolated or not. Hopefully you can figure it out though!

**Comment by balloonhead** [comment]
Same issue here but it is not necessary to join a game. Just start Vintage Story then press F11. It will only toggle once. 
Pressing F11 set the correct setting but has no reaction. Just look at the graphics settings for fullscreen, press F11, change to another screen and back to graphics and you see it triggers the button. 

Problem still is there in 1.18.15

**Comment by Th3Dilli** [comment]
ok i was able to figure out the issue, apparently there is an issue with dotnet publish that would not copy an older version of a library to the output if a newer one is already there (it fails to downgrade the version) 

so if you want to fix this issue right now you can copy the OpenTK*.dll's from 1.18.13 over

**Comment by balloonhead** [comment]
How can I get these without installing 1.18.13?

**Comment by balloonhead** [comment]
Okay fixed it. Had to install comlete 1.18.13, copy the libs to a temporary folder and then install 1.18.15 again and copy the libs back to the original folder. Fixed the bug for now.

**Comment by Th3Dilli** [comment]
1.19 fixes that, + new window settings
