### ISSUE TITLE
Placed ladders and tool racks disappear when broken (you get no items back)

### ISSUE THREAD

**Issue by zkol** [anegostudios/VintageStory-Issues#314]
**Game Version:** 1.9.6 Multiplayer
**Platform:** Linux (Ubuntu 18.4. LTS with mono 5.20.1.19)
**Modded:** No

### Description
In survival mode, placed ladders and tool racks simply disappear when broken (you get no items back as it was before).  I observed this on multiplayer and could reproduce it on singleplayer too.

### How to reproduce
1. Craft a ladder and a tool rack from sticks
2. Place the ladders on the ground and the tool rack on a wall
3. Try to break them to get them back in the inventory
4. The ladders and the tool rack are disappeared

### Expected behavior
They should appear as items to be picked up

**Comment by tyronx** [comment]
thanks, already fixed for 1.9.7
