### ISSUE TITLE
Sneak key bind not rebinding the "Shift+Click" inputs for interaction.

### ISSUE THREAD

**Issue by LastHazzerd** [anegostudios/VintageStory-Issues#3141]
### Game Version

v1.18.14 (stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I play left-handed, so I rebind my keys as a mirror of the default keys.
Such as changing Left Shift to Right Shift.

When I do this, the game's UI updates to reflect this, and says that I can place blocks by holding "R.Shift" and Right Clicking.
But I cannot actually do that. The game still has it set as the default key binding despite the change in UI.

Not to assume this is 100% accurate, but the Wiki says:
"This is the default key bind, please keep in mind that when changing, for instance, the Shift key for sneaking to a different one, all combinations previously using the shift key will change to your new key choice as well."

I've seen others mention this issue in both the discord, and in reports on this site, but including several other variables like mods. Forgive me if I'm writing this in vein, I just hope to present a repro-rate of 100%, since I encountered this issue on a fresh install of v1.18.14 and no mods. Purely just playing with my Left-Handed key binds.

Additionally, upon a fresh boot of the game, the UI will revert to saying "Shift + Right Click" to place blocks, despite the Sneak command still having the re-bound key saved from the previous session.

If further information is needed please let me know.
Thank you.

### How to reproduce

1. Open the settings menu and navigate to "Controls."
2. Locate the "Sneak" command and rebind the key to Right Shift.
3. In gameplay, attempt to place blocks or "Knap" stones. (Anything that requires a "Shift+Click" interaction).
4. Note that the expected action does not occur, even though the UI updated to reflect the "Sneak" command's rebind.
5. Additionally, closing and reopening the game will result in the UI reverting to default controls despite sneak still being rebound.

### Screenshots

![Vintage Story Lefty Keybind Issue Resize](https://github.com/anegostudios/VintageStory-Issues/assets/147351060/86f3b3ae-570e-4ff0-a7e3-d2291b522d9b)

### Logs

```Log```

**Comment by Selfeya** [comment]
I would like to add that rebinding the sneak key and/or the Shift-click key to RShift does not allow you to RShift+Click to move item stacks. This specifically requires the left shift button. I am also a lefty and didn't even know you could shift+click until someone told me.

**Comment by Craluminum2413** [comment]
![image](https://github.com/user-attachments/assets/c6c460c5-81cf-4b85-91a9-d8650eb53edb)
