### ISSUE TITLE
Can't update game version 1.18.8

### ISSUE THREAD

**Issue by Raybro29** [anegostudios/VintageStory-Issues#3143]
I've been stuck on version 1.18.8 for the past month or two. While the game is still stable and runs fine, I have been attempting to update to the current version of the game only for the update to freeze and stay at a certain percentage for a while as the game continues to run. I've tried again and again to update only for the same issue to come up. As of writing, the game version is now on 1.18.14 while I'm still stuck on 1.18.8

**Comment by Th3Dilli** [comment]
what operating system and logs please (client-main.txt)

**Comment by Raybro29** [comment]
My OS version is Windows 10 Home.
As for the log, the game still runs perfectly fine and doesn't crash when I
try to update it. The crash at the end of the log is relates to a separate
issue related to a mod;

9.10.2023 21:29:55 [Notification] Client logger started.
9.10.2023 21:29:55 [Notification] Game Version: v1.18.8 (Stable)
9.10.2023 21:29:56 [Notification] OpenAL Initialized. Available Mono/Stereo
Sources: 255/1
9.10.2023 21:29:56 [Notification] CPU Cores: 12
9.10.2023 21:29:56 [Notification] Available RAM: 32699 MB
9.10.2023 21:29:56 [Notification] Graphics Card Vendor: NVIDIA Corporation
9.10.2023 21:29:56 [Notification] Graphics Card Version: 3.3.0 NVIDIA 536.23
9.10.2023 21:29:56 [Notification] Graphics Card Renderer: NVIDIA GeForce
GTX 1050 Ti/PCIe/SSE2
9.10.2023 21:29:56 [Notification] Graphics Card ShadingLanguageVersion:
3.30 NVIDIA via Cg compiler
9.10.2023 21:29:56 [Notification] GL.MaxVertexUniformComponents: 4096
9.10.2023 21:29:56 [Notification] GL.MaxUniformBlockSize: 65536
9.10.2023 21:29:56 [Notification] Cairo Graphics Version: 1.17.3
9.10.2023 21:29:56 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
9.10.2023 21:29:56 [Notification] C# Framework: .net 7.0.10
9.10.2023 21:29:56 [Notification] OpenTK Version: 3.3.2 (A set of fast,
low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
9.10.2023 21:29:56 [Notification] Start discovering assets
9.10.2023 21:29:56 [Notification] Found 23 base assets in category lang
9.10.2023 21:29:56 [Notification] Found 0 base assets in category patches
9.10.2023 21:29:56 [Notification] Found 22 base assets in category config
9.10.2023 21:29:56 [Notification] Found 0 base assets in category
worldproperties
9.10.2023 21:29:56 [Notification] Found 46 base assets in category sounds
9.10.2023 21:29:56 [Notification] Found 97 base assets in category shapes
9.10.2023 21:29:56 [Notification] Found 72 base assets in category shaders
9.10.2023 21:29:56 [Notification] Found 16 base assets in category
shaderincludes
9.10.2023 21:29:56 [Notification] Found 131 base assets in category textures
9.10.2023 21:29:56 [Notification] Found 4 base assets in category music
9.10.2023 21:29:56 [Notification] Found 0 base assets in category dialog
9.10.2023 21:29:56 [Notification] Found 411 base assets in total
9.10.2023 21:29:56 [Notification] Loading sounds
9.10.2023 21:29:56 [Notification] Sounds loaded
9.10.2023 21:29:56 [Notification] (Re-)loaded frame buffers
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass .
9.10.2023 21:29:56 [Notification] Begin loading shaders
9.10.2023 21:29:56 [Notification] Load shaders now
9.10.2023 21:29:56 [Notification] Loading shaders...
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
standard.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
particlescube.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
particlesquad.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass sky.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
nightsky.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
woittest.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
transparentcompose.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
debugdepthbuffer.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
helditem.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
chunkopaque.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
chunkliquid.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
decals.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
final.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass gui.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
blur.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
chunktransparent.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
findbright.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
chunktopsoil.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
godrays.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
autocamera.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
blockhighlights.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
wireframe.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
entityanimated.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
luma.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
blit.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
particlesquad2d.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
shadowmapentityanimated.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
shadowmapgeneric.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
texture2texture.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
celestialobject.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
guitopsoil.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
colorgrade.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
guigear.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
ssao.
9.10.2023 21:29:56 [Notification] Loaded Shaderprogramm for render pass
bilateralblur.
9.10.2023 21:29:56 [Notification] Cached session key is valid, validating
with server
9.10.2023 21:29:57 [Notification] Server validation response: Good
9.10.2023 21:29:57 [Notification] Will search the following paths for mods:
9.10.2023 21:29:57 [Notification]     C:\Users\Jacob
Lopez\AppData\Roaming\Vintagestory\Mods
9.10.2023 21:29:57 [Notification]     C:\Users\Jacob
Lopez\AppData\Roaming\VintagestoryData\Mods
9.10.2023 21:29:57 [Warning] [loreweapons] Dependency 'game': Failed
parsing version string '1.18.0-*' at index 7: Unexpected character '*' in
PRE_RELEASE identifier (best guess: 1.18.0)
9.10.2023 21:30:00 [Notification] Initialized GUI Manager
9.10.2023 21:30:00 [Notification] Initialized Server Connection
9.10.2023 21:30:00 [Notification] Server args parsed
9.10.2023 21:30:00 [Notification] Server main instantiated
9.10.2023 21:30:14 [Notification] Window was resized to 0 0? Window
probably got minimized. Will not rebuild frame buffers
9.10.2023 21:30:43 [Notification] Processed server identification
9.10.2023 21:30:43 [Notification] Map initialized
9.10.2023 21:30:43 [Notification] Received server assets
9.10.2023 21:30:43 [Notification] Loading and pre-starting client side
mods...
9.10.2023 21:30:43 [Notification] Will search the following paths for mods:
9.10.2023 21:30:43 [Notification]     C:\Users\Jacob
Lopez\AppData\Roaming\Vintagestory\Mods
9.10.2023 21:30:43 [Notification]     C:\Users\Jacob
Lopez\AppData\Roaming\VintagestoryData\Mods
9.10.2023 21:30:43 [Warning] [loreweapons] Dependency 'game': Failed
parsing version string '1.18.0-*' at index 7: Unexpected character '*' in
PRE_RELEASE identifier (best guess: 1.18.0)
9.10.2023 21:30:43 [Warning] Multiple mods share the mod ID 'betterruins'
('BetterRuinsv0.2.2.zip', 'BetterRuinsv0.2.4.zip'). Will only load the
highest version one - v0.2.4.
9.10.2023 21:30:43 [Warning] Multiple mods share the mod ID
'maltiezfirearms' ('Firearms_0.1.10.zip', 'maltiezfirearms_0.2.2.zip').
Will only load the highest version one - v0.2.2.
9.10.2023 21:30:43 [Notification] Found 44 mods (5 disabled)
9.10.2023 21:30:43 [Notification] Mods, sorted by dependency:
aculinaryartillery, composter, evaporite, morecrops, femininity,
hideandfabric, HumanSkinTones, pieontheshelf, primitivesurvival,
rackablefirestarter, rooffix, rpgitemrarity, speararrowheadbits, game,
wildcrafttrees, alchemy, commonlib, decoclock, expandedfoods, freedomunits,
fromgoldencombs, loreweapons, mapautocenter, metaltongs, petai, claywheel,
rustboundmagic, simplestep, th3dungeon, vesselbuff, creative, vsquest,
survival, vsvillage, whatbagwasthatagain, metalrecovery, foxtaming,
morecandles, stonequarry
9.10.2023 21:30:44 [Notification] [morecandles] Successfully compiled 2
source files
9.10.2023 21:30:44 [Notification] Instantiated 140 mod systems from 39
enabled mods
9.10.2023 21:30:44 [Notification] [commonlib] Config StoneQuarry.Config,
StoneQuarry, Version=3.1.5.0, Culture=neutral, PublicKeyToken=null loaded
successfully
9.10.2023 21:30:44 [Notification] Done loading and pre-starting client side
mods.
9.10.2023 21:30:44 [Notification] Mod Config successfully loaded.
9.10.2023 21:30:44 [Event] started 'Composter' mod
9.10.2023 21:30:44 [Notification] modconfigload
9.10.2023 21:30:44 [Event] started 'Lore Weapons' mod
9.10.2023 21:30:44 [Notification] Mod Config successfully loaded.
9.10.2023 21:30:44 [Notification] Start called, registering tree class
9.10.2023 21:30:44 [Notification] External Origins in load order:
***@***.***:\Users\Jacob
Lopez\AppData\Roaming\Vintagestory\assets\creative\, ***@***.***:\Users\Jacob
Lopez\AppData\Roaming\Vintagestory\assets\survival\, ***@***.***
1.0.15.zip, ***@***.***, ***@***.***,
***@***.*** 1.0.3.zip, ***@***.*** 1.18.10-v0.1.1.zip,
***@***.***, ***@***.***_v0.0.3.zip,
***@***.***, ***@***.***,
***@***.***, ***@***.*** Fix 1.18.10-v0.0.1.zip,
***@***.***, ***@***.***, ***@***.***
Trees-1.2.4.zip, ***@***.***_1.6.16.zip, ***@***.***_v1.18.8_v0.9.1.zip,
***@***.*** 1.6.7.zip, ***@***.***,
***@***.***, ***@***.***_v1.0.1.zip, ***@***.***_v1.8.0.zip,
***@***.***_v1.1.0.zip, ***@***.***_1.2.8.zip,
***@***.***, ***@***.***_0.1.3.zip, ***@***.***,
***@***.***_v0.5.0.zip, ***@***.***_v0.7.3.zip,
***@***.***_1.0.0.zip,
***@***.***_V0.1.19-pre.1_Debug.zip, ***@***.***,
***@***.***_VS1.18.6_netstandard2.0_v3.1.5.zip,
***@***.***_1.1.3.zip
9.10.2023 21:30:44 [Notification] Found 111 external assets in category lang
9.10.2023 21:30:44 [Notification] Found 527 external assets in category
patches
9.10.2023 21:30:44 [Notification] Found 81 external assets in category
config
9.10.2023 21:30:44 [Notification] Found 29 external assets in category
worldproperties
9.10.2023 21:30:44 [Notification] Found 394 external assets in category
sounds
9.10.2023 21:30:45 [Notification] Found 5201 external assets in category
shapes
9.10.2023 21:30:45 [Notification] Found 33 external assets in category
shaders
9.10.2023 21:30:45 [Notification] Found 0 external assets in category
shaderincludes
9.10.2023 21:30:45 [Fatal] Game Version: v1.18.8 (Stable)
10/9/2023 9:30:45 PM: Critical error occurred
Loaded Mods: ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***
System.Exception: Don't know how to instantiate item of class
'MaltiezFirearm' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in
VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType
packet, IWorldAccessor world, ClassRegistry registry) in
VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1
items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 580
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in
VintagestoryLib\Client\Systems\Startup.cs:line 392
   at
Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in
VintagestoryLib\Client\Systems\Startup.cs:line 334
   at
Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object
a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Crash written to file at "C:\Users\Jacob
Lopez\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

9.10.2023 21:30:45 [Notification] Found 8370 external assets in category
textures
9.10.2023 21:30:45 [Notification] Found 67 external assets in category music
9.10.2023 21:30:45 [Notification] Found 18 external assets in category
dialog
9.10.2023 21:30:45 [Notification] Found 17 external assets in category
compatibility
9.10.2023 21:30:46 [Notification] Reloaded lang file now with mod assets
9.10.2023 21:30:46 [Notification] Compatibility lib: 4 assets added, 0
assets replaced.
9.10.2023 21:30:46 [Notification] JsonPatch Loader: 2787 patches total,
successfully applied 111 patches, missing files on 547 patches, unmet
conditions on 1780 patches, no issues
9.10.2023 21:30:46 [Notification] Window was resized to 0 0? Window
probably got minimized. Will not rebuild frame buffers
9.10.2023 21:30:47 [Error] Entity shape for entity maltiezfirearms:bullet
not found or errored, was supposed to be at
maltiezfirearms:shapes/bullet.json. Entity will be invisible!
9.10.2023 21:30:47 [Error] Entity shape for entity maltiezfirearms:slug not
found or errored, was supposed to be at maltiezfirearms:shapes/slug.json.
Entity will be invisible!
9.10.2023 21:30:47 [Notification] Reloaded sounds, now with mod assets
9.10.2023 21:30:47 [Notification] Composed 1 4096x4096 entities texture
atlases from 500 textures
9.10.2023 21:30:48 [Fatal] System.IO.DirectoryNotFoundException: Could not
find a part of the path 'C:\Users\Jacob
Lopez\AppData\Roaming\VintagestoryData\Cache\unpack\BetterRuinsv0.2.2.zip_d5d03ac00033\assets\game\worldgen\schematics\overground\climates\desert-savanna\ruins-o1\savanna-desert-1.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String
fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions
options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath,
FileMode mode, FileAccess access, FileShare share, FileOptions options,
Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at Vintagestory.Common.FolderOrigin.LoadAsset(IAsset asset) in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\FileIO\Origins\FolderOrigin.cs:line
54
   at Vintagestory.Common.AssetManager.GetManyInCategory(String
categoryCode, String pathBegins, String domain, Boolean loadAsset) in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\FileIO\AssetManager.cs:line
310
   at
Vintagestory.ServerMods.WorldGenStructureBase.LoadSchematicsWithRotations[T](ICoreAPI
api, AssetLocation[] locs, BlockLayerConfig config, String pathPrefix) in
C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructureBase.cs:line
52
   at Vintagestory.ServerMods.WorldGenStructure.Init(ICoreServerAPI api,
BlockLayerConfig config, RockStrataConfig rockstrata,
WorldGenStructuresConfigBase structureConfig, LCGRandom rand) in
C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructure.cs:line
133
   at Vintagestory.ServerMods.WorldGenStructuresConfig.Init(ICoreServerAPI
api) in
C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\WorldGenStructuresConfig.cs:line
57
   at Vintagestory.ServerMods.GenStructures.initWorldGen() in
C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\6.GenStructures\GenStructures.cs:line
104
   at
Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line
1113
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginWorldReady()
in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line
182
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase
runPhase) in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line
595
   at Vintagestory.Server.ServerMain.Launch() in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line
525
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in
C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientProgram.cs:line
377
9.10.2023 21:31:06 [Notification] Exiting game now. Server running=False.
Exit reason: Game crashed.

**Comment by Th3Dilli** [comment]
this seems related to a mod so please try without mods or try to delete / move the mods folder from your data folder

It might also be an issue with multiple versions of the same mods so you can try deleting the cache folder in your data folder as well

your data folder is at `C:\Users\Jacob
Lopez\AppData\Roaming\VintagestoryData`
