### ISSUE TITLE
Wooden path is only created from ancient planks. 

### ISSUE THREAD

**Issue by kolan2222** [anegostudios/VintageStory-Issues#3144]
### Game Version

1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Wooden path is only created from ancient(aged) planks, though logically it can be created from any planks. But creation with other types of boards does not work.

### How to reproduce

Saw and ancient planks = works. 
Saw and ANY other planks = doesn't work.

### Screenshots

![изображение](https://github.com/anegostudios/VintageStory-Issues/assets/67638604/4dcad002-f524-4c3a-8cee-6ad89f9ab33a)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Not a bug
