### ISSUE TITLE
can't move locked chest

### ISSUE THREAD

**Issue by Runeranock** [anegostudios/VintageStory-Issues#3159]
### Game Version

1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

i try to move a locked chest and i can't do it, after that if i ant to open it i can't . i need to disconnect to reopen it.
and i can't move it.

### How to reproduce

create a locked chest, put csomme item in, try to move it.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is a mod
