### ISSUE TITLE
Transparency issue with hats as of 1.18, did not exist in 1.17

### ISSUE THREAD

**Issue by Ketsuna009** [anegostudios/VintageStory-Issues#3163]
### Game Version

1.18.14

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Any of the hats that have translucent pixels cause the hair-layer underneath to become translucent down to the head layer. 

I checked on my 1.17 installation and the issue is not present in the same hats. The issue also does not show on any clothing for any other body parts, only the hats. 

I checked with a fresh new installation of 1.18 too just in case it was related to mods previously installed. 

I have confirmed that this also shows for other players in multiplayer. 

I included screenshots of the snow goggles and the jailor's hat to show where the issue does NOT occur

### How to reproduce

Wear any of these hats and look at the player model in third person. 

Hats:
Shepard's cowl
Roll hat
Noble fillet (very easy to see with this one)
Minstrel hat
Messenger hat
Merchant hat
Lackey hat
Gold coronet
Gem encrusted hat
Fortune teller scarf
Fancy headdress

### Screenshots

![2023-10-20_13-08-31](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/4c091423-2157-49d4-8218-1411032cf1a4)
![2023-10-20_13-08-17](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/b36a44da-717c-41e9-928f-28f406745bea)
![2023-10-20_13-07-24](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/76111a2d-9ce2-4916-ab8e-9835c5da19df)
![2023-10-20_13-10-50](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/62714495-9faa-4ee5-adf4-73d0c8ec045c)
![2023-10-20_13-10-39](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/ff5f0f03-d2e8-4388-be28-8f37c6584f04)
![2023-10-20_13-10-29](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/31fdd368-8af0-425b-adea-8b41f9d5bff6)
![2023-10-20_13-10-17](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/7b7c395c-aa91-46db-b7f9-0b38ccd726a8)
![2023-10-20_13-10-06](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/e3cea0cf-f02d-4dee-9cb2-23b809965aa7)
![2023-10-20_13-09-52](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/c0ae86a0-d584-4b82-89a2-b8c92bbbce04)
![2023-10-20_13-09-38](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/692b4f6b-76bf-4630-a0c8-fb616b20a37a)
![2023-10-20_13-09-28](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/69b5a5a2-d9f9-4e7e-92e0-2ec90cb1787e)
![2023-10-20_13-09-14](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/bbeac05d-f2bb-4483-a389-9e30834d9162)
![2023-10-20_13-09-03](https://github.com/anegostudios/VintageStory-Issues/assets/5674618/8f3a6b45-b31a-4731-be31-3c622eb3f2d4)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
I guess it is fixed in 1.20 since all clothes are 3D now
