### ISSUE TITLE
Charcoal pile texture is anchored at top layer

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/VintageStory-Issues#3167]
### Game Version

v1.18.15

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

This is a very minor rendering bug.

Players are expected to shovel up the charcoal pile blocks left over from a charcoal pit. This shoveling slowly removes the top layers of the block. So one would expect the bottom of the pile to stay the same when a top layer is removed. However, instead the side textures of the block imply that the bottom of the block is progressively getting removed with every shovel action instead of the top of the block.

I think this bug comes from `CubeTesselator.DrawBlockFace`. That function calculates which portion of the side textures to draw for a partial cube. It currently anchors the texture coordinate of the top layer of the block and adjusts the texture coordinate of the bottom layer. Whereas, it should anchor the texture on the bottom layer and adjust the coordinates of the top layer.

### How to reproduce

1. Run the command `/giveblock charcoalpile-8`.
2. Place down the charcoal block.
3. In survival mode, use a shovel to one-by-one remove the layers of the charcoal pile, and see how the sides of the block change.

### Screenshots

Notice how the bottom layers of the blocks are not identical.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/21202621/4c90745e-adbe-481f-be15-73a7e5324263)

**Comment by Ragolution** [comment]
Reproduced on 1.18.15, but definitely a very minor bug.

**Comment by radfast** [comment]
Thanks for reporting, fixed from upcoming game version 1.20.0-rc.6
