### ISSUE TITLE
Glider schematic crafts in multiples of 2, ignores stack restrictions

### ISSUE THREAD

**Issue by Bumber64** [anegostudios/VintageStory-Issues#3173]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The schematic copying recipe as defined in ``schematiccopy.json`` takes a schematic and 2 parchment. The output is a stack of 2 schematics, with the original remaining in the crafting grid. The first issue is that 2 parchment = 2 copies is unnecessary when 1:1 will do. The second (as a consequence of the first) is that the output is a stack of 2 glider schematics, when they aren't supposed to stack at all. Splitting the stack of 2 and then trying to restack them will fail as expected.

The issue can be avoided in this case by changing the recipe to 1:1, although the underlying bug might show up elsewhere.

### How to reproduce

1. Give yourself a glider schematic and 2 parchment.
2. Put the schematic in the crafting grid along with the stack of 2 parchment.
3. Grab the output stack of 2 glider schematics. The original remains in the grid.
4. You now have a size 2 stack of glider schematics in addition to the size 1 stack.

**Comment by EnigmaticaGH** [comment]
This is actually intended (developers said so sometime on Discord a while ago) and appears in many places, such as being able to craft up to 512 mortar in a single stack, double-headed drifters dropping a stack of 2 temporal gears, etc. The developers decided to keep it this way to prevent item loss with large crafted item stacks while keeping the balance provided by the original stack size

**Comment by RedramVS** [comment]
It's correct that outputting stacks beyond normal is ok.  However the recipe should *not* produce 2 copies of the schematic, since the original remains.   It should only make 1 additional copy.
