### ISSUE TITLE
You can't play on LAN server without Internet

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [anegostudios/VintageStory-Issues#3174]
### Game Version

1.18.15

### Platform

None

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

It is impossible to connect to the local server without Internet. Even if you disable verification on the server, the client is forced to try to connect the master server before.

This also breaks the workaround for modders to test multiple players from the same account locally.

```cs
private void HandleLoginTokenAnswer(Packet_Server packet)
{
    if (!this.game.IsSingleplayer)
    {
        this.game.ScreenRunningGame.ScreenManager.sessionManager.RequestMpToken(new Action<EnumAuthServerResponse, string>(this.onMpTokenReceived), packet.Token.Token);
        return;
    }
    this.sendIdentificationPacket();
}
```

### Logs

```Log```

**Comment by DearFox** [comment]
Just a little information: this bug has been present since version 1.18.4 and higher

**Comment by tyronx** [comment]
thanks for the report, should be addressed starting from rc7
