### ISSUE TITLE
world spawn issues, invisible wall, invisible chunks

### ISSUE THREAD

**Issue by NyxBSomethin** [anegostudios/VintageStory-Issues#3180]
### Game Version

v1.19 pre 2

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

the game locked up my pc while I was tabbed out (that's what happens at the end of the logs where stuff's freaking out about tabbing) so I lost my screenshots so this is a description of what happened;
within 200 blocks of spawn, along a diagonal of chunk borders the land went to load in and loaded nothing. It's clear, you can see into the ground of the existing chunks like its been cut through, nothing past that spawns. On the mini map and map they also remain blank. You can't jump off, there's an invisible barrier or something.

### How to reproduce

no idea, it was a brand new world, so i would assume it might be a world gen issue. I lowered the range to equator to 50k and did the gravel/sand/cave in setting, but other generation settings are standard survival

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13197488/client-main.txt)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in todays pre4
