### ISSUE TITLE
Can't mine trees

### ISSUE THREAD

**Issue by NyxBSomethin** [anegostudios/VintageStory-Issues#3181]
### Game Version

v1.19 pre 2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Can't mine trees. I only tried with a flint axe, but I am seeing in the discord some others have tried on all axes/trees and it doesn't look like they've added their own report here yet. Presumably all trees and axes have this issue, though I can't personally confirm.
When you mine them the particles that drop look sort of like those for ice or snow, I assume it's glitched leave particles?

### Logs

```Log```

**Comment by Zeee-eeek** [comment]
Can agree. I have the same problem.

**Comment by DejFidOFF** [comment]
Same here

**Comment by Craluminum2413** [comment]
Fixed in pre.3
