### ISSUE TITLE
Crash when creating new world in wilderness survival 

### ISSUE THREAD

**Issue by theOddApe** [anegostudios/VintageStory-Issues#3183]
### Game Version

v1.19.0-pre3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When I create a new world selecting the mode wilderness survival, the world is created but the client crashes at the moment to place the player in the world.
Same happens if I restart the game and try to open the above world.
No issues with normal survival or creative.

### How to reproduce

1. create new world in wilderness survival
2. it crashes

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13198958/client-main.txt)

**Comment by Davis1055** [comment]
Can confirm this also happens to me!

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13198979/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13198980/server-main.txt)

**Comment by theluckyone17** [comment]
Occurs under Linux as well, after creating a new world using wilderness survival mode: "System.NullReferenceException: Object reference not set to an instance of an object."
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/13199847/client-crash.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13199848/server-main.txt)

**Comment by tyronx** [comment]
thanks for the report, I believe this should be fixed in the pre4 that i will release today, otherwise please reopen the issue
