### ISSUE TITLE
Cannot chop trees

### ISSUE THREAD

**Issue by d3x0r** [anegostudios/VintageStory-Issues#3185]
### Game Version

v1.19-pre2

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

https://discordapp.com/channels/302152934249070593/1167857340519809085

Cannot chop trees... made a stone axe and chop on a tree, it goes through the steps of looking broken and then resets to normal and doesn't drop any wood.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It was fixed in pre.3
