### ISSUE TITLE
Relabelling the crate leaks the label texture atlas entry

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/VintageStory-Issues#3198]
### Game Version

v1.19.0-pre.2

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Unlike the labelled chest, the crate label stores the label texture inside of the block texture atlas. [BlockEntityCrate.FreeAtlasSpace](https://github.com/anegostudios/vssurvivalmod/blob/5a5528e1e95325741537ef152c813a8a69acd890/BlockEntity/BECrate.cs#L534) is supposed to free the label texture when it is no longer used.

The texture is freed when the block is deleted or the unloaded (by unloading the chunk). However, the texture is not freed when the contents of the crate are changed and a new label is drawn. Specifically, BlockEntityCrate.OnBlockInteractStart should call BlockEntityCrate.FreeAtlasSpace, but it does not.

The texture atlas caches the labels for each item type that is in a crate. So repeatedly relabelling the same crate with the same item does not use additional atlas slots.

### How to reproduce

1. Use creative mode to get a crate with a blank label, 2 different objects to eventually put in the crate, and a piece of charcoal for writing the labels.
2. Place the crate with the blank label in the world.
3. Shift right click the first item into the crate.
4. Shift right click the blank label with the charcoal to draw the item in the crate on the label.
5. Right click the crate to take out the first item.
6. Shift right click the second item into the crate.
7. The label still shows the first item. Shift right click the label with the charcoal to update the image on the label.
8. Run ".debug exptexatlas block" to save the texture atlas. The texture atlas will be saved as blockAtlas-0.png in the Vintage Story program directory (not the VS data directory).
9. Look at the blockAtlas-0.png and see how many crate labels it contains. The crate labels will be either on the inner row or inner column next to the black area on the bottom right corner of the image. If the leak reproduced, there will be a label for both the first and second items. If the leak did not reproduce, only the second label will be in the image.

### Screenshots

This shows the crate with the second item inside and second label.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/21202621/192ac26a-7216-4582-a45a-a51b040ace1a)

This is part of the texture atlas showing a label for both arid dirt and fireclay, even though only fireclay should be in the atlas.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/21202621/e066d38c-3e3c-4057-a6fa-ba1a5bef48e3)

### Logs

Labelling the crate does not produce any logs.

**Comment by tyronx** [comment]
thanks for the report! this should be fixed in rc5
