### ISSUE TITLE
Problème de crash du jeu 

### ISSUE THREAD

**Issue by NiohBogh** [anegostudios/VintageStory-Issues#3199]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Le jeu crash lors du démrage ou peu après avoir lancer. Tous les mods / fichiers du jeu sont bien installer je ne comprends pas pourquoi le jeu crash

### How to reproduce

Lancer le jeu, et il crash 

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/149955255/d5dad9e3-d801-4f1e-b6f5-6bd6ed9bd157)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13260067/client-main.txt)

**Comment by NiohBogh** [comment]
> ### Game Version
> _v1.18.15
> 
> ### Platform
> Windows
> 
> ### Modded
> Modded
> 
> ### SP/MP
> Multiplayer
> 
> ### Description
> Le jeu crash lors du démrage ou peu après avoir lancer. Tous les mods / fichiers du jeu sont bien installer je ne comprends pas pourquoi le jeu crash
> 
> ### How to reproduce
> Lancer le jeu, et il crash
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/149955255/280537348-d5dad9e3-d801-4f1e-b6f5-6bd6ed9bd157.png)
> 
> ### Logs
> `Log` [client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13260067/client-main.txt)

**Comment by Craluminum2413** [comment]
Remove all mods and try again

**Comment by NiohBogh** [comment]
How can i do that ?

**Comment by Craluminum2413** [comment]
In "AppData\Roaming\VintagestoryData\Mods" folder

**Comment by NiohBogh** [comment]
i dont find this folder

**Comment by NiohBogh** [comment]
i've do that, but doesnt work matter
