### ISSUE TITLE
Game freeze when knapping with empty hands

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#320]
Start knapping with a flint then left click with empty hands on the knapping surface causes the game to hard freeze until killed by the user. 

Need to gather some more on this. From what I know is that it mostly happens on AMD cards.

Confirmed freezing on: 
- Windows 7, v1.9.14, Radeon HD 6950

Not freezing on:
- Linux, v1.9.14, Radeon R5 M330
- Win 10, Radeon RX 550

Please report your version and Graphics card model if this bugs happens to you as well

**Comment by brummbar7** [comment]
As one of the people affected by this, I'd also clarify that it happens not only with empty hands, but in fact if you're holding any object other than the appropriate interaction material (stone/flint for knapping, clay for clay forming).   So I have to be very careful to keep the correct items in hand.

I also get the same freeze with wood piles, if I break an object in front of them, and am still holding down the button and it interacts with the wood pile.  So if I break a grass block in front of a wood pile accidentally, or in that one ruin with wood piles, if I break a cobble block, and behind is a wood pile.

**Comment by tyronx** [comment]
this seems fixed, at long last
