### ISSUE TITLE
Luxuries trader buys unobtainable book

### ISSUE THREAD

**Issue by Bumber64** [anegostudios/VintageStory-Issues#3204]
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The Luxuries trader buys the item type "lore-book-aged-orange" with the category "diaries". It seems, however, that "lore-book-aged-orange" is only obtainable with the categories "research" and "jonas". The "diaries" category only generates for the item types "lore-book-aged-darkbeige" and "lore-scroll", which the trader does not buy.

The trader should probably buy "lore-book-aged-darkbeige" diaries instead, which you can get through panning.

Related to issue #1020

**Comment by RedramVS** [comment]
@LukeUnbound  I took his word on this one and changed it to darkbeige, but wanted to tag you in on it since you know the book situation better than me, so you may want to double-check.
