### ISSUE TITLE
Chatbox does not register first keypress.

### ISSUE THREAD

**Issue by siriusgithub** [anegostudios/VintageStory-Issues#3208]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

After pressing "Enter" for the chatbox to appear the first keystroke is not registered. All other keys afterwards enter in normally. This applies to all characters (/, abc, 123, *&^, "(spacebar), etc."

Example: to write the sentence "hello world" I have to type on my keyboard "hhello world" instead. x2 h

### Logs

```Log```

**Comment by siriusgithub** [comment]
"t" was rebound to "Enter" to open chatbox
after resetting back to the original this problem is now gone. setting "t" to any other letter is fine ("n" was used) but "enter" key does not work

**Comment by Th3Dilli** [comment]
fixed in 1.19.0-rc.8
