### ISSUE TITLE
Some commands are registered way too late

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#3212]
### Game Version

v1.19.0-pre.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

**ModSystemCommandHandbook** doesn't get commands that are registered after sending **syntax packets**.
For example, **GuiDialogWorldMap** registers commands only after **ModSystemCommandHandbook** already sent syntax packets, thus `.map` command never ends up in command handbook,

### Screenshots
![image](https://github.com/anegostudios/VintageStory-Issues/assets/69315569/69638537-7c76-4c58-a837-9f42d6870771)

**Comment by Th3Dilli** [comment]
ty, now fixed with next 1.19 pre release
