### ISSUE TITLE
Chisel failures when using a mod

### ISSUE THREAD

**Issue by XirixNL** [anegostudios/VintageStory-Issues#3222]
### Game Version

v.1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Whenever I try a mod and creating a new world, my first attempt to chisel to make an axe or knife is going well but when I go for another attempt to make an axe I just can't seem to chisel any blocks away from the blueprint. The piece of flint just breaks.
 
I have in Settings my Microblock Chiseling on: most cubic blocks instead of Stone, wood and bricks. 

### How to reproduce

Install one the most populair mods.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Most likely a mod issue
