### ISSUE TITLE
Add option to fill cooking pot via water blocks

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#323]
It's me again!
I got back into the game after a while, and I noticed that you can only use a bucket to get water into a claypot, which seems very counter intuitive.
You should be able to just submerge the pot into a body of water to fill it.

Additionally, it seems like the soup recipes (That require water and thus copper) are the least efficient ones, so they would be more useful in the early game.

**Comment by Balduranne** [comment]
You could use the Sprint+Right Click method, which would make it consistent with the bucket usage too

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
