### ISSUE TITLE
Strange appearance of hands with SSAO enabled

### ISSUE THREAD

**Issue by zsuatem** [anegostudios/VintageStory-Issues#3230]
### Game Version

v1.19.0-pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Strange looking hands with SSAO enabled.
An ugly filter appears on the hand added in 1.19 when SSAO is enabled. 

It also occurs in immersive mode but is less noticeable.

Probably affects all versions 1.19.0-pre.X. Checked on pre.5 and pre.6.

### Screenshots

SSAO High
![image](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/0e6b1386-df03-4b2b-a07b-9ca4123b5d52)

SSAO Medium
![image](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/36273e24-bd45-4e85-8da8-985d10d622f1)

SSAO Off
![image](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/a1e1b194-63dd-479c-8e82-a7af7176b8d9)

Immersive First person mode & SSAO High
![image](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/b0284054-652a-446c-9d79-5588080e192b)

Immersive First person mode & SSAO Off
![image](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/499caee5-3547-44bb-93a0-fee024798323)

Specs
![image](https://github.com/anegostudios/VintageStory-Issues/assets/17302628/10ddf6dc-1723-4a4b-9ffc-8ae99604a964)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in v1.19.0-rc.2
