### ISSUE TITLE
[v1.19 pre7] unable to remove prospecting readings

### ISSUE THREAD

**Issue by ruenaros** [anegostudios/VintageStory-Issues#3240]
### Game Version

v1.19 pre7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Unable to delete prospecting reading waypoints

### How to reproduce

Right click any reading, click "confirm" on the delete reading prompt, and nothing happens

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed in pre10
