### ISSUE TITLE
Arms twisting

### ISSUE THREAD

**Issue by ArcticCuddlefish** [anegostudios/VintageStory-Issues#3241]
### Game Version

v1.19 pre-7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Only Mods are Status HUD and HUD Realtimeclock.

During the course of looting a surface ruin and fighting a few surface drifters, character arms started drifting left. I think this may be associated with breaking a block while being hit by rocks, but have not yet been able to reproduce. The only way I was able to fix this was by restarting the game.

While arms were twisted, was unable to change POV, screen stayed put but target reticle disappeared and then reappeared as I cycled "views"

### How to reproduce

I tragically cannot determine it T_T

Loot ruins while surface drifters who throw rocks at you. One got through and hit me, but I THINK it was breaking half-buried blocks while being hit by rocks.

### Screenshots

![2023-11-18_14-10-12](https://github.com/anegostudios/VintageStory-Issues/assets/81587655/8450e488-736f-4710-8633-b77d12907f23)
![2023-11-18_14-10-01](https://github.com/anegostudios/VintageStory-Issues/assets/81587655/b98e849d-4064-4cfb-badb-e595beec0cb9)
![2023-11-18_14-10-09](https://github.com/anegostudios/VintageStory-Issues/assets/81587655/2d949c37-1cd9-443e-b146-bbc4cc7d1b40)

### Logs

```Log```

**Comment by tyronx** [comment]
is this still an issue in rc.4?

**Comment by ArcticCuddlefish** [comment]
I have not had it happen since! I'll do some more specific ruins-combat and see if I can get it again, but I think you can assume it's gone if you don't hear back.

**Comment by tyronx** [comment]
awesome, thanks
