### ISSUE TITLE
Meteorite/Ruins Missing Textures 

### ISSUE THREAD

**Issue by ArcticCuddlefish** [anegostudios/VintageStory-Issues#3242]
### Game Version

v1.19 Pre7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Only Mods are Status HUD and HUD Realtimeclock.

It looks like a meteor intersecting with new ruins creates a mixed block with an unknown texture.

### How to reproduce

Presumably find a world with a meteor crashing into a new ruin. Suevite is visible behind that torch.

The seed for this world is 2089876478, and the coords of this problem are visible in the screenshot.

### Screenshots

![2023-11-17_13-56-31](https://github.com/anegostudios/VintageStory-Issues/assets/81587655/17e453f3-76d9-4519-b507-ea4ee3f3b2bd)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
I was not able to reproduce that but I am pretty sure this was the issue all the structures with chiseled blocks had and should be solved by now
