### ISSUE TITLE
Rain-on-glass error

### ISSUE THREAD

**Issue by ArcticCuddlefish** [anegostudios/VintageStory-Issues#3244]
### Game Version

v1.19 Pre-7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Only mods are Status HUD and HUD Real Time Clock

Plain glass slab makes a tinkling rain sound when there is no rain.

Rain sound occurs whether there is roof over the inner side (the side the glass is aligned with) or not

### How to reproduce

Make a cobblestone granite wall with a window 2 high by 4 wide. Switch plain glass slabs to vertical-only mode and place in the 8 window spots with the glass aligned with inside edge (stand outside and place them).

My current wind is 78% with partly cloudy skies and no rain. Rainfall is common here, it's June 1st, and it's nighttime.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.20
