### ISSUE TITLE
Add ability to cancel/change knapping.

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#325]
Simple enough - Sometimes I'll misclick and pick the wrong thing to knap, effectively wasting a stone. While it's not that big a loss, it's a little annoying that my only recourse is to smash the stone and start over instead of picking a different thing to craft before I start removing voxels. 

An option to do that with clayforming would be great too.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
