### ISSUE TITLE
You can Add Infinite ingots to Anvil

### ISSUE THREAD

**Issue by KonaCoffeeDrgn** [anegostudios/VintageStory-Issues#3250]
### Game Version

1.18.15

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### **Dejank Smithing Request**

**Believed impacted Code:**

ItemMetalPlate.cs and ItemIngot.cs
- https://github.com/anegostudios/vssurvivalmod/blob/master/Item/ItemMetalPlate.cs
- https://github.com/anegostudios/vssurvivalmod/blob/master/Item/ItemIngot.cs

Should include in the TryPlaceOn(), an event to ensure that ignots and plate can be added if and only if (IFF) it would provide the full resource, since adding material only adds height (with a [Max Height of 6) one could just check that a [Max Height] has not been achieved and [Max Height] would not be exceeded by adding ItemMetalPlate or ItemIgnot to Anvil.

**Why is this important:**
1. Mechanic is not explained in anyway, (the Player Handbook does not mention a Max height and The wiki Fails to mention a max height for voxel count.(https://wiki.vintagestory.at/index.php/Smithing))
2. Some recipes require 5 ignots (ie: the Anvil Base and Anvil Top) With potentially more to come. an end user may not know they can not just add 5 ignots in the beginning, without learning post mortem.
3. Adding additional ignots past 3 ignots will allow you to add ad infinitum, consuming the ignot and providing no value. 

**How would you communicate this error:**
I would communicate this the same way you communicate Using Copper on Steel by disallowing the action and communicate via Error 
`TriggerIngameError(this, "notequal", Lang.Get("Must be the same metal to add voxels"))`

You could use language such as:
 `TriggerIngameError(this, "notequal", Lang.Get("Try Hammering down your piece before adding additional voxels"))`

### How to reproduce

1. Add 8 Ignots to 2 Forges. 
2. Heat forges with Charcoal or compatible Coal.
3. Add All 8 ignots, You will notice there is no value after 3, and 5 will be consumed without throwing an error.  

### Screenshots

You can get an error for trying to add wrong metal but not trying to add too much metal.
![Error](https://github.com/anegostudios/VintageStory-Issues/assets/151813311/213eec00-9724-43ae-8608-372cf55a4fed)

### Logs

N/A

**Comment by Th3Dilli** [comment]
has now been fixed for next release, ty for the PR
