### ISSUE TITLE
Crashes when talking with a trader/merchant

### ISSUE THREAD

**Issue by TobyGentlemane** [anegostudios/VintageStory-Issues#3256]
### Game Version

v1.19.0-pre.7 (Unstable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Crashes when talking with a trader/merchant

### How to reproduce

Talk with trader

### Logs

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/13467510/client-crash.txt)

**Comment by TobyGentlemane** [comment]
Okay so it only happens if I play LAN /using a server on the pc and then joining locally. The problem does not exist in normal singelplayer

**Comment by tyronx** [comment]
looks like a mod issue to me. Please disable mods and see if the issue persists
