### ISSUE TITLE
Show HUD in screenshots for non-100% resolutions

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#326]
Sometimes I want to take a screenshot of the menus, either to show a bug or just plain _show off_. Since there's a dedicated button to toggle HUD, maybe the screenshot button could just capture what's on the screen, menus and all?

**Comment by tyronx** [comment]
Its a bit of a lacking feature. The HUD is shown in screenshot, but only if the screen resolution in the graphics settings is at 100%. Need to still code a special solution for non-100% resolutions.

**Comment by Balduranne** [comment]
Crap, I forgot about that. My bad. I guess the menus should stay at 100% and get overlayed or something

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by tyronx** [comment]
also this should now work, actually
