### ISSUE TITLE
The game closes when I search for something in the help window (H)

### ISSUE THREAD

**Issue by melfos** [anegostudios/VintageStory-Issues#3260]
When I try to search for help in the help tutorial that is activated with the "H" key the game immediately closes. The strange thing is that it is not with all the options but when I search, for example, what is on the chests. That's where the game ends. This doesn't happen if I search for foundry, for example. It is only with some themes that the error occurs. The version I have purchased is 1.18.15 (stable) and I have an 11 generation Intel Core I5 PC with 12 Megabytes of RAM. I am attaching the game crash file that appears when the program is closed. I just bought the game 2 days ago and I'm already having problems.

[VSCrashReporter.deps.json](https://github.com/anegostudios/VintageStory-Issues/files/13483428/VSCrashReporter.deps.json)
[LogCrashVS.txt](https://github.com/anegostudios/VintageStory-Issues/files/13483436/LogCrashVS.txt)

**Comment by Craluminum2413** [comment]
Mods are causing this crash, the game has nothing to do with it
