### ISSUE TITLE
[v1.19.0-pre.7] Invisible unfinished copper part

### ISSUE THREAD

**Issue by sk4r** [anegostudios/VintageStory-Issues#3263]
### Game Version

v1.19.0-pre.7

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### How to reproduce

1. Start smithing
2. Pick up the unfinished part
3. It's invisible in the inventory and in the world if thrown, but it's possible to interact with it.
Did not try other metals.

### Logs

```Log```

**Comment by dmitriyklimchuk-Calyx** [comment]
The same issue for any unfinished Work item 
![image](https://github.com/anegostudios/VintageStory-Issues/assets/124671494/62faff45-4a00-4c33-b935-ba84da59e7ba)

**Comment by RedramVS** [comment]
Confirmed.  Probably affects all metals, as in addition to copper work items, it is also true of iron ones.

**Comment by radfast** [comment]
Fixed in next upcoming version. Thank you for reporting!
