### ISSUE TITLE
It's sill not updating

### ISSUE THREAD

**Issue by ypoop** [anegostudios/VintageStory-Issues#3265]
Automatic update had been fixed, from memory, with 1.18.14. So you have to do a manual update, one last time, to 1.18.15, and the further automatic updates will be ok.

_Originally posted by @Saricane in https://github.com/anegostudios/VintageStory-Issues/issues/3251#issuecomment-1825645054_

Now what?
![Vintage update bug 2](https://user-images.githubusercontent.com/135677096/286779077-fa1b1f30-3fd7-438f-85a9-58383dff70fb.PNG)

**Comment by Craluminum2413** [comment]
@ypoop Update it manually through site

**Comment by ypoop** [comment]
@Craluminum2413 How?
