### ISSUE TITLE
Lighting bug with chiseled blocks

### ISSUE THREAD

**Issue by Burgersim** [anegostudios/VintageStory-Issues#327]
**Game Version:** v1.10.7
**Platform:** Windows
**Modded:** No

### Description
When right-clicking a block with a chisel to make it into a chiseled block, the block seemingly gets lighter, so chiseled blocks don't look like the normal blocks anymore, so you can't mix them well in a building.

### How to reproduce
1. Make an Iron Chisel.
2. Use it on different Stone Variants. (right-click)
3. See the difference when placing a "normal" block next to the converted chiseled block.

### Expected behavior
The Chiseled Block shouldn't change color.

### Screenshots
![StonesToChisel](https://user-images.githubusercontent.com/26793150/64992929-30362800-d8d5-11e9-9906-ec6397b91dbd.png)
Here the bottom row are chiseled blocks, and I placed normal blocks on the top row to show the difference.

**Comment by tyronx** [comment]
ohwait, thats a new bug. Fixing it now

**Comment by copygirl** [comment]
Can this issue be closed, now?

**Comment by tyronx** [comment]
yea, this is fixed
