### ISSUE TITLE
[v1.19.0] Cave-ins don't happen when they should

### ISSUE THREAD

**Issue by stinky-lizard** [anegostudios/VintageStory-Issues#3273]
### Game Version

v1.19.0-pre7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I messed around with trying to get cave-ins on 1.19.0-pre7 today, and I found that it's really hard to trigger them when they should trigger. If I'm reading the code right, in stone.json, non-cracked rock has between a 12.5% and 2% chance to collapse, even when not supported by anything. This means most of the time, rock stays suspended, and doesn't really need any support.

### How to reproduce

1. Open a creative world in 1.19.0-pre7 with cave-ins enabled. 2. Build a pillar of granite rock. 3. Break the supporting blocks, leaving two rock blocks suspended in the air. (Breaking all but a single one will drop the rock.) 4. Most of the time, the rock stays suspended, despite "Instability" reading 100% on the block info.

### Screenshots

![ezgif-4-7d98ca9666](https://github.com/anegostudios/VintageStory-Issues/assets/38111803/ad632908-8f42-4296-8c38-d41f785c8b75)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
the cave in system got some update and should work better now, 1.19.3
