### ISSUE TITLE
Getting killed by food gives the player a cryptic (untranslated?) death message

### ISSUE THREAD

**Issue by Azagwen** [anegostudios/VintageStory-Issues#3275]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Happened to me twice while I played, and didn't pay close enough attention to what I ate. Being killed after eating a Death cap sends off a confusing death message `ingameerror-poprivilege-buildbreak-dead`

### How to reproduce

Eat a death cap, or a meal containing a death cap with low enough health to be killed by it

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/30528331/4be2e2ab-5dba-4397-ac24-cf3b9b1601ec)

### Logs

N/A

**Comment by Bumber64** [comment]
I think it might be separate from the death message? IIRC, you get a message like that when you try to place a block right after you've been killed. The message could be indicating that the client is still trying to eat the food while the server has just informed the client that the player is now dead.
