### ISSUE TITLE
[1.19.0-pre.9] Invisible players in multiplayer

### ISSUE THREAD

**Issue by AncletYinglet** [anegostudios/VintageStory-Issues#3288]
### Game Version

v1.19.0-pre.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Player appears invisible in multiplayer environment. Issue on both sides; I am invisible to them, and they are invisible to me.

### How to reproduce

- Join 1.19.0-pre.9 server
- Invite a friend
- Observe

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/148595378/dedd971c-163a-4a06-99a1-75f4163a1234)

### Logs

```Log```

**Comment by Rexxios** [comment]
Yep, happens to me too

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
