### ISSUE TITLE
Ability to light charcoat pit with torch

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#329]
It would be nice if we didn't have to place a fire pit to light a charcoal pit. In many cases it results in some odd-looking extrusions at the top of the pit that doesn't look that great. Simply holding right click with a torch to set the wood pile on fire and then cover it up could do the trick, no?

**Comment by Harlekin13** [comment]
I think sneak+right click like with other things (forge, bloomery, anything in the world that's not a fireplace) would be better.

On the other hand the way it is now could be (insignificantly) better performance wise as the game doesn't have to check if it's a valid charcoal pit everytime a stack of firewood is set aflame...

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
