### ISSUE TITLE
cant join a server with 100 mods

### ISSUE THREAD

**Issue by That1GitHubUser** [anegostudios/VintageStory-Issues#3291]
Running on 64 bit Windows with 24506 MB RAM
Game Version: v1.18.15 (Stable)
09/12/2023 10:58:14: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.0.15, signs@1.0.1, bettercrates@1.6.0, betterruins@0.2.4, blacksmithname@1.1.4, hqzlights@1.1.1, driedpeat@1.0.2, extendedcrafts@1.1.0, extrachests@1.7.0, caninae@1.0.5, capreolinae@1.0.5, pantherinae@1.0.9, gwb@1.0.1, hackedlocusts@1.0.0, hideandfabric@1.3.0, craftableLitChimney@1.0.0, mannequinstand@1.0.1, materialaging@1.1.0, meteoricexpansion@1.2.4, millwright@1.1.1, moreclay@1.0.1, MoreTorchHolders@1.0.0, nailsmold@1.0.1, newfiesdrifters@1.0.4, pipeleaf@1.2.2, playerlist@1.6.0, potontheshelf@1.0.0, qptech@1.14.1, rackablefirestarter@1.0.0, she1fish@1.1.0, tprunes@1.1.0, translocatorengineeringredux@1.4.7, game@1.18.15, wildcrafttrees@1.2.4, wildcraft@1.6.6, abcsreborn@0.1.2, animalcages@2.2.0, autoatlas@1.0.1, betterjonasdevices@1.0.2, blacksmithgloves@1.0.1, calendar@1.0.0, canbeignited@1.1.0, commonlib@2.2.0, composter@1.1.0, cooperativecombat@1.1.1, decoclock@0.9.1, divisionoflabor@1.0.6, expandedfoods@1.6.8, extrachutes@1.0.0, fishing@1.1.5, fromgoldencombs@1.4.25, grassiergrass@1.0.0, hudclock@3.4.0, sailboat@1.1.0, knapster@2.6.3, liquidcontainers@1.2.0, moreanimals@1.2.4, claywheel@1.1.0, prospecttogether@1.2.4, rpcommand@1.0.6, scarecrow@1.3.1, scythemold@1.0.0, snowballs@1.0.1, stonebakeoven@1.1.1, storageoptions@1.0.1, th3dungeon@0.2.0, usefulstuff17@1.2.0, vanvar@3.2.2, creative@1.18.15, vsinstruments@1.2.4, survival@1.18.15, woodenfortifications@0.0.4, xlib@0.7.4, bullseye@2.5.0, em@2.4.1, feverstonewilds@1.4.3, sleekdoorglass@1.0.0, morecandles@1.1.3, playercorpse@1.8.0, rifteye@0.3.2, simplewinddirection@1.0.2, stonequarry@3.1.7, vsradiomod@0.1.4, wolftaming@1.8.0, xskills@0.7.5, bricklayers@2.4.0, moreroads@1.5.4
System.Exception: Don't know how to instantiate collectible behavior of class 'considerpetfood' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateCollectibleBehavior(CollectibleObject collectible, String code) in VintagestoryLib\Common\ClassRegistry.cs:line 220
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 192
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 563
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 381
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 334
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 09/12/2023 10:39:29, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB3DD.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_d9145cde-3a68-4a50-8fd6-8cfb05fde97c

Analysis symbol: 
Rechecking for solution: 0
Report Id: c5a4a560-18d3-49a5-be2a-f8164abab200
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 09/12/2023 10:39:28, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_d9145cde-3a68-4a50-8fd6-8cfb05fde97c

Analysis symbol: 
Rechecking for solution: 0
Report Id: c5a4a560-18d3-49a5-be2a-f8164abab200
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 09/12/2023 10:39:23, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x56e0
Faulting application start time: 0x01da2a855adbfcec
Faulting application path: C:\Users\\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report ID: c5a4a560-18d3-49a5-be2a-f8164abab200
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Caused by mod
