### ISSUE TITLE
v1.19.0-pre.9 No Meat Fur or Feathers when harvest Animals, No Loot on Drifters

### ISSUE THREAD

**Issue by Dalorend** [anegostudios/VintageStory-Issues#3292]
### Game Version

v1.19.0-pre.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Killed about 20 adult rabbits, 5 Chickens, 2 foxes and a racoon in a single day.
No hides feathers or meat. carcass turns to bone and harvests as normal.

Either this is terrible RNG or there is something odd going on?

new Vanilla world no mods.

Added client logs if helpful?

### Logs

```Log```
https://gist.github.com/Dalorend/831111adc5a220d9d18556d307a93ba7

**Comment by Dalorend** [comment]
Not getting any corpse harvestable drops. Drifters or animals. havent seen any wolves or bears yet so not sure if they are effected too.

**Comment by Dalorend** [comment]
Randomly started dropping loot correctly. and nearly died to a wolf spawning on me.... odd.

**Comment by MarcosMaurelli** [comment]
I can correlate, It happens to me with bears, wolfs, fishes, chickens, new added animals and drifters, into any new game on pre9
![no loot](https://github.com/anegostudios/VintageStory-Issues/assets/63467569/50bd62a7-7561-47e0-9f48-781e891112b9)

**Comment by MarcosMaurelli** [comment]
I can correlate, It happens to me with bears, foxes, wolfs, fishes, chickens, new added animals and drifters, into any new game on pre9.
![no loot](https://github.com/anegostudios/VintageStory-Issues/assets/63467569/5d858f6a-7d36-4464-81e1-deb1af0d5dc2)

**Comment by N0Game** [comment]
I've been having the same issue in pre 9 but when i roll back to pre 8 i get meat again, i don't think that mobs are dropping anything

**Comment by jevarlec** [comment]
This issue should be reopened as there are multiple users with the same problem.

I checked this with a vanilla world, hunted 15 animals, no drops at all. Would uploading a world file be useful?
