### ISSUE TITLE
v1.19.0-pre.9 Game crashes when opening color accurate map

### ISSUE THREAD

**Issue by Karidwen** [anegostudios/VintageStory-Issues#3294]
### Game Version

v1.19.0-pre.9

### Platform

None

### Modded

None

### SP/MP

None

### Description

No mods loaded. The game crashed at some point when opening the map. After extensive testing reproduced the issue on worldseed 1729196413
The more worlds I made (deleting previous ones) the faster the crash happened when opening the map. Now it happens right away when making a world with the same world seed.
Does not happen right away on fresh worlds.
Does not happen if I leave the brown map.

### How to reproduce

1. Make a new world and in customization select color accurate map.
2. Open the map with M
3. if it does not crash right away, run around some, opening the map now and then.
4. a game world which has already crashed will keep crashing sooner and with less walking around if a new world is generated with the same seed - with the color accurate map on

### Logs

server main https://gist.github.com/Karidwen/4ee091f003acff125f6b97e57203f245
server debug https://gist.github.com/Karidwen/4ef29fb033d25333e2a77f298f6654f4

**Comment by Karidwen** [comment]
Clean install of the game in v1.19.0-pre.9 and setting game graphics quality low, still results in crashes when opening the map if the color accurate map is turned on. Happens now with any game made (in SP).

**Comment by Craluminum2413** [comment]
Where is crash?

**Comment by Karidwen** [comment]
Crashlog does not open, if that is what you mean. The game just closes and the created game shows as 0 minutes played (or last saved trime if one would have played it for some time without issue). There seems to be something on the map which causes the crash. If the seed does not have it right away in seen distance, it works fine, but once the thing causing the issue is in map range, opening the map crashes the game.

**Comment by Th3Dilli** [comment]
I assume it may have been some other issue or it has been fixed (not sure what may have  caused it) and has not occurred again yet so will close this for now
