### ISSUE TITLE
v1.19.0-pre.9 Missing/Mismatched Ruins Textures and Overlays

### ISSUE THREAD

**Issue by Dalorend** [anegostudios/VintageStory-Issues#3296]
### Game Version

v1.19.0-pre.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Few places this has occured.
 Dark soil texture where gravel in microblocks should be.
Random "Air Block" and unknown block under.
Missing mold overlay,

### How to reproduce

Not sure. Haven't seen other stone types in this world yet.

these ruins were fine while playing yesterday when I had a seperate issue that resolved itself today (related to no harvestable items from animals or drifters).

Only Exception is the Air Block which has happened many times in previous 1.19 versions.

### Screenshots

![2023-12-10_03-45-33](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/eef5f3e4-4123-42da-bcfb-b24ad1597bda)
![2023-12-10_11-17-44](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/8de4924a-2258-48f0-9279-22d86564d4dc)
![2023-12-10_11-20-37](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/9a51c0e3-2cc8-490f-a5a2-0e49f1bc1da6)
![2023-12-10_11-20-40](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/d30c2f50-a96c-4c06-9939-a1e7ce525a8a)
![2023-12-10_03-45-36](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/92dbd98f-1d32-4032-86e3-3f1c82072e13)
![2023-12-10_11-05-36](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/f408da76-20ed-4422-84a3-d7aa1cd0ec3c)
![2023-12-10_11-05-38](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/17eaeb99-17f7-45e3-8c1f-de32609cf9a7)

### Logs

```Log```

**Comment by Dalorend** [comment]
![2023-12-10_14-28-37](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/0647b6e7-10c4-4b80-8b25-84f211b6fe94)
![2023-12-10_14-32-56](https://github.com/anegostudios/VintageStory-Issues/assets/132353257/b203d957-15ce-412c-a558-6cd9a602dfb3)

Appears that Tule and Thatch have also been somehow bugged?

**Comment by Karidwen** [comment]
This also happens on traders. 
![image](https://github.com/anegostudios/VintageStory-Issues/assets/153385890/17dabadb-95e7-4f99-a451-7b1ded544fb5)

**Comment by Th3Dilli** [comment]
ty,
this should have been solved already, so the latest rc.5 should have this fixed
