### ISSUE TITLE
[v1.19.0-pre8] Perpetual cavein everywhere around me, even on reload

### ISSUE THREAD

**Issue by stinky-lizard** [anegostudios/VintageStory-Issues#3298]
### Game Version

v1.19.0-pre8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was digging down to near the mantle, and seemingly randomly a cave in was triggered when I dug a block. This was strange, as I was only digging straight down and using ladders, but whatever - it didn't hurt me, so I figured it was fine.
Then I went back up to the surface, and there were cracked rocks all over the place. Here's a Youtube video showing this: https://youtu.be/hCe0fCrybHA (I normally get >60 FPS, it was already bad at this point, but not completely unplayable quite yet.) I couldn't see cracked rocks showing up, but there was definitely activity happening - there were mudslides happening out of nowhere. The FPS also TANKED like crazy, to the point where it was completely unplayable when unpaused.

I tried to keep going, but the FPS just got worse. Then, a wolf got me and I died. I respawned back at home, and the FPS was still bad. I even found cracked rocks outside my house. They definitely weren't there before.
Here's the worst part, though: I saved and quit the game - even quitting to desktop - and when I re-entered, it was still bad. Like, <1 FPS bad. At this point, I decided to just cut my losses, since it was _not_ getting better, and came here.

Here's the save: https://drive.google.com/file/d/1f668a5pvzDUPlRD0whUo1UlZxXSbdYaz/view?usp=sharing

### How to reproduce

I'm not sure. I think it may have been random? I was digging straight down near the mantle when it seems to have started.

### Logs

```Log```
<script src="https://gist.github.com/stinky-lizard/efc6c47959bec8687ffda42b827ee440.js"></script>

**Comment by radfast** [comment]
Thanks for reporting, fixed in next upcoming 1.19 release ... maybe today ;)
