### ISSUE TITLE
Drifters don't appear on surface at nights

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#33]
1.5.2.2, official server.
Melloyello (?), me, Saraty noticed that there are no drifters on the surface at night. They definitely appear in caves, locusts too. Wolves still appear at usual places. 
UncleSid in Discord #bugs said he didnt notice any mobs for the last 3 updates.

**Comment by copygirl** [comment]
I feel like I remember talk about new mobs appearing on the surface instead and having drifters be less common, but yes, not sure if this is intentional (or should be). Marking as a bug for now, considering Saraty was also concerned..?

**Comment by Heptagon-ru** [comment]
Fixed in 1.5.2.something, closing
