### ISSUE TITLE
instant died

### ISSUE THREAD

**Issue by duysw2** [anegostudios/VintageStory-Issues#3302]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

i always get killed by wolfs, bear and drifter with a single blow, i dont know how make them so strong in spite of armored, them still slay me with one hit

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/153526941/3be00f24-c62c-48d1-800f-a08ec3fe6117

### Logs

```Log```

**Comment by Bumber64** [comment]
https://www.vintagestory.at/forums/topic/10913-receiving-multiple-damage-until-instant-death-edit-2/

Are you using the Pet AI mod?

**Comment by duysw2** [comment]
am not install Pet AI in to the game, but i install Carry Capacity. Maybe this mob make this instant kill bug
