### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by AngryWraith** [anegostudios/VintageStory-Issues#3310]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Found a duplication glitch while using the auction section of trader.

### How to reproduce

1. Place item inside the auction slot of trader.
2. Close without removing the item.
3. Item drops on the floor and can be picked up.
4. Re-open auction section and the item still appears there and can be taken back.

The items dissapear when dropped but weapons etc are still usable in this state.

### Screenshots

![2023-12-15_21-25-19](https://github.com/anegostudios/VintageStory-Issues/assets/153956309/1bce7c15-7db8-4a7e-aaf7-516bf5b8a565)
![2023-12-15_21-26-07](https://github.com/anegostudios/VintageStory-Issues/assets/153956309/9fe9edc3-7597-4a16-a0f1-d05f4f892752)

**Comment by Th3Dilli** [comment]
thanks to korobya this will be fixed in the next released version
