### ISSUE TITLE
Crash on Harvesting Salmon

### ISSUE THREAD

**Issue by egocarib** [anegostudios/VintageStory-Issues#3312]
### Game Version

1.19.0-pre.9

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Encountered crash upon harvesting a salmon on local PC multiplayer server

Only using one mod that does not modify this behavior (AutoMapMarkers), so I don't think this is mod-related.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/3429497/61145df2-4f6e-484d-9b2e-71215336a78f)

### Logs

```Log```

**Comment by RedramVS** [comment]
@egocarib I could not reproduce this in single player.  Has it happened repeatedly, or just a one-time thing?

**Comment by egocarib** [comment]
Appears to be a duplicate of #3289
