### ISSUE TITLE
v1.19 : Polar bear can still jump as usual

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3314]
### Game Version

v1.19.0-pre9

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Starting from v1.19, polar bear is not supposed to be able to jump (balanced by a better swim speed). But he can still jump 3 blocks as usual.

### Screenshots

![bear1](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/db6b7447-fc0d-4407-a013-fe006f70ec00)
![bear2](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/738c0fbd-9724-49da-ab62-52258947d982)

**Comment by CookieBoy21** [comment]
This Issue was fixed in v1.19.0-rc.7/8 Dejank Redux and can be close. I checked it in 1.19.3 (Stable) and this bug is no more.
