### ISSUE TITLE
Vanilla 1.19.0 pre 9 Lot of errors in server-main.txt

### ISSUE THREAD

**Issue by teknik1** [anegostudios/VintageStory-Issues#3318]
### Game Version

v1.19.0 pre 9

### Platform

None

### Modded

None

### SP/MP

None

### Description

I get this log each time i create  a new world :

### How to reproduce

Just create a new world in vanilla 1.19.0 pre 9 with  Dev log on and see server-main.txt

### Logs
https://gist.github.com/teknik1/e808b77c4373f6611172a5d79a3ab730
[](https://gist.github.com/teknik1/e808b77c4373f6611172a5d79a3ab730)

**Comment by tyronx** [comment]
thanks for the reports, these should be gone in pre10
