### ISSUE TITLE
Vanilla 1.19.0 pre 9 Glitch when you get healed or taking damage

### ISSUE THREAD

**Issue by teknik1** [anegostudios/VintageStory-Issues#3319]
### Game Version

v1.19.0 pre 9

### Platform

None

### Modded

None

### SP/MP

None

### Description

This glitch is here since a long time ago when you take any damage or healing you can glitch into the wall.
[Vidéo (2).webm](https://github.com/anegostudios/VintageStory-Issues/assets/9663048/206efec4-e570-4ae4-a0a6-73832057f065)

You can also glitch up just seat down and jump again and again...

Maybe if player take damage when inside a block will help to solve this problem ?
And disallow jumping when we are seated ?

You can get roll back when you eat vintage-beaf each time you get healed this make little roll back.

### How to reproduce

Run and get healed with poultice or take damage from hunger, stone, ennemies....
I believe taking damage or get healed create a little rollback that allow you to glitch.

### Logs

```Log```

**Comment by pingouyn** [comment]
v1.19.0.rc6
Was about to open a new case and saw this one.  Just glitched through the wall whilst low on temporal stability, hence taking damage.
Also glitched through a wall 3 times before, always in cave whilst being attacked by drifters.  I guess I need to learn how to play better, wink!
=>  I corroborate this post for the taking damage part at least.

**Comment by Th3Dilli** [comment]
ty, this was fixed in 1.19.3

**Comment by pingouyn** [comment]
Happened to me again in 1.19.3 ...

**Comment by Th3Dilli** [comment]
oh sorry, it's in 1.19.4

**Comment by pingouyn** [comment]
ok ty :)
Didn't mean to be a pain, I am still playing in 1.19.3.
