### ISSUE TITLE
Water not updating when part of submerged block (Reed)

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#332]
**Game Version:** 1.10.9 (Old issue though?)
**Platform:** Windows
**Modded:** Not really
### Description
![2019-09-19_20-36-01](https://user-images.githubusercontent.com/10406037/65290501-83022080-db1d-11e9-9aad-69559450dd48.png)
Basically this. Dug a hole next to a submerged reed, but it wouldn't let the water through.

**Comment by copygirl** [comment]
Is this the right place to mention that water "physics" in Vintage Story in general are very weird?

**Comment by Balduranne** [comment]
> Is this the right place to mention that water "physics" in Vintage Story in general are very weird?

Probably. I remember when submerged reeds didn't count as water for crop moisture.

**Comment by Craluminum2413** [comment]
Also no longer relevant since 1.17
