### ISSUE TITLE
 [v1.19.0-pre.10] Animals and other players are invisible on Mac

### ISSUE THREAD

**Issue by sk4r** [anegostudios/VintageStory-Issues#3323]
### Game Version

v1.19.0-pre.10

### Platform

Mac

### Modded

Vanilla

### SP/MP

None

### Description

On Mac, in both single and multiplayer animals and other players are not visible, but their shadows and labels are. Pre-8 was fine, then pre-9 broke player visibility in multiplayer. Mac is ARM with Sonoma OS (latest). This is on Ultra High or Absolute Minimum setting.
First person hands _are_ visible.

On Linux that looks fine, both as a host and as a client.

### Logs

[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/13735161/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13735162/client-main.txt)

Logs suggest enabling `glDebug` but doing that crashes the game on startup:
```
System.NotSupportedException: Your graphics card does not seem to support gl debug mode (neither GL_ARB_debug_output nor GL_KHR_debug was found)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.set_GlDebugMode(Boolean value) in VintagestoryLib\Client\ClientPlatform\GLImpl.cs:line 38
   at Vintagestory.Client.ScreenManager.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ScreenManager.cs:line 134
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 311
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by tyronx** [comment]
Set glDebugMode to false in your clientsettings.json or delete the file entirely

**Comment by sk4r** [comment]
@tyronx , `glDebugMode` is already false, deleting clientsettings.json didn't help.

**Comment by tyronx** [comment]
You seem to be editing the wrong file then because this error is only thrown if this setting is enabled.

**Comment by tyronx** [comment]
ohwait, I'm dumb, sorry

**Comment by tyronx** [comment]
thanks for the report, this should be fixed next release

**Comment by sk4r** [comment]
thanks and no worries :smile:

**Comment by sk4r** [comment]
@tyronx , I'm still seeing shader compile errors in v1.19.0-rc.1 and the invisible creatures issue. Not sure if the fix made it in.
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/13757824/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13757825/client-main.txt)

**Comment by noridas80** [comment]
@sk4r I saw the compile error in the shader files mentioned in your log. Removed the #if ALLOWDEPTHOFFSET > 0 line and the corresponding #endif, and then the character displayed just fine.

**Comment by sk4r** [comment]
@noridas80 , thanks, that works! Taking out the lines between works too. Not sure which is the proper way, I couldn't tell much difference visually :smile: 

```diff
--- assets/game/shaders/standard.fsh.bak	2023-12-23 11:14:55
+++ assets/game/shaders/standard.fsh	2023-12-23 11:27:06
@@ -25,7 +25,7 @@
 uniform vec2 baseUvOrigin;
 uniform int normalShaded;
 uniform float damageEffect = 0;
-#if ALLOWDEPTHOFFSET > 0
+#if defined(ALLOWDEPTHOFFSET) && ALLOWDEPTHOFFSET > 0
 uniform float depthOffset;
 #endif
 
@@ -111,7 +111,7 @@
 	outColor.rgb *= b;
 	outGlow = vec4(glowLevel + glow, extraGodray - fogAmount, 0, outColor.a);
 
-#if ALLOWDEPTHOFFSET > 0
+#if defined(ALLOWDEPTHOFFSET) && ALLOWDEPTHOFFSET > 0
 	// This likely tanks performance in any other scenario so we do only only for the first person mode rendering. See also[ https://www.khronos.org/opengl/wiki/Early_Fragment_Test#Limitations](https://www.khronos.org/opengl/wiki/Early_Fragment_Test#Limitations)
 	gl_FragDepth = gl_FragCoord.z + depthOffset;
 #endif
```
```diff
--- assets/game/shaders/entityanimated.fsh.bak	2023-12-23 11:24:13
+++ assets/game/shaders/entityanimated.fsh	2023-12-23 11:25:45
@@ -30,7 +30,7 @@
 uniform float glitchEffectStrength;
 uniform int entityId;
 uniform int glitchFlicker;
-#if ALLOWDEPTHOFFSET > 0
+#if defined(ALLOWDEPTHOFFSET) && ALLOWDEPTHOFFSET > 0
 uniform float depthOffset;
 #endif
 
@@ -104,8 +104,8 @@
 	
 	outGlow = vec4(glowLevel + glow, 0, 0, color.a);
 	
-#if ALLOWDEPTHOFFSET > 0
+#if defined(ALLOWDEPTHOFFSET) && ALLOWDEPTHOFFSET > 0
 	// This likely tanks performance in any other scenario so we do only only for the first person mode rendering. See also[ https://www.khronos.org/opengl/wiki/Early_Fragment_Test#Limitations](https://www.khronos.org/opengl/wiki/Early_Fragment_Test#Limitations)
 	gl_FragDepth = gl_FragCoord.z + depthOffset;
 #endif
-}
\ No newline at end of file
+}
```

**Comment by tyronx** [comment]
oh it needs a defined test too? oof

**Comment by noridas80** [comment]
@sk4r I'm glad it worked. I just tried it out and it happened to work, but I don't fully understand the details behind it.

@tyronx I have immense respect for your work.
Wishing you continued growth and success in your future projects.

**Comment by tyronx** [comment]
Thanks! This is fixed in rc4 btw.
