### ISSUE TITLE
Error after closing game

### ISSUE THREAD

**Issue by AlexanderwithaA** [anegostudios/VintageStory-Issues#3325]
### Game Version

1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When I exited the game and pressed the power button on my computer (I was shutting down for the night) I got an error message preventing the computer from shutting down. I had left the game running for a while paused.

### How to reproduce

1 exit your world and close the game
2 press the power button on your pc near to when the window disappears
3 wait for any errors

I only had prospectorinfo v4.3.0 mod installed

### Screenshots

![Screenshot 2023-12-21 023626](https://github.com/anegostudios/VintageStory-Issues/assets/101488091/0101593a-a7b4-415b-88d8-bbf6dc08cd7c)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is most likely graphics driver issue, update your graphics drivers
