### ISSUE TITLE
(Thatch) roofing does not insulate.

### ISSUE THREAD

**Issue by NaturalHate** [anegostudios/VintageStory-Issues#3329]
### Game Version

v1.18.15

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Thatch roofing, particularly it seems to be the sides of the blocks, does not insulate, causing the interior not to count as a cellar or room.

I don't know if this is intended behavior for roofing in general, even though we clearly don't apply any insulation materials to any other building block either, but especially thatch roofing should generally insulate (if not all roofing in general), as thatch is quite literally used for its excellent insulating properties in real life as well and already quite a pain to gather. Adding insult to injury, hay blocks work perfectly fine as insulator, but look horribly blocky for a roof.

### How to reproduce

Build a cellar or room, try to seal it with roof blocks, fail.

**Comment by NaturalHate** [comment]
So @Rythillian says it's fixed in the upcoming 1.19 (for all roof blocks, or just thatch?).

But @Craluminum2413 closes it as "not planned" (meaning it is intentional?) and labels it as "duplicate" (of what? I searched closed issues for it and couldn't find any issues regarding it so please at least reference the issue that it is a duplicate of).

Getting mixed signals here.

**Comment by Craluminum2413** [comment]
@NaturalHate This is original issue 
https://github.com/anegostudios/VintageStory-Issues/issues/1458

**Comment by Craluminum2413** [comment]
Even though original issue is about blue clay roofing, It was fixed for all roofs
