### ISSUE TITLE
Add command to teleport to waypoint

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#333]
Unless it's already there and I don't know how to use it.

**Comment by tyronx** [comment]
you mean like, in survival mode?

**Comment by Balduranne** [comment]
No, to the admin commands. I tried using the teleport command to teleport to a waypoint by name or number, but I don't think that's an option. I know I could use the coords, but using the waypoint name or number on the list would be easier.

**Comment by copygirl** [comment]
Something like `/waypoint teleport <number|name>` (maybe `tp` for short) would be nice, indeed.

**Comment by Craluminum2413** [comment]
> https://www.vintagestory.at/forums/topic/3212-the-quest-for-the-lost-frames-v1140-rc5rc6
> Tweak: added /tpwp [starts with name] to teleport to a waypoint. Requires the teleport privilege.
