### ISSUE TITLE
Crash when Sorting Inventory

### ISSUE THREAD

**Issue by drbubba72** [anegostudios/VintageStory-Issues#3334]
### Game Version

1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Just clicked the Sort button in inventory

### Logs

Running on 64 bit Windows with 32698 MB RAM
Game Version: v1.18.15 (Stable)
12/24/2023 6:56:37 PM: Critical error occurred in the following mod: xinvtweaks@1.5.7
Loaded Mods: aculinaryartillery@1.0.15, advancedsmithing@1.3.0, africanmonitorlizards@1.0.7, asianmonitorlizards@1.0.1, autoclose@1.0.1, autopanning@1.0.1, bandedgeckos@1.2.0, bettercompost@1.0.1, bettercrates@1.6.0, betterruins@0.2.4, bettertraders@0.0.2, bushmeat_meals@1.0.7, cavecontent@1.0.1, cellardoor@1.3.0, conquestnaturepack@0.0.4, hqzlights@1.1.1, dungeonsandshafts@0.2.3, extraclayforming@1.0.0, extrainfo@1.5.3, fancysky@1.0.6, FarmSurvival@1.3.0, fixroads@1.3.1, capreolinae@1.0.5, foundrymod@1.0.0, giantgouramis@1.0.2, gravelsandfix@1.0.2, HangingOilLamps@1.0.1, healingwhilesleepingfix@1.0.1, burntimetimes2@1.0.0, indappledgroves@0.4.10-dev.8, itemlights@1.0.2, juicyores@1.0.0, longerburntime@1.0.1, mannequinstand@1.0.1, mcd1@1.0.0, meteoricexpansion@1.2.4, midnight-texturepackNS@1.1.0, millwright@1.1.1, moremolds@1.4.2, leadroof@1.3.4, newworldgianttortoises@1.0.3, pondfrogsi@1.2.3, palisademod@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.3.0, rainfrogs@1.2.1, roas@1.0.0, she1fish@1.1.0, simplifiedtanning@1.0.0, smokychimneys@1.0.0, spyglass@0.4.5, stacks@1.0.4, temporal_gears_stack@1.0.0, truesunfishes@1.1.2, usefuldrifterloot@1.0.3, game@1.18.15, weaponpackalphaunoff@1.4.0, wildcrafttrees@1.2.4, wildcraft@1.6.6, ancienttools@1.5.11, animalcages@2.2.0, ar-class@0.0.6, egocaribautomapmarkers@2.6.0, autoatlas@1.0.1, betterfirepit@1.1.2, betterjonasdevices@1.0.2, canbeignited@1.1.0, cancrops@0.1.17, carryon@1.6.1, composter@1.1.0, expandedfoods@1.6.8, fancyplanters@1.2.0, fishing@1.1.5, fromgoldencombs@1.4.25, glowingprojectiles@1.1.3, greenbegone@1.0.0, hudclock@3.3.0, knapster@2.6.3, knifecut@1.2.0, loreweapons@1.0.1, metaltongs@1.1.0, moreanimals@1.2.4, moredoor@1.0.0, morestickcrafting@1.0.2, petai@1.8.1, prospectorinfo@4.3.0, simplestep@1.0.8, sprucedup@1.0.3, stepup@1.2.0, stonebakeoven@1.1.1, stonerailings@1.1.0, storagecontroller@1.0.3, storageoptions@1.0.1, updatedtexturesandmodels@0.8.2, vtpp@1.1.0, creative@1.18.15, survival@1.18.15, woodfp@1.0.0, xlib@0.7.4, ageofconfession@1.3.0, bugnetcompatibility@1.0.1, bullseye@2.5.1, cancropsprimitivesurvivalcompat@1.0.1, feverstonewilds@1.4.3, plumpkins@1.0.1, shellpan@1.0.0, simplewinddirection@1.0.2, slanted_display_cases@1.0.0, tieredtradebags@1.0.0, xinvtweaks@1.5.7, xskills@0.7.5, cancropsxskillscompat@1.0.3
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at XInvTweaks.InventoryUtil.SortInventory(ICoreClientAPI capi, IInventory inventory, Int32 first)
   at XInvTweaks.ChestSortDialog.OnSort()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 308
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 293
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1862
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 209
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/24/2023 11:40:38 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1D99.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A7B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AEA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AF7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B17.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_befd3be3-8bd5-45e4-a77e-f006d784b2bb

Analysis symbol: 
Rechecking for solution: 0
Report Id: e516c818-fdaf-434c-8afa-36ec96f014c2
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/24/2023 11:40:33 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2c84
Faulting application start time: 0x01da3543f27f6972
Faulting application path: F:\Games\Vintagestory\Vintagestory.exe
Faulting module path: F:\Games\Vintagestory\Lib\openal32.dll
Report Id: e516c818-fdaf-434c-8afa-36ec96f014c2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/21/2023 10:31:44 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B9.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1121.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER119F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER119D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER11CD.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_953ba208-9b08-42d9-87f4-2d0b6d3fa473

Analysis symbol: 
Rechecking for solution: 0
Report Id: 88c0e462-46fd-4f0f-9811-a721a85bd9e5
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }

**Comment by Craluminum2413** [comment]
This is caused by Xandus Inventory Tweaks mod
