### ISSUE TITLE
Inexplicable crash on alt-tab

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#334]
**Game Version:** 1.10.9
**Platform:** Windows
**Modded:** Slightly

### Description
I alt-tabbed to stuff in my browser and do other stuff. After a while I alt tabbed back in the game, pressed Back to Game and it just CTD. I feel like it ran out of memory or something.

https://pastebin.com/Cvvfy8su

**Comment by tyronx** [comment]
thanks, should be fixed for the next version
