### ISSUE TITLE
No sheep or goats spawning after creating a new world.

### ISSUE THREAD

**Issue by LilacAlstro** [anegostudios/VintageStory-Issues#3344]
### Game Version

v1.19.0-rc.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I created a new survival world on a temperate starting environment (realistic world). No sheep spawned at all. I tried creating survival worlds with cold and warm starting locations to see if sheep or goats spawn elsewhere, but I didn't find anything within several thousand blocks. Other animals, such as different kinds of deer spawned just fine.

Mods used:
ProspectorInfo
Chiseltools
HUDclock

### Logs

```Log```

**Comment by RedramVS** [comment]
This is not a bug per se.  Most goats have a narrow set of spawn conditions - higher elevation, not too forested, and not too rainy.  So you first have to find high elevation areas, and then they also have to be moderate or lower forest, and same for rain.   There's a couple that spawn at low elevations in the tropics.   We may adjust these over time, but it's more an issue of balancing, not a bug.
