### ISSUE TITLE
Game WhiteScreens and Crashes/Closes Discord

### ISSUE THREAD

**Issue by ProphetManX** [anegostudios/VintageStory-Issues#3346]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

While playing and active in the game, everything is fine.  But when I step away from the computer for 5+ minutes, when I come back, the game has gone to a fully white screen and my discord has also closed completely.  The game is more hanging than crashed/closed, but it does close discord?  

### How to reproduce

Other than Opening the game, joining my realm that we're self hosting and other's are still connected to, I just walk away with the game open and connected to the game, and it eventually (within 15 minutes) has this problem.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
If you disable `Advanced=>Hardware Acceleration` in Discord, it will never close when game crashes

**Comment by Craluminum2413** [comment]
Also I don't see any crash here, post it and I reopen this issue
