### ISSUE TITLE
Tall Fern color mismatch & lacking animation when in flowerpot / planter.

### ISSUE THREAD

**Issue by NaturalHate** [anegostudios/VintageStory-Issues#3348]
### Game Version

v1.18.15

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Tall ferns appear bright green and without animations when put into a flowerpot or planter.

### How to reproduce

1. Grab tall fern.
2. Put into flowerpot or planter.
3. ???
4. Profit

### Screenshots

![2023-12-27_20-57-37](https://github.com/anegostudios/VintageStory-Issues/assets/15324196/b8777341-79c9-45eb-8d64-8691ea8182ce)

**Comment by RedramVS** [comment]
This is fixed in 1.19

**Comment by NaturalHate** [comment]
@RedramVS The color mismatch still persists in 1.19.

**Comment by RedramVS** [comment]
Hmm, not sure what happened there.  Tyron has to cherry-pick things from master into the updates now, so that may have caused an issue.  Next time hopefully.
