### ISSUE TITLE
BadAtom

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#335]
https://www.vintagestory.at/forums/topic/948-game-doesnt-start-when-clientsettingsjson-is-present/?tab=comments#comment-5039

OpenTK team says they need debug info. So one would need to make a debug build for Corax and post it to https://github.com/opentk/opentk/issues/937

**Comment by Th3Dilli** [comment]
does not effect us anymore since we now use OpenTK 4 which does not have that code path anymore as far as I can see
