### ISSUE TITLE
linen sales scam

### ISSUE THREAD

**Issue by FoxBlood75** [anegostudios/VintageStory-Issues#3350]
### Game Version

v1.19 rc4

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I don't know if this has been reported yet, or if I'm doing this correctly... not familiar with the GitHub thing lol

basically you can buy linen for one gear, but you can sell 2 for 6 when they both come up on the menu at the same time... I showed up with only 2 linen and no gears, but walked away with I think 6 and 10 gears? luckily the available amounts limited the 'scam' or I'd be a millionaire lol
just your generic scam the npc merchant bug.. clothing merchant right near my base. a nice surprise, but I assume it wasn't intended

### How to reproduce

have linen and visit a merchant

### Logs

```Log```

**Comment by RedramVS** [comment]
Fixed for next rc
