### ISSUE TITLE
Linen wallpaper rotated wrong

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/VintageStory-Issues#3351]
### Game Version

v1.19.0-rc.4

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

In 1.19.0, decors seem to be automatically rotated by the renderer. Previously each decor block had to perform its own rotation. It looks like the linen decor is performing its own rotation on top of the default decor rotation. The end result is that the linen decor is only rotated correctly for the top face of a block.

### How to reproduce

1. Go into creative mode.
2. Get a piece of linen.
3. Right click on a block on any face except the top face.

### Screenshots

All of the pieces of linen in the screenshot are attached to the floating dirt block. All faces of the dirt block should be covered with linen, but instead the linen is coming out at wrong angles.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/21202621/202de8e4-2113-476f-bc7a-6f1dc6af8cbe)

**Comment by Saricane** [comment]
I can confirm.

**Comment by tyronx** [comment]
thanks for the report, will be fixed in rc5
