### ISSUE TITLE
Crucible disappeared after falling into a pit kiln.

### ISSUE THREAD

**Issue by RichMerr** [anegostudios/VintageStory-Issues#3352]
### Game Version

v1.18.5

### Platform

None

### Modded

None

### SP/MP

None

### Description

Picking up a hot crucible without tongs resulted in dropping into a pit kiln and burning up or disappearing. I hadn't played since tongs were introduced so I panicked not quite knowing what was happening. However, being it was hot I couldn't place it back on a tile and so it was in a dropped state. I then went out to get the materials to make the tongs and when I returned the crucible couldn't be found nor all the copper I had panned for in early game. The Strorage Vessel was done so I grabbed it looking for the crucible but couldn't find it. I then dug up all the adjacent tiles to the kiln and no crucible was found. 

### How to reproduce

Fill a crucible with 25 units of copper or so
Set up a pit kiln very close to the fireplace you'll use for a cucible for a storage vessel.
Set the pit kiln ablaze. 
Heat the fireplace to max wood temp then swap in charcoal to reach smelting temp
Pick up the crucible without tongs and either an autodrop happens or you drop the crucible next to or in the ablaze pit kiln. 
Perhaps observe the cucible is burning or setting green ground on fire.
Go gather reeds for rope and sticks for tongs
Return and observe the crucible is no longer present either next to or inside the pit kiln, and the copper contents are missing as well. 
Dig the adjacent low fertility soil blocks to the pit kiln and no crucible is found there either. 

### Logs

Not a crash, can provide if helpful.

**Comment by Craluminum2413** [comment]
Crucible is most likely burned out, I will close it for now
