### ISSUE TITLE
Deer and goats scale 3 block walls, 1.18 animals disappeared in 1.19 rc4

### ISSUE THREAD

**Issue by Rufkut** [anegostudios/VintageStory-Issues#3354]
### Game Version

v1.19.0-rc.4

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Two issues:

1. I loaded my 1.18.5 save in 1.19 rc4 without mods. All my animals (gen 15-20) disappeared. This includes pigs, sheep, chickens, and wolves I trapped. I can respawn those using creative and commands. 

2. Deer, moose, and goats can traverse walls that are 3 blocks or higher.  

### How to reproduce

I've made a low res video:

https://github.com/anegostudios/VintageStory-Issues/assets/114462701/f4551e5c-6411-48f5-8787-969721992e6b

### Logs

```Log```

**Comment by tyronx** [comment]
high step height is intentional, as for the disappearing animals, do you have the old savegame for me to reproduce this issue?

**Comment by Rufkut** [comment]
I loaded a backup of the save in 1.18.5. I made a copy and loaded it in 1.19 rc4 but was able to reproduce the disappearing animal issue. The animals were still present after updating. Nevertheless, here is the original backup save: https://www.mediafire.com/file/gss10lbuc6cxndp/LP_World_1.18.vcdbs/file
