### ISSUE TITLE
My game can not launche

### ISSUE THREAD

**Issue by rodo404** [anegostudios/VintageStory-Issues#3356]
### Game Version

v1.18.15

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

My game keeps craching when I launche it, I tried to uninstall it and re-install it but it doesn't solve the problem.
Im doing this on a new Pc and I have not install anything other than the browser Opera gx and Steam.

Thanks for helping me :)

### Screenshots

![image_2023-12-31_181152692](https://github.com/anegostudios/VintageStory-Issues/assets/155318760/e4341945-79bc-4f3f-9948-54f6ed1d3425)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Update your graphics drivers

**Comment by rodo404** [comment]
> Update your graphics drivers

I tried and their is no update available

**Comment by rodo404** [comment]
> Update your graphics drivers

thanks now it works
