### ISSUE TITLE
Rush Matting Disappears After Being Placed on Other Rush Matting

### ISSUE THREAD

**Issue by MiningTcup** [anegostudios/VintageStory-Issues#3357]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

After placing rush matting, if you then place another rush matting on the first rush matting, the second one appears above the first for one frame and then disappears without dropping.

**MODS:**

- ArrowheadsRecovery_v1.0.1.zip
- Auto Map Markers (1.18.6 ).zip
- bds.zip
- BetterFirepit-1.1.2.zip
- betterpitkilntimer_1.1.0.zip
- BetterSticks_v1.0.zip
- BlockPick.zip
- BuzzWords1.5.0.zip
- carcasses_are_frail.zip
- CarryOn-1.18-net7_v1.6.0.zip
- CreatureKilledBy-1.0.0.zip
- DropVinesAnyway-v1.0.2.zip
- FarmlandDropsSoil-VS1.15-v1.4.0.zip
- GlowingProjectiles-v1.1.3.zip
- HealingWhileSleepingFix-v1.0.1.zip
- hudclock-3.3.0.zip
- InstantFirepits_v5.0.0.zip
- LowerShield
- naturalnight.zip
- NightLight-1.3.6.zip
- PickUpFast.zip
- ProspectorInfo-4.3.0.zip
- ResinOnAllSides-v1.0.0.zip
- salmonfix.zip
- ScytheMore-v1.0.1.zip
- slabsandstairs_1.0.0.zip
- slvbearnerf.zip
- SticksFromFirewood.zip
- Unbreakable_Arrows_1.0.0.zip
- VisibleOre.zip
- VisibleTerraPretaParticles-v1.1.0.zip
- WholeLottaTreeSeeds-1.0.0.zip
- zoombuttonreborn_1.6.0.zip

### How to reproduce

1. Get 2 rush mattings
2. Place the first one
3. Place the second one on the first one

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/125408675/2def9f44-67bb-451d-97df-7bb4fcf71a57

**Comment by Craluminum2413** [comment]
Fixed in 1.20
