### ISSUE TITLE
Make it so that not all files are 0x777

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#336]
Corax suggests this at the end of the install.sh
`
find ${VintageStoryVerzeichnis} -type f -executable \! -name *.sh -exec chmod a-x \{\} \;`

**Comment by thehuntedpie** [comment]
If what you are trying to do is remove global execute permissions for any file that is executable but does not end in .sh, the command is

 `find ${DIRECTORY} -type f -executable ! -name '*.sh' -exec chmod -x {} \;` 

using bash 4.3.48(1) and find 4.7.0-git but should work in many previous and later versions of both

**Comment by Th3Dilli** [comment]
this is already fixed as of 1.19
