### ISSUE TITLE
Red currant mash is not usable as animal feed

### ISSUE THREAD

**Issue by Soadreqm** [anegostudios/VintageStory-Issues#3360]
### Game Version

v1.19.0-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Dry red currant mash can't be used as animal feed. Only tested red currants, possible that all fruit mash behaves the same.

### How to reproduce

1. Obtain red currants and fruitpress
2. Press the berries to get dry mash
3. Place the fruit mash into a trough near some pigs
4. Fruit mash in trough is not shown to be suitable for any animal, pigs will not eat it

### Logs

```Log```

**Comment by Th3Dilli** [comment]
This will be fixed with rc5, ty
