### ISSUE TITLE
Server not saved (in Server list) when restarting the game

### ISSUE THREAD

**Issue by Burgersim** [anegostudios/VintageStory-Issues#337]
**Game Version:** 1.10.9
**Platform:** Windows
**Modded:** No

### Description
When I load up my game, my game server is no longer in the list of Servers when I go to Multiplayer.

### How to reproduce
1. Start Game
2. Go to Multiplayer.
3. Clock "Add New Server"
4. Add a new Server.
Optionally: Join Server once.
5. Close Game.
6. Start game up again.
7. Go to Multiplayer.

### Expected behavior
Server that I added via "Add Server should stay in the list, when I load up the game again. I shouldn't have to add the Server anew everytime.

**Comment by tyronx** [comment]
Thanks for the report! This is now fixed for the next bugfix release

**Comment by Burgersim** [comment]
Thx a lot, I love how well the bug reporting works in terms of quickly fixing stuff nd listening to the people playing the game ^^
