### ISSUE TITLE
Blue and Brown dyed cloth recipes

### ISSUE THREAD

**Issue by FoxBlood75** [anegostudios/VintageStory-Issues#3371]
### Game Version

v1.19 rc5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The blue and Brown dyed cloth recipes are incorrectly cycling through plain cloth as well as the mordanted cloth.. just these two, the other 9 are fine

### How to reproduce

open the recipe
wait for the handbook to cycle through accepted components

### Screenshots

![2024-01-04_08-13-11](https://github.com/anegostudios/VintageStory-Issues/assets/86390967/378fbf02-937a-499e-8de9-b7ea6def2084)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
This is a feature since 1.17.0
> Woad blue now has its own dye barrel since it doesn't require a mordant
> Removed Brown dye until we add more pigment options for it. For now, cloth can be added to strong tannin to make brown cloth without needing a mordant

**Comment by FoxBlood75** [comment]
Got it.. I didn't realize the blue was cycling as well since they look the same lol. my bad :)
