### ISSUE TITLE
crate recipe not working

### ISSUE THREAD

**Issue by FoxBlood75** [anegostudios/VintageStory-Issues#3374]
### Game Version

v1.19 rc5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It looks like RC5 broke the crate recipe, I crafted a few in rc4 that are still there (background of the screenshot) , but cannot craft any more now.

It also looks like the texture for planks is rotated as well in the crafting grid..  a clue perhaps?
the texture is rotated the same when i place them, and i created a new world to make sure it wasn't just that save..

also, when holding shift and hitting H while targeting a crate it doesn't open up the handbook page.. don't know if that's related, but thought it might help :)

oh, and i tried it for birch and oak as well.. so it's not just pine.

### How to reproduce

attempt to craft a crate

### Screenshots

![2024-01-04_10-37-07](https://github.com/anegostudios/VintageStory-Issues/assets/86390967/434cc8cb-0329-4199-9714-db4235e9edf4)

### Logs

```Log```

**Comment by PurpleSlayerFish** [comment]
+ 
I think, problem produce for all types of planks block, i can't craft creates and open planks recipes in guidebook, and I think, planks have different texture as at last snapshot (it has horizontal direction in create recipe, but vertical produced after sawing)

**Comment by RedramVS** [comment]
Ya this is a result of the plank recipe change.  The plank recipe now ouputs 'ud' planks (up-down) but old recipes are looking for 'ns' (north-south) planks.  Please let me know of any other recipes that use the old plank blocks.

**Comment by CardboardDecoy** [comment]
here to bolster. on rc.6 and still not working
![image](https://github.com/anegostudios/VintageStory-Issues/assets/153793676/d6e0219b-b987-4d5a-a8d5-142f2a7fc431)

**Comment by benjsibley** [comment]
Here to bump. Appears to still not be working on rc.7 despite fix note:

> Fixed: Crate recipes handbook derp (API: was a bug in all recipes using CopyAttributesFrom)

This example is the oak crate recipe

![crate bug](https://github.com/anegostudios/VintageStory-Issues/assets/3493334/82278a12-c2cf-44b9-888e-6f46faa14afd)

**Comment by RedramVS** [comment]
Crate recipes no longer use plank blocks in 1.19 full release.  Just boards and a saw.
