### ISSUE TITLE
Crash on opening handbook page to linen sack

### ISSUE THREAD

**Issue by jirgs** [anegostudios/VintageStory-Issues#3385]
### Game Version

v1.19..0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Crashes instantly on selecting the linen sack in the handbook

### How to reproduce

Press H to open handbook, type in linen sack, click on it

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #3366
