### ISSUE TITLE
Boars with offspring attack on passive mode

### ISSUE THREAD

**Issue by Chase22** [anegostudios/VintageStory-Issues#3389]
### Game Version

1.19.0-rc.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I don't know if this is intended behaviour but the passive boars aren't as passive anymore when they have offspring. They attack the player as soon as they get close

**Comment by Th3Dilli** [comment]
thank you for reporting, this should be fixed with the next release
