### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by solomonova-nina** [anegostudios/VintageStory-Issues#3394]
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

При запуске сервера игра крашится

### Logs

```Log```
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/13848723/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13848724/client-main.txt)
[xlevelingdescription.txt](https://github.com/anegostudios/VintageStory-Issues/files/13848725/xlevelingdescription.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/13848726/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/13848727/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/13848728/client-crash.txt)

**Comment by Craluminum2413** [comment]
Try 1.19.0-rc.5 version
