### ISSUE TITLE
[1.19.0-rc.5] Typography error in "The Morning" scroll

### ISSUE THREAD

**Issue by AncletYinglet** [anegostudios/VintageStory-Issues#3396]
### Game Version

v1.19.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

```___NEWPAGE___``` appears on top of the third page of the scroll "The Morning" when right clicked to read. Does not appear as such in the journal.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/148595378/4e69c41c-45bb-4bda-bbae-b7de8a377914)

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.20, I assume it is fixed
