### ISSUE TITLE
Invisible meal in placed bowl and can't eat straight out of it

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#340]
**Game Version:** 1.11.0-pre.3
**Platform:** Linux
**Modded:** Yes
\- CarryCapacity
\- Resource Models
\- Farmland Drops Soil

### Description
The food in this bowl is missing when placed on the ground. It appears correctly when held or in my inventory. Additionally, the interaction hint is telling me that I can eat from the bowl in-world but the key combination doesn't have an effect.

### Screenshots
![image](https://user-images.githubusercontent.com/272586/67623382-e0784400-f824-11e9-9aee-64f9f8f73a95.png)

**Comment by tyronx** [comment]
Is that still broken in pre.5?

**Comment by copygirl** [comment]
Meal is now visible, but still can't eat from it in-world.

**Comment by tyronx** [comment]
Any chance you remapped some keys? Eating from a placed bowl seems to work for ne

**Comment by copygirl** [comment]
Looks like I can eat only when I'm holding an item in my hand. Which plays the eating animation with said item. If the item has use action like torches or poultice that seems to be prioritized. Looks most strange while holding a sword.
