### ISSUE TITLE
Broken Handbook Link

### ISSUE THREAD

**Issue by MarkuBu** [anegostudios/VintageStory-Issues#3403]
### Game Version

Stable and Nightly

### Platform

Linux

### Modded

None

### SP/MP

None

### Description

There is a link in the source string 'handbook-storable-displaycase' that doesn't work

<a href="handbook://block-displaycase-east">

### How to reproduce

Open the handbook
Search for any Ashlar Block
Klick on 'Display Cases'

### Logs

```Log```

**Comment by tyronx** [comment]
thanks, will be fixed for next rc
