### ISSUE TITLE
Unable to slaughter animals

### ISSUE THREAD

**Issue by Zarkonnen** [anegostudios/VintageStory-Issues#3404]
### Game Version

1.19-rc6

### Platform

Linux

### Modded

No

### SP/MP

Singleplayer

### Description

I started a new game in 1.19 rc5 (later upgraded to rc6) and in that game only, I am unable to slaughter animals. If I hold down shift and RMB, nothing happens. I've tried on multiple corpses and with multiple knives. It works in other games I created. I've uploaded the save at http://zarkonnen.com/static/bumble/media/uploads/noslaughter.vcdbs.zip

### How to reproduce

Unknown

### Screenshots

Picture a seraph with a knife standing in front of a hare.

### Logs

https://gist.github.com/Zarkonnen/00a558ecd8577aa5d9d0c88727198bc9
https://gist.github.com/Zarkonnen/b32cd66914faa537c8808d0fca5fe556

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next rc

**Comment by Zarkonnen** [comment]
Can confirm this is fixed. :angel: :hocho: :rabbit2:
