### ISSUE TITLE
Reed basket Traps disapear

### ISSUE THREAD

**Issue by Darkmessiah81** [anegostudios/VintageStory-Issues#3407]
### Game Version

v1.19.0-rc.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Reed basket Traps disapear after placing grain or other lure items in them. the item and the trap are gone

### Logs

```Log```

**Comment by pingouyn** [comment]
Same as #3417 ?
If so, could be fixed in 1.19.0.rc7 (?)
