### ISSUE TITLE
I can't open mods folder, it says "Can't open C/Users/User" even tho in installed it in F: disk

### ISSUE THREAD

**Issue by NaturalBambooStuff** [anegostudios/VintageStory-Issues#3408]
### Game Version

1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

it's in the title

### How to reproduce

idk, I simply installed Vintage Story and tried to enter mod folder. Maybe the case is that my PC User is called "User UA", not just "User", and the game seeks precisely for "C:/Users/User" without considering that in different systems this path may differ in letters. 
![1](https://github.com/anegostudios/VintageStory-Issues/assets/34127467/540cf366-2c57-4916-ac18-34e041105a8f)
It says "Windows can't find C:/Users/User. Check if the name is correct and try again." I wonder if there's a way to change the path in the game's config?

### Screenshots

![1](https://github.com/anegostudios/VintageStory-Issues/assets/34127467/5807501a-6796-4f20-87b7-2498cb26368c)

### Logs

```Log```

**Comment by pingouyn** [comment]
Most likely something to do with the space in your PC name.
It reminds me the issue I'm currently having issues with starting a linux server when the directory path to the server.sh bash script includes a space.

**Comment by Th3Dilli** [comment]
ty, this is fixed in 1.19
