### ISSUE TITLE
Vast "stone desert" generated seemingly between generation borders

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#341]
**Game Version:** 1.11.0-pre.3
**Platform:** Linux
**Modded:** Yes
\- CarryCapacity
\- Resource Models
\- Farmland Drops Soil

### Description
I've got a huge granite stone "desert" that generated for me, seemingly between terrain that was generated in `1.10` and `1.11` - I saw the new beaches on the other side.

### Screenshots
![2019-10-30_20-06-11](https://user-images.githubusercontent.com/272586/67891849-b6d85900-fb53-11e9-8e5d-afe1b445008f.png)

**Comment by tyronx** [comment]
hm. Thats bad.

**Comment by tyronx** [comment]
Found and fixed the issue for pre.4, yay \o/
