### ISSUE TITLE
Wake up at dawn please!

### ISSUE THREAD

**Issue by pwbaim** [anegostudios/VintageStory-Issues#3412]
Please add a config setting to wake up at dawn. Watching the clock leap in large intervals and having to close the character window and THEN hit space is beyond clunky and unreliable. Minecraft had this right all along. Alternatively, allow a choice when starting sleep to 'only sleep until dawn' if your bed will take you beyond it. Daytime is too short to waste.

**Comment by Craluminum2413** [comment]
@pwbaim You can sleep anytime you want, it doesn't require night, also it is a suggestion

**Comment by pwbaim** [comment]
> @pwbaim You can sleep anytime you want, it doesn't require night, also it is a suggestion. [Post suggestions here](https://www.vintagestory.at/forums/forum/5-suggestions/)

I posted in suggestions. Otherwise, your answer is offensive nonsense and has nothing to do with my request other than the word, 'sleep'. This is a serious QoL defect and I consider it a  design bug. What is the purpose of beds with increasing duration other than allowing you to sleep through the night? Especially when in the field where there is little to do but wait for daybreak to only lose a significant chunk of the next day because of this flawed mechanic. If you want feedback, don't be dismissive of serious feedback.
