### ISSUE TITLE
Trap is broken

### ISSUE THREAD

**Issue by Shadeloid** [anegostudios/VintageStory-Issues#3417]
### Game Version

1.19.0 rc 6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When placing grain on the trap, it disappears and i can't move animals

### How to reproduce

Make a basket trap, place it down and put grain in there.

### Screenshots

![2024-01-09_01-29-30](https://github.com/anegostudios/VintageStory-Issues/assets/72017889/e0775943-eae3-4a78-b434-870605854c6f)
![2024-01-09_01-29-37](https://github.com/anegostudios/VintageStory-Issues/assets/72017889/24449d70-cdbd-4f8a-9dab-3c10af7dc852)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks, please try again in the upcoming rc7
