### ISSUE TITLE
Sleep is broken in many ways

### ISSUE THREAD

**Issue by Malnaur2** [anegostudios/VintageStory-Issues#3418]
### Game Version

v1.18.15

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

The latest sleep-related bug I've encountered is broken progression for the still I finally built and used. I loaded the still, added wood, fired it up and went to sleep shortly afterward. While I slept, the wood burned away but no liquid was actually processed! This is even worse than cooking not progressing while you sleep but not as bad as healing not happening while you sleep and having almost no control over waking at dawn. You went to the trouble of creating three tiers of beds but have never finished the basic elements of what happens to the various timelines while you sleep. You have created a wonderful game but technical debt is piling up and QoL is suffering because of it. Don't be the team that only works on sexy new features and never fixes broken things because it's not sexy. I've been there and it's not pretty.

### How to reproduce

Build a still. Set up the still to work. Go to sleep. Check results when you wake up. Be disappointed.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.19
