### ISSUE TITLE
Animals don't react to long range attacks

### ISSUE THREAD

**Issue by kingdrasker** [anegostudios/VintageStory-Issues#3420]
### Game Version

v1.18.14

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When you're a certain distance away from animals and you hit them with rocks, arrows, or any ranged attack they don't respond. They stand still and are an easy target for another hit. Bears and other dangerous creatures can easily be taken down this way since it doesn't do anything even when hit from this distance.
Video for clarification:
https://vimeo.com/901100167?share=copy

### How to reproduce

1. Make sure you have a ranged weapon of some kind.
2. Stand a certain distance away from an animal, some high ground to make hitting easy.
3. Shoot your ranged weapon at the target.
4. Observe as the animal does not respond to the damage, doesn't run away or aggro.

### Logs

```Log```

**Comment by AreYSerious** [comment]
I hope this gets fixed it's a major bug in my opinion. And very immersion breaking.

**Comment by Craluminum2413** [comment]
Now they do in 1.20
