### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by liam-sy** [anegostudios/VintageStory-Issues#3421]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

In the "invent a fire" step of the tutorial, the player is told to craft an axe "in **yor** inventory," which is a misspelling of "in **your** inventory"

### How to reproduce

Progress to the "invent a fire" step of the tutorial

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does that typo exist in 1.19.0-rc.6?

**Comment by Craluminum2413** [comment]
Can't find typo in 1.19.0-rc.6
