### ISSUE TITLE
1.19rc6 - Can't harvest animals

### ISSUE THREAD

**Issue by gerbilfat** [anegostudios/VintageStory-Issues#3429]
### Game Version

1.19rc6

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It is not possible to harvest/butcher animals, either player-killed or found. Animal bodies can be pushed around by the player, and the UI indicates they can be harvested with a tooltip. I've tried removing grass around the animal, restarting the client, and rolling a new game with the same result. There's no errors in the logs. 

Running vanilla single player 1.19rc6 on Arch Linux. 

### How to reproduce

1. Start a new vanilla single player game.
2. Kill an animal or find a dead one.
3. Approach with a knife. The tooltip about harvesting appears over the animal. 
4. Attempt to harvest the animal. No harvest animation or sound effect plays. No loot appears.

### Logs

```Log```

**Comment by tyronx** [comment]
the animation doesnt work everything else seems to work fine for me

**Comment by tyronx** [comment]
please try again in rc7/rc8, and write here if the issue persists.
