### ISSUE TITLE
Butterfly Offset From Center In Display Cases

### ISSUE THREAD

**Issue by BluntTongs** [anegostudios/VintageStory-Issues#3433]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

Butterfly display case transformations are currently unsatisfactory. Though difficult to notice initially, it's hard to stop seeing how offset they are when they're placed into the case themselves. Some butterflies even clip outside of the case. Additionally, they possess a Y transformation to spin them to be parallel to the display case's edges, but they do not properly line up on a 90 degree turn and are still noticeably tilted in a direction (as demonstrated by their wingtips not matching side-by-side).

Butterflies noticeably shifted to the "left" side of the display case, touching the glass but leaving a large gap on the opposite side:
![image](https://github.com/anegostudios/VintageStory-Issues/assets/19244401/340608a3-00c7-4dbd-8638-2240d9abe266)

Butterflies "tilted" at an angle that isn't parallel to the edge of the display case (I believe because their onDisplayTransform Y value isn't a multiple of 45):
![image](https://github.com/anegostudios/VintageStory-Issues/assets/19244401/84b0d88b-2bb6-42a4-9565-3d5b9f1bd919)

Note the wingtips clipping through the glass:
![image](https://github.com/anegostudios/VintageStory-Issues/assets/19244401/27e6ca6b-a8ac-4734-82cd-e076cf068771)

...This also means that butterflies in custom, modded display cases would always offset as well, which can be significantly more noticeable.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/19244401/afccdc7d-44a9-46e3-bf51-fdf1990c4c7e)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/19244401/f4420681-77e1-4440-85f4-e7304eff2797)

Thank you!

### How to reproduce

Place butterflies in a standard display case and observe the offset and tilt.

**Comment by RedramVS** [comment]
Hopefully fixed in 19.1, though with Tyron cherry-picking currently things can get missed.
