### ISSUE TITLE
Piles can visually disapear while placing new items into them

### ISSUE THREAD

**Issue by MimiVRC** [anegostudios/VintageStory-Issues#3435]
### Game Version

v1.19rc6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

This happens in vanilla but modded can help test it easier. When placing objects into a pile the pile visually flashes on and off but sometimes it does not go back visual. it seems the more complex the pile the higher chance it happens. it rarely happens with firewood, sometimes with ingots, but often happens with shingles and almost always happens on more complex modded piles such as the coins from Coinage.

reproduction steps in vanilla: 
1: Take a stack of shingle
2: place them in a pile. you will notice the pile often visually flashes on and off. you can land on it being disabled visually

### How to reproduce

reproduction steps in vanilla: 
1: Take a stack of shingle
2: place them in a pile. you will notice the pile often visually flashes on and off. you can land on it being disabled

the more complex the pile the easier it is to happen. if testing in modded some piles here it will happen every add to a pile, so using the coins from Coinage makes it very easy to reproduce

### Screenshots

video: https://github.com/anegostudios/VintageStory-Issues/assets/74305523/9a1ce87b-7906-4e2a-90ae-50ff90d5e1a5

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in next upcoming build, thank you for reporting :)

**Comment by MimiVRC** [comment]
just tested and seems fixed yes! thank you!
