### ISSUE TITLE
v1.19rc6 Wild wines don't work in worldgen

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3437]
### Game Version

v1.19rc6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Tested in 1.18.15 and 1.19rc6

### Screenshots

![2024-01-14_15-17-39](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/0d3e6a22-1f94-4247-a546-0f6c9053565a)
![2024-01-14_15-16-11](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/4fbd322e-c0ca-439a-b459-82093fa47d40)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
