### ISSUE TITLE
1.19rc6 Incorrect textures for cobble skull blocks and missing blocks for Aged polished rocks

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3438]
### Game Version

v1.19rc6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Pls add the 2 missing blocks and fix the textures for cobbleskull.

### Screenshots

![2024-01-12_23-05-49](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/709cd9c0-5187-4f7a-8f4a-f6c43ef425cf)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed for next release
