### ISSUE TITLE
v1.19rc6 Overlays and similar weird texture glitch if further away.

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3439]
### Game Version

v1.19rc6

### Platform

Windows

### Modded

Modded but should not be mod related.

### SP/MP

MP

### Description

[YoutubeVideo showing it.](https://youtu.be/8rTBETUH2zc)

### How to reproduce

place overlays on blocks and fly further away

### Logs

```Log```

**Comment by Th3Dilli** [comment]
ty,
this will be fixed with next pre
