### ISSUE TITLE
Some mushrooms cannot be planted inside planters and flower pots

### ISSUE THREAD

**Issue by pingouyn** [anegostudios/VintageStory-Issues#3442]
### Game Version

v1.19.0.rc8

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

Only mod used is HUD Clock.

Apologies if this is intended, but the wiki doesn't say some mushrooms shouldn't be planted in a planter or flower pot, so I'm assuming they all can.
I tried to plant the following mushrooms without any success :
- chicken of the woods
- tinder hoof

Many other mushrooms have been tried and worked fine.  I didn't try all of the existing mushrooms in the game (playing survival).  It's a pity I'm sure the chicken of the woods would look really cool!

### How to reproduce

1. Make a planter and a flower pot, fire them in a pit kiln.
2. Put them on the ground.
3. Right-click on the selected chicken of the woods or tinder hoof mushroom to try to plant them.
4. They cannot be planter, the characters tried to eat the mushroom.

### Logs

```Log```

**Comment by tyronx** [comment]
thesee grow on the sides of trees, not in soil, so intentional behavior

**Comment by pingouyn** [comment]
Cheers for the reply and all your great work whilst I'm at it!
That makes sense.  If that info could be added to the wiki pages for planter/flower pot and/or the mushrooms page, that'd be great.
In the meantime I'll run over to the suggestion feed to propose those mushrooms to be displayed on wood logs after being harvested.
