### ISSUE TITLE
Wooden blocks broken

### ISSUE THREAD

**Issue by Shadeloid** [anegostudios/VintageStory-Issues#3443]
### Game Version

1.19.0 rc 8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Trying to make a wood block, makes a wood block in the wrong orientation so you can't do anything with it aside from placing and making planks. Also making the crate fix meaningless.

### How to reproduce

Gather 4 planks.
Make a wooden block.
Can't make crate because it doesn't let you.

### Screenshots
![2024-01-15_11-01-40](https://github.com/anegostudios/VintageStory-Issues/assets/72017889/59e47d10-038d-4c6a-9985-fa5d5ea371f5)

![2024-01-15_09-19-56](https://github.com/anegostudios/VintageStory-Issues/assets/72017889/98d790ad-76ca-4867-ad22-f661da3fbcdb)

![2024-01-15_11-02-15](https://github.com/anegostudios/VintageStory-Issues/assets/72017889/c3297ef1-b92c-4223-a749-30926fe338a4)

### Logs

```Log```

**Comment by RedramVS** [comment]
This recipe was changed to involve only boards for 1.19 release.  So the plank blocks are no longer relevant to crates.

**Comment by radfast** [comment]
As Redram says, this is fixed in stable game versions 1.19.0 and 1.19.1 released today, please update to 1.19.1.  Thank you for reporting it!
