### ISSUE TITLE
[UI glitch] Loss of crucible/contained alloys when transferred

### ISSUE THREAD

**Issue by KelpyGee** [anegostudios/VintageStory-Issues#3446]
### Game Version

1.19.0-rc.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

When transferring a molten crucible from the player's inventory to a campfire with another molten crucible already in the output slot, the former disappears and all material inside vanishes with it. Found on official test server, and recreated later in single-player.

### How to reproduce

1. Put a campfire down with a crucible and smelt any metal
2. Wait till crucible pops into the output slot of the campfire
3. *Shift-Click* A new crucible (with smelted metal) into the campfire, any metal in the new one is lost

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Closed due to inactivity
