### ISSUE TITLE
[Mac] My Ui is scaled too high for me to use it so I can't change it in the game menu

### ISSUE THREAD

**Issue by sethamcd** [anegostudios/VintageStory-Issues#3452]
### Game Version

1.19.0

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

My UI scale is super high, so I can't navigate menus or apply settings changes, I keep being told to do a clean install but I can't find the location where vintage story stores it's user data files

**Comment by pingouyn** [comment]
Hi, if you manage to find where that file is "clientsettings.json", there's a parameter that can be tweaked: 
  "floatSettings": {
    "guiScale": 1.0,
...
If you decrease your value this could work.  I checked a few acceptable values on my machine for you:
0.5
0.625
0.75
0.875
1.0
1.125 ...

**Comment by radfast** [comment]
Thanks for reporting. It would be helpful to know what is your screen resolution on your Mac?  Seems to be a problem only with some screens.

**Comment by radfast** [comment]
This will be fixed in 1.19.2 in next few days, so I'm going to close this now.

Meanwhile please see [Retina displays](https://wiki.vintagestory.at/index.php/Installing_the_game_on_MacOS#Retina_displays) section of the Wiki installation guide for Mac
