### ISSUE TITLE
Crash - "climateLighterPlantTint" not present in Dictionary - 1.19.0 Stable 

### ISSUE THREAD

**Issue by Lbroil** [anegostudios/VintageStory-Issues#3455]
### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Game crashes either immediately or after a few minutes after updating to the newest stable version due to issue with "climateLighterPlantTint". Do not see this crash message reported elsewhere.
It happens both on single-player and when on LAN multiplayer.
I have uninstalled the game and entirely reinstalled, in addition to creating a new world. Crash still occurring.
Possibly related to game climate; started in a hot climate. From what I can tell, it is linked to our use of the full-color world map. Will try with the new world map and update if that solves it.

### How to reproduce

Create a hot climate survival world in 1.19.0. Play for a few minutes. I think the longest it has lasted is ~20.

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13969722/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13969724/server-main.txt)

**Comment by Lbroil** [comment]
Made a new world with all the same settings as the other two, except without the full color map option selected. Game no longer crashes. Played for several hours without issue.
I believe 1.19.0 is missing a reference that allows the game to render the light green of fruit trees on the world map with full color map enabled.

**Comment by malnaur** [comment]
I have had this crash in my fruit orchard using a prior world and with the new map active. See 3460 for my log output.

**Comment by 46hawk** [comment]
I have experienced this error in two separate worlds, one with full color map, one without. Each time, I noticed that I was near an olive tree in a hot climate, which notably uses the "climateLighterPlantTint" in fruittreefoliage.json, as mentioned by @bugreporter42. Removing that line seems to have helped.

**Comment by radfast** [comment]
> As a workaround, I removed the 'climateLighterPlantTint' lines from: _assets/survival/blocktypes/plant/fruittreefoliage.json_ and _assets/survival/blocktypes/plant/reedpapyrus.json_
> 
> and things are working.

This affects everyone, whenever an Olive tree is attempting to be on-screen.  As a temporary fix, you can also simply edit "Lighter" to "Light" in those two files - so delete the two letters "er" - and things will then work.  The team is aware of this issue and it will be fixed a.s.a.p., I'll leave this issue open though for now, to prevent duplicate reports.

**Comment by radfast** [comment]
This is fixed in 1.19.1 now released.  Apologies to all who were affected by it, and thank you to everyone who reported it.

I will leave this open for 24 hours in case there are any 1.19.0 players who did not yet update to 1.19.1.
