### ISSUE TITLE
Cant start grass/leaf fires

### ISSUE THREAD

**Issue by LeeFowler21** [anegostudios/VintageStory-Issues#3457]
### Game Version

1.19.0-Stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I tried starting a fire to burn grass with a torch to clear out an area, but it wouldn't start, it wasn't raining. It also didn't light ground leaves. I first noticed it in the rc.8 version, but didn't know if it was a bug as I mainly used mods before.

### Logs

```Log```

**Comment by GGBVanix** [comment]
As of 1.19.3, the only way you can start a fire in the world is to setup a pit kiln next to flammable blocks, such as trees and bushes. In addition, I also noticed that the fire does not spread to peat bricks placed on the ground. I could not light trees or bushes on fire. This was on a server with "allowfirespread" enabled, and I had "admin" privileges.

**Comment by radfast** [comment]
Assuming that you guys are both trying to start a fire in leaves/grass using a **torch**, this issue will be fixed in next upcoming release.  Therefore, I will close this as resolved.

If you are using a different technique to ignite leaves - not a torch - please give details...
