### ISSUE TITLE
Quicklime Model/Texture inheriting Flour itemtype/shape

### ISSUE THREAD

**Issue by niraethm** [anegostudios/VintageStory-Issues#3458]
### Game Version

v1.19.0

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

As of version 1.19.0, quicklime renders incorrectly on the player's hotbar as it shares a shape file with flour. Specifically this is because of the new model flour received, and quicklime inheriting it without proper gui transformations being set.

### How to reproduce

1. Load into world
2. Pick up/Spawn quicklime in hotbar/player hand

### Screenshots

![2024-01-17_20-46-18](https://github.com/anegostudios/VintageStory-Issues/assets/20865531/bc9bbe4c-3ba0-452e-b605-461ab96193ce)
![2024-01-17_20-46-31](https://github.com/anegostudios/VintageStory-Issues/assets/20865531/169c7b7e-ebed-41d5-bd9f-c9005c76f31e)

**Comment by RedramVS** [comment]
It is correct on master.  Apparently this came in after Tyron's feature freeze, and he did not cherry-pick it into the release branch.
