### ISSUE TITLE
Hand animation stuck when firestarter breaks

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#3459]
### Game Version

1.19.0

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

When you light your 20th fire and the firestarter breaks, the character continues rubbing their hands together until the game is restarted, even if the player switches to other items afterwards.
Might be related to https://github.com/anegostudios/VintageStory-Issues/issues/3454 and https://github.com/anegostudios/VintageStory-Issues/issues/3361

### How to reproduce

Use a firestarter until it breaks.

### Screenshots

![Screenshot at 2024-01-17 21-08-31](https://github.com/anegostudios/VintageStory-Issues/assets/19580483/19bbb741-913b-4dee-b620-7eec60032785)
![Screenshot at 2024-01-17 21-09-03](https://github.com/anegostudios/VintageStory-Issues/assets/19580483/5bd2a485-d5ed-4814-a3b5-00799656efd2)

### Logs

```Log```

**Comment by sekelsta** [comment]
The starving-hurt animation also seems to get stuck on when you've eaten food and am not starving anymore, but I haven't double checked this.

**Comment by Terraphice** [comment]
+1

**Comment by sekelsta** [comment]
Fixed in 1.19.2
