### ISSUE TITLE
Request: Add block 'ghost' when placing slabs/stairs

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#346]
Since their placement is dependant on how and where you click, it'd be great if we could see a shape outline to help with that.

**Comment by Craluminum2413** [comment]
VSHUD mod is the best example

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
