### ISSUE TITLE
Walking through walls

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3461]
### Game Version

1.19.0

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Able to walk into immediately adjacent dirt blocks. Collision check is obviously failing.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Can you reproduce it every time?

**Comment by malnaur** [comment]
I doubt I can find the hole I was in. Since it's never happened before this release and it was just a random hole I was hiding in, I shouldn't have to. Check what changed in that part of the code and find the bug.

**Comment by malnaur** [comment]
Experienced it again today in the Archive fighting mobs. Backed into a cobble wall and couldn't get out again (or break the block to escape because higher power).

**Comment by SpearAndFang** [comment]
This has been reported by several people and is easy to reproduce.  Just take some sort of injury near a block.  There's a chance you will get pushed into the block.  Seems like some sort of knockback bug.  I've personally had it happen getting stung by bees and taking fall damage. Many times.  1.19.0, 1.19.1

**Comment by pingouyn** [comment]
Seems linked to #3319, hence fixed in 1.19.4.
