### ISSUE TITLE
server.sh chooses the wrong server when running multiple servers with similar data paths

### ISSUE THREAD

**Issue by Wesmania** [anegostudios/VintageStory-Issues#3468]
### Game Version

v1.19.0

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

I'm running two multiplayer servers on one box, first with a data directory `/var/vintagestory/data`, second with `/var/vintagestory/data-1.19`. I also have a watchdog script that restarts servers on different conditions. I noticed that sometimes when performing a "restart" command for the first server, the second server will stop instead.

I'm not sure why it happens, but I think that the `pgrep` command in the script matches both server instances. It greps for `<a bunch of constant stuff> /var/vintagestory/data`, which I verified matches both server instances. I'd assume it then matches whatever has a lower PID and ends up selecting the wrong server.

### How to reproduce

* Launch two servers, with data path of the first being a prefix of the second, and I assume starting the second one before the first.
* Try to restart the first server.
* Repeat until the second server stops.

**Comment by pingouyn** [comment]
I had the same issue initially.  Having 2 directories for the server.sh script and separate Data directory wasn't enough.
There's a "serverconfig.json" file in the VintageStory directory for each server.  Towards the end you can give it the patch of the game save.  Could that be it?

**Comment by Wesmania** [comment]
I changed all the paths both in server.sh and serverconfig.json. The latter has 2 paths, for mods and saves, the earlier has 2 paths for server directory and data directory. Plus you have to change the screen session name. I'm pretty sure that's not it.

**Comment by pingouyn** [comment]
okies.  Other issue I had was with spaces in the directory path.  There are quotations missing here and there in the server.sh script and it messed up starting/stopping the wrong server.  I don't honestly believe it's related to you problem but it's worth a long shot; you never know it might spark something.
Check #3423, I've proposed a tested modification to the script, waiting for it to be approved.

**Comment by Wesmania** [comment]
I don't have spaces anywhere, so I doubt that's it.

**Comment by pingouyn** [comment]
No idea then, sorry it didn´t help.
The wiki advises starting a systemd service for each server when running multiple servers.
[https://wiki.vintagestory.at/index.php/Setting_up_a_Multiplayer_Server](url)

**Comment by Th3Dilli** [comment]
this seems to be related to the screen name 

if you change the SCREENNAME then it should work

I added now a comment that it should be changed as well when running multiple servers

ty for reporting

**Comment by Wesmania** [comment]
The servers I was running already had different values of SCREENNAME. This I discovered earlier when setting up servers because without the change scripts would apply to the same server every single time. I think the issue I found is something else.

**Comment by Th3Dilli** [comment]
are you sure about the screenname? since it tested it and with a different screen name it did work for me

**Comment by Wesmania** [comment]
I am, I was able to reproduce it right now.
* Made a directory `$dir`.
* Made 4 subdirectories: server, server2, data, data2.
* Unpacked servers to server and server2.
* Set VSPATH for server in "server" to `$dir/server`, DATAPATH to `$dir/data`, SCREENNAME to `vintagestory_server`.
* For server in "server2", set the three to `$dir/server2`, `$dir/data2` and `vintagestory_server2` respectively.
* Start server in "server" with `./server.sh start`.
* Start server in "server2" with `./server.sh start`.
* Verify that both servers are running with `./server.sh status`.
* For the server in "server", run `./server.sh restart`.
* After it's done, `./server.sh status` in "server2" will show that the server in "server2" is stopped.

**Comment by Th3Dilli** [comment]
ty, I found the issue now

and the reason why it was not an issue for me is that I used `vintagestory_server1` and `vintagestory_server2` where that did not happen

so now the following line in the `vs_stop()` function needed to be changed from
`if pgrep -u "${USERNAME}","${GROUPNAME:-root}" -f "${SCREENNAME}" > /dev/null ; then`

to
`if pgrep -u "${USERNAME}","${GROUPNAME:-root}" -f "${PGREPTEST}" > /dev/null ; then`

that does fix that issue
