### ISSUE TITLE
scroll rack fails to identify some contents

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3473]
### Game Version

1.19.0

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The scroll rack shows the titles of the upper three cylinders stored when examined but shows empty for the lower three and empty for all items in an adjacent rack. Also, 6-8 slots is very disappointing for an entire block storage. Finally, cylinders stick out the front despite plenty of room for them to be fully in the rack.

### Screenshots

![2024-01-18_23-34-44](https://github.com/anegostudios/VintageStory-Issues/assets/30317159/d81bc6dc-4c8b-4f5a-a5aa-5e323c2e73c7)
![2024-01-18_23-34-56](https://github.com/anegostudios/VintageStory-Issues/assets/30317159/7e559fd6-a9da-42b7-a0a0-c0113d0fd840)

### Logs

```Log```

**Comment by CookieBoy21** [comment]
This issue was fixed in v1.19.4-rc.1. Now scroll rack showing info correct .
