### ISSUE TITLE
tooltips not updating right between 2 of the same items

### ISSUE THREAD

**Issue by thehuntedpie** [anegostudios/VintageStory-Issues#348]
**Game Version:** 1.11.1 (stable)
**Platform:** Windows
**Modded:** No

### Description
Tooltips do not update right when moving from item to item of the same type in a container

### How to reproduce
1. open a container
2. place 2 items inside of the same type but with different expiration dates
3. hover your cursor over one item and view the expiration date
4. move your mouse over to the second item (same item type with different expiration date)
5. Observe that the expiration date shown for the second item is the same for the first, even though they are actually different.
6. Panic that the 64 cabbages you just harvested will expire in 5 hours, because you moused over the old cabbages first.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
N/A

**Comment by tyronx** [comment]
Thanks for the report, this is now fixed for the upcoming version
