### ISSUE TITLE
1.19 paste feature visual bug 

### ISSUE THREAD

**Issue by jonnypotseed** [anegostudios/VintageStory-Issues#3481]
### Game Version

v19.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Using the paste after the 19.0 update renders the placement model for everyone on the server.   

### How to reproduce

1. Copy build using the magic wand.
2. Use the paste to to place.
3. Watch everyone in chat lose their minds.

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in next game version 1.19.2, thank you for reporting, and apologies for the sanity of the other people in chat ...
