### ISSUE TITLE
Not Opening Mac OS 1.19.1

### ISSUE THREAD

**Issue by MollyMacek** [anegostudios/VintageStory-Issues#3485]
### Game Version

1.19.1

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Downloaded VS but when I open the application it bounces in my menu bar for a second and then disappears without opening.

### How to reproduce

1) Download VintageStory 1.19.1 Mac APP
2) Unpack the tar file
3) Move vintagestory file to /Applications
4) Try to start it -> Security warning about unsigned app -> allow to open it anyways
5) Try to start it -> nothing happens, it bounces for a second then disappears 

### Logs

```Log```

**Comment by radfast** [comment]
@MollyMacek  you closed this, did you succeed in making it work?

If there's anything that can help other Mac users, please let me know.

See also: https://wiki.vintagestory.at/index.php/Installing_the_game_on_MacOS - if there's anything we missed from that guide, it would be good to know.
