### ISSUE TITLE
Request: Turn compost block into Nitrous Fertilizer. 

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#349]
There's no Nitrogen-specific fertilizer, so the Compost block feels like a missed opportunity there.

**Comment by Angelnoir** [comment]
Or maybe turn compost blocks into all-round fertilizer. 1 Compost = 32 Fertilizer with 15% on N,P and K for example. 
So you could choose between using the block long-term (since it regenerates its nutritions) or to use it short-term as fertilizer for faster crop growth.

**Comment by copygirl** [comment]
From the [1.15.0-pre.1 changelog](https://info.vintagestory.at/v1dot15#pre1):

> Rot in barrel now produces compost items for instead of full blocks, can be used as fertilizer or to craft full compost blocks
