### ISSUE TITLE
BehaviorCreatureContainer null reference exception

### ISSUE THREAD

**Issue by NerdScurvy** [anegostudios/VintageStory-Issues#3491]
### Game Version

v1.19.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Requesting a fix to the Vanilla code to support modding.

The new Creature Container is causing an error if the player is placing a block, but does not have the block in their active slot.
CarryOn holds the carried block in a special slot so slot.ItemStack is null

Can we get a null check added to itemStack on the BehaviorCreatureContainer class for HasAnimal line 30?
        public bool HasAnimal(ItemStack itemStack)
        {
            return itemStack.Attributes?.HasAttribute("animalSerialized") == true;
        }

### How to reproduce

Using carryon@1.7.0-pre.3
1. Place Reed Chest on ground
2. Crouch and interact to pickup chest with CarryOn
3. Target ground, crouch and interact with ground to place chest block
4. Null Reference Error

### Logs

```2024-01-20 08:47:27: Critical error occurred in the following mod: carryon@1.7.0-pre.3
Loaded Mods: game@1.19.1, carryon@1.7.0-pre.3, creative@1.19.1, survival@1.19.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.HasAnimal(ItemStack itemStack) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 31
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 123```

**Comment by Craluminum2413** [comment]
Both things are not possible to reproduce in vanilla

**Comment by SpearAndFang** [comment]
There's a newer version of Carry On that should fix that.
