### ISSUE TITLE
GUI: Messages are a bit too hidden

### ISSUE THREAD

**Issue by Fulgen301** [anegostudios/VintageStory-Issues#35]
Ingame messages, such as from the prospecting pick or the bed, appear in the message box on [Tab]. However, if you don't know this, you might feel like "nothing happens, the game is broken". Also, it costs time always to toggle the message box to see messages (leaving it visible costs valuable screen space).

**Comment by copygirl** [comment]
Yes, I don't like this myself, either. To me these "event messages" are very immersion breaking and a lazy way to implement gameplay features. Hopefully the game eventually conveys all the information using mechanics and items.

As for prospecting, in my opinion it is very confusing in the first place and I'd prefer getting special chunks of rocks that one could grind down to find out which and how many ores are in the area.

As for the messages, first of all a dedicated "event" tab might be useful, used for all gameplay features to separate it from player chat. On top of that, perhaps each tab could be selected to display recent messages that fade out after some time on the HUD with a simple checkbox. By default every tab (except perhaps debugging related ones) should have this turned on.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
