### ISSUE TITLE
Aggressive Sheep in "Passive" World

### ISSUE THREAD

**Issue by Airova** [anegostudios/VintageStory-Issues#350]
**Game Version:** 1.11.2
**Platform:** Windows (8.1)
**Modded:** Yes: Carry Capacity, Salt Generation

I set my world to "passive", generated in 1.11.3. The wolves are not aggressive unless provoked now, but the sheep seem to frequently attack me unprovoked. At first I thought this was still the bug with them taking fall damage and blaming me, but it has happened several times in wide-open flat spaces with nowhere they could have fallen. Once one sheep attacks me, the whole flock joins in, and since I'm not prepared for combat given the world is set to passive, I get beaten pretty badly by them if I don't manage to run away. I'm uncertain what exactly is triggering their aggression, since it doesn't seem to happen all the time, though it has happened multiple times in totally different parts of the game world. I can provide a save file and/or footage of it happening if needed.

**Comment by tyronx** [comment]
Thanks for the report, Aira. Does it perhaps happen only if you get very close to a male bighorn sheep?

**Comment by Airova** [comment]
I'm not sure. I think it's been a male that attacks me first most of the time, but I will have to test that. I'll see if I can jump in later today and get you some more details.

**Comment by copygirl** [comment]
There has been a recent change in the behavior of animals, which includes rams attacking you simply for getting to close. I did mark this as a bug, since this is quite unexpected for players who deliberately chose mobs to be "passive" in the world customization screen, and should probably be fixed.

**Comment by Airova** [comment]
I see. Yes, that seems an odd choice for a world where even wolves don't attack unprovoked. I'd prefer not to have that happen in a passive world. At the very least, if getting "too close" to a ram counts as provoking, I'd ask that at least be made explicitly clear, since I certainly didn't expect it and wasn't prepared for it. Also, how close is too close? I don't think I ever got *that* close to a ram before getting attacked. Thanks for the heads up! When I next play, I will check to see if that is the case, and if not I will update with more details.

**Comment by tyronx** [comment]
Oh yea it seems i have missed to disable that one

**Comment by tyronx** [comment]
njuuuuu, i forgot to add this to v1.11.5. Sorry. Will be in the next release

**Comment by Airova** [comment]
Actually, I discovered last night that it was also happening with roosters, too, not sure if you've caught that already.

**Comment by tyronx** [comment]
aw, okay will fix

**Comment by Airova** [comment]
Heh, sorry, I keep finding them bit by bit. I also got attacked by a hyena out of nowhere, so I think that one also needs to be disabled. I think that should be it though: wolves are properly passive, pigs are properly passive. Hopefully rams are fixed, and you now know about roosters and hyenas. That's all the potentially aggressive animals that I know of. :D For now I'm doing fine just avoiding them. I gave myself lots of HP and made the animals weak so at least I'm not in any serious danger. Thanks a lot!

**Comment by copygirl** [comment]
There's been several patch releases for 1.11 now. Has this been addressed?

**Comment by Airova** [comment]
Rams are fixed. Hyenas and roosters are mostly fixed but every once in a while one of them still attacks me, no idea why... It seems to be random. :(

**Comment by Angelnoir** [comment]
Happened to me several times too, playing on "passive" with 1.12.4 stable.
Really seems random, yesterday I took a walk through the forest searching oak trees and suddenly a boar attacked me out of nowhere. 

This is just an idea, but what happens if you are hunting and attacking for example a boar and it manages to escape. It is possible to meet this same boar several ingame days later and client restarts later and its still aggressive?

**Comment by copygirl** [comment]
From what I understand this behavior is driven by "emotion states" in the entities. Those states can have varying times of being active, but should eventually go back to normal. Looking at the animal assets, half a minute is the max they should be aggressive for after you hit them.

**Comment by tyronx** [comment]
Is this is fixed by now?

**Comment by Craluminum2413** [comment]
They will still trying to attack you if they fall. But they can't hit you

**Comment by copygirl** [comment]
Sounds like this is resolved, then?
