### ISSUE TITLE
game crashes from title screen

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#3501]
### Game Version

v1.19.1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

after downloading the new update 1.19.1  decided to start a new world,  click on single player then create world and game crashes and sends me back to the desktop.  redownloaded the whole game and uninstalled, game still crashes.  turned off all mods so only trying to run this vanilla.  

running windows 11
processor - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.20 GHz
ram - 16.0 GB 

### Logs

```Log```  no log info to load as item crashes on main home screen

**Comment by NITRO1623** [comment]
Game was also running perfect on 1.18 with no issues till 1.19 update.

**Comment by Craluminum2413** [comment]
Did you make clean uninstall? Folder with Vintagestory.exe should be empty after uninstalling

**Comment by radfast** [comment]
"Turned off all mods"

Did you turn off Creative Mode, Essentials and Survival Mode?  These three are the vanilla game, you need to keep them enabled!

**Comment by NITRO1623** [comment]
I did not do a clean uninstall I just did the full Install of new update.  So to make sure I understand you would want me to delete game completely from computer and then download as fresh start?

**Comment by NITRO1623** [comment]
> "Turned off all mods"
> 
> Did you turn off Creative Mode, Essentials and Survival Mode?  These three are the vanilla game, you need to keep them enabled! 

Yes all the features are still active as well

**Comment by NITRO1623** [comment]
Thank you all.  I did to the new 1.19.3 update and seemed to fix it.  I did also find that three mods are causing the crashes

Carry on

Feverstone wilds

Survival mod (doesn't crash but does not work on 1.19.3)

Hopefully this helps everyone to but the issue seems to resolved I will close ticket

**Comment by SpearAndFang** [comment]
I think you mean 1.19.2, not 1.19.3
"Survival" mod is a part of the base game.  It definitely works.
If you mean Primitive Survival, both it and Carry On work with 1.19.2.  Sounds like you need to get an updated version of both.
