### ISSUE TITLE
Jumping Sand/gravel in sandstorm

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#3502]
### Game Version

v1.19.1

### Platform

Steam Deck

### Modded

Yes

### SP/MP

SP

### Description

Saw them in the distance. Soil and rock instability on. 1.19.1 on Steam Deck. No idea why...

### Logs

```Log```

**Comment by Bughaw** [comment]
![9346141_20240122171620_1](https://github.com/anegostudios/VintageStory-Issues/assets/22966611/457cde86-6332-4a6b-8e5d-e8bd77dfc723)
![9346141_20240122171623_1](https://github.com/anegostudios/VintageStory-Issues/assets/22966611/f7de745a-0b30-48fd-b68e-2f677804ff7d)
![9346141_20240122171623_2](https://github.com/anegostudios/VintageStory-Issues/assets/22966611/f8690543-4d39-4260-841b-6bced62de35d)
![9346141_20240122171625_1](https://github.com/anegostudios/VintageStory-Issues/assets/22966611/13378f5f-4f80-47ab-b07c-07c21227e416)

**Comment by Bughaw** [comment]
Not just falling, but bouncing up.

**Comment by Craluminum2413** [comment]
1.20 with new physics probably fixed it

**Comment by Bughaw** [comment]
Ok.  Thanks!
