### ISSUE TITLE
Shader compiler error "Unknown pre-processor directive #v" - Thai language issue

### ISSUE THREAD

**Issue by munkeawtoast** [anegostudios/VintageStory-Issues#3507]
### Game Version

v1.19.1

### Platform

None

### Modded

None

### SP/MP

None

### Description

Black screen after launch, text of "Loading shader..." comes on the screen for split second then  just black screen and cursor and nothing else. Can still interact with invisible UI elements.

Tried
- reinstalling the same version
- reinstalling previous versions 1.19.0, 1.18.15
- Deleting VintageStoryData and VintageStory from %APPDATA%

### How to reproduce

1. Start the game

### Logs

[client-main.txt](https://gist.githubusercontent.com/munkeawtoast/bff83edce2e0c02e4d3899567c71fce8/raw/02875bb866144d9f14a2eee82dc5770b04c78971/gistfile1.txt)

**Comment by Th3Dilli** [comment]
@munkeawtoast what is your system language set to?

@radfast fyi since you have more experience with this now I think

**Comment by munkeawtoast** [comment]
The system language is in English. The locale is in Thai.

What I've tried some more:
Upgrading Graphic driver.
Switching to Intel's built-in (it's white screen this time, here's the log: [client-main.txt](https://gist.github.com/munkeawtoast/b046a9f88dd75cf9c3420dfba981e683))

**Comment by Th3Dilli** [comment]
@munkeawtoast the issue you are having is specific to that language we are in the works of a fix for it, in the time being you could change that to something else to play

**Comment by radfast** [comment]
Update: this issue is fully fixed from game version 1.19.4-rc.1 and later :)
