### ISSUE TITLE
[linux] mesa_glthread not set when using the install.sh script

### ISSUE THREAD

**Issue by pingouyn** [anegostudios/VintageStory-Issues#3511]
### Game Version

v1.19.2

### Platform

Linux

### Modded

None

### SP/MP

None

### Description

Clean install.
The script works in the way that it installs the game to the correct directory location, the game works.  Nevertheless the script fails to read the answer to the question about using mesa_glthread or not, hence cannot properly set its value to run.sh.

### How to reproduce

1. Remove previous VS directory in /home
2. Download vs_client_linux-x64_1.19.2.tar.gz, unpack
3. Move to /vs_client_linux-x64_1.19.2
4. In terminal: ./install.sh
5. Select the default installation directory
6. The script doesn't let the user write an answer to the "Enable 'mesa_glthread'" question.

### Logs

(...)
Create LowercaseAlias for REF.png
vm.max_map_count is already greater than or equal to 262144
Do you want to enable 'mesa_glthread'?
Enabling this feature can provide a performance boost. However, if you experience a freezing window, you can navigate to your installation directory and remove it from the run.sh file.
Enable 'mesa_glthread'? : 
./install.sh: line 113: read: `(y/N): ': not a valid identifier
'mesa_glthread' disabled
./install.sh: line 125: cd: /mydrives/nvme-btrfs/@games/Vintage Story/client/vintagestory: No such file or directory
Do you want to remove your old installation which was moved to /home/UserName/.local/share/vintagestory.bak.2024_01_25-19_59_26? 
(...)

**Comment by Th3Dilli** [comment]
oh sorry, fixed now

ty
