### ISSUE TITLE
Can't pickup animal trap with cock inside. 

### ISSUE THREAD

**Issue by Alexiestree** [anegostudios/VintageStory-Issues#3518]
### Game Version

1.19.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I trapped a cock and tried to break trap with him but midbreaking i stopped and clicked on trap with right mouse button click. then trap droped on the floor, but I can't pick it up somehow. tried reenter world - no effect. breaking blocks under doesn't helped too.

### How to reproduce

1. Put a basket trap on floor and fill it with flax grain
2. Catch a cock
3. Try breaking trap and stop in the middle of breaking
4. Click on basket with right mouse button
5. Try to pick it up from floor.

### Screenshots

![Снимок экрана от 2024-01-27 08-53-26](https://github.com/anegostudios/VintageStory-Issues/assets/7397194/fcc61045-ff7d-4bbc-9926-00b2ec96f7a6)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is a feature, you need to put it into free backpack slot, not inventory slot
