### ISSUE TITLE
Clay forming pick-up issue

### ISSUE THREAD

**Issue by LolO366775** [anegostudios/VintageStory-Issues#3532]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

when you finish forming clay you are unable to right-click pick up the formed item, instead you have to break it and place it for it to be right-click pick-up-able.

### How to reproduce

1. use fire or blue clay to form any item that you can right click pick up(bowls, crocs, vessels, etc). 
2. finish forming the item. 
3. attempt to pick it up by right clicking and see that it doesn't work. 
4. break it with your hands. 
5. place it down. 
6. now you can right click it.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.20.0-pre.6
