### ISSUE TITLE
Spear disappears from inventory

### ISSUE THREAD

**Issue by Alexiestree** [anegostudios/VintageStory-Issues#3534]
### Game Version

1.19.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When you use spear and spam attack button and simultaneously opens inventory the spear disappears. I see that game thinks that I thrown it and tries to change it for new one if I have 2 spears inside inventory and i can find spears in empty slots by clicking on it, they appear in pointer

### How to reproduce

1. Take any spear
2. Try to spam left mouse button 
3. Simultaneously open inventory by pressing "E" button
4. See the result
5. If not try several times

If spear disappears click on the slot where spear was it must appear

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/7397194/19d1edcc-fdef-4038-9d35-4a11e75e1a4a

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you, that seemed to be an issue for multiple things like bow, throwables like stones

will be fixed in 1.20 due to some smaller API changes

further, the item is not gone it is just not shown on the client and need resyncing, so if you just click the slot it will reappear
