### ISSUE TITLE
Request: Better handbook filtering

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#354]
There really is no need for it to list every single type of ore nuggets from poor-rich when you're trying to find something you don't remember the name of. You could probably also narrow it down to stone types and then have them display what 'variants' they show up in (Bricks, cobble, sand etc) when you actually click it.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
