### ISSUE TITLE
Trader dialogue gui will not auto close after walking away

### ISSUE THREAD

**Issue by korobya** [anegostudios/VintageStory-Issues#3541]
### Game Version

1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Similar to #2416, but this issue about dialogue gui ([GuiDialogueDialog.cs](https://github.com/anegostudios/vssurvivalmod/blob/master/Systems/Dialogue/GuiDialogueDialog.cs))

### How to reproduce

1. Right click on a trader -> the dialogue gui'll open
2. Walk away -> the dialogue gui didn't close

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you will be fixed in an upcoming release (probably 1.20)
