### ISSUE TITLE
Soybeans can be placed in trough but are tagged as "unsuitable" for all animals and will not be eaten.

### ISSUE THREAD

**Issue by Ginevrasm** [anegostudios/VintageStory-Issues#3544]
### Game Version

v1.19.3 (Stable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I can place soybeans in a large trough.  When placed in the trough the tooltip will state that they are "unsuitable" as fodder.  Per the Wiki entry and prior version gaming, soybeans should be a suitable fodder for Bighorn sheep and pigs.  If the soybeans are left in the trough, they will remain uneaten.

### How to reproduce

1.  Place soybeans in large trough.
2.  Review tool tip to verify message stating "unsuitable."
(To test if soybeans will be eaten, place in livestock pen and wait.  You may also place a control trough with other fodder for comparison.)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Soybeans are poisonous to all animals when raw, I heard it is intended
