### ISSUE TITLE
Hoeing block with snowy grass allows seeing through the world

### ISSUE THREAD

**Issue by theDudeMan** [anegostudios/VintageStory-Issues#3548]
### Game Version

1.19.2

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Hoeing soil with snow layers and grass on it causes the snow to not render (though it can still be interacted with). Since the game still believes there are snow layers there, the connected faces of other snow layers are not rendered, thus allowing the player to see through blocks, and identify caves.

### How to reproduce

1. find a soil block with both grass and snow layers on top.
2. remove an adjacent block to gain access to the side of soil.
3. use hoe on side of soil.

### Screenshots

![2024-02-02_12-37-21](https://github.com/anegostudios/VintageStory-Issues/assets/50598644/93d4d7b3-8bba-4e51-9cd9-67cd7cc0719f)
![2024-02-02_12-21-11](https://github.com/anegostudios/VintageStory-Issues/assets/50598644/8e3643e9-5e8b-4ca1-b341-addf932c89ca)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Can't reproduce, I assumes it is fixed
