### ISSUE TITLE
bug with the chute, hubber, archemedes screw / pot.

### ISSUE THREAD

**Issue by tiba666** [anegostudios/VintageStory-Issues#3549]
### Game Version

1.19.3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

chute and archemedes screw bug ? 

if you place a stack in the hopper either by drop or place the flow works until (stack) - 1-3
the last 3 items get stuck in the chutes. if you then try to place more items int he hopper it will not work its like the state of the pipe do not update to get pushed down the chute anymore..
 
only way to fix the clog is do destoy the chute to emtry the chute for then replace the chute agian it will then work until the hopper run out of things agian but breaks when the hopper runs out of things to push down the chute.

### How to reproduce

make the setup like this 
![image](https://github.com/anegostudios/VintageStory-Issues/assets/519338/b21cda7e-e5cf-4d9a-a343-f3344066e9d4)

### Logs

```Log```

**Comment by tiba666** [comment]
added a youtube vid
https://youtu.be/JoPt5RLJpPU

**Comment by Th3Dilli** [comment]
thank you, this will be fixed in an upcoming release
