### ISSUE TITLE
Temperature of work item on the anvil does not decrease faster during rain

### ISSUE THREAD

**Issue by korobya** [anegostudios/VintageStory-Issues#3554]
### Game Version

1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Temperature of work item on the anvil does not decrease faster during rain, as it happens on the forge.

### How to reproduce

During the rain, place the preheated work items on the anvil and on the forge. 
The temperature of the work item on the forge decreases rapidly, but not on the anvil.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is a suggestion

**Comment by Craluminum2413** [comment]
Works as intended in 1.20.0, I assume it is fixed
