### ISSUE TITLE
pan litterally destroys sand when I squat and use it (if it's slightly panned)

### ISSUE THREAD

**Issue by DarthCalvinus** [anegostudios/VintageStory-Issues#3555]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

So I made a world and started panning, but then I accidentally squatted and right clicked and the pan replaced the partially panned sand.  

### How to reproduce

Pan some sand (only 1 or 2 layers) then squat and right click on the sand.

**Comment by Craluminum2413** [comment]
Duplicate of #1332
