### ISSUE TITLE
Cave-ins occur constantly near the mantle

### ISSUE THREAD

**Issue by EvanBalster** [anegostudios/VintageStory-Issues#3567]
### Game Version

v1.19.3.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The new cave-in mechanic exhibits strange behavior when breaking the bottommost two layers of stone above the mantle.

- Stability calculations appear to behave as if the mantle is empty space (as opposed to solid rock).
- Cave-in behavior is subject to several oddities.
  - Caved-in rock may be redeposited at its own position.  This may cause material duplication yielding excess stone and ores (uncomfirmed)
  - Caved-in rock will occasionally teleport to the surface of the world far above.

I am playing in standard mode, customized to enable sideways soil instability, cave-ins and ocean/landcover.

### How to reproduce

- Obtain some ladders and a good pick.  Ore blasting bombs for extra credit.
- Dig a vertical shaft down to the mantle.
- Observe odd behavior when mining the bottommost (y = 1~2) strata of stone.

### Screenshots

n/a.  Just a mess of cracked rock by the mantle.

### Logs

```Log```

No relevant entries were noted in server-main.txt or client-main.txt.

**Comment by CookieBoy21** [comment]
In 1.20 pre.6 when Tyron change something in "cave-ins", rocks started falling in huge numbers near the mantle. This made the existing bug even worse. I suggests put it in higher priority because it started happened to more people.


Here is video how this looked in pre.5, just few rocks was falling.

https://github.com/user-attachments/assets/04cf108a-6243-4a4f-818b-dd8c12c4e2e6

**Comment by Bughaw** [comment]
This is still an issue in 1.20.0pre13.

**Comment by Craluminum2413** [comment]
@maltiez2 could you look at it

**Comment by Bughaw** [comment]
This happened to me before in previous versions, but the current cave-in system is epic.  The entire bottom of the world starts falling out, drifting up to the surface, and falling on the surface too.  It is really bad.  I'm going to have to turn cave-ins off - hopefully before my laptop melts.

**Comment by maltiez2** [comment]
Rock floating up to the surface will be fixed in next update

**Comment by CookieBoy21** [comment]
Fixed in v1.20-rc.1.
