### ISSUE TITLE
Helpers Handbook not working anymore

### ISSUE THREAD

**Issue by Raybro29** [anegostudios/VintageStory-Issues#3573]
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I had to fix an issue where I accidentally removed the Player HUD (where food types, stats and temperature are listed) by removing a ClientSettings.json file. Doing so worked, but now I can't seem to open up my player handbook in order to check recipes for items. The moment I do, the game crashes instantly.
I'm not entirely sure what's causing this, my best guess is that I must've accidentally deleted something else alongside the client settings

### How to reproduce

As mentioned before, I'm not entirely sure what might be causing the issue, but I'll post the steps I did that started causing the issue.
1. Go into VintageStoryData in %appdata%
2. Delete ClientSettings.json (optionally, delete backup as well)
3. Run Vintage story and start/resume a world
4. Press H to open the player handbook when having the mouse over an item (IE, Flax twine)

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14230180/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14230181/server-main.txt)

**Comment by Th3Dilli** [comment]
the crash seems related to the mod `VesselBuff` please contact the mod auther for it
