### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by rukuliny** [anegostudios/VintageStory-Issues#3574]
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

this is my first time playing this game

### How to reproduce

I open the game and it just happens

### Screenshots

![vlcsnap-2024-02-11-11h52m31s5](https://github.com/anegostudios/VintageStory-Issues/assets/159707901/ce24eec8-533a-46ad-aa4c-4778f1e5361a)

### Logs

```Log```
Game Version: v1.18.5 (Stable) by OverF1X  
11/02/2024 11:50:48 a.m.: Critical error occurred
Loaded Mods: 
System.MissingMethodException: Método no encontrado: '!!0[] System.Array.Empty()'.
   en Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   en Vintagestory.Client.ClientProgram.<>c__DisplayClass16_0.<.ctor>b__0()
   en Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) en VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:línea 93

**Comment by Craluminum2413** [comment]
Pirated versions are not supported, they are absolutely unpredictable
