### ISSUE TITLE
game crashes all the time

### ISSUE THREAD

**Issue by SmallYuka** [anegostudios/VintageStory-Issues#3579]
### Game Version

v.1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/159829679/a99490ac-28ea-4452-b47b-5da0fc0497a6)

**Comment by Craluminum2413** [comment]
Duplicate of #3410
