### ISSUE TITLE
Certain "Unusable clutter" items in ruin chests are missing models

### ISSUE THREAD

**Issue by Agent00Ming** [anegostudios/VintageStory-Issues#3585]
### Game Version

1.19.4-rc1, 1.19.4-rc2

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Ruined fence, Ruined lantern, Aged lectern and Pile of aged books generating as loot inside of ruin chests have the "?" block model and are completely invisible when placed in the world.

### How to reproduce

Fly + Noclip through the ground to locate underground ruins. Looking through a couple of the collapsed chests, one will eventually come across "?" Unusable clutter mentioned above.

### Screenshots

![2024-02-14_11-04-44](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/5602b2be-c92e-4206-80b9-4eef06045cb4)
![2024-02-14_11-02-16](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/a2041251-4e14-46ed-bf78-4f02fac44c9c)
![2024-02-14_10-23-37](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/3f58cb6e-77d3-4fa3-82f6-88717a226018)
![2024-02-14_10-13-18](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/c151a85f-8926-493e-9715-777f674cdfbf)
![2024-02-14_11-06-01](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/8546dc06-c045-42cb-8268-0e73c1b63542)
![2024-02-22_19-13-31](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/027372df-ac16-480f-9649-e7a422beb1a6)
![2024-02-22_19-13-27](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/2cecef3c-92c4-49e3-b4ff-f03e3e7fb148)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for the careful and thorough report @Agent00Ming, this one was really helpful

These will all be fixed in upcoming 1.19.4-stable.  Unfortunately, it's not possible to fix already-generated chests, the fix only applies to new worldgen.
