### ISSUE TITLE
Escaped characters not un-escaped in speech bubbles

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#359]
**Game Version:** 1.11.11
**Platform:** Arch Linux
**Modded:** Yes (CarryCapacity, Farmland Drops Soil)

### Description
Typing characters that are escaped such as `<` and `>` don't get properly turned back to their un-escaped equivalents in the "speech bubbles" above players' heads.

### Screenshots
![image](https://user-images.githubusercontent.com/272586/71635342-f5f25b80-2c23-11ea-95de-6e2464272e22.png)
![image](https://user-images.githubusercontent.com/272586/71635357-1e7a5580-2c24-11ea-8f82-b70ef73a5673.png)

**Comment by tyronx** [comment]
This should be fixed in pre.6 or so
