### ISSUE TITLE
Smithing is broken in 1.19.4rc1

### ISSUE THREAD

**Issue by bugreporter42** [anegostudios/VintageStory-Issues#3593]
### Game Version

1.19.4rc1

### Platform

Linux

### Modded

None

### SP/MP

None

### Description

When hitting a work piece with a single click of the hammer, it swings, but no voxel is moved. It takes a longer click to get the voxel to move, likely resulting in multiple hammer swings.

IMO, smithing is unusable in its 1.19.4rc1 state. 1.19.3 was fine.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Hit is completely synced with animation, it works only when you hold left-click until animation ends
