### ISSUE TITLE
Temporal Storms world setting renders weirdly

### ISSUE THREAD

**Issue by Blazing-Blast** [anegostudios/VintageStory-Issues#3595]
### Game Version

1.19.3-1 AUR

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Text is not spaced as it should when it takes up multiple lines. Text overlaps.

### How to reproduce

1. Open the new world menu.
2. Customize the settings.
3. Scroll to the Temporal Stability tab.
4. Open the Temporal Storms drop-down menu.
5. The text is not spaced as it should be.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/69185984/98ff6f63-be20-4cb0-a8c2-b4dafa093ce2)

### Logs

Not applicable

**Comment by Craluminum2413** [comment]
Can't reproduce, I assume it was fixed
