### ISSUE TITLE
glasses and snow goggles : existing items lost

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3599]
### Game Version

v1.19.4-rc1

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

v1.19.4-rc1 introduced a change upon glasses and snow goggles. They are now placed on mask slot instead of head slot. But their game Id changed, and already collected items before this version are unusable. Only newly generated ones are working fine.

### Screenshots

![Screenshot_20240217_125831](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/4ae82a5d-28b4-4cc3-a0fb-f95647ffca94)

**Comment by radfast** [comment]
@Saricane thanks for the report.  Is this **only** on TOPTS, or is it on all your games?

If it is TOPTS only, we think possibly it just needs a server re-start, which will happen imminently...
