### ISSUE TITLE
Mouse wheel gets stuck

### ISSUE THREAD

**Issue by Fulgen301** [anegostudios/VintageStory-Issues#36]
Sometimes, turning the mouse wheel does nothing, so the next item isn't selected. The control doesn't get eaten by a black hole, however, it gets handled on the next mouse event - meaning that if such a control gets stuck and I click an enemy with a sword, the next item gets switched and I try to kill him with my carrot.

Arch Linux, mono 5.10.0, libinput 1.10.3

**Comment by tyronx** [comment]
Try fiddling with mouse wheel sensivity, might just need a bump?

**Comment by tyronx** [comment]
No feedback in several weeks, closing this

**Comment by Fulgen301** [comment]
I fiddled around with mouse wheel sensitivity, and it helps a little bit, the "bug" doesn't vanish though, it just doesn't occur that frequent anymore.

**Comment by tyronx** [comment]
Hm ok, sounds like an issue related to OpenTK

**Comment by Fulgen301** [comment]
Bug seems to be fixed in 1.6.0 pre2 (I don't experience the issue any more).
