### ISSUE TITLE
Funky spear animation

### ISSUE THREAD

**Issue by Shadeloid** [anegostudios/VintageStory-Issues#3600]
### Game Version

1.19.4 rc 1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

While staying still with a spear equiped, it jumps up and down non-stop until we move again.

### How to reproduce

1. Make a spear
2. Watch it jump up n down while staying still

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this is fixed in rc2
