### ISSUE TITLE
Handbook still recommends using the map to find clay

### ISSUE THREAD

**Issue by KironaDragryph** [anegostudios/VintageStory-Issues#3601]
### Game Version

1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The handbook still recommends searching for clay via the lighter-colored patches on the minimap or world map, but this now only works if you enable the classic/realistic coloring mode in worldgen (which is not the default).

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.19.4-rc.1
