### ISSUE TITLE
Items not dropped on death / Items despawned immediately

### ISSUE THREAD

**Issue by schall86** [anegostudios/VintageStory-Issues#3602]
### Game Version

1.19.4

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

I have died twice in 1.19.4 very near my spawn point. Both times all items are completely despawned or never dropped. I confirmed that the worldconfig deathpunishment setting is "drop." 

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What mods are installed?
