### ISSUE TITLE
Brown Sedge doesn’t change its color in winter

### ISSUE THREAD

**Issue by Philipp272-2** [anegostudios/VintageStory-Issues#3604]
### Game Version

1.19.3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The color of brown sedge is not change when it’s winter and every other plant is white/gray.

### How to reproduce

Go to a cold place and winter and look for brown sedge.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does it happen in 1.19.4-rc.1? I assume it is fixed
> Tule now has plantable roots.  Tule, cattails, and papyrus now have planter and flowerpot models that respond to climate
