### ISSUE TITLE
Shivering animation don´t stop until reload

### ISSUE THREAD

**Issue by stony99** [anegostudios/VintageStory-Issues#3605]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Once the shivering animation started, it never stops despite having 37.8°C body temperature. Maybe related to #3488. A reload fixes the issue.

### How to reproduce

Get cold enough to start shivering
Sit next to a lit campfire
Shivering doesnt stop until reload

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #3488
