### ISSUE TITLE
Cant place sign on left side of trunk

### ISSUE THREAD

**Issue by kf2903** [anegostudios/VintageStory-Issues#3607]
### Game Version

1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

We're trying to make a Storage system and try to label the trunks with signs, on one side of the trunk the sign places normally onto the trunk itself but on the other side of the trunk it generates half a block out with the signpost attached to the floor and not attached directly onto the trunk

### How to reproduce

place trunk, try to place signs on both sides, see results.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/71091059/c67b2fb3-7a7f-424e-bd67-2bfc3b983bd5)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for the report. Fixed in upcoming 1.19.4
