### ISSUE TITLE
Crates with parchment display stretched image

### ISSUE THREAD

**Issue by vintage-seraph** [anegostudios/VintageStory-Issues#3610]
### Game Version

v.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When parchment is applied to an aged crate, the image of the contents is stretched vertically.  See screenshot.

### Screenshots

![2024-02-18_21-57-19](https://github.com/anegostudios/VintageStory-Issues/assets/117089510/3bd88915-61b9-4c6f-81ea-d88c240f6760)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Isn't "stretched image" purely aesthetic thing?

**Comment by vintage-seraph** [comment]
Hi Dana, It is.  Still it is a visual defect in my opinion.  The dirt looks like a double stack.
![2024-02-19_13-10-33](https://github.com/anegostudios/VintageStory-Issues/assets/117089510/7771ba6c-a7b0-4287-bfdf-d04b15760e81)

**Comment by vintage-seraph** [comment]
Thank you!

Feb 23, 2024 8:15:37 AM radfast ***@***.***>:
