### ISSUE TITLE
(Website) 1.19.3 game updater leads to 404 error

### ISSUE THREAD

**Issue by wasakoki** [anegostudios/VintageStory-Issues#3615]
### Game Version

N/A

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When updating the game, the URL for the updater on the client area (https://account.vintagestory.at/) leads to a 404 error.

### How to reproduce

1. try to download the updater from https://account.vintagestory.at/

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/65874132/0e5bc7df-3a1b-45db-b6fd-4ee5634a4651)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/65874132/e10f0374-51f3-498a-b10d-3c2e73fd9a1b)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for reporting, this seems to be an intermittent issue affecting a small proportion of people these last 2 days, we are investigating.  Please try a different download file on the same page - maybe the full install, or test version 1.19.4-rc.2 released today.

**Comment by tyronx** [comment]
this is now fixed, thanks for the report
