### ISSUE TITLE
creative worlds unplayable

### ISSUE THREAD

**Issue by MaxitectDork** [anegostudios/VintageStory-Issues#3620]
### Game Version

1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Crashes when trying to load a singleplayer creative world.

### How to reproduce

1. load a creative world on single player
2. crash

### Logs

Running on 64 bit Windows with 24412 MB RAM
Game Version: v1.18.15 (Stable)
2/22/2024 3:23:32 PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.Exception: SendServerAssets failed. See log files.
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket() in VintagestoryLib\Server\ServerMainNetworking.cs:line 1101
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass13_0.<QueueLongDurationTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 122
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/22/2024 3:22:01 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER41FB.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER441E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER442F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER442D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER444D.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_8b4e867f-3a5c-449f-bcf9-a7c473ebb9d2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6c6fb9d6-6465-45b4-90eb-a982d2f0b35b
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/22/2024 3:21:57 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x450
Faulting application start time: 0x01da65e591d8c183
Faulting application path: C:\Users\Nrohd\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Nrohd\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 6c6fb9d6-6465-45b4-90eb-a982d2f0b35b
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2/22/2024 3:21:47 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
CoreCLR Version: 7.0.1624.6629
.NET Version: 7.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: SendServerAssets failed. See log files.
   at Vintagestory.Server.ServerMain.BuildServerAssetsPacket() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 1101
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass13_0.<QueueLongDurationTask>b__0(Object a) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\TyronThreadPool.cs:line 122
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 }

**Comment by radfast** [comment]
Post `server-main.txt` log file please, it may have further clues.

Does this only happen for one specific save file?  What if you create a new game, does that have the issue?

General comments:
- fairly confident there is nothing like this generally wrong with Creative Mode in game version 1.18.15, that is a stable game version which has been used by thousands of players (including Creative players) for the past 6 months or more
- you may have disabled core mods (Essentials, Creative Mode, Survival Mode) which are required, don't disable those!
- if not that, then you may have an incomplete or broken installation, especially if you moved around files yourself; please try a fresh installation using the Full Installer
- if not that, then I'm out of ideas, I guess could be something very wrong in your serverconfig but that shouldn't really affect this
- we've now updated to game version 1.19, try the latest 1.19.4-rc2 it resolves around 400 issues though not this specific one (it has an issue with the Clayforming process but that won't affect you if you are playing in Creative)

**Comment by MaxitectDork** [comment]
> Post `server-main.txt` log file please, it may have further clues.
> 
> Does this only happen for one specific save file? What if you create a new game, does that have the issue?
> 
> General comments:
> 
>     * fairly confident there is nothing like this generally wrong with Creative Mode in game version 1.18.15, that is a stable game version which has been used by thousands of players (including Creative players) for the past 6 months or more
> 
>     * you may have disabled core mods (Essentials, Creative Mode, Survival Mode) which are required, don't disable those!
> 
>     * if not that, then you may have an incomplete or broken installation, especially if you moved around files yourself; please try a fresh installation using the Full Installer
> 
>     * if not that, then I'm out of ideas, I guess could be something very wrong in your serverconfig but that shouldn't really affect this
> 
>     * we've now updated to game version 1.19, try the latest 1.19.4-rc2 it resolves around 400 issues though not this specific one (it has an issue with the Clayforming process but that won't affect you if you are playing in Creative)


it turns out its happening with any world that isnt a multiplayer server, whether the world is new or old.
all essential mods are enabled, and theres no mods ive downloaded except when connecting to servers.

a while ago i updated to 1.19 but went back to 1.18.15 to play on a server that has not updated yet. once they update i'll try the  new version and see if that fixes my issue.


[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14388564/server-main.txt)

**Comment by radfast** [comment]
> if not that, then you may have an incomplete or broken installation, especially if you moved around files yourself; please try a fresh installation using the Full Installer

Your log file shows it's this.  You have mixed together 1.18.15 and 1.19.x files by making manual changes.  That's not going to work.  You're welcome to run two different installations of the game, but you need to keep each in a separate folder.  I suggest delete the whole game folder (take care to keep the separate VintagestoryData folder with your settings and Saves, or maybe you changed that folder too?), then use the full installer for each version you want.  The installer allows you to set a different, custom, installation path.
