### ISSUE TITLE
Temporal storm skybox creature's textures display as missing

### ISSUE THREAD

**Issue by nikivarvar** [anegostudios/VintageStory-Issues#3623]
### Game Version

v1.19.4-rc.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Big giraffe creature in the skybox during temporal storms have missing textures for some reason, tried restarting the game and it's the same in two different worlds.

### How to reproduce

1. Make a sample world
2. Do `/time add 1 year`, so the next command would trigger a heavy temporal storm, big giraffe has higher chance of being displayed
3. Do `/nexttempstorm now`

### Screenshots

![2024-02-23_20-34-40](https://github.com/anegostudios/VintageStory-Issues/assets/9913382/4ca93bd7-1de3-4797-a1b5-75a6990a6b67)

### Logs

```Log```

**Comment by CookieBoy21** [comment]
This issues was fixed in v1.19.4 - Stableified glue. I tested it in v1.19.5-rc.1 - YABATP.
<img width="1280" alt="Vintagestory Screenshot 2024 03 08 - 13 52 18 98" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/52e2c9ac-afa7-47be-a1f5-61873667cc74">
