### ISSUE TITLE
Clay forming BUG!

### ISSUE THREAD

**Issue by WickedBuzzard** [anegostudios/VintageStory-Issues#3626]
### Game Version

v1.19.4-rc2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When I use sculpting forms from 1 or 3 types, I can’t finish them, since the rows shift regardless of the completion of the previous ones!

### Screenshots

![2024-02-24_16-44-30](https://github.com/anegostudios/VintageStory-Issues/assets/161125142/1058aa48-a107-40f1-a6a6-f090a1d46240)

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in 1.19.4-stable when it comes, thanks for reporting
