### ISSUE TITLE
Ferns don't drop when the soil block is broken.

### ISSUE THREAD

**Issue by Grubtuk** [anegostudios/VintageStory-Issues#3629]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Ferns (Deer, Eagle, Cinnamon) don't drop when the soil beneath them is broken. They just disappear into the void. They should probably drop their item similar to flowers.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is intended, I found `disappearOnSoilRemoved: true` attribute which is only used for fern block
