### ISSUE TITLE
Snow Blocking NPC Traders

### ISSUE THREAD

**Issue by Airova** [anegostudios/VintageStory-Issues#363]
**Game Version:** 1.11.10
**Platform:** Windows 8.1
**Modded:** Yes (CarryCapacity, Salt Production, Some of my own tweaks)

### Description
Not a bug as such, but an issue: in snowy biomes (so my entire snowball world), NPC traders will sometimes have a layer of fallen snow on the gates leading into their wagons. Because the area is protected, this snow can't be broken in survival mode, so you can't get in, and sometimes the trader is too far away to call over by right-clicking. In my single-player world I can just jump into creative mode to break the snow, but obviously that's not the case on servers, etc. 

I would suggest this could be fixed by either:
1. making it so NPC traders can't get snow on their wagons (or at least not on the gate)
2. making it so that snow layers are an exception to protection
3. making it so we can walk through snow layers (which to be honest, would be my preferred solution - it's pretty strange to not be able to walk through leafs, for example, when they have a thin layer of snow on the top - maybe if we walk through a suspended snow layer it would even disappear, which I think would be most realistic

### How to reproduce
1. Make a snowball world and walk around until you find a trader. The ones where the gate is not covered by a roof usually have this issue.

### Screenshots
![snowed in](https://user-images.githubusercontent.com/13468600/73648046-03649080-467d-11ea-8878-3a3de74fa67b.jpg)

**Comment by tyronx** [comment]
in v1.12 the 1 thick snow layers will no longer have a hitbox so you can pass through them
