### ISSUE TITLE
korean Font Error

### ISSUE THREAD

**Issue by zenser30** [anegostudios/VintageStory-Issues#3632]
### Game Version

1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

If change the language to Korean, the Korean language on some screens will be broken because the font does not match

### How to reproduce

change ingame setting lang Korean

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/29816137/0ac868de-c09f-47f3-af13-ebc3f26ecf16)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/29816137/542bdf7e-f805-43ff-8d5c-c1e9043ed826)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/29816137/e72b4d44-b7c0-49e4-91dc-a7ac30e3af27)

### Logs

```Log```

**Comment by zenser30** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/29816137/acb32b27-83bb-49c1-809e-bba15e8021c3)

**Comment by zenser30** [comment]
"defaultFontName": "batang",
    "decorativeFontName": "gulim"
![image](https://github.com/anegostudios/VintageStory-Issues/assets/29816137/221ebcdf-b905-4523-a4a5-fb3b33a2f35c)
The way I tried is to find fonts that support Korean and put them in one by one. batang, gullim are easy to see and even some words that are not fixed are fully printed

**Comment by tyronx** [comment]
thanks for the report, will be fixed in 1.19.4 stable
