### ISSUE TITLE
Very Erroneous Density Prospecting Results for Certain ore

### ISSUE THREAD

**Issue by Bownz11** [anegostudios/VintageStory-Issues#3637]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

This has happened mostly in the last 2 years on stable versions with fresh worlds, and no mods aside from prospector info, which is a text scraper only, and they always match what is shown in the in-game chat as well. I recently started a new 1.18.14 world in January, with dozens of mods, and had this same type of results. But I wouldn't chalk it up to mods, aside from potentially PI...

Across several playthroughs, and across the past year or two, I have noted several times where prospecting results have changed dramatically for the same chunk when re-prospected, in both directions (showing new deposits not previously shown OR taking away some that were purportedly there). I'm unsure as to how / why. That being said, essentially, it will provide almost all correct readings, Say, High Native Copper, Decent Bituminous Coal, Decent Sphalerite and Traces of Cinnabar. You could expect to find all three of those ores in the chunk column. But I have on several worlds, got readings like that, then do a prospecting node search wit radius of 256 or resorted to creative to dig spaced vertical shafted when I suspect it to be incorrect and find no results. 

Like maybe there was no copper period, then re-placing the stone blocks in the exact same positions I initially prospected to get the initial results. Will get a different result, usually after a fresh game restart. Which would Correct? The readings to Decent Bituminous Coal, Decent Sphalerite and Traces of Cinnabar. With no mention of copper (correctly since there is none)   OR recently I've had the inverse, prospecting several hundred instances to never find an ore, only to dig for something else and find absolutely boat loads of the ore. I will attach several screenshots from various times this has happened, as I brought it up in the discord prior. I will attach some live game screenshots of freshly prospected areas, which I tried to mine, followed by re-prospecting them after a client restart, showing different results.

This has happened mostly in the last 2 years on stable versions with fresh worlds, and no mods aside from prospector info, which is a text scraper only, and they always match what is shown in the in-game chat as well. I recently started a new 1.18.14 world in January, with dozens of mods, and had this same type of results. But I wouldn't chalk it up to mods, aside from potentially PI...

You can reach out to me on the discord if you like @Bownz

### How to reproduce

1. Play the game
2. Prospect for minerals, traveling far and wide for hours trying to find borax
3. Get readings of no borax anywhere
4. Give up, go mine Native Platinum deposit, freshly prospecting it for a large area
5. Find huge Borax and Sulfur deposits. ( No readings??? Also no sulfur ever anywhere in this world yet...)
6. Prospect and get no results again
7. Restart Game Client
8. Re-place stones in exactly the same locations as 30 seconds ago
9. Prospect and get correct? Results showing deposits.

### Screenshots

![2024-02-25_17-16-00](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/476a56ce-6f59-4593-ba6a-3398f735ffcc)
![2024-02-25_17-16-22](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/4d0a90b3-bd0e-425c-906a-aa43c6fcd630)
![2024-02-25_18-59-40](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/cb7e6a05-7926-4cad-bc79-6452242620c4)
![2024-02-25_18-59-52](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/608f3b73-027b-4cd7-86fc-f0b970bb59fc)

The four above are from today, and show no results, being corrected to showing some results. This client is modded

The below images are from last October, and are noted in the discord, and show it having some amount of ore, and then after a client restart, showing no results, the final 3 pictures show a cheesed node search with radius of 256, confirming there was no spawns period for the whole, which would be very unlikely, even with the purported low readings, that were higher than others that show huge amounts in the node search.

![2023-10-29_23-16-41](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/72706043-e73e-47d4-942b-bc147d81e18d)
![2023-10-29_23-16-35](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/84de70f2-1899-4c7c-b490-28379e2a5f6d)
![2023-10-29_23-15-23](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/f91a1e7e-df93-4bad-ad25-8923f99a007c)
![2023-10-29_21-35-41](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/fd0a9ef9-0522-4809-a457-28d28ebe3996)
![2023-10-29_21-35-22](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/b95caded-94d2-4969-9403-944b85efa99c)
![2023-10-29_21-22-53](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/c70cbd06-ff25-492f-8e38-2e255cc0ce61)
![2023-10-29_21-22-28](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/74260657-0048-468c-a710-74f70f81cc2f)
![2023-10-29_21-19-29](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/8876f5a2-2e3e-4c78-9c0f-b8448a65c1ce)
![2023-10-29_21-19-07](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/a0b74ace-2d81-46ea-b4be-4b940e23fc3c)

**Comment by Bownz11** [comment]
I also recalled an area on this same modded world, where I could not find borax, triggering this expedition, I sunk a shaft through the sedimentary layers (about 60 blocks depth) that can hold borax, and found none, digging shafts spaced 10 apart, (node search radius 5. so there is 100% coverage, and across about 15 chunks with admittedly poor results, I found no borax what so ever, but many of the "very poor" or traces of, ores. and a few not listed. 

![2024-02-25_20-39-58](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/57e29b99-6543-44aa-ba8b-cd2fd2666006)
![2024-02-25_20-40-18](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/57ea6d37-8302-469d-9533-1368179f84bb)
![2024-02-25_20-40-47](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/b03015e2-c800-43f0-92c3-5c937dc7ef88)
![2024-02-25_20-40-50](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/6b8c6462-3f55-4aa2-85e3-3a2d3515f353)
![2024-02-25_20-40-52](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/4ed94604-2524-4c49-a404-bc12e6f7f3a8)
![2024-02-25_20-40-55](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/384e6482-9d04-44f8-8fd8-dc0494460a79)

I've gone and checked all the chunks that showed a hit for borax, there is no borax to be had here period.

I've noted this with his world as well, several ores are simply not found in anything, traces, or any density, including two types of iron, (magnetite, limonite)..

I am quite worried as I've had this bug / issue on my personal radar for quite some time, and it really makes me wonder because of how many people that have trouble finding a specific ore in gameplay help that may not have 30 gameplay hours of patience accross multiple weeks to spend prospecting and finding the ores, simply they are not displaying because of potentially a bug, or chasing ores that aren't there, when this aspect of the game is difficult enough for the average player, and a point of gripe of many (Not me, I love mining, obviously.)

**Comment by Craluminum2413** [comment]
Does it happen in 1.19.3?

**Comment by Bownz11** [comment]
I haven't attempted it yet in 1.19.3 although it happens infrequently and I'm not sure the exact sequence of events to get it to begin to occur, I've had it occur since at least 1.16 I would speculate. I can attempt it in the future, but I think time may be a factor. It may be hard to actually tell, especially In the case you don't find something you're after, you may never go through the area again or re-prospect an area you've been to. I suppose it may be worth a foray into a vanilla version of 1.19.3 to see if I can replicate it. 

My thoughts for reproduction of the bug would be play for some extended period of time. I usually play 3 or 4 hours, usually traveling and prospecting a few thousand blocks in a new area. Log off, or restart the client, then begin prospecting again getting sometimes vastly different results, usually pertains only to a certain few minerals. I will say the only ones I for certain know it had happened with are Sulfur, Borax, Bituminous coal, and Anthracit. As I usually spent a lot of time prospecting and mining those.

**Comment by Bownz11** [comment]
I've had it occur again, within minutes of launching the game, I was fleshing out some areas near my house for results, found potentially both Bituminous Coal and Anthracite with somewhat poor results, and did a fresh swath of chunks, all show results, and after digging 5 or 6 vertical shafts across 7 or 8 chunks, found none. I then, prior to restarting, re-prospected a few of the chunks, still showing anthracite results, then exited to menu, and re-loaded the world, still got results showing anthracite. I then set propick radius to 256. and relaunched the entire client, I verified that within 256 of the chunk there is not a single piece of Bituminous coal or Anthracite, and then I re-prospected at the same previous location for one chunk which I marked out. And got "corrected" readings, showing only the results of what actually shows up on the 256 Radius Node search, matching up pretty well. 

![2024-02-27_22-49-00](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/651546ce-d2a8-4405-9c23-1f4483b8e68d)
![2024-02-27_22-49-02](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/d54d6055-e5a1-4290-a752-9a7742231235)
![2024-02-27_22-49-15](https://github.com/anegostudios/VintageStory-Issues/assets/64448580/38641863-5e9e-41c6-a5f2-c4a141c8f772)

looking at my results across the few chunks, it seems to only be affecting a few types of ore, Bituminous Coal and Anthracite certainly, but a few of the results showed both Borax and Sulfur specifically that disappeared afterwards.

And only seems to occur differently after / when relaunching the entire client? 

I'm going to setup a vanilla 1.19.3 world, and creative in some equipment and play survival my more normal way, to see if I can get results over the next few days.

**Comment by FluffyTowels** [comment]
Isn't density prospecting for one horizontal point rather than the entire chunk?

**Comment by Bownz11** [comment]
Density is the Reading of probabilities of spawns, taken for the Density Map, You may be mixing it up with Node search, which is the definitive, yes no / hot cold reading of what is *truly* there

**Comment by FluffyTowels** [comment]
No I meant the chance based density mode. According to the wiki (and my personal experience) the results are based on the specific block's horizontal coordinates rather than the chunk. Though there is a chance I am wrong about it since I'm a somewhat new player

**Comment by Bownz11** [comment]
Oh yes, you are correct, for these tests I usually centre on a specific chunk (one of the 4 centre blocks) and re-place the specific block used for initial and subsequent blocks used to re-test and get the same physical results. Which are always the same exact numbers and densities, aside from the added / removed Erroneous / False positive ones

**Comment by radfast** [comment]
Likely related to #3557.  I don't think you need to test any more for now @Bownz11 .  We'll see if we can get #3557 fixed in next release in next few days, and then if you can kindly test that that is also OK with your tests, that will be awesome.

**Comment by Bownz11** [comment]
Hey yup. Reading over that one, I believe that's the culprit, personally. I was thinking it was some issue with the ore map but I'm only getting the symptoms on the play side seems that guy dug REALLY deep into the code side. I mostly noticed in my singleplayer unmodded worlds starting September/ October quite heavily but itbwas only for certain ores only some of the time. With the results being mostly right. So that would make sense. Then mostly played a multi-player sever that didn't restart often and didn't find much issue.  I thought I searched pretty good for mining and prospecting and density and stuff but not hard enough it would seem. I'll test a bit once I see a patch go through in 1.19. Thanks rad!

**Comment by radfast** [comment]
As mentioned above, we believe this issue will be fixed in upcoming 1.19.5, but would be grateful if you have the chance to test and confirm when it comes ... likely 2-3 days from now, I cannot be certain at this point.   I will close the issue for now but you are welcome to continue posting, I will be notified and will see it.

**Comment by tyronx** [comment]
I doubt it. Pro pick reads from the generated map data, but from the map generators
