### ISSUE TITLE
game starts ok but never launches any world

### ISSUE THREAD

**Issue by stath1121** [anegostudios/VintageStory-Issues#3640]
### Game Version

v.1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

i downloaded and installed a fress 1.19.3 version. the game starts ok and all but when i get to generate a new world it never launches.. It gets stuck on the loading screen. Shows all the events and then every 5 minutes repeats "it pauses", "one last gaze".
the game is vanilla, no mods at all.

### Logs

client-main

https://gist.github.com/stath1121/cfb419b816a17c096ab2943404215f44

**Comment by Craluminum2413** [comment]
Do you have any mods in `\AppData\Roaming\Vintagestory\Mods` or `\AppData\Roaming\VintagestoryData`?

**Comment by Craluminum2413** [comment]
I just checked your logs, you have a ton of mods, try without them and if it still happens, I will reopen this issue

**Comment by stath1121** [comment]
yes sorry you where right! I've had the folder removed before but for some reason it was full of mods now I've checked again. removed them again and its now working! 
Thank you very much!!!
