### ISSUE TITLE
Unlocalized string "material-leadsolder"

### ISSUE THREAD

**Issue by BossmanZero** [anegostudios/VintageStory-Issues#3649]
### Game Version

1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When making lead solder, the crucible calls the result "material-leadsolder" instead of a localized string for lead solder. I have not found values for "material-leadsolder" in any of the language JSONs. "material-silversolder" does appear in most of them.

### How to reproduce

1. Place crucible in fire pit.
2. Add tin and lead nuggets to crucible in proportions for lead solder.

### Screenshots

![Unlocalized material-leadsolder](https://github.com/anegostudios/VintageStory-Issues/assets/84172679/8e6d5d22-66a9-45ac-a81e-cfbaa8d3a2cd)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks, good find, fixed in 1.19.5 when it comes
