### ISSUE TITLE
Clutter bookshelves are not reparable

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#3653]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

All clutter blocks are reparable except these blocks in `survival/blocktypes/wood/` folder are missing `Reparable` behavior:
```
bookshelf-clutter-agedacacia.json
bookshelf-clutter-lore.json
bookshelf-clutter.json
```

```json
"behaviors": [
    { "name": "Reparable" }
],	
```

### Logs

```Log```

**Comment by radfast** [comment]
Thanks, nice spot. Fixed in 1.19.5 when it comes
