### ISSUE TITLE
Drop down selection

### ISSUE THREAD

**Issue by Jeremyrwb** [anegostudios/VintageStory-Issues#366]
**Game Version:** 1.12.2
**Platform:** Windows
**Modded:** No
### Description
Explain the issue you're running into.

Fairly straightforward, the words on dropdown menus in the World customization screen don't line up with where you actually click on.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![image](https://user-images.githubusercontent.com/61125824/74613861-69aed180-50c7-11ea-9af9-a5d89e8c912d.png)

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed in v1.12.3 that i released a few hours ago
