### ISSUE TITLE
Game randomly freezes

### ISSUE THREAD

**Issue by Tumbolisu** [anegostudios/VintageStory-Issues#3666]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

My friend's game randomly freezes with no discernible reason. Sometimes it's just after a single minute of gameplay, sometimes it can take an hour or two. Since the game simply freezes, and has to be force closed, it does not trigger a crash report or anything like that.

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14473799/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/14473802/client-debug.txt)

**Comment by Tumbolisu** [comment]
My friend is starting to suspect that his physical RAM sticks are faulty. So, chances are that there is nothing wrong with the game here!

**Comment by radfast** [comment]
Logs look clean.  Vintage Story does place high demands on all core parts of a PC system, especially at higher settings, so if something is wrong with hardware or drivers then issues are probably quite likely.  We are not _aware_ of any freezing issue in 1.19.4, especially in Windows 10 which must be the most tested - that doesn't mean there is no issue (could be something that only happens rarely with certain worldgen or coordinates), but it is worth ruling out other causes first.

There are Memory Test tools.  I suggest also check / fully re-install graphics drivers, especially if it is quite a new PC.

See also:  https://wiki.vintagestory.at/index.php/Framerate_and_Performance

I will close for now, but please do re-open this if you or your friend believe there is an issue in the game itself.

**Comment by Tumbolisu** [comment]
No issues found with memtest. We have a new clue, though: The game only freezes with VSync disabled! While testing, on two different occasions, the game froze literally just a second after disabling VSync. But it NEVER freezes with VSync enabled.
His monitor has a resolution of 2160x1440 with a refresh rate of 165 Hz. "Window Mode" is set to "Fullscreen". Even though his monitor has a refresh rate of 165 Hz, VSync caps at just 60 fps. His computer can achieve over 100 fps without VSync.

**Comment by Tumbolisu** [comment]
> I will close for now, but please do re-open this if you or your friend believe there is an issue in the game itself.

I don't think I can re-open an issue that was closed by a repo collaborator.

**Comment by radfast** [comment]
Thanks for the extra info.

The game has no deep code using VSync, we just tell the graphics card (GPU) to use it if the player enables VSync.  In other words, the code to operate VSync is inside the GPU drivers or else operating system (Windows) code.  Issues in driver code are also consistent with the situation you describe, i.e. no reported error from the game and having to hard-close the game.

I suggest research VSync issues with this specific GPU or this specific driver version.  If it's an Nvidia card, there is also some info [here](https://www.vintagestory.at/forums/topic/6244-potential-fix-for-stuttering-nvidia-cards/) about good Nvidia Control Panel settings etc.
