### ISSUE TITLE
Server Glitch/Rollback 

### ISSUE THREAD

**Issue by Airova** [anegostudios/VintageStory-Issues#367]
**Game Version:** 1.12.3
**Platform:** Linux (server) / Windows 8.1 (client)
**Modded:** Yes: CarryCapacity, Salt Production, Farmland Drops Soil, + My own tweaks

### Description
Has only happened once so far, only an hour or two after the server had first started. Three players were online and suddenly we experienced a massive lag spike that lasted nearly a minute ("cannot communicate with server" message). No one is sure what caused the lag (similar spikes are caused by caveins/avalanches but no one was aware of that happening this time). About five minutes later, the server booted all the players. The console had no messages at all (seemed to be up and running normally) but no one could log back in. After restarting the server, everyone was able to log back in, but the server had been rolled back to the moment of the massive lag spike earlier.

### How to reproduce
Not sure, unfortunately.

### Logs
The server did not crash and I don't see any log files in the folder. If the logs are kept somewhere other than the game's main directory, I'm not sure where, but I can get them if told where to find them.

**Comment by copygirl** [comment]
> The server did not crash and I don't see any log files in the folder. If the logs are kept somewhere other than the game's main directory, I'm not sure where, but I can get them if told where to find them.

I guess that might depend on how the server is started on Linux. I know there is a script that I think comes with the game you can use and maybe it puts the logs elsewhere?

**Comment by Airova** [comment]
Okay the person hosting the server helped me find the logs. I'm honestly not sure which ones will be helpful or whether they will be helpful at all. I didn't think to grab them right after it happened (but if it happens again I will do so). We kept playing for many hours after that and the server has since been restarted. But in case they are helpful, here are the log files.
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/4219410/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4219411/server-main.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4219408/server-debug.txt)

**Comment by copygirl** [comment]
Yeah I was hoping there was something keeping around past log files but it doesn't look like so.

**Comment by tyronx** [comment]
Yea i also don't see anything related to such behavior. Is the bug reproducible? Perhaps a connection problem with that physical server itself?

If its not reproducibe i think it would be safe to close this issue

**Comment by copygirl** [comment]
I would prefer for it to be marked as incomplete (and optionally close if you really want to) and wait for the issue to occur again so we can be given the logs for the time the server presumably locked up.
