### ISSUE TITLE
Freezing screen

### ISSUE THREAD

**Issue by Resserfis** [anegostudios/VintageStory-Issues#3671]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

From the middle of nothing my game freezes and if i touch something it crashes like every
3-5 minutes freezes

### How to reproduce

Instal like 30 mods and Then it freezes i Think that is mods

### Screenshots

Its not visual lol just freezes

### Logs

I dont have logs

**Comment by Craluminum2413** [comment]
Remove mods
