### ISSUE TITLE
Steel axe durability is not 2.5x iron axe durability

### ISSUE THREAD

**Issue by toasthut** [anegostudios/VintageStory-Issues#3672]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The steel axe has 1800 durability when it should be 2250 (2.5 times the iron axe's 900 durability)

### Logs

```Log```

**Comment by CookieBoy21** [comment]
In this case steel chisel should have 5000 instead 6000 because 2000 x 2.5 = 5000 and steel steel scythe 3375 instead of 3400 because 1350 x 2.5 is 3375.

**Comment by Craluminum2413** [comment]
Suggestion should be posted on forums https://www.vintagestory.at/forums/forum/5-suggestions/ or in official discord

**Comment by toasthut** [comment]
Not a suggestion, just seemed to be an error based on this handbook text. Thank you for the clarification!
![image](https://github.com/anegostudios/VintageStory-Issues/assets/133024025/a7a94302-7168-4154-bd6e-711ddb83c0fa)
