### ISSUE TITLE
Handbook : text overlay

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3677]
### Game Version

1.19.4

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

Example : handbook for glue.  Behind the word mouse you can see a ghost word click. 

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/2b9cf8c2-06cf-4317-a01a-c3faa1a9ff58)

**Comment by Craluminum2413** [comment]
Duplicate of #3638
