### ISSUE TITLE
crucible.json - wrong baking temperature

### ISSUE THREAD

**Issue by Mellygion** [anegostudios/VintageStory-Issues#3679]
### Game Version

1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Wrong value in file ...\Vintagestory\assets\survival\blocktypes\clay\crucible.json 
crucible-smelted
in line: 55
is: meltingPoint: 2400 
should be: meltingPoint: 1200

### Screenshots

![2024-03-04_20-22-06](https://github.com/anegostudios/VintageStory-Issues/assets/74473594/4ec4c232-7a61-45ef-8175-70081ae7e653)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is showing temperature for crucible
