### ISSUE TITLE
Tooltip for wooden pan has broken <hk> tag

### ISSUE THREAD

**Issue by rowantwig** [anegostudios/VintageStory-Issues#3680]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The message has a broken <hk></hk> tag. I don't know how I haven't noticed this until now...

### How to reproduce

1. Hold wooden pan with tooltips enabled.

### Screenshots

![Untitled](https://github.com/anegostudios/VintageStory-Issues/assets/162151342/e2468f5a-b086-4182-afda-dcaa2730f9c6)

**Comment by Th3Dilli** [comment]
thank you this now fixed in 1.19.5-rc2
