### ISSUE TITLE
Game crashes while loading in world

### ISSUE THREAD

**Issue by NicusMaximus** [anegostudios/VintageStory-Issues#369]
**Game Version:** v1.12.4 (Stable)21.02.2020 23:29:27
**Platform:** Windows
**Modded:** No

### Description
I changed the colour of my waypoint and just typed in 2222222 and i guess that caused the game to crash. I tried to load back into my world, and it crashed again, so its not possible for me to play that world at the moment, it seems.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.4 (Stable)21.02.2020 23:29:27: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_PXYtRBuMxa2kzXRdtXFyvLBWC1E entitypacket, _RH2yUybUikKm1ExPZxrALgNaKFn game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_3vohWahW9bdoUNmSAXW5W3dMDmE serverpacket)
   bei _RH2yUybUikKm1ExPZxrALgNaKFn._uBBnmdSghg86404aKMHCaVRqGai(Single )
   bei _GX0cNnpedLggDuZpKPzlyI0yfk1._cmpPjNHBd5qDIbiKqsKvSkTPcHe(Single )
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._l9ByZEMecR7t7QvrEygLSVEPA7G(Single )
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._wVES3I4AcneyUTHpdRuLu6EHvCH(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU , String[] )
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 21.02.2020 23:24:57, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.OverflowException
   bei System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   bei Vintagestory.GameContent.GuiDialogEditWayPoint.onColorChanged(System.String)
   bei Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.KeyEvent)
   bei Vintagestory.API.Client.GuiComposer.OnKeyPress(Vintagestory.API.Client.KeyEvent)
   bei Vintagestory.API.Client.GuiDialog.OnKeyPress(Vintagestory.API.Client.KeyEvent)
   bei _FcKycQ9Qsx721lQUs4UvwfiruyB._XbwacL1qnLSoc1VXKK6482TUwul(Vintagestory.API.Client.KeyEvent)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(System.Object, OpenTK.KeyPressEventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.Platform.Windows.WinGLNative.HandleChar(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU, System.String[])
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(System.Threading.ThreadStart)

 }

**Comment by copygirl** [comment]
I have fixed the initial `OverflowException` crash but Tyron will have to investigate the reoccurring crash.

**Comment by tyronx** [comment]
Please send us your savegame, via drop box or some other file drop server, then i can investigate the other issue

**Comment by NicusMaximus** [comment]
Im sorry i didnt answer sooner. How do i find the savegame?

**Comment by tyronx** [comment]
In %appdata%/VintageStoryData/saves

**Comment by NicusMaximus** [comment]
Ok got it, i didnt use dropbox but used another file share platform, i hope it works.
https://b24-se6yhw.bitrix24.de/company/personal/user/1/disk/path/Vintage story save/

**Comment by NicusMaximus** [comment]
OK got it, i hope it works, never done file sharing before.
https://b24-se6yhw.bitrix24.de/company/personal/user/1/disk/path/Vintage story save/

**Comment by tyronx** [comment]
That seems to require a login, try WeTransfer.com perhaps

**Comment by NicusMaximus** [comment]
all right, here is the link: https://we.tl/t-Pn6OdpN9U0

**Comment by tyronx** [comment]
Thanks, I seem to be able to join the world just fine with version 1.12.5, is it working for you as well now?

**Comment by tyronx** [comment]
Oh I think I know why, should be fixed in v1.12.6!

**Comment by NicusMaximus** [comment]
Ok it does not work for me unfortunatly :/
Here is the Chrash log: 
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.6 (Stable)05.03.2020 16:57:59: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_SvdsJ8rAj5IJMgybr4V0EiweDqA entitypacket, _CeG6XgwLRetaWBDy7Vuk520qgAQ game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_7OUkGToX9NINMWWPfgPKDVWAzxq serverpacket)
   bei _CeG6XgwLRetaWBDy7Vuk520qgAQ._mQhaVaLnY2Z1jjUbgwS7BEeClrG(Single )
   bei _AAX9lxzB4UBE4vpOAjnLc7EGRaAA._ukBPmjLVq1Em3v9POQXsw4ulMUE(Single )
   bei _3bQQdrrneYMg7sUqAp4FsQ2XEfN._lShc2IGpVH0SOA7ydOiSsErkATH(Single )
   bei _3bQQdrrneYMg7sUqAp4FsQ2XEfN._k3aLAIz3swGZO8aqd7pDrKnxALc(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _TPKNmFO93xHjVpa9EspHS9LXWzH._TsFumLr7TNG7iLJEc5uVYqFSeNG(_qRgBLoQrmfmbiUcRN39BpLhs3mN , String[] )
   bei _QHQMScYkRrkBYdQDlv19fyrujIx._TsFumLr7TNG7iLJEc5uVYqFSeNG(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 21.02.2020 23:24:57, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.OverflowException
   bei System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   bei Vintagestory.GameContent.GuiDialogEditWayPoint.onColorChanged(System.String)
   bei Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.KeyEvent)
   bei Vintagestory.API.Client.GuiComposer.OnKeyPress(Vintagestory.API.Client.KeyEvent)
   bei Vintagestory.API.Client.GuiDialog.OnKeyPress(Vintagestory.API.Client.KeyEvent)
   bei _FcKycQ9Qsx721lQUs4UvwfiruyB._XbwacL1qnLSoc1VXKK6482TUwul(Vintagestory.API.Client.KeyEvent)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(System.Object, OpenTK.KeyPressEventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.Platform.Windows.WinGLNative.HandleChar(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU, System.String[])
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(System.Threading.ThreadStart)

 }

**Comment by NicusMaximus** [comment]
Ok i didnt mean to make the text that Big. sorry. -_-

**Comment by copygirl** [comment]
@NicusMaximus No worries I'll fix your comment. Be sure to surround logs with triple back-ticks: ` ``` `

**Comment by copygirl** [comment]
I'm going to close this as duplicate in favor of #390, because this one is also about the initial crash that caused the world to be corrupted.
