### ISSUE TITLE
Auction for 'en route' item : text cropped

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3691]
### Game Version

1.19.5-rc1

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

The screenshot is self-explanatory

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/d9eb7754-a430-4ba9-9ebf-2e4113bac518)

**Comment by Craluminum2413** [comment]
Fixed no idean when
