### ISSUE TITLE
double clicking on a non-empty crock with a bowl of rot crashes game with an unhandled exception

### ISSUE THREAD

**Issue by jgordon510** [anegostudios/VintageStory-Issues#3695]
### Game Version

1.19.4

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Double-clicking on a non-empty crock (in my case it's sealed) with bowl of rot causes the game to crash with an unhandled exception.  Single-clicking doesn't cause the issue, and it's not present on an empty crock.  

### How to reproduce

1. equip an bowl of rot
2. place a non-empty crock on the ground
3. double click on the crock with the bowl of rot enabled

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Where is crash log?

**Comment by radfast** [comment]
Thanks for the report. Fixed in upcoming 1.19.5-stable
