### ISSUE TITLE
Repairing ruined bookshelves reports full asset name in chat

### ISSUE THREAD

**Issue by Agent00Ming** [anegostudios/VintageStory-Issues#3697]
### Game Version

1.19.5-rc1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Repairing the newly repairable bookshelves (#3653) causes the full asset name to be shown in the repair message in the chat.

### How to reproduce

Acquire pitch glue. Locate repairable ruined bookshelf block or place some down from the creative inventory (1.19.5-rc1). Repair said ruined bookshelf. Observe unusual repair message in chat.

### Screenshots

![Grimshot_20240309_074920](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/8236e34d-6a1f-4c46-8f85-b35fd36fcd1e)
![2024-03-09_07-59-02](https://github.com/anegostudios/VintageStory-Issues/assets/107314235/b7385d51-5255-4185-ae98-9ece6f78944a)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for clear report, this will be fixed in 1.19.5-stable when it comes

**Comment by radfast** [comment]
and thanks @Craluminum2413 you're such a star
