### ISSUE TITLE
Jonaslamps not behaving like clutter blocks since glue update.

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3702]
### Game Version

v1.19.5 rc1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Try to mine a jonaslamp or gaslamp in survival (it will break). Try to fix it up with glue (nothing will happen).

Normal clutter behaviour worked in 1.19.3

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for the careful report, fixed in upcoming 1.19.5-stable
