### ISSUE TITLE
Cannot equip glasses?

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3704]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I have been wearing plain glasses for several versions and finally found snow goggles.  I repaired the goggles but, after removing the plain glasses, I now cannot equip either pair of glasses. The slot remains empty!

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by malnaur** [comment]
The same mods I have used for months without issue. None of them are crafting mods.
12/07/2023 09:14 PM 31,213 autoloot.zip
08/17/2023 01:58 PM 11,525 BetterMoisture.zip
02/29/2024 11:19 AM 30,921 blockoverlay-3.2.1.zip
12/04/2023 05:48 PM 37,404 ButcheringFix-v1.0.0.zip
01/25/2024 11:01 PM 49,516 DanaTweaks-v1.2.0.zip with most tweaks disabled
02/29/2024 03:59 PM 10,219 GlowingProjectiles-v1.1.3.zip
01/28/2024 10:17 PM 10,943 HUDGameTimeClock.zip
01/19/2024 01:01 PM 1,992 SatUp.zip
02/13/2024 09:27 PM 11,707 VisibleHighFertilityParticles.zip
01/20/2024 07:56 AM 11,286 VisibleMeteoriteParticles.zip
01/21/2024 07:14 PM 11,257 VisiblePeatParticles.zip
01/24/2024 08:52 PM 11,252 VisibleResinParticles.zip
01/19/2024 07:04 PM 21,967 wrenchtip_disable_1.0.0.zip

The server has BettrerMoisture and Satup

**Comment by Craluminum2413** [comment]
@malnaur Does googles say anything like "clutter" in their description?

**Comment by Craluminum2413** [comment]
Have you tried all slots?

**Comment by malnaur** [comment]
Both pairs of glasses show as clothing items with condition and warmth values. Other clothing slots work fine and other head items like a Minguan and barber hood also work correctly in the same head slot. Only the glasses fail and I started by wearing the plain glasses having equipped them a couple of revs back. Once removed, they could not be placed back. I assume the glasses have incorrect entries in their data that fails to make them valid for head slot.

**Comment by Craluminum2413** [comment]
I can't reproduce this in 1.19.5-rc.1 without any mods
![image](https://github.com/anegostudios/VintageStory-Issues/assets/69315569/fe8668b7-90f0-4113-867a-d754e797de45)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/69315569/b7fa3a33-3ef0-4ac4-b58d-984ad275ed88)

**Comment by malnaur** [comment]
ok. it must just be me.

**Comment by malnaur** [comment]
root cause determined to be my stupidity. issue resolved
