### ISSUE TITLE
Coordinate display off by -1 in each dimension

### ISSUE THREAD

**Issue by BossmanZero** [anegostudios/VintageStory-Issues#3705]
### Game Version

1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The coordinate display box appears to be off by -1 in each dimension when compared to the world map. I also noticed this problem when using the /settlpos function: it would not find the translocator if I used the coordinates from standing on it, even when varying the Y position.

### How to reproduce

1. Activate coordinate display.
2. Stand on a surface block.
3. Open the map and point at the current location marker.
4. Compare the cursor tooltip with the coordinate display.

### Screenshots

![Display coordinates discrepancy](https://github.com/anegostudios/VintageStory-Issues/assets/84172679/f38cb060-74ca-424a-91fe-8147b0131995)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
This is because block you are standing on is 1 block lower than you

**Comment by BossmanZero** [comment]
> This is because block you are standing on is 1 block lower than you, that coordinate display gets position from EntityPos, which is always 1 block higher than block you are standing on

That doesn't explain why the X and Z coordinates are off too.

**Comment by Craluminum2413** [comment]
Strange then

**Comment by Craluminum2413** [comment]
@BossmanZero can you place walls around one block and stay on that block? So that you will be perfectly centered

**Comment by Craluminum2413** [comment]
@BossmanZero map icon is 2x2 pixels size, this may explain why X and Z are different when you hover a little bit further

**Comment by Craluminum2413** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/69315569/7a2fecda-8112-454e-9ff1-41870729e716)
