### ISSUE TITLE
Missing translation for material-electrum

### ISSUE THREAD

**Issue by Grubtuk** [anegostudios/VintageStory-Issues#3706]
### Game Version

1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

There's a missing translation for material-electrum.

### Screenshots

![2024-03-10_19-09-31](https://github.com/anegostudios/VintageStory-Issues/assets/138725381/38c94398-7728-48eb-af2a-5f304fe8c20e)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks, fixed in 1.19.5-stable when it comes
