### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Abi2sweet** [anegostudios/VintageStory-Issues#3708]
### Game Version

v1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Whoops I added this to the forums originally. Hi! I love this game but the other day my pc turned off due to a power outage mid game. Now every time I launch it crashes on validating server or the other black screen loading messages. I cant even get into the main menu. Ive tried re installing the game but no dice. As well as running as admin. Any Ideas? Ive added my crash report

{ TimeGenerated = 3/11/2024 11:54:44 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.4.0, time stamp: 0x65310000
Faulting module name: nvoglv64.dll, version: 31.0.15.4617, time stamp: 0x654d44ed
Exception code: 0xc0000409
Fault offset: 0x0000000000f69625
Faulting process id: 0x1a4c
Faulting application start time: 0x01da73cc6994f891
Faulting application path: C:\Users\PC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1fea8972dc2f0a69\nvoglv64.dll
Report Id: f9fb5718-db37-4151-8def-effa0aa3204b
Faulting package full name:
Faulting package-relative application ID:  } 

### Logs

```Log```

**Comment by Abi2sweet** [comment]
false alarm
Nvidia Driver problems go burr

**Comment by radfast** [comment]
nvoglv64 is part of your Nvidia graphics drivers, yep
