### ISSUE TITLE
Creative Rain Slider Permanently Breaks Weather

### ISSUE THREAD

**Issue by SecretFoxfire** [anegostudios/VintageStory-Issues#3710]
### Game Version

1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

Adjusting the rain in the world edit menu in creative mode permanently breaks the auto-changing weather patterns in the world. I have tested it on both a server and in singleplayer, both in a modded world and in pure vanilla. It is very reproducible.
Unchecking the "override defaults" button doesn't actually re-enable default weather patterns. The entire server stays locked in to whatever rain level I last set, regardless of biome. (This is easiest to test in the desert, where there was a permanent thunderstorm despite "very rare" rainfall.)
I originally turned off the rain to clear the fog so I could see to set up our server, then unchecked "override defaults" to set the weather back to auto-changing. However, after a week or so of play, the players were complaining that it never rained despite being in "almost all the time" rain zones. I tried adjusting the slider to make it rain, then again unchecking "override defaults," but the rain just kept turning off permanently whenever I unchecked the box.
In the end I discovered that if I turned the rain on then logged off of the server and logged back in, THEN unchecked the "override defaults" button, the fog would turn back on. I thought that meant the problem was fixed, but it turned out after more testing that this only locked the rain into the last level I set instead of turning it off. It never stopped raining even in the desert.
After trying everything I could think of, it appears to be impossible to re-set the weather patterns to auto-changing once they have been disabled. For now I have set my server's weather to a light rain so everyone's crops don't dry out, but obviously we would like the weather to be fixed.

### How to reproduce

1. In a new world, in creative mode, find a very rainy area and turn off the rain using the slider in the world edit menu. The rain stops and the fog disappears.
2. Uncheck the "override defaults" button. The rain does not restart and the fog does not reappear.
3. Use the slider to set the rain back to whatever level you want, then uncheck the button again and see the rain clear.
4. Go to a dry area like a desert and set the rain to a high level using the slider. Note that the fog still does not reappear.
5. Leave the world/server and then log back in.
6. Uncheck the "override defaults" button. The fog suddenly appears, and the rain does not stop.
7. Wait as long as you need to confirm that the rain will never stop or slow down and the fog never lifts.

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for the report.

you can fix this for now using the command `/weather setprecipa`
that will remove the rain override

for the next release unchecking the override default values will also remove the rain override again
