### ISSUE TITLE
Worldgen anomaly

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3712]
### Game Version

1.19.5-rc1

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

Chunks freshly generated by v1.19.5-rc1.
TOPTS server, coords = -1000, -54000

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/ecdd5387-96e9-4322-a8f2-8a12738a1ea3)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/84909583/11e77eb8-2262-4161-b8a8-0d6c8d791dbc)

**Comment by Th3Dilli** [comment]
ty this should now be fixed in 1.19.5-rc2

and I manually regened the parts broken on the map there
