### ISSUE TITLE
Mouse Wheel Problem

### ISSUE THREAD

**Issue by dakko12** [anegostudios/VintageStory-Issues#3718]
### Game Version

v1.19.4

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

mods when it first occurred: AccessibilityTweaks_v3.6.1, CarryOn-1.19_v1.7.4
removed mods and it still occurs

Used mouse wheel slider (and other mouse sliders) in an attempt to fix inability to scroll through inventory slots.* Wasn't happy with the result, but played anyway.

Went to use map and, instead of zooming in (as expected) it over-responded to make the map a teeny tiny size. I was able to enlarge the map with my touchpad and found that any use of the mouse wheel resulted in making the map smaller (very very small).

Reset wheel sliders to default positions and it did not fix the map problem. Deleted clientsettings and restarted without changing sliders, did not fix map problem.

Important: 1.19 was installed last night. I played without fiddling with the sliders, and the map was fine. Fiddled with sliders this morning and map broke. Problem also extends to 1.18, which had been fine prior to fiddling with the sliders in 1.19. Btw, I have the TMG shortcut set to allow playing more than one version and I'm surprised that the slider changes in 1.19 affected my other game. This is the target path (and I've used this same means for a number of versions now):  C:\Games\Vintagestory\VS19\Vintagestory.exe --dataPath=C:\Games\Vintagestory\VS19

*regarding scrolling through inventory: I never achieved a satisfactory result, regardless of how much fine-tuning was done with slider(s): kept skipping over some slots, especially slot numbers 1 & 2, almost like it was repelled by those spots (but it also randomly skipped other slots too, just most often it was 1 and/or 2). I inquired about this in the forums (I do not use discord) and one long-time and very experienced user mentioned also having problems and that they no longer use the scroll wheel because of it (they play without a map so could not speak to that issue).

**ETA: changing from Microsoft mouse to Logitech and map is now working. Forgot to check inventory scrolling problem, but will report back.**
**ETA2:** confirmed, using Logitech mouse and both scrolling problems are fixed. This is using the game after deleting clientsettings, so no changes have been made to the sliders... and I'm not going to experiment with it as I am afraid it could break the map again.

### How to reproduce

1. change the mouse sliders (predominantly the wheel slider, although I changed all of them at one time or another in trying to solve the scroll-through-inventory problem; I'm unable to narrow it down as making changes has no effect on the map problem)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does it happen without any mods?

**Comment by dakko12** [comment]
Yes, that was mentioned on line 2: "removed mods and it still occurs"

**Comment by dakko12** [comment]
Was using a Microsoft Mouse; switched to a **LogiTech mouse** and the scroll wheel is now working (on the map). Forgot to check the scroll inventory problem, but wanted to mention this latest news.

**Comment by radfast** [comment]
Sounds like the Microsoft Mouse is broken then, or its drivers are wonky.  If LogiTech mouse works properly, that does kind of prove that the game is working correctly, I would say ...

**Comment by dakko12** [comment]
Yes, **adjusting the sliders** in Vintage Story broke my mouse within Vintage Story. There was **No Problem with My Mouse until I adjusted the sliders**. **Adjusting the sliders** in Vintage Story did something to my system, somehow, to cause the same problem in a completely separate install of Vintage Story that it should not have had access to.

There is **absolutely something wrong with the game**. Please re-read the post and see that it is affecting other players besides myself... one in particular that no longer uses the mouse wheel to access inventory because it is causing problems. Please go to the forum yourself and see what he posted in response to my query.

**Comment by radfast** [comment]
To unpack things:

- Using mouse wheel to select hotbar slots, can sometimes jump over a slot:  this is expected behavior if the mousewheel sensitivity is _above_ 1:1, depending on the physical properties of your mouse wheel of course;  you may also have a non-smooth or jumpy mouse wheel, since the manifestation appears to be different with different hardware.  Either way it is not an issue in the game code I think. Game code works perfectly at 1:1 with a normally working mouse.
- Using mouse wheel to select hotbar slots, can sometimes not move: this is expected behavior if the mousewheel sensitivity is _below_ 1:1, especially if it is the type of wheel which provides output in fixed increments
- Zoom behavior on the map is janky if the mousewheel sensitivity is below 1:1  (zooms out to smallest size if the mousewheel is moved either up _or_ down): this seem to be a bug which I will investigate
- Changing mouse sensitivity settings in one game installation affected another game installation: this is not possible in vanilla if the installations are fully separate, I mean there is no possible mechanism for it - Vintage Story does not output anything which could change a Windows system setting, nor does Vintage Story store any 'hidden' data or settings or anything in the registry (except one thing necessary to enable the "1-click mod install" feature). Specifically, mouse wheel sensitivity settings are read from `clientsettings.json` and no other place. If you are seeing transference then you must be somehow using the same `clientsettings.json` file; or else a mod or launcher is doing something.

**Comment by dakko12** [comment]
I have a hard time accepting that it is strictly a 3rd party hardware issue, especially with the recent report of problems with the Weather Slider (and the similarity of not being able to return to default settings). But I have a few thoughts and some new info:

1. played 1.18 for a short time before installing 1.19 to refamiliarize myself with controls

Everything was normal.

2. I've used separate installations since at least v. 11

At some point (maybe v15 or 16?), the new installation began pulling mod info from the most recent previous installation. My workaround solution: rename folders of previous installations. But I would not have thought it possible for VS to pull mod info from a completely separate installation. I vaguely recall some discussion of this in discord, and perhaps a revision of the Target path was advised? I cannot recall now. My current Target path:

C:\Games\Vintagestory\VS19\Vintagestory.exe --dataPath=C:\Games\Vintagestory\VS19

3. After installing 1.19, I created the shortcut with target path above **before opening the game**

- Played for an hour or so, everything was fine except that there was no ability to scroll through the hotbar (no movement at all). I just used the numbers instead.

**- Despite the target path**, it seems that VS wrote some stuff to Roaming > VintagestoryData, including a clientsettings.json

4. Next day I played again, this time adjusting the sliders.

- that is when the map problem started, in both installations
- inability to return to the default settings* of the night before, even when deleting the 1.19 clientsettings.json (btw, I did verify that 1.18 has it's own clientsettings.json that was last changed about a year ago)

*This sounds very similar (in my opinion) to the weather slider problem that was just reported - inability to return to default settings after using the slider

I don't have time to explore this further as I'm about to head out, but I'm wondering...

Maybe there is an issue with that clientsettings.json in Roaming. Should it even be there, considering the Target path?

**Comment by radfast** [comment]
There are no "ethereal" settings which are not in `clientsettings.json`.

> Despite the target path, it seems that VS wrote some stuff to Roaming > VintagestoryData, including a clientsettings.json

If that is occurring that is a serious concern. How sure are you that this is what occurred, and is it reproducible in the current version?  For example, can you temporarily clear out or rename Roaming/VintagestoryData, then start the game with your target path, and see whether anything gets written to that folder?
