### ISSUE TITLE
Inconsistency: Chert Knapping Unavailable

### ISSUE THREAD

**Issue by Egger3rd** [anegostudios/VintageStory-Issues#372]
I love that this game encourages learning about real life survival skills.  I was a little confused though when knapping was allowed using flint--a type of chert--but not chert.  Just thought it should work the same is all.

**Comment by Craluminum2413** [comment]
> https://www.vintagestory.at/forums/topic/4751-the-homesteading-update-v115-pre1/?tab=comments#comment-22088
> Tweak: Chert is now a knappable stone
