### ISSUE TITLE
Spear attack repeats multiple times after LMB stops being pressed

### ISSUE THREAD

**Issue by Qwsafex** [anegostudios/VintageStory-Issues#3721]
### Game Version

v1.19.5-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description
When I only press LMB once, quite often spear attacks multiple times, which completely messes up timings and makes hunting and fighting very difficult.

**Expected behavior:** spear attacks once
**Actual behavior:** spear attacks anywhere from 1 to 4 times.

### How to reproduce

1. Choose a flint spear on your toolbar
2. Press left mouse button once 

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/17797074/513ad851-1e73-40f2-b2e6-3d85eeb35a86

### Logs

```Log```

**Comment by Natsew** [comment]
@Craluminum2413 I see more and more people affected by this on Reddit, especially the working with metals problem is pretty critical to the game. I don't know how you set priorities, but this might be more important than 'medium'.
https://www.reddit.com/r/VintageStory/comments/1bgvbq6/smithing_splitting_random_blocks_bug/

**Comment by Craluminum2413** [comment]
@Natsew high priority is "Crashes and issues that affect survival gameplay"

**Comment by Natsew** [comment]
@Craluminum2413 thank you for clarification! But doesn't inability to reliably smith metals and use weapons affect survival gameplay? E.g you can easily screw meteoric iron gear when working on it due to the issue: when you remove voxels of metal, it can randomly remove additional parts or move it in the wrong place because this issue lead to random double-clicks in the metal working part.

**Comment by mrgrim** [comment]
After installing rc.2 my hammer and spear were working properly for a while, but something has gone horribly wrong. I can no longer swing my hammer or spear. The spear just kind of jiggles a little on left click, and the hammer doesn't swing at all. Even after restarting the client _and_ server the issue persists!

**Comment by radfast** [comment]
Thank you @mrgrim, it's very helpful to have feedback quickly after -rc.2 is released, we appreciate it!

**Comment by tyronx** [comment]
thanks for the report, please test again in rc.3 that i am about to release

**Comment by mrgrim** [comment]
I put a good 8 hours in on rc.3 tonight, and so far this problem has not reoccurred. If it ever does, I'll update. Thank you for reacting so quickly!
