### ISSUE TITLE
Incomplete tooltip for soybean

### ISSUE THREAD

**Issue by pingouyn** [anegostudios/VintageStory-Issues#3722]
### Game Version

v1.19.3

### Platform

None

### Modded

None

### SP/MP

None

### Description

Till I saw another recent bug report I had no idea you could cook with soybean, thinking it was for pickling only.  On a side note that'll make my wife happy - she used to be a vegetarian!

The help page doesn't bring that info.
The mouse over tooltip doesn't talk about it either.

Similarly to other cooking ingredients, could the following information be added to the tooltip for soybean?
- When cooked: XXX sat        (should be 160 I guess?)
- Food Category: Protein

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does it happen in 1.19.5-rc.1?

**Comment by pingouyn** [comment]
Yes, confirmed in 1.19.5-rc.1

**Comment by Craluminum2413** [comment]
@pingouyn It looks like it is intended that soybeans are only edible after cooking

**Comment by radfast** [comment]
I don't think any items have a tooltip showing their saturation **when cooked**.   (Cattail roots are another example, they are not edible items unless cooked.  Or cassava crop which is edible only when processed.)

The player is supposed to acquire this knowledge by testing things for themselves, or using IRL knowledge I guess.

There is a separate issue here which is there is no Handbook help for the cooking system in general, so no "cooks into" information and no meal recipes.  We will probably add that some time, but it's not a 5-minute fix.

**Comment by pingouyn** [comment]
okies for the "When cooked", it makes sense.
I still feel it's missing the "Food Category: Protein" though.  All (/most?) other harvestable have that tooltip from what I can see.  It would direct the player to be a bit more curious and try things out with this ingredient.

A more in-depth help page about the cooking system would surely help especially with new players.  I appreciate the work it intails, no rush at all :-)
