### ISSUE TITLE
Infinite prospecting with stone bloc and leaf/berrybush

### ISSUE THREAD

**Issue by Nathaanlennon** [anegostudios/VintageStory-Issues#3737]
### Game Version

v.1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer Edit : and solo

### Description

While prospecting, if the stone is placed on top(or just touching) of leaves or berrybushes, when you break the block with your prospecting pickaxe, the bloc isn't destroyed but it just pop on the ground like regular blocks. It need to be surronded by air or other leaves/berrybush blocs

Edit : the bug works with every non-full bloc, even stick, egg, or whatever is stocked on the ground

### How to reproduce

1. While prospecting, put a block of stone on top(or every face) of a leaf bloc or berrybush bloc. The bloc need to be surronded by air/leaves/berrybush
2. Break it with the prospecting pickaxe
3. The bloc pop on the ground like regulars blocs instade of being destroyed

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/56509912/52fc8d1b-3cbf-4205-925d-25b049361610)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/56509912/c3d630cf-628a-4b53-bfe6-dc6f55ca1f57)

### Logs

```Log```

**Comment by Nathaanlennon** [comment]
Edit : I made some tests on solo, and the results are the same, and it work with slabs or chiseled blocs whatever the form of the bloc. I suspect that while the stone bloc is mined by the prospection pickaxe, the bloc is updated and figure out that it's surronded by air and so it pop out.

**Comment by Nathaanlennon** [comment]
Edit : I made some other tests, it work with EVERY bloc who are not a full bloc exept pebble or in-progress flint

**Comment by radfast** [comment]
This is intended behavior, known as "quarrying".  Stone blocks, which have no stone neighbours, will drop when broken ... it is how to make a Quern for example.
