### ISSUE TITLE
Weird artifacts in shadows, with SSAO feature turned on. 

### ISSUE THREAD

**Issue by vegvel31** [anegostudios/VintageStory-Issues#3739]
### Game Version

v.1.19.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Keep seeing artifacts within shaded areas when the SSAO feature is active. Artifacts seem only to shrink when I lower the SSAO from high to medium, and only disappear when the feature is turned off. Adjusting the resolution also affects the artifacts, but to a lesser extent. Seems others have had similar issues, although they were apparently fixed in 1.19.0-rc.2. (https://github.com/anegostudios/VintageStory-Issues/issues/3230).

Tried reverting back to 1.93 and 1.92, but did not see any change. I have also tried experimenting with Nvideas control panel, in case the issue was caused by a setting there, but haven't found anything that changes the effect. Only turning off the SSAO fixes the issue.

As part of the troubleshooting I have done fresh installs of earlier versions, as well as a fresh install of the current stable release, so I don't think it's caused by missing files. 

(_I posted about this earlier on the discord page, but should've just posted the issue here, so sorry in advance if this comes off as a bit overbearing_).

### How to reproduce

1. Activate SSAO on either medium or high quality on the current version of Vintage Story. 

### Screenshots

(Shaded areas with artifact, in this case the resonator. Happens elsewhere as well) 
![2024-03-19_21-44-05](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/eb4354fd-e6ef-43c9-b472-2e9320eeefa3)

(Same picture, but with SSAO turned off) ![2024-03-19_22-59-41](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/d57af6f9-dfa0-460c-85cb-ce183a1e8570)

(Artifacts showing up on the FOV-outline. SSAO turned on, upper left corner) 
![2024-03-19_23-02-06](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/6f825a61-fab2-4646-943e-a96e76999528)

(Artifacts showing up on the FOV-outline. SSAO turned of, upper left corner) 
![2024-03-19_23-02-11](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/ec1353db-22c7-4f25-969f-0dce91c2a593)

### Logs

```Log```

**Comment by radfast** [comment]
Zoomed to show the issue
![image](https://github.com/anegostudios/VintageStory-Issues/assets/6842258/d259c9a0-74b0-4e90-a70f-3719b8fa4326)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/6842258/5bb2458d-c47c-4bfc-b4eb-bac4ba43e1fe)

**Comment by tyronx** [comment]
this looks to be block specific issues, caused by inverted faces

**Comment by vegvel31** [comment]
I've been playing a little while on my save file, and I think you're onto something with the inward facing part, since it's mostly shadows behind objects or in shaded corners. But I also observed it now on a nearby trader, in the shaded parts of his model, so it's not only limited to blocks. I'll post the images below: 

Artifacts on a trader, AND nearby blocks: ![2024-03-21_18-52-44](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/c731153e-0c9f-4609-8395-493472e95a29)

Artifacts on the trader carriage wheels: ![2024-03-21_18-52-27](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/510ee32b-afd3-461e-950e-544a6565db30)

Artifacts in shadows of ruin-blocks: ![2024-03-21_18-39-44](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/898a63d1-aed7-4ebe-a187-9a6025f0712f)

Artifacts in shaded parts of a lantern: ![2024-03-21_18-39-55](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/8bd521d3-e488-41b0-8f42-3daa7b4f8e50)

Artifacts on book and inc&quill, next to resonator: ![2024-03-21_18-39-13](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/9a598fc3-e121-4683-88fe-aac74e7e06c5)

Artifacts on fruit press, watering can, and behind torch in a torch holder: ![2024-03-21_18-39-25](https://github.com/anegostudios/VintageStory-Issues/assets/68665759/d5e1fba2-012e-42f0-977a-3a3d0d4a4a56)

Just give me a notice if you guys want more images or some information regarding the save-file. I'll keep an eye out for any more instances of the artifacts. Going to check out other entities now, in case they have similar shading artifacts like the trader.

**Comment by vegvel31** [comment]
Can btw. confirm that it's still an issue on 1.19.5. I'm also currently playing on another computer entirely, and still experiencing the issue.

**Comment by tyronx** [comment]
artifacting will be reduced in the high quality setting in pre5
