### ISSUE TITLE
Trader Window Not Opening

### ISSUE THREAD

**Issue by Carltoffel** [anegostudios/VintageStory-Issues#374]
**Game Version:** 1.12.4
**Platform:** Arch Linux
**Modded:** No

### Description
One trader has no trading window anymore. Another one is working as expected. No problems with other ingame windows.

### How to reproduce
1. right click on trader opens trading window
2. ???
3. right click on trader locks the view and the mouse cursor appears, but no window opens

### Expected behavior
The trading window should appear.

**Comment by copygirl** [comment]
Have you looked in the logs (specifically `server-main.txt` and `client-main.txt`) for errors that occur around the time you try to interact with the trader?

Also, something I will just mention here that might be unrelated is that it appears you have to have an empty hand to interact with the trader.

**Comment by Carltoffel** [comment]
I could not see anything in the client logs and I didn't looked in the server logs because I assumed a lokal game does not use them.
Right now I am on another computer (still Arch Linux) and the trader works as expected, even with equipped items.

I don't think it is directly related to #379 because in my case right clicking the trader multiple times did not work (but i was able to open chests in this view).

**Comment by Carltoffel** [comment]
> Have you looked in the logs (specifically `server-main.txt` and `client-main.txt`) for errors that occur around the time you try to interact with the trader?
Okay, back on the original machine I was able to reproduce the issue with 1.12.5.
The log files don't contain anything interesting, there is nothing between the unpause and pause messages.

To sum things up, the savegame has no trader window on a specific machine, for a specific trader. Maybe it has something to do with options that aren't saved in the savegame... something like the option whether a window is moveable or not.

**Comment by Carltoffel** [comment]
#382 is related, scaling the interface down solved my issue. So I think the problem is the general window behavior especially when the GUI is scaled. There is another strange behavior when windows are overlapping, they sometimes switch the one which is on top.
How do we continue these issues? Put them together in one issue (windows not showing is scaling related) seems good but what about windows overlapping? New issue or continue in #382?

**Comment by copygirl** [comment]
I could have a look at the overlapping dialog issue.

**Comment by copygirl** [comment]
Update: I looked into the dialog overlapping issue and created a merge request for Tyron to look at, that should fix the odd behavior.

**Comment by tyronx** [comment]
I assume this is fixed by now, please reopen issue otherwise.
