### ISSUE TITLE
The "Cancel" button on create a backup confirmation screen does nothing

### ISSUE THREAD

**Issue by LarekFlynn** [anegostudios/VintageStory-Issues#3744]
### Game Version

v1.19.5 Stable

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

After clicking create a backup on a single player save, the "Please Confirm Create backup now?" screen has a cancel button that does nothing. Expected behavior of returning to the "modify world" screen.

### How to reproduce

1.  launch game
2.  select "Singleplayer"
3. Select the edit button on right edge of a save
4. select "Create a backup"
5. select "Cancel"
6. It does nothing

### Logs

```Log```

**Comment by tyronx** [comment]
thanks, will be fixed in 1.19.6
