### ISSUE TITLE
Game use 30% of GPU Power while in Main menue and background

### ISSUE THREAD

**Issue by Magiehammer** [anegostudios/VintageStory-Issues#376]
**Game Version:** 1.12.4 (stable)
**Platform:** Windows 10 64-bit
**Modded:** No

### Description
The Game still use 30% of my GPU load while just do nothing than moving a static picture in background of the main menu, and also when the game runs in background.

### How to reproduce
Start the Game, switch on another Screen or via Alt-Tab to Task-Manager -> See GPU load.

### Expected behavior
Lower than 10% of GPU load while just Main Menu

### Screenshots
http://prntscr.com/r710pa

### Specs
CPU: Ryzen 7 2700X
GPU: Nvidia GTX 1060 6GB
RAM: 32 GB
144 Hz Monitor -> Setting on 120 Hz -> Game on 120 FPS and V-Sync on.

Greetings,
Magiehammer

**Comment by Angelnoir** [comment]
I can reproduce it in 1.12.5-rc.3 unstable.
Tried a bit with different graphics settings in main menu and found that it scales well with the fps limit.
- Windowed:
--Without vsync:
60FPS = 17% GPU
144FPS = 38% GPU
--With vsync:
60FPS = 99% GPU
144FPS = 99% GPU
-Fullscreen
--Without vsync:
60FPS = 15% GPU
144FPS = 37% GPU
--With vsync:
60FPS = 97% GPU
144FPS = 97% GPU

Additionally I tried to deactivate/activate through all settings and found that only deactivating "God Rays" lowers the gpu utilization in main menu:

- Windowed:
--Without vsync:
60FPS = 6% GPU
144FPS = 11% GPU
--With vsync:
60FPS = 97% GPU
144FPS = 97% GPU

But I think at least in 1.12.5-rc.3 there is something broken with vsync.

Specs
CPU: Ryzen5 1600X
GPU: Nvidia GTX 1060 6GB
RAM: 16 GB

**Comment by Magiehammer** [comment]
Ah, thanks for the tests!
For now I may reduce the GPU load via disabling vsync.

**Comment by Angelnoir** [comment]
I confirm that both issues (vsync and god ray GPU utilization) are unchanged in 1.12.5 (stable).

**Comment by tyronx** [comment]
Thanks for the report and thorough testing, I've now disabled the post-processing effects while the game is in the menu screens. Will be in v1.12.6

**Comment by Bloodsaw** [comment]
I can confirm that the original issue is fixed.
vsync is not fixed, but I will create a new issue for that.
