### ISSUE TITLE
Search issue with quotation marks and brackets

### ISSUE THREAD

**Issue by Erfarenort** [anegostudios/VintageStory-Issues#3762]
### Game Version

v1.20.0-pre.5

### Description

In Russian and Ukrainian translations for some items (tuning cylinders, paintings and tapestries) the best decision is to use guillemets (`«`, `»`) instead of brackets. Is it possible to ignore (equate to a space) quotation marks, guillemets (`«`, `»`, `"`) and brackets (`(`, `)`) in search strings of handbook and creative inventory, how was it done with diacritics in #2559?

Even if maintaining the exact translation with brackets, searching must include them (and not only with tuning cylinders, paintings and tapestries).

**Comment by tyronx** [comment]
ok, this should be in the next release 👍
