### ISSUE TITLE
/time add should not allow negative values

### ISSUE THREAD

**Issue by lOmicronl** [anegostudios/VintageStory-Issues#3764]
### Game Version

1.19.x

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I read both the official forums and reddit, and lately I've been seeing an increasing amount of people reporting problems and broken savegames after using _/time add_ with a negative number to go back in time. Not sure if this is new (perhaps this was overlooked in the command rework), or if this has always been possible, but I've been seeing noticeably more of these posts in 2024 than in previous years.

_/time add_ should really only accept positive values, because savegames still appear to react very poorly to going back in time.

Related: #3170

**Comment by tyronx** [comment]
i agree, thanks for the report, will be in 1.19.6
