### ISSUE TITLE
Anvil double-strike in SP

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3765]
### Game Version

v1.19.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Started a new world and using a copper anvil and copper hammer, I get random double strikes in all modes. Most strikes are fine but a significant percentage are double taps. Seems to be most likely after a rotation. Maybe the fix for failing strikes in 1.19.4 has now promoted double strikes?

### How to reproduce

use an anvil to hand craft a metal piece.

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in 1.19.6
