### ISSUE TITLE
Hammer not registering hits for smithing

### ISSUE THREAD

**Issue by verocrisul** [anegostudios/VintageStory-Issues#3766]
### Game Version

1.19.6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Prior to this update, every now and then the hammer would double hit. A patch was issued to help with that which i downloaded and used today, except now my hammer hit won't register, and it happens much more frequently than the double hitting was.

### How to reproduce

1. heat up iron ingot
2. place on anvil
3. attempt to smith

In my play i was making the double nails and strips.

### Logs

```Log```

**Comment by CattailAle** [comment]
Happens with me on Linux, 1.19.6 vanilla.

**Comment by Craluminum2413** [comment]
Fixed in 1.19.7
