### ISSUE TITLE
Game crash when in Creative menu and attempt to type the letter "T" upper or lower case.

### ISSUE THREAD

**Issue by Bulwark77** [anegostudios/VintageStory-Issues#3771]
I have a Test world to make sure mods and other things work for my YouTube tutorial videos. I noticed on the last update "1.19.6" That it happened and still persists even after the "1.19.7" stable. 
How it happened. Load test world and go into Creative with /gm c enter. Bring up creative menu. Attempt to type "Tools" to search for a particular tool. As soon as I hit the letter "T". Game crashes. 

Attach log files from crash report. 
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839403/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839404/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839405/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839406/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839407/client-main.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839408/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839409/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839410/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839411/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839412/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839413/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839415/server-storyevent.txt)
[server-worldgen.txt](https://github.com/anegostudios/VintageStory-Issues/files/14839416/server-worldgen.txt)

**Comment by Craluminum2413** [comment]
Caused by mod
