### ISSUE TITLE
Wrench won't rotate roof blocks

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3783]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Given the aggravating behavior when placing roof blocks (e.g., slate roof) that refuse to place in a logical way, the wrench should let you adjust them like other blocks but it doesn't. This is a bug even if it looks like a suggestion. Inconsistencies like this are scattered throughout the game and kill immersion.

### Logs

```Log```

**Comment by malnaur** [comment]
Adding a line to behavior for each json file fixes this although the blocks cycle through snow covered and bare as well as rotating so that's weird but it does work.

example:
{ name: "WrenchOrientable", properties: { baseCode: "slantedroofing-{material}-east-free"  } }

**Comment by Craluminum2413** [comment]
Closing because it is a suggestion
