### ISSUE TITLE
1.12.5-rc.3 Chest only opens after double right click

### ISSUE THREAD

**Issue by Angelnoir** [anegostudios/VintageStory-Issues#379]
**Game Version:** 1.12.5-rc.3
**Platform:** Windows 10 64bit 1909
**Modded:** No 

### Description
First right click on a chest make the sound of opening but does not show the chest inventory, second right click on chest make the sound of closing but opens the chest inventory.

### How to reproduce
1. Place a wooden chest
2. Right click it
3. Right click it again

### Expected behavior
First right click on a chest make the sound of opening and opens the chest inventory.
Closing chest make the sound of closing and closes the chest inventory.

**Comment by copygirl** [comment]
Could be related to #374.

**Comment by Angelnoir** [comment]
@copygirl maybe, but in 1.12.4 (stable) this issue does not exist for me. Everything's working as expected there.

**Comment by Angelnoir** [comment]
Is fixed in 1.12.5 (stable)
