### ISSUE TITLE
Experience level doesn't increase

### ISSUE THREAD

**Issue by Fulgen301** [anegostudios/VintageStory-Issues#38]
The experience level doesn't increase, it stays at level 0. The bar below, however, changes its value.

**Comment by copygirl** [comment]
Experience levels are unimplemented currently and they have no use. I suppose once they might have some use it would be strange to suddenly be able to unlock / get access to everything right away. On the other hand, it *would* be nice to have an indication of how long you've played the game (without dying) and some feeling of progres. (Personally not a fan of RPG leveling/skill/... elements in games.)

**Comment by tyronx** [comment]
the xp bar is gone since v1.9, so no longer relevant
