### ISSUE TITLE
Vintage story doesn't start

### ISSUE THREAD

**Issue by thomasbogue** [anegostudios/VintageStory-Issues#3804]
### Game Version

1.19.7

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

My computer froze up, so I hard restarted it.  I can't remember if VS was running.  After I restarted the computer Vintage Story gave the following error when I tried to start it as usual:

Running on 64 bit Linux (Linux Mint 21.3) [Kernel 5.15.0.102] with 32042 MB RAM
Game Version: v1.19.7 (Stable)
4/12/2024 12:50:08 PM: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)

I removed all VS files in ~/.config and ~/.local and reinstalled, but the error was unchanged.  This includes removing all installed mods.  I've started from the start menu shortcut, from the .local folder, and from the install folder with the same result.

### How to reproduce

Start Vintage Story

### Logs

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/14961429/client-crash.txt)

**Comment by Craluminum2413** [comment]
Have you updated your graphics drivers to last version? Have you tried without mods?

**Comment by thomasbogue** [comment]
Further testing indicates that all of my games fail to load.  I'm assuming that something in my OS install is borked.
