### ISSUE TITLE
unable to join server that is specifically for version 1.19.3, only 1.19.3, no other version i cannot do any other version. 

### ISSUE THREAD

**Issue by Woodstonks** [anegostudios/VintageStory-Issues#3805]
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

i cannot join because i am missing zero mods and the game cannot download zero mods 

### Screenshots

![image_2024-04-12_144242196](https://github.com/anegostudios/VintageStory-Issues/assets/166775805/7f9d0c47-e013-4cfa-a488-8ed73025861f)
![image_2024-04-12_144256758](https://github.com/anegostudios/VintageStory-Issues/assets/166775805/4c1991be-50b1-47db-b2f5-1817e12f0ec6)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It was completely fixed in 1.19.4
