### ISSUE TITLE
1.19.7 Berry bushes revert back after shearing

### ISSUE THREAD

**Issue by melodelic** [anegostudios/VintageStory-Issues#3811]
### Game Version

v1.19.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

After each time you have picked berries off a bush (and the bush is sheared), it goes back to being wild looking. Unless something has changed since 2002, Tyron said that it was not supposed to do that and that they are meant to stay sheared for a year.

Note: Cranberry bushes don't always revert to wild after picking them if they are sheared.

### How to reproduce

1) Set down a Berry Bush
2) Use Shears (to make it look less wild)
3) Wait until it has ripened
4) Take Berries
5) It should spring back to being wild

### Logs

https://gist.github.com/melodelic/5ea897b69a732002b42955047b4a5133
https://gist.github.com/melodelic/329f6df546305c0afae434951af50489

**Comment by Craluminum2413** [comment]
How many days per year is set in your world?

**Comment by melodelic** [comment]
9 days (7.2 real life hours) for both the unmodded save (where the logs came from) as well as the modded save I normally play in

**Comment by Craluminum2413** [comment]
@melodelic And it happened after 9 days?

**Comment by melodelic** [comment]
I shear the bushes before spring. then it would flower as it got warm enough. And once it ripened, I would pick it and it would go back to being bushy. But yes, it would happen 2-3 times each year as I hate it when the bushes look wild so I would shear them again once they were picked.

**Comment by melodelic** [comment]
Oh! My bad, I read "How many days per year is set in your world?" as how many days per month. I've got it set as 9 days per month, which is 108 days per year.

**Comment by tyronx** [comment]
PR 60 merged 👍
