### ISSUE TITLE
Lighting issue underground

### ISSUE THREAD

**Issue by m0urnu** [anegostudios/VintageStory-Issues#3813]
### Game Version

1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I covered up one end of a tunnel-like underground cave with several layers of soil (low and medium fertility), cob, and packed dirt. This part of the cave remains lighted as if the outside light got inside. The light level seems consistent with the light level outside (brighter during daytime etc.) 

I later built a cellar there, the separating wall in the images did not create the problem. The problem was there before.

Mods used:
Airtight sleek doors
Better firepit
Carry On
Human-like skin for seraphs
Plains and valleys
Rivers
Simple cloth
The critters package
Vanilla Plus worldgen
Zoom button - reborn

### How to reproduce

I'm not sure. Haven't had this happen before.

### Screenshots

![2024-04-14_20-45-03](https://github.com/anegostudios/VintageStory-Issues/assets/167023310/6631ee3e-851e-4ca5-a124-03d15e566afb)

![2024-04-14_20-45-27](https://github.com/anegostudios/VintageStory-Issues/assets/167023310/5416bec6-6b52-4850-bbae-2cf640de253e)

![2024-04-14_20-45-52](https://github.com/anegostudios/VintageStory-Issues/assets/167023310/4feeb519-1242-4c56-b719-3cecd41ef0f4)
from outside the cellar room with hay blocking the entrance

![2024-04-14_20-45-59](https://github.com/anegostudios/VintageStory-Issues/assets/167023310/ef8c3843-ae4f-407e-825b-93a648f86735)
from outside the cellar room with a hay block removed

### Logs

Not sure what to add here... Let me know if there's something specific I should look for.

**Comment by Craluminum2413** [comment]
Fixed in 1.20
