### ISSUE TITLE
Player Arms Flail with Oar

### ISSUE THREAD

**Issue by CptSwank** [anegostudios/VintageStory-Issues#3819]
### Game Version

V1.19.7

### Platform

Windows 10

### Modded

No

### SP/MP

SP

### Description

When not on a raft, having the oar equipped and left clicking will cause the player to swing their arms constantly until game file is relaunched. Does not appear to affect aim of *Sling* have not tried other ranged/thrown weapons. Tools appear to work normally - Visual issue only, but rather headache/nausea inducing.

### How to reproduce

Equip Oar (Maple used when bug disovered, have not tried other woods) - Left click

### Logs

```Log```

**Comment by Iell** [comment]
I also get this bug. The oar I used was pine.

**Comment by Craluminum2413** [comment]
Duplicate of #3774
