### ISSUE TITLE
Forgotten Noble Robe Rendering Issues

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#3823]
### Game Version

v1.19.7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The forgotten noble robe has a few massive rendering issues.
The hood Z-fights with hair and some belts and accessories become invisible.

EDIT: (The scribe hood also Z-fights with hair, just thought I would edit this to add this in here).

### How to reproduce

Wear the forgotten noble robe.

### Screenshots

![1](https://github.com/anegostudios/VintageStory-Issues/assets/165099009/2fed9147-30ba-481e-8a73-633131743215)
![2](https://github.com/anegostudios/VintageStory-Issues/assets/165099009/bc5da10a-2ed1-4209-ade0-d78ccd2b9a47)

### Logs

```Log```

**Comment by ifozz** [comment]
Just writing this in here; I don't know if the robe was hiding my belt and accessory or if it was from taking armour off and putting it back on repeatedly. I just thought I would add this here.

**Comment by Craluminum2413** [comment]
Does it still happen in 1.20?

**Comment by Craluminum2413** [comment]
I guess it is fixed in 1.20 since all clothes are 3D now
