### ISSUE TITLE
Buckets Sometimes Stack

### ISSUE THREAD

**Issue by JadzD2001** [anegostudios/VintageStory-Issues#3825]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Buckets will stack when picking them up, yet not when stacking in inventory.

### How to reproduce

Have buckets on ground, pick them up with an empty hand will stack them in my inventory. Once I separate them they can no longer be stacked together, unless added to inventory without the use of the mouse.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #862
