### ISSUE TITLE
Missing and misslinked translations on oneskyapp

### ISSUE THREAD

**Issue by Angelnoir** [anegostudios/VintageStory-Issues#383]
**Game Version:** 1.12.5

### Description
Since the german translation was merged into the latest build, I checked some elements ingame.
I found at least one place where translations are missing, but already translated at oneskyapp for months.
Maybe others could help to find more possible misslinked / missing translations.

### Screenshots
![image](https://user-images.githubusercontent.com/7362698/75389435-c63f9700-58e6-11ea-98b7-6aa69fc3b0bd.png)

![image](https://user-images.githubusercontent.com/7362698/75389604-11f24080-58e7-11ea-9b64-d5be25c126dc.png)

![image](https://user-images.githubusercontent.com/7362698/75389652-2df5e200-58e7-11ea-9801-7ff6b0db6dcf.png)

**Comment by Angelnoir** [comment]
![image](https://user-images.githubusercontent.com/7362698/75389873-9775f080-58e7-11ea-94a6-393495d10495.png)
![image](https://user-images.githubusercontent.com/7362698/75389937-b7a5af80-58e7-11ea-8960-76a7c48ddb8b.png)

And the other ones were translated long ago too.

**Comment by Angelnoir** [comment]
In den Einstellungen fehlt auch noch einiges:
![image](https://user-images.githubusercontent.com/7362698/75393965-71ece500-58ef-11ea-9ebe-2d4de67c2315.png)

Und hier das dazugehörige Mouse-over von den Spielständen
![image](https://user-images.githubusercontent.com/7362698/75393300-0eae8300-58ee-11ea-9951-170a61a54704.png)

**Comment by Angelnoir** [comment]
![image](https://user-images.githubusercontent.com/7362698/75616021-b5438f80-5b4b-11ea-927c-5cb076729dc4.png)

There are already translations on oneskyapp

**Comment by Bloodsaw** [comment]
![image](https://user-images.githubusercontent.com/61588797/75627015-c2ed2980-5bcc-11ea-8123-85fe64d346b6.png)

![image](https://user-images.githubusercontent.com/61588797/75627026-d5fff980-5bcc-11ea-9ad7-186f9e48336e.png)

![image](https://user-images.githubusercontent.com/61588797/75627036-e0ba8e80-5bcc-11ea-89b5-b9006fe132db.png)

![image](https://user-images.githubusercontent.com/61588797/75627043-ee701400-5bcc-11ea-835f-e22d105df6f3.png)

![image](https://user-images.githubusercontent.com/61588797/75627055-10699680-5bcd-11ea-85cc-d1470828a8e9.png)

**Comment by tyronx** [comment]
Ok, uploading some extra phrases to one sky now, thanks for the report

**Comment by tyronx** [comment]
This should be all completed by now
