### ISSUE TITLE
Visual bug on creative mode.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#3830]
### Game Version

v1.19.7 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I have visual bug on top of my screen when I run word on creative mode and move in to corner. Thanks to it I can see like with x-ray also I found out that when I will turn on survival mode and turn back creative this bug will be no more.

### How to reproduce

1. Run word on creative mode.
2. Dig small tunnel like on photo.
3. Fly into corner or use ladder for move your camera into corner.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 04 21 - 00 12 35 63" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/61c00ade-8c92-4e6d-83b6-c82ef6f3d571">
<img width="1280" alt="Vintagestory Screenshot 2024 04 21 - 00 12 47 23" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/0a0da7f7-371c-43f7-add0-15c3ef27b77d">
<img width="1280" alt="Vintagestory Screenshot 2024 04 20 - 20 46 41 61" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/c36dbc90-6649-4635-8d7a-fef57ba99f09">

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@CookieBoy21 Does it happen in survival? If no, then I close this

**Comment by CookieBoy21** [comment]
Only in creative mode.

**Comment by Craluminum2413** [comment]
Okay this is not issue then because it doesn't affect anything
