### ISSUE TITLE
Issues with Adding New Playstyle in Mod

### ISSUE THREAD

**Issue by morcam** [anegostudios/VintageStory-Issues#3837]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Yes

### SP/MP

None

### Description

I'm trying to create a new playstyle in a similar way to the existing creative playstyle, and have run into a variety of issues that effectively prevent me from doing so. I'm not entirely sure if this is something that is currently intended to be moddable, but it does seem like that's the intention.

Fixing any one of these issues would allow creating a new playstyle:
1. Adding an new playstyle cannot be done in a normal mod that contains a modinfo.json. The modinfo.json overrides any ModInfoAttribute, so you can't have both, and the WorldConfig field is not deserialized in the modinfo.json, so adding this is not possible through the modinfo.json. 
2. **Removing the modinfo.json to try to use the ModInfoAttribute causes an error in any non-DLL mod. This seems like the most obvious candidate for being a newly-introduced bug,** since the documentation seems to imply that you can use either one mechanism or the other. But this is not the case.
3. Adding a new playstyle IS possible through a DLL mod, but then you can't add the translations for the gamemode name. The translation string would be like playset-myplayset, but there does not seem to be any way to add translations through a DLL mod for the main menu. I also tried using a second mod, but that mod also does not seem to be able to add the translations to the main menu. Adding the langkey to the built-in /Vintagestory/assets/game/lang/en.json works fine, of course.

If there is some way to do this that I'm unaware of, I'd be happy to learn about it! I'm unable to find any documentation on this. 

I did notice there's an early loading patcher mod that allows loading mods in the main menu, which of course allows working around this, although I'd prefer to avoid that, if possible.

**Comment by Craluminum2413** [comment]
Mods don't load in main menu

**Comment by morcam** [comment]
> Mods don't load in main menu

@Craluminum2413 - Playsets are the exception to that rule. We were just discussing this in Discord. Is there something I can further explain about the issue?

**Comment by Craluminum2413** [comment]
You can't do anything with game menu sadly

**Comment by morcam** [comment]
> You can't do anything with main menu sadly

@Craluminum2413 - I'm not trying to mod the main menu. I'm trying to add a new playstyle entry. The playstyle modding is literally in the ModInfoAttribute. It seems clear to me that it's intended to be moddable through some mechanism.

**Comment by Craluminum2413** [comment]
Playstyle is completely main menu feature

**Comment by morcam** [comment]
@Craluminum2413 - Okay! So is the official stance that this modding feature is incomplete and not yet intended for use?

**Comment by Craluminum2413** [comment]
Something Ike that

**Comment by pizza2004** [comment]
This functionality has been implemented for years.  You use `worldconfig.json` in the same folder as your `modinfo.json`.  There is no way to implement the language strings in the current stable release, however.

**Comment by morcam** [comment]
Hey @pizza2004 - That's good to know! But if the language strings still don't work, I wouldn't call this issue resolved? As stated in the OP, I did manage to accomplish the same thing through the DLL mod. But that also has the same problem with language strings being nonfunctional.

**Comment by pizza2004** [comment]
To be clear, there won't be a way to add language files if you are using a DLL mod either way, but the issue *is* resolved internally.  If you'd prefer I could open the issue back up until a stable release where it's fixed, but I'm not sure what the need is since it's not really an issue that people commonly report or search for.

**Comment by morcam** [comment]
Oh, sorry, I didn't understand from your first post that the language strings were actually being fixed in an upcoming release. In that case, this issue is definitely resolved! Thanks!

In my case, I was trying to add the language strings in one (regular) mod, and the playstyle in a DLL mod, with a dependency between the two. But that's not really important, now.
