### ISSUE TITLE
Several identical ruins generate within 50 blocks of one another

### ISSUE THREAD

**Issue by pingouyn** [anegostudios/VintageStory-Issues#3840]
### Game Version

v1.19.7

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

I noticed an extremely unusual ruins generation in my world (seed 416955508).

4 identical ruins generated within the same cave system at coordinates below.  The ruins are fairly small (not sure how to explain, the ones with a crucible in an active firepit situated on chiselled blocks, a straw bed and usable clay bowls nearby).
The only difference between the 4 ruins were the items found inside a broken chest:
- Ruin A: 5134, 31, 2501
- Ruin B: 5170, 27, 2524
- Ruin C: 5171, 51, 2517
- Ruin D: 5183, 50, 2468

Additional info:
* I arrived in that cave system from a translocator, if that makes any difference.
* I didn't finish to check that cave system, there may be other identical ruins.  Sadly I didn't take any screenshot either, sorry, my character was definitely ill-equipped for that cave.
* At the time of chunk generation for that specific area, the only mod used was "Simple HUD Clock".
* I believe those chunks were generated around v1.19.1 to v1.19.3, somewhere there.  It was in v1.19.x for sure as the world didn't exist before that.  All world options were left at default except for "Chisel most blocks"

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Most likely a pure coincidence, I will close it for now
