### ISSUE TITLE
Scrollracks having issues with spawning via worldgen

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3847]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/44593ec6-f150-4641-b6c6-d34c336220b9)
It seems like structures with the scroll rack can cause it resulting in a weird question mark block.

### How to reproduce

Try this mod it spawn scrollracks all over the place with ? texture
[bugfixmod_forscrollracks.zip](https://github.com/anegostudios/VintageStory-Issues/files/15139469/bugfixmod_forscrollracks.zip)

### Screenshots

![2024-04-27_20-34-19](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/0eafa1ec-e1bd-4291-87e8-73d36ca318fb)
![2024-04-27_20-34-27](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/2b796fc6-2233-446a-82fc-4c62b7a7fd8c)

### Logs

No logs pointing to this found. Checked worlgen main and debug

**Comment by AreYSerious** [comment]
Updated with test mod and more images

**Comment by AreYSerious** [comment]
Antler mounts have the same issue aswell pls fix

**Comment by Th3Dilli** [comment]
ty,
those are now fixed in 1.20 ;)
