### ISSUE TITLE
Using commands caused a crash!

### ISSUE THREAD

**Issue by lumit66** [anegostudios/VintageStory-Issues#3851]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/120006851/b45b0a58-fd07-4f10-b430-f3bfe520e4f9)
This seems to be a crash caused by setting double: [3.5] while using the command. How can I fix it?

**Comment by Craluminum2413** [comment]
Pirated versions are absolutely unpredictable and are not officially supported
