### ISSUE TITLE
Broken Items respawn with 1 durability when another item is dragged to its former slot

### ISSUE THREAD

**Issue by Angelnoir** [anegostudios/VintageStory-Issues#386]
**Game Version:** 1.12.5 Stable
**Platform:** Windows 10
**Modded:** No

### Description
_I report this issue for the player Gryphius218_
When an item breaks in a slot on the hand and directly after that, another item is dragged to the same slot, the former broken item reappears in the inventory with 1 Durability left.
After it happens for the first time, it can be repeated with the item endlessly.

It happened two times for Gryphius, first time with a sword, the second time with a chisel.

### How to reproduce
Not sure yet. I myself could not reproduce it. Will try to put more information here when possible.

### Screenshots
Screenshots from Gryphius218

![](https://cdn.discordapp.com/attachments/682941884619948053/682970372576247820/2020-02-28_16-19-34.png)
Chisel in Slot 7 with low durability

![](https://cdn.discordapp.com/attachments/682941884619948053/682970385179869200/2020-02-28_16-19-46.png)
Chisel broken after usage

![](https://cdn.discordapp.com/attachments/682941884619948053/682970390913482777/2020-02-28_16-19-56.png)
Replacing the broken chisel with stones

![](https://cdn.discordapp.com/attachments/682941884619948053/682970392188551230/2020-02-28_16-19-59.png)
Chisel reappeared with 1 Durability

**Comment by copygirl** [comment]
I noticed this can also happen when client and server desync because client thinks it is hitting an enemy but server doesn't. So the client applies damage and desyncs the durability..?

**Comment by Craluminum2413** [comment]
I think it is fixed when auto tool replacing was added, also [this can affect it too](https://www.vintagestory.at/forums/topic/5079-the-homesteading-update-v115-rc3/#:~:text=Fixed%3A%20Durability%20syncing%20issue%20(1.15%20issue)%2C%20on%20replacing%20broken%20tools)

**Comment by copygirl** [comment]
Yeah, will assume fixed until reported otherwise.
