### ISSUE TITLE
Behaviors should be an object keyed by their code

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#387]
Currently, behaviors are defined like this:
```json
behaviors: [
  { code: "repulseagents" }, 
  { code: "controlledphysics", stepHeight: 1.1251 },
  { code: "despawn", minPlayerDistance: 8, belowLightLevel: 8, minSeconds: 300 },
  { code: "health", currenthealth: 5, maxhealth: 5, }
]
```
This makes patching them complicated, as you have to select an array index (`/server/behaviors/3` for health) rather than using the behavior code (`/server/behaviors/health`). So I suggest defining behaviors like this in the future:
```json
behaviors: {
  repulseagents: {}, 
  controlledphysics: { stepHeight: 1.1251 },
  despawn: { minPlayerDistance: 8, belowLightLevel: 8, minSeconds: 300 },
  health: { currenthealth: 5, maxhealth: 5, }
}
```

**Comment by tyronx** [comment]
Really good idea although maybe tricky to get the execute order just right with such layout.

**Comment by copygirl** [comment]
Ah, I didn't think of that. Well, I guess you could have a field for explicit execution ordering, defaulting to ordering by the behavior's name if they're the same priority?

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
