### ISSUE TITLE
Graphite

### ISSUE THREAD

**Issue by udrzba** [anegostudios/VintageStory-Issues#3873]
### Game Version

v1.17.9

### Platform

None

### Modded

None

### SP/MP

Singleplayer

### Description

Graphite. It is not written at all what it is for or what to do with it.

### How to reproduce

![Bez názvu](https://github.com/anegostudios/VintageStory-Issues/assets/169517329/05d847cb-977c-4618-8793-910aaefdc220)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is not used for anything a

**Comment by udrzba** [comment]
Or is the dreamer planning something? graphite is rampant as an anti-corrosion coating in blacksmithing, so I don't know why there is no point.
