### ISSUE TITLE
Flickering & Black Screen Making It Impossible To Play

### ISSUE THREAD

**Issue by zabulonian** [anegostudios/VintageStory-Issues#3876]
### Game Version

v1.19.7

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The following issue is identical on both the Linux version of the game, and the Windows version if run via Wine (tried Lutris's default, Proton-GE-9-2, and Proton-Experimental). This issue also occurs both when installing through the tarball and using the Flatpak version. This issue does not occur on the same hardware when booted into Windows (but I never boot into Windows except to test things like this).

Upon launching the game and entering the main menu, the left side menu will flicker when clicking the mouse around (see steps to reproduce). Upon creating a new world or entering an existing one, the game will flicker to black on the character creation screen, and then remain black except the mouse cursor. Sounds can still be heard.

Changing v-sync settings changed the way the flickering felt (frequency, etc), but the end result was still a mostly stable black screen on character creation. 

This issue can be mitigated by switching to windowed mode, and resizing the window. At certain window sizes, the flickering becomes minimal and I am able to create a character and walk around, though occasionally the screen will flash black. 

PC Details:
Distro: Nobara Linux 39
Kernel: 6.8.7-201.fsync.fc39.x86_64
DE: KDE Plasma 6.0.4
WM: KWin (Wayland)
GPU: Nvidia GeForce RTX 3060 TI
GPU Driver Version: 550.67 
CPU: Intel i7-12700
Monitor Resolution: 2560 x 1440
Refresh rate: 144 hz

### How to reproduce

To reproduce menu flickering:
1. Launch game
2. Open settings menu
3. Open advanced graphics
4. Click around (not on various options, just on the game) 
5. Move mouse around over options. These two steps will cause the left side menu to flicker

To reproduce flickering to black + persistent black screen once in-game:
1. Either create a new world, or enter an existing one. Survival settings do not appear to matter.
2. Wait for it to generate/load. You may notice the generation text box flickering.
3. Once in, you will briefly see the character creation screen flicker to black, and then maintain a black screen with only the mouse cursor visible.
4. Tabbing in or out may make it flicker again, briefly revealing the character creation screen. 

To reproduce the mitigation:
1. Launch the game
2. Navigate to settings, and make sure the game is set to windowed and the border is resizeable 
3. Resize the border until the window is both smaller and more-or-less maintains the look it had when full screen (biome visible around the graphics menu)
4. Either create a new world, or enter an existing one
5. The game will no longer flicker to black as often. 
6. Now, you may move around and do other game activities, but you will notice the game's screen flicker black a few times a minute.

### Logs

```Log```

**Comment by Agent00Ming** [comment]
This is not an issue with the Vintage Story. It is Nvidia drivers not supporting implicit sync. You will have to wait until Nvidia 555 driver drops and explicit sync support getting merged into the Wayland compositor of your choosing.

**Comment by Agent00Ming** [comment]
You can either revert to a driver prior before the 545 series or simply drive your Wayland compositor on intel integrated graphics and offload the game to the Nvidia card.
