### ISSUE TITLE
GUI: World Creation missing options if below 1080 vertical pixels

### ISSUE THREAD

**Issue by Bloodsaw** [anegostudios/VintageStory-Issues#388]
**Game Version:** 1.12.5
**Platform:** Windows 10 64bit 1909
**Modded:** No 

### Description
Tin and Copper drop-down boxes are cut if the resolution or window size is below 1080p

### Expected behavior
Maybe an additional vertical scrolling of the menu if the drop-down fields are opened

### Screenshots
![image](https://user-images.githubusercontent.com/61588797/75605961-5ef13500-5ae8-11ea-89f7-b517bdae9081.png)

**Comment by Craluminum2413** [comment]
Right now it is much higher and I don't think there should be any difficulty with this setting
