### ISSUE TITLE
Female caribou don't grow antlers

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#3885]
### Game Version

1.19.8

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Female caribou don't grow antlers in the game, even though they do IRL.

### How to reproduce

View a male and a female caribou in November. Note that the male has antlers and the female does not.

**Comment by Craluminum2413** [comment]
This is a suggestion https://www.vintagestory.at/forums/forum/5-suggestions/
