### ISSUE TITLE
Client crash  on joining modded server.

### ISSUE THREAD

**Issue by Matiam0** [anegostudios/VintageStory-Issues#3888]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I'm not entirely sure what the cause is. I've tried removing the mods and adding them back 1x1, New World, and a few other things, but the issue just comes back later. Let me know if you need further info.

### How to reproduce

1. Join the server [71.127.152.175:42420],
2. Play for a bit or crash instantly on join. CTD

### Logs

**Client**
[Crash](https://gist.github.com/Matiam0/7f51398761fad1aa98f3935d090c7818)
[Main](https://gist.github.com/Matiam0/0901c44ca768231c80477be44984f123)
[Debug](https://gist.github.com/Matiam0/386d300033d52e95edf013c623a60414)

**Comment by Craluminum2413** [comment]
Does it happen without any mods installed?

**Comment by Matiam0** [comment]
It happens with mods, vanilla is fine. If this is the wrong area I'd like a point in the right direction.

**Comment by Matiam0** [comment]
Alright, no clue as to what mod it might be but thanks anyway.
