### ISSUE TITLE
Client crash after try to login to 1.19.8 server

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#3889]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Server update, client update, clients permanently crashes and can´t connect to the server.

Running on 64 bit Windows 10.0.19045.0 with 65458 MB RAM
Game Version: v1.19.8 (Stable)
25.05.2024 7:37:03: Critical error occurred
Loaded Mods: bettercrates@1.7.1, chiseltools@1.11.5, coloredeggs@2.0.0, extrachests@1.8.0, largercrock@1.0.2, millwright@1.1.5, primitivesurvival@3.5.5, rpvoicechat@2.3.9, locustmod2@2.4.2, temporal_gears_stack@1.0.0, translocatorengineeringredux@1.5.1, game@1.19.8, alchemy@1.6.32, betterfirepit@1.1.4, carryon@1.7.4, commonlib@2.3.7, composter@1.1.0, electricity@0.0.11, farmlanddropssoil@1.4.0, fromgoldencombs@1.4.30, hudclock@3.4.0, leaderstats@1.0.29, medievalexpansion@3.13.1, moreplaster@1.0.2, natsachievements@1.1.0, petai@2.2.4, playerlist@1.7.4, sleepvote@1.0.7, stonebakeoven@1.1.3, creative@1.19.8, survival@1.19.8, woodbarrels@1.1.0, workbenchexpansion@1.8.0, xlib@0.8.3-pre.1, cats@2.0.1, cavebeacons@1.0.8, electricityaddon@0.0.2, electricityextensions@0.0.6, em@2.6.0, playercorpse@1.9.0, tpnet@1.14.3, wolftaming@2.1.2, xskills@0.8.5-pre.1, bricklayers@2.5.3, moreroads@1.5.6
System.Exception: Don't know how to instantiate item of class 'itemcanchestslist' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 274
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 18
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 570
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 388
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 341
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25.05.2024 7:36:12, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.19.8.0, časové razítko: 0x661e0000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x3940
Čas spuštění chybující aplikace: 0x01daae65480e1f2d
Cesta k chybující aplikaci: D:\games\Vintagestory_1_19\Vintagestory.exe
Cesta k chybujícímu modulu: D:\games\Vintagestory_1_19\Lib\openal32.dll
ID zprávy: c3a3f8f1-2afe-4cdd-8ba7-10e87b7a7555
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 25.05.2024 7:35:57, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.19.8.0, časové razítko: 0x661e0000
Název chybujícího modulu: KERNELBASE.dll, verze: 10.0.19041.4355, časové razítko: 0xd7762934
Kód výjimky: 0xe0434352
Posun chyby: 0x000000000002ba99
ID chybujícího procesu: 0x3940
Čas spuštění chybující aplikace: 0x01daae65480e1f2d
Cesta k chybující aplikaci: D:\games\Vintagestory_1_19\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Windows\System32\KERNELBASE.dll
ID zprávy: e4bc8eda-0d59-46f4-aded-96da4a0a5b3e
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 25.05.2024 7:31:49, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.19.8.0, časové razítko: 0x661e0000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x1df8
Čas spuštění chybující aplikace: 0x01daae64a94553f1
Cesta k chybující aplikaci: D:\Games\Vintagestory_1_19\Vintagestory.exe
Cesta k chybujícímu modulu: D:\Games\Vintagestory_1_19\Lib\openal32.dll
ID zprávy: 29ee47bc-e442-496b-809a-7dd079be260c
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by Craluminum2413** [comment]
itemcanchestslist is modded item
