### ISSUE TITLE
Savegame doesn't start after crash

### ISSUE THREAD

**Issue by Aelin22** [anegostudios/VintageStory-Issues#389]
**Game Version:** 1.12.5
**Platform:** Windows 10
**Modded:** No 

### Description
The game was paused and when I came back to my laptop it crashed. I tried to start the saved world again and it doesn't work. (It still crashes after restart of the laptop)

### Logs
```
Version: v1.12.5 (Stable)29.02.2020 12:58:19: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_8dScwjQY5uofBfFnZ0b1RxQaDb0 entitypacket, _cbodHKZNx5G5B0ajOJRiKOMUi6d game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_ao2wb43bENgLDz41hdvNvtazUHu serverpacket)
   bei _cbodHKZNx5G5B0ajOJRiKOMUi6d._BhJwuFi29qoR0AeIVw0bFfSc9Yg(Single )
   bei _eFf91QQdB7idG1E2ZqAM9ppaVVg._L70FVKtGSJalOIsw6MvDPGFXhpg(Single )
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._AjNkRnsn39TXAz2S4OVzXdXYu0h(Single )
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
```

**Comment by Bloodsaw** [comment]
If its possible, please upload your savegame to a filehoster (like wetransfer, dropbox, onedrive) and share the url. So we could try to replicate the issue and later tyron could use it for debugging. 
If you need help with uploading it, pm me.

**Comment by Aelin22** [comment]
https://www.dropbox.com/s/vq0wjkoh9wanyjk/valley%20of%20new%20beginnings.vcdbs?dl=0
I hope it works :-)

**Comment by Bloodsaw** [comment]
Same crashes happens for me if I try to load the provided savegame.

[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4270695/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4270696/client-main.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4270697/client-crash.txt)

**Comment by copygirl** [comment]
> Maybe the sqlitedb file is getting corrupt after client crashes.

Tyron has dealt with reports like this before. It's unfortunate that we don't have the log file from the original crash that occurred. I'll open up an issue for that!

**Comment by copygirl** [comment]
I'll close this in favor of #390, since it's likely the very same issue. Thank you for providing the world file!
