### ISSUE TITLE
Modded Mash and Modded rot not functioning as intended

### ISSUE THREAD

**Issue by Dekkan** [anegostudios/VintageStory-Issues#3892]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

So while working on building modded fruit mash for new berry bushes the new "mash" could be taken from the creative menu and put into the troughs but pressing the fruit in game produces mash that does not go into the troughs.  Similarly some modded food rot, instead of going into the "stackable" item slot in a barrel, it goes into the barrel as if it were a liquid.  I believe the issue is that some items (like the mash) are retaining some sort of information (like a liquid setting) and that is keeping the item from working correctly in the case of mash in the trough and rot in the barrel.  Both items appear fine based on testing from the creative menu but will not work when actually pressed in a survival world or from some rotted modded foods.

### How to reproduce

1. Insert berries from modded plants (wildcraft berries) into fruitpress.
2. Press the berries (collecting juice and mash)
3. Attempt to put mash into a trough (this is where the mash fails to work)

AND
1. allow some modded foods to rot.
2. put rot into barrel (does not go into the item stack slot and instead fills like a liquid)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
This issue is caused by mods
