### ISSUE TITLE
1.19.7 Pls Fix the Lore system 

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3897]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/601d1d48-1922-450b-9e0d-c03f93a3bc6e)

### How to reproduce

take or make a lore randomizer place it in a chest and insert it with worldedit so you get plenty books.
while reading them all you will encounter those weird things

### Logs

```None```

**Comment by AreYSerious** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/c8532634-e57a-44c2-879f-faa6453d4616)
also this

**Comment by AreYSerious** [comment]
Its also is it intended that if both of the windows are above each other and you want to move one you move both if the one behind would also be selected
![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/43156572-84bc-4ac4-b2fb-f76d0fde68aa)

**Comment by AreYSerious** [comment]
![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/4773af82-66dc-4c67-8333-54065ae57780)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/b84760f4-3fa3-4344-a358-610b2817a881)

pls also add better way to go from one page to another in books
not by strings but at least by words.

**Comment by tyronx** [comment]
Uh, this is not a vanilla asset though

**Comment by AreYSerious** [comment]
@tyronx @Craluminum2413 

https://www.youtube.com/watch?v=fwhAikCcGf8

**Comment by AreYSerious** [comment]
Here with vanilla assets

**Comment by AreYSerious** [comment]
Just spawn in a bunch of lore with
![image](https://github.com/user-attachments/assets/3a3345fb-2692-4ba7-8b64-d3d7283275ce)
and then look at the item descriptions it only is an issue for lore stuff with multiple entries

**Comment by tyronx** [comment]
oh yea, this is completely broken on vanilla. Thanks for the report, will fix

**Comment by tyronx** [comment]
fixed for 1.20

**Comment by AreYSerious** [comment]
@Craluminum2413 can you maybe reopen this
bcs this fix might have caused the issue https://github.com/anegostudios/VintageStory-Issues/issues/4484
@tyronx did you test this properly bcs I can only get the first piece of each lore category

**Comment by AreYSerious** [comment]
Ty that was fast

**Comment by AreYSerious** [comment]
That was fast ty Cral
