### ISSUE TITLE
Scythe misses some crops in 3x3 area

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#39]
1.5.2.2, official server.
When scything crops, often not the whole 3x3 area is cut, but a ctop in the corner is left untouched.
![2018-03-24_12-04-10](https://user-images.githubusercontent.com/25122345/37862336-47d782c0-2f5c-11e8-833a-ec393d2c6cc9.png)
![2018-03-24_12-04-14](https://user-images.githubusercontent.com/25122345/37862337-47f898fc-2f5c-11e8-9c32-904ae6622e56.png)

**Comment by tyronx** [comment]
This was kinda incorrectly communicated. Scythes do break crops within a 3x3 but were not supposed to break all 9 crops at once, but rather just 6 or so. It used to be the closest 6 to the player until 1.5.2.2, now it's just 6 by a fixed pattern (to fix server side ghost blocks)

**Comment by Heptagon-ru** [comment]
Ok, I tested in 1.5.2.6, works as explained. I updated Wiki page. Closing the ticket.
