### ISSUE TITLE
Changing dayspermonth leading to jumping from may to march

### ISSUE THREAD

**Issue by BOR15** [anegostudios/VintageStory-Issues#3904]
### Game Version

v1.19.8 (stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I was in my survival world that ive played in 6 in game days so far, but a lot of time with time frozen (not sure if thats relevant) and I wanted to try setting dayspermonth to 18 instead of 9 but upon reloading after changing it with ingame commands im suddenly in march and everything is freezing. Still day 6 and the same exact time as before or atleast it was really close. But instead of it being may it was march.

### How to reproduce

Change the dayspermonth from 9 to 18 in a world that has some amount of playtime after using time stop and reload. Im unsure if playtime and stopped time are actually necessary but it might be so im mentioning it. I didnt really test more after finding the bug because im scared of murdering my crops.

### Logs

```Log```
[client-main.txt](https://github.com/user-attachments/files/15526521/client-main.txt)

**Comment by Craluminum2413** [comment]
This is normal when you mess with time
