### ISSUE TITLE
Storagemaster's Blueprint calls for Aged wooden Planks that do not exist

### ISSUE THREAD

**Issue by TalShar783** [anegostudios/VintageStory-Issues#3907]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When attempting to use the Storagemaster's Blueprint to create Aged Wooden Crates or other things that call for Aged wooden Planks (the block), it would appear that the recipe calls for a different variant of Aged wooden Planks, one that is not obtainable according to the recipe book. If you click on those in the survival guide, it will not show a page showing how they can be obtained. It clicks, and nothing happens. It's worth noting that they are rendered differently, too; the planks appear to be vertical in the recipe book, whereas the ones you can obtain and craft appear vertical.

### How to reproduce

Attempt to craft Aged Wooden Crate with Storagemaster's Blueprint recipe in Survival mode.

### Screenshots

![Screenshot_3](https://github.com/anegostudios/VintageStory-Issues/assets/25249298/1f4b6248-44ff-4274-9a62-f5519fbffdaa)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Not vanilla issue
