### ISSUE TITLE
Store older log files in a compressed format

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#391]
It would really be helpful if all the log and crash files relevant to a single launch of Vintage Story could be kept around, stored in a compressed archive format of some sort. This would make it possible to investigate crashes that have occurred when a player already restarted their game to continue playing.

Perhaps we could grab all the relevant log files at startup and package them up in a single archive which contains them all. The archive would be named after the date and time the log files were created, which we either get from the file attributes or check from peeking in one of the logs.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
