### ISSUE TITLE
"wearableAttachment" and "wearableattachment" behave differently

### ISSUE THREAD

**Issue by SunnyOpossum** [anegostudios/VintageStory-Issues#3918]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I was told that capitalization didn't matter in .json files, and so far that has held true except in this one single case. Using "wearableAttachment" in a clothing item json will produce the expected result of a clothing item with 3D elements. Using "wearableattachment" will also produce the same result, except the item is invisible everywhere except when being worn in a clothing slot. Its invisible in the guis, in the player's hand, and dropped in the world.

### How to reproduce

Switch an item's json from "wearableAttachment" to "wearableattachment" and observe how the item remains functional but becomes completely invisible in the areas previously described.

### Logs

This issue was not reported in any of the logs.

**Comment by Craluminum2413** [comment]
What happens when there is no such attribute at all?
