### ISSUE TITLE
When I play Vintage Story I do not see items on the ground.

### ISSUE THREAD

**Issue by Fiero1Fan** [anegostudios/VintageStory-Issues#392]
**Game Version:** 1.12.5
**Platform:** Windows 
**Modded:** vshud disabled.. No help

### Description
When I play I do not see items on the ground. When I throw something into the water I can see it in the water but not on land.

### How to reproduce
Always happens.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Nothing to see.

### Logs
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4270895/client-main.txt)

**Comment by Bloodsaw** [comment]
I remember another person from discord with a similar issue.
What worked for him was deleting the `clientsettings.json` in `%appdata%\VintageStoryData`.
Can you please update to 1.12.6 and try it again?

**Comment by tyronx** [comment]
No new feedback in several months, closing issue.
