### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by DB-3670** [anegostudios/VintageStory-Issues#3924]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I'm currently having trouble starting Vintage Story. I'll click on the game and nothing happens. I've had VS for a while and have never encountered this issue before. I've lately been trying to reinstall VS both in 1.19 and 1.18 and I still run into the same problem of not getting the game to start. I've found someone on the issue tracker who's having the same problem as me. It seems that there might be an issue with the .net 7 Desktop Runtime with regards to running VS. I've tried reinstalling .net 7 as well with no success either. Also, every time I reinstall VS I don't see the "VintagestoryData" folder or the "main", "server", or the folder that had all of my installed mods.

### How to reproduce

I double-click on the game, the loading icon briefly appears, then nothing happens.

### Logs

```Log```

**Comment by DB-3670** [comment]
I was able to get the "VintagestoryData" folder back by clicking on the "VintagestoryServer" application. I'll now include the "server-debug.txt", "server-event.txt", and "server-main.txt" logs in case they may be helpful.
[server-main.txt](https://github.com/user-attachments/files/15792741/server-main.txt)
[server-event.txt](https://github.com/user-attachments/files/15792742/server-event.txt)
[server-debug.txt](https://github.com/user-attachments/files/15792743/server-debug.txt)

**Comment by DB-3670** [comment]
I've completely deleted all third party mods and have tried every suggestion (reinstalling VS, installing older versions, reinstalling dependencies, looking through the files, etc.) and the issue still persists. VS is the only application on my computer having this issue. Could something have happened to my game account?

Whenever I run the "VintagestoryServer" application, I see the message in yellow at the very bottom (pic). What does that mean?
<img width="959" alt="VS Server Problem" src="https://github.com/anegostudios/VintageStory-Issues/assets/172310325/c454920f-8618-49f8-8fa8-3eff78e1efb9">

**Comment by Craluminum2413** [comment]
What if you launch it normally through Vintagestory.exe

**Comment by DB-3670** [comment]
Nothing happens. The hourglass icon briefly appears next to my cursor, then disappears. It was the same result regardless of the version.

**Comment by DB-3670** [comment]
I just installed VS on another laptop of mine it it seems to run normally on that one. So it seems that the issue is related to something on my main computer, though I still haven't figured out what.

**Comment by DB-3670** [comment]
I've decided to start using my other laptop as my main one since it performs better anyways. It's likely that the other one was nearing the end of it's life. I've been able to play VS 1.19.8 and haven't run into any further issues.

**Comment by Craluminum2413** [comment]
If it happens again, I will reopen it
