### ISSUE TITLE
Request: Add outline to Chalk/Lime text on signs - Hard to read. 

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#393]
![2020-02-29_15-26-09](https://user-images.githubusercontent.com/10406037/75614572-23666300-5b08-11ea-87b2-f234f98cae33.png)
It's really hard for me to read those unless they're right in my face. Maybe add a solid outline to those or let the player change the background?

**Comment by tyronx** [comment]
oi, that used to be more readable. I guess I broke that in a recent update. Fixed in v1.12.6
