### ISSUE TITLE
Soybean missing models

### ISSUE THREAD

**Issue by Desoroxxx** [anegostudios/VintageStory-Issues#3932]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Soybeans have no models and a Soybean Stew with Turnip Garnish is not named correctly.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/82710983/cb3a1365-4f84-482c-bfae-8e92ad10f95a)

**Comment by staniboy** [comment]
Dublicate of #3699, still present in 1.20 rc5
