### ISSUE TITLE
Inconsistent JSON formatting with Variants - Purposeful or Style Issue?

### ISSUE THREAD

**Issue by AH1684** [anegostudios/VintageStory-Issues#3936]
### Game Version

1.19.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In some of the JSON files where certain blocks may have variants, when assigning things by type, sometimes the wildcard type is used, e.g.:
"*-raw"
other times the full name is used, e.g.:
"claypot-raw"

The example I've run into here is focused pot.json. attributesByType & combustiblesByType use the full names, but then some of the TexturesByType or others use the wildcard variant names.

Assuming this is unintentional, this inconsistency makes the otherwise easy-to-use variant & patching systems more painful.

- If I want to add a second set of variants to a block using full-names in fields where wildcard names suffice, I must move the entire object to a new wildcard name.
- However, doing so means that my mod has become horribly incompatible with any other mods that might add otherwise simple patches to this json.
- Furthermore, the ModMaker3000 automatic solution to object renames is a separate delete and add with the entire value within the patch. Requiring manual editing to keep the mod patches as unintrusive & flexible as possible.

Of course, if the wildcard names were used as often as possible in vanilla, then adding new variants becomes as simple as making minor changes to the fields I want to change. Keeping compatibility between mods also is magnitudes simpler.

I saw I could make a pull-request, going through jsons and editing them using my best judgement. I don't mind doing so, but I do want to verify whether this is intended design or not for reasons I'm unaware of! 

### How to reproduce

Open a json with variants and explicit ID usage where not necessary. E.g., pot.json.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
They still work though

**Comment by Craluminum2413** [comment]
I close it since it is not issue
