### ISSUE TITLE
coordinates bug

### ISSUE THREAD

**Issue by rian178** [anegostudios/VintageStory-Issues#3948]
### Game Version

v1.19.8(Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I want to use coordinates but it does not show up.
Also if I click in the settings. It does not show up. 

### Screenshots

![2024-06-29_17-22-59](https://github.com/anegostudios/VintageStory-Issues/assets/174198027/fcb33522-8fd2-464c-95f7-867217d78359)
![2024-06-29_17-23-24](https://github.com/anegostudios/VintageStory-Issues/assets/174198027/a366459c-a80d-474b-a107-18b2e252a5b0)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What happens when you type `/worldconfig allowCoordinateHud`?

**Comment by rian178** [comment]
I can try

**Comment by rian178** [comment]
It doesn't work.
![2024-06-29_19-08-28](https://github.com/anegostudios/VintageStory-Issues/assets/174198027/23d34feb-e73a-47f5-8600-240d2911e162)

**Comment by Craluminum2413** [comment]
Well that means that it is disabled. type `/worldconfig allowCoordinateHud true` to enable it

**Comment by rian178** [comment]
yes it works
thank you
