### ISSUE TITLE
Rounding error when using crucible

### ISSUE THREAD

**Issue by MyNameIsBee** [anegostudios/VintageStory-Issues#3958]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When trying to make tin bronze, when having 124 x 3 nuggets of copper in 3 slots and 40 nuggets of cassiterite the text displays:

> Will create 2059 units of Tin Bronze

despite a nugget of copper and a nugget of tin both having a value of 5 units.

### How to reproduce

1. Place Crucible on fire pit.
2. Insert 124 nuggets of Copper in slot 1, 2 and 3.
3. Insert 40 nuggets of Cassiterite in slot 4.
4. Text is displayed.

### Screenshots

![rounding bug](https://github.com/anegostudios/VintageStory-Issues/assets/63526679/fd0e24d1-6e39-4a17-a235-c6d6f13fa1c5)

### Logs

Gist Logs: https://gist.github.com/MyNameIsBee/c84e3b3f231163c629398d033bba4b8f

**Comment by pizza2004** [comment]
Should be fixed in the next version.
