### ISSUE TITLE
Sign posts disappearing if placed on slabs

### ISSUE THREAD

**Issue by Bloodsaw** [anegostudios/VintageStory-Issues#397]
**Game Version:** 1.12.5
**Platform:** Windows
**Modded:** No 

### Description
If you try to place a sign post onto a slab block it just disappears. 

### Expected behavior
I guess you just should get a message like with blocks "Cannot place this block here. Requires a solid ground" 

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![image](https://user-images.githubusercontent.com/61588797/75625222-4a7e6c80-5bbc-11ea-935b-dcbb7525550a.png)

![image](https://user-images.githubusercontent.com/61588797/75625225-52d6a780-5bbc-11ea-816c-ffbe0443a846.png)

**Comment by tyronx** [comment]
thanks, this should be fixed in v1.12.6
