### ISSUE TITLE
Can create water source on vanilla

### ISSUE THREAD

**Issue by YourMaido** [anegostudios/VintageStory-Issues#3981]
### Game Version

v.1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Wanted to try to cool down my ingots in molds but ended up creating watersource with wooden bucket.

### How to reproduce

1. Place ingot mold(probably other placebles work) on solid block (sand, soil, whatever)
2. Pour water from bucket on that block with ingot mold
3. Get new water source block

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Pick up mold and replace water source with solid block

**Comment by YourMaido** [comment]
> Pick up mold and replace water source with solid block

yeah sure, thought I can bug report here, didn't look or find better place
