### ISSUE TITLE
Inventory is empty if dying in lava

### ISSUE THREAD

**Issue by Bloodsaw** [anegostudios/VintageStory-Issues#399]
**Game Version:** 1.12.5
**Platform:** Windows 
**Modded:** No

### Description
If your deathPunishment is set to keep and you die because of falling into lava, the inventory on death screen and after respawn is blank. 
Workaround is save&exit and loading the world again. 

Issue was found by discord user @MiaMinadie

### How to reproduce
1. Create or load a world with deathPunishment = keep
2. Stay in lava until you die.
3. Respawn

### Logs
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4272001/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4272002/client-main.txt)

**Comment by Craluminum2413** [comment]
Reproduceable even in 1.15.0-pre. 2

**Comment by Craluminum2413** [comment]
Seems fixed. I tested on 1.15.0-pre.6

https://user-images.githubusercontent.com/69315569/122922396-3db2f880-d36c-11eb-8c02-3786e4bdaade.mp4
