### ISSUE TITLE
Stick bounce non stop

### ISSUE THREAD

**Issue by DanDinCri** [anegostudios/VintageStory-Issues#3990]
### Game Version

1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After cutting down a pine tree with a flint axe, there's a stick that started bouncing, and every time it touches the ground the bounce speed increases. The stick reached a point where it's not comming down, so I can't screenshot it.

### How to reproduce

1. Cut down a pine tree with a flint axe.

### Logs

```Log```

**Comment by pingouyn** [comment]
Starting playing in 1.18.x.  Has often happened to me with sticks on trees, and stones (the tiny stones) jumping up and down when breaking several rocks in caves...  Recurring issue

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/1844
