### ISSUE TITLE
Per-world mod selection

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#4]
It would be nice to have the ability to specify what mods are enabled on a per-world basis instead of globally, probably in existing world creation and edit screens.

Perhaps this could also be used when connecting to a server, where it only loads the mods it requests, erroring if any are missing. If it doesn't already work like that.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
