### ISSUE TITLE
Minor: Display of 0 Servings when bowl nearly empty

### ISSUE THREAD

**Issue by Angelnoir** [anegostudios/VintageStory-Issues#400]
**Game Version:** 1.12.5
**Platform:** Windows 10
**Modded:** No

### Description
A nearly empty bowl showed 0 servings remaining, but there was still food in the bowl. Probably something like 0.01 servings remaining.
![0serving](https://user-images.githubusercontent.com/7362698/75632352-8d136980-5bfb-11ea-84ac-66aec7a68c95.png)

### How to reproduce
Nearly impossible to reproduce, have to have just the right amount of hunger and dish.

### Expected behavior
Maybe never show less than 0.1

**Comment by Craluminum2413** [comment]
Was fixed in some version, now it displays percent
![image](https://user-images.githubusercontent.com/69315569/229118298-3caae21c-3256-4862-8001-087f1dd869c6.png)
