### ISSUE TITLE
Time is jumping forward in hours

### ISSUE THREAD

**Issue by ChrisW0604** [anegostudios/VintageStory-Issues#4004]
### Game Version

V1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Time is jumping in blocks of multiple hours at a time i.e. it will go from 15:00 to 17:00 in one jump or be normal for five minutes and jump again. It is completely unplayable at present.
This game is been going for 65 hours of game play before problem started no mods have been added or adjusted since start of game.

### How to reproduce

It is constantly happen since I logged in today.
I have logged out of the game and restarted the game and it still happens.

### Screenshots

N/A

### Logs

```Log```
[server-main.txt](https://github.com/user-attachments/files/16489300/server-main.txt)

**Comment by Craluminum2413** [comment]
What '/time speed' command shows?

**Comment by ChrisW0604** [comment]
Hi DanaYou can clear this I did a restart on my PC a few minutes after your email before running the command and problem seems to have cleared. Thanks and regards ChrisOn 5 Aug 2024, at 8:10 PM, Dana ***@***.***> wrote:﻿
What '/time speed' command shows?
