### ISSUE TITLE
Does it happen without any mods?

### ISSUE THREAD

**Issue by GodOfDucks1337** [anegostudios/VintageStory-Issues#4014]
Does it happen without any mods?

_Originally posted by @Craluminum2413 in https://github.com/anegostudios/VintageStory-Issues/issues/4010#issuecomment-2272932523_
            
no it does not, I think ive found what is causing the crash, there is a mod called "extra chests"
I removed it and I can open the chest with the dough pie in it without any issues

**Comment by Craluminum2413** [comment]
Why you created issue for this reply?

**Comment by GodOfDucks1337** [comment]
It was on accident, tried to reply in the same issue we talked in, im sorry.
