### ISSUE TITLE
Clutter Hitboxes incorrect

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#4020]
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

![2024-08-12_15-59-18](https://github.com/user-attachments/assets/84942405-2958-4c14-a96b-f2609f8fbcfb)
Image should explain itself

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.20, I assume it is fixed
