### ISSUE TITLE
Clipping through roof when jumping

### ISSUE THREAD

**Issue by Archionxd** [anegostudios/VintageStory-Issues#4027]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Whenever I jump while underneath a block that is right above or one block above my head it either pushes me into the floor or launches me into the sky, causing me to die from fall damage.

### How to reproduce

1. put a block above your head 2. jump

### Screenshots

https://github.com/user-attachments/assets/4a02bde9-7b5b-4dc8-bb50-fab73309b5a4

**Comment by Craluminum2413** [comment]
Most likely fixed in 1.20
