### ISSUE TITLE
Berry bush growth timer not reset when raccoons steal berries

### ISSUE THREAD

**Issue by pizza2004** [anegostudios/VintageStory-Issues#4034]
### Game Version

v1.19.8

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Raccoons will harvest berries from berry bushes but the game will not reset the timer like it does any other time the bush is changes its state, meaning that it can sometimes be left with more than 30 days until it flowers again.

### How to reproduce

Place down ripe berry bushes and spawn raccoons nearby to steal the berries

**Comment by tyronx** [comment]
PR 60 merged 👍
