### ISSUE TITLE
Problem during generation of world in single player

### ISSUE THREAD

**Issue by belywin** [anegostudios/VintageStory-Issues#4048]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Hello, when i launch the game with mod i have a problem to generate the world

### How to reproduce

When i launch the word, i wait for the loading and at the end of loading a crash occured 

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32677 MB RAM
Game Version: v1.19.8 (Stable)
27/08/2024 22:29:07: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.5, backpackpackplus@1.0.3, bettercrates@1.7.1, bettershears@1.0.0, bloomeryfulldrops@1.0.0, chiseltools@1.12.3, craftablejparts@1.0.0, decor@1.1.4, EasyFruitTrees@1.0.1, extrachests@1.8.0, fantasycreatures@0.7.1, fastermetal@1.0.0, HangingOilLamps@1.0.1, HumanSkinTones@0.0.3, juicyores@1.0.0, lanternpost@1.0.8, mannequinstand@1.0.3, millwright@1.1.6, moremetals@1.0.9, nocharcoallost@1.0.0, OresAPlenty@3.2.0, primitivesurvival@3.6.4, qptech@1.15.2, sortablestorage@2.2.6, swordz@1.1.8, temporal_gears_stack@1.0.0, game@1.19.8, alloycalculator@1.0.0, ancienttools@1.5.18, animalcages@3.0.2, animationmanagerlib@0.8.8, egocaribautomapmarkers@3.1.0, autoloot@1.0.1, betterfirepit@1.1.4, betterruins@0.3.7, biggercellars@1.0.0, blocksoverlay@3.2.4, branchcutter@1.0.1, butchering@1.6.7, carryon@1.7.4, clipfix@2.0.2, commonlib@2.5.0-rc.2, expandedfoods@1.7.0, extrainfo@1.8.1, foodshelves@1.1.5, fromgoldencombs@1.6.2, hudclock@3.4.0, knapster@2.11.1, labeledtrunk@1.0.4, maltiezbows@1.0.4, medievalexpansion@3.13.1, mobsradar@2.1.1, norottinghides@1.0.0, petai@2.2.6, rhadditions@4.0.6, sailboat@1.3.1, simpleemotemenu@1.1.0, creative@1.19.8, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.6, woodenfortifications@0.0.4, workbenchexpansion@1.8.0, awearablelight@1.1.1, bullseye-continued@2.5.8, captureanimals@2.7.0, em@2.7.0, extraoverlays@1.4.0, helvehammerext@1.6.0, lohnscroptempsplus@2.0.0, stonequarry@3.3.1, vanity@2.2.0, vsvillageaged@0.0.4, vsvillageindustrial@0.0.4, vsvillagetowers@0.0.4, wolftaming@2.1.3, bricklayers@2.5.6, moreroads@1.5.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemNugget.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Item\ItemNugget.cs:line 45
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world) in VintagestoryLib\Common\GameContent\Inventory\CreativeTab.cs:line 43
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world) in VintagestoryLib\Common\GameContent\Inventory\CreativeTabs.cs:line 48
   at Vintagestory.Client.NoObf.GuiDialogInventory.<OnOwnPlayerDataReceived>b__6_0() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 58
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/08/2024 22:21:46, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.8.0, horodatage : 0x661e0000
Nom du module défaillant : unknown, version : 0.0.0.0, horodatage : 0x00000000
Code d’exception : 0xc0000005
Décalage d’erreur : 0x00007ffd505bb210
ID du processus défaillant : 0x97f4
Heure de début de l’application défaillante : 0x01daf8bdb16ca2c1
Chemin d’accès de l’application défaillante : C:\Users\Thibault\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: unknown
ID de rapport : 4fb7035d-753c-4272-817a-d7db19d7ed45
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 27/08/2024 22:02:52, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.8.0, horodatage : 0x661e0000
Nom du module défaillant : unknown, version : 0.0.0.0, horodatage : 0x00000000
Code d’exception : 0xc0000005
Décalage d’erreur : 0x00007ff884e0c410
ID du processus défaillant : 0x8dd4
Heure de début de l’application défaillante : 0x01daf8bbdcca563c
Chemin d’accès de l’application défaillante : C:\Users\Thibault\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: unknown
ID de rapport : 8465dd59-3bd1-4bbc-a004-3c85989059be
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 27/08/2024 21:59:09, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.8.0, horodatage : 0x661e0000
Nom du module défaillant : unknown, version : 0.0.0.0, horodatage : 0x00000000
Code d’exception : 0xc0000005
Décalage d’erreur : 0x00007ff884e0fdb0
ID du processus défaillant : 0x8c9c
Heure de début de l’application défaillante : 0x01daf8bb5835632b
Chemin d’accès de l’application défaillante : C:\Users\Thibault\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: unknown
ID de rapport : 12312d43-a1e7-449f-ace6-77dc3cc0d5c8
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

**Comment by Craluminum2413** [comment]
Maybe some mods are conflicting and causing this bug

**Comment by belywin** [comment]
Do you know what mod can cause this problem or how can I detect it?

**Comment by Craluminum2413** [comment]
No idea

**Comment by belywin** [comment]
It was the mod More Metal who have a problem
