### ISSUE TITLE
"Something went awry...please check the program logs... (Exception thrown by server during startup or process)"

### ISSUE THREAD

**Issue by CircusSeal** [anegostudios/VintageStory-Issues#4052]
### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

I installed some new mods, including Lichen and Farm Life. I didn't realize at first that Lichen was outdated, and my save file got corrupted. I tried to fix it by turning off Lichen in the mod manager and deleting the folder /home/******/.config/VintagestoryData/Cache/unpack/, and I thought it would be enough. However, it just got corrupted again, so I did the same thing with Farm Life. That wasn't enough, either.

Right now, I'm trying to figure out SQLite, but I'm basically completely incapable of doing anything on computers beyond just clicking on a file or two, so my hopes aren't too high that I'll be able to do it.

In the meantime, here are my server logs:

server-debug: https://pastebin.com/uChwxek4

server-event: https://pastebin.com/9qcSrZDE

server-main: https://pastebin.com/frfRyDXJ

### Logs

```Log```

server-debug: https://pastebin.com/uChwxek4

server-event: https://pastebin.com/9qcSrZDE

server-main: https://pastebin.com/frfRyDXJ

**Comment by Craluminum2413** [comment]
Does it work when you load creative flat world with and without mods?

**Comment by CircusSeal** [comment]
> Does it work when you load creative flat world with and without mods?

The same thing happened when I tried to do it with mods, but when I disabled all my mods and created a creative world, it worked fine.

**Comment by Craluminum2413** [comment]
Ok then it is caused by some mods
