### ISSUE TITLE
Jonas Parts&Frame Stack Randomizer

### ISSUE THREAD

**Issue by MusicMakerOwO** [anegostudios/VintageStory-Issues#4056]
### Game Version

1.19.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I'm not sure it is a bug but it looks like one, instead of just listing out the parts they are all grouped together. However that also means you can't click on said items to see their recipes and uses, not to mention how hard the formatting is to read. I would imagine each item should be listed separately and then add a note below of their chances?

### How to reproduce

1. Press 'H' to open the guide
2. Search 'locust', select 'Locust Nest' (cloth variant)
3. See the 'Jonas Parts&Frame Stack Randomizer' as the 5th listed item

### Screenshots

![image](https://github.com/user-attachments/assets/68d0105d-4a12-4c45-88d2-491493282b18)

### Logs

N/A

**Comment by maltiez2** [comment]
Will be fixed in next update
