### ISSUE TITLE
Copper casting not working

### ISSUE THREAD

**Issue by flusenfrei** [anegostudios/VintageStory-Issues#4062]
### Game Version

v.1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I am trying to cast copper, but I am having a hard time getting it to melt. It uses so much coal and the temperature has rises over the melting point and the nuggets are still solid. Sometimes it helps to take half of the pieces out and the yellow or even white-hot crucible pops in the right output to be taken out, but that is no workaround. I am just playing around in an easy setting with the game, so I do not know if the problem can occur in an unmodded game.

Casting seems to work sometimes, when I use lots and lots of charcoal, and the crucible gets to white-hot for a long time, but that needs so many resources. The issue shows in the progress bar. It goes up, but very slowly, and rises over the point of melting and is just halfway there.

Since I do use some mods, this bug report might NOT be useful, but I send it anyway.

Mods:
Auto Map Markers (Code)
Better Ruins
Better Traders (Content)
HUD Clock (Code)
Knapster (Code)
Rivers (Code)
Th3Dungeon (Code)
Th3DungeonTopEntrance (Code)

I didn't think the mods really do something like that, but I've sent two log data pieces that shows that mods are loaded and some typical stuff or warnings in a log when mods are added.

### How to reproduce

1. Make a 'Crucible'	
2. Throw in copper 'nuggets'
3. Heat up with 'Firewood'
4. Change to Charcoal and wait what happens.	

### Screenshots

![2024-09-02_20-15-29](https://github.com/user-attachments/assets/ead39db2-e7ee-4413-94c2-b29a3f77ac6f)
![2024-09-02_20-17-10](https://github.com/user-attachments/assets/06612338-c542-48bc-bf46-e992aea72afc)
![2024-09-02_22-08-00](https://github.com/user-attachments/assets/950fc4fd-3c01-4a73-bf3b-b51f307bf979)

### Logs

```Log``` Game Version: v1.19.8 (Stable)
28.08.2024 23:59:41: Critical error occurred
Loaded Mods: bettertraders@0.0.7, game@1.19.8, egocaribautomapmarkers@3.1.0, betterruins@0.3.7, commonlib@2.4.0, hudclock@3.4.0, knapster@2.11.1, prospecttogether@1.3.0, rivers@3.1.0, scarecrow@1.5.1, th3dungeon@0.2.1, creative@1.19.8, survival@1.19.8, em@1.0.1, stonequarry@3.3.1, th3dungeontopentrance@0.1.1, moreroads@1.5.7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Server.ServerMain.Stop(String reason) in VintagestoryLib\Server\ServerMain.cs:line 1053
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in VintagestoryLib\Client\ClientProgram.cs:line 435

---------------------------------------------------------------------------

4.9.2024 14:22:41 [Notification] Client logger started.
4.9.2024 14:22:41 [Notification] Game Version: v1.19.8 (Stable)
4.9.2024 14:22:41 [Notification] Process path: G:\Vintagestory\Vintagestory.exe
4.9.2024 14:22:41 [Notification] Operating System: Windows 10.0.19045.0
4.9.2024 14:22:41 [Notification] CPU Cores: 16
4.9.2024 14:22:41 [Notification] Available RAM: 32688 MB
4.9.2024 14:22:42 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
4.9.2024 14:22:42 [Notification] Graphics Card Vendor: NVIDIA Corporation
4.9.2024 14:22:42 [Notification] Graphics Card Version: 3.3.0 NVIDIA 555.85
4.9.2024 14:22:42 [Notification] Graphics Card Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
4.9.2024 14:22:42 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
4.9.2024 14:22:42 [Notification] GL.MaxVertexUniformComponents: 4096
4.9.2024 14:22:42 [Notification] GL.MaxUniformBlockSize: 65536
4.9.2024 14:22:42 [Notification] C# Framework: .net 7.0.13
4.9.2024 14:22:42 [Notification] Cairo Graphics Version: 1.17.3
4.9.2024 14:22:42 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
4.9.2024 14:22:42 [Notification] Zstd Version: 1.5.5
4.9.2024 14:22:42 [Notification] Start discovering assets
4.9.2024 14:22:42 [Notification] Found 25 base assets in category lang
4.9.2024 14:22:42 [Notification] Found 0 base assets in category patches
4.9.2024 14:22:42 [Notification] Found 24 base assets in category config
4.9.2024 14:22:42 [Notification] Found 0 base assets in category worldproperties
4.9.2024 14:22:42 [Notification] Found 48 base assets in category sounds
4.9.2024 14:22:42 [Notification] Found 95 base assets in category shapes
4.9.2024 14:22:42 [Notification] Found 72 base assets in category shaders
4.9.2024 14:22:42 [Notification] Found 16 base assets in category shaderincludes
4.9.2024 14:22:42 [Notification] Found 133 base assets in category textures
4.9.2024 14:22:42 [Notification] Found 4 base assets in category music
4.9.2024 14:22:42 [Notification] Found 0 base assets in category dialog
4.9.2024 14:22:42 [Notification] Found 417 base assets in total
4.9.2024 14:22:42 [Notification] Loading sounds
4.9.2024 14:22:42 [Notification] (Re-)loaded frame buffers
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass .
4.9.2024 14:22:42 [Notification] Sounds loaded
4.9.2024 14:22:42 [Notification] Begin loading shaders
4.9.2024 14:22:42 [Notification] Load shaders now
4.9.2024 14:22:42 [Notification] Loading shaders...
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass standard.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass particlescube.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass particlesquad.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass sky.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass nightsky.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass woittest.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass helditem.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass decals.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass final.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass gui.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass blur.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass findbright.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass godrays.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass autocamera.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass wireframe.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass entityanimated.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass luma.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass blit.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass texture2texture.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass celestialobject.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass colorgrade.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass guigear.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass ssao.
4.9.2024 14:22:42 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
4.9.2024 14:22:42 [Notification] Cached session key is valid, validating with server
4.9.2024 14:22:44 [Notification] Server validation response: Good
4.9.2024 14:22:44 [Notification] Will search the following paths for mods:
4.9.2024 14:22:44 [Notification]     G:\Vintagestory\Mods
4.9.2024 14:22:44 [Notification]     C:\Users\dropdead\AppData\Roaming\VintagestoryData\Mods
4.9.2024 14:22:50 [Notification] Initialized GUI Manager
4.9.2024 14:22:50 [Notification] Initialized Server Connection
4.9.2024 14:22:50 [Notification] Server args parsed
4.9.2024 14:22:50 [Notification] Server main instantiated
4.9.2024 14:22:55 [Notification] Processed server identification
4.9.2024 14:22:55 [Notification] Map initialized
4.9.2024 14:22:55 [Notification] Received server assets
4.9.2024 14:22:55 [Notification] Loading and pre-starting client side mods...
4.9.2024 14:22:55 [Notification] Will search the following paths for mods:
4.9.2024 14:22:55 [Notification]     G:\Vintagestory\Mods
4.9.2024 14:22:55 [Notification]     C:\Users\dropdead\AppData\Roaming\VintagestoryData\Mods
4.9.2024 14:22:55 [Notification] Found 13 mods (0 disabled)
4.9.2024 14:22:55 [Notification] Mods, sorted by dependency: bettertraders, game, wlts, egocaribautomapmarkers, betterruins, hudclock, knapster, rivers, th3dungeon, creative, survival, vsvillage, th3dungeontopentrance
4.9.2024 14:22:55 [Notification] Instantiated 143 mod systems from 13 enabled mods
4.9.2024 14:22:55 [Notification] Done loading and pre-starting client side mods.
4.9.2024 14:22:55 [Notification] External Origins in load order: modorigin@G:\Vintagestory\assets\creative\, modorigin@G:\Vintagestory\assets\survival\, mod@BetterTradersv0.0.7.zip, mod@WholeLottaTreeSeeds-1.0.0.zip, mod@Auto Map Markers (1.19).zip, mod@BetterRuinsv0.3.7.zip, mod@hudclock-3.4.0.zip, mod@Knapster_v2.11.1.zip, mod@rivers_3.1.0.zip, mod@th3dungeon_0.2.1.zip, mod@vsvillage_v1.0.6.zip, mod@Th3DungonTopEntrance_0.1.1.zip
4.9.2024 14:22:55 [Notification] Found 254 external assets in category lang
4.9.2024 14:22:55 [Notification] Found 48 external assets in category patches
4.9.2024 14:22:55 [Notification] Found 89 external assets in category config
4.9.2024 14:22:55 [Notification] Found 25 external assets in category worldproperties
4.9.2024 14:22:55 [Notification] Found 419 external assets in category sounds
4.9.2024 14:22:55 [Notification] Found 3667 external assets in category shapes
4.9.2024 14:22:55 [Notification] Found 13 external assets in category shaders
4.9.2024 14:22:55 [Notification] Found 0 external assets in category shaderincludes
4.9.2024 14:22:55 [Notification] Found 5673 external assets in category textures
4.9.2024 14:22:55 [Notification] Found 68 external assets in category music
4.9.2024 14:22:55 [Notification] Found 18 external assets in category dialog
4.9.2024 14:22:55 [Notification] Found 11 external assets in category compatibility
4.9.2024 14:22:55 [Notification] Reloaded lang file now with mod assets
4.9.2024 14:22:55 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
4.9.2024 14:22:55 [Notification] JsonPatch Loader: 320 patches total, successfully applied 7 patches, missing files on 55 patches, unmet conditions on 20 patches, no errors
4.9.2024 14:22:56 [Notification] Received 3589 item types from server
4.9.2024 14:22:56 [Notification] Loaded 9500 block types from server
4.9.2024 14:22:56 [Notification] Reloaded sounds, now with mod assets
4.9.2024 14:22:56 [Notification] Composed 1 4096x4096 entities texture atlases from 489 textures
4.9.2024 14:22:57 [Notification] Collected 2172 shapes to tesselate.
4.9.2024 14:22:57 [Warning] Texture asset 'game:textures/block/bone.png' not found (defined in Item vsvillage:villagergear-weapon-bow-recurve).
4.9.2024 14:22:57 [Notification] Composed 1 4096x4096 items texture atlases from 1744 textures
4.9.2024 14:22:58 [Notification] Composed 1 4096x4096 blocks texture atlases from 4490 textures
4.9.2024 14:22:58 [Notification] Server assets loaded
4.9.2024 14:23:00 [Notification] Blocks tesselated
4.9.2024 14:23:01 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
4.9.2024 14:23:06 [Notification] Server launched
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass standard.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass entityanimated.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass lines.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass aurora.
4.9.2024 14:23:07 [Notification] Initialised WeatherSystemClient.  simLightning is good.
4.9.2024 14:23:07 [Notification] HUD Clock Mod v3.4.0 loading
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass rift.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass machinegear.
4.9.2024 14:23:07 [Notification] Started 86 systems on Client:
4.9.2024 14:23:07 [Notification]     Mod 'Knapster_v2.11.1.zip' (knapster):
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Program
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyTilling.Systems.EasyTillingClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasySmithing.Systems.EasySmithingClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyQuern.Systems.EasyQuernClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyPressing.Systems.EasyPressingClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyPanning.Systems.EasyPanningClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyKnapping.Systems.EasyKnappingClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyHarvesting.Systems.EasyHarvestingClient
4.9.2024 14:23:07 [Notification]         ApacheTech.VintageMods.Knapster.Features.EasyClayForming.Systems.EasyClayFormingClient
4.9.2024 14:23:07 [Notification]     Mod 'VSEssentials.dll' (game):
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.Core
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.EntityPartitioning
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ErrorReporter
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemItemRendererOptimizer
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemFpHands
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.POIRegistry
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.RoomRegistry
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.WeatherSystemClient
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.WorldMapManager
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.LoadColorMaps
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ClothManager
4.9.2024 14:23:07 [Notification]     Mod 'rivers_3.1.0.zip' (rivers):
4.9.2024 14:23:07 [Notification]         Rivers.RiversMod
4.9.2024 14:23:07 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.Client.NoObf.ModSystemBossHealthBars
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.DebugSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.UpgradeTasks
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.GenMaps
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.MyceliumSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemLabelMeshCache
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemGliding
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemMeasuringRope
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemStopRaiseShieldAnim
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemAuction
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.Core
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemBoatingSound
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.CharacterSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.MealMeshCache
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.DialogueSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.FruitingSystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemCommandHandbook
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemSurvivalHandbook
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemTutorial
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemNightVision
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModJournal
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModLootRandomizer
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.MicroBlockModelCache
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemRifts
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSleeping
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.TeleporterManager
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModTemperature
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.SystemTemporalStability
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemOreMap
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.ModSystemSnowballs
4.9.2024 14:23:07 [Notification]         Vintagestory.GameContent.TraderOutfits
4.9.2024 14:23:07 [Notification]     Mod 'VSCreativeMod.dll' (creative):
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.Core
4.9.2024 14:23:07 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
4.9.2024 14:23:07 [Notification]     Mod 'Auto Map Markers (1.19).zip' (egocaribautomapmarkers):
4.9.2024 14:23:07 [Notification]         Egocarib.AutoMapMarkers.MapMarkerMod
4.9.2024 14:23:07 [Notification]         Egocarib.AutoMapMarkers.GUI.MapMarkerGUISystem
4.9.2024 14:23:07 [Notification]     Mod 'hudclock-3.4.0.zip' (hudclock):
4.9.2024 14:23:07 [Notification]         hudlock.src.HUDClockMod
4.9.2024 14:23:07 [Notification]     Mod 'vsvillage_v1.0.6.zip' (vsvillage):
4.9.2024 14:23:07 [Notification]         VsVillage.VillageManager
4.9.2024 14:23:07 [Notification]         VsVillage.VsVillage
4.9.2024 14:23:07 [Notification]     Mod 'th3dungeon_0.2.1.zip' (th3dungeon):
4.9.2024 14:23:07 [Notification]         th3dungeon.Th3Dungeon
4.9.2024 14:23:07 [Notification] Loading shaders...
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass standard.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass particlescube.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass particlesquad.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass sky.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass nightsky.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass woittest.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass helditem.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass decals.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass final.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass gui.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass blur.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass findbright.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass godrays.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass autocamera.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass wireframe.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass entityanimated.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass luma.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass blit.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass texture2texture.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass celestialobject.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass colorgrade.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass guigear.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass ssao.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass standard.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass entityanimated.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass lines.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass aurora.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass rift.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass machinegear.
4.9.2024 14:23:07 [Notification] Reloaded shaders now with mod assets
4.9.2024 14:23:07 [Notification] Received level init
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass instanced.
4.9.2024 14:23:07 [Notification] Initialized Music Engine
4.9.2024 14:23:07 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
4.9.2024 14:23:07 [Notification] Rift weather not available
4.9.2024 14:23:07 [Notification] Received level finalize
4.9.2024 14:23:07 [Notification] Loaded Shaderprogramm for render pass clouds.
4.9.2024 14:23:07 [Notification] Loading world map cache db...
4.9.2024 14:23:08 [Notification] [Auto Map Markers] Successfully established connection with the server.
4.9.2024 14:23:08 [Warning] ===============================================================
4.9.2024 14:23:08 [Warning] (x_x) Captured 1 issues during startup:
4.9.2024 14:23:08 [Warning] Texture asset 'game:textures/block/bone.png' not found (defined in Item vsvillage:villagergear-weapon-bow-recurve).
4.9.2024 14:23:08 [Warning] ===============================================================
4.9.2024 14:23:12 [Notification] Finished fully loading sounds (async)
4.9.2024 14:23:15 [Notification] Client pause state is now on
4.9.2024 14:23:18 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
4.9.2024 14:23:21 [Notification] Client pause state is now off
4.9.2024 14:23:25 [Notification] Client pause state is now on
4.9.2024 14:23:28 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
4.9.2024 14:24:07 [Notification] Client pause state is now off
4.9.2024 14:24:09 [Notification] Client pause state is now on
4.9.2024 14:24:11 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
4.9.2024 14:24:30 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
4.9.2024 14:35:14 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers

**Comment by Craluminum2413** [comment]
Try without mods

**Comment by Craluminum2413** [comment]
Closed due to inactivity
