### ISSUE TITLE
Transparent Pixels in Clothing Make Character See-Through

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#4066]
### Game Version

1.19.8(Stable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Several clothing items seem to produce transparent pixels on the character body when they overlap with others, creating errors where you can see through the Seraph. 

### How to reproduce

The above outfit uses: Wear them. 
- Squire Tunic
- Alchemist Shirt
- Chateau Pants
- Forlorn Hope Bracer

### Screenshots

![image](https://github.com/user-attachments/assets/76c9455f-fa5e-4d4f-bb74-3b3ff0c94765)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It is most likely will be fixed in 1.20

**Comment by ifozz** [comment]
Brought this up with Saraty a while back, transparent pixels are being removed when clothing switched to 3D in 1.20.
