### ISSUE TITLE
Missing mainmenu textures causes LoadTexture crash at startup

### ISSUE THREAD

**Issue by Auzze** [anegostudios/VintageStory-Issues#407]
**Game Version:** 1.12.5
**Platform:** Windows 10
**Modded:** No

### Description
it just crashed, I just brought the game, installed and imputed my info, hit the start and it crashed

### Expected behavior
the game to start

### Screenshots
https://www.dropbox.com/s/8roa1nzj9vc9b8c/Screenshot_98.png?dl=1

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.5 (Stable)5/03/2020 12:17:37 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   at _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------
```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4287475/client-main.txt)

**Comment by Tansu-Tansu** [comment]
### crash on startup. me too.

Game Version: 1.12.5
Platform: Windows 10
Modded: No

Description
it just crashed, I just brought the game, installed and imputed my info, hit the start and it crashed.

How to reproduce
game install→start[Vintagestory.exe]→crashed.(Immediately after)
It crashes / doesn't do the thing.
Expected behavior
the game to start

Screenshots
![q1](https://user-images.githubusercontent.com/61794921/75897049-4df34b80-5e7b-11ea-884f-a68f6aaa5ea0.jpg)

Log
Running on 64 bit Windows with 64 GB RAM 
Version: v1.12.5 (Stable)2020/03/05 0:50:51: Critical error occurred
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   場所 _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   場所 _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   場所 _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   場所 _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   場所 Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   場所 System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   場所 OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   場所 OpenTK.GameWindow.DispatchRenderFrame()
   場所 OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   場所 _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   場所 _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by takevox** [comment]
me too.

Game Version: 1.12.5
Platform: Windows 10
Modded: No

### Logs

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.5 (Stable)2020/03/05 2:36:56: Critical error occurred
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   場所 _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   場所 _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   場所 _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   場所 _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   場所 Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   場所 System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   場所 OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   場所 OpenTK.GameWindow.DispatchRenderFrame()
   場所 OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   場所 _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   場所 _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
Also reported on Discord, @tyronx responded:

> **Tyron:** that crash would happen if a file is missing **@Auzze**, particularly `assets/textures/gui/backgrounds/mainmenu*.png`
> **Tyron:** sounds like something went wrong during installation

He's looking into it!

**Comment by Auzze** [comment]
sry, I was looking in the wrong place, I do have them installed
![Screenshot_100](https://user-images.githubusercontent.com/478323/75932112-bcabc580-5eca-11ea-9a06-71eaefac4fa4.png)

**Comment by Loapu** [comment]
This problem seems to happen all around the globe. Maybe the login-services are unavailable or something?

**Comment by Elladon** [comment]
same here : 
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.5 (Stable)05.03.2020 00:40:16: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by Elladon** [comment]
same : 
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.5 (Stable)05.03.2020 00:45:43: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by PrinceOfStrings** [comment]
> 
> 
> Some packages are missing `mainmenu9.png` to `mainmenu11.png`, causing this problem.

Hey, i had the same problem. When i saw your post a quick fix came in mind and the game started again!!

I just copied one of the mainmenu*.pngs and renamed them mainmenu9 to 10. Started VS and is running just fine!
Peace

**Comment by Bloodsaw** [comment]
Every installer and tar.gz packages in the 1.12.x tree is only shipped with mainmenu1-8.
The packages for <= 1.11.11 were shipped with mainmenu1-11.

@PrinceOfStrings workaround is functional 

> > Some packages are missing `mainmenu9.png` to `mainmenu11.png`, causing this problem.
> 
> Hey, i had the same problem. When i saw your post a quick fix came in mind and the game started again!!
> 
> I just copied one of the mainmenu*.pngs and renamed the copies mainmenu9, mainmenu10 and mainmenu11 since the original ones were in fact missing. Started VS and is running just fine!
> Peace

**Comment by AssassinStella** [comment]
Yes it works @PrinceOfStrings thank you ^-^

**Comment by AkayathePanda** [comment]
hey hey 
i had this problem when i start the game :)


[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4290445/client-crash.txt)

**Comment by Tansu-Tansu** [comment]
crash on startup.
### ※problem solving
Game Version: 1.12.5
Platform: Windows 10
Modded: No
How to reproduce
game install→start[Vintagestory.exe]→crashed.(Immediately after)

### ※問題解決しました。
●原因は\Vintagestory\assets\game\textures\gui\backgrounds内のPNGファイルmainmenu.pngファイル（mainmenu9~11.png）が欠落しているためでした。
●対策方法は\Vintagestory\assets\game\textures\gui\backgroundsフォルダ内のmainmenu.pngファイル(mainmenu.pngならどれでもOK)をコピーしてmainmenu9、mainmenu10、mainmenu11を新たに作るだけで解決します。
●Yes it works @PrinceOfStrings thank you！ ^o^

**Comment by toffi112** [comment]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.5 (Stable)05.03.2020 02:38:14: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 04.03.2020 23:07:09, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFF96C9A839
Stapel:
   bei System.Environment._Exit(Int32)
   bei System.Environment._Exit(Int32)
   bei System.Environment.Exit(Int32)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   bei OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe, System.String[])
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(System.Threading.ThreadStart)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._HDnbZ9U7ok6mEhsXb9UbGfTHtaF(System.String[])

**Comment by copygirl** [comment]
Here's the announcement from Discord.
> **Balduranne - Art Contributor:** PSA:
> The game is currently crashing due to missing main menu backgrounds. As a workaround, create `assets\game\textures\gui\backgrounds\mainmenu9.png` and `assets\game\textures\gui\backgrounds\mainmenu10.png`, for example by duplicating `mainmenu8.png`. The path can be found in your Vintage Story game installation directory.
>
> We apologize for the inconvenience.

So, you can try to apply the workaround temporarily, or just wait for the next release, which should hopefully come out within the next 12 hours.

**Comment by copygirl** [comment]
Version `1.12.6` has just been released which should address this issue.

**Comment by copygirl** [comment]
Fun fact: The game crashes all of a sudden without an update, because the main menu background image changes every few days. Unfortunately, Tyron forgot to change the number of backgrounds from 10 to 8 when, presumably, he removed some of them. Now, recently, the background switched to `mainmenu9.png`, which doesn't exist, causing the crash.
