### ISSUE TITLE
Impossible to put grass in a pit kiln

### ISSUE THREAD

**Issue by geek4life04** [anegostudios/VintageStory-Issues#4070]
### Game Version

1.19.8

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

When I try to do a pit kiln, it’s impossible to add the grass. I’m stuck with only the option to pick up the item. I notice that when I put only three items, like when I want to fire 3 bowls pr 3 crucible for exemple, I’m able to put the grass and build the pit kiln. But when I put 4 items, or a mold or two ingots mold, I’m not able to put grass to build my put kiln. 

I had mods on so I disable all my mods. I try to start a new world but it doesn’t go,  and I try to uninstall my game and reinstall it. The problem seems to persist. Now I’m stuck because I cannot have any mold to make pickaxe or hammer to upgrade to the copper age. 

### Screenshots

https://github.com/user-attachments/assets/45eea393-057f-484e-83a8-1ad0c910e6de

![IMG_1055](https://github.com/user-attachments/assets/b69bc3b8-1029-4f06-8bf2-8cd4c314b388)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
You still have mods enabled, I assume it is mod issue
