### ISSUE TITLE
The crocks sometimes wont show message for how many days the food would be fresh

### ISSUE THREAD

**Issue by StressedFairy** [anegostudios/VintageStory-Issues#4071]
### Game Version

1.19

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Just what i said is nothing to bad just wanted to help improve the game

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Do they have hot food inside?

**Comment by MyraMidnight** [comment]
I guess the crock was still too hot, but perhaps if there was a comment/indicator that expire date will appear once it cools down then it wouldn't feel as much like a bug.
