### ISSUE TITLE
Game crashing when putting Copper ingot on Copper anvil

### ISSUE THREAD

**Issue by DukkSauze** [anegostudios/VintageStory-Issues#4074]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When putting heated copper ingot on copper anvil to smith it, as soon as I shift + right click to put the bar down, game crashes out.

### Logs

```Log```
[client-chat.txt](https://github.com/user-attachments/files/16920141/client-chat.txt)
[client-crash.txt](https://github.com/user-attachments/files/16920142/client-crash.txt)
[client-debug.txt](https://github.com/user-attachments/files/16920143/client-debug.txt)
[client-main.txt](https://github.com/user-attachments/files/16920144/client-main.txt)
[client-audit.txt](https://github.com/user-attachments/files/16920145/client-audit.txt)

**Comment by Craluminum2413** [comment]
I'm not sure why you poined it is vanilla, but crash is certainly caused by captureanimals mod

**Comment by DukkSauze** [comment]
Oh wow, I hadnt even realized I had the mod enabled. After disabling it, game works as it should. Thank you!
