### ISSUE TITLE
Only male moose !

### ISSUE THREAD

**Issue by Thor8472** [anegostudios/VintageStory-Issues#4092]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I found lots of moose in different worlds! even multiple farmed spawn points in single player mode. There are always only male moose! are you right? Why are there no female moose (or calves)?! I think a lot of people thought there were women, but in my experience thats only male moose without antlers.

### How to reproduce

1. Search for Moose 2. only find Male ;)

### Logs

```Log```

**Comment by sekelsta** [comment]
Confirmed on 1.20-rc.1 vanilla.
This is printed in the logs whenever a moose spawns: `[Warning] Entity with code game:deer-moose-male-adult has defined a companion spawn game:moose-female-adult, but no such entity type found.`
Looking at the moose entity, spawn companions are defined as `["moose-female-adult", "moose-female-baby", "moose-male-baby"]` when they should be `["deer-moose-female-adult", "deer-moose-female-baby", "deer-moose-male-baby"]`

**Comment by Thor8472** [comment]
Thx sekelsta! Its seems like the bug has been found! I hope it will be fix soon and not forgotten besides the big 1.20 changes ;)

**Comment by sekelsta** [comment]
Though, one might argue that moose should instead have solitary spawns, where females spawn separately without males but sometimes with calves.

**Comment by pizza2004** [comment]
Should be fixed in next release.
