### ISSUE TITLE
Kiln can't create fire clay bricks or blue clay bricks

### ISSUE THREAD

**Issue by ejzzje** [anegostudios/VintageStory-Issues#4099]
### Game Version

1.20 pre1

### Platform

None

### Modded

None

### SP/MP

None

### Description

Using a left-to-right order of raw red clay bricks, raw fire clay bricks, and raw blue clay bricks in four kilns with different amounts of doors open resulted in the following colors:
0 doors: red clay bricks, tan clay bricks, cream clay bricks
1 door: red clay bricks, orange clay bricks, grey clay bricks
2 doors: red clay bricks, red clay bricks, black clay bricks
3 doors: red clay bricks, brown clay bricks, black clay bricks
I assume raw fire clay and red clay bricks were mixed up with the intention of fire clay always producing fire clay bricks for bloomeries and one of the two black clay brick outcomes was supposed to be blue.

### Logs

```Log```

**Comment by RedramVS** [comment]
Fire bricks were firing into the intended red brick colors, which I've fixed (and mae fire fire into fire bricks).  Blue bricks as a finished product however will no longer be a thing in 1.20.   Blue clay raw bricks will make cream, grey, and black only.  Existing finished blue bricks will be remapped to the new grey.
