### ISSUE TITLE
Wood Trapdoors are no longer valid blocks for keeping rooms closed

### ISSUE THREAD

**Issue by pizza2004** [anegostudios/VintageStory-Issues#4101]
### Game Version

v1.20.0 pre-1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When building a room and using a trapdoor for the door the game does not properly detect the trapdoor as a valid block to close off the room.

(I noticed that the airtight field in the JSON is mistyped as `"door-solid*": true`, even though that should be `"trapdoor-solid*": true` if this were meant to work.)

### How to reproduce

Build a room with the new trapdoors.

### Logs

```Log```

**Comment by pizza2004** [comment]
I'm noticing also that the ruined wood trapdoors should probably not be airtight even if they are "solid" because of the way they look.

Also, the metal trapdoors say their material is wood still.

**Comment by Marcafk** [comment]
This is caused by a type in the airtight tag, wooden trapdoors have :
Solid trapdoors arent sealing a room, it appears the airtight tag has a typo, with the line:
        airtightByType: {
            "door-solid*": true,
            "*": false
        },
while meta trapdoors say trapdoor-solid*": true.
Changing the test in the json does appear to fix the issue
