### ISSUE TITLE
Wearing Leg Armour Makes your Character Model Freak Out

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4104]
### Game Version

v1.20.0 pre-1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Wearing leg armour messed up your character model.

### How to reproduce

1. Wear leg armour.

![legarmourbug](https://github.com/user-attachments/assets/a408dcf6-1071-4e20-8b84-4d46134a4a52)

### Logs

```Log```

**Comment by ifozz** [comment]
Apparently steel plate legs are oddly exempt from this. Lots of other leg armour is not, however.

**Comment by ifozz** [comment]
It isn't just leg armour turns out, some other armour does this, too.

**Comment by RedramVS** [comment]
Could you please test this again with pre2?  Pre2 may have fixed this.

**Comment by ifozz** [comment]
> Could you please test this again with pre2? Pre2 may have fixed this.

Yep. Sorry for the delay on this one, pre-2 did indeed fix this. :)
