### ISSUE TITLE
Leather Bracers Change Necklace Texture

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4107]
### Game Version

v1.20.0 pre-1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Wearing leather bracers will change the texture of your becklace.

### How to reproduce

1. Wear leather bracers and a necklace at the same time.

![normal1](https://github.com/user-attachments/assets/2d46f296-0a95-4d42-8150-ee154df4e646)

![bracers2](https://github.com/user-attachments/assets/75d586e9-44e6-4c21-a3e5-cf868c5bce53)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
