### ISSUE TITLE
Water Plants Waterlogging Above Water Level

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4109]
### Game Version

v1.20.0 pre-1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Water plants can generate with some parts out of water, which will waterlog the air block.

### Screenshots

![plant](https://github.com/user-attachments/assets/34aebe09-c576-48fe-8111-87c01a90d5a5)

### Logs

```Log```

**Comment by paginaweb123** [comment]
download
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by tyronx** [comment]
Hm, never seen this before. Is this still reproducible? If so, please reopen and provide us with a world seed

**Comment by ifozz** [comment]
> Hm, never seen this before. Is this still reproducible? If so, please reopen and provide us with a world seed

I haven't seen it since, so I think it might be fixed? This was all the way back in pre-1.
I'll let you know if it happens again but from what I can tell it seems to be gone.
