### ISSUE TITLE
Jumping Momentum Resets on Movement Midair

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4112]
### Game Version

v1.20.0 pre-1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When holding jump and running and then moving in a different direction midair, your momentum will be reset when you touch the ground, allowing only for short hops until you build up speed again.

### How to reproduce

1. Run while holding the jump key.
2. Move midair while still holding jump in a different direction.
3. You will only be able to perform small hops until you run without jumping to build speed again.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does it happen only in 1.20?

**Comment by ifozz** [comment]
> Does it happen only in 1.20?

Yeah, tested in both 1.19 and 1.20. This only happens in 1.20.

**Comment by Craluminum2413** [comment]
Fixed in pre.4
