### ISSUE TITLE
Soil won't settle after landslide

### ISSUE THREAD

**Issue by jevarlec** [anegostudios/VintageStory-Issues#4115]
### Game Version

v1.20-pre.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I have a world with sideways instability enabled. The issue is that, after a larger landslide, some soil block won't settle and continuously hover between positions. It is hard to describe and screenshots are probably not going to be useful. World file is 10MB when compressed, would it help if I share that?

### How to reproduce

1. Make a new world with sideways instability enabled
2. Cause a large landslide

### Screenshots

![2024-09-19_17-15-09](https://github.com/user-attachments/assets/5cfc8cdb-3972-46d6-bc0e-12f679ef77d9)

**Comment by Craluminum2413** [comment]
I saw such behavior even in 1.14, so it is very old issue

**Comment by Craluminum2413** [comment]
Looks like there is strange behavior that makes unstable blocks not settle on non-solid surfaces

**Comment by tyronx** [comment]
This should be addressed by now. Please reopen if not fixed yet.
