### ISSUE TITLE
Tamed elk floats better than a boat

### ISSUE THREAD

**Issue by Guimoute** [anegostudios/VintageStory-Issues#4116]
### Game Version

v1.20.0 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It moves very fast in water and doesn't sink.

### Screenshots

https://github.com/user-attachments/assets/90ccf650-c559-46e6-9886-f80fea7de3b6

### Logs

```Log```

**Comment by Marcafk** [comment]
Honestly it should float higher, its head is underwater, do you want it to drown?

**Comment by Craluminum2413** [comment]
@Marcafk Have you seen how dogs swim?

**Comment by Marcafk** [comment]
Yes they keep their nose above water so they can breathe.

**Comment by Craluminum2413** [comment]
Fixed in some pre, no idea which one
