### ISSUE TITLE
User Unfriendly Block References

### ISSUE THREAD

**Issue by lensless-github** [anegostudios/VintageStory-Issues#4117]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I have noticed two instances of user-unfriendly names displayed in the block info tooltip at the top of the screen. The first was when filling a watering can from a flowing water block, and the second was for a cooked soybean pie.

### How to reproduce

1. Set a water source block where it will flow to neighboring blocks
2. Fill watering can from block of flowing water
3. Note block info displayed at top of screen
------------------------
1. Fill pie with soybeans
2. Cook pie
3. Note pie name when removed from oven

### Screenshots

![2024-09-14_17-31-33](https://github.com/user-attachments/assets/da7587e9-39c1-48af-9228-cbe2b23bead5)
![2024-09-17_22-02-10](https://github.com/user-attachments/assets/319734c2-dd4d-44fb-8a06-0cceb54212ef)

### Logs

```Log```

**Comment by RedramVS** [comment]
Should be in pre3, thanks!
