### ISSUE TITLE
Certian Inventory Items Not Working

### ISSUE THREAD

**Issue by Endless-Oats** [anegostudios/VintageStory-Issues#4118]
### Game Version

1.20

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Low tier inventory items are not working at all. Specifically, baskets, hunter backpacks and linen sacks do not provide extra inventory space. Backpacks and reinforced backpacks work fine. Initially used mods, but uninstalled all of them and tried again to the same results. Tried multiple different worlds, multiple different seeds and settings, and tested it in creative. 

### How to reproduce

1. Load a world
2. Use a basket
3. Profit???

### Screenshots

![2024-09-20_03-58-07](https://github.com/user-attachments/assets/ca290377-4c78-40cf-8060-b20e9fd4204e)
![2024-09-20_03-58-14](https://github.com/user-attachments/assets/dbe769e0-40e0-4dca-befc-680d2fc59bb7)
![2024-09-20_04-09-24](https://github.com/user-attachments/assets/c5288c44-0591-4554-b3bd-5fd0d8921e01)

### Logs

```Log```

**Comment by Endless-Oats** [comment]
Here's logs, sorry
[server-main.log](https://github.com/user-attachments/files/17072401/server-main.log)
[client-main.log](https://github.com/user-attachments/files/17072405/client-main.log)

**Comment by Craluminum2413** [comment]
Is it pre.1 or pre.2?

**Comment by Endless-Oats** [comment]
pre.2, and I just reinstalled VS and it fixed it. Not sure why that works but I figured it would.
