### ISSUE TITLE
You can use elk for looking through blocks.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4121]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Riding elk can be used for looking through blocks like on video.

### How to reproduce

Check Video.

### Screenshots

https://github.com/user-attachments/assets/eba0e7e4-5272-4585-b1ef-0359ee611a96

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does it happen in survival?

**Comment by CookieBoy21** [comment]
I made fast test and yes it's only in creative mode.

https://github.com/user-attachments/assets/56400e59-7cff-41a5-a628-ec182519bdc8

**Comment by Craluminum2413** [comment]
Nothing is broken then
