### ISSUE TITLE
During riding when elk will take damage his animation will bugged.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4122]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Elk animation will bugged after taking damage like on video. You can reset it by pressing key for stop, jump, run etc.

### How to reproduce

Check Video.

### Screenshots

https://github.com/user-attachments/assets/c4ef3fd4-39b3-4dc1-9227-4277ff5874fe

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, should be fixed in pre3
