### ISSUE TITLE
Storage vessels break and have permenent extremely increased multiplier after unloading the chunk they are in 1.20pr2

### ISSUE THREAD

**Issue by Marcafk** [anegostudios/VintageStory-Issues#4127]
Was testing cellar designs and encountered anomalous numbers in previously built designs, a storage vessel inside a cellar was reporting 12 year storage for grain.
On testing it appears that storage vessels that are in chunks which get unloaded have their effective multiplier increased , the displayed numbers are the same though. baskets dont seem affected, grains are the most obviously affected but it does also appear to affect meat in storage vessels.
To replicate: Place a storage vessel, run or fly out of view distance, then return, then place another vessel next to it which will have the same displayed storage multiplier, take some grain and put half in each one, the new one will have the correct multiplier while the old one will be wrong. If the vessel is in a cellar the shelf life of the grain will be much much higher.

**Comment by Marcafk** [comment]
on more testing it will trigger just from logging out and reloading the world.  
![image](https://github.com/user-attachments/assets/37858ef2-7e2d-49fa-91fa-c71ef113c745)
here is what some spelt in a cellar in -50 arctic looks like after restarting. It was on.y 1.7 years originally

**Comment by Marcafk** [comment]
Further testing with shelves appear to show the number increasing over time, watching some jam slowly tick up to 2500 year shelf life.

**Comment by tyronx** [comment]
this should already be fixed a while ago
