### ISSUE TITLE
Every time I cut down a tree a single log drops and starts bouncing

### ISSUE THREAD

**Issue by Dystop-1a** [anegostudios/VintageStory-Issues#4128]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Every single time I cut down a tree all but one of the logs don’t drop and that one log will be bouncing. I cannot pick it up. I tried digging a 2x2 and 3x3 hole around it to get it to stop and pick it up but it just. Won’t. This makes any kind of progress impossible bc I need wood

**Comment by tyronx** [comment]
as cral wrote. this is addressed in 1.20
