### ISSUE TITLE
Game crashes after opening it (it worked yesterday)

### ISSUE THREAD

**Issue by Madnanvintage** [anegostudios/VintageStory-Issues#413]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.4 (Stable)05.03.2020 09:56:11: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _Nm2Dey99KsdwIYLpu4GOdoFloZP._qP4paZogWeAkBAdIetsRHNRsPeR()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._ryUq828Jdon4eHk5toV3WI6D1nH()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._TNhCFDnDMOpUfVxHZgPyWvoTAtF()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._wVES3I4AcneyUTHpdRuLu6EHvCH(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU , String[] )
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(ThreadStart )
-------------------------------

Would be great if you help me fast, because I took a dayoff just to play it and now it doesn't work. ._.

**Comment by Timmiwurschtl** [comment]
Same here, both 1.12.4 and 1.12.5 does crash. You should download the newest version 1.12.6 (https://account.vintagestory.at), it seems to work :)
Enjoy your free day!

**Comment by Madnanvintage** [comment]
Oh it worked. Thank you very much!
