### ISSUE TITLE
Disappearing items after using boat cargo slot.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4130]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In game there is bug that allow your items to disappearing from your inventory. You can trigger him by placing items like chest in cargo slot and open it. Right now after doing it chest will get label "empty" what is mention here #4129. After it you can shift+click your items from inventory even in survival and they will disappear but not entirely. They will teleport to cargo slot, exactly where you put your chest. You can put there crate and start taking back your missing items.

### How to reproduce

1. Place and open chest in boat cargo slot.
2. Now you can shift + click you items form inventory
3. Swap chest with crate and start taking your missing items 

### Screenshots

https://github.com/user-attachments/assets/e5a2a811-b1f0-4b91-a914-aa8f0b80323f

https://github.com/user-attachments/assets/1e60da2b-a142-47e8-ac8e-e5182941ab1f

All your items will be on here, exactky where you open your chest
<img width="1280" alt="Vintagestory Screenshot 2024 09 21 - 00 15 22 20" src="https://github.com/user-attachments/assets/812143be-0fe4-4227-9c6d-9bc6906e10b2">

https://github.com/user-attachments/assets/9ca83742-e7ee-4fd0-bf94-49eb265a22c7

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Should be fixed in pre.6
