### ISSUE TITLE
"Moving" Spawn and /serverconfig setspawnhere not working

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4131]
### Game Version

1.20pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I Created map in 1.20pre1. Make a "spawn" place but /serverconfig setspawnhere not working, so I raise the build to match the spawn location at 0 / 150 / 0. Then updated to 1.20pre2 - 0/0 moved about 30 blocks away. /serverconfig setspawnhere still not working ( command says the spawn change but not ). Playing for a while and after death I spawn again in different location.. 0/0 moved again few blocks...

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Did it happen in 1.19 before?

**Comment by DejFidOFF** [comment]
> Did it happen in 1.19 before?

Never before.. There are just Livemap, Playerlist, VS Server panel, The3essentials.. But no mod that modify the game..

**Comment by DejFidOFF** [comment]
Brand new install of VS included all in /VintagestoryData

**Comment by Wesmania** [comment]
I'm confirming the same issue, completely vanilla with no mods.

**Comment by Wesmania** [comment]
Also, the docs for "/serverconfig setspawn" list "z position" where it should be "y position", maybe it's related?

**Comment by Craluminum2413** [comment]
Fixed in pre.5
