### ISSUE TITLE
New mob can bugged after using standing on 2 legs animation.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4136]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

New mob can bugged when he will walk after using standing on 2 legs animation.

### How to reproduce

1. Spawn a lot of this enemies and look.

### Screenshots

https://github.com/user-attachments/assets/6b497c02-d041-4e00-91f7-b16d151b8dc8

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, will be fixed for pre3
