### ISSUE TITLE
Deepsplit type of new enemy have model problem.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4139]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Deepsplit type of new enemy have model problem.

### How to reproduce

1. Spawn Deepsplit type and take a good look on him.

### Screenshots

<img width="316" alt="Vintagestory Screenshot 2024 09 21 - 19 03 33 01" src="https://github.com/user-attachments/assets/16c21ae6-7d93-4b3b-afbf-8fb8b5a4a08d">
<img width="1280" alt="Vintagestory Screenshot 2024 09 21 - 19 02 51 15" src="https://github.com/user-attachments/assets/aa14acb8-d66b-49c3-b117-7323bbae3090">

https://github.com/user-attachments/assets/819773f7-be2b-4e13-afc8-2f2e9d3073ae

### Logs

```Log```

**Comment by RedramVS** [comment]
Should be fixed in pre3
