### ISSUE TITLE
Unable to climb down through metal trapdoors.

### ISSUE THREAD

**Issue by waru0w0** [anegostudios/VintageStory-Issues#4142]
### Game Version

v1.20 pre.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I can't get down through a metal trapdoor into a 1-block underground passageway, whether I have a ladder or not, whether I have a rope ladder or not, I can't get down. I tested this in creative mode, so I don't know if it's a modeling issue or an unfinished feature.

### How to reproduce

1. Place a metal trapdoor over a 1-block-sized passageway and try to walk through it.

### Screenshots

![2024-09-22_16-48-13](https://github.com/user-attachments/assets/346723c1-52e5-41fc-b57e-e43f932cecbd)

### Logs

```Log```

**Comment by waru0w0** [comment]
Someone first reported that wooden trap doors don't separate rooms, so we fixed that.

**Comment by Craluminum2413** [comment]
I added code label because I think it is the code that generates wrong hitboxes

**Comment by Craluminum2413** [comment]
Fixed in pre.4
