### ISSUE TITLE
You can use rope for put elk on elk.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4143]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

You can use rope for put elk on elk, it's work with animals like pig too.

### How to reproduce

1. Use rope on on elk
2. Use this same rope on other elk.

### Screenshots

https://github.com/user-attachments/assets/5bebd99d-2791-4193-a2eb-7f1c3ef82a1b

<img width="1280" alt="Vintagestory Screenshot 2024 09 22 - 01 32 19 11" src="https://github.com/user-attachments/assets/3b7cbc8b-9ef3-41da-a3ba-aaac2f012b8f">

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update

**Comment by Craluminum2413** [comment]
Here is elk sandwich before new pre releases
![2024-11-15_13-31-40](https://github.com/user-attachments/assets/d005fba0-8471-4427-9c26-aaafdbd21e68)
