### ISSUE TITLE
Healing elk will make him panic.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4144]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Elk will run away like they was hit after healing him.

### How to reproduce

1. Make sure elk have some hp lost.
2. Heal him with healing items.
3. Watch how he run away from you.

### Screenshots

https://github.com/user-attachments/assets/70f1b18b-cea3-4f69-8275-f5b95d2216d0

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, will be fixed in pre3

**Comment by maltiez2** [comment]
Will be fixed in next update
