### ISSUE TITLE
World Configuration User interface Glitch

### ISSUE THREAD

**Issue by 2amazing2much** [anegostudios/VintageStory-Issues#4147]
### Game Version

v1.20-pre.2

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When configuring a world, after pressing the "Survival Challenges" tab and scrolling down then pressing another tab causes the text and options of every other tab to stick to the bottom of their respective tabs.

### How to reproduce

1. go to world configuration
2. Press the "Survival Challenges" Tab and scroll down
3. do not scroll up, leave the scroll wheel at the bottom, and then press another Tab
4. all other pages are now temporarily formatted wrong, and stick to the bottom of the Tab.
5. To undo this, you simply have to go back to the "Survival Challenges" Tab and scroll up. (even if the scroll bar is already at the top)

### Screenshots

![Screenshot 2024-09-22 233329](https://github.com/user-attachments/assets/130d15ca-50ca-4586-a606-c08744821702)
![Screenshot 2024-09-22 233350](https://github.com/user-attachments/assets/1dda479b-fa91-4e50-9bb6-ec980e3b56da)
![Screenshot 2024-09-22 233344](https://github.com/user-attachments/assets/4a3b2a56-08dc-4e5e-a2c2-7d06cd7ebcd4)
![Screenshot 2024-09-22 233357](https://github.com/user-attachments/assets/b20c3acd-beae-4077-884b-e41db8a63643)

### Logs

```Log```

**Comment by tyronx** [comment]
hm. strange. i am not able to reproduce this

**Comment by tyronx** [comment]
Please reopen if reproducible again
