### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by LaserCraft52** [anegostudios/VintageStory-Issues#415]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.4 (Stable)05.03.2020 11:24:39: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _Nm2Dey99KsdwIYLpu4GOdoFloZP._qP4paZogWeAkBAdIetsRHNRsPeR()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._ryUq828Jdon4eHk5toV3WI6D1nH()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._TNhCFDnDMOpUfVxHZgPyWvoTAtF()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._wVES3I4AcneyUTHpdRuLu6EHvCH(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU , String[] )
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(ThreadStart )
-------------------------------

**Comment by Timmiwurschtl** [comment]
We have multiple issues open for this now...pls pay attention to that.
The solution (for my girlfriend, another player here and for me) was simply to download the newest version (v1.12.6). That should fix the crash, we already played :)

**Comment by PAT899** [comment]
https://www.vintagestory.at/blog.html/news/crash-on-startup-fix-v1126-r240/

**Comment by LaserCraft52** [comment]
Thanks for the advise
The game is working now again
