### ISSUE TITLE
cannot calcinate flint in firepit

### ISSUE THREAD

**Issue by Satras1** [anegostudios/VintageStory-Issues#4153]
### Game Version

v.1.20.0 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

cannot calcinate flint in firepit to craft fire clay. firepit tooltip suggests use of crucible to calcinate flint, yet crucible will not accept flint as input.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It looks like it needs bloomery

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in pre3
