### ISSUE TITLE
Hide rots during lime soaking

### ISSUE THREAD

**Issue by dordle** [anegostudios/VintageStory-Issues#4154]
### Game Version

v1.20 pre1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Hot climates cause hide to rot even during soaking in a sufficiently hot climate like a tropical one.

### How to reproduce

1. Put hide in limewater in hot climate, outside
2. Set it to soak
3. Wait
4. It rots before it finishes

**Comment by Craluminum2413** [comment]
Do you mean it rots in barrel?

**Comment by dordle** [comment]
Yes. It rots within the limewater soaking recipe inside a barrel after it's been closed. The recipe is quick enough that it probably won't occur unless the ambient air peaks at 35°C or higher, but it still does.

**Comment by BradyThe** [comment]
This applies to any item sealed in a barrel that has a shelf life. Until 1.20.0 sealing a barrel removed the spoilage from the item within, with 1.20.0 this was either added or snuck in.

v1.19.8:
![2024-10-06_00-23-57](https://github.com/user-attachments/assets/f97b83e9-5cf8-4e6b-b366-18bb586bca02)

v1.20.0pre5:
![2024-10-06_00-27-39](https://github.com/user-attachments/assets/5e38b8c4-28cb-46c9-98d7-f1100b869083)

**Comment by maltiez2** [comment]
Should be fixed already
