### ISSUE TITLE
Buggy sailing on the raft if camera POV change

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4155]
### Game Version

1.20pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

If sailing on raft and change camera view it starts to sail backwards ( and glitching )

### Screenshots

https://github.com/user-attachments/assets/51148a67-ae9b-4058-90d1-72de58a9b6f7

### Logs

```Log```

**Comment by maltiez2** [comment]
Now player facing the right way in third person.
