### ISSUE TITLE
Missing recipe? Red clay can't be used to make slate roof.

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#4156]
### Game Version

v1.20.0-pre.2

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I don't know if this is intentional or not, but red clay seems to be most plentiful in v1.20. Unfortunately it can't be used to make slate roof blocks.

### How to reproduce

Try to make any slate roof block with red clay.

### Logs

```Log```

**Comment by DejFidOFF** [comment]
I play 1.20pre2 for a while. Found 12 depostits of red clay, 2 of blue one and 0 of fire clay.. idk what is going on here..

**Comment by Marcafk** [comment]
> I play 1.20pre2 for a while. Found 12 depostits of red clay, 2 of blue one and 0 of fire clay.. idk what is going on here..

Fireclay now can only be found in the ground underneath black coal deposits. Or small quantities in cracked vessels in ruins.
However, now it can be made using ground calcined flint and regular clay. Rrc2 has a bug where ir cant be cooked in firepit but that should get fixed soon.

**Comment by RedramVS** [comment]
fireclay can also be found in bauxite sand (and bauxite gravel in pre3 as well).  That didn't make it into the patch notes unfortunately.  pre3 will also have the commodities trader selling it.  Pre3 will also allow all kinds of clay to be used in slate roof construction.
