### ISSUE TITLE
Bell can't spawn new type of enemy.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4159]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Bell can't spawn new type of enemy, only drifters and locust.

### How to reproduce

1. Spawn few bells. 
2. Make sure you are safe and turn on survival mode.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 09 22 - 16 08 46 17" src="https://github.com/user-attachments/assets/f9771e85-0866-4c2f-8d45-2ade57a6dd9c">

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Changelog for 1.20 doesn't have anything about bells
