### ISSUE TITLE
GUI problem on character creation.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4165]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

There is problem with clicking on "hit box" of all options during character creation. On photo I marked how this look. It's just lower that it's should.

### How to reproduce

1. Open character creaton.
2. Try click any hair type, little below other type.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 09 25 - 23 38 23 11" src="https://github.com/user-attachments/assets/4ad9fedc-2951-4f87-9da7-77da0af46e47">

https://github.com/user-attachments/assets/ed917d6c-6a94-4ae1-adcf-b1251b9cb575

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Did it happen in 1.19 before?

**Comment by CookieBoy21** [comment]
It's was in 1.19 too.

**Comment by CookieBoy21** [comment]
Fixed in v1.20 pre.10
