### ISSUE TITLE
Passenger in raft is left behind on v1.20.0-pre.2

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#4168]
### Game Version

v1.20.0-pre.2

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I was running the server locally. When another player got in to my raft, they appear seated on top of the water and don't move when the raft moves.

### How to reproduce

1. Get in a raft.
2. Have your friend get in with you.
3. Paddle away.

### Screenshots

![2024-09-26_15-43-06](https://github.com/user-attachments/assets/e2bf42e1-38f3-485c-8a37-08fd0cf9be72)

### Logs

Nothing to report here.

**Comment by CrystalChris55** [comment]
Can confirm the same on a dedicated server as well.

**Comment by AbortRetryFail** [comment]
This seems to be fixed as of 1.20.0-pre.9
