### ISSUE TITLE
Can remove non-removable decor with another decor

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#4169]
### Game Version

v1.20.0-pre.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Can remove such decor as wallpapers which is by default is non-removable by placing linen/carpet at the same place

### How to reproduce

1. Place wallpaper on face of a block
2. Try place linen on the same face
3. Wallpaper is dropped, but it shouldn't

**Comment by maltiez2** [comment]
Will be fixed in next update
