### ISSUE TITLE
Game has crashed

### ISSUE THREAD

**Issue by Ike-cyber** [anegostudios/VintageStory-Issues#417]
**Game Version:** v1.12.5
**Platform:** Windows 
**Modded:** No 

### Description
Could not start the game.

### How to reproduce
 It crashes / doesn't do the thing.

### Logs
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.5 (Stable)05.03.2020 11:55:45: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )

**Comment by Timmiwurschtl** [comment]
We have multiple issues open for this now...pls pay attention to that.
The solution (for my girlfriend, another player here and for me) was simply to download the newest version (v1.12.6). That should fix the crash, we already played :)

**Comment by PAT899** [comment]
https://www.vintagestory.at/blog.html/news/crash-on-startup-fix-v1126-r240/
