### ISSUE TITLE
Brown and red bricks are still hidden in handbook

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#4170]
### Game Version

v1.20.0-pre.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

1.20 adds crafting of brown and red bricks, but they are still hidden in handbook

How to fix:
Open `survival/blocktypes/clay/brickcourse.json`, then remove lines below from attributes:
```json
"excludeByType": {
    "*-brown": true,
    "*-red": true
}
```

### How to reproduce

1. Open handbook
2. Search for any red or brown bricks
3. Try open their page
4. It doesn't open

**Comment by RedramVS** [comment]
Should be fixed next update
