### ISSUE TITLE
Elk mark on map don't disappear after his body gone.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4173]
### Game Version

v1.20 pre4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Elk mark on map don't disappear after his body gone, until you will mark new elk again.

### How to reproduce

1. Mark elk as your own.
2. Kill him.
3. Skip time until his body will gone.
4. Check map.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 09 27 - 19 24 23 96" src="https://github.com/user-attachments/assets/e4d5ec9d-ef1c-4e79-be22-9e5f554e6a32">

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
