### ISSUE TITLE
Extreme Performance Loss in Preview Build 1.20.P4

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#4175]
### Game Version

1.20.P4

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Updating into the New Pre-Release Version, noticed a severe loss in performance on the High setting in comparison to the previous 1.20.P2 build. The following features had to be reduced in order to acquire a decent 60fps, otherwise it had terrible performance. 

![image](https://github.com/user-attachments/assets/73c7944d-4749-4837-8e0b-0e575e49fc7d)

### How to reproduce

Update to the new pre-release version 4. 
Set settings to at least High. 
Observe. 

### Logs

```Log```

**Comment by Marcafk** [comment]
This is probably a separate issue, however I found that felling a giant oak or redwood would destroy my fps while looking at the dropped items, 25ish stacks of logs in either case.

**Comment by nskjellum** [comment]
This seems to have been fixed in between the pre-release updates, having tested with 1.20.P4
