### ISSUE TITLE
1.20pre4 When building boat missing to show the ingredience

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4184]
### Game Version

1.20pre4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

When starting to build the boat at one point you don´t know what 21 items missing....

### How to reproduce

Start a build boat..

### Screenshots

![boat missing](https://github.com/user-attachments/assets/91ca3410-20f1-48b8-922b-67a1c9a4494f)

### Logs

```Log```

**Comment by RedramVS** [comment]
You are correct that it's a bug that it does not show those 21 ingredients, however I just wanted to mention that it does show the necessary ingredients if you have the interaction info overlay enabled, in case you did not have that enabled.  You do have to get fairly close to the boat to see interaction helps when enabled.

**Comment by DejFidOFF** [comment]
..and you can easilly duplicate roller logs by placing and pick up them..

**Comment by Craluminum2413** [comment]
> ..and you can easilly duplicate roller logs by placing and pick up them..

Make separate issue for this

**Comment by Craluminum2413** [comment]
Fixed in pre.6
