### ISSUE TITLE
Artisan Scarf Clipping Bug

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4187]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The artisan scarf has a clipping bug on one side - it clips through coats that hang below the waist.

### How to reproduce

1. Wear the artisan scarf and a long coat.

### Screenshots

![scarf](https://github.com/user-attachments/assets/4f6985b2-a149-4d18-ab2c-4e249349e4da)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed in the next pre
