### ISSUE TITLE
Scythe "trim grass" tool mode destroys grass blocks in many situations

### ISSUE THREAD

**Issue by Guimoute** [anegostudios/VintageStory-Issues#4189]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Grass blocks are destroyed despite setting the scythe's tool mode to "**trim** grass".

- Hitting eaten grass with a scythe in this tool mode should simply do nothing. Your beard doesn't disappear when you pass the beard trimmer in it twice. It just stays short. 
- Hitting cattails destroys grass around it regardless of tool mode and grass length.

### How to reproduce

In "trim grass" tool mode, scythe:
- eaten grass.
- cattails (and likely its variants like papyrus and tule).
 

### Screenshots

https://github.com/user-attachments/assets/873dd319-5bbd-44ba-975b-d06c4ba58baa

### Logs

No.

**Comment by maltiez2** [comment]
Will be fixed in next update

**Comment by Guimoute** [comment]
> Will be fixed in next update

Good to hear, thank you! 
I didn't know modders could be assigned to specific tasks. :D
