### ISSUE TITLE
Wrong texture of sailboat in winter?

### ISSUE THREAD

**Issue by Satras1** [anegostudios/VintageStory-Issues#4195]
### Game Version

v.1.20.0 pre4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I don't think the sailboat should look like that in winter...

### Screenshots

![2024-10-01_09-23-42](https://github.com/user-attachments/assets/8c3eeeb5-30c1-484b-b745-c14a49c68105)

### Logs

```Log```

**Comment by maltiez2** [comment]
Seems to be already fixed
