### ISSUE TITLE
Forlorn Hope Tunic Disalligned Textures

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4196]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The textures on one arm of the Forlorn Hope Tunic are disalligned.
The icon and on the sleeve is supposed to fit the centre of the arm, like it does in 1.19, but on one arm it is off-centre.
The dots are also in a different, unintended position.

This also applies to the King Blouse.

### How to reproduce

1. Wear Forlorn Hope Tunic

### Screenshots

![2024-10-01_17-26-38](https://github.com/user-attachments/assets/e7807c27-63c8-4388-a304-bc7caa5a7a40)
Disalligned texture.

![2024-10-01_17-26-41](https://github.com/user-attachments/assets/017a0627-d479-431d-bc00-4a6ea347f010)
Other sleeve showing correct allignment of symbol and dots.

### Logs

```Log```

**Comment by RedramVS** [comment]
These should both be fixed in the next pre or 2
