### ISSUE TITLE
Cloaks and Helmets Clipping

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4197]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Cloaks and helmets can clip into each other.

### How to reproduce

1. Wear a cloak and a helmet.

### Screenshots

![2024-10-01_17-38-57](https://github.com/user-attachments/assets/974b1c32-bb86-45dd-badf-3e13ee607605)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed in the next pre or 2
