### ISSUE TITLE
Clockmaker Pants Suspenders Clipping

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4198]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The suspenders of the Clockmaker Trousers clip into shirts.

### How to reproduce

1. Wear the clockmaker trousers and a shirt.

### Screenshots

![2024-10-01_17-42-23](https://github.com/user-attachments/assets/a28ffc34-7c0d-47dc-ba61-1313cd176900)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed in the next pre or 2
