### ISSUE TITLE
1.5.2.5 Chest access funkyness 3

### ISSUE THREAD

**Issue by RainnMannx** [anegostudios/VintageStory-Issues#42]
Cant select chest from a certain distance, though once you select one that you can reach, it allows you to select ones that should be out of reach, letting you open it and it closes right after that.
https://youtu.be/ohj62_tco5M

**Comment by tyronx** [comment]
Already reported and fixed for 1.5.2.3

**Comment by RainnMannx** [comment]
Pardon, thought it was fixed with 1.5.2.2

**Comment by RainnMannx** [comment]
Think this is different then the other chest one, this happens only after selecting a chest you can reach.

**Comment by RainnMannx** [comment]
Still in 1.5.2.3

**Comment by tyronx** [comment]
Aw :/
But why D:

**Comment by RainnMannx** [comment]
https://youtu.be/cUCVVbS5K3A
Looks like its getting better.
Range to select and open is fine as far as i can tell now.
Range to select after a chest has been selected and open properly seems to be farther then it was before.
The range is at the the edge of barely selectable.
Why does the range extend when select and open a chest?
![chest](https://user-images.githubusercontent.com/24833382/37881317-274e3676-3064-11e8-8f6f-5c8fa036470c.png)
Green, chest that can be selected before opening a chest.
Yellow, chest that can be selected after selecting a chest, and opens ok.
Red, chest that can be selected after selecting a chest, and closes immediately once opened.

**Comment by Craluminum2413** [comment]
Reproducible even in 1.15.0-pre2 :)

**Comment by JustForVS** [comment]
Works for doors, too. Just unlock the curser and you can open doors from a greater distance (as soon as you get the block info overlay). So the reason is not the chest.

**Comment by Th3Dilli** [comment]
thank you very much @noelle-lavenza for the detailed info on how to fix it 

should be taken care of for next release
