### ISSUE TITLE
[Bug] Support beams will delete water blocks if placed in certain way

### ISSUE THREAD

**Issue by BradyThe** [anegostudios/VintageStory-Issues#4201]
### Game Version

1.19.8, 1.20.0-pre.4

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

If placed in certain positions the beginning (first block) of a support beam will delete the intersected water block or the face of adjacent water blocks.

Seen on stream on v1.20.0-pre.4.
Tested on v1.19.8.

Potentially related to https://github.com/anegostudios/VintageStory-Issues/issues/2618.

### How to reproduce

1. Place support beam on block adjacent to water.

### Screenshots

![20241001205929_1](https://github.com/user-attachments/assets/c10dfdc6-3ff4-4311-9191-7f22cf7e6b78)
![20241001205948_1](https://github.com/user-attachments/assets/c235bfcd-9ddf-4f6b-a48e-ca80317e566c)
![20241001210400_1](https://github.com/user-attachments/assets/c01e7077-e8d0-49ce-96d5-9de2a472a423)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
Thank you , will be fixed with next pre release
