### ISSUE TITLE
Player Report: FireFish

### ISSUE THREAD

**Issue by Spiderchipmonk32** [anegostudios/VintageStory-Issues#4207]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

A player by the user name FireFish was allowed to enter the claim on an official server and stole 64 flax from another user named root01 and stole iron nuggets from our group before running away. FireFish was apparently caught hiding things in a chest which leads me and another member of my group to believe that those items where not the only things that he had stolen as many hammers (iron, bismuth bronze and copper) had gone missing previous within a short period of time.

### How to reproduce

1. Not possible

**Comment by Craluminum2413** [comment]
This place is not for player reports, report it in discord to people TOPSModerator with role
