### ISSUE TITLE
1.20pre4 When sleeping, can´t wake up ( before whole cycle )

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4208]
### Game Version

1.20pre4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Go sleep and try to wake up before whole cycle ( by bed ) is done.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@DejFidOFF what happened?
