### ISSUE TITLE
Salted hide not working with Borax

### ISSUE THREAD

**Issue by yellowincarnate** [anegostudios/VintageStory-Issues#4210]
### Game Version

1.20 pre 4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Salted hide (Huge) is unable to be turned into soaked hide in diluted borax.

### Screenshots

![2024-10-02_22-12-11](https://github.com/user-attachments/assets/b50f2421-de53-4bdd-a6ba-a395f0cf98ec)

### Logs

```Log```

**Comment by RedramVS** [comment]
Will be fixed in next pre
