### ISSUE TITLE
Putting items into reed chest mounted on raft creates "ghost" items

### ISSUE THREAD

**Issue by Monkeybrain73** [anegostudios/VintageStory-Issues#4214]
### Game Version

v1.20.0 pre4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Some times when putting items into a reed chest placed on the new raft, the items duplicates and creates ghost variants of the items. When moved back into your inventory, the items poof completely, both the original and ghost items.

The new ghost items can be stacked together with the original, if stack size allows, and moved back and forth between the chest on the raft and inventory.

As soon as you try to swap place with any other item in your inventory, the entire stack of the duped items disappears, original and ghost versions.

### How to reproduce

1. Place reed chest on the raft
2. Open the chest and put any item in
3. Move the item to a different slot
4. Move item back to your inventory
5. Swap place with another item in your inventory, and the item that had been in the reed chest will disappear

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Should be fixed in pre.6
