### ISSUE TITLE
Forgotten Noble Robe Offers No Warmth

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4218]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The forgotten noble robe no longer offers any kind of warmth bonus.

### Screenshots

![nowarmth](https://github.com/user-attachments/assets/ad7f8be8-b8e5-401e-a9ec-ce30619e0434)

### Logs

```Log```

**Comment by ifozz** [comment]
Neither do:
Handsome laced gloves
Clockmaker wristguard
Hunter hood

There may be more that I have missed.

**Comment by RedramVS** [comment]
Should be fixed next pre
