### ISSUE TITLE
One Side of the Scribe Table (Tablecloth) is Dark

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4222]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

For some reason, the tablecloth texture on one side of the scribe tables is dark (regardless of lighting or sunlight).

### Screenshots

![2024-10-04_19-32-46](https://github.com/user-attachments/assets/3b208eca-f50b-47c6-9201-e3d6a44cb1ab)
Dark side.

![2024-10-04_19-32-51](https://github.com/user-attachments/assets/d7ffe347-20ef-47c3-b563-0f9ab9a059b6)
Light side.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Does it happen in 1.20?

**Comment by ifozz** [comment]
> Does it happen in 1.20?

Yeah, still happens in 1.20.

**Comment by RedramVS** [comment]
Should be fixed next pre
