### ISSUE TITLE
Shift clicking items from inventory when hotbar is full voids objects

### ISSUE THREAD

**Issue by lmbz115** [anegostudios/VintageStory-Issues#4237]
This a reopen of [(https://github.com/anegostudios/VintageStory-Issues/issues/4177)]

This issue was closed because the user was in creative, but this happens in survival. This video was recreated in a multiplayer server on version 1.19.8. Attached is the clip and screenshot of the audit log. Items are voided in survival.

https://github.com/user-attachments/assets/ed174536-23fa-49ea-b935-30c32e9db1b7

![image](https://github.com/user-attachments/assets/bd4a9f32-f576-4e33-9ca2-c5e8e934cc47)

**Comment by Craluminum2413** [comment]
Duplicate of #4177

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4134
