### ISSUE TITLE
Item respawn of half looted animals after chunk reload

### ISSUE THREAD

**Issue by Bloodsaw** [anegostudios/VintageStory-Issues#424]
**Game Version:** 1.12.6
**Platform:** Windows 10
**Modded:** No

### Description
Found by discord User @Jacks:
"Items do respawn after a while, if you dont loot animals completely."

Unlike original reported you cannot really duplicate the items, they will disappear if you try to stack them with "real" items or to use them.  

### How to reproduce
1. Kill an animal
2. Loot some items and leave the rest
3. Close loot window
4. Type `/debug cr` to force reloading the chunks at current play position
5. reopen the looting inventory

Also if you Shift+LMB the respawned items dissappear right away.
You are able to drag'n'drop them into your inventory and stack them with existing items.
If you klick the new stack now, you will automatically "drag'n'drop" the old amount and and the rest disappears.
Sometimes you are even able with RMB to duplicate numbers of the stacks, but they also disappear after interacting again.

### Screenshots
![2020-03-05_16-48-54](https://user-images.githubusercontent.com/61588797/75999887-2778f300-5f03-11ea-992d-97e14ef8aae7.png)

![2020-03-05_16-49-16](https://user-images.githubusercontent.com/61588797/75999905-2e076a80-5f03-11ea-94d2-b358dbea0bb9.png)
![2020-03-05_16-51-14](https://user-images.githubusercontent.com/61588797/75999930-352e7880-5f03-11ea-9d66-a6a22eb9bd2a.png)

**Comment by tyronx** [comment]
I think this is fixed in v1.12.11

**Comment by Bloodsaw** [comment]
I'm still able to reproduce this on 1.12.11.
It only happens after reloading the chunk though. 

Whats strange too, that in the moment `/debug cr` is done with reloading the chunk you are seeing the dying animation of the animal again. Maybe this information helps finding the culprit

**Comment by threeheadeddingo** [comment]
This issue does not necessarily require any kind of chunk loading/unloading as far as I know.

You can replicate these kinds of loot synchronization errors simply by having one person kill an animal, loot only a few things (not enough to make the body explode), and then have another player check the inventory of the dead animal. The other player will see that nothing has been looted until they try to manipulate the inventory, then it synchronizes up.

**Comment by Bloodsaw** [comment]
The initial reported issue of @jacks is now fixed with 1.12.14

> Fixed: Should fix harvested creature drops not properly synced up to all players
I did some test and wasn't able to trigger this.  Good work!
