### ISSUE TITLE
Bowtorn enemy will still shooting to you after your dead.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4246]
### Game Version

v1.20 pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Bowtorn enemy will still shooting to you after your dead. 

### How to reproduce

1. Just give Bowtorns kill yourself.

### Screenshots

https://github.com/user-attachments/assets/79443f19-2ba3-4162-ae0a-5db5e249d98f

### Logs

```Log```

**Comment by BradyThe** [comment]
They also never lose sight of you, will track your movement and continue shooting at you, even if unreachable and separated by solid blocks.

**Comment by CookieBoy21** [comment]
Fixed not sure when, tested in pre.9
