### ISSUE TITLE
Game crash at start

### ISSUE THREAD

**Issue by saures07** [anegostudios/VintageStory-Issues#4250]
### Game Version

all that i've tried

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

this thing pop up when i try to launch the game, i downloaded launcher from their site : https://info.vintagestory.at/v1dot20

### Screenshots

![image](https://github.com/user-attachments/assets/66c5d979-d4ac-4b10-90f9-59ef02be3354)
![image](https://github.com/user-attachments/assets/e83655a0-f1da-41e8-af7d-de28ab0c62df)

### Logs

[client-audit.log](https://github.com/user-attachments/files/17280456/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/17280457/client-chat.log)
[client-crash.log](https://github.com/user-attachments/files/17280458/client-crash.log)
[client-crash.txt](https://github.com/user-attachments/files/17280459/client-crash.txt)
[client-debug.log](https://github.com/user-attachments/files/17280460/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/17280461/client-main.log)
[server-worldgen.txt](https://github.com/user-attachments/files/17280462/server-worldgen.txt)

**Comment by Craluminum2413** [comment]
Try update, downgrade or reinstall your graphics drivers

**Comment by saures07** [comment]
> Try update, downgrade or reinstall your graphics drivers

i've updated drivers to latest yesterday, but i havent tried to reinstall them, i will try
