### ISSUE TITLE
Speleothems can prevent Resonance Archive progress

### ISSUE THREAD

**Issue by TherronKeen** [anegostudios/VintageStory-Issues#4255]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

In the Resonance Archives area, the hallway leading out of the water reservoir to the wooden walkway can be blocked by randomly generated speleothems. 

### Screenshots

![2024-10-06_21-46-06](https://github.com/user-attachments/assets/c2e35828-a409-42ab-87c8-e5eaac80bfa7)
![2024-10-06_21-46-10](https://github.com/user-attachments/assets/3954883f-b1fe-42be-8530-a7f55e380e15)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in 1.20
