### ISSUE TITLE
Visual Bug for snow on brick stairs

### ISSUE THREAD

**Issue by LazierThanThou85** [anegostudios/VintageStory-Issues#4258]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Snow doesn't show up on certain stair placements.  Instead of the snow appearing on top, it copies the texture of the staircase and puts it in the snow layer.  I've seen only seen this on staircases made by bricks(Blue clay brick stairs, Fire clay brick stairs, Brown clay brick stairs).  I assume it also happens with Red clay brick stairs, but I haven't actually seen it.
![2024-10-08_16-46-21](https://github.com/user-attachments/assets/db2cfaea-f23b-44c3-ab6a-2200aaddcea4)
![2024-10-08_16-46-35](https://github.com/user-attachments/assets/555b62f7-8443-4134-a2a1-cb342dab9056)
![2024-10-08_16-46-43](https://github.com/user-attachments/assets/6825e595-6922-4e17-808f-d88e90dce2c4)
You can also tell it's happening by the wire frame outline on the blocks where my cursor is pointed.  It's especially noticeable in the first screenshot, because it includes stone path stairs right next to it.

### How to reproduce

Make X clay brick stairs, make it snow, see if the snow layer appears.

### Logs

```Log```

**Comment by RedramVS** [comment]
This was also an issue with new brick slabs.  Both should be fixed next pre.  Let us know if you notice on any other blocks.
