### ISSUE TITLE
Part of Malefactor Trousers is Strangely Darker

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4266]
### Game Version

v1.20.0 pre-5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Part of the Malefactor Trousers waistband is darker than the rest, and I do now know if this is intentional or not, so I thought I would just report it here. :)

### Screenshots

![malefactor](https://github.com/user-attachments/assets/c8e6798a-663a-4f0f-93be-17adebdc93c8)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed next pre
