### ISSUE TITLE
Squeezing honeycomb into barrel vanishes

### ISSUE THREAD

**Issue by Krougal** [anegostudios/VintageStory-Issues#4268]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Squeezing honeycomb into barrel honeycomb is used as expected. No honey goes into barrel nor does wax get created.

### How to reproduce

1. Ctl + click over barrel with honeycomb in hand.
2. When process is finished note that honey level in barrel does not change.
3. Note that you didn't get 3 more wax in inventory either.
4. Squeezing into bucket or bowl is working as expected. I can also pour a bucket into a barrel and it works as expected.

### Logs

```Log```

**Comment by Krougal** [comment]
Checking the wiki, I see barrel is not listed so perhaps this is not a bug but should be a feature request instead?

**Comment by Craluminum2413** [comment]
> Checking the wiki, I see barrel is not listed so perhaps this is not a bug but should be a feature request instead?

Yes this is a suggestion, suggestions are only allowed on forums or in discord
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by Krougal** [comment]
Although I would consider it a bug that it allows you to squeeze it out when it is not a valid target...

**Comment by BradyThe** [comment]
> Although I would consider it a bug that it allows you to squeeze it out when it is not a valid target...

I'd most certainly say so.

**Comment by Craluminum2413** [comment]
@Krougal Do you mean whole honeycomb disappears?

**Comment by Krougal** [comment]
> @Krougal Do you mean whole honeycomb disappears?

Correct.
