### ISSUE TITLE
VS crashing after "cumulative .net update" last night

### ISSUE THREAD

**Issue by mactso** [anegostudios/VintageStory-Issues#4269]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

My son in law's computer is crashing in single player and multi player after the .net update last night.

The game starts and he gets to the point of selecting single or multi player, but while loading the game, the screen goes  black.   

We confirmed no windows or video card updates for the prior 10 days.  The game worked fine Monday and Tuesday afternoons.  The problem started this morning when we tried to log on to play.

### How to reproduce

1) Get an older windows 10 machine that got the .net update last night.
2024 - 10 Cumulative Update for .NET framework 3.5, 4.8, 4.8.1 for Windows 10, version 22H2 for x64 (kb5044091)
2) Run Vintage Story,  Enter a single player or multi player game.  The game should crash within a couple minutes of starting or even before it finishes starting.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Have you tried to reinstall NET 7?

**Comment by mactso** [comment]
I'll confirm tomorrow late morning / early afternoon when we try again.  He did reinstall Vintage Story.
The update last night appears to have installed .NET 8.

Update in about 10 to 12 hours.

**Comment by mactso** [comment]
Okay, he reinstalled both .NET 7 and removed and reinstalled Vintage Story and the game is working again.
