### ISSUE TITLE
You can call wounded elk with flute.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4271]
### Game Version

v1.20 pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

You can call wounded elk with flute.

### How to reproduce

1. Mark elk with head medallion.
2. Make sure he is wounded.
3. Call him with flute.

### Screenshots

https://github.com/user-attachments/assets/0186ee08-4a9a-4cdb-bd99-b5c1cebbdd89

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
