### ISSUE TITLE
Coral reefs looks like thrown garbage

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4272]
### Game Version

1.20pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

It´s really cool addition, but it looks like trash thrown from van to water..

### Screenshots

![2024-10-08_19-45-52 kopie](https://github.com/user-attachments/assets/de0e7cd1-56de-4f99-9d6c-38be2690267d)
![2024-10-08_19-46-30 kopie](https://github.com/user-attachments/assets/5feb375f-b742-4c70-8a44-555b9d6ee310)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Do they generate yet or you placed them?

**Comment by DejFidOFF** [comment]
This is how it´s natural generates

**Comment by RedramVS** [comment]
Reefs are still a work in progress, but throwing out opinions on appearance is not an appropriate use of the bug reporting function.  Also your screenshots aren't an accurate representation, as they lack the murkiness of the water which actually prevents one from being able to view the entire reef at once.
