### ISSUE TITLE
Can't pick up "reed basket" (after using it as a "reed basket trap") when loaded with item.

### ISSUE THREAD

**Issue by Y0wann** [anegostudios/VintageStory-Issues#4277]
### Game Version

v1.20.0-pre.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Unable to pick up "reed basket" (after using it as a "reed basket trap") when loaded with item.
Also wrong texture

### How to reproduce

-Release the animal caught form the "reed basket trap".
-Having any item in the added slots from the basket.
-Drop the basket from your inventory
-Then can't pick it up

https://github.com/user-attachments/assets/e96aa4c0-1ea9-488c-bd60-7f913d946ee5

### Logs

```Log```

**Comment by BradyThe** [comment]
This issues should be fixed in pre6 (#4200).
