### ISSUE TITLE
1.20pre5 Bugged Iron Anvil

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4281]
### Game Version

1.20pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

First (low) - If another player try to assembly anvil it not render top part for others.
Secend (criticle) - Iron anvil refuses to assembly.

### How to reproduce

Try to assembly two parts of Iron anvil

### Screenshots

https://github.com/user-attachments/assets/88189b9b-0af0-401c-9125-2cf745f167bf

https://github.com/user-attachments/assets/43624f87-d8e7-400b-a2cb-b5ff1ca7e99e

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of #3746

**Comment by DejFidOFF** [comment]
It´s not duplicated since this is in new version? I saw that thread, but I guess that was solved in 1.19.8

**Comment by Craluminum2413** [comment]
@DejFidOFF Doesn't matter which version
