### ISSUE TITLE
Various Clutter Issues

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4282]
### Game Version

v1.20.0 pre-5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

1. Bottom of metal table (tablecloth) is invisible from beneath.
2. Metal wiring on various metal clutter is transparent.

### Screenshots

![2024-10-11_15-49-12](https://github.com/user-attachments/assets/1af05308-74a8-4fec-a51f-057c018fbeb8)
![2024-10-11_15-49-19](https://github.com/user-attachments/assets/e971f890-4387-48f2-9174-dd444679d4fe)

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next pre
