### ISSUE TITLE
1.20-pre5 : Terra preta still generated

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#4284]
### Game Version

v1.20 pre5

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Still possible to find terra preta in a 1.20 pre 5 generated world. Probably because it is in a ruin. The ruin name is `agricultural-main-city/elevated-farmland1.json`.

### Screenshots

![2024-10-11_21-41-56](https://github.com/user-attachments/assets/b676c224-284d-4fcc-8f51-67f1f7fd7dc7)

**Comment by RedramVS** [comment]
Insofar as terra preta irl is made by people, it makes sense for this to appear in ruins (as opposed to randomly in the wild).  This is working as intended.
