### ISSUE TITLE
Player animation goes crazy with low framerate

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#4285]
### Game Version

1.20-pre.5, 1.20-pre.7

### Platform

Linux, Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

[crazyhands.webm](https://github.com/user-attachments/assets/51f2322b-7b39-4857-bca4-347606f0979a)

### How to reproduce

1. Set quality preset to high (on a computer where this setting results in low framerate?)
2. Open Vintage Story and enter a world

### Logs

```Log```

**Comment by sekelsta** [comment]
Fixed by reinstall.

**Comment by sekelsta** [comment]
This started happening again pretty often with pre 7. Seems to be framerate related. Was happening with High quality preset, I changed that to Medium and it only happened while looking at water, then changed it to Low and it stopped happening.
With the default settings, this happens on about 3/4 of worlds.

**Comment by sekelsta** [comment]
Now occurs both with and without the second monitor plugged in.

**Comment by sekelsta** [comment]
Also seeing this on Windows on pre 7 with quality preset High.

**Comment by Craluminum2413** [comment]
Fixed in pre.10
