### ISSUE TITLE
Random tabbing out

### ISSUE THREAD

**Issue by DonCinnamon** [anegostudios/VintageStory-Issues#4290]
### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Whenever I play the game, it randomly unlocks my mouse and to get back into the normal mode I have to click. I rebinded the unlock mouse key, so it isn't that.

### How to reproduce

1 Load into mulitplayer 2 play

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What game version? How to reproduce it exactly?

**Comment by DonCinnamon** [comment]
1.19.8 and it seems to happen randomly

**Comment by DonCinnamon** [comment]
Restarted computer and it fixed itself
