### ISSUE TITLE
Mediterranean cypress sapling in planter have pine sapling graphic.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4291]
### Game Version

v1.20 pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Mediterranean cypress sapling in planter have pine sapling graphic.

### How to reproduce

Just plant these 2 trees in planter next to each other.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 10 12 - 17 26 16 42" src="https://github.com/user-attachments/assets/61e61608-b752-4533-9ebe-cb9ff1e207db">

### Logs

```Log```

**Comment by RedramVS** [comment]
Should be fixed next pre
