### ISSUE TITLE
Resonator animation is glitched.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4298]
### Game Version

v1.20 pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Resonator animation is glitched.

### How to reproduce

1. Turn on Resonator and check how it work. Check video.

### Screenshots

https://github.com/user-attachments/assets/6a329b76-b9db-443b-8015-ed69f067d766

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Tyron said it will be fixed in pre.7
