### ISSUE TITLE
Hand Baskets do not add inventory space

### ISSUE THREAD

**Issue by RaKlavinGNS** [anegostudios/VintageStory-Issues#4299]
### Game Version

1.20 pre 5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Crafted hand baskets, placed directly into backpack spots, nothing immediately showed, closed crafting, opened it, still no new inventory space. Save & Leave world, return, nothing changes. 

The install for 1.20 pre 5 was done without deleting the OG game set in 1.19.8

### How to reproduce

1. create hand basket using 10 cattails
2. add to backpack slot
3. no new inventory created

### Screenshots

![2024-10-13_00-39-26](https://github.com/user-attachments/assets/48c52f08-1cd2-4379-a35e-41b23ea4f78b)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Reinstall the game

**Comment by RaKlavinGNS** [comment]
I'd thought about that, but figured since I won't be the only one ever who would install 1.20 without first deleting 1.19 that this could be an issue with a conflict somewhere.

ty for your time though.
