### ISSUE TITLE
New Enemy Small Z-Fighting Issue

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4304]
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

There is a tiny Z-fighting issue I have noticed on the new enemy. Might be more I have not noticed yet.

### Screenshots

![zfight](https://github.com/user-attachments/assets/e0cbf6dc-59bf-404a-b8de-4c01332f7721)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed next pre
