### ISSUE TITLE
Malefactor Cloak Permanent Hole

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4305]
### Game Version

v1.20.0 pre-5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

This is a strange one to describe, but this one specific pixel of the Malefactor Cloak will show your character's skin colour even if what you are wearing underneath should not be showing your character's skin colour there. In the provided images, I am wearing a rotwalker coat underneath, which should not let me see my skin colour in that pixel.

### Screenshots

![cloak1](https://github.com/user-attachments/assets/12e580dd-c849-47b4-b21f-be58b4603ee3)
![cloak2](https://github.com/user-attachments/assets/3257e2c8-9dcd-44d5-9cc1-02af37622a74)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed next pre
