### ISSUE TITLE
Barber Surgeon Hand Wraps Turning Coat Sleeves Transparent

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4306]
### Game Version

v1.20.0 pre-5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Barber surgeon hand wraps will make coat sleeves transparent.

### Screenshots

![wrap](https://github.com/user-attachments/assets/15842f9d-a853-4020-bd68-8cc7df9fc9d9)

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed next pre
