### ISSUE TITLE
Leather Leg Armour Z-Fighting With Boots

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4308]
### Game Version

v1.20.0 pre-6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Leather leg armour Z-fights with boots, eg Malefactor wrapped boots.

### Logs

```Log```

**Comment by RedramVS** [comment]
This has a been a problem for some time with a lot of (maybe most) footwear.   I have gone through and modified as many as I could find to work with leather leg armor, and not clip.  I'll close this issue, but let me know if you find more after next rc.

**Comment by ifozz** [comment]
> [RedramVS](/RedramVS)

Thank you! I have noticed that this has fixed it for seemingly all normal footware! :D
The exceptions are the Nadiyan footware, which still clip through armour.
