### ISSUE TITLE
Burned Out Torches have a tooltip for lighting them but they cannot be lit

### ISSUE THREAD

**Issue by McFrugal** [anegostudios/VintageStory-Issues#4312]
### Game Version

1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When a placed torch burns out, and you target it, it shows a tooltip of shift right click (with a torch) to "ignite" but burned out torches cannot be lit, only broken.

### How to reproduce

Place a torch, wait until it burns out, target it.

### Logs

```Log```

**Comment by RedramVS** [comment]
This is not actually resolvable in the json, but Tyron says it should be fixed next pre
