### ISSUE TITLE
Cooked fish has less saturation than raw fish

### ISSUE THREAD

**Issue by McFrugal** [anegostudios/VintageStory-Issues#4313]
### Game Version

1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Raw fish has 220 satiation, cooked fish has 200.  Cooking wild fish is necessary to kill parasites, so this doesn't really make sense.

### Logs

```Log```

**Comment by RedramVS** [comment]
raw fish satiation will be reduced to 100 in next pre
