### ISSUE TITLE
Can't place four fired cooking pots in the same block anymore in pre 6

### ISSUE THREAD

**Issue by ejzzje** [anegostudios/VintageStory-Issues#4317]
### Game Version

1.20 pre6

### Platform

None

### Modded

None

### SP/MP

Singleplayer

### Description

In previous versions, by aiming at the corner of a block you could place a fired cooking pot on the ground at that corner and a total of four on the block surface. In pre 6 this no longer works and aiming at the corner places the pot in the center of the block face.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Will be fixed in pre.7
