### ISSUE TITLE
1.20pre6 No recipe for Cupronickel ingot

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4320]
### Game Version

1.20pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Placed hot cupronickel on anvil do not nothing. No pop up recipe.

### How to reproduce

Place hot cupronickel on anvil

### Logs

```Log```

**Comment by Craluminum2413** [comment]
It should be hot
