### ISSUE TITLE
MacBook Pro M1 MacOS Sequoia - Everything has a blue-ish tint (incorrect colors)

### ISSUE THREAD

**Issue by Matrix-aas** [anegostudios/VintageStory-Issues#4327]
### Game Version

v1.20 pre6

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The game starts and works fine, but the colors inside the game world are "inverted", the blocks are blue.
Also, when I hover over any block, the entire in-game interface disappears completely (became invisible, including the ESC pause menu).

### How to reproduce

1) Launch the game

2) Get upset by what you see

3) Touch all the settings and realize that nothing can be changed

### Screenshots

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/bfa9bda2-5a46-413c-9de3-31f93084bc92">

<img width="1525" alt="image" src="https://github.com/user-attachments/assets/80395210-8559-4210-8a38-cf8b22372a4f">

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/ecd88bec-6462-4c1a-908d-3a758bdee134">

**Comment by Matrix-aas** [comment]
This issue was previously known in Minecraft. Red and Blue colors flipped on Mac M1 (M-Silicone).

https://github.com/PrismLauncher/PrismLauncher/issues/698

https://www.reddit.com/r/GoldenAgeMinecraft/comments/zjki8k/beta_173_red_and_blue_colors_flipped_on_mac_m1/

**Comment by perkthefox** [comment]
Same problem for me

**Comment by Matrix-aas** [comment]
(In version 1.20.0-pre.7 the bug is still present)

**Comment by Matrix-aas** [comment]
The fix I found in the Minecraft patch is:

```
if (GL11.glGetString(GL11.GL_RENDERER).contains("Apple M")) {
    GL11.glEnable(GL30.GL_FRAMEBUFFER_SRGB);
}
```

Maybe if this helps the devs can add it for VS too?

**Comment by Hibagon74** [comment]
I'm running a 2019 MacBook Pro with Intel processor and am seeing this as well.

**Comment by Skamandrios42** [comment]
This is still a problem in 1.20.0-rc1, I am using a MacBook Air (2022 m2, Ventura 13.6.7). The color inversion is also present in the welcome screen on start up of the game.

**Comment by Th3Dilli** [comment]
thank you, we figured out the issue

and fixed the blue tint and the bright colors caused by the srgb fix, you can find .dll to replace for rc.1 in [discord](https://discord.com/channels/302152934249070593/1287144582261375102)

or wait till we release rc.2

**Comment by Eyelikegiants** [comment]
I just used .vrec toggle for the first time and the whole video is blue tinted like this! My game isn't at all. I'm on 12.20.12. 

Any solution to this? (Other than screen rec)
