### ISSUE TITLE
Sulfuric Acid Bugs

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4333]
### Game Version

v1.20.0pre6

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Sulfuric acid recipe (x6) results in "6 portions of unknown" in the cooking pot.  The result can ONLY be scooped out using a bowl or a crock, but otherwise cannot be removed.  Once in a crock it can only be removed to a bowl.  Once in a bowl, the bowl cannot be poured into any liquid storage (jug, barrel, nor bucket).
If I transfer the cooking pot with the 6 portions of unknown to the fireplace input slot, it turns into 60ml of sulfuric acid, but I cannot make chromium sulfate because the 60ml of acid is stuck in the first slot, and I need 2 slots of acid to make it.

### How to reproduce

Follow the recipe to make sulfuric acid.  The resulting acid does not work or allow you to save it up since it acts like a meal.

### Screenshots

![20241019_173103](https://github.com/user-attachments/assets/e96e629a-b389-48d2-9906-c132f8075e16)
![20241019_173115](https://github.com/user-attachments/assets/26448d3c-2f8b-415d-b5bc-bf6ce2e5af97)

### Logs

```Log```

**Comment by RedramVS** [comment]
Yes, currently the new recipes involving the dirty pot don't work at an optimal level.  We're awaiting some improvements to the dirty pot code to, among other things, allow output of multiple items per recipe.  Flint calcining will also probably be moved to a dirty pot recipe once this happens (possibly lime cooking as well).

**Comment by Bughaw** [comment]
Still present in pre7.  I appreciate the team's work on this excellent game!

**Comment by DejFidOFF** [comment]
Hey guys, Dana o/ And by the way do someone do a math? The insane amount of resources to make one sturdy leather backpack? Exactly 6000 peaces of sulfure chunks for one backpack is out of this world... From 6l water + 10 powdered sulfur + 5 saltpeter = 0,05l sulfure acid. For 1 portion of chromium sulfate needs 2l of sulfuric acid + 2 crushed chromite. for 1 sturdy leather = 3 portion + hide....

**Comment by Pbprovost** [comment]
Pretty sure it's supposed to be yielding 1L of acid and then 1L of chromium sulfate, not 0.01L. If you change the items code to not have the items per liter 100 thing it yields appropriately. The recipe has dirtypotoutputquantity 100, which probably supposed to make it yield 100 "items" of the product, which would be 1L. It just doesn't work yet.

**Comment by Craluminum2413** [comment]
Does it happen for anyone in pre.10?

**Comment by Bughaw** [comment]
In pre10, the output of the sulfuric acid recipe no longer comes out as unknown.  But the amount is only 60ml of sulfuric acid still, and there is no way to remove it from the cooking pot without a mod, so there is no way to save any up or to prepare the chromium sulfate recipe yet.

**Comment by Pbprovost** [comment]
Looks like this is fixed in pre.11.

**Comment by Bughaw** [comment]
Yes.  It is fixed in pre11.  Thank you!
