### ISSUE TITLE
Skin 16 change colors of eyes from white to grey.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4340]
### Game Version

v1.20 pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Skin 16 change colors of eyes from white to grey in character creation menu.

### How to reproduce

During character creation check how eyes look in skin 16 and other skins.

### Screenshots

<img width="285" alt="Vintagestory Screenshot 2024 10 20 - 16 16 56 12" src="https://github.com/user-attachments/assets/04cb8a2f-f620-4d85-8afe-6b2a55f59376">
<img width="285" alt="Vintagestory Screenshot 2024 10 20 - 16 16 53 38" src="https://github.com/user-attachments/assets/c91114f4-9aed-4c0e-b7f3-0b29ad983234">

### Logs

```Log```

**Comment by RedramVS** [comment]
This should be fixed next pre
