### ISSUE TITLE
When you deconstruct boat with animals they will bugged.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4342]
### Game Version

v1.20 pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When you deconstruct boat with animals they will bugged in air like on videon also when I first time tested what will happend when I will do it elk just died like on secound video but I couldn't do it again.

### How to reproduce

Just destroy boat with animals on board with saw.

### Screenshots

https://github.com/user-attachments/assets/cb1c136d-3662-414a-b1c0-7fa7bd84c8f0

<img width="1280" alt="Vintagestory Screenshot 2024 10 21 - 01 42 42 21" src="https://github.com/user-attachments/assets/ca6863a3-b92b-4cd6-a393-0909d9750ca9">

https://github.com/user-attachments/assets/9d026c7b-a293-40a4-9ffc-e778895a116d

### Logs

```Log```

**Comment by CookieBoy21** [comment]
Ah okay elk will die when you will start deconstruct boat by aiming him and still pressing mouse key.

https://github.com/user-attachments/assets/f7383a8c-a59a-40ec-bb98-98249f8bc71d

**Comment by maltiez2** [comment]
Will be fixed in next update
