### ISSUE TITLE
Ground Does Not Load

### ISSUE THREAD

**Issue by UnorthoTox** [anegostudios/VintageStory-Issues#4343]
### Game Version
1.19.8

### Platform

Windows 10

### Modded

Yes 

### SP/MP

SP

### Description

When I create a new world and complete my character setup, I proceed to freefall to my death due to there being no terrain whatsoever. The same issue happens on existing worlds where there's a whole chunk missing, and I can fall down it instead of an invisible wall stopping me. Most of the other loaded chunks in my existing worlds are fine, but I'm not even able to play in new worlds I create.

### How to reproduce

1. Create a new world; it doesn't matter what features are customized or chosen.
2. Wait for the world to spawn you in and proceed to create your character.
3. The terrain noticeably never loads in regardless of how much time has passed and lets you fall into the void.

### Screenshots

![Issue Log](https://github.com/user-attachments/assets/b48f9dd3-8ac6-4950-9908-ac82482b2d58)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What mods are installed?

**Comment by UnorthoTox** [comment]
A Culinary Artillery, Clumps, Expanded Foods, HUD Clock, Kobold Player
Model, Mobs Radar, Primitive Survival, Rivers and Tree Tapper

**Comment by Craluminum2413** [comment]
@UnorthoTox Try without mods, some worldgen mods like "Rivers", for example, can break worlds
