### ISSUE TITLE
Various Saddle Blankets Z-Fighting and Missing Geometry

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4348]
### Game Version

v1.20.0 pre-6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

[EDIT: Various saddle blankets are affected by this.]
The survivor saddle blanket is missing parts of it's geometry and is also Z-fighting, perhaps because of this.

### Screenshots

![blanket](https://github.com/user-attachments/assets/b13474aa-2116-4a2e-b9f0-d1ca0c55d5ca)
![blanket2](https://github.com/user-attachments/assets/3e531411-6a66-469e-9ecd-9439cc3b097a)

### Logs

```Log```

**Comment by ifozz** [comment]
This also happens on the:
-Azure embroidered saddle blanket
-Embroidered green saddle blanket
-Squire Saddle Blanket
-Merchant Saddle Blanket
-Rotten King Saddle Blanket

**Comment by ifozz** [comment]
I have discovered the cause of this is the affected blankets being one pixel smaller around the border than the other blankets.

**Comment by RedramVS** [comment]
There are some other issues with saddle blanket textures and model that will need fixing, but these texture gaps will be expanded to fill those spots next pre.
