### ISSUE TITLE
Able to deconstruct raft into sailboat resources

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#4352]
### Game Version

v1.20.0-pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Can deconstruct raft the same way as sailboat and get exactly the same resources back.

To fix, set **deconstructible** to **false** and **deconstructDrops** to **null** for raft
or
set proper **deconstructDrops** for raft, like logs and ropes

### How to reproduce

1. Place a raft
2. Use saw on raft (the same way as when descontructing sailboat)
3. You get sailboat resources back

**Comment by RedramVS** [comment]
Should be fixed next pre
