### ISSUE TITLE
Ingot mold is missing "shatter when get wet" description

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#4355]
### Game Version

v1.20.0-pre,7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

All burned molds except ingot mold has description that says it shatters when gets wet

### How to reproduce

1. Open ingot mold in handbook

### Screenshots

Ingot mold
![image](https://github.com/user-attachments/assets/d1bd660d-94b7-4c64-97a2-5d968ddcda5b)

Anvil mold as example
![image](https://github.com/user-attachments/assets/156a2326-1690-487f-8137-642a61a908fe)

**Comment by Craluminum2413** [comment]
To fix, add this to en.json
```json
"block-handbooktext-ingotmold-burned-*": "description"
```

**Comment by RedramVS** [comment]
should be fixed next pre
