### ISSUE TITLE
In v1.20 pre7 oboe voice sounds different.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4358]
### Game Version

v1.20 pre7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Oboe sounds different in v1.20 pre6 and v1.20 pre7. On video you can see that I didn't even change voice settings.

### How to reproduce

Check how oboe sounds in v1.20 pre6 and v1.20 pre7.

### Screenshots

v1.20 pre6

https://github.com/user-attachments/assets/3e9aeb2f-e3bd-441c-9475-716591e0103f

v1.20 pre7

https://github.com/user-attachments/assets/2c2c603c-dbb3-49a5-8813-bae265ed2c48

### Logs

```Log```

**Comment by ifozz** [comment]
All the voices sound different.
They're all pitched much higher than usual.

**Comment by RedramVS** [comment]
Changes were made to the sound system, for behavior purposes I believe.  Not sure if this is json-fixable.

**Comment by melodelic** [comment]
Yep, I was about to make a complaint about this as well. The voices are so shrill that I cannot play for more than a few minutes or I will risk giving myself a migraine. The voices are absolutely way too shrill in 1.20 pre-7.

**Comment by CookieBoy21** [comment]
Fixed in pre.8
