### ISSUE TITLE
I cannot load INTO the game at all

### ISSUE THREAD

**Issue by bananamanthe1** [anegostudios/VintageStory-Issues#4362]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

it crashes everytime it loads

### How to reproduce

play the game

### Screenshots

![image](https://github.com/user-attachments/assets/7790f19c-e9d1-4af5-9608-2e98d11c06d3)

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16233 MB RAM
Game Version: v1.19.8 (Stable)
10/23/2024 7:46:49 PM: Critical error occurred
Loaded Mods: 
System.IO.FileNotFoundException: Could not load file or assembly 'OpenTK.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'OpenTK.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/23/2024 6:19:28 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4249, time stamp: 0x0cf64c6a
Exception code: 0xe0434352
Fault offset: 0x000000000005fe4c
Faulting process id: 0x0x6a50
Faulting application start time: 0x0x1db25a200e5d896
Faulting application path: C:\Users\LaneC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: beab5c71-3ee5-4ce0-814b-573507b49747
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/23/2024 6:19:25 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4249, time stamp: 0x0cf64c6a
Exception code: 0xe0434352
Fault offset: 0x000000000005fe4c
Faulting process id: 0x0x8a0
Faulting application start time: 0x0x1db25a1fed1b765
Faulting application path: C:\Users\LaneC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 64d84fab-ac42-438e-b6e9-f5feef527ae3
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/23/2024 6:17:48 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4249, time stamp: 0x0cf64c6a
Exception code: 0xe0434352
Fault offset: 0x000000000005fe4c
Faulting process id: 0x0x6548
Faulting application start time: 0x0x1db25a1c5da66f2
Faulting application path: C:\Users\LaneC\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c7a23259-65e7-468b-be55-c6ea50f8678e
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment]
Reinstall the game
