### ISSUE TITLE
Quarter log corner textures are misaligned

### ISSUE THREAD

**Issue by ejzzje** [anegostudios/VintageStory-Issues#4363]
### Game Version

1.20 pre7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The northwest and northeast quarter log corner textures are misaligned. It's easier to see on the debarked versions but present in the versions with bark as well.

### Screenshots

![quarter logs](https://github.com/user-attachments/assets/e6ad6a2b-27bc-49d9-b3bc-ace0367fa402)

### Logs

```Log```

**Comment by RedramVS** [comment]
Looks fine for me.  Can anyone else reproduce?

**Comment by Craluminum2413** [comment]
@RedramVS place north and south, or west and east

**Comment by RedramVS** [comment]
Ah I see.  Thanks.

**Comment by RedramVS** [comment]
Should be fixed next pre
