### ISSUE TITLE
Forced Transparent Pixels on Clothing in Regards to New Glove Placement

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4365]
### Game Version

v1.20.0 pre-7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

There are certain transparent pixels on clothing (such as this tattered linen shirt) that force gloves to also have transparent pixels when worn together.

### Screenshots

![2024-10-24_13-36-45](https://github.com/user-attachments/assets/da71fd44-56ed-48c4-9670-49d69cd0fee7)
![2024-10-24_13-36-50](https://github.com/user-attachments/assets/cc5a5549-9461-4f92-982c-7732067ef51d)

### Logs

```Log```

**Comment by RedramVS** [comment]
Tattered shirt will be fixed next pre

**Comment by ifozz** [comment]
> Tattered shirt will be fixed next pre

Just discovered this happens on the prince tunic, too. :)
