### ISSUE TITLE
Thunderlord painting is broken for south and west variants

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#4374]
### Game Version

v1.20.0-pre.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

How to fix:
```cs
"@painting-(thunderlord)-.*": [
	{ name: "HorizontalAttachable" }, 
	{ name: "Multiblock", propertiesByType: {
			"*-north": { sizex: 1, sizey: 2, sizez: 1, cposition: { x: 0, y: 0, z: 0 } },
			"*-east": { sizex: 1, sizey: 2, sizez: 1, cposition: { x: 0, y: 0, z: 0 } },
			"*-south": { sizex: 1, sizey: 2, sizez: 1, cposition: { x: 0, y: 0, z: 0 } },
			"*-west": { sizex: 1, sizey: 2, sizez: 1, cposition: { x: 0, y: 0, z: 0 } } 
		}
	} 
],
```

It should be `x: 0, y: 0, z: 0` everywhere, not 1 or 2, just 0

### How to reproduce

1. Get thunderlord painting
2. Place west and south variants
3. Target upper half
4. There is NO collision, it is somewhere on the side

**Comment by RedramVS** [comment]
All four directions look fine to me.    Can anyone else reproduce?

**Comment by Craluminum2413** [comment]
> All four directions look fine to me. Can anyone else reproduce?

Look at both blocks of the painting, not only one

**Comment by Craluminum2413** [comment]
@RedramVS 
https://github.com/user-attachments/assets/9586e360-6404-43ae-b0eb-d1b80ca50e86

**Comment by Craluminum2413** [comment]
Issue is very annoying because it makes painting work as 2x2 multiblock

**Comment by RedramVS** [comment]
I gotcha, thanks.  Should be fixed next pre.
