### ISSUE TITLE
Survivor Boots Texturing/Rendering Issue

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4377]
### Game Version

v1.20.0 pre-7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The 3D patches of the Survivor Boots will sometimes change texture to seemingly random textures.
In the provided image, they seem to have a birch wood type texture, though I have also seen them have a jailor tunic orange texture and a different blue texture akin to lapis.

This seems to happen if you are wearing the Survivor boots, then replace them with a different pair of boots, and then put the Survivor boots back on again.

### How to reproduce

1. Wear Survivor Boots
2. Replace them with other boots
3. Put Survivor Boots on again

This bug is a bit fickle and can be tricky to reproduce, since sometimes nothing will happen.
I'd suggest taking a look at their model to see if any issues can be spotted there. :)
### Screenshots

![2024-10-27_12-38-11](https://github.com/user-attachments/assets/5c95abdf-e30c-439c-a848-4bb61b8443b2)

### Logs

```Log```

**Comment by RedramVS** [comment]
Removed the extra patch cuboids.  Hopefully should be fixed next pre.
