### ISSUE TITLE
Certain Clothing Missing Buttons/Seams

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4378]
### Game Version

v1.20.0 pre-7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Certain 3D buttons and seams have been removed from clothing when the texture layout changed in 1.20.

The affected items I have found so far are:
-Minstrel shirt
-Squire tunic
-Temptress velvet shirt

### Screenshots

![2024-10-27_12-47-09](https://github.com/user-attachments/assets/6874b6df-c0e4-460c-a657-0c9fa2a927c9)
![2024-10-27_12-47-15](https://github.com/user-attachments/assets/a119a507-79dd-40f3-be98-0eb2053aa186)
![2024-10-27_12-47-22](https://github.com/user-attachments/assets/3edfeefc-fc0c-41d8-b76b-31c39b8c6a39)

### Logs

```Log```

**Comment by RedramVS** [comment]
Prince shirt was also missing buttons.  All four should be fixed next pre.  Let us know if you notice any more.
