### ISSUE TITLE
Saddle Blankets on Elk are Off by One Pixel

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4388]
### Game Version

v1.20.0 pre-7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Seemingly every saddle blanket (except maybe forlorn hope) is off by one pixel on the elk - one side has one less row of pixels.
This also means one side will have "stretched" pixels or the border pixels while the other side will not - as only one side has this extra row.

### Screenshots

![2024-10-28_17-35-28](https://github.com/user-attachments/assets/c898c3f9-dad4-41b6-a6f1-27fbb873b3c2)
![2024-10-28_17-35-31](https://github.com/user-attachments/assets/579a9024-5ee1-4a48-8bb2-3b68e6f4b183)

### Logs

```Log```

**Comment by ifozz** [comment]
This also seemingly does not apply to the alchemist saddle blanket, either.

**Comment by RedramVS** [comment]
Should be fixed next pre
