### ISSUE TITLE
v1.19.8 Visual bug with keybinds displacement in the guidebook

### ISSUE THREAD

**Issue by bonenaut7** [anegostudios/VintageStory-Issues#4390]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

While I was translating mods, I'm found out that in some case, keybinds with long localized names has weird displacement, and cover some text in the next line(Look at the screenshot section)

### How to reproduce

1. Set russian language for the game
2. Set interface size to 8 units
2. Create a guide (like the Metal Casting one) and use [text from the link(pastebin)](https://pastebin.com/9mtAXzZH) with text from the screenshot (Used as description of a survival mechanic in public mod)
3. Open guide and look closer to the end of description

### Screenshots

![image](https://github.com/user-attachments/assets/36407a7b-effd-4b9a-a479-837a6c76d0d9)

### Logs

*Client log doesn't contain any warnings or errors*

**Comment by Craluminum2413** [comment]
Would be nice if anyone tried to reproduce it in 1.20

**Comment by bonenaut7** [comment]
@Craluminum2413 issue is present on the latest available 1.20.0-pre7 version of the game (downloaded and tested it right now)
![image](https://github.com/user-attachments/assets/6c79e2a8-276f-442e-9ea6-71b8b8e9d752)
