### ISSUE TITLE
Reversing all world changes on exiting and re-entering the game

### ISSUE THREAD

**Issue by ChickenSquatch** [anegostudios/VintageStory-Issues#440]
Game Version: 1.12.6
Platform: Windows
Modded: No 

After the update which fixed the game crashing on startup, every time I exit the game world and re-enter it, it reverses everything i did. deletes every item placed in the world and moves everything back to how it was when it generated... making it effectively impossible to play. it spawned me where it should and i kept my inventory contents, but every place or moved object was remove or reset. trees i planted, structures i built, it even put some ruins i broke back together.

### How to reproduce
1. Start new world, do anything, save and exit to main menu, re-load the same save.

### Expected behavior
I think it's quite obvious what should have happened. all of my progress should have been saved, the game world should remember what's been done in it.

### Logs
```
No crash, just a super major bug rendering the game unplayable.
```

**Comment by copygirl** [comment]
> No crash, just a super major bug rendering the game unplayable.

Please upload your `server-main.txt`. There likely still in an error being logged when the game tries to save. And, ideally, also upload your world file. (Tyron keeps recommending WeTransfer for that, so I will too.)

The data folder for the game is in AppData. Logs are in `Logs/`, world files are in `Saves/`. One of the easier ways to get to it would be to go to the main menu, then *Mod Manager* and clicking *Open Mods Folder*. From there just go one folder up.

**Comment by copygirl** [comment]
Announcement on Discord:

> **Tyron:** We've discovered a rather severe issue related to savegames. Please do not customize your world size to be above 1mil by 1mil blocks. There is a number overflow bug that will make it so that chunks are never properly saved, i.e. all progress will be lost. Any world size until 1million by 1 million is fine however. Will disable those extra sizes asap.

Is this what you did in your world, also?

**Comment by tyronx** [comment]
no response in over 2 weeks, i think we can close this

**Comment by ChickenSquatch** [comment]
Yes, sorry. It was the bug from the expanded world size, the patch fixed it.
