### ISSUE TITLE
Blackguard Shirt Lacks One Row of Side Pixels on Legs

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4404]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Both sides of the Blackguard shirt have missing rows of pixels along the sides of the legs.

### Screenshots

![shirt](https://github.com/user-attachments/assets/0942f67d-8e50-43a8-822b-c6671dfe1c56)

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next pre
