### ISSUE TITLE
Aged Armour Stands Generating in Only One Orientation

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4406]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Aged armour stands in ruins will only generate facing one direction, as opposed to facing the direction the ruin generated in.

### Screenshots

![2024-10-31_11-47-53](https://github.com/user-attachments/assets/198cd977-e18a-4849-a73a-d4509c2891ba)
In this image, you can see the aged armour stand is facing the wall instead of facing forward like it should be.
Sometimes, depending on how the ruin it is inside generates, it will be facing forward, since it only faces one orientation.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
I'm sure this is json fix because you only need to replace them in schematics once

**Comment by Craluminum2413** [comment]
Fixed in pre.10
