### ISSUE TITLE
Stone Paths/Slabs/Stairs are not reinforceable

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#4412]
### Game Version

Any

### Platform

None

### Modded

None

### SP/MP

None

### Description

Stone Paths/Slabs/Stairs are not reinforceable as while almost all blocks are. This looks like an oversight more than a team decision.

While it makes sense for blocks affected by gravity (sand, gravel), stone paths are not. They should be reinforceable.

### How to reproduce

1. Place Stone paths
2. Get stone and plumb & square
3. Try to reinforce the paths.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
To fix:
Add this to attributes
```json
"reinforcable": true,
```

**Comment by RedramVS** [comment]
should be added next pre
