### ISSUE TITLE
Merchant Shirt has Asymmetrical Row of Pixels

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4414]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The merchant shirt has this row of green pixels on one side that is not on the other.

### Screenshots

![2024-11-02_10-46-05](https://github.com/user-attachments/assets/8fce9471-59c6-44ce-b5ee-8ef0cc46b7b8)
![2024-11-02_10-46-08](https://github.com/user-attachments/assets/34b66d2a-01f6-4fe9-90bc-10a63482d00e)

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next pre
