### ISSUE TITLE
Sturdy Belt is Missing Geometry in Some Places

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4415]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The sturdy belt is missing some faces on it's model.

### Screenshots

![2024-11-02_10-51-46](https://github.com/user-attachments/assets/56ace965-4302-4aa9-a565-7e562e4fbcc4)
Viewed from behind, part of the back is missing faces.

![2024-11-02_10-52-01](https://github.com/user-attachments/assets/db81aa0d-3895-4a71-85c6-7389bed7031d)
Viewed from the front, part of the buckle is missing faces.

![2024-11-02_10-51-52](https://github.com/user-attachments/assets/2e27f97d-10ce-4819-8ec6-2d4131701c3c)
Thought I'd put it here that the texturing on the back looks a little odd in general, though I do not know if this counts as a bug.

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next pre
