### ISSUE TITLE
Blue Plaid Blanket and Azure Embordered Blanket Share the Same Recipe

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4417]
### Game Version

v1.20.0 pre-9

### Platform

None

### Modded

None

### SP/MP

None

### Description

The blue plaid saddle blanket and the azure embroidered saddle blanket have the exact same crafting recipe as each other.

### Logs

```Log```

**Comment by RedramVS** [comment]
Should be fixed next pre
