### ISSUE TITLE
Schematic C (Bloody) does Not Give Lore Entry

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4418]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The tapestry "Schematic C (bloody)" does not give a lore entry. Instead, it gives you a journal entry that simple says "tapestrylore-schematic-c-bloody"

This has not happened with any other tapestries I have seen in pre-9, but I think that they should all probably be taken a look at just to make sure, as I cannot reliably get them to test them all.

### Screenshots

![2024-11-02_13-34-10](https://github.com/user-attachments/assets/572e35af-a9bc-4e37-866a-448e967be172)

### Logs

```Log```

**Comment by Waterspark63** [comment]
This still happens in 1.20.0-RC.4, will be on RC5 later today, and will edit if it happens on RC.5 as well.

**Comment by tyronx** [comment]
thanks for the report, will be fixed in rc6
