### ISSUE TITLE
Marketeer cape and litham combo removes facial hair and litham

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4419]
### Game Version

1.20.0-pre.9

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

When using the Marketeer litham it correctly hides all facial hair.
When using the Marketeer cape it correctly shows most facial hair (not long hair down the backside).

But:

When using both the litham and cape all facial hair AND the litham are hidden.

This problem also occurs when using other capes that includes a hood.

### Screenshots

No cape or litham:
![Screenshot from 2024-11-02 11-21-59](https://github.com/user-attachments/assets/55f678e9-03c6-4598-8090-223baa475c64)

Only litham:
![Screenshot from 2024-11-02 11-22-51](https://github.com/user-attachments/assets/390c809f-cd6d-435a-87e8-f87aa84b20fa)

Only cape:
![Screenshot from 2024-11-02 11-23-57](https://github.com/user-attachments/assets/491b9aed-be2c-4097-8177-6a3398ad0b5a)

Both litham and cape:
![Screenshot from 2024-11-02 11-24-31](https://github.com/user-attachments/assets/249aebe3-ad5f-40fd-a5fc-29ec017b96a4)

Litham and other capes.
![Screenshot from 2024-11-02 11-25-05](https://github.com/user-attachments/assets/8dd4ef88-c13b-4e0e-a5c4-b72c05a2d42f)
![Screenshot from 2024-11-02 11-25-51](https://github.com/user-attachments/assets/15514f30-7dd3-4e63-b4b6-416f7bfcf0be)
![Screenshot from 2024-11-02 11-26-00](https://github.com/user-attachments/assets/f9191097-9b43-4a62-8282-e4a00fec743a)

### Logs

```Log```

**Comment by tannyl** [comment]
A side note: The litham is actually only a mouth-vail, yet in game it covers both mount and head.
Instead I belive it should be called a [**tagelmust**](https://en.wikipedia.org/wiki/Litham#Tagelmust_or_Afrwal_or_litham)

**Comment by RedramVS** [comment]
The layer hiding should be fixed next pre.  I'll mention the name thing to the story team.  That part may or may not change.

**Comment by RedramVS** [comment]
Luke says he did research on this when naming it, and sources are inconsistent.  Ultimately he decided it's as much cultural as anything, and there's not really a significant difference.  So, the name will remain as-is.

**Comment by tannyl** [comment]
Completely fine @RedramVS. Thanks for update about it.  :)
