### ISSUE TITLE
Game crashes when I try to start it.

### ISSUE THREAD

**Issue by YunaAndMagics** [anegostudios/VintageStory-Issues#442]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.4 (Stable)06.03.2020 12:11:04: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _Nm2Dey99KsdwIYLpu4GOdoFloZP._qP4paZogWeAkBAdIetsRHNRsPeR()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._ryUq828Jdon4eHk5toV3WI6D1nH()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._TNhCFDnDMOpUfVxHZgPyWvoTAtF()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._wVES3I4AcneyUTHpdRuLu6EHvCH(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU , String[] )
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(ThreadStart )
-------------------------------

**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by zerrberuss** [comment]
Same Problem:

Running on 64 bit Windows with 40 GB RAM 
Version: v1.12.5 (Stable)06.03.2020 12:34:29: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by Bloodsaw** [comment]
Please update to 1.12.6, this was already fixed.
You can download it from main page.
