### ISSUE TITLE
Skirt preview/thumbnail is offset outside its viewbox

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4420]
### Game Version

1.20.0-pre.9

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

The preview/thumbnail for the skirt `item-clothes-lowerbody-skirt` is offset outside its viewbox. The below image shows it.

### Screenshots

![Screenshot from 2024-11-02 12-24-50](https://github.com/user-attachments/assets/9d01d69f-b411-4165-ae78-d284848ae10b)

### Logs

```Log```

**Comment by RedramVS** [comment]
Should be fixed next pre
