### ISSUE TITLE
Damage log reasons "heal" and "gravity" missing from translation files

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4422]
### Game Version

1.20.0-pre.9

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I am in the process of translating to danish and was translating the damage log entries.

I can't find the **heal** or **gravity** reasons strings in the translation files or on crowdin.

There might also be missing other strings, as I don't know how many reasons there might be.

See screenshot below.

### Screenshots

![Screenshot from 2024-11-02 16-06-04](https://github.com/user-attachments/assets/2fdaa4c4-dc71-49a4-993e-04bda46f9c3a)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
https://github.com/anegostudios/vsapi/blob/310979a89bb1b5659bbf7a651e959e9e9de93bbc/Common/Entity/EntityPlayer.cs#L1309-L1327

**Comment by radfast** [comment]
Fixed in upcoming 1.20-rc.5, thank you @tannyl and @Craluminum2413
