### ISSUE TITLE
Chateau shirt is missing flavor text in-game.

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4428]
### Game Version

1.20.0-pre.9

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The **Chateau blouse** `clothes-upperbody-chateau-blouse` is missing the flavor text (blue text) from its handbook page/info popup.

The text for it is defined in the translations.

### Screenshots

Chateau blouse:
![Screenshot from 2024-11-03 11-44-27](https://github.com/user-attachments/assets/64ea0e70-b9b0-4951-9bfd-446215df35a8)

Compared to its counterpart - Chateau pants:
![Screenshot from 2024-11-03 11-44-39](https://github.com/user-attachments/assets/b93ad3f1-683b-4bf0-b4b2-4100afcdc09b)

### Logs

```Log```

**Comment by RedramVS** [comment]
Should be fixed next pre
