### ISSUE TITLE
Hot water don't hurt player anymore.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4431]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Hot water don't hurt player anymore for some reason.

### How to reproduce

Jump in survival mode to hot water.

### Screenshots

https://github.com/user-attachments/assets/8c30608f-30cf-42f3-a67e-7d51d5b19336

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
