### ISSUE TITLE
Elk don't losing owner after taking medallion.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4440]
### Game Version

v1.20.0 pre-10

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Elk don't losing owner after taking medallion.

### How to reproduce

Just put medallion on elk and after it take medallion from him. You will be still his owner.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 11 05 - 14 55 46 89" src="https://github.com/user-attachments/assets/a1894da7-cdd5-48bc-8304-860036aaa215">

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
