### ISSUE TITLE
Can no longer open elk saddlebags without starting to ride elk

### ISSUE THREAD

**Issue by M3username** [anegostudios/VintageStory-Issues#4442]
### Game Version

v1.20.0-pre.10

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Every time I access the saddlebags of my elk, I also end up hopping into the saddle and start riding it. 
The saddlebag inventory is still accessible and works as intended, I just have to get off the elk again every time.

### How to reproduce

Outfit an elk with saddlebags and access the saddlebag inventory.

**Comment by CookieBoy21** [comment]
Issues was fixed in 1.20-pre.11
