### ISSUE TITLE
In creative mode tamed elk have albino tamed elk icon.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4455]
### Game Version

v1.20.0 pre-11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In creative mode tamed elk have albino tamed elk icon.

### How to reproduce

Open items list in creative mode.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 11 06 - 17 21 29 55" src="https://github.com/user-attachments/assets/35e9abd2-031e-416a-9ad5-3bbce28ba098">

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@CookieBoy21 What is wrong here?

**Comment by Craluminum2413** [comment]
Oh they both have albino texture

**Comment by RedramVS** [comment]
should be fixed next pre
