### ISSUE TITLE
Handbook text on fruit tree cuttings not in translation files

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4457]
### Game Version

1.20.0-pre.11

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

A piece of text on the handbook pages for fruit tree cuttings is not translated, and it missing from the translation files and crowdin.

It is the string `Values are averages, as they can vary sligtly for each tree.`

The string is found here:

                sb.AppendLine("Values are averages, as they can vary slightly for each tree.");

/https://github.com/anegostudios/vssurvivalmod/blob/51c586a3111cdc5c4df5c928b7c158234748c11c/Systems/FruitTree/BlockFruitTreeBranch.cs#L359

### Screenshots

![Screenshot from 2024-11-06 21-02-13](https://github.com/user-attachments/assets/1c0ba986-55c9-4036-8a81-5d3cfeda6436)

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in upcoming 1.20-rc.6:

	"handbook-fruittree-note-averages": "Values are averages, as they can vary slightly for each tree.",
