### ISSUE TITLE
Azure Embroidered Blanket and Reindeer Herder Waistband Have Same Crafting Recipes

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4460]
### Game Version

v1.20.0 pre-11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The azure blanket and the reindeer herder waistband have the same recipes.

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next pre
