### ISSUE TITLE
Can't attach medallion to elk

### ISSUE THREAD

**Issue by gerbilfat** [anegostudios/VintageStory-Issues#4461]
### Game Version

1.20 pre10

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I bought an elk from a trader and crafted a medallion to claim it. I'm unable to attach the medallion to the elk on the medallion spot. 

vanilla 1.20 pre10, SMP

### How to reproduce

1. Buy an elk from a trader
2. Craft a medallion
3. Attempt to attach the medallion to the elk. Nothing happens.

### Logs

```Log```

**Comment by ifozz** [comment]
Are you holding the sprint key (for me it's shift) while right clicking?

**Comment by Craluminum2413** [comment]
There should be tooltip when you target specific part on elk's head
