### ISSUE TITLE
Jam made of pineapple is not using the correct translation

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4463]
### Game Version

1.20.0-pre.11

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Jam made of pineapple is called _Pineapple slices jam_ in the game. But it should actually the name **Pineapple jam**.
The translations files (and crowdin) contains an entry especially for jam made of pineapple slices, but this translation string is not being used.

I looked at the code:
https://github.com/anegostudios/vssurvivalmod/blob/51c586a3111cdc5c4df5c928b7c158234748c11c/Systems/Cooking/CookingRecipe.cs#L235-L238

Based on this line `string jamName = fruits[0].Collectible.LastCodePart() + "-jam";` I expect that it tries to find the translation with the key `pineapple-jam` since the fruit item is called `item-fruit-pineapple`.

But this key is never found in the files, since the string **Pineapple jam** uses the key `pineappleslice-jam`.

### Screenshots

Shows the problem (using danish translations):
![Screenshot from 2024-11-07 17-58-16](https://github.com/user-attachments/assets/45422ef4-8eb9-466c-b29a-55d7b10edc17)

### Logs

```Log```

**Comment by radfast** [comment]
Has now been fixed in 1.20.0-rc.4.  Thank you for reporting
