### ISSUE TITLE
Locust teleporting to you during fight.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4465]
### Game Version

v1.20.0 pre-11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Locust teleporting to you during fight.

### How to reproduce

Just fight with locust.

### Screenshots

https://github.com/user-attachments/assets/386db348-1d79-4705-b60f-40802e415f45

https://github.com/user-attachments/assets/fdc506b3-c231-4b38-b681-64da23d5f0eb

https://github.com/user-attachments/assets/1cb18ddd-644a-4e70-b5f2-890a67f63f43

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Send logs from "\AppData\Roaming\VintagestoryData\Logs"

**Comment by CookieBoy21** [comment]
Which one exactly?
![Zrzut ekranu 2024-11-07 222237](https://github.com/user-attachments/assets/ec90a21c-28cc-4278-af8d-3a387e673a72)

**Comment by Craluminum2413** [comment]
@CookieBoy21 All of them

**Comment by CookieBoy21** [comment]
[client-debug.log](https://github.com/user-attachments/files/17669650/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/17669651/client-main.log)
[server-debug.log](https://github.com/user-attachments/files/17669653/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/17669654/server-main.log)
[server-audit.log](https://github.com/user-attachments/files/17669655/server-audit.log)
[client-chat.log](https://github.com/user-attachments/files/17669656/client-chat.log)
[client-audit.log](https://github.com/user-attachments/files/17669657/client-audit.log)
[server-build.log](https://github.com/user-attachments/files/17669659/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/17669661/server-chat.log)
[client-crash.log](https://github.com/user-attachments/files/17669662/client-crash.log)
[server-worldgen.log](https://github.com/user-attachments/files/17669664/server-worldgen.log)

**Comment by CookieBoy21** [comment]
Fixed in 1.20 pre.13
