### ISSUE TITLE
1.20pre11 Raw cheese did not mature

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4472]
### Game Version

1.20pre11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Raw cheese if put to the shelf did not start maturing. Just says spoilage time.

### Screenshots

![2024-11-08_13-30-34](https://github.com/user-attachments/assets/8a33926f-1add-48df-a7e9-d6d0222a2173)

### Logs

```Log```

**Comment by Bughaw** [comment]
This issue is still present in pre13.
![Screenshot from 2024-11-18 00-58-56](https://github.com/user-attachments/assets/5f100033-e151-4aaf-8033-da389db61e3f)
