### ISSUE TITLE
Clay oven don't showing us any tips what we can put inside.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4473]
### Game Version

v1.20.0 pre-11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Few pre verions ago there was tips what we can put inside.

### How to reproduce

Try look at clay oven and notice that there is no tips what we can put inside.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 11 08 - 17 00 59 58" src="https://github.com/user-attachments/assets/a5a4db6a-604d-45d1-b096-5d317a4949a6">

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
