### ISSUE TITLE
Unstackable dry mash

### ISSUE THREAD

**Issue by ejzzje** [anegostudios/VintageStory-Issues#4476]
### Game Version

1.20 pre11

### Platform

None

### Modded

None

### SP/MP

None

### Description

If two stacks of dry mash for the same fruit are made in a fruit press they're unable to be stacked with each other.

### How to reproduce

Take a stack of 64 berries, place 32 in two different fruit presses (bucket optional), squeeze one then squeeze the other, retrieve 10 dry mash from each fruit press, attempt to combine the stacks.

### Logs

```Log```

**Comment by avalonv** [comment]
In my experience this seems to affect a variety of items. Besides dry mash, I have unstackable rot and buckets, and as of the new rope physics added in 1.20.0, I've seen quite a few unstackable rope as well. Unfortunately I have no idea how to reliably reproduce any of these, whatever triggers it feels very inconsistent.

**Comment by pingouyn** [comment]
Happened to me too for mash.  Sometimes they stack other times they don't.
In my opinion it could be linked to whether or not you let the pressing process go through entirely, or other timing issues.

A similar bug, pasting here in case it's related.
Crafted items and identical trader purchased items do not stack (for instance lanterns) until the trader bought item is placed in the world then picked up, after which they can be stacked in inventory. #3733.

**Comment by ejzzje** [comment]
The mash issue specifically seems to have been caused by some tag the fruit press was adding, it's fixed now in 1.20 rc6. I'd assume any other unstackable item bug is also being caused by tags being attached by their sources. In the lantern example given the item has the tag, gets placed as a block which no longer stores it then gets picked up again tagless and now able to stack.
