### ISSUE TITLE
Problem with wooden tongs and passing the gods to left hand 

### ISSUE THREAD

**Issue by AnnaAslanyan** [anegostudios/VintageStory-Issues#4488]
### Game Version

v1.20.0-pre.13

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

the problems started after installation of new version v1.20.0-pre.13
There isn't possible to pass any good to left hand with using button X
Also there's not possible to take and work with hot burning ingot.
From user point of view the bug is critical.

### Logs

```Log```

**Comment by maltiez2** [comment]
@AnnaAslanyan reenter the world, it should help

**Comment by DejFidOFF** [comment]
> @AnnaAslanyan reenter the world, it should help

No, It´s not

**Comment by AbortRetryFail** [comment]
Confirming on my server that hot ingots are untouchable even with wooden tongs equipped. Smithing is effectively broken in pre.13.

**Comment by noelle-lavenza** [comment]
> Confirming on my server that hot ingots are untouchable even with wooden tongs equipped. Smithing is effectively broken in pre.13.

Just a hunch: Can you try putting the tongs in your tenth hotbar slot instead to see if that works?

**Comment by Craluminum2413** [comment]
@maltiez2 Maybe it happens only in old worlds?

**Comment by noelle-lavenza** [comment]
> It looooks like what happens is, you have the offhand in slot 10 in 1.19. When you load an old (pre-1.20.0pre13 or whenever the skill slot was added) character in 1.20.0pre13, it adds the skill slot in slot 11, but it's expected in slot 10:
> ```cs
> protected override ItemSlot NewSlot(int slotId)
> {
>     return slotId switch
>     {
>         10 => new ItemSlotSkill(this), 
>         11 => new ItemSlotOffhand(this), 
>         _ => new ItemSlotSurvival(this)
>         {
>             BackgroundIcon = ((1 + slotId).ToString() ?? "")
>         }, 
>     };
> }
> ```
> There's code to swap their _items_ but not their positions:
> ```cs
>         if (slots.Length == 12)
>         {
>             slots[11].Itemstack = slots[10].Itemstack;
>             slots[10].Itemstack = null;
>         }
> ```
> And since they get serialised in that order, that character always has slots 10 and 11 swapped, meaning attempts to access the offhand slot get the skill slot instead.
> It might be as simple as just `(slots[10], slots[11]) = (slots[11], slots[10])` to swap them rather than trying to swap the itemstacks

I wrote this up on the #gamedev channel on the VS Discord server and figured it'd be a good idea to forward it here. A user named Rihiral/foxdog2 found that wiping player data fixed the bug, which clued me in that it was probably an issue with migrating characters to the latest update.

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release

**Comment by DejFidOFF** [comment]
> > It looooks like what happens is, you have the offhand in slot 10 in 1.19. When you load an old (pre-1.20.0pre13 or whenever the skill slot was added) character in 1.20.0pre13, it adds the skill slot in slot 11, but it's expected in slot 10:
> > ```cs
> > protected override ItemSlot NewSlot(int slotId)
> > {
> >     return slotId switch
> >     {
> >         10 => new ItemSlotSkill(this), 
> >         11 => new ItemSlotOffhand(this), 
> >         _ => new ItemSlotSurvival(this)
> >         {
> >             BackgroundIcon = ((1 + slotId).ToString() ?? "")
> >         }, 
> >     };
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There's code to swap their _items_ but not their positions:
> > ```cs
> >         if (slots.Length == 12)
> >         {
> >             slots[11].Itemstack = slots[10].Itemstack;
> >             slots[10].Itemstack = null;
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And since they get serialised in that order, that character always has slots 10 and 11 swapped, meaning attempts to access the offhand slot get the skill slot instead.
> > It might be as simple as just `(slots[10], slots[11]) = (slots[11], slots[10])` to swap them rather than trying to swap the itemstacks
> 
> I wrote this up on the #gamedev channel on the VS Discord server and figured it'd be a good idea to forward it here. A user named Rihiral/foxdog2 found that wiping player data fixed the bug, which clued me in that it was probably an issue with migrating characters to the latest update.

It was on server and world is start in 1.20pre1 and updated to every pre version
