### ISSUE TITLE
In the moment of your dead, you can get on elk and respawn on him instead of respawn point.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4498]
### Game Version

v1.20.0 pre-13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In the moment of your dead, you can get on elk and respawn on him instead of respawn point.

### How to reproduce

Just kill yourself with death cap mushroom and still keep pressing mouse button looking on elk to get on him after dead.

### Screenshots

https://github.com/user-attachments/assets/7b27a7df-294c-4631-8385-f1e548ccdac7

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
