### ISSUE TITLE
1.20pre11 Shield did not block bowthorne projectile

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4499]
### Game Version

1.20pre11

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

1.20pre11 Shield did not block bowthorne projectile

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@DejFidOFF is it pre.13?

**Comment by DejFidOFF** [comment]
pre11 I don´t using pre13 because off hand bug

**Comment by tyronx** [comment]
please reopen this if you can still reproduce this in the latest version
