### ISSUE TITLE
Investigate asphyxiation damage taken from doing everyday things

### ISSUE THREAD

**Issue by RainnMannx** [anegostudios/VintageStory-Issues#45]
When you keep trying to wall into a wall, planks, stone, doors, etc, you can take damage.
https://youtu.be/Vl5UWX1dlqE

**Comment by tyronx** [comment]
is that on the server, because i haven't updated it to 1.5.2.5 yet

**Comment by copygirl** [comment]
@tyronx Shouldn't we keep the issue open until it is properly fixed?

**Comment by tyronx** [comment]
yea, also possible

**Comment by RainnMannx** [comment]
Yes, it was on the official server.

**Comment by copygirl** [comment]
Closing in favor of #30.
