### ISSUE TITLE
Issue with the Alchemist Shirt

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4503]
### Game Version

v1.20.0 pre-13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The arms of the alchemist shirt are unintentionally asymmetrical. You can see this in the provided screenshot.

### Screenshots

![2024-11-13_15-01-47](https://github.com/user-attachments/assets/085d640c-6725-4da9-a480-fcd8f6e439ea)

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next rc
