### ISSUE TITLE
Signs can no longer be placed on the end of trunks

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4506]
### Game Version

v1.20.0pre13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Signs can no longer be placed on the left end of trunks.  It worked in all 1.19 versions.

### How to reproduce

1. Make and place a trunk.
2. Make a sign.
3. Place the sign on the left end of the trunk.  If you press control it opens the trunk.  If you press shift, it places the sign as a normal sign with a post instead of a sign on the end of the trunk.

### Screenshots

![Screenshot from 2024-11-12 23-57-30](https://github.com/user-attachments/assets/a971874b-8a81-417e-afca-f7e004fc1728)

### Logs

```Log```

**Comment by maltiez2** [comment]
will be fixed in next update
