### ISSUE TITLE
Snow Goggles Lore not Showing

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4515]
### Game Version

v1.20.0 pre-13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The description for the snow goggles does not show as they are labelled as a "head" item in the clothing descriptions list, but are actually a "face" item in the game.

### Logs

```Log```

**Comment by RedramVS** [comment]
will be fixed next rc
