### ISSUE TITLE
Snow layers accumulate on kelp tops when directly under the ocean surface

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4517]
### Game Version

1.20.0pre13

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Snow layers accumulate on the top of unfrozen ocean where the kelp reaches the surface.

### Screenshots

![Screenshot from 2024-11-15 05-13-43](https://github.com/user-attachments/assets/41967d7e-3b4a-4f13-bb8b-7899bcc0d173)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
For devs:

To fix, add `snowCoverage: false` to kelp json

**Comment by RedramVS** [comment]
should be fixed next rc
