### ISSUE TITLE
'Delete server from own list confirmation question' missing in translations

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4524]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I can't find the `Really delete server entry '{0}'?` string in the translation files or crowdin.

The string is found when asked to confirm deleting a server entry from you own servers list.

### Screenshots

![Screenshot from 2024-11-17 19-07-18](https://github.com/user-attachments/assets/2f1ef9ac-ba21-40d3-9ec2-17874e07d798)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you. Fixed in upcoming 1.20.0-rc.6. New lang entry:

	"multiplayer-deleteserver-confirmation": "Really delete server entry '{0}'?",
