### ISSUE TITLE
Search field placeholder text in 'Public servers list' is not using/is missing translation

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4525]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

The search field in the public servers list has the placeholder text: `Search...`

Either:

A: It is not using the string already found in the translations which is used for the search field placeholders in the survival handbook and creative inventory. This string uses the key `Search...`

B: It is missing its own separate translation.

### Screenshots

![Screenshot from 2024-11-17 19-12-34](https://github.com/user-attachments/assets/9cae7239-c93f-4806-bac9-d0326c9b7c2c)

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in upcoming 1.20.0-rc.5.  Thank you for raising this
