### ISSUE TITLE
World height slider popup (in 'Customize play style')  not using translation until interacted with

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4526]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When viewing the popup on the **World height** slider in the **Customize play style** window when creating a new world, the translation is not used on the text in the popup (displaying the currently selected world height in blocks) until you interact with the slider by clicking on it or sliding with it. After this the text is correctly translated.

### Screenshots

Hovering over the slider but have not interacted with it yet.
![Screenshot from 2024-11-17 21-01-22](https://github.com/user-attachments/assets/e41fa269-f049-4f76-acca-e11a019028a9)

Clicked the slider button ones. Now the text gets translated correctly.
![Screenshot from 2024-11-17 21-01-26](https://github.com/user-attachments/assets/ef8d4c5d-57bb-4f77-93df-92675cf04f13)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you. I've fixed this for 1.20-rc.6 in both this Customise world screen, and in the Graphics Settings where view distance had a similar issue (though it was localised, the tooltip changed before/after interaction)
