### ISSUE TITLE
Time stopped and Time resumed chatbox messages missing from translations

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4527]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When doing `/time stop` the game responds with **Time stopped**.
When doing `/time resume` the game responds with **Time resumed**.

I can't find those two text strings in the translation files or crowdin.

### Screenshots

![Screenshot from 2024-11-17 22-29-46](https://github.com/user-attachments/assets/97d429a6-409e-4c35-bcbb-95e446b7a230)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks, added from 1.20-rc.6 (or on CrowdIn, from the next CrowdIn keys update whenever that comes).
The keys will be like this:

	"command-time-stopped": "Time stopped",
	"command-time-resumed": "Time resumed",
