### ISSUE TITLE
'Everything' word in prospecting dropdown box on worldmap missing translation

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4528]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In the dropdown box in the **Prospecting** sub-window that comes up along with the **worldmap**, we have the option to show everything. This option does not have a translation attached in the files nor on crowdin.

### Screenshots

![Screenshot from 2024-11-17 22-35-06](https://github.com/user-attachments/assets/f0a337db-ee00-4895-97e9-77d7417a74f6)

### Logs

```Log```

**Comment by radfast** [comment]
Another one fixed in upcoming 1.20-rc.6.   For this, we'll use key: `"worldmap-show-everything"`
