### ISSUE TITLE
The game crashes when I try to view the recipe

### ISSUE THREAD

**Issue by murahych** [anegostudios/VintageStory-Issues#4529]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Good afternoon.
The game crashes when viewing recipes in the "H" menu, the crash occurs both when entering something in the search (and it feels like it happens when pressing certain keys - which ones I couldn't determine), it also crashes when clicking on a recipe with the mouse in the menu itself - this applies to both recipes from mods and vanilla ones.

I'm playing on version 1.19.8 with mods

When it crashes, it displays a window with a log.

Sorry for the bad English - I'm not a native speaker.

### How to reproduce

1. Open the recipe menu - "H" button
2. Try entering the name to search for the recipe (when entered - crashes). OR Try clicking on the recipe in the interface (when clicking on the recipe - crashes).
For example, a chest recipe (if you click on the chest, it immediately crashes)

### Screenshots

![VintageStoryCrash](https://github.com/user-attachments/assets/1151de9f-9410-4e57-be4c-6592f57383a9)

### Logs

```Log```
[client-main.txt](https://github.com/user-attachments/files/17796633/client-main.txt)
[server-main.txt](https://github.com/user
[server-crash.txt](https://github.com/user-attachments/files/17796638/server-crash.txt)
-attachments/files/17796634/server-main.txt)
[client-crash.txt](https://github.com/user-attachments/files/17796637/client-crash.txt)

**Comment by Craluminum2413** [comment]
Caused by sortablestorage mod

**Comment by murahych** [comment]
Wow, I didn't even think about this mod, I'll definitely check it out without it.
Thanks for the help.
