### ISSUE TITLE
Error messages when placing roller logs missing translation

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4532]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The following error messages are not in the translation files or crowdin.

`(api as ICoreClientAPI)?.TriggerIngameError(this, "need5", "Need 5 rolles to place a boat construction site");`
 https://github.com/anegostudios/vssurvivalmod/blob/8d875722b93c39a353846e25aeb83bc1b50d32bb/Systems/Boats/ItemRoller.cs#L154

`(api as ICoreClientAPI)?.TriggerIngameError(this, "unsuitableLocation", "Requires a suitable location near water to place a boat construction site. Boat will roll towards the blue highlighted area. Use tool mode to rotate");`
https://github.com/anegostudios/vssurvivalmod/blob/8d875722b93c39a353846e25aeb83bc1b50d32bb/Systems/Boats/ItemRoller.cs#L159

Also, none of the text strings are wrapped in `Lang.Get(".......")`

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, will be fixed in rc2
