### ISSUE TITLE
'Obtained by killing & harvesting' missing in translations

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4543]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The string `Obtained by killing & harvesting` is missing in the translation files and crowdin.
The string is found in the survival handbook pages for items like flax fiber.

### Screenshots

![Screenshot from 2024-11-21 07-53-07](https://github.com/user-attachments/assets/60c73da7-4599-427d-b9ed-83702c0d6aae)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for reporting.  Included in 1.20-rc.6, the new key in CrowdIn will be `"handbook-obtainedby-killing-harvesting"`
