### ISSUE TITLE
Malefactor Cloak Model Seam Issue

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4549]
### Game Version

v1.20.0 pre-13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The Malefactor Cloak has an issue with the model on one of the shoulders. The blue shown is from the forlorn hope tunic worn underneath.

### Screenshots

![2024-11-22_10-33-44](https://github.com/user-attachments/assets/ca3dba4f-361a-4f83-b0f5-618d3f6cfbba)

### Logs

```Log```

**Comment by RedramVS** [comment]
should be fixed next update
