### ISSUE TITLE
Reed Chests cannot be used to directly capture tame animals

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4551]
### Game Version

v1.20.0pre13

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Reed chests can no longer be placed in the bag slots so they can no longer be used to directly transport tamed animals.  I understand another bug was fixed with reed chests adding player storage, but the fix seems to have broken something.

### Logs

```Log```

**Comment by maltiez2** [comment]
Will be fixed in next update
