### ISSUE TITLE
Pro Pick Bug I can only juse the Density Search Mode

### ISSUE THREAD

**Issue by rian178** [anegostudios/VintageStory-Issues#4557]
### Game Version

v1.19.8 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I wanted to use the prospecting pickaxe but I could only use one mode. I could only use the Density Search Mode and nothing else. I also used the copper prospecting pickaxe and I tried some other prospection pickaxes in creativ mode but it also did not work.

### How to reproduce

Use the prospecting pickaxe and use the keyboard button F and it will only apear one mode and it is the Density Search Mode

### Screenshots

![2024-11-22_22-16-44](https://github.com/user-attachments/assets/68436a4b-8348-4420-8922-2bcf4194fcbe)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
To enable node search, use `/worldConfig propickNodeSearchRadius 6` for example

**Comment by rian178** [comment]
Thanks it worked
