### ISSUE TITLE
Ability to transform metal plates on anvil

### ISSUE THREAD

**Issue by reicherBene** [anegostudios/VintageStory-Issues#456]
I think it would be nice if you have the opportunity to heat metal plates in the forge and then transform them on the anvil (if that's already possible tell me pls ;). Creating metal plates and metal chains with the hammer tooks quite a long time so it would be nice if I could use a metal plate to easily create a metal chain.

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/topic/3314-stable-steel-age-and-character-customization-v1140/?tab=comments#comment-13116

Feature: Anvil improvements
- Metal plates can now also be used to smith tools and other metal produce
