### ISSUE TITLE
Frogs don't making noises.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4561]
### Game Version

v1.20.0 pre-13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Frogs don't making noises.

### How to reproduce

Just find frogs and try hear that they making any noises

### Screenshots

https://github.com/user-attachments/assets/3360dfaf-0745-434b-8202-604f5008036d

### Logs

```Log```

**Comment by Craluminum2413** [comment]
@CookieBoy21 Show your sound settings

**Comment by CookieBoy21** [comment]
<img width="1280" alt="Vintagestory Screenshot 2024 11 23 - 20 17 40 15" src="https://github.com/user-attachments/assets/63559068-bb9b-4eec-a6a5-807278418599">

**Comment by CookieBoy21** [comment]
Also I can hear grasshoppers without any problems but I can't hear frogs.

**Comment by CookieBoy21** [comment]
@Craluminum2413 Ah okay, frogs making noises when it's getting dark, and it was intentional. So there is no issue in this case.
