### ISSUE TITLE
Hover tooltip for contrast setting is not using correct text

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4564]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The hover tooltip for the `Contrast` graphics setting is using the wrong text.

The text it is using is for the `Ambient Bloom` setting (which does not seem to be part of the graphic settings anymore).

### Screenshots

Here hovering (mouse pointer does not show up due to screenshot method) over the `Contrast` setting (in danish `Kontrast`)
![Screenshot from 2024-11-25 18-01-03](https://github.com/user-attachments/assets/40c7aec7-c8dc-42c7-919c-fba214844ba1)

From crowdin
![Screenshot from 2024-11-25 18-03-13](https://github.com/user-attachments/assets/ca5cd6d4-a3bd-401b-aa21-80a819cc3253)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you.  Fixed from upcoming 1.20-rc.6.  The new tooltip will have key `"setting-hover-contrast"` and its text in English will be (provisionally, subject to editing by other dev team members):

> Changes the overall contrast (lightness) of the scene. Has no effect on framerate. Setting disabled (automatically controlled by the game) if Dynamic Color Grading is on.
