### ISSUE TITLE
New creature has insane spawn rates during heavy temporal storms

### ISSUE THREAD

**Issue by hladislav** [anegostudios/VintageStory-Issues#4565]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

The server is hosted on Windows computer through in game local server feature.

During the heavy temporal storm huge amount of enemies spawned outside of my home. I am not sure if this is intended. I survived medium storm on 1.20 pre13 and there wasn't nearly this much enemies.

### Screenshots

![storm](https://github.com/user-attachments/assets/9904764e-cc68-4e19-897b-55a35b67ed1b)
![image](https://github.com/user-attachments/assets/81655222-ec02-436d-9b54-220b0f02360b)

### Logs

```Log```

**Comment by maltiez2** [comment]
Temporal storms can have different enemies composition. This is intended
