### ISSUE TITLE
Pulverized Chromite not computing correctly

### ISSUE THREAD

**Issue by taArden** [anegostudios/VintageStory-Issues#4566]
### Game Version

v1.20.0-pre.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When pulverizing Chromite chunks or nuggets the pulverizer only outputs crush in whole values. Medium chunk of chromite should crush to 1.3x and nuggets to 0.3x. 15 nuggets should give 4.5 crushed chromite but only gave 3 crushed chromite remaining nuggets were deleted/not returned to player.  Same happened with chunks: 15 medium chunks should give 19.5 but only gave 15.

### How to reproduce

1. Using a hopper connected to a powered pulverizer, input multiple chromite chunks or nuggets that should produce a partial amount. 2. Compare to expected result.

### Logs

```Log```

**Comment by maltiez2** [comment]
Output quantities are probability based. There is not such thing as half of an item.
