### ISSUE TITLE
Planter does not have a model for a Green spire cypress tree

### ISSUE THREAD

**Issue by bonenaut7** [anegostudios/VintageStory-Issues#4567]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Planter does not have a model for a Green spire cypress tree.
When trying to put Green spire cypress seed to a planter, a tree appears, but it's model is identical to the Pine tree model.

### How to reproduce

1. Get a planter
2. Get a Green spire cypress seed in a sapling growth stage
3. Plant it to a planter

### Screenshots

![image](https://github.com/user-attachments/assets/63527adf-a504-4b8c-96e4-1c9bc1b1f781)

And Green spire cypress screenshot to clarify exact tree type
![image](https://github.com/user-attachments/assets/fc437df8-d820-4efc-80ed-6237427cc8e5)

### Logs

_There's no log entries so far_

**Comment by Craluminum2413** [comment]
Fixed in 1.20
