### ISSUE TITLE
Incorrect unit type on ingot forms with molten metal

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4570]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When an ingot mold is filled with a metal it uses the incorrect unit type for the metal.

If you use copper it says `xxx units of liquid Copper ingot` instead of just  `xxx units of liquid Copper`.

Other forms uses the correct unit type.

### Screenshots

![Screenshot from 2024-11-27 18-20-13](https://github.com/user-attachments/assets/c479f4a7-c933-4dec-864f-9317d1715925)
![Screenshot from 2024-11-27 18-50-37](https://github.com/user-attachments/assets/b5fcdb88-868b-4d51-af95-7c0b89ced81d)

### Logs

```Log```

**Comment by tannyl** [comment]
@Craluminum2413, I am not talking about the states "liquid", "soft" or "hardened", but about the type of metal.

Look at the type of metal the ingot mold contains. It says the ingot mold contains _32 units of Copper **ingot**_.
It should say _32 units of Copper_ without the added ingot.

All other forms say _32/100 units of Copper_ (if they had 32 units of copper in them).

So if you look at the screenshot with the ingots, it looks like one of them contains 32 copper ingots out of a maximum 100 copper ingots, and the other one 100 out of 100.

What they actually contain are 32 units of copper and 100 units of copper. And you need 100 units of copper to make 1 ingot.

**Comment by tannyl** [comment]
Also as a side note, maybe the ingot molds should also use the same text as all the other molds show how much is needed in total (so 32/100 units of copper instead of just 32 units of copper) so they are consistent  with each other.

**Comment by radfast** [comment]
Thank you, fixed in upcoming 1.20-rc.6
