### ISSUE TITLE
Interacting with a chiseled block (primary breaking) causes game to crash.

### ISSUE THREAD

**Issue by joerik6611** [anegostudios/VintageStory-Issues#4578]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Interacting with a chiseled block (primary breaking) causes game to crash.

The block is a chiseled block consisting of a sandstone slab, ice, and glass. Interestingly, when the chisel is used on the block to show materials, the game does not show it having any materials other then sandstone.

Cases of the crash:
- Editing the block via chisel = crash
- Removing the block via breaking= crash
- Entering the word in safe mode and removing the block = crash
- Entering the word in safe mode and overwriting the block via world edit = crash
- Entering the word in safe mode and deleting the block after setting particles to off (0%) in the graphics settings = no crash

### How to reproduce

It is unclear what combination of chiseling actions created this situation, but the game always crashes on attempting to remove this block except for the case identified above. The chiseled block has no modded blocks in it.

### Screenshots

![2024-11-30_00-03-24](https://github.com/user-attachments/assets/68c64080-18c8-4a87-9a7e-ab47d5ef78af)
![2024-11-30_00-03-27](https://github.com/user-attachments/assets/31e53700-fb39-481f-9deb-63d50540ef27)

### Logs

[client-crash.txt](https://github.com/user-attachments/files/17964615/client-crash.txt)

**Comment by maltiez2** [comment]
Will be fixed in next update

**Comment by radfast** [comment]
Closing because this is fixed in 1.20-rc.1.  @joerik6611 you would need to update to have the fix.  We believe it's a rare issue, maybe a one-off, so you might be able to continue playing 1.19.8 without this fixed, if you are are not yet ready to update to 1.20.
