### ISSUE TITLE
Temperature string for items in clayoven is not translateable 

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4587]
### Game Version

1.20.0-pre.13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When baking items in the clayoven it will show the temperature of each items in the oven, in the block info box.

The temperature string for each item being baked is not being translated using `Lang.Get()`

Look here: https://github.com/anegostudios/vssurvivalmod/blob/8d875722b93c39a353846e25aeb83bc1b50d32bb/Systems/Cooking/Clayoven/BEClayOven.cs#L694
It is using `string.Format()` instead.

This makes it impossible to have consistent formatting for SI units, as we in danish need a space between the number and the SI unit.

### Screenshots

The temperature for the items is shown as `268°C` but in danish it needs to be `268 °C`
The line above for the ovens temperature is in the translation files and thus has the correct formatting.
![Screenshot from 2024-12-03 18-30-33](https://github.com/user-attachments/assets/b0758ada-542b-47c0-8c69-5f6747d8b20a)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you, fixed in upcoming 1.20-rc.6.  It will use the existing key: `"{0}°C"`
