### ISSUE TITLE
Can't put reed chest on raft

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4595]
### Game Version

v1.20.0rc1

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Ctrl+clicking with a reed chest on the location makes the game think I'm trying to capture the raft in the chest instead of placing the chest on the raft.  See screenshot.  The sailboat may have a similar issue.

### How to reproduce

1. Make a raft.
2. Put the raft in water.
3. Make a reed chest.
4. Ctrl+click to try to put a reed chest into the boat.

### Screenshots

![Screenshot from 2024-12-04 14-48-06](https://github.com/user-attachments/assets/bde0dd96-a7d2-4da4-87c0-b7262bda57c9)

### Logs

```Log```

**Comment by Kalmorph** [comment]
It happened with me earlier today on _1.20-rc.4_. There was a mod that did a workaround in 1.20-rc.1 that actually send me to this post, but aparently it got removed.
Didn't noticed anything related to that in the patchnotes for rc.5 and rc.6, so I assume is still bugged?

**Comment by Bughaw** [comment]
No.  It was fixed in rc5.  Just checked in rc6, it is fixed.
