### ISSUE TITLE
Fix "incorrect known srgb profile" error log spam

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#46]
via `pngcrush -rem gAMA -rem cHRM -rem iCCP -rem sRGB -noreduce -ow <files>.` as suggested in #13

**Comment by tyronx** [comment]
command executed for all pngs in 1.5.4. Lets hope it wont break textures.

**Comment by copygirl** [comment]
Seems to be fixed!

**Comment by tyronx** [comment]
Yay! No broken textures ingame?

**Comment by copygirl** [comment]
Oh right. Well, I wasn't one of the people who had broken textures in the first place. Should ask them for confirmation?
