### ISSUE TITLE
Blue Clay / Fire Clay blocks should break more quickly with pickaxes

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#460]
Hello, I have a interesting suggestion that I've come up in my gameplay in general and in latest nathan wostrel's video (https://www.youtube.com/watch?v=ZiQrpBoYi6g). If you break any of the shingle brick results - blocks, slabs, stairs - with bare hands or any tool, it's the same speed. I would suggest these blocks become breakable faster with pickaxes: if you consider burned clay in real life, they are more prone to being broken faster with something with a sharp tip.

Also, consider the work of making the shingles and hence the blocks. It would be a nice compensation to making it easier to break these blocks, if any.

**Comment by Zaldaryon** [comment]
Maybe adding a property of "stone tier 0", like cobblestone. it breaks ok with bare hands, but much quicker with a pickaxe.

**Comment by Craluminum2413** [comment]
Already so, also in 1.15.0-pre.3
> Tweak: Increased block breaking time for refractorybrick, but gave pickaxes a miningspeed bonus for ceramic materials

**Comment by Craluminum2413** [comment]
Close issue?
