### ISSUE TITLE
Sound bug with a rickety translocator

### ISSUE THREAD

**Issue by bonenaut7** [anegostudios/VintageStory-Issues#4602]
### Game Version

1.20 rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

If you'll destroy a rickety translocator while it plays sounds (while you standing on it), and then you'll destroy it, sound will play continue to indefinitely.

### How to reproduce

1. Place a rickety translocator
2. Stand on it and wait for sound to appear
3. Destroy a rickety translocator

### Logs

_There are no log entries so far_

**Comment by maltiez2** [comment]
Will be fixed in next update
