### ISSUE TITLE
Cave art can no longer be erased with the watering can

### ISSUE THREAD

**Issue by SunnyOpossum** [anegostudios/VintageStory-Issues#4604]
### Game Version

v1.20pre.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Previously, induvidual cave art symbols could be erased by using a watering can on them. This was broken in a recent 1.20 pre-release. I am not 100% sure which one, but likely pre.3 or pre.4 because their changelogs mention modifying the cave art code.

### How to reproduce

1.Draw cave art on a block using charcoal, hematite, limonite, or chalk
2.Use a filled watering can on the art, it will not erase like it is supposed to
3.Repeat the first two steps in the current stable release to see the intended behavior

### Logs

```Log```

**Comment by radfast** [comment]
Fixed in upcoming 1.20-rc.2.  Thank you for the report!
