### ISSUE TITLE
Tallow Candles

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#461]
Hello. Considering the cost of making the candles, as the relative same use of beeswax in preservation, I'd like to suggest tallow candles, being the simplest recipe:

- Burn 2 fat in the firepit, every 2 fat will make 1 tallow.
(this recipe could be more complicated, like cooking fat with water on a pot... but that might require new mechanics for letting the tallow to get cold and such).
- Combine tallow as the same as beeswax: 6 tallow make 1 candle. (it doesn't need to have another type of candle, the same as beeswax recipe is enough).

It's a nice source of candles if people want to avoid looking for bees, like the same for preservation, since they can use fat already for sealing crocks.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
