### ISSUE TITLE
game crash on hand book use

### ISSUE THREAD

**Issue by Paddy69** [anegostudios/VintageStory-Issues#4614]
### Game Version

v1.20.0-rc.1 (Unstable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

game crash on using the hand book on and item, or when clicking on an item in the hand book

### How to reproduce

1.1) open hand book
1.2) search for item
1.3) click item
1.4) game crash

2.1) open inventory
2.2) hover over vanilla item
2.3) press hand book keybind (default H)
2.4) game crash

### Logs

```Log```
[client-main.log](https://github.com/user-attachments/files/18041945/client-main.log)
[client-crash.log](https://github.com/user-attachments/files/18041947/client-crash.log)

**Comment by Craluminum2413** [comment]
Caused by mod, update your mods
