### ISSUE TITLE
Connecting to 'Offline' server results in UDP connection error. 

### ISSUE THREAD

**Issue by UC101** [anegostudios/VintageStory-Issues#4615]
### Game Version

v.1.20.0-rc.1

### Platform

None

### Modded

None

### SP/MP

Multiplayer

### Description

When connecting to a local server in offline mode and/or if the sever has no internet connection the game fails to establish a UDP connection. 

I have a home server that runs on my LAN but has no internet connection. One of the things it does is run a Vintage Story server. 
In previous versions of the game _(last tested running 1.19.4)_ this has worked fine, I just have `"VerifyPlayerAuth"` set to false and I have been able to connect. 
However this seems to have broken in somewhere along the development of 1.20. I discovered this in 1.20.0-rc.1.

Attempting to connect to my offline server now results in this error message:
![084619](https://github.com/user-attachments/assets/3b249ac4-8b56-4162-a270-a7a30accc0f1)
At the same time the only thing the server log says about my client is:
`[Notification] Client 1 connected on UDP` with no mention of a disconnect. 

I got curious and did some digging into the server. (I've never modded Vintage Story or touched its internals before so take my analysis with a grain of salt) 
The culprit appears to be an if statement in `ServerMain` in the function `FinalizePlayerIdentification`. 
This statement in particular: `if (serverUdpNetwork.connectingClients.ContainsKey(client.LoginToken) && !client.IsLocalConnection)`
I made a patch that simply removes this check entirely and was able to connect just as I had in the past. I'm not sure if this has any unintended ramifications. 

If this is the intended behavior, _I.E. offline servers are not a supported feature_, then I feel a better error message should be displayed.

### How to reproduce

1. Turn on airplane mode
2. Launch a vintage story server with Auth disabled
3. Launch a vintage story client and attempt to connect to the server
Result: 
`Was unable to establish UDP connection with server.`

( In my testing very rarely I was able to connect to the server, which leads me to believe there may be a race condition involved )

**Comment by tyronx** [comment]
hi, is this any better with rc.4 now?

**Comment by Nyuhnyash** [comment]
Still in 1.20.0-rc.4.
TCP PlayerIdentification is sometimes handled before the UDP Connect has completed.

**Comment by Nyuhnyash** [comment]
The check in the `FinalizePlayerIdentification` is gone in rc.6, so the problem is also gone.
