### ISSUE TITLE
Crash immediately when swimming under water

### ISSUE THREAD

**Issue by godrowr** [anegostudios/VintageStory-Issues#4618]
### Game Version

v1.20-rc1

### Platform

Mac

### Modded

None

### SP/MP

Singleplayer

### Description

**Issue**: Single player, new world generated. Upon dunking the player's head underwater the game freezes, then crashes. No log issue is reported to the user. 
**Reproducible**: Yes 100% of the time. 
**Latest net .7 runtime**: 7.0.15-osx-x64
**System:** Macbook Air. 

### How to reproduce

1. Generate a new world in v1.20
2. Find the nearest body of water at least two blocks deep so head is under water.
3. Go into the water and dip head under. 
4. Instant crash. 

### Logs

```Log```

**Comment by godrowr** [comment]
[client-crash.log](https://github.com/user-attachments/files/18053838/client-crash.log)

**Comment by Th3Dilli** [comment]
thank you this now fixed in rc2

duplicate #4639
