### ISSUE TITLE
Trying to complete step 5 or 13 in the 'First Steps' tutorial breaks the tutorial.

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4623]
### Game Version

1.20.0-rc.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It is not possible to complete step 5 of the 'First Steps' tutorial. In this step the player is tasked with picking up 5 sticks. When ever a stick is picked up (player placed sticks do not count) the tutorial just stops and the tutorial text box vanishes.

The tutorial step can not be resumed from the survival handbook, but the tutorial as a whole can be restarted. But will keep breaking at step 5.

I can skip the step by using the command `.tutorial skip`

When I reached step 13 the tutorial broke again, but this time without actually picking up or creating any firewood.

### How to reproduce

1. Start game and make a new world
2. Start 'First Steps' tutorial
3. Try to complete step 5 by picking up a stick.
4. Tutorial breaks.

### Logs

```Log```

**Comment by tannyl** [comment]
There seems to be no errors in logs or crashes related to this.

**Comment by radfast** [comment]
Thank you for the clear issue report, and having the tutorial work is obviously very important for new players.  I have been able to reproduce and fix the issue.

Fixed in upcoming 1.20_rc.2
