### ISSUE TITLE
Food on a shelf in a cellar lasts longer than tooltip would imply

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#4624]
### Game Version

1.20-rc.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Single player

### Description

Food on a shelf in a cellar lasts a surprisingly long time, longer than the tooltip would imply.

### How to reproduce

1. Make a small cellar with a shelf, a storage vessel, and a chest
2. Observe them all show the same ("other") stored food perish rate, in my case, 0.26.
3. Place bushmeat on the shelf and in each container. Bushmeat lasts 2 days in player inventory, so at .26 perish rate should last a bit under 8 days.
4. Observe the perish times. Bushmeat on shelf says fresh for 88 days, in chest or storage vessel fresh for 6 days.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
1.20-rc.1?

**Comment by sekelsta** [comment]
Yes, I've edited that in now

**Comment by SONZ-INA** [comment]
Noticed this too, wrote a bug report on Discord here:
https://discord.com/channels/302152934249070593/1316151196376891452

Tooltip displays proper perish multiplier, but on food the multiplier is about 0.0175x

**Comment by maltiez2** [comment]
Will be fixed in next update
