### ISSUE TITLE
IMultiBlockInteract.GetSounds naming

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [anegostudios/VintageStory-Issues#4625]
IMultiBlockInteract.GetSounds added in v1.20 breaks the previous convention of MB prefix for multiblock methods. This is confusing and requires using base.GetSounds for the common block method. I like new GetSounds naming, but maybe it should be used for all IMultiblock methods then, rather than specific one?

If you want to switch to the new naming, you can mark the old methods as Obsolete. Or do the same for the new GetSounds and replace it with MBGetSounds. Until release 1.20 comes out, this can still be changed without any major changes by modders too @tyronx @Th3Dilli

**Comment by Th3Dilli** [comment]
oh yeah thanks, will be renamed in rc2
