### ISSUE TITLE
Chromium Tanned Hide Recipe Broken On Updated 1.19.8 World

### ISSUE THREAD

**Issue by Mark-Jen** [anegostudios/VintageStory-Issues#4626]
### Game Version

1.20.0rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After updating my 1.19.8 world to 1.20.0rc.1, I was attempting to produce sturdy leather. I could produce sulfuric acid and chromium sulfate, but nothing happens when I place a liter of chromium sulfate in the first three slots of a cooking pot and a scrapped hide in the last slot, as the guide says. Could formerly installed mods break this somehow? I had mods on the world before the update but uninstalled them for the latest version.

### How to reproduce

1. Create a world in 1.19.8. Bonus points if you have a firepit and a pot there already.
2. Update the game to 1.20.0rc.1, boot the old world and have it update.
3. Attempt to create chromium tanned hide.

### Screenshots

![Screenshot 2024-12-08 112009](https://github.com/user-attachments/assets/b28bfaa6-6522-490f-a91f-696e2b7e09c0)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Show recipe for leather you want to craft

**Comment by Mark-Jen** [comment]
![Screenshot 2024-12-08 143137](https://github.com/user-attachments/assets/674f826a-ffad-4a7f-80d6-830d9e79415d)

**Comment by Mark-Jen** [comment]
Issue fixed in 1.20.0rc5. Recipe now functional.
