### ISSUE TITLE
Glider cannot be placed in the inventory or any other storage container, it also lacks the two inventory slots it should have.

### ISSUE THREAD

**Issue by shasdhhs** [anegostudios/VintageStory-Issues#4628]
### Game Version

1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The glider cannot be placed in any storage container, even crates, or the inventory. You can only store it in your backpack slot. It also lacks the two inventory slots that the glider should provide to the player.

### How to reproduce

Craft the glider and try and put it in a storage container.

### Logs

```Log```

**Comment by tehtelev** [comment]
I found a place to put it - in a bonfire)) 
![2024-12-11_22-54-34](https://github.com/user-attachments/assets/1035a387-cbd1-49d0-bfd7-80b57bf95293)

**Comment by tyronx** [comment]
thanks for the report, will be fixed in rc2

**Comment by Craluminum2413** [comment]
Related https://github.com/anegostudios/VintageStory-Issues/issues/4220
