### ISSUE TITLE
Brown Daub requires blue clay not red clay

### ISSUE THREAD

**Issue by melodelic** [anegostudios/VintageStory-Issues#4631]
### Game Version

v1.20.0-rc.1 unstable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Brown Daub requires blue clay and not red clay like the rest of the daubs (except blue daub).

### Screenshots

![2024-12-08_15-23-32](https://github.com/user-attachments/assets/eddeef54-7d61-44a4-9984-a1e223df50ba)

### Logs

```Log```

**Comment by RedramVS** [comment]
This was changed in a recent rc so all raw daub accepts all clays.  It should be changed as of the most recent rc.
