### ISSUE TITLE
Additionally Inventory Space bugged

### ISSUE THREAD

**Issue by OliveRiggz** [anegostudios/VintageStory-Issues#4632]
### Game Version

v1.20.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Inventory space is bugged where hand baskets and hunter backpacks (potentially leather backpacks, etc.) no longer add extra slots. Additionally, in a file where there were previously added inventory from hunter backpacks, those items appear to have been removed, since there were arrows in my added inventory and my bow was still unable to be used.

### How to reproduce

Put a hand basket/hunter backpack into the intended slot, and the new inventory slots do not appear

### Screenshots

![Screenshot 2024-12-08 115928](https://github.com/user-attachments/assets/e1daa5c7-ddd2-477d-8798-48fa4b3ec771)

**Comment by Craluminum2413** [comment]
Reinstall the game
