### ISSUE TITLE
Unable to create Windmill rotors

### ISSUE THREAD

**Issue by Hadranar** [anegostudios/VintageStory-Issues#4635]
I'm using the correct recipe, just not able to make it. Hammer at top middle, chisel true middle, 2 logs bottom middle, fat right of logs and resin left of logs. It's not showing up as the product. I assume this is a bug, so I'm reporting it here. Thank you!

**Comment by tannyl** [comment]
You should remember to use the "Bugreport" template when creating an issue:
https://github.com/anegostudios/VintageStory-Issues/issues/new/choose

What version of the game are you using?

Maybe post some screenshots of when you are trying to create the item.

Also I just tried creating the rotors in v1.20.rc1 and that worked fine.

**Comment by Hadranar** [comment]
I apologize, I didn't see the bug template before posting.

I also noticed I was using the 1.19.8 client. Was this a known issue to that version? 

Anyways, I went ahead and updated to 1.20 and all works now. Thank you for your help and time, and have a great holiday!

**Comment by tannyl** [comment]
@Hadranar I haven't run into the issue in 1.19.8, but none the less, it is always good to try the latest version to see if anything has changed. :slightly_smiling_face:
