### ISSUE TITLE
Incorrect string used when updating "deposit" line in "Create Auction" window.

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4636]
### Game Version

1.20.0-rc.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In the "Create Auction" dialog box there is a line showing how much of an deposit you need to pay depending on auction duration.

This line uses two different text strings. One when the dialog box is created: Lang.Get("Deposit: {0}", 1)
https://github.com/anegostudios/vssurvivalmod/blob/f905b60d6967cf9758689df723886230205b7260/Systems/Auction/GuiDialogCreateAuction.cs#L88

And another when the line is later updated when changing duration: `Lang.Get("Deposit: {0}x", cost)`
https://github.com/anegostudios/vssurvivalmod/blob/f905b60d6967cf9758689df723886230205b7260/Systems/Auction/GuiDialogCreateAuction.cs#L110

An **x** has been added, which is clearly an error. Both lines should just be `Lang.Get("Deposit: {0}", 1)` to be consistent among them self's and all the other _price lines_.

### Screenshots

![Screenshot from 2024-12-09 07-41-39](https://github.com/user-attachments/assets/3c621c50-f795-493e-bd31-9f13e3c0355b)

![Screenshot from 2024-12-09 07-43-32](https://github.com/user-attachments/assets/d74c1c51-fece-41cc-875e-f147e2f7dd84)

![Screenshot from 2024-12-09 07-43-42](https://github.com/user-attachments/assets/1b0cce05-1b09-4fb5-b259-965ffcef1bad)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you for reporting, this is already fixed in upcoming version 1.20-rc.2
