### ISSUE TITLE
Translation of "Trader cut on sale" string from "Create Auction" dialog box is bugged

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4638]
### Game Version

1.20.0-rc.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In the **Create Auction** dialog box we have the line **Trader cut on sale (10%):** followed by the amount and the gear icon.

The gear icon is not part of the translation but is added via concatenation, but the concatenation of the string and the gear icon is handle incorrectly, thus making the translation always fail.

This happens both where the dialog box is created and when the "cut" is updated.

Here the box is created and the line added:
https://github.com/anegostudios/vssurvivalmod/blob/f905b60d6967cf9758689df723886230205b7260/Systems/Auction/GuiDialogCreateAuction.cs#L89C48-L89C66
The part handling the translations is:
`Lang.Get("Trader cut on sale (10%): {0}" + " " + gearIcon, 1)`

But the problem is that the gear icon is added to the text before translation, thus making `Lang.Get` try to find the _string + gear icon code_ and translate that, which will fail since the translation uses the key `Trader cut on sale (10%): {0}`

The concatenation needs to move outside `Lang.Get` and the code needs to be changed to:
`Lang.Get("Trader cut on sale (10%): {0}", 1) + " " + gearIcon`

The same problems happens where the "cut" gets updated:
https://github.com/anegostudios/vssurvivalmod/blob/f905b60d6967cf9758689df723886230205b7260/Systems/Auction/GuiDialogCreateAuction.cs#L104
The part handling the translation is:
`Lang.Get("Trader cut on sale (10%): {0}" + " " + gearIcon, (int)gearcut)`

But the code should actually look like this:
`Lang.Get("Trader cut on sale (10%): {0}", (int)gearcut) + " " + gearIcon`

### Logs

```Log```

**Comment by radfast** [comment]
Thank you for the clear report and the refs to the auction dialog source code.  Massively helpful!

This is fixed in upcoming 1.20-rc.2
