### ISSUE TITLE
Harvesting Enemies Major Delay

### ISSUE THREAD

**Issue by NordicLink** [anegostudios/VintageStory-Issues#4652]
### Game Version

v1.20.0-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When harvesting enemies or creatures, oftentimes the window takes multiple seconds after the animation finishes to open. However, sometimes the animation finishes at the window and does not appear for more than 30 seconds, requiring moving away from the creature multiple times and clicking on it repeatedly to try and get it to appear. (Bowtorn and the crawling enemy recently added are the worst offenders by far.)

### How to reproduce

Harvest a creature. The new enemies have the longest delay.

**Comment by radfast** [comment]
Does this occur in an _unmodded_ game?  Would you mind testing please, as I think high chance this is a mod issue.

**Comment by NordicLink** [comment]
> Does this occur in an _unmodded_ game? Would you mind testing please, as I think high chance this is a mod issue.

Tested and was unable to reproduce. Sorry for the submission.

**Comment by radfast** [comment]
No worries.  You could try disabling mods one by one or in small handfuls, to see if you can figure out which exact mod is the cause, then report to that mod author.
