### ISSUE TITLE
Hacked locust attack me

### ISSUE THREAD

**Issue by iForged** [anegostudios/VintageStory-Issues#4657]
### Game Version

1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After upgrading to 1.20-rc.1 on my server, I noticed that my hacked corrupt locust started attacking me. I sent it to the "better world". Then, I enabled creative mode, spawned a new one, and hacked it again, but it also began attacking me.

Afterward, I generated a new world in single-player and repeated the actions. The result was the same.
This works for both corrupt and bronze locusts.
At the same time, they still seem to attack my enemies.

Video: https://youtu.be/guOivteQrLs

### How to reproduce

1. Find or spawn a (corrupt/bronze) locust.
2. Hack it.
3. Try approaching it within striking distance.

### Screenshots

-

### Logs

-

**Comment by maltiez2** [comment]
Will be fixed in next update
