### ISSUE TITLE
Armor Stands at Garderoom in Residence Archives empty

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4659]
### Game Version

v1.20.0rc1

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Aged armor stands in garderoom in Resonance Archives appear empty, but give "damaged" crystallized ores and cloth when shift right-clicked instead of the damaged armor.  Did the loot get corrupted or mapped incorrectly?

### Screenshots

![screenshot (1)](https://github.com/user-attachments/assets/9642424b-fb2b-4ab0-8093-84e897f5fa83)

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you, this will be fixed in next release
