### ISSUE TITLE
New enemies do not disappear after a temporal storm

### ISSUE THREAD

**Issue by tehtelev** [anegostudios/VintageStory-Issues#4667]
### Game Version

v1.20-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

During a strong temporal storm, I was sitting at a merchant's. After it was over, I wanted to continue my journey, but new shooting Enemies do not disappear and do not go anywhere at all. They're all level 4 and you can't just kill them. It is very difficult to escape from them without armor. It takes a long time to kill them in close combat, as the others start shooting at the same time.

### How to reproduce

1. Wait for the temporal storm.
3. Hide and do nothing.
3. Wait for the storm to end.

### Screenshots

![u3ymFeOYZvY](https://github.com/user-attachments/assets/dca5c474-96d6-4422-97ff-e6035a926c84)

### Logs

```Log```

**Comment by tyronx** [comment]
this works as intended. After a storms end, only half of the mobs despawn

**Comment by PiqueYo** [comment]
This isn't just half the mobs and isn't just after storms though @tyronx

It only affects bowtorn, not shivers or drifters, and anytime they spawn they always stay unless you go >64 blocks away, regardless if its from rift or storm, day or night they will just loiter until either you manage to leave or kill them all

It feels a bit off at least for early game when you typically die trying to run away from them if you're unlucky enough to get a cluster and can't just wait them out even after a day or two
