### ISSUE TITLE
Blue clay shingles don't get converted when updating the world

### ISSUE THREAD

**Issue by UbaserB** [anegostudios/VintageStory-Issues#4669]
### Game Version

v1.20.0-rc.1 (Unstable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

You'd think the blocks get converted to black clay shingle blocks when the world gets updated, but they're just 'unknown' and I don't want to go out and manually collect all the tiles again... especially considering how many it took to build my base. I assume others feel the same way as me.

### How to reproduce

1. Place down blue clay shingle blocks in the world in version 1.19.8.
2. Download version 1.20.0 and load the world.
3. See blocks with missing textures and names where the blue clay shingles used to be.

### Screenshots

![image](https://github.com/user-attachments/assets/44b64249-043d-4042-b1e9-dccb7a076020)

![image](https://github.com/user-attachments/assets/eedc52a4-5871-4926-8c7a-a0a669272462)

**Comment by tyronx** [comment]
I am not able to reproduce this. Perhaps you have not applied the remappings. Please reopen otherwise.
