### ISSUE TITLE
Lantern with colored glass glow with normal light when hanged on elk/boat.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4680]
### Game Version

1.20-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Lantern with colored glass glow with normal light when hanged on elk/boat.

### How to reproduce

Just put lantern with colored glass on elk/boat.

### Screenshots

https://github.com/user-attachments/assets/9c6d44b6-0154-49b9-901a-e5782872a839

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed next release
