### ISSUE TITLE
[1.20] Vanilla Story Structure Worldheight Issue

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#4683]
### Game Version

v1.20.0-rc.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Tobias cave can get blocked of bcs of either missing fillerblocks to help if terrain is not ideal
Village is getting dirt blocks on farms and is partly floating.

Might want to adjust increase fillerblocks or come up with better scaling to worldheight

### How to reproduce

Increase Worldheight to 384 and check story locations

### Screenshots

![2024-12-13_20-25-27](https://github.com/user-attachments/assets/dc0c78a7-a78b-4ba5-a3cc-d74d65547872)
![2024-12-13_20-24-03](https://github.com/user-attachments/assets/03a73ba8-982e-44bd-9256-a085fa6558be)
![2024-12-13_20-22-17](https://github.com/user-attachments/assets/5bf0b6da-502b-45cd-95cf-800617beac7d)
![2024-12-13_20-22-12](https://github.com/user-attachments/assets/12d5c6b5-b883-4f07-8450-15fd132e8236)

**Comment by Th3Dilli** [comment]
ty niclass, will be fixed in next release
