### ISSUE TITLE
Text within notice/announcement goes behind the element (so not fully readable) when translated. 

### ISSUE THREAD

**Issue by MyraMidnight** [anegostudios/VintageStory-Issues#4690]
### Game Version

v1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

There is an announcement/notice  that simply cannot display the full text, which is an issue for translations that might not have the same word length as original English. I would think this would also be an issue if font size was changed or just overall reusability of said element.

### Screenshots

![announcement-text](https://github.com/user-attachments/assets/cc4f669b-2bf0-4186-9393-8bd33c2ac314)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, will be fixed in rc6

**Comment by MyraMidnight** [comment]
If the banner was on the other side (over image) then it wouldn't be bound by the width of the menu, because you might want to make that adjust to the size of window (client really is not resize friendly at the moment). Just an idea. 

Though resizing had no effect on this particular issue being reported here.
