### ISSUE TITLE
[1.20-rc.2/rc.3] Client unlaunchable on Linux

### ISSUE THREAD

**Issue by dordle** [anegostudios/VintageStory-Issues#4691]
### Game Version

v1.20-rc.2+

### Platform

Linux

### Modded

None

### SP/MP

None

### Description

The game does not launch when executed via the main executable.
`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'CommandLine, Version=2.9.1.0, Culture=neutral, PublicKeyToken=snip'. The system cannot find the file specified.

File name: 'CommandLine, Version=2.9.1.0, Culture=neutral, PublicKeyToken=snip'
   at Vintagestory.Client.ClientProgram..ctor(String[] rawArgs)
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs)
   at Vintagestory.ClientLinux.Main(String[] args)`

The same error occurs with any other executable.
v1.20-rc.1 launches perfectly fine in the same environment.

### How to reproduce

1. Launch the game.

### Logs

N/A

**Comment by Th3Dilli** [comment]
How did you get that error?
Did you launch it from the terminal?

Since rc2 and 3 we have included some code that should display a popup when it detects a installation that may contain files from a previous version. How do you upgrade to new versions?

It is necessary to fully wipe the assets folder and not just extract the new version over the old one.

**Comment by dordle** [comment]
I launched from terminal, also separately from Lutris. No additional settings from terminal, only ./Vintagestory (or ./VintagestoryServer).
I extracted into a completely new folder. There were no additional files of any sort for rc2 or rc3. Only VintagestoryData gets carried over, but considering the executable didn't even get far enough to start logging, it seems immaterial.

**Comment by Th3Dilli** [comment]
ok, very strange
I do not see that issue on my end on Linux

can you check if you see a CommandLine.dll inside the `Lib` folder?

**Comment by dordle** [comment]
Thank you, the Lib folder was missing files. It did not extract properly (twice, in fact). I'll have to blame myself or my dodgy archive extractor. Chalk it up to user error.
