### ISSUE TITLE
Rotating something on the anvil thats being hammered by a helve hammer misaligns its template

### ISSUE THREAD

**Issue by NastyFlytrap** [anegostudios/VintageStory-Issues#4698]
### Game Version

v19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

If you rotate the item in quick succession a few times the voxel grid will be dis-aligned from the actual voxels that are there, meaning you have to 'move the piece to the side' to fit the template

### How to reproduce

Put hot item on anvil, have it be hammered by a helve hammer, rotate it a few times

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4698

**Comment by Craluminum2413** [comment]
oh damn

**Comment by Craluminum2413** [comment]
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3608

**Comment by NastyFlytrap** [comment]
Ah yes. This post is deffinitely a duplicate of this post

lol
