### ISSUE TITLE
Handbook breaking dough recipe icon

### ISSUE THREAD

**Issue by killsode** [anegostudios/VintageStory-Issues#470]
**Game Version:** 1.12.8
**Platform:** Windows 10
**Modded:** No

### Description
Crafting dough works normally until you open the handbook for the type of dough you are trying to craft, then the icon in the output slot does not appear, you can still craft it by clicking the output slot

### How to reproduce
1. Place spelt/any flour and a bucket of water into your crafting grid
2. Look at the crafting recipe for the type of dough you just crafted
3. Repeat step 1
4. The visual output for the recipe breaks, if you click the empty slot you can pick up the dough

### Expected behavior
The dough appearing in the output slot

### Screenshots
![Step one](https://user-images.githubusercontent.com/50812218/76696648-c69ea700-66c8-11ea-9193-8d3f9e6e35ae.png)
![Step two](https://user-images.githubusercontent.com/50812218/76696666-cf8f7880-66c8-11ea-8f28-1e66d1896e9e.png)
![Step three](https://user-images.githubusercontent.com/50812218/76696668-d1f1d280-66c8-11ea-8056-8c89a367c8c0.png)

**Comment by copygirl** [comment]
I believe this is a known issue. Clicking the empty output slot should give you the dough, still. But I looking at the handbook recipe breaks the output showing up, that may be important information for fixing the issue.

**Comment by killsode** [comment]
i can test if its just phantom quickly

**Comment by killsode** [comment]
It does indeed appear to be a visual bug, i'll update my post

**Comment by tyronx** [comment]
thanks a bunch, this is now fixed in the next version of the game
