### ISSUE TITLE
Visual Bug - Handbook Bismuth Bronze Ingot - some "Ingredient for" shown on top of additionally opened Inventory

### ISSUE THREAD

**Issue by GrimFred** [anegostudios/VintageStory-Issues#4707]
### Game Version

v1.20.rc4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When opening the Handbook, then opening the inventory on top of it, the "Bismuth bronze hammer head" and the "bismuth bronze prospecting pick head" are always shown on top of the Inventory.

Additionally when mousing over a field in the inventory it shows the tooltip from the "Ingredient for" List from the Survival Handbook.
I

### How to reproduce

1. Open Survival Handbook to the Bismuth Bronze ingot page
2. open the inventory
3 ???
4. Profit from Bugs.

### Screenshots

![grafik](https://github.com/user-attachments/assets/f2be8fb6-d4be-40e7-bb2d-083861f66182)

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in rc.6
