### ISSUE TITLE
Game and Wiki disagree on the "growing" status of farm crops

### ISSUE THREAD

**Issue by GazzTFP1** [anegostudios/VintageStory-Issues#471]
**Game Version:** 1.12.8
**Platform:** Windows
**Modded:** Yes ([Graveyard Mod](https://www.vintagestory.at/forums/topic/638-111-graveyard-mod/))

### Description
The game claims that farm crops on dry farmland are "growing" while according to the [Wiki](https://wiki.vintagestory.at/index.php?title=Farming) a nearby water source is required.

### How to reproduce
1. Use a hoe to create "dry" farmland more than 3 spaces away from a water block.
2. Plant a crop seed on it.
3. Observe that the planted seed displays e.g. "Carrots (growing)", but does not grow unless it rains eventually.

### Expected behavior
Crops on dry farmland display e.g. "Carrots (too dry)" if they are not growing because they require water.

**Comment by copygirl** [comment]
The "growing" in the name of the crop doesn't necessarily indicate that the crop is currently able to grow, but rather that it is not yet fully grown and therefore shouldn't be harvested yet. I understand the confusion however and will leave this up.

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/124763251-70e4b280-df3c-11eb-8975-81b834fbca7b.png)

**Comment by copygirl** [comment]
Indeed, will close for now, as there is a lot more information available. Having "Moisture" be one of the stats implies that it affects crop growth in some way. The wiki can be edited by its contributors to reflect the current mechanics of the game. (Which should probably handled through its dedicated channel in the Discord server.)
