### ISSUE TITLE
"Auction house" message in chat box not translatable due to bug and translation unfriendly

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4710]
### Game Version

1.20.0-rc.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When entering a world, it will display information in the chat box about the current state of your auctions.

The final message is build of several strings:

The first part is **Auction House: You have** which uses the translation key `Auction House: You have` (note: please use contextual keys instead of the strings as keys as this helps us translating a lot)
 
In the code found at https://github.com/anegostudios/vssurvivalmod/blob/d42d85eaef4fa3cdbea304fc0e74663c52c2985c/Systems/Auction/Auction.cs#L316
they key used to fetch the string is not correct. It has a space added at the end: `sb.Append(Lang.Get("Auction House: You have "));`

Another problem is that the whole string that is being build is not translation friendly since we have limited control over how the multiple strings get put together in this section: https://github.com/anegostudios/vssurvivalmod/blob/d42d85eaef4fa3cdbea304fc0e74663c52c2985c/Systems/Auction/Auction.cs#L313-L325

So I have a few suggestions to an alternative approach:

**Always show all lines in the message, even if empty, which will also make the code simpler.**

In the translation files old strings are replaced with this key and string (note I have pluralized as well):

`auctionmessage-status` => **Auction House: You have {p0:0 sold auctions|1 sold auction|# sold auctions}, {p1:0 expired auctions|1 expired auction|# expired auctions}, {p2:0 active auctions|1 active auction|# active auctions}, {p3:0 purchased auctions|1 purchased auction|# purchased auctions} en-route and {p4:0 purchased auctions|1 purchased auction|# purchased auctions} ready for pick-up.**
 
And the code for it:
```
if (expiredAuctions > 0 || activeAuctions > 0 || readyPurchasedAuctions > 0 || enroutePurchasedAuctions > 0 || soldAuctions > 0)
{
    byPlayer.SendMessage(GlobalConstants.GeneralChatGroup, Lang.Get("auctionmessage-status", soldAuctions, expiredAuctions, activeAuctions, readyPurchasedAuctions, readyPurchasedAuctions);, EnumChatType.Notification);
}
```

**Print it out as a list.**

In the translation files old strings are replaced with these keys and strings (note I have pluralized as well):

auctionmessage-status => **Auction House: You have**
auctionmessage-status-sold => **- {p0:|1 sold auction|# sold auctions}**
auctionmessage-status-expired => **- {p0:|1 expired auction|# expired auctions}**
auctionmessage-status-active => **- {p0:|1 active auction|# active auctions}**
auctionmessage-status-purchased => **- {p0:|1 purchased auction|# purchased auctions} en-route**
auctionmessage-status-ready => **- {p0:|1 purchased auction|# purchased auctions} ready for pick-up**

and the code for it:
```
if (expiredAuctions > 0 || activeAuctions > 0 || readyPurchasedAuctions > 0 || enroutePurchasedAuctions > 0 || soldAuctions > 0)
{
    StringBuilder sb = new StringBuilder();
    sb.Append(Lang.Get("auctionmessage-status"));
    if (soldAuctions > 0) { sb.AppendLine(Lang.Get("auctionmessage-status-sold", soldAuctions)); }
    if (expiredAuctions > 0) { sb.AppendLine(Lang.Get("auctionmessage-status-expired", expiredAuctions)); }
    if (activeAuctions > 0) { sb.AppendLine(Lang.Get("auctionmessage-status-expired", activeAuctions)); }
    if (enroutePurchasedAuctions > 0) { sb.AppendLine(Lang.Get("auctionmessage-status-purchased", readyPurchasedAuctions)); }
    if (readyPurchasedAuctions > 0) { sb.AppendLine(Lang.Get("auctionmessage-status-ready", readyPurchasedAuctions)); }

    byPlayer.SendMessage(GlobalConstants.GeneralChatGroup, sb.ToString(), EnumChatType.Notification);
}
```

### Logs

```Log```

**Comment by radfast** [comment]
In general I don't think it's a good idea to **change** the translation keys after we already released in this form, because some language teams will already have translated the existing keys.   Normally, we only change keys to signify some different usage, effectively to alert translators that the existing key might be out of date (for example, adding or removing a {0} parameter).

I take the point that in future, in general, it will be easier for translators if translation keys are in the 1-word language-neutral form, not English phrases.

The idea of separate lines is a good one, and we can pluralize the en.json too.
