### ISSUE TITLE
Typo variable in string on crowdin

### ISSUE THREAD

**Issue by MyraMidnight** [anegostudios/VintageStory-Issues#4712]
### Game Version

v1.20.0-rc.4

### Platform

None

### Modded

None

### SP/MP

None

### Description

There seems to be a duplicate use of a variable in a string that I noticed while translating. So both days and hours would probably show same number, and therefor incorrect information?

`Your active server time will expire in {0:0.#} days and {0:0.#} hours`

the second variable is probably supposed to be `{1:0.#}` like in related strings.
Said string has no context, as seen screenshot, but can be found with the search on crowdin.

### Screenshots

![source-string-typo](https://github.com/user-attachments/assets/835e25dc-9f50-486e-ace8-3cd79dbb1b55)

### Logs

```Log```

**Comment by radfast** [comment]
Good spot, thank you
