### ISSUE TITLE
Pine raft is missing description

### ISSUE THREAD

**Issue by singlain** [anegostudios/VintageStory-Issues#4715]
### Game Version

v1.20.0-rc.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Using only **Plains and Valleys mod**.

### How to reproduce

1. Craft a pine raft
2. Place it and look at it's description above

### Screenshots

![image](https://github.com/user-attachments/assets/0d40c329-00e6-403d-8220-81c92694f225)

### Logs

```Log```

**Comment by singlain** [comment]
To be exact - oar slot is missing it's description

![image](https://github.com/user-attachments/assets/a0c178c1-3f0d-462a-80b3-50929babf88a)

**Comment by RedramVS** [comment]
Will be fixed next update
