### ISSUE TITLE
Third Person Switch Raft Glitch

### ISSUE THREAD

**Issue by singlain** [anegostudios/VintageStory-Issues#4718]
### Game Version

v.1.20.0-rc.4

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Only using Plains and Valleys mod.
If you enter a raft while in third person, switch the seat and switch to the first person, your hands will be floating
With immersive first person mode disabled, hands just float
With immersive first person mode enabled, your character appear like they're standing while riding the raft.

### How to reproduce

1. Swtich to the third person
2. Take an oar to row
3. Get on a back seat of a raft
4. Switch to the front seat of a raft
5. Swtich to first person

### Screenshots

https://github.com/user-attachments/assets/549e6494-84ff-49bb-8a48-0a6531662141

https://github.com/user-attachments/assets/80053fb7-ff9d-44f6-b39f-00c9ebdcdc07

### Logs

```Log```

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc6
