### ISSUE TITLE
Save game crashes while loading :-(

### ISSUE THREAD

**Issue by Satras1** [anegostudios/VintageStory-Issues#472]
**Game Version:** 1.12.8
**Platform:** Windows 7
**Modded:** No

### Description
can't load a save game, new world seems to work

### How to reproduce
1. Load save game
2. loading log appears and finishes
3. Before entering the world, it crashes

### Expected behavior
Loading the saved game

### Screenshots
-

### Logs
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.12.8 (Stable)16.03.2020 17:27:45: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_9J05IwqX3DMJjYc4TgQdHtYCjUh serverpacket)
   bei _DheU0S41ys8PmWwanVxliVufAfL._8pFQWKHqjk1Z0lk74wVtfciws7e(Single )
   bei _EBtxK36Ixmcei9M4cHb3yN0CdBY._SBmZIE5zeKBZLld4sDoBkph45oC(Single )
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._xnJNZgMqo5oGjGjHTS2kXgpC9eH(Single )
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._uw3xmExX4CRVc5TYKty6OJkT52C(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ , String[] )
   bei _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 15.03.2020 19:40:31, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
{ TimeGenerated = 15.03.2020 12:30:49, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
{ TimeGenerated = 15.03.2020 00:33:23, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: System.AccessViolationException
   bei OpenTK.Graphics.OpenGL.GL.VertexAttribDivisor(Int32, Int32)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.UploadMesh(Vintagestory.API.Client.MeshData)
   bei _y7gbkC6Sb4RbMUkXD1ZFsNoqY0X..ctor(Vintagestory.API.Client.ICoreClientAPI, Int32)
   bei _BD9MyN7PfCdKieQz7kUsgT1LryB..ctor(_TCuegFvuCG7xQqhWKljGWgaccAS, Vintagestory.API.Client.ICoreClientAPI, Int32)
   bei _KlotEyZDv9YR1R9UAbDvY1c2Cfd..ctor(_TCuegFvuCG7xQqhWKljGWgaccAS, _XkGl9w6M8orX9nOwS1SceuffZ2g)
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ, System.String[])
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ, System.String[])
   bei _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(System.Threading.ThreadStart)
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._8XkLfQdRlqL0OAaS59a2mavRA8j(System.String[])

 }

**Comment by Satras1** [comment]
After restarting the computer, I COULD load the broken savegame, only to crash out maybe 2 minutes later. Bug report:

Running on 64 bit Windows with 4 GB RAM 
Version: v1.12.8 (Stable)16.03.2020 17:49:28: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_9J05IwqX3DMJjYc4TgQdHtYCjUh serverpacket)
   bei _DheU0S41ys8PmWwanVxliVufAfL._8pFQWKHqjk1Z0lk74wVtfciws7e(Single )
   bei _EBtxK36Ixmcei9M4cHb3yN0CdBY._SBmZIE5zeKBZLld4sDoBkph45oC(Single )
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._xnJNZgMqo5oGjGjHTS2kXgpC9eH(Single )
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._uw3xmExX4CRVc5TYKty6OJkT52C(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ , String[] )
   bei _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 15.03.2020 19:40:31, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
{ TimeGenerated = 15.03.2020 12:30:49, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
{ TimeGenerated = 15.03.2020 00:33:23, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: System.AccessViolationException
   bei OpenTK.Graphics.OpenGL.GL.VertexAttribDivisor(Int32, Int32)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.UploadMesh(Vintagestory.API.Client.MeshData)
   bei _y7gbkC6Sb4RbMUkXD1ZFsNoqY0X..ctor(Vintagestory.API.Client.ICoreClientAPI, Int32)
   bei _BD9MyN7PfCdKieQz7kUsgT1LryB..ctor(_TCuegFvuCG7xQqhWKljGWgaccAS, Vintagestory.API.Client.ICoreClientAPI, Int32)
   bei _KlotEyZDv9YR1R9UAbDvY1c2Cfd..ctor(_TCuegFvuCG7xQqhWKljGWgaccAS, _XkGl9w6M8orX9nOwS1SceuffZ2g)
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ, System.String[])
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ, System.String[])
   bei _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(System.Threading.ThreadStart)
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._8XkLfQdRlqL0OAaS59a2mavRA8j(System.String[])

 }

**Comment by Bloodsaw** [comment]
In version 1.12.8 there should be an option to repair your corrupted savegame.
Its in the loading menu when you click the small pencil on the right. 
Please follow the instructions you receive there.

**Comment by Satras1** [comment]
Thank you! that seems to have solved the problem.

**Comment by Bloodsaw** [comment]
Glad to hear. Could you please share what happened before your savegame was corrupted?

**Comment by Satras1** [comment]
I think the most notable thing that happened was as I was prospecting for ores the game requested 4 ore samples (the initial one, "two more", "one more" then ANOTHER "one more". In the pit there were some critters running around, some were dead, some were only carcasses. The game always crashed shortly after I was leaving the pit and during storing away items.

**Comment by Bloodsaw** [comment]
I don't think that the prospecting was the cause of the crash. From reading the crash log and your description I conclude that its more down to an issue with entities.:

> "some critters running around, some were dead, some were only carcasses"

> `bei Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_9J05IwqX3DMJjYc4TgQdHtYCjUh serverpacket)
bei`

Maybe the server spawned another critter and some rare condition lead to this exception. Like desync or occupied space. 
@tyronx @copygirl what happens if the server wants to spawn a critter on a place occupied by a carcass?

**Comment by copygirl** [comment]
@Satras1:
> I think the most notable thing that happened was as I was prospecting for ores the game requested 4 ore samples (the initial one, "two more", "one more" then ANOTHER "one more".

Not related to the crash, but each block you sample needs to be at least 3 blocks away from other sample locations. It will say the same thing twice if you didn't do that.

@Bloodsaw:
> what happens if the server wants to spawn a critter on a place occupied by a carcass?

I don't see how that could cause a problem, but to be fair I haven't checked the code. (Not familiar with it.)
