### ISSUE TITLE
"Resume Tutorial" string missing in translation file

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4724]
### Game Version

1.20.0-rc.5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

On this line of code the text used on the start/stop button for the tutorial in the survival handbook is handled:
https://github.com/anegostudios/vssurvivalmod/blob/d42d85eaef4fa3cdbea304fc0e74663c52c2985c/Systems/Handbook/Tutorial/GuiHandbookTutorialPage.cs#L59
`startStopButton.Text = Lang.Get(prevProgress > 0 ? "Resume Tutorial" : "Start Tutorial");`

The string **Resume Tutorial** is not in the translation files nor crowdin.

Remember to give it a contextual translation key (thanks @radfast). I suggest giving it a key like **handbook-tutorial-button-resume** (`startStopButton.Text = Lang.Get(prevProgress > 0 ? "handbook-tutorial-button-resume" : "Start Tutorial");`)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks, another good spot.  We'll go for `"button-tutorial-resume"` for consistency with a few other button names
