### ISSUE TITLE
Reinforced wooden signs are editable by another players

### ISSUE THREAD

**Issue by bonenaut7** [anegostudios/VintageStory-Issues#4725]
### Game Version

v1.19.8

### Platform

None

### Modded

None

### SP/MP

Multiplayer

### Description

Reinforced wooden signs are editable by another players (Other signs could be affected too, not sure that's a bug because of that though)

### How to reproduce

1. Place a wooden sign, write something on it
2. Reinforce the sign with something (for example: granite rock)
3. Let another player edit the sign

### Logs

_There are no log entries so far_

**Comment by Craluminum2413** [comment]
It was fixed in 1.20
