### ISSUE TITLE
Malefactor Cloak's Hood - Visual Issue

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4728]
### Game Version

v1.20.0 rc-5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The Malefactor Cloak's hood has a visual issue.

The hood has no texture underneath like other hooded items (eg fur coat) so appears disconnected from the rest of the cloak if viewed from certain angles. Try sleeping in third person to make this obvious.

### Screenshots

![hood](https://github.com/user-attachments/assets/edec166d-08d4-47f5-9fbc-a61f94ebc051)

### Logs

```Log```

**Comment by RedramVS** [comment]
As some background, this is something of a relic of the days when clothing textures were applied as overlays on the seraph's skin.  The box that at that time received the hood texture, was also a hair texture box, and very long.  As such, it did not have a bottom face.  Fast forward to 3d clothes, and we can make hoods with bottoms, and have done on several that have nice neat edges.  However we'd have to redo the ragged bottom edge of this malefactor cloak hood, as it can't really receive a flat bottom face, being so ragged.   Saraty likes the ragged edge.   As such, it'll remain as-is.
