### ISSUE TITLE
Barrels can be used to get liquid in non liquid slots

### ISSUE THREAD

**Issue by InsanityGod** [anegostudios/VintageStory-Issues#4734]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

You can use a barrel to get liquids inside a slot that shouldn't be able to hold liquid.

### How to reproduce

1. Make a firepit
2. Put on Cooking Pot
3. Fill slot with water
![2024-12-18_20-08-26](https://github.com/user-attachments/assets/5c10d51d-bfb8-47be-a22e-e10f0d4f168d)

4. Right click on liquid with barrel to pick it up (just like with bucket)
![2024-12-18_20-11-32](https://github.com/user-attachments/assets/dba9af38-6028-49df-b25e-a4dfb3a8bbb1)

5. Place down barrel and open it
![2024-12-18_20-13-10](https://github.com/user-attachments/assets/0446a5eb-871f-4e21-b7e8-2c52be7ef3b7)

6. Now you can take out the water and move it around as if it is a solid
![2024-12-18_20-14-33](https://github.com/user-attachments/assets/ac35e725-3813-47a4-813c-e1158fb9f733)

**Comment by radfast** [comment]
Thank you for reporting and thank you @Craluminum2413 for reviewing. This is fixed in upcoming 1.20.0-rc.6
