### ISSUE TITLE
1.20rc5 Getting kicked from server after Drifter (entity) looting 

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4739]
### Game Version

1.20rc5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When collecting loot from drifter it cause exeption.

### Logs

19.12.2024 10:19:28 [Error] Exception: Specified argument was out of the range of valid values. (Parameter 'slotId')
   at Vintagestory.API.Common.InventoryGeneric.get_Item(Int32 slotId) in VintagestoryApi\Common\Inventory\InventoryGeneric.cs:line 103
   at Vintagestory.Common.InventoryNetworkUtil.HandleClientPacket(IPlayer byPlayer, Int32 packetId, Packet_Client packet) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 87
   at Vintagestory.GameContent.EntityBehaviorHarvestable.OnReceivedClientPacket(IServerPlayer player, Int32 packetid, Byte[] data, EnumHandling& handled) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 347
   at Vintagestory.API.Common.Entities.Entity.OnReceivedClientPacket(IServerPlayer player, Int32 packetid, Byte[] data) in VintagestoryApi\Common\Entity\Entity.cs:line 1457
   at Vintagestory.Server.ServerMain.HandleEntityPacket(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\ServerGeneralPacketHandler.cs:line 447
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 141

**Comment by Craluminum2413** [comment]
Does it happen without mods?

**Comment by DejFidOFF** [comment]
> Does it happen without mods?

How can be mod involved? Just moving vanilla items from drifter container, no code mod involved.

**Comment by Craluminum2413** [comment]
@DejFidOFF Maybe some mod changed slots count for harvestable inventory on client side but forgot to do that on server side

**Comment by DejFidOFF** [comment]
> @DejFidOFF Maybe some mod changed slots count for harvestable inventory on client side but forgot to do that on server side

Only in my mod in /patches :

    {
        "op": "addmerge",
        "path": "/client/behaviors/4/quantitySlots",
        "value": 8,
        "file": "entities/land/drifter.json"
    }

**Comment by Craluminum2413** [comment]
@DejFidOFF Patch this on server too

**Comment by DejFidOFF** [comment]
> @DejFidOFF Patch this on server too

I have this mod on the server, what can I do more?

**Comment by Craluminum2413** [comment]
@DejFidOFF You need to patch both client and server, not just client

**Comment by DejFidOFF** [comment]
> @DejFidOFF You need to patch both client and server, not just client

really don´t understend. I have this mod on the server. mod is both sides, so when client try to connect to the server it download the mod for client also.. And if I edit that and made this:

        "op": "addmerge",
        "path": "/client/behaviors/4/quantitySlots",
        "value": 8,
        "file": "entities/land/bowtorn.json",
            "side": "Server"
            
            It´s still kicking me..

**Comment by DejFidOFF** [comment]
> @DejFidOFF You need to patch both client and server, not just client

I can patch whatever still kicking from server.

**Comment by Craluminum2413** [comment]
@DejFidOFF try these
```json
   "op": "addmerge",
    "path": "/client/behaviors/4/quantitySlots",
    "value": 8,
    "file": "entities/land/bowtorn.json"

   "op": "addmerge",
    "path": "/server/behaviors/4/quantitySlots",
    "value": 8,
    "file": "entities/land/bowtorn.json",
```

**Comment by DejFidOFF** [comment]
It´s a vanilla bug. Not something causing my mod. My mod is just add to "harvestable" "quantitySlots:8" that´s all.
So "quantitySlots" properity don ´t working or working bad.

**Comment by Craluminum2413** [comment]
@DejFidOFF You need to change quantitySlots for both client and server with 2 separate patches:
- Patch **client** with new **quantitySlots**
- Patch **server** with new **quantitySlots**

**Comment by DejFidOFF** [comment]
> [@DejFidOFF](https://github.com/DejFidOFF) You need to change quantitySlots for **both** client and server with 2 separate patches:
> 
> * Patch **client** with new **quantitySlots**
> * Patch **server** with new **quantitySlots**
> 
> Note that it is not possible to change them with just one patch, you need **two patches**, this is important detail

Oooh, didn´t know that :( Thank you <3
