### ISSUE TITLE
Knapping Selection box empty

### ISSUE THREAD

**Issue by Zank82** [anegostudios/VintageStory-Issues#474]
**Game Version:** 1.12.8
**Platform:** Windows 10
**Modded:** Yes 

Shift Click to open knapping menu, nothing to select. 

[https://imgur.com/a/1zMMQuF](https://imgur.com/a/1zMMQuF)
EDIT: Nevermind,  Drifter Butchering Mod broke it.

**Comment by copygirl** [comment]
I just want to point out, this happens in general when there's an error loading certain assets / recipes. Specifically, I've noticed this can happen when updating a server without clearing the `assets/` folder, causing old files to be loaded.
