### ISSUE TITLE
Lake odd level worldgen bug

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#475]
**Game Version:** 1.12.9-rc1
**Platform:** Windows 10
**Modded:** No

### Description
I've found a way to reproduce the water lake leveling worldgen bug.

### How to reproduce
1. Find a lake that is near sealevel and that occupies more than 1 chunk;
2.  Use /wgen regen 0 on one of the chunks;
3. Look the discrepancy;
4. Use /wgen regen with a number that ocuppies all the lake. (normally 1 or 2 for small lakes);
5. The leveling is fixed;
6. I tested and was able to reproduce the bug many times at 6933, 116, 5623 on Chrometech.

### Expected behavior
It might have to do with lake chunks generating at different times. If possible, this part of worldgen might be checked, or at least you might guarantee that all the lake chunks load at the same time.

### Screenshots
![2020-03-17_12-52-38](https://user-images.githubusercontent.com/50756284/76875669-a3523400-684f-11ea-82e3-e64a442ef4b4.png)
![2020-03-17_12-52-51](https://user-images.githubusercontent.com/50756284/76875672-a51bf780-684f-11ea-8611-a1a043feac3e.png)

**Comment by Bloodsaw** [comment]
Unfortunately this happens quite regularly. Here's also a screenshot of failed world gen with cut off water: 

![2020-03-14_22-37-26](https://user-images.githubusercontent.com/61588797/77011099-69765000-696b-11ea-8d38-a9c97b625b41.png)

**Comment by Zaldaryon** [comment]
@Bloodsaw Could you reproduce the error and the fix as I stated above? It's an old bug, as far as I know. (1.9 onwards at least).

**Comment by Bloodsaw** [comment]
Yep can confirm that regen 5 fixed the whole lake in that place.

**Comment by tyronx** [comment]
Fixed in v1.13, at long last \o/
