### ISSUE TITLE
Audit System not reporting Sail Boats

### ISSUE THREAD

**Issue by Darkx352** [anegostudios/VintageStory-Issues#4756]

**Comment by radfast** [comment]
@Craluminum2413 why close?  Sail boat creation sounds like something which should be included in the `server-audit.log`

**Comment by Craluminum2413** [comment]
@radfast Because it is empty and they opened https://github.com/anegostudios/VintageStory-Issues/issues/4757

**Comment by radfast** [comment]
/me slaps head

So sorry, I didn't see 4757
