### ISSUE TITLE
Last bits of clay placed when clayforming are free

### ISSUE THREAD

**Issue by Wesmania** [anegostudios/VintageStory-Issues#4766]
### Game Version

v1.20-rc.5

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

When clayforming, the last bit of clay placed does not factor into the clay cost of an item and does not subtract from the clay held in hand when the number of available bits goes in the negative. This is meaningful for e.g. making shingles, as placing the last 9 bits all at the same time lets you spend 3 clay on 12 shingles instead of 4 clay.

### How to reproduce

* Start clayforming a shingle.
* For the last shingle, fill in a single row first, then the last 9 bits all at once with a 3x3 tool.
* Observe how you spent 3 clay instead of 4.

**Comment by Craluminum2413** [comment]
Do you mean it consumes less clay?

**Comment by Wesmania** [comment]
Depends on the definition of "should". If the idea is that every piece of clay is 25 or so bits and anything that's clayformed that has more than 25 * N bits needs at least N pieces, then yes.

**Comment by pizza2004** [comment]
Should be fixed in the next release.

**Comment by pizza2004** [comment]
Upon review it was decided this is okay to leave in as a game mechanic.

**Comment by VinterNacht** [comment]
This was a poor decision... shame upon you, shame upon your family, shame upon your cow... ;)
