### ISSUE TITLE
Fire Brick Gratings drop Fire Brick Blocks

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4767]
### Game Version

v1.20.0rc5

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

If you break a placed fire brick grating, it turns into a fire brick block.

### How to reproduce

1. Create a fire brick grating.
2. Place the grating.
3. Break the grating (I used a pickaxe.).
4. A fire brick block drops instead.

### Logs

```Crash```

**Comment by Bughaw** [comment]
Handbook also shows the gratings drop blocks.
![screenshot (4)](https://github.com/user-attachments/assets/aa49e49b-ae8a-4d66-9fc7-ca0e100bf669)

**Comment by pizza2004** [comment]
Fixed in -rc.6.
