### ISSUE TITLE
Linux: Main menu quote font is missing a character for the closing ‟ 

### ISSUE THREAD

**Issue by Perturbee** [anegostudios/VintageStory-Issues#4769]
### Game Version

1.20.0-RC5

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

For some reason the end quote in the little phrase at the bottom of the starting screen is displayed as a box.
I have all the required MST fonts installed (and then some) but I'm unable to find which it's looking for. 
![2024-12-22_12-26](https://github.com/user-attachments/assets/e53208f5-04f3-4e3d-970a-9a71edca4b9b)
Please note, this has been an "issue" from the start on my system.

I've tried running `fc-match ‟` on my system and it says "Arial" "regular" which is installed, but apparently not the one.

### How to reproduce

The system is openSUSE Leap 15.6 with the Microsoft fonts pack installed. Nothing is logged and the code says:
`this.quoteTexture = this.ScreenManager.api.Gui.TextTexture.GenUnscaledTextTexture("„" + this.quote + "‟", CairoFont.WhiteDetailText().WithSlant(FontSlant.Italic));` but I can't work out what's wrong with it.

### Screenshots

![2024-12-22_12-26](https://github.com/user-attachments/assets/72efa026-28f8-4f33-9669-b272eeddeb81)
![2024-12-22_08-28](https://github.com/user-attachments/assets/dd62ab1a-0729-4d91-bd2b-ce4e94f1dea2)

### Logs

I realise this is only a minor optical issue, but it's strange that it does this out of the box, while having all the necessary fonts installed.

**Comment by Craluminum2413** [comment]
You are most likely missing some font

**Comment by pingouyn** [comment]
Hi, go to the folder where vinstage story is installed (for me ~/.local/share/vintagestory) and run VS using the following command.  You should see info on what fonts are used:
FC_DEBUG=2053 ./run.sh

Hope you'll find the missing one.

**Comment by Perturbee** [comment]
Thank you for that, that is a mighty impressive list to work through, :) I'll start digging for the missing one.

**Comment by radfast** [comment]
The relevant sourcecode of the game for this font is:  `CairoFont.WhiteDetailText().WithSlant(FontSlant.Italic)`.   Therefore, it's the Cairo library choosing the font, it will be looking for an **Italic** version of the defaultFontName, with size 14.

The defaultFontName is configurable by the user in `clientsettings.json`.  Unless you're using an Asian language where the game might change it for certain languages (specific to the language character set), it's normally:

    "defaultFontName": "sans-serif",

(But you as the user can change that to whatever you like on your own machine)

**Comment by radfast** [comment]
I don't think there's any bug in the game here, and the user can select their own font for this in `clientsettings.json` as I have explained above.  Therefore this issue can be closed.

**Comment by Perturbee** [comment]
The font "Noto Sans" was the one that made it work!
