### ISSUE TITLE
Able to fuse cold anvil top part to hot base part

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4770]
### Game Version

1.20.0-rc.5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In the descriptions for ferrous anvils it states you must create and top and base part and then fuse them together using an flux agent in between. The description also states both the top and the base must be hot while doing this.

This is not the case and you are able to fuse a cold top to a hot base. See screenshot below.

It is easy to see in the code why this happens: https://github.com/anegostudios/vssurvivalmod/blob/47b8a492f77c53ad121980bcce9f0778791fdbb5/BlockEntity/BEAnvilPart.cs#L175-L186

The section handling adding top part does not do any checks to see if the anvil top part is hot or have any temperature at all.

The section checking the base does check its temperature: https://github.com/anegostudios/vssurvivalmod/blob/47b8a492f77c53ad121980bcce9f0778791fdbb5/BlockEntity/BEAnvilPart.cs#L147

Also there are two unused strings for this in the translations. See image below. Only the string with the key `"Too cold to weld, reheat the part on the forge."` is used.

### Screenshots

![Screenshot from 2024-12-22 15-46-07](https://github.com/user-attachments/assets/ef52dda7-4f5e-46c6-a3c9-81f5e6c2cfb9)

![Screenshot from 2024-12-22 16-02-43](https://github.com/user-attachments/assets/80447545-cd20-4855-abc4-c4bfd1f8a87b)

### Logs

```Crash```

**Comment by pizza2004** [comment]
Should be fixed in the next release.
