### ISSUE TITLE
Aged Armour Stand Generated Wearing a White Nadiyan Peasant Hat with Durability

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4776]
### Game Version

v1.20.0 rc-5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

This is a very strange one but it's exactly as the title says.

Inside a ruin, this armour stand generated with a white Nadiyan peasant hat. The hat has a durability bar for some reason, too.

### Screenshots

![2024-12-23_12-10-38](https://github.com/user-attachments/assets/1d7d5c34-37c0-4b35-b57d-d401a8e786f0)
![2024-12-23_12-12-40](https://github.com/user-attachments/assets/0bac65bb-f226-40fb-b4b7-8d004320a243)

### Logs

```Crash```

**Comment by radfast** [comment]
Thanks for reporting.  Any chance you can please go back to this ruin, stand inside, and type this command in chat:  `/wgen pos structures`.   This will tell us the precise name of the ruin, which will hopefully let the issue be solved quickly.

**Comment by ifozz** [comment]
> Thanks for reporting. Any chance you can please go back to this ruin, stand inside, and type this command in chat: `/wgen pos structures`. This will tell us the precise name of the ruin, which will hopefully let the issue be solved quickly.

Gotcha. It may take me a little bit to trek back but it shouldn't be too long.
Can I keep this hat around by the way? It's pretty cute and I was wondering if the fact it has a glitched durability bar would in any way corrupt/interfere with anything.

**Comment by radfast** [comment]
I don't think the hat will break anything (famous last words). A hat is still a hat, even if it has durability. Did you try wearing it already?

**Comment by radfast** [comment]
BTW you can use command `/tp -1554 95 -719` to go back there instantly, assuming you have command permissions (if it's your own singleplayer game, you do automatically)

**Comment by ifozz** [comment]
> I don't think the hat will break anything (famous last words). A hat is still a hat, even if it has durability. Did you try wearing it already?

Yeah, it can be worn and repaired as per normal. Far as I can tell it's just a normal clothing item with durability for some reason.

Nearly at the ruin, I'll have the info in a second. Completely forgot I could TP there haha

**Comment by ifozz** [comment]
> BTW you can use command `/tp -1554 95 -719` to go back there instantly, assuming you have command permissions (if it's your own singleplayer game, you do automatically)

Alright, it's the
undergroundruin/s-art-treasury

**Comment by ifozz** [comment]
Oh also, this same ruin has a book in a display case with zero associated lore. Completely blank, no attached lore when viewed in dev mode.

**Comment by ifozz** [comment]
I'm probably also going to fix the hat to 100% and then swap it with an identical one through creative. Just to put my mind to rest that it won't cause anything else to glitch out haha

**Comment by radfast** [comment]
> Alright, it's the undergroundruin/s-art-treasury

Awesome thank you, much appreciated

**Comment by radfast** [comment]
Sorry one more question for you.  This game world, which game version was it first generated in?  (You can see from the Singleplayer world selection screen, if you click on the pencil 'edit' icon next to the world name, then it will show you)

**Comment by ifozz** [comment]
> Sorry one more question for you. This game world, which game version was it first generated in? (You can see from the Singleplayer world selection screen, if you click on the pencil 'edit' icon next to the world name, then it will show you)

This was made in rc-1 and has subsequently been updated throughout the rc's. These chunks the ruin was in might have been generated in either rc1, rc2 or rc3.

**Comment by Th3Dilli** [comment]
thanks, this will be fixed in next release
