### ISSUE TITLE
Crock Pots not getting shelf spoilage benefits.

### ISSUE THREAD

**Issue by Darkx352** [anegostudios/VintageStory-Issues#4787]
### Game Version

v1.20.rc5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

In RC.5 in single or MP mode with ZERO mods. Crock pots are not getting their shelf parish speed reduction.
I tested this in pre.13, and the parish is applied, but in rc.5, it is not.

I tested this in a cellar on multiple save games. And version to confirm. XOXO Darkx.

### How to reproduce

This can be recreated by cooking food and putting it in a crock pot. Then, set it on the floor to get its base timer. and then on a shelf, the modifier doesn't apply. It will have the same timer.

**Comment by Bughaw** [comment]
Shelves are not supposed to add an additional storage buff.  There was a bug that was patched in rc5 that applied the cellar's buff twice.

**Comment by Darkx352** [comment]
![image](https://github.com/user-attachments/assets/5a7be1cc-6625-4e2a-80a4-7cbcbcc57c5b)
Then, the top description needs to be removed.
