### ISSUE TITLE
Fruitpress doesn't press (RC6 only, previous were okay if buggy)

### ISSUE THREAD

**Issue by Perturbee** [anegostudios/VintageStory-Issues#4794]
### Game Version

1.20.0-RC6

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Fruitpress screw-press doesn't work at all, you can fill it with fruit, but the press doesn't work. All you can get is wet mash.

### How to reproduce

1. grab a fruitpress (either make one or pick one from creative) and a bucket and enough fruit
2. fill the fruitpress to full
3. try to use the screw at the top, it doesn't work.

### Logs

Nothing in the logs.

**Comment by Perturbee** [comment]
Never mind, I'm dumb. 
The action used to be initiated with right-click, now it's CTRL-right-click.

**Comment by radfast** [comment]
Does the block interaction help for the Fruit Press now correctly tell you it's Ctrl + right-click?

**Comment by Perturbee** [comment]
It doesn't tell me anything, that's the problem. I had to find out by creating a new world.
![2024-12-25_16-18](https://github.com/user-attachments/assets/ce75d860-38b3-4734-a5ad-64d3db1cf8d6)

**Comment by Craluminum2413** [comment]
@Perturbee Do you have tooltips enabled? You can press `Ctrl + B` to show them

**Comment by Perturbee** [comment]
Ctrl-B removes the tooltip at the top, it turns out it's Ctrl-N and that made them show again. I don't know at which point I disabled those.
