### ISSUE TITLE
Archives Doors Lack Collision

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4807]
### Game Version

v1.20.0 rc-6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The entry doors to the archives have no hitboxes. Cannot even mine them.
These were however generated in rc2, so please inform me if this is just a case of needing to run /wgen regen 1
(I did regen the archives in rc3 but that could still be a root cause here).

### Screenshots

![image](https://github.com/user-attachments/assets/aa51b423-ae83-426b-94b4-fb25942bf800)

### Logs

```Crash```

**Comment by pizza2004** [comment]
This happened only with these entry doors and no other doors anywhere in your world?

**Comment by ifozz** [comment]
> This happened only with these entry doors and no other doors anywhere in your world?

No, only these entry doors specifically. Not other doors in the world or in the archives it seems.

**Comment by pizza2004** [comment]
And can you confirm they were working when you regenerated it, before reloading in rc.6?

**Comment by ifozz** [comment]
> And can you confirm they were working when you regenerated it, before reloading in rc.6?

That I cannot. I never attempted to collide with them before rc6.

**Comment by ifozz** [comment]
Just regenned the archives and the doors are normal, so it has been fixed for me now. Rc6.

**Comment by pizza2004** [comment]
If you end up having a problem again, especially in a reproducible way, feel free to open up the ticket again. :)
