### ISSUE TITLE
1.20rc6 Recipe for Table with marble not working

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4818]
### Game Version

1.20rc6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Puting all ingredients for table with marble board not working. Not workin´n on heavilly moded SMP and also in single vanilla.

### Screenshots

![2024-12-28_11-31-55](https://github.com/user-attachments/assets/fec6a967-e475-42a5-881b-761604cf4f65)

### Logs

```Crash```

**Comment by Craluminum2413** [comment]
@DejFidOFF What material is saw made of?

**Comment by Craluminum2413** [comment]
This recipe allows `meteoric iron` and `steel` saws only

**Comment by radfast** [comment]
In next version, I've added some handbook text which makes clear that steel or meteoric iron saw is required.
