### ISSUE TITLE
Horns and antlers not harvestable from deer and goats

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#4819]
### Game Version

1.20.0-rc.6

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Killing and harvesting a deer or goat with horns/antlers no longer gives them as an item, the way it did in 1.19.

### How to reproduce

1. Kill a goat or deer (other than water deer) during an age/season where it has horns/antlers.
2. Harvest the corpse with a knife
3. You can get meat, fat, hide, but no antlers

### Screenshots

On 1.20.0-rc.6:
![Screenshot at 2024-12-28 08-07-42](https://github.com/user-attachments/assets/36b8f69a-3094-4940-a8c1-e46b2f202f50)

On 1.19.8:
![Screenshot at 2024-12-28 08-10-52](https://github.com/user-attachments/assets/5c3e113f-e0c0-4a5d-81e4-c06be541d4b8)

### Logs

```Crash```

**Comment by ThyCaptainOats** [comment]
Butchering Mod author here. The old system was seemingly paved over in the new update. A fix for this would stop people telling me my mod is causing this issue. 

Thank you!

**Comment by pizza2004** [comment]
Should be fixed in the next release.
