### ISSUE TITLE
Traversing along a wall diagonally left/right different.

### ISSUE THREAD

**Issue by FewChar** [anegostudios/VintageStory-Issues#482]
**Game Version:** 1.2.8
**Platform:** Windows
**Modded:** No

### Description
When walking along a wall diagonaly, depending on whether you are going with the wall to the left and the drop to the right, or vice versa, one way you fall, one way you traverse.

### How to reproduce
imagine 4 Blocks seen from the top:

1 2
3 4

2 and 3 are the same height, 1 is higher, 4 is lower.
Without jumping, moving from block 2 to 3 works, moving from 3 to 2, you fall down.

### Expected behavior
Both should be the same (preferably IMHO you should be able to traverse.

**Comment by FewChar** [comment]
Ok, I have done more tests, The issue stands, but the rules are different:
It depends on whether you are going north/south or east/west

Imagine this as a map of 9 blocks, north being at the top:
a b c
d e f
g h i

They have the heights:
0 1 0
1 2 1
0 1 0

b -> d  # works
b -> f  # works
h -> d # works
h -> f # works

d -> b # falls
d -> h # falls
f -> b # falls
f -> h # falls

**Comment by copygirl** [comment]
I have run into this issue myself and was bothered by it a lot. There is a fix available, but we've pushed it back to 1.13 to give it enough time to be tested internally, and in the coming 1.13 pre-releases, to make sure there is no glitching into walls or similar.

Thank you for reporting.

**Comment by Craluminum2413** [comment]
Has this been fixed?

**Comment by copygirl** [comment]
I believe so.
