### ISSUE TITLE
Deer not shedding antlers

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#4821]
### Game Version

1.20.0-rc.6

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Deer do not drop an antler item on the ground when the antlers go from full grown to recently shed.

### How to reproduce

1. Obtain a male deer. I tested with white-tailed deer but it should be the same for any species except water deer.
2. Watch him at 6 am on Feb 3
3. Notice that he loses his antlers, but does not drop them as an item

### Screenshots

![Screenshot at 2024-12-28 10-24-41](https://github.com/user-attachments/assets/5cc7e41b-c409-49b1-92d3-4d9d26ae36db)
No item is dropped in between these
![Screenshot at 2024-12-28 10-24-55](https://github.com/user-attachments/assets/738d637a-6fd3-46b2-baf5-36ea8942a6e7)

### Logs

```Crash```

**Comment by ThyCaptainOats** [comment]
Butchering Mod author here (again). The old system was seemingly paved over in the new update. A fix for this would stop people telling me my mod is causing this issue.

Thank you! x2

**Comment by pizza2004** [comment]
This should be fixed in the next release.
