### ISSUE TITLE
SmeltedRatio of 6 to 1 ingot results in rounding error giving back only 99 units of metal

### ISSUE THREAD

**Issue by remd** [anegostudios/VintageStory-Issues#4823]
### Game Version

v1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I'm trying to write a small mod that allows the player to smelt tools back into ingots. I've overridden arrowheads to set smeltedRatio to 6 and smeltedStack to 1 ingot of the appropriate metal.

This should allow the player to smelt 6 arrowheads back into 100 units of metal using the crucible. The text of the crucible states that 100 units will be given but only 99 are received when the smelting finishes.

I believe the issue lies in the lack of Math.round() inside DoSmelt() in BlockSmeltingContainer in the non-alloy code path. https://github.com/anegostudios/vssurvivalmod/blob/master/Block/BlockSmeltingContainer.cs#L124

Some Discord discussion around this bug: https://discord.com/channels/302152934249070593/351624415039193098/1322668666113753089

### How to reproduce

1. Create minimal content mod that adds combustiblePropsByType to game:itemtypes/toolhead/arrowhead and makes crucibles large enough to hold arrowheads.
```
[
  {
    "file": "game:blocktypes/clay/crucible",
    "op": "replace",
    "path": "/attributesByType/crucible-burned/maxContentDimensions",
    "value": {"width": 0.5, "height": 0.5, "length": 0.5}
  },
  {
    "file": "game:itemtypes/toolhead/arrowhead",
    "op": "add",
    "path": "/storageFlagsByType",
    "value": {
      "*-copper": 4
    }
  },
  {
    "file": "game:itemtypes/toolhead/arrowhead",
    "op": "add",
    "path": "/combustiblePropsByType",
    "value": {
      "*-copper": {
        "meltingPoint": 1084,
        "meltingDuration": 10,
        "smeltedRatio": 6,
        "smeltedStack": { "type": "item", "code": "ingot-copper", "stacksize": 1}
      }
    }
  }
]
```
2. Smelt 6 copper arrowheads in a crucible (crucible states 100 units of Copper will be created)
![image](https://github.com/user-attachments/assets/62a0bc07-50f2-4879-9961-633981f5e58f)
3. Only 99 units of Copper are given in the resultant crucible
![image](https://github.com/user-attachments/assets/84d3efd3-5fdd-4d56-9797-900c28e65f59)

### Logs

[client-main.log](https://github.com/user-attachments/files/18268004/client-main.log)
[server-main.log](https://github.com/user-attachments/files/18268005/server-main.log)

**Comment by pizza2004** [comment]
Should be fixed in the next version.

**Comment by remd** [comment]
Thanks so much!
