### ISSUE TITLE
Game Audio not working through VM audio systems.

### ISSUE THREAD

**Issue by Dragoness669** [anegostudios/VintageStory-Issues#483]
**Game Version:** 1.12.8 (stable)
**Platform:** Windows
**Modded:** No

### Description
No audio running for the game whatsoever. Windows Advanced setting registers the game audio, switching channels has no result. 
I have the same problem with Vanilla Minecraft, both Native Launcher and MultiMC. 
If Vintage Story uses the same audio engine as Minecraft, then there might be something on my side, and not the game. I know several other friends can hear audio just fine.

### Screenshots
Windows Audio Settings [![Screenshot from Gyazo](https://gyazo.com/5a208a887c01ee63a7bcb5e913c1b75c/raw)](https://gyazo.com/5a208a887c01ee63a7bcb5e913c1b75c)

Loadup log from Minecraft [![Screenshot from Gyazo](https://gyazo.com/0355302238949313ccd4f845023b9afe/raw)](https://gyazo.com/0355302238949313ccd4f845023b9afe)

**Comment by Bloodsaw** [comment]
I'm using the advanced audio myself. Sometimes its a bit buggy after clean reboots, but most of the time its working. I am able to switch VS from default to any other audio output device. Some games does not like if you switch the audio output at runtime. (even experienced crashes and no-sound issues in other applications). For example VS only needs a restart after switching.

**Comment by Dragoness669** [comment]
That doesn't help either, no sound at all even with default settings and
audio engine reset.

**Comment by Bloodsaw** [comment]
Have you tried to select the audio output ingame? Or maybe you already configured it there resulting in negating the windows setting.

**Comment by Dragoness669** [comment]
nope, I have all the sound bars maxed, and no options to change outputs
through the game interface

**Comment by tyronx** [comment]
@Dragoness669 you can change the output in the latest version.

> BloodsawLast Saturday at 11:45 AM
> @Tyron relating to #483 on github. Is there any way to debug the openAL module? *edit: for me

Well, since it looks like to be a fault of the OS/OpenAL system itself, you could make an example application for that purpose

**Comment by Bloodsaw** [comment]
It seems it is some incompatibility between his device and openAL. 
I don't know if @tyronx is already using the OpenAL-Soft libraries, since the original openAL from creative is quite outdated. https://github.com/kcat/openal-soft

**Comment by Dragoness669** [comment]
I need to close this ticket.. sound was restored in the 1.12.09 update.. I
was able to set the sound channel and it started working. I was in the
Discord at the time talking about it. funny thing tho, I also can hear
Minecraft sounds now too.. even after I had to roll back to 1.12.08 cause
Akliz only updates their versions every Monday, I still had sounds working.
We're playing 1.12.11 now on our server, we plan to update to .13 when our
server provider updates their listing.

**Comment by Bloodsaw** [comment]
As per requested by @Dragoness669 the issue is resolved for now and ticket should be closed.
