### ISSUE TITLE
Missing from translation files strings

### ISSUE THREAD

**Issue by Damglador** [anegostudios/VintageStory-Issues#4831]
### Game Version

v1.19.8

### Platform

Linux

### Modded

Vanilla

### Description

I checked if strings for it are available on Crowdin and have a mod that updates translation to the latest from Crowdin.

Untranslated parts are:
- Checking {mod name}
- ...success!
- {size} downloaded. Mod installed.

"Checking {0}" seems to be available on Crowdin, but either it was translated too late and isn't updated by my mod, or it's just not used here. Other strings in the list aren't available on Crowdin

### How to reproduce

1. Switch game language to Ukrainian
2. Go to https://mods.vintagestory.at/list/mod
3. Select any mod
4. Do 1-click install
5. Get the progress menu in game

### Screenshots

![image](https://github.com/user-attachments/assets/a180aadd-3363-47c4-8715-aa752d8a8c97)

**Comment by Damglador** [comment]
Found another missing string (Obtained by killing & harvesting)
![Знімок 2024-12-30 04:07:53](https://github.com/user-attachments/assets/7b6f4b95-855d-493c-9b98-6727ecfc8874)
On Crowdin
![image](https://github.com/user-attachments/assets/f06a6238-e2e6-4b42-9e42-407cd9e92d96)

**Comment by radfast** [comment]
Thank you for reporting.   On the second one, this string is now (or very soon will be) in CrowdIn:

	"handbook-obtainedby-killing-harvesting": "Obtained by killing & harvesting",

(but you'll need to update to game version 1.20.0-rc.7 when it comes, to have it)

We'll look at the first one

**Comment by radfast** [comment]
And the first ones should now be fixed in 1.20.0-rc.7.  "Checking {0}..." was already in CrowdIn, we just did not use it properly, now we do.  We have added one more new string to CrowdIn:

	"mod-successfully-downloaded": "<font color=\"#80ff80\">success</font>! {0} kb downloaded. Mod installed."

-----

@Damglador, question for you, which fonts do you use in your `clientsettings.json` for best display of Cyrillic characters on Linux?  Looks good in your screenshots

**Comment by Damglador** [comment]
@radfast     
```
"defaultFontName": "sans-serif",
"decorativeFontName": "Lora",
```
Didn't change them.

**Comment by radfast** [comment]
> @radfast
> 
> ```
> "defaultFontName": "sans-serif",
> "decorativeFontName": "Lora",
> ```
> 
> Didn't change them.

Thanks, looks like Linux handles those settings better than Windows then.  On Windows, we sometimes have missing characters, in Ukrainian language, for the fonts it selects.  If I knew a better font to use, we can have the code automatically switch to it when the language is changed to Ukrainian.
