### ISSUE TITLE
1.20 rc.6 Bowtorn don't disappear after temporal storm

### ISSUE THREAD

**Issue by MonsterHorns** [anegostudios/VintageStory-Issues#4836]
### Game Version

1.20 rc.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Bowtorn spawned during a temporal storm don't disappear when the storm ends, resulting in the player getting instantly killed after going out of cover. Similar thing happens after a regular night, they don't run away with daylight, but there are not as many so it's manageable at least.

### How to reproduce

1. Wait for a temporal storm
2. Hide in a hole
3. Wait for the storm to end
4. Dig out and try to run away
5. Get shot at from all directions and die in 2 seconds

### Logs

```Crash```

**Comment by Craluminum2413** [comment]
It is intended, read comments below
https://github.com/anegostudios/VintageStory-Issues/issues/4667#issuecomment-2553384336
https://github.com/anegostudios/VintageStory-Issues/issues/4565#issuecomment-2500795505
