### ISSUE TITLE
A stack of items in a firepit loses its temperature every time a single item is smelted

### ISSUE THREAD

**Issue by Orangutanion** [anegostudios/VintageStory-Issues#4838]
### Game Version

v1.20

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

When smelting a stack of items in a firepit (like lime, flint, bushmeat, etc), you need to first heat up the whole stack of items before one item smelts. However, when you do smelt one item out of the stack, the entire stack loses its temperature, and you need to resmelt the stack once more. This behavior is not realistic. In real life, when you boil a pot of water, the pot of water does not lose its temperature when some of the water boils off. Material stays at its boiling/melting point and then changes state once extra energy is added. 

Players commonly fix this with the [BetterFirepit mod](https://github.com/LeggyJameh/BetterFirepit). All this mod does is add two lines of code in the ‎BlockEntityFirepit::smeltItems method to maintain stack temperature. The vanilla behavior of the firepit consumes a lot of fuel to smelt a small quantity of items, and there is a strategy to get behind this by removing all but one item right before an item smelts so that the rest of the stack does not reset temperature. Players should not be incentivized to do this. 1.20 makes it so that now you need to smelt flint with coal to get fireclay, so this behavior is no longer avoidable for basic progression.

### How to reproduce

1. Put 8 flint into a firepit
2. Heat it up with coal
3. When one flint smelts, the 7 remaining flint will lose all temperature that had accumulated, and you will now need to heat up 7 flint to continue smelting.
4. Once the 7 flint is heated up to 1050C, remove all flint and then insert one flint. Now you're holding 6 flint at 1050C in your hand so none of it loses temperature when the one flint smelts. You can keep inserting hot flint from your hand to quickly smelt it without needing to reheat the whole stack of flint.

**Comment by Craluminum2413** [comment]
https://discord.com/channels/302152934249070593/1289213132266541066/1289343311584170107
