### ISSUE TITLE
Wind mill does not rotate anymore in 1.12.9 stable

### ISSUE THREAD

**Issue by SWEIHER** [anegostudios/VintageStory-Issues#485]
**Game Version:** 1.12.9 (stable)
**Platform:** Windows
**Modded:** No

### Description
Wind mill does not run anymore after update from 1.12.8.

### How to reproduce
There was a wind mill with 4 sails running perfectly before update. After update it doesn't run. So I added another sail to get 100%. But even with 68% wind power and 100% sail power it won't run. I made a new and higher mill and destroyed all fences around but no rotation anymore. 

### Expected behavior
Rotating windmill at 68%/100% of the rotor

### Screenshots
![image](https://user-images.githubusercontent.com/27846274/77225298-233d0e80-6b6e-11ea-8370-0fed3713777e.png)
![image](https://user-images.githubusercontent.com/27846274/77225349-7f079780-6b6e-11ea-8fa3-48718cf9b685.png)

### Logs
n/a

**Comment by SWEIHER** [comment]
Additional information: The game was running on PC #1 with open to LAN und I played on PC #2 while the problem occured.

**Comment by SWEIHER** [comment]
Works again in 1.12.11

**Comment by copygirl** [comment]
Thanks for confirming!
