### ISSUE TITLE
Using the Hammer on a tree log resets your position & causing server exceptions

### ISSUE THREAD

**Issue by Bloodsaw** [anegostudios/VintageStory-Issues#486]
**Game Version:** 1.12.9
**Platform:** Windows 10
**Modded:** No

### Description
If you use a hammer on a tree (did it by accident, thought it was the axe...) your position resets constantly and the server-event and server-main is flooded with events/exceptions.

For me I am able to reproduce this at wish.

### Expected behavior
Nothing should happen since the hammer cannot break the log.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![image](https://user-images.githubusercontent.com/61588797/77235676-3f659d80-6bb8-11ea-8b74-6ca92eb34089.png)

### Logs
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4364006/server-main.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/4364007/server-event.txt)

**Comment by tyronx** [comment]
lolwut, how does it even :O

**Comment by tyronx** [comment]
thanks a lot, if been searching for the source of this exception spam for a while now. fixed for next version

**Comment by Bloodsaw** [comment]
Fixed in 1.12.13 (stable).
Tested and confirmed.
