### ISSUE TITLE
shift klick bug? 

### ISSUE THREAD

**Issue by eloki** [anegostudios/VintageStory-Issues#487]
on 1.12.10
shift klick to put an itam from my inventory to a chast... 
game stopt working 

**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by eloki** [comment]
i did it agan i wantet to put a arc stam in to a barral form a chast with shift klick. game brock dwon agan ... so dont pres shift klick ^^ at the moment

**Comment by eloki** [comment]
ok you can pras shift klick to geht stuf out of the beral but not in to the beral ... if i find out more i will let you know

**Comment by eloki** [comment]
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4365115/client-crash.txt)

**Comment by tyronx** [comment]
fixed, thank you!
