### ISSUE TITLE
Item in hand not synchronized across MP when item is consumed

### ISSUE THREAD

**Issue by threeheadeddingo** [anegostudios/VintageStory-Issues#489]
**Game Version:** 1.12.11
**Platform:** Windows
**Modded:** Yes, copygirl's CarryCapacity mod

### Description
In a multiplayer game, any action that causes you to consume an item in your hand does not synchronize your hand's new state to other players. As a result, other players will still see you as holding that item even if it has been consumed and is now gone. Hand state will only update upon switching to a new item or clearing by switching to an empty hotbar slot.

So for instance, if you see a player eating their last cranberry, after they eat it, you will still see that they are holding a cranberry although they no longer have one. This goes for seemingly any "consumption" action that is not the player actually switching items.

### How to reproduce
1. In a MP game, observe a player holding a consumable item in their hand, such as cooked meat or a berry (for example).
2. Player eats the food, or "consumes" the item some other way if it's something else.
3. Player's hand still appears to be holding that item even after it is consumed.

### Expected behavior
You would expect the other player's hands state to be synchronized.

**Comment by copygirl** [comment]
While that will be a good way to reproduce it, I've also noticed desync issues with held items happening in other cases: Not being able to see someone's offhand item (torch) or them holding an item that they don't even have in their inventory.

**Comment by tyronx** [comment]
Thanks for the report. Made it so that it just broadcasts the hotbarslot every time its modified, on the engine side. So should be fixed next version

**Comment by Bloodsaw** [comment]
@threeheadeddingo Please try again in 1.12.13 and confirm if this is fixed.

**Comment by threeheadeddingo** [comment]
This does finally appear to be fixed as intended. Haven't tested exhaustively, but I'm confident enough to close the issue if that's alright.
