### ISSUE TITLE
Lantern panes rendering inconsistently based on hand/viewing angle/etc.

### ISSUE THREAD

**Issue by threeheadeddingo** [anegostudios/VintageStory-Issues#491]
**Game Version:** 1.12.11
**Platform:** Windows 10 x64
**Modded:** Yes, CarryCapacity

### Description
When carrying a lantern in the right hand, a single pane appears missing. When in the left, all panes appear missing. Other players' lanterns also have panes not rendering based on where you're looking in relation to them.

### How to reproduce
1. For the render error in your own hands, simply observing and swapping the lantern between hands seems to always produce this error.
2. To witness this error in other people's lanterns, you may have to walk around them a bit until viewing them at an angle at which the error occurs.

### Expected behavior
All lantern panes should be rendered at all times.

### Screenshots
![2020-03-25_20-21-39](https://user-images.githubusercontent.com/62622422/77627385-cf874800-6f14-11ea-823c-bec1e549dae2.png)
![2020-03-25_20-21-55](https://user-images.githubusercontent.com/62622422/77627408-d7df8300-6f14-11ea-808c-e7fc31c9a258.png)
![2020-03-25_20-22-07](https://user-images.githubusercontent.com/62622422/77627419-dca43700-6f14-11ea-8143-81ea4b0dbaef.png)

Note that in the first screenshot, my lantern is missing a pane. The other player's lantern appears correctly. When switching to the left hand, all panes disappear. Last shot shows walking around the other player until a pane on their lantern disappears.

**Comment by tyronx** [comment]
thanks for the report. fixed in 1.13-pre.11
