### ISSUE TITLE
Map resets on every start

### ISSUE THREAD

**Issue by balloonhead** [anegostudios/VintageStory-Issues#495]
**Game Version:** 1.12.8 - 1.12.13
**Platform:** Windows
**Modded:** No

### Description
Everytime I start the game and load my savegame the map is resetted and I'm missing all the explored parts of it. Only the waypoints are still there.

### How to reproduce
1. run around so the large map gets some more information
2. check the map so you see how big the worldmap is
3. quit to the main menu
4. load the savegame
5. Map is resetted and starts new.

### Expected behavior
All the worldmap data should be there. All explored landscapes should be on the map.

**Comment by copygirl** [comment]
Currently "works as intended". The map is temporary, and can only store so many "chunks" at the same time. However, it is a feature that will be worked on in the future.
