### ISSUE TITLE
Butchering underwater

### ISSUE THREAD

**Issue by Dafri84** [anegostudios/VintageStory-Issues#496]
When a creature dies in water and sinks to the bottom, when you harvest the creature you cannot loot it it until you quit and relaunch the map. You'll be able to "empty" the inventory but you won't get anything.
Seen with mountain goats both male and female,

**Comment by copygirl** [comment]
Next time you report a regular bug, please use one of the provided [issue templates](https://github.com/anegostudios/VintageStory-Issues/issues/new/choose). Then I wouldn't have to ask which version of the game are you running.

It sounds like an issue that was reported and from what I remember fixed, but perhaps it has somehow snuck back in..?

**Comment by Dafri84** [comment]
Sorry for not using the templates, but I am using the most current stable version 1.12.13 I do believe.

**Comment by tyronx** [comment]
Fairly sure this has been fixed in v1.12.14. Please reopen otherwise. Thanks for the report.
