### ISSUE TITLE
Cooking roots results in a broken meal

### ISSUE THREAD

**Issue by lOmicronl** [anegostudios/VintageStory-Issues#497]
**Game Version:** 1.12.13
**Platform:** Windows
**Modded:** No
**Localization:** English (default)

### Description
Cooked cattail roots are valid cooking ingredients; the game allows them in the cooking pot, and the pot will process them to make a meal. This is different from, for example, uncooked roots - which will not cause the pot to start processing no matter in what combinations you put them into it.

However, no valid meal is generated when using these cooked roots as primary ingredients.

### How to reproduce
1. Place at least two cooked cattail roots into a cooking pot on a fire.
2. Observe the preview of which meal this will generate; it shows a broken string, not a valid meal type. However, the pot will begin processing.
3. After the meal is cooked, take the pot off the fire. Observe the description. Usually, it lists the nutrition provided by the meal. There is no such number here.
4. Place the pot, and fill a bow from it. The filled bowl lacks a food texture and, once again, has a broken description.
5. Eat the meal. Observe that you get exactly the same amount of nutrition as if you ate the ingredient roots individually. The 50% cooking bonus is not applied.

### Expected behavior
Cooked cattail roots provide vegetable nutrition, and thus should result in a vegetable stew when cooked in a pot.

Alternatively, if they are not supposed to be a vegetable stew starter, they should not cause the pot to begin processing a meal.

### Additional notes
Due to a lack of other foods, I have not yet tested what happens if cooked cattail roots are added as secondary ingredients to a normally valid meal.

**Comment by copygirl** [comment]
> Eat the meal. Observe that you get exactly the same amount of nutrition as if you ate the ingredient roots individually. The 50% cooking bonus is not applied.

FYI the cooking bonus is not a hardcoded 50% - each ingredient has a second property that defines how many nutrients it will provide when cooked. I presume this defaults to the non-cooked food value if not present.

Interesting though. I don't think cattail roots are supposed to be able to be used as part of a meal.

**Comment by lOmicronl** [comment]
Hmm. I see now what you mean. What does the wiki refer to, then, when it states that "Meals have a 50% extra satiety bonus from the ingredients' total satiety"? On the same page, the word 'sateity' is used to refer to the hunger bar, so my first instinct was to take it as referring to the amount the bar is restored.

Of course, the wiki can be wrong =P Especially when multiple authors get their terminology crossed. Does it refer to the grace period before the bar starts dropping again, then?

And as for the cooked cattail roots, perhaps they are simply autodetected by the cooking system because they have a valid vegetable nutrition value? If that's all the cooking pot checks for when determining a potential meal, that could be why it starts processing.

**Comment by copygirl** [comment]
Maybe the wiki just makes a wrong assumption - though it's true that it's roughly 50%. I didn't look into the code for meals so I, too, just go by what I assume is happening, considering the existence of the `nutritionPropsWhenInMeal` property.

Regarding the naming, **Satiety** is your hunger bar, and **Nutrition** is the 4 food categories you can fill (which improves your maximum health). My guess is that if you eat a food that gives you, say, 100 fruit nutrition, you increase your fruit nutrition bar by 100, as well as your satiety / hunger bar by 100.

**Comment by tyronx** [comment]
I think i fixed that in v1.12.14 already. Just tested in v1.13 - 2 cattail roots do not create a valid meal anymore now. Thanks for the report!
