### ISSUE TITLE
Simple improvement of screenshot organization

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#50]
Please consider adding a client config option which sets the current value of directory where screenshots are located.
If set to an absolute path - obvious behavior. If into a relative path - means that it is a sub path in the default location.

This will allow to categorize screenshots hierarchicly, e.g. categories bugs,ore,server,single,caves,... using macroses which will redefine the path dynamically.

E.g. Ctrl-O will define path to "officialServer/ores" so the next screenshot will go there.
Ctrl-Shift-O to "single/ores", Ctrl-Shift-B - to "officialServer/bugs".
I will be even able to set Ctrl-B to place bug screenshots into Dropbox synced directory, to reference them in tickets.

Same might be useful for videos, but at least for me the screenshot library is growing much faster than videos.

**Comment by Craluminum2413** [comment]
It would be better to add new video codecs

**Comment by Heptagon-ru** [comment]
1. Cral's comment is 100% offtopic
2. My suggestion is now irrelevant, with the introduction of waypoints. Please close the ticket as obsolete.

**Comment by Heptagon-ru** [comment]
Oh wait I can close myself! Closing the ticket as obsolete with waypoints addition.

**Comment by Craluminum2413** [comment]
I meant folders for different codecs
