### ISSUE TITLE
Outfit Selector Opens After Initial World Creation

### ISSUE THREAD

**Issue by Rainboux** [anegostudios/VintageStory-Issues#501]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
Whenever selecting a previously saved world the outfit selector comes up. 

### How to reproduce
1. Open a previously saved world.
2. Outfit selector reopens upon entering world even after having selected outfit before.

### Expected behavior
Not have to choose outfit after opening a saved world every time. 

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
No crash associated with issue.

**Comment by Bloodsaw** [comment]
I changed the type to suggestion, cuz I think that is the way it is intended atm.
If you don't want to select any clothing, you just use the lower right button and save your choice. You will be never asked again even without choosing any clothes. 

The reoccurring is helpful if you unintentionally closed the window or want to select the clothing later. 
Please reach back if this answers your question/issue and if not add a suggestion how you would like that the game behaves.

**Comment by tyronx** [comment]
No response in several months, closing issue.
