### ISSUE TITLE
Sleeping does not accelerate healing

### ISSUE THREAD

**Issue by lOmicronl** [anegostudios/VintageStory-Issues#502]
**Game Version:** 1.12.13
**Platform:** Windows
**Modded:** No

### Description
When the player is wounded, satiation consumption is increased, and health slowly regenerates over time.

When the wounded player sleeps in a bed, time is accelerated. This causes the increased satiation consumption to accelerate as well. However, the health regeneration rate is not affected by the sleeping speedup. The player is essentially penalized for no return.

### How to reproduce
1. Injure yourself. Note your current HP.
2. Sleep in a bed, any bed.
3. Note your HP after you wake up.
4. Now wait how long it takes to regenerate the same amount of HP while not sleeping. It will be immediately clear that no accelerated healing occured during the sleeping period.

### Expected behavior
Healing should accelerate at the same time as other processes in the world - at least. Perhaps bedrest should in fact convey a small bonus.

**Comment by Craluminum2413** [comment]
This is how it can be fixed
<https://github.com/Craluminum-Mods/HealingWhileSleepingFix/blob/main/src/EntityBehavior/EntityBehaviorFixedHealingWhileSleeping.cs>

**Comment by noelle-lavenza** [comment]
Should probably scale `recoverySpeed` in `EntityBehaviorHealth.OnGameTick` by `SpeedOfTime`. Note that if done in the wrong spot, this would increase the autoheal hunger drain as well, stacking on top of the already-high hunger drain from sleeping.

**Comment by Th3Dilli** [comment]
thank you for reporting and the feedback

we now have changed the updating of the health and hunger stats to be dependent on ingame time and thus it will automatically accelerate with speed-up time

further, we added a worldconfig to adjust the health regeneration so it can be adjusted the same as the hunger rate in the world creation customization screen or via the command `/worldconfig playerHealthRegenSpeed 1`

this is going to be part of 1.19
