### ISSUE TITLE
Papyrus acts like cattails

### ISSUE THREAD

**Issue by Caeleron** [anegostudios/VintageStory-Issues#503]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
OnBlockBroken for BlockReed drops cattail items when papyrus is also considered a BlockReed. 

### How to reproduce
Breaking a papyrus plant drops a cattail item.

### Expected behavior
Papyrus should drop papyrus and papyrus root rather than their cattail counterpart.

**Comment by copygirl** [comment]
This is intentional, for now. The eventual papyrus item should be usable in the same recipes that cattail is, but to allow such would require going through and changing a lot of recipes, and possibly other work. You're certainly right, but this change is currently on the back burner.

**Comment by Craluminum2413** [comment]
> https://www.vintagestory.at/forums/topic/4751-the-homesteading-update-v115-pre1/?tab=comments#comment-21652
> Feature: Papyrus now drops papyrus tops and roots
