### ISSUE TITLE
Game detects .DS_Store and hidden files

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#505]
**Game Version:** 1.12.14
**Platform:** Mac
**Modded:** VSHUD

### Description
When loading saves on macOS .DS_Store and hidden files are displayed.

### How to reproduce
1. Add a hidden file.
2. Enter the singleplayer save loading screen.

### Expected behavior
The game should ignore hidden files, those starting with a "." character.

### Screenshots
![image](https://user-images.githubusercontent.com/22282562/79070187-13fb3d80-7ca2-11ea-97c2-a9c802038e76.png)

**Comment by tyronx** [comment]
Thanks for the report, this will be fixed in v1.13-pre.12. It'll only load files with the .vcdbs ending
