### ISSUE TITLE
Can't fuel a bloomery or put anything in it

### ISSUE THREAD

**Issue by wqpvs** [anegostudios/VintageStory-Issues#508]
**Game Version:** 1.12.14
**Platform:** Windows 
**Modded:** No 

### Description
On my multiplayer server, all of a sudden i can't fuel bloomeries. I had run several today, but now i can't. It was at somepoint after i messed up an iron bloom and tried to put it in a bloomery to remelt it? Anyways i couldn't do that and found i couldn't put charcoal in the bloomery; in any bloomery. I've tried using shift and not using shift. I've reset the server, the client etc. Just won't work.

### How to reproduce
1. Bloomery
2. Add coal
3. Does nothing

### Expected behavior
Fuel the bloomery with the coal as before.

**Comment by copygirl** [comment]
The bloomery doesn't allow you to put in more fuel than required anymore. As a side-effect, you need to add what you want to smelt before you put in the fuel.
