### ISSUE TITLE
freshly spawned entities can get hit once without taking any damage

### ISSUE THREAD

**Issue by Eypsi1on** [anegostudios/VintageStory-Issues#512]
**Game Version:** 1.12.14
**Platform:** Manjaro 5.5.18-3
**Modded:** No

### Description
When you start a fresh new world or spawn an animal or drifter or trader their health in creative mode says x/0. x being health they have, the 0 being their maximum. For example hen has max health of 3 so on spawn it says 3/0
Then no matter how strong or weak hit you do the second max health number starts matching their initial health so hen for says 3/3. Then any hit you do starts doing damage as normal. To put it in perspective a black bronze spear throw does 8 damage. A hen can survive that once because of this bug.
What fixes it for all spawned entities is reloading the world (save and quit, then open it back up) or unloading the chunk by going far away and back.
But main problem are drifters as their nature is to spawn around you when underground which guarantees they will have this bug on them and basically gives a fixed 1 extra hit needed to their usual hit to kill count.
Going back in survival for the first hit doesn't matter, the issue persists.
I spawned a ram, waited like 5 minutes as I made lunch irl. The health stayed bugged so time doesn't fix this (or at least in any reasonable amount)

### How to reproduce
1. Start a new world or spawn entities in creative
2. In creative or I guess through debug commands check the entities health as it's x/0
3. Hit it with anything and watch the number change and second hit actually doing damage
4. For drifters go underground via noclip in creative or wait for night and check their health. Nightmare drifters say 40/0

### Expected behavior
They should take damage on first hit after spawn.

**Comment by noelle-lavenza** [comment]
Could not reproduce in 1.18.3.

**Comment by DArkHekRoMaNT** [comment]
As far as I remember it was solved many versions ago
