### ISSUE TITLE
Quern processing: animation trigger but does not process.

### ISSUE THREAD

**Issue by darnuria** [anegostudios/VintageStory-Issues#515]
Game Version: v1.12.14 (Stable)
**Platform:** Linux, Ubuntu 18.04.4 LTS
**Modded:** No
**Processor:** Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
**MonoVersion:** C# Framework: Mono 6.8.0.105 (tarball Tue Feb 4 21:20:20 UTC 2020)

**Immersive mouse mod:** activated

### Description

While using the quern the animation is triggered but the item is not processed.
It seems to be mostly triggered while using the lower part of the block.

### How to reproduce

1. Put processable item in (periodite) quern
2. Click on the lower part (seems to trigger the bug)
3. Animation is triggered but does not process 

### Workaround

To processes again I have to stop using it and reuse it.

### Expected behavior

If I using the quern, It must be functional either by using the upper part or the bottom part or the animation may not trigger at all if using the lower part.

### Screenshots

Here the setup where I encounter the problem.

My cursor is positioned below the "moving part" it's moving but not working.
![Screenshot from 2020-04-21 23-55-49](https://user-images.githubusercontent.com/2827553/80279080-7ec56380-86fb-11ea-8218-db020cb3a7f2.png)

**Comment by tyronx** [comment]
This should be fixed in v1.13, thanks for the report. Please reopen if still present.
