### ISSUE TITLE
Memory leak associated with textures and sounds

### ISSUE THREAD

**Issue by darnuria** [anegostudios/VintageStory-Issues#516]
**Platform:** Linux, Ubuntu 18.04.4 LTS
**Modded:** No
**Processor:** Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
**Memory:** 8 Go ~ 6.5 Go usable by the game
**MonoVersion:** C# Framework: Mono 6.8.0.105 (tarball Tue Feb 4 21:20:20 UTC 2020)
**Immersive mouse setting:** on
**Game Mode**: both creative and survival

### Description

I got run ouf of memory issue quite often after one hour on less of playing sometime more.
and message inviting me to set environment variable `TEXTURE_DEBUG_DISPOSE` to get a trace.

> Note: I noticed a really big latency while opening the inventory with `TEXTURE_DEBUG_DISPOSE` set also something like 1s.

### How to reproduce

1.0 Butchers animals open Harvesting GUI
1.1 Select prospector pick tool mode "F menu"
1.2 Add waypoint through the worldmap
2. Got really noticeable performance issues after a long time
3. Got a crash or reboot the game.

## Settings

Devmode: off

### Graphics

![Screenshot from 2020-04-25 17-15-17](https://user-images.githubusercontent.com/2827553/80283512-5f88ff00-8718-11ea-95c7-4b49e1e30822.png)

### Sound

![Screenshot from 2020-04-25 17-15-42](https://user-images.githubusercontent.com/2827553/80283523-7cbdcd80-8718-11ea-805a-aa4ffeb9c344.png)

### Interface

![Screenshot from 2020-04-25 17-16-39](https://user-images.githubusercontent.com/2827553/80283538-8e9f7080-8718-11ea-8f25-89804a2c2bfc.png)

### Logs

Excerpt of the full log with `TEXTURE_DEBUG_DISPOSE=1`.
At the moment of the log I got no crash in this run

#### Search origin of the leaks

I dived a little bit in the logs I provided, the leaks seems related to Floating GUI:

- Prospecting pick tool mode selector [raffined logs](https://gist.github.com/darnuria/95ffbf7e511aa977c71b2b797a389987#file-2020-04-25-leak-prospecting-pick-skils-select-log)
- Harvestable animal dialog [raffined logs](https://gist.github.com/darnuria/95ffbf7e511aa977c71b2b797a389987#file-2020-04-25-leak-gui-haverstable-animal-log)
- Adding a waypoint through the world map [raffined logs](https://gist.github.com/darnuria/95ffbf7e511aa977c71b2b797a389987#file-2020-04-25-leak-gui-add-waypoint-worldmap-log)

If useful a gist of the `glxinfo` command:
https://gist.github.com/darnuria/a5686d6131353fb3d0b1a0528f3bd813

#### Gist with all the logs

<https://gist.github.com/darnuria/95ffbf7e511aa977c71b2b797a389987>

#### Edit history

- 2020-04-27 I removed the "full log excerpt" and produced more raffined logs excerpt.

**Comment by darnuria** [comment]
Also two question what is the way to report with «not really explicable crash»? I shall just runn `VSCrashReporter.exe` after a crash or put the dump somewhere?

And related to the leakage bug shall I try to `strace` the VintageStory process if I might help you?

**Comment by tyronx** [comment]
Thanks for the thorough report, several if not all of these leaks should be fixed in v1.13. Please reopen if the issue persists.

Yes on a crash without report it can help to run VSCrashReporter.exe to get the crash log. Usually a stack trace is sufficient for me, unless its a hard to reproduce bug. 

Glad to hear you like the game :-)
