### ISSUE TITLE
Crash report on behalf of a russian-speaking user

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#518]
Terribly sorry for not filling the report by the template, but I just got these log files from a Russian-speaking user Telfiya, so hopefully all the info can be found in them. I haven't launched the game for a long time so already forgot all the correct ways to bug report.
She claims she bought the game just yesterday.
If additional info is required, do tell, I'll ask her.

[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/4541035/client-chat.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4541037/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4541038/client-debug.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4541039/client-crash.txt)

**Comment by tyronx** [comment]
Could perhaps happen when a player connects and dies before the client is done initializing. I added an extra check for this now. Will be in v1.13-pre.11. Thanks for the report!
