### ISSUE TITLE
Crash during smithing a saw

### ISSUE THREAD

**Issue by DesLandysh** [anegostudios/VintageStory-Issues#521]
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.14 (Stable)30.04.2020 14:24:19: Critical error occurred
System.IndexOutOfRangeException: Индекс находился вне границ массива. (Index was in out of range of array - my translate from Ru)
   в Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   в Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   в Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   в _AwTvpwXV1bHGBB8plvoGTYT5ihD._aXg8ff7JchZYkTRDnSjo139TZJH()
   в Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   в _hLaepLRCOckdCEvZTPp1GxfgrdT._gvVdZYlJjMijmkAmKtFDCvJNXax(Single )
   в _hLaepLRCOckdCEvZTPp1GxfgrdT._nu0syyqM6QcVDRvU3XOrq03zfUh(Single )
   в _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._ibkrrJqCs89QNSe99xnFzRxp3sL(Single )
   в _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   в _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   в _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.13-pre.10 and onwards.
