### ISSUE TITLE
Character window opening with wrong key

### ISSUE THREAD

**Issue by Val-zero** [anegostudios/VintageStory-Issues#524]
**Game Version:** 1.12.14
**Platform:** Windows 10
**Modded:** No

### Description
I've kept the default control settings, so the character inventory window opens with the C key. On my PC, I can turn down the sound volume with fn + F11, but when I do, the character inventory window also opens/closes. 
Happens on multiplayer (official test server) and solo. 
I don't know if it's linked to the key combination or the sound function, but either way it's an odd behavior. 

### How to reproduce
1. Press fn + F11 (or any key that turns down volume ?)

**Comment by noelle-lavenza** [comment]
Fixed in OpenTK 4.0, and also fixed by Tyron for OpenTK 3.x, included in 1.16.
OpenTK issue: https://github.com/opentk/opentk/issues/579
3.x fix: https://github.com/opentk/opentk/pull/1360
