### ISSUE TITLE
Login failed due to Password restrictions

### ISSUE THREAD

**Issue by arasium** [anegostudios/VintageStory-Issues#525]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
Some game account password are allowed in the website registration but failed when we try to login in game.

### How to reproduce
1. Go to your game account webpage and change your password to "Py-TH`fqz?'Q0CWgq]]<"
2. Launch your game and try to log
3. Login failed message

### Expected behavior
Either the password is rejected in the "change game account password" webpage or the game login succesfully

**Comment by tyronx** [comment]
Thank you very much for this report. Way overdue, but I got this fixed now. I believe i fixed this once, but then broke it again at some point. It was the '<' which got lost along the way.
