### ISSUE TITLE
the server from the list disappeared

### ISSUE THREAD

**Issue by momai** [anegostudios/VintageStory-Issues#526]
**Game Version:** 1.12.14
**Platform:** Windows / Mac / Linux (all)
**Modded:** No

### Description
the server from the list disappeared
at the same time you can enter the server, it is turned on.
### How to reproduce
show screenshot

### Expected behavior
server: 212.41.34.4
cat  /var/vintagestory/data/serverconfig.json
 "ServerName": "[RU] Vintage Story Server",
"ServerMonitor": true,

![image](https://user-images.githubusercontent.com/1340282/81438304-35eac180-9175-11ea-934d-c40e8fdf4a39.png)

```

**Comment by tyronx** [comment]
is this still happening?

**Comment by tyronx** [comment]
no new info in several months, closing
