### ISSUE TITLE
Snow on top of snow gives no-clip view.

### ISSUE THREAD

**Issue by darnuria** [anegostudios/VintageStory-Issues#527]
**Game Version:** v1.12.14 (Stable)
**Platform:** Linux, Ubuntu 18.04.4 LTS
**Modded:** Yes only VSHUD novocain mod
**Processor:** Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
**MonoVersion:** C# Framework: Mono 6.8.0.105 (tarball Tue Feb 4 21:20:20 UTC 2020)

### Description

When snow is placed on top of snow I can see through the fabric of the universe (blocks).
Happens sometimes in snowy pine forest.

### How to reproduce

1. Avalanche or wood cutting moves snow around
2. Snow fall on a block with snow already on it
3. Access the universe fabric

### Screenshots

Found on chrometech if needed.

![Screenshot from 2020-05-10 15-38-57](https://user-images.githubusercontent.com/2827553/81621947-03003200-93f0-11ea-9972-de93c92ca386.png)

### Edits ###

Changed **modded** to yes.

**Comment by Craluminum2413** [comment]
Fixed long ago
