### ISSUE TITLE
Leaves texture keep rendering after cuting

### ISSUE THREAD

**Issue by darnuria** [anegostudios/VintageStory-Issues#528]
**Game Version:** v1.12.14 (Stable)
**Platform:** Linux, Ubuntu 18.04.4 LTS
**Modded:** Yes only VSHUD Novocain mod
**Processor:** Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
**MonoVersion:** C# Framework: Mono 6.8.0.105 (tarball Tue Feb 4 21:20:20 UTC 2020)
**Gamemode**: Survival (not able to reproduce it on creative yet)

### Description

When (birch) leaves with snow on top are cut and snow is placed below, if you cut it (with a pair of shears) sometimes the leaves do not disappears, and all other leaves cut in the chunk will not disappear.

You get lot, but the texture keep rendering you can pass through.

### How to reproduce

0. (maybe) find leaves with snow on top
1. Cut leaves with shears
2. Leaves are cutted but texture is rendered

Not able to reproduce the setup in 10 min in creative or survival on solo, maybe timing or load is involved in the problem. ¯\_(ツ)_/¯
### Screenshots

Found on Chrometech today if needed coordinates on screenshots:

Leaves I cut who triggered the bug:
![Screenshot from 2020-05-14 14-20-33](https://user-images.githubusercontent.com/2827553/81935405-e7b04500-95f0-11ea-84f1-d23c9cf7b949.png)

Pointer says it's nothing but render:
![Screenshot from 2020-05-14 14-21-15](https://user-images.githubusercontent.com/2827553/81935476-fc8cd880-95f0-11ea-9bef-c13684c29a01.png)

Bug affecting other leaves on the chunk:
![Screenshot from 2020-05-14 14-21-31](https://user-images.githubusercontent.com/2827553/81935542-162e2000-95f1-11ea-8fab-cd469140be92.png)

Leaves on a distant chunk seems not affected.

**Comment by copygirl** [comment]
I've found this on other occasions, where an older version of a chunk would render a second time on top of the usual. Most recently this happened to me when gathering cattail on a multiplayer server.

**Comment by tyronx** [comment]
Thanks for the report. This is a very old bug. I *hope* I've got this fixed in v1.14.0 stable an onwards. Please reopen otherwise

**Comment by darnuria** [comment]
No problem will checkout when I get time to play in holiday ! Thanks for your time on the game it's great! :D
