### ISSUE TITLE
Severe grafical artefacts after minimizing the game with God Rays enabled

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#533]
**Game Version:** 1.12.14(Stable)
**Platform:** win 10 1909 (18363.836)
**Modded:** Both in Vanilla and modded, discovered in modded:
- AnvilMetalRecovery_PR0_Debug
- CarryCapacity-0.4.9
- hudclock_v1.0.0-Final
- morerecipes_v1.0.0
- necessaries_v0.7-B
- NoMonsters-1.0.0
- ProspectorInfo-1.1.0
- TpToPoint_v1.0.0

### Description
If game is minimized and restored, the graphics becomes severely distorted, see screenshot and video.
Reported by player Sayary.
He has Radeon RX 570 4Gb   and  Radeon R7 240 LP 1Gb  in his PC.
He uses RX570 for VS.
He noticed that sometimes if you alt-tab from and to the game or minimize and maximize it quickly (e.g. can reproduce on demand by rapidly clicking on the running game "icon" in the taskbar), the graphics becomes severely distorted, many static lines of dots overlaying the game graphics.
![gbubvs](https://user-images.githubusercontent.com/25122345/82326997-612ba700-99e6-11ea-96ad-69bee331971c.png)
This distortion is fixed by either disabling god rays in the running game,
or by relaunching the game without disabling godrays.
He tested his GPU in Assaseen Creed 4 on max for few hours - no changes, so hopefully GPU is healthy. He also keeps an eye on its temperature - all ok.
His graphics options:
![gpubugsettings](https://user-images.githubusercontent.com/25122345/82327468-1fe7c700-99e7-11ea-94cc-7a2b75645073.png)

His bug demonstration video can be viewed online here:
https://yadi.sk/i/eczvABadkbO4xg

He did try to switch videostream on the fly while game is running from RX570 to R7240 typing some command in cmd, idk, some driver feature. This did not fix the bug in the running game. He did not try to test the bug on R7240 because that GPU is quite weak, he keeps it as a legacy one.

### How to reproduce
Run the game on a PC with Radeon RX 570 4Gb with God Rays enabled.
While in a world, quickly minimize and restore the game window e.g. by clicking ot the game icon in taskbar. Observe the distortions.
Fix by disabling God Rays or without disabling them relaunch the game.

### Expected behavior
Not having any artefacts/distortions.

**Comment by tyronx** [comment]
Looks like a bug in the driver to me. No idea whats going on in any case :<

**Comment by tyronx** [comment]
Is this still happening btw?

**Comment by Sayary-NULL** [comment]
No. This error is no longer present. (1.13-pre. 5)

**Comment by Heptagon-ru** [comment]
Sayary confirmed not having the issue for some time already, so closing the ticket by his request in discord DM.
