### ISSUE TITLE
"Could not find climate map for region coord" being logged many times per second

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#536]
**Game Version:** 1.12.14
**Platform:** macOS Catalina
**Modded:** No

### Description
Occasionally, the logs will be filled with messages like `26.5.2020 08:02:23 [VerboseDebug] Could not find climate map for region coord 711,587. Looks like the server didn't send it. Tinted blocks might be incorrectly colored.` Several messages with different region coords will be logged per second, up to about 12 or so, for any length of time. I have noticed that this only happens in some places. The two attached logs were taken on the OPTS around the region coords 683, 586 and 682, 585. I completely shut the game down between the two logs and the issue persisted. I think, but I am not sure, that this may cause large increases in CPU usage.

I have not been able to reproduce this error on single player.

### Logs
Files are about a megabyte each.
[client-debug 1.txt](https://github.com/anegostudios/VintageStory-Issues/files/4682119/client-debug.1.txt)
[client-debug 2.txt](https://github.com/anegostudios/VintageStory-Issues/files/4682121/client-debug.2.txt)

**Comment by tyronx** [comment]
iirc this should be fixed in v1.13
