### ISSUE TITLE
There is no spawn conditions for "California Poppy" and "Orange Lupine" in game files

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#540]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
There is no California Poppy spawn in game files.

### How to reproduce
1. Go to **assets\survival\worldgen\blockpatches.json**
2. Search for "california", "poppy", "golden" or "orange".
3. No items found.

### Expected behavior
Considering this is a type of flower already ingame, translations and it's the only flower in the code that doesn't have spawn conditions (there is even sit place of butterflies in the flower already), should that be changed?

**Comment by copygirl** [comment]
Just for the record: Orange lupine, like white and red I believe, have special in-code conditions for spawning inside larger patches of the other, more common lupine. There was a bug that made orange lupine never get picked though - and I have fixed this.

I haven't looked in the [survival mod](https://github.com/anegostudios/vssurvivalmod) yet to see if there's any references to those flowers.

**Comment by Zaldaryon** [comment]
@copygirl Update - the orange lupine is fixed on 1.13pre onwards, but as of pre4, Golden Poppy still has no spawn conditions in the same file from the report. 

The flower still shows in the Handbook. If it's not implemented yet, I suggest to take it off of the Handbook,or maybe set spawn conditions on said file.

**Comment by tyronx** [comment]
Both will now spawn in pre.5
