### ISSUE TITLE
Unable to login back to server after power outage

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#542]
**Game Version:** 1.12.14
**Platform:** Windows 10
**Modded:** No

### Description
On behalf of Lary Romero.
He reported that after his computer switched off unexpectedly because of power outage, he can not join GoodMC server any more (been playing around a month), with an error "The server closed down the socket without response. The server may be password protected or whitelisted".
Server's admin told him to change the name to fix the issue, but he already have recently changed the name 16 days ago because of the same reason, so can't change 45 days more.
He asks either how to fix this problem without changing the name, or to change the name to "Romero" now.
His current in-game name is "Laryromero".

### How to reproduce
1. Play on GoodMC server a bit.
2. Expose your PC to a power surge to force it to switch off
3. Reboot and try to login to the GoodMC server

### Expected behavior
Being able to connect to the server without any issues.

### Screenshots
![5](https://user-images.githubusercontent.com/25122345/84603631-7afec380-ae98-11ea-917e-c2ecf52deb7b.png)

**Comment by Heptagon-ru** [comment]
It is unclear is GoodMC server is pirated or not. Lary says they claim they are official one but still allow players with pirated version to login.

**Comment by Heptagon-ru** [comment]
He can succesfully login to the official gameserver.vintagestory.at  at least.

**Comment by tyronx** [comment]
So from what I understand he tries to connect to a server that has `VerifyPlayerAuth` disabled so players of a pirated game can join. The purpose of purchased and validated accounts is to protect against account impersonation.

If I were to add ways of preventing that I would kinda shoot myself in the foot, but thanks for the report. Working as intended.
