### ISSUE TITLE
Branchy leaves are missing some texture info (probably) leaving them as white on map and triggering white particles when broken

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#547]
**Game Version:** 1.13pre5
**Platform:** Windows
**Modded:** No

### Description
Branchy leaves have some missing texture or info that when they are broken, they trigger white particles instead of green ones. That might be the same cause as they show as white in the minimap/bigmap.

### How to reproduce
1. Go on a creative world or survival world but gamemode yourself to creative.
2. Acquire any branchy leaves.
3. Place it in the world and watch the minimap/bigmap.
4. Break them and watch the particle effect.

### Expected behavior
They should break and trigger greenish particles like normal leaves (not the branchy variant) and show as green on the maps, like the non-branchy ones.

### Screenshots
![branchy_leaves_when_broken](https://user-images.githubusercontent.com/50756284/87796113-51caad80-c81f-11ea-9ea5-b14a1a2f7c87.png)
![common_leaves_when_broken](https://user-images.githubusercontent.com/50756284/87796115-52fbda80-c81f-11ea-93e3-d1ecaa8615a3.png)
![branchy_leaves_as_white_on_map](https://user-images.githubusercontent.com/50756284/87796118-53947100-c81f-11ea-98bb-baefa3e4f6e6.png)
![branchy_leaves_placed_on_world_and_map](https://user-images.githubusercontent.com/50756284/87796121-53947100-c81f-11ea-9982-6d47d31b7475.png)

**Comment by tyronx** [comment]
thanks for the report, this is fixed in pre.7 already i think
