### ISSUE TITLE
Inconsistent trader pricing

### ISSUE THREAD

**Issue by Fulgen301** [anegostudios/VintageStory-Issues#548]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
The trader price list is sometimes quite inconsistent. Example:
- Trader buys one type of carpet for 12 gears, but other types for one gear.
- Trader buys a golden chest, if memory serves me, for one or two gears.

Saraty thinks the prices seem to get fixed after relogging.

### How to reproduce
No direct reproduction known to me, it sometimes happens when playing.

### Expected behavior
Reasonable pricing.

### Screenshots
![2020-07-09_17-06-57](https://user-images.githubusercontent.com/18363765/87854250-e9f48f80-c910-11ea-8d0f-f824eec47fdb.png)

**Comment by tyronx** [comment]
thanks for the report, fixed for pre.9
