### ISSUE TITLE
Chisel bug

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#549]
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** No

### Description
Mantle blocks can be chiseled and therefore, removed.

### How to reproduce
1. Get a chisel.
2. Go down to mantle block level.
3. Right click with a chisel in the mantle block.
4. Break the chiseled mantle block with a pickaxe.
5. Hole to the void.

### Expected behavior
Mantle blocks should be the ultimate protection, therefore, not having the property of being chiseled.

### Screenshots
![mantle](https://user-images.githubusercontent.com/50756284/87993265-75f8e980-cac0-11ea-8b35-5a26875f6606.png)

**Comment by tyronx** [comment]
Thank you, this should be fixed in pre.8
