### ISSUE TITLE
Memory leak in unmanaged code

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#55]
- After about 2 hours of gameplay the client consumes about 2gb of memory
- GC memory consumption remains stable at 400-500mb (as seen in a memory snapshot and in the debug screen)
- Still happens when playing on a multiplayer server
- Still remains at about the same even after a collect on the large memory heap
- Still remains at about the same after leaving the world/server (but keeping the game running)

=> Can only be a leak in unmanaged code thats used by the client? Maybe OpenGL or Cairo graphics?
=> maybe can use ants memory profiler to debug this https://www.youtube.com/watch?v=fR7QND_htFU

**Comment by tyronx** [comment]
Several classes holding references to unmanaged objects will now scream if they get disposed without their unmanaged object being properly disposed. Fixed several dozen such occurrences, but nothing that would indicate the level of memory leaking we are seeing.

**Comment by copygirl** [comment]
Do those classes implement the `IDisposable` pattern properly, so `Dispose` is called when the instance is garbage collected?

**Comment by tyronx** [comment]
Can't dispose during garbage collection for textures, all opengl stuff has to happen in the main thread.

**Comment by tyronx** [comment]
Memory leaks seem to be gone for the most part now.
