### ISSUE TITLE
Quern doesn't crush materials with nuggets.

### ISSUE THREAD

**Issue by Electricianfromhell** [anegostudios/VintageStory-Issues#552]
**Game Version: 1.13 pre 1** 
**Platform: Windows**
**Modded: No**

### Description
Quern doesn't Crush materials with nuggets in them

### How to reproduce
1. Make a Quern
2. Hook it up to a Windmill
3. Place any material with metal nuggets in it you crush with the hammer.
4. The Quern doesn't crush the material with nuggets in it.

### Expected behavior
The quern would crush the material with nuggets giving metal nuggets for melting in the crucible.

### Screenshots

![quern bug](https://user-images.githubusercontent.com/11165643/89133689-f02b6400-d4eb-11ea-9b5a-60905ceac5fe.jpg)

**Comment by copygirl** [comment]
From what I know the quern wasn't intended to do this, but it makes some sense to add such functionality, so I will change this issue to a suggestion. Some open questions are: Should the quern output nuggets, or a new item? Should it refuse to grind harder source rocks or metals? (Perhaps a crusher structure is required for them.)

**Comment by tyronx** [comment]
yea, the quern is not meant for that. Perhaps in the future the new pulverizer will be able to do that. you need to use a hammer on those for now
