### ISSUE TITLE
Weather Command does not Change Weather Properly

### ISSUE THREAD

**Issue by Electricianfromhell** [anegostudios/VintageStory-Issues#553]
**Game Version: 1.13.0-pre.13 (unstable)** 
**Platform: Windows**
**Modded: No**

### Description
Typing /weather set clearsky in the command console when it's raining makes the sky go clear but does not stop the rain when the sky goes clear and typing /weather set heavyrain when the sky is clear makes the sky go dark, but it does not start raining when the sky goes dark.

### How to reproduce
1. type /weather set heavyrain into command console
2. watch sky change color with no heavy rain.

### Expected behavior
weather should change to weather pattern expected when weather command is entered such as a clear sky with no rain when /weather set clearsky is entered into command console.

**Comment by tyronx** [comment]
Hi, this no longer works because setting precipitation is now done via `/weather setprecip [-1..1]` (where -1 is no rain and 1 is full rain)
