### ISSUE TITLE
New Feature: Dross and Slag

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#554]
Dross and Slag should be introduced as part of the metal smelting processes. The crucible should have item output slots added to it.

Dross is a solid impurity that forms from a metal being oxidized that forms a very thin layer and floats on the surface of a metal during the smelting process.

Slag is a mixture of oxidized metals along with silicates that can be separated when heated hot enough during the smelting process that the impurity's separate and build up and usually float on the surface of your metal in the crucible like layers of oil in water

Dross depending upon the metal smelted (forms on lower melting point metals like tin, lead, zinc, aluminum and some alloys) should be created in the crucible and would need to be skimmed off the surface with a spoon to remove it.

Slag is similar to dross and would need to be removed by getting your metal hot enough so the impurity's would separate out from the metal where you could skim off the slag with a spoon like in the video to remove it.

https://www.youtube.com/watch?v=gF7c_nGvo8Q

Slag should be able to be run through the quern to grind it up to a powder where it could be re smelted to refine it farther to separate out and attempt to recover any remaining metal from it. What remains of it could be used for construction materials.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
