### ISSUE TITLE
New Feature: Quicksand

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#555]
Quicksand that you could sink in and get stuck or drown in should be added as a hazard that can be found in game. Usually quicksand is not bottomless like the movies show it to be. In real life you float in quicksand, but it can be quite hard to escape.

Some forms of quicksand.

Quicksand found on beaches, traps you where you can't escape until the tide comes in and drowns and kills you or you starve to death from the sun killing you like in real life. 

Wet Quicksand found in deserts fed by tiny springs, can trap you and the sun does the rest like in the video.

https://www.youtube.com/watch?v=yg88Tw8oAbk

peat bog quicksand - Wet peat found near the eye of a bog, You could go down in it and drown very quickly if you struggle. A Idiot dives into it in the photo.

![bog](https://user-images.githubusercontent.com/11165643/89225228-de0efb80-d5a7-11ea-9625-c4b55dd466b0.jpg)

Mud Volcano - Clay like mud ejected at the surface by a mud volcano, some mud volcanoes are cold and can be bathed in for health benefits. Some are boiling hot like Yellowstone and are two hot to touch and if jumped in would do massive damage like boiling water or lava. This is a must add if adding mud and quicksand. Mud volcanoes are usually found in groups close to each other like in Yellowstone or the middle east or a single one in the middle of nowhere like the ones in Brazil.

Hot springs of water with health benefits / Boiling hot springs of water too hot to swim in should come with the mud volcano too.

![mud-85_1280-e1551299612742](https://user-images.githubusercontent.com/11165643/89225740-b8362680-d5a8-11ea-92cb-0af622ff2810.jpg)

Mud found in rivers and swamps etc - similar to peat bog quicksand but may be thicker and harder to escape from.

Dry Quicksand - Found in deserts very rarely and it can swallow you whole in seconds if you step on top of and disturb it, simular to grain bin quicksand like the photo below.

![From-the-Editor_Caution-do-not-enter_June_Grain-bin-safety_E](https://user-images.githubusercontent.com/11165643/89225589-70af9a80-d5a8-11ea-8a0b-98bf10311186.jpg)

**ARTIFICIAL QUICKSAND TYPES**

Mixing the materials below could be used to build a artificial quicksand pit in game

Powdered clay + Water = Wet Clay

Peat + Water = Wet Peat

Dirt + Water = Mud

Sand + Water = Quicksand

Silt + Water = Siltsand

Cornstarch + Water = Oobleck

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
