### ISSUE TITLE
New Feature: Gases

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#556]
Another idea for a new feature i had that would make mining even more realistic is gases. 

Some gases that should be added that could be found underground and in mines if not ventilated properly

**Methane / Firedamp (CH4) (colorless, odorless, explosive)**

Firedamp is a mining term for a set of explosive gases found in mines. It’s mostly made up of methane and methane is often an interchangeable term when miners talk about firedamp.

Methane (CH4) is a colourless, odourless, highly flammable, and highly explosive noxious gas. It occurs naturally in coal seams and shale deposits and is a major component of the natural gas that we burn for energy.

Methane gas accumulates in “pockets” of the coal and adjacent strata naturally over millions of years and can be released as the coal is mined. As the pockets are penetrated by the mining machinery the gas seeps into the pit where explosive mixtures of methane can form.

Methane has a density relative to air of 0.55. Because it’s much lighter than air it tends to accumulate at higher levels within enclosed spaces where little ventilation exists to disperse it.

Methane is only combustible at levels between 4 and 16%. Below that range there isn’t enough to be ignited, and above that range the mixture is too dense to be explosive. The riskiest level of methane in the air is said to be 9.5% where it finds the perilous balance. All it takes is a naked flame or a spark from a machine to cause an explosion when these levels of methane are in the air.

Methane in sufficient quantities is also capable of displacing oxygen from the air and can cause asphyxia in humans who breathe it in. When humans do not receive enough oxygen to the brain it can cause headaches, nausea, dizziness, and can ultimately result in death when the oxygen concentration drops below 6%.

**Hydrogen Sulfide / Stinkdamp (H2S) (colorless, rotten egg smell, explosive and toxic)**

Stinkdamp is the mining term given to hydrogen sulfide (H2S) due to its characteristic smell of rotten eggs.

Hydrogen sulfide is a highly poisonous, flammable, colourless, and as mentioned, pungent-smelling gas. It has only ever been found in trace amounts in mines - but it can be lethal in even small concentrations.

It is produced from the decomposition of iron pyrites in a mine due to the presence of water and how they interact.

As mentioned H2S is a highly toxic gas capable of causing death in humans via asphyxiation.
In lower levels, it will irritate the eyes, nose, and throat, as it increases it has a narcotic effect on the nervous system causing headache, dizziness and difficulty breathing. At higher levels of exposure H2S suppresses oxygen in the blood and tissues resulting in paralysis of the respiratory system and ultimately death in severe cases. Prolonged low exposure can lead to bronchitis, pneumonia, migraine, and loss of motor control.

It can also form flammable mixtures in the air in the range of 4.5 - 45% where any sort of ignition would cause an explosion. With a heavy density of 1.9 it can accumulate in low points in the mine that are poorly ventilated.

As always, the best way to prevent stinkdamp is proper ventilation and methods to test for the gases.

**carbon dioxide / Black Damp (CO2) (Colorless, slight acrid smell, toxic)**

Black damp is the mining term for the suffocating mixture of carbon dioxide and other unbreathable gases that can build-up in mines causing poisoning, asphyxiation, and ultimately death if left untreated.

Carbon dioxide (CO2) is a colorless, noxious gas that only gives off a slight acrid smell at higher concentrations making it very hard to identify through human senses.

While not toxic in itself, once carbon dioxide is mixed with the air it reduces the available oxygen one can breathe. The early symptoms of black damp (drowsiness, dizziness, and light-headedness) are easily mistaken for simple fatigue however lethal doses will cause asphyxiation that can easily result in death within seconds.

If there is 18% carbon dioxide in the air it can kill, levels as low as 3% can cause breathing difficulties with symptoms worsening as the percentage increases.

Carbon dioxide forms through the decomposition of organic materials, such as rotting mine timbers, as well as through human and animal respiration. The coal itself, once exposed to the air of a mine, will begin to absorb oxygen and exude carbon dioxide. With a heavier density relative to normal air (1.53) carbon dioxide will accumulate in lower-lying areas within the mine.

The accumulation of black damp in a mine is caused predominantly by poor ventilation however other factors can be attributed such as the temperature, the amount of exposed coal, and the type of coal.

The fact that black damp will always be present where coal is present and that it is hard to identify and distinguish between fatigue, increases the risk that warning signs will be missed allowing black damp to cause serious harm within seconds.

Therefore prevention of black damp and identification of the dangerous gases is essential for mine safety.

**carbon monoxide / White Damp (CO) (Colorless, odorless, explosive, toxic)**

White damp is a mixture of poisonous gases found in coal mines and is predominantly made up of carbon monoxide (CO).

It is colourless, odourless, and tasteless making it very hard for a human to detect. It is commonly referred to as a “silent killer”.

Carbon monoxide is a product of the incomplete combustion of carbon.
In coal mines, large quantities of CO is generated during the oxidation of coal, and during mine fires or explosions. It will then be present in what miners call afterdamp - the resulting noxious gases given off by these fires, explosions, or blasting.

Carbon monoxide is extremely toxic - it is absorbed by the haemoglobin in the blood blocking the ability of the haemoglobin to absorb and carry oxygen around the body, in turn, the body will begin to shut down.
Carbon monoxide is also cumulative meaning that a person can be exposed for a number of short periods to no apparent ill effect, however, with each interaction the person will become more and more susceptible to its effect. If its levels get as high as 0.2%, death will take place within one or two hours.

It is also highly flammable and explosive in mixtures with air between 12.5 and 74% with the most explosive concentration being 29%.

And flames won’t extinguish in its presence as it would with carbon dioxide. It is therefore one of the most dangerous gases found in a mine, and one of the most difficult to detect.

Infamously, the domestic canary was used as an early warning against any noxious gases in the past. This is because carbon monoxide affects small animals more quickly than humans, and when exposed to carbon monoxide the bird would fall from their perch alerting the miners to move to safety.

There is now modern equipment that can easily detect carbon monoxide without any cost to life.

**Bonus: Coal Dust / Black Lung**

Black lung disease is a common name for any lung disease that develops from inhaling the coal dust that comes from the mining process of extracting coal. This name comes from the fact that those with the disease have lungs that look black instead of pink. Medically, it is a type of pneumoconiosis called coal workers' pneumoconiosis (CWP)

**Finale - Prevention & Detection Of Mine Gases**

The most effective, safe, and efficient way of keeping mines free of dangerous gases is done through quality mining ventilation systems.

Mine ventilation provides a safe flow of air through the workings of a mine at a measurable volume that dilutes and removes any build-up of dangerous gases and other chemical and physical contaminants that may be present, as well as regulating the temperature.

To create a thorough safe mining environment prevention must be supported by detection.

Detection of dangerous gases in mines has changed and developed over the years with some techniques becoming traditions ingrained in the mining culture.

The use of the canary has become a symbol for gas testing in mines, along with a testing flame, and the further developed flame safety lamps.

Did you know? A man, known as a fireman, penitent, or monk would edge forward with a candle on the end of a stick to test for the gases. If there was an explosion he was simply to keep his head down to allow it to pass over him - maybe not the safest means of detection.

Some form a ventilation system should be added in game that might be similar to the bellows a bit available early on in the game that could be powered by a windmill or waterwheel or something mechanical like the quern and helve hammer. The device would suck air into a mine from the entrance if it was set up like in the image or it pump air underground through a pipe. It would have to work like the image depicts a mine ventilation system.

![1200px-Ventilación_aspirante svg](https://user-images.githubusercontent.com/11165643/89343268-095e1d00-d672-11ea-9884-d1884508ebc1.png)

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
