### ISSUE TITLE
OpenGL "after final compo" error

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#559]
**Game Version:** 1.13.0-pre.10 and up
**Platform:** macOS
**Modded:** No

### Description
When I enter a world every frame throws `after final compo   - OpenGL threw an error: InvalidOperationEnable Gl Debug Mode in the settings or clientsettings.json to track this error`. This happens regardless of anything on-screen or any setting enabled or disabled.
This error was not present before pre.10.

### How to reproduce
1. Enter a world.

### Graphics info
Graphics Card Vendor: NVIDIA Corporation
Graphics Card Version: 4.1 NVIDIA-14.0.32 355.11.11.10.10.143
Graphics Card Renderer: NVIDIA GeForce GT 750M OpenGL Engine
Graphics Card ShadingLanguageVersion: 4.10
Cairo Graphics Version: 1.12.14
OpenAL Version: 1.1

**Comment by VeryGoodDog** [comment]
I did some testing on this, and I have determined the issue is caused by changes made to `blockhighlights.vsh`. Lines 6, 21, and 22 were changed between pre.9 and pre.16.

No errors were thrown when I pasted the pre.9 versions of it into an otherwise unmodified pre.16 app.

**Comment by tyronx** [comment]
thanks, this should be fixed in the next release
