### ISSUE TITLE
Some 1.13 flowers not recognized as flowers by bees

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#561]
**Game Version:** 1.13.0rc1
**Platform:** Windows
**Modded:** No

### Description
All crotons and all rafflesias are not recognized as flowers by bee skeps and beehives.

### How to reproduce
1. Add an empty skep and a populated skep nearby.
2. Add 1 normal flower (lupine, for example) and the rest the new flowers (crotons, rafflesias).
3. Wait some time (a few days ingame to be sure). The flower count on populated skep is only 1.

### Expected behavior
The populated skep should count those flowers as well, as they are categorized as flowers. If they are not flowers, that category should be removed to not confuse users.

### Screenshots
![brownflower](https://user-images.githubusercontent.com/50756284/89711865-648a5b00-d963-11ea-9766-9cb7e04377b2.png)
![brownrafflesia](https://user-images.githubusercontent.com/50756284/89711867-65bb8800-d963-11ea-9bc0-09e232e95c5c.png)
![croton](https://user-images.githubusercontent.com/50756284/89711870-66ecb500-d963-11ea-80b2-22a0e733ab29.png)
![crotonflower](https://user-images.githubusercontent.com/50756284/89711871-66ecb500-d963-11ea-8969-33823b9c56e6.png)
![redflower](https://user-images.githubusercontent.com/50756284/89711872-67854b80-d963-11ea-84cf-e7a97c5506c5.png)
![redrafflesia](https://user-images.githubusercontent.com/50756284/89711873-67854b80-d963-11ea-968a-fccbd174c69b.png)

**Comment by tyronx** [comment]
ok, they will no longer be marked flowers next release
