### ISSUE TITLE
Leaf blocks when broken with shears give white and red particles

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#562]
**Game Version:** 1.13.0rc1
**Platform:** Windows
**Modded:** Yes, VSHUD.

### Description
Leaf blocks when broken with shears give white and red particles. It doesn't happen if you break them by hand or any other tool.

### How to reproduce
1. Get shears.
2. Go to a tree.
3. Break the leaves with shears and watch particles.
4. Now get a lost with not a shear in hand.
5. Break the leaves and watch the right colored particles.

### Expected behavior
They should give particles at the leaves colors.

### Screenshots
Youtube link: https://youtu.be/-PqZvkmhNrM

**Comment by tyronx** [comment]
thanks for the report, does this still happen?

**Comment by copygirl** [comment]
I've seen red particles when shearing blocks in 1.13.4. Not sure about 1.14.

**Comment by Craluminum2413** [comment]
I don't see any white or red particles while breaking leaves with hand or shears in the latest versions. Only brownish and greenish particles as it should be

**Comment by Craluminum2413** [comment]
> https://www.vintagestory.at/forums/topic/3624-stable-christmas-patch-v1143/?tab=comments#comment-14787
> Fixed: White and red particles when shearing leaves
