### ISSUE TITLE
Visual effect of ore veins and bits to reflect light

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#564]
Would be nice of them ore bits and veins to reflect the light or at least shine a bit when you look at them in the dark with a light source in hand. Sometimes veins textures don't differ much from the stone textures and are easy to miss and this would help not to. It would also "stimulate" the night raids, as currently sleeping don't cover the whole night, and there is usually nothing to do but to wait for morning on early game stages.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
