### ISSUE TITLE
To make ALT key rebindable and/or toggleable

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#565]
Current setting of ALT being the mouse release button is quite uncomfortable in immersive mouse mode (ALT+7 to 0 are quite far from WASD). It would be great If you could make it so this command could be either bound to another key or mouse button, or make the free mouse mode toggleable.

**Comment by tyronx** [comment]
Thanks for the suggestion, it will be rebindable next release
