### ISSUE TITLE
Everything is purple and there is little to no shading?

### ISSUE THREAD

**Issue by SpxterWohlf** [anegostudios/VintageStory-Issues#566]
**Game Version:** v1.13.0-rc. 1
**Platform:** Windows
**Modded:** No

### Description
Everything is purple, everything, there is almost no shading and everything is dark. I just started a brand new world on a copy I bought today.

### How to reproduce
1. Start game
2. I set the graphics to Low 
3. I created a world
*Side note just created a new world and spawned in a tree
![image](https://user-images.githubusercontent.com/33076633/89970580-bd394c80-dc1e-11ea-8293-28b971b13555.png)
Everything is purple and last time the sky was just black

### Expected behavior
I saw YouTube videos and screenshots with green worlds, I don't think this is Terraria courruption or something

### Logs
https://gist.github.com/Wohlf-craft/2080d0db4bbb45ad1f9a763376f5bd0d
https://gist.github.com/Wohlf-craft/c7b5af03287f60d9012e1c55bf8e2db1

I hope this was a ok report, I am new to this.

**Comment by Wohlf-craft** [comment]
I saw the game updated again today, same thing happened. Same process as before

Logs:
https://gist.github.com/Wohlf-craft/c1b52d6d0c06181b2ab6a8a9b2133a72
https://gist.github.com/Wohlf-craft/de432ae63d513d832e28fc87119ca4a5

**Comment by tyronx** [comment]
thanks for the report, this is a hardware specific issue. It can be mitigated by enabling "Purple grass fix" in the graphics settings
