### ISSUE TITLE
.blockitempngexport item clipping

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#568]
**Game Version:** 1.13-rc.2 (but on all previous versions)
**Platform:** Mac
**Modded:** No

### Description
Some items' PNGs created with `.blockitempngexport 400` are cut off on the backplane. The issue gets worse as the image size goes up.

**Comment by Craluminum2413** [comment]
Fixed in [1.14.3-rc.2](https://www.vintagestory.at/forums/topic/3594-post-christmas-patch-v1143-rc2/#:~:text=Fixed%3A%20Z%2Dclipping%20issues%20in%20pngs%20generated%20by%20.blockitempngexport)
