### ISSUE TITLE
problem withe the Helve hammer

### ISSUE THREAD

**Issue by ritter-manni** [anegostudios/VintageStory-Issues#572]
**Game Version:** v1.13.0(satble)
**Platform:** Windows 10 64bit
**Modded:** No 

### Description
hi I have a little problem with the Helve Hammer on a multiplayer server (1.13 stable). the animation is played correctly but when the bar is visually finished it is not thrown out. if I then take it off and put it on again, it is not processed at all

### How to reproduce
my set up is i have 4 windmill (with 3 set's of sails each) feeding in a big gear then axels down to ground leven wher i turn withe a litle gear in 1 axel then in a transmischen withe a clutch then in the hevelhammer

### Expected behavior
that the hevel hammer produce a iron ingot out of a hot iron bloom

### Screenshots
[https://prnt.sc/u4wiv3.](https://prnt.sc/u4wiv3.) [https://prnt.sc/u4wrnm](https://prnt.sc/u4wrnm)

### Logs
```
Paste crash here.

i have no crash report to post :-(

**Comment by copygirl** [comment]
Just a suggestion for future issue reports: "1.13 stable" doesn't tell us which version the issue occurred in. Say, if the developers put out `1.13.1` and `1.13.2` - we can't be sure which version you might be talking about. In the main menu, it says "1.13.0" in the lower right corner. That's the info we need. (Pre-releases and release candidates will say `1.13.0-pre.1`, `1.13.0-rc.1` or similar.)

**Comment by ritter-manni** [comment]
version 1.13.0 (stabel) ^^

**Comment by kwegar** [comment]
Same issue on 1.13.1  (the latest stable patch)  do not have 4 windmills though.. but leave it there forever add an ingot nothing ever finished. (and my mill never seems to grind flower when i config to power it instead.  only built it after 1.13.1  others on server that built on 1.13 seem to still work fine.

**Comment by tyronx** [comment]
thanks for the report, pretty sure this has been fixed already, please reopen otherwise
