### ISSUE TITLE
Game crash like every 5 mins without doing anything

### ISSUE THREAD

**Issue by Altair91** [anegostudios/VintageStory-Issues#574]
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.0 (Stable)25.08.2020 19:13:19: Critical error occurred
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdate(WeatherState msg)
   bei Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdates()
   bei Vintagestory.GameContent.CloudRenderer.CloudTick(Single deltaTime)
   bei Vintagestory.GameContent.CloudRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   bei _1lotrgXN2NetimRAD4ZAefxwrjm._Ew2FBwtlqRJ9Adp9eFRdFA2PyGp(Single )
   bei _GOvhuoHvUhV6DSqmhF1QtCbrUki._u475OTafdqfLJg04OqOzYKfDELL(Single )
   bei _GOvhuoHvUhV6DSqmhF1QtCbrUki._hdByNlLQKfOWBdLqhR3ruj4UiBf(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _JQ8hJZaWfIKtgNCRVIFwsWJlGbD._PobINQXMJm1DRr8Q98KrBuOyaBI(_oOE8RvwwsA8CcfDxUcot5Tu1mbq , String[] )
   bei _E1zChrmPoD6YADl4x90dHsneZYx._PobINQXMJm1DRr8Q98KrBuOyaBI(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 25.08.2020 18:53:45, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IndexOutOfRangeException
   bei Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdate(Vintagestory.GameContent.WeatherState)
   bei Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdates()
   bei Vintagestory.GameContent.CloudRenderer.CloudTick(Single)
   bei Vintagestory.GameContent.CloudRenderer.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   bei Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   bei _1lotrgXN2NetimRAD4ZAefxwrjm._Ew2FBwtlqRJ9Adp9eFRdFA2PyGp(Single)
   bei _GOvhuoHvUhV6DSqmhF1QtCbrUki._u475OTafdqfLJg04OqOzYKfDELL(Single)
   bei _GOvhuoHvUhV6DSqmhF1QtCbrUki._hdByNlLQKfOWBdLqhR3ruj4UiBf(Single)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _JQ8hJZaWfIKtgNCRVIFwsWJlGbD._PobINQXMJm1DRr8Q98KrBuOyaBI(_oOE8RvwwsA8CcfDxUcot5Tu1mbq, System.String[])
   bei _E1zChrmPoD6YADl4x90dHsneZYx._PobINQXMJm1DRr8Q98KrBuOyaBI(System.Threading.ThreadStart)

 }
{ TimeGenerated = 25.08.2020 18:30:52, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IndexOutOfRangeException
   bei Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdate(Vintagestory.GameContent.WeatherState)
   bei Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdates()
   bei Vintagestory.GameContent.CloudRenderer.CloudTick(Single)
   bei Vintagestory.GameContent.CloudRenderer.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   bei Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   bei Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   bei _1lotrgXN2NetimRAD4ZAefxwrjm._Ew2FBwtlqRJ9Adp9eFRdFA2PyGp(Single)
   bei _GOvhuoHvUhV6DSqmhF1QtCbrUki._u475OTafdqfLJg04OqOzYKfDELL(Single)
   bei _GOvhuoHvUhV6DSqmhF1QtCbrUki._hdByNlLQKfOWBdLqhR3ruj4UiBf(Single)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _JQ8hJZaWfIKtgNCRVIFwsWJlGbD._PobINQXMJm1DRr8Q98KrBuOyaBI(_oOE8RvwwsA8CcfDxUcot5Tu1mbq, System.String[])
   bei _E1zChrmPoD6YADl4x90dHsneZYx._PobINQXMJm1DRr8Q98KrBuOyaBI(System.Threading.ThreadStart)

 }

**Comment by copygirl** [comment]
Duplicate of #569.
