### ISSUE TITLE
Crock math is broken

### ISSUE THREAD

**Issue by Shionsan** [anegostudios/VintageStory-Issues#575]
**Game Version:** 1.13.1
**Platform:** Windows
**Modded:** Yes (CarryCapacity-0.4.10)

### Description
Food portions exchange via crocks is broken.

### How to reproduce
1. Make a 6 portions of food in a claypot.
2. Use crock on it.
Claypot is empty while crock is 4 portions full.

If you keep using full crock on any other non-empty crock/pot, the result becomes unpredictable. But in the end you will have only one crock with food and all other crocks/pots will end up empty.

**Comment by tyronx** [comment]
hm, I cannot reproduce this issue. When I right click a full pot with an empty crock, 2 portions remain and i cannot take any more

**Comment by tyronx** [comment]
thanks for the report, i think all food transfer issues should be fixed in v1.14
