### ISSUE TITLE
Respawn after death makes the player appear at the place of death

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#58]

**Comment by Heptagon-ru** [comment]
Btw, I haven't experienced this bug, but fyi quite often I get some items still in my hotbar after death. Sometimes not. Never backpacks yet.

**Comment by tyronx** [comment]
Yea it might be caused by this bug as well

**Comment by tyronx** [comment]
Seems fixed. No new reports on this so far.
