### ISSUE TITLE
Clutch cannot be crafted in survival.

### ISSUE THREAD

**Issue by threeheadeddingo** [anegostudios/VintageStory-Issues#583]
**Game Version:** 1.13.4
**Platform:** Windows 10
**Modded:** No

### Description
Transmission can be crafted in survival, but the clutch cannot, thus indirectly making the transmission unusable in survival. Handbook shows a clutch recipe but placing the required items into the crafting window yields no result.
```

**Comment by tyronx** [comment]
Seems to be craftable just fine for me. Can you show a screenshot of that issue?

**Comment by tyronx** [comment]
no new info supplied. please reopen if new info is available
