### ISSUE TITLE
Can't cook mushroom stew

### ISSUE THREAD

**Issue by reicherBene** [anegostudios/VintageStory-Issues#588]
---
name: Bug report
about: I found an issue with the game
labels: 'type: bug, status: new'
assignees: ''

---

**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
Can not cook mushroom stew by placing mushrooms in the second two slots of the cooking pot. It works with some other vegetable in the first two slots and added mushroom in the last slots. I'm not sure if thats really a bug but it seems to me cause mushrooms are used to work as vegetable when cooking a vegetable stew.

![2020-09-20_17-29-34](https://user-images.githubusercontent.com/61832950/93715190-20949380-fb68-11ea-8b1c-c97ad8dfd6c0.png)

**Comment by copygirl** [comment]
According to the recipe for the vegetable stew, the first ingredient can't be a mushroom. This might be an oversight, but it is also likely it is entirely intentional.

**Comment by tyronx** [comment]
Thanks for the report, it do would make sense to be able to make pure mushroom stew, I've adjusted the recipe for next version 👍
