### ISSUE TITLE
game just dosen't load

### ISSUE THREAD

**Issue by Richplayz** [anegostudios/VintageStory-Issues#589]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No 

### Description
when i load the game it just turns the screen black and then closes

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
for it to open

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![Screenshot 9_22_2020 4_36_16 PM](https://user-images.githubusercontent.com/71731969/93934982-ea831b00-fcf1-11ea-9dbd-fbee7c89beb7.png)

### Logs
```


In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
Can you attach the `client-main.txt`? You can find it in `%appdata%/VintagestoryData/Logs`. (You can press Win+R and then paste that text in for the file explorer to go directly to that folder.)

**Comment by tyronx** [comment]
No new info supplied in 2 months. Please reopen if new info is available
