### ISSUE TITLE
Crash on World Load [Kubuntu]

### ISSUE THREAD

**Issue by Rhyagelle** [anegostudios/VintageStory-Issues#590]
**Game Version:** 1.13.4
**Platform:** Linux (Kubuntu 20.04 | **Kernel:** 5.4.0-48-generic | **qt:** 5.12.8)
**Modded:** No & Yes (tried modded and non-modded. **Mods are:** carrycapacity, gates, hayblocks and VSHUDCompat)

### Description

After creating a world, the game freezes on the loading dialogue. After a moment of sitting there, it will crash to the desktop without an error message. It does the same with logging into a world. I've tried no mods (with no mods, the game will load in but freeze as soon as you see the world) and moving mods between /ApplicationData/vintagestory/mods to /.config/VintagestoryData/Mods/, but it did nothing. Game refuses to load in.

### How to reproduce
1. Make a world / log into a world
2. Wait through loading dialogue 
3. Click screen after it seemingly "stops" loading (when the text stops)

### Expected behavior
N/A

### Screenshots

https://i.imgur.com/kcZWyc2.png

### Logs

**client-main.txt:** https://gist.github.com/Rhyagelle/51956909c43d9dc16020d9dd33120587
**server-main.txt:** https://gist.github.com/Rhyagelle/2a05b623b1f7bf6aa88a51b5e04a9da1

**Comment by copygirl** [comment]
Copying the exception from `client-main.txt` for making future searches easier:
```
23.9.2020 18:48:53 [Fatal] Version: v1.13.4 (Stable)9/23/2020 6:48:53 PM: Critical error occurred
System.TypeLoadException: VTable setup of type VSHUD.LightUtilSystem failed
  at VSHUD.LightUtilModSystem.<StartClientSide>b__3_0 () [0x00000] in <4653ab348fa043359047af2b3c5ff576>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize () [0x0000a] in <f4a48dd783cc40918cec721779475ae5>:0 
  [...]
```

You say that a similar issue occurs without mods, too. Can you try that and upload your `client-main.txt` again?

**Comment by tyronx** [comment]
Thanks for the report, but that's a mod crashing, not an issue of the vanilla game. Please report it to Novocain instead. If it crashes without mods, please create a new ticket.

**Comment by copygirl** [comment]
The `TypeLoadException` is strange, but it might indeed be an incompatibility with newer versions of the game. If you get a different exception when running the game without mods, I recommend opening another issue. Otherwise, respond and I will reopen the issue.

**Comment by Rhyagelle** [comment]
It still crashes without the mods, yea. 

And certainly. Here is the log for without mods. It is a slightly different kind of crashing. When the world loads in, it freezes at "sight" of the world and then closes to the desktop. I get orange and red text in the terminal (when I run "mono vintagestory.exe"), too. 

**Log:** https://gist.github.com/Rhyagelle/8bd60a4dc0018e93230a22911c3043d8

(terminal output is massive, and forgets prior text if it gets too big, so I've cut the start of the text from when it begins and tried to capture it as it crashes)

**Terminal output (launch):** https://gist.github.com/Rhyagelle/2c044d212d17b60c3248c0804081b61d

**Terminal output (end, crash):** https://gist.github.com/Rhyagelle/91a64b133fda11a9f9561fe41fada0ec

**Comment by copygirl** [comment]
The `Stream does not support writing` is likely just from the game trying to print one of those texture leak messages while the game already closed, which themselves are probably also from the game closing unexpectedly? That's my guess, anyway. I'm not sure I can help more.
