### ISSUE TITLE
MissingMethodException (set_LargeObjectHeapCompactionMode) on game start

### ISSUE THREAD

**Issue by Demyan255** [anegostudios/VintageStory-Issues#591]
### Game Version: 1.13.4
Platform: Windows 7
Modded: No

### Description
When I run the game it gives an error

### How to reproduce
 It crashes / doesn't do the thing.

### Expected behavior
I would like the game to start

### Screenshots
They are not needed here

### Logs
Client-crash:
Version: v1.13.4 (Стабильно) artEA#800126.09.2020 9:18:32: Critical error occurred
System.MissingMethodException: Method not found: 'Void System.Runtime.GCSettings.set_LargeObjectHeapCompactionMode(System.Runtime.GCLargeObjectHeapCompactionMode)'.
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(_6Ki7onGUDN2hMDvAS3I5KRRsLrr logger)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )

Client-main:
26.9.2020 09:18:32 [Notification] Client logger started.
26.9.2020 09:18:32 [Notification] Game Version: v1.13.4 (Стабильно) artEA#8001
26.9.2020 09:18:32 [Warning] Client side assembly resolver did not find the assembly in the binary path, the lib path or the mods path. Tested for the following paths: 
E:\Vintage Story v1.13.4\Lib\MonoMac.dll
E:\Vintage Story v1.13.4\MonoMac.dll
C:\Users\Demyan\AppData\Roaming\VintagestoryData\Mods\MonoMac.dll
E:\Vintage Story v1.13.4\Mods\MonoMac.dll

**Comment by copygirl** [comment]
Tyron recommends installing the [latest .NET Framework](https://www.microsoft.com/en-US/download/details.aspx?id=55167) to fix the issue [as seen here](https://www.vintagestory.at/forums/topic/1501-spiel-startet-nicht/) (German).

Please let me know if that fixes your crash.

**Comment by copygirl** [comment]
I'm going to assume this is resolved.
