### ISSUE TITLE
little GUI glitch

### ISSUE THREAD

**Issue by reicherBene** [anegostudios/VintageStory-Issues#593]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
When hovering over the "close handbook" button, there seems to be too much offset on the orange text (more than the other buttons). No big deal, just wanted to mention :)

### Screenshots
![2020-09-26_14-23-24](https://user-images.githubusercontent.com/61832950/94340842-26c1be80-0005-11eb-900c-a41afb551a09.png)

**Comment by Craluminum2413** [comment]
Not actual? Don't have this issue in 1.15.0-pre.2 for example
