### ISSUE TITLE
Constant Drifter Sound Effects

### ISSUE THREAD

**Issue by ApacheTech** [anegostudios/VintageStory-Issues#595]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

 **Sound Effects Bug:**

When stood in the third story of a fully enclosed building, over 20 blocks above ground level, the noise from the drifters spawning in the caves 30+ blocks below the building is still plainly audible, and as loud as it would be if the Drifters were in the same room. This causes an incessant white-noise when playing which is nigh-on impossible to get away from while in the vicinity of the build. I believe this to be a bug, or at the least, an oversight. There is currently no efficient way to light up caves, or surrounding area to stop the spawning, so it means that even during daytime hours, drifters still spawn, and are insanely loud, considering they are over 50 blocks away, in a sealed cave, through multiple layers of rock, gravel, grass, and wood. I shouldn't be able to hear them at all.

**Steps to reproduce:**

1. Find an underground cave.
2. Light up the surrounding surface area (in my case, a building), to dissuade spawning in the immediate area.
3. Stay in the area through a few day cycles.

**Expected Results:**

 • Groaning during the night from surface drifters that spawn and wander into the lit up area, but then leave in the morning.
 • Other than that, silence.

**Actual results:**

 • Groaning during the night from surface drifters that spawn and wander into the lit up area, but then leave in the morning.
 • Loud, incessant, relentless groaning from the caves below ground.

**Potential Fixes:**

 • When in an enclosed area, such as a building, with the doors closed, drifter noises from outside should be muted.
 • Drifters within underground caves should be muted when players are on the surface above.

**Preferred Additional Fix to the wider problem:**

 • Include an ability to adjust/mute the volume of hostile mobs within the Sound Options of the game (bringing in the option to adjust/mute passive mobs, neutral mobs, echo chambers, and block interaction sfx).

**Why this is a bug/oversight:**

 • There is currently no possible way to get away from the constant white-noise of these drifters. It's insufferable, and destroys the playability of the game. There is no way that the sound should penetrate through the ground like this, and there is no way to stop it short of overwriting the drifter sound effect files of the game with silent OGG files. 
```

**Comment by Craluminum2413** [comment]
@ApacheTech it doesn't happen anymore?

**Comment by ApacheTech** [comment]
This was fixed years ago.
