### ISSUE TITLE
Fog ignores doors

### ISSUE THREAD

**Issue by whitebyte** [anegostudios/VintageStory-Issues#596]
**Game Version:** 1.13.4
**Platform:** Linux
**Modded:** No

### Description
Fog ignores doors. It appears in closed rooms that have doors, the only way to make it disappear is to use solid materials.
Technically there are small windows inside a door, but I thought it's purely cosmetic.

If it's intended behavior, would be nice to have a new "hermetic" door recipe with glass windows

### Screenshots
![fog](https://user-images.githubusercontent.com/7704186/94467809-1f98dd00-01cc-11eb-9b21-2a58aae7b3e4.png)

**Comment by copygirl** [comment]
See #1538.
