### ISSUE TITLE
Character screen - unreadable  text

### ISSUE THREAD

**Issue by whitebyte** [anegostudios/VintageStory-Issues#597]
**Game Version:** 1.13.4
**Platform:** Linux (KDE Neon, Ubuntu derivative)
**Modded:** No

### Description
Unreadable text on the character screen, please see the attached screenshot

### Screenshots
![unreadable](https://user-images.githubusercontent.com/7704186/94471284-8bca0f80-01d1-11eb-8b40-3ab811bf2b13.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.14
