### ISSUE TITLE
Locked into death screen on multiplayer after dying of hunger

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#6]
> On multiplayer, I died of hunger, and cannot re-spawn, only Rage quit. When I re-loaded the game  I instantly died again, still hungry.  Did several times, same thing happens, over and over.

~ John Erik Oliveira [on the forums](https://www.vintagestory.at/forums/topic/347-multiple-bugs-will-add-as-found/?do=findComment&comment=2088)

**Comment by tyronx** [comment]
Is this reliably reproducible still? Anyone else experiencing this?

**Comment by tyronx** [comment]
No feedback provided in 2 months. Closing issue.
