### ISSUE TITLE
Interacting on an already opened chest causes GUI to stop updating

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#60]
When you place items in the glitched GUI they will appear to disappear, and removing items appears to leave behind a duplicate. This is only a visual glitch, no actual duplication or voiding of items seems to occur.

Shouldn't right clicking a chest when it's already open close it? Perhaps with a small sub-second grace period so accidental double-clicking (due to impatience & lag?) doesn't immediately close it.

**Comment by tyronx** [comment]
> Shouldn't right clicking a chest when it's already open close it? 
Ok, did just that now for 1.5.3.
