### ISSUE TITLE
Crash when copying to clipboard (Requested Clipboard operation did not succeed)

### ISSUE THREAD

**Issue by SpxterWohlf** [anegostudios/VintageStory-Issues#600]
**Game Version:** v1.13.4
**Platform:** Windows 2004
**Modded:** Yes https://i.imgur.com/pC290bB.png

### Description
Tried to copy seed to clipboard and it crashed

### How to reproduce
1. Started game,
> I turned off the music
> I also opened a world and canceled the opening process (with the button)
2. I opened the edit button next to a world
3. I pressed copy seed to clipboard

### Expected behavior
To not crash

### Logs

**Crash Report**
```
https://gist.github.com/Wohlf-craft/9fa9f4e1ffa66c09120ee9f382a2f207

**Client-main.txt**
```https://gist.github.com/Wohlf-craft/4fc469e282d0094cda3218afbf654e70```

**Server-main.txt**
```https://gist.github.com/Wohlf-craft/dc2b33a5e0e86e30970a7dfa6c4ba9c5```

**Comment by copygirl** [comment]
The crash report and logs 404 for me.

**Comment by Craluminum2413** [comment]
I tried to do this in 1.15, nothing crashed for me. I don't know in which version it was fixed

**Comment by copygirl** [comment]
Might have been an issue with that particular Windows version. Will close for now.
