### ISSUE TITLE
Binding sneak to the left Alt key doesn't work (on Windows)

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#605]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
I'm used to use the left alt for sneaking (in other games). When I bound the left Alt in the Vintage Story to the Sneak, it doesn't work. I can bind the key, but the sneaking doesn't work.

### How to reproduce
1. Bind the left Alt key to the Sneaking.
2. Try to sneak using the left alt in game. It doesn't sneak. It just freeze a player rotating while holding it.

### Expected behavior
I expect that sneaking will work on the left Alt key

Thanks!
Fipil

**Comment by copygirl** [comment]
Certain keys, like the mouse buttons, are currently hardcoded into the game. The `Alt` key is used to switch between locking and unlocking the mouse cursor from the game - something that is particularly useful / needed when playing with Immersive Mouse Mode enabled. (You can use it to look around after opening a container.)

But yes, this key should ideally be able to be rebound (#565) or unbound (#404) completely so you can use it for sneaking. I will poke Tyron to get his attention on these issues once again.

**Comment by fipil** [comment]
Tahks, for me it's quite uncomfortable to use a different keys, as I'm used to use and configure my own keys for moving, such I'm using in all games. 
If it would be possible to do it by creating a mod, I can do it. I'm a .net senior developer, so if this is the possible way, i'd like to do it.

**Comment by tyronx** [comment]
Hokay, made the alt key no longer hardcoded. It can now be remapped like any other key. Meaning if you remap the new "release mouse cursor" key then putting sneak on alt should work as intended. Will be in the next release of the game. 

If you would like the thing right away and want to mod it either delete the release mouse cursor code or patch it as i did:
1. Register a new hotkey (via capi.Input.HotKeys)
2. Add a reference to VintageStoryLib.dll to your project, cast api.World to ClientMain, from there on somehow use the Harmony code patching library to patch UpdateFreeMouse() to use the new hotkey (I never used Harmony). You'd need to replace the first line
`bool isAltKeyDown = KeyboardState[(int)GlKeys.AltLeft] || KeyboardState[(int)GlKeys.AltRight];`
with this
```
int altKey = ScreenManager.hotkeyManager.HotKeys["releasemouse"].CurrentMapping.KeyCode;
bool isAltKeyDown = KeyboardState[altKey];
```

**Comment by fipil** [comment]
Thank you very much, that's great!
