### ISSUE TITLE
Uh oh! crash Report

### ISSUE THREAD

**Issue by Wulfgang99** [anegostudios/VintageStory-Issues#606]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```Running on 64 bit Windows with 8 GB RAM 
Version: v1.13.4 (Stable)10/4/2020 9:23:52 PM: Critical error occurred
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos()
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

**Comment by Wulfgang99** [comment]
so yeah, help me fix this so that i can play the damn game, or send me back the money i spent to buy the fucker

**Comment by copygirl** [comment]
I can only recommend making sure that you have the right graphics driver installed. With your attitude, I do not wish to debug this issue any further than that. You can request a refund for the game [here](https://www.vintagestory.at/support/).

**Comment by Wulfgang99** [comment]
I am sorry about the attitude. Was immature of me for sure. Thanks for the recommended fix, I will look it this.

Agin I apologize for being rude.
________________________________
