### ISSUE TITLE
Cooking issues with cooked cattail roots

### ISSUE THREAD

**Issue by lOmicronl** [anegostudios/VintageStory-Issues#609]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
This may be a regression of #497.

When cooking with a claypot, cooked cattail roots are valid ingredients - both for starting a vegetable stew, and as an added vegetable in other meal types. #497 suggests that this should not be the case.

When cooking such meals, cooked cattail roots generate no texture inside the pot. With a vegetable stew, this results in an empty pot that nevertheless still steams and contains food that can be eaten from bowls or filled into crocks. Other meal types look as they would if no secondary ingredient was present, but do have vegetable satiety values.

Using one or more cooked cattail roots in a claypot results in a broken string for the meal.

Uncooked cattail roots are not valid ingredients for cooking.

### How to reproduce
1. Create a firepit
2. Place a claypot on the firepit
3. Form a valid pot cooking recipe that includes one or more cooked cattail roots as a primary or secondary vegetable ingredient

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.14.0 stable. Cattail roots were not meant as valid meal ingredient and no longer will be there.
