### ISSUE TITLE
First item in pile causes temperature reassignment (Plates/Ingots, etc.)

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#611]
Description:
When placing down a pile of ingots, or plates, the pile will assume the temperature value of the first ingot or plate used to create the pile, ("the base item") and assume its heat value. 

The base item's temperature will decay normally, over time, as will any other items added to the stack, but new items can used or added in this way to instantly heat them to the base item's current temperature.

This issue very likely extends to planks, peat and firewood as well, though the application for that is far more limited than metal bars and plates. I did not test for planks/peat/firewood due to the lack of game benefit in raising their temperature.  It is also similarly likely this could effect clay ingot molds, as they're the only one that can really 'pile' with another item.

Game Version:
1.13.4

Steps to Reproduce:
1. Heat up any ingot to any temperature, ideally one that is visibly noticeable
2. Place the ingot on the ground, in a pile, using shift-mb2.
3. Add unheated ingots to the pile.
4. All ingots become the temperature of the base ingot.

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/topic/3726-wintery-stability-patch-v1146-rc1/?tab=comments#comment-15496
"Tweak: Adding ingots to existing piles of ingots now averages and spreads the temperature"
