### ISSUE TITLE
Attempting to merge unfilled, un-mergeable Crocks causes one to become empty.

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#613]
**Game Version:** 1.13.4
**Platform:** Win

### Description
Attempting to combine crocks that would not normally properly combine causes one of the crocks to empty out.

### How to reproduce
1. Cook some food with 2 servings and 3-4 ingredients.
2. Cook some different food with 2 servings and 3-4 ingredients.
3. Store both in separate crocks, sealing irrelevant.
4. Attempt to transfer food from one crock to another, via shift+mb2, while one is placed on the ground.
5. One crock becomes empty.

### Expected behavior
Crocks not eating their food.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.14
