### ISSUE TITLE
Stuck in block when using bed

### ISSUE THREAD

**Issue by Namele5s** [anegostudios/VintageStory-Issues#614]
**Game Version:** 1.13.4
**Platform:** Windows 
**Modded:** No 

### Description
Explain the issue you're running into.

### How to reproduce
1. Sleep in hay bed
2. Wake up, stuck in block
3. Exiting the world and reloading seems to work around

Link is the save file where it's occurring. [https://drive.google.com/file/d/17eLdZNk1_g2ngA3Ld0kvwxX81FlIii85/view?usp=sharing](https://drive.google.com/file/d/17eLdZNk1_g2ngA3Ld0kvwxX81FlIii85/view?usp=sharing)

### Expected behavior
Wake up after using bed be above the bed and/or not stuck

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by Rovetown** [comment]
Couldn't you just make it so the Player spawns next to the bed? scan if a block is directly in contact with the bed, and if not, then spawn the player there.

**Comment by Th3Dilli** [comment]
this should have been fixed a while back already

the new behavior is to try and find a free spot next to the bed to put the player in to prevent that
