### ISSUE TITLE
Entities vanish in the sky

### ISSUE THREAD

**Issue by TaskaRaine** [anegostudios/VintageStory-Issues#616]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
A throwable entity will vanish any time its position is approximately 32+ blocks above ground level. It will continue to move along its trajectory until it nears the ground, then becomes visible once again. They seem to still exist as objects in the world. They just aren't rendered.

This was checked with a thrown spear, a thrown rock, flax grain and terra preta that were dropped from the hotbar with Q. 

### How to reproduce
1. Create a new world, creative or survival.
2. Activate creative mode and fly sufficiently high into the sky. Preferably well beyond 32+ blocks from the ground. 
3. Give yourself a spear or throwable stone through the creative menu.
4. Throw the object downward.
5. The object will not visibly appear until it nears the ground.

### Expected behavior
I'd expect entities to always be visible unless they are out of render range. 

### Logs
I didn't see any relevant log information.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.3
