### ISSUE TITLE
1.14.0-pre.1 Crash when placing bloom on anvil.

### ISSUE THREAD

**Issue by TheHaterofGravel** [anegostudios/VintageStory-Issues#617]
**Game Version:** 1.14.0-pre.1
**Platform:** Windows
**Modded:** No

### Description
The game crashes when an iron bloom is placed on an anvil. Tried on new world, and on a pre-1.14 world and gotten the same results. 

### How to reproduce
1. Get an iron bloom.
2. Place it on any anvil.
3. Game crashes.

### Logs

Client-main:
https://gist.github.com/TheHaterofGravel/f910b3e303dc357f3c1d53ecccab3dd5#file-client-main
Server-main:
https://gist.github.com/TheHaterofGravel/19d10fec2c46dba6e47d6d492b598673

**Comment by TheHaterofGravel** [comment]
Similar crash happens when you place a heated meteoric iron ingot down on a bronze anvil.
log:
Client-main:
https://gist.github.com/TheHaterofGravel/1b198fba69e5357a9dd02679818b8079

**Comment by tyronx** [comment]
Thanks for the report, i've now fixed these issues, will be in pre.3

**Comment by jrddunbr** [comment]
Darn! I searched for the crash text and didn't see anything. Sorry to duplicate..

**Comment by tyronx** [comment]
No problem! 👍
