### ISSUE TITLE
1.14-pre.1 Crash when viewing either archimedes screw recipes

### ISSUE THREAD

**Issue by TheHaterofGravel** [anegostudios/VintageStory-Issues#618]
**Game Version:** 1.14-pre.1
**Platform:** Windows
**Modded:** No

### Description
When looking in the handbook for either Archimedes screw recipes, the game crashes. 

### How to reproduce
1. Open handbook.
2. Search either Archimedes screw recipes (ported or standard).
3. Game crashes.

### Logs
client-main:
https://gist.github.com/TheHaterofGravel/cc495f5e94ad0ea547cecf8feb2f9064
server-main:
Its a client-side crash, no meaningful data in server-main log.

**Comment by tyronx** [comment]
Thanks for the report, this should be fixed in pre.2
