### ISSUE TITLE
Large gears and windmills??

### ISSUE THREAD

**Issue by Karther** [anegostudios/VintageStory-Issues#621]
**Game Version:** X.Y.Z
**Platform:** Windows 10
**Modded:** yes but I remove mods and get same effect. Large wheel simply stops when anything attached to it.

### Description
Large Gears when put in place run hammer for a second Super fast then it all stops and even if you remove a gear here and replace or other they always end up stopping.. This is even with only helve hammer attached.. and plenty of wind windmill with just hammer of just Quern on large gear do same thing at full wind

### How to reproduce
1. Make windmill 
2. Use it on helve hammer or quern with large gear
3. Gears al stop turning ( and no
![2020-10-24_22-55-49](https://user-images.githubusercontent.com/8433115/97100184-f4c86a00-164d-11eb-89f5-50805db56574.png)
![2020-10-24_22-55-49](https://user-images.githubusercontent.com/8433115/97100189-0447b300-164e-11eb-848f-86d3e3482e5e.png)

 there's plenty of wind.

### Expected behavior
Large wheel should turn and support helve hammer and possibly other item quern. Works for second super fast then it all stops..

### Screenshots
I dragged it over I dont know if it attached it didnt show after it timed for a min..?

Game doesn't crash so not sure If log matters..?
### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
Will close as duplicate for now. Tyron created an issue (#579) to collect mechanical power related things. From what I remember, I saw a video on the weirdness of large gears when they were chained together. It would briefly power things very fast, then halt. Presumably because of the "stress" being too high?
