### ISSUE TITLE
Cooked food disappearing!?

### ISSUE THREAD

**Issue by RepsacA** [anegostudios/VintageStory-Issues#623]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
When you take a Claypot from the campfire with newly cooked food, then right click on the small Fired Crock with the Claypot in hand(twice) all the servings disappear both in the pot and the Fired Crock..

 ### How to reproduce
1. Make a 'Claypot'
2. Use it on 'Firedcrock (twice in a row)'
3. Food disappears.

### Expected behavior
Contain all the food from the Claypot into the small Fired crock.

### Screenshots
![2020-10-25_17-32-46](https://user-images.githubusercontent.com/42547899/97113145-a916ce80-16e8-11eb-9c49-6ad3a0b24de4.png)

### Logs
game doesn't crash..

**Comment by tyronx** [comment]
thanks for the report, annoying bug indeed, its fixed in v1.14
