### ISSUE TITLE
Extremely loud thunder and lightning sounds are not classed as "weather".

### ISSUE THREAD

**Issue by ApacheTech** [anegostudios/VintageStory-Issues#624]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
With "Weather sound level" on 0%, the ear-piercingly loud thunder and lightning effects still play at 100% volume.

Also, there's a typo in the sound option name, it should read "Weather Sound Level", rather than "Weather sound level".

### How to reproduce
1. Set "Weather sound level" to 0%.
2. Set weather pattern to stormy.
3. Throw headphones across room, and recover from temporary tinnitus.

### Expected behaviour
1. Set "Weather sound level" to 0%.
2. Set weather pattern to stormy.
3. Blissful, beautiful silence.

### Screenshots
N/A

### Logs
N/A

**Comment by noelle-lavenza** [comment]
`/lntest` on weather sound level 0% results in no sound. Seems to have been fixed at some point. The incorrect capitalisation is still there though, but should likely be its own separate issue—maybe combined with other similar cases.
