### ISSUE TITLE
Cheesemaking Guide

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#627]
Add a cheesemaking guide for 1.14 to help players on how to make and preserve cheese and all dairies.

**Comment by Craluminum2413** [comment]
Added in [1.15.0-rc.1](https://www.vintagestory.at/blog.html/news/the-homesteading-update-v115-rc1-r284/):
> Feature: Handbook additions, including cheese making

![image](https://user-images.githubusercontent.com/69315569/124743447-6e775e00-df26-11eb-8f1d-89a58b204dbf.png)
