### ISSUE TITLE
graceTimer does not default to zero and Temporal Stability is stuck at 0% on new dedicated server start

### ISSUE THREAD

**Issue by astynax777** [anegostudios/VintageStory-Issues#628]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
Starting a new dedicated server by launching the VintagestoryServer.exe directly defaults the graceTimer to over 52 days.  The Temporal Stability gear indicator shows 0% and does not change.  Running /worldconfig graceTimer on the server console shows the value is 0.  

### How to reproduce
1. Launch a dedicated server on fresh install by running VintagestoryServer.exe
2. Notice no drifters appear
3. After one game day the in-game message will notify you that Over 52 days left before monsters begin to appear
4. Also notice the Temporal Stability is at 0% and does not change

### Expected behavior
Default graceTimer

### Screenshots
![image](https://user-images.githubusercontent.com/1410906/97333971-8b657880-1852-11eb-9539-b4a615226a5a.png)
![image](https://user-images.githubusercontent.com/1410906/97334392-147caf80-1853-11eb-9640-3294e17da78c.png)

### Logs
N/A

**Comment by astynax777** [comment]
So far in my troubleshooting to see what causes this, it appears to happen when the server needs to generate the serverconfig.json file.

**Comment by tyronx** [comment]
Is that an old world or newly generated world by the server? Did you run any other /worldconfig commands?

**Comment by tyronx** [comment]
Ok, no need to answer those, I figured it out, will be fixed next release, thank you!
