### ISSUE TITLE
Server crashes on launch in Official Mono Docker image

### ISSUE THREAD

**Issue by nalabelle** [anegostudios/VintageStory-Issues#629]
**Game Version:** 1.13.4

**Platform:** Linux
**Modded:** No

### Description
The server crashes when on launch when running in the Mono Docker container. It appears to be failing to enumerate a path while trying to open a connection to the SQLite database in the Saves folder.

### How to reproduce
1. Build an image using [Dockerfile.txt](https://github.com/anegostudios/VintageStory-Issues/files/5450016/Dockerfile.txt): `docker build -t vintage-story .`
2. Create a data volume: `docker volume create vintage-story`
3. Start the container with `docker run -v vintage-story:/app/data --rm -it --entrypoint /bin/bash vintage-story`
4. Run the server: `mono VintagestoryServer.exe --dataPath /app/data`
5. The server crashes with:
~~~
Version: v1.13.4 (Stable)10/28/2020 06:27:50: Critical error occurred
System.IO.FileNotFoundException: Could not find file ""
  at System.IO.DriveInfo.GetDiskFreeSpace (System.String path, System.UInt64& availableFreeSpace, System.UInt64& totalSize, System.UInt64& totalFreeSpace) [0x00014] in <f2b3ab7dfff746f594d2ef5b16ec3c90>:0
~~~

and a 0 byte `default.vcdbs` is created.

### Logs
[server-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/5450006/server-crash.txt)
[vs_trace.txt](https://github.com/anegostudios/VintageStory-Issues/files/5450009/vs_trace.txt)
[serverconfig.json.txt](https://github.com/anegostudios/VintageStory-Issues/files/5450043/serverconfig.json.txt)
Filesystems:
~~~
Filesystem                                                                       Size  Used Avail Use% Mounted on
storage/docker/971fa53644fd405b9d115aadfafef3b4508e049e5089158b91f8564846d670e4  500G  831M  499G   1% /
tmpfs                                                                             64M     0   64M   0% /dev
tmpfs                                                                             27G     0   27G   0% /sys/fs/cgroup
shm                                                                               64M     0   64M   0% /dev/shm
storage/docker/volumes                                                           884G  385G  499G  44% /app/data
storage/docker                                                                   500G  502M  499G   1% /etc/hosts
tmpfs                                                                             27G     0   27G   0% /proc/acpi
tmpfs                                                                             27G     0   27G   0% /sys/firmware
~~~

Let me know if there's anything further I can provide to help, thanks!

**Comment by tyronx** [comment]
huh, strange. can i also see the server-main.txt?

**Comment by DArkHekRoMaNT** [comment]
No further info provided. Closed as stale
