### ISSUE TITLE
SQLiteException: The database disk image is malformed

### ISSUE THREAD

**Issue by Gaxon1** [anegostudios/VintageStory-Issues#631]
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
Had a power outage and PC shut down. When I logged back the cooking pot was on my hotbar but also on the cooking fire I had just removed it from.

### Logs
1.11.2020 22:55:20 [Notification] Server logger started.
1.11.2020 22:55:20 [Notification] Game Version: v1.13.4 (Stable)
1.11.2020 22:55:20 [Event] Launching server...
1.11.2020 22:55:20 [Event] Server v1.13.4, network v1.13.6, api v1.7.0
1.11.2020 22:55:20 [Notification] Entering runphase Initialization
1.11.2020 22:55:20 [Event] Loading configuration...
1.11.2020 22:55:20 [Notification] Entering runphase Configuration
1.11.2020 22:55:20 [Notification] Loading savegame
1.11.2020 22:55:20 [Notification] Loaded existing save game data. Playstyle: surviveandbuild, Playstyle Lang code: preset-surviveandbuild, WorldType: preset-surviveandbuild
1.11.2020 22:55:20 [Notification] Savegame C:\Users\chris\AppData\Roaming\VintagestoryData\Saves\sunny village lands.vcdbs loaded
1.11.2020 22:55:20 [Notification] World size = 1000000 256 1000000
1.11.2020 22:55:20 [Event] Loading assets...
1.11.2020 22:55:20 [Notification] Start discovering assets
1.11.2020 22:55:20 [Notification] Found 0 base assets in category blocktypes
1.11.2020 22:55:20 [Notification] Found 0 base assets in category itemtypes
1.11.2020 22:55:20 [Notification] Found 13 base assets in category lang
1.11.2020 22:55:20 [Notification] Found 0 base assets in category patches
1.11.2020 22:55:20 [Notification] Found 22 base assets in category config
1.11.2020 22:55:20 [Notification] Found 0 base assets in category worldproperties
1.11.2020 22:55:20 [Notification] Found 31 base assets in category sounds
1.11.2020 22:55:20 [Notification] Found 2 base assets in category shapes
1.11.2020 22:55:20 [Notification] Found 59 base assets in category textures
1.11.2020 22:55:20 [Notification] Found 0 base assets in category recipes
1.11.2020 22:55:20 [Notification] Found 0 base assets in category worldgen
1.11.2020 22:55:20 [Notification] Found 1 base assets in category entities
1.11.2020 22:55:20 [Notification] Found 128 base assets in total
1.11.2020 22:55:20 [Notification] Entering runphase AssetsReady
1.11.2020 22:55:20 [Notification] Will search the following paths for mods:
1.11.2020 22:55:20 [Notification]     C:\Users\chris\AppData\Roaming\Vintagestory\Mods
1.11.2020 22:55:20 [Notification]     C:\Users\chris\AppData\Roaming\VintagestoryData\Mods
1.11.2020 22:55:20 [Notification] Found 3 mods (0 disabled)
1.11.2020 22:55:20 [Notification] Mods, sorted by dependency: game, creative, survival
1.11.2020 22:55:20 [Notification] Instantiated 62 mod systems from 3 enabled mods
1.11.2020 22:55:20 [Notification] External Origins in load order: custom@C:\Users\chris\AppData\Roaming\Vintagestory\assets\creative\, custom@C:\Users\chris\AppData\Roaming\Vintagestory\assets\survival\
1.11.2020 22:55:20 [Notification] Found 248 external assets in category blocktypes
1.11.2020 22:55:20 [Notification] Found 149 external assets in category itemtypes
1.11.2020 22:55:20 [Notification] Found 0 external assets in category lang
1.11.2020 22:55:20 [Notification] Found 11 external assets in category patches
1.11.2020 22:55:20 [Notification] Found 26 external assets in category config
1.11.2020 22:55:20 [Notification] Found 22 external assets in category worldproperties
1.11.2020 22:55:20 [Notification] Found 261 external assets in category sounds
1.11.2020 22:55:20 [Notification] Found 1174 external assets in category shapes
1.11.2020 22:55:20 [Notification] Found 2769 external assets in category textures
1.11.2020 22:55:20 [Notification] Found 218 external assets in category recipes
1.11.2020 22:55:20 [Notification] Found 308 external assets in category worldgen
1.11.2020 22:55:20 [Notification] Found 51 external assets in category entities
1.11.2020 22:55:20 [Notification] Reloaded lang file with mod assets
1.11.2020 22:55:20 [Event] Loading save game...
1.11.2020 22:55:20 [Notification] Entering runphase ModsAndConfigReady
1.11.2020 22:55:20 [Notification] JsonPatch Loader: 2 patches total, successfully applied 2 patches, no errors
1.11.2020 22:55:21 [Notification] Reloaded 18 weather patterns, 5 wind patterns and 5 weather events
1.11.2020 22:55:24 [Notification] BlockLoader: Entities, Blocks and Items loaded
1.11.2020 22:55:24 [Notification] Started 57 systems on Server:
1.11.2020 22:55:24 [Notification]     Mod 'VSEssentials.dll' (game):
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.Core
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.EntityPartitioning
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ErrorReporter
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
1.11.2020 22:55:24 [Notification]         Vintagestory.Essentials.PathfindSystem
1.11.2020 22:55:24 [Notification]         Vintagestory.Essentials.PathFindDebug
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.JsonExport
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.LeafBlockDecay
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.POIRegistry
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.RoomRegistry
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.WeatherSystemServer
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.WorldMapManager
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.LoadColorMaps
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.RecipeLoader
1.11.2020 22:55:24 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenPatchesPrePass
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.SaplingControl
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenSnowLayer
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenTerra
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
1.11.2020 22:55:24 [Notification]         VSSurvivalMod.Systems.GameEffects
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.NpcControl
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenCreatures
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenMaps
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.WgenCommands
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.DebugSystem
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.UpgradeTasks
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ModTemperature
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.CustomSpawnConditions
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.SystemTemporalStability
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ModJournal
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ModLootRandomizer
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.ModSleeping
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.TeleporterManager
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenDeposits
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenStructures
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenCaves
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenBlockLayers
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenPonds
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenVegetation
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenRivulets
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenLightSurvival
1.11.2020 22:55:24 [Notification]         Vintagestory.GameContent.TraderOutfits
1.11.2020 22:55:24 [Notification]     Mod 'VSCreativeMod.dll' (creative):
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.Core
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
1.11.2020 22:55:24 [Notification]         Vintagestory.ServerMods.GenLightCreative
1.11.2020 22:55:26 [Event] 5 metal alloys loaded
1.11.2020 22:55:26 [Event] 5 cooking recipes loaded
1.11.2020 22:55:26 [Event] 232 crafting recipes loaded from 133 files
1.11.2020 22:55:26 [Event] 148 smithing recipes loaded
1.11.2020 22:55:26 [Event] 52 clay forming recipes loaded
1.11.2020 22:55:26 [Event] 31 knapping recipes loaded
1.11.2020 22:55:26 [Event] 46 barrel recipes loaded
1.11.2020 22:55:26 [Notification] Server map set
1.11.2020 22:55:26 [Notification] Entering runphase LoadGame
1.11.2020 22:55:26 [Notification] Entering runphase WorldReady
1.11.2020 22:55:27 [Notification] Reloaded 25 tree generators
1.11.2020 22:55:27 [Event] Loading 7x7x8 spawn chunks...
1.11.2020 22:55:27 [Event] 0% (49 in queue)
1.11.2020 22:55:27 [Event] Begin save game ticking...
1.11.2020 22:55:27 [Notification] Entering runphase RunGame
1.11.2020 22:55:27 [Notification] Starting server threads
1.11.2020 22:55:27 [Event] Singleplayer Server now running!
1.11.2020 22:55:27 [Notification] All clients disconnected, pausing game calendar.
1.11.2020 22:55:27 [Notification] A Client attempts connecting via Dummy connection, assigning client id 1
1.11.2020 22:55:27 [Notification] Client uid ************************* attempting identification. Name: Gaxon
1.11.2020 22:55:27 [Notification] Placing player at 500055.78125 111 499989.125
1.11.2020 22:55:31 [Warning] Server overloaded. A tick took 515ms to complete.
1.11.2020 22:55:36 [Event] Gaxon 127.0.0.1 joins.
1.11.2020 22:55:37 [Notification] A client reconnected, resuming game calendar.
1.11.2020 22:55:53 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
1.11.2020 22:55:53 [Fatal] System.Data.SQLite.SQLiteException (0x80004005): The database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at _0iMxI2I03vkzFydOIflolMqTuob._FhMBcrv6PCJe0HTCihF1fLlS7NaA(UInt64 , String )
   at Vintagestory.Server.ServerSystemSupplyChunks.TryLoadMapChunk(Int32 chunkX, Int32 chunkZ, ServerMapRegion forRegion)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapChunk(Int32 chunkX, Int32 chunkZ)
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn()
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeperateThreadTick(Single dt)
   at Vintagestory.Server.ServerThread.Update()
   at Vintagestory.Server.ServerThread.Process()
1.11.2020 22:55:53 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exeption during Process
1.11.2020 22:55:53 [Notification] Server ticking has been suspended
1.11.2020 22:55:53 [Notification] Entering runphase Shutdown
1.11.2020 22:55:53 [Notification] Defragmented listener lists
1.11.2020 22:55:53 [Event] Mods and systems notified, now saving everything...
1.11.2020 22:55:53 [Event] Saved savegamedata...
1.11.2020 22:55:53 [Event] Saved player world data...
1.11.2020 22:55:53 [Event] Saved map regions...
1.11.2020 22:55:53 [Event] Saved map chunks...
1.11.2020 22:55:53 [Event] Saved loaded chunks...
1.11.2020 22:55:53 [Event] Saved generating chunks...
1.11.2020 22:55:53 [Event] World saved! Saved 20 chunks, 0 mapchunks, 0 mapregions.
1.11.2020 22:55:53 [Event] Shutting down 5 server threads... 
1.11.2020 22:55:53 [Event] Killed console thread
1.11.2020 22:55:53 [Event] All threads gracefully shut down
1.11.2020 22:55:53 [Event] Doing last tick...
1.11.2020 22:55:53 [Event] Stopped the server!
1.11.2020 22:55:53 [Warning] Server overloaded. A tick took 682ms to complete.

**Comment by Craluminum2413** [comment]
#690, #773, #814, #868

**Comment by copygirl** [comment]
#690 @JennyFunny
> #### Description
> Crashes on connection to server (vamist.dev)
> #### How to Reproduce
> Game crashes on connection, it crashed instantly when i put the bronze saw into the crafting square.
Crashes on connection always afterwards.

#773 @Bertramqaz
> #### Description
> I recently downloaded the map of a multiplayer server hosted with some friends (in 1.14.5). The server was discontinued and so I play in Single Player now.
> After moving to Single Player however, the game crashes within seconds of loading unless I switch to 32 or 64 render distance (96 too after prolonged time).
> I've tried running with and without mods and in both 1.14.5 and 1.14.7 as well as tried to see if it was a specific block(s), but that was negative.
> My best theory is that the program gets overloaded with information, but I can't read code, only know basics of digital electronics.
> #### How to reproduce
> - Download a multiplayer 1.14.5 world
> - Open it in singleplayer with a high render distance
> - Fly/stand around until it decides to crash

#814 @gymteach
> Game crashes on start. Often crashes randomly. Actually shuts down my computer when it crashes.
> 
> Correction, it allowed me to create a new world. Now the crashes shut down the game, but not the computer. I guess that is progress. I appreciate any ideas. I will have my system checked out. Its a good idea. Thank you.

#868 @embienbi
> I have played the game in single player with no problems, in multiplayer on other servers without issue, but on one server the game crashes as soon as I log in. The server owner has tried deleting my character from the server in case the issue was with my inventory, but the error continues.

----

Looking at #868, this issue can happen with any of the SQL database files, including the client-side files handling world map data.

**Comment by copygirl** [comment]
Closing in favor of #1163.
