### ISSUE TITLE
Shooting a  bow crashes the game

### ISSUE THREAD

**Issue by Criperum** [anegostudios/VintageStory-Issues#633]
**Game Version:** 1.14.0-pre3
**Platform:** Windows 10
**Modded:** No

### Description
In creative sooting a bow crashed the game

### How to reproduce
1. Go to creative.
2. Spawn a bow and arrows 
3. Aim and pool
4. Release the bow

### Expected behavior
Arrow is shot

### Logs
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.0-pre.3 (Unstable)02.11.2020 14:37:20: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.Common.ClassRegistryAPI.CreateEntity(EntityProperties entityType)
   в Vintagestory.GameContent.ItemBow.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   в Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   в Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в _mO1OMh8kncBt6cjOWOIAi4uKXfh._tqCBmo91Iso0C6Z4MxE3pGk9BGm(Single )
   в _bLYKVt0OIIpbDM9s6d78wEvV4kh._T6ntkYAYy93JTmMeUW5BPEb2H9g(Single )
   в _bLYKVt0OIIpbDM9s6d78wEvV4kh._9wnG1I0dv2nE1qiCj4WtSykSuSBA(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _Af9KcMdBp4FV1bF3d63CYMzaRzM._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(_Ky6UZsVVbxXy26d1FTibdLqrMyI , String[] )
   в _slFJfYF3pqJDCES83egtGxsoWTD._hX3i5Vm8yHkCuhYPtFN3CuEBTRN(ThreadStart )

**Comment by Criperum** [comment]
Crashes only on meteoritic iron arrows and steel arrows.

**Comment by tyronx** [comment]
thanks for the report, this has been fixed in pre.4 i believe
