### ISSUE TITLE
Infinite Ladder

### ISSUE THREAD

**Issue by Telemnaar** [anegostudios/VintageStory-Issues#64]
I placed a ladder on the wall and in order to get back to the surface I clicked, with ladder in hand, on the already placed ladder in order to "stack it upwards". The moment I tried to go up the ladder I started to take damage and got pancaked.
Then I went back to retrieve my stuff and all parts except the ladder I placed first were gone.

While I stacked it up the amount of ladders in my inventory didnt decrease.

**Comment by copygirl** [comment]
I'm a bit confused by your description. Can you explain it in different worlds, perhaps attach a picture - if that would help me?

**Comment by Telemnaar** [comment]
Hopefully the rewrote description is more easily understandable.

**Comment by copygirl** [comment]
> The moment I tried to go up the ladder I started to take damage and got pancaked.

Fall damage? In #30, Tyron said he added another chat tab that specifies what kind of damage you're taking. I believe right now you can easily glitch into blocks going up a ladder if not careful, as well.

> Then I went back to retrieve my stuff and all parts except the ladder I placed first were gone.
> While I stacked it up the amount of ladders in my inventory didnt decrease.

That might be a glitch where the chunk got reset on the client and thinks the ladder isn't there anymore, but on the server side it is. What happens if you try to place a block in a ladder space?

**Comment by Telemnaar** [comment]
![2018-04-03_07-33-05](https://user-images.githubusercontent.com/38019053/38231083-492214c6-3711-11e8-8863-4b28ea90d4d1.png)

**Comment by Telemnaar** [comment]
It is gravity damage as you can see and for the ladder you can see one the screenshot I only used 1 out of 4 ladders I still had in my inventory. I tried to place blocks, they didnt get placed so it seems it registers it as a normal block and I can climb them like normal.

**Comment by sirStroam** [comment]
related. Extending ladders up and down using the new mechanic makes fake ladders that disappear when you relog.

**Comment by copygirl** [comment]
Closing this issue in favor of #66. You were first, @Telemnaar, but there's a bit more information in the other issue by now. Thanks for reporting! :heart:
