### ISSUE TITLE
(1.1.4.0-pre.6) Grid crafting not working

### ISSUE THREAD

**Issue by PaulMisto** [anegostudios/VintageStory-Issues#641]
**Game Version:** 1.14.0-pre.6
**Platform:** Windows 10
**Modded:** No

### Description
I've had a world in the experimental versions(1.14) and updated to 1.14.0-pre.6 from 1.1.4.0-pre.5 and all the grid crafting recipes don't work. In the last version the grid crafting was working just fine, but now it doesn't in my survival world. I've tried to craft something in a creative flat world(switching gamemodes) and there it worked, in the same version.

I've tried to find out what happened, but i could not, so sorry if it's a dumb report.

**Comment by copygirl** [comment]
Could you attach your `server-main.txt` log file?

**Comment by PaulMisto** [comment]
Sure, I hope this is the right one!

[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/5517097/server-main.txt)

**Comment by copygirl** [comment]
Yeah it looks like there are no errors:

> 10.11.2020 13:31:55 [Notification] Found 234 external assets in category recipes
> 10.11.2020 13:32:00 [Event] 266 crafting recipes loaded from 143 files

So the devs will have to take a look at this.

**Comment by tyronx** [comment]
my bad, already fixed in pre7, thanks for the report
