### ISSUE TITLE
NotSupportedException: [...] OpenGL version 330 is required

### ISSUE THREAD

**Issue by j3ffreyw0ods** [anegostudios/VintageStory-Issues#643]
I'm from Russia and my English is bad))
![image](https://user-images.githubusercontent.com/74385505/99014559-90693e00-255b-11eb-838e-5077abf79e55.png)
I downloaded everything that was in the folder "redist" 
![image](https://user-images.githubusercontent.com/74385505/99014666-ca3a4480-255b-11eb-8f7e-dcf589ff2d21.png)
![image](https://user-images.githubusercontent.com/74385505/99014707-e807a980-255b-11eb-99c0-26fdc35fa09a.png)

does not start and opens the program:
![image](https://user-images.githubusercontent.com/74385505/99014559-90693e00-255b-11eb-838e-5077abf79e55.png)

![image](https://user-images.githubusercontent.com/74385505/99014785-19807500-255c-11eb-95ba-76e811c61ed5.png)

here's what it says:
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.13.4 (Стабильно) artEA#800113.11.2020 2:50:46: Critical error occurred
System.NotSupportedException: Your graphics card supports only OpenGL version 140 (1.40 - Intel Build 9.17.10.4229), but OpenGL version 330 is required.
Please check if you have installed the latest version of your graphics card driver. If they are, your graphics card may be to old to play Vintage Story.(Note: In case of modded gameplay with modded shaders, the mod author may be able to lower the OpenGL version requirements)
   в Vintagestory.Client.NoObf.Shader.EnsureVersionSupported(String versionUsed, String ownFilename)
   в Vintagestory.Client.NoObf.Shader.EnsureVersionSupported()
   в Vintagestory.Client.NoObf.ShaderProgram.Compile()
   в Vintagestory.Client.NoObf.ShaderRegistry.loadRegisteredShaderPrograms()
   в _LSAAgZhw31Rqs2is6nnojfZBbQC._BL0PigheDieo6G01vpqOQ8xL3Od()
   в _2CEJrix6eZjnKir3XZC1241baqf._toICAyZ9EYSaLsmD4KTuQWUbqjP(Single )
   в _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   в _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   в _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
Your (integrated?) graphics card or driver does not support the OpenGL version that Vintage Story uses. You may be able to fix this by installing a recent graphics driver. Do you have a dedicated graphics card?

**Comment by j3ffreyw0ods** [comment]
> Your (integrated?) graphics card or driver does not support the OpenGL version that Vintage Story uses. You may be able to fix this by installing a recent graphics driver. Do you have a dedicated GPU?

graphics card? yes. well, i'll try it. :)

**Comment by copygirl** [comment]
This is not an issue with the game or something that can be resolved on our end, so I will close this issue for now. However, it might make sense to provide a prettier error message with some tips on what you could do in this case, so I will poke the developers about that.
