### ISSUE TITLE
(1.14.0-pre.8) Longblade not swinging

### ISSUE THREAD

**Issue by PaulMisto** [anegostudios/VintageStory-Issues#645]
**Game Version:** 1.14.0-pre.8
**Platform:** Windows 10
**Modded:** No

### Description
A small visual bug. When u swing a longblade, the animation is bugged. If u have smth in ur offhand, it swings the offhand, and if u don't, no hands swing.

### Screenshots
It's more of an animation bug, so I don't rly think a screenshot would help

**Comment by PaulMisto** [comment]
I forgot to add, this is observable in 3rd person(maybe in multiplayer too?).

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in rc.6
