### ISSUE TITLE
Lower bake temperature for clay shingles?

### ISSUE THREAD

**Issue by PaulMisto** [anegostudios/VintageStory-Issues#646]
I feel like 850°C for shingles is a a bit too much given the fact that other then the bricks, all the clay molds and pottery and such have 600-650°C bake point. I think either by reducing the temp to 600-650 or tweaking the thing where after 1 shingle bakes, the other one starts back at 0 would fix this problem and make shingle blocks more accessible..

**Comment by Craluminum2413** [comment]
When will the clay shingle piles be added and can be baked in a pit kiln, this issue can be closed

**Comment by Craluminum2413** [comment]
Close issue

1.15.0-pre.4
> Feature: Shingles are now ground storable
