### ISSUE TITLE
Greenhouse plant animation

### ISSUE THREAD

**Issue by TimP69** [anegostudios/VintageStory-Issues#654]
The plants in greenhouses currently blow in the wind (animate) just as plants out in the open do.  Having plants (often) wildly flailing about does not make sense since the structures are fully enclosed and thus sheltered from the wind.

Perhaps an easy way to address this would be to suppress animation of any plant on a block currently receiving the +5°C greenhouse buff?

This issue also affects potted plants, but since planters can be placed in arbitrary locations, checking for a greenhouse buff is not a reliable approach for planters.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by dajtxx** [comment]
The forum says to enter bugs here. I was about to enter this bug but why not reopen this one?
