### ISSUE TITLE
[rc.4] Metals changing while smithing

### ISSUE THREAD

**Issue by SariaAkineko** [anegostudios/VintageStory-Issues#667]
1.14-rc.4on official public test server & RabbitTech server

Happened in three different instances:
1) On TOPTS, when placing a heated iron ingot on an anvil, the iron ingot changed to a black bronze longsword work item, without any selection window. Tried two times more, later after relogging, and nothing of the sort happened.
2) On TOPTS, two times in a row, iron blooms worked by a helve hammer fell of when finished as gold hammer heads instead - further blooms were turned into iron ingots without an issue.
3) On RabbitTech, a tin bronze and a gold work item turned into iron ingots (unfortunately I have no more information about how it happened exactly)

Seems to be random, not reproducible.

**Comment by tyronx** [comment]
Thanks for the report. Is this issue still happening?

**Comment by SariaAkineko** [comment]
I've not seen it happening myself any more (but haven't tried much smithing since, tbh) and have not heard any further reports from others

**Comment by tyronx** [comment]
Ok. It is possible that merely a version discrepancy between server and client caused this

**Comment by copygirl** [comment]
Will close this issue then until someone runs into this issue again.
