### ISSUE TITLE
Incompatible state of the stream of the basic compression procedure.

### ISSUE THREAD

**Issue by prinz441** [anegostudios/VintageStory-Issues#669]
**Game Version:** 1.13.4
**Platform:** Windows / Mac / Linux (which?) Windows
**Modded:** No / Yes (which?) No

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?
When you start the world crashes an error that does not allow you to play

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![unknown](https://user-images.githubusercontent.com/55759709/100514905-79e0fa80-3189-11eb-9247-7b76e441dbab.png)

### Logs
```
Running on 64 bit Windows with 8 GB RAM
Version: v1.13.4 (Stable)28.11.2020 14:44:46: Critical error occurred
System.IO.Compression.ZLibException: Incompatible state of the stream of the basic compression procedure.
in System. IO.Compression.DeflaterZLib.Deflate(FlushCode flushCode)
in System. IO.Compression.DeflaterZLib.ReadDeflateOutput(Byte[] outputBuffer, FlushCode flushCode, Int32& bytesRead)
in System. IO.Compression.DeflaterZLib.System.IO.Compression.IDeflater.GetDeflateOutput(Byte[] outputBuffer)
in System. IO.Compression.DeflateStream.WriteDeflaterOutput(Boolean isAsync)
in System. IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
in Vintagestory. Common.CompressionDeflate.Compress(Byte[] data)
in Vintagestory. Common.WorldChunk.Pack(Boolean commit)
in Vintagestory. Server. ServerSystemSupplyChunks.<>c__DisplayClass17_0.<loadOrGenerateChunkColumn>b__0 ()
in Vintagestory. Server. ServerMain.ProcessMainThreadTasks ()
in Vintagestory. Server. ServerMain.ProcessMain ()
in Vintagestory. Server. ServerMain.Stop(String reason)
in _lYLQLGyldvbDG9rPQyiRVeIqQVp. _jhlACAxVTWwWpkUsVk64nWsVWoN()
in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
in System.Threading.ThreadHelper.ThreadStart()
-------------------------------
```

**Comment by copygirl** [comment]
Before you try the following, could you attach the `server-main.txt` log file?

Once you're done that, can you see if the error goes away if you start the world in repair mode? To do that, go to the world selection screen, click the edit button next to the world and look for a button that says "Run in Repair mode". This is an error I haven't seen before in connection with world corruption though so I'm not sure if it will help.

**Comment by tyronx** [comment]
This is likely a broken windows / .net installation. Please reinstall your system.

**Comment by copygirl** [comment]
I will go ahead and close this, then? Can reopen again if more information is available.
