### ISSUE TITLE
Repaired translocator teleported without generating the ruin and translocator on the other side

### ISSUE THREAD

**Issue by pest666** [anegostudios/VintageStory-Issues#676]
I'm running 1.14rc7.  I ended up in solid rock facing a cave.  I was able to get out by breaking two blocks and moving into the empty space created.  It doesn't seem like I was sent to the wrong coordinates. It seems like the game failed to generate the necessary structure at the far end, as the location I teleported to fits the usual description of a place you'd find a small ruin with a translocator inside it.

**Comment by tyronx** [comment]
In rc.8 i made a fix related to translocators finding the exit point. Please report again if this happens after that version

**Comment by copygirl** [comment]
Then I shall close this issue until it turns out it wasn't fixed.

**Comment by pest666** [comment]
I just upgraded to 1.14.2, logged into the same world, and TPed back to my base.  When I tried the translocator again, it send me back to the exact same location as the first time.  There was still no translocator or ruin on the other end.  I know the location of another translocator, but I need one more temporal gear before I can fix it.  I'll report my findings when I do.

**Comment by copygirl** [comment]
I assume that previously broken translocators wouldn't be fixed by this issue, unfortunately. Future ones you repair should work however. Thanks for keeping us updated!

**Comment by pest666** [comment]
Oh wow, you're quick!  Thanks, I will.  I'll just cheat and set up teleporters between these two locations.
