### ISSUE TITLE
No mushroom tops after updating to 1.14.0

### ISSUE THREAD

**Issue by trezker** [anegostudios/VintageStory-Issues#679]
**Game Version:** 1.14.0
**Platform:** Linux (Ubuntu 16.04 LTS)
**Modded:** No

### Description
All mushrooms I find are already harvested.

### How to reproduce
1. Make a new world
2. Find mushrooms
3. The mushrooms have no tops

### Expected behavior
Mushrooms should have tops upon first discovery.

**Comment by trezker** [comment]
Finally found mushrooms with caps after ~11 hours played. Maybe grew tops after game start, but they were in an area I hadn't visited before.

**Comment by whitebyte** [comment]
Happened to me as well

**Comment by TaskaRaine** [comment]
This seems to be intended.

The 1.14.0 change log states: 'All mushrooms now spawn in a harvested state'

**Comment by copygirl** [comment]
That is a bit strange, though. What's the reasoning behind this? There is no mechanic in the game where a non-player can cause a mushroom to be harvested. It only means that there is no additional food source the _first_ time you explore a region.

**Comment by trezker** [comment]
Yeah that strikes me as very odd. If you apply the same design to all resources you wouldn't have any veggie food sources for several days and be reduced to exclusively hunting baby animals with your flint knife.

**Comment by Harlekin13** [comment]
I mean they could generate randomly harvested or not harvested, which would imply that animals maybe ate from them. same as berry bushes or wild crops generate in different stages. Finding them randomly harvested with knowing no animal eats mushrooms could even imply there being others around who try to avoid seraphs and once seeing one in an area retreat from it.

**Comment by Craluminum2413** [comment]
I think it was done for game balance

**Comment by Craluminum2413** [comment]
I think it is not relevant in 1.16 anymore, isn't it?
