### ISSUE TITLE
Slate stones should be marked as "unusable for knapping"

### ISSUE THREAD

**Issue by whitebyte** [anegostudios/VintageStory-Issues#681]
**Game Version:** 1.14.0
**Platform:** Linux
**Modded:** No

### Description
They are de-facto unusable for knapping, but it's not reflected in their description

**Comment by whitebyte** [comment]
Same for conglomerate stones

**Comment by Craluminum2413** [comment]
Addition: Chert is now knappable from 1.15 version, but it doesn't even display in the description that it can be used for

**Comment by tyronx** [comment]
fixed this for pre.11, thank you.
