### ISSUE TITLE
Item icons will overflow the UI container in the handbook if it is crafted from/used to craft too many things.

### ISSUE THREAD

**Issue by TaskaRaine** [anegostudios/VintageStory-Issues#684]
**Game Version:** 1.14.0 & 1.14.2
**Platform:** Windows
**Modded:** Yes

### Description
When looking up a specific item, the icons for items crafted from/used to craft that specific item will overflow the UI container vertically instead of being hidden. Text and the large icon for the item searched hide properly, just not all the clickable smaller icons. Everything hid properly in VS 1.13.4.

### How to reproduce
1. Make an item that is used to craft an excessive amount of things(sorry, I don't know of any items in vanilla Vintage Story that will demonstrate this).
2. Look up the item using the handbook.
3. Item icons will overflow the container vertically.

### Expected behavior
Item icons should hide and only be visible when scrolled onto the UI container.

### Screenshots
![HandbookOverflow_1](https://user-images.githubusercontent.com/53409481/101846152-5a00ed80-3b1e-11eb-85f0-a12eafd1cfcc.png)
![HandbookOverflow_2](https://user-images.githubusercontent.com/53409481/101846161-5ff6ce80-3b1e-11eb-9f55-91d99e3bc978.png)

### Logs
No relevant logs.

**Comment by DArkHekRoMaNT** [comment]
Use attributes/handbook/groupBy: ["*"], ["* -free"], [* -down-free], etc. for group your items/blocks in the handbook.

**Comment by Craluminum2413** [comment]
Fixed in [1.15.6-rc.3](https://www.vintagestory.at/blog.html/news/homesteading-balance-and-stability-patch-3-v1156-r295/?tab=comments#:~:text=Updates%20since%20rc.3-,Fixed%3A%20Handboook%20page%20stack%20overflow%20on%20modded%20items,-Fixed%3A%20Missing%20%22with)
