### ISSUE TITLE
Milk Can't Be Taken With Bowl

### ISSUE THREAD

**Issue by Airova** [anegostudios/VintageStory-Issues#688]
**Game Version:** 1.14.0
**Platform:** Windows 8.1
**Modded:** Yes (Carry Capacity)

### Description
The wiki says we should be able to take milk from a bucket with a bowl and drink it to get dairy saturation without having to make cheese, but it doesn't work. Instead of taking the milk, it shows a looping "taking" animation and the bowl remains empty. Same happens if I try to take it from a barrel.

**Comment by copygirl** [comment]
Confirmed that this is a bug.

**Comment by tyronx** [comment]
ok, this is now implemented for next version. Seems like i've never gotten around to actually added the milk bowl
