### ISSUE TITLE
Working iron blooms directly into items and slight (?) changes to smithing mechanics

### ISSUE THREAD

**Issue by Harlekin13** [anegostudios/VintageStory-Issues#691]
Currently iron blooms have to be worked into ingots before you can then work the ingots into items.

I think it would be nice to be able to skip that step, that would solve issue #689 too.

And currently when you want to smith something you have to select it before, and as you get the form correct you automatically and immediately take the item from the anvil.

Other than that i think it would be nice to be able to work on any metal work item and if it matches a recipe/correct form when taking it off the anvil it will turn into that item instead of only being able to work it into the item you selected beforehand.
What i mean is you still can select an desired outcome (and for iron bloom and similar things the ingot could just be the default outcome that you can't change), but if you make a mistake instead of having to smelt it down and start anew you could still make something useful out of it. For example you wanted to make shears, but because of lagg deleted one voxel too much, you still could make a knife or chisel out of it. Or chains if you deleted 4 instead of 3 voxels to form a plate.

Sorry the templates seem to not work for me.

**Comment by Harlekin13** [comment]
labels: 'status: new, type: enhancement,'

**Comment by Harlekin13** [comment]
label:"type: enhancement"

**Comment by copygirl** [comment]
I think you are meant to work the bloom into an ingot beforehand to get rid of all that slag. It might not make much sense in the voxel crafting system the game chose to use to represent the work being put in, but the additional hammering step is supposed to represent what one might have had to done "back in the days".

**Comment by Harlekin13** [comment]
I mean you still would have to get rid of the slag, but you could hammer the iron into the right form directly after, without having to first create an ingot, i don't want to get rid of having to remove the slag.

It would make smithing more immersive as that way you could make the item preview optional and you could change your plan for smithing a work item while smithing without having to  completely smelt the item again. Which would be even more realistic too.
I'm not sure though how much more coding that would be compared to the way smithing works atm.

**Comment by Harlekin13** [comment]
would like to add the following to the idea:

ingots (which are 42 voxels) stay at 100 units of metal.
when casting you'd need 2.5 units of metal per voxel of the items recipe (rounded up at the end)
when smithing any metal voxel you hammer away gives you a unit of metal shavings worth 2 units of metal
any metal item can be turned into an amount of shavings equal to voxels of the recipe times left durabilty over max durabilty, rounded up or in case of workitems voxels left
that would mean casting and recyling you'd lose 20% of the metal; smithing and recyling in the end slightly less, because you get 2 bonus voxels when casting an ingot and in case of iron a few shavings plus when working the bloom into an ingot/workitem

That way smithing would be better than casting without actually having to touch itemstats.

**Comment by Craluminum2413** [comment]
This is a suggestion https://www.vintagestory.at/forums/forum/5-suggestions/
