### ISSUE TITLE
Minor config file issue

### ISSUE THREAD

**Issue by lOmicronl** [anegostudios/VintageStory-Issues#693]
**Game Version:** 1.14.2
**Platform:** Windows
**Modded:** No

### Description
File ...\assets\survival\recipes\grid\armor\lamellar.json:

Line 73 reads 'name: "wood lamellar pants",' but the recipe is for metal lamellar pants. The other metal recipes in the same file have the result correctly named 'metal lamellar something'.

It's very likely entirely harmless, but then again, the fix takes 30 seconds, so might as well =)

**Comment by Craluminum2413** [comment]
Already fixed, but I cannot find when it was fixed
