### ISSUE TITLE
ghost blocks and invisible blocks (issues with block textures not showing or not disappearing)

### ISSUE THREAD

**Issue by Harlekin13** [anegostudios/VintageStory-Issues#694]
**Game Version:** 1.13.4 played locally (will update once the world i play in is out of deepest winter)
**Platform:** Windows 10
**Modded:** Yes (but none, that should be able to produce the problem)
![grafik](https://user-images.githubusercontent.com/34014817/102086566-8ebfbe00-3e18-11eb-8529-9f8405fc4cb1.png)

### Description
Yesterday i came across ghost blocks while mining, meaning i mine blocks but the textures stay in place until i break a few blocks more.
On the other hand sometimes it takes quite some time when i place blocks until their textures are shown.
Not sure but the screen flickering to black and back when placing blocks might be related to this?

### How to reproduce
Am not able to reliably reproduce, may be an issue with the game running for (really) long times (could have been something around 10 hours or more, with all in all 1-2 hours of it being paused).
may be related to #528

### Screenshots
Will try to provide a screenshot when i come across it again. but i'm not sure how useful that would be.

Yay, are able to use the templates now. Github only hid the buttons behind some popup.

**Comment by copygirl** [comment]
Is this still an issue with 1.14.5?

**Comment by Harlekin13** [comment]
Maybe i didn't play long enough at a time for it to happen again. But with #528 marked as resolved and it not having occured again yet, it's quite possibly no issue anymore, if my suspicion of the issues being connected was right.

**Comment by copygirl** [comment]
Alright, thank you! Let's close the issue for now. Can always comment to reopen or open a new one.
