### ISSUE TITLE
Screenshots taken with F12 upside down

### ISSUE THREAD

**Issue by JulianGro** [anegostudios/VintageStory-Issues#697]
**Game Version:** 1.14.2 (Stable)
**Platform:** Linux Mint 19.3
**Modded:** No

### Description
Screenshots taken with F12 are upside down *and* switched left and right.

### How to reproduce
1. Make a screenshot with F12
2. Open screenshot

### Expected behavior
Screenshot should not be upside down or switched left and right.

### Screenshots
![2020-12-15_20-46-22](https://user-images.githubusercontent.com/11144627/102266099-47205b80-3f18-11eb-8c58-4359c7ed1e15.png)

### Logs
Screenshot was taken right before stopping the last instance.
[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/5698268/Logs.zip)

**Comment by Craluminum2413** [comment]
Strange

**Comment by Craluminum2413** [comment]
Does it still happen?

**Comment by JulianGro** [comment]
Doesn't happen to me anymore on Debian Testing with Mono 6.8.0.105 and Vintage Story v1.17.11
