### ISSUE TITLE
Cannot place a slab onto another slab

### ISSUE THREAD

**Issue by JulianGro** [anegostudios/VintageStory-Issues#698]
**Game Version:** 1.14.2 (Stable)
**Platform:** Linux Mint 19.3
**Modded:** No

### Description
Cannot place a slab onto another different slab if they were to share the same Block.

### How to reproduce
1. Place a slab
2. Place a slab of a different type ontop of the former slab
3. Second slab gets places with half a block gap above

### Expected behavior
The second slab should just place right on top of the first slab.

### Screenshots
![2020-12-15_20-46-22](https://user-images.githubusercontent.com/11144627/102266707-1b51a580-3f19-11eb-9565-eb969cce6972.png)

### Comment
For people that played Minecraft, this might not be weird, but it is still very limiting and not obvious for someone who has never played Vintage Story or Minecraft before.
On my screenshot you can see that it essentially ruins my plan for a roof.

**Comment by copygirl** [comment]
This might be unexpected or undesired behavior, but is simply a known limitation of the bloxel engine. Working around it requires some special-casing for slab + slab interactions. Ideally, the engine may support a way to handle multiple distinct parts in a single block in a generic way so it could be used by other combinations, such as a cooking pot or bowl on linen.

In light of this, I will convert this to a suggestion.

**Comment by tyronx** [comment]
It could auto-convert into a chiseled block 🤔

**Comment by copygirl** [comment]
Could it auto-convert them back again, too?

**Comment by Harlekin13** [comment]
I guess it's about having different materials, right?

Else a double slab block could do the trick, same material slabs put onto each other look like same material fullblock but when taken down would become 2 slabs again.

**Comment by Craluminum2413** [comment]
The difference is that there is [Double Slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs) mod for this in minecraft. I think it would be possible to take the same logic from there

**Comment by sirStroam** [comment]
This has been labeled as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
