### ISSUE TITLE
Quartz chunks now smeltable, but never cool

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#699]
**Game Version:** 1.14.2
**Platform:** Win7
**Modded:** No 

### Description
With the addition of Coke fueltype, Quartz is now able to be melted in a crucible.

This has some interesting side-effects.

### How to reproduce
1. Put Quartz chunks in a crucible
2. Heat it up with Coke
3. It melts and fills the crucible like a metal
4. Pour the glass into an ingot mold (or any other valid mold)
5. The liquid glass never hardens
6. ???

### Expected behavior
Glass blocks, I guess? I really don't know what I expected.

### Screenshots
https://cdn.discordapp.com/attachments/334233095374897152/788501685394866196/unknown.png

**Comment by copygirl** [comment]
This should be a feature. GLASS TOOLS AND WEAPONS!!

**Comment by Ragolution** [comment]
tbh glass spears would be pretty nasty against anyone without armor.

**Comment by tyronx** [comment]
thanks for the report, this is now fixed by raising glass smelting temperature

**Comment by copygirl** [comment]
NO GLASS TOOLS?! :sob:
