### ISSUE TITLE
I can't even Launch the game

### ISSUE THREAD

**Issue by hanaji7** [anegostudios/VintageStory-Issues#700]
**Game Version:** 1.14.2
**Platform:** Windows 
**Modded:** No 
### Description
Explain the issue you're running into.
 I can't even open the application. It seems to say that my graphics doesn't support it. Does this mean I can't play with my current system?

### Expected behavior
If not obvious, what did you expect to happen?
For the application to Launch
### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.2 (Stable)12/16/2020 5:27:09 PM: Critical error occurred
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos()
   at _Ine8FeGTtDXciSIfaZMHMwCLKGBA._8puLW8J44fiq3A5hthQTfB8WNxc(_SbVlAI6dJIZ4JRt0da0lu23DF14 , String[] )
   at _lErb0L2e9E9htuT2VVnAsXIZqc7A._8puLW8J44fiq3A5hthQTfB8WNxc(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment]
Do you know which graphics card you have in your system? Try updating your graphics card driver.
