### ISSUE TITLE
slab lighting inconsistancy

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#701]
**Game Version:** 1.14.2
**Platform:** Win7
**Modded:** No

### Description
Lighting on slabs inconsistant with smooth shadows of other blocks, refer to example

### How to reproduce
1. place slab block
2. light it up a little but not too much
3. it looks bad and blocky

### Screenshots
![image](https://user-images.githubusercontent.com/1075592/102555695-44974080-4095-11eb-9259-694adcce7577.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.14.3 and hopefully didn't break anything else ^_^;
