### ISSUE TITLE
Crashes when creating a world

### ISSUE THREAD

**Issue by AtamashiHero** [anegostudios/VintageStory-Issues#704]
**Game Version:** 1.14.2
**Platform:** Windows
**Modded:** No 

Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.2 (Stable)20.12.2020 20:33:40: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.Server.ServerMain.Stop(String reason)
   в _Ine8FeGTtDXciSIfaZMHMwCLKGBA._7qFtOrLrruN94uuyGVDb8Un9J6o()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()

```

**Comment by copygirl** [comment]
Is there any mention of another error in the server-main.txt or client-main.txt when this error occurs? If this occurs again, can you upload those files for us?

**Comment by AtamashiHero** [comment]
> Есть ли какое-нибудь упоминание о другой ошибке в server-main.txt или client-main.txt когда возникает эта ошибка? Если это повторится, можете ли вы загрузить эти файлы для нас?

There seemed to be no more mentions. It crashes constantly, moreover, I can enter the servers, but I can't create a single one, it crashes

**Comment by AtamashiHero** [comment]
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/5721143/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/5721144/server-main.txt)

**Comment by copygirl** [comment]
I deleted your comment because it appeared to contain an IP which you might have not meant to share. I however found this error in the `client-main.txt` log file. The `x.x.x.x` string here was said IP address.

```
20.12.2020 20:50:40 [Fatal] Newtonsoft.Json.JsonReaderException: Input string 'x.x.x.x' is not a valid number. Path 'Ip', line 38, position 20.
   в Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   в Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   в Newtonsoft.Json.JsonTextReader.ReadAsString()
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в Vintagestory.Server.ServerSystemLoadConfig.LoadConfig(ServerMain server)
   в Vintagestory.Server.ServerSystemLoadConfig.OnBeginConfiguration()
   в Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   в Vintagestory.Server.ServerMain.Launch()
   в _Ine8FeGTtDXciSIfaZMHMwCLKGBA._7qFtOrLrruN94uuyGVDb8Un9J6o()
 ```

Have you edited the `serverconfig.json` yourself at any point?
Either way, you might want to edit it and change one line. That should fix it.
```
  "Ip": null,
```

However, this appears to be an issue and should be looked into.

**Comment by AtamashiHero** [comment]
I bought this game today and haven't climbed in the game codes.

**Comment by copygirl** [comment]
Can you find the `serverconfig.json`? Deleting it should allow it to be recreated and the error should go away.

**Comment by AtamashiHero** [comment]
Already found, now I will delete

**Comment by AtamashiHero** [comment]
thanks, its working

**Comment by tyronx** [comment]
thanks, the game will now log a useful error instead of crashing when the serverconfig.json is invalid
