### ISSUE TITLE
Long keybinds not visible in Macro Manager

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#71]
When a keybind is e.g. Ctrl+Shift+Number5, I don't see which number it is in the Macro manager:
![2018-04-09_08-33-16](https://user-images.githubusercontent.com/25122345/38481996-20ac8354-3bd6-11e8-84cc-4e345ff917fe.png)

**Comment by tyronx** [comment]
This could be abbreviated to `5` anyway, that should fix it sufficiently, done for 1.5.3.
