### ISSUE TITLE
Oil lamp issue

### ISSUE THREAD

**Issue by whitebyte** [anegostudios/VintageStory-Issues#712]
**Game Version:** 1.14.3-rc1
**Platform:** Linux
**Modded:** No

### Description
Placing an oil lamp somehow decreases a light level. Please see the attached screenshots

![2020-12-25_19-04-29](https://user-images.githubusercontent.com/7704186/103139561-36c16b00-46e6-11eb-873b-af6495b4f804.png)
![2020-12-25_19-04-28](https://user-images.githubusercontent.com/7704186/103139564-3a54f200-46e6-11eb-9e7b-b6a1e2f55f8d.png)

Note the second screenshot (without the lamp) is better lit that the first one (with the lamp)

**Comment by whitebyte** [comment]
A correction: the actual issue is that a placed oil lamp produces less light than one simply thrown on the ground

**Comment by whitebyte** [comment]
...ok it makes less and less sense

![Screenshot_20201225_193540](https://user-images.githubusercontent.com/7704186/103139795-90c33000-46e8-11eb-8df9-f3f83c0cbe04.png)

Turns out it's some general light glitch. Take a look at the black shadow. It's clearly not supposed to be here, because the room is well lit

**Comment by tyronx** [comment]
wow strange, can you send me the save game?

**Comment by whitebyte** [comment]
@tyronx unfortunately I don't have it anymore. Feel free to close as "not reporoduceable"

**Comment by copygirl** [comment]
Actually, one of the recent releases had some fix related to a lighting bug in 2-high spaces, so maybe I'll close as "assumed fixed unless proven otherwise". Haha.
