### ISSUE TITLE
Game save file in use.

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#714]
**Game Version:** 1.14.2
**Platform:** Windows
**Modded:** No

### Description
Sometimes when I'm trying to load a world I'm getting a message: _"Have no write access to this file, it seems in use. Make sure no other client or server is currently using this savegame"_. I have no other Vintage Story related apps open. Restarting Vintage Story doesn't help with anything, I have to restart my PC.

### How to reproduce
It happens rarely
1. Log into a world
2. Exit the world
3. Try logging into the world again

### Screenshots
![obraz](https://user-images.githubusercontent.com/38937849/103169518-a34e7e00-483c-11eb-95c2-1226d955f4fd.png)

### Logs
I'm not sure whether there is a log file generated when I try to log in.

**Comment by tkkot** [comment]
Interesting, I tried moving the file in file explorer and got a message saying it's in use by Lenovo.Modern.ImController.PluginHost.Device.exe Does someone know what that means?

**Comment by tkkot** [comment]
Ok, I closed that program in the task manager and everything works

**Comment by tkkot** [comment]
But I still want to know why it happens and what it means

**Comment by copygirl** [comment]
I will have to close this issue because it's not related to the game. I also don't know what to recommend. You can search online for the file name and see some of the recommendations on Lenovo's forums or similar.
