### ISSUE TITLE
Plan doesn't rotate with voxels when smithing

### ISSUE THREAD

**Issue by maclaird1** [anegostudios/VintageStory-Issues#715]
**Game Version:** 1.14.2
**Platform:** Windows 
**Modded:** No 

### Description
When creating a tool on the anvil when you rotate the piece it shifts where the metal needs to go. So if you build out one side andd rotate the unit it does not rotate the plan with the existing metal. This causes you to put metal where it is not needed and then because it is at the edge you cannot move it over again. I would also like to see a way to push edge metal back into the unit so you can move it somewhere else and not have to waste a second ingot.

### How to reproduce
1. Make a '....'scythe head rotate it part way through the build and note that the parts you have worked on are now show as off the plan.
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen? I had hoped it would rotate the plan with the metal so you can see the other side

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![scythe](https://user-images.githubusercontent.com/76656506/103174425-a3904e80-4827-11eb-88e2-050ff2c8706b.JPG)
![scythe](https://user-images.githubusercontent.com/76656506/103174432-af7c1080-4827-11eb-9206-0897496624e5.JPG)

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
This hasn't happened for me in a long time, definitely not in 1.14. Does this happen every single time you attempt to rotate a work piece? Does it happen in 1.14.5 still?

**Comment by Craluminum2413** [comment]
> https://www.vintagestory.at/forums/topic/3749-wintery-stability-patch-v1146-1147
> Fixed: Lag spikes when Smithing on a rotated work item
