### ISSUE TITLE
Mouse Cursor is invisible, and tab/enter don't work to press buttons or setup a character.

### ISSUE THREAD

**Issue by Astrobirder** [anegostudios/VintageStory-Issues#716]
**Game Version:** 1.14.2
**Platform:** Windows 10
**Modded:** Yes

### Description
In fullscreen mode, the cursor is invisible on my i7-2700k, with AMD HD 6970 Graphics card, with latest drivers.
In windowed mode, the cursor is VISIBLE and the game works fine. (thanks for the suggestion Tyron!).

### How to reproduce
1. Open game in fullscreen mode on my system.

### Screenshots
I attempted to record an mp4 with OBS, and something REALLY strange occurs!  I can SEE the cursor from the OBS preview, and it's INSIDE the recording, but it's NOT on the screen, in fullscreen mode.

### Logs
```
It doesn't crash--it's just not usable when you can't see the cursor!

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Couldn't find the logs or either of these txt files.
```

**Comment by copygirl** [comment]
Which game version?

**Comment by copygirl** [comment]
Perhaps there is something odd with the game changing the default cursor in your case.

(I was about to close the issue due to lack of response, but I just noticed you had edited your issue. Please comment when you update so we get notified of such a change.)

**Comment by Ringater** [comment]
I am having the same problem here.

**Game Version:** v1.20.12 (Stable)
**Platform:** Windows 11
**Modded:** No
**Specs:**
Processor	12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	663BBD04-7581-4B26-A63A-B3AABDF1FC0F
Product ID	00342-20876-78216-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	23H2
Installed on	‎3/‎4/‎2023
OS build	22631.5335
Experience	Windows Feature Experience Pack 1000.22700.1081.0

GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU (4 GB RAM)

**Description**

With the Window Mode setting set to Fullscreen or Fullscreen + Always on top, my mouse cursor is not visible ingame. Changing this to either Windowed or Maximized Borderless allows the mouse cursor to become visible.

**How to reproduce**

1. Set Window Mode to Fullscreen or Fullscreen + Always on top
