### ISSUE TITLE
API requests

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#72]
- [x] `OnBlockInteractStart` - to interact with blocks the same as items
- [x] `OnBlockInteractStep` - to interact with blocks the same as items
- [x] `OnBlockInteractStop` - to interact with blocks the same as items
and an ability to call animations made in the model creator.
- [ ] `OnEntityRecieveDamageEvent` - armor, effects like minecraft thorns or feather falling, to trigger item abilities, etc
- [x] `OnEnityWorldSpawnEvent` - have greater control over what spawns where.

**Comment by copygirl** [comment]
> and ability to call animations made in the model creator.

Looked around and found `Entity.StartAnimation`. Isn't that what you want?

**Comment by sirStroam** [comment]
That's one piece of the puzzle, maybe.

**Comment by tyronx** [comment]
All implemented except OnEntityRecieveDamageEvent

**Comment by sirStroam** [comment]
All features added. Closing
