### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lokia12** [anegostudios/VintageStory-Issues#721]
**Game Version:** X.Y.Z
**Platform:** Windows 10 pro
**Modded:**  Yes (which?) VSCreativeMod.dil,VSEssentials.dil,VSSurvivalMod.dil

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here. { TimeGenerated = 28.12.2020 00:20:55, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.IO.FileNotFoundException
   в _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])

 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by tyronx** [comment]
This is an incomplete crash report. Please describe in greater detail whats going on.

**Comment by copygirl** [comment]
Closing because lack of response.
