### ISSUE TITLE
Weird item conversion on helve hammer

### ISSUE THREAD

**Issue by tkkot** [anegostudios/VintageStory-Issues#722]
**Game Version:** 1.14.2
**Platform:** Windows
**Modded:** No

### Description
An iron bloom worked on a helve hammer converted into a golden hammer head. I was "helping" the hammer with getting rid of the slag.

### How to reproduce
1. Heat an iron bloom
2. Place it under a working helve hammer
3. Start removing the slag with a hammer manually
4. Let the helve hammer finish
5. The golden hammer head popped off

**Comment by tkkot** [comment]
Found a similar bug report that got closed. I will just add, I was playing on a singleplayer world.

**Comment by copygirl** [comment]
The other issue is likely #667.

**Comment by tyronx** [comment]
Huh. This is rather perplexing.

**Comment by tkkot** [comment]
It only happened once. After that all blooms turned into Iron ingots. I  didn't try to reproduce the bug afterwards. I have absolutely no idea why it didn't work that one time.

**Comment by copygirl** [comment]
Someone left behind an unfinished chisel on the Aura Fury server. I figured I'd finish it, but it turned into an anvil piece when I tried. It might have been left in a chest for a couple of updates.

**Comment by tkkot** [comment]
My iron bloom was propably somewhere from 1.13. But I hadn't worked on it before. And when I placed it on the anvil it was still a bloom. It converted when it was finished.

**Comment by tyronx** [comment]
Oh yea, Saraty also reported one case of an iron bloom turning into a iron anvil base on AuraFury.

**Comment by tyronx** [comment]
Ooooooh, I bet any unfinished work item from v1.13 that gets finished in v1.14 will exhibit thus bug. 
Ok, I know why it happens now 🤦

**Comment by copygirl** [comment]
@tyronx I believe the unfinished chisel that turned into an anvil piece was from a different 1.14 version, not all the way back to 1.13. It would be good to check if smaller updates or simply server restarts do this.

**Comment by DArkHekRoMaNT** [comment]
Since this bug hasn't reappeared in the past two years, I'll close this as stale. It has probably been fixed.
