### ISSUE TITLE
1.14.3 Client untextured Stone Path

### ISSUE THREAD

**Issue by ErebusAres** [anegostudios/VintageStory-Issues#726]
**Game Version:** 1.14.3
**Platform:** Windows
**Modded:** No

### Description
when i logged in the Stone Path texture is White block Red "?" Texture [ ? ]

### How to reproduce
Log in to server (haven't checked SP)

### Expected behavior
expected "real" texture

### Screenshots
https://cdn.discordapp.com/attachments/105510287959928832/795691325286645810/unknown.png

### Logs
no crash

**Comment by copygirl** [comment]
You should see whether this is also an issue on the client.
The server might require remapping blocks from 1.14.2 to 1.14.3.

**Comment by ErebusAres** [comment]
ok yeah, it looked fine in my SP play area.
how do we remap blocks on the server?
thanks.

**Comment by ErebusAres** [comment]
found it on the wiki, it was the server remapping.
