### ISSUE TITLE
Crash with 1.14.4 update

### ISSUE THREAD

**Issue by bobmek** [anegostudios/VintageStory-Issues#727]
Hey, with the new 1.14.4 update, I keep getting random crashes. The game was stable with all other versions, but this one seems to crash like this fairly consistently every 5 minutes or so.

![image](https://user-images.githubusercontent.com/20116734/103663524-2fe4f480-4f3f-11eb-9248-5765933fb3dd.png)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/5770981/client-main.txt)

**Comment by copygirl** [comment]
Can you test 1.14.5 to see if this is resolved?

> Also released v1.14.5 to fix a crash bug in the lighting engine!

**Comment by bobmek** [comment]
Yeah! Played for 5 minutes and no crashing. I think you got it! Thanks SO MUCH! 

Of course as the game loaded back up, I forgot I was running away from a wolf.  :-|

**Comment by copygirl** [comment]
That's unfortunate. :laughing: Glad it works!
