### ISSUE TITLE
game crash after starting the world

### ISSUE THREAD

**Issue by xXdsdXx** [anegostudios/VintageStory-Issues#729]
Game Version: 1.14.2
Platform:Windows 
Modded:Yes 

### Description
I enter the game and after 10 seconds crash
I enter the game and after 10 seconds crash
Вхожу в игру и через 10 сек вылетает
go into the game and after 10 seconds of flight
заходим в игру и через 10 секунд полета

### How to reproduce
Make a 'I died and then I was reborn. I went to get my resources and the game froze. Then I go into the world and see that all my things and duplicates of things are not far away. and 10 seconds after loading crash'

### Expected behavior
that I will return for my things, take them and continue to play

### Logs

Running on 64 bit Windows with 8 GB RAM 
Version: Ознокомительная версия artEA#8001 v1.14.2 (VoronWood)06.01.2021 21:46:11: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   в Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_yYcLwwVgddc6OWOmqOfREe6xnKd serverpacket)
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   в _uWwiuXC8cGTH1JnsWiUY9FUaXOo._0WtXQJqGAidcdKMfPHF0OxDIauE(Single )
   в _ydpin5JFjepNgd3JOZRb2z5I5Fg._LvRZFcsDWyPwKLB1F2UK7fQ2N6d(Single )
   в _ydpin5JFjepNgd3JOZRb2z5I5Fg._GO2qaUrk9dl0IceTLiA7P4LcpAB(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _Ine8FeGTtDXciSIfaZMHMwCLKGBA._8puLW8J44fiq3A5hthQTfB8WNxc(_SbVlAI6dJIZ4JRt0da0lu23DF14 , String[] )
   в _lErb0L2e9E9htuT2VVnAsXIZqc7A._8puLW8J44fiq3A5hthQTfB8WNxc(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 06.01.2021 21:46:11, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.NullReferenceException
   в Vintagestory.API.Common.EntityItem.FromBytes(System.IO.BinaryReader, Boolean)
   в Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_yYcLwwVgddc6OWOmqOfREe6xnKd)
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single)
   в _uWwiuXC8cGTH1JnsWiUY9FUaXOo._0WtXQJqGAidcdKMfPHF0OxDIauE(Single)
   в _ydpin5JFjepNgd3JOZRb2z5I5Fg._LvRZFcsDWyPwKLB1F2UK7fQ2N6d(Single)
   в _ydpin5JFjepNgd3JOZRb2z5I5Fg._GO2qaUrk9dl0IceTLiA7P4LcpAB(Single)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double, Double)
   в _Ine8FeGTtDXciSIfaZMHMwCLKGBA._8puLW8J44fiq3A5hthQTfB8WNxc(_SbVlAI6dJIZ4JRt0da0lu23DF14, System.String[])
   в _lErb0L2e9E9htuT2VVnAsXIZqc7A._8puLW8J44fiq3A5hthQTfB8WNxc(System.Threading.ThreadStart)

 }
{ TimeGenerated = 06.01.2021 16:11:50, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.IO.FileNotFoundException
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._jyInOxlJtjeDvyVArlNd6UT8Cuf(System.String[])

 }
{ TimeGenerated = 06.01.2021 16:11:44, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.IO.FileNotFoundException
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._jyInOxlJtjeDvyVArlNd6UT8Cuf(System.String[])

 }

**Comment by copygirl** [comment]
Go to the world selection screen, click the pencil icon next to your world and select "Run in Repair mode". That usually gets rid of errors like this. Good luck!

**Comment by copygirl** [comment]
Closing due to lack of response.
