### ISSUE TITLE
suggested commands

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#73]
- A command to change where relative 0,0,0 is. (This is where people assume spawn is)
- When a command needs coordinates being able to type `here` and have it grab your coordinates.
- `/save here as home` A way to make a list of coordinate locations with names so you can type `/tp home` take you to spot you've saved as home or `/tp [playername] dungeon` sends them to a place you've saved as dungeon. `/listsavedcoords` would print out a list of the names and associated relative coordinates. `/listsavedcoords -a` would list it in absolute coordinates.
- command to open other players inventory (remove banned items or restore lost items)
- command to see where players respawn point is set to. 
- command to change players respawn point. (help stop player from making death loop)

**Comment by Craluminum2413** [comment]
It would also be nice to have a command a /settemp for item in active slot that can be heated

**Comment by Craluminum2413** [comment]
Added one command from this suggestion
> Tweak: made "/role [rolename] spawnpoint" easier to use. No longer needs absolute coords can use flexible coords i.e. ~ ~ ~ or =absx =absy =absz or x y z.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
