### ISSUE TITLE
Server database backup suspends server - needs restart after every backup. / We need incremental backup too.

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#731]
**Game Version:** 1.14.2 Server
**Platform:** Linux 
**Modded:** No 

### Description
We run small server for few players. VS database file grows more and more. It's about 6 GB now. Having some backup of database is very important. However daily backup of 6 GB file is a nightmare. We use server command "/genbackup". Server is about 10 minutes totally CKU (during backup). And finally it is suspended. I should start server again every morning.
Does anybody know how to make incremental backup ?
Please Tyron, can you do something to overcome this problem? I know this is some architecture and it's complicated to change it. However daily backup of many GB with suspended server after backup is really problem.

### How to reproduce
1. Run a server with big database file (more GBs)
2. Use command "/genbackup"
3. It suspends server after backup operation

### Expected behavior
Server should run normally after backup.
Or server should be able to make incremental backups too to minimalize server/disk usage.

### Screenshots
------

### Logs
28.12.2020 03:27:25 [Notification] Server ticking has been resumed
28.12.2020 03:27:25 [Event] Offthread save of savegame done.
28.12.2020 03:27:25 [Event] Offthread save of 0 chunks done.
28.12.2020 03:27:25 [Notification] Offthread save of 0 generating chunks done.
28.12.2020 03:27:25 [Event] Offthread save of 0 map chunks done.
28.12.2020 03:57:27 [Notification] Server ticking has been suspended
28.12.2020 03:57:27 [Notification] Autosaving game world. Notifying mods, then systems of save...
28.12.2020 03:57:27 [Notification] Defragmented listener lists
28.12.2020 03:57:27 [Event] Mods and systems notified, now saving everything...
28.12.2020 03:57:27 [Event] Will do offthread savegamedata saving...
28.12.2020 03:57:27 [Event] Saved player world data...
28.12.2020 03:57:27 [Event] Saved map regions...
28.12.2020 03:57:27 [Event] Saved map chunks...
28.12.2020 03:57:27 [Event] World saved! Saved 0 chunks, 0 mapchunks, 0 mapregions.
28.12.2020 03:57:27 [Notification] Server ticking has been resumed
28.12.2020 03:57:27 [Event] Offthread save of savegame done.
28.12.2020 03:57:27 [Event] Offthread save of 0 chunks done.
28.12.2020 03:57:27 [Notification] Offthread save of 0 generating chunks done.
28.12.2020 03:57:27 [Event] Offthread save of 0 map chunks done.
28.12.2020 04:00:01 [Notification] Handling Command /genbackup 
28.12.2020 04:00:01 [Notification] Ok, generating backup, this might take a while
28.12.2020 04:08:49 [Warning] Server overloaded. A tick took 417833ms to complete.
28.12.2020 04:28:28 [Warning] Server suspend requested, but reached max wait time. Server is only partially suspended.
28.12.2020 04:28:28 [Notification] Unable to autosave, was not able to pause the server
28.12.2020 04:28:28 [Notification] Server ticking has been resumed
28.12.2020 04:28:28 [Warning] Server overloaded. A tick took 60243ms to complete.
28.12.2020 04:29:29 [Warning] Server suspend requested, but reached max wait time. Server is only partially suspended.
28.12.2020 04:29:29 [Notification] Unable to autosave, was not able to pause the server
28.12.2020 04:29:29 [Notification] Server ticking has been resumed
28.12.2020 04:29:29 [Warning] Server overloaded. A tick took 60681ms to complete.
28.12.2020 04:30:30 [Warning] Server suspend requested, but reached max wait time. Server is only partially suspended.
28.12.2020 04:30:30 [Notification] Unable to autosave, was not able to pause the server
28.12.2020 04:30:30 [Notification] Server ticking has been resumed
28.12.2020 04:30:30 [Warning] Server overloaded. A tick took 60380ms to complete.
28.12.2020 04:31:41 [Warning] Server suspend requested, but reached max wait time. Server is only partially suspended.
28.12.2020 04:31:41 [Notification] Unable to autosave, was not able to pause the server
28.12.2020 04:31:41 [Notification] Server ticking has been resumed
28.12.2020 04:31:41 [Warning] Server overloaded. A tick took 70461ms to complete.
28.12.2020 04:32:47 [Warning] Server suspend requested, but reached max wait time. Server is only partially suspended.
28.12.2020 04:32:47 [Notification] Unable to autosave, was not able to pause the server
28.12.2020 04:32:47 [Notification] Server ticking has been resumed
28.12.2020 04:32:47 [Warning] Server overloaded. A tick took 64825ms to complete.

**Comment by tyronx** [comment]
Ok, I've fixed the issue where an active backup and a autosave would cause the server to freeze, but I cannot fix the fact that you seem to have very slow disk writes. A call to /genbackup of a 3.2 GB save takes about 3 minutes for me

**Comment by petrnowak** [comment]
Thanks Tyron.

Incremental backup: ok, I understand.
