### ISSUE TITLE
over 10 crashes in an hour

### ISSUE THREAD

**Issue by feevs** [anegostudios/VintageStory-Issues#732]
**Game Version:** 1.14.4 (no issue in 1.14.2)
**Platform:** Windows
**Modded:** No / Yes (which?)
yes and no (huid clock), turned it off to see if it´s a problem

### Description

Multiple crashes in a row. Game crashes, i reload, i take one step, it crashes again.

### Logs

i don´t know what exactly you need, but i found this multiple times in the log:

8.1.2021 09:56:32 [Notification] Wow, client daytime drifted off significantly from server daytime (17,9 mins)
8.1.2021 09:58:32 [Fatal] Caught unhandled exception in thread 'relight'. Exiting game.
8.1.2021 09:58:32 [Fatal] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
```

**Comment by copygirl** [comment]
There were issues in the lighting engine in 1.14.4. Please update to 1.14.5.
