### ISSUE TITLE
Firepit processing is a little too fuel-efficient

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#733]
**Game Version:** 1.14.3
**Platform:** Windows 
**Modded:** No 

### Description
When cooking, baking or crucible smelting, processes, once started, won't lose temperature and consequently halt or reverse until the fire is almost cold. 

### How to reproduce
Just let fuel run out during any of the mentioned processes. Letting the fire cool down between adding fuel won't halt progress in any known instance - I've completed quite a bit of food and ceramics with several temperature drops in between refueling, and one particular instance of smelting copper nuggets didn't see the progress halt and reverse until the fire dropped below ~50C.

### Expected behavior
Gradual loss of temperature and progress on the item(s) once the fire cools below the needed processing temperature

**Comment by copygirl** [comment]
Will mark as a suggestion since this is currently intentional. Items generally do keep their temperature for some amount of time before they start to lose it, which gives players a little more time to, for example, cast molten metal and work metal without having reheat multiple times.

**Comment by CalligoMiles** [comment]
I see. That makes sense, but as it is right now it seems... excessively generous.

**Comment by Craluminum2413** [comment]
So you can just heat 64 (16x4) of iron ingots and process them on anvil

**Comment by copygirl** [comment]
I've also given my thoughts on improving firepit processing to the devs before. Reworking it would take a non-trivial amount of time (and if not done right could break existing firepits) so it's understandable they're focusing on more important features and issues.

**Comment by Craluminum2413** [comment]
Have you thought about making an experimental mod with a modified firepit?

**Comment by sirStroam** [comment]
This has been marked as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
