### ISSUE TITLE
Forge does not emit heat

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#734]
**Game Version:** 1.14.3
**Platform:** Windows
**Modded:** No

### Description
The forge, despite running similar temperatures as a coal-fueled firepit, apparently doesn't emit any heat whatsoever

### How to reproduce
Fire up a forge in subzero temperatures and watch yourself get frostbite anyway

### Expected behavior
To not freeze to death while working the smithy

**Comment by copygirl** [comment]
This should have been fixed in 1.14.3, so definitely something to look into.

> Tweak: Bloomeries also provide some heat, forges provide a bit more heat
> ~ [Stable Christmas Patch (v1.14.3)](https://www.vintagestory.at/blog.html/news/stable-christmas-patch-v1143-r275/)

**Comment by tyronx** [comment]
thanks for the report, will be fixed next release
