### ISSUE TITLE
Weird gravel path shovel interactions

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#735]
**Game Version:** 1.14.5
**Platform:** Win7
**Modded:** No

### Description
Gravel path blocks can't be cleared of snow, and when broken are added to your inventory as a snow-covered block.

### How to reproduce
1. Make a road
2. Let it snow
3. Dig road with shovel
4. Something weird happens

### Screenshots
![image](https://user-images.githubusercontent.com/1075592/104108092-ea525f80-528f-11eb-9bdc-8468cb8b33ad.png)

**Comment by copygirl** [comment]
Can confirm this also happens on Aura Fury. You can get rid of the snow by placing a block on top.

**Comment by tyronx** [comment]
this is also fixed in v1.14.6-rc.1
