### ISSUE TITLE
Falling snow deletes copper nuggets

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#738]
**Game Version:** 1.14.3
**Platform:** Windows 
**Modded:** No

### Description
I cut down a tree, and the snow falling down in the wake of its collapse deleted the surface copper nugget deposit next to it entirely.

### How to reproduce
Presumably, anything that causes snow to fall or slide onto surface nugget deposits aside from the weather, though it could be snow coming down from branches in particular. I'm... disinclined to test further when I'm barely into the copper age in survival.

**Comment by Craluminum2413** [comment]
Reproducible in 1.15.0-pre.2

**Comment by RedramVS** [comment]
loose stones, loose ores, and loose boulders have been changed to replaceability 6100 (from 6500 previously), which causes the snow to not replace them.  at 6200 they would be replaced.  I did not test anything between 6100 and 6200.
