### ISSUE TITLE
Bug Shift+click in craft

### ISSUE THREAD

**Issue by DesTristes** [anegostudios/VintageStory-Issues#743]
**Game Version:** 1.14.5
**Platform:** Windows
**Modded:** Yes 

### Description
Bug Shift+click in craft (sorry for my bad english)

### How to reproduce
1. Make a 'Bloomery base'
2. Use it on 'Fire bricks'
3. Doesn't do the thing.

**Comment by copygirl** [comment]
Comfirmed - this happened to me as well.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in v1.14.6-rc.1
