### ISSUE TITLE
Placing chutes is unusable, horrible and a real pain!

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#744]
**Game Version:** 1.14.2
**Platform:** Client - Windows, server is running on Linux
**Modded:** No

### Description
Placing 3-way chute is unusable. I'm not able to place chute as I want. Event when there are three chutes directed to the block where I'd like to place the 3-way chute, the chute is placed and rotated wrongly!
How can I rotate the chute, so it can be placed propertly to connect another chutes?
There is only one sentence about placing chutes in the wiki: "These blocks place directionally, with the output facing away from the player." Okay, but which output is the one described in case of the 3-way chute?
Tyron, please do something with that, it's really unusable - it seems that the chute is placed intentionally randomly to make players angry...

Thank you very much. I love VintageStory, but this is a real pain.
Filip

### Screenshots
Here is how I want to place chute
![2021-01-10_21-07-31_LI](https://user-images.githubusercontent.com/768590/104134130-1c46ed00-5388-11eb-86bb-938a2f48045b.jpg)

Here is how it's placed - wrongly
![2021-01-10_21-07-46](https://user-images.githubusercontent.com/768590/104134165-46001400-5388-11eb-91aa-bc86ac6dfed3.png)

**Comment by fipil** [comment]
An additional note, I'd like to use a 2-way chute to connect these two chutes, but I was not able to rotate the 2-way chute to connect two chutes horizontaly. So I found, that I can use the 3-way chute and it works. I placed the two another 3-way chutes properly, bud the last one I cannot place.

**Comment by Harlekin13** [comment]
You could place it against a block to place it facing the right way, but the addition of a way/tool to rotate chutes and maybe other directional blocks, would really be nice.

**Comment by fipil** [comment]
> You could place it against a block to place it facing the right way, but the addition of a way/tool to rotate chutes and maybe other directional blocks, would really be nice.

Thank you for comment, but how? Would you be so kind and describe me an exact method how can I place the 3-way chute to each of the possible rotations? I did not find the exact method.

**Comment by Harlekin13** [comment]
In the case above, place a block between wall and where the chute should be, face the block, place the chute. the direction the chute is placed is directional in two ways A) it depends on the block you place it against B) it depends on the players position in relation to the block it's placed against, there may be even a C) it tries to autoconnect to other chutes.

**Comment by Craluminum2413** [comment]
Can this be considered as a suggestion?🤔

**Comment by Craluminum2413** [comment]
Can be completely fixed by using something like that
https://user-images.githubusercontent.com/69315569/154951374-34c77e82-9a1e-4d48-9b74-7c96a1306793.mp4
```json
[
  {
    "op": "add",
    "path": "/behaviors/-",
    "value": {
      "name": "ExchangeOnInteract",
      "properties": {
        "exchangeStates": ["*-ns", "*-we", "*-ground"],
        "sound": "effect/latch",
        "actionLangCode": "blockhelp-chute-changeorientation"
      }
    },
    "file": "blocktypes/metal/chute-cross.json"
  },
  {
    "op": "add",
    "path": "/behaviors/-",
    "value": {
      "name": "ExchangeOnInteract",
      "properties": {
        "exchangeStates": ["*-ud", "*-ns", "*-we"],
        "sound": "effect/latch",
        "actionLangCode": "blockhelp-chute-changeorientation"
      }
    },
    "file": "blocktypes/metal/chute-straight.json"
  },
  {
    "op": "add",
    "path": "/behaviors/-",
    "value": {
      "name": "ExchangeOnInteract",
      "properties": {
        "exchangeStates": ["*-t-ns", "*-t-we", "*-t-ud-n", "*-t-ud-e", "*-t-ud-s", "*-t-ud-w"],
        "sound": "effect/latch",
        "actionLangCode": "blockhelp-chute-changeorientation"
      }
    },
    "file": "blocktypes/metal/chute-t.json"
  },
  {
    "op": "add",
    "path": "/behaviors/-",
    "value": {
      "name": "ExchangeOnInteract",
      "properties": {
        "exchangeStatesByType": {
          "*-elbow-*": ["*-up-north", "*-up-east", "*-up-south", "*-up-west", "*-down-north", "*-down-east", "*-down-south", "*-down-west"],
          "*-3way-*": ["*-up-north", "*-up-east", "*-up-south", "*-up-west", "*-down-north", "*-down-east", "*-down-south", "*-down-west"]
        },
        "sound": "effect/latch",
        "actionLangCode": "blockhelp-chute-changeorientation"
      }
    },
    "file": "blocktypes/metal/chute.json"
  }
]
```

**Comment by Craluminum2413** [comment]
No longer relevant since 1.17 added wrench tool for rotating such blocks
