### ISSUE TITLE
/worldconfig microblockChiseling set to 'all' but I still cannot chisel plaster

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#748]
**Game Version:** 1.14.2
**Platform:** Client: Windows, server: linux
**Modded:** Client-only mod HUD Clock 2.4.0 on the client running on windows. On server side there is no mod installed.

### Description
I set the configuration: /worldconfig microblockChiseling to all on our server.
Then I restarted server.
When I try to use chisel on the Plaster cube, it doesn't work. Also on Glass cube it doesnt work.

Putting the command "/worldconfig microblockChiseling" writes that it's set to "all".

### How to reproduce
Do steps described above.

### Expected behavior
I can chisel plaster, glass or another cubic blocks. Especially I need plaster, to create interior walls side from plaster and exterior side as cobblestone.

Thank you.
Filip

**Comment by copygirl** [comment]
Glass is not chiselable from what I know. Plaster probably should be, however.

**Comment by fipil** [comment]
Okay, glass is not a problem, what I need is the Plaster. Thanks.

**Comment by tyronx** [comment]
thanks for the report, next version plaster will be chiselable.

Glass will also be chiselable eventually, its on my todolist

**Comment by fipil** [comment]
That's great! Thank you very much.
Filip
