### ISSUE TITLE
Tapestry miniature (in trader inventory, in mouse hover detail window, ...) is mirrored.

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#750]
**Game Version:** 1.14.2
**Platform:** Linux
**Modded:** No

### Description
Tapestry miniature (in trader inventory, in mouse hover detail window, ...) is mirrored. => very confusing when buying tapestry Salvation (2x2).
When buing most of the tapestries it's not real problem because even mirrored miniature is distinguishable from other parts of the same tapestry serie. However with Salvation tapestry it is a problem because left - right parts of tapestry is mirrored picture in fact. That's why I repeatedly wrongly buy the other (left-rihtg) part of tapestry finally ending with a lot of left parts a no one right part until I figured out what is happening....

### How to reproduce
1. Find trader with Salvation tapestry (or another one to demostrate mirroring).
2. Carefully look how the tapestry looks like in trader inventory / mouse hover item detail window.
3. Buy the tapestry
4. Look how it looks in your inventory.
5. Place the tapestry on wall and look how it looks.
6. See difference ?

### Expected behavior
Tapestry itself and all its miniatures (in all inventories - player/trader/mouse hover item detail window/...) should look the same (not mirrored one in some inventories).

### Screenshots
Attached... One screenshot - tapestry in trader inventory. The second one - tapestry in player inventory / placed on wall. Its the same for all other types of tapestries. All are mirrored: trader versus player/placed on a wall.

![Salvation1](https://user-images.githubusercontent.com/8435741/104305725-5241b980-54cd-11eb-8f40-0e5055784c40.png)
![Salvation2](https://user-images.githubusercontent.com/8435741/104305729-5372e680-54cd-11eb-8f2f-586d59aed183.png)

This definitely isn't too serious problem. As soon as player figures what is happening can easily correct it.

**Comment by copygirl** [comment]
Appears to happen with many items such as translocators, see mentioned issue.

**Comment by l1ving** [comment]
This is still an issue. Related video attached.

https://user-images.githubusercontent.com/17222512/155657419-93e2a930-f221-4643-96a8-6b2ff2563c7f.mp4

**Comment by tyronx** [comment]
It just dawned on me, this can be easily fixed with negative x-scaling 🤯 
Thanks. Will be fixed next release or next major release.
