### ISSUE TITLE
Firewood is only partially converted to charcoal

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#751]
**Game Version:** 1.14.5
**Platform:** Windows
**Modded:** No 

### Description
When opening up a finished charcoal pit, several stacks of firewood had neither burned up nor converted to charcoal for no apparent reason. 

### How to reproduce
I have no idea - half a dozen previous piles in the same pit went fine.

### Screenshots
![VS charcoal pile](https://user-images.githubusercontent.com/19876578/104377101-39192700-5526-11eb-90ca-c25283234a8f.png)

**Comment by copygirl** [comment]
Is this reproducible with the same configuration? What are the dimensions of the charcoal pit and where did you put the fire pit?

A real quick guess would be that the firewood/charcoal is on a chunk border and at a crucial time when it was supposed to start burning or convert to charcoal, a chunk was unloaded?

**Comment by CalligoMiles** [comment]
That seems plausible, I did log off shortly after igniting it.

The pit was 3x3x1, with the coordinates visible below the map. The firepit was on top of the central pile.

**Comment by CalligoMiles** [comment]
Update: It happened again on the next batch in the same pit, now 3x3x2, to the same row. Apparently just logging off shortly after suffices.

**Comment by Harlekin13** [comment]
maybe try putting the firepit onto one of these piles, if it is the chunk border, it then should leave the other piles untouched (or it may be directional).

**Comment by CalligoMiles** [comment]
I ended up shifting the whole thing a block to the north, that solved it.

**Comment by Craluminum2413** [comment]
> https://www.vintagestory.at/forums/topic/4043-new-stable-vs-mod-db-v115-sneak-peek-v1148/?tab=comments#comment-17542
> Fixed: occasionally charcoal pits not fully converting if span unloaded chunk border
