### ISSUE TITLE
Trapdoors should let smoke pass through

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#752]
Title. Trapdoors look for all the world like wooden grating, yet putting one in a chimney will keep the smoke inside your house. I think it would look quite a bit better if it could pass through unhindered.

![VS trapdoor smoke](https://user-images.githubusercontent.com/19876578/104477607-99a97200-55c1-11eb-8126-20a6f4b81ec2.png)

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
