### ISSUE TITLE
Partially spoiled crocks display wrong sat value

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#755]
**Game Version:** 1.14.5
**Platform:** Windows 
**Modded:** No 

### Description
Crocks, both sealed and unsealed, that are in the process of spoiling display a sat value for their contents that's significantly lower than it should be. 

When taken out and consumed the food gives the right values again.

### How to reproduce
Make a (hefty) meal and store it until it starts spoiling but check before it's entirely rotten. Sealing may be required too.

### Screenshots
![VS spoiled crock](https://user-images.githubusercontent.com/19876578/104630829-9edaef80-569b-11eb-8906-86e95d4e73bf.png)

**Comment by DArkHekRoMaNT** [comment]
Works fine in 1.18.5
