### ISSUE TITLE
Quern sound still plays when disconnected by transmission

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#762]
**Game Version:** 1.14.5
**Platform:** Windows
**Modded:** No 

### Description
The quern sound effect keeps playing when the quern is no longer powered - with my particular setup involving a clutch transmission that serves to disconnect it.

Update: It still plays even when the rotor loses power

### How to reproduce
Presumably, set up a quern to be powered by a windmill, with a transmission in between. Then disengage the transmission while the rotor remains powered.

My particular setup runs from the rotor (full sails) through one angled gear to a big gear. The big gear immediately links to 2 transmissions with angled gears, one of which then powers the quern from below with the help of another angled gear.

### Expected behavior
For the sound to cease once the quern loses power

**Comment by DArkHekRoMaNT** [comment]
Can't reproduce in 1.18.5, probably fixed
