### ISSUE TITLE
Items are duplicating and messing up when taken from wood pile  / forge / anvil

### ISSUE THREAD

**Issue by BENETNATH** [anegostudios/VintageStory-Issues#764]
**Game Version:** 1.14.7 (and before
**Platform:** Windows 10 (client) - Windows 7 (server)
**Modded:** No 

### Description
When a player take an item, like a wood piece from a wood pile, it appears twice in the item bar, in two different slots. when he puts the item back to the pile, depending on the item slot he is using, either it's adding back of not. 
Same thing happens when putting an ingot on an anvil, sometimes the partially worked ingots doubles when grabbed back. And if you place one of the item back (the wrong slot), it may even not be displayed, but the anvil would be considered as used, and the pointer will mention it. 

### How to reproduce
1. Make a wood pile
2. Take a wood piece from it, it's added twice in the item slot
3. Put it back

### Screenshots
Video has been added to discord :
https://discordapp.com/channels/302152934249070593/334233095374897152/801145996645236786

### Logs
nothing on server console.

I did not log more than that. But I can provide if needed.
```

**Comment by Barhandar** [comment]
Not related to wood piles/forges/anvils, is a general bug with hotbar slots, persists in 1.17.9. I do not know how to reliably trigger or resolve it.

**Comment by DArkHekRoMaNT** [comment]
Marked as duplicate #2252 (this issue is more relevant now)
