### ISSUE TITLE
Cellar bonus not consistent - especially after loading a save

### ISSUE THREAD

**Issue by EarthwormO** [anegostudios/VintageStory-Issues#765]
**Game Version:** 1.14.7
**Platform:** Windows 
**Modded:** No 

### Description
Food preservation is highly inconsistent and changes without room changes.

### How to reproduce
1. Made a room with 5x3 internal dimensions.  Walls are all Slate Cobblestone, floor and ceiling are Granite Cobblestone.  With a wooden door.  Place Shelf, has food perish speed of .29.  Save game and exit.  Reload Saved game.  Same shelf now has 0.79 Food perish speed.
Happens with most storage vessels in the room as well.  Except for 1.  Seems whatever vessel or shelf in the upper South side of the room does not get affected, and keeps its original perish speeds.

I have to break and replace all my shelves and storage vessels to get them back to the proper preservation each time I load my game.  During a single run (without saving and exiting my cellar seems to work fine.)

### Expected behavior
Food Perish speed should be consistent between Save Game loads.

### Screenshots
Attaching three screenshots.  

FirstEnterGame.png is when I first loaded up the game and looked at a shelf in the Cellar.  Notice Food Perish speed 0.74.  
Breakandreplace.png I broke the shelf and put it exactly back in the same place.  Food Perish speed now 0.29
AfterReload.png - Saved the game and exited.  Re-opened Vintage Story and reloaded game.  Shelf is back to 0.74.
![FirstEnterGame](https://user-images.githubusercontent.com/13572988/105402101-a1ce6680-5bec-11eb-8fc4-ab622054e546.png)
![Breakandreplace](https://user-images.githubusercontent.com/13572988/105402106-a3982a00-5bec-11eb-8aa6-7f1cf35e01b1.png)
![AfterReload](https://user-images.githubusercontent.com/13572988/105402110-a430c080-5bec-11eb-9b9a-2af45ea3a7a6.png)

### Logs
```
No crash
```

**Comment by Craluminum2413** [comment]
Fixed in 1.14.8 - 1.14.10
> https://www.vintagestory.at/forums/topic/3926-wintery-stability-patch-2-v1148-rc1
> https://www.vintagestory.at/forums/topic/4442-vintagehosting-v1149-v11410
> Fixed: Cellars on chunk boundaries not showing correct perish speed until a block update occurred
> Fixed: Spoilage rates in containers in cellars were shown incorrectly in tooltips client-side
> Fixed: Update cellar spoilage rates instantly when player looks at tooltip, not next temperature tick
