### ISSUE TITLE
Part of map not drawing correctly

### ISSUE THREAD

**Issue by paul59** [anegostudios/VintageStory-Issues#767]
VS 1.14.7
MX Linux 19.3, Radeon RX570 8gb, 16gb RAM

I think this is a bug, I don't see anything on the ground to account for it...

![image](https://user-images.githubusercontent.com/3756822/105524506-a02d9d00-5cd7-11eb-99f3-84a7c3259de9.png)

**Comment by Craluminum2413** [comment]
There isn't even information where the player is

**Comment by Craluminum2413** [comment]
Maybe it is fixed too in [1.16.0-rc.1](https://www.vintagestory.at/forums/topic/6102-homesteading-part-2-half-a-combat-update-v1160-rc1-rc2/#:~:text=Tweak%3A%20Fine%20tuned%20snow%20accumulating%20and%20melting%20to%20be%20a%20bit%20less%20abrupt.)?

**Comment by copygirl** [comment]
The linked fix is about snow physically accumulating on the ground, not world map related.
