### ISSUE TITLE
When bell is disabled, monsters still spawn despite being disabled

### ISSUE THREAD

**Issue by mintyogi** [anegostudios/VintageStory-Issues#769]
**Game Version:** 1.14.7
**Platform:** Windows
**Modded:** Yes - NoMonsters 1.1.0

### Description
Disabled entities still spawn when bells are disabled via patch too.
Bells, drifters, and locusts can still spawn with No Monsters 1.1.0 (which patches out bells, drifters, and locusts) the disabled entities still spawn

### How to reproduce
1. Install and enable [NoMonsters v1.1.0](https://github.com/mintyogi/NoMonsters/releases/tag/1.1.0) (which patches out bells, drifters, and locusts)
2. Spawn bell or change to night
3. Drifters spawn despite being disabled

### Expected behavior
Bells, drifters, and locusts should not spawn.

**Comment by Craluminum2413** [comment]
Bell will cause crash if drifters and locusts was disabled with patches except bell

**Comment by Craluminum2413** [comment]
Can't reproduce, I assume it is fixed
