### ISSUE TITLE
Acacia saplings drop rate too low?

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#77]
1.5.2.6, official server.
Acacia atm seems to have a bit too low saplings drop rate.
I get approx 1 **extra** sapling per 3 standalone trees. This is much lower than other trees, I guess mostly because of less leaves per tree.
Such a low rate makes reforesting acacia forests and planting forests for terraforming less fun.
Also acacia has unique form, which sometimes makes fully shearing it less comfortable.
Please consider buffing a bit, ~2 times I would suggest.

**Comment by tyronx** [comment]
Ok, doubled the drop rate for 1.5.3!
