### ISSUE TITLE
Make mouse keys selectable in Settings-Controls for more ergonomic control settings (Mouse1 / 2 / 3 / 4 or more).

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#771]
Make mouse keys selectable in Settings-Controls for more ergonomic control settings.

**Comment by meganukebmp** [comment]
I would very much want this feature as well. I like to play with my mouse buttons swapped around and I would love to be able to rebind them

**Comment by Craluminum2413** [comment]
Can help https://mods.vintagestory.at/show/mod/658

**Comment by meganukebmp** [comment]
> Can help https://mods.vintagestory.at/show/mod/658

Haha yes, I am the creator. Got frustrated and made that mod. Still, an official toggle would be great!

**Comment by Craluminum2413** [comment]
#404

**Comment by Craluminum2413** [comment]
![image](https://github.com/user-attachments/assets/eacb4648-be4f-49fc-a26a-f4f3063ef7a8)

**Comment by BradyThe** [comment]
Just for the sake of thoroughness (the OP mentioned "more" after all): VS recognizes up to 5 mouse buttons. Any more (side) buttons are not bindable.

**Comment by Craluminum2413** [comment]
@BradyThe Side buttons are bindable, I tested it

**Comment by BradyThe** [comment]
> @BradyThe Side buttons are bindable, I tested it

Consider my comment a Layer 8 problem. Cheers!
