### ISSUE TITLE
Traider doe not want to trade

### ISSUE THREAD

**Issue by Gutsherr3** [anegostudios/VintageStory-Issues#775]
**Game Version:** V1.14.7
**Platform:** Windows 10
**Modded:** No

### Description
I cannot sell anything to some traders. I sold one piece once to some traders and now they do not buy anything from me anymore.
It is not possible to put the wanted Items in the selling slots. It works with some new traders I found after the last update. They buy till their needs are fulfilled. But the earlier found traders do not accept any items. They sell their stuff but do not buy.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
I know that traders will only buy up to the maximum they want. I don't suppose you've put more in their inventory than they want?

**Comment by Craluminum2413** [comment]
I think it's better to close this issue. Since traders don't buy them, if you put in more than they are willing to buy

**Comment by copygirl** [comment]
Yeah this should be closed due to lack of response.
