### ISSUE TITLE
1.14.7 stable - object placement preview issue with lantern in hand

### ISSUE THREAD

**Issue by CaptainCJH** [anegostudios/VintageStory-Issues#777]
**Game Version:** 1.14.7
**Platform:** Windows 10 64 bit
**Modded:** Yes with VSHUD.dll 2.0.3

### Description
With any lantern in my hand, all objects preview as a brass lantern when using SHIFT to place them on the ground. Removing the object in hand returns preview object to normal when attempting to place it.

### How to reproduce
1. Put any lantern in your hand in inventory
2. Attempt to place any placeable object such as a torch or a bucket
3. All objects will preview as a brass lantern.
4. removing lantern from hand in inventory restores normal preview object behavior.

![2021-01-30_13-50-50](https://user-images.githubusercontent.com/33158003/106366635-cfa95e80-6302-11eb-816a-db859eb52186.png)
![2021-01-30_13-51-11](https://user-images.githubusercontent.com/33158003/106366639-d8019980-6302-11eb-834e-0d3a9f1cf1ee.png)
![2021-01-30_13-51-59](https://user-images.githubusercontent.com/33158003/106366641-d9cb5d00-6302-11eb-85b4-6999dc10bb86.png)
![2021-01-30_13-52-35](https://user-images.githubusercontent.com/33158003/106366649-dfc13e00-6302-11eb-8f8f-381c19c236b3.png)

**Comment by copygirl** [comment]
VSHUD adds the placement preview. Can you explain how this bug is related to Vintage Story rather than just the mod?

**Comment by CaptainCJH** [comment]
Ok gotcha. Then it is not and I will contact the author of the mod.
