### ISSUE TITLE
Wrong part info in tapestry "Salvation" 

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#778]
**Game Version:** 1.14.7
**Platform:** client: Windows, server: Linux
**Modded:** Yes (Medieval expansion; Rope bridges)

### Description
Some part info in tapestry "Salvation" is wrong. Bottom-left part has info Top-right.  And Top-right part has info Bottom-left. Please keep in mind that Salvation tapestry parts miniatures are mirrored left<->right (another reported issue).

Bottom-right and top-left are ok.

### How to reproduce
1. Put all four parts of tapestry Salvation into 
2. Move cursor over tapestry parts...

### Expected behavior
The right part info.

### Screenshots
Attached:

![Ashampoo_Snap_sobota 30  ledna 2021_23h57m53s_003_](https://user-images.githubusercontent.com/8435741/106370399-efb83c80-6359-11eb-8929-0c3be3dc130a.jpg)
![Ashampoo_Snap_sobota 30  ledna 2021_23h57m35s_002_](https://user-images.githubusercontent.com/8435741/106370400-f0e96980-6359-11eb-8d1c-9f185811f6a8.jpg)

**Comment by l1ving** [comment]
This is now fixed.
