### ISSUE TITLE
Buggy crafting with SHIFT key

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#780]
I was not able to reproduce this bug. However it could be serious so I decided to put it here. Someone else reported this in Forum in Bugs:
https://www.vintagestory.at/forums/topic/3870-after-making-skeps-with-shift-click-skeps-continue-to-be-made-with-other-recipes-when-shift-clicking-147/?tab=comments#comment-16426

**Game Version:** 1.14.7
**Platform:** client: Windows, server: Linux
**Modded:** Yes (Medieval expansion, Roped bridges)

### Description
I crafted a lot of bloomery chimney with use of SHIFT key at once. Some time later: I tried to scrap 11 soaked hides with use of SHIFT (knife at the top; 11 soaked hides below knife in craft). I used SHIFT click and I got 1 scraped hide and 10 bloomery chimneys.

### How to reproduce
1. Make a lot of bloomery chimneys with use of SHIFT key (to craft all pcs at once)
2. Scrape 11 soaked hides with knife with use of SHIFT key (to scrap all at once)
3. You'll get 1 scraped hide and 10 bloomery chimneys

### Expected behavior
You should get 11 scraped hides

**Comment by Craluminum2413** [comment]
This definitely applies to multiplayer
