### ISSUE TITLE
Disable coordinate overlay feature not working completely

### ISSUE THREAD

**Issue by Criperum** [anegostudios/VintageStory-Issues#787]
**Game Version:** 1.14.8-rc.-1
**Platform:** Windows
**Modded:** No

### Description
The coordinate overlay check box that disables coordinates on 'V' and hides them from Ctrl+F3 overlay still shows the coordinates of blocks user looking at revealing the user coordinates

### How to reproduce
1. Create ot join the world with coordinate overlay disabled
2. Press Ctrl+F3
3. Look at any block

### Expected behavior
The Selected block section does not contain block coordinates
![2021-02-14_22-07-33](https://user-images.githubusercontent.com/13226034/107886467-11482500-6f11-11eb-9846-1bf39fdcbd8b.png)

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

**Comment by radfast** [comment]
Thanks, this is now fixed in next build of 1.14.8
