### ISSUE TITLE
Items remain in crafting grid on death

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#788]
**EDIT by @copygirl:** Dupe bug is no longer occurring, but crafting grid items still remain after death.

**Game Version:** 1.14.7
**Platform:** Windows 
**Modded:** N0

### Description
When dying in the middle of crafting it drops the completed product without consuming the ingredients

### How to reproduce
1. Put a completed recipe in the crafting recipe so the output item shows
2. Kill yourself
3. Pick up items

### Expected behavior
Expected it to not drop the finished product

### Screenshots
https://youtu.be/Caoe7X6SQ9I

**Comment by Craluminum2413** [comment]
Close issue?

**Comment by copygirl** [comment]
@Craluminum2413 Did you see if it can't be reproduced anymore?

**Comment by Craluminum2413** [comment]
I tried to reproduce it in 1.15.0-pre.2, items remain in the crafting grid, nothing drops out at the output when you die

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.8

**Comment by copygirl** [comment]
> Fixed: Dying did not eject the crafting grid inventory contents
~ [1.15.0-pre.8](https://info.vintagestory.at/v1dot15#pre8)
