### ISSUE TITLE
Controls in main menu don't fit in smaller window despite space being available

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#79]
![screenshot_2018-04-17_12-56-53](https://user-images.githubusercontent.com/272586/38867277-d0e3be2c-4243-11e8-95fc-7baf5b246205.png)

**Comment by Craluminum2413** [comment]
I think these issues are the same: #265, #388

**Comment by copygirl** [comment]
You're right I think these have all been addressed.
