### ISSUE TITLE
Shooting the armor stand makes it impossible to break

### ISSUE THREAD

**Issue by KleiMomentulas** [anegostudios/VintageStory-Issues#794]
Game Version: 1.14.7
Platform: Windows
Modded: No

Description
Explain the issue you're running into.

How to reproduce
1. Shoot an arrow or throw spear at the armor stand
2. If you get a hit sound and armor stand flashed red you can't now destroy it it

**Comment by Craluminum2413** [comment]
Invalid issue? You can only pick it up and not break it, can you?

**Comment by Craluminum2413** [comment]
Can't reproduce this bug in 1.15.0-pre.3

**Comment by copygirl** [comment]
Will close for now until someone managed to reproduce it.
