### ISSUE TITLE
Make it easier to run multiple server instances at the same time

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#8]
>  Right now we cannot have 2 servers running Vintage Story with different versions, once you install the update it will not let you run the old version.
> 
> Right now we also cannot run 2 servers with the same version at the same time using different ports. Or at least I and Skol could not find a way to create this without having to manually create the files for it. 
> 
> Bottom line we need a server launcher that is capable of handling multiple instances with different ports and different versions of the server.

~ tony Liberatto [on the forums](https://www.vintagestory.at/forums/topic/426-multiple-instances-of-the-server-on-the-same-machine/)

**Comment by tyronx** [comment]
the server.sh supports this since v1.9 or so
