### ISSUE TITLE
Random crash, can't reconnect

### ISSUE THREAD

**Issue by bitcynth** [anegostudios/VintageStory-Issues#80]
[VintagestoryCrash.txt](https://github.com/anegostudios/VintageStory-Issues/files/1923633/VintagestoryCrash.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/1923634/server-main.txt)
![screenshot](https://user-images.githubusercontent.com/34239865/38927777-18ed6056-4307-11e8-99c8-ef68a33b6719.png)

stuff

**Comment by tyronx** [comment]
Does this still happen in 1.5.3?

**Comment by bitcynth** [comment]
Yes, I still can't connect to the chrometech.at server.

**Comment by tyronx** [comment]
Added some debug logging to fix this for next release

**Comment by tyronx** [comment]
Server is updated, please do try and join one more time @bitcynth, then i'll check out the logs

**Comment by tyronx** [comment]
Ok, fixed for 1.5.5
