### ISSUE TITLE
Invisible Bowl Texture

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#804]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### Description
Invisible texture of an empty bowl after using an empty crock on it

### How to reproduce
1. Place an empty bowl
2. Right-click with empty crock on the bowl
3. Bowl texture will disappear, on the minimap it will look like a white pixel

### Expected behavior
Nothing

### Screenshots
![2021-03-03_13-58-10](https://user-images.githubusercontent.com/69315569/109802440-806b8c00-7c28-11eb-82ca-616d473575e3.png)

**Comment by copygirl** [comment]
This appears to have been fixed in [v1.14.9-rc.1](https://www.vintagestory.at/blog.html/news/vintagehosting-preparations-v1149-rc1-r281/).

> Right clicking with an empty crock on an empty bowl made the bowl invisible
