### ISSUE TITLE
Deleting a waypoint from the map

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#805]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### Description
A strange window appears and map locked after deleting a waypoint in the same coordinates as another waypoint

### How to reproduce
1. Create two waypoints at the same coordinate
2. Delete or choose (close after choosing one) one of these waypoints
3. A strange window appears, the map locked

### Videos

https://user-images.githubusercontent.com/69315569/122209317-0f857280-cead-11eb-94c7-95872f37a727.mp4

**Comment by Craluminum2413** [comment]
creative and survival

**Comment by copygirl** [comment]
Random guess: Two dialogs are opened when clicking to edit a waypoint. The game then gets confused when one of them is closed. Waypoint dialogs may all share the same ID..?

**Comment by Craluminum2413** [comment]
@copygirl Yes, two dialogs are opened at the same time. I added video to explain it better

**Comment by Craluminum2413** [comment]
1.15.0-pre.4
> Fixed: Deleting a waypoint that overlaps another causes a black square on the screen
