### ISSUE TITLE
[minor streamlining] lighting fireplace with torch

### ISSUE THREAD

**Issue by Harlekin13** [anegostudios/VintageStory-Issues#806]
Anything other than fireplaces seems to be lit with sneak+right click when holding a torch, when holding a firestarter that's correct for fireplaces too, but with a torch you can light the fireplace with only right click too.

I think it would improve intuitive play if everything gets lit with the same keys, no matter the thing you use to light it.

Easiest to implement would be to remove the option right click to light on fireplaces when holding a torch and have it use sneak+right click like everything else.

**Comment by Craluminum2413** [comment]
Sounds like a suggestion https://www.vintagestory.at/forums/forum/5-suggestions/
