### ISSUE TITLE
[minor streamlining] take torch with right click

### ISSUE THREAD

**Issue by Harlekin13** [anegostudios/VintageStory-Issues#807]
Lantern and oil lamps can be taken with a right click when the hand is empty.

Torches should be treated the same way. Maybe they even should be able to be taken out of a torch holder instead of having to break it?

**Comment by copygirl** [comment]
You can take torches out of torch holders exactly the way you described.

**Comment by Craluminum2413** [comment]
Can be done by adding RightClickPickup behavior to torch. It does exactly what you want.

**Comment by sirStroam** [comment]
We are no longer doing suggestions on the issue tracker. Please add to the suggestions on the forums.
