### ISSUE TITLE
stuck when loading in

### ISSUE THREAD

**Issue by Macciebe** [anegostudios/VintageStory-Issues#808]
**Game Version:** X.Y.Z
**Platform:** Windows 
**Modded:** No 

### Description
When loading into my old world, I am stuck inside something and am nbot able to play on

### Screenshots
![2021-03-06 (2)](https://user-images.githubusercontent.com/74201770/110201075-87311380-7e61-11eb-89c5-744698ecc042.png)

**Comment by Craluminum2413** [comment]
Invalid issue. No version, no additional information

**Comment by copygirl** [comment]
I'll close this as incomplete for now.
