### ISSUE TITLE
Cannot get firewood item from firewood pile with middle click

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#813]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### How to reproduce
1. Make a firewood pile
2. Go to creative
3. Copy firewood pile with MMB (middle mouse button)
3. You get invisible firewood

### Expected behavior
You have copied a visible firewood item

**Comment by Craluminum2413** [comment]
Now it happens to all the piles in the pre-releases of 1.15

**Comment by Craluminum2413** [comment]
Now only these items give the wrong number of items they contain. Peat pile gives just one peat item, firewood pile gives invisible firewood pile
![image](https://user-images.githubusercontent.com/69315569/123005050-2a307d80-d3be-11eb-88ab-2cc29ca269e8.png)

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in rc.3
