### ISSUE TITLE
Honeycomb fills bucket GUI but picking up shows empty bucket

### ISSUE THREAD

**Issue by MrKrumb** [anegostudios/VintageStory-Issues#816]
**Game Version:** 1.14.8 (Stable)
**Platform:** Windows 10
**Modded:** No 

### Description
Harvesting honeycomb in bucket shows GUI working, but picking up bucket shows empty and honeycomb appears to be lost. 
Moving items around in inventory will return original honeycomb

### How to reproduce
1. Get honeycomb
2. Use it on a bucket
3. It does strange things

### Expected behavior
Would expect wax in inventory and honey in bucket when picked up

### Logs
```
Did not crash ( and has never crashed :) )

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.15.0-pre.2
