### ISSUE TITLE
The last removed block/blocks from the chunk leaves its texture

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#828]
**Game Version:** 1.14.x, 1.15.0-pre.6
**Platform:** Windows 10
**Modded:** No

### Description
"/debug cr" is useless, it fixes only the textures that remain. doesn't fix chunk at all.

### How to reproduce
1. Enter any world
2. Place any block in empty chunk then remove it
3. The block leaves its texture

### Videos
https://user-images.githubusercontent.com/69315569/122218568-3fd20e80-ceb7-11eb-95ce-942a064a6a4c.mp4

https://user-images.githubusercontent.com/69315569/122218576-41033b80-ceb7-11eb-8a73-f6c6c01c9af3.mp4

https://user-images.githubusercontent.com/69315569/122218579-42346880-ceb7-11eb-8098-4987d0f4a090.mp4

https://user-images.githubusercontent.com/122218758-6d1ebc80-ceb7-11eb-9778-9f031a600b0d.mp4

**Comment by radfast** [comment]
Thanks for reporting and updating this issue @Craluminum2413 
Sorry it's taken so long for us to get to it.

It is indeed an engine bug in all 1.15 versions, related to some of the performance optimisations.  We know the cause and are looking at fixing as a priority now.   Plainly, the issue is client side only

**Comment by Craluminum2413** [comment]
Originally, the issue was about the ladders, but I remade it to this chunk problem. Although the ladder bug was discovered back in 1.14, but to reproduce the ladder bug, you also need an empty chunk. Maybe also look at them too?

**Comment by Craluminum2413** [comment]
Briefly about what the "ladder issue" was

**Ladder**

https://user-images.githubusercontent.com/69315569/123397958-b0f67d80-d5ab-11eb-8792-be3dac182e45.mp4

**Chute**

https://user-images.githubusercontent.com/69315569/123397962-b227aa80-d5ab-11eb-96b9-2454459bdcdb.mp4

**Door**

https://user-images.githubusercontent.com/69315569/123398400-27937b00-d5ac-11eb-9a07-03402c8ef9b8.mp4

**Comment by radfast** [comment]
Fixed for 1.15-pre.9 or whichever is next after pre.8 :)

Thanks @Craluminum2413  for the careful report, amazing!
