### ISSUE TITLE
Holding Alt doesn't allow you interact with blocks in certain cases

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#834]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### Description
`Igniting a firepit` / `tilling a farmland` holding Alt doesn't work if your actual cursor (not Alt's cursor) looking at `a ignited firepit` / `a tilled farmland`.

#### Firepit
1. Make two firepits and refuel them
2. Ignite one of them
3. Try to ignite second firepit while looking with actual cursor at ignited firepit holding Alt
4. The second firepit will not ignite
#### Farmland
1. Till a soil block
2. Try to till another soil block while looking with actual cursor at tilled soil block holding Alt 
3. You can't till another block
### Expected behavior
Firepit is ignited, soil has been tilled

### Videos

https://user-images.githubusercontent.com/69315569/122205640-2924bb00-cea9-11eb-9baa-ef85497619c6.mp4

https://user-images.githubusercontent.com/69315569/122205729-3e014e80-cea9-11eb-8cdc-fb272cdc2e70.mp4

**Comment by chriswa** [comment]
I believe this also affects hoeing dirt into farmland.

**Comment by Craluminum2413** [comment]
Yes it is. I just tested it in the same way and I couldn't make a new farmland with hoe

**Comment by Craluminum2413** [comment]
Resolved by itself
