### ISSUE TITLE
Knapping pattern orientation breaks immersion (very slightly)

### ISSUE THREAD

**Issue by chriswa** [anegostudios/VintageStory-Issues#838]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** No

### Description
When knapping, the orientation of the knapping pattern is always aligned with true north. For example, if you spin around and get yourself lost, then face any direction and knap some knives, the blades of your knives will always face west. This can be used as a funky compass.

### How to reproduce
1. Shift-right click a knappable stone
2. Select knives
3. Look at the pattern on the ground

### Expected behavior
The orientation of the pattern should be relative to the player's facing when starting the knap.

**Comment by Craluminum2413** [comment]
It can be applied to many other blocks

**Comment by sirStroam** [comment]
This has been marked as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by Craluminum2413** [comment]
Falling blocks also always only fall to the north

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/125190208-a5aa7f80-e244-11eb-91ce-7d82fc220466.mp4

**Comment by sirStroam** [comment]
The falling thing should be put in its own issue.

**Comment by Craluminum2413** [comment]
Okay, I will create issue about this
