### ISSUE TITLE
Items rendered in GUI item slots appear horizontally flipped

### ISSUE THREAD

**Issue by chriswa** [anegostudios/VintageStory-Issues#839]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** No

### Description
Shapes rendered into GUI item slots (and tooltip previews) appear to be flipped horizontally from how they appear in the player's hand in first or third person, as if viewed in a mirror. Most shapes in the game seem to be horizontally symmetrical, so this issue is not very noticeable.

### How to reproduce
1. Get a Broken Static Translocator in your active slot
2. Go into 3rd person and pan the camera around until you can see your front
3. Mouseover the item slot to get a big, rotating preview
4. Compare what's in your hand to what's in the GUI

### Screenshots
![chiral0](https://user-images.githubusercontent.com/529800/112902561-27faa380-909b-11eb-8ce2-a30b03942c55.png)
![chiral1](https://user-images.githubusercontent.com/529800/112902553-2204c280-909b-11eb-8a6e-fc55c059f988.png)

**Comment by Craluminum2413** [comment]
Related to #750

**Comment by copygirl** [comment]
True, will close as duplicate for now.
