### ISSUE TITLE
Baked Shingle can be Baked Again

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#849]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### Description
The baked shingle can be baked again infinitely

### How to reproduce
1. Make a campfire and refuel it
2. Put baked shingle in the campfire
3. Ignite ~~Start the process~~
4. Baked shingle baking again

### Expected behavior
Baked shingle doesn't bake

### Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/69315569/113576836-edf44900-9628-11eb-8adc-3ce173b35fe5.png)
![Screenshot_3](https://user-images.githubusercontent.com/69315569/113576839-ef257600-9628-11eb-8768-69b4f635782e.png)

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/113836673-c40c6500-9795-11eb-8dfa-e81bdb8bed0b.png)

**Comment by Craluminum2413** [comment]
Accidentally closed, lol
![image](https://user-images.githubusercontent.com/69315569/113836701-cbcc0980-9795-11eb-86c3-3bdb2ee27955.png)

**Comment by Craluminum2413** [comment]
Accidentally closed, lol

**Comment by tyronx** [comment]
thanks for the report, this is now fixed in pre.7
