### ISSUE TITLE
Worldgen crops won't grow

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#85]
All crops spawned on worldgen don't grow because the grass they are growing on does not have the required nutrients because it's grass.

**Comment by tyronx** [comment]
It's on joshes todo list for a while now

**Comment by jchappelle** [comment]
Worldgen crops now receive server ticks. As of version 1.5.2 I think. I resolved the Jira issue on April 1st so it hasn't worked that way for very long.

**Comment by sirStroam** [comment]
They may receive ticks but not nutrients needed to grow.

**Comment by Heptagon-ru** [comment]
I am not 100% sure but in 1.5.2 I have seen non-grown crops near my base and they still don't grow. They should have gotten enough ticks because me and neighbours are running near that chunk quite often, at least all barren dirt turned into grass, but the crops are still on stage 1 approx.

**Comment by Heptagon-ru** [comment]
Yes, found one.
The ladders under word "West" are where the road is. So this area is constantly visited from my base start, and I have neighbours for few weeks. But crop is not growing any more it seems.
![2018-04-22_11-14-12](https://user-images.githubusercontent.com/25122345/39093061-dae9ea40-4621-11e8-936b-617b3ba68912.png)

**Comment by sirStroam** [comment]
Last I tested this works. Will reopen upon pending failed tests.

**Comment by tyronx** [comment]
yay
