### ISSUE TITLE
Confusing tooltips

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#853]
**Game Version:** 1.14.8
**Platform:** Windows 10
**Modded:** No

### Description
The mushroom says that it can be harvested when it is already harvested.

### How to reproduce
1. Enable "block interaction help" setting
2. Find a harvested mushroom
3. Tooltip says that it can be harvested

### Expected behavior
It shouldn't say that it can be harvested if it has already been harvested.

### Screenshots
![2021-04-07_18-27-09](https://user-images.githubusercontent.com/69315569/113894206-6fd2a680-97d0-11eb-82eb-0a161185f6d0.png)

**Comment by tyronx** [comment]
thanks for the report, this should be fixed for pre.7
