### ISSUE TITLE
Grass doesn't spread on medium soil

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#86]
confirmed by multiple experiments. 
![image](https://user-images.githubusercontent.com/12073699/39082952-3f54f6a4-4510-11e8-9d26-f9d3fafc72b8.png)

didn't test high fertility soil because people use it for farms, not for grass usually

**Comment by Heptagon-ru** [comment]
On the ifficial server it spreads succesfully, just tested. First grass block appeared after about 2 minutes, next one - two more. Will check now when low and medium are close together.

![2018-04-21_15-20-33](https://user-images.githubusercontent.com/25122345/39084100-461a18da-4578-11e8-9bea-9ece11673770.png)

**Comment by Heptagon-ru** [comment]
I have compared all 3 soils (cant craft high fertility grass block, so used medium) - and after 5 minutes growts was quite equal.
Btw, Stroam, on your picture it looks like the low fertility plot touches some grass block, at the left bottom part. Maybe grass was spreading from there?
![2018-04-21_15-40-45](https://user-images.githubusercontent.com/25122345/39084242-a4f1ef16-457a-11e8-9a4b-c6ff3bb77da3.png)

**Comment by sirStroam** [comment]
It is not touching the grass

**Comment by sirStroam** [comment]
This appears to be in association with the RNG bug. Upon further testing, after restarting my client this behavior disappears. So I'm closing it.

**Comment by tyronx** [comment]
Oh okay, good

**Comment by Heptagon-ru** [comment]
Stroam, as a starter I used a crafted grass block (straw+dirt), low fertility for low fertility plot, medium for medium, medium for high fertility (impossible to craft high fertility grass).
