### ISSUE TITLE
Full bucket of water emptied onto the floor in room creates a permanent water source 

### ISSUE THREAD

**Issue by vinstory** [anegostudios/VintageStory-Issues#861]
**Game Version:**1.14.8
**Platform:** Windows 
**Modded:**  Yes (which?) HUD clock 2.4.2

### Description
Emptied a full bucket of water onto the floor and it created a permanent water source as shown in attached screen shot. Restart didn't fix it. Placing a dirt block on the water source stopped the water and removing the block. got rid of the water source. Am able to reproduce by emptying the full bucket again.  Then again it could be considered a "feature" ;)

### How to reproduce
1. Empty full bucket of water on the floor inside of a room
2. 
3.

### Screenshots
![Screenshot (179)](https://user-images.githubusercontent.com/82376654/114377793-f693d480-9b7e-11eb-9a71-67516b759c99.png)

**Comment by copygirl** [comment]
Thank you for reporting it but the bucket being able to create these source blocks is, as of this time, entirely intentional.
