### ISSUE TITLE
Items picked up on mouse cursor are not dropped on death

### ISSUE THREAD

**Issue by AZsSPC** [anegostudios/VintageStory-Issues#866]
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** No

### Description
if you die with items picked up by your mouse - you'll re-spawn with it (checked in multiplayer) ((sorry for bad eng))

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.15.0-pre.3
https://user-images.githubusercontent.com/69315569/122421332-f7891e00-cf94-11eb-80c7-36a0f1e9ca3a.mp4

**Comment by copygirl** [comment]
Will assume fixed then.
