### ISSUE TITLE
Can't cast coopper hammer

### ISSUE THREAD

**Issue by Rihnami** [anegostudios/VintageStory-Issues#867]
**Game Version:** 1.14.9 and 1.14.10
**Platform:** Windows 7 64 bit
**Modded:** No 

### Description
I can't cast coopper hammer, but other coopper tools is casting

**Comment by Craluminum2413** [comment]
Steps to reproduce? Any screenshots?

**Comment by copygirl** [comment]
Did you forget to fire the hammer mold?

**Comment by Rihnami** [comment]
Sorry, I'm inattentive. It's been other hammer
