### ISSUE TITLE
Can place rocks, clay, flint in the air

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#87]
1.5.2.6, official server. 
Can place ("attach") rocks, clay for making molds, flint for knapping, sneak-right clicking on a vertical side of a block. No block under the placed rock is required, can place so it hovers above a ground.
![2018-04-22_00-14-03](https://user-images.githubusercontent.com/25122345/39088881-fdd48b50-45c2-11e8-9fa2-3d096dcc0039.png)

**Comment by tyronx** [comment]
Thank you, fixed for 1.5.3. Flint can no longer be placed. Stones will drop to the ground.

**Comment by Heptagon-ru** [comment]
1.6 rc1 , PTS (public test server)

Hmm, how to reopen a ticket?

Still can place rocks "in air" if there is another rock under it. Looks kinda cheaty, idk.
Can place clay molds gui in air, no block underneath is required.
Flint seems ok, can't place in any variant.

![2018-08-01_20-23-53](https://user-images.githubusercontent.com/25122345/43537851-1b727324-95c9-11e8-89d2-f2bca9b40a31.png)

**Comment by Heptagon-ru** [comment]
@copygirl Please reopen?

**Comment by tyronx** [comment]
Seems to be fixed for loose stones. Fixed it now for clay forms.
