### ISSUE TITLE
Superflat turns into realistic after customizing world

### ISSUE THREAD

**Issue by kousakak** [anegostudios/VintageStory-Issues#872]
**Game Version:** 1.14.10
**Platform:** Windows
**Modded:** No

### Description
I select superflat mode and then customized the world size and applied settings and creatde the world,then the world become a realisic one.

### How to reproduce
1. select superflat mode
2. change the customize world setting and apply
3. It turn into realistic one after world is created

**Comment by Craluminum2413** [comment]
I found a seed with a huge ocean.
1. Choose `Creative Building` preset
2. Choose `Customize`
3. Choose `1536` world height
4. Write seed `1506550105`
