### ISSUE TITLE
Item names in the handbook have issues with VTML

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#875]
**Game Version:** 1.14.10
**Platform:** Windows 10
**Modded:** Yesn't

### Description
Editing text for the item names with VTML causes showing the whole code in the handbook, while outside of handbook it works fine.

### How to reproduce
1. Edit name of any item/block in the **lang** file to, for example, `<font color=\"#1097b4\">Name</font>`
2. Open the handbook and search for the item/block
3. It will show the whole code of edited name

### Expected behavior
Shows item/block name in the same way as outside the handbook (player/creative inventory)

### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/69315569/116718819-0b77c100-a9e3-11eb-8485-b687715c4688.png)
![image](https://user-images.githubusercontent.com/69315569/116718966-34985180-a9e3-11eb-9653-92dfca89d443.png)
![photo_2021-04-30_20-28-49](https://user-images.githubusercontent.com/69315569/116731733-c3f93100-a9f2-11eb-8131-409a4acbf1dc.jpg)

**Comment by Craluminum2413** [comment]
Could this be related to localization and the game engine?

**Comment by tyronx** [comment]
No, its just not supported at the moment. I could easily fix the detail page title, but in the overall handbook list its still unformatted. Will add this feature once we have a use for it in vanilla Vintage Story
