### ISSUE TITLE
Can't open chest after loggin in on server.

### ISSUE THREAD

**Issue by Grzegorz1984** [anegostudios/VintageStory-Issues#882]
**Game Version:** 1.14.10
**Platform:** Windows 
**Modded:** No

### Description
Can't open chests. Running and picking tools works. Other players( 2 ) don't
have this issue.

### How to reproduce
1. Connect to server
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
I expected to open the chest. 

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
Just so I understand: By "picking tools" you mean right clicking a tool rack to get a tool?

**Comment by Grzegorz1984** [comment]
Yes,

exactly. Looking into it further it looked like a lag or network issues.
I don't think this error would be easy to reproduce or fix.
Topic could be closed.
