### ISSUE TITLE
Can't eat meal from bowl

### ISSUE THREAD

**Issue by McBainWRX** [anegostudios/VintageStory-Issues#891]
**Game Version:** 1.15.0-pre1
**Platform:** Windows 
**Modded:** No

### Description
I could not eat a meal from a bowl.  I tried left and right mouse button, and combinations with shift, ctrl and alt.

### How to reproduce
1. Cook a meal in a cookpot, pick up one serving with a bowl.
2. Use the bowl.  In previous versions you eat the meal with the use mouse button.
3. Nothing happens, the meal is not consumed and no hunger saturation is given.

### Expected behavior
The meal would be consumed and hunger would be reduced.

### Screenshots
NA

**Comment by raeu16** [comment]
I have the same problem but I discovered a way around it. If you place the bowl on the floor, crouch, and then click and hold right mouse button on the bowl, you’ll eat the meal.

**Comment by Davis105** [comment]
I too have the same issue!

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.2
