### ISSUE TITLE
Fallen leaves doesn't render the block side texture of the block they attached it

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#896]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Fallen leaves does not render the block side texture of the block they attached it.

### How to reproduce
1. Attach fallen leaves to any block (the surface is preferable)
2. The texture of the block side isn't rendered

### Expected behavior
The texture of the block side is rendered

### Screenshots
![2021-05-25_16-08-35](https://user-images.githubusercontent.com/69315569/119504888-140aaf80-bd75-11eb-84f7-611c3d7ecf0b.png)

**Comment by radfast** [comment]
Thanks for reporting.  Now fixed.  The fix will be in `pre.2` :)
