### ISSUE TITLE
Pie from sunflower dough have no texture

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#897]
**Game Version:** 1.15.0-pre.1, 1.15.0-pre.4
**Platform:** Windows
**Modded:** No

### Description
Pie from sunflower dough have no texture

### How to reproduce
1. Make a pie by placing sunflower dough on the table
2. It has no texture

### Expected behavior
It has texture

### Screenshots
![2021-05-25_16-32](https://user-images.githubusercontent.com/69315569/119507695-baf04b00-bd77-11eb-85a4-2a885c205bdf.png)

**Comment by copygirl** [comment]
Fixed in [1.15.0-pre.2](https://info.vintagestory.at/v1dot15#pre2):

> Fixed: Missing pie dough texture for pies

**Comment by Craluminum2413** [comment]
Screenshot from 1.15.0-pre2
![2021-05-29_21-48-57](https://user-images.githubusercontent.com/69315569/120081766-ea7cbb80-c0c7-11eb-9550-a3503787e962.png)

**Comment by Craluminum2413** [comment]
Pineapple filling has no texture too by the way. Oh, I should have said that 24 days ago

**Comment by Craluminum2413** [comment]
Okay, pineapple filling texture is fixed in 1.15.0-pre.5

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.7
