### ISSUE TITLE
Three breads and one pie in a clay oven

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#898]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Its possible to place three breads and one pie in a clay oven

### How to reproduce
1. Place a clay oven
2. Place one pie (you can't place more than one) in the clay oven
3. Then place three breads (you can't place more than three) in the same clay oven

### Expected behavior
Impossible to place breads in the clay oven if pie there

### Screenshots
![2021-05-25_16-53-15](https://user-images.githubusercontent.com/69315569/119510550-44a11800-bd7a-11eb-9ec4-4869ea962ddc.png)

**Comment by radfast** [comment]
Thanks very much for the clear report.  Now fixed.  The fix will make its way into `pre.2` when that comes.
