### ISSUE TITLE
Pie doesn't display in their description that it contains the second dough, if it was added

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#899]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Pie doesn't display in their description that it contains the second dough, if it was added. Also it doesn't display their freshness in placed state (block info overlay)

### How to reproduce
1. Start making a pie
2. Add any filling
3. Complete the pie with any other dough

### Expected behavior
It displays all doughs that were added

### Screenshots
(I added cassava dough and rye dough)
![image](https://user-images.githubusercontent.com/69315569/119515528-9c418280-bd7e-11eb-8cef-cdbfcf465584.png)

**Comment by Craluminum2413** [comment]
In the latest versions, something has been changed and now they do not display at all the dough from which they were made, so I think this can be closed, let the developers do what they want

**Comment by copygirl** [comment]
I'll leave it open just in case it was unintentional. Someone from the development team can look it over in the coming days and confirm it themselves. I think knowing what kind of dough(s) a pie was made from is kind of neat. It adds more "flavor" in a way, makes the end result feel a little more personal.

**Comment by Craluminum2413** [comment]
Some of 1.15 updates reduced that information, so I think it is no longer relevant
![image](https://user-images.githubusercontent.com/69315569/148459758-3a39a7c4-1678-4480-89fb-34cde45aa65f.png)

**Comment by copygirl** [comment]
I heard something about the names of foods being simplified so you're right.
