### ISSUE TITLE
In-progress charcoal pit fire spreads uncontrollably

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#90]
Vasemir on Discord found that if you open an in-progress, the fire extends outwards in odd ways.

> **Vasemir:** i think it's even burning underwater and it's turning when it hits the wall of some kind

![fire1.png](https://cdn.discordapp.com/attachments/404984611551182849/437712801050394634/fire1.png)
![fire2.png](https://cdn.discordapp.com/attachments/404984611551182849/437712827386429443/fire2.png)

**Comment by copygirl** [comment]
> **Vasemir:** @copygirl 
> As you posted my problem on to-do-list, I'd like to clarify:
> 
> I made a 4-cubes big charcoal pile and left it for about **3-4 days**. Then I opened it (it was still smoking, but I thought it was normal), but not from the "front" where the fire pit was, but from the back. I dug out the charcoal and then the fire spread, always moving to the north and east (I think it depended on positive coordinates).
> It was burning even in the air, but turned every time it hit the surface. It did not cause any damage. Putting blocks in already flaming path did not cause fire to turn mid-way.
> 
> After restarting the game problem was gone.

3 to 4 days of waiting for the charcoal pit to find it still partially on fire and expanding is strange. I wonder if it has to do with chunk border weirdness. To have the problem disappear when restarting makes me think it was a client-side thing.

**Comment by PyralIron** [comment]
sometimes i will think i light an ore bomb or a bloomery, but the animation just continues indefinitely before i relog. i think its probably a discrepancy between the client side and the server side, caused by lag in my case

**Comment by sirStroam** [comment]
I've had the same thing happen with bombs.

**Comment by tyronx** [comment]
Hm yea, how to reproduce that? :/

**Comment by tyronx** [comment]
This is likely due to the rng going haywire in 1.5.2.6. Please reopen if its still happens above that version.
