### ISSUE TITLE
Some items appear multiple times in "drops when broken" section in handbook

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#903]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Some block drops are duplicated in the handbook

### How to reproduce
1. Open handbook
2. Search for "Cracked vessel (Ore)" and "Grass"
3. Some items are duplicated in "Drops when broken"

### Expected behavior
Items aren't duplicated in the "Drops when broken"

### Screenshots
![2021-05-25_22-44](https://user-images.githubusercontent.com/69315569/119573828-738cad80-bdbd-11eb-80cd-55578986607b.png)
![2021-05-25_22-45](https://user-images.githubusercontent.com/69315569/119573833-74254400-bdbd-11eb-9514-90a452290869.png)

**Comment by Craluminum2413** [comment]
Also in creative inventory:
Chalk cobble skull
![image](https://user-images.githubusercontent.com/69315569/119977051-9d61f200-bfc0-11eb-8412-0a3ef65c577e.png)

**Comment by tyronx** [comment]
These are 3 different bugs. The first one is fixed in pre.7

**Comment by tyronx** [comment]
3rd one now also fixed in pre.7.

**Comment by Craluminum2413** [comment]
It looks like the 2nd one is the most difficult. It required you to rewrite the code to avoid duplicates, or add what tools should be used to harvest it

**Comment by tyronx** [comment]
yea, it should display the required tool

**Comment by Craluminum2413** [comment]
And of course the amount of items that will be dropped

**Comment by tyronx** [comment]
Well. This will have to suffice for now
![2021-06-22_20-59-14](https://user-images.githubusercontent.com/762006/122976163-c0ec4280-d39c-11eb-8d06-c32ebd0c638b.png)

**Comment by tyronx** [comment]
will also add a notice to the drop item stack tool tip
