### ISSUE TITLE
Unbalanced recipe for slanted roofing from clay

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#904]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
Slanted blueclay/fireclay roofing is crafted from 3 clay shingles and by alternate recipe from 4 clay shingles.
I suggest make recipe to directly convert clay shingle stairs to slanted clay roofing or have two recipes:
`1 clay shingles stairs` -> `2 slanted clay roofing` (and vice versa)
`3 clay shingles` -> `2 slanted clay roofing` (already exists)

### Screenshots
![2021-05-26_00-56](https://user-images.githubusercontent.com/69315569/119574916-dd598700-bdbe-11eb-9b98-60fbf08d898c.png)
![2021-05-26_00-56_1](https://user-images.githubusercontent.com/69315569/119574917-ddf21d80-bdbe-11eb-9cd5-5f2e441cb829.png)

**Comment by sirStroam** [comment]
This has been marked as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
