### ISSUE TITLE
Tools making using an iron anvil making mechanics

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#909]
To get closer to the concept of getting rid of the crafting grid, I would suggest to craft tools by "sticking a stick into the ground and putting on the tool heads, then hammering them with a stone or a hammer from the top" with using an iron anvil making mechanics. Maybe use the same mechanics for iron door making.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
