### ISSUE TITLE
Farmland doesn't drop soil when harvested

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#91]
If the intention is to prevent resetting the nutrients in the soil too easily, then simply change it so a non-grassy soil block, when tilled, starts out with 0 nutrients or so. Alternatively, you could drop a "no nutrients" block when breaking farmland (unless they are at their max), but then it would be annoying since they don't stack. Still, it is quite annoying to lose a soil block like that simply for tilling it. This too had me annoyed back in TFC.

**Comment by zkol** [comment]
Reflectiong the implementation in 1.5.3: 

Status : Soil comes in 3 "flavors" (low, medium, high fertitlity) and 3 states (barren, sparse grass, grassy). Farmland also comes in the 3 "flavors" (low, medium, high fertitlity) but in addition with detailed nutrient levels. 

Issue: Farmland does not drop soil as the description say

Possible solution: drop a "barren" soil block of the same "flavor". Tilling a barren block should result in the lowest nutrient level for the given "flavor" to avoid cheating.

**Comment by tyronx** [comment]
What copy meant is that it could drop a drained soil block that when placed slowly recovers again

**Comment by copygirl** [comment]
> What copy meant is that it could drop a drained soil block that when placed slowly recovers again

Either that or tilling a non-grassy soil block would start out the farmland's nutrients at 0%.

**Comment by tyronx** [comment]
This is intended behavior so relabeling

**Comment by Bloodsaw** [comment]
Want to add another suggestions that would feel more accurate and immersive:
If the fertility of the farmland is < its original values you should get a "depleted" low/medium/etc soil block, but if >= the original value you should get a normal one.

Furthermore this behavior should be added in the handbook.

For new players it can be quite irritating that they lose their tera petra when they try to relocate it.

**Comment by copygirl** [comment]
On the thread of my [patch mod](https://www.vintagestory.at/forums/topic/1209-farmland-drops-soil-110/) that drops soil upon breaking farmland, I had another suggestion:

> What about doing something similar to food regarding the stacking? Picking up a farmland block with lower than full nutrients will store its nutrients on the item itself. If the nutrients are similar enough to an existent stack in your inventory, they automatically stack. If not, you can still forcefully stack them, like food with varying amounts of freshness. Either way, the nutrients will be averaged.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
