### ISSUE TITLE
Unable to stack charcoal on ground or into the forge

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#910]
**Game Version:** 1.15.0-pre1
**Platform:** Windows 
**Modded:** No

### Description
Cannot stack charcoal on ground and into a forge

### How to reproduce
1. Take charcoal in hand
2. Apply it on ground or forge (shift + right mouse button)
3. It open an empty popup. When typing 'ESC' to close the popup, instead of stacking charcoal, we get a "paleolithic" handprint on the ground.

### Expected behavior
Stacking charcoal on the ground or into the forge.

**Comment by Craluminum2413** [comment]
Problem with Shift + RMB is gone sway, so now you able to put them at the forge, but still impossible to pile up charcoal and coke

**Comment by Saricane** [comment]
Yes, good news, because this one was really annoying.

**Comment by hlangeveld** [comment]
Looks like this is now fixed in 1.15-pre2 indeed. I was now able to forge my first saw in 1.15*

**Comment by Craluminum2413** [comment]
But you still not able to pile up them

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.3
