### ISSUE TITLE
Snow texture doesn't render on the stairs/slabs

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#911]
**Game Version:** 1.15.0-pre1, 1.15.0-pre.6
**Platform:** Windows
**Modded:** No

### Description
Snow texture doesn't render on the normal placed stairs and vertical slabs. Instead, it renders the texture of the block below (in this case, stairs/slab texture).

### How to reproduce
1. Place stairs in the most usual way / Place slab vertically
2. Wait until everything is covered with snow
3. It renders the same texture

### Expected behavior
It renders snow

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/119826762-0bdf7b00-bf01-11eb-937b-7e2f44d04aa4.png)
![image](https://user-images.githubusercontent.com/69315569/119826875-27e31c80-bf01-11eb-9c8d-13a2b03e33dd.png)

**Comment by Craluminum2413** [comment]
The trader in the description also looks north

**Comment by Craluminum2413** [comment]
![Uploading 2021-06-04_22-59-30.png…]()

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.7
