### ISSUE TITLE
Stair/slab top invisible with snowed-on fence on top

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#912]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### Description
The top part texture of the vertical slab/normal placed stairs under the fence/gate isn't rendered when snow on the top.

### How to reproduce
1. Place stairs in the most usual way / Place slab vertically
2. Place any of these blocks on the top: roughhewnfence, roughhewnfencegate, drystonefence, woodenfence, woodenfencegate.
3. Wait until everything is covered with snow
4. The top part texture doesn't render

### Expected behavior
The texture is rendered normally

### Screenshots
![2021-05-27_15-20-41](https://user-images.githubusercontent.com/69315569/119827446-d0917c00-bf01-11eb-897e-6d770d25ea0a.png)
![2021-05-27_15-40-00](https://user-images.githubusercontent.com/69315569/119827453-d1c2a900-bf01-11eb-9960-5e72f7b8d7fd.png)

**Comment by copygirl** [comment]
This might have been addressed in [1.15.0-pre.2](https://info.vintagestory.at/v1dot15#pre2), can you check?

> Fixed: Upside of stairs invisible in some cases.

**Comment by Craluminum2413** [comment]
Fixed for stairs only. Slabs still have this issue
![2021-05-29_21-54-32](https://user-images.githubusercontent.com/69315569/120081885-7abb0080-c0c8-11eb-83fb-a13d6af87ca0.png)

**Comment by Craluminum2413** [comment]
![2021-06-16_16-43-43](https://user-images.githubusercontent.com/69315569/122230164-0fdc3880-cec2-11eb-9693-745a8cfd5ea4.png)

**Comment by sirStroam** [comment]
New photo
![image](https://user-images.githubusercontent.com/12073699/123385682-a9eb5300-d54a-11eb-855c-2fb2d2671a19.png)

**Comment by tyronx** [comment]
Pretty sure this effectively needs a minor rewrite on how snow fall is handled. Likely a special block attributes if it blocks snowfall or not.

**Comment by Craluminum2413** [comment]
![2021-08-02_16-49-07](https://user-images.githubusercontent.com/69315569/127872202-79b004d0-cd7c-45b6-b97a-14e9c9d49c11.png)

**Comment by Ragolution** [comment]
Reproduced similar in 1.15.4

https://user-images.githubusercontent.com/1075592/127910397-bc201a45-403b-4e92-8cc1-f19ef58585f0.png

https://user-images.githubusercontent.com/1075592/127910580-0051a158-c33e-4fcc-aed6-e00323a7b045.png

**Comment by Craluminum2413** [comment]
Have no idea do I need to create another issue or not.
Very often I get snow like this
![2021-08-02_19-01-52](https://user-images.githubusercontent.com/69315569/127915352-774b905f-9bc4-475e-839d-ecf6766f3de1.png)

**Comment by tyronx** [comment]
Thanks for the report, some of these issues should be fixed next release

**Comment by Ziver7** [comment]
Getting a possibly related problem when looking at snowed on stairs. You can see straight down in the void, when peeking down on stairs.

![2021-08-09_17-28-33](https://user-images.githubusercontent.com/13258651/128790703-84de718b-f3b3-42d7-9ced-d7f7b7b9893e.png)

**Comment by Craluminum2413** [comment]
https://www.vintagestory.at/forums/topic/5466-stairs-with-snow-on-them-is-a-xray-glitch

**Comment by Ragolution** [comment]
This seems to also effect chiseled blocks which are placed under fences, which causes their top faces to become invisible

![image](https://user-images.githubusercontent.com/1075592/133931999-df5f4352-680d-4001-b6bf-6677021fa291.png)
![image](https://user-images.githubusercontent.com/1075592/133932003-4019ceb5-5aab-4bca-a934-449ee5365c59.png)

**Comment by radfast** [comment]
> Have no idea do I need to create another issue or not. Very often I get snow like this ![2021-08-02_19-01-52](https://user-images.githubusercontent.com/69315569/127915352-774b905f-9bc4-475e-839d-ecf6766f3de1.png)
> 
> All the mods I play with cannot influence it in any way, there are only vanilla blocks except that paved road near fence from BuildingPlus mod

This specific issue is now fixed in 1.16.4-rc#  It's a chunk boundary issue, connected with the game not re-drawing the neighbour chunk after doing a bulk update to the current chunk for snowfall (or snowmelt ... it's actually snowmelt which causes this issue seen here)

**Comment by radfast** [comment]
> Fixed for stairs only. Slabs still have this issue ![2021-05-29_21-54-32](https://user-images.githubusercontent.com/69315569/120081885-7abb0080-c0c8-11eb-83fb-a13d6af87ca0.png)

Now fixed for slabs as well, in 1.16.4-rc#
