### ISSUE TITLE
Can't play resonancearchive-2 and resonancearchive-4 at the echo chamber

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#914]
**Game Version:** 1.15.0-pre1
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Place an echo chamber
2. Put resonancearchive-2 or resonancearchive-4 at the echo chamber
3. Doesn't play

### Expected behavior
It plays

**Comment by Craluminum2413** [comment]
I edited ```\itemtypes\resonancearchive.json``` file and now they work
for 2: ```music/resonancearchives/through-the-grass-survive.ogg``` to ```music/through-the-grass-survive.ogg```
for 4: ```music/resonancearchives/winter.ogg``` to ```music/winter.ogg```

![image](https://user-images.githubusercontent.com/69315569/121398246-d35a8b00-c95d-11eb-9f3d-582024504d26.png)
![image](https://user-images.githubusercontent.com/69315569/121398288-dfdee380-c95d-11eb-9078-8433f28eee35.png)

**Comment by tyronx** [comment]
thanks this is now fixed for pre.7

**Comment by Craluminum2413** [comment]
Can't play resonancearchive-2 (`The Invention`), due to
> Tweak: Replaced winter resonance archive track with "The invention" track

**Comment by tyronx** [comment]
you probably mean resonancearchive-4. Thanks for letting me know, fixed, again 🤦‍♂️

**Comment by Craluminum2413** [comment]
Yes, sometimes I confuse with the names
