### ISSUE TITLE
Add more slots for bloomery inventory + recipes for colored glass making in primitive way

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#916]
Main uses:
- Ferroalloys
- Colored glass making (examples below, recipes do not claim to be absolutely realistic):
  - Crushed magnetite + Crushed quartz = Black glass
  - Crushed limonite/lead + Crushed quartz = Yellow glass
  - Crushed hematite + Crushed quartz = Brown glass
  - Crushed copper + Crushed quartz = Blue/green/red glass
  - Crushed sulfur+ Crushed quartz = Amber glass (maybe orange?)
  - Crushed nickel + Crushed quartz = Violet glass
  - Crushed manganese + Crushed colored glass = Non-colored glass (decolorized by manganese)

> https://www.thoughtco.com/the-chemistry-of-colored-glass-602252
> https://en.wikipedia.org/wiki/Glass_coloring_and_color_marking
> Wikipedia

**Comment by tels-git** [comment]
The bricklayers mod already implements glass color, colored glass smelting and glass-color-based glazings for ceramics in a process that based upon real-work processed and at the same time (hopefully) in the spirit of VS processes and gameplay:

https://mods.vintagestory.at/show/mod/329

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
