### ISSUE TITLE
Ability to smelt a work item to the amount of ingots that were originally used

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#917]

**Comment by sirStroam** [comment]
This has been marked as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

**Comment by Craluminum2413** [comment]
Could this be called a nuisance? 
![nuisance](https://user-images.githubusercontent.com/69315569/125001642-d24f7300-e05b-11eb-8c09-87442b564d9b.png)

**Comment by copygirl** [comment]
The people in charge of the issue tracker decide what's higher priority, and the wording on those tags isn't law. You can play the game just fine without ever needing to re-smelt work items. It would just be a nice thing to have. Hence: Suggestion.

**Comment by Craluminum2413** [comment]
How to melt work items?
