### ISSUE TITLE
Trader cart : floating wooden cubes

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#922]
**Game Version:** 1.15.0-pre1
**Platform:** Windows 
**Modded:** No 

### Description
Floating wooden cubes on a trader cart.

### How to reproduce
1. Generate world with seed 1791128181
2. Teleport to 990/115/10526

### Screenshots
![marchand](https://user-images.githubusercontent.com/84909583/120014867-dd39d100-bfe2-11eb-9110-7bd8ba51535b.jpg)

**Comment by Craluminum2413** [comment]
What the name of trader?

**Comment by copygirl** [comment]
I think the name of the trader is randomized. This might be an issue with chiseled blocks not being rotated or mirrored correctly with the cart when it is generated.

**Comment by Saricane** [comment]
Floyd the Artisan.

**Comment by Craluminum2413** [comment]
Okay, the trader's name is really useless in this case

**Comment by Craluminum2413** [comment]
Maybe it depends on which side of the world the trader's settlement is facing?

**Comment by Craluminum2413** [comment]
**Game version:** 1.15.0-pre.2
**World seed:** 1829935939
Trader's cart looks to north
/tp 198 118 33
![2021-06-04_22-45-04](https://user-images.githubusercontent.com/69315569/120854978-873acf80-c586-11eb-925e-c7b52230e52d.png)

**Comment by Saricane** [comment]
I have just found one which is on East/West alignment.

**Comment by Craluminum2413** [comment]
Game version: 1.15.0-pre.2
World seed: 1046419625
/tp -419 112 368
![2021-06-07_16-24-48](https://user-images.githubusercontent.com/69315569/121024503-f265eb00-c7ac-11eb-96eb-176e554fd944.png)

**Comment by Craluminum2413** [comment]
@Saricane I think you found another cart, different from what I found

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.4
> Fixed: Multiple issues with chiseled block rotations and snow covered chiseled block rotations when placed from schematics (e.g. trader carts)
