### ISSUE TITLE
Honey in Winter

### ISSUE THREAD

**Issue by DaSanko24** [anegostudios/VintageStory-Issues#924]
Not to make things harder on purpose, but I am thinking that perhaps bees and honey production is not supposed to be happening in the middle of winter.
As you can see on the screenshot, then there is plenty of action happening with the bees. And if set to a realistic environment, then during winter or at least cold times, bees would not be active, or harvestable.

I hope that you can use this as input.

Thank you in advance.

**Comment by DaSanko24** [comment]
So I am having issues showing the screenshot, never the less, honey production is happening during winter. Whether this is intended or not :)

**Comment by copygirl** [comment]
Looks like this has actually been added in [1.15.0-pre.1](https://info.vintagestory.at/v1dot15#pre1):

> Tweak: Bees no longer actively produce honey or fly around below 0°C. And timers reset below -10°
