### ISSUE TITLE
Make it so Tree Leaves die when there is no logs near them.

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#927]
Make it so Tree Leaves floating in the air die and disappear like in minecraft when there is no log near them or their not connected to the ground like bushes are.

removing logs in creative sometimes leaves behind a bunch of ugly floating tree leaves.

![vs tree bug - Copy](https://user-images.githubusercontent.com/11165643/120055011-7a0b6700-c001-11eb-9d27-2dd075e2be66.jpg)

**Comment by copygirl** [comment]
Is this an issue in creative, specifically? Leaves *should* disappear over time when the logs are removed.

**Comment by Craluminum2413** [comment]
Judging by my many hours of observation, only single leaves disappear

**Comment by tyronx** [comment]
Thanks for the report. Test this again in pre.7 please, I fixed some issues related to leaf decay there.
