### ISSUE TITLE
Make it so ingots can be removed from molds when hot using tongs / pincers

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#928]
In real life ingots can be removed from their molds when their still red hot and quenched in water to cool them off rapidly with tongs / pincers. 

Make it so Vintage Story ingots can be removed from molds when their hot using tongs / pincers so we don't have to wait for the mold to cool down completely before removing the ingot.

**Comment by Craluminum2413** [comment]
It would be even better if you had to use tongs/pincers for it

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
