### ISSUE TITLE
Infinite hay

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#929]
**Game Version:** 1.15.0-pre1
**Platform:** Windows 
**Modded:** No

### Description
Turning hay stack into dry grass still return 6 grass

### How to reproduce
1. Craft a hay stack with 4 dry grass (according to the new rules described in the handbook)
2. Put the resulting hay stack in the grid
3. You can get 6 dry grass (instead of 4)

### Expected behavior
Turn the hay stack into 4 dry grass instead of 6

### Screenshots
![hay1](https://user-images.githubusercontent.com/84909583/120059367-78698f80-c051-11eb-95c2-8d961172d60f.jpg)
![hay2](https://user-images.githubusercontent.com/84909583/120059369-7a335300-c051-11eb-8081-28dc154e2f26.jpg)

**Comment by copygirl** [comment]
Fixed in [1.15.0-pre.2](https://info.vintagestory.at/v1dot15#pre2):

> Tweak: Haybales now required 8 dry grass instead of 6
