### ISSUE TITLE
flowing water animation on ice

### ISSUE THREAD

**Issue by Carolusclen** [anegostudios/VintageStory-Issues#93]
So if there is ice blocks in the water there is no flowing animation on the side of the ice for the water.
however, if the water is 2 or more blocks deep, then the water animation shows on the side of the ice.

**Comment by tyronx** [comment]
Can you make a screenshot of that? I couldn't reproduce any oddities with water and ice

**Comment by tyronx** [comment]
ok should be fixed for 1.5.4
