### ISSUE TITLE
Custom Height Creative Worlds generate survival style terrain rather than superflat.

### ISSUE THREAD

**Issue by crustmonkey** [anegostudios/VintageStory-Issues#930]
**Game Version:** 1.14.8, 1.14.10, 1.15.0-pre.1
**Platform:** Windows 10
**Modded:** Nope

### Description
Starting a new creative single player world and customizing it with any height besides 256 results in realistic climate survival style world generation regardless of having chosen superflat.

### How to reproduce
Click "Single Player". click "Create New World", then "Creative Building", then "Customize".
On the "Customize" screen move the World Height Slider to anything other than 256. Leave the Climate Distribution as "superflat". Click "Apply" then "Create World". If applicable, hit Confirm after reading the world height warning. Observe that the new world is not flat at all.

### Expected behavior
Should be flat. I remember it used to work just fine regardless of world height. back before the seasons and food spoilage. It broke sometime around then I think.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.7
