### ISSUE TITLE
Placing Slope Test Block causes excessive render culling of landscape

### ISSUE THREAD

**Issue by crustmonkey** [anegostudios/VintageStory-Issues#932]
Game Version: 1.15.0-pre.1
Platform: Windows 10
Modded: No
Description
Placing the slope test block renders many nearby blocks invisible, causing visual "holes" in the terrain.

How to reproduce
Place slope test block. Pyramid block seems fine. I'm not sure if this is indicative of a problem with the slope test block itself or with the game's obj rendering. In case it's relevant, I'm running a gtx 1070, driver version 27.21.14.5671. I might try updating the driver tomorrow and seeing if the problem persists. If you need more info I go by "BreakfastTime" in the discord.

Screenshots
![2021-05-29_01-01-16](https://user-images.githubusercontent.com/38269731/120060221-1cd0df00-c01c-11eb-848c-de65dd8781b4.png)

**Comment by tyronx** [comment]
thanks for the report, this is now fixed for pre.7
