### ISSUE TITLE
Cornflower and woad flower have no texture in the planter

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#935]
**Game Version:** 1.15.0-pre.1, 1.15.0-pre.5
**Platform:** Windows
**Modded:** No

### Description
Cornflower has no texture in the planter

### How to reproduce
1. Place a planter
2. Put cornflower in the planter
3. Cornflower has no texture

### Expected behavior
Cornflower has texture

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/120072126-d40c3b00-c09a-11eb-9492-8eb5a9b40c1d.png)

**Comment by Craluminum2413** [comment]
Woad flower has no texture in the planter too

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.8

**Comment by copygirl** [comment]
> Fixed: Woad and cornflower invisible when placed in pots and planters

~ [1.15.0-pre.8](https://info.vintagestory.at/v1dot15#pre8)
