### ISSUE TITLE
Signs: wrong kind on vertical slabs and not popping when parent block destroyed

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#94]
1.5.2.6, official server

1. When sign is placed on a vertical slab , on the side which coincides with the block face, it is placed as a standing sign, not a label (plaque) sign. I would expect it to become of the label type. Behaves the same on wooden and cobble slabs
Btw, when a sign is placed on the back of stairs, wooden or cobble, it becomes a plaque type, which is expected
2. When the block on which sign is placed, is removed, sign don't popup. I thought it was only slabs/stairs issue, allowing floating signs of both kinds, but it works for all blocks.
Same with trapdoors.
Ladders seem to pop up as expected, like torches.
Idk if intended.
![2018-04-24_22-12-40](https://user-images.githubusercontent.com/25122345/39209455-769cb8b2-480e-11e8-8e36-efcc17666bd7.png)

**Comment by tyronx** [comment]
Ok, should be fixed for 1.5.3
