### ISSUE TITLE
Parts of anvil can be duped

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#940]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** StepUp

### Description
Will give you the same amount of anvil parts when destroying one anvil part placed from the stack.

### How to reproduce
1. Get the number of anvil parts (top or bottom) greater than or equal to three in one stack.
2. Place one anvil part from this stack
3. Break this anvil part
4. You get the same amount of anvil parts you have in stack

### Expected behavior
You only get one anvil part that you just broke

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/123006349-30275e00-d3c0-11eb-8260-03ba4379358a.mp4

**Comment by tyronx** [comment]
thank you for the report! this is now fixed for pre.7
