### ISSUE TITLE
trader generation bug

### ISSUE THREAD

**Issue by Kilz0** [anegostudios/VintageStory-Issues#941]
![image](https://user-images.githubusercontent.com/85085692/120125940-8256d400-c1b2-11eb-895c-15104cbfdb1c.png)
seed is: 755501265

**Comment by copygirl** [comment]
What is the game version?

**Comment by Kilz0** [comment]
> 
> 
> What is the game version?

1.14.10 (stable)
It won't generate the same thing , I tried creating a new world with same seed but the structures are randomly generated.

**Comment by Craluminum2413** [comment]
I guess it is fixed in 1.15.0-pre.4
> Fixed: Ruins and other surface structures sometimes generating floating or inside blocks

**Comment by copygirl** [comment]
Might as well assume this is fixed until reported otherwise.
