### ISSUE TITLE
Fruit pie : last part does not replenish satiety

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#942]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
When you eat a pie, the last part (out of 4) does not replenish satiety.

### How to reproduce
1. Make a pie
2. Cut it, eat the 3 first parts. Everything is ok.
3. Later, eat the last part, cry, and prepare another pie because you're still hungry :-)

### Screenshots

![pie](https://user-images.githubusercontent.com/84909583/120213987-26cd2a80-c234-11eb-8024-d3cd5a0ffccc.jpg)

**Comment by Craluminum2413** [comment]
How do you even eat them? I can't eat them, I always just pick them up

**Comment by copygirl** [comment]
Sneak and right click, like with placed bowls, would be my guess.

**Comment by Craluminum2413** [comment]
Sneak + RMB does the same thing as RMB for me, when I interact with pie slices, I just pick up it

**Comment by Saricane** [comment]
I don't remember (often doing this by "muscle memory"), and as a nomad, I'm not currently in situation to produce another one to test. I'll try again asap :-)

**Comment by Craluminum2413** [comment]
I only know that I can't eat pie slices

**Comment by Saricane** [comment]
In creative or survival mode, or both ?

**Comment by Craluminum2413** [comment]
Both

**Comment by Saricane** [comment]
Oh, I remember, you must have a knife in hand.

**Comment by Craluminum2413** [comment]
Seems fixed in 1.15.0-pre.4
> Fixed: Multiple issues with pies

**Comment by Saricane** [comment]
> Fixed: Various issues with pies (missing mixed meat texture, unfinished pies were bakeable with a broken model, incorrect nutrition calculation)

Still there in pre9.

**Comment by copygirl** [comment]
Ah. I was hoping @Craluminum2413 checked if it was fixed. You're saying it still doesn't replenish food?

**Comment by Saricane** [comment]
Yes, tested on a 1 fruit pineapple pie, with pre9.

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/123625341-5877e800-d818-11eb-9ed3-b91a3c2f8934.mp4

**Comment by Craluminum2413** [comment]
Rename issue to "The last pie part picked up with hand doesn't replenish satiety"
https://user-images.githubusercontent.com/69315569/123626197-3c287b00-d819-11eb-99a0-955e9bcbf280.mp4

**Comment by Craluminum2413** [comment]
### How to reproduce
1. Make a pie, bake it
2. Cut three pieces with knife, pick up fourth piece with hand
3. You got 3 pieces (0.25 sat) and 1 piece (0 sat)

https://user-images.githubusercontent.com/69315569/124382901-67f0a880-dcd2-11eb-9372-7c7e9eaf8f61.mp4

**Comment by Craluminum2413** [comment]
I think this title fits better - "The fourth piece of pie picked up by hand has 0 saturation"

**Comment by Craluminum2413** [comment]
Fixed in [1.15.0 (Stable)](https://www.vintagestory.at/blog.html/news/the-homesteading-update-v1150-r287/):
> Fixed: Picking up last slice of pie gave you a slice with 0 servings

https://user-images.githubusercontent.com/69315569/125944634-f87a15b2-0458-4048-8756-a06e13f7453b.mp4
