### ISSUE TITLE
Crash when stacking items

### ISSUE THREAD

**Issue by Shuro** [anegostudios/VintageStory-Issues#945]
**Game Version:** 1.15-pre2
**Platform:** Windows 
**Modded:** No 
**Other Notes:**
* happened on multiplayer-server
* Other players / server not affected

### Description
A friend had a crash without error window after stacking lots of planks on the ground. Not sure what kind of race condition triggered it.

### How to reproduce
1. Craft Pinewood planks
2. Stack them on the ground
3. ???
4. Crash

### Logs
```
Sadly no error window or error in logs.
```

**Comment by Craluminum2413** [comment]
It cannot be related to just one type of board. I tried to reproduce this but got nothing
![Uploading 2021-06-01_04-53-33.png…]()

**Comment by Craluminum2413** [comment]
Hooray, I reproduced the bug and it crashed. You need to stack boards more than three 48+48+48

**Comment by Craluminum2413** [comment]
Tried to stack clay bricks in the same conditions, crashed too

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/120798431-0360f300-c546-11eb-9706-012ce0cab956.png)

**Comment by Craluminum2413** [comment]
Since the clay bricks have the higher wrong collision, you need to jump over clay brick pile and continue stack them under yourself, without jumping (it's important!). Will crash

**Comment by Craluminum2413** [comment]
Metal plates cause crash too

**Comment by tyronx** [comment]
thanks, fixed for pre.7
