### ISSUE TITLE
Specified piles have wrong hitbox

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#947]
**Game Version:** 1.15.0-pre.4
**Platform:** Windows
**Modded:** StepUp

### Description
Piles that have wrong hitbox
- Board pile
- Metal plate pile

### Videos

https://user-images.githubusercontent.com/69315569/122677694-133a3180-d1ec-11eb-8567-244015b6a44a.mp4

**Comment by Craluminum2413** [comment]
Fixed for clay brick piles only. Not fixed: metal plate pile, board pile

**Comment by tyronx** [comment]
thanks, fixed for pre.7
