### ISSUE TITLE
New log types cannot be used as fuel

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#948]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No 

### Description
Bald cypress log can't burn in a firepit. Must be turned into firewood first.

### Expected behavior
Unless this new kind of wood is very special, it should burn like any other log.

### Screenshots
![cypress](https://user-images.githubusercontent.com/84909583/120386035-66753e80-c328-11eb-9825-3b4826c20dec.jpg)

**Comment by Craluminum2413** [comment]
Larch, ebony, walnut, purpleheart too. Maybe change issue name to "Logs of new trees have missing combustiblePropsByType"?

**Comment by Craluminum2413** [comment]
Also they cannot be used to craft leaded glass panes

**Comment by tyronx** [comment]
thanks for the report, both of these issues should be fixed in pre.7
