### ISSUE TITLE
Stuttering movement

### ISSUE THREAD

**Issue by CYblK4** [anegostudios/VintageStory-Issues#949]
**Game Version:** All versions after 1.12.14 (I did not test every version after that, but I did test many, including the latest 1.15.0-pre.2)
**Platform:** Windows
**Modded:** No

### Description
Movement alternates between a larger and smaller step each frame, producing stuttering movement.

### How to reproduce
Move in any direction.

### Expected behavior
Movement should remain constant every frame as long as you aren't accelerating/decelerating.

### Video Clips
https://imgur.com/a/KF29OXG
Comparison between 1.14.10 and 1.12.14. Recorded at 120 fps, played back at 2 fps

**Comment by copygirl** [comment]
Could this be micro-stutters causing the frame times to be different lengths? Is this noticeable in normal gameplay?

**Comment by CYblK4** [comment]
It's noticeable in normal gameplay. I just tested 1.12.14, 1.13.0 and 1.15.0-pre.2 with the frame time graph open. Fps is capped at 120. All versions have tiny frame time spikes when a movement key is held, but visually movement remains smooth in 1.12.14.

**Comment by Craluminum2413** [comment]
Can be related to #1133

**Comment by CYblK4** [comment]
I just booted up 1.18.1 stable to test and found that the movement no longer stutters.
