### ISSUE TITLE
recipe wild card replacer doesn't work with two wild cards

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#95]
`{
    ingredientPattern: "L,S",
    ingredients: {
        "L": { type: "item", code: "game:stone-*", name: "rock", quantity: 4, allowedVariants: ["andesite", "chalk", "claystone", "granite", "sandstone", "shale", "basalt"] },
        "S": { type: "block", code: "game:sand-*", name: "type" }
    },
    width: 1,
    height: 2,
    output: { type: "block", code: "softroad-sand-{type}-{rock}-east", quantity: 1 }
}`

In this recipe, the game replaces both `{type}` and `{rock}` with the same name and doesn't cover all combinations like `softroad-sand-sandstone-andesite-east`.

example:
[test.zip](https://github.com/anegostudios/VintageStory-Issues/files/1956304/test.zip)

**Comment by tyronx** [comment]
added in 1.7
