### ISSUE TITLE
Impossible to place crucible with molten metal inside

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#950]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** StepUp

### How to reproduce
1. Melt any metal in a crucible
2. Place the crucible on the ground with Shift + RMB
3. It's not possible to place crucible

### Expected behavior
You placed crucible

**Comment by tyronx** [comment]
Thanks for the report. This will be fixed in v1.15.3, albeit loose the ability to emit smoke particles when its hot. I'd like to re-add this part in 1.16
