### ISSUE TITLE
Fallen leaves texture glitches

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#951]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** StepUp

### Description
The texture of fallen leaves blinks strangely if you turn the camera while looking at them

### How to reproduce
1. Place a fallen leaves
2. Move the player's camera
3. The texture is blinking

### Expected behavior
Texture should look the same as it was in 1.15.0-pre1

### Screenshots
![ezgif com-gif-maker](https://user-images.githubusercontent.com/69315569/120516293-dbec1800-c3d7-11eb-9a1c-f8b8e69cfcf1.gif)

**Comment by Craluminum2413** [comment]
Invisible in 1.15.0-pre.3

**Comment by tyronx** [comment]
Thanks for the report, this will by fixed in pre.7, simply by disabling this block type - we will implement it properly in the future
