### ISSUE TITLE
Cooking pot and crucible have bad stack size

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#955]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
'8 cooking pots' / '4 crucibles' in the firepit give you one 'cooking pot with meal' / 'crucible with metal'

### How to reproduce
1. Place firepit and refuel it
2. Put 8 cooking pots / 4 crucibles to the firepit
3. Put any food inside, for example, 1+1 meat / metal (for crucible)
4. Ignite and wait to end of the process
5. It will give you 1 cooking pot / crucible, 7 cooking pots / 3 crucibles just disappeared

### Expected behavior
One cooking pot / crucible in the output, rest in the input

### Gifs
![2021-06-08 23-04-27](https://user-images.githubusercontent.com/69315569/121251167-3fca8100-c8af-11eb-8517-7c6d0c842ee6.gif)
![2021-06-08 23-04-06](https://user-images.githubusercontent.com/69315569/121251172-40fbae00-c8af-11eb-9172-47c4d5b54204.gif)

**Comment by tyronx** [comment]
thanks for the report, this should already be fixed in the current pre.6
