### ISSUE TITLE
Missing trader (empty cart)

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#957]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
Found a cart without trader. He (or she) is not in the cart, not around, nowhere. I tried to 

- wait a few hours
- sleep in the bed
- CTRL-F1
- quit and restart game
- load the map with v1.14.10

No way to make him appear.

### How to reproduce
1. Generate the following world --> width=heigth=512k, seed 1791128181
2. Teleport to 839/115/71765 (this may take a while in a newly generated world)
I tried to do this test, it works.

**Comment by Craluminum2413** [comment]
![2021-06-04_18-13-56](https://user-images.githubusercontent.com/69315569/120824064-bdfdef00-c560-11eb-9fb3-50bb7bffb5ef.png)

**Comment by Saricane** [comment]
Good job. And did you encountered the trader ? it seems not. I only see a weird blue square.

**Comment by Craluminum2413** [comment]
This blue block is Meta (Spawner)
