### ISSUE TITLE
How to enable real fullscreen?

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#958]
I would like to enable fullscreen, where I can minimize the game by just pressing Win, without pressing F11 a lot of times. Almost all games what I play (e.g. WarThunder) have three options: "Fullscreen, Fullscreen window, Window". This game has only two options, "WIndow" and "Fullscreen window", but no real fullscreen.

**Comment by Craluminum2413** [comment]
Judging by the new changes, will this also be considered a suggestion?

**Comment by sirStroam** [comment]
Yes this is a suggestion and we are no longer accepting suggestions on the issues tracker.

**Comment by Craluminum2413** [comment]
In this case, Fullscreen is misleading, because game doesn't have Fullscreen

**Comment by copygirl** [comment]
"Fullscreen window" or "windowed fullscreen" are common terms for this type of pseudo fullscreen.

**Comment by Craluminum2413** [comment]
It would be nice to have a third option anyway, as in many games
