### ISSUE TITLE
Agriculture trader doesn't sell seeds

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#959]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** StepUp

### Description
Agriculture trader doesn't sell seeds. No seeds in the trader-foods.json file

### How to reproduce
1. Open "survival\entities\humanoid\trader-foods.json" file
2. Search for seeds
3. There are no seeds

### Expected behavior
Sells seeds

**Comment by copygirl** [comment]
I was confused for a moment but you're right, the changelog does say they're supposed to sell seeds:

> Tweak: Renamed foods trader to agriculture trader. Now also sells seeds.

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.5
> The foods trader now sells seeds, cheese and soil
