### ISSUE TITLE
prospecting works with loose stones

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#96]
By placing stones down you can break them with the prospecting pick to get readings.

**Comment by tyronx** [comment]
It's kinda intentional to prospect on loose stones, but it should not be prospectable with placed ones. The plan is to use one of the 5 free block bits to hold a natrually generated 1/0 flag and test against that

**Comment by tyronx** [comment]
Decided to remove prospecting with loose stones for now.

**Comment by copygirl** [comment]
Nnnooooouu~!

**Comment by tyronx** [comment]
If its any consolation - prospecting also needs one sample less now

**Comment by Heptagon-ru** [comment]
Actually I have the same feelings as copygirl :D I just recently heard about this trick and havent even try it widely.
