### ISSUE TITLE
Trader cart : broken ladder

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#960]
**Game Version:** 1.15.0-pre2
**Platform:** Windows 
**Modded:** No

### Description
The ladder of the cart breaks itself as soon as I try to climb. This is the second time I find such a bug.
The ladder parts then lays on the ground.
Moreover, when the ladder breaks, another ladder appears on the side of the cart.

### How to reproduce
1. Generate the following world --> width=heigth=512k, seed 1791128181
2. Teleport to the coordinates on the screenshot.

### Expected behavior
Some stronger ladders :-)

### Screenshots
![cart](https://user-images.githubusercontent.com/84909583/120856130-a7b35b80-c57f-11eb-9ac5-119d634f25b7.jpg)

**Comment by copygirl** [comment]
Related to #922?

Was the ladder floating? It's strange that the side ladders "appears" after the front one pops off though. Are you sure about that?

**Comment by Saricane** [comment]
No, it's not related to #922. The ladder was correctly placed.
But I regenerated the same world to do the test again.

1) You're right, the ladder on the side did not spawned, it was already there. My bad, I was persuated it spawned under my eyes. 
2) At the second try, the ladder did not dissapear ! But **if I cut the grass just below the ladder,  it breaks the ladder too**. That's not logical.
3) In the meantime, I just found another cart with exactly the same configuration (two steps of ladder with the bottom not touching the ground) and this time, even if I cut the grass below it, the ladder  remains untouched.

All that sounds strange, because I'm absolutely sure the first time I visited this trader, I did nothing else than trying to climb the ladder (I never cut grass around to make an offering to the trader first 😃 )

**Comment by copygirl** [comment]
Hmm I see. It doesn't look like the ladder actually has any full support by the cart structure in this case. Only if it happens to be spawned on solid ground. It would need solid side of a block to attach to, such as a full wood block or the correct side of a stair.

**Comment by Craluminum2413** [comment]
Seems fixed in 1.15.0-pre.3?
> Fixed: Trader JSONs updated for remapped door and ladder codes

**Comment by copygirl** [comment]
That sounds like the ladders were remapped but doesn't mention changed behavior..? I would like to see this one confirmed fixed by spawning / finding these traders and taking out the ground beneath (if they didn't spawn that way) to see if the ladders still pop off.

**Comment by Saricane** [comment]
I tried to generate this map again with pre4, but this map was generatd with pre1, and it seems that modifications have been made on the worldgen since. So, at the same place, no more trader. Can't repeat the test. Sorry.

**Comment by tyronx** [comment]
Thanks for the report, this is now fixed by allowing ladders to be attached to half slabs
