### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#961]
Not fixed:
![image](https://user-images.githubusercontent.com/69315569/121383874-73111c80-c950-11eb-9c94-e6f2b09543b1.png)

Fixed:
#693 
![2021-06-04_23-13](https://user-images.githubusercontent.com/69315569/120858074-e864a200-c58a-11eb-83e5-126372652172.png)
![image](https://user-images.githubusercontent.com/69315569/122221430-f0411200-ceb9-11eb-8781-f245f3bc68bc.png)

**Comment by Craluminum2413** [comment]
#693

**Comment by Craluminum2413** [comment]
![image](https://user-images.githubusercontent.com/69315569/122221430-f0411200-ceb9-11eb-8781-f245f3bc68bc.png)

**Comment by Craluminum2413** [comment]
Russian translation, should be "Бесконечно"
![image](https://user-images.githubusercontent.com/69315569/126877247-30e0abed-090f-4dbd-bc2f-6def2db126d5.png)

**Comment by explorerbeer** [comment]
I also want to add a Russian translation error. Instead of "Один день до начала появления монстров", writes "ОдинЬ день до начала появления монстров". The soft sign at the end is not needed.

**Comment by copygirl** [comment]
Do note that non-English localizations are powered by the community. You can suggest changes [here](https://crowdin.com/project/vintage-story-game).

**Comment by Craluminum2413** [comment]
Rhodochrosite ore sometimes translated as manganese, should be only rhodochrosite or only manganese

**Comment by Craluminum2413** [comment]
Bald cypress crate
![image](https://user-images.githubusercontent.com/69315569/148710115-620e4e91-9676-4880-8d36-f5048be3e643.png)

**Comment by Craluminum2413** [comment]
All fixed except Tier1 etc. but I close it as resolved
