### ISSUE TITLE
Add two shelves

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#963]
Values: shelvable for small, shelvableMedium for medium, shelvableLarge for large

The small one is already in the game.
The medium shelf (two slots) would look like two horizontal slabs placed on top of each other (maybe use it for cooking pots?)
The large shelf (one slot) would look like whole block shelf for one large item, like anvil mold, bucket etc.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
