### ISSUE TITLE
Hover over the search box

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#964]
Make search box focus when you hover over the search box (handbook, creative inventory), and when you don't hover over the search / move the cursor away from the search box (when you hover over items icons), it becomes "inactive". Anyway you can add it only when you hovering over items, because you can press CTRL + F to switch directly to the search box

**Comment by copygirl** [comment]
The word for this is "focus", I believe. Removing the focus from the search bar simply because you are moving the mouse away would be very confusing. (Especially when your mouse typically moves a little when you take your hand off it to start typing.)

**Comment by Craluminum2413** [comment]
How do you deal with this then? I would like to immediately switch to getting items from creative inventory without extra clicks (Since you cannot take a whole stack while you are in the search field)

**Comment by copygirl** [comment]
A shortcut, or automatically focusing the search bar when opening the creative window, would help. Perhaps pressing backspace could re-focus it right away as well. Not getting whole stacks while the search bar is focused sounds like an issue.

**Comment by Craluminum2413** [comment]
I can get the whole stacks with MMB, but can't with Shift

**Comment by Craluminum2413** [comment]
I found a solution, you can simple press Tab to defocus the search box. But it would still be nice if you had to press Esc twice (to defocus, then to close)

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
