### ISSUE TITLE
Pineapple and Rice : eternal growing ?

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#966]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
Disclaimer : I don't know if this is a bug, just a strong feeling.
Since I play with v1.15, and despite having covered huge ground (playing as a nomad), I have never seen a mature wild rice nor a mature pineapple. I found dozens of pineapple plants, often grouped by 2,3,4 or 5, but always in different growing states, never harvestable. Statistically, I doubt this is normal. Same for wild rice.
Other new plants (cassava, amaranth, peanuts) are fine. So ...

### Screenshots
![pineapple](https://user-images.githubusercontent.com/84909583/120903618-71411380-c647-11eb-94f5-011e7db98d0d.jpg)

**Comment by copygirl** [comment]
I've seen talks around changes to crop growth and such so they are related to the time of the year or so, particularly with pineapples. I'm not sure if that's already been implemented and how finished the implementation is.

**Comment by Craluminum2413** [comment]
This happened to me in 1.14 versions with vanilla and modded crops

**Comment by Saricane** [comment]
Ok, but I have been roaming on this map for nearly a year now, so I should have encountered at least one juicy pineapple, no ?

**Comment by copygirl** [comment]
Wild crops only grow in chunks that are loaded around the player, and do so very slowly. Maybe that's why you haven't found one?

**Comment by tyronx** [comment]
Thanks for the report. This was by design, but now as you mention it, not good design. Hot weather crop will now also spawn in their ripe stages from pre.7 onwards.
