### ISSUE TITLE
change json entity drops to include item pools

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#97]
right now there's no way to define a pool of objects to drop from. Maybe something like. 

```js
drops: [
		{
			type: "item", 
			code: "meat-raw", 
			quantity: { avg: 4.5, var: 1.5 } 
			chance: .5  //gives it a 50% to drop anything
		},
		{
			type: "itempool1", 
			quantity: { avg: 1, var: 0 } //how many different items from the pool. In this case it always picks just one.
			chance: .1 //gives it a 10% chance to drop anything
		},
		{
			type: "item", 
			code: "fat", 
			quantity: { avg: 0.75, var: 0 } 
			chance: .2
		}
	],
ItemPool1: [
		{
			type: "item", 
			code: "pelt grey", 
			quantity: { avg: 4.5, var: 1.5 } 
			weight: 5 //gives it a 5/(5+2+2) chance of being picked
		},
		{
			type: "item", 
			code: "pelt white", 
			quantity: { avg: 1.25, var: 0 } 
			weight: 2
		},
		{
			type: "item", 
			code: "pelt black", 
			quantity: { avg: 0.75, var: 0 } 
			weight: 2
		}
	],
```

Could be in the same entity json file or maybe it'd be better if the drop pool was it's own json that was referenced from the entity json.

**Comment by tyronx** [comment]
I think it should probably look more like that random shapes/textures syntax where you define an array of `alternates` for each drop. Also easier to code than referencing other lists

**Comment by sirStroam** [comment]
You are probably right. As long as it can be done from the json and covers weights and chance I don't care about the syntax.

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
