### ISSUE TITLE
You can heat blister steel in a crucible

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#972]
**Game Version:** 1.14.10
**Platform:** Windows
**Modded:** No

### Description
You can heat blister steel in a crucible, while other iron+ tier metals you can only heat in a forge.

### How to reproduce
1. Grab a stack of blister steel.
2. Add in a crucible
3. Add 1 coal and light up the firepit.
4. Wait for it to reach 1000-1100 C.
5. Remove the blister steel and work it in a helvehammer.

### Expected behavior
Blister steel should be only heatable in a forge, same way as iron / meteoric iron / steel.

**Comment by Craluminum2413** [comment]
You can also heat any ingots in this way using peat

**Comment by Zaldaryon** [comment]
I know I can do this with peat. The *issue* is it shouldn't be allowed with blister steel since iron and meteoric iron and steel, you can't.

**Comment by Craluminum2413** [comment]
I think would be nice to have something like "IsMeltableInCrucible"

**Comment by Craluminum2413** [comment]
If I am not mistaken, it was fixed in 1.15.0-pre.4
![image](https://user-images.githubusercontent.com/69315569/122639640-93389c80-d103-11eb-94cb-35a950c901db.png)

**Comment by Craluminum2413** [comment]
Close issue? Now it is definitely impossible to put ingots in the crucible

**Comment by copygirl** [comment]
Ah yes, missed closing it. Thank you.
