### ISSUE TITLE
No stone icon in block interaction help for placed stones

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#974]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
"Pick up" for stones has no stone icon, although the rest of the tips have

### How to reproduce
1. Toggle "Show block interaction help"
2. Place any stone
3. It has no stone icon in "Pick up"

### Screenshots
![2021-06-07_16-46](https://user-images.githubusercontent.com/69315569/121027811-efb8c500-c7af-11eb-97c9-da398b154d2e.png)

**Comment by copygirl** [comment]
The empty rectangle means "empty hand" - as in you are meant to have an empty hand and right click to pick up the stone.

This is intended.
