### ISSUE TITLE
Fruit pie : mangled crust

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#978]
**Game Version:** 1.15.0-pre3
**Platform:** Windows
**Modded:** No

### Description
When you cut the first part of a pie, the crust of the second part dissapears. Tested with 2 different pies.

### Screenshots
![pie](https://user-images.githubusercontent.com/84909583/121431386-9e5c3180-c979-11eb-9236-8f1db9261758.jpg)

**Comment by Craluminum2413** [comment]
Only variant 1 has this error, while variants 2 (lattice) and 3 (diagonal lattice) don't

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/122221791-4e6df500-ceba-11eb-820a-6c71b0e5ee15.mp4

**Comment by Craluminum2413** [comment]
Fixed in 1.15.0-pre.4
