### ISSUE TITLE
Inconsistency: knapping flint vs all other stones

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#98]
I was trying to knap stone but kept placing it down and it made the stone block instead of the knapping grid like it does with flint. It was confusing me for a second until I clicked the placed stone with stone in hand a second time. I would either have flint act as all stone does or have stones act as flint does.

**Comment by milochristiansen** [comment]
I'm not sure this is worth "fixing", but if it is, making flint work like the other stones would be my preference. Losing the ability to place decorative stones would be too much price to pay for such a minor gain.

(It would be cool if you could place ore nuggets as well)

**Comment by tyronx** [comment]
yea dunno how to fix that without loosing the ability to place stones

**Comment by sirStroam** [comment]
add placeable flint stones?

**Comment by milochristiansen** [comment]
That is harder than it sounds. How will you decide which visual variant to use?

**Comment by sirStroam** [comment]
Make a new one or use the same model and color all of it like Flint.

**Comment by Craluminum2413** [comment]
Why not add "F" menu for stones to switch between throwable and knappable?

**Comment by sirStroam** [comment]
No longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
