### ISSUE TITLE
Cutting a small oak surrounded by giant ones

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#984]
**Game Version:** 1.15.0-pre3
**Platform:** Windows 
**Modded:** No 

### Description
When I cut a small oak (4 logs) closely surrounded by giant ones, the cutting time is way too long, and does not match the size of the tree (even with an iron axe). And when the cut is finally finished, all the giant oaks surrounding the little one lose almost all their foliage.
It's the second time I encouter this bug, but this time, I can give the coordinates to reproduce the action.

### How to reproduce
1. Generate a world with the following parameters : width=height = 512k, seed = 1791128181
2. /tp to -24,131,74468
3. Chop the small oak surrounded by the giant ones

### Screenshots
![oak](https://user-images.githubusercontent.com/84909583/121581643-58ad7080-ca2e-11eb-8968-d7061ec6a96d.jpg)

**Comment by Saricane** [comment]
> 
> 
> This is intentional

Are you sure about that ? Such a behaviour has absolutely no sense.

**Comment by Craluminum2413** [comment]
Why? It makes no difference for the axe how much foliage is on top, this is programmed to break absolutely all the wood and foliage available from above. Because for an axe it's one tree. If the trees here were like in Dynamic Trees MC mod, it would be much simpler and there would be no such "inconvenience"

**Comment by Saricane** [comment]
In such a case, I should harvest a number of logs corresponding to the time spent hitting the small trunk. But no, I only get the 4 logs of the small oak. And the giant oaks don't lose logs, only leaves. Moreover, the leaves that dissapears are not only "above" the small oak, but belong to a wider area, including the 3 giant oaks. So, I still believe there should be something to tweak.

**Comment by copygirl** [comment]
There might be an issue if it indeed cut the leaves without also cutting the logs of the bigger trees. I don't think it should have cut the smaller tree. Perhaps the tree cutting code checks for leaves connectivity separately from log connectivity?

Though do keep in mind that the game doesn't store information on which leaves and log blocks belong to which "tree", so there is no way for it to truly "make sense" at this time. Not until trees and logging are overhauled.

**Comment by copygirl** [comment]
> I thought the same seed would generate the same world to the exact small piece of grass.

Yeah it probably depends on which order the chunks are generated. It's also possible there is a random number generator that's tied to things other than just the current chunk that's currently being generated.
