### ISSUE TITLE
Ladders interchange each other

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#989]
**Game Version:** 1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### Description
Ladders interchange each other when vertically placed. For example, if rope ladder is placed, then next wooden ladder above or below will be changed to rope ladder, and vice versa.

### How to reproduce
1. Place a rope / wooden ladder
2. Place a wooden / rope ladder above or below
3. A wooden / rope ladder replaced with a rope / wooden ladder when placing

### Videos

https://user-images.githubusercontent.com/69315569/121772240-e4cdae00-cb7c-11eb-9533-017cad9cb2c7.mp4

**Comment by tyronx** [comment]
thanks for the report, this will be fixed in pre.7
