### ISSUE TITLE
Clay oven : no need to bake it

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#993]
**Game Version:** 1.15.0-pre3
**Platform:** Windows
**Modded:** No

### Description
2 methods to build a clay oven . By assembling fire bricks, or by clay forming. But unlike every other clay item, the oven build by clay forming is directly usable, without baking it first.

### How to reproduce
1. Take fire clay
2. Build a clay oven by forming clay voxels
3. You get a fully usable oven.

### Expected behavior
It would be logical to bake it first, like any other clay product

**Comment by Craluminum2413** [comment]
I find clay oven recipe **very unbalanced** and I think it's better to change it to

![image](https://user-images.githubusercontent.com/69315569/121787421-a1039480-cbce-11eb-8443-b04828603e90.png)

Because to make the clay oven with clay forming you need to spend about 69 raw fireclay, this is a huge amount of fireclay. But for recipe in crafting grid you need just 5 fireclay bricks

**Comment by tyronx** [comment]
grid recipe was a placeholder, its removed now

**Comment by Craluminum2413** [comment]
It is in progress I think, not resolved?

**Comment by copygirl** [comment]
From what I understand the clay oven is fired as it's used. I think I forgot to close this issue.

**Comment by Craluminum2413** [comment]
As you see, there is no way to bake it
![image](https://user-images.githubusercontent.com/69315569/122690437-430c2800-d232-11eb-8ffc-58edce562196.png)

**Comment by copygirl** [comment]
Doesn't it say it in the "Usage" section?

**Comment by Craluminum2413** [comment]
This is for baking items, not for baking the oven itself. But it's better to ask the developers

**Comment by tyronx** [comment]
We are still undecided about it. Perhaps the player will need to dry it 1-3 days or fire it once.

**Comment by Saricane** [comment]
The handbook says that the oven is build by clay forming, and the page for clay forming says that it must then be baked. If you decide there is no need to bake it, the handbook wil have to be updated to match this choice.
