### ISSUE TITLE
Pie after storage : instant spoiled

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#994]
**Game Version:** 1.15.0-pre3
**Platform:** Windows
**Modded:** No

### Description
A pie which has been stored in a vessel+cellar for days get instantly spoiled when put in the inventory. Despite what is written when you open the vessel.

### How to reproduce
1. Make a pie
2. Store it in a vessel, until it is given as something like "fresh for 4 days left".
3. Put it in your hand, it is 100% spoiled.

### Expected behavior
When you put the pie in your hand, it should have the same time left as when it is in the vessel.

### Screenshots
![pie1](https://user-images.githubusercontent.com/84909583/121803028-ddbba400-cc3f-11eb-85c1-bd328d1e714a.jpg)
![pie2](https://user-images.githubusercontent.com/84909583/121803030-de543a80-cc3f-11eb-8ef2-04471add59d1.jpg)

**Comment by Craluminum2413** [comment]
It shouldn't have the same time left as when it is in the vessel, any food in hand will immediately become much worse stored, than in a container, since there are different rates of decay

**Comment by Saricane** [comment]
Once in your hand, the pie should start with the same "fresh time" as in the vessel, even if, of course, it will then decay way faster than in the storage. If not, how could you manage the content of all your different foods in your vessels. You'd never know if a food is already rotten.

**Comment by Craluminum2413** [comment]
Well, pies have a little problems. They don't even write when they will rot, if placed. When white and black are mixed, the filling is red. And etc.

**Comment by Saricane** [comment]
Yes, but when all those little problems will be fixed, pies will remain an interesting food, thanks to the satiety reward comparing to the raw ingredients.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in pre.5
