### ISSUE TITLE
Bronze armlet : make them meltable

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#995]
When panning, you often find bronze armlets. Problem, no trader seems to accept them and you can't melt them.
We should be able to melt them in the crucible to get 1 bronze ingot.

**Comment by Craluminum2413** [comment]
Would be nice to make the tool heads meltable too

**Comment by Saricane** [comment]
> 
> 
> Would be nice to make the tool heads meltable too

Hmm, how to deal with durability ? It would not be fair to be able to melt a tool once it's durability is close to zero. May be you would have to put several old tools in your crucible (same alloy, of course), and the game would compute how much ingots you can expect, then  round the result to the lower integer.
For example, if the result is less than 1 ingot, you can't melt. For 1,7 ingot, you get 1 ingot, and so on.

**Comment by Craluminum2413** [comment]
Tool heads aren't the same as tools
![image](https://user-images.githubusercontent.com/69315569/121805496-29784880-cc54-11eb-8569-66bb256e5dcf.png)

**Comment by Saricane** [comment]
Oh yes, you were talking about brand new heads. I see. Well, why not, you're right.

**Comment by Craluminum2413** [comment]
And for tools, you can come up with a superb formula:
### Durability:
```
90-99% = 90 units
80-89% = 80 units
70-79 = 70 units
60-69 = 60 units
50-59 = 50 units
40-49 = 40 units
30-39 = 30 units
20-29 = 20 units
10-19 = 10 units
```
Yes, you lose some percentage, but it's better than nothing.

I would also very much like halves of ingots, that is, 1/4 is 25/100, and 1/10 is 10/100 and etc.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
