### ISSUE TITLE
Ladder placement in corner wall

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#998]
**Game Version:** 1.15.0-pre3
**Platform:** Windows
**Modded:** No 

### Description
Depending on the position of the player, ladders can be placed in the wrong face of a corner wall. Seems specific with ladders (Ok with wild vines, for example)

### How to reproduce
1. Stand in a corner wall, but no so close of one of the two walls (like on screenshots 1 and 2).
2. Place a ladder (wood or rope) on the left wall.
3. The ladder is well placed.
4. Now get closer to the left wall (like on screenshots 3 and 4)
5. Place a ladder on the left wall.
6. The ladder is sticked to the wrong face of the wall.

### Expected behavior
The ladder should always be placed on the face matching the hitbox chosen. Seems specific with ladders (Ok with wild vines, for example)

### Screenshots
Placement OK.
![lad3](https://user-images.githubusercontent.com/84909583/121815371-71a86280-cc76-11eb-9044-65d4aa57d28e.jpg)
![lad4](https://user-images.githubusercontent.com/84909583/121815373-7240f900-cc76-11eb-837a-9c70b7f3bf75.jpg)

Wrong placement.
![lad1](https://user-images.githubusercontent.com/84909583/121815396-96043f00-cc76-11eb-963f-a5151dc0ec49.jpg)
![lad2](https://user-images.githubusercontent.com/84909583/121815397-969cd580-cc76-11eb-95ee-d4519a5ceca5.jpg)

**Comment by copygirl** [comment]
Looks like the placement is based on the player's orientation. Might be intentional, but I'll obviously leave it up for the devs to make a clear statement.

**Comment by tyronx** [comment]
Looks unintuitive. Will now use the looked at face instead. Will be in pre.4
