### ISSUE TITLE
Baking pie causes NullReferenceException

### ISSUE THREAD

**Issue by astynax777** [anegostudios/VintageStory-Issues#999]
**Game Version:** v1.15pre3
**Platform:** Windows
**Modded:** No

### Description
Playing multiplayer with about 4-5 players.  Player was baking pie in the oven and froze/crashed the server

### Logs
```
13.6.2021 11:56:05 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.CarryOverFreshness(ICoreAPI api, ItemSlot[] inputSlots, ItemStack[] outStacks, TransitionableProperties perishProps)
   at Vintagestory.GameContent.BlockPie.OnBaked(ItemStack oldStack, ItemStack newStack)
   at Vintagestory.GameContent.BlockEntityOven.IncrementallyBake(ItemStack stack, Single dt, Int32 slot)
   at Vintagestory.GameContent.BlockEntityOven.HeatInput(Single dt)
   at Vintagestory.GameContent.BlockEntityOven.OnBurnTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by astynax777** [comment]
I'm attempting to get the server back up.  I'd like to either remove the pie or the clay oven so we can continue our world.  How can I do this?  I have programming/database experience if necessary.  I can also provide the save file.

**Comment by copygirl** [comment]
Hoping it doesn't cause other issues, you could potentially remove the block definition for the oven in the assets, so all ovens in loaded chunks will be removed, then re-add it again.

It would indeed be nice to have an external took for editing VS worlds.

**Comment by astynax777** [comment]
I tried removing the oven folder and two json files in assets and joined the world but it still tries to tick the oven and gives me the error.  I tried writing a mod to remove a block at the location, but it doesn't remove the block if the chunk isn't loaded and it won't execute if the chunk is loaded due to the error spam.

```
private void BreakBlockCommand(IServerPlayer player, int groupId, CmdArgs args)
{
    _api.Server.LogVerboseDebug("Executing break block command");
    if(args.Length == 3)
    {
        var x = args.PopInt();
        var y = args.PopInt();
        var z = args.PopInt();
        _api.Server.LogVerboseDebug($"Before Convert: x {x} y {y} z {z}");
        if (x.HasValue && y.HasValue && z.HasValue)
        {
            var pos = ConvertLocalToWorld(x.Value, y.Value, z.Value);
            _api.Server.LogVerboseDebug($"After Convert: x {pos.X} y {pos.Y} z {pos.Z}");

            _api.World.BlockAccessor.BreakBlock(pos, _players.First());
        }
    }
}

private BlockPos ConvertLocalToWorld(int x , int y, int z)
{
    var worldWidth = _api.WorldManager.MapSizeX;
    var worldHeight = _api.WorldManager.MapSizeZ;
    return new BlockPos(worldWidth / 2 + x, y, worldHeight / 2 + z);
}
```

**Comment by copygirl** [comment]
I suppose it's possible that the block entity continues existing even without its associated block and that definitely is a huge bummer. (If the block type was indeed properly removed.) Just to make sure: You did remove said assets from the server folder? You do seem pretty competent so I think you know your way around - just in case.

You might be able to remove the mapping (maybe using reflection or Harmony if a public API method is not available) or possibly even override the mapping by providing your own dummy block entity with no functionality that has the same name.

**Comment by astynax777** [comment]
We took a risk and loaded the save in v1.14, removed the block (since it's new to v1.15), and loaded it back into v1.15.  There were a few invisible blocks that we had to replace after the downgrade/upgrade and had to redo the molds in the mold racks and it was good to go.

**Comment by tyronx** [comment]
For future issues like these: Disable the pie block type, restart server, remove offending block, enable pie block, restart server

**Comment by tyronx** [comment]
This should be fixed in pre.4

**Comment by astynax777** [comment]
> For future issues like these: Disable the pie block type, restart server, remove offending block, enable pie block, restart server
> 
> That should do it

Yeah, I didn't think of that but I should have!  Is the process of disabling the block simply removing the blocktype and shape JSONs and textures? (I'm guessing we don't even need to remove the textures).

**Comment by copygirl** [comment]
@astynax777 Oh, derp! The stacktrace does mention the issue being in `BlockPie`. (At least, that's the last part of the code it executed.) I was thinking it was related to the oven itself updating and thus removing that would help.
